pilot/pkg/serviceregistry/kube/controller/pod.go

The Pod event log is at Info causing lot of these log lines in medium sized clusters. This PR changes it to debug

change pod event log level to debug

---

pkg/test/framework/components/istio/operator.go
pkg/test/framework/components/namespace/kube.go
pkg/test/framework/components/policybackend/kube.go
pkg/test/kube/accessor.go
pkg/test/kube/dump.go

1. DRY up logic to fetch pods and dump logs
2. ~~Move the `deployment.DumpX` functions to `namespace`. As they were, they operated at a namespace scope, having them in `deployment` (with no usages in that package) was confusing.~~ namespace isn't a great place either, lots of interdependency so it causes import cycles.

test framework: centralize pod dump and include envoy configs

---

prow/lib.sh

Without this, the pod never starts. The test seems to pass though, so
not sure what exactly this is needed for. This matches the instructions
on https://metallb.universe.tf/installation/ though. If we don't want
it, we should probably remove the deployment that is depending on this

Add memberlist secret for metallb

---

pilot/pkg/bootstrap/server.go
pilot/pkg/bootstrap/server_test.go

Fixes https://github.com/istio/istio/issues/23638. The debounce interval in CI seems to be not sufficient - it is failing with `key cert mismatch`. Increasing it in tests for now - If the flakyness still persists , I will move FakeWatcher which needs more changes.

fix test istiod cert reload flake

---

pilot/pkg/bootstrap/server.go
pilot/pkg/bootstrap/servicecontroller.go
pilot/pkg/proxy/envoy/v2/bench_test.go
pilot/pkg/proxy/envoy/xds/xds.go
pilot/pkg/serviceregistry/serviceentry/conversion.go
pilot/pkg/serviceregistry/serviceentry/conversion_test.go
pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go

external is confusing, serviceentry is more explicit.

rename package external to serviceentry

---

galley/pkg/config/analysis/analyzers/util/constants.go
galley/pkg/config/analysis/local/analyze.go
galley/pkg/server/settings/args.go
galley/pkg/server/settings/args_test.go
istioctl/cmd/add-to-mesh.go
istioctl/cmd/describe.go
istioctl/pkg/convert/ingress.go
pilot/cmd/pilot-agent/main.go
pilot/cmd/pilot-discovery/main.go
pilot/pkg/bootstrap/server.go
pilot/pkg/bootstrap/server_test.go
pilot/pkg/config/kube/gateway/conversion.go
pilot/pkg/model/context.go
pilot/pkg/security/trustdomain/bundle.go
pkg/config/constants/constants.go
pkg/dns/dns.go
pkg/spiffe/spiffe.go
pkg/test/framework/components/echo/kube/instance.go
pkg/test/framework/components/environment/native/native.go

This was broken by https://github.com/istio/istio/pull/23173
Restored the setting of the domain and added a test.
Also declaring a common constant for the default domain.

Fix broken cluster-local domain override

---

pilot/pkg/bootstrap/servicecontroller.go
pilot/pkg/features/pilot.go

Before we optimize this, we should disable it by default.
https://github.com/istio/istio/blob/283ac68909b471504589625238e6930362840013/pilot/pkg/serviceregistry/external/servicediscovery.go#L509
As the quantity of pods/endpoints can be huge and so this can be very costly.

Add a feature flag for se selecting pods

---

pilot/pkg/model/context.go
pilot/pkg/model/push_context.go
pilot/pkg/model/push_context_test.go

Any Envoy trying to connect to a discovery server will either:
- have an istiod instance in the same cluster
- have an istiod-remote service that forwards traffic to the primary cluster's ingressgateway
In either case, traffic from the proxy to the discovery server should be cluster-local. 
This fixes https://github.com/istio/istio/issues/23591

set discoveryAddress to be cluster-local by default

---

pilot/pkg/bootstrap/istio_ca.go
pilot/pkg/bootstrap/server.go
pilot/pkg/features/pilot.go

As noted as one of the TODOs in #23492 , this PR
- Moves `initDNSCerts` out of `initSecureGrpcListener` and creates them before we run init of any services
- Refactored parts of code in `NewServer` to separate functions so that it becomes more manageable.

server: move init certs out of secure gRPC listener

---

manifests/charts/istio-telemetry/kiali/Chart.yaml
manifests/charts/istio-telemetry/kiali/values.yaml
manifests/profiles/default.yaml
operator/cmd/mesh/manifest-generate_test.go
operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-telemetry/kiali/values.yaml
operator/cmd/mesh/testdata/manifest-generate/data-snapshot/profiles/default.yaml
operator/cmd/mesh/testdata/manifest-generate/output/helm_values_enablement.golden.yaml
operator/cmd/mesh/testdata/profile-dump/output/all_off.yaml

Manual cherry-pick because this auto-cherry-pick failed: https://github.com/istio/istio/pull/23676
(cherry picked from commit ff77aa24363513406773e2cc7c7261931fad7faa)
Signed-off-by: John Mazzitelli <mazz@redhat.com>

[kiali] move to v1.18 to address compatibility fixes for istio 1.6

---

pilot/cmd/pilot-agent/main.go
pilot/pkg/bootstrap/istio_ca.go
pilot/pkg/bootstrap/server.go
pilot/pkg/features/pilot.go
pkg/jwt/jwt.go
security/pkg/k8s/tokenreview/k8sauthn.go
security/pkg/server/ca/authenticate/kube_jwt_test.go
security/pkg/server/ca/server_test.go

Cosmetic change. As per go conventions, it is redundant to have the prefix of a constant the same as that of the package name. The context of `jwt` is already implied by referring to the `jwt` package.
[ ] Docs
[X] Networking
[] Policies and Telemetry
[X] Security

rename JWT policy constants as per go conventions

---

security/pkg/pki/util/keycertbundle.go
security/pkg/pki/util/keycertbundle_test.go
security/pkg/server/ca/monitoring.go

These are highly timing dependant, leading to frequent flakes. This
changes the tests to be completely deterministic and not rely on
time.Now() while still maintaining the same coverage as previously.
Fixes https://github.com/istio/istio/issues/23616

Fix flaky cert expiry tests

---

pkg/test/framework/features/features.gen.go
pkg/test/framework/features/features.yaml
pkg/test/framework/tools/featuresgen/cmd/root.go
pkg/test/framework/tools/featuresgen/cmd/root_test.go
pkg/test/framework/tools/featuresgen/main.go
tests/integration/pilot/analysis/analysis_test.go

Feature-based testing will require labels for tests. To ensure labels are consistent, spelled correctly, and are organized, a YAML file is used to generate the labels. This PR contains a generator that generates string constants from a YAML file for these labels.

add labels for feature-based testing

---

galley/pkg/config/analysis/analyzers/analyzers_test.go
galley/pkg/config/analysis/analyzers/injection/injection.go
galley/pkg/config/analysis/msg/messages.gen.go
galley/pkg/config/analysis/msg/messages.yaml

Resolves https://github.com/istio/istio/issues/23319
Supercedes https://github.com/istio/istio/pull/23528
This removes inventorying control planes, which won't work if the control plane is running on another cluster (or tenant.)
This preserves the warning about having both old and new injector labels.

Neither validate nor suggest alternate revision injection labels

---

istioctl/cmd/proxyconfig.go

Tested with `cat ./pkg/test/framework/components/echo/common/testdata/config_dump.json | istioctl proxy-config bootstrap --file -`

Support read from stdin for proxy config

---

istioctl/cmd/sidecar-bootstrap.go

Add more experimental markings to the sidecar-bootstrap command, to signify it may still need to be changed after rounds of reviews/experimenting

mark sidecar-bootstrap as experimental

---

istio.deps

Include fix for https://github.com/istio/proxy/pull/2850. This is a security fix.

[release-1.6] Update proxy sha

---

security/pkg/nodeagent/test/testdata/bootstrap.yaml

Add missing config for inbound_listener_tls to enable the mutual tls which remains the same as the outbound_cluster_tls
Detailed infrastructure you can find here: 
https://github.com/istio/istio/tree/master/security/pkg/nodeagent/test

add missing config for inbound_listener_tls for sds server

---

go.mod
go.sum
istio.deps
prow/release-commit.sh

The same as https://github.com/istio/istio/pull/23830, but since make gen was failing I'll over ownership. I will test this on OpenShift 4.3.5 when this gets merged.
Run `UPDATE_BRANCH=release-1.6 ./bin/update_deps.sh; make gen`

[release-1.6] Update cni/sha and other dependencies

---

pilot/pkg/model/context.go
pilot/pkg/model/service.go
pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
pilot/pkg/proxy/envoy/v2/ads.go
pilot/pkg/proxy/envoy/v2/eds.go
pilot/pkg/serviceregistry/aggregate/controller.go
tests/integration/mixer/outboundtrafficpolicy/allowany/egressproxy/traffic_allow_any_egressproxy_test.go
tests/integration/pilot/envoyfilter/main_test.go
tests/integration/pilot/sidecar_api_test.go
tests/integration/pilot/sidecarscope/main_test.go

```go
// ClusterID specifies the cluster where the proxy resides.	
// TODO: clarify if this is needed in the new 'network' model, likely needs to	
// be renamed to 'network'	
ClusterID string
```
We rely on complex logic to get the clusterID for a proxy rather than using what's provided directly be metadata. The logic depends on the registry/Controller having it's network setup properly if using meshNetwork config (see #https://github.com/istio/istio/pull/23825)
Overall this simplifies getting the cluster ID for a proxy.

use clusterID from metadata

---

pkg/test/framework/components/environment/kube/flags.go
pkg/test/framework/components/environment/kube/kube.go
pkg/test/framework/components/environment/kube/settings.go
pkg/test/framework/suite.go

This is a follow-on to the work in #23759, which does the following:
1. Allows customization of the kube client transport
2. Uses kube client for all Accessor operations (rather than kubectl)
This PR is independent, however, and can be submitted prior to #23759.

[Test Framework] Allow customizing kube Accessor creation

---

pilot/pkg/model/context.go
pilot/pkg/model/push_context.go
pilot/pkg/model/push_context_test.go

Cherry picking #23625 into release 1.6 to fix shared control plane multicluster

set discoveryAddress to be cluster-local by default (#23625)

---

pilot/pkg/networking/core/v1alpha3/cluster_builder.go

Signed-off-by: Yuchen Dai <silentdai@gmail.com>
Thanks @howardjohn 
Fix #23821

pilot: cluster use select all endpoints if label is empty

---

istioctl/cmd/describe.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
pilot/pkg/proxy/envoy/v2/ep_filters.go

A few places were using a hardcoded string value instead of the metadata variable name

use istio metadata variable rather than string

---

pkg/test/framework/resource/context.go
pkg/test/framework/scope.go
pkg/test/framework/suite_test.go
pkg/test/framework/suitecontext.go
pkg/test/framework/testcontext.go

In cases where another part of the testing framework or a test itself needs a reference a resource, this can be useful to avoid plumbing a reference to the resource through every constructor/function. As the PR currently sits, it's only useful when only one of the given type of resource is expected in the context.

test framework: allow fetching resources from context

---

istioctl/pkg/install/pre-check.go

Fixes #23000
Signed-off-by: zillani shaik <shaikzillani@gmail.com>

resolve nil pointer deference if kubectl context doesn't exist, fixes #2300

---

pkg/istio-agent/sds-agent.go
security/pkg/nodeagent/cache/secretcache.go
security/pkg/nodeagent/sds/sdsservice_test.go
security/pkg/nodeagent/sds/server.go

Followup of https://github.com/istio/istio/pull/23647. For file mounted certs, SDS service needs to skip token

sds: skip reading jwt token for file mounted certs

---

security/pkg/nodeagent/test/csr_failure/csr_test.go
security/pkg/nodeagent/test/empty_certchain/empty_cert_test.go

Enable the csr_failure and emprt certchain test for node agent 
Issue Id: https://github.com/istio/istio/issues/22729

enable skip test for csr and empty cert test

---

security/pkg/nodeagent/test/cert_rotation/rotation_test.go

Reenable the rotation cert test by checking the number of cert update during the proxy running duration
Issue Id: https://github.com/istio/istio/issues/22729

enable the rotation cert test by checking the number of cert update

---

pilot/pkg/serviceregistry/kube/controller/controller.go

Found in the slack convo. This is useful to debug.
[ ] Docs
[ ] Security

add proxyid to log lines while getting service instances

---

manifests/charts/gateways/istio-egress/templates/serviceaccount.yaml
manifests/charts/gateways/istio-ingress/templates/role.yaml
manifests/charts/gateways/istio-ingress/templates/rolebindings.yaml
manifests/charts/gateways/istio-ingress/templates/serviceaccount.yaml
operator/cmd/mesh/manifest-generate_test.go

As described in #23303, this backports #23570 the custom resource names in gateway setup

[release-1.6] Backport PR #23570 to release-1.6

---

istioctl/pkg/validate/validate.go
istioctl/pkg/validate/validate_test.go

Resolves https://github.com/istio/istio/issues/24064 .
cc @jasonwzm the change follows your code in _pkg/webhooks/validation/server/server.go_.  When you introduce multi-version, make sure it is available to istioctl.

Don't skip networking.istio.io/v1beta1 for "istioctl validate -f"

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
pilot/pkg/networking/util/util.go

Add TCP MX Alpn in UpstreamTlsContext for clusters that specify http2_protocol_options too
Ref: https://github.com/istio/istio/issues/23907
Signed-off-by: gargnupur <gargnupur@google.com>

Add TCP MX Alpn in UpstreamTlsContext for clusters that specify http2_protocol_options too

---

security/pkg/nodeagent/cache/secretcache.go
security/pkg/nodeagent/cache/secretcache_test.go
security/pkg/nodeagent/sds/sdsservice.go
security/pkg/nodeagent/sds/sdsservice_test.go
security/pkg/nodeagent/sds/server.go

Continuing on #23647 , this PR skips waiting for ingress gateway secret for file mounted certs

sds: skip waiting for ingress gateway secret for file mounted certs

---

pilot/pkg/bootstrap/istio_ca.go
pilot/pkg/bootstrap/namespacecontroller.go
pilot/pkg/bootstrap/namespacecontroller_test.go

Backport of
https://github.com/istio/istio/commit/77304211dc0c75820ab9cd2f2fe03e5d5211edca.
I have confirmed this fixes https://github.com/istio/istio/issues/22463,
as I can reliably reproduce and have witness all of the logs in the
issue lose the election at some point

[1.5] Fix namespace configmap controller losing election lock

---

pilot/pkg/model/gateway.go
pilot/pkg/model/gateway_test.go

Currently if both of these exist, only one is used. However, we generate
literally the same config for http 1 and 2 - so no reason not to merge.
Fixes https://github.com/istio/istio/issues/24061
Fixes https://github.com/istio/istio/issues/19690

Fix HTTP2/HTTP conflict at Gateway

---

pilot/pkg/bootstrap/certcontroller.go

This is not correct, we may have DNS certificates for hosts like
istiod.com or localhost. Instead, we should create these in the provided
`namespace` field. The hostname part is just for the name of the CSR, it
could be anything really, so I kept it consistent.

Don't use discoveryAddress for k8s CA

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
pilot/pkg/networking/util/util.go

[Release-1.5] Add TCP MX Alpn in UpstreamTlsContext for clusters that specify http2_protocol_options
Cherry-pick : https://github.com/istio/istio/pull/23929

[Release-1.5] Add TCP MX Alpn in UpstreamTlsContext for clusters that specify http2_protocol_options

---

istioctl/pkg/install/pre-check.go
istioctl/pkg/install/pre-check_test.go

To fix https://github.com/istio/istio/issues/24132
More Info: https://github.com/istio/istio/issues/23184
with **k8 1.15** or greater.
```go
$ istioctl experimental precheck
Checking the cluster to make sure it is ready for Istio installation...
#2. Kubernetes-version
-----------------------
Istio is compatible with Kubernetes: v1.15.0.
-----------------------
Install Pre-Check passed! The cluster is ready for Istio installation.
```
with **k8 1.14** throws invalid version error
```go
$ istioctl experimental precheck
Checking the cluster to make sure it is ready for Istio installation...
#2. Kubernetes-version
-----------------------
The Kubernetes API version: v1.14.0 is lower than the minimum version: 1.15
Error: 1 error occurred:
* The Kubernetes API version: v1.14.0 is lower than the …
```

Update min k8 version required for Istio

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
pilot/pkg/networking/util/util.go

[Release-1.6] Add TCP MX Alpn in UpstreamTlsContext for clusters that specify http2_protocol_options too  (#23929)
* Add TCP MX Alpn in UpstreamTlsContext for clusters that specify http2_protocol_options too
Ref: https://github.com/istio/istio/issues/23907
Signed-off-by: gargnupur <gargnupur@google.com>
Updated based on feedback
Signed-off-by: gargnupur <gargnupur@google.com>
Updated based on feedback
Signed-off-by: gargnupur <gargnupur@google.com>
* fix lint error after rebase
Signed-off-by: gargnupur <gargnupur@google.com>

[Release-1.6] Add TCP MX Alpn in UpstreamTlsContext for clusters that specify http2_protocol_options too 

---

istioctl/pkg/install/pre-check.go
istioctl/pkg/install/pre-check_test.go

Related https://github.com/istio/istio/pull/24134
The minimum supported k8 version for Istio 1.7 is 1.16-1.18 (3 versions). Ref: https://github.com/istio/istio/pull/24134#issuecomment-634690848

Update min k8 supported version for istio 1.7

---

security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go

This prints the error returned by the server to the log instead of printing an empty struct.
[ ] Docs
[ ] Networking
[X] Security

Improve debugging of failed STS requests.

---

pkg/test/framework/components/environment/kube/settings.go

Follow up to https://github.com/istio/istio/pull/23732, added new flag `NetworkTopology` to String method
[ ] Docs
[ ] Networking
[ ] Security

add NetworkTopology to String method

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
tests/integration/pilot/cni/cni_test.go
tests/integration/security/mtls_first_party_jwt/strict_test.go
tests/integration/security/mtlsk8sca/strict_test.go
tests/integration/security/reachability_test.go
tests/integration/security/testdata/beta-mtls-off-headless.yaml
tests/integration/security/util/reachability/context.go

this is a manual cherry-pick from #21987
fixes: #23844

[release-1.6] Disable TransportSocket for headless service when mtls is auto detected 

---

Makefile.core.mk

Old base image was showing vulnerabilities:
```
CVE-2020-3810	apt	APT could be made to crash if it opened a specially crafted file.	Upgrade apt to >= 1.6.12ubuntu0.1	
CVE-2019-20795	iproute2	IPRoute could be made to execute arbitrary code if it received a speciallycrafted input.	Upgrade iproute2 to >= 4.15.0-2ubuntu1.1	
CVE-2019-1547	libssl1.1	Several security issues were fixed in OpenSSL.	Upgrade libssl1.1 to >= 1.1.1-1ubuntu2.1~18.04.6	
CVE-2019-1549	libssl1.1	Several security issues were fixed in OpenSSL.	Upgrade libssl1.1 to >= 1.1.1-1ubuntu2.1~18.04.6	
CVE-2019-1551	libssl1.1	Several security issues were fixed in OpenSSL.	Upgrade libssl1.1 to >= 1.1.1-1ubuntu2.1~18.04.6	
CVE-2019-1563	libssl1.1	Several security issues were fixed in OpenSSL.	Upgrade libssl1.1 to >= …
```

[release-1.6] Update base image

---

install/tools/certs/Makefile

Previously this results in ns/my-namespace//sa which is not valid
[ ] Docs
[ ] Networking
[ ] Security

Fix invalid SPIFFE cert generation

---

pilot/pkg/model/fake_store.go
pilot/pkg/networking/core/v1alpha3/filters.go
pilot/pkg/networking/core/v1alpha3/listener.go

This has a couple small changes:
* Fix to the FakeStore to allow benchmark to run. We don't (yet!) run
this in CI
* Premarshall the ALPN filter to avoid creating it 100s of times
* If we have a conflict, short circuit to avoid construction a full
filter chain and throwing it away
* Stop calling listener.Validate() (see
https://github.com/istio/istio/issues/22648 for more info)
```
name                                 old time/op    new time/op    delta
ListenerGeneration/empty-6             4.09ms ± 3%    2.92ms ± 0%  -28.70%  (p=0.008 n=5+5)
ListenerGeneration/telemetry-6         5.00ms ± 4%    3.88ms ± 2%  -22.39%  (p=0.008 n=5+5)
ListenerGeneration/virtualservice-6    4.05ms ± 2%    2.92ms ± 2%  -27.88%  (p=0.008 n=5+5)
name                                 old alloc/op   new alloc/op …
```

Optimize listener generation

---

pkg/test/framework/components/echo/docker/sidecar.go
pkg/test/framework/components/echo/echo.go
pkg/test/framework/components/echo/kube/sidecar.go
tests/integration/multicluster/multimaster/main_test.go
tests/integration/multicluster/remote/main_test.go
tests/integration/multicluster/telemetry.go

Adds initial telemetry tests to the multicluster scenarios.
This PR is the starting point for validation of multicluster telemetry. At this point in time, it simply attempts to validate that `source_cluster` and `destination_cluster` labels are available in the telemetry. It does not attempt to validate that they have any specific value or similar. These tests will hopefully be expanded upon in the 1.7 release cycle.

test(multicluster): add initial telemetry validation test

---

istioctl/cmd/analyze.go

This PR should prevent the churn in the docs reference like seen here:
```
<tr>
<td><code>--output &lt;string&gt;</code></td>
<td><code>-o</code></td>
- <td>Output format: one of [json yaml log]  (default `log`)</td>
+ <td>Output format: one of [log json yaml]  (default `log`)</td>
</tr>
```
[ ] Docs
[ ] Networking
[ ] Security

Sort output formats - unsorted causes churn in html and istio.io PRs

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
tests/integration/pilot/cni/cni_test.go
tests/integration/security/mtls_first_party_jwt/strict_test.go
tests/integration/security/mtlsk8sca/strict_test.go
tests/integration/security/reachability_test.go
tests/integration/security/testdata/beta-mtls-off-headless.yaml
tests/integration/security/util/reachability/context.go

Reverts istio/istio#24168
See https://github.com/istio/istio/issues/24028

Revert "[release-1.6] Disable TransportSocket for headless service when mtls is auto detected "

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
tests/integration/pilot/cni/cni_test.go
tests/integration/security/mtls_first_party_jwt/strict_test.go
tests/integration/security/mtlsk8sca/strict_test.go
tests/integration/security/reachability_test.go
tests/integration/security/testdata/beta-mtls-off-headless.yaml
tests/integration/security/util/reachability/context.go

Reverts istio/istio#21987
See https://github.com/istio/istio/issues/24028

Revert "Disable TransportSocket for headless service when mtls is auto detected"

---

tests/testdata/config/rule-default-route-cors-policy.yaml

**Description**
In this PR, we change the block of CORS Policy definition on testdata files, from `allowOrigin` to `allowOrigins` so tests to run on supported resources.
Starting from Istio 1.6, the block with deprecated `allowOrigin` is not respected thus not working.
**Resolves**
- https://github.com/istio/istio/issues/24145
- https://github.com/istio/istio/issues/23757
**Related to**
- https://github.com/istio/api/pull/1453
**Checklist**

CORS Policy TestData: Change to allowOrigins block

---

pilot/pkg/proxy/envoy/v2/ads.go
pilot/pkg/proxy/envoy/v2/eds.go

Couple of function calls in eds path are called before they are actually needed This PR fixes them
[ ] Docs
[ ] Security

eds: only call functions when needed

---

CODEOWNERS

Add .gitignore, .gitattributes, Makefile.core.mk to the
list of files that are managed by the test and release WG.
Cheers,
-steve
[ ] Docs
[ ] Networking
[ ] Security

Modify CODEOWNERS with micro review optimizations

---

.gitignore
Makefile.core.mk

As `install/kubernetes` is removed in 1.6, there is no need to clean and ignore it.

Clean up Make for deprecated files to remove

---

pilot/pkg/proxy/envoy/v2/adapter.go
pilot/pkg/proxy/envoy/v2/ads.go
pilot/pkg/proxy/envoy/v2/ads_test.go
pilot/pkg/proxy/envoy/v2/cds.go
pilot/pkg/proxy/envoy/v2/discovery.go
pilot/pkg/proxy/envoy/v2/discovery_test.go
pilot/pkg/proxy/envoy/v2/eds.go
pilot/pkg/proxy/envoy/v2/gen2.go
pilot/pkg/proxy/envoy/v2/init_test.go
pilot/pkg/proxy/envoy/v2/internalgen.go
pilot/pkg/proxy/envoy/v2/lds.go
pilot/pkg/proxy/envoy/v2/rds.go

This allows support for both versions of the transport protocols, while
keeping internal implementation limited to just v3. This involves:
* Bumping internal implemention from v2 -> v3
* Adding a new "adapter" which upconverts v2 to v3
* Add test for v3 clients
A future PR will change the defaults to actually start using V3.
For https://github.com/istio/istio/issues/19885

Support v2 and v3 XDS transport protocols

---

manifests/charts/base/templates/endpoints.yaml
manifests/charts/base/templates/services.yaml
operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/templates/endpoints.yaml
operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/templates/services.yaml

Fixes: #24269 manual cherry pick of #24219
[ ] Docs
[x ] Installation
[ ] Networking
[ ] Security

[release-1.6] cherry pick use external name when remote pilot addr is hostname #24219

---

pkg/test/framework/components/echo/kube/builder.go
pkg/test/framework/components/echo/kube/instance.go
pkg/test/framework/components/echo/kube/workload.go
pkg/test/framework/components/istio/operator.go
pkg/test/kube/accessor.go

Broken out of https://github.com/istio/istio/pull/24166/files
Use pods for the readiness check rather than Endpoints. Its largely the
same thing if we make the assumption Kubernetes will create an endpoint
immediately or "soon enough" after marking a pod ready. This supports
pods without an associated Service.
Also cleanup leader election configmaps. This makes it so that new test
suites do not have a large delay at startup trying to become the leader
from a previous test.
[ ] Docs
[ ] Networking
[ ] Security

Fix cleanup and change readiness check for tests

---

manifests/gateways/istio-egress/templates/deployment.yaml
manifests/gateways/istio-ingress/templates/deployment.yaml
operator/pkg/vfs/assets.gen.go

[ ] Docs
[ ] Networking
[ ] Security
This is backport of #24242 to release-1.5 for fixing incorrect service account name used in custom IngressGateway Deployment.

Backport #24242 to release-1.5 - Fix incorrect ServiceAccount used in custom IngressGateway Deployment 

---

pilot/pkg/proxy/envoy/v2/ep_filters.go
pilot/pkg/proxy/envoy/v2/ep_filters_test.go
pilot/pkg/serviceregistry/kube/conversion.go

In AWS, load balancer services get hostnames instead of IPs.
Resolving these hostnames to IPs in Pilot is incorrect as these resolutions
are transient and could lead to incorrect routing. We are better off
skipping these gateways for split horizon until we figure out a way to
ship aggregate cluster that contains the dns hostnames.
[ ] Docs
[ ] Networking
[ ] Security

Skip using gateways with hostnames in split horizon

---

pkg/adsc/adsc.go

Regression caused by #23833
Spec: `It is also not safe to call CloseSend concurrently with SendMsg.`
Example: https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/24314/unit-tests_istio/14042

Fix race condition in adsc

---

tests/integration/mixer/policy/white_black_listing_test.go

unskipped by https://github.com/istio/istio/pull/24277, has failed 100% since then

Skip whitelist test

---

istioctl/pkg/multicluster/remote_secret.go

`create-remote-secret` command currently uses os.Exit() for one of the failure scenarios.  During integration tests, the error gets lost unless it is returned.  The integration tests will fail with no explanation if os.Exit is used
[ ] Docs
[ ] Networking
[ ] Security

create-remote-secret silently fails for integration tests

---

pkg/bootstrap/option/convert_test.go

[X ] Security
This PR adds tests to the TLS context converter. The three modes for TLS here are simple, mutual, and istio mutual, and this PR adds tests for all of them.

TLS Context Tests

---

pilot/pkg/proxy/envoy/v2/ads.go

Currently everything is declared as unauthenticate. This is because CheckSecurityLevel looks like RequestContext which isn't present. The auth info is only present in the peer info. I tried to rewrite the check security level for peer info but its not possible since its all grpc-internal. So I feel like the best option is to remove it entirely. I couldn't find any docs suggesting this was a bad idea.
[ ] Docs
[ ] Networking
[ ] Security

Fix XDS client authentication

---

Makefile.core.mk

Example output:
```
$ make help
build                Builds all go binaries.
clean                Cleans all the intermediate files and folders previously generated.
format               Auto formats all code. This should be run before sending a PR.
gen                  Update all generated code.
help                 Show this help
lint                 Runs all linters.
push                 Build and push docker images to registry defined by $HUB and $TAG
racetest             Runs all unit tests with race detection enabled
```
This will need to go to common-files. Submitting here first to let people try it out and get initial feedback

Add help message to makefile

---

pilot/pkg/model/context.go
pilot/pkg/networking/core/v1alpha3/cluster_builder.go
pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
pilot/pkg/networking/core/v1alpha3/listener.go
pilot/pkg/proxy/envoy/v2/ads.go
pilot/pkg/proxy/envoy/v2/cds.go
pilot/pkg/proxy/envoy/v2/debug.go
pilot/pkg/proxy/envoy/v2/eds.go
pilot/pkg/proxy/envoy/v2/lds.go
pilot/pkg/proxy/envoy/v2/rds.go
pkg/bootstrap/testdata/all_golden.json
pkg/bootstrap/testdata/auth_golden.json
pkg/bootstrap/testdata/authsds_golden.json
pkg/bootstrap/testdata/default_golden.json
pkg/bootstrap/testdata/running_golden.json
pkg/bootstrap/testdata/runningsds_golden.json
pkg/bootstrap/testdata/stats_inclusion_golden.json
pkg/bootstrap/testdata/tracing_datadog_golden.json
pkg/bootstrap/testdata/tracing_lightstep_golden.json
pkg/bootstrap/testdata/tracing_stackdriver_golden.json
pkg/bootstrap/testdata/tracing_tls_golden.json
pkg/bootstrap/testdata/tracing_zipkin_golden.json
tools/packaging/common/envoy_bootstrap_v2.json

For https://github.com/istio/istio/issues/19885
Pilot now supports either v2 or v3 requests. This just switches the default to requesting v3. Additionally, it changes the ConfigSource types to reference the same version requested. So cds vX -> eds vX. As part of this change I had to move the requestedTypes to the node rather than the connection.

Switch to actually request/use XDS v3

---

tools/certs/Makefile

- enhance fetch-root-ca  to support extract root ca from both `cacerts `and `istio-ca-secret`
- do not rely on PID to set CA's serial number

enhance fetch-root-ca and do not rely PID as serial number

---

pilot/pkg/model/sidecar.go
pilot/pkg/model/sidecar_test.go

Avoid pilot crashes, as described in the issue #24453
[ ] Docs
[x ] Networking
[ ] Security

Fix: Pilot crash when set illegal host in sidecar resource

---

pilot/cmd/pilot-agent/status/server.go
pkg/kube/inject/app_probe.go
pkg/kube/inject/inject_test.go
pkg/kube/inject/testdata/inject/app_probe/startup_live.yaml
pkg/kube/inject/testdata/inject/app_probe/startup_live.yaml.injected
pkg/kube/inject/testdata/inject/app_probe/startup_only.yaml
pkg/kube/inject/testdata/inject/app_probe/startup_only.yaml.injected
pkg/kube/inject/testdata/inject/app_probe/startup_ready_live.yaml
pkg/kube/inject/testdata/inject/app_probe/startup_ready_live.yaml.injected

Currently startup probes have no support with rewriteAppHTTPProbe. Adding it for [24203](https://github.com/istio/istio/issues/24203)
[ ] Docs
[ ] Networking
[ ] Security

Adding support for startup probe.

---

pilot/pkg/proxy/envoy/v2/discovery.go
pilot/pkg/proxy/envoy/v2/eds.go

Currently `UpdateServiceShards` is being executed for Service Entries also which I think is not needed unless I am missing some thing. This PR fixes it ~~and also moves the logic to identify registries to `DiscoveryServer` initialization so that it is done only once~~. Looks like some tests add registry dynamically after server is initialized.
[ ] Docs
[ ] Security

eds: do not update service shards for service entries

---

pilot/pkg/proxy/envoy/v2/ads_test.go
pilot/pkg/proxy/envoy/v2/eds_sh_test.go
pilot/pkg/proxy/envoy/v2/init_test.go

Moves split horizon test to v3
[ ] Docs
[ ] Security

eds: move split horizon test to v3

---

pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/controller_test.go

Removes `reflect.DeepEqual` in frequently used endpoint comparison
[ ] Docs
[ ] Security

remove reflect deep equal in endpoint comparison

---

manifests/charts/global.yaml
manifests/charts/istio-telemetry/prometheus/templates/deployment.yaml
manifests/profiles/default.yaml

This is a cherry-pick of https://github.com/istio/istio/pull/24415
[ ] Docs
[ ] Networking
[ ] Security

[release-1.6] Apply proxyMetadata to Prometheus sidecar

---

pilot/pkg/proxy/envoy/v2/cds.go
pilot/pkg/proxy/envoy/v2/eds.go
pilot/pkg/proxy/envoy/v2/gen2.go
pilot/pkg/proxy/envoy/v2/lds.go
pilot/pkg/proxy/envoy/v2/monitoring.go
pilot/pkg/proxy/envoy/v2/rds.go

We already filter these from metrics, should filter from logs as well.
This means the connection is disconnecting without errror; we already
log these at info levels so we aren't even losing any log info here just
reducing spam
[ ] Docs
[ ] Networking
[ ] Security

Remove extraneous Send failure logs

---

pilot/pkg/security/model/authentication.go
pkg/kube/util.go

Use local filepath for consistency with sidecar SDS, and allow
authentication
[ ] Docs
[ ] Networking
[ ] Security

Allow running Ingress locally

---

istioctl/cmd/proxyconfig.go
istioctl/pkg/writer/envoy/configdump/listener.go

Resolves https://github.com/istio/istio/issues/24353
Each line is still wider than I want.
This is based on @howardjohn 's https://github.com/howardjohn/istio/blob/istioctl/listener-filterchains/istioctl/pkg/writer/envoy/configdump/listener.go .  Minor improvements:
- works with both v2 and v3 listeners
- output sorted by port and address
- MATCH column slightly more terse
- Default is `--verbose==true`
The output, on my system, is 
```
ADDRESS        PORT  MATCH                                                           DESTINATION
172.21.0.10    53    ALL                                                             outbound|53||kube-dns.kube-system.svc.cluster.local
172.21.186.46  53    ALL …
```

More detailed output and sorted output for "istioctl pc listeners"

---

pilot/pkg/proxy/envoy/v2/eds_sh_test.go
pilot/pkg/proxy/envoy/v2/lds_test.go
pilot/pkg/proxy/envoy/v2/xds_test.go
pkg/test/env/envoy.go
pkg/test/env/envoy_conf.go
pkg/test/env/http_client.go
pkg/test/env/http_server.go
pkg/test/env/ports.go
pkg/test/env/setup.go
security/pkg/nodeagent/test/cert_rotation/rotation_test.go
security/pkg/nodeagent/test/csr_failure/csr_test.go
security/pkg/nodeagent/test/empty_certchain/empty_cert_test.go
security/pkg/nodeagent/test/setup.go
security/pkg/nodeagent/test/success_sds/sds_test.go
security/pkg/nodeagent/test/testdata/bootstrap.yaml
security/pkg/stsservice/test/failure_sts_token_fetch/token_failure_test.go
security/pkg/stsservice/test/proxy_cached_sts_token/proxy_cached_token_test.go
security/pkg/stsservice/test/renew_sts_token/renew_token_test.go
security/pkg/stsservice/test/server_cached_short_lived_sts_token/short_lived_cached_token_test.go
security/pkg/stsservice/test/server_cached_sts_token/server_cached_token_test.go
security/pkg/stsservice/test/setup.go
security/pkg/stsservice/test/sts_fetch_timeout/sts_timeout_test.go
security/pkg/stsservice/test/success_sts/proxy_sts_test.go
tests/testdata/bootstrap_tmpl.json

This PR copies the testing deps for pilot and security out of the `mixer/` package and into the `pkg/test/env` package. It then updates the impacted tests to point at the new package.
This PR is part one (of many) in removing Mixer from the codebase. The impacted tests should probably be rewritten to use a more modern Istio framework for testing (and/or use case labelling), but that is beyond the scope of this PR.
NOTE: No new code is added in this PR. The `env` package is copied over from `mixer/` tests, with the mixer-specific bits cut out.
[ ] Docs
[ ] Networking
[ ] Security

refactor: move pilot/security test dep out of mixer

---

pilot/pkg/proxy/envoy/v2/ads_test.go
pilot/pkg/proxy/envoy/v2/cds_test.go
pilot/pkg/proxy/envoy/v2/debug_test.go
pilot/pkg/proxy/envoy/v2/eds_sh_test.go
pilot/pkg/proxy/envoy/v2/eds_test.go
pilot/pkg/proxy/envoy/v2/init_test.go
pilot/pkg/proxy/envoy/v2/lds_test.go
pilot/pkg/proxy/envoy/v2/rds_test.go

This is a precursor to moving tests over to v3. This PR just renames the base functions
connectADS -> connectADSv2 and connectADSV3 -> ConnectADS. Same for send and receive functions.
Once this is merged, will follow-up with moving tests to v3 gradually.
[ ] Docs
[ ] Security

xds: rename tests

---

manifests/charts/gateways/istio-egress/templates/deployment.yaml
manifests/charts/gateways/istio-ingress/templates/deployment.yaml

Fixes https://github.com/istio/istio/issues/24515
See original issue at https://github.com/istio/istio/issues/24469
Relevant parameters had to be moved into container securityContext
Manual cherry-pick of https://github.com/istio/istio/pull/24506

[release-1.6] manifests: fix PodSecurityContext for gateways

---

README.md

This PR updates the current README to match the current status of the project.
In particular, the PR:
- Removes all mentions of Mixer
- Calls out Istiod (grouping Pilot/Galley/Citadel as subcomponents)
- Alpha sorts the repository list
- Adds the community repo to the repository list
- Adds a link to the `operator/` package in istio/istio.
[ X ] Docs

docs: Update README to reflect current project realities

---

pilot/pkg/proxy/envoy/v2/ads_test.go
pilot/pkg/proxy/envoy/v2/cds_test.go
pilot/pkg/proxy/envoy/v2/debug_test.go
pilot/pkg/proxy/envoy/v2/eds_test.go
pilot/pkg/proxy/envoy/v2/init_test.go

Moves EDS tests to v3
[ ] Docs
[ ] Security

xds: move eds tests to v3

---

pilot/pkg/proxy/envoy/v2/cds_test.go
pilot/pkg/proxy/envoy/v2/init_test.go
pilot/pkg/proxy/envoy/v2/lds_test.go

Moves CDS and LDS tests to v3
[ ] Docs
[ ] Security

xds: move cds and lds tests to v3

---

pilot/cmd/pilot-discovery/main.go

According to https://grpc.io/, the name should be `gRPC`, not `grpc`.
[x] Docs
[ ] Networking
[ ] Security

the name should be gRPC

---

pkg/test/kube/accessor.go
tests/integration/telemetry/dashboard_test.go
tests/integration/telemetry/main_test.go

This adds a helper function to extract specific types from config, and
uses it in some other places already doing the same. Then we use it in
the tests in place of grafana.
[ ] Docs
[ ] Networking
[ ] Security

Use samples grafana for tests

---

pkg/test/framework/components/istio/operator.go

Currently using string manipulation to setup meshNetworks in integration tests. This changes things to use the generated structs for all manipulation until we write the iop file. 
This fragility causes yaml like [this](https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/24549/integ-multicluster-k8s-tests_istio/4360/artifacts/pilot-test-583455f754f1466a9b89/_suite_context/istio-deployment-769424605/iop.yaml) to be generated. 
If we were to try to run [pilot/meshnetwork tests](https://github.com/istio/istio/blob/master/tests/integration/pilot/meshnetwork/main_test.go) they would break with conflicts in meshNetworks. 
This makes things generally less fragile and users of the framework can be more comfortable setting values via ControlPlaneValues without the test framework …

test framework: use proto structs to manipulate iop yaml

---

pilot/pkg/networking/apigen/apigen_test.go
pilot/pkg/networking/grpcgen/grpcgen_test.go
pilot/pkg/networking/grpcgen/testdata/xds_bootstrap.json

Fixes #24681. Not sure if this is the right way to do it, my assumption is that tests `grpcgen_test.go` and `apigen_test.go` are being run on the same machine concurrently. I just bumped up the port number.
To avoid future errors like this, in our critical services, maybe we should implement some sort of interface that returns a callback to the port that is available, if the default port is not available, especially for testing. If we use it across tests, then we wouldn't have these errors anymore.

Fix Test Flake - Bump Port

---

pilot/cmd/pilot-agent/main.go
pilot/cmd/pilot-discovery/main.go

Currently, on a connection failure to CA, we log messages like
```
2020-06-08T23:52:39.466564Z     info    Subchannel Connectivity change to CONNECTING
2020-06-08T23:52:39.466642Z     info    Subchannel picks a new address "localhost:15012" to connect
2020-06-08T23:52:39.466789Z     info    pickfirstBalancer: HandleSubConnStateChange: 0xc000a3a2f0, {CONNECTING <nil>}
2020-06-08T23:52:39.466860Z     info    Channel Connectivity change to CONNECTING
2020-06-08T23:52:39.468138Z     info    grpc: addrConn.createTransport failed to connect to {localhost:15012  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:15012: connect: connection refused". Reconnecting...
2020-06-08T23:52:39.468194Z     info    Subchannel Connectivity change to TRANSIENT_FAILURE …
```

Disable spammy gRPC logs

---

tests/integration/mixer/policy/ratelimiting_test.go

Make ratelimiting test less flaky
From the logs, test fails because prometheus only reported around 290 total requests and we wait to receive full 300 requests sent. Thus, removing this hard limit to make test less flaky.
[ ] Docs
[ ] Networking
[ ] Security

Make ratelimiting test less flaky

---

pilot/pkg/serviceregistry/kube/controller/controller_test.go

This has been flaky for almost a year now... time to end it
[ ] Docs
[ ] Networking
[ ] Security

Partially skip flaky pod test

---

pkg/kube/client_config.go
pkg/test/framework/components/environment/kube/kube.go
pkg/test/framework/components/environment/kube/settings.go
pkg/test/framework/resource/environment.go
pkg/test/framework/resource/settings.go
pkg/test/framework/suite.go
pkg/test/framework/suite_test.go
pkg/test/framework/suitecontext.go

This was accidentally removed in #24149. This is currently the only mechanism available for overriding cluster accessor creation with custom transports.
[ ] Docs
[ ] Networking
[ ] Security

[Test Framework] Restore environment creation override

---

mixer/adapter/kubernetesenv/cache.go
mixer/adapter/kubernetesenv/cache_test.go

[ ] Docs
[ ] Networking
[ ] Security
It was observed that Mixer would incorrectly return source names when it did lookups by IP (generally for TCP traffic) and when there were more than 1 pods with the same IP (can be possible where pods exist for completed jobs along with another pod that's actually the source). The fix here is to sort the pods by `creationTimestamp` during lookup and return the latest pod.

Sort pods during lookup by IP

---

pkg/test/framework/suite.go
pkg/test/framework/suite_test.go

When running with BUILD_WITH_CONTAINER=1, the Istio code is stored under `/work`. The logic in the test ID generation specifically looks for paths containing `istio.io/istio`, which is not found in this case. The path stripping logic is therefore skipped entirely, resulting in a testID of the form "_work_...".
The whitelist for feature label enforcement is unfortunately coupled to the form of the test IDs. This results in whitelisted tests failing due to feature label enforcement when BUILD_WITH_CONTAINER=1.
This PR changes the logic to use regexes and includes paths for "/work" as a work-around.
[ ] Docs
[ ] Networking
[ ] Security
[ ] …

[Test Framework] Fix generated testID for BUILD_WITH_CONTAINER=1

---

tools/istio-docker.mk

This is broken on docker 19.03.2 which is what our CI uses. Its not
much, if at all, slow it seems.
[ ] Docs
[ ] Networking
[ ] Security

Stop using buildx for docker.save

---

security/pkg/nodeagent/sds/sds_stream_test.go
security/pkg/nodeagent/sds/sdsservice.go

fix issue: https://github.com/istio/istio/issues/23715
high level context:
basic network variable:
- sdsclients map : store all the current connection network with a  key (connection id + resource name)
- cache.secrets map: store all the secrets with the same key connection id as sdsclients
1. when the gateway and secret are deleted, the sdsservice will detect that and build a new connection with id (connection.local-5) trying to reconnect. The secrets and connections are stored in the cache.secrets and sdsclients seperately.
2. when the user recreated the gateway, the sdsservice detects that and close the former connection(connection.local-5, remove this connection from the sdsclients), but somewhat the secrets are not removed from the cache.secrets
3. when the secret are created, the …

Fix ingress SDS not getting secret updates and create unit tests

---

prow/integ-suite-kind.sh
prow/lib.sh

This provides a way to start the kind environment and just let it keep running without automatically shutting down. Useful for testing/debugging locally. The test target is also now optional, so it can be run with just `./prow/integ-suite-kind.sh --manual`.
[ ] Docs
[ ] Networking
[ ] Security

[Test Framework] Allow running kind setup manually

---

pilot/pkg/networking/core/v1alpha3/listener.go
pilot/pkg/networking/core/v1alpha3/listener_test.go

Currently gRPC status filter is only added for inbound connection manager. This PR adds to outbound connection manager as well
[ ] Docs
[ ] Security

listener: add grpc status filter for outbound http connection manager

---

galley/pkg/config/analysis/analyzers/analyzers_test.go
galley/pkg/config/analysis/analyzers/deprecation/deprecation.go
galley/pkg/config/analysis/analyzers/testdata/deprecation.yaml

Resolves https://github.com/istio/istio/issues/19355
As far as I can tell those are the only fields still in the API but newly hidden for 1.7.
Requesting @nrjpoddar because he wrote the commit that removed them https://github.com/istio/api/pull/1437

"istioctl analyze" new warnings for Sidecar fields are being used

---

samples/bookinfo/platform/kube/bookinfo-ingress.yaml

Bookinfo example when using Ingress was missing css and javascript because `/static` pages are not served without these rules.
[ ] Docs
[ ] Networking
[ ] Security

Fix bookinfo ingress example missing styles/js

---

pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
pilot/pkg/networking/core/v1alpha3/httproute_test.go
pilot/pkg/networking/core/v1alpha3/listener_test.go
pilot/pkg/networking/core/v1alpha3/networkfilter_test.go

Currently all of these test modify the same proxy object. Instead, we
should copy it each time we use.
Related: https://github.com/istio/istio/issues/24824

Fix pilot tests sharing mutable global state

---

tests/integration/tests.mk

This PR aims to fix a potential bug in tests.mk file (#24909). This PR should be reviewed together with https://github.com/istio/test-infra/pull/2727. The default value of `_INTEGRATION_TEST_SELECT_FLAGS` is updated to be the env variable `TEST_SELECT` from [here](https://github.com/istio/test-infra/blob/master/prow/config/jobs/istio.yaml). If TEST_SELECT is not provided, such as post-submit tests `integ-k8s-116`, `integ-k8s-117` and `integ-k8s-119`, the test select flags will be set to `-postsubmit,-flaky,-multicluster`
[ ] Docs
[ ] Networking
[ ] Security

Potential bug in tests.mk file

---

prow/lib.sh

When setting up multiple kind clusters for in the prow scripts we create a `kind` network as a workaround to issues running `kind create cluster` in parallel. This makes our `docker network create` more similar to what kind does [here](https://github.com/kubernetes-sigs/kind/blob/7620a6b488866a57cac5e73fc4540c348c6437d0/pkg/cluster/internal/providers/docker/network.go#L101) 
[ ] Docs
[ ] Networking
[ ] Security

prow setup: create kind network with ipmasq

---

tools/go-ordered-test.sh

Fixes https://github.com/istio/istio/issues/24824
This is not intended to be run in CI (because its super slow), just
locally. If we don't want it checked in I can just keep it in my local
scripts folder
[ ] Docs
[ ] Networking
[ ] Security

Add script to test order dependant go tests

---

pkg/kube/client.go

This provides a bit of performance improvement and security.
It lets us address questions related to https://github.com/istio/istio/issues/24331
- Currently Pilot provides XDS on 15012 and /version on 15014.  Can we combine these?
- Should there be a gRPC version endpoint?  Should it look like XDS Events or something else

Use port-forward instead of exec to get control plane version

---

pilot/pkg/networking/core/v1alpha3/gateway.go
pilot/pkg/networking/core/v1alpha3/gateway_test.go

https://github.com/istio/istio/pull/21198 added attempt count only for sidecar virtual hosts. This PR adds for gateway virtual hosts also
[ ] Docs
[ ] Security

add attempt count for gateway virutal hosts

---

pkg/test/framework/features/features.yaml
pkg/test/framework/integration/framework_test.go
pkg/test/framework/test.go
pkg/test/framework/testcontext.go

I am guessing this will solve
https://github.com/istio/istio/issues/24028
I am not proud of this solution, but I spent quite a few hours on this
and its the best I could come up with. The sequencing here is quite
complicated...
[ ] Docs
[ ] Networking
[ ] Security

Fix test cleanup of RunParallel

---

pilot/pkg/networking/core/v1alpha3/listener_test.go

This test is currently failing 1/3 of the time. The order of Services()
is not defined, AND its implemented differently in all registries. We
already have other tests that verify this works properly if we have
different times set on the service (which does have a defined ordering),
so this test is just validating incorrect assumptions.
[ ] Docs
[ ] Networking
[ ] Security

Remove broken/obsolete test

---

pilot/pkg/serviceregistry/kube/controller/controller.go

Fixes https://github.com/istio/istio/issues/24927
Current we pass the service *name* to ServiceUpdate. In the SE registry,
we pass hostname, as expected. The result of using the name is that on
service deletion, we actually use the wrong key for deletion.
[ ] Docs
[ ] Networking
[ ] Security

Fix endpointShardz leak

---

Makefile.core.mk

Bump base image for CVEs. Essentially a cherrypick of #24972 but using 1.6.
[ ] Docs
[ ] Networking
[ ] Security

[release-1.6] Bump base image version

---

prow/release-commit.sh

I'll create the PR to prevent a base image vulnerability from failing the release test.
Is there any discussion that relates to if there should be a failure in this case. I would say no unless we had some automation in place to build/push new images so the pipeline wouldn't be stopped until someone was available. If automation was in place, then failing this test might make sense.
[ ] Docs
[ ] Networking
[ ] Security

Ignore base image vulnerabilities during release testing

---

pilot/pkg/networking/core/v1alpha3/gateway.go
pilot/pkg/networking/core/v1alpha3/gateway_test.go

https://github.com/istio/istio/pull/22664 removed validation for sidecar listeners. This PR removes validation for gateway listeners
[ ] Docs
[ ] Security

remove validation for gateway listeners

---

pkg/test/framework/logging.go

This way users still see some level of logging. They can always disable
it explicitly if, for whatever reason, they want no logs.
The context here its impossible to run with framework:info currently,
which is my preferred log level
[ ] Docs
[ ] Networking
[ ] Security

Log framework scope even without CI flag

---

tests/integration/pilot/locality/distribute_test.go
tests/integration/pilot/locality/main_test.go

Sending 100 requests at once seems to overwhelm CI sometimes:
https://github.com/istio/istio/issues/25010
Trying to drop it down a bit
[ ] Docs
[ ] Networking
[ ] Security

Drop requests from 100 -> 50 for locality tests

---

pilot/pkg/networking/core/v1alpha3/cluster.go

Grouping `SIMPLE` and `MUTUAL` mode together instead of `ISTIO_MUTUAL` and `MUTUAL` mode. Results in some code duplication but we get better code readability. Grouping SIMPLE and MUTUAL will also be required down the line for cleaner and less repetitive code down the line with `CredentialName` TLS setting introduction.
[ ] Docs
[x] Networking
[x] Security

refactor applyUpstreamTLSSettings 

---

istioctl/cmd/describe.go

Resolves https://github.com/istio/istio/issues/24946
The problem was introduced with https://github.com/istio/istio/pull/23962/files#diff-ff5de02ffe7a166c1116286636b575a3R1200 .
It was confusing that the code returned an err if no DR existed, so instead of undoing the logging I made the function a bit cleaner.

'istioctl x describe' Don't consider it a problem if no destination rule is found

---

pkg/kube/inject/testdata/webhook/daemonset.yaml.injected
pkg/kube/inject/testdata/webhook/deploymentconfig-multi.yaml.injected
pkg/kube/inject/testdata/webhook/deploymentconfig-with-canonical-service-label.yaml.injected
pkg/kube/inject/testdata/webhook/deploymentconfig.yaml.injected
pkg/kube/inject/testdata/webhook/frontend.yaml.injected
pkg/kube/inject/testdata/webhook/hello-config-map-name.yaml.injected
pkg/kube/inject/testdata/webhook/hello-mtls-not-ready.yaml.injected
pkg/kube/inject/testdata/webhook/hello-multi.yaml.injected
pkg/kube/inject/testdata/webhook/hello-probes.yaml.injected
pkg/kube/inject/testdata/webhook/job.yaml.injected
pkg/kube/inject/testdata/webhook/list-frontend.yaml.injected
pkg/kube/inject/testdata/webhook/list.yaml.injected
pkg/kube/inject/testdata/webhook/replicaset.yaml.injected
pkg/kube/inject/testdata/webhook/replicationcontroller.yaml.injected
pkg/kube/inject/testdata/webhook/resource_annotations.yaml.injected
pkg/kube/inject/testdata/webhook/statefulset.yaml.injected
pkg/kube/inject/testdata/webhook/status_annotations.yaml.injected
pkg/kube/inject/testdata/webhook/traffic-annotations-empty-includes.yaml.injected
pkg/kube/inject/testdata/webhook/traffic-annotations-wildcards.yaml.injected
pkg/kube/inject/testdata/webhook/traffic-annotations.yaml.injected
pkg/kube/inject/testdata/webhook/user-volume.yaml.injected
pkg/kube/inject/webhook_test.go

In a recent commit these somehow got deleted, and our test decided a
missing input file is a t.Skip() instead of t.Fatal(). This rolls back
those files, and makes it an error if they are missing

Add back deleted tests

---

go.mod

[Build tools ](https://github.com/istio/tools/pull/872) uses `1.14.2` and most of the breakages are fixed in https://github.com/istio/istio/issues/21567 so I think it's safe to move from `1.13` to `1.14`.

Update go to 1.14 in go.mod

---

samples/tcp-echo/src/Dockerfile
tools/packaging/rpm/Dockerfile.build

Few leftovers go version update found during https://github.com/istio/istio/pull/25022. I wasn't able to test rpm build, I think @jwendell can help here ?

Update go version for tcp-echo sample and rpm build

---

tests/integration/pilot/main_test.go
tests/integration/pilot/traffic_shifting_test.go
tests/integration/pilot/util.go
tests/integration/pilot/vm/util.go
tests/integration/pilot/vm/vm_test.go

This PR extends pilot/traffic_shifting.go test to include tests for VMs. This test keeps the original non-vm tests, and added pre- and post-submit tests. 
[ ] Docs
[ ] Networking
[ ] Security

Extend traffic shifting test to include VM tests

---

pkg/test/echo/server/endpoint/grpc.go

[ ] Docs
[ ] Networking
[ ] Security

Avoid include binary metadata in echo app grpc response

---

pilot/pkg/networking/core/v1alpha3/gateway.go

For clusters with many gateways this is a massive line, when its not
very useful
[ ] Docs
[ ] Networking
[ ] Security

Remove potentionally massive log line

---

pilot/pkg/xds/ads.go
pilot/pkg/xds/ads_common.go
pilot/pkg/xds/ads_common_test.go
pilot/pkg/xds/cds.go
pilot/pkg/xds/debug.go
pilot/pkg/xds/discovery.go
pilot/pkg/xds/discovery_test.go
pilot/pkg/xds/eds.go
pilot/pkg/xds/ep_filters_test.go
pilot/pkg/xds/gen2.go
pilot/pkg/xds/internalgen.go
pilot/pkg/xds/lds.go
pilot/pkg/xds/pushqueue.go
pilot/pkg/xds/pushqueue_test.go
pilot/pkg/xds/rds.go

Fixes lint issues introduced in #24837 
- Rename `XdsConnection` -> `Connection`
- Rename `XdsEvent` -> `Event`
- Rename `XdsType` -> `Type`
[ ] Docs
[ ] Networking
[ ] Security

xds: lint fixes

---

pilot/pkg/model/config.go
pilot/pkg/model/virtualservice_test.go

In large clusters this has been shown to uses ~20% of CPU and ~10%/60% of
allocations  in terms of byes/number leading to huge GC trashing
BenchmarkResolveGatewayName/old-8               10342688
1222 ns/op             320 B/op         16 allocs/op
BenchmarkResolveGatewayName/new-8               39173893
322 ns/op              64 B/op          4 allocs/op
[ ] Docs
[ ] Networking
[ ] Security

Optimize ResolveGatewayName

---

mixer/pkg/lang/cel/builder_test.go

https://github.com/google/cel-go/issues/175 - required us to use a mutex in the test until it was fixed, and now it is fixed.
Found this while looking at #25063 - looking into it.
[X ] Configuration Infrastructure
[X ] Installation

Remove CEXLCompatibility Mutex

---

samples/bookinfo/platform/consul/bookinfo.yaml
samples/bookinfo/platform/kube/bookinfo-db.yaml
samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
samples/bookinfo/platform/kube/bookinfo-details.yaml
samples/bookinfo/platform/kube/bookinfo-mysql.yaml
samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
samples/bookinfo/platform/kube/bookinfo-ratings.yaml
samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
samples/bookinfo/platform/kube/bookinfo.yaml
samples/bookinfo/src/details/Dockerfile
samples/bookinfo/src/mongodb/Dockerfile
samples/bookinfo/src/mysql/Dockerfile
samples/bookinfo/src/productpage/Dockerfile
samples/bookinfo/src/productpage/productpage.py
samples/bookinfo/src/ratings/Dockerfile
samples/bookinfo/src/reviews/reviews-wlpcfg/Dockerfile

Last updated year ago https://github.com/istio/istio/pull/16556.
Not upgraded python version to the latest `3.8.3` because of some dependency issues, it was failing locally.
Referenced https://github.com/istio/istio/pull/24304 for updating tag

Update the base image versions to latest for bookinfo sample

---

pkg/test/framework/analyzer.go
pkg/test/framework/analyzer_runtime.go
pkg/test/framework/operations.go
pkg/test/framework/runtime.go
pkg/test/framework/suite.go
pkg/test/framework/suite_test.go
pkg/test/framework/suitecontext.go
pkg/test/framework/test.go
pkg/test/framework/testcontext.go
tests/integration/galley/namespace_test.go
tests/integration/tests.mk

When trying to quickly iterate locally; adding subtests to existing whitelisted tests (see mirrorTest) will trigger a failure. Small annoyance, but easy to run into.
As part of https://github.com/istio/istio/issues/24581 I needed a good way to track whether or not a test supported multicluster; that didn't fit cleanly into the feature labels. 
This will also help enumerate existing tests which tests need feature labels added. 
When running tests with `ANALYZE_TESTS` env var set (can move this to `--istio.test.analyze`) they will finish nearly instantly (doesn't actually run the test) and produce YAML that tells us:
- Validity (right now the only thing that invalidates is the lack of feature label/whitelist)
- Allows single-cluster (minClusters < 2)
- Allows multi-cluster (maxClusters != …

test framework: analyze test metadata without running them

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go

For HTTP2 cluster, ALPNH2Only was not being set in SIMPLE mode. Added more unit tests to cover this as well as SNI 
[ ] Docs
[ ] Networking
[x] Security

Bug Fix missing HTTP2 ALPN for UpstreamTLSContext

---

pilot/cmd/pilot-agent/main.go
pilot/pkg/bootstrap/certcontroller.go
pilot/pkg/bootstrap/istio_ca.go
pilot/pkg/bootstrap/server.go
pilot/pkg/networking/apigen/apigen_test.go
pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/xds/ads.go
pilot/pkg/xds/ads_test.go
pilot/pkg/xds/discovery.go
pkg/adsc/adsc.go
pkg/adsc/adsc_test.go
pkg/istio-agent/sds-agent.go
pkg/istio-agent/sds-agent_test.go
security/pkg/nodeagent/cache/secretcache.go
security/pkg/nodeagent/sds/server.go
security/pkg/pki/ca/ca.go
tests/util/pilot_server.go

- If istiod is started without access to K8S, for example by tests - generate and in memory self-signed root,
so tests or local use with mTLS is possible
- Update ADSC support for mTLS connections and envoy v3, part of improving the testing abilities.
Since v2 is deprecated it seems better to switch the test as well. I know the change on security is mixed and 
unrelated to v3 - but it's pretty hard to split the PR by line, and all changes to ADSC are related to 'improved testing' 
Extracted from PR#24398, to split it in smaller pieces.
[ ] Docs
[x] Networking
[x] Security

Security changes for testing

---

pilot/pkg/bootstrap/configcontroller.go
pilot/pkg/config/kube/ingress/controller.go
pilot/pkg/config/kube/ingress/conversion_test.go
pilot/pkg/config/kube/ingress/status.go
pilot/pkg/config/kube/ingress/status_test.go

This is a perf optimization to minimize the number of watches we open to the api server.
Part of #24640

ingress controller: use shared informers

---

pkg/test/framework/resource/context.go
pkg/test/framework/scope.go
pkg/test/framework/scope_test.go
pkg/test/framework/testcontext.go

The main fix here is that Context.GetResource should return an error. The fact that it didn't made it so we wouldn't check the suite scope in TestContext.
The other fix/enhancement is that all parent scopes will be traversed. For slices, that means resources in the entire scope ancestry will be collected. 
[ ] Docs
[ ] Networking
[ ] Security

fix: get resource from scope traverses parents

---

pilot/pkg/model/push_context.go

Currently, we initalize a default sidecar scope for each *service* -
but the scopes only differ by namespace. Instead, we can just create one
per namespace required.
```
name                              old time/op  new time/op
InitPushContext/gateways-8        5.90ms ± 0%  3.17ms ± 0%
InitPushContext/empty-8            268ns ± 0%   245ns ± 0%
InitPushContext/telemetry-8        273ns ± 0%   247ns ± 0%
InitPushContext/virtualservice-8   163ns ± 0%   149ns ± 0%
```
I often see this codepath using a large chunk of Pilot CPU in real world
tests, so I think the change is significant in these cases.
Benchmarking built on https://github.com/istio/istio/pull/25117
[ ] Docs
[ ] Networking …

Don't initialize multiple default sidecars for ns

---

pilot/pkg/xds/adapter.go
pilot/pkg/xds/gen2.go

This PR adds a new field to XDS responses from gen2 (for example, istio.io/connections)
```
"controlPlane": {
"identifier": "{\"component\":\"pilot\",\"id\":\"istiod-123456-1234\",\"info\":{\"version\":\"937e5ccc577c72971ed41c90dc791ce9caa0f6c5-dirty\",\"revision\":\"937e5ccc577c72971ed41c90dc791ce9caa0f6c5-dirty\",\"golang_version\":\"go1.14.2\",\"status\":\"Modified\",\"tag\":\"1.6.0-alpha.2-610-g937e5ccc5\"}}"
}
```
The format of identifier is wrapped JSON.
There are two purposes.  I propose to use the version as a replacement for istiod.istio-system:15014/version because that endpoint is not available under central Istiod 
(the issue is https://github.com/istio/istio/issues/24331 )
The pod name is there for debugging -- if we get an XDS response with this, to let us identify which pod …

Send envoy.config.core.v3.ControlPlane proto with experimental XDS

---

pilot/pkg/bootstrap/server.go

Validation Server is on by default now. Fixes incorrect comment.
[ ] Docs
[ ] Security

fix incorrect comment

---

pilot/pkg/model/push_context.go

Xds interface docs mention EDSupdate is only for service entry. This PR fixes it
[ ] Docs
[ ] Security

fix xds updater interface docs

---

pilot/pkg/xds/bench_test.go
pilot/pkg/xds/testdata/benchmarks/empty.yaml
pilot/pkg/xds/testdata/benchmarks/gateways-shared.yaml
pilot/pkg/xds/testdata/benchmarks/gateways.yaml
pilot/pkg/xds/testdata/benchmarks/telemetry.yaml

* Add new test for gateways. This is motivated by
https://github.com/istio/istio/issues/25116
* Make the tests more flexible/explicit. All config is now in the test
files. This does make the test a bit larger, as we define the
Services and service instance in each test, but its more flexible and
explicit so I think its worth it
* Add more debugability. Tests now report the XDS size(in bytes and # of
resources), and with a flag can do a configdump.
* Add a test for push context initialization. This can help us make
decisions about what makes sense to put in push context and what
doesn't, as push context is essentially a cache.
[ ] Docs
[ ] Networking
[ ] Security
[ ] Test and …

Improvements to XDS benchmarks

---

pilot/tools/debug/pilot_cli.go

Move Pilot CLI to v3
[ ] Docs
[ ] Security

xds: move pilot cli to v3

---

istioctl/cmd/root.go
istioctl/cmd/version.go
istioctl/pkg/clioptions/central.go
istioctl/pkg/multixds/gather.go
istioctl/pkg/xds/client.go

Resolves https://github.com/istio/istio/issues/24331
This command creates an experimental `istioctl x version` subcommand.  The output is identical to `istioctl version`.  The command uses XDS instead of /debug and /version.
The command will show incorrect values for the control plane unless https://github.com/istio/istio/pull/25042 is also merged.  Ideally that PR will merge first.

Initial XDS-based (experimental) version subcommand

---

istioctl/cmd/deprecated_cmd.go
pilot/pkg/bootstrap/configcontroller.go
pilot/pkg/config/kube/crdclient/client.go
pilot/pkg/config/kube/crdclient/client_test.go
pkg/kube/client.go
pkg/test/kube/mock_client.go

This is a perf optimization to minimize the number of watches we open to the api server.
Part of #24640

 Move istio CRD reader to shared informers

---

pilot/pkg/config/kube/ingress/controller.go

Currently this will panic when pilot exits; we should not run the
informers ourselves anymore, as they can only call .Run() one time and
they are shared. This is already called later at the top level
[ ] Docs
[ ] Networking
[ ] Security

Fix ingress crash on shutdown

---

pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/controller_test.go
pilot/pkg/serviceregistry/kube/controller/pod_test.go

This is no longer used now, we have the full node informer so we might as well just use that.

kube controller: remove metadata informer

---

pilot/pkg/bootstrap/server.go
pkg/spiffe/spiffe.go

Adds logging of SPIFFE-related reasons for rejecting a client.
Logs at INFO level.
While testing I was frustrated because totally bogus requests (e.g. grpcurl -insecure) logged failure:
```
error	ads	Failed to authenticate client &{[::1]:57854 {{772 true false 4865 h2 true localhost [] [] [] [] 0x1410950 []} {PrivacyAndIntegrity}}}
```
... but near successes logged nothing.  This change ensures something will be logged if an XDS client connection is rejected for a SPIFFE reason.

Log XDS client rejections due to SPIFFE

---

pilot/pkg/model/push_context.go
pilot/pkg/model/push_context_test.go
pilot/pkg/model/sidecar.go
pilot/pkg/model/sidecar_test.go
pilot/pkg/model/virtualservice.go
pilot/pkg/networking/core/v1alpha3/gateway.go

Fixes https://github.com/istio/istio/issues/25116
Against current master
```
name                               old time/op        new time/op        delta
InitPushContext/gateways-6               4.27ms ± 1%        4.03ms ± 1%   -5.59%  (p=0.008 n=5+5)
InitPushContext/gateways-shared-6         662µs ± 1%         465µs ± 1%  -29.75%  (p=0.008 n=5+5)
InitPushContext/empty-6                   302ns ± 2%         298ns ± 2%     ~     (p=0.222 n=5+5)
InitPushContext/telemetry-6               298ns ± 2%         298ns ± 3%     ~     (p=0.635 n=5+5)
InitPushContext/virtualservice-6          168ns ± 4%         171ns ± 2%     ~     (p=0.183 n=5+5)
RouteGeneration/gateways-6                387ms ± 1%         112ms ± 1%  -71.03%  (p=0.008 n=5+5)
RouteGeneration/gateways-shared-6         462ms ± 3% …
```

pilot: fix n^2 scaling behavior with gateways

---

pilot/pkg/xds/ads_common.go

Sidecar has no effect on gateways, no need to trigger a push
[ ] Docs
[ ] Networking
[ ] Security

Do not trigger push to Gateways when Sidecar object changes

---

pkg/istio-agent/sds-agent.go

Issue: Regression from 1.6.0 to 1.6.1. When ECC_SIGNATURE_ALGORITHM was being
set the secret cache was being created without the proper settings.
https://github.com/istio/istio/blob/master/pkg/istio-agent/sds-agent.go#L384 creates the secret cache, but this is not set until https://github.com/istio/istio/blob/master/pkg/istio-agent/sds-agent.go#L513
[ ] Docs
[ ] Networking
[X] Security

Fix agent starting when using ECC_SIGNATURE_ALGORITHM

---

go.mod
go.sum

Update to current fortio (includes fix for #21289 )
https://github.com/fortio/fortio/compare/v1.3.1...v1.4.1
ran `go mod tidy` after go.mod update
[ ] Docs
[ ] Networking
[ ] Security

update fortio to 1.4.1

---

pilot/pkg/xds/discovery.go
pilot/pkg/xds/eds.go

Fixes regression caused by https://github.com/istio/istio/pull/24487
The `||` check is always true, should instead be `&&`.
[ ] Docs
[ ] Networking
[ ] Security

Fix non k8s registry check

---

security/pkg/server/ca/authenticate/cert_authenticator_test.go
security/pkg/server/ca/server_test.go

Add unit test of CSR request to server to test cliencertauthenticator works correctly
[ ] Docs
[ ] Networking
[X] Security

Add unit test of CSR request to server unit test to test cliencertauthenticator works correctly

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go

UpstreamTLSContext generation function just how we have a separate function for building downstream TLS context. This logic is quite extensive and needs to be decoupled into it's own function and TLS context needs to be tested separately. These changes were made in https://github.com/istio/istio/pull/25202 but git diff for this isn't pretty and makes it hard to review. So I've decoupled the moving to separate function logic here and will later rebase these changes in #25202 .  Ref:https://github.com/istio/istio/issues/14039

Move UpstreamTLSContext Generation to separate function and extend test coverage

---

pkg/dns/dns.go

The pkg/dns/dns.go implementation is currently leaking timers, and has a channel send/receive deadlock race. The included commits address both the resource waste as well as eliminate the potential for a deadlock.
[ ] Docs
[X] Networking
[ ] Security

dns: Deadlock fix and performance improvements.

---

istioctl/pkg/clioptions/central.go
istioctl/pkg/multixds/gather.go
istioctl/pkg/xds/client.go
pkg/adsc/adsc.go

Adds `--insecure` option to `istioctl x verify`.  This debugging option works the same as `--insecure` on _grpcurl_.

istioctl --xds-san and --insecure options for testing XDS

---

pilot/pkg/xds/eds.go

If endpoint shard is newly created (that means new service) we any way do a full push. So we do not have to compare service accounts. This PR skips that
[ ] Docs
[ ] Security

eds: compare service accounts for existing endpoint shards only

---

pilot/pkg/xds/ads.go
pilot/pkg/xds/monitoring.go

Signed-off-by: Liam White <liam@tetrate.io>
Adds a version label to `pilot_xds` to give more information on data plane versions with needing to scrape the entire data plane.
See https://istio.slack.com/archives/C38CF1PEC/p1594141641327900 for background.
[ ] Docs
[x] Networking
[x] Policies and Telemetry
[ ] Security

Add version label to `pilot_xds`  metric

---

pilot/pkg/config/kube/crdclient/cache_handler.go
pilot/pkg/config/kube/crdclient/client.go
pilot/pkg/config/kube/crdclient/metrics.go

Discovered while diagnosing https://github.com/istio/istio/issues/25271
Messages like `Skipping CRD networking.x-k8s.io/v1alpha1/GatewayClass as it is not present` should be logged under a scope so that they can be tracked or suppressed.

Log CRD client messages under a scope

---

pilot/pkg/model/push_context.go
pilot/pkg/model/sidecar.go
pilot/pkg/networking/core/v1alpha3/gateway.go
pilot/pkg/networking/core/v1alpha3/route/route.go
pilot/pkg/networking/util/util.go

```
name                                  old time/op        new time/op        delta
ListEquals-6                                16.3µs ± 1%        16.1µs ± 2%     ~     (p=0.421 n=5+5)
InitPushContext/gateways-6                  4.07ms ± 1%        4.09ms ± 2%     ~     (p=0.222 n=5+5)
InitPushContext/gateways-shared-6            454µs ± 1%         450µs ± 2%     ~     (p=0.690 n=5+5)
InitPushContext/empty-6                      290ns ± 3%         287ns ± 1%     ~     (p=0.548 n=5+5)
InitPushContext/telemetry-6                  290ns ± 1%         292ns ± 2%     ~     (p=0.460 n=5+5)
InitPushContext/virtualservice-6             165ns ± 4%         162ns ± 1%     ~     (p=0.079 n=5+5)
RouteGeneration/gateways-6                   111ms ± 1%          43ms ± 2%  -61.04%  (p=0.008 n=5+5) …
```

Optimize performance for large numbers of services

---

pilot/pkg/xds/ads.go
pilot/pkg/xds/debug.go
pilot/pkg/xds/eds.go
pilot/pkg/xds/eds_sh_test.go
pilot/pkg/xds/eds_test.go
pilot/pkg/xds/rds.go

ads: use watched resourcenames instead of clusters and routes

---

pilot/pkg/config/kube/crdclient/client.go
pilot/pkg/config/kube/crdclient/client_test.go

When moving to istio/client-go, there was regression in behavior when a
CRD was missing. Previously we return nil, now we return error.
Old code:
https://github.com/istio/istio/blob/release-1.6/pilot/pkg/config/kube/crd/controller/controller.go#L425
[ ] Docs
[ ] Networking
[ ] Security

Fix missing CRDs in client

---

istioctl/cmd/proxystatus.go
istioctl/cmd/proxystatus_test.go
istioctl/pkg/writer/compare/cluster.go
istioctl/pkg/writer/compare/comparator.go
istioctl/pkg/writer/compare/listener.go
istioctl/pkg/writer/compare/route.go
istioctl/pkg/writer/pilot/status.go
istioctl/pkg/writer/pilot/status_test.go
istioctl/pkg/writer/pilot/testdata/multiStatusMultiPilot.txt
istioctl/pkg/writer/pilot/testdata/multiStatusSinglePilot.txt
istioctl/pkg/writer/pilot/testdata/singleStatus.txt
istioctl/pkg/writer/pilot/testdata/singleStatusFallback.txt

Refactor and update output of `istioctl proxy-status`
Old output with (**PILOT**)
```
$ $GOPATH/src/istio.io/istio/out/linux_amd64/istioctl proxy-status
NAME                                                   CDS        LDS        EDS        RDS          PILOT                      VERSION
details-v1-558b8b4b76-h9jbz.default                    SYNCED     SYNCED     SYNCED     SYNCED       istiod-6cf8d4f9cb-zsk5v     1.6.0
istio-ingressgateway-66c994c45c-brfkd.istio-system     SYNCED     SYNCED     SYNCED     NOT SENT     istiod-6cf8d4f9cb-zsk5v     1.6.0
productpage-v1-6987489c74-wchxv.default                SYNCED     SYNCED     SYNCED     SYNCED       istiod-6cf8d4f9cb-zsk5v     1.6.0
prometheus-7bdc59c94d-g65j5.istio-system               SYNCED     SYNCED     SYNCED     SYNCED …
```

update pilot to istiod for istioctl proxy-status

---

tools/istio-iptables/pkg/cmd/run.go
tools/istio-iptables/pkg/cmd/run_test.go

closes https://github.com/istio/istio/issues/25000
This PR only pulls in the iptables gen fix, curious what differences there may be in templates/template-locations for 1.5? 
[ ] Docs
[X] Networking
[ ] Security

cherry-pick: istio iptables filters empty values

---

pkg/envoy/proxy.go
pkg/envoy/proxy_test.go

before:
```
2020-07-08T09:05:19.592489Z     info    envoy upstream  [bazel-out/k8-opt/bin/external/envoy/source/server/lds_api.cc:78] lds: add/update listener '0.0.0.0_8090'
2020-07-08T09:05:19.592833Z     info    envoy upstream  [bazel-out/k8-opt/bin/external/envoy/source/server/lds_api.cc:78] lds: add/update listener '10.96.0.10_9153'
2020-07-08T09:05:19.593176Z     info    envoy upstream  [bazel-out/k8-opt/bin/external/envoy/source/server/lds_api.cc:78] lds: add/update listener '10.111.165.28_853'
2020-07-08T09:05:19.593263Z     info    envoy upstream  [bazel-out/k8-opt/bin/external/envoy/source/server/lds_api.cc:78] lds: add/update listener 'virtualOutbound'
2020-07-08T09:05:19.599121Z     info    envoy upstream  [bazel-out/k8-opt/bin/external/envoy/source/server/lds_api.cc:78] lds: …
```

Reduce length of envoy logs

---

pkg/test/env/istio.go
pkg/test/framework/components/gcemetadata/gce_metadata_server.yaml
pkg/test/framework/components/gcemetadata/gcemetadata.go
pkg/test/framework/components/gcemetadata/kube.go

Adds a testing component for a GCE Metadata Server.
This will enable the integration testing of GCP platform bootstrapping for VMs. Right now, there is no configurability provided, but this can be expanded in the future to provide configuration of the test server to match testing needs.
This is a follow-on PR to: https://github.com/istio/istio/pull/25264. Future PRs will include the use of this component in the setup, etc.

feat(testing): Add GCE Metadata Server component

---

pkg/test/framework/components/echo/kube/instance.go

https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25294/integ-ipv6-k8s-tests_istio/1732
What happens is the pod startup just takes a while due to a fresh image
pull. We only wait 30s here - instead we should wait for the full
readiness timeout.
[ ] Docs
[ ] Networking
[ ] Security

Fix VM test flakes

---

Makefile.core.mk
bin/protoc.sh
mixer/pkg/attribute/generate_word_list.sh

By making sure `-mod=vendor` is not used or assumed as default
when there is a vendor/ directory.
`make gen` also needs the dependencies to be downloaded in the go cache (commands
like `go list -m all` do not work with `-mod=vendor`).

Better handle vendored trees

---

pkg/test/fakes/gce_metadata_server/Dockerfile
pkg/test/fakes/gce_metadata_server/Makefile
pkg/test/fakes/gce_metadata_server/main.go

This PR establishes a basic fake for a GCE Metadata server. At the moment, nothing currently uses this fake. The intention is to use this in VM testing to provide simulation of GCE environment for testing purposes. The initial use of this will be for e2e telemetry tests on VMs.
The `Makefile` and `Dockerfile` are provided to allow easy creation of new images when required. It is NOT expected that these will need to be used at any frequency.
/cc @justinwei2 @howardjohn 

(test): add fake for GCE Metadata Server

---

pkg/test/framework/features/features.yaml
tests/integration/pilot/traffic_shifting_test.go
tests/integration/pilot/vm/util.go
tests/integration/pilot/vm/vm_test.go
tests/integration/pilot/vm/vm_traffic_shifting_test.go

This PR aims to address the TODO left in TestVmOS. This moves the function `sendTraffic` to the util file, and create a new test to decouple the traffic shifting from `vm_test.go`. This might be clearer and TestVmOS could focus on performing reachability checks. 
[ ] Docs
[ ] Networking
[ ] Security

De-dup send traffic and decouple traffic shifting

---

tools/dump_kubernetes.sh

While the comment in the `dump_kubernetes.sh` script (`dump... secrets (names only)`) let you think it's secure to dump and share your cluster's config dump,  the full cluster's secrets are dumped. This is a high security risk for users who may share their root certs and maybe other sensible informations.
This PR effectively only dump secret's name (kubectl get secret --all-namespaces).It also add an option `--add-full-secrets` in case you really want that. 
It also remove the `--export` keyword that is deprecated for quite some time.
[ ] Docs
[ ] Networking
[ ] Security

removed secret dumps and deprecated --export from dump_kubernetes.sh

---

Makefile.core.mk
bin/protoc.sh
mixer/pkg/attribute/generate_word_list.sh

By making sure `-mod=vendor` is not used or assumed as default
when there is a vendor/ directory.
Manual cherrypick of #25360.

[release-1.6] Better handle vendored trees

---

tools/istio-iptables/pkg/cmd/root.go
tools/istio-iptables/pkg/cmd/run.go
tools/istio-iptables/pkg/cmd/run_test.go
tools/istio-iptables/pkg/config/config.go
tools/istio-iptables/pkg/constants/constants.go

150XX ports are reserved for istio
Reserve port 15008 for not capture. Expecting 
Follow up:
Pilot generates inbound http2 listener on 15008 with enforced istio certs. for sidecar envoy.
Pilot generates outbound cluster to connect 15008 endpoint.
Part of #24540

networking: add better transport security iptables rules

---

galley/pkg/config/source/kube/apiserver/watcher.go

The logic for recovering the tombstone here is confusing and seems wrong. The result of `tombstone.RecoverResource()` will be nil if there is an error -- it's not returning an error value.
[ ] Docs
[ ] Networking
[ ] Security

Fix tombstone recovery bug in Galley

---

pilot/pkg/networking/core/v1alpha3/gateway.go
pilot/pkg/networking/core/v1alpha3/route/route.go

Moves the expensive sorting part of the merge after all appends are complete. 
Goes from m*n to m+n for merging. 
<table class='benchstat '>
<tr class='configs'><th><th>master (7d9e726d4c)<th>548e4acba0<th>06047384a7</th>
<tbody>
<tr><th><th colspan='3' class='metric'>time/op
<tr>
<td>RouteGeneration/gateways-12<td>38.0ms ± 1%<td>38.4ms ± 2%<td>40.1ms ± 1%
<tr>
<td><b>RouteGeneration/gateways-shared-12</b><td><b style="color: red">364ms ± 7%</b><td><b>173ms ± 2%</b><td><b>177ms ± 1%</b>
<tr>
<td>RouteGeneration/empty-12<td>676µs ± 2%<td>680µs ± 2%<td>679µs ± 1%
<tr>
<td>RouteGeneration/telemetry-12<td>686µs ± 1%<td>691µs ± 1%<td>695µs ± 2%
<tr>
<td>RouteGeneration/virtualservice-12<td>1.57ms ± 2%<td>1.55ms ± 1%<td>1.55ms ± 1%
</tbody>
</table>
**master vs new (with 12)**
```
name …
```

optimize CombineVHostRoutes

---

pilot/pkg/config/kube/crd/config_test.go
pilot/pkg/config/kube/crd/roundtrip/roundtrip.go

For https://github.com/istio/istio/issues/14935
I explicitly tested this would have caught two bugs we have had around
CRD pruning (one currently blocking istio/api update)
[ ] Docs
[ ] Networking
[ ] Security

Add roundtrip fuzzing tests for our CRDs

---

pilot/pkg/security/model/authentication_test.go

[ ] Docs
[ ] Networking
[X] Security

Add unit test for mode/authentication to cover ConstructSdsSecretConfigWithCustomUds, ConstructValidationContext, ApplyCustomSDSToCommonTLSContext

---

CODEOWNERS
releasenotes/template.yaml

This is the first step towards automating the release notes process. This presents a template that we will link to in a prow job. This will be expected to be filled in for *all* user facing changes. 
Part of https://github.com/istio/istio/issues/23622
[ ] Docs
[ ] Networking
[ ] Security

Added template for release notes

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go

` rejected: Error adding/updating cluster(s) outbound|443||edition.cnn.com: Proto constraint validation failed (UpstreamTlsContextValidationError.CommonTlsContext: ["embedded message failed validation"] | caused by CommonTlsContextValidationError.CombinedValidationContext: ["embedded message failed validation"] | caused by CombinedCertificateValidationContextValidationError.ValidationContextSdsSecretConfig: ["value is required"]): common_tls_context {
combined_validation_context {
default_validation_context {
}
}
}`
If caCredential is not specified and no proxy metadata cert override exists, attempt to create empty file watcher result in erroneous TLSContext.  This bug was captured by documentation testing:https://github.com/istio/istio.io/pull/7669. 
This got broken in changes made here: …

[Bug Fix] Empty ResouceName results in ill configured UpstreamTLSContext

---

pilot/pkg/status/reporter.go
pilot/pkg/status/reporter_test.go

Optimize reverse status due to high cpu utilization in tests.
[ ] Docs
[ ] Networking
[ ] Security

record reverseStatus as hashset, due to high cpu utilization

---

pilot/pkg/model/gateway.go
pilot/pkg/networking/core/v1alpha3/gateway.go

Store SniHosts by Server in MergedGateway to avoid recomputation of sni hosts per server
[ ] Docs
[ ] Security

gateway: do not compute snihosts for service repeatedly

---

pkg/test/framework/components/ingress/kube.go

- massive log lines with the entire k8s api object(s) now just print the names
- remove duplicated code for getHTTPAddressInner
[ ] Docs
[ ] Networking
[ ] Security

cleanup ingress test component

---

galley/pkg/config/analysis/analyzers/virtualservice/destinationhosts.go
galley/pkg/config/analysis/analyzers/virtualservice/destinationrules.go
galley/pkg/config/analysis/analyzers/virtualservice/util.go

Fixes #25440, unblocks #22872. Changes mirror hosts to be distinct from other hosts.
[ ] Docs
[ ] Networking
[ ] Security

Split mirrors into separate path in virtualservice analyzers

---

prow/benchtest.sh

Sometimes it goes too long:
https://storage.googleapis.com/istio-prow/logs/benchmark-report_istio_postsubmit/40/artifacts/benchmark-log.txt
[ ] Docs
[ ] Networking
[ ] Security

Increase timeout for benchtest

---

pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/controller_test.go
pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
pilot/pkg/serviceregistry/kube/controller/endpoints.go
pilot/pkg/serviceregistry/kube/controller/endpointslice.go
pilot/pkg/serviceregistry/kube/controller/pod.go

@ramaraochavali @nrjpoddar what do you think? The basic idea is we record any pods we are missing. When those pods in later, we re-add the endpoint to the queue.
TODO: there is still a memory leak if the pod never comes

Trigger endpoint update when pod comes in

---

pkg/test/framework/components/echo/kube/deployment.go

local dev improvement
This fails when I run on real k8s clusters unless there is some time between the Istio deploy and the VM test. Works fine in CI because MetalLB assigns external IPs pretty much instantly. 
[ ] Docs
[ ] Networking
[ ] Security

echo retries GetRemoteDiscoveryAddress

---

istioctl/cmd/proxyconfig.go
istioctl/pkg/writer/envoy/configdump/cluster.go
istioctl/pkg/writer/envoy/configdump/route.go

Resolves https://github.com/istio/istio/issues/23987 by providing one line per virtual-host-route instead of one line per-overall route.  New columns DOMAINS, MATCH, CONFIG, and VS (virtual service) supply information.
The previous output is still available if `--verbose=false` is specified.
The previous version shows
```
NAME        VIRTUAL HOSTS
http.80     1
1
1
```
The new version shows
```
NAME                                  DOMAINS     MATCH                  VIRTUAL SERVICE
http.80                               *           /productpage           bookinfo.default
http.80                               *           /static*               bookinfo.default
http.80                               *           /login                 bookinfo.default
http.80                               * …
```

More output columns for 'istioctl pc routes' and 'clusters'

---

pilot/pkg/bootstrap/server.go
pilot/pkg/serviceregistry/kube/controller/multicluster.go
pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go

This updates the namespace controller to use the new shared informers. This is a perf optimization to minimize the number of watches we open to the api server.
Part of https://github.com/istio/istio/issues/24640

namespace controller: use shared informer

---

pilot/cmd/pilot-agent/main.go
pkg/istio-agent/sds-agent.go
pkg/istio-agent/xds-agent.go

Based on https://github.com/istio/istio/pull/25411#pullrequestreview-446234102, As the default `ControlPlaneAuthPolicy` is `MUTUAL_TLS`. There is no need for setting `RequireCerts` in SDS Agent.
Ref PR:
https://github.com/istio/istio/pull/25411
https://github.com/istio/api/pull/1493

Cleanup RequireCerts from SDS Agent

---

pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/controller_test.go
pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
pilot/pkg/serviceregistry/kube/controller/endpoints.go
pilot/pkg/serviceregistry/kube/controller/endpointslice.go
pilot/pkg/serviceregistry/kube/controller/pod.go

The pod lookup exists in endpoint and endpoint slice - This PR refactors it. Also there was a bug in key used while getting pod from shared informer (was using endpoint key instead of pod key) - fixed that. Renamed some functions.
[ ] Docs
[ ] Security

refactor pod lookup code

---

pilot/pkg/model/config.go
pilot/pkg/model/sidecar.go

Use ConfigKey for map keys will waste too much memory.
Before Optimize:
After Optimize

optimize memory usage (#25531)

---

pkg/bootstrap/platform/azure.go
pkg/bootstrap/platform/azure_test.go
pkg/bootstrap/platform/discovery.go

Support for the Azure platform with a few metadata attributes extracted as proof of functionality.
Checked that retrieved metadata and locality are as expected in comparison to the API curl request described on https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service
Metadata() is incomplete at the moment, but azure_name, azure_location, and azure_vm_id are basic attributes that have been added in. The others are parsed from the tags field. An example of the metadata:
"PLATFORM_METADATA": {
"azure_vm_id": "5376324d-0cd7-4e3a-b350-d967eb74d097",
"azure_location": "centralus",
"orchestrator": "Kubernetes",
"creationSource": "aks-aks-nodepool1-34440236-vmss",
"azure_name": "aks-nodepool1-34440236-vmss_0",
"poolName": "nodepool1",
"resourceNameSuffix": …

Azure Platform Support

---

istioctl/cmd/proxystatus.go
istioctl/cmd/root.go
istioctl/pkg/multixds/gather.go
istioctl/pkg/writer/compare/comparator.go
istioctl/pkg/writer/pilot/status.go
pilot/pkg/xds/debug.go
pilot/pkg/xds/internalgen.go

Resolves https://github.com/istio/istio/issues/25373 .
This provides similar function to Istio's /debug/syncz (the variant that returns all proxies)
The response is in CSDS format.
To test this, do `istioctl x ps --xds-address localhost:15010`.  The response is nearly identical to the original:
```
NAME                                                   CDS        LDS        EDS          RDS          ISTIOD                      VERSION
productpage-v1-7f4cc988c6-fmnfj.default                SYNCED     SYNCED     NOT_SENT     NOT_SENT     istiod-79bb4ccbfd-jw9d6     ad6880c4d6a9994f9823291423771258e3b9749d-dirty
test-1.default                                                                                         istiod-79bb4ccbfd-jw9d6     ad6880c4d6a9994f9823291423771258e3b9749d-dirty …
```

XDS-based replacement for /debug/syncz

---

pilot/pkg/model/push_context.go
pilot/pkg/model/sidecar.go
pilot/pkg/networking/core/v1alpha3/networkfilter.go
pilot/pkg/networking/plugin/mixer/mixer.go
pilot/pkg/networking/plugin/mixer/mixer_test.go
pilot/pkg/xds/bench_test.go
pilot/pkg/xds/eds.go
releasenotes/25519.yaml

```
name                         old time/op    new time/op    delta
EndpointGeneration/1/100-8      257µs ±16%     157µs ±11%  -39.00%  (p=0.008 n=5+5)
EndpointGeneration/10/10-8      100µs ± 9%     102µs ±14%     ~     (p=0.841 n=5+5)
EndpointGeneration/100/10-8     590µs ±13%     626µs ±11%     ~     (p=0.310 n=5+5)
EndpointGeneration/1000/1-8     869µs ± 8%     940µs ± 7%     ~     (p=0.095 n=5+5)
name                         old alloc/op   new alloc/op   delta
EndpointGeneration/1/100-8     75.1kB ± 0%    75.1kB ± 0%     ~     (p=0.357 n=5+5)
EndpointGeneration/10/10-8     22.2kB ± 0%    22.2kB ± 0%     ~     (p=0.095 n=5+5)
EndpointGeneration/100/10-8    41.9kB ± 0%    42.0kB ± 0%     ~     (p=0.730 n=5+5)
EndpointGeneration/1000/1-8    37.7kB ± 3%    37.9kB ± 1%     ~     (p=0.690 …
```

Optimize DR lookup in EDS

---

pilot/pkg/xds/eds.go
pilot/pkg/xds/monitoring.go
releasenotes/25519.yaml

```
name                           old time/op    new time/op    delta
EndpointGeneration/100/1-8       94.3µs ± 7%    89.7µs ±17%     ~     (p=0.635 n=3+3)
EndpointGeneration/1000/1-8       855µs ± 2%     822µs ± 3%     ~     (p=0.125 n=3+3)
EndpointGeneration/10000/1-8     7.62ms ± 6%    7.14ms ± 3%     ~     (p=0.162 n=3+3)
EndpointGeneration/100/100-8      714µs ± 3%     665µs ± 7%     ~     (p=0.156 n=3+3)
EndpointGeneration/1000/100-8    5.17ms ± 7%    6.45ms ±20%     ~     (p=0.193 n=3+3)
name                           old alloc/op   new alloc/op   delta
EndpointGeneration/100/1-8       6.59kB ± 0%    4.69kB ± 0%  -28.90%  (p=0.000 n=3+3)
EndpointGeneration/1000/1-8      37.9kB ± 0%    35.9kB ± 0%   -5.29%  (p=0.000 n=3+3)
EndpointGeneration/10000/1-8      312kB ± 5%     304kB ± 3% …
```

Remove inaccurate and non-performant EDS metrics

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go

Generating secret watching SDS config is useless and incorrect in case when the proxy is of type Sidecar

Disable SDS Config generation for Sidecar Proxy when CredentialName is set

---

prow/benchtest.sh

Right now its using 16 CPUs but is limited to 8. I think this leads to
flaky results
[ ] Docs
[ ] Networking
[ ] Security

Pin number of CPUs for benchmark

---

go.mod
go.sum
licenses/github.com/openshift/build-machinery-go/LICENSE

Please provide a description for what this PR is for:
This PR fixes an error I see when I try to set up my local build environment with `istio/istio`:
```
go: github.com/openshift/api@v3.9.1-0.20191008181517-e4fd21196097+incompatible: invalid pseudo-version: preceding tag (v3.9.0) not found
```
This PR pins the commit SHA of `openshift/api` instead of using a problematic pseudo-version. Switching to a commit SHA solves the problem for me.
[ ] Docs
[ ] Networking
[ ] Security

pin a commit SHA of openshift/api as a dep instead

---

pilot/pkg/bootstrap/istio_ca.go
security/pkg/pki/ca/ca.go
security/pkg/pki/ca/ca_test.go
security/pkg/pki/ca/selfsignedcarootcertrotator.go
security/pkg/pki/ca/selfsignedcarootcertrotator_test.go
security/pkg/server/ca/server_test.go

When user specifies env `CITADEL_CA_RSA_KEY_SIZE` that key size is used to
generate Istio CA certificates allowing for finer control of security.
Part of a bigger effort to specify later Key parameters (e.g. RSA Key sizes for CSRs, type of Signature algorithm).
[ ] Docs
[ ] Networking
[X] Security

Add env to support RSA Key size for Istio self signed CA certificates

---

pkg/test/framework/analyzer.go
tests/integration/tests.mk

- fix for unnecessary failures
- add target for analyzing subdirectory
`make test.integration.analyze` passes, should be able to bring back https://github.com/istio/test-infra/pull/2744 job
[ ] Docs
[ ] Networking
[ ] Security

test analyzer does not fail unlabeled tests when suite is skipped

---

pkg/test/framework/components/echo/config.go
pkg/test/framework/components/echo/kube/deployment.go
pkg/test/framework/components/istio/operator.go
pkg/test/framework/components/stackdriver/kube.go
pkg/test/framework/components/stackdriver/stackdriver.go
pkg/test/framework/features/features.yaml
tests/integration/telemetry/stackdriver/vm/main_test.go
tests/integration/telemetry/stackdriver/vm/testdata/client_request_count.json.tmpl
tests/integration/telemetry/stackdriver/vm/testdata/server_access_log.json.tmpl
tests/integration/telemetry/stackdriver/vm/testdata/server_request_count.json.tmpl
tests/integration/telemetry/stackdriver/vm/vm_test.go

This PR adds an initial test of Stackdriver telemetry function for VMs. In particular, it exercises metrics and logging paths for a server running on a VM.
This is part of a larger push to validate telemetry function in VM environments.
A few notes:
- avoids VM DNS issues by directly referencing the fake Stackdriver and GCE Metadata servers by cluster IP (and not names).
- does not validate proper Monitored Resource usage (must be done in a follow-on effort).
- uses `http` requests for now (as opposed to the `grpc` in existing Stackdriver tests).
Future improvements:
- validate traces and edges
- validate MR (`gce_instance`)
- use VM simplification work for VM setup
Local results:
```bash
$ HUB=gcr.io/istio-testing TAG=1.7-dev go test ./tests/integration/telemetry/stackdriver/vm/... …
```

feat(testing): Add VM-based Stackdriver tests for metrics and logs.

---

tools/istio-iptables/pkg/cmd/run.go
tools/istio-iptables/pkg/cmd/run_test.go

iptables should not build any v6 rules on v4 only system.
Signed-off-by: Yuchen Dai <silentdai@gmail.com>
fix #25289
#24538

iptables: fix dns rules on v4 only system

---

pilot/pkg/model/sidecar.go
pilot/pkg/xds/ads_common_test.go

Continuation of https://github.com/istio/istio/pull/25403 for https://github.com/istio/istio/issues/25364
Adds the following to the list of "namespace scope" resources for a sidecar:
- EnvoyFilter
- AuthorizationPolicy
- ~PeerAuthentication~ will have issues
- RequestAuthentication
Still need to validate this scoping is accurate for these resource types.

sidecar scope matches ns for envoy filter and authn/z

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
pilot/pkg/networking/core/v1alpha3/gateway_test.go
pilot/pkg/security/authn/utils/utils_test.go
pilot/pkg/security/model/authentication.go
pilot/pkg/security/model/authentication_test.go
pilot/pkg/xds/bench_test.go
pilot/pkg/xds/testdata/benchmarks/tls.yaml
pkg/bootstrap/option/convert.go

```
$ benchstat /tmp/{old,new}
name                                 old time/op        new time/op        delta
ClusterGeneration/gateways-8               3.59ms ± 8%        3.79ms ±17%     ~     (p=0.548 n=5+5)
ClusterGeneration/gateways-shared-8        3.77ms ± 3%        3.83ms ±15%     ~     (p=0.548 n=5+5)
ClusterGeneration/empty-8                  1.69ms ±10%        1.80ms ±11%     ~     (p=0.421 n=5+5)
ClusterGeneration/tls-8                    5.91ms ±11%        5.18ms ± 2%  -12.34%  (p=0.016 n=5+4)
ClusterGeneration/telemetry-8              1.59ms ± 2%        1.62ms ± 4%     ~     (p=0.421 n=5+5)
ClusterGeneration/virtualservice-8          420µs ± 5%         391µs ± 2%   -6.91%  (p=0.008 n=5+5)
name                                 old alloc/op       new alloc/op       delta …
```

Optimize memory usage of SDS cluster config generation

---

manifests/profiles/demo.yaml

resolve: https://github.com/istio/istio/issues/25626
cherrypick https://github.com/istio/istio/pull/24566
[ ] Docs
[ ] Networking
[ ] Security

Cherrypick 24566 - update proxy readiness probe to port 15021 and cleanup demo profile.

---

samples/bookinfo/platform/kube/cleanup.sh

This PR checks if the namespace is available and if it does not, script assume the default namespace. It also waits for `30s` before cleanup exists.
**Before**:
If the user provides an invalid namespace, bookinfo cleanup runs and shows successful cleanup. 
```
$ samples/bookinfo/platform/kube/cleanup.sh
namespace ? [default] y
using NAMESPACE=y
Application cleanup may take up to one minute
Application cleanup successful
```
When you check pods, it shows the pods are still running.
```
$ kubectl get pods
NAME                              READY   STATUS             RESTARTS   AGE
details-v1-6c9f8bcbcb-2n7b5       2/2     Running            0          120m
productpage-v1-7df7cb7f86-ks2qb   1/2     CrashLoopBackOff   26         120m
ratings-v1-65cff55fb8-f2cr4       2/2     Running …
```

verify if namespace exists during bookinfo cleanup

---

istioctl/cmd/config_test.go
istioctl/cmd/root.go
pkg/test/framework/components/istio/operator.go

Temporarily rolling back part of #25280 which causes a concurrent map write panic when deploying istio in parallel for multicluster tests. 
https://github.com/istio/istio/blob/a09277852d82e6b13eacd87003a822c232081b03/istioctl/cmd/root.go#L142
A proper fix adding locking to the viper package is incoming if we think that's worth it.
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25612/integ-multicluster-k8s-tests_istio/6961
https://prow.istio.io/view/gcs/istio-prow/pr-logs/pull/istio_istio/25631/integ-multicluster-k8s-tests_istio/6956
[ ] Docs
[ ] Networking
[ ] Security

fix broken multicluster tests

---

galley/pkg/config/testing/basicmeta/collections.gen.go
galley/pkg/config/testing/k8smeta/collections.gen.go
pkg/config/schema/ast/ast.go
pkg/config/schema/codegen/collections.go
pkg/config/schema/codegen/collections_test.go
pkg/config/schema/collections/collections.gen.go
pkg/config/schema/metadata.gen.go
pkg/config/schema/metadata.yaml

This PR is an experiment.  The idea is to mark deprecated Istio types in the schema, and use that information in the deprecation analyzer.
If approved this would be used in conjunction with a second PR to enable the `istioctl analyze` for https://github.com/istio/istio/issues/24471 .

Track deprecated Istio types

---

bin/init.sh

Proposing a very small change for a spelling mistake in /bin/init.sh;
[ ] Docs
[ ] Networking
[ ] Security

fix spelling mistake in file init.sh

---

pkg/test/framework/components/namespace/namespace.go
pkg/test/framework/resource/flags.go
pkg/test/framework/resource/settings.go

Especially combined with https://github.com/istio/istio/pull/25636, this
makes local test development *much* faster. There is a basically no
overhead of test setup, so most tests which are of the form apply
config,send traffic, check result can run completely in under 1s.
[ ] Docs
[ ] Networking
[ ] Security

Add stableNamespaces option to test framework

---

istioctl/cmd/config_test.go
istioctl/cmd/root.go
istioctl/pkg/clioptions/central.go

Restore the functionality removed in https://github.com/istio/istio/pull/25633
The PR follows the example of _tools/istio-iptables/pkg/cmd/root.go_ setting the defaults in an `init()` so it is guaranteed to occur exactly once during a run.

Move Viper default setting to init()

---

pilot/pkg/model/push_context_test.go
pilot/pkg/xds/bench_test.go
pilot/pkg/xds/debug.go
pilot/pkg/xds/eds.go
pilot/pkg/xds/fake.go

Goals:
* Scope down the set of inputs to the EDS pipeline so it doesn't depend
on proxy
* Compute some things up front to reduce recomputation
* Define a key that can be used for caching EDS responses (future PR)
```
$ benchstat /tmp/{old,new}
name                         old time/op    new time/op    delta
EndpointGeneration/1/100-6      139µs ± 2%     119µs ± 2%  -14.38%  (p=0.008 n=5+5)
EndpointGeneration/10/10-6     67.4µs ± 2%    64.9µs ± 2%   -3.67%  (p=0.016 n=5+5)
EndpointGeneration/100/10-6     472µs ± 4%     472µs ± 6%     ~     (p=1.000 n=5+5)
EndpointGeneration/1000/1-6     708µs ± 6%     684µs ± 9%     ~     (p=0.310 n=5+5)
name                         old alloc/op   new alloc/op   delta
EndpointGeneration/1/100-6     63.7kB ± 0%    57.3kB ± 0%  -10.05%  (p=0.008 n=5+5) …
```

Add endpoint builder to define EDS dependencies

---

tools/certs/Makefile

- fix issues that switching cluster fails to generate correct certs.
- fix issue that if old certs exists will prevent new certs generated
- add function to support define `ISTIO_NAMESPACE` in case istio is not installed into `istio-system` namespace. 
- remove unused intermediate files

enhance and fix Makefile to generate certs

---

pkg/test/framework/components/istio/istio.go
prow/integ-suite-kind.sh
tests/integration/multicluster/helper.go
tests/integration/multicluster/multimaster/main_test.go
tests/integration/multicluster/remote/main_test.go
tests/integration/pilot/istioctl_test.go
tests/integration/pilot/main_test.go
tests/integration/pilot/mirror_test.go
tests/integration/pilot/routing_test.go
tests/integration/tests.mk

Split the first few commits out from https://github.com/istio/istio/pull/24549 as a first step in breaking up that PR
This PR shouldn't change the behavior of any tests. It just allows us to run `integ-pilot-multicluster-tests_istio` without the whole suite being skipped and incrementally convert pilot tests in separate PRs. 
[ ] Docs
[ ] Networking
[ ] Security

tests: allow pilot suite to run with more than one cluster

---

pkg/bootstrap/config.go
pkg/bootstrap/option/instances.go
pkg/envoy/proxy.go
releasenotes/notes/add-sni-host.yaml
tools/packaging/common/envoy_bootstrap.json

To enable SNI/TLS based routing to function properly, for example:
```
kind: Gateway
metadata:
name: istiod3
namespace: istio3
spec:
selector:
istio: ingressgateway
servers:
- port:
number: 15012
protocol: tls
name: TLS-XDS
tls:
mode: PASSTHROUGH
hosts:
- "istiod3.mycluster.appdomain.cloud"
---
metadata:
name: istiod3-vs
namespace: istio3
spec:
hosts:
- istiod3.mycluster.appdomain.cloud
gateways:
- istiod3
tls:
- match:
- port: 15012
sniHosts:
- istiod3.mycluster.appdomain.cloud
route:
- destination:
host: istiod
port:
number: 15012
```
cc @howardjohn @irisdingbj @nmittler @frankbu 
[ ] Docs
[ ] …

add discovery host as sni host to xds-grpc cluster

---

galley/pkg/config/analysis/analyzers/analyzers_test.go
galley/pkg/config/analysis/analyzers/deprecation/deprecation.go
galley/pkg/config/analysis/analyzers/testdata/deprecation.yaml
pkg/config/schema/metadata.gen.go
pkg/config/schema/metadata.yaml
releasenotes/notes/24471.yaml

For https://github.com/istio/istio/issues/24471
Incorporates the mixer deprecations into `istioctl analyze`
This PR also introduces warnings if the user has CRDs for RBAC that should no longer be present.

Analyze deprecated crs

---

pkg/test/framework/logging.go
pkg/test/framework/suite.go

This may just be personal preference, but in my opinion the debug
logging obscures the logs we want to look for during failures, and I
often find people who are not experts in the integration tests being
confused by them.
Up until ~1 month ago we did not have debug logging, which I think was
the right move personally.
[ ] Docs
[ ] Networking
[ ] Security

Disable debug logging in CI

---

pkg/kube/util.go

the kubeconfig env var is checked first prior to use in cluster k8s config.
tested this pretty extensively with central istiod single cluster: https://github.com/istio/istio/wiki/Central-Istiod-single-cluster-steps
[ ] Docs
[ x  ] Networking
[ ] Security

update cluster loading rule comment

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_builder.go
pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
pilot/pkg/xds/eds.go

Follow-up to discussion here: https://github.com/istio/istio/pull/25588#discussion_r456217149
Call applyTrafficPolicy once per cluster to avoid leftover cluster configuration settings from previous calls not getting properly set/unset.
includes a bug fix for DestinationRules of the following type:
```
metadata:
name: bookinfo-ratings
spec:
host: "*.example.org"
trafficPolicy:
tls:
mode: MUTUAL,
clientCertificate: "/defaultCert.pem"
privateKey: "/defaultPrivateKey.pem"
caCertificates: "/defaultCaCert.pem"
subsets:
- name: foobar
trafficPolicy:
portLevelSettings:
port:
number: 8080
```
Cluster `outbound|8080|foobar|foo.example.org` was actually getting configured with a TLS …

Call ApplyTrafficPolicy once per cluster

---

tests/integration/pilot/vm/README.md

This adds the first README.md to the VM testing for others who would like to continue writing and extending VM tests.
[ ] Docs
[ ] Networking
[ ] Security

Documentation to extend VM tests

---

pkg/test/framework/components/echo/echoboot/echoboot.go
tests/integration/multicluster/cluster_local.go
tests/integration/multicluster/reachability.go
tests/integration/multicluster/telemetry.go
tests/integration/operator/switch_cr_test.go
tests/integration/pilot/ingress/ingress_test.go
tests/integration/pilot/istioctl_test.go
tests/integration/pilot/locality/distribute_test.go
tests/integration/pilot/locality/failover_test.go
tests/integration/pilot/locality/prioritized_test.go
tests/integration/pilot/mirror_test.go
tests/integration/pilot/revisions/revisions_test.go
tests/integration/pilot/vm/vm_test.go
tests/integration/pilot/vm/vm_traffic_shifting_test.go
tests/integration/security/authorization_test.go
tests/integration/security/filebased_tls_origination/destination_rule_tls_test.go
tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go
tests/integration/security/jwt_test.go
tests/integration/security/mtls_healthcheck_test.go
tests/integration/security/mtlscert_pluginca_securenaming/mtlscert_pluginca_securenaming_test.go
tests/integration/security/pass_through_filter_chain_test.go
tests/integration/security/sds_egress/sds_istio_mutual_egress_test.go
tests/integration/security/sds_ingress/util/util.go
tests/integration/security/sds_tls_origination/util/util.go
tests/integration/security/sds_vault_flow/sds_vault_flow_test.go
tests/integration/security/util/reachability/context.go
tests/integration/telemetry/dashboard_test.go
tests/integration/telemetry/outboundtrafficpolicy/helper.go
tests/integration/telemetry/stackdriver/vm/vm_test.go

This function never fails, so adjust the API to express this

echoboot.NewBuilder cannot return error

---

prow/integ-suite-kind.sh

This is to avoid duplicating this logic on every job as we add a
https://github.com/istio/test-infra/pull/2832 build cache to the jobs
[ ] Docs
[ ] Networking
[ ] Security

Avoid caching test results for integ tests

---

tests/integration/pilot/cni/cni_test.go

Fixing broken CNI tests in release-1.6 branch, by changing CNI image tags from latest to 1.6-dev in tests.

[release-1.6] Fixing broken CNI tests

---

tests/integration/pilot/cni/cni_test.go

Fixing broken CNI tests in release-1.5 branch, by changing CNI image tags from latest to 1.5-dev in tests.

[release-1.5] Fixing broken CNI tests

---

istioctl/pkg/install/pre-check.go
istioctl/pkg/install/pre-check_test.go
releasenotes/notes/min-k8-ver-for-1.8.yaml

The minimum supported k8 version for `Istio 1.8` is `1.17-1.19` (3 versions). Ref: https://github.com/istio/istio/pull/24134#issuecomment-634690848
For `1.7` support.
https://github.com/istio/istio/pull/24167
https://github.com/istio/istio.io/pull/7422

Update min k8 supported version for istio 1.8

---

pkg/test/echo/server/forwarder/protocol.go

In negative testing this ends up stalling for 2s (connect timeout),
which adds up quickly. Instead, we can stop blocking and just let the
call fail when the call is made. The end result is the same without a
huge delay.
This brings each instance of the reachability tests (which we have many
of) from 20s to 2s
[ ] Docs
[ ] Networking
[ ] Security

No Block on gRPC connection

---

pkg/test/framework/components/istio/operator.go

`manifest apply` command is deprecated and will be removed in 1.7
[ ] Docs
[ ] Networking
[ ] Security

use install to replace deprecated manifest apply command for integration test.

---

tests/integration/pilot/main_test.go
tests/integration/pilot/mirror_test.go
tests/integration/pilot/testdata/traffic-mirroring-template.yaml

Builds on #25636
This will be a bit cleaner once the refactoring in
https://github.com/istio/istio/pull/25754 lands
This cuts runtime from 30s to 10s. The addition of `external` will be used in another test as well, so its generally useful.

Share echo instances in mirroring tests

---

pilot/pkg/serviceregistry/kube/controller/controller_test.go
pilot/pkg/serviceregistry/kube/controller/fake.go
pilot/pkg/serviceregistry/kube/controller/pod_test.go
pilot/pkg/xds/fake.go
pilot/pkg/xds/xds_test.go
pkg/kube/client.go

Expands on https://github.com/istio/istio/pull/25655 to allow testing kube serviceregistry logic
- FakeDiscoveryServer uses an aggregate service registry with ServiceEntry and Kube
- Kube registry uses faked client with hardcoded objects
- MeshNetworks test uses kube registry
The following coverage via xds_test was 0. Converting only one test, MeshNetworks, gets us some solid coverage of the kube regsitry. 
file | statistics
-- | --
controller.go | 34.5% statements
endpoint_builder.go | 90.9% statements
endpointcontroller.go | 60.5% statements
endpoints.go | 23% statements
endpointslice.go | 0% statements
fake.go | 43.1% statements
multicluster.go | 0% statements
namespacecontroller.go | 0% statements
network.go | 40% statements
pod.go | 20.5% statements
util.go | 26.8% statements
To get …

test kube ServiceRegistry in xds_test

---

releasenotes/notes/psfile.yaml

In #25627 there was a typo of `istioctlS` instead of `istioctl`.  This
resolves that as well as ensuring the file ends with a newline (as all
of the other release notes do).
[X] Docs
[ ] Networking
[ ] Security

typo: Fix typo in psfile.yaml release note

---

tests/integration/pilot/ingress_test.go

Regression from https://github.com/istio/istio/pull/25819 that fails in our old k8s version postsubmit tests

Skip Ingress test on unsupported k8s versions

---

pilot/pkg/serviceregistry/kube/controller/fake.go

For the kube Controller there is a race between Services being loaded and Endpoints being built. This was causing test flakes, fixes https://github.com/istio/istio/issues/25863.
```
$ go test -run TestMeshNetworking -count=20 -race
...
PASS
ok      istio.io/istio/pilot/pkg/xds    11.519s
$ go test -run TestMeshNetworking -count=100
...
PASS
ok      istio.io/istio/pilot/pkg/xds    16.917s
```
This PR is a workaround that waits for the related service before force-syncing the endpoint. Should we look into handling this elsewhere by retrying the endpoint event or attempting to wait for the service? Maybe just on controller init? 
https://github.com/istio/istio/blob/78fa9a988acdda70785b0dd5b1ea1b30cb89e1bc/pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go#L96
[ ] Configuration …

fix kubecontroller flake in XDS tests

---

pilot/pkg/status/state.go

Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>
Go uses the same address variable while iterating in a range, so use a copy when using its address, otherwise we end up using the last value for all iterations.
[ ] Docs
[ ] Networking
[ ] Security
[X ] Developer Infrastructure

[pilot] ReconcileStatuses: fix iterator range issue

---

pilot/pkg/model/sidecar_test.go

Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>
Go uses the same address variable while iterating in a range, so use a copy when using its address, otherwise we end up using the last value for all iterations.
[ ] Docs
[ ] Networking
[ ] Security
[X ] Developer Infrastructure

[pilot/sidecar_test] TestSidecarOutboundTrafficPolicy: fix range iterator issue

---

pilot/pkg/xds/bench_test.go

Fixes output below:
```
~/g/s/i/istio ❯❯❯ go test ./pilot/pkg/xds -bench=Generation -run='XXX'  -count='5
2020-07-27T20:34:54.767663Z     info    Initializing Kubernetes service registry "Kubernetes"
goos: darwin
goarch: amd64
pkg: istio.io/istio/pilot/pkg/xds
BenchmarkRouteGeneration/gateways-12            2020-07-27T20:34:54.979403Z     info    Initializing Kubernetes service registry "Kubernetes"
25          45712393 ns/op              2733 kb/msg             1001 resources/msg
BenchmarkRouteGeneration/gateways-12            2020-07-27T20:34:56.281291Z     info    Initializing Kubernetes service registry "Kubernetes"
2020-07-27T20:34:56.485913Z     info    Initializing Kubernetes service registry "Kubernetes"
24          48634769 ns/op              2733 kb/msg             1001 …
```

disable logging in benchmarks

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go

The solution in https://github.com/istio/istio/pull/25517 was slightly incomplete. As it doesn't avoid TLS generation error later in the function. Right now if 1000 DR are deployed with credentials, we'll see 1000 Errors in istiod logs regarding absence of tls.privatekey and tls.clientcert

Avoid Sidecar Cluster Config Generation for UpstreamClusters when CredentialName is set

---

pilot/pkg/config/kube/gateway/controller.go

Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>
Go uses the same address variable while iterating in a range, so use a copy when using its address, otherwise we end up using the last value for all iterations.
[ ] Docs
[ ] Security
[X ] Developer Infrastructure

[pilot/gateway] controller: fix range iterator issue

---

pilot/pkg/serviceregistry/kube/controller/controller_test.go
pilot/pkg/serviceregistry/kube/controller/pod_test.go

This has been flaky for literally a year. I am pretty confident this
will fix the issues once and for all. This expands our previous hack to
skip on node update failure as well.
Without pr: `2142 runs so far, 6 failures`. With PR: `1506 runs so far, 0 failures`

Fix pod locality flakes

---

prow/lib.sh

fixes a small issue on zsh `install_metallb:9: no matches found: .[0].IPAM.Config[0].Subnet` when trying to 
```
source prow/lib.sh
install_metallb $KUBECONFIG
```
[ ] Docs
[ ] Networking
[ ] Security

quote jq path in prow metallb setup

---

pkg/test/echo/server/endpoint/grpc.go
pkg/test/echo/server/forwarder/http.go
pkg/test/echo/server/forwarder/protocol.go

Currently, every ForwardEcho request leaks a connection. I originally
thought we should fix it to reuse connections, but I think its probably
best we don't, as I worry that would lead to cases where we are using an
old connection that has different properties (strict vs plain text, for
example) that leads to unexpected test results
[ ] Docs
[ ] Networking
[ ] Security

Close connections in echo

---

manifests/profiles/demo.yaml
operator/pkg/apis/istio/v1alpha1/validation/validation.go
operator/pkg/apis/istio/v1alpha1/validation/validation_test.go

Partial backport of a massive PR in master. This fixes the deprecation
warning when installing with demo profile, and adds a regression test.
this has no impact on the generated manifests; the option does nothing.
[ ] Docs
[ ] Networking
[ ] Security

[release-1.7] Fix deprecated setting in demo profile

---

tests/integration/pilot/main_test.go

This fixes the post submit failure, while we debug why VM tests fail with wasm.
There was no cheap way to disable this just for VM test and keep it for the rest since everything uses the same testMain.

Disable wasm test in VM

---

.github/pull_request_template.md

This pull request adds a checkbox to the pull request template that can be checked if the pull request doesn't have any user facing changes.  If this checkbox is checked, the release-notes-none label will be applied and the PR will not ask for release notes. This will allow anyone to skip adding a PR to release notes even if they don't have permission to add labels. 
Related to: https://github.com/istio/bots/pull/239/files
This will look like: 
And to help us figure out who should review this PR, please
[ ] Docs
[ ] Networking
[ …

Add release-notes-none autolabel

---

pilot/pkg/serviceregistry/kube/controller/controller_test.go

This ensures we are actually getting the right pod, and populating the
correct service account information. It doesn't fix any bug - the code
works today, just expanding the testing
[ ] Docs
[ ] Networking
[ ] Security

Expand endpoints before pod test to check pod

---

pkg/test/framework/components/istio/operator.go
tests/integration/multicluster/base/main_test.go
tests/integration/multicluster/centralistio/main_test.go

Part of #25933. The intent is to next add another multicluster test that doesn't use meshExpansion
[ ] Docs
[X] Networking
[ ] Security

Move meshExpansion to ControlPlaneValues in tests

---

pilot/pkg/serviceregistry/kube/controller/util.go
pilot/pkg/serviceregistry/kube/conversion.go
pilot/pkg/xds/xds_test.go
releasenotes/notes/fix-nodeport-meshnetwork.yaml

The following skips building nodePort mappings if the nodeSelector annotation is set:
https://github.com/istio/istio/blob/312ac4e0c37f0339c4f6b1608ee594d059ff7944/pilot/pkg/serviceregistry/kube/conversion.go#L121
Then when we decide whether or not to grab node addresses for the service, we make sure it _is_ set:
https://github.com/istio/istio/blob/07232fcb2989492f68b76f92c4ac24c3ff986f1f/pilot/pkg/serviceregistry/kube/controller/util.go#L194
IIUC this prevents actually using these NodePort services for meshNetworks gateways. Either the first or second check should be changed to match the other. I've added a test to validate things are built properly. The test fails without the fix. Do we expect this annotation to be set on all IGW? 
The [new tests …

fix NodePort services for meshNetworks gateway

---

pilot/pkg/xds/discovery.go
pilot/pkg/xds/simple.go

Moves v2 registration to a separate function which is invoked only for gRPC.
[ ] Docs
[ ] Security

move v2 registration out of main path

---

docker/Dockerfile.base
istioctl/pkg/util/configdump/listener.go
manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
manifests/charts/istiod-remote/files/injection-template.yaml
pilot/pkg/networking/core/v1alpha3/dns_listener.go
pkg/test/framework/components/echo/kube/deployment.go
pkg/test/framework/components/echo/kube/instance.go
releasenotes/notes/dns-capture.yaml
tools/istio-iptables/pkg/cmd/run.go
tools/istio-iptables/pkg/cmd/run_test.go

Note: compared to master, dns capture for all k8s pods (in tests)
has been disabled in this branch.
This PR contains fixes to iptables setups that currently exists in release-1.7
for the DNS capture functionality.
There will be another followup PR that will remove the ndots change as well.

[manual cherry-pick] fixing dns resolution issues (#25964)

---

pilot/cmd/pilot-agent/main.go
pkg/istio-agent/sds-agent.go
pkg/security/security.go
security/pkg/credentialfetcher/fetcher.go
security/pkg/credentialfetcher/fetcher_test.go
security/pkg/credentialfetcher/plugin/gce.go
security/pkg/credentialfetcher/plugin/mock.go
security/pkg/nodeagent/cache/mock/secretcache_mock.go
security/pkg/nodeagent/cache/secretcache.go
security/pkg/nodeagent/cache/secretcache_test.go
security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient_test.go
security/pkg/nodeagent/sds/sdsservice.go
security/pkg/nodeagent/test/setup.go
security/pkg/stsservice/test/setup.go
security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin.go
security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin_test.go
security/pkg/stsservice/tokenmanager/sts_test.go
security/pkg/stsservice/tokenmanager/tokenmanager.go

* Add credential fetcher in istio agent.
Add credential fetcher in istio agent. Credential fetcher fetches platform specific workload credential, which is used by istio agent to provisioning certificates for workloads.

[manual cherry-pick] Add credential fetcher in istio agent (#25614)

---

pilot/pkg/bootstrap/configcontroller.go
pilot/pkg/bootstrap/server.go
pilot/pkg/bootstrap/servicecontroller.go
pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/multicluster.go
pilot/pkg/xds/ads_test.go
pilot/pkg/xds/cds_test.go
pilot/pkg/xds/debug.go
pilot/pkg/xds/debug_test.go
pilot/pkg/xds/discovery.go
pilot/pkg/xds/discovery_test.go
pilot/pkg/xds/eds_sh_test.go
pilot/pkg/xds/eds_test.go
pilot/pkg/xds/fake.go
pilot/pkg/xds/init_test.go
pilot/pkg/xds/lds_test.go
pilot/pkg/xds/rds_test.go
pkg/adsc/adsc.go

Currently, pilot tests generally spin up a full bootstrap.Server, which has a lot of overhead. This changes to use the minimal fake server, using an in memory buffcon listener
Additionally, there are various fixes for tests - comments inline
Before: 80s
After: 35s (still way too long)

Pilot unit test improvements

---

galley/pkg/config/analysis/analyzers/all.go
galley/pkg/config/analysis/analyzers/analyzers_test.go
galley/pkg/config/analysis/analyzers/destinationrule/ca-certificates.go
galley/pkg/config/analysis/analyzers/testdata/destinationrule-compound-mutual-simple.yaml
galley/pkg/config/analysis/analyzers/testdata/destinationrule-compound-simple-mutual.yaml
galley/pkg/config/analysis/analyzers/testdata/destinationrule-mutual-destination.yaml
galley/pkg/config/analysis/analyzers/testdata/destinationrule-mutual-port.yaml
galley/pkg/config/analysis/analyzers/testdata/destinationrule-simple-destination.yaml
galley/pkg/config/analysis/analyzers/testdata/destinationrule-simple-port.yaml
galley/pkg/config/analysis/analyzers/testdata/destinationrule-with-ca.yaml
galley/pkg/config/analysis/msg/messages.gen.go
galley/pkg/config/analysis/msg/messages.yaml
releasenotes/notes/dr-analyzer.yaml

#Ref: https://github.com/istio/istio/issues/25652
Cherrypick to 1.6 and 1.5(if analyzer exists)
edit: Analyzer exists in 1.5, so we can cherrypick to 1.5 too

DestinationRule Analyzer against no caCertificates

---

pilot/pkg/model/config_test.go
pkg/test/echo/client/client.go
pkg/test/echo/common/util.go

fix TestReachability flake
I have seen it many times, here is one 
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/26058/integ-security-k8s-tests_istio/17637
```
2020-08-03T06:24:20.683349Z	info	tf	  [ 0]                        vm-v1-67bb7d5cf5-6j994         Running (Ready)
2020-08-03T06:24:20.683758Z	info	tf	  [ 0]                          a-v1-d476f5469-sk9q8         Running (Ready)
TestReachability: context.go:111: initialize instances: 1 error occurred:
* initialize TestReachability/[*kube.instance-2]: grpc client: context deadline exceeded
2020-08-03T06:24:21.054546Z	info	tf	=== DONE (failed):  Test: 'security[TestReachability] (21.119566006s)' ===
2020-08-03T06:24:21.054571Z	error	tf	=== Dumping Namespace reachability-22-85702 State...
--- FAIL: TestReachability …
```

Increase grpc connection timeout

---

istioctl/pkg/validate/validate.go

We shouldn't deprecate `istioctl validate`, because it does some things that analyzers can't yet do, such as strict YAML validation.
Resolves https://github.com/istio/istio/issues/24332 .
We still want to remove it, but not in 1.7, and maybe not in 1.8.

Don't claim 'istioctl validate' is deprecated

---

pilot/pkg/xds/eds_test.go

Currently we wait for EDS only, which means some tests may fail later
since they get an RDS/LDS update when they are expecting EDS update. We
should wait for the full push to complete first. Ran this 100x locally
without fail
[ ] Docs
[ ] Networking
[ ] Security

Fix EDS tests

---

pilot/pkg/bootstrap/configcontroller.go
pilot/pkg/bootstrap/multicluster.go
pilot/pkg/bootstrap/server.go
pilot/pkg/bootstrap/servicecontroller.go
pilot/pkg/xds/lds_test.go
pilot/pkg/xds/simple_test.go

Rename `EnvoyXdsServer` -> 'DiscoveryServer` as it is not just for Envoy now.
[ ] Docs
[ Z] Networking
[ ] Security

rename EnvoyXdsServer to XDSServer

---

pilot/pkg/serviceregistry/aggregate/controller.go
pilot/pkg/serviceregistry/kube/controller/fake.go
pilot/pkg/xds/fake.go
pilot/pkg/xds/xds_test.go

Fixes #26048
go test with -race -count=50 passes. 
* The global push context needs to be reinitialized after the force-sync. 
* it passes sometimes because ConfigUpdate calls Push which re-init PushContext but debounce may delay that. If theres a way to check that debounce has settled we could do that instead of `InitContext`. 
* Cleaned up the ForceResync to check all resources. This was not necessary to fix the flake but may prevent future ones. 
* Fix race in aggregate controller for merging services across multiple registries
[ ] Docs
[X] Networking
[ ] Security
Please check any …

fix mesh network flakes

---

galley/pkg/config/analysis/local/analyze.go
galley/pkg/config/analysis/local/analyze_test.go

We are using analyzers but its triggered directly from inside our code
as opposed to istioctl. Since the resources are already parsed, it does not
make sense to initiate a kube in memory source (that requires YAML strings).
Added the in-memory source as a source for the analyzer so that external
code using the analyzer as a library can import it.
[ ] Docs
[ ] Networking
[ ] Security
[x ] Does not have any changes that may affect Istio users.

Add pure in-memory analyzer source

---

pkg/test/framework/components/istio/config.go
pkg/test/framework/components/istio/operator.go
samples/istiod-gateway/istiod-gateway.yaml
tests/integration/multicluster/base/main_test.go
tests/integration/multicluster/centralistio/main_test.go
tests/integration/pilot/main_test.go
tests/integration/security/main_test.go
tests/integration/telemetry/stackdriver/vm/main_test.go

Part of #25933 and based on https://github.com/nmittler/istio/commit/09fbb1a4d89310b343e394cc1658f95b368c3219
The sample is meant to be used in docs on how to expose istiod through ingress for multicluster and VM setup
[X] Docs
[ ] Networking
[ ] Security

Create code sample for exposing istiod through ingress and use it in tests

---

tests/integration/pilot/vm_test.go

This PR tries to fix the VM post-submit tests so that the instances could be deployed with different images. Currently the images are used only as the testcase name. 
[ ] Docs
[ ] Networking
[ ] Security

Fix: VM post-submit test should be deployed with each image

---

istioctl/cmd/kubeuninject.go

If you're using IstioCNI and trying Istioctl remove-from-mesh, you will find that all istio-related stuff is removed from the deployment manifest except for the init-container. This PR will fix that
[ ] Docs
[ ] Networking
[ ] Security

remove istio-validation container when running istioctl rm

---

pilot/pkg/networking/core/v1alpha3/route/route.go
pilot/pkg/networking/core/v1alpha3/route/route_test.go

This PR https://github.com/istio/istio/pull/25492 has stopped sending max program size for older proxies. However Envoy via this PR https://github.com/envoyproxy/envoy/pull/11187 is still enforcing the max program size via run time keys (defaults to 100). It looks like we need to set the max program size via runtime key or find a better solution otherwise this will break customers. So for now I am reverting that change and setting the max program size back. We can think about a better option.
https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/matcher/v3/regex.proto.html#type-matcher-v3-regexmatcher-googlere2
[ ] Docs
[ ] Security
[ ] User …

add max program size back

---

mixer/pkg/attribute/envoyProtoBag.go
operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-policy/templates/config.yaml

Added a new attribute to distinguish Envoy Service Access Logs from Mixer Report ones for ease of use when migrating between the two.
Since destination.uid isn't provided by ALS, it default includes destination.ip additionally for dispatcher preprocess to create bags correctly.
@bianpengyuan 
[ ] Docs
[ ] Networking
[ ] Security

[release-1.7] Extra Envoy Access Log Attribute and Bag Preprocess Fix

---

pilot/pkg/serviceregistry/kube/controller/network.go

When we update meshNetworks in the `istio` we update some fields on the controller that set the network for endpoints, but the network is only set when we first process the k8s events for these resources. The expectation is that you could change the config map and have the endpoints regenerated and pushed with the proper network. 
This PR is a bit hacky - it just reloads everything from Kubernetes. If this works then we can change it to be more fine-grained. 
Note: this problem would not effect purely label-based networks config; the design we talked about in networking-wg will trigger these updates properly. 
[ ] Docs
[X] Networking
[ ] Security
[ ] User …

reload services and endpoints when networks change

---

manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.7.yaml
manifests/charts/istiod-remote/templates/telemetryv2_1.7.yaml
pkg/test/framework/components/stackdriver/kube.go
tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go
tests/integration/telemetry/stackdriver/testdata/client_tcp_connection_count.json.tmpl
tests/integration/telemetry/stackdriver/testdata/server_tcp_connection_count.json.tmpl
tests/integration/telemetry/stackdriver/testdata/tcp_server_access_log.json.tmpl

Enable TCP Telemetry v2 export via Stackdriver filter (#25646)
[ ] Docs
[ ] Networking
[ ] Security

[Release-1.7] Enable TCP Telemetry v2 export via Stackdriver filter (#25646)

---

pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/network.go
pilot/pkg/xds/fake.go
pilot/pkg/xds/xds_test.go
pkg/config/mesh/networks_watcher.go

Expands on #26236 
- TestMeshNetworks:
- reuse the fake discovery server for different MeshNetwork configs
- init with empty mesh networks and update on each scenario
- tested with -count 50 and -race, not flaky
- Only need to resync Pods and Endpoints
- Make sure the resync happens before we trigger the force push
[ ] Docs
[X] Networking
[ ] Security

cleanup networks resync and add tests

---

pilot/pkg/serviceregistry/kube/controller/network.go
pilot/pkg/xds/bench_test.go
pilot/pkg/xds/discovery.go
pilot/pkg/xds/fake.go

There is an actual race that we did not have tests covering until recently - we run `reloadNetworkLookup` during init as well as in a handler for networks watcher. It's technically possible that they could race. 
```
PASS
ok      istio.io/istio/pilot/pkg/xds    27.786s
~/g/s/i/i/p/p/xds ❯❯❯ echo !!
go test -count 100 -race -run TestMeshNet
```
Since the last tests I add require updating the global push context, we need to further synchronize access to Env.PushContext in test code that uses FakeDiscoveryServer. Originally, we copied the _first_ version of the push context to the root of the FakeServer, now we want to access the actual one on `Env`, which requires syncrhonization. 
[ ] Docs
[X] Networking
[ ] …

fix race when reloading kube controller networks

---

pkg/test/framework/components/istio/operator.go

This profile is now the same as the default
[ ] Docs
[ ] Networking
[ ] Security

Don't specify remote profile in test framework deploy

---

pilot/pkg/model/context.go
pilot/pkg/model/context_test.go
pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
pilot/pkg/networking/core/v1alpha3/listener_test.go
pilot/pkg/networking/core/v1alpha3/route/route_test.go
pilot/pkg/xds/ads.go
pilot/pkg/xds/cds.go
pilot/pkg/xds/debug.go
pilot/pkg/xds/discovery_test.go
pilot/pkg/xds/eds.go
pilot/pkg/xds/ep_filters_test.go
pilot/pkg/xds/gen2.go
pilot/pkg/xds/internalgen.go
pilot/pkg/xds/lds.go
pilot/pkg/xds/rds.go

This PR
- Moves the `mutex` to `Proxy` from `Connection` where it is only used for protecting proxy changes
- Rename `node` -> `proxy` in `Connection`
- Minor comment fixes
[ ] Docs
[ ] Security

ads: move mutex to proxy

---

pilot/pkg/xds/xds_test.go

Testing xds using mesh networks handlers is still somewhat flaky. This reverts to setting up a new discovery server per meshNetworks config
[ ] Docs
[X] Networking
[ ] Security

dont test reloading meshNetworks in xds_test

---

pilot/cmd/pilot-agent/main.go
pkg/bootstrap/config.go

Get rid of unneeded spiffe stuff, not used now for control plane. Also
break out some methods to get rid of monolith main()
[ ] Docs
[ ] Networking
[ ] Security

Cleanup agent main a bit

---

istioctl/pkg/install/verify.go

Fix description for istioctl verify-install

---

go.mod
pkg/bootstrap/platform/gcp.go

This dep is ~22mb, bloats the binary. See https://github.com/istio/istio/issues/26232

Remove dependency on google.golang.org/api

---

istioctl/cmd/testdata/webhook/example-mutating-webhook-config.yaml
istioctl/cmd/testdata/webhook/example-validating-webhook-config.yaml
manifests/charts/base/files/gen-istio-cluster.yaml
manifests/charts/base/templates/validatingwebhookconfiguration.yaml
manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml
manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/base/templates/validatingwebhookconfiguration.yaml
operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/gen-istio.yaml
operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml
operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/files/gen-istiod-remote.yaml
operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/templates/mutatingwebhook.yaml
operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
operator/cmd/mesh/testdata/manifest-generate/output/flag_output_set_profile.golden.yaml
operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_kubernetes.golden.yaml
pkg/kube/adapter.go
pkg/kube/inject/inject.go
pkg/kube/inject/webhook.go
pkg/kube/inject/webhook_test.go
pkg/webhooks/validation/server/monitoring.go
pkg/webhooks/validation/server/server.go
pkg/webhooks/validation/server/server_test.go
tests/integration/security/webhook/config/galley-webhook.yaml
tests/integration/security/webhook/config/sidecar-injector-webhook.yaml

* add forward compatibility with k8s admissions api v1
* add support for v1 and v1beta1 AdmissionReview versions
* use admission API adapter in validating webhooks
(cherry picked from commit c4a14db008d6546d27b00d7318e3100eda8e2603)
Fixes #26379 
This is a manual cherrypick of PR #26312 
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does not have any changes that may …

add forward compatibility with k8s admissions api v1 (#26312)

---

samples/cross-network-gateway/cross-network-gateway.yaml

Goal is to not mix TLS and mTLS on the same port. TLS is on 443, mTLS is on 15443.
[ ] Docs
[ ] Networking
[ ] Security

Change sample cross-network port to 15443

---

manifests/charts/global.yaml
manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
manifests/charts/istiod-remote/files/gen-istiod-remote.yaml

https://github.com/istio/istio/issues/24379
We've adjusted the default value in pilot runtime to 5s in 1.6.5: https://github.com/istio/istio/commit/0ac15a91fe72dff58f758ef7abad194dd785ba0a, However it does not take effect because it is overridden by protocolDetectionTimeout in global value.
This is already the default in master and release-1.7, this global value has already been removed there.
[ ] Docs
[ ] Networking
[ ] Security

[release-1.6] Increase default proto sniffing timeout to 5s

---

pilot/pkg/bootstrap/server.go
pilot/pkg/serviceregistry/aggregate/controller.go
pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/controller_test.go
pilot/pkg/serviceregistry/kube/controller/fake.go
pilot/pkg/serviceregistry/kube/controller/multicluster.go
pilot/pkg/serviceregistry/kube/controller/pod_test.go
pilot/pkg/serviceregistry/kube/conversion.go
pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
pilot/pkg/xds/ads.go
pilot/pkg/xds/bench_test.go
pilot/pkg/xds/discovery.go
pilot/pkg/xds/fake.go
pilot/pkg/xds/simple.go
pilot/pkg/xds/xds_test.go
pkg/kube/client.go
pkg/kube/secretcontroller/secretcontroller.go
releasenotes/notes/fix-nodeport-meshnetwork.yaml

Needed several of these to deal with merge conflicts, and #25733 is a related change
* ecea62332c - sync initial resources in order when starting registry (#26142)
* ec4543d655 - fix mesh network flakes (#26085)
* d8ec4c4a1a - fix NodePort services for meshNetworks gateway (#25990)
* 87ac93277f - add: ensure envoys can only connect after caches have been synced (#25733)
* 004d8582f6 - test kube ServiceRegistry in xds_test (#25698)
* 7453483b10 - Refactor benchmark test (#25671)
-- I may be able to reduce the amount pulled in but it may not include tests/be tricky to pull the tests in. 
cc @JimmyCYJ 
[ ] Docs
[X] Networking
[ ] Security
[ ] …

cherry pick 1.7: sync initial resources in order when starting registry (#26142)

---

bin/init.sh
manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.7.yaml
manifests/charts/istiod-remote/templates/telemetryv2_1.7.yaml
manifests/profiles/default.yaml
pilot/docker/Dockerfile.proxyv2
tools/istio-docker.mk
tools/packaging/deb/istio.mk

manual cherry-pick of #25589
1. Package precompiled wasm images
2. Create `wasmEnabled` option with default `false`.
This PR *DOES NOT* turn on wasm/v8 for istio stats, but makes it available for experimentation.
@PiotrSikora @kyessenov

Package precompiled wasm files and make option available

---

pilot/pkg/networking/core/v1alpha3/cluster_builder.go
pkg/config/mesh/mesh.go

Sets DNS lookup family to `AUTO`
[ ] Docs
[ ] Networking
[ ] Security

cluster: remove dns lookup family

---

pilot/pkg/features/pilot.go
pilot/pkg/xds/ads.go
pilot/pkg/xds/cds.go
pilot/pkg/xds/debug.go
pilot/pkg/xds/discovery.go
pilot/pkg/xds/lds.go
pilot/pkg/xds/rds.go

Removes
- clusters, listeners and routes in `adsz` endpoint as they should be available in `/config_dump`
- Removes `cdsz` endpoint as it is available in `/config_dump`
[ ] Docs
[ ] Security

remove clusters, listeners and routes in adsz endpoint

---

manifests/charts/istio-telemetry/mixer-telemetry/templates/deployment.yaml

Note: I reopened #25565 and changed the target branch to istio release 1.6
Simply imports missing parts from https://github.com/istio/istio/blob/1.5.8/install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml#L276
.proto and profiles/ have already these values
[ ] Docs
[ ] Networking
[ ] Security

[release-1.6] Add missing telemetry.loadshedding.* options to mixer container args

---

samples/cross-network-gateway/cross-network-gateway.yaml

Goal is to not mix TLS and mTLS on the same port. TLS is on 443, mTLS is on 15443.
[ ] Docs
[ ] Networking
[ ] Security

Cherry-pick 1.7: Change sample cross-network port to 15443 (#26389)

---

security/pkg/credentialfetcher/plugin/gce.go

In the VM, when envoy and sds-agent are running as different uid in the same group, envoy needs read permission 0640 to access the VM credential.
[ ] Docs
[ ] Networking
[x] Security

Grant read permission to component in the same group

---

pkg/test/framework/scope.go
tests/integration/multicluster/base/main_test.go
tests/integration/multicluster/centralistio/main_test.go
tests/integration/multicluster/cluster_local.go
tests/integration/multicluster/helper.go
tests/integration/multicluster/loadbalancing.go
tests/integration/multicluster/reachability.go
tests/integration/multicluster/telemetry.go

We don't currently test that we distribute traffic between all clusters in reachability. I saw failures I _think_ are related to this in https://github.com/istio/istio/pull/25923. 
Also made it so we share echos as much as possible via an Apps struct (similar to pilot tests)
[ ] Docs
[X] Networking
[ ] Security

add cross cluster load balancing test

---

pilot/pkg/bootstrap/monitoring.go
pilot/pkg/bootstrap/server.go
pkg/kube/client.go

Currently debug/monitoring and readiness share the same mux. As a result of that the debug and monitoring handlers are also available on `8080` port. We have a requirement to not expose these debug endpoints outside of pod - So we configured monitoringAddr accodinlgy. But we can not configure httpAddr like that because it exposes readiness probe. This PR splits the mux such that debug/monitoring has one mux used by monitoring server and httpServer has a separate readinessMux.
[ ] Docs
[ ] Security
[ ] Does …

server: split monitoring and readiness mux

---

istioctl/cmd/dashboard_test.go
istioctl/cmd/root.go

The dashboard is graduated a year ago. Docs are already updated to remove `experimental` from `dashboard` commands.
Related:
https://github.com/istio/istio/pull/16571
https://github.com/istio/istio/pull/17824

Dashboard is no longer experimental

---

pilot/pkg/serviceregistry/serviceentry/conversion.go
pilot/pkg/serviceregistry/serviceentry/conversion_test.go
pilot/pkg/serviceregistry/serviceentry/servicediscovery.go

Logic will be:
* If spec.labels is present, use those
* If not, use metadata.labels
Fixes https://github.com/istio/istio/issues/23947

Allow fetching workload labels from WE metadata

---

galley/testdatasets/validation/dataset.gen.go
galley/testdatasets/validation/dataset/networking-v1alpha3-WorkloadGroup-invalid.yaml
galley/testdatasets/validation/dataset/networking-v1alpha3-WorkloadGroup-valid.yaml
go.mod
go.sum
pilot/pkg/config/kube/crdclient/gen/main.go
pilot/pkg/config/kube/crdclient/types.gen.go
pkg/config/schema/collections/collections.gen.go
pkg/config/schema/gvk/resources.gen.go
pkg/config/schema/metadata.gen.go
pkg/config/schema/metadata.yaml

PR to update the istio.io/client-go version as a result of the [changes in client-go](https://github.com/istio/client-go/pull/224) and changes and [changes in api](https://github.com/istio/api/pull/1554). Also included changes to generate the WorkloadGroup schemas properly in istio.io/istio.
Not sure which category this falls under, feel free to edit if necessary.
[ ] Docs
[ ] Networking
[ ] Security

Update istio.io/client-go version (WorkloadGroup changes)

---

pilot/pkg/serviceregistry/serviceentry/conversion.go
pilot/pkg/serviceregistry/serviceentry/conversion_test.go
pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go

This reverts #26405, which is causing test flakes (see https://github.com/istio/istio/issues/26465).
[ ] Docs
[ ] Networking
[ ] Security

Revert "Serviceentry handler optimization (#26405)"

---

pkg/kube/client.go

This is printed in `istioctl ps` when there are no istiod instances.
[ ] Docs
[ ] Networking
[ ] Security

fix error message to use Istiod instead of pilot

---

pilot/pkg/bootstrap/server.go

https://github.com/istio/istio/pull/26481 multiplexes gRPC on plain text port if gRPC port is off. But the place it was added is incorrect. When http server is being initialized, ` s.GRPCListener` will always be nil as it is initialized later. This PR fixes that order.
[ ] Docs
[ ] Security

server: fix multiplexing on plain text port

---

pilot/pkg/model/push_context.go
pilot/pkg/model/push_context_test.go

Fixes https://github.com/istio/istio/issues/25253
Opening for early comments - still need tests.
One thing we may consider is adding a map of only private DR (or maybe even a special case for just root namespace...). This way we can distinguish between `*.local` rules meant as "global" and `exportTo=.` rules meant for istio-system and resolve `NOTE: This does mean that we are effectively giving destination rules in other namespace precedence over private dest rules in the config root namespace`
cc @rshriram @hzxuzhonghu

Fix private destination rules in root namespace

---

pkg/bootstrap/platform/azure.go
pkg/bootstrap/platform/azure_test.go
pkg/bootstrap/platform/discovery.go

Follow up to this [Azure Platform Support](https://github.com/istio/istio/pull/24995).
Main changes are allowing the prefix to be set rather than hardcoded to "azure_", and lowering logging to a debug level so it doesn't create a warning when running discovery on a non-Azure platform.

Azure platform optional prefix and logging level followup

---

pkg/test/framework/components/istio/operator.go
pkg/test/framework/components/namespace/kube.go
pkg/test/framework/resource/dumper.go
pkg/test/framework/runtime.go
pkg/test/framework/scope.go
pkg/test/framework/suite.go
pkg/test/framework/testcontext.go
tests/integration/pilot/analyze_test.go
tests/integration/pilot/ingress_test.go
tests/integration/pilot/istioctl_test.go
tests/integration/pilot/mirror_test.go
tests/integration/pilot/routing_test.go
tests/integration/pilot/validation_test.go

When a single test in a suite fails, the valuable information about the state of pods, etc. isn't dumped until the entire suite finishes. For tests that share resources at the suite level, config that may have affected the dump may be cleaned up before we dump the state. 
For example, in the link below most of the meaningful information is under _suite_context/. The individual tests only show the config that was applied rather than how it affected Envoy config.
https://gcsweb.istio.io/gcs/istio-prow/pr-logs/pull/istio_istio/25923/integ-pilot-multicluster-tests_istio/84/artifacts/pilot-12fd1f21ee014570b4e0b1e99/
With this change, the subtest directory will have a dump from before cleanup (assuming cleanup doesn't rely on defer):
https://gcsweb.istio.io/gcs/istio-prow/pr-logs/pull/istio_isti …

test framework: dump entire suite when a single test fails

---

pkg/test/framework/scope.go
pkg/test/framework/testcontext.go

Overriding the `*testing.T`'s `Cleanup` as well as adding our own `CleanupOrFail`
WhenDone will not be skipped by `--istio.test.nocleanup`. `ctx.Cleanup` or `ctx.CleanupOrFail` should be used for cleanup that can be safely skipped without affecting other tests.
[ ] Docs
[ ] Networking
[ ] Security

test framework: separate method for skippable test-level cleanup

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/xds/testdata/benchmarks/empty.yaml

```
name                       old time/op        new time/op        delta
ClusterGeneration/empty-8        4.84ms ± 0%        4.28ms ± 0%   ~     (p=1.000 n=1+1)
name                       old alloc/op       new alloc/op       delta
ClusterGeneration/empty-8        1.93MB ± 0%        1.71MB ± 0%   ~     (p=1.000 n=1+1)
name                       old allocs/op      new allocs/op      delta
ClusterGeneration/empty-8         23.4k ± 0%         21.0k ± 0%   ~     (p=1.000 n=1+1)
```

Add auto mtls to benchmark tests and improve memory

---

pkg/envoy/admin.go

See https://github.com/envoyproxy/envoy/pull/11639/files
The old draining behavior: GOAWAY/connection: close all existing
connections, reject all new connections. This means if a connection is
established (because of slow propogationo of endpoint updates or similar
issues), it will be closed. This connection actually has a chance to
succeed, if the app has not shut down yet, or for ingress its very
likely to be ok as we know envoy is still running.
The new behavior will still goaway existing connections, but new
connections are accepted
Along with bumping up the drain to 10s, I have gotten 100% success with https://github.com/istio/istio/issues/26524; prior to this it fails every rollout

Drain listeners gracefully

---

galley/testdatasets/validation/dataset.gen.go
galley/testdatasets/validation/dataset/networking-v1alpha3-WorkloadGroup-invalid.yaml
galley/testdatasets/validation/dataset/networking-v1alpha3-WorkloadGroup-valid.yaml
tests/integration/pilot/validation_test.go

It is run in parallel but due to go loop semantics, we just test the
last element in the loop! As a result an invalid config (had namespace
in it) was merged, which meant the test failed ~1/10 times. This fixes
that and cleans up the logging a bit
[ ] Docs
[ ] Networking
[ ] Security

Fix validation test errors

---

pilot/pkg/bootstrap/istio_ca.go
pilot/pkg/bootstrap/server.go
pilot/pkg/xds/authentication.go
pilot/pkg/xds/discovery.go
security/pkg/server/ca/server.go
security/pkg/server/ca/server_test.go

This change adds JWT authenticator to the XDS server. As part of this, there is a lot of refactoring of the CA server so we can split out the authenticators part and share the same constructor for the authenticators. There is a ton of dead code removed in the process

Add JWT authentication to XDS server

---

pilot/pkg/xds/ads.go

Minor change to xds send logic to close the `errChan` and handle `t.Stop` properly
[ ] Docs
[ ] Security

handle timeout properly in xds send

---

Makefile.core.mk

It's needed for common/scripts/report_build_info.sh
See https://github.com/istio/common-files/pull/300

Export VERSION variable

---

istioctl/pkg/writer/envoy/configdump/listener.go

We use routes for these only because they are HTTP - they are
essentially just forwarding to a cluster, similar to TCP
```
ADDRESS PORT  MATCH                                      DESTINATION
0.0.0.0 15006 Trans: tls; App: HTTP TLS; Addr: 0.0.0.0/0 Inline Route: /*
0.0.0.0 15006 Trans: tls; App: HTTP TLS; Addr: ::0/0     Inline Route: /*
0.0.0.0 15006 ALL                                        Inline Route: /*
0.0.0.0 15006 Trans: tls; Addr: ::0/0                    InboundPassthroughClusterIpv6
0.0.0.0 15006 Trans: tls; Addr: 0.0.0.0/0                InboundPassthroughClusterIpv4
ADDRESS PORT  MATCH                                      DESTINATION
0.0.0.0 15006 Trans: tls; Addr: ::0/0                    InboundPassthroughClusterIpv6
0.0.0.0 15006 Trans: tls; App: HTTP TLS; Addr: ::0/0 …
```

Show cluster for single cluster route destinations

---

istioctl/pkg/writer/envoy/configdump/listener.go

AddressSuffix is also removed since its never used by Istio and
unimplemented by Envoy to clean up the code a bit
```
ADDRESS PORT  MATCH                                      DESTINATION
0.0.0.0 15006 Trans: tls; App: HTTP TLS; Addr: 0.0.0.0/0 Inline Route: /*
0.0.0.0 15006 Trans: tls; App: HTTP TLS; Addr: ::0/0     Inline Route: /*
0.0.0.0 15006 ALL                                        Inline Route: /*
0.0.0.0 15006 Trans: tls; Addr: ::0/0                    InboundPassthroughClusterIpv6
0.0.0.0 15006 Trans: tls; Addr: 0.0.0.0/0                InboundPassthroughClusterIpv4
ADDRESS PORT  MATCH                                      DESTINATION
0.0.0.0 15006 Trans: tls; App: HTTP TLS; Addr: 0.0.0.0/0 Inline Route: /*
0.0.0.0 15006 Trans: tls; App: HTTP TLS; Addr: ::0/0     Inline Route: /* …
```

Fix missing port for proxy-config listener

---

pilot/pkg/features/pilot.go
pilot/pkg/xds/ads.go
pilot/pkg/xds/ads_test.go
pilot/pkg/xds/bench_test.go
pilot/pkg/xds/debug.go
pilot/pkg/xds/discovery.go
pilot/pkg/xds/eds.go
pilot/pkg/xds/endpoint_builder.go
pilot/pkg/xds/fake.go
pilot/pkg/xds/xds_cache.go
pilot/pkg/xds/xds_cache_test.go
pilot/pkg/xds/xds_test.go
pilot/test/xdstest/extract.go
pkg/adsc/adsc.go
releasenotes/notes/eds-cache.yaml

This is on by default for tests only, will probably be disabled prior to merge
The idea here is to cache EDS responses. Cache invalidation is on a per hostname basis.
Likely bugs that need to be considered before turning this on:
* Probably leaks memory
* Probably some edge cases where we do not invalidate properly
Note: the reason this PR is so small is I had a PR a couple weeks ago preparing for this: #25598
Performance impact on a cluster with 2.5k pods with a split of 1, 5, and 25 replica services:
CPU: 5 vCPU -> 1.5 vCPU
Heap: no change
Stack, interestingly, goes from 70mb -> 120mb. Not sure why, the pprof will not show stack usage

Add a cache for EDS responses

---

pkg/test/framework/components/echo/common/call.go
pkg/test/framework/components/echo/echo.go
pkg/test/framework/components/echo/kube/deployment.go
pkg/test/framework/components/echo/kube/instance.go
pkg/test/util/retry/retry.go
tests/integration/pilot/istioctl_test.go
tests/integration/pilot/main_test.go
tests/integration/pilot/routing_test.go

As seen here, server first protocols are broken in most cases. This acts
as a baseline for future improvements - currently working on a design
doc that I hope will make most of these green.
[ ] Docs
[ ] Networking
[ ] Security

Add testing for server first protocols

---

pkg/test/framework/components/istio/config.go
pkg/test/framework/components/istio/operator.go
tests/integration/multicluster/base/main_test.go
tests/integration/multicluster/centralistio/main_test.go
tests/integration/pilot/main_test.go
tests/integration/security/main_test.go
tests/integration/telemetry/stackdriver/vm/main_test.go

Cleanup after #26091. Adding these resources should be lightweight enough to always do this rather than having another flag
[ ] Docs
[ ] Networking
[ ] Security

Always expose control plane istiod in tests

---

pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/controller_test.go

Removes a check that would remove every serviceinstance for a proxy when meshNetworks isn't configured. 
`endpointNetwork` will return empty if `fromRegistry` isn't set, but the metadata will be populated if `network` is set. This is very easy to misconfigure. 
This check doesn't really need to be there. In the aggregate registry, we skip checking the cluster's registry based on the cluster ID metadata, which is more reliable. 
Tested that setting clusterName and network allows gateway to bind 0.0.0.0:8080 without extra hacks. 
https://github.com/istio/istio/blob/1cc05bcf798644262547032d6714fab2603121e3/pilot/pkg/serviceregistry/aggregate/controller.go#L265-L271
[ ] Docs
[X] Networking
[ ] Policies and …

allow specifying network for cluster without meshNetworks being configured

---

pkg/test/echo/client/parsedresponse.go
pkg/test/framework/components/echo/instances.go
pkg/test/framework/components/echo/kube/instance.go
pkg/test/framework/components/echo/kube/workload.go
pkg/test/framework/resource/cluster.go
pkg/test/framework/resource/environment.go
tests/integration/multicluster/loadbalancing.go
tests/integration/pilot/ingress_test.go
tests/integration/pilot/istioctl_test.go
tests/integration/pilot/locality_test.go
tests/integration/pilot/main_test.go
tests/integration/pilot/mirror_test.go
tests/integration/pilot/routing_test.go
tests/integration/pilot/vm_test.go

- Echos are deployed to every cluster (except VMs)
- Additional subtest per-cluster as "source"; increase echo call count to reach all clusters. 
- Tests that affect routing also check for all clusters to be hit
- Discovered that multi-network causes traffic to be unequally distributed across clusters (https://github.com/istio/istio/issues/26293)
[Passing run #1](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/25923/integ-pilot-multicluster-tests_istio/88) 
[Passing run #2](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/25923/integ-pilot-multicluster-tests_istio/89)
[Passing run #3](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/25923/integ-pilot-multicluster-tests_istio/90)
[Passing run …

convert pilot tests to use all clusters

---

pilot/pkg/networking/core/v1alpha3/listener.go
pilot/pkg/networking/core/v1alpha3/listener_test.go

* Fix NONE resolution ServiceEntry
Fixes https://github.com/istio/istio/issues/25844
* Clean up 0 instances logic for label selector
(cherry picked from commit bd6d9eceb1565b6fbfb2586dec7b4ac154e2d1cc)
[ ] Docs
[ ] Networking
[ ] Security

Fix NONE resolution ServiceEntry (#26619)

---

istioctl/cmd/kubeuninject.go
istioctl/cmd/kubeuninject_test.go
istioctl/cmd/remove-from-mesh.go
istioctl/cmd/testdata/uninject/deploymentconfig-app-probe.yaml
istioctl/cmd/testdata/uninject/deploymentconfig-app-probe.yaml.injected

Fixes #26677 
Users who enable AppProbeRewrites during istio-injection face an issue where the rewritten app probe isn't restored when executing `istioctl x remove-from-mesh deployment`. This PR fixes that
[ ] Docs
[] Installation
[ ] Networking
[ ] Security

remove-from-mesh should also restore rewritten app probes

---

pilot/pkg/xds/ep_filters.go
pilot/pkg/xds/xds_test.go
pkg/test/framework/resource/cluster.go
releasenotes/notes/26486.yaml
tests/integration/pilot/main_test.go
tests/integration/pilot/routing_test.go
tests/integration/pilot/vm_test.go

When a sidecared pod in network1 tries to reach a non-sidecared pod in network2, it will result in `TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER`.
This is problematic in a scenario where the non-sidecared service exists in both networks. We would loadbalance between endpoints we can reach and ones we cannot. It may be possible to do TLS termination for these endpoints at the gateway, but for now we should at least remove the unreachable endpoints. 
* Don't build cross-network endpoints with tlsmode disabled. 
* Test that cross network VMs still work in integration tests
* Test that we hit all network-local non-sidecar pods in integration tests (naked service)
* Update XDS tests to set tls mode properly
pilot-multicluster test runs: …

filter out cross-network non mTLS lb eps

---

tests/integration/pilot/routing_test.go

We send a lot of traffic all at once, causing occasional timeouts in the
CI. I can reproduce locally, with this fix it seems to pass consistently
[ ] Docs
[ ] Networking
[ ] Security

Increase timeout on traffic test

---

istioctl/cmd/proxyconfig.go

Simplify `proxy-config` subcommands to make it easier to update. Similar to what we have for [Dashboard](https://github.com/istio/istio/blob/master/istioctl/cmd/dashboard.go#L386) commands 
Based on https://github.com/istio/istio/pull/25359#issuecomment-675891508 , next step is to create [endpoint_config](https://www.envoyproxy.io/docs/envoy/latest/api-v3/admin/v3/config_dump.proto#admin-v3-endpointsconfigdump) and update `endpointConfigCmd` once https://github.com/istio/istio/pull/25359 is merged.

Refactor proxy-config cmd into independent sub commands

---

pilot/pkg/model/config.go
pilot/pkg/model/config_test.go

Fixes pilot `Config` deep copy bug. Map pointers were just being copied, so copies shared the same labels and annotations.

Pilot: Config deep copy bug fix

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
pilot/pkg/networking/core/v1alpha3/configgen.go
pilot/pkg/networking/core/v1alpha3/gateway.go
pilot/pkg/networking/core/v1alpha3/httproute.go
pilot/pkg/networking/core/v1alpha3/listener.go
pilot/pkg/networking/core/v1alpha3/listener_builder.go
pilot/pkg/networking/core/v1alpha3/listener_test.go
pilot/pkg/networking/plugin/authn/authentication.go
pilot/pkg/networking/plugin/authz/authorization.go
pilot/pkg/networking/plugin/plugin.go
pilot/test/xdstest/extract.go

Currently we have a ton of code dedicated to plugins which are doing
nothing. Aside from adding complexity to the code, they are also
wrong/misleading. Because we don't use the plugins, we end up generating
all sorts of partial pluginParameters that do not have all params,
such that if we *did* use these functions they wouldn't work anyways.
Additionally, we use "pluginParams" all over the main code, when we
should instead use listenerOpts.
This cleans up the dead plugin functions and fields
Part of the goal here is to explicitly declare the dependencies for config gen rather than passing in mega-structs which are partially populated, which is critical for XDS caching: https://github.com/istio/istio/issues/26732
[ ] Docs
[ ] Networking
[ ] …

Cleanup XDS Plugins

---

pilot/pkg/model/xds_cache.go
pilot/pkg/xds/discovery.go
pilot/pkg/xds/xds_cache_test.go

the CDS/LDS/RDS cannot import the `xds` package. This moves the caching
layer up to the model so we avoid this circular import
For https://github.com/istio/istio/issues/26732

Move XDS cache to model

---

istioctl/cmd/kubeuninject.go

The uninject logic does not remove all of the volumes injected by proxy injector
[ ] Docs
[ ] Networking
[ ] Security

remove all injected volumes when running remove-from-mesh/uninject

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
pilot/pkg/networking/core/v1alpha3/gateway.go
pilot/pkg/networking/core/v1alpha3/gateway_test.go
pilot/pkg/security/model/authentication.go
pilot/pkg/security/model/authentication_test.go
pkg/istio-agent/sds-agent.go

* We no longer have "custom" SDS - we have credentialName SDS (gw/dr)
and workload SDS. Rename things to align with this
* Do not pass custom UDS socket. This is a constant; treat it as such.
This makes things a bit simpler for SDS in Istiod.
[ ] Docs
[ ] Networking
[ ] Security

Refactor SDS logic

---

pilot/pkg/features/pilot.go
pilot/pkg/security/authn/utils/utils.go
pilot/pkg/security/authn/utils/utils_test.go
pilot/pkg/serviceregistry/kube/conversion.go
pilot/pkg/serviceregistry/kube/conversion_test.go
pilot/pkg/xds/ads.go
pilot/pkg/xds/ads_common_test.go
pilot/pkg/xds/ads_test.go
pilot/pkg/xds/authentication.go
pkg/istio-agent/sds-agent.go
pkg/istio-agent/xds-agent.go
pkg/spiffe/spiffe.go
pkg/spiffe/spiffe_test.go
releasenotes/notes/xds-authz.yaml

This adds basic authorization to the XDS connection. This consists of
extracting the identities and verifying the SA and NS are consistent
with the identity.
This is flag protected and on by default for testing - happy to turn it
off before merging.
As part of this work, I refactored some of the SPIFFE code to make it easier to extract the fields we need from a spiffe identity.
[ ] Docs
[ ] Networking
[ ] Security

Add authorization to XDS connection

---

pilot/pkg/networking/core/v1alpha3/fake.go
pilot/pkg/networking/core/v1alpha3/listener_test.go
pilot/pkg/xds/ads_test.go
pilot/pkg/xds/bench_test.go
pilot/pkg/xds/eds_sh_test.go
pilot/pkg/xds/fake.go

We have made some major improvements to the tests in xds package.
However, we cannot reuse this in the v1alpha3 package (config gen)
because of cyclic imports.
This PR splits up the FakeDiscoveryServer. The configgen parts are
handled by a new struct in the v1alpha3 package. The XDS specific parts
are layered on top of this in the xds package. This allows both tests to
share the same interface and implementation.
As part of this PR I migrated a few tests to use this new model - I did
not do all of them to avoid making a huge PR. I might do this in a
followup if I have time, or at the very least we should encourage this
for new testing
[ ] Docs
[ ] Networking
[ ] Security
[ ] Test …

Split out xds.FakeDiscoveryServer for use in configgen

---

releasenotes/notes/25794.yaml
releasenotes/notes/26185.yaml
releasenotes/notes/audit-authz-policy.yaml
releasenotes/notes/debug-handlers.yaml
releasenotes/notes/eds-cache.yaml
releasenotes/notes/envoy-filter.yaml
releasenotes/notes/k8s-auth.yaml
releasenotes/notes/trust-domain-validation.yaml
releasenotes/notes/update-grafana-memory-compute.yaml

Preview of the release notes (additional content added that's not in 1.7). GitHub doesn't accept HTML, so I added a .txt extension. 
[minorReleaseNotes.md.html.txt](https://github.com/istio/istio/files/5124354/minorReleaseNotes.md.html.txt)
Preview of the upgrade notes:
[upgradeNotes.md.html.txt](https://github.com/istio/istio/files/5124361/upgradeNotes.md.html.txt)
This PR fixes the release notes to match the release notes schema.

Fix release notes to match schema

---

pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/controller_test.go

* allow specifying network without meshNetworks fully configured
* remove redundant slice alloc and add safety check for clusterID
* move cluster id check
* set clustername to match in tests
* isControllerForProxy
(cherry picked from commit 97c21c4e6036a3e09484ae1d5c007a94c134c2ff)
fixes #26657

[release-1.6] allow specifying network for cluster without meshNetworks being configured

---

pilot/pkg/xds/ep_filters.go
pilot/pkg/xds/xds_test.go
releasenotes/notes/26486.yaml

* filter out cross-network non mTLS lb eps
* release note
* format
* set service account on xds_test servieentry ep
* remove dr
* release note wording
(cherry picked from commit 755e6411530817897cfb0437d44da06b150aad48)
fixes https://github.com/istio/istio/issues/26706

[release-1.7] filter out cross-network non mTLS lb eps

---

release/downloadIstioCandidate.sh
release/downloadIstioCtl.sh

[Release artifacts ](https://github.com/istio/istio/releases)don't have `istio-1.7.0-linux.tar.gz`. It always appends architecture for `Linux` artifacts `istio-1.7.0-linux-amd64.tar.gz`.
The old scripts will always fail in the first attempt because `istio-1.7.0-linux.tar.gz` never exists.
```
Downloading istio-1.7.0 from 
https://github.com/istio/istio/releases/download/1.7.0/istio-1.7.0-linux.tar.gz ...Failed.
```
It then retires by appending `arch`.
```
Trying with TARGET_ARCH. Downloading istio-1.7.0 from 
https://github.com/istio/istio/releases/download/1.7.0/istio-1.7.0-linux-amd64.tar.gz ...
```
**Which is not required, and we can directly call downloading istio with arch for Linux.**
**Old output:**
```
$ curl -L https://istio.io/downloadIstio | sh -
% Total    % Received % Xferd …
```

Update istio download script

---

istioctl/cmd/root.go

To fix https://github.com/istio/istio.io/issues/7931
Based on https://github.com/istio/istio.io/issues/7931#issuecomment-674913422
The following are moved out of the experiment.
`analyze`  https://github.com/istio/istio/pull/19488
`convert-ingress` https://github.com/istio/istio/pull/16571
`dashboard` https://github.com/istio/istio/pull/17824, https://github.com/istio/istio/pull/26408
`upgrade` https://github.com/istio/istio/pull/19955
cc: @esnible Do suggest any other command that you think also needs to be hidden.

Remove graduted command from experimental section docs

---

pilot/pkg/networking/core/v1alpha3/gateway.go

There are many issues caused by missing virtual services, this pr logs a warning when no vs bound to a gateway.
https://github.com/istio/istio/issues/8374#issuecomment-680856038
[ ] Docs
[X] Networking
[ ] Security

warn when no vs bound to gateway

---

pilot/cmd/pilot-agent/status/ready/probe.go
pilot/cmd/pilot-agent/status/ready/probe_test.go

Checked Envoy and confirmed with @lizan that Envoy readiness state(Server.State) will not change unless it is hot restarted or health check fails. Since we do not have both, it is safe to cache and rely on readiness probe going through Envoy for verifying Envoy is serving traffic.
[ ] Docs
[ ] Security

cache envoy readiness value

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_builder.go

We don't call plugins for clusters anymore. Instead use cluster builder
[ ] Docs
[ ] Networking
[ ] Security

Remove usage of pluginParams in clusters

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go
pilot/test/xdstest/extract.go

For https://github.com/istio/istio/issues/26732
This is a superset of https://github.com/istio/istio/pull/26733. Feel fee to merge that one first if it makes review easier
Currently, we build up all of the clusters, then we apply all the
EnvoyFilter patching. This makes caching impossible, as we cannot
independently cache individual clusters.
This change decomposes the logic: we check if a cluster is removed, and
if not we do any merges. At the end, we insert all newly added clusters.

cds: split envoyfilter logic to apply to only one cluster at a time

---

istioctl/pkg/multicluster/remote_secret.go
istioctl/pkg/multicluster/remote_secret_test.go

The flag used across all `istioctl` command is `--kubeconfig` and not `--Kubeconfig`.
https://preliminary.istio.io/latest/docs/reference/commands/istioctl/#istioctl-experimental-create-remote-secret

Update kubeconfig flag for create-remote-secret

---

pilot/pkg/model/context.go
pilot/pkg/model/push_context.go
pilot/pkg/networking/apigen/apigen.go
pilot/pkg/networking/grpcgen/grpcgen.go
pilot/pkg/xds/ads.go
pilot/pkg/xds/cds.go
pilot/pkg/xds/eds.go
pilot/pkg/xds/gen.go
pilot/pkg/xds/internalgen.go
pilot/pkg/xds/lds.go
pilot/pkg/xds/rds.go
pilot/pkg/xds/simple.go

We have had a concept of "full push" for a while, which really meant
"non EDS". This adopts the code to allow incremental updates for
non-EDS types.
This is split off https://github.com/istio/istio/pull/26277
[ ] Docs
[ ] Networking
[ ] Security

Allow incremental updates for non-EDS types

---

pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
pilot/pkg/networking/core/v1alpha3/fake.go
pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
pilot/pkg/serviceregistry/memory/discovery.go
pilot/test/xdstest/extract.go

Use the new ConfigGenTest recently added. In addition, stop doing things like `clusters[7]` - reference by explicit name instead, and migrate some to table driven tests

Clean up cluster tests

---

pilot/pkg/xds/eds.go
pilot/pkg/xds/eds_test.go
pkg/adsc/adsc.go

After the generic gen change, we started doing incremental EDS pushes if
a endpoint changed during a full push
[ ] Docs
[ ] Networking
[ ] Security

Fix regression in EDS pushes

---

pkg/config/validation/validation.go
pkg/config/validation/validation_test.go

Fixed https://github.com/istio/istio/issues/26397 by looking for single `%` and refusing to validate if found.
```
route:
- destination:
host: httpbin
headers:
response:
set:
r-my-name-is: "%HOSTNAME%"  # Header is given hostname
r-favorite-fruit-is: apple # Header is given value "apple"
r-code-details: "%INVALID%"  # IGNORED BY ENVOY
r-i-love-istio: "100%%"  # Header is given value "100%"
r-crazy: "1234%apple"  # envoy.api.v2.RouteConfiguration rejected: Invalid header configuration. Un-terminated variable expression
```
This code is looking for cases that Envoy rejects, not for cases that are ignored by Envoy.
While writing this PR I noticed that our existing tests cover `VirtualService.http.route.headers` but not `VirtualService.http.headers`.  I only added new cases in the style of …

Validate header set/add based on Envoy syntax

---

pkg/test/kube/dump.go

Makes it easier to differentiate similar services/pods across clusters
https://gcsweb.istio.io/gcs/istio-prow/pr-logs/pull/istio_istio/26835/integ-pilot-multicluster-tests_istio/279/artifacts/pilot-6948a88beb67497d94290c327/TestTraffic/sniffing/auto-tcp_a-%3ea_from_cluster-4/_test_context/echo-1-946-state936378166/
[ ] Docs
[ ] Networking
[ ] Security

cleanup multicluster dump directories

---

galley/testdatasets/validation/dataset.gen.go
galley/testdatasets/validation/dataset/networking-v1alpha3-VirtualService-invalid.yaml
galley/testdatasets/validation/dataset/networking-v1beta-VirtualService-invalid.yaml
tests/integration/pilot/validation_test.go

TestValidation flakes as it runs in parallel

Fix TestValidation

---

pkg/istio-agent/sds-agent.go

Cherry-pick an fix that has already been fixed
ref: https://github.com/istio/istio/issues/26821
[ ] Docs
[ ] Networking
[X] Security

add outputOutputKeyCertToDir to enable workload load from the file cert

---

pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/multicluster.go

When we delete a cluster secret we remove the service registry but not endpoint shards. If the service exists in both clusters, the remote cluster's endpoints will still be pushed. This fix removes the need to restart istiod when a remote secret is removed. 
There may be other things that need to be cleaned up besides this. 
[ ] Docs
[X] Networking
[ ] Security

cleanup services when removing cluster secret

---

istioctl/cmd/kubeuninject.go
istioctl/cmd/remove-from-mesh.go
releasenotes/notes/remove-from-mesh-fix.yaml

(cherry picked from commit 707b28d8b8e6dac582f55fe40403109f4d3cbb4e)
Manual cherry pick of PR #26812 
[ ] Docs
[ ] Networking
[ ] Security

[release-1.7] remove cni initContainers and volumes in remove-from-mesh (#26812)

---

tools/istio-iptables/pkg/cmd/root.go
tools/istio-iptables/pkg/cmd/run.go
tools/istio-iptables/pkg/cmd/run_test.go

We dont need DNS_AGENT and ISTIO_META_DNS_CAPTURE separately as we are doing interception in the agent.
[ ] Docs
[x] Networking
[ ] Security

clean up IPtables rules for DNS interception

---

releasenotes/README.md
releasenotes/template.yaml

One request related to the release notes schema was to add a field to specify docs. 
These links will be appended to the note. 
This is inspired by Kubernetes (https://relnotes.k8s.io/?documentation=official and https://github.com/kubernetes/kubernetes/pull/83474). 
For:
```
issue:
- https://github.com/istio/istio/issues/23622
- 23624
docs:
- [usage] https://istio.io/latest/docs/tasks/traffic-management/request-routing/
- [reference] https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/
releaseNotes:
- |
**Fixed** an issue preventing the operator from recreating watched resources if they are deleted
```
This would appear as: 
**Fixed** an issue preventing the operator from recreating watched resources if they are deleted …

Add docs field

---

pilot/pkg/xds/ads.go

My whole istiod log ends up being this. In reality, most pushes will be
filtered out. Even if they are not filtered, we will see the pushes for
individual resource logs so I don't think we need this one
[ ] Docs
[ ] Networking
[ ] Security

Remove excessive "pushing" log

---

pkg/test/framework/components/istio/istio.go
tests/integration/multicluster/base/main_test.go
tests/integration/multicluster/centralistio/main_test.go
tests/integration/pilot/analysis/main_test.go
tests/integration/pilot/cni/cni_test.go
tests/integration/pilot/main_test.go
tests/integration/pilot/revisions/revisions_test.go
tests/integration/security/ca_custom_root/main_test.go
tests/integration/security/chiron/main_test.go
tests/integration/security/filebased_tls_origination/main_test.go
tests/integration/security/main_test.go
tests/integration/security/mtls_first_party_jwt/main_test.go
tests/integration/security/mtlsk8sca/main_test.go
tests/integration/security/sds_egress/main_test.go
tests/integration/security/sds_ingress_k8sca/main_test.go
tests/integration/security/sds_tls_origination/main_test.go
tests/integration/security/sds_vault_flow/main_test.go
tests/integration/security/webhook/webhook_test.go
tests/integration/telemetry/main_test.go
tests/integration/telemetry/outboundtrafficpolicy/traffic_test.go
tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
tests/integration/telemetry/stackdriver/vm/main_test.go
tests/integration/telemetry/stats/prometheus/http/nullvm/stats_filter_test.go
tests/integration/telemetry/stats/prometheus/http/wasm/stats_wasm_filter_test.go
tests/integration/telemetry/tracing/clienttracing/client_tracing_test.go
tests/integration/telemetry/tracing/servertracing/tracing_test.go

Haven't fully looked into why this breaks things yet, but it causes ingress gateway in remote clusters to not come up during multicluster setup. Their logs have:
```
2020-09-01T18:24:40.785873Z	info	xdsproxy	connecting to upstream istiod-remote.istio-system.svc:15012
2020-09-01T18:24:40.801011Z	error	xdsproxy	upstream recv error: rpc error: code = Unknown desc = authentication failure
2020-09-01T18:24:40.801140Z	error	xdsproxy	downstream recv error: rpc error: code = Canceled desc = context canceled
2020-09-01T18:24:40.801490Z	warning	envoy config	StreamAggregatedResources gRPC config stream closed: 2, authentication failure
2020-09-01T18:24:54.663487Z	warn	Envoy proxy is NOT ready: config not received from Pilot (is Pilot running?): cds updates: 0 successful, 0 rejected; lds updates: 0 …
```

don't set PROXY_XDS_VIA_AGENT in multicluster mode

---

istioctl/cmd/root.go
istioctl/pkg/validate/validate.go

Based on https://github.com/istio/istio/pull/26846#pullrequestreview-476629926. Also added alias `v` for validate.

Hide redundant kubeconfig flag from istioctl validate

---

pkg/istio-agent/agent.go

This got regressed in the recent refactoring. We do not have to run gateway secret fetcher (and secret controller) if gateway is using file mounted certs.
[ ] Docs
[ ] Networking
[ ] Security

do not run gateway secret fetcher for file mounted certs

---

pilot/pkg/serviceregistry/serviceregistry_test.go

https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/3572
This is not graceful, but currently there is no way to get notified  whether service/endpoint/pod s are populated

Fix TestWorkloadInstances flake

---

samples/bookinfo/src/reviews/reviews-wlpcfg/build.gradle

Refactored task clean of gradle file for reviews-wlfcfg
Description: `gradle build` creates only apps folder in servers/LibertyProjectServer/ directory whereas in `gradle clean` task, directories lib, logs, workarea, resources is getting cleaned up. So removed these lines as a part of `gradle clean` task.
[ ] Docs
[ ] Networking
[ ] Security
[ X] User Experience

Refactored task clean in bookinfo reviews app

---

pilot/pkg/xds/ads.go

We used to log the first CDS request and now we no longer are. I was
going to add that back but it seems more appropriate to log a new
connection
[ ] Docs
[ ] Networking
[ ] Security

Add log for new connections

---

tools/dump_kubernetes.sh

Fixes #26552 
Before:
```
./dump_kubernetes.sh
Fetching debug/configz from istiod
Error from server (BadRequest): container istio-proxy is not valid for pod istiod-6f5fd7cb8f-5gjtv
Fetching debug/endpointz from istiod
Error from server (BadRequest): container istio-proxy is not valid for pod istiod-6f5fd7cb8f-5gjtv
Fetching debug/adsz from istiod
Error from server (BadRequest): container istio-proxy is not valid for pod istiod-6f5fd7cb8f-5gjtv
Fetching debug/authenticationz from istiod
Error from server (BadRequest): container istio-proxy is not valid for pod istiod-6f5fd7cb8f-5gjtv
Fetching metrics from istiod
Error from server (BadRequest): container istio-proxy is not valid for pod istiod-6f5fd7cb8f-5gjtv
Retrieving Kubernetes resource configurations
```
After:
```
./dump_kubernetes.sh …
```

Fix istiod logs (no istio-proxy container)

---

tools/istio-iptables/pkg/cmd/root.go

Please provide a description of what this PR is for.
Currently, we are unable to ascertain the exact root cause of an istio-validation container failure. It would be helpful to log the error message before exiting
[ ] Docs
[X] Networking
[ ] Security

enable error log when istio-validation exits with a non-zero code

---

.github/ISSUE_TEMPLATE/bug_report.md

This is easier to understand
```
$ kubectl version --short
Client Version: v1.19.0
Server Version: v1.18.2
```
As compared to the full version which has lot of information.
```yaml
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-28T18:36:35Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Use kubectl version --short flag for bug report template

---

cni/pkg/install-cni/pkg/install/cniconfig_test.go

Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>
This PR fixes the goroutine leak in TestGetCNIConfigFilepath(). If the goroutine times out, then it will block on the channels resultChan and errChan since there would not be corresponding reader. To fix this, use a buffered channel.
[ ] Docs
[ ] Networking
[ ] Security
[X ] Developer Infrastructure

TestGetCNIConfigFilepath: fix goroutine leak

---

galley/pkg/config/analysis/analyzers/all.go
galley/pkg/config/analysis/analyzers/analyzers_test.go
galley/pkg/config/analysis/analyzers/testdata/virtualservice_dupmatches.yaml
galley/pkg/config/analysis/analyzers/virtualservice/matches.go
galley/pkg/config/analysis/analyzers/virtualservice/util.go
galley/pkg/config/analysis/msg/messages.gen.go
galley/pkg/config/analysis/msg/messages.yaml

Resolves https://github.com/istio/istio/issues/25533
Does **NOT** resolve https://github.com/istio/istio/issues/23073 .
Messages look like:
```
Warning [IST0130] (VirtualService duplicate-match galley/pkg/config/analysis/analyzers/testdata/virtualservice_dupmatches.yaml:25) VirtualService rule 1 not used (all matches used by prior rules).
Warning [IST0130] (VirtualService sample-foo-cluster01.foo galley/pkg/config/analysis/analyzers/testdata/virtualservice_dupmatches.yaml:1) VirtualService rule 1 not used (only the last rule can have no matches).
Info [IST0131] (VirtualService almost-duplicate-match galley/pkg/config/analysis/analyzers/testdata/virtualservice_dupmatches.yaml:47) VirtualService rule 1 match 0 is not used (duplicates a match in rule 0).
Info [IST0131] (VirtualService …
```

Analyze duplicate VirtualService matches

---

manifests/charts/istio-telemetry/kiali/templates/clusterrole.yaml
manifests/charts/istio-telemetry/kiali/values.yaml
releasenotes/notes/kiali-fix-rbac.yaml

Attempt to fix https://github.com/istio/istio/issues/27109
Merging directly at `release-1.7` branch as on `master` Kiali manifests have already been removed.
- **Kiali: Add rbac.istio.io apiGroup to clusterRoles**
Newer versions of Kiali that are compatible with Istio 1.7 require some additional permissions on the utilized clusterRoles. In this PR, we include the missing apiGroup to corresponding Kiali manifests.
- **Kiali: Bump minor version to 1.23** 
- **Kiali: Switch to anonymous auth strategy** 
In newer versions of Kiali that are compatible with Istio 1.7, auth login strategy has been removed thus not supported. In this PR, we are migrating to anonymous auth strategy which is also Kiali's default one.
[ ] Docs
[ ] Networking
[ ] …

Fix Kiali RBAC and bump to latest stable version that is compatible with Istio 1.7+

---

pkg/test/framework/components/environment/kube/flags.go
pkg/test/framework/components/environment/kube/settings.go
pkg/test/framework/components/istio/operator.go

When running tests locally, I noticed that this topology `--controlPlaneTopology 0:0,1:0` had what should have been a remote cluster being deployed as a "config cluster". Because the defaults for ConfigClusterValues are not baked into the framework code, but are in the externalistiod test main, these clusters are probably being deployed as if they're independent primary clusters. 
The logs in this PR confirm that switching this deploys things properly:
```
2020-09-09T07:27:20.926092Z	info	tf	setting up cluster-0 as primary cluster
...
2020-09-09T07:27:39.710299Z	info	tf	setting up cluster-2 as primary cluster
...
2020-09-09T07:28:00.393005Z	info	tf	setting up cluster-3 as primary cluster
...
2020-09-09T07:28:25.447590Z	info	tf	setting up cluster-4 as remote cluster …
```

use cp topology as default cfg topology

---

tests/integration/pilot/common/routing.go

Accidentally skipped gRPC and removed TCP entirely in #26835 
[ ] Docs
[ ] Networking
[ ] Security

re-enable grpc and skip tcp traffic sniffing tests

---

tests/integration/pilot/common/routing.go

#26835 had improvements like telling us how many requests failed, actually including fields like ClusterName in TCP responses but didn't fix the connection resets. 
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/27049/integ-pilot-k8s-tests_istio/19817
[ ] Docs
[ ] Networking
[ ] Security

disable tcp again

---

tests/integration/pilot/istioctl_test.go

\#27178 removed some waiting logic. This adds it back, due to test
flakes:
https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/3647
[ ] Docs
[ ] Networking
[ ] Security

Wait for pod in TestAddToAndRemoveFromMesh

---

pilot/pkg/dns/dns.go

```
panic: interface conversion: interface {} is nil, not *dns.LookupTable
goroutine 122 [running]:
istio.io/istio/pilot/pkg/dns.(*LocalDNSServer).ServeDNS(0xc0007dc240, 0xc0007f9590, 0x308ff20, 0xc00051e420, 0xc001682c60)
istio.io/istio/pilot/pkg/dns/dns.go:154 +0x514
istio.io/istio/pilot/pkg/dns.(*dnsProxy).ServeDNS(0xc0007f9590, 0x308ff20, 0xc00051e420, 0xc001682c60)
istio.io/istio/pilot/pkg/dns/proxy.go:79 +0x52
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc0007c9420, 0x308ff20, 0xc00051e420, 0xc001682c60)
github.com/miekg/dns@v1.1.30/serve_mux.go:103 +0x5d
github.com/miekg/dns.(*Server).serveDNS(0xc0007e18c0, 0xc000b54000, 0x1b, 0x200, 0xc00051e420)
github.com/miekg/dns@v1.1.30/server.go:609 +0x2f7
github.com/miekg/dns.(*Server).serveUDPPacket(0xc0007e18c0, 0xc00155a304, 0xc000b54000, …
```

Fix crash when first DNS requests comes before NDS is loaded

---

tools/certs/Makefile.k8s.mk
tools/certs/Makefile.selfsigned.mk

Was trying @esnible 's external istiod istioctl cmd, and couldnot find out how to use these make files without looking at code.
Before:
```
~/go/src/istio.io/istio/tools/certs on  master! ⌚ 16:36:18
$ make -f Makefile.selfsigned.mk 
make: *** No rule to make target `Makefile', needed by `help'.  Stop.
```
After:
```
~/go/src/istio.io/istio/tools/certs on  master! ⌚ 16:59:00
$ make -f Makefile.selfsigned.mk 
help:		print this help message
root-ca:	generate root CA files (key and certifcate) in current directory.
<name>-cacerts: generate self signed intermediate certificates for <name> and store them under <name> directory.
<namespace>-certs: generate intermediate certificates and sign certificates for a virtual machine connected to the namespace `<namespace> using serviceAccount …
```

fix help for make cert files

---

pilot/pkg/xds/debug.go

I did not make this a part of config_dump since that is mirror envoy
format and will be sent over the wire for istioctl (maybe?) and we don't
currently have a wrapper proto like all the other types
Fixes https://github.com/istio/istio/issues/27153

nds: add debug endpoint

---

bin/init.sh

These were duplicated because we had somethings running init.sh directly. We no longer do. In this time, the init.sh directly has broken, which leads me to believe its not used. As a result, I think removing the duplication is a better fix than fixing it, that way we only need to maintain one set of variables.

Reduce variable duplication in init and makefile

---

pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
pilot/pkg/networking/core/v1alpha3/listener.go
pilot/pkg/networking/core/v1alpha3/listener_builder.go
pilot/pkg/networking/core/v1alpha3/listener_test.go

Cache EnvoyFilterWrapper in listener builder to avoid frequent calls to push context.
[ ] Docs
[ ] Security

optimize listener patches

---

pkg/test/framework/components/echo/call.go
pkg/test/framework/components/echo/common/call.go
pkg/test/framework/components/echo/config.go
pkg/test/framework/components/echo/instances.go
tests/integration/pilot/common/apps.go
tests/integration/pilot/common/routing.go
tests/integration/pilot/mirror_test.go
tests/integration/telemetry/stackdriver/testdata/server_access_log.json.tmpl
tests/integration/telemetry/stackdriver/vm/testdata/server_access_log.json.tmpl

This re-enables the sniffing tests, only skipping the TCP which is
currently flaky due to issues with our `echo` client which is being
addressed separately. In addition, we add testing of the external
service. To support this change, I added a way for an echo instance to
declare its default hostname. This way, we can treat it like any regular
service
[ ] Docs
[ ] Networking
[ ] Security
Please check any characteristics that apply …

Re-enable protocol sniffing test and add external

---

operator/cmd/mesh/manifest-migrate.go

It was causing confusion to users, see https://github.com/istio/istio/issues/26230

[release-1.6]remove deprecated help message for manifest migrate

---

pilot/pkg/networking/core/v1alpha3/cluster.go
releasenotes/notes/27293.yaml

Do not apply locality load balancer settings for inbound clusters. Fixes https://github.com/istio/istio/issues/27293
[ ] Docs
[ ] Security

do not apply locality load balancer settings for inbound clusters

---

pilot/pkg/model/service.go
pilot/pkg/networking/core/v1alpha3/fake.go
pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/fake.go
pilot/pkg/serviceregistry/kube/controller/pod.go
pilot/pkg/serviceregistry/serviceentry/conversion.go
pilot/pkg/serviceregistry/serviceentry/conversion_test.go
pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
pilot/pkg/serviceregistry/serviceregistry_test.go
pilot/pkg/xds/ads_test.go
pilot/pkg/xds/fake.go
pilot/pkg/xds/xds_test.go
pilot/test/xdstest/extract.go
releasenotes/notes/we-updates.yaml

PR is split into many commits
1. does some testing refactoring to support this, and adds 2 failing tests
2. Fixes #27151, enables the test
3. Fixes #27183, enables the test
4. Fixes pod updates for SE selects pod
5. Fixes SE updates for SE selects pod
6. Fixes https://github.com/istio/istio/issues/27185
Somehow we managed to have 4 different bugs covering all 4 update scenarios. They should be all fixed and tested now.
cc @kyessenov @JimmyCYJ

Fix Service and WorkloadEntry updates

---

README.md
logo/istio-bluelogo-whitebackground-unframed.svg

Adding Istio logo in README.md file, so that when someone will read the README file by clicking on it they will directly redirect to Istio [website](https://istio.io/)
How the README.md file will look [here](https://github.com/RanabirChakraborty/istio/tree/Logo-1)
[X] Docs

Logo-1: Adding Istio logo in README.md

---

go.sum
istioctl/cmd/authz.go
istioctl/cmd/dashboard.go
istioctl/cmd/proxyconfig.go
istioctl/cmd/proxyconfig_test.go
istioctl/cmd/proxystatus.go
istioctl/cmd/proxystatus_test.go
istioctl/pkg/util/handlers/handlers.go
pkg/kube/client.go
pkg/test/kube/mock_client.go
releasenotes/notes/27086.yaml

For https://github.com/istio/istio/issues/26080
Instead of knowing the pod name, e.g. `istioctl proxy-status httpbin-6674f664d-fw2hd`, users will be able to imply the pod from other types, similar to how 'kubectl logs' or 'kubectl exec' work.  For example
```
kubectl proxy-status deployment/httpbin
kubectl ps service/httpbin
```

istioctl: allow pods to be referred to indirectly, using service/<svc> or deployment/<dep>, like kubectl

---

tests/integration/pilot/common/routing.go
tests/integration/pilot/vm_test.go

At some point [integ-pilot-multicluster-tests_istio](https://testgrid.k8s.io/istio_istio#integ-pilot-multicluster-tests_istio) started failing the VM OS tests and all headless connectivity tests. I think this is related to DNS changes, but I want to get this job to be green and mark it required so it doesn't have any further regressions that block converting our tests. 
cc @nmittler @rshriram 
[ ] Docs
[X] Networking
[ ] Security

disable headless and VM OS tests for multicluster

---

pkg/kube/client.go

Resolves https://github.com/istio/istio/issues/27317
The 'istioctl version' legacy command should only get the version on :15014/version from Istiod.  There are no longer other microservice pods.
@howardjohn This might be suitable for a `cherry-pick-1.7`.
This problem manifests when a user installs with an Ingress Gateway Deployment Pod with label `istio=<anything-other-than-ingressgateway>`.  
- With this change, `istioctl version` only picks up the version from Istiod pod.  This means `istioctl version` with this applied will not detect if the mixer was not pruned by the install.
- An alternative is to continue contacting all unrecognized `istio=` labelled pods, and suppress this message.
- Another alternative is to continue with this message, which is caused by a user putting `istio: …

Only check Istiod pod version on port 15014

---

tests/integration/multicluster/helper.go
tests/integration/multicluster/loadbalancing.go

Right now we only test that we hit one service in the remote clusters. We should make sure we can have multiple instances in multiple clusters in loadbalancing rotation. 
[ ] Docs
[X] Networking
[ ] Security

test that we load balance across multiple subsets in remote clusters

---

pilot/pkg/serviceregistry/kube/controller/controller.go

fix bug in https://github.com/istio/istio/pull/27002
issue：[release-1.6] cleanup services when removing cluster secret #26930

fix error service name in Cleanup

---

pilot/pkg/xds/ads.go
pilot/pkg/xds/ads_test.go
pilot/pkg/xds/discovery_test.go
pilot/pkg/xds/init_test.go

Conform to XDS spec in
https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#how-the-client-specifies-what-resources-to-return.
This has not been found as a bug in normal Envoy interaction, but it
breaks `istioctl wait` and `istioctl ps` today. What happens is Envoy
will send an RDS request with empty resources. This can happen at
startup or at any point in time (removing all VS for gateway, for
example). When this happens, today, we just keep sending it an empty
list of resources, which it will accept but never ACK.
This changes to actually drop the subscription, so we never even send
these empty resources.
[ ] Docs
[ ] Networking
[ ] Security
[ ] …

Fix handling of empty resources

---

samples/bookinfo/src/details/details.rb
samples/bookinfo/src/productpage/productpage.py
samples/bookinfo/src/reviews/reviews-application/src/main/java/application/rest/LibertyRestEndpoint.java

Update bookinfo to propagate all headers that Istio can use for context propagation.
This will let us:
1. Write more thorough e2e tests for tracing.
2. Demonstrate different context propagation in documentation and examples.
[X] Docs
[ ] Networking
[ ] Security

bookinfo: propagate all tracing headers

---

tools/certs/README.md

**Please provide a description for what this PR is for.**
In Istio/tools/certs/README.md, there was an outdated term 'intermediate Citadels'. Since Istio is organized differently now, the term should be 'intermediate CAs'. I updated the term to 'intermediate CAs'.
**And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.**
[X] Docs
[ ] Networking
[ ] Security
**Pull Request Attributes**

Changed term from intermediate Citadels to intermediate CA in Istio/tools/certs/README.md

---

tests/integration/security/ca_custom_root/main_test.go
tests/integration/security/chiron/main_test.go
tests/integration/security/filebased_tls_origination/main_test.go
tests/integration/security/main_test.go
tests/integration/security/mtls_first_party_jwt/main_test.go
tests/integration/security/mtlsk8sca/main_test.go
tests/integration/security/sds_egress/main_test.go
tests/integration/security/sds_ingress/ingress_test.go
tests/integration/security/sds_ingress_istiod/ingress_test.go
tests/integration/security/sds_ingress_k8sca/main_test.go
tests/integration/security/sds_tls_origination/main_test.go
tests/integration/security/sds_vault_flow/main_test.go
tests/integration/security/webhook/webhook_test.go

This PR is the first step to convert security integration tests to multicluster supported. 
[ ] Docs
[ ] Networking
[X] Security

Remove RequireSingleCluster() within security integration tests

---

pkg/test/echo/cmd/client/main.go

This allows dropping `client` in for `curl` in many cases
[ ] Docs
[ ] Networking
[ ] Security

Make test client more like curl

---

pkg/kube/client.go

Resolves https://github.com/istio/istio/issues/27383 by falling back to the exec behavior if port 15014 is unavailable for `istioctl version` and friends.

Fallback to 'exec' if port forward to 15014 unavailable

---

pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
releasenotes/notes/27425.yaml

Add a "REPLACE" operation for EnvoyFilter patch. This operation only supports Network filter and HTTP filter.
This is the implementation of issue #27425
Signed-off-by: huabing zhao <zhaohuabing@gmail.com>
[ ] Docs
[*] Networking
[ ] Security

Implement REPLACE operation for EnvoyFilter patch

---

tools/istio-docker.mk

**Fix for [27428](https://github.com/istio/istio/issues/27428), Change for fixing the build of the operator without a build-tools container.**
[ ] Docs
[ ] Networking
[ ] Security

issues/27428: Change for fixing the build of the operator without a build-tools container.

---

tests/integration/pilot/common/routing.go

On top of #27332, we need this to get a "green" baseline to fix these tests from. 
#27343 will likely need to re-break some tests for CI to produce valuable debugging info. 
https://prow.istio.io/?pull=27344&job=integ-pilot-multicluster-tests_istio
[ ] Docs
[X] Networking
[ ] Security

pilot tests: vm only validates hitting headless service in local-cluster

---

pkg/istio-agent/health/health_check.go
pkg/istio-agent/xds_proxy.go

See
https://stackoverflow.com/questions/57717635/golang-for-select-blows-up-cpu
We should not loop over closed channels like this
[ ] Docs
[ ] Networking
[ ] Security

Fix infinite loop in xdsproxy

---

pkg/test/framework/components/echo/kube/deployment.go
pkg/test/framework/components/stackdriver/stackdriver.yaml
tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
tests/integration/telemetry/stackdriver/testdata/custom_bootstrap.yaml.tmpl
tests/integration/telemetry/stackdriver/vm/main_test.go
tests/integration/telemetry/stackdriver/vm/testdata/server_access_log.json.tmpl
tests/integration/telemetry/stackdriver/vm/testdata/server_edge.prototext.tmpl
tests/integration/telemetry/stackdriver/vm/testdata/trace.prototext.tmpl
tests/integration/telemetry/stackdriver/vm/vm_test.go

PR to add coverage for tracing to Stackdriver integration tests.  Refactors the test structure a bit in an attempt to improve readability by separating out the tests parts and the setup parts (as well as to fail faster when there are setup issues).
Notes:
- a custom bootstrap override is used for the VM to enable population of a testing endpoint for Cloud Trace (it is not read from env vars, as elsewhere)
- a custom proxy config is used to simulate real-world VM configuration reqs for Cloud Trace.
- `custom_tags` are added to each span to simulate annotation of canonical service information with each span.
[ X ] Does not have any changes that may affect Istio users.

test(stackdriver): add tracing integration test for VMs

---

pkg/test/framework/components/istio/eastwest.go
tests/integration/tests.mk

- better std err dump
- probably due to using `istioctl` in script, can we rely on `istioctl` being the built one, or should we give `istio.io/istio/out/...` path? 
[ ] Docs
[ ] Networking
[ ] Security

fix eastwest gen

---

istioctl/pkg/validate/validate.go
istioctl/pkg/validate/validate_test.go

To fix https://github.com/istio/istio/issues/27311
Originated from https://github.com/istio/istio/pull/27242#issuecomment-691469641
After this PR.
```
$ make lint
Validating samples/health-check/liveness-http-same-port.yaml...
"samples/health-check/liveness-http-same-port.yaml" is valid
Validating samples/helloworld/helloworld-gateway.yaml...
"samples/helloworld/helloworld-gateway.yaml" is valid
Validating samples/helloworld/helloworld.yaml...
"samples/helloworld/helloworld.yaml" is valid
Validating samples/kubernetes-blog/bookinfo-ratings.yaml...
"samples/kubernetes-blog/bookinfo-ratings.yaml" is valid
Validating samples/kubernetes-blog/bookinfo-reviews-v2.yaml...
"samples/kubernetes-blog/bookinfo-reviews-v2.yaml" is valid
Validating samples/kubernetes-blog/bookinfo-v1.yaml... …
```

Fix Lint warning for missing Deployment spec.template.metadata.labels

---

tests/integration/tests.mk

Seems like the presubmit and non-presubmit are identical except for the test select flags and the PATH being set (recently fixed). They can be consolidated to avoid further confusion. 
[ ] Docs
[ ] Networking
[ ] Security

consolidate kube make targets

---

tools/bug-report/pkg/bugreport/bugreport.go

To fix https://github.com/istio/istio.io/issues/8191
Related:
https://github.com/istio/istio/pull/27107
Before:
```
$ ./out/linux_amd64/istioctl bug-report -h
bug-report selectively captures cluster information and logs into an archive to help diagnose problems and optionally uploads the archive to a GCS bucket. 
Proxy logs can be filtered using:
--include|--exclude ns1,ns2.../dep1,dep2.../pod1,pod2.../cntr1,cntr.../lbl1=val1,lbl2=val2.../ann1=val1,ann2=val2...
where ns=namespace, dep=deployment, cntr=container, lbl=label, ann=annotationThe filter spec is interpreted as 'must be in (ns1 OR ns2) AND (dep1 OR dep2) AND (cntr1 OR cntr2)...'The log will be included only if the container matches at least one include filter and does not match any exclude filters.All parts of the filter are …
```

Use backtick for istioctl bug-report description

---

pkg/test/env/istio.go
pkg/test/framework/components/environment/kube/flags.go

The framework currently assumes that KUBECONFIG is separated by commas, which is not supported by the spec. This change allows the variables to be comma-seprated, but then converts them to being properly colon-separated.
Follow-on PRs will get rid our our usage of commas from prow jobs.
[ ] Docs
[ ] Networking
[ ] Security

[Test Framework] Support colon-separated KUBECONFIG

---

istioctl/cmd/add-to-mesh.go
istioctl/cmd/authz.go
istioctl/cmd/describe.go
istioctl/cmd/proxyconfig.go
istioctl/cmd/remove-from-mesh.go
istioctl/cmd/root.go

Experimental commands have currently 3 different warning message in `istioctl <cmd> --help`.
```
THIS COMMAND IS UNDER ACTIVE DEVELOPMENT AND NOT READY FOR PRODUCTION USE.
THIS COMMAND IS STILL UNDER ACTIVE DEVELOPMENT AND NOT READY FOR PRODUCTION USE.
THESE COMMANDS ARE UNDER ACTIVE DEVELOPMENT AND NOT READY FOR PRODUCTION USE.
```
Use one common warning for all the experimental commands. So that it will be easier to change and update. 
```
THIS COMMAND IS UNDER ACTIVE DEVELOPMENT AND NOT READY FOR PRODUCTION USE
```
Example:
```
$ ./out/linux_amd64/istioctl x add-to-mesh -h
'istioctl experimental add-to-mesh' restarts pods with an Istio sidecar or configures meshed pod access to external services.
Use 'add-to-mesh' as an alternate to namespace-wide auto injection for troubleshooting …
```

Use common warning for experimental commands

---

pkg/config/validation/validation.go
pkg/config/validation/validation_test.go

This adds some initial pattern to the validation logic to support
passing up errors and warnings without massive plumbing changes, as well
as adding the first warning message
[ ] Docs
[ ] Networking
[ ] Security

Add first warning to validation

---

pkg/test/framework/analyzer.go
pkg/test/framework/test.go

Missing feature labels won't fail an actual test, but bad feature labels will. Only the analyzer should fail, actual tests should still run but give a warning. 
The error message about using "leafs" of the features.yaml also gets moved into the analyzer in this PR. 
[ ] Docs
[ ] Networking
[ ] Security

bad feature labels only fail analyzer

---

pkg/test/framework/components/environment/kube/flags.go

We were unnecessarily setting a default. We later on use the values from the environment as a default if this value is unset.
[ ] Docs
[ ] Networking
[ ] Security

[Test Framework] Fix default for --istio.test.kube.config.

---

pkg/test/framework/components/environment/kube/flags.go

Prevents single-network multi-cluster tests from erroring with:
```
2020-09-24T22:45:17.230947Z	error	tf	Test setup error: failed generating eastwestgateway manifest for cluster-0 using "/Users/tairan/Documents/go/src/istio.io/istio/out/darwin_amd64/istioctl\n": exit status 1: The NETWORK environment variable must be set.
```

test framework: default to single network

---

pilot/pkg/networking/core/v1alpha3/accesslog.go
pilot/pkg/networking/core/v1alpha3/listener_test.go

Replace FileAccessLog_LogFormat(Deprecated) and FileAccessLog_JsonFormat(Deprecated) with FileAccessLog_LogFormat
[ ] Docs
[ ] Networking
[ ] Security

Replace FileAccessLog_LogFormat(Deprecated) and FileAccessLog_JsonFormat(Deprecated) with FileAccessLog_LogFormat

---

security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin.go

This is to keep the behavior align with stsclient. Use GKE_CLUSTER_URL as the source of truth if GKE_CLUSTER_URL is set.
[ ] Docs
[ ] Networking
[x] Security

read GKE_CLUSTER_URL if set

---

bin/update_proxy.sh

Try to figure out how does istio/proxy update it's latest sha to istio/istio, since I've been worked on update istio/envoy sha to istio/proxy, in which they fetched the latest istio/test-infra sha not in the targeted repo 
log: https://prow.istio.io/view/gs/istio-prow/logs/update-proxy_envoy_periodic/1

Print cmd for istio/proxy update latest sha to istio/istio

---

tools/bug-report/pkg/archive/archive.go
tools/bug-report/pkg/bugreport/bugreport.go
tools/bug-report/pkg/common/common.go
tools/bug-report/pkg/content/content.go
tools/bug-report/pkg/kubectlcmd/kubectlcmd.go

Logs are returned through the API server and because bug-report is fully parallel it would be hammered for large clusters. This change both rate limits the rate of API server requests and the number of parallel log fetches (since these can be long running).
The PR also adds a small UX improvement - the still running fetch commands are displayed periodically so user gets some feedback if things are taking a long time. 
e.g. 
The following fetches are still running: 
```
PodExec istio-system/istiod-version-16-85d45b4dc4-mss5f/discovery:pilot-discovery request GET debug/adsz
kubectl get --all-namespaces all,jobs,ingresses,endpoints,customresourcedefinitions,configmaps,events -o yaml
ProxyGet default/reviews-v1-564b97f875-fj45d:certs
kubectl cluster-info dump
```

Limit concurrency and request rate

---

pilot/pkg/networking/core/v1alpha3/listener.go

This PR removes setting the generate request id on connection manager - This is any way is [defaulted to true](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto.html?highlight=generate_request_id) in Envoy
[ ] Docs
[ ] Security

do not set generate requestid on connection manager

---

pilot/pkg/model/envoyfilter.go
pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go
pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch_test.go
releasenotes/notes/27084.yaml

Adds support for `INSERT_FIRST`, `INSERT_BEFORE`, and `INSERT_AFTER` insert operations for HTTP_ROUTE's in EnvoyFilter.  Similar to filters, the order of routes matter, so `ADD` is insufficient
part of https://github.com/istio/istio/issues/26692
[ ] Docs
[ ] Security

Support for HTTP_ROUTE array insert in EnvoyFilter

---

istioctl/cmd/dashboard_test.go
istioctl/cmd/istiodconfig.go
istioctl/cmd/istiodconfig_test.go
istioctl/cmd/metrics_test.go
istioctl/cmd/root.go
pkg/test/kube/mock_client.go
releasenotes/notes/istiod-config.yaml

Currently there is `istioctl pc log` command for Envoy proxy.
This changes adds similar functionalities for `istiod` through
`controlz` API.
Implements #24922
[ ] Docs
[ ] Networking
[ ] Security
[ x ] User Experience

istioctl: add command to manage logging levels for istiod

---

tests/integration/tests.mk

This is handled by RequireSingleCluster. Adding this causes our k8s
version tests  to skip almost all versions
[ ] Docs
[ ] Networking
[ ] Security

Remove multicluster flag

---

tests/integration/tests.mk

The presubmit "all" target (that we use for postsubmits) runs with +integ on, but does not include it when listing directories via `go list`. 
[ ] Docs
[ ] Networking
[ ] Security

include integ build tag in go list for presubmit target

---

tools/bug-report/pkg/bugreport/bugreport.go
tools/bug-report/pkg/cluster/cluster.go
tools/bug-report/pkg/content/content.go

- replace "cluster-info dump" with "config current-context" and display this in the logs and CLI
- remove noisy log about missing owning deployment

Minor UX fixes to bug-report

---

Makefile.core.mk
common/scripts/setup_env.sh

Replaced hardcoded "amd64" with env. variables to enable build on other platforms. Set TARGET_ARCH on s390x platform.
[ ] Docs
[ ] Networking
[ ] Security

Build on s390x platform

---

pilot/pkg/config/kube/ingress/status.go

Don't stop processing ingress status updates just because a record is found that doesn't need to be updated, as there may be records later in the list that do need to be updated.
[ ] Docs
[x] Networking
[ ] Security

Fix ingress status update bug (istio#27523)

---

pilot/pkg/model/push_context.go
pilot/pkg/model/service.go
tests/integration/pilot/endpointslice/endpointslice_test.go

Caching the cluster VIPs only happens when we initServiceRegistry in the push context. We skip that if no services were changed. In that case, we need copy the cluster vip cache from the previous push context.

fix cluster vip resolution for multi-cluster

---

pilot/pkg/serviceregistry/serviceentry/conversion.go
pilot/pkg/serviceregistry/serviceentry/conversion_test.go

Aside from consistency/completeness, this is really useful for TLS
origination. Rather than modifying apps (to switch port from 80 to 443,
but stay plaintext, which is weird), we can transparently add tls
origination like:
```yaml
metadata:
name: httpbin
spec:
hosts:
- httpbin.org
ports:
- number: 80
name: http
protocol: HTTP
targetPort: 443
resolution: DNS
---
metadata:
name: originate-tls
spec:
host: httpbin.org
trafficPolicy:
tls:
mode: SIMPLE
```
[ ] Docs
[ ] Networking
[ ] Security
Pull …

Support TargetPort for DNS Service Entry

---

istioctl/cmd/root.go

Before:
```
omResourceDefinition
2020-09-24T22:58:14.733523Z     info    klog    apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
2020-09-24T22:58:14.735641Z     info    klog    apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
2020-09-24T22:58:14.737788Z     info    klog    apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
2020-09-24T22:58:14.740332Z     info    klog    apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use …
```

Fix excessive logs in istioctl operations

---

pilot/pkg/model/push_context.go
pilot/pkg/networking/core/v1alpha3/gateway_simulation_test.go
pilot/pkg/networking/core/v1alpha3/listener_test.go
pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
pilot/pkg/networking/core/v1alpha3/tls.go
pilot/pkg/simulation/traffic.go
pilot/test/xdstest/validate.go

This is just expanding testing. This covers the outbound passthrough cases, and captures one (known) bug.
Additionally, I noticed some incorrect logic in the validation that I fixed.

Add traffic passthrough testing with simulation

---

pilot/pkg/xds/ads_test.go
pilot/pkg/xds/cds.go
pilot/pkg/xds/eds.go
releasenotes/notes/push-cds-and-eds-on-virtualservice-update.yaml

Currently, VirtualService changes do not trigger CDS updates.
Istio is supposed to transitively include all destinations specified in
the VirtualService as part of the CDS. This is correctly calculated
after https://github.com/istio/istio/pull/20408 was included, but if the
change is actually made to the virtualservice and no subsequent changes
are made to the DestinationRule or Service, the new cluster will not
actually get pushed.
Only LDS & RDS trigger, so we will route to a nonexistent cluster,
resulting in 503 NR errors in envoy until a full push of clusters is
triggered again.
Fixes https://github.com/istio/istio/issues/27650
[ ] Docs
[X] Networking
[ ] Security
[ ] Test and …

xds: push cds on vs update

---

pilot/pkg/model/authentication_test.go
pilot/pkg/model/jwks_resolver.go
pilot/pkg/model/jwks_resolver_test.go
pilot/pkg/model/test/mockopenidserver.go

This should have no real impact on the production code, other than a new
variable that is set to the same value it was previously but set
different for tests (to avoid slow 1s retries).
[ ] Docs
[ ] Networking
[ ] Security

Speed up JWKS tests (15s -> 0.5s)

---

pilot/pkg/config/kube/crdclient/client_test.go

Saw that this test was missing, might add some confidence when adding the status subresource.

Add Update test to Client Go

---

pilot/pkg/networking/core/v1alpha3/gateway.go
pilot/pkg/networking/core/v1alpha3/gateway_test.go

* Stop creating invalid double wildcard domains
For https://github.com/istio/istio/issues/25350
Does not fully fix the problem, see envoy issue
* Add release notes
(cherry picked from commit 0e8aebca29dc1dd0df1af01e5701176f39fb7d43)
[ ] Docs
[ ] Networking
[ ] Security

[1.6] Stop creating invalid double wildcard domains (#27362)

---

pkg/test/echo/docker/Dockerfile.app_sidecar_base_centos
pkg/test/echo/docker/Dockerfile.app_sidecar_centos_7
pkg/test/framework/components/echo/kube/deployment.go
prow/lib.sh
tools/build-base-images.sh
tools/buildx-gen.sh
tools/istio-docker.mk
tools/skip-image.sh

Skip distroless for `app-*` images. These add substantial amount of load
to CI, for no benefit. They are NOT distroless images, we just build
everything 2x.

Optimize docker building

---

pilot/pkg/bootstrap/server.go
pilot/pkg/secrets/kube/multicluster.go
pilot/pkg/secrets/kube/secrets.go
pilot/pkg/secrets/kube/secrets_test.go
pilot/pkg/secrets/model.go
pilot/pkg/xds/bench_test.go
pilot/pkg/xds/fake.go
pilot/pkg/xds/sds.go
pilot/pkg/xds/sds_test.go

* Add testing for authorization
* Add testing for multicluster
* Add support for multicluster. credentials are read from ANY cluster; authorization is check only in the local (to proxy) cluster.

Add multicluster support for Gateway SDS

---

pilot/pkg/features/pilot.go
pilot/pkg/xds/ads.go

We are seeing "2020-09-25T18:36:23.207985Z	info	ads	Timeout writing sidecar~10.100.181.200" in some envs occasionally. 
Making this configurable to test if it helps
[ ] Docs
[ ] Security

make xds send timeout configurable

---

istioctl/pkg/util/configdump/listener.go
istioctl/pkg/util/configdump/route.go

Resolves https://github.com/istio/istio/issues/27665
No test added.  I don't want to check in Envoy config, and I don't have an integration test that includes a 1.6.x ingressgateway as part of the mesh.

Always treat Envoy routes as v3, even if Envoy doesn't

---

tests/integration/pilot/common/routing.go

No need to log the list of ~50 responses (in mc mode). The count is what we're checking here.

long log on shifting test failure

---

pkg/kube/configmapwatcher/configmapwatcher.go
pkg/kube/configmapwatcher/configmapwatcher_test.go

As part of #27707. This is meant to be used to create a new configMapWatcher in pkg/config/mesh/watcher.go
If in the future there are other ConfigMaps that need to be watched, this could potentially be lifted up into the Server object. The field selector would be replaced by a map from ConfigMap name to callback, the queue objects would also be ConfigMap names, etc.

Controller for watching a ConfigMap

---

pilot/pkg/serviceregistry/kube/controller/controller_test.go
pilot/pkg/serviceregistry/kube/controller/pod_test.go

Previously, we skip tests where the k8s bug is hit. However, we only did
this for some of the tests, so other ones were still flaking. Now, I
tested we can simply retry the create and it will consistently work. I
then abstracted this out to a function that is used by all tests. I
tested this 20k times without failure.
[ ] Docs
[ ] Networking
[ ] Security

Fix kube controller test flakes.

---

istio.deps

This PR updates the proxy SHA for release-1.6

Update SHAs to pick up Envoy CVE and spanKind

---

pkg/test/framework/components/istio/eastwest.go
pkg/test/framework/components/istio/operator.go
samples/multicluster/gen-eastwest-gateway.sh

This removes istioctl from the script, the user can use the generated yaml with`isitoctl generate` and `kubectl` or modify it and use it how they see fit. We will need to update any docs that reference this script. 
fixes https://github.com/istio/istio/issues/27644

eastwest sample script generates operator yaml

---

pkg/config/mesh/watcher.go
pkg/config/mesh/watcher_test.go
pkg/kube/configmapwatcher/configmapwatcher.go
pkg/kube/configmapwatcher/configmapwatcher_test.go

As part of #27707. The intent is that this will be used when a local file isn't provided
[ ] Docs
[X] Networking
[ ] Security

Add NewConfigMapWatcher for mesh config

---

security/pkg/nodeagent/cache/secretcache.go
security/pkg/nodeagent/cache/secretcache_test.go

Fixes https://github.com/istio/istio/issues/24609.
Istio installation fails when using an existing CA, unless the cert chain ends with a newline.
The reason is that the code concatenates the cert chain with the root cert, resulting in an invalid PEM certificate due the following line: 
```
-----END CERTIFICATE----------BEGIN CERTIFICATE-----
``` 
This PR makes sure that when concatenating certificates they are always separated by a newline. If the cert chain doesn't end with a newline, it adds it resulting in a valid 
```
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
```
[ ] Docs
[ ] Networking
[x] Security
[ ] Developer …

make sure concatenated certs are separated by new lines

---

galley/pkg/config/analysis/analyzers/util/config.go

To fix https://github.com/istio/istio/issues/27791
Before:
```
$ istioctl analyze --all-namespaces
Warning [IST0102] (Namespace kube-node-lease) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kube-node-lease istio-injection=enabled' to enable it, or 'kubectl label namespace kube-node-lease istio-injection=disabled' to explicitly mark it as not needing injection
Warning [IST0102] (Namespace local-path-storage) The namespace is not enabled for Istio injection. Run 'kubectl label namespace local-path-storage istio-injection=enabled' to enable it, or 'kubectl label namespace local-path-storage istio-injection=disabled' to explicitly mark it as not needing injection
Error: Analyzers found issues when analyzing all namespaces.
See …
```

Exclude kube system namespaces for istioctl analyze

---

galley/pkg/config/analysis/analyzers/injection/injection.go
galley/pkg/config/analysis/msg/messages.gen.go
galley/pkg/config/analysis/msg/messages.yaml

To fix https://github.com/istio/istio/issues/27390
Before:
```
$ istioctl analyze --all-namespaces
Warning [IST0102] (Namespace kube-node-lease) The namespace is not enabled for Istio injection. Run 'kubectl label namespace kube-node-lease istio-injection=enabled' to enable it, or 'kubectl label namespace kube-node-lease istio-injection=disabled' to explicitly mark it as not needing injection
Warning [IST0102] (Namespace local-path-storage) The namespace is not enabled for Istio injection. Run 'kubectl label namespace local-path-storage istio-injection=enabled' to enable it, or 'kubectl label namespace local-path-storage istio-injection=disabled' to explicitly mark it as not needing injection
Error: Analyzers found issues when analyzing all namespaces.
See …
```

Use Info instead of Warn for istioctl analyzer istio injection

---

go.sum
tools/bug-report/pkg/bugreport/bugreport.go
tools/bug-report/pkg/common/common.go

The following Istio control plane revisions/versions were found in the cluster:
Revision istio-169:
&version.MeshInfo{
{
Component: "istiod",
Info:      version.BuildInfo{Version:"1.6.9-gke.0-96a48092d219e3e087343165180f60b396c4d421", GitRevision:"dirty", GolangVersion:"", BuildStatus:"Modified", GitTag:"1.6.9-gke.0-96a48092d219e3e087343165180f60b396c4d421"},
},
}
The following proxy revisions/versions were found in the cluster:
Revision istio-169: Versions {1.6.9-gke.0}

Add revision and version info to bug-report

---

pilot/cmd/pilot-agent/main.go
pkg/istio-agent/agent.go
pkg/istio-agent/xds_proxy.go

Change-Id: I0dee2da459f05ee5a32a23438a03ab516877cd6f
Envoy - when using google-grpc - supports adding custom headers. 
This is needed when the XDS server is running behind external load balancers, or needs special handling.
Note that "ClusterID" is already added to headers. 
Using the same mechanism we use for node metadata - env variables - this is not a candidate for 
ProxyConfig because we can't guarantee support for all cases. 
[ ] Docs
[ ] Networking
[ ] Security …

Add support for custom headers in the agent proxy

---

istioctl/cmd/analyze.go
istioctl/cmd/analyze_test.go

Follow up for https://github.com/istio/istio/pull/27793
Based on @esnible https://github.com/istio/istio/issues/27390#issuecomment-696908674
> We should not say ERROR if the highest level is WARNING
Before:
```
$ istioctl analyze --all-namespaces
Warning [IST0102] (Namespace default) The namespace is not enabled for Istio injection. Run 'kubectl label namespace default istio-injection=enabled' to enable it, or 'kubectl label namespace default istio-injection=disabled' to explicitly mark it as not needing injection.
Error: Analyzers found issues when analyzing all namespaces.
See https://istio.io/v1.8/docs/reference/config/analysis for more information about causes and resolutions.
```
After:
```
$ ./out/linux_amd64/istioctl analyze --all-namespaces
Warning [IST0102] (Namespace default) …
```

istioctl analyze: do not error if the threshold is warning

---

go.mod
pilot/pkg/config/kube/crdclient/client.go
pilot/pkg/config/kube/crdclient/client_test.go
pilot/pkg/config/kube/crdclient/gen/types.go.tmpl
pilot/pkg/config/kube/crdclient/types.gen.go

Part of this is already in #27761 tested and working. For now, only supporting regular [RFC 6902](https://tools.ietf.org/html/rfc6902) json patch, not strategic merge or any of the other k8s patch types. 
As far as the auto-registration code is concerned, this simple patch helps a lot to avoid conflicts when writers have completely separate concerns.

support PATCH in crdclient

---

CODEOWNERS

This is to prevent uncontrolled modifications to values.yaml, which we will try to deprecate in 1.9.

Require approval from Environments leads for any values.yaml changes

---

pilot/pkg/xds/fake.go
pkg/istio-agent/xds_proxy.go
pkg/istio-agent/xds_proxy_test.go

Extend testing. Fix a bug when reusing closed upstream error channel

xdsproxy: add tests for reconnect

---

pkg/istio-agent/health/health_probers_test.go

Add tests for `health_probers.go` in `istio-agent`
[ ] Docs
[ ] Networking
[ ] Security

Add tests for health probers

---

pkg/kube/inject/watcher.go
pkg/kube/inject/webhook.go

Work towards being able to use a ConfigMap watcher instead for #27707
[ ] Docs
[X] Networking
[ ] Security

Refactor file watching for injection

---

pkg/istio-agent/xds_proxy.go

This is refreshed on every call regardless of the expiry, remove to
avoid confusion.
(cherry picked from commit 47c202d5c029d69f0c66baf8de4148a8b77a4d92)
[ ] Docs
[ ] Networking
[ ] Security

Remove unused/wrong expiry on token

---

istioctl/pkg/xds/client.go
pilot/pkg/bootstrap/configcontroller.go
pilot/pkg/networking/apigen/apigen_test.go
pilot/pkg/xds/ads_test.go
pilot/pkg/xds/eds_test.go
pilot/pkg/xds/fake.go
pilot/pkg/xds/lds_test.go
pkg/adsc/adsc.go
pkg/adsc/adsc_test.go
pkg/istio-agent/local_xds_generator.go

This pr mainly addresses two issues:
1. grpc client will reconnect, reply on it and so no connection leak
2.  auto rotate tls certificate

rework on ads client 

---

pilot/pkg/config/kube/ingress/controller.go

Fixes https://github.com/istio/istio/issues/28004
In a contrived setup with 1qps limit this brings startup time from 104s to 19s. In a real cluster, 3.84s to 600ms

Reduce calls to api server on init

---

pkg/kube/inject/watcher_test.go

Fixes #28012
[ ] Docs
[X] Networking
[ ] Security

Wait for injector ConfigMap watcher to sync in flaky test

---

pilot/pkg/bootstrap/mesh.go
pilot/pkg/bootstrap/sidecarinjector.go
pkg/kube/inject/watcher.go
pkg/kube/inject/watcher_test.go
pkg/kube/inject/webhook.go
pkg/kube/inject/webhook_test.go

As part of #27707
[ ] Docs
[X] Networking
[ ] Security
This should only affect istiod deployments that are manually edited to remove mounting of the inject volume

Watch injector ConfigMap when local config is absent

---

pkg/bootstrap/option/convert.go
releasenotes/notes/zipkin-datadog-host-ip-interpretation.yaml

This is to support some tracer setting (Datadog, Zipkin), where `$(HOST_IP)` is used for address. Tracer address used to be specified within proxy container params, and thus could be interpreted with pod HOST_IP env var. Now tracer config is passed in with mesh config volumn at gateway, k8s env var interpretation does not work. This is to achieve the same interpretation as k8s.
fix https://github.com/istio/istio/issues/27911 and fix https://github.com/istio/istio/issues/27016

Add host ip interpretation into pilot agent

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_builder.go
pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go

This original port is used by tunnel between client sidecar and server sidecar.
Once the request is tunneled at client sidecar, the server sidecar must recover the original network attributes when extract the request from the tunnel.
Follow up PRs will address the cases that endpoints port are not unique. 
For H2 BTS tunnel, I will introduce another http connection pool to read this metadata and encode the metadata into the upstream request.
Imagine the k8s service is 
```
name: foo.ns
port: 80
target_port: 8080
```
So the outbound EDS cluster config is: 
```
CDS:
cluster: outbound|80||foo.ns
cluster_metadata: 
- original_port: 8080
endpoints:  EDS_XYZ
```
```
EDS:
name: EDS_XYZ
- address: 1.2.3.4:15009   # server pod has sidecar
- address: 1.2.3.5:15009   # server pod has sidecar
- …
```

add cluster NetworkingMetadata

---

pilot/pkg/model/context.go
pilot/pkg/model/context_test.go
pilot/pkg/model/push_context_test.go
pilot/pkg/model/service.go
pilot/pkg/networking/core/v1alpha3/fake.go
pilot/pkg/networking/core/v1alpha3/listener_test.go
pilot/pkg/serviceregistry/aggregate/controller.go
pilot/pkg/serviceregistry/aggregate/controller_test.go
pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/controller_test.go
pilot/pkg/serviceregistry/memory/discovery.go
pilot/pkg/serviceregistry/mock/discovery.go
pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
pilot/pkg/xds/ads.go

I noticed that we do not propogate errors in ADS - instead, we return
`nil`, which seems like a bug. In the process, I found most of the
errors never actually occur. I cleaned up these interfaces to not return
an `error`. The one remaining real error case is a send error (typically
timeout). Before this PR, we would exit the stream but with `nil`, now
we properly return the error so its exposed to clients
[ ] Docs
[ ] Networking
[ ] Security

Propogate ADS errors and remove errors that never occur

---

pilot/pkg/model/context.go
pilot/pkg/xds/ads.go
pilot/pkg/xds/debug.go
releasenotes/notes/fix-connection-lock.yaml

[Manual cherry-pick](https://github.com/istio/istio/issues/28082)  of #26260. Needed to prevent rare Pilot deadlock and memory leak in Syncz debug endpoint. @howardjohn @hzxuzhonghu  
[ ] Docs
[X] Networking
[ ] Security

Manual cherry-pick of https://github.com/istio/istio/pull/26260

---

pkg/test/framework/components/bookinfo/kube.go
pkg/test/framework/components/istio/config.go
pkg/test/framework/components/namespace/kube.go
pkg/test/framework/components/namespace/namespace.go
pkg/test/framework/components/namespace/namespace_test.go
pkg/test/framework/resource/flags.go
pkg/test/framework/resource/settings.go
tests/integration/README.md

Add test flag to overwrite the default namespace label for sidecar
injection. If a namespace is created with a revision label, the
label will remain as is.
[ ] Docs
[ ] Networking
[ ] Security

Add test flag to overwrite default namespace label with revision

---

tests/integration/pilot/common/apps.go

Setting this value breaks the VM tests in the multi-cluster pilot job. Due to this setting, WorkloadEntries aren't created in all clusters, only the ones that the agent connects to. 
In the future we will need to improve auto-registration to be compatible with multi-primary multicluster.

fix multicluster vm test

---

tests/integration/pilot/ingress/ingress_test.go

Resolve: https://github.com/istio/istio/issues/28113
[ ] Docs
[ ] Networking
[ ] Security

[release-1.7] Manual cherry-pick: skip Ingress test on unsupported k8s versions (#25853)

---

istioctl/pkg/multicluster/apply_test.go
istioctl/pkg/multicluster/cluster.go
istioctl/pkg/multicluster/cluster_test.go
istioctl/pkg/multicluster/env.go
istioctl/pkg/multicluster/env_test.go
istioctl/pkg/multicluster/remote_secret.go
istioctl/pkg/multicluster/remote_secret_test.go
pkg/kube/client.go
pkg/test/framework/components/istio/operator.go

Currently, creation of a remote secret requires that the istio-reader-service-account has been installed on the remote cluster. This will fail if we haven't already installed Istio on the remote cluster.
Conversely, the installation of Istio on the remote cluster requires that the primary cluster has already been given its remote secret. If this doesn't happen, Istio workloads (e.g. istio-ingressgateway) will never be able to start because the control plane in the primary cluster will reject the requests.
This creates a chicken-or-the-egg problem which makes installation difficult.
With this change, we can modify the installation flow for remote clusters to the following:
1) Install Istio on primary cluster
2) Create remote secret and install in primary cluster
3) Install Istio on remote …

Allow create-remote-secret to create istio-reader-service-account

---

pilot/pkg/features/pilot.go
pilot/pkg/networking/core/v1alpha3/listener_builder.go

Fixes https://github.com/istio/istio/issues/28026
This PR is for 1.6 only, as it is intended only for in place upgrade between certain 1.5 -> 1.6 upgrade paths. This change has no impact by default to minimize potentially high impact changes so late into the 1.6 release

Conditionally keep inbound listeners

---

Makefile.core.mk

We currently set `STATIC=0 LDFLAGS='-extldflags -static -s -w'` as part of the
build. This does not make much sense, since STATIC sets LDFLAGS to
empty, so we don't pass `-static -s -w`.
I believe we do want to pass these flags, as they were originally added
for a reason.
Binary size changes for istioctl, agent, and pilot in mb:
```
114 -> 81
104 -> 75
108 -> 77
```
Helps with https://github.com/istio/istio/issues/26232
[ ] Docs
[ ] Networking
[ ] Security

Remove conflicting STATIC variable from build

---

Makefile.core.mk

I bumped the image 2 values since a prior version, dev.7, had vulnerabilities and I'm not sure how long the scanner would hold on to those results.

[release-1.7] Bump the build image

---

pkg/test/framework/components/istio/config.go
pkg/test/framework/components/istio/operator.go

Save all manifests used for deployments instead of having only
the last one.
Also dump all manifests used when a test fails.

Support more than one deployment per cluster

---

pilot/pkg/networking/core/v1alpha3/httproute.go
pilot/pkg/networking/core/v1alpha3/route/route.go
pilot/pkg/networking/core/v1alpha3/route/route_test.go

MaxGrpcTimeout is broken in new proxy.
Istio API is untouched.
Fix #28089 
[ ] Docs
[ ] Networking
[ ] Security

[release-1.8] cherry-pick Deprecate MaxGrpcTimeout in go-control-plane (#28089)

---

tools/bug-report/pkg/bugreport/bugreport.go
tools/bug-report/pkg/cluster/cluster.go

Found during debugging of https://github.com/istio/istio/issues/27177
More Info: https://github.com/istio/istio/pull/27794
Before:
```
$ istioctl bug-report
...
Fetching proxy logs for the following containers:
istio-system/istio-ingressgateway/istio-ingressgateway-5cf694469b-2677k/istio-proxy
istio-system/istiod/istiod-7c65b8f5cf-rssbd/discovery
local-path-storage/local-path-provisioner/local-path-provisioner-78776bfc44-pf6bv/local-path-provisioner
Fetching Istio control plane information from cluster.
Running istio analyze on namespace istio-system.
Running istio analyze on namespace local-path-storage.
Creating archive at /home/shaansar/Projects/src/istio.io/istio/bug-report.tgz.
Cleaning up temporary files in /tmp/bug-report.
Done.
```
After:
```
$ istioctl bug-report
...
Fetching …
```

istioctl bug-report: skip system namespaces to analyze

---

galley/pkg/config/analysis/msg/messages.gen.go
galley/pkg/config/analysis/msg/messages.yaml

Part of https://github.com/istio/istio/issues/27960
Based on https://github.com/istio/istio/issues/27960#issuecomment-708655493

istioctl analyze set warn for no caCertificates in DestinationRule

---

istioctl/cmd/proxyconfig.go

Makes it possible to do `istioctl proxy-config secrets ...`
[ ] Docs
[ ] Networking
[ ] Security

Add 'secrets' alias to 'istioctl proxy-config secret' command

---

pkg/test/framework/components/istio/eastwest.go
samples/multicluster/gen-eastwest-gateway.sh

Use `--arg <value>` instead of environment vars to improve UX. 
fixes #28197

refactor eastwest script to use args

---

tests/integration/operator/switch_cr_test.go

Otherwise they stay around and can cause other tests to fail.
In a concrete example, deployment "istiod-canary" stays live
and interferes in pilot's TestMultiRevision test, which also
deploys a "istiod-canary", but, since a deployment with that
name already exists, operator doesn't redeploy it, because it's
already there.

Delete istiod pods on cleanup

---

pilot/pkg/bootstrap/configcontroller.go
pilot/pkg/config/kube/ingress/conversion.go
pilot/pkg/config/kube/ingress/conversion_test.go
pilot/pkg/config/kube/ingress/status.go
pilot/pkg/config/kube/ingress/status_test.go

Addresses #25308 
Before, we had two different places where we decided (1) which Ingress resources the controller should process and (2) which Ingress resources the StatusWatcher should update statuses for. However, the controller and status watcher should operate on the same set of Ingresses.
The old StatusWatcher mechanism did not take `IngressClass` into account at all when deciding whether to update Ingress status so this PR updates it to use the same decision mechanism as the main controller.
[ ] Docs
[x] Networking
[ ] Security
Please check any characteristics that apply to this pull …

Update Ingress status for same set of Ingresses that the controller handles

---

tests/integration/operator/switch_cr_test.go

Otherwise they stay around and can cause other tests to fail.
In a concrete example, deployment "istiod-canary" stays live
and interferes in pilot's TestMultiRevision test, which also
deploys a "istiod-canary", but, since a deployment with that
name already exists, operator doesn't redeploy it, because it's
already there.
Manual cherrypick of https://github.com/istio/istio/pull/28205

[release-1.7] Delete istiod pods on cleanup

---

pilot/pkg/security/authz/builder/testdata/action-audit-HTTP-for-TCP-filter-in.yaml
pilot/pkg/security/authz/builder/testdata/action-audit-HTTP-for-TCP-filter-out.yaml
pilot/pkg/security/authz/builder/testdata/action-deny-HTTP-for-TCP-filter-in.yaml
pilot/pkg/security/authz/builder/testdata/action-deny-HTTP-for-TCP-filter-out.yaml
pilot/pkg/security/authz/builder/testdata/all-fields-in.yaml
pilot/pkg/security/authz/builder/testdata/all-fields-out.yaml
pilot/pkg/security/authz/builder/testdata/multiple-policies-out.yaml
pilot/pkg/security/authz/builder/testdata/single-policy-in.yaml
pilot/pkg/security/authz/builder/testdata/single-policy-out.yaml
pilot/pkg/security/authz/model/generator.go
pilot/pkg/security/authz/model/generator_test.go
pilot/pkg/security/authz/model/model.go
pilot/pkg/security/authz/model/principal.go
pkg/config/security/security.go
pkg/config/security/security_test.go
pkg/config/validation/validation.go
pkg/config/validation/validation_test.go
releasenotes/notes/remote-ip.yaml
releasenotes/template.yaml
tests/integration/security/authorization_test.go
tests/integration/security/jwt_test.go
tests/integration/security/main_test.go
tests/integration/security/testdata/authz/v1beta1-ingress-gateway.yaml.tmpl
tests/integration/security/util/authn/authn_util.go

cherry-pick https://github.com/istio/istio/pull/27906
* create remoteIpBlocks and update ipBlocks for AuthorizationPolicy
By adding remoteIpBlocks and notRemoteIpBlocks in Source,
an AuthorizationPolicy can trigger actions based on the original
client IP address gleaned from the X-Forwarded-For header or the
proxy protocol. The ipBlocks and notIpBlocks fields have also been
updated to use direct_remote_ip in Envoy instead of source_ip
* use correct attribute for RemoteIpBlocks
* fix unit tests and add integration tests for remote.ip attribute
* fix notRemoteIp integration test
* initialize headers if it is nil
* Combine remoteIp tests into IngressGateway test and add release note
* add titles to links
* remove unneeded tests
* fix quotes in releasenote, run make gen
* make upgradeNotes a …

Add remoteIpBlocks functionality to AuthorizationPolicy (#27906)

---

pilot/pkg/config/kube/ingress/status.go

This warning spams clusters that have no ingress service (#28252)
[ ] Docs
[x] Networking
[ ] Security

Remove unnecessary warning log from ingress status watcher

---

pilot/pkg/model/context.go
pilot/pkg/model/context_test.go
releasenotes/notes/28269.yaml

[ ] Docs
[X] Networking
[ ] Security
* This PR changes the algorithm of choosing the IP address to bind `inbound` listener to in case of a node with multiple IP addresses
* In `k8s` case
* nodes typically have only a single IP address
* this PR doesn't …

pilot: GlobalUnicastIP of a model.Proxy should be set to the 1st applicable IP address in the list

---

galley/pkg/config/analysis/analyzers/util/config.go
tools/bug-report/pkg/bugreport/bugreport.go
tools/bug-report/pkg/bugreport/flags.go
tools/bug-report/pkg/config/config.go

To fix https://github.com/istio/istio/issues/27988
Good to merge after https://github.com/istio/istio/pull/27980
Before:
```
$ istioctl bug-report --exclude=ns1,ns2
Running with the following config: 
istio-namespace: istio-system
...
exclude:  { Namespaces: ns1 } AND { Namespaces: ns2 }
...
Fetching proxy logs for the following containers:
istio-system/istio-ingressgateway/istio-ingressgateway-5cf694469b-2677k/istio-proxy
istio-system/istiod/istiod-7c65b8f5cf-rssbd/discovery
kube-system//etcd-istio-testing-control-plane/etcd
kube-system//kindnet-8c86m/kindnet-cni
kube-system//kube-apiserver-istio-testing-control-plane/kube-apiserver
kube-system//kube-controller-manager-istio-testing-control-plane/kube-controller-manager
kube-system//kube-proxy-rn9g6/kube-proxy …
```

istioctl bug-report: do not override system namespaces if --exclude flag is provided

---

tests/integration/pilot/ingress_test.go

Adds an integration test to make sure ingress status is updated for ingresses we're handling (#28225) 
[ ] Docs
[x] Networking
[ ] Security

Add ingress status integration test

---

pilot/pkg/model/context.go
pilot/pkg/model/context_test.go
releasenotes/notes/28269.yaml

* cherry-picking https://github.com/istio/istio/pull/28260 into `release-1.8`

cherry-pick: pilot: GlobalUnicastIP of a model.Proxy should be set to the 1st applicable IP address in the list (#28260)

---

istioctl/pkg/writer/envoy/configdump/route.go

```
NOTE: This output only contains routes loaded via RDS.
NAME                                                                                                     DOMAINS                      MATCH                  VIRTUAL SERVICE
https.443.https-443-ingress-service1-default-0.service1-istio-autogenerated-k8s-ingress.istio-system     *                            /*                     404
https.443.https-443-ingress-service2-default-0.service2-istio-autogenerated-k8s-ingress.istio-system     *                            /*                     404
http.80                                                                                                  service1.demo.........io     /*                     service1-demo-......-io-service1-istio-autogenerated-k8s-ingress.default
http.80 …
```

Show empty routes in pc routes

---

pilot/pkg/model/envoyfilter.go
pkg/config/validation/validation.go
pkg/config/xds/xds.go

Fixes https://github.com/istio/istio/issues/26390
Example run:
```
istioctl validate -f /tmp/envoyfilter.yaml
"/tmp/envoyfilter.yaml" has warnings:
* EnvoyFilter//custom-protocol: Envoy filter: unknown field "address" in envoy.config.endpoint.v3.LbEndpoint
```

Add warnings for unknown fields in EnvoyFilter

---

cni/pkg/install-cni/pkg/install/cniconfig.go
cni/pkg/install-cni/pkg/install/cniconfig_test.go
cni/pkg/install-cni/pkg/install/testdata/list-with-istio.conflist
cni/pkg/install-cni/pkg/install/testdata/list-with-istio.conflist.golden
releasenotes/notes/27771.yaml

Fixes: #27771 
Before the PR, istio-cni plugin configuration was inserted into the CNI plugin list everytime (e.g. after node reboot), which resulted in multiple istio-cni plugins in the final config. Which caused `iptables-restore` to fail and blocked `azure-cni` from making network requests needed to assign pod IP, causing pods fail to start.
PR adds code to remove existing `type: istio-cni` plugins from the config, before inserting the new plugin.
[ ] Docs
[X] Networking
[ ] Security
[ ] Does not have any changes that …

When installing istio-cni remove existing istio-cni plugin before inserting a new one

---

pilot/pkg/config/kube/ingress/conversion.go
pilot/pkg/config/kube/ingress/status.go
pilot/pkg/config/kube/ingress/status_test.go

Before, if there was no `IngressService` specified, we would use the `app: ingressgateway` selector to find running IngressGateway instances. However, we should be taking into account  the `IngressSelector` config option (and use `istio: ingressgateway` as the default). Also adds a missing check for unspecified (`""`) IngressService (from #27751). 
However, before merging this, I'm pretty confused on why the behavior here is how it is in the first place: https://github.com/istio/istio/blob/22d9a05c0f85a9da74e17211d50087a7dc713dc5/pilot/pkg/config/kube/ingress/status.go#L184-L209
Why does it make sense to add the public IPs of nodes running IngressGateways to the Ingress's status if no IngressService is specified? The service meant to be exposed in the Ingress won't actually be reachable …

Make ingress gateway selector in status watcher match the one used to generate gateway

---

tests/integration/pilot/ingress_test.go

The sooner we get multicluster pilot test consistently passing, the sooner we can make it required and avoid having new things be added without passing under multi-cluster mode.

skip ingress test in multicluster

---

pilot/pkg/features/pilot.go
pilot/pkg/model/context.go
pilot/pkg/xds/ads.go
pilot/pkg/xds/ads_test.go
pilot/pkg/xds/monitoring.go
releasenotes/notes/backpressure.yaml

Fixes: #25685
At large scale, Envoy suffers from overload of XDS pushes, and there is
no backpressure in the system. Other control planes, such as any based
on go-control-plane, outperform Istio in config update propogations
under load as a result.
This changes adds a backpressure mechanism to ensure we do not push more
configs than Envoy can handle. By slowing down the pushes, the
propogation time of new configurations actually increases. We do this by
keeping note, but not sending, any push requests where that TypeUrl has
an un-ACKed request in flight. When we get an ACK, if there is a pending
push request we will immediately trigger it. This effectively means that
in a high churn environment, each proxy will always have exactly 1
outstanding push per type, and when the ACK is recieved …

Wait until ACK before sending additional pushes

---

istioctl/cmd/remove-from-mesh.go
istioctl/cmd/remove-from-mesh_test.go

To fix https://github.com/istio/istio/issues/28186
Before:
Where `local-path-provisioner` don't have sidecar as it is in system namespace, still we get.
```
$ istioctl experimental remove-from-mesh deploy local-path-provisioner -n local-path-storage
deployment "local-path-provisioner.local-path-storage" updated successfully with Istio sidecar un-injected.
```
```
$ istioctl experimental remove-from-mesh deployment istio-egressgateway  -n istio-system
Error: 1 error occurred:
* failed to update deployment "istio-egressgateway.istio-system" for service "istio-egressgateway.istio-system" due to Deployment.apps "istio-egressgateway" is invalid: spec.template.spec.containers: Required value
```
After:
```
$ ./out/linux_amd64/istioctl x rm deploy local-path-provisioner -n local-path-storage …
```

remove-from-mesh: skip system namespace to remove sidecar

---

pkg/istio-agent/xds_proxy.go

This solves two main issues:
1. prevent upstream receive goroutine from leaking
2. split upstream request handling and response handling, as we know the send could take very long

Xds proxy improve

---

istioctl/pkg/install/verify.go

resolve: https://github.com/istio/istio/issues/28284#issuecomment-716934577
Fix the manifests path missing issue for `verify-install` command in the development build:
```
This will install the Istio 1.9.0 profile into the cluster. Proceed? (y/N) y
✔ Istio core installed
✔ Istiod installed
✔ Ingress gateways installed
✔ Installation complete                                                                                                                                                  
Error:
compiled in charts not found in this development build,
use manifests as local charts instead e.g:
- istioctl install --set hub=gcr.io/istio-testing -d manifests/
- or istioctl operator init --hub=gcr.io/istio-testing -d manifests/
- or run make gen-charts and rebuild istioctl
```
[ ] Configuration …

fix manifestpath for verify install.

---

galley/pkg/config/analysis/analyzers/injection/injection-image.go
istioctl/cmd/injector-list.go
istioctl/cmd/root.go
releasenotes/notes/injector-list.yaml

Along with https://github.com/istio/istio/pull/27737 resolves https://github.com/istio/istio/issues/23892
See https://docs.google.com/document/d/1E4bda0RcmKQOpn7_h3dEcKBLCARK1MsbNZn3OUm-VSE/edit?ts=5f7f4484# for a user story showing how this would be used.
This is the non-admin listing of "control planes" by listing injectors.
The basic idea is that users, especially during a canary, might forget what state their canary is in -- which control planes they are using, and which namespaces are linked to which control plane.  The output is something like
```
$ istioctl x injector list
NAMESPACE  ISTIO-REVISION POD-REVISIONS
bookinfo   18x            default: 6 NEEDS RESTART: 6
default    default        default: 1
ibm-system                <non-Istio>: 7
INJECTOR-HOOK …
```

List Istio injectors

---

istioctl/cmd/root.go

Attempt to fix https://github.com/istio/istio/issues/28005
Based on @linsun comments
> I recommend us enhance it to search for sidecar innjector cm in the -n ns.

kube-inject: hide namespace flag in favour of istioNamespace

---

cni/cmd/istio-cni/main_test.go

The `interceptRuleMgrType` decalred in main.go as "iptables", it would
be changed to "mock" in func resetGlobalTestVariables().
When run single test, it would be "iptables" and make test failed.
Fix #28333
[ ] Docs
[ ] Networking
[ ] Security
/release-note-none

cni: fix order dependent test failures

---

pkg/test/framework/components/stackdriver/stackdriver.yaml

See
https://github.com/istio/proxy/blob/release-1.6/test/envoye2e/stackdriver_plugin/cmd/Makefile#L21
[ ] Docs
[ ] Networking
[ ] Security

Update fake-stackdriver to the one used in istio/proxy release-1.6

---

pkg/istio-agent/xds_proxy.go

Fix #28382
[ ] Docs
[ ] Networking
[X] Security

istio-agent: only send NDS if DNS is enabled

---

CODEOWNERS

This is currently owned by docs which doesn't make sense as its scripts and install YAMLs owned by networking

Add OWNERS for samples/multicluster

---

pilot/pkg/serviceregistry/kube/conversion.go
pilot/pkg/xds/mesh_network_test.go
releasenotes/notes/28406.yaml

This allows usecases like https://github.com/istio/istio/issues/28381 without having to manually specify gateway IP in meshNetworks.

support service.spec.externalIPs for multi-network gateway address

---

pilot/pkg/config/kube/ingress/controller.go
tests/integration/pilot/ingress_test.go

Fixes the issue surfaced in #26919. Before this change, the Ingress controller was filtering out updates to Ingress config. This made it so that even after a user configured an Ingress to no longer be targeted by Istio, we would just keep on handling the routes.
Also adds integration test coverage for this case.
[ ] Docs
[x] Networking
[ ] Security

Make ingress controller register updates to Ingress config

---

pilot/pkg/networking/core/v1alpha3/httproute.go
pilot/pkg/networking/core/v1alpha3/httproute_test.go
pilot/pkg/networking/core/v1alpha3/route/route.go
pilot/pkg/networking/core/v1alpha3/route/route_test.go
pilot/pkg/networking/util/util.go

if we have domains like {foo, foo.local}, the order we build matters. If
foo is first, we will build the foo virtual host, then the foo.local.
But if foo.local is first, we build a single virtual host with both
domains, and then a second one with empty domain.
This is broken for three reasons
1. Empty domain list is rejected by envoy
2. The behavior is nondeterministic. Should have stable Service ordering
3. You may explicitly want the non-expanded versions

Fix duplicates in HTTP domains

---

prow/lib.sh

If we don't do this, calling the prow script might fail if we have clusters that persist throughout multiple runs. This happened to me while running tests locally, as I had a few other active kind clusters:
```
+ for cluster in $(kind get clusters)
+ kind export kubeconfig --name=primary
Set kubectl context to "kind-primary"
++ kind get nodes --name=primary
+ for node in $(kind get nodes --name="${cluster}")
+ kubectl annotate node primary-control-plane kind.x-k8s.io/registry=localhost:5000
error: --overwrite is false but found the following declared annotation(s): 'kind.x-k8s.io/registry' already has a value (localhost:5000)
```
You only hit this on the second run, as all nodes of the non-istio clusters have then already been annotated …

prow: overwrite existing node annotations

---

pkg/bootstrap/testdata/all_golden.json
pkg/bootstrap/testdata/auth_golden.json
pkg/bootstrap/testdata/authsds_golden.json
pkg/bootstrap/testdata/default_golden.json
pkg/bootstrap/testdata/running_golden.json
pkg/bootstrap/testdata/runningsds_golden.json
pkg/bootstrap/testdata/stats_inclusion_golden.json
pkg/bootstrap/testdata/tracing_datadog_golden.json
pkg/bootstrap/testdata/tracing_lightstep_golden.json
pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
pkg/bootstrap/testdata/tracing_stackdriver_golden.json
pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
pkg/bootstrap/testdata/tracing_tls_golden.json
pkg/bootstrap/testdata/tracing_zipkin_golden.json
pkg/bootstrap/testdata/xdsproxy_golden.json
tools/packaging/common/envoy_bootstrap.json

Addresses #28433. In short, this change is needed to keep certain requests from 1.7 proxies -> 1.6 proxies from 503ing.
Having the `strict_1xx_and_204_response_headers` envoy config enabled (default-on) makes it so that proxies will reject http responses having code 1xx/204 and having the "Transfer-Encoding" header present. Our proxies <=v.1.6.x will send such responses by default (this [envoy change](https://github.com/envoyproxy/envoy/pull/11458) was just merged ~5mos ago), resulting in our 1.7 proxies 503ing in those cases.
My main concern here (and I have been able to confirm this) is that this will introduce the same compatibility issue between 1.7 proxies that have this feature enabled -> 1.7 proxies that don't (since from the relevant Envoy PR, disabling the …

Disable strict_1xx_and_204_reponse_headers in envoy bootstrap config

---

pilot/pkg/features/pilot.go
pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/listener.go
pilot/pkg/security/model/authentication.go
releasenotes/notes/tls-version.yaml

See https://github.com/istio/istio/issues/28120
See https://github.com/envoyproxy/envoy/issues/13864
This resolves a downtime event on in place upgrade from 1.6 to 1.7. This
is a couple seconds of 503s.
This is intentionally sent only to 1.7 as it is only relevant for this
branch.
Please note this feature flag is shipped by on by default. We have two
choices:
* Off by default. Anyone upgrading from 1.6 to 1.7 will continue to get
downtime unless they read the release notes and add the flag.
* On by default. Anyone with 1.7 already deployed, but that still has
1.6 proxies will encur a downtime unless they read the release notes and
remove the flag.
I have chosen on by default, as the set of people with 1.6 proxies with
1.7.x Istiod upgrading to 1.7.5 seems far smaller than the impacted set …

Do not switch TLS version on 1.6 -> 1.7 upgrade

---

pilot/pkg/config/kube/crdclient/client.go
pilot/pkg/config/kube/crdclient/client_test.go

It doesn't make sense to read the CRDs if we are already disabling the
controller if the flag is not enabled
[ ] Docs
[ ] Networking
[ ] Security

Fully flag protect service-apis

---

istioctl/cmd/proxyconfig.go

`istioctl pc --help` examples are missing `log` and `secret` subcommand. Are these intentionally excluded as these described as experimental in a subcommand help?
---
[x] Docs
[ ] Networking
[ ] Security

Add missing subcommands to proxy-config help synopsis

---

istioctl/cmd/workload.go
pkg/test/framework/components/echo/config.go
pkg/test/framework/components/echo/kube/deployment.go

Allows using the `istioctl x workload entry configure` command to generate config that's ready-to-go for autoregistration.

autoregister flag for workload entry command

---

pilot/pkg/model/config.go
pilot/pkg/model/config_test.go
pilot/pkg/model/destination_rule.go
pilot/pkg/model/push_context.go

Use map instead of loop statement to match exactly
- Add benchmark testcase for MostSpecificHostMatch
- Refer the necessary judgment statements to the outside of the looping structure like needle.IsWildCarded()
[ ] Docs
[ ] Networking
[ ] Security

Improved performance of MostSpecificHostMatch

---

galley/pkg/config/analysis/analyzers/analyzers_test.go
galley/pkg/config/analysis/analyzers/testdata/virtualservice_host_not_defined_gateway.yaml
galley/pkg/config/analysis/analyzers/testdata/virtualservice_host_not_found_gateway.yaml
galley/pkg/config/analysis/analyzers/virtualservice/gateways.go
galley/pkg/config/analysis/msg/messages.gen.go
galley/pkg/config/analysis/msg/messages.yaml

This PR adding analyzer in `istioctl analyze` to check incompatible host between VirtualService and Gateway.
Issue: https://github.com/istio/istio/issues/28172
data:
```
kind: Gateway
metadata:
name: gw
spec:
selector:
istio: ingressgateway
servers:
- hosts:
- foo.com
port:
name: http
number: 80
protocol: HTTP
---
metadata:
name: service
spec:
gateways:
- istio-system/gw
hosts:
- bar.com
http:
- match:
- uri:
prefix: /
route:
- destination:
host: helloworld
```
result:
```
istio $ ./out/linux_amd64/istioctl analyze --use-kube=false testing.yaml -n default                                                 master*
Error [IST0132] (VirtualService service.default …
```

add analyzer for incompatible host between VirtualService and Gateway

---

istioctl/cmd/workload.go
istioctl/pkg/multicluster/cluster.go

We're now using east-west gateway (soon to be called expansion gateway #28196) for accessing istiod from outside the cluster. The `istioctl x workload entry configure` command needs to grab the IP from this instead of the ingressgateway.

workload entry configure command allows specifying ingress service name

---

pilot/pkg/networking/core/v1alpha3/cluster.go

This is fixing a small regression in #28498 that caused excessive
logging for clusters without TLS settings.
Old code:
```go
if tlsContext != nil {
c.TransportSocket = &core.TransportSocket{
Name:       util.EnvoyTLSSocketName,
ConfigType: &core.TransportSocket_TypedConfig{TypedConfig:
util.MessageToAny(tlsContext)},
}
}
```
You can see the MessageToAny was guarded by nil check. In the current
code, we nil check *after* the MessageToAny. In practice, MessageToAny
will handle nil pretty well and return nil back, but it will spam
confusing error level logs in the meantime.
[ ] Docs
[ ] Networking
[ ] Security
Pull …

Fix issue with any marshal of nil

---

pilot/pkg/xds/ads.go
pilot/pkg/xds/workloadentry.go

- When `RegisterWorkload` fails(maybe workloadgroup not exist), close the stream and make retry originated from sidecar. This is to make istiod stateless in this case.
- use patch instead of update for unregister
- make connect/disconnect time readable

Improve wle reg/unreg robustness

---

manifests/charts/gateways/istio-ingress/templates/preconfigured.yaml
releasenotes/notes/fix-multicluster-envoyfilter.yaml

Signed-off-by: Erik Jankovič <erikjankovic@gmail.com>
Cherry-pick #27264 for multicluster configuration.
Closes #28282, updates #27909  
[ ] Docs
[ ] Networking
[ ] Security

chore(manifests): update config to typed config (#27264)

---

pilot/pkg/model/config.go
pilot/pkg/model/config_test.go

Addresses #28645. Docs for VirtualService `hosts` field say `Could be a DNS name with wildcard prefix or an IP address. Depending on the platform, short-names can also be used instead of a FQDN (i.e. has no dots in the name)`. However, current logic does not actually support IPs in that field. 
Think it's by accident that `IPv4` worked (logic checked for `'.'`), but `IPv6` addresses are mistakenly treated as shortnames and have service domains added. Should be corrected to make sure we're not adding service domains to IPs (unless I'm mistaken in my reading of the docs and this is intended behavior).
[ ] Docs
[x] Networking
[ ] Security
[ ] …

Add explicit check for IP addresses when resolving VirtualService host shortname

---

pilot/pkg/bootstrap/certcontroller.go
pilot/pkg/bootstrap/istio_ca.go
pilot/pkg/xds/ads_test.go
security/pkg/pki/ca/ca.go
security/pkg/pki/ca/ca_test.go

When using self-signed Istiod CA, Istiod server needs a long-lived cert signed by Istiod CA itself (we make its lifetime equals the CA cert lifetime). Because the Istiod CA checks the requested lifetime should be smaller than the max workload cert lifetime, we extended the max workload cert to be equal to the CA cert lifetime. This actually makes the max workload cert lifetime effectiveless.
This PR fixes this by not conducting the max workload cert lifetime check for the Istiod server's certificate issuance (called via GenKeyCertNoLifetimeChecking). The max workload cert lifetime is still effective (by default 90 days) against normal workload cert issuance.
[ ] Docs
[ ] Networking …

Max workload cert lifetime should not apply to istiod's server cert

---

istioctl/cmd/proxyconfig.go
istioctl/cmd/proxyconfig_test.go
releasenotes/notes/27490.yaml

To fix https://github.com/istio/istio/issues/27490
Based on @esnible  https://github.com/istio/istio/issues/27490#issuecomment-698413935
> istioctl does accept a --selector <selector> for some commands, e.g. istioctl dashboard envoy. There is no reason not to make some/all of the istioctl proxy-config commands take the same --selector argument if it will help.
Logs by directly passing pods name.
```
$ istioctl pc log istiod-5d884bcc7-mpbpt -n istio-system
2020-10-14T08:45:00.146435Z     error   klog    an error occurred forwarding 41023 -> 15000: error forwarding port 15000 to pod 8becc3bca0ef848c919139d7ecba423647ed738989d12abb5c17425ccd4a4948, uid : failed to execute portforward in network namespace "/var/run/netns/cni-f636d912-b685-538b-d549-29e6d71feb3d": failed to dial 15000: dial …
```

istioctl proxy-config log: add label selector to filter logs

---

releasenotes/notes/trust-domain-validation.yaml

The trust domain release note doesn't have a properly formatted action. This can cause issues with validation in the release notes tooling.

Fix trust domain RM

---

Makefile.core.mk
pilot/pkg/xds/v2/model.go
pkg/config/xds/filter_types.gen.go
pkg/config/xds/filter_types.go

75mb -> 64mb
We could have also done massive refactoring to avoid using build tags,
but I think in the near future we will need build tags for dropping k8s
import, so it seems useful to implement this at least for the short
term.
[ ] Docs
[ ] Networking
[ ] Security

Trim agent binary by 14mb by conditionally compiled XDS filters

---

.github/ISSUE_TEMPLATE/bug_report.md

Adds `Upgrade[ ]` to our bug report issue template so that we can better track upgrade problems. Considered also adding `upgrading from` and `upgrading to` versions on the template but decided against. Accompanied by autolabeler change [here](https://github.com/istio/bots/pull/302) 
[ ] Docs
[ ] Networking
[ ] Security

Add 'Upgrade' product area to bug report template

---

pilot/pkg/bootstrap/server.go
pilot/pkg/xds/debug.go

Agent -> pkg/xds -> debug.go -> inject/ -> operator/
Cut the chain at debug.go to not import inject/
Agent binary size 77.9mb -> 76.8mb
Also will be *required* long term to drop k8s dependency, so its not just 1mb

Drop dependency on the operator from the agent

---

pilot/pkg/model/config.go
pilot/pkg/model/push_context.go

Allow passing unset map to MostSpecificHostMatch to avoid allocs in IsClusterLocal.
[ ] Docs
[ ] Networking
[ ] Security

allow passing unset map to MostSpecificHostMatch

---

go.mod
go.sum
pilot/cmd/pilot-agent/main.go
pilot/cmd/pilot-discovery/main.go
releasenotes/notes/28604.yaml

Fix #28482
[ ] Docs
[ ] Networking
[ ] Security

pilot: allow enabling gRPC logging with --log_output_level

---

samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
samples/bookinfo/platform/kube/bookinfo-details.yaml
samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
samples/bookinfo/platform/kube/bookinfo-ratings.yaml
samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
samples/bookinfo/platform/kube/bookinfo.yaml

All of the bookinfo samples containers are able to run as non-root. Therefore it's okay to also add the `securityContext` to the Kubernetes deployments.
This PR resolves issue #23232 
[ ] Docs
[ ] Networking
[ ] Security
<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

add runAsUser to bookinfo samples to run as non-root

---

Makefile.core.mk
pilot/pkg/xds/v2/model.go
pkg/config/xds/filter_types.gen.go
pkg/config/xds/filter_types.go

* Trim agent binary by 11mb by conditionally compiled XDS filters
75mb -> 64mb
We could have also done massive refactoring to avoid using build tags,
but I think in the near future we will need build tags for dropping k8s
import, so it seems useful to implement this at least for the short
term.
* Trim another 4mb
(cherry picked from commit 19c8ea42031a5fb19c64654e6d8c9e468339460b)
[ ] Docs
[ ] Networking
[ ] Security …

[1.8] Trim agent binary by 14mb by conditionally compiled XDS filters (#28670)

---

pilot/pkg/model/context.go
pilot/pkg/serviceregistry/aggregate/controller.go
pilot/pkg/serviceregistry/kube/controller/controller.go
pkg/config/constants/constants.go
pkg/test/framework/components/echo/kube/builder.go

* Allow fallthrough to `getProxyServiceInstancesFromMetadata` for VMs in kube-controller
* We could implement something similar in the serviceentry registry, not sure how valuable this would be. 
* Clean up noise due to our test "vms" being a pod. 
* Should fix #27234 – the change to `isControllerForProxy` prevents the `frommetadata` method from returning early for a vm. 
* Remove `break` that prevents a Workload to be selected by Services and ServiceEntries simultaneously

GetProxyServiceInstances cleanup

---

galley/pkg/config/analysis/analyzers/schema/validation.go
galley/pkg/config/analysis/msg/messages.gen.go
galley/pkg/config/analysis/msg/messages.yaml

Example:
```
$ grun ./istioctl/cmd/istioctl analyze /tmp/dr.yaml --use-kube=false -A
Error [IST0106] (DestinationRule reviews-cb-policy /tmp/dr.yaml:1) Schema validation error: duration must be greater than 1ms
Warning [IST0132] (DestinationRule reviews-cb-policy /tmp/dr.yaml:1) Schema validation warning: outlier detection consecutive errors is deprecated, use consecutiveGatewayErrors or consecutive5xxErrors instead
Error: Analyzers found issues when analyzing all namespaces.
See https://istio.io/v1.9/docs/reference/config/analysis for more information about causes and resolutions.
```
For https://github.com/istio/istio/issues/27179
Open question: what do we want to do about current single-resource validation messages, such as InvalidRegexp. We want to add them to the standard warnings so …

Display schema validation warnings in istioctl analyze

---

Makefile.core.mk
pilot/pkg/xds/v2/model.go
pkg/config/xds/filter_types.gen.go
pkg/config/xds/filter_types.go

* Trim agent binary by 11mb by conditionally compiled XDS filters
75mb -> 64mb
We could have also done massive refactoring to avoid using build tags,
but I think in the near future we will need build tags for dropping k8s
import, so it seems useful to implement this at least for the short
term.
* Trim another 4mb
(cherry picked from commit 19c8ea42031a5fb19c64654e6d8c9e468339460b)
[ ] Docs
[ ] Networking
[ ] Security …

[1.7] Trim agent binary by 14mb by conditionally compiled XDS filters (#28670)

---

pkg/bootstrap/platform/gcp.go

* Remove dependency on google.golang.org/api
This dependency is ~22mb which bloats the binary
* lint
For https://github.com/istio/istio/issues/26232
Drops compiled agent from 78mb to 73mb

[1.7] Remove dependency on google.golang.org/api (#26242)

---

pkg/test/framework/resource/flags.go
pkg/test/framework/resource/settings.go
tests/integration/README.md
tests/integration/pilot/common/apps.go
tests/integration/pilot/common/routing.go
tests/integration/pilot/common/traffic.go

1. Add test input config argument to disable VM related parts in
TestTraffic.
2. Skip all the VM related parts based on the input argument.
[ ] Docs
[ ] Networking
[ ] Security

Skip VM related parts for TestTraffic

---

pkg/test/framework/components/istio/operator.go
tests/integration/iop-remote-integration-test-defaults.yaml

Recent changed disabled ingress/egress – this brings them back and deploys eastwest in parallel. 
Needed for multicluster testing of ingress, security, telemetry

test framework: deploy gateways for remote clusters

---

releasenotes/notes/28003.yaml

This will need to go into the 1.8 release notes. This is pointing at the wrong issue.

Fix observed generation release note

---

samples/sleep/sleep.yaml

Otherwise, the pods always stick around for 30s after removal, slowing
down following the tasks.
[ ] Docs
[ ] Networking
[ ] Security

Add terminationGracePeriodSeconds=0 to sleep sample

---

pkg/istio-agent/xds_proxy.go

Currently, we have a WithBlock, BackoffConfig, 5s timeout, and
(implicitly) Envoy's downstream retry/backoff logic. These
interact poorly.
Because we have a 5s timeout, the gRPC backoff config doesn't actually
work, since we are cutting it off. When its cut off, we get an error
like "context cancelled", rather than a useful one like "cert
verification failed".
This change drops the WithBlock and backoff config. Instead, we will
rely on Envoy's own retry and backoff logic.
The end result is we do not have any conflicting retry/backoff configs,
and the error messages when we fail to connect to istiod will now give
proper context.

Switch gRPC dial params on xds-proxy

---

pilot/pkg/model/validation.go
pilot/pkg/networking/core/v1alpha3/cluster.go
pkg/config/validation/validation.go
pkg/test/echo/common/model.go
pkg/test/framework/components/echo/echo.go
pkg/test/framework/components/echo/kube/deployment.go
pkg/test/framework/components/echo/kube/instance.go
releasenotes/notes/pod-ip-listener.yaml
tests/integration/pilot/common/apps.go
tests/integration/pilot/common/routing.go
tests/integration/pilot/common/traffic.go
tests/integration/pilot/istioctl_test.go

Copy of https://github.com/istio/api/pull/1314 and https://github.com/istio/istio/pull/22117 but with a different implementation
This allows defining a Sidecar like
```yaml
kind: Sidecar
metadata:
name: echo
spec:
workloadSelector:
labels:
app: echo
ingress:
- port:
number: 8080
protocol: HTTP
name: http
defaultEndpoint: pod:8080
egress:
- hosts:
- "*/*"
```
and instead of 127.0.0.1 we send to <POD_IP>
`pod` is probably the wrong name here since it applies to VMs, etc.

Add support for applications listening on Pod IP

---

pkg/kube/inject/inject.go
pkg/kube/inject/template.go
pkg/kube/inject/validate.go

Currently we have a big inject.go file serving many tasks. This splits
it up into validation, templating, and the core injection.
This will be useful to make a future PR I have not so big. This PR is
strictly moving code around, there should be no functional changes
[ ] Docs
[ ] Networking
[ ] Security

inject: split massive file

---

istioctl/cmd/workload.go
releasenotes/notes/28794.yaml

cc @howardjohn 
We mentioned we wanted to turn this on by default in 1.8 (https://github.com/istio/istio.io/pull/8418) – with the docs changes to use this command, here is where we'd set that default.

enable dns capture by default in workload command

---

tests/integration/pilot/common/routing.go

Temporary to get pilot-multicluster job required. Issue #28834 tracks fixing these flakes.

disable flaky multicluster pilot tests

---

pkg/kube/inject/inject.go

This is for future proofing. Its painful to change the injection
template since if the injector and the template and image fall out of
sync new functions fail. Adding sprig now will ensure in the future when
we inevitably need new functions in sprig we can easily add them
[ ] Docs
[ ] Networking
[ ] Security

Add sprig to injection template

---

galley/pkg/config/analysis/msg/messages.gen.go
galley/pkg/config/analysis/msg/messages.yaml

Four analysis codes are no longer generated by Istio.  See https://github.com/istio/istio.io/issues/7844#issuecomment-726350837 for list.
Removing these dead codes will remove them from http://istio.io/latest/docs/reference/config/analysis/
cc @frankbu

Remove analysis codes that are no longer used

---

istioctl/pkg/util/clusters/wrapper.go

This mirrors the logic for config dump
[ ] Docs
[ ] Networking
[ ] Security

Allow unknown fields in istioctl cluster dump

---

pilot/pkg/xds/monitoring.go

Currently pilot_proxy_queue_time contains pilot_proxy_convergence_time, but they
use different buckets, when they land between 0.1 and 1 second, histogram_quantile()
returns bigger queue time than convergence time.
[ ] Docs
[ ] Networking
[ ] Security

Align proxy queue time and convergence time histogram buckets

---

istioctl/cmd/workload.go
pilot/pkg/features/pilot.go
pkg/istio-agent/xds_proxy.go
pkg/test/framework/components/echo/kube/deployment.go

This will use JWT if we have PROV_CERT but the certs don't exist. 
* fixes #28824 where we never use the JWT fo fetch cert/key because they're not found. This will make us fallthrough to use the JWT first, and only use cert/key once they exist. 
* Integration tests are now closer to what we document

try token if certs specified by PROV_CERT don't exist for the first time bootstrapping

---

tests/integration/pilot/common/routing.go

Manual cherry pick of #28836 so we can make this job required in the 1.8 branch

[release-1.8] disable flaky multicluster pilot tests (#28836)

---

tests/integration/telemetry/dashboard_test.go
tests/integration/telemetry/main_test.go

Cherry-pick https://github.com/istio/istio/pull/28741
* Make dashboard test multicluster
* don't instantiate multiple subtests
* fix fmt
* skip validation of pilot metrics for non primary clusters
* fix based on comment
[ ] Docs
[ ] Networking
[ ] Security

[Release-1.8] Make dashboard test multi-cluster (#28741)

---

pkg/kube/client.go
pkg/test/framework/components/echo/config.go
pkg/test/framework/components/echo/kube/builder.go
pkg/test/framework/components/echo/kube/instance.go

Currently every call to ApplyYAML will reinitialize discovery, which can
take O(seconds) on slow clusters. This likely doesn't impact CI much, which
runs in kind, but on GKE I saw echo deployment times go from 30s+ to 5s.
[ ] Docs
[ ] Networking
[ ] Security

Improve speed of YAML apply/echo init

---

tests/integration/security/ca_custom_root/secure_naming_test.go
tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go
tests/integration/security/util/reachability/context.go

[ ] Docs
[ ] Networking
[X] Security

Fix the duplicate test cases because of multiple b services deployed and skip the current failed ca_custom_root test cases in multicluster setup

---

common/scripts/gobuild.sh
common/scripts/setup_env.sh
security/pkg/nodeagent/cache/secretcache.go

While Istio 1.6 is nearing end of support, we'd like this patch to be included in any final 1.6 release, since CA root certs included in `DestinationRule` TLS config can cause mesh communication to break. (The DR's root cert is used to validate the peer Pod's certificate instead of the istio CA root). 
(cherry picked from commit 2cbbf53da0acb42d23decabd2dacd7929961f515)
[ ] Docs
[x] Networking
[x] Security

[release-1.6] cherry-pick: do not update root certs for destination rule certs (#27268)

---

tests/integration/telemetry/dashboard_test.go

Wait for only 20s instead of 100s, to increase test time
Stop sending HTTP traffic to TCP port
Send to all clusters in parallel. Before it was 100s * 5 clusters = 500s per test

Improve dashboard test

---

CODEOWNERS

Backfill after Shriram left to avoid bus factor of only having 3 of us
[ ] Docs
[ ] Networking
[ ] Security

Add @nmittler to CODEOWNERs top level

---

istioctl/cmd/workload.go

While adding a "Verify DNS" section to https://preliminary.istio.io/latest/docs/setup/install/virtual-machine/ where the user curls a helloworld service from their VM, I found that this must be in cluster.env instead of the proxy meta file.

set dns capture in cluster.env with workload cmd

---

istioctl/cmd/kubeuninject.go
istioctl/cmd/remove-from-mesh.go
pilot/cmd/pilot-agent/status/server.go
pilot/cmd/pilot-agent/status/server_test.go
pkg/kube/apimirror/probe.go
pkg/kube/inject/app_probe.go

Importing k8s libraries adds up to 40mb to the binary. This, along with many other changes, allows completely dropping the imports and cutting the agent binary size in half. See https://github.com/howardjohn/istio/pull/new/agent/tiny-binary-full-branch for this end state.

Mirror http prober API

---

pilot/pkg/bootstrap/server.go
security/pkg/server/ca/authenticate/cert_authenticator.go
security/pkg/server/ca/authenticate/cert_authenticator_test.go
security/pkg/server/ca/authenticate/common.go
security/pkg/server/ca/authenticate/common_test.go
security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go
security/pkg/server/ca/authenticate/kubeauth/kube_jwt_test.go
security/pkg/server/ca/authenticate/oidc.go

Importing k8s libraries adds up to 40mb to the binary. This, along with many other changes, allows completely dropping the imports and cutting the agent binary size in half. See https://github.com/howardjohn/istio/pull/new/agent/tiny-binary-full-branch for this end state.

Drop kube import from ca auth

---

pilot/pkg/bootstrap/mesh.go
pilot/pkg/networking/core/v1alpha3/fake.go
pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
pilot/pkg/xds/fake.go
pkg/config/mesh/kubemesh/watcher.go
pkg/config/mesh/kubemesh/watcher_test.go
pkg/config/mesh/watcher.go
pkg/config/mesh/watcher_test.go
security/pkg/k8s/configutil.go
security/pkg/k8s/configutil_test.go
tests/binary/binaries_test.go

* Move mesh configmap watcher out of the core `mesh` package
* Move security kubernetes `util`s to its own package
This drops the Kubernetes dependency for the agent completely.
This essentially completes https://github.com/istio/istio/issues/26232
for the agent (but not Istiod).
[ ] Docs
[ ] Networking
[ ] Security

Split remaining Kubernetes imports from agent

---

istioctl/pkg/install/k8sversion/version.go
istioctl/pkg/install/k8sversion/version_test.go

`version.Segments()` is useful to extract valid version info.
```
[istio-master] $ ./out/linux_amd64/istioctl x precheck
...
#2. Kubernetes-version
-----------------------
Istio is compatible with Kubernetes: v1.19.1.
...
```

Refactor: extract Kubernetes version

---

pkg/test/framework/components/istio/operator.go

This should massively speed up multicluster tests with multiple suites.. especially valuable for https://github.com/istio/istio/issues/26888

perform multicluster cleanup in parallel

---

pilot/pkg/bootstrap/server_test.go
pilot/pkg/bootstrap/sidecarinjector.go

When the Pilot is deployed in a non-K8s environment, the process of initializing the server will cause the program to panic. In order to reproduce this issue, as in the following example, set the service registry of the Pilot to Mock registry,  build and run discovery cmd.
```
./pilot-discovery discovery --registries=mock --configDir=/tmp
```
Then, I got the nil pointer dereference error.
```
panic: runtime error: invalid memory address or nil pointer dereference
```
I find the reason. When the local injection config is not exist in the path `./var/lib/istio/inject` specified in initial `serverArgs`, the  server will find the remote injection config by accessing ConfigMap with KubeClient. Our Pilot is deployed in a non-K8s environment and the KubeClient will not be created, so we get the …

Fix nil pointer dereference in initSidecarInjector of Pilot

---

pkg/test/framework/components/istio/operator.go
pkg/test/util/yml/file.go

This will make it so eastwest gateway is removed in parallel. This
doesn't impact CI much, but on GKE it takes ~1min to remove a LB service so
this makes the cleanup 1min faster
[ ] Docs
[ ] Networking
[ ] Security

Remove all manifests in parallel

---

tests/integration/iop-integration-test-defaults.yaml

This drops gateway init time from ~20s to 1s. Probably why we have so
many flakes as well...
[ ] Docs
[ ] Networking
[ ] Security

Remove CPU limits for gateways

---

pilot/docker/Dockerfile.proxyv2
tools/istio-docker.mk

When/if this is approved, I will fork off https://github.com/GoogleContainerTools/distroless/compare/master...howardjohn:iptables?expand=1 into an istio org repo.
This replaces our current hacks to get iptables into distroless. The end result:
* No longer relying on fragile copying from ubuntu
* Easy multi-arch support
* We are only adding the minimal dependencies for iptables now; the resulting docker image is ~40mb smaller since previously we copied unneeded extras.

Remove distroless copying hacks

---

tools/istio-iptables/pkg/cmd/root.go

istio-iptables is now a binary instead of a script, so we should fix its long description shown in the "help" output.
[ ] Docs
[ ] Networking
[ ] Security

Fix the long description of istio-iptables shown in the 'help' output

---

pilot/cmd/pilot-discovery/main.go

Short term solution for https://github.com/istio/istio/issues/27945.
Note that the setting here roughly correlates to the number of new
connections we can accept per second so its important to not be slow
[ ] Docs
[ ] Networking
[ ] Security

Bump QPS of kube client

---

pkg/kube/inject/inject.go
pkg/kube/inject/inject_test.go
pkg/kube/inject/testdata/webhook/TestWebhookInject.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_mtls_not_ready.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_no_containers.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_no_containers_imagePullSecrets.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_no_containers_volumes.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_no_containers_volumes_imagePullSecrets.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_no_imagePullSecrets.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_containers.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_containers_imagePullSecrets.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_containers_volumes.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_imagePullSecrets.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_volumes.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initContainers_volumes_imagePullSecrets.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_no_initcontainers_containers_volumes_imagePullSecrets.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_no_volumes.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_no_volumes_imagePullSecrets.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_replace.patch
pkg/kube/inject/testdata/webhook/TestWebhookInject_replace_backwards_compat.patch
pkg/kube/inject/webhook.go

Depends on https://github.com/istio/istio/pull/29023
This allows the template to be a Pod instead of a PodSpec. This is
implemented with support for the old behavior as well, so its fully
backwards compatible. In a followup PR, I will modify the default
template to use this format

Allow passing full pod object as injection template

---

pkg/test/framework/scope.go

Before this change we'd get an error like
`2020-11-23T21:30:35.889236Z     error   tf      Error during close: 0 errors occurred:`
[ ] Docs
[ ] Networking
[ ] Security

Add ErrorOrNil to multierror append in cleanup to avoid extraneous error

---

pilot/pkg/bootstrap/configcontroller.go

https://github.com/istio/istio/blob/887439cbbfde1b1af62cb2a8ac0cc654ea36afec/pilot/pkg/bootstrap/server.go#L479
kubeClient is only set if we have a kube registry. We need the client for the crdclient – in "Mock" mode we will crash
fixes https://github.com/istio/istio/issues/29048

nil check to fix mock registry crash

---

pilot/pkg/bootstrap/configcontroller.go
pilot/pkg/bootstrap/server.go
releasenotes/notes/config-source-scheme.yaml

Now we choose a type of config source by the following code.
```
// for file
strings.Contains(configSource.Address, fsScheme+"://")
// for xds server
strings.Contains(configSource.Address, "xds://")
// for k8s controller
strings.Contains(configSource.Address, "k8s://")
```
Since the scheme is always in the prefix of the url, we should use `strings.HasPrefix` instead of `strings.Contains` when we initial config sources of Pilot server. In addition, the method `url.Parse` appears once in each conditional branch, and it appears 3 times in total. In order to make code clean and avoid hard code, we introduce the new type `ConfigSourceScheme`.
[ ] Docs
[] Networking
[ ] Security
[ ] Test …

Add a type ConfigSourceScheme to make code clean and avoid hard code

---

pilot/pkg/xds/workloadentry.go
pilot/pkg/xds/workloadentry_test.go

Previously we only used WorkloadGroup.Spec.Template.Labels + the labels from the Node metadata sent in the XDS request. 
This includes both the labels and annotations from WorkloadGroup.Spec.Metadata in the generated WorkloadEntries to fix #29151.

merge labels and annotations from workloadgroup.spec.metadata

---

pilot/pkg/networking/core/v1alpha3/accesslog.go
pilot/pkg/networking/core/v1alpha3/accesslog_test.go
pilot/pkg/networking/core/v1alpha3/listener.go
pilot/pkg/networking/core/v1alpha3/listener_builder.go
pilot/pkg/networking/core/v1alpha3/listener_test.go
pilot/pkg/networking/core/v1alpha3/networkfilter.go
pilot/pkg/networking/util/util.go
releasenotes/notes/default-access-log.yaml

These log operators should be very useful for troubleshooting and debugging in many cases. 
Example Logs (RESPONSE_CODE_DETAILS): (`via_upstream` , `filter_chain_not_found`, `http1.codec_error`, `rbac_access_denied_matched_policy[none]`)
```
[2020-10-29T03:22:16.126Z] "GET /headers HTTP/1.1" 200 - via_upstream - "-" 0 547 5 4 "-" "curl/7.73.0-DEV" "24e58e43-e576-9048-829b-02e3f3da16f0" "httpbin:8000" "127.0.0.1:80" inbound|8000|| 127.0.0.1:51680 172.17.0.7:80 172.17.0.6:59022 outbound_.8000_._.httpbin.foo.svc.cluster.local default
[2020-10-29T03:23:33.415Z] "- - -" 0 NR filter_chain_not_found - "-" 0 0 0 - "-" "-" "-" "-" "-" - - 172.17.0.7:80 172.17.0.6:59800 - -
[2020-10-29T03:24:13.520Z] "- - HTTP/1.1" 400 DPE http1.codec_error - "-" 0 11 0 - "-" "-" "-" "-" "-" - - 172.17.0.7:80 …
```

add RESPONSE_CODE_DETAILS and CONNECTION_TERMINATION_DETAILS to access log

---

pilot/pkg/serviceregistry/aggregate/controller.go
pilot/pkg/serviceregistry/aggregate/controller_test.go

fixes https://github.com/istio/istio/issues/22093 and is pre-work for #29026 
The main advantage is that we can actually associate the ServiceEntry registry with a cluster (no longer rely on `ClusterID == ""`). We eventually plan on [reading WorkloadEntry from multiple clusters](https://docs.google.com/document/d/1Q_JqW7v1SC2Crg5ped9Bf8fyauglB-YqHYk7hwSuWOk/edit). To do this, we need to be able to shard the WorkloadInstances/Endpoints by source cluster.

properly use cluster id and provider id

---

pilot/pkg/config/kube/crdclient/client.go
pilot/pkg/config/kube/crdclient/client_test.go

Fixes #29054, needed so that 1.7.x istiod won't hang on startup reading service API CRDs it doesn't recognize

[release-1.7] Manual cherry-pick for "flag protect service-apis (#28488)"

---

pkg/adsc/adsc.go

Signed-off-by: huabing zhao <huabingzhao@tencent.com>
Fix the issue in adsc: handleRecv is blocked by sync chan.  
[ ] Docs
[X] Networking
[ ] Security

Fix: adsc is blocked by sync chan

---

pilot/pkg/xds/discovery.go
pkg/kube/secretcontroller/secretcontroller.go

It seems to me that the synchronization for `serverReady` could be atomic.Bool instead of two mutexs, unless the `IsServerReady()` should be blocked during the `EndpointShardsByService` is being updated.
Please correct me if I misunderstood anything here.
[ ] Docs
[ ] Networking
[ ] Security

pilot/xds: replace mutex with atomic.Bool when accessing cache sync

---

pkg/test/framework/components/echo/common/envoy_test.go
pkg/test/framework/components/namespace/kube.go
pkg/test/framework/components/namespace/namespace.go
tests/integration/security/authorization_test.go

Adds `SetLabel` to the test framework's namespace interface. Useful for upcoming work around upgrade testing
[ ] Docs
[ ] Networking
[ ] Security

Add SetLabel to test framework namespace interface

---

pkg/istio-agent/health/health_check.go
pkg/istio-agent/health/health_probers.go
pkg/istio-agent/health/health_probers_test.go

Reuse the HTTP client for each prober to benefit from cached TCP connections inside the `http.Transport`.
[ ] Docs
[x] Networking
[ ] Security

istio-agent/health: reuse the HTTP client of prober

---

operator/cmd/mesh/upgrade.go
operator/cmd/mesh/upgrade_test.go
releasenotes/notes/29183.yaml

Manually cherry-pick of https://github.com/istio/istio/pull/29191
[ ] Docs
[ ] Networking
[ ] Security

[release-1.8] istioctl upgrade: fix downgrade to lower version (#29191)

---

prow/integ-suite-kind.sh

first part of fixing https://github.com/istio/istio/issues/29053
Allows us to specify at the prow-job level which kubeadm ClusterConfiguration config to use for KinD. A follow up PR in test-infra will have the failing job use prow/config/endpointslice.yaml.

allow setting kind cluster config yaml from integ-suite-kind

---

pkg/test/framework/components/echo/config.go
pkg/test/framework/components/echo/kube/deployment.go
samples/extauthz/README.md
samples/extauthz/ext-authz.yaml
samples/extauthz/local-ext-authz.yaml
tests/integration/security/authorization_test.go
tests/integration/security/main_test.go
tests/integration/security/testdata/authz/v1beta1-custom.yaml.tmpl

[ ] Docs
[ ] Networking
[x] Security

ext-authz: add e2e tests and example configuration for local ext-authz server in the same pod

---

cni/pkg/install-cni/pkg/install/cniconfig_test.go

This is timing out very rarely, seems like 1/10000 runs locally. Bump the timeout a bit to resolve

Fix CNI test flakes

---

pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_builder.go
pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
pilot/pkg/networking/core/v1alpha3/fake.go
pilot/pkg/networking/core/v1alpha3/listener.go
pilot/pkg/networking/core/v1alpha3/networkfilter.go
pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
pilot/pkg/networking/util/util.go
pilot/pkg/simulation/traffic.go
releasenotes/notes/inbound-cluster-rename.yaml
tests/integration/pilot/common/routing.go
tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
tests/integration/telemetry/stackdriver/testdata/tcp_server_access_log.json.tmpl

Fixes https://github.com/istio/istio/issues/29199
In Istio 1.8, we dropped the Service name from the inbound cluster
specifier. As a result, we have a regression due to overlapping
Services. The problem comes from the fact that inbound listener is based
on workload/target port, but the cluster name is based on Service port.
This means we can only have a single cluster per Service port. In
reality, we should have a single cluster per workload port.
This switches the naming to use workload port. Regression integration
tests for this issue were added in
https://github.com/istio/istio/pull/29201 and activated in this PR, as
well as additional unit tests which I think give pretty solid coverage
of this change.

Switch inbound cluster naming to use workload port, rather than Service port

---

pkg/queue/delay.go

This is a tiny improvement for #29226 
As we all know, the number of `P` determines how many goroutines can run in parallel, thus it would be a better choice for the buffered size of `execute` channel.
[ ] Docs
[ ] Networking
[ ] Security

pkg/queue: improve the capacity of execute channel

---

prow/config/endpointslice.yaml

Copies config from our default trustworthy-jwt.yaml
allows un-reverting https://github.com/istio/test-infra/pull/3080

endpointslice config uses kind-registry

---

tests/fuzz/fuzz.go

There have been discussions on adding fuzzing to Istio and setting up continuous fuzzing as well. See https://github.com/istio/istio/issues/14935
This PR adds 2 fuzzers that are implemented by way of Dvyukovs go-fuzz which is supported by OSS-fuzz.
In a few minutes I will set up the integration files on the OSS-fuzz side. They will fail for now, but once the fuzzers are merged here, they will build sucessfully.

Add 2 fuzzers

---

pilot/pkg/serviceregistry/kube/controller/fake.go
pilot/pkg/xds/fake.go

fixes deadlock in https://github.com/istio/istio/issues/29341 (tested by setting chan capacity to 1)
doesn't fix the fact that we have 6 discovery servers.... could be the `t.Cleanup` not being called in timeout failures?

start fake discovery server to avoid deadlock

---

pkg/test/helm/helm.go
tests/integration/helm/install_test.go

Attempt to fix https://github.com/istio/istio/issues/29167
based on data from https://storage.googleapis.com/istio-prow/logs/integ-k8s-115_istio_postsubmit/1331309815770648576/build-log.txt
There's reason to believe that the test doing a helm delete and an
immediate helm install was causing issues between test runs. Post-merge
this will still need to be monitored.
* Add --timeout flag to helm install command with a default of
2 minutes, up from 30s.
* Delete the istio-system namespace in-between tests and wait for it to
be removed before proceeding.
[ ] Docs
[ ] Networking
[ ] Security …

Fix flaky integration test - helm/TestInstallWithFirstPartyJwt

---

istioctl/pkg/verifier/verifier.go

Resolves https://github.com/istio/istio/issues/26276
When `verify-install` fails, it was only printing the first problem it found.  The user with multiple problems rarely wants to see only one, often a different problem is the underlying one.
This is especially burdensome when the CLI is on a different version than the control plane.  (There will be other PRs tacking that more specifically).  What was happening was that only the first difference between the CLI's expected install and the actual install was being shown.
With this change instead of stopping on the first mistake we print an error message for each one:
```
istioctl verify-install --context istio-test-paid2 -d manifests
✔ ClusterRole: istiod-istio-system.default checked successfully
...
✘ EnvoyFilter: …
```

Verify install keep going

---

pilot/pkg/model/context.go
pilot/pkg/model/context_test.go
pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/cluster_builder.go
pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
pilot/pkg/networking/core/v1alpha3/cluster_test.go
pilot/pkg/networking/core/v1alpha3/fake.go
pilot/pkg/networking/core/v1alpha3/listener.go
pilot/pkg/networking/core/v1alpha3/networkfilter.go
pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
pilot/pkg/networking/util/util.go
pilot/pkg/simulation/traffic.go
pilot/pkg/xds/lds_test.go
releasenotes/notes/inbound-cluster-rename.yaml
tests/integration/pilot/common/apps.go
tests/integration/pilot/common/routing.go
tests/integration/pilot/common/traffic.go
tests/integration/telemetry/stackdriver/testdata/tcp_server_access_log.json.tmpl

Cherrypick:
* #28507 (dependency)
* #29201 (tests)
* #29203 (implementation)

[1.8] Cherrypick inbound cluster format changes

---

galley/testdatasets/validation/dataset.gen.go
galley/testdatasets/validation/dataset/networking-v1alpha3-WorkloadGroup-invalid.yaml
pkg/config/schema/collections/collections.agent.gen.go
pkg/config/schema/collections/collections.gen.go
pkg/config/validation/validation.go
pkg/config/validation/validation_test.go

Kubernetes 1.20 tests are currently broken, since our old invalid config
is now considered valid (see
https://github.com/kubernetes/kubernetes/pull/95423). In fixing this, I
realized we don't have any validation for WorkloadGroup! This adds
validation, by applying the same validation WorkloadEntry has to the
template of workload group. However, workload entry validation is pretty
much nil, so this change isn't very beneficial beyond getting tests
passing.
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does not have any changes …

Add validation for workload group

---

operator/cmd/mesh/install.go
operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
operator/pkg/name/name.go

manual cherry-pick of https://github.com/istio/istio/commit/aaf3a601512681e66e9d1874110b27e69ed1c249
* add annotation to installed-state CR and ignore during reconcile
* skip the post install test for operator only

[release1.8] add ignore reconcile annotation to Operator CR  (#29378)

---

pkg/config/schema/fuzz_test.go
pkg/config/validation/validation.go
pkg/config/validation/validation_test.go
pkg/kube/apimirror/probe.go

Note: technically adding validation is a breaking change, but we haven't launched this feature yet so it should not be a concern.

Add validation for VM readiness probe

---

pkg/istio-agent/health/health_check.go
pkg/istio-agent/health/health_probers.go
pkg/istio-agent/health/health_probers_test.go
pkg/kube/apimirror/probe.go

* Correctly set default settings
* Match Kubernetes options more closely, including setting user agent
header and sending `connection: close`.
* Add some debug logging
* Simplify exec code by using more of the exec library builtins. This
also fixes the `$PATH`
[ ] Docs
[ ] Networking
[ ] Security

Various improvements to health checking for VMs

---

samples/helloworld/helloworld.yaml

Backports a change from our new samples
Blocks https://github.com/istio/istio.io/pull/8539
This change allows us to run the following to deploy only the Service to each cluster:
```bash
kubectl apply --context="${CTX_CLUSTER1}" \
-f $ISTIO_DIR/samples/helloworld/helloworld.yaml \
-l service=helloworld -n sample
kubectl apply --context="${CTX_CLUSTER2}" \
-f $ISTIO_DIR/samples/helloworld/helloworld.yaml \
-l service=helloworld -n sample
```

add service label to helloworld sample

---

istioctl/cmd/version.go

Resolves https://github.com/istio/istio/issues/29381 by sending the messages printed when there is no control plane to stderr rather than stdout.

"istioctl version" error messages to stderr, not stdout

---

security/pkg/nodeagent/cache/monitoring.go
security/pkg/nodeagent/cache/secretcache.go

When File watchers fails to add a watcher for example watches have exceeded etc. in secret cache, it just logs message. We would like add a metric so that we can alert when such a thing happens. It also adds metric when the secret generation fails for files. 
[ ] Docs
[ ] Networking
[ X] Security

add metrics for file watchers is sds

---

istioctl/cmd/analyze.go
istioctl/pkg/install/verify.go
istioctl/pkg/util/formatting/formatter.go
istioctl/pkg/verifier/verifier.go
releasenotes/notes/29376.yaml

Resolves https://github.com/istio/istio/issues/29336
The only output change is to colorize the little ✔ and ✘ markers.
Uses the same technique as `istioctl analyze` to see if it is safe to colorize.
I didn't test this on Windows.  Windows has some non-ANSI terminals.  Our progress bar uses github.com/mattn/go-colorable for those Windows terminals.  I didn't bring that it, because I don't have a Windows machine to test on and invoking it directly outside of a progress bar would mean changing _go.mod_.

istioctl verify-install: Colorize success/failure markers

---

manifests/charts/istio-control/istio-discovery/values.yaml
manifests/charts/istiod-remote/values.yaml

Default for `global.istioNamespace` set twice in `istiod-remote/values.yaml` and `istio-discovery/values.yaml`, this change removes the duplicates.
[ ] Docs
[ ] Networking
[ ] Security

Remove duplicate istioNamespace definitions in values.yaml

---

pkg/test/framework/resource/flags.go
pkg/test/framework/resource/settings.go
tests/integration/README.md
tests/integration/pilot/common/apps.go
tests/integration/pilot/common/routing.go
tests/integration/pilot/common/traffic.go

Cherry-pick ability to skip VM tests (#28729)
Fixes https://github.com/istio/istio/issues/29459
[ ] Docs
[ ] Networking
[ ] Security

Cherry-pick into 1.8: #28729

---

prow/config/trustworthy-jwt.yaml

This is attempting to resolve some issues where etcd is overloaded especially in multicluster tests (like https://github.com/istio/istio/issues/29458), by putting etcd memory in ram. 
After a few iterations in CI, RAM usage by the test pods is not detectably increased. Fairly low sample save, but there seems to be less etcd timeouts in logs. Test times are pretty variable currently so not sure if its faster - I expect it to be trivially faster but more reliable, which is harder to test in a PR

Experiment with in memory etcd storage

---

pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
releasenotes/notes/fix-default-filter-chain.yaml

This was broken in 1.8 with the introduction of DefaultFilterChain

Properly apply EnvoyFilter patches to default filter chain

---

pilot/pkg/serviceregistry/kube/controller/multicluster.go
pilot/pkg/serviceregistry/kube/controller/multicluster_test.go

This was skipped in race test, which is always used in our CI. Enabling
in all modes and fixing the failures (this broke a week ago or so)
[ ] Docs
[ ] Networking
[ ] Security

Fix and run  Test_KubeSecretController in CI

---

pilot/pkg/serviceregistry/kube/controller/multicluster.go

Although we need this for istiod-less remotes, it can be undesirable in some scenarios so we should guard it with flags. 
Related discussion: https://github.com/istio/istio/pull/28768#discussion_r539052937
cc @ramaraochavali

only perform patch-cert loop on remote clusters in external istiod mode

---

tests/integration/pilot/common/apps.go

This may give us a little more coverage on a stable connection with an auto-registered VM

use auto-registration for main vm in single-cluster pilot test

---

pilot/pkg/networking/core/v1alpha3/cluster_builder.go
pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
releasenotes/notes/passthrough-subsets.yaml

When we generate passthrough subsets(Subset trafficpolicy sets load balancer as Passthrough), we add locality endpoints for non EDS discovery types and Envoy rejects those subset clusters with the error
"ORIGINAL_DST clusters must have no load assignment or hosts configured,"
This PR skips adding locality endpoints for pass through subsets.
[ ] Docs
[ ] Security

do not add locality endpoints for passthrough subsets

---

galley/pkg/config/analysis/analyzers/util/config.go
pkg/config/constants/constants.go
pkg/kube/inject/initializer.go

Right now, during injection, only `kube-system` and `kube-public` are recognised as system namespaces. We want to enable an `AllNamespaces` option in our mutating webhooks, so we would need to ignore the other known system namespaces by default as well.
[ ] Docs
[ ] Networking
[ ] Security

always ignore kube's known system namespaces during injection

---

pkg/config/mesh/mesh.go

Without this the node meta is 
```
{
"APP_CONTAINERS": "sleep",
"CLUSTER_ID": "Kubernetes",
"DNS_CAPTURE": "true",
"EXCHANGE_KEYS": "NAME,NAMESPACE,INSTANCE_IPS,LABELS,OWNER,PLATFORM_METADATA,WORKLOAD_NAME,MESH_ID,SERVICE_ACCOUNT,CLUSTER_ID",
"INSTANCE_IPS": "10.244.0.15,fe80::a833:8bff:fe1a:9476",
"INTERCEPTION_MODE": "REDIRECT",
"ISTIO_PROXY_SHA": "istio-proxy:ed0e581060499e4ed0f68925fbbc8f2f12340c9a",
"ISTIO_VERSION": "1.8.0",
"LABELS": {
"app": "sleep",
"istio.io/rev": "default",
"pod-template-hash": "8f795f47d",
"security.istio.io/tlsMode": "istio",
"service.istio.io/canonical-name": "sleep",
"service.istio.io/canonical-revision": "latest"
},
"MESH_ID": "cluster.local",
"NAME": "sleep-8f795f47d-fs998",
"NAMESPACE": "default",
"OWNER": …
```

remove empty proxy config to reduce data size sent in xds request

---

pkg/bootstrap/config.go
pkg/bootstrap/config_test.go

Since we have already get information ISTIO_META in method `extractMetadata`, we need not get information ISTIO_META again in method `extractAttributesMetadata`.
[ ] Docs
[ ] Networking
[ ] Security

Remove the code that repeatedly obtained ISTIO_META

---

pkg/config/validation/validation.go
pkg/config/validation/validation_test.go

validation was failing for istioctl when attempting to use `$(HOST_IP):9411`
https://github.com/istio/istio/pull/28043#issuecomment-742971357
[ ] Docs
[X ] Installation
[ ] Networking
[ ] Security

zipkin address validation for $(HOST_IP) tracer

---

pilot/pkg/features/pilot.go
pilot/pkg/networking/core/v1alpha3/cluster.go
pilot/pkg/networking/core/v1alpha3/listener.go
pilot/pkg/networking/plugin/metadataexchange/metadataexchange.go
pilot/pkg/security/authn/utils/utils.go

This has been enabled by default since 1.5 and was intended only as a
feature flag. Removing now to simplify the code.

pilot: cleanup mx feature flag

---

samples/certs/generate-workload.sh
tests/integration/security/ca_custom_root/main_test.go
tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go
tests/integration/security/util/cert/cert.go

Due to https://github.com/openssl/openssl/issues/10442 I am not able to
generate workload certificates since my username contains a '.' on my
development machine (e.g. `j.delgado`)
To be specific, openssl fails on https://github.com/istio/istio/blob/917fd076c4514b2c16c79e6feeae1dcbd8358580/samples/certs/generate-workload.sh#L50 due to the `-CA "$DIR"/ca-cert.pem` cli argument.
Attempts to read from /Users/j.srl. Have it use a full temp directory
passed in. Otherwise default to the previous behavior.
[ ] Docs
[ ] Networking
[X] Security
Please check any characteristics that apply to this …

Fix generate-workload.sh working when fullpaths contain '.'

---

pilot/pkg/networking/core/v1alpha3/listener_builder.go
pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
pilot/pkg/networking/core/v1alpha3/peer_authentication_simulation_test.go
pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
pilot/pkg/simulation/traffic.go
pilot/test/xdstest/test.go

This expands a bunch of testing of inbound filter chains, in particular with mtls modes. Part of this is fixing the tests to properly account for the disabled filter predicate, which is why some tests results have changed to closer match real envoy behavior. Additionally, there are a lot of incorrect behaviors that are marked

Expand and fix testing of inbound filter chains

---

pilot/pkg/model/context.go
pilot/pkg/model/context_test.go

For dev versions, we get a version set like 1.8-alpha.SHA. We do not
know the patch version of these.
This changes the behavior to treat these as the max patch version,
rather than `.0`. This mirrors the bevaior of an unset version, which is
also treated as "latest".
The motivation for this is to allow checks like `>= 1.8.1`; with the
current code the dev builds do not pass this check.
Blocker for https://github.com/istio/istio/pull/29333

Treat unset patch as highest, rather than lowest, patch version

---

tests/integration/iop-integration-test-defaults.yaml

This is helpful for local testing, where we run multiple times.
Currently, the eastwest gateway would get pruned since the IstioOperator
of the control plane has no name.
Possible we should look into making it so this isn't needed, filing
another issue for that: https://github.com/istio/istio/issues/29633

Do not prune eastwest gateway on deployment

---

pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/serviceregistry_test.go
releasenotes/notes/vm-multiple-targetport.yaml

Previously, if you have a service with multiple ports, only the first targetPort is applied - the rest will get the targetPort ignored. This was due to an optimization trying to make serviceInstancesFromWorkloadInstances only called for O(services) rather than O(services*ports).
This removes the optimization, fixing the bug. I don't think we need to fix the optimization as its over complex for minimal gain IMO. If we see this showing high usage we can re-evaluate

Fix Services with multiple ports and targetPort selecting WorkloadEntry

---

tests/integration/pilot/common/routing.go

Otherwise it gets the random namespace in the name, which makes
test-grid look bad
[ ] Docs
[ ] Networking
[ ] Security

Make test name deterministic

---

pilot/cmd/pilot-agent/main.go
pilot/cmd/pilot-agent/status/ready/probe.go
pilot/cmd/pilot-agent/status/server.go
pilot/pkg/xds/ads.go
pilot/pkg/xds/workloadentry.go
pkg/istio-agent/agent.go
pkg/istio-agent/health/health_check.go
pkg/istio-agent/health/health_check_test.go
pkg/istio-agent/health/health_probers.go
pkg/istio-agent/xds_proxy.go

Currently we only check application health. This expands this to also
perform the same health checks that k8s gets on the agent. These are
aggregated with AggregateProbe.
Depends on https://github.com/istio/istio/pull/29426

Add envoy health check for VMs

---

galley/pkg/config/analysis/diag/message.go
galley/pkg/config/analysis/diag/message_test.go
releasenotes/notes/29445.yaml

Fixes https://github.com/istio/istio/issues/29445
Relates to https://github.com/kiali/kiali/issues/3505
The severity level for the `validationMessages` in the status field are not present.
It looks like the mapping from Message descriptor the the message object was wrong (needs to be uppercased).
[ ] Docs
[ ] Networking
[ ] Security

Fixing wrong message level mapping in validationMessages

---

istioctl/cmd/testdata/inject-config.yaml
pkg/kube/inject/inject.go
pkg/kube/inject/inject_test.go
pkg/kube/inject/webhook.go
pkg/kube/inject/webhook_test.go

I originally added this in an attempt to support reading 1.8 template by
1.9 istiod. This is *not* something we have backwards compatibility
guarantees, and its something we have broken almost every release.
I later realized its not feasible to support this, and since its not
even very useful (it mostly helps when someone accidentally uses the
`latest` image but release charts - which is good to fail fast). So this
PR cleans it up.
[ ] Docs
[ ] Networking
[ ] Security …

injection: remove attempted legacy injection template support

---

pilot/pkg/model/status/helper.go
pilot/pkg/xds/fake.go
pkg/istio-agent/xds_proxy.go
pkg/istio-agent/xds_proxy_test.go

Fixes https://github.com/istio/istio/issues/29648
This ensures we always send a health update for the most recent state
when we reconnect to Istiod. This handles cases where health changes
while disconnect, as well as cases where our WorkloadEntry is removed
entirely (perhaps an extended disconnect from Istiod) and we reconnect.

Make health check messages resiliance to reconnections

---

istioctl/pkg/verifier/verifier.go

Resolves https://github.com/istio/istio/issues/26266
Fixing the following:
- if using a file IOP with no namespace set, defaults to `default` instead of `istio-system` for control plane components
- Does not count Deployment if other things in IOP are incorrect -- we want to acknowledge there was at least an IOP
- If we fail because of something early (e.g. no manifests) we should display that failure rather than having a generic message
cc @ostromart @su225 it would be great if one of you could review

'istioctl verify-install' improper default of Istio namespace

---

pilot/pkg/dns/dns.go
pilot/pkg/dns/dns_test.go

Sending NXDOMAIN means we are able to handle the request, and we know
it does not exist. Instead, we should send an err.
This was tested with
https://www.dns-oarc.net/files/dnsperf/data/queryfile-example-10million-201202.gz,
comparing the results of DNS queries through the proxy and direct.
[ ] Docs
[ ] Networking
[ ] Security

Do not send NXDOMAIN on dns failures

---

pilot/pkg/dns/dns.go
pilot/pkg/dns/dns_test.go
releasenotes/notes/29681.yaml

The answer records for the CNAME did not have any class. This works for
some code paths in glibc, but it does not work when `ai_family` is set to
`AF_INET`.
$ nslookup www.google.com
;; Warning: Message parser reports malformed message packet.
Server:		172.20.0.10
Address:	172.20.0.10#53
Non-authoritative answer:
www.google.com.namespace.svc.cluster.local	canonical name = www.google.com.
Name:	www.google.com
Address: 240.240.0.13
** server can't find www.google.com: NXDOMAIN
Fixes #29681
[ ] Docs
[X] Networking
[ ] Security …

Set INET class for CNAME response

---

istioctl/pkg/verifier/verifier.go

Part of https://github.com/istio/istio/issues/29371
Follow up for https://github.com/istio/istio/pull/29442
Install multiple control planes.
```
[istio-1.7.4]$ ./bin/istioctl install
[istio-1.8.1]$ ./bin/istioctl install -r 1-8-1
[istio-master]$ ./out/linux_amd64/istioctl install -r 1-9-0
```
```
$ k get pod -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-5b67df9bf4-qxb6k   1/1     Running   0          49s
istiod-1-8-1-7b67c8cdfc-4rzcv           1/1     Running   0          2m2s
istiod-1-9-0-7fcf88df57-wmw99           1/1     Running   0          53s
istiod-7c487bdcd7-sb2t8                 1/1     Running   0          4m26s
```
**Notice**: `3 Istio control planes detected, checking --revision 1-9-0 only`.
```
$ …
```

istioctl verify-install:  display count of multiple control planes

---

pilot/pkg/xds/ads.go
pilot/pkg/xds/ads_test.go
pilot/pkg/xds/discovery.go
pilot/pkg/xds/simple.go
pilot/pkg/xds/statusgen.go
pkg/istio-agent/local_xds_generator.go

Adds connect/disconnect events back and does minor refactoring (renaming it to statusgen, if folks does not like it I can put it back).
[ ] Docs
[ ] Security

add connect/disconnect events back in internalgen

---

pilot/pkg/xds/filters/filters.go
tools/istio-iptables/pkg/cmd/run.go

It was deprecated since https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.14.0#deprecated

remove use deprecated envoy.listener.original_src

---

pkg/test/framework/components/echo/common/envoy_test.go
pkg/test/framework/components/namespace/kube.go
pkg/test/framework/components/namespace/namespace.go
tests/integration/pilot/revisioned_upgrade_test.go
tests/integration/security/authorization_test.go

Integration test for revision-based upgrades that checks that a rollout completed with updated images and that tests traffic before and after the rollout.
Later work will include making this test agnostic to the upgrade method (i.e. pass in an `UpgradeFunc`, doesn't matter if in-place or revisioned), sending traffic during upgrade, testing that metrics continued to accumate during the upgrade.
/cc @jacob-delgado
[ ] Docs
[ ] Networking
[ ] Security

Add integration test for revision-based upgrade

---

pilot/pkg/model/jwks_resolver.go

For a cluster behind a corporate proxy server, istiod needs internet access to fetch jwt. This PR utilizes the proxy environment variables (say http_proxy) to connect to "issuer" and "jwksUri".
We have edited deployment/istiod using following command:
kubectl set env deployment/istiod http_proxy="http://192.168.1.47:3128" https_proxy="http://192.168.1.47:3128" NO_PROXY="10.234.0.0/20,*.svc.cluster.local,istiod.istio-system.svc,istio-ingressgateway,localhost,*.istio-system.svc" -n istio-system
And to help us figure out who should review this PR, please
[ ] Docs
[x] Networking
[x] Security
[ ] …

Environment proxy pilot
