istio/istio

pkg/istio-agent/health/health_check_test.go
* Use dynamic ports to avoid conflict
* Switch the sync mechanism to avoid race condition causing negative
waitgroup
(https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/28598/unit-tests_istio/1326201514657583104)
[ ] Docs
[ ] Networking
[ ] Security
=> Fix healthcheck test flakes

tests/integration/security/mtls_first_party_jwt/main_test.go, tests/integration/security/pass_through_filter_chain_test.go, tests/integration/security/util/framework.go, tests/integration/security/util/reachability/context.go
[ ] Docs
[ ] Networking
[X] Security
=> Convert TestMtlsStrictK8sCA into multicluster support

pkg/test/framework/components/opentelemetry/kube.go, pkg/test/framework/components/opentelemetry/opentelemetry-collector.go, pkg/test/framework/components/zipkin/kube.go, pkg/test/framework/components/zipkin/zipkin.go, pkg/test/framework/config.go, pkg/test/framework/resource/context.go, prow/integ-suite-kind.sh, tests/integration/telemetry/constants.go, tests/integration/telemetry/tracing/opencensusagent/tracing_test.go, tests/integration/telemetry/tracing/tracing.go, tests/integration/telemetry/tracing/zipkin/clienttracing/client_tracing_test.go, tests/integration/telemetry/tracing/zipkin/servertracing/tracing_test.go, tests/integration/tests.mk
[ ] Docs
[ ] Networking
[ X] Policies and Telemetry
[ ] Security
=> Convert Tracing Tests to use Multicluster and Echo App

go.mod, go.sum, prow/release-commit.sh
```UPDATE_BRANCH=release-1.7 ./bin/update_deps.sh; make gen```
=> Update branch dependencies

go.mod, go.sum, istio.deps, pkg/test/framework/components/stackdriver/kube.go, prow/release-commit.sh
Run ```UPDATE_BRANCH=release-1.6 ./bin/update_deps.sh; make gen```
=> Update release-1.6 dependencies

pilot/pkg/bootstrap/server.go, pilot/pkg/bootstrap/servicecontroller.go, pilot/pkg/model/controller.go, pilot/pkg/serviceregistry/aggregate/controller.go, pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/fake.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go, pilot/pkg/serviceregistry/memory/discovery.go, pilot/pkg/serviceregistry/mock/discovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/xds/fake.go
And to help us figure ot who should review this PR, please 
[ ] Docs
[ ] Networking
[ ] Security
=> Cleanup controller interface

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
=> Workloadentry add should trigger push to the proxy

releasenotes/notes/25669.yaml
=> Fix release notes for Mixer to point to docs

pilot/pkg/features/pilot.go
Mitigation for https://github.com/istio/istio/issues/28315
[ ] Docs
[ ] Networking
[ ] Security
=> Disable gateway scoping

pilot/pkg/serviceregistry/aggregate/controller.go, pilot/pkg/serviceregistry/aggregate/controller_test.go
=> Remove middle registries variable

tests/integration/security/chiron/main_test.go
[ ] Docs
[ ] Networking
[x] Security
=> Remove RequireSingleCluster in chiron test

tests/integration/security/authorization_test.go, tests/integration/security/testdata/authz/v1beta1-conditions.yaml.tmpl, tests/integration/security/util/framework.go, tests/integration/security/util/rbac_util/util.go, tests/integration/security/util/reachability/context.go
[ ] Docs
[ ] Networking
[X] Security
=> Convert first part of authorization tests to be multicluster supported

go.mod, go.sum, prow/release-commit.sh
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.8] Run UPDATE_BRANCH=release-1.8 ./bin/update_deps.sh

tests/integration/security/ca_custom_root/main_test.go, tests/integration/security/ca_custom_root/secure_naming_test.go, tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go, tests/integration/security/ca_custom_root/trust_domain_validation_test.go, tests/integration/security/util/cert/cert.go, tests/integration/security/util/connection/checker.go
[ ] Docs
[ ] Networking
[X] Security
=> Convert ca custom root into multicluster supported

tests/integration/telemetry/outboundtrafficpolicy/traffic_test.go, tests/integration/telemetry/stats/prometheus/nullvm/istioctl_metrics_test.go, tests/integration/telemetry/stats/prometheus/stats.go, tests/integration/telemetry/tracing/opencensusagent/tracing_test.go, tests/integration/telemetry/tracing/zipkin/clienttracing/client_tracing_test.go, tests/integration/telemetry/tracing/zipkin/servertracing/tracing_test.go
Refactor some telemetry tests so they use same suite
[ ] Docs
[ ] Networking
[ X] Policies and Telemetry
[ ] Security
=> Refactor some telemetry tests so they use same suite

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go
Part of https://github.com/istio/istio/issues/28878
This also might fix https://github.com/istio/istio/issues/24915 - not sure if these cases genuinely have 800k pushes being recorded or its getting multiplied by the race
=> Fix PushRequest.Merge race

pkg/istio-agent/sds-agent.go, releasenotes/notes/28813.yaml
Manual cherry pick of https://github.com/istio/istio/pull/26978
[ ] Docs
[ ] Networking
[ ] Security
=> do not run gateway secret fetcher for file mounted certs [cherry pick of 26978]

Makefile.core.mk
Update the base image
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.7] Update 1.7 base image

security/pkg/nodeagent/util/util.go
cc @liminw 
I'd prefer to wait for #28842 to land first, so this will actually be integration tested.
=> restrict permissions of cert and key in agent

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
=> [release-1.7] Workloadentry add should trigger push to the proxy (#28785)

Makefile.core.mk
Update the base image
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.6] Update 1.6 base image

pkg/test/framework/components/environment/kube/cluster.go, pkg/test/framework/components/environment/kube/kube.go, pkg/test/framework/components/istio/ingress.go, pkg/test/framework/components/istio/operator.go, pkg/test/framework/components/istio/util.go, pkg/test/framework/components/istioctl/kube.go, pkg/test/framework/components/namespace/kube.go, pkg/test/framework/resource/cluster.go, pkg/test/kube/dump.go, tests/integration/helm/install_test.go, tests/integration/operator/switch_cr_test.go, tests/integration/pilot/cni/cni_test.go, tests/integration/pilot/istioctl_test.go, tests/integration/pilot/revisions/uninstall_test.go, tests/integration/pilot/webhook_test.go, tests/integration/security/ca_custom_root/secure_naming_test.go, tests/integration/security/chiron/dns_cert_test.go, tests/integration/security/sds_ingress/util/util.go, tests/integration/security/sds_tls_origination/util/util.go, tests/integration/security/util/cert/cert.go, tests/integration/telemetry/dashboard_test.go
Cherry-pick [Test Framework] Cleanup logic for cluster types (#28593)
[ ] Docs
[ ] Networking
[ ] Security
[ X] Test and Release
=> [Release-1.8] [Test Framework] Cleanup logic for cluster types (#28593)

pilot/pkg/features/pilot.go, pkg/istio-agent/xds_proxy.go, pkg/test/framework/components/echo/kube/deployment.go
Manual cherry-pick of #28842
fixes https://github.com/istio/istio/issues/28936
=> [release-1.8] try token if certs specified by PROV_CERT don't exist for the first time bootstrapping (#28842)

tests/integration/telemetry/tracing/opencensusagent/tracing_test.go, tests/integration/telemetry/tracing/zipkin/clienttracing/client_tracing_test.go, tests/integration/telemetry/tracing/zipkin/servertracing/tracing_test.go
Remove verification of cluster-4 in tracing test
[ ] Docs
[ ] Networking
[ X] Policies and Telemetry
[ ] Security
=> Remove verification of cluster-4 in tracing test

tests/integration/tests.mk
[ ] Docs
[ ] Networking
[ ] Security
=> Remove accidentally merged debug logging flags

pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, pkg/config/xds/deprecated.go
Fixes https://github.com/istio/istio/issues/28920
=> Add warnings for using deprecated types and filter names in EnvoyFilter

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go
part of https://github.com/istio/istio/issues/28878
[ ] Docs
[ ] Networking
[ ] Security
=> Fix concurrent push context initialization

tests/integration/security/sds_ingress/ingress_test.go, tests/integration/security/sds_ingress_gateway/ingress_test.go
[ ] Docs
[ ] Networking
[X] Security
=> Remove RequireSingleCluster for sds related tests

tests/integration/security/filebased_tls_origination/destination_rule_tls_test.go, tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go, tests/integration/security/filebased_tls_origination/main_test.go
[ ] Docs
[ ] Networking
[X] Security
=> Remove RequireSingleCluster in filebased tls origination

tools/istio-docker.mk
To help debug https://github.com/istio/istio/issues/28948
To help debug https://github.com/istio/istio/issues/28948
[ ] Docs
[ ] Networking
[ ] Security
=> Add logs to buildkit

pkg/kube/inject/webhook.go
We lock it on write, but don't check the lock on read
Part of https://github.com/istio/istio/issues/28878
[ ] Docs
[ ] Networking
[ ] Security
=> Fix race in sidecar injector

pilot/pkg/serviceregistry/external/servicediscovery.go, pilot/pkg/serviceregistry/external/servicediscovery_test.go
=> [release-1.6] Workloadentry add should trigger push to the associated proxy  (#28785)

operator/pkg/helmreconciler/apply.go
more details found at https://github.com/kubernetes/kubernetes/issues/96351, which requires GKE fix. Keep it in master as it works normally and we can still work and test it out with GKE folkd
=> skip server side apply because of gke neg webhook issue

pilot/pkg/xds/ads.go, pilot/pkg/xds/debug.go, pilot/pkg/xds/discovery.go, pilot/pkg/xds/internalgen.go
fixes https://github.com/istio/istio/issues/28958
[ ] Docs
[ ] Networking
[ ] Security
=> Consistently lock and copy ads clients

galley/pkg/config/testing/basicmeta/generate.go
[ ] Docs
[ ] Networking
[ ] Security
=> Remove duplicate goimport

Makefile.core.mk, tools/build-base-images.sh, tools/istio-docker.mk
[ ] Docs
[ ] Networking
[ ] Security
=> Bump base image again

prow/integ-suite-kind.sh
Part one for https://github.com/istio/istio/issues/29025 to sync KinD versions
=> update multicluster kind image

pilot/pkg/networking/core/v1alpha3/accesslog.go
Fixes #28901
[ ] Docs
[ ] Networking
[X ] Policies and Telemetry
[ ] Security
=> Fix TcpProxyValidationError for accesslog service

istioctl/cmd/dashboard.go, istioctl/cmd/dashboard_test.go, releasenotes/notes/29034.yaml
Fix #28970 
[ ] Docs
[ ] Networking
[ ] Security
=> istioctl/dashboard: fix namespace shorthand flag

go.mod, go.sum, pilot/pkg/config/kube/gateway/conversion.go, tests/integration/pilot/testdata/service-apis-crd.yaml
This bumps us up to the first official release of the API(!). This PR
isn't changing much at all since we were already close to up to date, mostly just ensuring we test with the latest version.
[ ] Docs
[ ] Networking
[ ] Security
=> Update service-apis to the official v1alpha1 release

pkg/test/framework/components/istio/istio.go, pkg/test/framework/components/istio/operator.go, prow/integ-suite-kind.sh, prow/lib.sh
Just to help debugging, especially as we look at slow tests now
=> Improve tracing of test framework timings

tests/integration/pilot/istioctl_test.go
Example failure
https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/1328973466551980032
There is a race here if anything in the cluster changes at the same
moment the test runs, they may be out of sync. This is not a bug.
[ ] Docs
[ ] Networking
[ ] Security
=> Fix racy ProxyStatus tests

pilot/pkg/features/pilot.go
Mitigation for https://github.com/istio/istio/issues/28315
(cherry picked from commit 43eeb780b4a24db8aabda28daf68fef4c1fc85ec)
This was accidentally reverted in https://github.com/istio/istio/commit/cff2cbff1b5788c14920bc4df1773264952f1c55
=> Disable gateway scoping (#28832)

tests/integration/telemetry/policy/envoy_ratelimit_test.go
Unflake Ratelimit Tests
Fixes https://github.com/istio/istio/issues/28949
[ ] Docs
[ ] Networking
[ X] Policies and Telemetry
[ ] Security
=> Unflake Ratelimit Tests

pilot/pkg/security/authz/builder/builder_test.go, pilot/pkg/security/authz/builder/extauthz.go, pkg/config/validation/extensionprovider.go, tests/integration/security/main_test.go
API update in PR: https://github.com/istio/api/pull/1757
cc @howardjohn 
[ ] Docs
[ ] Networking
[x] Security
=> ext_authz: support omitting the namespace in service

manifests/charts/istio-telemetry/mixer-telemetry/templates/deployment.yaml, releasenotes/notes/28916.yaml
Cherry-pick of https://github.com/istio/istio/pull/28952
resolve: https://github.com/istio/istio/issues/28916
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.6] Cherry pick: fix conflict between replicas with hpa

tests/integration/security/ca_custom_root/secure_naming_test.go, tests/integration/security/util/reachability/context.go
[ ] Docs
[ ] Networking
[X] Security
=> Manual cherrypick https://github.com/istio/istio/pull/28928

galley/pkg/config/analysis/msg/messages.gen.go, galley/pkg/config/analysis/msg/messages.yaml
Resolves https://github.com/istio/istio/issues/28889
=> Cherry pick removal of dead analysis codes

pilot/pkg/bootstrap/server_test.go, pilot/pkg/bootstrap/sidecarinjector.go
Fixes https://github.com/istio/istio/pull/29049. The same issue is also in release-1.8, which needed be fixed. 
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.8] Manual cherry-pick for "Fix nil pointer dereference in initSidecarInjector of Pilot (#29049)"

pilot/pkg/model/push_context.go
Adjust code logic in push_context.go
[ ] Docs
[X] Networking
[ ] Security
=> Adjust code logic in push_context.go

Makefile.core.mk
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.6] Update base image for build

pilot/pkg/networking/core/v1alpha3/accesslog.go, pilot/pkg/networking/core/v1alpha3/listener_test.go, releasenotes/notes/nested-json-log.yaml
[ ] Docs
[ ] Networking
[ ] Security
Fixes https://github.com/istio/istio/issues/28597
=> Pilot: allow nested json access log format

pilot/cmd/pilot-agent/status/server.go, pilot/cmd/pilot-agent/status/server_test.go, releasenotes/notes/28344.yaml
Fix #28040 
[ ] Docs
[ ] Networking
[ ] Security
[] Test and Release
/release-note-none
/release-notes-none
=> Add pprof endpoint to pilot-agent

pkg/test/echo/server/endpoint/grpc.go, pkg/test/framework/components/echo/common/call.go, tests/integration/security/authorization_test.go, tests/integration/security/reachability_test.go, tests/integration/security/util/framework.go, tests/integration/security/util/reachability/context.go
[ ] Docs
[ ] Networking
[ ] Security
=> Attempt to turn off 10s reachability sleep

releasenotes/notes/fix-high-memory-usage-due-toserviceentries.yaml
This was created without a release note but is a fix for an issue created by users for high memory usage in their environment.
=> Add release note for 25531

pkg/test/framework/components/istio/operator.go
[ ] Docs
[ ] Networking
[ ] Security
=> Trace istio deploy/teardown in trace.yaml

pilot/cmd/pilot-agent/main.go, pkg/envoy/proxy.go
Fixes https://github.com/istio/istio/issues/28066
[ ] Docs
[ ] Networking
[ ] Security
=> Pass JSON log encoding to envoy logs

istioctl/cmd/describe.go, istioctl/cmd/root.go
[x ] Docs
[ ] Networking
[ ] Security
=> Fix typo in comments

pilot/pkg/serviceregistry/kube/controller/controller.go
Signed-off-by: shaoy <andrew.shaoyu@gmail.com>
[ ] Docs
[ ] Networking
[ ] Security
fix fatal error: concurrent map read and map write
=> workloadInstancesByIP add RClock

tests/integration/pilot/multi_version_revision_test.go
Separates logic for installing a revisioned control plane, adds tcp echo calls to cross-revision traffic tests.
[ ] Docs
[ ] Networking
[ ] Security
=> Refactor multi-version revision test

operator/cmd/mesh/install.go
Cherrypick https://github.com/istio/istio/pull/28253 and https://github.com/istio/istio/pull/28532
Close https://github.com/istio/istio/issues/29179 and https://github.com/istio/istio/issues/29180
[ ] Docs
[ ] Networking
[ ] Security
=> improve istio install req message.

samples/multicluster/README.md, samples/multicluster/expose-istiod-https.yaml, samples/multicluster/expose-istiod.yaml, samples/multicluster/expose-services.yaml, samples/multicluster/gen-eastwest-gateway.sh
prereq for https://github.com/istio/istio.io/pull/8539/
=> backport new multicluster samples

pilot/pkg/model/push_context.go, pilot/pkg/model/sidecar.go, pilot/pkg/model/virtualservice.go, pilot/pkg/model/virtualservice_test.go, pilot/pkg/xds/ads_test.go
Fix: #29123
[ ] Docs
[X] Networking
[ ] Security
=> Fix bug: delegate vs change could not trigger push to sidecars

manifests/charts/istio-telemetry/mixer-telemetry/templates/deployment.yaml, releasenotes/notes/28916.yaml
resolve: https://github.com/istio/istio/issues/28916
[ ] Docs
[ ] Networking
[ ] Security
=> fix conflict between replicas with hpa.

pkg/queue/delay.go, pkg/queue/delay_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> pkg/queue: optimize the delay queue and resolve some TODOs

pkg/kube/util.go
https://istio.slack.com/archives/C37A4KAAD/p1606494243046400
[ ] Docs
[X] Networking
[ ] Security
=> Fix crash when invalid ownerref set

go.mod, pkg/kube/inject/watcher.go
Fix #https://github.com/istio/istio/issues/29194
`github.com/howeyc/fsnotify` is not maintained, and has some issues
https://github.com/istio/istio/issues/29194#issuecomment-734121421
=> Update fsnotify dependency

tests/integration/pilot/common/apps.go, tests/integration/pilot/common/routing.go, tests/integration/pilot/common/traffic.go
Regression test for https://github.com/istio/istio/issues/29199
=> Add test for overlapping service

pkg/test/framework/components/istio/operator.go
fixes https://github.com/istio/istio/issues/29276
=> perform multicluster cleanup in parallel (#29062)

pilot/pkg/bootstrap/server.go, pilot/pkg/xds/debug.go
[ ] Docs
[ ] Networking
[ ] Security
=> Update inject debug handler for new injection logic

pkg/kube/configmapwatcher/configmapwatcher.go
The `Controller.HasSynced()` is used for `cache.WaitForCacheSync()` which will keep polling until the underlying cache has synced and the callback has been called at least once, thus the synchronization of `hasSynced` mark could be in a more lightweight way: an atomic variable instead of a mutex.
[ ] Docs
[ ] Networking
[ ] Security
=> kube/configmapwatcher: leverage atomic variable as sync indication

tools/build-base-images.sh, tools/buildx-gen.sh, tools/istio-docker.mk
This will be needed to publish the base images as multi-architecture
cc @morlay
=> Support multi-arch builds

tests/integration/README.md
[ ] Docs
[ ] Networking
[ ] Security
=> Add best practices link to test README.md.

pilot/pkg/xds/ads.go, pilot/pkg/xds/fake.go, pilot/pkg/xds/workloadentry.go
[ ] Docs
[X] Networking
[ ] Security
=> Reuse envoy interface 

pilot/pkg/xds/bench_test.go, pilot/pkg/xds/fake.go
[ ] Docs
[ ] Networking
[ ] Security
=> Avoid overwhelming push queue in benchmark test

prow/config/endpointslice.yaml
Tested this locally, we were missing the ES controller enablement
=> Properly enable endpoint slice feature

pkg/adsc/adsc.go, pkg/adsc/adsc_test.go
Adsc doesn't remove deleted resources when receving xDS pushing, resulting outdated resources in the local store
Signed-off-by: huabing zhao <huabingzhao@tencent.com>
[ ] Docs
[X] Networking
[ ] Security
=> fix: remove deleted resources from local store

tools/go-ordered-test.sh
[ ] Docs
[ ] Networking
[ ] Security
=> Improve output of go-ordered-test and allow verbose

tests/util/leak/check.go, tests/util/leak/check_test.go
Fixes https://github.com/istio/istio/issues/27919
Adding this to other tests will be in a followup PR to keep it small
scope
[ ] Docs
[ ] Networking
[ ] Security
=> Add a goroutine leak checker

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, pilot/pkg/networking/core/v1alpha3/cluster_test.go, releasenotes/notes/28942.yaml
Fixes https://github.com/istio/istio/issues/28942
[ ] Docs
[ ] Security
=> enable locality weighted config when distribute is present

istioctl/cmd/workload.go, pkg/test/framework/components/echo/common/config.go, pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/components/echo/kube/deployment_test.go, pkg/test/framework/components/echo/kube/instance.go, tests/integration/pilot/vm_test.go
Cherry pick of #29130 which sets up testing for VMs. Future changes will utilize this. 
Also includes a small fix for generating properly formatted proxy config. 
fixes https://github.com/istio/istio/issues/29347
=> set up echo VMs using istioctl workload commands (#29130)

tests/integration/operator/main_test.go
These failures have been reported for over 20 days and are causing
consistent failures accross our tests.
https://github.com/istio/istio/issues/28863
We should not let a single (beta) feature destroy our test stability.
[ ] Docs
[ ] Networking
[ ] Security
=> Skip operator integration tests

pilot/pkg/xds/workloadentry.go
=> Expand logging on auto registration

pilot/pkg/model/push_context.go, pilot/pkg/model/sidecar.go, pilot/pkg/model/virtualservice.go, pilot/pkg/model/virtualservice_test.go, pilot/pkg/xds/ads_test.go, pkg/config/validation/validation.go, pkg/config/validation/virtualservice_test.go, releasenotes/notes/delegate-vs.yaml
Manually cherry-pick #29193
Fix: #29261
=> [release-1.7] delegate vs change could not trigger push to sidecars

istioctl/pkg/install/verify.go
Backporting timestamp unmarshal related fix
fixes https://github.com/istio/istio/issues/25688
[ ] Docs
[ ] Networking
[ ] Security
=> fix managed fields timestamp unmarshal issue (while unmarshaling IOP)

pilot/pkg/serviceregistry/kube/controller/controller.go
Fix typo in comment.
[X] Docs
[ ] Networking
[ ] Security
=> Fix typo in comment

tools/bug-report/pkg/archive/archive.go, tools/bug-report/pkg/bugreport/bugreport.go, tools/bug-report/pkg/common/common.go
To fix https://github.com/istio/istio/issues/28399
=> istioctl bug-report: add istio-operator logs to the cluster archive

prow/lib.sh
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-115_istio_postsubmit/1334941244761051136
I figure this will either pre-warm it when there is less work going on
and it will work, give it 2 shots at starting up, or at the very least
hopefully our log capturing will work and we can finally see what is
failing...
This is pretty much a desperate attempt to get things working
consistently
[ ] Docs
[ ] Networking
[ ] Security
=> Attempt to fix random buildkit failures

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go, pilot/pkg/model/sidecar.go, pilot/pkg/model/sidecar_test.go, pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/plugin/authn/authentication.go, pilot/pkg/xds/ads_common_test.go, releasenotes/notes/29414.yaml
Fix #29414
[ ] Docs
[X] Networking
[ ] Security
=> Fix root ns sidecar influence xds push

pilot/pkg/dns/dns.go, pilot/pkg/dns/dns_test.go, pilot/pkg/dns/proxy.go
This will be helpful for debugging any DNS issues we encounter,
currently we have no visibility into this
=> Add debug logging for DNS

pilot/pkg/bootstrap/server.go, pilot/pkg/model/jwks_resolver.go, pilot/pkg/model/jwks_resolver_test.go, pilot/pkg/model/push_context_test.go, pilot/pkg/model/test/mockopenidserver.go, pilot/pkg/secrets/kube/multicluster.go, pilot/pkg/secrets/kube/secrets_test.go, pilot/pkg/serviceregistry/kube/controller/fake.go, pilot/pkg/xds/ads_test.go, pilot/pkg/xds/debug_test.go, pilot/pkg/xds/discovery_test.go, pilot/pkg/xds/fake.go, pilot/pkg/xds/pushqueue_test.go, pkg/kube/secretcontroller/secretcontroller.go
Depends on https://github.com/istio/istio/pull/29351 and https://github.com/istio/istio/pull/29350
=> Fix a bunch of goroutine leaks in our tests

pilot/pkg/model/context.go, pilot/pkg/model/service.go, pilot/pkg/xds/nds_test.go, pkg/test/framework/components/echo/kube/instance.go, releasenotes/notes/auto-allocate-dns.yaml, tests/integration/pilot/istioctl_test.go
Fixes https://github.com/istio/istio/issues/29324
[ ] Docs
[ ] Networking
[ ] Security
=> Split DNS Auto allocate from dns capture

tests/integration/telemetry/tracing/tracing.go
Before we called Build() multiple times on the loop
=> tracing test: fix echo deployment

releasenotes/notes/29427.yaml
from https://github.com/istio/istio/issues/29427 so it can be generated upon 1.8 upgrade note.
[x ] Docs
[x ] Networking
[ ] Security
=> Add a release note for upgrade issue

pilot/pkg/networking/core/v1alpha3/cluster_builder.go
https://github.com/istio/istio/pull/29513#discussion_r539881122
[ ] Docs
[ ] Security
=> remove unnecessary condition

pilot/pkg/features/pilot.go, pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/listener_test.go
[x ] Docs
[x ] Networking
[ ] Security
=> update trace sampling default in desp

pkg/test/echo/server/forwarder/protocol.go
Forgot the final piece to wire it through
[ ] Docs
[ ] Networking
[ ] Security
=> Fix missing part of ALPN client code

istioctl/pkg/verifier/verifier.go
To fix https://github.com/istio/istio/issues/29440
Part of https://github.com/istio/istio/issues/28148
```
[istio-master] $ ./out/linux_amd64/istioctl install --revision 1-9-0 --set hub=gcr.io/istio-testing -d manifests/
✔ Istio core installed                                                                                                                
✔ Istiod installed                                                                                                                    
✔ Ingress gateways installed                                                                                                          
✔ Installation complete
```
```
$ ./out/linux_amd64/istioctl verify-install
✔ ClusterRole: istiod-istio-system.default checked successfully
✔ ClusterRole: …
```
=> istioctl verify-install: use revision from istiod if it is empty

samples/multicluster/expose-istiod-https.yaml, samples/multicluster/expose-istiod.yaml, samples/multicluster/gen-eastwest-gateway.sh
Backports https://github.com/istio/istio/pull/28657 and https://github.com/istio/istio/pull/27976 to 1.8
=> [release-1.8] backport updated east-west gateway samples

istioctl/cmd/testdata/vmconfig/simple/mesh.yaml.golden, istioctl/cmd/testdata/vmconfig/simple/workloadgroup.yaml, istioctl/cmd/workload.go, pilot/pkg/model/status/helper.go, pilot/pkg/model/status/workloadentry.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceregistry_test.go, pilot/pkg/xds/workloadentry.go
* Propogate WorkloadGroup to ProxyConfig
* Read health status in registry
=> Propogate WG readiness probe to proxy config

pilot/pkg/model/context.go, pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/controller_test.go, pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go, pilot/pkg/serviceregistry/kube/controller/endpoints.go, pilot/pkg/serviceregistry/kube/controller/endpointslice.go, pilot/pkg/serviceregistry/kube/controller/pod.go, pilot/pkg/serviceregistry/kube/controller/pod_test.go, pilot/pkg/serviceregistry/kube/controller/util.go, pilot/pkg/serviceregistry/kube/controller/util_test.go, pilot/pkg/serviceregistry/kube/conversion.go, pilot/pkg/serviceregistry/serviceregistry_test.go
fix #28981
[ ] Docs
[X] Networking
[ ] Security
=> Fix getting pod of hostnetwork

operator/cmd/mesh/upgrade.go, operator/cmd/mesh/upgrade_test.go, releasenotes/notes/29183.yaml
Manual cherry-pick of https://github.com/istio/istio/pull/29191
This will fix https://github.com/istio/istio/issues/29439
=> [release-1.7] istioctl upgrade: fix downgrade to lower version

releasenotes/notes/locality-lb-docs.yaml
[x] Docs
[ ] Networking
[ ] Security
=> Add release notes for updated locality LB docs

pilot/pkg/bootstrap/configcontroller.go, pilot/pkg/controller/workloadentry/workloadentry_controller.go, pilot/pkg/controller/workloadentry/workloadentry_controller_test.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/ads_test.go, pilot/pkg/xds/discovery.go, pilot/pkg/xds/internalgen.go, pilot/pkg/xds/simple.go, tests/integration/pilot/vm_test.go
[ ] Docs
[X] Networking
[ ] Security
=> Simplify internal generator and refactor a wle controller

tests/integration/pilot/multi_version_revision_test.go
Fixes postsubmit failures caused by deploying 1.7 on k8s 1.15 @howardjohn 
[ ] Docs
[ ] Networking
[ ] Security
=> Skip MultiVersionRevisionTest on too-old k8s versions

releasenotes/notes/multicluster-global-domain.yaml, releasenotes/notes/multicluster-install-docs.yaml
[x] Docs
[ ] Networking
[ ] Security
=> Add release notes for multicluster docs and deprecation of .global

pkg/test/framework/components/istio/config.go, pkg/test/framework/components/istio/flags.go, pkg/test/framework/components/istio/istio.go, pkg/test/framework/components/istio/operator.go, tests/integration/README.md, tests/integration/security/file_mounted_certs/main_test.go, tests/integration/security/mtlsk8sca/main_test.go, tests/integration/security/sds_ingress_k8sca/main_test.go
Given a few tests can't work with east west gw today, follow up PR from https://github.com/istio/istio/pull/28296#issuecomment-742826062
[ ] Docs
[ ] Networking
[ ] Security
[x ] Test and Release
=> Allow a flag to deploy ew gateway

pilot/pkg/networking/plugin/plugin.go
[X] Docs
[ ] Networking
[ ] Security
=> Remove useless comment.

pilot/pkg/config/aggregate/config.go, pilot/pkg/config/aggregate/config_test.go, pilot/pkg/config/kube/crdclient/client.go, pilot/pkg/config/kube/crdclient/client_test.go, pilot/pkg/config/kube/crdclient/gen/types.go.tmpl, pilot/pkg/config/kube/crdclient/types.gen.go, pilot/pkg/config/kube/gateway/controller.go, pilot/pkg/config/kube/ingress/controller.go, pilot/pkg/config/memory/config.go, pilot/pkg/config/memory/controller.go, pilot/pkg/config/memory/monitor_test.go, pilot/pkg/config/monitor/monitor.go, pilot/pkg/controller/workloadentry/workloadentry_controller.go, pilot/pkg/controller/workloadentry/workloadentry_controller_test.go, pilot/pkg/model/authorization_test.go, pilot/pkg/model/config.go, pilot/pkg/model/fake_store.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go, pilot/pkg/serviceregistry/serviceregistry_test.go, pilot/pkg/xds/ads_test.go, pilot/test/mock/config.go, pkg/adsc/adsc.go, pkg/istio-agent/xds_proxy_test.go
cc @stevenctl take a look at the latest two commits
Based on #29554
[ ] Docs
[X] Networking
[ ] Security
=> Handle wle register/unregister race

releasenotes/notes/29681.yaml
Copy & paste error
[X] Docs
[ ] Networking
[ ] Security
=> Fix issue number in release notes for #29681

tests/integration/pilot/multi_version_revision_test.go
Adds another traffic type to the multi-version revision test, refactors cleanup logic to be more idiomatic
[ ] Docs
[ ] Networking
[ ] Security
=> TestMultiVersionRevisionTest: add grpc calls

pilot/pkg/xds/discovery.go
Addresses comment https://github.com/istio/istio/pull/29705#discussion_r546794360
[ ] Docs
[ ] Security
=> move to watching instead of using locks in sendResponse

pkg/kube/inject/inject.go, pkg/kube/inject/inject_test.go, pkg/kube/inject/testdata/inject/multiple-templates.yaml, pkg/kube/inject/testdata/inject/multiple-templates.yaml.injected, pkg/kube/inject/webhook.go
Part of
https://docs.google.com/document/d/1Rmp9B3DDypgMCau-YAqidx_r3qvKLZj6jUX-t22zj84
This adds support for selecting multiple templates, as well as providing aliases for the templates
=> Support multiple injection templates

pilot/pkg/controller/workloadentry/workloadentry_controller.go, pilot/pkg/controller/workloadentry/workloadentry_controller_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fix leaks in workload entry controller

pilot/pkg/xds/ads_test.go
Example:
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29646/unit-tests_istio/1344009311113711616
Also renamed it since we have two tests named the same which is
confusing.
The issue here is not related to the cache at all, but expecting XDS to
be strongly ordered. If a spurious EDS push occurs, we may expect it to
be updated too quickly. Instead, we should retry until we get the
desired state (eventually consistency is fun).
Local test: `2375 runs so far, 0 failures (100.00% pass rate). 1.828031302s avg, 7.819774289s max, 879.418829ms min`
[ ] Docs
[ ] Networking
[ ] Security
Pull Request …
=> Fix TestXdsCache flakes

pilot/pkg/serviceregistry/kube/controller/multicluster.go, tests/integration/pilot/validation_test.go
Related to:
https://github.com/istio/istio/issues/29419
https://github.com/istio/istio/issues/29600
=> multicluster: split validation and injection patch start

pkg/kube/inject/webhook_test.go
The metrics reporter is eventually consistent, so we need to retry.
Also switch to a more reliable method to export the metrics values.
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29805/unit-tests_istio/1344360137158037504
`1526 runs so far, 0 failures (100.00% pass rate). 1.504449281s avg, 2.196549208s max, 832.041271ms min`
=> Fix TestRunAndServe test flakes

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
=> minor fixes to cluster builder

galley/pkg/config/analysis/analyzers/multicluster/meshnetworks.go, pilot/pkg/serviceregistry/providers.go
[ ] Docs
[ ] Networking
[ ] Security
=> remove mcp Provider

istioctl/cmd/dashboard.go, istioctl/cmd/dashboard_test.go, releasenotes/notes/29032.yaml
Fix #29022
[ ] Docs
[ ] Networking
[ ] Security
=> istioctl/dashboard: add option to support skip browser open

pkg/test/framework/components/echo/kube/deployment.go, samples/extauthz/ext-authz.yaml, tests/integration/security/authorization_test.go
[ ] Docs
[ ] Networking
[X] Security
=> update ext-authz sample app tag

tests/integration/security/authorization_test.go, tests/integration/security/testdata/authz/v1beta1-custom.yaml.tmpl
[ ] Docs
[ ] Networking
[X] Security
=> [ext-authz] Add integration tcp test

pilot/pkg/bootstrap/server.go, pilot/pkg/xds/ads.go
[ ] Docs
[x] Networking
[ ] Security
=> Reorder the server start and the waitCacheSync

pilot/pkg/dns/proxy.go
Fixes #29526 
Signed-off-by: Kailun Qin <kailun.qin@hotmail.com>
=> dns agent: server should be served over localhost only

pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, tools/packaging/common/envoy_bootstrap.json
To reduce DNS load when zipkin is not installed in cluster.
For https://github.com/istio/istio/issues/29898
=> Bump DNS refresh rate for zipkin

istioctl/pkg/verifier/verifier.go, releasenotes/notes/29855.yaml
Resolves https://github.com/istio/istio/issues/29607
=> If no IOP is present, 'istioctl verify-install' detects Istio using Istio's webhook

Makefile.core.mk, bin/retry.sh, tools/istio-docker.mk
Fixes https://github.com/istio/istio/issues/29847
[ ] Docs
[ ] Networking
[ ] Security
=> Add retries around infrastructure flakes

pkg/config/mesh/mesh.go, pkg/config/mesh/watcher.go
**What this PR does?**
https://github.com/istio/istio/blob/e60c24a399ab0e8293abfc74e9c7d7b7e7e4391e/pkg/config/mesh/mesh.go#L33
`mesh.go` import `filewatcher` but do nothing about watch. It seems disturbed.
This PR move `addFileWatcher ` to appropriate place.
=> refine config/mesh code

pilot/pkg/controller/workloadentry/workloadentry_controller.go, pilot/pkg/controller/workloadentry/workloadentry_controller_test.go, pilot/pkg/xds/ads.go, pkg/istio-agent/health/health_check.go, pkg/istio-agent/health/health_check_test.go
=> Handle healthcheck info missing

pilot/docker/Dockerfile.proxyv2
[ ] Docs
[ ] Networking
[ ] Security
=> Add doc on where distroless is built from

Makefile.core.mk
Update base image to satisfy imagescanner
=> [release-1.8] Update base image

pilot/pkg/networking/core/configgen.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/extension_configuration_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/extension_configuration_patch_test.go, pilot/pkg/networking/core/v1alpha3/extension_config_builder.go, pilot/pkg/xds/discovery.go, pilot/pkg/xds/ecds.go, pilot/pkg/xds/ecds_test.go, pilot/pkg/xds/testdata/ecds.yaml, pilot/pkg/xds/v3/model.go, pkg/config/xds/xds.go
ref: https://github.com/istio/istio/issues/29989
=> Add ECDS support to istiod.

pilot/cmd/pilot-agent/config.go, pilot/cmd/pilot-agent/main.go, pkg/bootstrap/config.go
* Avoid logging fully Proxy struct; we only care about a few fields and
its masssive
* Remove warnings that are expected
* Remove duplicate IP address logging
[ ] Docs
[ ] Networking
[ ] Security
=> Cleanup istio-agent logs

pilot/pkg/networking/core/v1alpha3/extension_config_builder.go, pilot/pkg/xds/ecds.go
Address comments added in https://github.com/istio/istio/pull/29990 after merging.
=> Clean up ECDS generator code.

pkg/istio-agent/agent_test.go
RSA keys are too slow for our CI to handle with -race enabled. Instead,
switch to ECC by default, and make just one test use RSA.
Additionally, bump the timeout up a bit more just in case.
[ ] Docs
[ ] Networking
[ ] Security
=> Fix TestAgent flakes

tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go, tests/integration/telemetry/stats/prometheus/customizemetrics/testdata/attributegen_envoy_filter.yaml
1. update classify metric test to include grpc
2. update test to adapt to multicluster framework
=> update classify metric test to include grpc and for multicluster

tests/integration/security/authorization_test.go, tests/integration/security/pass_through_filter_chain_test.go, tests/integration/security/util/framework.go
[ ] Docs
[ ] Networking
[X] Security
=> Refactor security integration tests echo deployments

common/Makefile.common.mk, prow/release-commit.sh
Use release-1.9 branch. Don't publish latest tag
[ ] Docs
[ ] Networking
[ ] Security
=> Update branch from master to release-1.9; don't publish latest

Makefile.core.mk
=> [release-1.9] Update base version to 1.9-dev.2

tests/integration/pilot/analysis/main_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> enable mc tests for status

pkg/test/framework/resource/matcher.go, pkg/test/framework/resource/matcher_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Stop skipping all tests

pkg/test/framework/suite.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fix automatic suite naming when run outside GOPATH

pkg/adsc/adsc_test.go
For https://github.com/istio/istio/issues/29910
=> Make TestADSC_Save runnable in parallel

pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/networkfilter.go, releasenotes/notes/30067.yaml
Fixes https://github.com/istio/istio/issues/30067
[ ] Docs
[ ] Security
=> allow idle timeout of 0s

common/scripts/kind_provisioner.sh, pilot/pkg/serviceregistry/kube/controller/util_test.go, pilot/pkg/xds/debug.go
To facilitate debugging multi clusters
[ ] Docs
[X] Networking
[ ] Security
=> Multi cluster: add debug interface for push context

pilot/pkg/model/push_context.go, pilot/pkg/security/authn/factory/factory.go
=> Simplify meshnetworks init

pkg/istio-agent/xds_proxy.go
This was turned into TokenProvider, shared with CA code
[ ] Docs
[ ] Networking
[ ] Security
=> Remove deadcode: fileTokenSource

tests/integration/telemetry/stats/prometheus/stats.go
Test for https://github.com/istio/istio/issues/25185, https://github.com/istio/istio/issues/20538
=> Add stats test for server without sidecar.

samples/bookinfo/policy/productpage_envoy_ratelimit.yaml
=> Stop using deprecated typeurl and filter name

pilot/pkg/xds/v3/model.go
[ ] Docs
[ ] Networking
[ ] Security
=> Clean up extension config type const.

Makefile.core.mk, bin/retry.sh
[ ] Docs
[ ] Networking
[ ] Security
=> Fix retry.sh not failing due to piping

prow/integ-suite-kind.sh
[ ] Docs
[ ] Networking
[ ] Security
=> Update to kind 1.20.0

galley/pkg/config/analysis/analyzers/analyzers_test.go, galley/pkg/config/analysis/analyzers/annotations/annotations.go, galley/pkg/config/analysis/analyzers/util/find_errorline_utils.go, galley/pkg/config/analysis/msg/messages.gen.go, galley/pkg/config/analysis/msg/messages.yaml, releasenotes/notes/29918.yaml
Cherry pick https://github.com/istio/istio/pull/29918 into 1.9
=> annotation deprecation and alpha status analyzer (#29918)

pilot/pkg/model/jwks_resolver.go, tests/integration/security/authorization_test.go, tests/integration/security/testdata/authz/v1beta1-custom.yaml.tmpl
[ ] Docs
[ ] Networking
[X] Security
=> [ext-authz] add e2e test to ingress gateway

pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
Fixes https://github.com/istio/istio/issues/30191
=> Fix envoyfilter matching virtual inbound passthrough

pilot/pkg/status/state.go, pilot/pkg/status/state_test.go
=> improve performance of casting status type

pilot/pkg/model/push_context.go, pilot/pkg/security/authn/factory/factory.go, pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/network.go, pilot/pkg/xds/fake.go, pilot/pkg/xds/mesh_network_test.go, releasenotes/notes/30070.yaml
Manual cherry-pick of #30070. Fixes #30185. Had to include a refactor PR #30157.
=> [release-1.9] trigger push when networks change

pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/network.go
make gateway service's externalIPs takes precedence.
[ ] Docs
[X] Networking
[ ] Security
=> Fix externalips overridden

security/pkg/stsservice/server/server.go, security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin.go
Otherwise we may try to do unneccesary work
[ ] Docs
[ ] Networking
[ ] Security
=> Only call DumpRequest when debug logs are enabled

tests/integration/operator/switch_cr_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Update info output to expanded yaml

galley/pkg/config/analysis/local/source.go, galley/pkg/config/processing/session.go, galley/pkg/config/source/kube/apiserver/source.go, galley/pkg/config/source/kube/apiserver/status/controller.go, go.sum, pilot/pkg/bootstrap/configcontroller.go
Fixes #22478
Fixes #30160 
Fixes #30133
=> prevent panics in galley

pkg/config/validation/validation.go
Fixes https://github.com/istio/istio/issues/30225
[ ] Docs
[ ] Networking
[ ] Security
=> Allow new retryOn policies

go.mod, go.sum
fix failed of istio-testing applying
Fixes: https://github.com/istio/istio/issues/30249
=> fix failed of istio-testing applying

pkg/kube/portforwarder.go
=> Fix dash command bind local addres always localhost

tests/integration/telemetry/stats/prometheus/nullvm/istioctl_metrics_test.go, tests/integration/telemetry/stats/prometheus/stats.go
=> call WithClusters in prometheus echo setup

go.mod, go.sum, prow/release-commit.sh
Run BUILD_WITH_CONTAINERS=1 UPDATE_BRANCH=master ./bin/update_deps.sh; make gen
[ ] Docs
[ ] Networking
[ ] Security
=> Update dependencies with update_deps.sh; update code due to changed libraries

pkg/wasm/cache.go, pkg/wasm/convert.go, pkg/wasm/httpfetcher.go, pkg/wasm/monitoring.go
https://github.com/istio/istio/issues/29989
=> Add metrics for Wasm module cache and config conversion.

tests/integration/security/sds_ingress/ingress_test.go, tests/integration/security/sds_ingress/util/util.go, tests/integration/security/sds_ingress_k8sca/main_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Share echo deployment in ingress test for performance

tests/integration/pilot/common/routing.go, tests/integration/pilot/common/traffic.go
This tests some iptables rules we don't have much coverage for. No code
changes, just adding tests.
[ ] Docs
[ ] Networking
[ ] Security
=> Add test for self-calls

pkg/test/framework/components/echo/kube/instance.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fix empty network in workload group

pilot/pkg/networking/core/v1alpha3/gateway_simulation_test.go
For https://github.com/istio/istio/issues/30321. Just asserting the
current, broken, behavior
[ ] Docs
[ ] Networking
[ ] Security
=> Add negative test case for duplicate virtual services

pilot/pkg/bootstrap/istio_ca.go, pilot/pkg/bootstrap/options.go, pilot/pkg/bootstrap/server.go, pilot/pkg/bootstrap/server_test.go, releasenotes/notes/30294.yaml, security/pkg/server/ca/authenticate/oidc.go, security/pkg/server/ca/authenticate/oidc_test.go
Please provide a description for what this PR is for: due to auto merge conflicts https://github.com/istio/istio/issues/30341, this PR is to manually cherrypick https://github.com/istio/istio/pull/30294 from master branch to release-1.9 branch.
[ ] Docs
[X ] Security
=> [Cherry-pick into release-1.9] OIDC JWT authenticator (#30294)

pilot/pkg/status/reporter.go
Reporter's `dirty` field is not necessary ,  no code read this field.
[ ] Docs
[ ] Networking
[*] Policies and Telemetry
[ ] Security
[*] Does not have any changes that may affect Istio users.
=> remove Reporter's *dirty* field

pkg/test/framework/components/opentelemetry/kube.go, pkg/test/framework/components/zipkin/kube.go, pkg/test/framework/config.go, pkg/test/framework/integration/framework_test.go, pkg/test/framework/resource/context.go, pkg/test/framework/suite_test.go, pkg/test/framework/suitecontext.go, pkg/test/framework/testcontext.go, pkg/test/util/yml/file.go, pkg/test/util/yml/parts.go, tests/integration/helm/upgrade/helm_upgrade_test.go, tests/integration/pilot/analyze_test.go, tests/integration/pilot/ingress_test.go, tests/integration/pilot/istioctl_test.go, tests/integration/pilot/locality_test.go, tests/integration/pilot/mirror_test.go, tests/integration/pilot/multi_version_revision_test.go, tests/integration/pilot/revisioned_upgrade_test.go, tests/integration/pilot/validation_test.go, tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
* Rename WhenDone to ConditionalCleanup, to avoid ambiguity.
* Allow calling cleanup functions in suite context
This is a pre-cursor PR to one that will make ApplyYAML automatically
cleanup. I may just send that as a followup commit if the reviews are
slow.
[ ] Docs
[ ] Networking
[ ] Security
=> Improvements to test framework cleanup

pkg/adsc/adsc_test.go
For https://github.com/istio/istio/issues/29910
=> Make TestADSC_Run runnable in parallel

pilot/cmd/pilot-agent/main.go, pkg/bootstrap/config.go, pkg/bootstrap/option/instances.go, pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json, pkg/envoy/proxy.go, tools/packaging/common/envoy_bootstrap.json
This was a backup plan for xdsproxy, to enable use of JWT from Envoy
directly. Since xdsproxy is now default/stabilized, we don't need this
anymore
[ ] Docs
[ ] Networking
[ ] Security
=> Remove experimental CALL_CREDENTIALS option

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_test.go, pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/gateway_test.go, pilot/pkg/networking/util/util.go, pilot/pkg/security/authn/utils/utils.go, pilot/pkg/security/authn/utils/utils_test.go, pilot/pkg/security/authn/v1beta1/policy_applier_test.go, pilot/pkg/security/model/authentication.go, pilot/pkg/security/model/authentication_test.go, pkg/bootstrap/option/convert.go, pkg/bootstrap/option/convert_test.go, pkg/bootstrap/option/instances_test.go, pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json, tools/packaging/common/envoy_bootstrap.json
The new proxy has fixed the setNodeOnFirstMessage only bug. This PR adds that feature to Istio.
[ ] Docs
[ X] Security
=> set node on first message only

galley/pkg/server/settings/args.go, istioctl/cmd/describe.go, pkg/test/framework/components/cluster/aggregate/factory.go, pkg/test/framework/components/cluster/aggregate/factory_test.go, pkg/test/framework/components/cluster/factory.go, pkg/test/framework/components/cluster/fake/fake.go, pkg/test/framework/components/cluster/kube/factory.go, pkg/test/framework/components/cluster/topology.go, pkg/test/framework/components/echo/kube/deployment_test.go, pkg/test/framework/components/echo/kube/instance.go, pkg/test/framework/components/environment/kube/fake.go, pkg/test/framework/components/environment/kube/flags.go, pkg/test/framework/components/environment/kube/kube.go, pkg/test/framework/components/environment/kube/settings.go, pkg/test/framework/components/redis/redis.go, pkg/test/framework/resource/cluster.go, pkg/test/framework/resource/environment.go, pkg/test/framework/suite.go, pkg/test/framework/suite_test.go, prow/config/topology/multicluster-large.json, prow/config/topology/multicluster.json, prow/config/topology/single.json, prow/integ-suite-kind.sh, prow/lib.sh, tests/integration/tests.mk
Cherry-pick #30288
Tests may fail without a common-files cherry-pick. 
fixes https://github.com/istio/istio/issues/30330
=> [release-1.8] test framework: read kubeconfig path from topology file (#30288)

pilot/cmd/pilot-agent/main.go, pkg/security/security.go, releasenotes/notes/29942.yaml, security/pkg/nodeagent/caclient/credentials.go, security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go, security/pkg/stsservice/mock/faketokenmanager.go, security/pkg/stsservice/server/server.go, security/pkg/stsservice/sts.go, security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin.go, security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin_test.go, security/pkg/stsservice/tokenmanager/tokenmanager.go, security/pkg/stsservice/tokenmanager/tokensource.go
Please provide a description for what this PR is for: https://github.com/istio/istio/issues/30421
Due to the merge conflicts, manual cherry-picking is required.
[ ] Docs
[ ] Networking
[X ] Security
=> [release-1.9] Add an option to enable token exchange for the XDS flow (#29942)

pilot/cmd/pilot-agent/config/config.go, pilot/cmd/pilot-agent/config/config_test.go, pilot/cmd/pilot-agent/main.go, pilot/cmd/pilot-agent/security/security.go, security/pkg/nodeagent/caclient/credentials_test.go
Please provide a description for what this PR is for: https://github.com/istio/istio/issues/30419
Due to the merge conflicts, manual cherry-picking is required.
This PR depends on https://github.com/istio/istio/pull/30422, so it should be rebased and merged after https://github.com/istio/istio/pull/30422 is merged.
[ ] Docs
[ ] Networking
[X ] Security
=> [release-1.9]Add tests for getting tokens for XDS (#30411)

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go
fix: #30387
[ ] Docs
[X] Networking
[ ] Security
=> Fix namespace isn't resolved correctly in VirtualService delegation

galley/pkg/config/analysis/analyzers/analyzers_test.go, galley/pkg/config/analysis/analyzers/annotations/annotations.go
Resolves https://github.com/istio/istio/issues/30405
=> Don't report when alpha annotations are used

manifests/charts/istio-operator/templates/clusterrole.yaml
cherrypick istio-operator permission of https://github.com/istio/istio/pull/29752 to release-1.8
resolve: https://github.com/istio/istio/issues/30106
[ ] Docs
[ ] Networking
[ ] Security
=> cherrypick istio-operator permission update in 29752 to release-1.7

pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
=> [release-1.7] Fix envoyfilter matching virtual inbound passthrough

manifests/profiles/empty.yaml, manifests/profiles/minimal.yaml
resolve: https://github.com/istio/istio/issues/30056 and https://github.com/istio/istio/issues/30018
[ ] Docs
[ ] Networking
[ ] Security
=> cherrypick 27198 to release-1.7.

Makefile.core.mk
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.7] Update the base image

galley/pkg/config/analysis/analyzers/all.go, galley/pkg/config/analysis/analyzers/analyzers_test.go, galley/pkg/config/analysis/analyzers/gateway/certificate.go, galley/pkg/config/analysis/analyzers/testdata/gateway-duplicate-certificate.yaml, galley/pkg/config/analysis/msg/messages.gen.go, galley/pkg/config/analysis/msg/messages.yaml
Issue: all common problem should have analyzer
https://github.com/istio/istio/issues/21158
common problem: https://istio.io/docs/ops/common-problems/network-issues/#404-errors-occur-when-multiple-gateways-configured-with-same-tls-certificate
limitation:
- only working with `PILOT_SCOPE_GATEWAY_TO_NAMESPACE` false value. I cannot get this value from anywhere. So cannot decide the logic. since the default value is `false`.
- The current logic is comparing the name since I cannot get the raw certificate and somehow comparing the certificate directly with OpenSSL. So we cannot validate the same certificate that configures in a different mode (example: gateway X via `ServerTLSSettings.credentialName` and gateway Y via `ServerTLSSettings.serverCertificate` and `ServerTLSSettings.privateKey`). …
=> Analyzer: duplicate certificate in Gateway

pkg/test/echo/server/endpoint/http.go
port may be nil
[ ] Docs
[ ] Networking
[ ] Security
=> Fix crash when using UDS

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go, releasenotes/notes/18-17-sidecar-ingress.yaml
Fixes https://github.com/istio/istio/issues/30437
Put a hold for @Stono to verify
Note: This went directly to the 1.8 branch, as we do not want it on master or 1.9. Please review it as an original PR, not a cherrypick
=> Fix 1.8 Istiod with 1.7 proxy with Sidecar.Ingress

pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
=> [1.8] Fix envoyfilter matching virtual inbound passthrough

istioctl/cmd/dashboard.go, istioctl/cmd/dashboard_test.go, releasenotes/notes/30208.yaml
Manual cherry-pick of https://github.com/istio/istio/pull/30467
Will close https://github.com/istio/istio/issues/30480
=> [release-1.8] Fix dashboard controlz could not port forward to istiod pod (#30467)

tools/istio-iptables/pkg/cmd/run.go, tools/istio-iptables/pkg/config/config.go
=> add dns capture variable to ip table logs

Makefile.core.mk
fixed https://github.com/istio/istio/issues/30489
=> support add debug info into build

manifests/charts/istio-control/istio-discovery/templates/configmap.yaml, manifests/charts/istiod-remote/templates/configmap.yaml, pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/components/istio/config.go, pkg/test/framework/components/istio/flags.go, pkg/test/framework/components/istio/operator.go, tests/integration/iop-integration-test-defaults.yaml, tests/integration/iop-istiodless-remote-integration-test-defaults.yaml, tests/integration/security/ecc_signature_algorithm/main_test.go
=> [release-1.9] fix discoveryAddress in configmap template

releasenotes/notes/28346.yaml, releasenotes/notes/cluster-labels-prometheus.yaml, releasenotes/notes/default-access-log.yaml, releasenotes/notes/default-container.yaml, releasenotes/notes/injector-selectors.yaml, releasenotes/notes/kiali-update-v1.29.yaml, releasenotes/notes/mcp-removal.yaml, releasenotes/notes/pod-ip-listener.yaml, releasenotes/notes/redirect-dns-iptables.yaml, releasenotes/notes/tracing-canonical-service.yaml
Part of https://github.com/istio/istio.io/pull/8884
=> Add missing issue number for 1.9 release notes

pkg/url/url.go
Fix https://github.com/istio/istio/issues/30515
=> Fix istioctl analyze docs url version error

pilot/pkg/bootstrap/configcontroller.go, pilot/pkg/config/kube/ingress/conversion.go, pilot/pkg/config/kube/ingress/conversion_test.go, pilot/pkg/config/kube/ingress/status.go, pilot/pkg/config/kube/ingress/status_test.go, releasenotes/notes/ingress-status-fixes.yaml, tests/integration/pilot/ingress_test.go
Includes:
* [https://github.com/istio/istio/pull/28263/commits](https://github.com/istio/istio/pull/28263/commits
)
* [https://github.com/istio/istio/pull/28771/commits](https://github.com/istio/istio/pull/28771/commits) (excluding the "Activate metallb in prow" commit)
* [https://github.com/istio/istio/pull/28225/commits](https://github.com/istio/istio/pull/28225/commits)
* [https://github.com/istio/istio/pull/28254/commits](https://github.com/istio/istio/pull/28254/commits)
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does …
=> [release-1.8] [cherry-pick] ingress status fixes

pilot/pkg/controller/workloadentry/workloadentry_controller.go
Fixes https://github.com/istio/istio/issues/30487
[ ] Docs
[ ] Security
=> add metrics for auto registrations

galley/pkg/config/analysis/diag/message.go, galley/pkg/config/analysis/diag/message_test.go, galley/pkg/config/analysis/diag/messages_test.go, istioctl/pkg/util/formatting/formatter_test.go
=> documentation_url -> documentationUrl everywhere

istioctl/cmd/tag.go, pkg/test/framework/features/features.yaml, tests/integration/pilot/istioctl_test.go, tests/integration/pilot/revisions/revision_tag_test.go
Adds an integration test to make sure that adding revision tags leads to injection
[ ] Docs
[ ] Networking
[ ] Security
=> Revision tag integration test

pkg/test/framework/components/cluster/cluster.go, tests/integration/pilot/multi_version_revision_test.go
Fixes #30572, conditional skip got flipped
[ ] Docs
[ ] Networking
[ ] Security
=> Fix condition to make revision test skip on k8s <1.16

tests/integration/telemetry/stats/prometheus/customizemetrics/testdata/attributegen_envoy_filter.yaml
[ ] Docs
[ ] Networking
[ ] Security
=> Add initial fetch timeout to metric customization remote fetch test.

pilot/pkg/networking/core/v1alpha3/cluster.go, releasenotes/notes/30181.yaml, tests/integration/pilot/locality_test.go
Fix: #30181
[ ] Docs
[X] Networking
[ ] Security
=> set MaxEjectionTime to BaseEjectionTime if it is greater than 300s

pkg/test/framework/components/istio/operator.go
Getting ingress for a non-kube cluster could result in a future k8s call to find the ingress external IP, which will fail since the external cluster doesn't have a kube client. 
An alternative solution is making ExtendedClient calls to non-kube clusters always go through to their connected kube cluster, but hiding this detail may lead to test writers making multiple kube calls to the same cluster with different input.
=> make ingress work with staticvm

manifests/charts/istio-operator/files/gen-operator.yaml, manifests/charts/istio-operator/templates/clusterrole.yaml
cherrypick istio-operator permission of https://github.com/istio/istio/pull/29752 to release-1.8
resolve: https://github.com/istio/istio/issues/30106
[ ] Docs
[ ] Networking
[ ] Security
=> cherrypick 29752 for the istio operator permissions.

Makefile.core.mk
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.8] Update base image to 1.8-dev.7

pilot/pkg/config/monitor/monitor.go, releasenotes/notes/30683.yaml
Fixes https://github.com/istio/istio/issues/30683.
[ ] Docs
[ ] Networking
[ ] Security
=> Fix unnecessary full push in serviceentry store.

Makefile.core.mk, go.mod, go.sum, prow/release-commit.sh
run UPDATE_BRANCH=release-1.9 ./bin/update_deps.sh; make gen
Update base image
[ ] Docs
[ ] Networking
[ ] Security
=> run UPDATE_BRANCH=release-1.9 ./bin/update_deps.sh; make gen

pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/listener_test.go
Fixes https://github.com/istio/istio/issues/28861
=> Fix concurrent sort of SNI hosts and CIDR

pilot/pkg/dns/dns.go, releasenotes/notes/dns-localhost-loop.yaml, tests/integration/pilot/common/routing.go, tools/istio-iptables/pkg/cmd/root.go, tools/istio-iptables/pkg/cmd/run.go, tools/istio-iptables/pkg/cmd/run_test.go, tools/istio-iptables/pkg/config/config.go
Cherry-pick of https://github.com/istio/istio/pull/30647 sha 267d46fd3efa944a8834786eb729da3f8c252fb9
Fixes https://github.com/istio/istio/issues/30699
=> [release-1.9] Fix DNS loop when there is a local DNS proxy (#30647)

galley/pkg/config/analysis/analyzers/analyzers_bench_test.go, galley/pkg/config/analysis/analyzers/schema/validation_test.go, galley/pkg/config/analysis/diag/helper.go, galley/pkg/config/analysis/diag/messages.go, galley/pkg/config/processing/snapshotter/analyzingdistributor_test.go, galley/pkg/config/source/kube/rt/origin.go, galley/pkg/config/source/mcp/origin.go, pkg/config/resource/origin.go
=> reduce cost of sorting k8s analysis messages

istioctl/cmd/dashboard.go, istioctl/cmd/dashboard_test.go
To fix https://github.com/istio/istio/issues/30691
=> Fix envoy dashboard with custom namespace

pkg/test/framework/components/cluster/clusterboot/factory.go, pkg/test/framework/components/cluster/config.go
Currently, this is randomly sorted. So we pick a random one, causing a
lot of test flakes
Hopefully:
fixes https://github.com/istio/istio/issues/30621
fixes https://github.com/istio/istio/issues/30595
fixes https://github.com/istio/istio/issues/30600
(cherry picked from commit c11dc3dabc1a686a3bf7cd8b6c031c5170e90bbc)
[ ] Docs
[ ] Networking
[ ] Security
=> Fix ctx.Clusters().Default()

pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/gateway_test.go, pilot/pkg/networking/plugin/authn/authentication.go, pilot/pkg/security/authn/policy_applier.go, pilot/pkg/security/authn/utils/utils.go, pilot/pkg/security/authn/utils/utils_test.go, pilot/pkg/security/authn/v1beta1/policy_applier.go, pilot/pkg/security/authn/v1beta1/policy_applier_test.go, pilot/pkg/security/model/authentication.go, pilot/pkg/security/model/authentication_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Remove sdsUdsPath

security/pkg/nodeagent/cache/secretcache.go
This got missed in some refactoring - So fixing it
[ ] Docs
[ ] Networking
[X ] Security
=> fix missing stat secret failures stat increment

istioctl/cmd/workload.go
Fixes #30703 
[ ] Docs
[ ] Networking
[ ] Security
=> [istioctl] handle default revision in workload command

pilot/pkg/networking/util/util.go
[X] Docs
[ ] Networking
[ ] Security
=> fix LocalityToString comment

pilot/cmd/pilot-agent/main.go, pkg/envoy/proxy.go
* Pass JSON log encoding to envoy logs
Fixes https://github.com/istio/istio/issues/28066
* fix lint
(cherry picked from commit 6f492bad78d875bcf24bd26767669b39552a4191)
[ ] Docs
[ ] Networking
[ ] Security
=> [1.8] Pass JSON log encoding to envoy logs (#29159)

tools/go-stress-test
Had a random echo in there, also used the wrong variable
[ ] Docs
[ ] Networking
[ ] Security
=> Fix bugs in go-stress-test

tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go, tests/integration/telemetry/stackdriver/stackdriver_filter_test.go, tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go, tests/integration/telemetry/stats/prometheus/stats.go
=> telemetry tests: fix more loop vars in goroutines

tests/integration/telemetry/stats/prometheus/wasm/bad_wasm_filter_test.go
fixes #30593
[ ] Docs
[ ] Networking
[ ] Security
=> Fix bad wasm remote load test flaky.

pkg/test/echo/cmd/server/main.go, pkg/test/echo/common/model.go, pkg/test/echo/server/instance.go, pkg/test/framework/components/echo/echo.go, pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/components/echo/kube/instance.go, tests/integration/pilot/common/apps.go, tests/integration/pilot/common/routing.go
Increasing testing before we change this logic a bit in
https://docs.google.com/document/d/1j-5_XpeMTnT9mV_8dbSOeU7rfH-5YNtN_JJFZ2mmQ_w/edit#
[ ] Docs
[ ] Networking
[ ] Security
=> Expand testing of application bind and sidecar

istioctl/cmd/wait.go
Help debug failures like https://github.com/istio/istio/issues/29315
[ ] Docs
[ ] Networking
[ ] Security
=> Dump entire wait respones from pilot when verbose is set

tools/bug-report/pkg/archive/archive.go, tools/bug-report/pkg/bugreport/bugreport.go
To fix https://github.com/istio/istio/issues/30836
=> istioctl bug-report: use .tar.gz

istioctl/cmd/dashboard.go, istioctl/cmd/dashboard_test.go, istioctl/pkg/util/handlers/handlers.go, pkg/kube/client.go, pkg/test/kube/mock_client.go, releasenotes/notes/30208.yaml
Manual cherry-pick of https://github.com/istio/istio/pull/30467
Will close https://github.com/istio/istio/issues/30479
=> [release-1.7] Fix dashboard controlz could not port forward to istiod pod (#30467)

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go, releasenotes/notes/30387.yaml
fix #30429 
cherry-pick #30423
=> [release-1.7] Fix namespace isn't resolved correctly in VirtualService delegation

pkg/kube/inject/webhook.go
Fixes https://github.com/istio/istio/issues/30814
This was a regression during changes in 1.9
=> Fix HoldApplicationUntilProxyStarts

pilot/pkg/networking/core/v1alpha3/accesslog.go
No behavior change here expected aside from Istiod logging
[ ] Docs
[ ] Networking
[ ] Security
=> Avoid spurious error log on unset JSON access log format

pkg/config/constants/constants.go, pkg/test/framework/components/echo/kube/builder.go, pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/components/echo/kube/deployment_test.go, pkg/test/framework/components/echo/kube/instance.go, pkg/test/framework/components/echo/kube/pod_controller.go, pkg/test/framework/components/echo/kube/util.go, pkg/test/framework/components/echo/kube/workload.go, pkg/test/framework/components/echo/kube/workload_manager.go
This will help test more scenarios where pods are being restarted or upgraded.
[ ] Docs
[ ] Networking
[ ] Security
=> [Test Framework] Support dynamic echo workloads

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
Fixes https://github.com/istio/istio/issues/30823
We may set refreshIndexes true while already processing a
maybeRefreshIndexes, say to add config X. At the end of maybeRefreshIndexes, we set
refreshIndexes to false. At this point, config X was not processed, but
refreshIndexes==false, so we skip an update
=> Fix races in ServiceEntry refreshIndexes

pkg/config/validation/validation.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fix typo in validation message

pilot/pkg/model/gateway.go, pilot/pkg/model/gateway_test.go, pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/gateway_test.go
Attempt to fix https://github.com/istio/istio/issues/24118
Fixes https://github.com/istio/istio/issues/24118
[ ] Docs
[ ] Security
=> refactor MergeGateway to cleanup Servers field

istioctl/cmd/revision.go
[ ] Docs
[ ] Networking
[ ] Security
=> [istioctl/cmd]: trim trailing whitespace

pkg/kube/inject/webhook.go
(cherry picked from commit f1c0ce6c495e1dcc36947f74c714a07d6e990a72)
Fixes https://github.com/istio/istio/issues/30867
=> Fix HoldApplicationUntilProxyStarts (#30846)

security/pkg/nodeagent/cache/secretcache.go
[ ] Docs
[ ] Networking
[ X] Security
=> add debounce for secret watcher

tools/bug-report/pkg/bugreport/bugreport.go, tools/bug-report/pkg/content/content.go
To fix https://github.com/istio/istio/issues/30835
=> istioctl bug-report: collect node info

pilot/pkg/networking/core/v1alpha3/listener.go
[ ] Docs
[ ] Networking
[ ] Security
=> Clean up default for bind

security/pkg/nodeagent/cache/secretcache.go
Change debug ->info as it will be useful
[ ] Docs
[ X] Security
=> change log line to info in secret watcher

Makefile.core.mk
For https://github.com/istio/istio/issues/29596
Next step is include it in the release
Manually built at
http://storage.googleapis.com/howardjohn/tmp/istioctl-osx-arm64. Please
test it, I don't have a mac.
=> Add support for apple silicon

pilot/pkg/serviceregistry/aggregate/controller.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fix store lock for GetRegistryIndex

pilot/pkg/networking/core/v1alpha3/accesslog.go, releasenotes/notes/access-log-service-crash.yaml
fixes https://github.com/istio/istio/issues/30939
=> Add transport version to access log service.

pkg/test/framework/components/cluster/cluster.go, pkg/test/framework/components/cluster/clusterboot/factory_test.go, pkg/test/framework/components/cluster/topology.go, tests/integration/multicluster/cluster_local.go, tests/integration/multicluster/helper.go, tests/integration/multicluster/loadbalancing.go, tests/integration/multicluster/telemetry.go, tests/integration/pilot/common/routing.go, tests/integration/pilot/mirror_test.go, tests/integration/security/authorization_test.go, tests/integration/security/ca_custom_root/secure_naming_test.go, tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go, tests/integration/security/jwt_test.go, tests/integration/security/pass_through_filter_chain_test.go, tests/integration/security/util/reachability/context.go, tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go, tests/integration/telemetry/tracing/opencensusagent/tracing_test.go, tests/integration/telemetry/tracing/zipkin/clienttracing/client_tracing_test.go, tests/integration/telemetry/tracing/zipkin/servertracing/tracing_test.go
cherry-pick 6d5406628e
Fixes #30706
=> use a deterministic cluster name for subtests

bin/update_deps.sh, docker/Dockerfile.distroless, pilot/docker/Dockerfile.proxyv2, prow/release-commit.sh
cherry-pick 2342789b76
Fixes #30796
=> Add updating of distroless image to update_deps.sh

istioctl/cmd/workload.go
Avoid nil map assignment
[ ] Docs
[ ] Networking
[ ] Security
=> Support meshConfig without proxyMetadata set

pkg/security/security.go, security/pkg/credentialfetcher/fetcher_test.go, security/pkg/credentialfetcher/plugin/gce.go, security/pkg/credentialfetcher/plugin/gce_test.go, security/pkg/credentialfetcher/plugin/mock.go, security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go, security/pkg/util/jwtutil.go, security/pkg/util/jwtutil_test.go
[ ] Docs
[ ] Networking
[ ] Security
Fix #30961
=> cherry pick 30908

releasenotes/notes/duplicate-http-header-probe-fix.yaml
Adds release note for http probe rewrite fix backported earlier (#30955) 
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.8] Add release note for duplicated probe rewrite headers

pkg/test/framework/components/echo/util/traffic/generator.go, tests/integration/pilot/revisioned_upgrade_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> [Test Framework] Cleanup traffic generator interface

releasenotes/notes/wasm-plugin-config-update.yaml
fixes https://github.com/istio/istio/issues/29843
=> [release-1.9] Add a release notes for Wasm filter config update fix.

pilot/pkg/xds/ads_test.go
Just adds a test for https://github.com/istio/istio/pull/30875
[ ] Docs
[ ] Networking
[ ] Security
=> Add regression test for bad connection ID

pilot/pkg/xds/ads.go
For more context, refer to https://github.com/istio/istio/pull/30875#issuecomment-781777526
[ ] Docs
[X] Networking
[ ] Security
=> Prevent push to invalid connection

pkg/test/echo/docker/Dockerfile.app_sidecar_base_centos
Needed for master-2021-02-22T14-24-32
[ ] Docs
[ ] Networking
[ ] Security
=> Add additional ignoring for latest hadolint version

pkg/test/echo/docker/Dockerfile.app_sidecar_base_centos
[ ] Docs
[ ] Networking
[ ] Security
=> Fix dockerfile yum clean all

pilot/pkg/xds/ads.go
Reverts istio/istio#30984
```
panic: close of closed channel
goroutine 6378 [running]:
istio.io/istio/pilot/pkg/xds.(*Connection).Stop(...)
istio.io/istio/pilot/pkg/xds/ads.go:999
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).receive.func1(0xc004d25020, 0xc004fe2fc0)
istio.io/istio/pilot/pkg/xds/ads.go:148 +0x45
istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).receive(0xc000740780, 0xc004fe2fc0, 0xc004d25020, 0xc004619d20)
istio.io/istio/pilot/pkg/xds/ads.go:157 +0x75a
created by istio.io/istio/pilot/pkg/xds.(*DiscoveryServer).Stream
istio.io/istio/pilot/pkg/xds/ads.go:297 +0x5bc
```
Lots of  TestVMRegistrationLifecycle started failing with this.
=> Revert "Prevent push to invalid connection"

istioctl/cmd/add-to-mesh.go, istioctl/cmd/kubeinject.go, istioctl/cmd/proxyconfig.go, releasenotes/notes/30991.yaml
Fixes #30991
[ ] Docs
[ ] Networking
[ ] Security
=> Fix kube-inject for revisions

bin/diff_yaml.py
This commit changes to use common sequence repetition operation to
repeat asterisk character
[ ] Docs
[ ] Networking
[ ] Security
=> diff_yaml.py: to repeat a string use an operator

pilot/pkg/bootstrap/server.go
Avoid errors about http server closing on shutdown
=> Make logs more graceful on Istiod shutdown

bin/init.sh, releasenotes/notes/bad-envoy-build.yaml
Fixes https://github.com/istio/istio/issues/31038
=> Fix issues causing us to use envoy-centos binaries

Makefile.core.mk
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.7] Update the 1.7 base image version

bin/update_deps.sh, go.mod, go.sum
Add client-go to update_deps.sh as it is an istio.io dependency
[ ] Docs
[ ] Networking
[ ] Security
=> Add client go update

pkg/bootstrap/testdata/all_golden.json, tools/packaging/common/envoy_bootstrap.json
[ ] Docs
[ x ] Installation
[ ] Networking
[ x ] Policies and Telemetry
[ ] Security
=> change metrics svc to V3

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
Fixes https://github.com/istio/istio/issues/31029
[ ] Docs
[ ] Security
=> fix service discovery test flake

security/pkg/nodeagent/cache/secretcache.go
Fixes https://github.com/istio/istio/issues/31030
[ ] Docs
[ ] Networking
[ X] Security
=> fix file secret test flake

common/scripts/kind_provisioner.sh, pkg/test/framework/components/echo/annotations.go, pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/components/echo/kube/testdata/basic.yaml, pkg/test/framework/components/echo/kube/testdata/healthcheck-rewrite.yaml, pkg/test/framework/components/echo/kube/testdata/multiversion.yaml, pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml, pkg/test/kube/dump.go
Fixes https://github.com/istio/istio/issues
=> Dump core dumps when proxy crashes

pilot/pkg/networking/core/v1alpha3/serviceentry_simulation_test.go
related to https://github.com/istio/istio/issues/29197
=> negative test for overlapping ServiceEntry address

galley/pkg/config/analysis/analyzers/deployment/services.go, galley/pkg/config/source/kube/apiserver/status/util.go, istioctl/pkg/install/pre-check.go, pilot/pkg/security/authz/matcher/metadata.go, pkg/config/validation/validation.go
It is a very tiny performance improvement & refactor by pre-specifying slice size (if already obvious).
[ ] Docs
[ ] Networking
[ ] Security
=> add len while creating slices where it is obvious instead of dynamic sizin

pilot/pkg/features/pilot.go, pilot/pkg/model/xds_cache.go, pilot/pkg/xds/xds_cache_test.go
We have been using the LRU without issues for many releases, clean this
up to simplify things
[ ] Docs
[ ] Networking
[ ] Security
=> Remove unbounded XDS cache

pilot/pkg/dns/dns.go, pilot/pkg/dns/dns_test.go, pilot/pkg/networking/core/v1alpha3/name_table.go, releasenotes/notes/dns-round-robin.yaml
Fixes https://github.com/istio/istio/issues/31064
Code is borrowed from coredns
=> Load balance statefulset DNS response

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go, pilot/pkg/model/sidecar_test.go, pilot/pkg/networking/core/v1alpha3/name_table.go, pilot/pkg/networking/core/v1alpha3/name_table_test.go
Addresses some review comments
[ ] Docs
[ ] Security
=> address review comments for dns

pilot/pkg/model/push_context.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/eds.go, pilot/pkg/xds/gen.go
=> merge pushtype to trigger reason

pilot/pkg/xds/ads.go
To give better visibility into type of errors
=> use gRPC errors codes in Istiod

pilot/pkg/serviceregistry/aggregate/controller.go, pilot/pkg/serviceregistry/kube/controller/multicluster_test.go
Detected by https://github.com/istio/istio/pull/31094
=> Fix race in aggregate controller readiness

pilot/pkg/model/service.go, pilot/pkg/networking/core/v1alpha3/name_table.go, pilot/pkg/networking/core/v1alpha3/name_table_test.go, pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go
fixes: https://github.com/istio/istio/issues/31104
=> Support pod dns resolve

pilot/pkg/networking/core/v1alpha3/cluster.go, tests/integration/pilot/locality_test.go
Fixes https://github.com/istio/istio/issues/30649
[ ] Docs
[ ] Security
=> revert base ejection time fix

pilot/pkg/status/state.go
Detected in https://github.com/istio/istio/pull/31094
=> Fix data race in analysis status update

pilot/pkg/networking/core/v1alpha3/name_table.go
=> fix dns name table comments

.gitignore
[ ] Docs
[ ] Networking
[ ] Security
=> Remove dup line in .gitignore

pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/gateway_test.go
Fix the comments from previous pr.
=> Donot set StripPortMode if not enabled

bin/diff_yaml.py
According to PEP-8 recommended style is snake_case. Hence, update the
name of byResourceName function to also use the same style
[ ] Docs
[ ] Networking
[ ] Security
[ X] Developer Infrastructure
=> diff_yaml.py: unify function name style

Makefile.core.mk
Non-existent prerequisites are format.gofmt format.goimports
[ ] Docs
[ ] Networking
[ ] Security
=> Remove .PHONY target non-existent prerequisites

pilot/pkg/model/service.go, pilot/pkg/serviceregistry/aggregate/controller.go, pilot/pkg/serviceregistry/aggregate/controller_test.go, pilot/pkg/serviceregistry/kube/controller/controller_test.go, pilot/pkg/serviceregistry/kube/conversion.go, pilot/pkg/serviceregistry/mock/discovery.go, pilot/pkg/serviceregistry/mock/discovery_mock.go
=> optimize cluster vip mutex in service

tools/build-base-images.sh
[ ] Docs
[ ] Networking
[ ] Security
=> Support comma seperated list of HUBS for build-base-images.sh

bin/init.sh
Fixes #31218  `make clean istioctl` on a Mac
=> Fix build failure on Macs

pkg/bootstrap/platform/azure.go, pkg/bootstrap/platform/azure_test.go, releasenotes/notes/azureTags.yaml
=> [release-1.8] fix(azure bootstrap): handle tags with semicolons or without values

pkg/bootstrap/platform/azure.go, pkg/bootstrap/platform/azure_test.go, releasenotes/notes/azureTags.yaml
=> [release-1.9] fix(azure bootstrap): handle tags with semicolons or without values

pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go, releasenotes/notes/31168.yaml
Signed-off-by: zhongfox <foxzhong@tencent.com>
fix https://github.com/istio/istio/issues/31166
support filter chain name match
=> Add filter chain name match support to envoyfilter

pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/util/util.go, pilot/pkg/networking/util/util_test.go, pilot/pkg/xds/endpoint_builder.go, pilot/pkg/xds/ep_filters.go, releasenotes/notes/destination-cluster-stats-label.yaml
fixes https://github.com/istio/istio/issues/29373
=> Add cluster into endpoint workload metadata.

pilot/pkg/serviceregistry/serviceentry/conversion.go
[ ] Docs
[X] Networking
[ ] Security
=> minor refactor in service entry conversion

tests/integration/pilot/ingress_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fix custom gateway test when using revision tag

pilot/pkg/model/service.go, pilot/pkg/serviceregistry/aggregate/controller.go, pilot/pkg/serviceregistry/kube/controller/controller_test.go, pilot/pkg/serviceregistry/kube/conversion.go
=> fix race cluster vip mutex in service (#31204)"

istioctl/pkg/multicluster/remote_secret.go
As suggested in https://github.com/istio/istio/issues/31271. This should help KinD users. Also https://github.com/istio/istio/issues/31081
=> warn when using localhost in remote secret command

pilot/pkg/xds/ads.go
[ ] Docs
[ ] Networking
[ ] Security
=> Use gRPC error for unauthenticated

pkg/envoy/proxy.go
Fixes https://github.com/istio/istio/issues/31137
Depends on https://github.com/envoyproxy/envoy/pull/15226 - we can
backport IFF we backport that
[ ] Docs
[ ] Networking
[ ] Security
=> Fix invalid JSON log format

Makefile.core.mk
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.8] Bump 1.8 base image

tools/build-base-images.sh
[ ] Docs
[ ] Networking
[ ] Security
=> Update build-base-images.sh to verify if images may already exist

tests/integration/pilot/istioctl_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Avoid putting temporary file in source tree

releasenotes/notes/vm-cleanup-iptables.yaml, tools/packaging/common/istio-start.sh, tools/packaging/common/istio.service
fixes https://github.com/istio/istio/issues/29556
[ ] Docs
[ ] Networking
[ ] Security
=> Cleanup iptables when systemd service stops

pilot/pkg/model/xds_cache.go, pilot/pkg/xds/xds_cache_test.go
Fixes https://github.com/istio/istio/issues/31332
[ ] Docs
[X] Networking
[ ] Security
=> fix xds cache race

.gitignore
This is used by intellij/goland to store run configuration
[ ] Docs
[ ] Networking
[ ] Security
=> Add .run/ to gitignore

pilot/pkg/model/jwks_resolver_test.go
Fixes #31287
Fixes flaky jwks resolver tests.
[ ] Docs
[ ] Networking
[x] Security
=> fix flaky jwks resolver tests

security/pkg/nodeagent/sds/sdsservice.go, security/pkg/testing/sdsc/sdsclient.go
[ ] Docs
[ ] Networking
[ X] Security
=> use v3 secret type

tests/integration/security/sds_tls_origination/egress_gateway_origination_test.go, tests/integration/security/sds_tls_origination/main_test.go, tests/integration/security/sds_tls_origination/util/util.go
[ ] Docs
[ ] Networking
[x] Security
=> Test sds tls origination with default cluster

pkg/config/constants/constants.go, pkg/kube/util.go, pkg/test/framework/components/echo/common/call.go, pkg/test/framework/components/echo/kube/builder.go, pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/components/echo/kube/deployment_test.go, pkg/test/framework/components/echo/kube/instance.go, pkg/test/framework/components/echo/kube/pod_controller.go, pkg/test/framework/components/echo/kube/util.go, pkg/test/framework/components/echo/kube/workload.go, pkg/test/framework/components/echo/kube/workload_manager.go, pkg/test/framework/components/echo/staticvm/instance.go, pkg/test/framework/components/namespace/kube.go, pkg/test/kube/util.go, tests/integration/pilot/revisioned_upgrade_test.go
Cherry-picks: [https://github.com/istio/istio/pull/30675](https://github.com/istio/istio/pull/30675)
Reverts: [https://github.com/istio/istio/pull/31243](https://github.com/istio/istio/pull/31243)
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.9] Support dynamic echo backport

pilot/pkg/bootstrap/sidecarinjector.go, pkg/kube/inject/monitoring.go, pkg/kube/inject/webhook.go, pkg/kube/inject/webhook_test.go
This param is not used in any way.
=> Clean up sidecar injector monitoring port

pilot/pkg/bootstrap/server.go, pilot/pkg/model/cluster_local.go, pilot/pkg/model/cluster_local_test.go, pilot/pkg/model/context.go, pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go, pilot/pkg/networking/core/v1alpha3/fake.go, pilot/pkg/networking/core/v1alpha3/httproute_test.go, pilot/pkg/networking/core/v1alpha3/listener_builder_test.go, pilot/pkg/networking/core/v1alpha3/listener_test.go, pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go, pilot/pkg/networking/core/v1alpha3/networkfilter_test.go, pilot/pkg/networking/grpcgen/grpcgen_test.go, pilot/pkg/xds/ep_filters_test.go, pilot/pkg/xds/simple.go
This is in support of #31401
[ ] Docs
[x] Networking
[ ] Security
=> Refactor cluster local logic

pilot/pkg/bootstrap/sidecarinjector.go, pkg/kube/inject/webhook.go, pkg/kube/inject/webhook_test.go
=> Clean up health check file param from injector.

pilot/pkg/config/kube/ingress/controller.go, pkg/kube/client.go
I thought we used this in more places, so this doesn't make a huge
difference... but I am planning to add at least one more so this will
cut API server calls a bit.
[ ] Docs
[ ] Networking
[ ] Security
=> Cache Kubernetes version

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, releasenotes/notes/auto-mtls-passthrough.yaml, tests/integration/security/reachability_test.go, tests/integration/security/testdata/automtls-passthrough.yaml
Fixes https://github.com/istio/istio/issues/23494
Note: this is stacked on https://github.com/istio/istio/pull/31285. I will rebase it once that merges
=> Fix auto mtls for PASSTHROUGH load balancer mode

tests/integration/pilot/revisioncmd/revision_view_test.go, tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fixups for updating golang-ci

tests/integration/telemetry/stackdriver/stackdriver_filter_test.go, tests/integration/telemetry/stackdriver/vm/vm_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Add more log to sd integration test.

tests/integration/pilot/ingress_test.go
Seeing some test flakes. The problem is we just apply the deployment and
immediately send traffic and fail after 20s if we get 503. instead we
should wait for it to be ready
[ ] Docs
[ ] Networking
[ ] Security
=> Add wait for custom gateway

security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
[ ] Docs
[ ] Networking
[x] Security
=> Add more info to STS error log

pkg/bootstrap/config.go, releasenotes/notes/duplicated-extra-stats-tag.yaml
=> Handle duplicated extra stats tags gracefully.

pkg/test/framework/components/echo/config.go, pkg/test/framework/components/echo/echotest/echotest.go, pkg/test/framework/components/echo/echotest/fake.go, pkg/test/framework/components/echo/echotest/filters.go, pkg/test/framework/components/echo/echotest/filters_test.go, pkg/test/framework/components/echo/echotest/run.go, pkg/test/framework/components/echo/echotest/setup.go, pkg/test/framework/components/echo/echotest/utils.go, pkg/test/framework/components/echo/instances.go, pkg/test/framework/testcontext.go, tests/integration/pilot/common/routing.go, tests/integration/pilot/common/traffic.go
=> test framework: *echotest.T for enumerating subtests

pilot/pkg/config/kube/ingress/status.go, pilot/pkg/config/kube/ingress/status_test.go, releasenotes/notes/31336.yaml
Fixes #31527
[ ] Docs
[x] Networking
[ ] Security
=> [release-1.8] Fix runaway ingress status logs

pilot/tools/debug/pilot_cli.go
[ ] Docs
[ ] Networking
[ ] Security
=> fix command

pilot/pkg/config/kube/ingress/status.go, pilot/pkg/config/kube/ingress/status_test.go, releasenotes/notes/31336.yaml
Fixes #31528
[ ] Docs
[x] Networking
[ ] Security
=> [release-1.9] Fix runaway ingress status logs

pilot/pkg/xds/ads.go
[ ] Docs
[ ] Networking
[ ] Security
=> Cherrypick better ADS errors to release-1.9

pilot/pkg/bootstrap/server.go, pilot/pkg/trustbundle/trustbundle.go, security/pkg/nodeagent/cache/secretcache.go, security/pkg/pki/ca/ca.go, security/pkg/pki/ca/ca_test.go, security/pkg/pki/ca/selfsignedcarootcertrotator.go, security/pkg/pki/ca/selfsignedcarootcertrotator_test.go
Trustbundle: Make changes to monitor Istio CA root-cert directly
Related to https://github.com/istio/istio/issues/31111
[ ] Docs
[ ] Networking
[ ] Security
=> Trustbundle: Make changes to monitor Istio CA root-cert directly

go.mod, go.sum, prow/release-commit.sh
run UPDATE_BRANCH=release-1.9 ./bin/update_deps.sh; make gen
=> [release-1.9] Update dependencies

tools/build-base-images.sh
[ ] Docs
[ ] Networking
[ ] Security
=> Add buildx-create before building new base images

pkg/test/echo/cmd/client/main.go
fixes https://github.com/istio/istio/issues/31614
=> Fix echo client cert file variable.

pkg/config/mesh/watcher.go, pkg/test/framework/features/features.yaml, pkg/test/framework/test.go, tests/integration/pilot/multicluster_test.go
Another attempt of moving things out of the multicluster/ package.
=> cluster local test in pilot suite

tests/integration/telemetry/policy/envoy_ratelimit_test.go, tests/integration/telemetry/policy/testdata/enable_envoy_local_ratelimit_sa.yaml
[ ] Docs
[ ] Networking
[ ] Security
=> rate limit: test inbound service account local rate limit

pilot/pkg/xds/delta.go
[ ] Docs
[ ] Networking
[ ] Security
=> Stop logging ADS at debug level

tests/integration/security/authorization_test.go
[ ] Docs
[ ] Networking
[x] Security
=> Unskip authz tests for multi-cluster

pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/controller_test.go, pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go, pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go, pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go, pilot/pkg/serviceregistry/kube/controller/endpoints.go, pilot/pkg/serviceregistry/kube/controller/endpointslice.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go, pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go, pilot/pkg/serviceregistry/kube/controller/network.go, pilot/pkg/serviceregistry/kube/controller/serviceexportcontroller.go, pilot/pkg/serviceregistry/kube/controller/util.go
[ ] Docs
[ ] Networking
[ ] Security
=> Add "kube" scope for service registry logs

pilot/pkg/xds/gen.go
Fix for https://github.com/istio/istio/issues/30661
This is the functional part.  The test will be added in a follow-up.
=> Send control plane version with XDS response

tests/integration/security/authorization_test.go
This is a manual cherry-pick PR that fixes https://github.com/istio/istio/issues/31657
* unskip authz tests for multi-cluster
* skip deny test
[ ] Docs
[ ] Networking
[ ] Security
=> Unskip authz tests for multi-cluster (#31620)

istioctl/pkg/multixds/gather.go, istioctl/pkg/xds/client.go, tests/integration/pilot/istioctl_test.go
Resolves https://github.com/istio/istio/issues/31647
cc @irisdingbj
=> Use default serviceAccount when getting token credentials

istioctl/cmd/workload.go
To make cases https://github.com/istio/istio/issues/31624 like clearer
=> istioctl x workload: warn if gateway ip can't be detected

pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go, releasenotes/notes/31573.yaml
HTTP_FILTER don't support INSERT_FIRST due to implement bug
[ ] Docs
[x] Networking
[ ] Security
[] Test and Release
=> Fix INSERT_FIRST bug for http filter

releasenotes/notes/28996.yaml
Release note for issue #28996, solved by PR #29216
[X] Docs
[ ] Networking
[ ] Security
=> Release note for issue 28996, solved by PR29216

tests/integration/telemetry/policy/envoy_ratelimit_test.go, tests/integration/telemetry/policy/testdata/enable_envoy_local_ratelimit_sa.yaml
[ ] Docs
[ ] Networking
[ ] Security
=> test: a flake fix

pilot/cmd/pilot-agent/main.go, pilot/pkg/model/context.go, pkg/bootstrap/config.go, pkg/bootstrap/config_test.go, pkg/bootstrap/instance_test.go, pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json, pkg/envoy/proxy.go, pkg/envoy/proxy_test.go
Follow up to #31664. Ensure that node metadata has all options needed to construct the bootstrap.
=> envoy: place all options into node metadata

istioctl/cmd/add-to-mesh.go, istioctl/cmd/authz.go, istioctl/cmd/debug.go, istioctl/cmd/metrics.go, istioctl/cmd/tag.go
[ ] Docs
[ ] Networking
[ ] Security
=> [istioctl]: cleanup help doc trailing whitespace

pilot/pkg/model/envoyfilter.go
[ ] Docs
[ ] Networking
[ ] Security
=> Extend envoyfilter optimization

releasenotes/notes/configmap-mount.yaml
[ ] Docs
[ ] Networking
[ ] Security
=> Add missing release note

prow/integ-suite-kind.sh
[ ] Docs
[ ] Networking
[ ] Security
=> Update kind image to 1.20.5

pilot/pkg/serviceregistry/aggregate/controller.go
[ ] Docs
[X] Networking
[ ] Security
=> add clusterid to logs

cni/README.md
Remove installation related content since they are available at Istio.io, and clean up some content based on old istio/cni repo. Also did some minor editings to the left content.
=> Clean up Istio CNI readme

samples/ratelimit/rate-limit-service.yaml
[x] Docs
[ ] Networking
[ ] Security
should add configmap to this file, otherwise, the pod cannot run well.
=> add ratelimit configmap

tests/integration/security/pass_through_filter_chain_test.go, tests/integration/security/util/framework.go
Manually cherry-pick https://github.com/istio/istio/pull/31663
[ ] Docs
[ ] Networking
[ ] Security
Fixes #31733 
=> cherry-pick #31663

pkg/istio-agent/xds_proxy.go
[ ] Docs
[X] Networking
[ ] Security
=> xds proxy: return err for upstream error also

tests/integration/pilot/common/apps.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fix "HTTPS" port that wasn't actually using TLS

pilot/pkg/bootstrap/mesh.go, pilot/pkg/features/pilot.go, pkg/config/mesh/kubemesh/watcher.go, pkg/config/mesh/kubemesh/watcher_test.go, pkg/config/mesh/watcher.go
1. Handle case where we read user configmap first
2. Fix potentional startup race condition
3. Add a few more docs
4. Add tests
5. Fix data race
=> Bug fixes and tests for mesh config merging

pilot/pkg/model/push_context.go, pilot/pkg/model/sidecar.go, pilot/pkg/model/sidecar_test.go
=> SidecarScope convert only takes service that is visible to the sidecar

pilot/pkg/networking/core/v1alpha3/name_table.go, pilot/pkg/networking/core/v1alpha3/name_table_test.go
Reverts istio/istio#31783
I don't how this passed tests in presubmit but it's raining all the postsubmit tests.. needs some investigation
=> Revert "dns: consider network local endpoints for stateful sets"

tests/integration/pilot/common/apps.go
Fixes https://github.com/istio/istio/issues/31794
=> [1.8] Fix "HTTPS" port that wasn't actually using TLS (#31792)

pkg/test/framework/components/istio/ingress.go, pkg/test/framework/components/istio/ingress/interface.go, pkg/test/framework/components/istio/util.go
* make it easier to use custom ports
* improve logging
=> Improve Ingress support in test framework

pilot/pkg/features/pilot.go, pilot/pkg/model/xds_cache.go, pilot/pkg/xds/eds.go, pilot/pkg/xds/endpoint_builder.go, pilot/pkg/xds/sds.go, pilot/pkg/xds/xds_cache_test.go, pkg/test/kube/dump.go, pkg/test/util/retry/retry.go, tests/integration/pilot/ingress_test.go
* 040ef05 - fix xds cache race (#31339) (3 weeks ago)
* 9366430 - Add runtime assertions to istiod (#31045) (4 weeks ago)
* fed241b - Remove unbounded XDS cache (#31078) (5 weeks ago)
helps with a future cherry pick of #30705
=> backport xds cache changes

istioctl/cmd/add-to-mesh.go, istioctl/cmd/kubeinject.go, pkg/kube/inject/inject.go, pkg/kube/inject/inject_test.go
https://github.com/istio/istio/issues/29270
=> support xds address for kube-inject

istioctl/cmd/internal-debug.go
=> Remove unreachable code in internal-debug

istioctl/cmd/workload.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fix bad formatting in log

tools/bug-report/pkg/bugreport/bugreport.go, tools/bug-report/pkg/content/content.go
For https://github.com/istio/istio/issues/31834
=> Fix bug-report target cluster context error

pkg/test/framework/features/features.yaml, releasenotes/notes/29270.yaml, tests/integration/pilot/istioctl_test.go, tests/integration/pilot/testdata/hello.yaml
add one integration test and  release notes for kube-inject
=> add one integration test and  release notes for kube-inject

samples/bookinfo/platform/kube/bookinfo-db.yaml, samples/bookinfo/src/ratings/ratings.js, samples/ratelimit/rate-limit-service.yaml
This reverts commit 8f1518137d981aa54acfa268be8c5fbfdc60ebd5.
[x] Docs
[ ] Networking
[ ] Security
Should not push to release branch. Fisrtly should push to master, then cherry-pick to release.
=> Revert "add ratelimit configmap (#31734)"

pilot/pkg/xds/monitoring.go, pilot/pkg/xds/sds.go, releasenotes/notes/31779.yaml
For https://github.com/istio/istio/issues/31779
=> Add pilot_sds_certificate_errors_total metric for sds

tests/integration/pilot/istioctl_test.go
Resolves https://github.com/istio/istio/issues/30661 by adding the integration test I promised.
=> Integration test for 'istioctl experimental version'

pkg/config/model.go
Not significant but minor opti
[ ] Docs
[X] Networking
[ ] Security
=> minor optimization in model

pkg/bootstrap/config.go, pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json
[ ] Docs
[ ] Networking
[ ] Security
=> Clean up two unused stats tag from default bootstrap tag list.

pkg/bootstrap/instance_test.go, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, tools/packaging/common/envoy_bootstrap.json, tools/packaging/common/gcp_envoy_bootstrap.json
[ ] Docs
[ ] Networking
[ ] Security
=> Remove unnecessary root cert config from Stackdriver tracer config.

pilot/cmd/pilot-agent/status/ready/probe_test.go, pilot/cmd/pilot-agent/status/server_test.go, pilot/cmd/pilot-agent/status/testserver/server.go
[ ] Docs
[X] Networking
[ ] Security
=> refactor test server in to common code for agent

pilot/pkg/networking/core/v1alpha3/cluster_builder.go
=> change passthrough clusters to use new protocol options

security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fix sts token exchange request retry logic.

pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go
[ ] Docs
[X] Networking
[ ] Security
=> remove downstream protocol usages

pilot/cmd/pilot-agent/status/ready/probe_test.go, pilot/cmd/pilot-agent/status/server_test.go, pilot/cmd/pilot-agent/status/testserver/server.go
[ ] Docs
[X] Networking
[ ] Security
=> change test server to use dynamic port

tools/bug-report/pkg/config/config.go
=> Fix err always nil (unreachable code)

istioctl/cmd/revision.go, istioctl/cmd/root.go, istioctl/cmd/tag.go, releasenotes/notes/revision-tag-command.yaml, tests/integration/pilot/revisions/revision_tag_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Move `istioctl tag` command group to `istioctl revision tag` subcommand

pkg/kube/apimirror/probe.go
https://github.com/istio/istio/blob/8b14ab5fc044727ea2bae271599328479aa9ec3a/pkg/kube/apimirror/probe.go#L40-L42
[ ] Docs
[ ] Networking
[ ] Security
=> Fix allows repeated headers

pilot/pkg/model/jwks_resolver.go
Signed-off-by: Shiming Zhang <wzshiming@foxmail.com>
[ ] Docs
[ ] Networking
[x] Security
=> Fix backoff max limit

pilot/pkg/xds/endpoint_builder.go, pilot/pkg/xds/ep_filters_test.go
=> mtls checker handles dr explicitly setting ISTIO_MUTUAL

pkg/test/kube/dump.go
=> Include EDS in configdump

pilot/pkg/security/authz/builder/builder_test.go, pilot/pkg/security/authz/builder/extauthz.go, pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-no-namespace-out1.yaml, pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-no-namespace-out2.yaml, pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-out2.yaml, pilot/pkg/security/authz/builder/testdata/http/custom-http-provider-out2.yaml
This PR implements some new API changes for more flexibility, note the feature will still be in experimental for 1.10.
[ ] Docs
[ ] Networking
[x] Security
=> Update ext-authz extension provider with more flexibility

pilot/pkg/model/authentication.go, pilot/pkg/model/xds_cache.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, pilot/pkg/networking/util/util.go, pilot/pkg/networking/util/util_test.go, pilot/pkg/security/authn/policy_applier.go, pilot/pkg/security/authn/v1beta1/policy_applier.go, pilot/pkg/xds/eds_sh_test.go, pilot/pkg/xds/endpoint_builder.go, pilot/pkg/xds/ep_filters.go, pilot/pkg/xds/ep_filters_test.go, pilot/pkg/xds/mesh_network_test.go, pilot/pkg/xds/sds.go, pilot/pkg/xds/xds_cache_test.go, pkg/test/framework/config.go, releasenotes/notes/30705.yaml, tests/integration/security/mtls_first_party_jwt/strict_test.go, tests/integration/security/mtlsk8sca/strict_test.go, tests/integration/security/reachability_test.go, tests/integration/security/util/framework.go, tests/integration/security/util/reachability/context.go
=> filter out non mTLS cross network endpoints  (#30705)

pkg/test/framework/components/istio/ingress.go, pkg/test/framework/components/istio/ingress/interface.go, pkg/test/framework/components/istio/util.go
* make it easier to use custom ports
* improve logging
Fixes https://github.com/istio/istio/issues/31826
(cherry picked from commit 76a6110364b4fef9030c33c3465876e99c6a4c0c)
=> [1.8] Improve Ingress support in test framework (#31798)

releasenotes/notes/31338.yaml
add release notes for istioctl x internal-debug
=> add release notes for  `istioctl x internal-debug`

cni/pkg/repair/monitoring.go, cni/pkg/repair/repair.go, cni/pkg/repair/repair_test.go
Also simplify the code by avoiding holding a pointer to the metric object in the reconciler, and combine the metric test into the existing test.
=> [CNI] Add repair type label to repaired pod stats.

tests/integration/security/authorization_test.go, tests/integration/security/testdata/authz/v1beta1-deny.yaml.tmpl, tests/integration/security/testdata/authz/v1beta1-negative-match.yaml.tmpl, tests/integration/security/testdata/authz/v1beta1-workload-ns-root.yaml.tmpl, tests/integration/security/testdata/authz/v1beta1-workload-ns1.yaml.tmpl, tests/integration/security/testdata/authz/v1beta1-workload-ns2.yaml.tmpl
Use the same variable name to make it easier to connect the relationship between test code and policy template.
[ ] Docs
[ ] Networking
[x] Security
=> refactor authorization e2e test for better readability

pilot/pkg/model/authentication.go, pilot/pkg/model/xds_cache.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, pilot/pkg/networking/util/util.go, pilot/pkg/networking/util/util_test.go, pilot/pkg/security/authn/policy_applier.go, pilot/pkg/security/authn/v1beta1/policy_applier.go, pilot/pkg/xds/eds_sh_test.go, pilot/pkg/xds/endpoint_builder.go, pilot/pkg/xds/ep_filters.go, pilot/pkg/xds/ep_filters_test.go, pilot/pkg/xds/mesh_network_test.go, pilot/pkg/xds/sds.go, pilot/pkg/xds/xds_cache_test.go, pkg/test/framework/config.go, pkg/test/framework/resource/cluster.go, releasenotes/notes/30705.yaml, tests/integration/security/authorization_test.go, tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go, tests/integration/security/mtls_first_party_jwt/strict_test.go, tests/integration/security/mtlsk8sca/strict_test.go, tests/integration/security/reachability_test.go, tests/integration/security/util/framework.go, tests/integration/security/util/reachability/context.go
=> [release-1.8] filter out non mTLS cross network endpoints  (#30705) 

pilot/pkg/xds/delta.go
[ ] Docs
[X] Networking
[ ] Security
=> match delta with ads

galley/pkg/config/analysis/msg/messages.gen.go, galley/pkg/config/analysis/msg/messages.yaml
The old one was confusing and not grammatically correct
=> Improve analyzer msg

pilot/pkg/bootstrap/server_test.go
=> Pick a free unbinded port

pilot/cmd/pilot-agent/options/agent.go, pilot/cmd/pilot-agent/status/server.go, pkg/istio-agent/agent.go, pkg/istio-agent/health/health_check.go, pkg/istio-agent/health/health_check_test.go, pkg/istio-agent/health/health_probers.go, pkg/istio-agent/health/health_probers_test.go, pkg/istio-agent/xds_proxy.go
=> vm prober send probe to right ip

pkg/kube/mock_client.go, pkg/kube/version.go, pkg/kube/version_test.go, pkg/test/framework/analyzer.go, pkg/test/framework/components/cluster/cluster.go, pkg/test/framework/components/cluster/topology.go, pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/suite.go, tests/integration/helm/install_test.go, tests/integration/pilot/endpointslice/endpointslice_test.go, tests/integration/pilot/ingress_test.go, tests/integration/pilot/main_test.go, tests/integration/pilot/mcs/serviceexport_test.go, tests/integration/pilot/multi_version_revision_test.go, tests/integration/pilot/revisioncmd/revision_view_test.go, tests/integration/security/external_ca/main_test.go, tests/integration/security/file_mounted_certs/main_test.go, tests/integration/security/filebased_tls_origination/main_test.go, tests/integration/security/mtls_first_party_jwt/main_test.go, tests/integration/security/sds_egress/main_test.go, tests/integration/security/sds_tls_origination/main_test.go
For https://github.com/istio/istio/issues/31964
=> Skip first party jwt on k8s 1.21+

Makefile.core.mk
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.10] Update to new base image

pkg/test/framework/components/cluster/staticvm/staticvm.go, pkg/test/framework/components/cluster/staticvm/staticvm_test.go, pkg/test/framework/components/echo/staticvm/workload.go
to allow tests like TestPassthroughFilterChain to use this
=> staticvm: allow specifying instance ip

galley/pkg/config/analysis/msg/messages.gen.go, galley/pkg/config/analysis/msg/messages.yaml
[ ] Docs
[ ] Networking
[ ] Security
=> Switch warning to error per TOC feedback

pkg/kube/client.go, pkg/kube/rpc_creds.go, pkg/kube/rpc_creds_test.go
Signed-off-by: Shiming Zhang <wzshiming@foxmail.com>
Fix read and write confilicts
[ ] Docs
[ ] Networking
[ ] Security
=> Fix read and write confilicts

samples/httpbin/sample-client/fortio-deploy.yaml
[ ] Docs
[ ] Networking
[ ] Security
=> Remove unused stats

pilot/cmd/pilot-agent/status/server.go
This is an cherry-pick of #31981
Fixes #32106
=> [release-1.8] Fix probe header

pilot/cmd/pilot-agent/config/config.go, pilot/cmd/pilot-agent/config/config_test.go
Alternative to https://github.com/istio/istio/pull/30694
=> Allow setting concurrency in ProxyConfig for gateway

prow/integ-suite-kind.sh
[ ] Docs
[ ] Networking
[ ] Security
=> Update kind image

pilot/pkg/xds/ads.go, pilot/pkg/xds/eds.go, pilot/pkg/xds/gen.go, pilot/pkg/xds/sds.go, pkg/istio-agent/xds_proxy.go
To help debug abnormal phenomena found in #31943 that EDS comes before CDS
=> Print connection ID

pkg/test/echo/server/endpoint/http.go, pkg/test/echo/server/forwarder/http.go
Avoid golang processing the URL which limits our ability to tests
non-standard clients.
[ ] Docs
[ ] Networking
[ ] Security
=> Send a print out original path of request

pilot/pkg/model/service.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/delta.go
Do not recompute sidecar and merge gateways if they have not changed while pushing to proxy
[ ] Docs
[ ] Security
=> do not recompute sidecar and gateway if not changed

pilot/cmd/pilot-agent/status/server.go, pilot/cmd/pilot-agent/status/server_test.go
This is an cherry-pick of #31981
Fixes #32105
=> [release-1.9] Fix probe header

pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go, releasenotes/notes/28996.yaml
Cherry pick from release-1.9 commit 5643e303879cbdf3dbc28b693724d303aad0ddc5
* Fix to enable choice of TLS parameters within Envoy Filters (Cherry pick of PR #29216)
* Add release note for PR #29216
[ ] Docs
[X] Networking
[ ] Security
=> Cherry pick release 1.8 fix envoyfilter (#31358)

pkg/test/framework/components/echo/config.go, pkg/test/framework/components/echo/echotest/filters.go, pkg/test/framework/components/echo/instances.go, tests/integration/pilot/common/routing.go, tests/integration/pilot/common/traffic.go
Using echotest to gain coverage for any added workload type
=> convert selfcall cases to use echotest

pkg/test/framework/components/istio/ingress.go, pkg/test/framework/components/istio/ingress/interface.go, pkg/test/util/yml/apply.go, tests/integration/pilot/common/routing.go, tests/integration/security/sds_ingress/util/util.go
Fixes https://github.com/istio/istio/issues/26630
This is a fairly large change since we didn't have any HTTPS tests
already, so it required a few extra changes
[ ] Docs
[ ] Networking
[ ] Security
=> Add test for :scheme match in VS

pkg/test/framework/components/echo/common/config.go, pkg/test/framework/components/echo/config.go, pkg/test/framework/components/echo/kube/deployment.go, tests/integration/pilot/vm_test.go
fixes https://github.com/istio/istio/issues/31427
=> echo: abstract VMIMage to VMDistro

pilot/pkg/xds/eds.go, pilot/pkg/xds/sds.go
Partial revert of
https://github.com/istio/istio/commit/02f27d47630c1b56e802b7d12ef6f4e3b96d4c0e
Without this, EDS log is different from other logs which seems off
[ ] Docs
[ ] Networking
[ ] Security
=> make EDS log consistent with other ADS types

pilot/pkg/grpc/grpc.go, pilot/pkg/grpc/grpc_test.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/delta.go, pkg/istio-agent/xds_proxy.go, pkg/istio-agent/xds_proxy_delta.go, pkg/istio-agent/xds_proxy_test.go
[ ] Docs
[X] Networking
[ ] Security
=> move isexpectedgrpcerror to grpc package

pkg/test/helm/helm.go, security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go, security/pkg/util/jwtutil.go, tests/integration/helm/install_test.go, tests/integration/helm/main_test.go, tests/integration/helm/upgrade/helm_upgrade_test.go, tests/integration/helm/util.go
Manual cherry-pick of https://github.com/istio/istio/pull/32159 and https://github.com/istio/istio/pull/32012
Fixes https://github.com/istio/istio/issues/32168 and https://github.com/istio/istio/issues/32162
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.9] Allow, with warning, users using first-party-jwt with Kubernetes 1.21+ and helm integration test fix for 1st party JWT

pkg/wasm/httpfetcher.go
Signed-off-by: Shiming Zhang <wzshiming@foxmail.com>
[ ] Docs
[x] Networking
[ ] Security
=> Fix the response body is not closed  in 4xx when istio-agent fetch wasm

pkg/wasm/httpfetcher.go
[ ] Docs
[x] Networking
[ ] Security
=> Support exponential backoff for istio-agent fetch wasm

pkg/test/echo/common/model.go, pkg/test/framework/components/echo/annotations.go, pkg/test/framework/components/echo/kube/deployment.go, releasenotes/notes/prom-cert-permission.yaml, security/pkg/nodeagent/util/util.go, tests/integration/telemetry/stats/prometheus/stats.go
Fix https://github.com/istio/istio/issues/31743
=> [release-1.9] Make output cert readable to other containers running on kube. (#31531)

tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go, tests/integration/telemetry/stats/prometheus/customizemetrics/testdata/attributegen_envoy_filter.yaml
Fixes https://github.com/istio/istio/issues/32050
=> Fallback metric customization test to nullvm if remote URL is not accesible

pilot/pkg/serviceregistry/kube/controller/multicluster.go
[ ] Docs
[X] Networking
[ ] Security
=> simplify multi cluster delete

operator/pkg/helmreconciler/reconciler.go
This is an manually cherry-pick of https://github.com/istio/istio/pull/32252
=> [release-1.9] Manually cherrypick Add SSA detecting method

pilot/pkg/model/sidecar.go, pilot/pkg/model/sidecar_test.go
remove `listenerHosts` to reduce memory cost
=> Optimize IstioEgressListenerWrapper memory cost

pilot/pkg/networking/core/v1alpha3/route/route.go
[ ] Docs
[X] Networking
[ ] Security
=> minor route optimizations

cni/README.md
To fix https://github.com/istio/istio/issues/32262
=> Don't use preliminary link for CNI docs

pilot/pkg/features/pilot.go, pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/listener_test.go, pilot/pkg/networking/core/v1alpha3/tracing.go
Clean up unused metric and evaluate trace sampling in features
[ ] Docs
[ ] Security
=> remove unused metric

tests/integration/security/ca_custom_root/multi_root_test.go, tests/integration/security/ca_custom_root/secure_naming_test.go, tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go, tests/integration/security/ca_custom_root/trust_domain_validation_test.go
=> unskip multi-root test in multi-cluster

pilot/pkg/security/authz/builder/builder_test.go, pilot/pkg/security/authz/builder/extauthz.go, pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-no-namespace-out1.yaml, pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-no-namespace-out2.yaml, pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-out2.yaml, pilot/pkg/security/authz/builder/testdata/http/custom-http-provider-out2.yaml
cherrypick https://github.com/istio/istio/pull/31882 and https://github.com/istio/istio/pull/31968
The API is already in 1.10 and code change is in master (forgot to add the cherry-pick label before), will include release note in a follow-up, this PR just cherry-picks the exact changes in master.
[ ] Docs
[ ] Networking
[x] Security
=> Cherry pick ext-authz changes for 1.10

pilot/pkg/model/sidecar.go, pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/plugin/authn/authentication.go
[ ] Docs
[ ] Networking
[ ] Security
=> remove SidecarScope.HasCustomIngressListeners

istioctl/cmd/internal-debug.go
This PR is for [issue#31703](https://github.com/istio/istio/issues/31703), and handle for multiple istiods debug information
[ ] Docs
[ ] Networking
[ ] Security
=> Aggregate the output for the command from multiple istiod

pilot/pkg/model/sidecar.go
To optimize memory allocation for sidecarScope construction, we found this during load test.
=> Pre allocate capacity for sidecarScope construction

pilot/pkg/bootstrap/certcontroller.go, pilot/pkg/bootstrap/istio_ca.go, pilot/pkg/bootstrap/server.go, pilot/pkg/bootstrap/server_test.go, pilot/pkg/bootstrap/servicecontroller.go, pilot/pkg/bootstrap/sidecarinjector.go, pilot/pkg/bootstrap/validation.go, pilot/pkg/keycertbundle/watcher.go, pilot/pkg/keycertbundle/watcher_test.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go, pilot/pkg/serviceregistry/kube/controller/multicluster_test.go, pkg/webhooks/validation/controller/controller.go, pkg/webhooks/validation/controller/controller_test.go, pkg/webhooks/webhookpatch.go
manually cherry-pick #31737 and #32302
fix: #32301
=> [release-1.10] Added keyCertBundle watcher instead of outputing to files

galley/pkg/config/analysis/analyzers/all.go, galley/pkg/config/analysis/analyzers/analyzers_test.go, galley/pkg/config/analysis/analyzers/deployment/pod.go, galley/pkg/config/analysis/analyzers/testdata/deployment-con-sec-uid.yaml, galley/pkg/config/analysis/analyzers/testdata/deployment-pod-sec-uid.yaml, galley/pkg/config/analysis/analyzers/testdata/pod-con-sec-uid.yaml, galley/pkg/config/analysis/analyzers/testdata/pod-sec-uid.yaml, galley/pkg/config/analysis/analyzers/util/constants.go, galley/pkg/config/analysis/msg/messages.gen.go, galley/pkg/config/analysis/msg/messages.yaml
To fix https://github.com/istio/istio/issues/31991
Related:
https://github.com/istio/istio/pull/31900
https://github.com/istio/istio.io/pull/9462
=> Add analyzer for detecting UID 1337 for app pod

tests/integration/pilot/common/routing.go
Otherwise we get repeated names and then we lose state
[ ] Docs
[ ] Networking
[ ] Security
=> Show cluster name in test

security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go, security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient_test.go, security/pkg/stsservice/test/setup.go, security/pkg/stsservice/tokenmanager/google/mock/mockserver.go, security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin.go, security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin_test.go, security/pkg/stsservice/tokenmanager/sts_test.go
Update Google STS endpoint.
https://cloud.google.com/iam/docs/reference/sts/rest
[ ] Docs
[ ] Networking
[x] Security
=> Change STS endpoint

tests/integration/security/authorization_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Use stable cluster name in subtest

pilot/pkg/networking/plugin/authn/util.go, pilot/pkg/networking/plugin/authn/util_test.go
Fixes https://github.com/istio/istio/issues/32245
[ ] Docs
[x] Networking
[x] Security
=> Dedup trust domain aliases for TLS validation context

tests/integration/pilot/istioctl_test.go
https://storage.googleapis.com/istio-prow/logs/integ-k8s-118_istio_postsubmit/1384370290624040960/build-log.txt
5s is too small
[ ] Docs
[ ] Networking
[ ] Security
=> Deflake TestDescribe

tools/bug-report/pkg/bugreport/bugreport.go, tools/bug-report/pkg/common/common.go, tools/bug-report/pkg/content/content.go
This PR was submitted for issue: [issue#31918](https://github.com/istio/istio/issues/31918)
[ ] Docs
[ ] Networking
[ ] Securitygit commit -m "this submit is for issue#31918"
=> analyzer should run with -A for bug-report based on issue#31918

release/downloadIstioCandidate.sh, release/downloadIstioCtl.sh
To fix https://github.com/istio/istio/issues/32230
=> DownloadIstio script: add exit status code

istioctl/cmd/internal-debug.go
handle the conflict of internal-debug.go for PR 32312 based on release-1.10 
[ ] Docs
[ ] Networking
[ ] Security
=> handle the conflict of internal-debug.go for PR 32312 based on release-1.10 

istioctl/cmd/internal-debug.go, pilot/pkg/grpc/grpc.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/delta.go, pilot/pkg/xds/v3/model.go
Minor ads improvements , refactoring and some unnecessary lock removals (lock only when needed)
[ ] Docs
[X] Networking
[ ] Security
=> minor ads improvements

pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json, tools/packaging/common/envoy_bootstrap.json
[ ] Docs
[X] Networking
[ ] Security
=> remove deprecated http2 protocol options in bootstrap clusters

samples/multicluster/README.md, samples/multicluster/expose-istiod-https.yaml, samples/multicluster/expose-istiod.yaml, samples/multicluster/expose-services.yaml
[ ] Docs
[ ] Networking
[ ] Security
=> Allow mc sample gws to be used with different system ns

security/pkg/pki/ca/ca_test.go, security/pkg/pki/util/generate_cert.go
This was reported by a real user.
Not sure if this is a good idea or not, wanted to open for feedback from experts like @myidpt @costinm
=> Handle clock skew in CA signing

manifests/charts/istio-cni/templates/daemonset.yaml
(cherry picked from commit 9ea961b2472c2cfb7f0431a21e5aaed08324a594)
[ ] Docs
[X] Networking
[ ] Security
=> [istio-cni] bump priority class to system-node-critical (#32341)

pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go, pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go, security/pkg/k8s/configutil.go, security/pkg/k8s/configutil_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.9]change kubeclient get call to lister call in namespace controller

pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go, pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go, security/pkg/k8s/configutil.go, security/pkg/k8s/configutil_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.10]change kubeclient get call to lister call in namespace controller

Makefile.core.mk
Update base image used for the same as 1.9.3
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.9] update base image

pkg/test/kube/dump.go
[ ] Docs
[ ] Networking
[ ] Security
Addresses #31477. Adds a check in pkg/test/kube/dump.go to see if the container has crashed by looking for a terminated state. Returns an error if the container has crashed.
```release-note
NONE
```
=> Check for container crashes in kube test package 

pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/controller_test.go, pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go, pilot/pkg/serviceregistry/kube/controller/network.go
[ ] Docs
[X] Networking
[ ] Security
=> minor fixes kube registry

pkg/config/validation/validation.go, pkg/config/validation/validation_test.go
[ ] Docs
[X] Networking
[ ] Security
=> add validations to workload entry

tests/integration/pilot/revisioncmd/revision_view_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Ignore CNI at revision command test.

pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
This condition is almost always triggered for new Services
=> Reduce log spam of kube controller

galley/pkg/config/analysis/analyzers/deployment/pod.go
To fix https://github.com/istio/istio/issues/32474 in https://github.com/istio/istio/pull/31993
=> Fix IST0144 regression

pilot/pkg/model/context.go
[ ] Docs
[ ] Networking
[ ] Security
=> injector: schematize app_containers and istio_proxy_sha

releasenotes/notes/authz-dry-run.yaml, releasenotes/notes/authz-ext-authz.yaml
Add release notes for new changes in 1.10.
[ ] Docs
[ ] Networking
[x] Security
=> add release notes for dry-run and ext-authz

pilot/pkg/networking/core/v1alpha3/name_table.go, pkg/test/framework/components/echo/common/config.go, pkg/test/framework/components/echo/config.go, pkg/test/framework/components/echo/echotest/filters.go, pkg/test/framework/components/echo/echotest/run.go, pkg/test/framework/components/echo/kube/deployment.go, tests/integration/pilot/common/apps.go, tests/integration/pilot/common/routing.go, tools/packaging/common/istio-start.sh
Fixes https://github.com/istio/istio/issues/31148
Fixes https://github.com/istio/istio/issues/32393
=> Add tests for statefulset to integration tests

pkg/test/framework/components/cluster/topology.go
[ ] Docs
[ ] Networking
[ ] Security
=> Allow Name==StableName when possible in test framework

tests/integration/security/authorization_test.go, tests/integration/security/util/framework.go
[ ] Docs
[ ] Networking
[ ] Security
=> Check workload availability before testing

tests/integration/pilot/common/routing.go
[ ] Docs
[ ] Networking
[ ] Security
=> Skip new test that fails in postsubmit

releasenotes/notes/inbound-passthrough.yaml
Fixes a spelling error in release notes yaml. 
=> Fix spelling error

istioctl/cmd/wait.go, istioctl/cmd/wait_test.go, pilot/pkg/model/config_test.go, pilot/pkg/status/ledger.go, pilot/pkg/status/report.go, pkg/config/model.go
[ ] Docs
[x] Networking
[ ] Security
=> Make the Key identifier of a Config object unique

istioctl/cmd/kubeinject.go
=> kube-inject: use Istio sidecar

security/pkg/pki/ca/ca_test.go
[ ] Docs
[ ] Networking
[x] Security
=> ca: merge tests for SignCSR

pkg/test/framework/components/namespace/kube.go, pkg/test/kube/dump.go
YAML should be more readable, deployments are useful when troubleshooting why no pods are ready
=> test framework: dump yaml and include deployment state

LICENSE
[ ] Docs
[ ] Networking
[ ] Security
=> Bump year in license.

security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
Please provide a description for what this PR is for:
When json.Marshal(values) returns an error, the json value returned to the caller will be invalid and cause a token request failure. This PR handles the error of marshaling a token request.
[ ] Docs
[ ] Networking
[X ] Security
[X ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> Handle the error of failing to marshal a token request

security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
Please provide a description for what this PR is for:
To facilitate the diagnosis of STS, change STS logging statements from Debugf to Errorf.
[ ] Docs
[ ] Networking
[ X] Security
[ X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> Change STS logging statements from Debugf to Errorf

operator/pkg/helmreconciler/reconciler.go
Fixes https://github.com/istio/istio/issues/32571
=> [1.9] Stop creating namespace when --dry-run is set

pilot/pkg/model/authentication.go, pilot/pkg/security/authn/v1beta1/policy_applier.go
[ ] Docs
[x] Networking
[x] Security
=> Consolidate peer authn and authn policy MTLS mode conversion func

istioctl/cmd/describe.go, pilot/pkg/model/listener.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch_test.go, pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/listener_builder.go, pilot/pkg/networking/core/v1alpha3/listener_builder_test.go, pilot/pkg/networking/core/v1alpha3/listener_test.go, pilot/pkg/simulation/traffic.go
No functional change
[ ] Docs
[X] Networking
[ ] Security
=> minor renaming and refactoring in envoy filters

pkg/test/kube/dump.go
[ ] Docs
[ ] Networking
[ ] Security
=> Skip test dump if no pods found.

tests/integration/helm/upgrade/helm_upgrade_test.go, tests/integration/helm/upgrade/util.go, tests/integration/helm/util.go, tests/util/sanitycheck/sanity_check.go
Add a test for helm-based revision installations.
[ ] Docs
[ ] Networking
[ ] Security
=> Add helm-based revision upgrade test

pkg/test/kube/dump.go
=> use k8s yaml library for ci dump

security/pkg/nodeagent/caclient/credentials.go, security/pkg/nodeagent/caclient/credentials_test.go
[ ] Docs
[ ] Networking
[x] Security
=> Use credential fetcher to fetch token for XDS

pilot/pkg/bootstrap/server.go, security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go, security/pkg/server/ca/authenticate/kubeauth/kube_jwt_test.go
Fixes https://github.com/istio/istio/issues/28756
[ ] Docs
[ ] Networking
[x] Security
=> kubejwt-authenticator: use dynamically updated trust domain

pkg/test/framework/components/echo/util/traffic/generator.go, pkg/test/framework/components/echo/util/traffic/result.go, tests/integration/pilot/revisioned_upgrade_test.go
A few refactorings for traffic generator to make its usage cleaner.
There is a lot of boilerplate when you have multiple generators.
=> tf: Improvements to traffic generator

pilot/pkg/networking/core/v1alpha3/cluster.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fix comments for inbound cluster building

pilot/pkg/xds/ads.go, pilot/pkg/xds/delta.go
Resolves https://github.com/istio/istio/issues/32547
I didn't test the delta variant of the code, but I brought it to equality with the non-debug variant.
=> Don't watch debug URLs

pkg/istio-agent/agent.go
[ ] Docs
[ ] Networking
[ ] Security
=> xds: abort bootstrap discovery on ctrl-c

manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml, manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml, manifests/charts/istiod-remote/files/gen-istiod-remote.yaml, manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
Cherrypick https://github.com/istio/istio/pull/32368
Sort of fixes https://github.com/istio/istio/issues/32761
Fixes https://github.com/istio/istio/issues/32765
=> Backport mutating webhook port in yaml

pilot/pkg/bootstrap/certcontroller.go, pilot/pkg/bootstrap/istio_ca.go, pilot/pkg/bootstrap/istio_ca_test.go, security/pkg/k8s/chiron/controller.go, security/pkg/k8s/chiron/controller_test.go, security/pkg/k8s/controller/casecret.go, security/pkg/k8s/secret/secret_util.go, security/pkg/k8s/secret/secret_util_test.go, security/pkg/pki/ca/ca.go, security/pkg/pki/ca/ca_test.go, security/pkg/pki/ca/selfsignedcarootcertrotator.go, security/pkg/pki/ca/selfsignedcarootcertrotator_test.go, security/tools/generate_cert/main.go, tests/integration/security/chiron/dns_cert_test.go, tests/integration/security/util/cert/cert.go, tests/integration/security/util/secret/secret.go
[ ] Docs
[ ] Networking
[x] Security
=> ca: reuse consts instead of hardcode where applicable

go.mod, go.sum
[ ] Docs
[ ] Networking
[ ] Security
=> Update go-control-plane go.mod replace

pilot/pkg/features/pilot.go
[ ] Docs
[x] Networking
[ ] Security
=> Cleanup stale env after removal of Gateway SDS from the agent

tests/integration/pilot/original_src_addr_test.go
Can't assume we have a single workload per echo instance when running under multiple revisions
[ ] Docs
[ ] Networking
[ ] Security
=> Fix pilot/TestTproxy for multiversion tests

Makefile.core.mk, go.mod, go.sum, pilot/pkg/features/pilot.go, pilot/pkg/model/service.go, pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/xds/eds.go, pilot/pkg/xds/endpoint_builder.go, pilot/pkg/xds/ep_filters.go, pkg/test/framework/components/echo/call.go, pkg/test/framework/components/echo/common/call.go, pkg/test/framework/components/istio/util.go, tests/integration/pilot/common/apps.go, tests/integration/pilot/common/routing.go, tests/integration/pilot/common/traffic.go, tests/integration/pilot/multicluster_test.go, tests/integration/security/normalization_test.go
1.10: https://github.com/istio/istio/pull/32839
=> Cherrypick 5/11 security fixes to master

pkg/istio-agent/agent.go, security/pkg/nodeagent/sds/sdsservice.go, security/pkg/nodeagent/sds/sdsservice_test.go, security/pkg/nodeagent/sds/server.go, security/pkg/nodeagent/test/setup.go
[ ] Docs
[x] Networking
[ ] Security
=> pilot-agent: remove unnecessary error and checks in SDS server

pilot/pkg/serviceregistry/aggregate/controller.go
[ ] Docs
[ ] Networking
[ ] Security
[] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> Get proxy workload label from specified cluster

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fix Comments

pilot/pkg/serviceregistry/kube/controller/multicluster.go
[ ] Docs
[ ] Networking
[ ] Security
=> remove redudant ResyncPeriod, actually not used

pkg/test/kube/dump.go
Helpful to know if it is proxy or app without digging through artifacts
=> Log which container crashed

tests/integration/security/pass_through_filter_chain_test.go
Fixes https://github.com/istio/istio/issues/32868
=> Fix name of TestPassThroughFilterChain

releasenotes/notes/27342.yaml, releasenotes/notes/31095.yaml, releasenotes/notes/31910.yaml, releasenotes/notes/32201.yaml, releasenotes/notes/agent-xds-piggyback.yaml, releasenotes/notes/cni-dns-capture.yaml, releasenotes/notes/inbound-passthrough.yaml, releasenotes/notes/istiod-config-size-bytes.yaml, releasenotes/notes/strict_1xx_204_fix.yaml, releasenotes/template.yaml
This fixes several release notes that don't match the schema.
=> Fix broken release notes

pilot/pkg/networking/core/v1alpha3/gateway.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fix log in pilot gateway

cni/pkg/install-cni/pkg/install/cniconfig.go
Fix https://github.com/istio/istio/issues/32768
=> Add log before busy waiting for CNI network config.

pilot/pkg/bootstrap/server.go
Please provide a description for what this PR is for: https://github.com/istio/istio/issues/32722
[ ] Docs
[ ] Networking
[ ] Security
[X ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> [Cherry-pick] Adjust the order of authenticators

security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin.go
This is printing the date its expired, not the TTL. Now its the
duration.
[ ] Docs
[ ] Networking
[ ] Security
=> Fix TTL log

pilot/pkg/config/kube/crdclient/client.go, pilot/pkg/config/kube/ingress/controller.go, pilot/pkg/config/kube/ingressv1/controller.go, pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go, pilot/pkg/serviceregistry/kube/controller/serviceexportcontroller.go, pkg/config/mesh/kubemesh/watcher.go, security/pkg/k8s/chiron/controller.go
[ ] Docs
[ ] Networking
[ ] Security
=> Check result of cache.WaitForCacheSync()

pkg/istio-agent/agent.go, pkg/istio-agent/agent_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> bootstrap: add discovery unit test

pkg/test/echo/server/endpoint/grpc.go, pkg/test/echo/server/endpoint/http.go, pkg/test/echo/server/endpoint/tcp.go
This improves some inconsitencies in echo logging to improve debugging.
Now all protocols log request and response, and an "id" is associated to
help join the two together.
[ ] Docs
[ ] Networking
[ ] Security
=> Consistency in echo logging

pilot/cmd/pilot-agent/options/options.go, pkg/istio-agent/README.md
[x] Docs
[x] Networking
[ ] Security
=> Update info of XDS proxy tap to port 15004

pilot/pkg/serviceregistry/kube/controller/controller.go
[ ] Docs
[ ] Networking
[ ] Security
=> use k8s topology label key

operator/cmd/mesh/install.go
[ ] Docs
[ ] Networking
[ ] Security
=> Add newline to upgrade survey notice

pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
Make use of shared namespace informer.
[ ] Docs
[X] Networking
[ ] Security
=> Share namespace informer

istio.deps
Fix PR https://github.com/istio/istio/pull/32896/files
=> [release-1.9] Update proxy sha 19

tests/integration/pilot/common/apps.go, tests/integration/pilot/common/routing.go
[ ] Docs
[ ] Networking
[ ] Security
=> Update Autopassthrough tests to use ingressgateway

pilot/pkg/xds/delta.go
[ ] Docs
[ ] Networking
[ ] Security
=> fix: fix log in delta

pilot/pkg/serviceregistry/kube/controller/multicluster.go, security/pkg/nodeagent/sds/server.go
=> Fix incorrectly attribute trigger reasons

prow/lib.sh
=> Bump buildx version

tests/integration/pilot/common/apps.go, tests/integration/pilot/common/routing.go
* Replace eastwest with ingress gateway
* Patch replace eastwest with ingress gateway
[ ] Docs
[ ] Networking
[ ] Security
[ x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> Cherry-pick pull/32970 to release-1.9

pkg/config/validation/validation.go, pkg/config/validation/validation_test.go
[ ] Docs
[X] Networking
[ ] Security
=> add validation for local origin errors

pilot/pkg/xds/eds.go, pilot/pkg/xds/eds_test.go
[ ] Docs
[X] Networking
[ ] Security
=> simplify update service accounts

pilot/pkg/bootstrap/mesh.go, pkg/config/mesh/kubemesh/watcher.go, pkg/config/mesh/networks_watcher.go, pkg/config/mesh/watcher.go
Fixes https://github.com/istio/istio/issues/32962
[ ] Docs
[ ] Networking
[ ] Security
=> Fix reading of mesh network from configmap

tests/integration/pilot/common/apps.go, tests/integration/pilot/common/routing.go
* Replace eastwest with ingress gateway
* Patch replace eastwest with ingress gateway
[ ] Docs
[ ] Networking
[ ] Security
[ x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> Cherry-pick pull/32970 to release-1.8 (#32970)

pilot/pkg/security/model/authentication.go, pilot/pkg/security/model/authentication_test.go
Not used by anything but a test of itself
=> Remove some deadcode in sds

tests/integration/tests.mk
=> Revert "Temporarily disable CI dumping"

tests/integration/pilot/common/apps.go, tests/integration/pilot/common/routing.go
* Replace eastwest with ingress gateway
* Patch replace eastwest with ingress gateway
[ ] Docs
[ ] Networking
[ ] Security
[ x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> Cherry-pick pull/32970 to release-1.10

pilot/pkg/networking/core/v1alpha3/listener_builder.go, pilot/pkg/networking/core/v1alpha3/peer_authentication_simulation_test.go
Fixes https://github.com/istio/istio/issues/28506
[ ] Docs
[x] Networking
[ ] Security
=> Remove unneeded match on Pod IP added by Sidecar.Ingress

security/pkg/stsservice/tokenmanager/tokenmanager.go
To help debug cases where the token manager fails
=> Add small logging improvement

Makefile.core.mk
[ ] Docs
[ ] Networking
[ ] Security
=> [1.9] Bump to 1.9-dev.9

pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/gateway_simulation_test.go, pilot/pkg/serviceregistry/serviceentry/conversion.go, pilot/pkg/serviceregistry/serviceentry/conversion_test.go
(cherry picked from commit 88ed872842b9705daab507658f454b4cd3831cb2)
Fixes https://github.com/istio/istio/issues/33033
=> [1.9] Workaround conflicting port mapping in Gateway (#33021)

istioctl/pkg/verifier/verifier.go
=> Fix empty response from verify-install

pilot/cmd/pilot-agent/main.go, pilot/cmd/pilot-agent/status/ready/probe.go, pilot/cmd/pilot-agent/status/ready/probe_test.go, pilot/cmd/pilot-agent/status/server.go
[ ] Docs
[X] Networking
[ ] Security
=> manual cherry pick of 32892

go.mod, go.sum, pilot/pkg/networking/grpcgen/grpcgen_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Bump grpc to 1.38

tests/integration/multicluster/centralremotekubeconfig/main_test.go
This has been timing out (but not t.Fail ing) for a long time, skip it
until its fixed so we don't waste 5min each time
[ ] Docs
[ ] Networking
[ ] Security
=> Skip broken test

pilot/pkg/bootstrap/configcontroller.go, pilot/pkg/config/kube/gateway/controller.go, pilot/pkg/config/kube/gateway/controller_test.go, pilot/pkg/config/kube/gateway/conversion.go, pilot/pkg/model/context.go, pilot/pkg/model/push_context.go
Design:  https://docs.google.com/document/d/1wgYnCnypxYMc_nGPZsLr7JIqTe727TwKiNopPkrJ2-k/
Split out commits:
* https://github.com/istio/istio/pull/32719
* https://github.com/istio/istio/pull/32806
=> Implement Gateway-API controller refactoring

prow/lib.sh
Experiment for https://github.com/istio/istio/issues/32985
=> test: experiment with not using buildx

prow/lib.sh
For https://github.com/istio/istio/issues/32985
=> Enable buildkit debug logs

pilot/pkg/serviceregistry/serviceentry/conversion.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
=> should be workload instance, not service instance

pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Fixes https://github.com/istio/istio/issues/33115
[ ] Docs
[X] Networking
[ ] Security
=> add explicit http protocol options when none is available

prow/lib.sh
Reverts istio/istio#33133
Things are still broken, they are just slow *and* broken now. Lets revert to make them fast at least
=> Revert "test: experiment with not using buildx"

pkg/test/framework/scope.go
Example failure https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-119_istio_postsubmit/1397944377011081216
=> Fix deadlock in SkipLock

tests/integration/pilot/common/routing.go, tests/integration/pilot/common/traffic.go
Adds some min version requirements to a few traffic test cases.
[ ] Docs
[ ] Networking
[ ] Security
=> Add min required version to traffic tests

pilot/pkg/dns/dns_test.go
[ ] Docs
[X] Networking
[ ] Security
=> minor dns test fix

pilot/pkg/model/jwks_resolver_test.go
This test is not stable - it relies on time.Sleep which is frowned upon.
Its extremely difficult to properly test this, as there are internal
variables we are introspecting, etc.
IMO the best action is to just remove the test. Its a bit overkill to
test that our backoff is exponential, and not worth flaky tests.
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, …
=> Remove flaky TestJwtRefreshIntervalExponentialBackoff

tests/integration/pilot/README.md
The vm file path in `tests/integration/pilot/README.md` is outdated. Update it to the correct one.
[x] Docs
[ ] Networking
[ ] Security
=> update doc file path

security/pkg/nodeagent/cache/secretcache.go
[ ] Docs
[ ] Networking
[X] Security
=> wait for some time to give chance to both key and cert are written

prow/integ-suite-kind.sh
Fixes some kubelet panic we have seen
=> Bump k8s test version to v1.21.1

pkg/test/framework/components/echo/cmd/echogen/echogen.go, pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/components/namespace/kube.go, pkg/test/framework/resource/flags.go, pkg/test/framework/resource/settings.go, pkg/test/framework/resource/version.go, pkg/test/framework/resource/version_test.go, pkg/test/framework/test.go
Manual cherry-pick of [https://github.com/istio/istio/pull/32518](https://github.com/istio/istio/pull/32518)
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.10] Move from IstioVersions to Revisions in test framework (#32518)

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, pilot/pkg/networking/core/v1alpha3/cluster_test.go, pilot/pkg/serviceregistry/serviceentry/conversion_test.go, releasenotes/notes/32539.yaml
Fixes https://github.com/istio/istio/issues/32539
[ ] Docs
[X] Networking
[ ] Security
[] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> honour subject alt names from service entry

tests/integration/pilot/istioctl_test.go, tests/integration/pilot/multi_version_revision_test.go, tests/integration/pilot/piggyback_test.go, tests/integration/pilot/revisioncmd/main_test.go, tests/integration/pilot/revisioned_upgrade_test.go, tests/integration/pilot/revisions/revisions_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Add label.CustomSetup and RequireIstioVersion to assorted pilot tests

pilot/pkg/networking/core/v1alpha3/route/route.go, pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json, pkg/config/validation/validation.go, releasenotes/notes/host-in-route-destination.yaml, tests/integration/pilot/common/routing.go, tools/packaging/common/envoy_bootstrap.json
Fixes #33226
Long term tracked in https://github.com/envoyproxy/envoy/issues/16775
A fair chunk of code duplication, but with the expectation that we just delete this in the near future so its clean to remove
=> Fix regression preventing Host header set in vs destination section

pilot/pkg/model/sidecar.go, pilot/pkg/model/sidecar_test.go
Reverts istio/istio#33113
@ramaraochavali said this caused a regression
=> Revert "check if virtual service destinations has matching ports"

pilot/pkg/model/sidecar.go, releasenotes/notes/service-ordering.yaml
Opening early to get feedback, probably need proper tests..
=> Fix overlapping service ordering

samples/bookinfo/README.md
[ √] Docs
[ ] Networking
[ ] Security
=> fix a misspelling bug in istio/samples/bookinfo #33277

istioctl/cmd/add-to-mesh.go, istioctl/cmd/admin.go, istioctl/cmd/dashboard.go, istioctl/cmd/describe.go, istioctl/cmd/injector-list.go, istioctl/cmd/remove-from-mesh.go
[ ] Docs
[ ] Networking
[ ] Security
We should check the `args` just like this:
https://github.com/istio/istio/blob/master/istioctl/cmd/tag.go#L101-L110
```go
Args: func(cmd *cobra.Command, args []string) error {
if len(args) != 0 {
return fmt.Errorf("unknown subcommand %q", args[0])
}
return nil
},
RunE: …
```
=> code cleanup: use cobra.Args to check command line arguments

pkg/test/echo/client/parsedresponse.go, pkg/test/framework/features/features.yaml, tests/integration/security/normalization_test.go
[ ] Docs
[ ] Networking
[x] Security
=> add more common patterns to path normalization test

istio.deps, pilot/pkg/bootstrap/server.go, pilot/pkg/config/kube/crdclient/client.go, pilot/pkg/config/kube/ingress/controller.go, pilot/pkg/config/kube/ingressv1/controller.go
Fix: #33218
[ ] Docs
[x] Networking
[ ] Security
=> Fix sync during bootstrap

tests/integration/pilot/webhook_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fix TestWebhook to work under non-default revisions

pilot/pkg/xds/pushqueue_test.go
Added test
[ ] Docs
[ ] Networking
[ ] Security
=> Added deterministic push order test per connection

istioctl/pkg/validate/validate.go
It looks like this file forgot to close
[ ] Docs
[ ] Networking
[ ] Security
=> Close the used file

pilot/pkg/model/virtualservice.go, pilot/pkg/model/virtualservice_test.go
Fix #33251
[ ] Docs
[X] Networking
[ ] Security
=> virtualservice set default delegate namespace to root's

pilot/cmd/pilot-agent/request.go, pkg/test/framework/components/echo/cmd/echogen/echogen.go, pkg/test/kube/dump.go, tests/integration/pilot/common/traffic.go
using https://github.com/istio/istio/pull/33234/files we can more reliably get ndsz at the agent's point of view rather than the control-plane's. Both may be valuable.
=> dump ndsz via agent

pilot/pkg/bootstrap/monitoring.go, releasenotes/notes/add-istiod-uptime-metric.yaml
Simple metric to monitor uptime of `istiod` instances.
=> add uptime metric for istiod server

pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/monitoring.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go
This name tag we pass is empty - so there is no value. I am removing it.
[ ] Docs
[X] Networking
[ ] Security
=> remove name tag from envoy filter error metrics

pilot/pkg/model/gateway.go
This ensures the annotation doesn't mess with the new gateway mode,
since it doesn't make sense there.
Fixes https://github.com/istio/istio/issues/33298#issuecomment-857465111
[ ] Docs
[ ] Networking
[ ] Security
=> Fix using new Gateway api with legacy gw annotation

pkg/test/framework/components/echo/echoboot/echoboot.go
[ ] Docs
[ ] Networking
[ ] Security
=> fix minor tf log

pkg/istio-agent/agent.go
Fixes https://github.com/istio/istio/issues/33349
=> agent: use non blocking select

pilot/pkg/networking/core/v1alpha3/accesslog.go, pilot/pkg/networking/core/v1alpha3/accesslog_test.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/listener_builder.go, pilot/pkg/networking/core/v1alpha3/listener_test.go, pilot/pkg/networking/core/v1alpha3/networkfilter.go, pilot/pkg/networking/core/v1alpha3/networkfilter_test.go, pilot/pkg/networking/util/util.go, pilot/pkg/security/model/authentication.go, pilot/pkg/security/model/authentication_test.go, pkg/bootstrap/option/convert.go
We do not support Istiod 1.11 and 1.9 proxy, so clean this up a bit
=> Drop support for 1.9 proxies

pilot/pkg/config/kube/crdclient/cache_handler.go, pilot/pkg/serviceregistry/kube/controller/controller.go
do some cleanup after fixing server ready status mark
[ ] Docs
[ ] Networking
[ ] Security
=> cleanups for k8s controller

pilot/pkg/model/xds_cache.go, pilot/pkg/xds/debug.go
=> Add debug endpoint to show size of XDS caches

go.mod, go.sum
Fix: #33314
[ ] Docs
[ ] Networking
[ ] Security
=> downgrade quic-go

pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, releasenotes/notes/ef-tls-regression.yaml
Fixes https://github.com/istio/istio/issues/33385
=> Fix regression when using custom transport_socket envoyfilter

releasenotes/notes/33293.yaml, security/pkg/nodeagent/cache/secretcache.go
Fixes https://github.com/istio/istio/issues/33293
[ ] Docs
[ ] Networking
[ ] Security
=> handle remove files in secret watcher

pilot/cmd/pilot-agent/options/security.go, pilot/cmd/pilot-discovery/app/cmd.go, pilot/pkg/bootstrap/certcontroller.go, pilot/pkg/bootstrap/istio_ca.go, pilot/pkg/bootstrap/options.go, pilot/pkg/bootstrap/server.go, pilot/pkg/bootstrap/server_test.go, pilot/pkg/bootstrap/sidecarinjector.go, pilot/pkg/config/kube/gateway/controller.go, pilot/pkg/features/pilot.go, pilot/pkg/networking/plugin/authn/util.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go, pilot/pkg/status/state.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/deltaadstest.go, pilot/pkg/xds/discovery.go, pilot/pkg/xds/pcds.go, pkg/bootstrap/config.go
This makes things cleaner, (slightly) faster, more consistent, and
easier to override at later points in code/test
=> Consistently early resolve environment variables

pilot/pkg/features/pilot.go, pilot/pkg/networking/core/v1alpha3/networkfilter.go
[ ] Docs
[ ] Networking
[ ] Security
=> envoy: add mongo filter feature

pkg/kube/client.go
This only impacts test code, not real prod code. Basically if the
informer will never sync, because the test has closed, the
fastWaitForCacheSync would poll indefinitely for it to sync. This makes
sure we exit early if the channel is closed
[ ] Docs
[ ] Networking
[ ] Security
=> Fix leaky informer run and wait

security/pkg/nodeagent/cache/secretcache_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> add test for cert delete and add

Makefile.core.mk, pilot/docker/Dockerfile.proxyv2
[ ] Docs
[ ] Networking
[ ] Security
=> Bump base images

pkg/test/framework/components/echo/echoboot/echoboot.go
Should not error out if injection template missing
[ ] Docs
[ ] Networking
[ ] Security
=> [tf] Avoid erroring out when injection template missing

pilot/pkg/xds/authentication.go
This has been standard practice for all of our env vars, to ensure that
other packages can override (for tests, etc)
[ ] Docs
[ ] Networking
[ ] Security
=> Export XDS_AUTH_PLAINTEXT variable

pkg/test/kube/util.go, tests/integration/pilot/common/routing.go, tests/integration/pilot/gw_topology_test.go
We can now efficiently update mesh config, no need for a new suite
[ ] Docs
[ ] Networking
[ ] Security
=> Merge gateway topology test into common suite

pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, releasenotes/notes/ef-tls-regression.yaml
Fixes https://github.com/istio/istio/issues/33410
* Fix regression when using custom transport_socket envoyfilter
Fixes https://github.com/istio/istio/issues/33385
* do not patch TSM
* test and lint
* lint
* More comments
(cherry picked from commit 97d8df38eb725dc8acaaa9fceb714968d32dfe54)
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance …
=> [1.9] Fix regression when using custom transport_socket envoyfilter (#33386)

istioctl/cmd/sysexits_test.go, releasenotes/notes/revision-tag-command.yaml
[ ] Docs
[ ] Networking
[ ] Security
=>  add ut for sysexit.go

tests/integration/pilot/ingress_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fix ingress test on old and new kubernetes versions

go.mod, go.sum
SHould work going forward as automation was fixed.
[ ] Docs
[ ] Networking
[ ] Security
=> Manual update of gogo-genproto.

common/config/.golangci-format.yml, common/config/.golangci.yml, tests/integration/security/fuzz/main_test.go
Partially addresses https://github.com/istio/istio/issues/33418
[ ] Docs
[ ] Networking
[ ] Security
=> Add integfuzz tag to lint and format configs

tests/integration/pilot/common/routing.go, tests/integration/pilot/common/traffic.go
[ ] Docs
[X] Networking
[ ] Security
=> add integration test for idle timeout in DR

pilot/pkg/model/gateway.go, pilot/pkg/model/gateway_test.go, pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/gateway_test.go, releasenotes/notes/33405.yaml
https://github.com/istio/istio/issues/33405
[ ] Docs
[X] Networking
[ ] Security
[] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> fix gateway merge on same port

pkg/test/framework/components/istio/ingress.go, pkg/test/framework/components/istio/ingress/interface.go, tests/integration/pilot/common/apps.go, tests/integration/pilot/common/routing.go, tests/integration/pilot/ingress_test.go, tests/integration/security/sds_ingress/util/util.go
https://github.com/istio/istio/issues/32282
hold to determine impact on test time
=> multicluster test for ingress

pilot/tools/debug/pilot_cli.go
[ ] Docs
[ ] Networking
[ ] Security
=> portForwardPilot: don't wait another second when reachable

pilot/pkg/model/push_context.go, pilot/pkg/model/xds_cache.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/discovery.go, pilot/pkg/xds/eds.go, pilot/pkg/xds/endpoint_builder.go
This was ran 4x in a row with assertions enabled without failures (https://prow.istio.io/pr-history/?org=istio&repo=istio&pr=33361)
Comments inline on why changes are needed
=> Fix cache invalidation issues in EDS

pilot/pkg/model/context.go
Minor variable name change
[ ] Docs
[X] Networking
[ ] Security
=> minor variable change

pilot/pkg/model/gateway.go, pilot/pkg/networking/core/v1alpha3/gateway.go
[ ] Docs
[X] Networking
[ ] Security
=> enable stable order for gateway listeners

Makefile.core.mk, pilot/pkg/xds/fake.go, pilot/pkg/xds/sds.go, pilot/pkg/xds/sds_test.go
=> Release-1.10.2-patch merge

pilot/pkg/xds/fake.go, pilot/pkg/xds/sds.go, pilot/pkg/xds/sds_test.go
=> Istiod security fix.

pilot/pkg/xds/discovery.go
[ ] Docs
[ ] Networking
[ ] Security
=> Added comments to DiscoveryServer mutex

pilot/pkg/xds/ads.go, pilot/pkg/xds/discovery.go, pilot/pkg/xds/monitoring.go
It is helpful to do load test than debug log
[ ] Docs
[ ] Networking
[ ] Security
=> Record push context init time

pilot/pkg/networking/core/v1alpha3/name_table_test.go
Adds some multi cluster and multi network cases for DNS
[ ] Docs
[X] Networking
[ ] Security
=> dns: add multi cluster and multi network cases

pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch_test.go, pilot/pkg/networking/core/v1alpha3/httproute.go
[ ] Docs
[ ] Networking
[ ] Security
=> Optimize rc patch by acquiring envoyfilterwrappr once per node

pkg/config/validation/validation.go, pkg/config/validation/validation_test.go
=> Add jwks field validation to avoid sidecar crash

pkg/kube/secretcontroller/secretcontroller.go, pkg/kube/secretcontroller/secretcontroller_test.go
Fixed a bug, when secret update, should take into consideration the clusters that are being deleted in the secret. 
For example:
Original secret:
```
data:
cluster1: "kubeconfig1"
cluster2: "kubeconfig2"
```
Updated secret:
```
data:
cluster1: "kubeconfig1"
```
[ ] Docs
[ ] Networking
[ ] Security
=> Fix multi secret update did not handle cluster delete

go.mod, go.sum
Picks up #33606 automated change which was closed needing a rebase.
[ ] Docs
[ ] Networking
[ ] Security
=> Update client-go manually

pilot/pkg/networking/core/v1alpha3/cluster_builder.go, releasenotes/notes/33536.yaml
fix: https://github.com/istio/istio/issues/33536
[ ] Docs
[ ] Networking
[ ] Security
=> Fix Istio config gen fails when sum of endpoint weights over uint32 max

go.mod, go.sum, licenses/github.com/AdaLogics/go-fuzz-headers/LICENSE, tests/fuzz/config_validation_fuzzer.go
This PR adds a fuzzer that creates a config and validates it.
Once this fuzzer is merged, I will make the necessary changes on the OSS-fuzz side to run this fuzzer continuously.
[ ] Docs
[ ] Networking
[x] Security
=> fuzzing: Add config validation fuzzer

tests/fuzz/mesh_fuzzer.go
This PR adds a fuzzer for the mesh parsing routines.
Once this fuzzer is merged, I will make the necessary changes on the OSS-fuzz side to run this fuzzer continuously.
[ ] Docs
[ ] Networking
[x] Security
=> fuzzing: Add mesh fuzzer

pilot/pkg/xds/delta.go, pilot/pkg/xds/xdsgen.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fix small typo in debug log

pilot/pkg/networking/util/util_test.go, pilot/pkg/xds/endpoint_builder.go
[ ] Docs
[ ] Networking
[ ] Security
=> Improve network2 -> network import

pkg/test/framework/components/istio/operator.go
We were previously starting tests before the gateway was available.
[ ] Docs
[ ] Networking
[ ] Security
=> Wait for remote eastwestgateway public IP

pilot/pkg/model/network.go, pilot/pkg/model/push_context.go, pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/serviceexportcache.go, pilot/pkg/xds/debug.go, pilot/pkg/xds/ep_filters_test.go
Also doing some other misc cleanup.
[ ] Docs
[x] Networking
[ ] Security
=> Adding debug/exportz for MCS

pilot/pkg/serviceregistry/kube/controller/controller.go
currently we are just triggering a push for that service specifically,
which may lead to missed updates
[ ] Docs
[ ] Networking
[ ] Security
=> Trigger full push when network gateway changes

pkg/adsc/adsc.go
Increase code readability，using switch-case instead of multiple if-else
[x] Docs
[ ] Networking
[x] Security
=> Using switch-case instead of multiple if-else

pilot/pkg/xds/bench_test.go
We don't currently measure this – we need to set gateways/networks to find out the impact of #33715
=> include multi-network eds logic in benchmark

pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go, pilot/pkg/serviceregistry/kube/controller/endpoints.go, pilot/pkg/serviceregistry/kube/controller/endpointslice.go, pilot/pkg/serviceregistry/serviceregistry_test.go
fixes https://github.com/istio/istio/issues/33672
this fix makes sure that the cache is not wiped when a single delete is called.
cc @howardjohn
=> fix endpointslice deletion bug

pilot/pkg/dns/dns.go, pilot/pkg/dns/monitoring.go
Fixes https://github.com/istio/istio/issues/33222
[ ] Docs
[X] Networking
[ ] Security
=> dns: add dns proxy stats

cni/cmd/istio-cni/main.go, cni/cmd/istio-cni/main_test.go, go.mod, go.sum
Fix https://github.com/istio/istio/issues/25847
Meanwhile remove several unimplemented commands and make cni description better.
=> Update CNI network plugin dependency.

pilot/pkg/xds/eds_sh_test.go
[ ] Docs
[x] Networking
[ ] Security
=> Resolving follow-on comments for #33715

pilot/pkg/model/sidecar.go, pilot/pkg/model/sidecar_test.go
Fix: https://github.com/istio/istio/issues/33765
=> fix multiple egress hosts select same service error

pilot/pkg/networking/core/v1alpha3/route/retry/retry.go, pilot/pkg/networking/core/v1alpha3/route/retry/retry_test.go, releasenotes/notes/33737.yaml, tests/integration/pilot/common/routing.go
https://github.com/istio/istio/issues/33737
[ ] Docs
[X] Networking
[ ] Security
[] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> fix remote retry localities

pilot/pkg/serviceregistry/kube/controller/controller.go
Unified format，extract method: syncSystemNamespace/syncNodes/syncServices
[ ] Docs
[x] Networking
[ ] Security
=> Extract method to sync namespace/node/service

pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go, pilot/pkg/serviceregistry/kube/controller/endpoints.go, pilot/pkg/serviceregistry/kube/controller/endpointslice.go
Previously #25978 has fixed in `buildIstioEndpoints`, this is to completely fix it.
[ ] Docs
[ ] Networking
[ ] Security
=> handle pod occur later than endpoint

pilot/pkg/serviceregistry/kube/controller/controller.go
[ ] Docs
[] Networking
[ ] Security
=> fix kube controller link
