- tests/integration/pilot/ingress_test.go
- tests/integration/pilot/multi_version_revision_test.go
- tests/integration/pilot/revisioned_upgrade_test.go
Cleanup PR, moves from `t.Run(...)` to `ctx.NewSubtest(...).Run(...)` in `integration/pilot` suite (per [writing good integration tests](https://github.com/istio/istio/wiki/Writing-Good-Integration-Tests#prefer-frameworktestcontext-over-testingt) guide)
[ ] Docs
[ ] Networking
[ ] Security
> Use ctx.Run rather than t.Run in integration/pilot tests

- pkg/test/framework/components/echo/common/envoy_test.go
- pkg/test/framework/components/echo/echo.go
- pkg/test/framework/components/echo/kube/instance.go
- tests/integration/pilot/multi_version_revision_test.go
- tests/integration/pilot/revisioned_upgrade_test.go
Allows echo instances to be restarted without port forwarding failures. 
The flow is (1) close all websocket connections to old workloads, (2) do a `kubectl rollout restart` on the echo deployment, and (3) re-initialize the echo instance's workloads.
cc @nmittler since we talked about this a few weeks ago
[ ] Docs
[ ] Networking
[ ] Security
> [test-framework] Add restart to echo instance

- pkg/test/framework/components/istio/config.go
- pkg/test/framework/components/istio/flags.go
- pkg/test/framework/components/istio/helm.go
- pkg/test/framework/components/istio/istio.go
- pkg/test/helm/helm.go
- tests/integration/helm/install_test.go
- tests/integration/helm/main_test.go
The current suite of helm-based installs do not conform to the
integration testing framework. For scenarios where installation will
differ from the istioctl variant, built-in functionality would make it
easier for others to write tests. This would help also in that it would
support such flags such as --istio.test.nocleanup.
There is no multi-cluster support.
[ ] Docs
[ ] Networking
[ ] Security
> Add support for helm installs to integration framework

- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
The current implementation affects the filterChains even though the destination port doesn't match.
We should only apply the EnvoyFilter when the destination port matches.
Signed-off-by: zhaohuabing <huabingzhao@tencent.com>
[ ] Docs
[X] Networking
[ ] Security
> Fix: EnvoyFilter destination port match is incorrect

- pilot/pkg/xds/eds.go
- pilot/pkg/xds/gen.go
This was present on others, but missing for EDS. Add it for consistency.
End result:
```
2020-12-29T16:06:02.397001Z     info    ads     CDS: PUSH for node:4c5bab2845ad.default resources:10 size:4.1kB
2020-12-29T16:06:02.397126Z     info    ads     EDS: PUSH for node:4c5bab2845ad.default resources:5 size:981B empty:1 cached:0/5
2020-12-29T16:06:02.397683Z     info    ads     LDS: PUSH for node:4c5bab2845ad.default resources:7 size:15.3kB
2020-12-29T16:06:02.397902Z     info    ads     NDS: PUSH for node:4c5bab2845ad.default resources:1 size:330B
2020-12-29T16:06:02.398067Z     info    ads     RDS: PUSH for node:4c5bab2845ad.default resources:3 size:1.9kB
```
put an X in all …
> Add size to EDS log

- go.mod
- go.sum
- licenses/github.com/evanphx/json-patch/v5/LICENSE
- pilot/pkg/config/kube/crdclient/client.go
- pilot/pkg/config/kube/crdclient/client_test.go
- pilot/pkg/config/kube/crdclient/gen/types.go.tmpl
- pilot/pkg/config/kube/crdclient/types.gen.go
- pilot/pkg/config/memory/config.go
- pilot/pkg/config/memory/controller.go
- pilot/pkg/controller/workloadentry/workloadentry_controller.go
- pilot/pkg/controller/workloadentry/workloadentry_controller_test.go
- pilot/pkg/xds/ads.go
- pkg/config/model.go
#29685 handles the case where we `QueueUnregisterWorkload` is called for the orignal connection _after_ a reconnect by dropping the disconnect event. 
This PR handles the case where `QueueUnregisterWorkload` is called _before_ the reconnect logic, but it's queued workitem is handled _after_. This is robust to both same-instance, and multiple-instance cases. 
We use the merge patch to reduce the number of failures from `Patch`. Using another retry loop would require additional complexity to stop retrying if the connection is terminated. 
<details>
<summary> old description </summary>
This may solve part of the case that https://github.com/istio/istio/pull/29685 describes without being tied to a single istiod. 
Now we check if the `ConnectedAt` timestamp was set using the same connection …
> vm auto registration: discard stale disconnect events

- tests/integration/telemetry/stats/prometheus/nullvm/dashboard_test.go
- tests/integration/telemetry/stats/prometheus/stats.go
* Fix an issue where tcp port is wrong. It still worked because its just
tcp metrics but we should probably send proper traffic
* Change from "send a bunch of traffic, then check metrics" to "send a
bunch of traffic in the background, while we continuously check for
metrics". This is both faster (we don't have a minimum test time of 20s)
but also less flaky
Testgrid showing recent failures: https://testgrid.k8s.io/istio_istio#integ-telemetry-k8s-tests_istio&width=20&exclude-non-failed-tests=
> Refactor dashboard test to reduce flakes

- pilot/pkg/model/context.go
- pilot/pkg/networking/apigen/apigen.go
- pilot/pkg/networking/grpcgen/grpcgen.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/cds.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/gen.go
- pilot/pkg/xds/lds.go
- pilot/pkg/xds/nds.go
- pilot/pkg/xds/rds.go
- pilot/pkg/xds/sds.go
- pilot/pkg/xds/sds_test.go
- pilot/pkg/xds/simple.go
- pilot/pkg/xds/statusgen.go
This is split out of https://github.com/istio/istio/pull/29688 which
requires sending errors. This just allows the generators to return an
error; in this PR all generators always return non-nil errors as
expected.
[ ] Docs
[ ] Networking
[ ] Security
> ads: refactor to allow Generator to return error

- pkg/istio-agent/health/health_probers_test.go
Example:
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/29646/unit-tests_istio/1343983060076466176
The problem is we have a 1s timeout, but the command also takes 1s. This
makes it racy. Instead, make the timeout shorter and command longer.
```
4072 runs so far, 0 failures (100.00% pass rate). 530.759386ms avg, 927.967307ms max, 298.880314ms min
```
> Fix TestExecProber flakes

- pilot/cmd/pilot-agent/main.go
- pkg/config/constants/constants.go
- pkg/istio-agent/agent.go
- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_test.go
Fixes https://github.com/istio/istio/issues/29749
This is a real bug, although one that probably has minimal to no impact.
What happens is we register a stream, then call close. Normally, this
unregisters the stream, then the new connection is established and
everything works fine.
In some cases, the new connection happens *before* we unregister the old
stream, so unregister closes the new stream instead of the old one.
If this were to happen in the real world, Envoy would just reconnect
again so not much harm done.
The fix here is to make it so we only close the old connection when its
matching the one we expect. We also explicitly close the old stream if
we have two concurrent streams (shouldn't happen, but who knows...)
Additionally, made the XDS path configurable so unit tests can run …
> Fix TestXdsProxyReconnects flakes

- pilot/pkg/config/aggregate/config_test.go
- pilot/pkg/config/kube/crdclient/client_test.go
- pilot/pkg/networking/core/v1alpha3/fake.go
- pkg/test/util/retry/retry.go
This adds a new retry method, that takes a bool function instead of an
error function. Its very common to have functions doing
```go
if cond() { return error } else { return nil }
```
Now they can just do `retry.Until(cond)`, which is a bit simpler.
I also moved a few examples over to the new syntax to validate the API
makes sense and works.
[ ] Docs
[ ] Networking
[ ] Security
> Add retry.Until helper function

- .gitignore
Generated when running `go test -c`. I have seen a few users check these
in accidentally (mostly me).
> Add golang compiled tests to gitignore

- pilot/pkg/xds/filters/filters.go
- pkg/test/echo/client/parsedresponse.go
- pkg/test/echo/server/endpoint/http.go
- pkg/test/framework/components/echo/call.go
- pkg/test/framework/components/echo/common/call.go
- releasenotes/notes/standard-alpn.yaml
- tests/integration/pilot/common/apps.go
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/common/traffic.go
- tests/integration/pilot/istioctl_test.go
Fixes #24619
This allows outbound TLS origination to maintain standard ALPN values
(rather than `istio-` values). A more proper solution would be to send
only istio ones when the destination is a sidecar, and only standard
ones when not, but this requires a total change of how the filter works.
The end result here is no impact on sidecar traffic other than an
additional ALPN set, which should never impact filter chain matching
(since first ALPN has precedence), but outbound TLS will have multiple
ALPNs set and the standard ALPNs should be selected.
> Set standard alpns as well in outbound traffic

- pkg/test/framework/features/features.yaml
- tests/integration/security/ecc_signature_algorithm/main_test.go
- tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
Fixes https://github.com/istio/istio/pull/28894
Cherry-pick of https://github.com/istio/istio/pull/28894 via sha 5a5c0ebf40d232d0886389d4b6a74976dba87a14
* Add integration test for ECC_SIGNATURE_ALGORITHM
There was a previous regression when specifying ECC_SIGNATURE_ALGORITHM,
see https://github.com/istio/istio/pull/25203.
Setup:
- A test namespace is created
- A client and server Echo deployment is created in this namespace
- The appropriate PeerAuthentication and DestinationRule resources are
set so that mTLS is strict and used
- The root CA is not altered and it will use a generated certificate
using RSA. Due to https://github.com/istio/istio/pull/27239, the
root CA no longer has to ECC to enable ECC_SIGNATURE_ALGORITHM. This has
the benefit of additional testing as well.
Test:
- The …
> [release-1.8] Add ECC_SIGNATURE_ALGORITHM env integration test (#28894)

- pilot/pkg/xds/eds_test.go
The root cause is we may have some lingering RDS/LDS pushes not
finished. Instead, we should wait for EDS response specifically, not any
respones, and check that we didn't get any CDS response.
963 runs so far, 0 failures (100.00% pass rate). 7.433370536s avg, 9.768572747s max, 5.345023667s min
[ ] Docs
[ ] Networking
[ ] Security
> Fix TestEndpointFlipFlops test flakes

- pkg/kube/secretcontroller/secretcontroller.go
This causes a bunch of logs like `klog  timed out waiting for caches to sync` in all of our tests,
which gets highlighted by Prow and obscures real errors. I don't think
we really need this log, it only happens when the stop channel is closed
so Istio is shutting down; no other controllers do it.
[ ] Docs
[ ] Networking
[ ] Security
> Remove spammy logs in unit tests

- pilot/pkg/serviceregistry/kube/controller/controller.go
- Just fixing the debug log format for the kubernetes endpoints synchronization:
```
debug   initializing 0 nodes
debug   initializing 0 services
debug   initializing 0 pods
debug   initializing0 endpoints
```
```
debug   initializing 0 nodes
debug   initializing 0 services
debug   initializing 0 pods
debug   initializing 0 endpoints
```
[ ] Docs
[ ] Networking
[ ] Security
> Fix the debug log format for the kubernetes endpoints synchronizations

- prow/integ-suite-kind.sh
The trace command, defined in prow/lib.sh, requires the ARTIFACTS
variable be set otherwise it crashes. When running the integ-suite-kind.sh script to get
a multicluster setup I had to define this manually. Move the definition
of this variable from a later defined location to that before trace is executed.
[ ] Docs
[ ] Networking
[ ] Security
> integ-suite-kind.sh requires ARTIFACTS variable

- pilot/pkg/secrets/kube/secrets.go
- pilot/pkg/secrets/kube/secrets_test.go
- releasenotes/notes/sds-cacert-precedence.yaml
Fixes https://github.com/istio/istio/issues/29856
This restores the behavior prior to Istio 1.8, and adds a test
> Fix -cacerts precedence order

- pilot/pkg/serviceregistry/kube/controller/controller.go
Race 1: simple data race, add proper RLock since we mutate these
variables (with Lock())
Race 2: Run() is called in a goroutine. This means we may start doing
things before Run() actually happens. HasSynced can pass without Run()
being called, so the issue that arises is that reloadNetworkLookup
doesn't run, and multinetwork gives unexpected results. This is
trivially reproducible with a sleep(1s) in start of Run().
This was tested (along with some other fixes I am working on) by running
TestMeshNetworking 10k times over 1hr and getting 0 failures.
[ ] Docs
[ ] Networking
[ ] Security …
> Fix race conditions in multinetwork

- pkg/test/framework/features/features.yaml
- tests/integration/security/ecc_signature_algorithm/main_test.go
- tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
Fixes https://github.com/istio/istio/pull/28894
Cherry-pick of https://github.com/istio/istio/pull/28894 with sha 5a5c0ebf40d232d0886389d4b6a74976dba87a14
* Add integration test for ECC_SIGNATURE_ALGORITHM
There was a previous regression when specifying ECC_SIGNATURE_ALGORITHM,
see https://github.com/istio/istio/pull/25203.
Setup:
- A test namespace is created
- A client and server Echo deployment is created in this namespace
- The appropriate PeerAuthentication and DestinationRule resources are
set so that mTLS is strict and used
- The root CA is not altered and it will use a generated certificate
using RSA. Due to https://github.com/istio/istio/pull/27239, the
root CA no longer has to ECC to enable ECC_SIGNATURE_ALGORITHM. This has
the benefit of additional testing as well.
Test:
- The …
> [release-1.7] Add ECC_SIGNATURE_ALGORITHM env integration test (#28894)

- tests/integration/telemetry/stats/prometheus/nullvm/dashboard_test.go
This PR attempts to address test flakes related to querying of k8s container metrics in the dashboard tests. It removes them from consideration in evaluating dashboard queries.
Resolves https://github.com/istio/istio/issues/29871
[ X ] Does not have any changes that may affect Istio users.
> Remove container metrics from dashboard tests

- pkg/test/framework/components/echo/kube/instance.go
- tests/integration/pilot/revisioned_upgrade_test.go
Bump timeout for rollout readiness from 30->60 seconds, addresses failures like [https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/1346538920686391296](https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/1346538920686391296)
[ ] Docs
[ ] Networking
[ ] Security
> [test framework] Bump timeout for echo instance rollout

- pkg/test/framework/components/echo/kube/instance.go
Use the echo instance's `ReadinessTimeout`  for `Restart()` timeout rather than hardcoded value, @nmittler per your comment on timeout-bump PR
[ ] Docs
[ ] Networking
[ ] Security
> [test-framework] Use echo instance ReadinessTimeout for restart timeout

- pkg/queue/delay.go
- pkg/queue/delay_test.go
Tested with `7397 runs so far, 0 failures (100.00% pass rate). 258.117472ms avg, 570.8326ms max, 35.770251ms min`
Before fix, failed with:
```
==================
WARNING: DATA RACE
Read at 0x00c0000c20e0 by goroutine 34:
istio.io/istio/pkg/queue.(*pq).Push()
/home/howardjohn/go/src/istio.io/istio/pkg/queue/delay.go:54 +0x6db
istio.io/istio/pkg/queue.(*delayQueue).Run()
/home/howardjohn/go/src/istio.io/istio/pkg/queue/delay.go:220 +0x688
Previous write at 0x00c0000c20e0 by goroutine 33:
istio.io/istio/pkg/queue.(*pq).Push()
/home/howardjohn/go/src/istio.io/istio/pkg/queue/delay.go:54 +0xc6
container/heap.Push()
/usr/lib/go-1.15/src/container/heap/heap.go:53 +0x56
istio.io/istio/pkg/queue.(*delayQueue).PushDelayed()
/home/howardjohn/go/src/istio.io/istio/pkg/queue/delay.go:168 +0x1cb …
```
> Fix race in delayed queue

- pilot/pkg/bootstrap/server.go
- pilot/pkg/networking/core/v1alpha3/fake.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/discovery_test.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/fake.go
This contains 3 fixes for 3 races mentioned in detail in https://github.com/istio/istio/issues/29830
1. concurrent PushContext initialization may lead to storing resulting push contexts out of order, dropping a later push context. This is fixed by simply dropping `go` on AdsPushAll. It doesn't need to be a goroutine anyways, its not doing any blocking work.
2. A race between initProxy and addCon; we get some PC-1 when we init proxy, then PC-2 starts to push, but since we are not registered, we miss the push and never get an update. The fix here is to add the connection first, but block pushes until the proxy has completed initialized
3. HasSynced returns true before push context initialization is complete, leading to early connecting proxies not getting the full state of the world. This …
> Fix various races in push context initialization

- cni/cmd/istio-cni-taint/main.go
- cni/pkg/taint/taintcontroller.go
- cni/pkg/taint/taintcontroller_test.go
The issue here is we add the nodes to our fake informer but not to the
fake client, so if the informer updates it breaks the test. This means
we are actually only passing when the informer is empty.
The real logic in the CNI code is also highly suspicious, I am pretty
sure RegisterTaints will always return 0 nodes since we have the same
issue of not loading the informer first. However, I am focusing only on
fixing the tests right now.
`9502 runs so far, 0 failures (100.00% pass rate). 106.009871ms avg, 215.807378ms max, 61.498086ms min`
> Fix RegisterTaints test flakes

- tools/istio-docker.mk
I am not sure why it works in the CI, but on my machine any VM image I
build is broken since the certs are not readable. This fixes the issue.
[ ] Docs
[ ] Networking
[ ] Security
> docker: chmod certs to make them readable

- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/components/echo/kube/instance.go
- tests/integration/iop-integration-test-defaults.yaml
Currently, we rely on Kubernetes health checking, which isn't actually
available in a real VM. This changes our tests to exercise the health
checking we will actually run
> Enable VM native health checking for tests

- istioctl/cmd/proxyconfig.go
Added >1 year ago now, has as much test coverage (and works the same way) as the other `istioctl proxy-config` commands
[ ] Docs
[ ] Networking
[ ] Security
> Remove experimental marker from istioctl pc secret command

- releasenotes/notes/redirect-dns-iptables.yaml
- tools/istio-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/cmd/run.go
- tools/istio-iptables/pkg/cmd/run_test.go
- tools/istio-iptables/pkg/config/config.go
- tools/istio-iptables/pkg/constants/constants.go
In current state it is impossible to reasonably use dns redirection to agent when imported iptables package is used by other golang module. Environmental variable "ISTIO_META_DNS_CAPTURE" is added as global private module variable forcing potential users of the library to have to set up this variable in environment before their binary is up and running.
This change fixes that problem by simply adding "redirect-dns" option to iptables CLI, making it possible to use dns redirection directly from within go code that imports that package without having to set up environmental variable.
[ ] Docs
[x] Networking
[ ] Security
[ ] Developer …
> Update istio iptables CLI to specify DNS redirection

- pilot/pkg/dns/dns.go
- pilot/pkg/networking/core/v1alpha3/name_table.go
- pilot/pkg/xds/testdata/nds-se.yaml
These are filtered in istio-agent anyways, but this just makes it more
clear they are not supported. There should be no user facing change -
CIDR is not supported in DNS response before nor after this change
[ ] Docs
[ ] Networking
[ ] Security
> Filter CIDRs in NDS response

- pilot/pkg/dns/dns.go
When host contains capital letters，it will resolv fail by smart dns proxy。
In this place,it make the query name to lowercase.
[ x] Configuration Infrastructure
[ x] Docs
[ x] Installation
[Y] Networking
[ x] Performance and Scalability
[ x] Policies and Telemetry
[ x] Security
[ x] Test and Release
[ x] User Experience
[ x] Developer Infrastructure
> Make host lowercase

- pkg/istio-agent/agent_test.go
The 2048 bit RSA is so expensive on a highly contended node sometimes
signing the cert times out in CI
Fixes https://github.com/istio/istio/issues/29920
[ ] Docs
[ ] Networking
[ ] Security
> Increase timeout for TestAgent

- prow/config/topology/multicluster-large.json
- prow/config/topology/multicluster.json
These clusters are named cluster1, cluster2, etc. But in the test
framework, they end up like cluster-0, cluster-1, etc.
Changing these for consistency to avoid the confusion of differernt
numbering schemes
[ ] Docs
[ ] Networking
[ ] Security
> tf: rename multicluster clusters

- pilot/pkg/model/push_context.go
- pilot/pkg/model/sidecar.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/gen.go
Add the version information into push context and sidecar scope, add
version/nonce to some additional (debug logs), and add /debug/sidecarz
endpoint. All of these are helpful around debugging issues with push
context initialization, version ordering, etc.
[ ] Docs
[ ] Networking
[ ] Security
> Improve debugging around push contexts, sidecar scope

- manifests/charts/istio-control/istio-discovery/values.yaml
- manifests/charts/istiod-remote/values.yaml
- pilot/cmd/pilot-agent/main.go
@howardjohn i think you already implemented [this](https://github.com/istio/istio/blob/84f00a1e81337b94cacce65fa9936ed390dd3fd2/pilot/cmd/pilot-agent/main.go#L360) so I'm just marking comments to be correct.
related to https://github.com/istio/istio/issues/28708
[ ] Docs
[x ] Networking
[ ] Security
> caAddress is default to discoveryAddr

- tests/integration/pilot/common/routing.go
- tests/integration/pilot/common/traffic.go
This works around a real bug to make our tests less flaky.
Fixes https://github.com/istio/istio/issues/29915
The bug is well understood at this point I think
(https://github.com/envoyproxy/envoy/issues/14598), so for now there is
no need to suffer flakes while its being worked on.
The issue with the previous test is it rapidly adds and removes TLS
options to the cluster. Envoy appear to have a race where it sometimes
drops the last update. The changes here ensure we apply the TLS options
a single time, then send a bunch of requests, rather than flip-flopping.
[ ] Docs
[ ] Networking
[ ] Security
Pull Request …
> Fix tls-origination test flakes

- cni/cmd/istio-cni/iptables.go
Prevents BusyBox's build of `nsenter` from incorrectly parsing `istio-iptables.sh` arguments as its own. Discovered when using the Kubernetes distribution "k3s" (https://github.com/k3s-io/k3s/issues/1434). A similar fix was used for [Linkerd](https://github.com/linkerd/linkerd2-proxy-init/pull/26).
[ ] Docs
[X] Networking
[ ] Security
> Fixes BusyBox nsenter from parsing iptables script args

- pkg/kube/inject/validate.go
This log is often outdated, as we forget to add annotations here. I
considered making it so we look at the full list of annotations in the
API, but instead decided to remove this entirely. My rationale was that
logging in Istiod is the incorrect place to expose this, and this
information is already (correctly) exposed by `istioctl analyze`.
[ ] Docs
[ ] Networking
[ ] Security
> Hide "unknown annotation" logs

- samples/extauthz/src/Makefile
ext authz sample current tag is 0.6 but makefile still uses 0.5. This PR fixes it
[ ] Docs
[ ] Networking
[ ] Security
> update ext authz tag in make file

- pkg/istio-agent/xds_proxy.go
Results, assuming https://github.com/envoyproxy/envoy/pull/14616#pullrequestreview-565567086 removes envoy logs for status code=0
```
2021-01-11T18:05:53.451244Z     info    xdsproxy        connected to upstream XDS server: localhost:15012
2021-01-11T10:06:14.309738Z     warning envoy config    StreamAggregatedResources gRPC config stream closed: 0,
2021-01-11T18:06:14.759961Z     info    xdsproxy        connected to upstream XDS server: localhost:15012
2021-01-11T10:06:17.576631Z     warning envoy config    StreamAggregatedResources gRPC config stream closed: 14, connection error: desc = "transport: Error while dialing dial tcp [::1]:15012: connect: connection refused"
2021-01-11T10:06:18.262982Z     warning envoy config    StreamAggregatedResources gRPC config stream closed: 14, …
```
> Another attempt at xds proxy log cleanup

- istioctl/pkg/multicluster/remote_secret.go
- istioctl/pkg/multicluster/remote_secret_test.go
Allows overriding the `server` when we want istiod to access the API server using a specific IP/hostname. 
Could be useful in environments that have private-IPs for the API server, or to help with allowing multi-cluster tests to workaround [the lack of docker0 on MacOS](https://docs.docker.com/docker-for-mac/networking/#there-is-no-docker0-bridge-on-macos).
cc @myidpt
> add --server flag to create-remote-secret

- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
- pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- pilot/pkg/simulation/traffic.go
- pilot/pkg/xds/filters/filters.go
- pilot/test/xdstest/test.go
- pkg/test/echo/client/parsedresponse.go
- pkg/test/echo/server/endpoint/http.go
- pkg/test/framework/components/echo/call.go
- pkg/test/framework/components/echo/common/call.go
- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/components/echo/kube/testdata/basic.yaml
- pkg/test/framework/components/echo/kube/testdata/healthcheck-rewrite.yaml
- pkg/test/framework/components/echo/kube/testdata/multiversion.yaml
- pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml
- releasenotes/notes/standard-alpn.yaml
- releasenotes/notes/tls-fc.yaml
- releasenotes/notes/vm-multiple-targetport.yaml
- tests/integration/pilot/common/apps.go
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/common/traffic.go
- tests/integration/pilot/istioctl_test.go
- tests/integration/security/reachability_test.go
- tests/integration/security/testdata/plaintext-to-permissive.yaml
- tests/integration/security/util/framework.go
- tests/integration/security/util/reachability/context.go
* #29584 provides baseline testing
* #29589 fixes critical regression in TLS
* #29529 fixes a long standing bug causing the incorrect ALPN to be sent to external services
* #29621 fixes an issue with WorkloadEntry causing tests to fail
These are all in one PR since they all depend on each other.
> [1.8] Various TLS fixes

- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
- releasenotes/notes/envoyfilter-legacy-names.yaml
Fixes https://github.com/istio/istio/issues/29858
Fixes https://github.com/istio/istio/issues/29909
The issue here is we apply a merge with the legacy filter name,
overwriting the filter name, then
later expect to match on the new filter name, which fails (since its now
the legacy name).
[ ] Docs
[ ] Networking
[ ] Security
> Prevent EnvoyFilter overwriting others when using deprecated names

- pilot/pkg/serviceregistry/kube/controller/controller.go
Currently, we trigger all the pod and endpoint read events. This always
fails, and spams the logs, since Services have not been synced.
Instead, at startup just prepare the networks/gateways and rely on the
standard SyncAll call to trigger the explicit pod sync.
Without this, we get many `Handle EDS endpoint: skip collecting workload entry endpoints, service rancher.io-local-path/local-path-storage has not been populated`
> Fix networks initialization

- pilot/pkg/model/sidecar.go
- pilot/pkg/model/sidecar_test.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
Currently sidecar.Egress is required. This is a major pain when you just
want to set outbound traffic policy or ingress settings.
I have changed this to be optional. When its not set, the existing
behavior (`hosts: [*/*]`) is maintained.
The API docs already say this field is not required
> Sidecar.Egress: provide default and allow unset

- go.mod
- go.sum
Update dependency gogo/protobuf from 1.3.1 to 1.3.2
[ ] Docs
[ ] Networking
[ ] Security
> Update gogo/protobuf to 1.3.2

- security/pkg/nodeagent/sds/sdsservice.go
- security/pkg/nodeagent/sds/server.go
SDS Service trying to pre generate certs and fills the logs with warning "failed to warm certificate: failed to generate workload certificate: attempted to fetch secret, but ca client is nil".  This is not needed for file mounted certs case.
[ ] Docs
[ ] Networking
[X ] Security
> do not try to pre generate certs for file mounted certs

- bin/retry.sh
Currently, retry.sh is buffering up all the output which makes it hard
to tell what is going on.
[ ] Docs
[ ] Networking
[ ] Security
> retry.sh: stream output to stdout

- pkg/bootstrap/testdata/all_golden.json
- pkg/bootstrap/testdata/auth_golden.json
- pkg/bootstrap/testdata/authsds_golden.json
- pkg/bootstrap/testdata/default_golden.json
- pkg/bootstrap/testdata/running_golden.json
- pkg/bootstrap/testdata/runningsds_golden.json
- pkg/bootstrap/testdata/stats_inclusion_golden.json
- pkg/bootstrap/testdata/tracing_datadog_golden.json
- pkg/bootstrap/testdata/tracing_lightstep_golden.json
- pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
- pkg/bootstrap/testdata/tracing_stackdriver_golden.json
- pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
- pkg/bootstrap/testdata/tracing_tls_golden.json
- pkg/bootstrap/testdata/tracing_zipkin_golden.json
- pkg/bootstrap/testdata/xdsproxy_golden.json
- tools/packaging/common/envoy_bootstrap.json
Fix the name here is repeated with prometheus_stats. Although it works, it's better to modify it.
[ ] Docs
[ ] Networking
[ ] Security
> Fix envoy_bootstrap agent cluster name

- galley/pkg/config/analysis/analyzers/analyzers_test.go
- galley/pkg/config/analysis/analyzers/annotations/annotations.go
- galley/pkg/config/analysis/analyzers/util/find_errorline_utils.go
- galley/pkg/config/analysis/msg/messages.gen.go
- galley/pkg/config/analysis/msg/messages.yaml
- releasenotes/notes/29918.yaml
This is the first part of an implementation for https://github.com/istio/istio/issues/29154
Check annotations and report at INFO level if they are deprecated or alpha
To test interactively, built _istioctl_ and run `istioctl analyze`.
Create a deprecated/alpha annotation for testing
```
kubectl create svc nodeport foo --tcp 8080
kubectl annotate svc foo alpha.istio.io/canonical-serviceaccounts=bar
```
@nmittler Would love to have your input, as your framework provided the ability.
> annotation deprecation and alpha status analyzer

- pkg/test/framework/components/istio/helm.go
- pkg/test/kube/dump.go
We get a lot of users seeing these "errors" and missing that the error
is a few more lines up the page. Drop these to warnings to make it clear
this is NOT why the test failed, but rather an issue after the test has
already failed
> Drop log level for test framework dumping

- pkg/test/framework/resource/flags.go
- pkg/test/framework/resource/matcher.go
- pkg/test/framework/resource/matcher_test.go
- pkg/test/framework/resource/settings.go
- pkg/test/framework/testcontext.go
Currently, tests can be selectively run with -test.run or testing only
specific packages with `go list`. However, test.run cannot do
exclusions, so if we want to skip a single test its quite hard. For
example, as an internal user I may not support the FooBar feature and
may want to skip the test. With this change, I can add
`--istio.test.skip=FooBar`.
> test framework: allow skipping tests as a CLI flag

- tests/integration/pilot/multi_version_revision_test.go
Accidentally introduced a go 1.16 feature
[ ] Docs
[ ] Networking
[ ] Security
> Make integ test support go 1.15

- pkg/test/framework/testcontext.go
maybe the better fix is to swap the functions as well? I am not sure which is more intuitive.
> Fix mixed up cleanup/whendone comment

- pilot/pkg/model/push_context.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/fake.go
- pilot/pkg/serviceregistry/kube/controller/network.go
- pilot/pkg/xds/fake.go
- pilot/pkg/xds/mesh_network_test.go
- releasenotes/notes/30070.yaml
fixes https://github.com/istio/istio/issues/30054 by checking for a diff in the networks for a given service that was updated. If there is any difference, we trigger a push. 
This does _not_ cover what happens if the label _was_ on a Service and was then removed. It's difficult to tell which network the label was previously, so we don't know which network to remove this gateway from.
> trigger push when networks change

- pkg/istio-agent/agent_test.go
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/30138/unit-tests_istio/1351717598479257600
Sometimes our CI is SUPER slow to sign a single RSA cert - in the log
above it took 8s
[ ] Docs
[ ] Networking
[ ] Security
> Bump TestAgent timeout up (again)

- pkg/test/framework/components/echo/echo.go
- pkg/test/framework/components/echo/echoboot/echoboot.go
- pkg/test/framework/components/echo/kube/builder.go
- tests/integration/multicluster/helper.go
- tests/integration/pilot/common/apps.go
- tests/integration/pilot/multi_version_revision_test.go
- tests/integration/pilot/vm_test.go
- tests/integration/security/authorization_test.go
- tests/integration/security/ca_custom_root/main_test.go
- tests/integration/security/ecc_signature_algorithm/main_test.go
- tests/integration/security/sds_egress/sds_istio_mutual_egress_test.go
- tests/integration/security/util/framework.go
- tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
- tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
- tests/integration/telemetry/stats/prometheus/stats.go
- tests/integration/telemetry/tracing/tracing.go
Additional changes to go along with #30092.
- This will allow us to swap out echo deployment strategies based on cluster type. 
- Also removes the need for looping/duplicating echo.Configs per-cluster (for services identical across clusters). 
- _May_ reduce telemetry test times, there were multiple places that called `Build` on echobuilder more than once.
> refactor echo.Builder to allow multiple clusters

- pilot/pkg/bootstrap/server.go
This fixes a bug where the port is labeled as http2, and KNative or
Istio upgrades the port to HTTP/2. Low risk for all other cases.
[ ] Docs
[ ] Networking
[ ] Security
> When running Istiod in a KNative environment the ports are multiplexed.

- pilot/pkg/features/pilot.go
- pilot/pkg/xds/testdata/ecds.yaml
- pkg/config/constants/constants.go
- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_test.go
- pkg/wasm/cache.go
- pkg/wasm/convert.go
- pkg/wasm/convert_test.go
- releasenotes/notes/reliable-wasm-remote-load.yaml
Manual cherry-pick of https://github.com/istio/istio/issues/30235
* Add ECDS interception and Wasm conversion into xds proxy.
* update
* file path
* fix race in test
* clean up
* do not block on downstream error channel
* add a release note.
* add feature flag for Wasm remote load conversion.
* update
* update
[ ] Docs
[ ] Networking
[ ] Security
> [release-1.9] Add ECDS interception and Wasm conversion into xds proxy. (#30086)

- istioctl/pkg/install/k8sversion/version.go
- istioctl/pkg/install/k8sversion/version_test.go
- istioctl/pkg/install/pre-check_test.go
- releasenotes/notes/min-k8-ver-for-1.9.yaml
Ref: https://docs.google.com/document/d/14Xfe9V0vv8d7W75c21d-cY2XyK6xvRH0_Kg8j_zfh4Y/edit#
Istio `1.9` supports k8 `1.17` to `1.20` versions.
Previous change:
https://github.com/istio/istio/pull/28814
> Update min k8 supported version for Istio 1.9

- istioctl/pkg/install/pre-check.go
To fix https://github.com/istio/istio/issues/30300
Before:
```
[istio-1.9.0-beta.0]$ ./bin/istioctl x precheck
Istio Revision "" already installed in namespace "istio-system"
```
After:
Install Istio without revision.
```
[istio-1.9.0-beta.0]$ ./bin/istioctl install --set values.global.jwtPolicy=first-party-jwt
[istio-master]$ ./out/linux_amd64/istioctl x precheck
"default" revision of Istio is already installed in "istio-system" namespace
```
Install Istio with revision `1-9-beta`
```
[istio-1.9.0-beta.0]$ ./bin/istioctl install -r 1-9-beta --set values.global.jwtPolicy=first-party-jwt
[istio-1.9.0-beta.0]$ ./out/linux_amd64/istioctl x precheck
"1-9-beta" revision of Istio is already installed in "istio-system" namespace
```
> Fix empty revision for precheck

- pkg/test/framework/components/istio/operator.go
- pkg/test/kube/dump.go
Just ran into a case where stale config broke a test. This would make it simple to spot.
> Add configz to tf dump

- pilot/pkg/bootstrap/istio_ca.go
- pilot/pkg/bootstrap/options.go
- pilot/pkg/bootstrap/server.go
- pilot/pkg/bootstrap/server_test.go
- releasenotes/notes/30294.yaml
- security/pkg/server/ca/authenticate/oidc.go
- security/pkg/server/ca/authenticate/oidc_test.go
Please provide a description for what this PR is for: https://github.com/istio/istio/issues/30295
- Implement an OIDC JWT authenticator that supports both JWKS-URI and OIDC discovery. The OIDC JWT authenticator can be configured through the JWT_RULE env variable and when configured, it will be used as an istiod authenticator.
- Add tests for the OIDC JWT authenticator.
[ ] Docs
[X ] Security
> OIDC JWT authenticator

- manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
- manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.8.yaml
- manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.9.yaml
- manifests/charts/istiod-remote/templates/telemetryv2_1.8.yaml
- manifests/charts/istiod-remote/templates/telemetryv2_1.9.yaml
- operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/telemetryv2_1.8.yaml
- operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/templates/telemetryv2_1.8.yaml
- operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
- operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
(cherry picked from commit a94cb8dac3e57b4134ce000820d164430e2419ba)
Fixes https://github.com/istio/istio/issues/30278
> Use non-deprecated envoyfilter names (#30220)

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
Suppose there are services with the same hostname but in different namespaces, and these services are only visible to the namespace where they are located. When we are building a cluster key from the Destination in HTTPRoute, in order to comply with the visibility specified by the ExportTo attribute of the Service, we need to obtain a service with the same namespace as the VirtualService from PushConext. 
However, the current code just gets the service directly based on the hostname, without considering the issue of visibility.
[ ] Docs
[ ] Networking
[ ] Security
> Enhance the namespace isolation of services in buildGatewayHTTPRouteConfig.

- pilot/pkg/features/pilot.go
- tests/integration/iop-integration-test-defaults.yaml
This is intended for 1.10, not 1.9. We are planning promotion in 1.9, so
this should be safe for 1.10. Additionally, these flags are very low
risk - nothing happens for users unless they actually configure the
proxy/workloadgroup to use these features.
[ ] Docs
[ ] Networking
[ ] Security
> Enable VM flags by default

- pkg/kube/inject/inject_test.go
- pkg/kube/inject/testdata/inject/hello.yaml.cni.injected
- pkg/kube/inject/webhook.go
fixes https://github.com/istio/istio/issues/30376
The namespace label is a catch-all that hides this in integration tests #28126 and 1.8+ users, so it was not noticed to be missing when https://github.com/istio/istio/pull/28800 deleted it (see changes to webhook.go, permalink not working)
> inject network label on pods based on env value

- pilot/pkg/dns/dns_test.go
DNS resolve error could happen in UDP protocol with error:
=== RUN   TestDNS/udp-success:_non_k8s_host_not_in_local_cache
dns_test.go:221: Failed to resolve query for www.bing.com.: dns: overflowing header size
This change increases the UDP receive buffer size.
[ ] Docs
[ ] Networking
[ ] Security
> Fix flaky TestDNS case

- pilot/pkg/model/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_simulation_test.go
Duplicate HTTPS virtual services bound to a gateway will lead to envoy
rejections - "multiple filter chains with the same matching rules are defined".
This patch changes the current behavior of no duplication checking on such case
that will eventually fail with a NACK and instead picks only the first one of
the duplicated match rules.
Fixes https://github.com/istio/istio/issues/30321
[ ] Docs
[x] Networking
[ ] Security …
> gateway: skip duplicate VirtualService matches

- pilot/pkg/xds/eds_test.go
- pilot/pkg/xds/fake.go
Fixes https://github.com/istio/istio/issues/30364
The bug is in the test code - we create a new service, but we do not
wait for it to be propogated. Instead of adding retry loop, just make
sure the service is created before we start the test
[ ] Docs
[ ] Networking
[ ] Security
> Fix TestEDS flake

- pkg/test/framework/components/environment/kube/flags.go
- pkg/test/framework/components/environment/kube/settings.go
- pkg/test/framework/components/redis/redis.go
[ ] Docs
[ ] Networking
[ ] Security
> rename kubeconfigsFlag back to KubeConfig for istio.io tests (need public)

- pilot/cmd/pilot-agent/config/config.go
- pilot/cmd/pilot-agent/config/config_test.go
- pilot/cmd/pilot-agent/main.go
- pilot/cmd/pilot-agent/security/security.go
- security/pkg/nodeagent/caclient/credentials_test.go
Please provide a description for what this PR is for: 
Add tests for getting tokens for XDS
- Test case 1: xdsAuthProvider is google.GCPAuthProvider.
- Test case 2: xdsAuthProvider is empty.
- The tests need to call constructProxyConfig() and setupSecurityOptions() to
configure the options used by the token provider. Thus,
constructProxyConfig() and setupSecurityOptions() are refactored such
that they can be called in tests.
[ ] Docs
[ ] Networking
[X ] Security
> Add tests for getting tokens for XDS

- operator/cmd/mesh/install.go
- operator/cmd/mesh/install_test.go
- releasenotes/notes/26940.yaml
Fixes #27810
* reject empty revision
* test empty revision
* Fix duplicate test
* fix test build failures
* register gomega
* move test to unit, prerun
* releasenote
* validate revision as qualified name
* add copyright
* fix note format
* fmt
* remove duplicate import
* gofmt
* remove integ test
* remove install-revision label, as it isn't used.
* Fix spelling and formatting
* fix imports
[ ] Docs
[ ] Networking
[ ] Security
> Cherry Pick Prevent empty revision on install (#26959)

- pilot/cmd/pilot-agent/main.go
- pkg/istio-agent/agent.go
- pkg/istio-agent/xds_proxy.go
- pkg/security/security.go
Benefits of this PR:
* Can support any platform without needing to remember/change the path
* We don't log the 100s of lines of the system certs
Negatives:
* New magic SYSTEM value
* Old non xds-proxy is a bit hacky, but should work
(cherry picked from commit 69da35d43f954811bca20c4baf644f0e9303e2d5)
Fixes https://github.com/istio/istio/issues/30396
> Improve using system certs on CA/XDS (#28417)

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_test.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/security/authn/utils/utils.go
- pilot/pkg/security/authn/utils/utils_test.go
- pilot/pkg/security/authn/v1beta1/policy_applier_test.go
- pilot/pkg/security/model/authentication.go
- pilot/pkg/security/model/authentication_test.go
- pkg/bootstrap/option/convert.go
- pkg/bootstrap/option/convert_test.go
- pkg/bootstrap/option/instances_test.go
- pkg/bootstrap/testdata/all_golden.json
- pkg/bootstrap/testdata/auth_golden.json
- pkg/bootstrap/testdata/authsds_golden.json
- pkg/bootstrap/testdata/default_golden.json
- pkg/bootstrap/testdata/running_golden.json
- pkg/bootstrap/testdata/runningsds_golden.json
- pkg/bootstrap/testdata/stats_inclusion_golden.json
- pkg/bootstrap/testdata/tracing_datadog_golden.json
- pkg/bootstrap/testdata/tracing_lightstep_golden.json
- pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
- pkg/bootstrap/testdata/tracing_stackdriver_golden.json
- pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
- pkg/bootstrap/testdata/tracing_tls_golden.json
- pkg/bootstrap/testdata/tracing_zipkin_golden.json
- pkg/bootstrap/testdata/xdsproxy_golden.json
- tools/packaging/common/envoy_bootstrap.json
Fixes https://github.com/istio/istio/issues/30461
I think this should be in 1.9 because I am a bit worried about the upgrade implications of setting this on existing new proxies for in place upgrade. If we merge it in 1.9, this will never happen, as 1.8 proxies will be unchanged.
If we do not merge this here, I strongly recommend we change the proxy version check to be GE110 instead of GE19.
However, I do think we should merge here, as it results in 50% CPU usage in istiod.
> set node on first message only (#30390)

- manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
- manifests/charts/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml
- manifests/charts/istio-control/istio-discovery/values.yaml
- manifests/charts/istiod-remote/templates/istiod-injector-configmap.yaml
- manifests/charts/istiod-remote/values.yaml
- operator/cmd/mesh/manifest-generate_test.go
- operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/files/gen-istio.yaml
- operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml
- operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istio-control/istio-discovery/values.yaml
- operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/files/gen-istiod-remote.yaml
- operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/templates/istiod-injector-configmap.yaml
- operator/cmd/mesh/testdata/manifest-generate/data-snapshot/charts/istiod-remote/values.yaml
- operator/cmd/mesh/testdata/manifest-generate/input/sidecar_template.yaml
- operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
- operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
- operator/cmd/mesh/testdata/manifest-generate/output/sidecar_template.golden.yaml
- operator/pkg/apis/istio/v1alpha1/v1alpha1.pb.html
- operator/pkg/apis/istio/v1alpha1/values_types.pb.go
- operator/pkg/apis/istio/v1alpha1/values_types.proto
cherry-pick to fix https://github.com/istio/istio/issues/30402. Also update operator test snapshot and regenerate test golden files.
* Fix sidecar injector default template options.
* add a test for sidecar template
* add test files
* update data snapshot and gen golden file
[ ] Docs
[ ] Networking
[ ] Security
> [release-1.9] Fix sidecar injector default template config option. (#30353)

- pkg/test/framework/components/echo/kube/instance.go
- pkg/test/framework/components/opentelemetry/kube.go
- pkg/test/framework/components/prometheus/kube.go
- pkg/test/framework/components/zipkin/kube.go
- pkg/test/framework/config.go
- pkg/test/framework/resource/context.go
- tests/integration/pilot/common/traffic.go
- tests/integration/pilot/istioctl_test.go
- tests/integration/pilot/locality_test.go
- tests/integration/pilot/mirror_test.go
- tests/integration/pilot/multi_version_revision_test.go
- tests/integration/security/authorization_test.go
- tests/integration/security/ca_custom_root/secure_naming_test.go
- tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go
- tests/integration/security/ca_custom_root/trust_domain_validation_test.go
- tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
- tests/integration/security/file_mounted_certs/p2p_mtls_test.go
- tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go
- tests/integration/security/jwt_test.go
- tests/integration/security/mtls_healthcheck_test.go
- tests/integration/security/pass_through_filter_chain_test.go
- tests/integration/security/sds_egress/sds_istio_mutual_egress_test.go
- tests/integration/security/sds_tls_origination/egress_gateway_origination_test.go
- tests/integration/security/sds_tls_origination/util/util.go
- tests/integration/security/util/reachability/context.go
- tests/integration/telemetry/policy/envoy_ratelimit_test.go
- tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go
This is a superset of https://github.com/istio/istio/pull/30335 and  https://github.com/istio/istio/pull/30336, its slightly smaller if you review those first.
Currently, we have a few cases:
* Test apply YAML, forgets to cleanup
* Test apply YAML, and is force to add extra code to cleanup
* Test apply YAML, and is force to add extra code to cleanup *and* they cleanup wrong (inconsistent cleanup for --nocleanup and cleanup)
All of these are not great.
Instead, this changes the default behavior of ApplyYAML to always clean up. This makes it very hard to shoot yourself in the foot when writing a test, and cleans up the code.
For some use cases where cleanup is explicitly not desired (such as `echo` deployment), a new function to apply without cleanup is added
> Test framework: automatically clean up YAML applied by default

- pkg/test/framework/features/features.yaml
- tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
- tests/integration/telemetry/stats/prometheus/customizemetrics/testdata/attributegen_envoy_filter.yaml
- tests/integration/telemetry/stats/prometheus/stats.go
- tests/integration/telemetry/stats/prometheus/wasm/bad_wasm_filter_test.go
- tests/integration/telemetry/stats/prometheus/wasm/testdata/bad-filter.yaml
* Convert customize metrics to use remote load.
* lint
* feature label
* fix
* fix build
* fix
* make bad wasm remote load test single cluster
* fix
[ ] Docs
[ ] Networking
[ ] Security
> [release-1.9] Add integration tests for Wasm module remote load (#30241)

- istioctl/cmd/dashboard.go
- istioctl/cmd/dashboard_test.go
- releasenotes/notes/30208.yaml
To fix https://github.com/istio/istio/issues/30208
Before:
```
[istio-1.9.0-beta.1]$ k get po -n istio-system
NAME                                    READY   STATUS    RESTARTS   AGE
istio-ingressgateway-5787d6946b-jxfsg   1/1     Running   0          4m
istiod-56dd66799-jfdvs                  1/1     Running   0          5m
```
```
[istio-1.9.0-beta.1]$ ./bin/istioctl dashboard controlz istiod-56dd66799-jfdvs -n istio-system
Error: could not build port forwarder for ControlZ istiod-56dd66799-jfdvs: failed retrieving pod: pods "istiod-56dd66799-jfdvs" not found
```
After:
```
[istio-master] ./out/linux_amd64/istioctl dashboard controlz istiod-56dd66799-jfdvs -n istio-system
http://localhost:9876
```
> Fix dashboard controlz could not port forward to istiod pod

- pkg/test/framework/features/features.yaml
- tests/integration/security/external_ca/basic_reachability.go
- tests/integration/security/external_ca/main_test.go
Related to issue [#27418](https://github.com/istio/istio/issues/27606) - effort to promote feature from pre-alpha to beta
[ ] Docs
[ ] Networking
[X] Security
[] Test and Release
> External CA: Adding e2e integration tests to interoperate with external CA using K8s CSR API

- pkg/test/framework/features/features.yaml
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/gateway_topology/gw_topology_test.go
Add integration test for https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/
XFCC is already covered by the security integration tests
[ ] Docs
[ ] Networking
[ ] Security
> Add integration test for gateway topology using X-Forwarded-For

- security/pkg/nodeagent/cache/secretcache.go
Fixes https://github.com/istio/istio/issues/30119
Today, we send a CSR immediately at start up as a "warm up" to improve
latency and ensure we output a cert (for VMs, etc). However, if the CSR
is slower than Envoy's first SDS request, we will send another CSR. This
is wasteful and can lead to increased load on the CA.
Instead, we can just block until the initial request is done. This will
never block forever as the CSR call has a timeout already.
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does not have any changes that may …
> Prevent duplicate CSRs at startup

- tests/integration/security/external_ca/main_test.go
[ ] Docs
[ ] Networking
[X] Security
> fix post submit failures: security external ca ensure integration tests only run after K8s 1.18

- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/components/echo/kube/deployment_test.go
- pkg/test/framework/components/echo/kube/testdata/basic.yaml
- pkg/test/framework/components/echo/kube/testdata/healthcheck-rewrite.yaml
- pkg/test/framework/components/echo/kube/testdata/multiversion.yaml
- pkg/test/framework/components/echo/kube/testdata/secret.yaml
- pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml
v2 gives `map[interface{}]interface{}` and unstructured needs `map[string]interface{}` which is given by v3
actually tested this time
fixes #30455
> use correct yaml package to read image pull secret

- common/config/.golangci-format.yml
- go.mod
- go.sum
- pilot/pkg/networking/grpcgen/grpcgen.go
- pilot/pkg/networking/grpcgen/grpcgen_test.go
- pilot/pkg/networking/grpcgen/testdata/xds_bootstrap.json
- pilot/test/grpcgen/grpcinit.go
- pilot/test/mock/config.go
This PR updates the grpc-go to latest released version and removes the workarounds for v2.
[ ] Docs
[ ] Security
> update grpc go and remove v2 workarounds

- pilot/pkg/dns/dns.go
Example debian GCE VM:
```
$ cat /etc/resolv.conf
domain c.project-id.internal
search c.project-id.internal. google.internal.
nameserver 169.254.169.254
```
In our code, we were appending the search namespace a dot, so we get
`c.project-id.internal..` which doesn't match. As a result, if a VM and
Service had the same name, the VM took precedence unexpectedly.
[ ] Docs
[ ] Networking
[ ] Security
> Fix DNS search namespaces with existing trailing dot

- pkg/istio-agent/xds_proxy.go
xds_proxy logs the following warning for every 30 mins when istiod disconnects it
upstream terminated with unexpected error rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: NO_ERROR
That is not useful. This PR handles that case.
[ ] Docs
[ ] Security
> remove xds proxy periodic disconnect warning logs

- tests/integration/pilot/common/routing.go
- tests/integration/pilot/vm_test.go
The TODOs to enable these tests have been around a while, could have been enabled a while ago. 
- sniffing from VM to k8s
- VM os tests in multicluster mode
> enable previously disabled VM tests

- pkg/test/framework/components/istio/config.go
- pkg/test/framework/components/istio/operator.go
- tests/integration/security/ecc_signature_algorithm/main_test.go
The comment on RemoteClusterValues is:
```
// Default value will be ControlPlaneValues if no remote values provided
```
But at some point it seems that defaulting was removed. This brings it back. fixes #30592 and fixes #30587
> fix defaulting remote cluster values

- istioctl/pkg/multicluster/remote_secret.go
- istioctl/pkg/multicluster/remote_secret_test.go
In certain managed Kubernetes environments, there may be multiple secrets linked to a newly created ServiceAccount by default (i.e. RedHat OpenShift on IBM Cloud). Following the instructions covered [here](https://istio.io/latest/docs/setup/additional-setup/external-controlplane/#set-up-the-control-plane-in-the-external-cluster) in these environments will fail currently with the following error:
```
❯ istioctl x create-remote-secret \
--context="${CTX_REMOTE_CLUSTER}" \
--type=config \
--namespace=external-istiod
error: could not get access token to read resources from local kube-apiserver: wrong number of secrets (2) in serviceaccount external-istiod/istiod-service-account
```
`istioctl x create-remote-secret` command is currently restricted in a way that it cannot succeed if there are …
> Introduce remote secret name parameter for "istioctl x create-remote-secret"

- pilot/pkg/security/authn/utils/utils.go
- pilot/pkg/security/authn/utils/utils_test.go
- pilot/pkg/security/authn/v1beta1/policy_applier_test.go
- releasenotes/notes/tls-inbound-all-protocols.yaml
Currently, its accidentally inside the "if protocol == HTTP" clause. I
am pretty sure its intended to be outside of it, so it applies to all
protocol types.
> Fix inbound TLS v2 settings

- pkg/test/framework/components/echo/echoboot/echoboot.go
Tests creating echo configs with `DeployAsVM` should not have to guard the `With` call with the flag check.
> dont attempt vm deployments in skipVM mode

- istioctl/pkg/verifier/verifier.go
To fix https://github.com/istio/istio/issues/30612
Before:
```
[istio-1.9.0-rc.0]$ istioctl verify-install
1 Istio control planes detected, checking --revision "" only
✔ ClusterRole: istiod-istio-system.istio-system checked successfully
✔ ClusterRole: istio-reader-istio-system.istio-system checked successfully
```
After:
```
[istio-master]$ ./out/linux_amd64/istioctl verify-install
1 Istio control planes detected, checking --revision "default" only
✔ HorizontalPodAutoscaler: istio-ingressgateway.istio-system checked successfully
✔ Deployment: istio-ingressgateway.istio-system checked successfully
```
```
[istio-master]$ istioctl install -r 1-10-0
[istio-master]$ ./out/linux_amd64/istioctl verify-install
1 Istio control planes detected, checking --revision "1-10-0" only
✔ ClusterRole: …
```
> istioctl verify-install: fix empty revision

- istioctl/cmd/tag.go
- istioctl/cmd/tag_test.go
Fixes `istioctl x tag` command on k8s 1.15
[ ] Docs
[ ] Networking
[ ] Security
> [istioctl] use admit v1beta1 rather than admit v1 in revision tag command

- pilot/pkg/networking/core/v1alpha3/cluster.go
- releasenotes/notes/30181.yaml
- tests/integration/pilot/locality_test.go
cherry-pick #30602
fix: #30648
> [release-1.9] set MaxEjectionTime to BaseEjectionTime if it is greater than 300s 

- pilot/pkg/config/memory/config.go
The validation operation still works in `Update`、`UpdateStatus` and `Patch` method of ConfigStore even if we specify `skipValidation` as true.
[ ] Docs
[ ] Networking
[ ] Security
> Fix missing skip validation

- pilot/pkg/dns/dns.go
- releasenotes/notes/dns-localhost-loop.yaml
- tests/integration/pilot/common/routing.go
- tools/istio-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/cmd/run.go
- tools/istio-iptables/pkg/cmd/run_test.go
- tools/istio-iptables/pkg/config/config.go
Fixes https://github.com/istio/istio/issues/30309
This changes the interception to only apply to servers that are listed
in /etc/resolv.conf. This ensures that we allow the requests from the
local DNS proxy to be forwarded as is. Note its hypothetically possible
for the DNS proxy to be configured to send to something that is also in the
nameserver list but I doubt its very common, and I don't know how to
work around that
Hold until additional manual testing is done:
> Fix DNS loop when there is a local DNS proxy

- pkg/test/framework/components/echo/common/config.go
- pkg/test/framework/components/echo/echoboot/echoboot.go
- pkg/test/framework/components/echo/instances.go
- pkg/test/framework/components/echo/kube/deployment_test.go
- pkg/test/framework/components/echo/kube/instance.go
- tests/integration/security/util/reachability/context.go
- FillInDefaults needs to be the same for all echo configs, that way the Ports match no batter which cluster. 
- Since the VM is not in the same "cluster" as the pods, we shouldn't filter it out in security tests 
- leaving the "is primary" match for now
> allow security tests to run against real VMs

- pkg/test/framework/components/cluster/cluster.go
- pkg/test/framework/components/cluster/clusterboot/factory_test.go
- pkg/test/framework/components/cluster/topology.go
- tests/integration/multicluster/cluster_local.go
- tests/integration/multicluster/helper.go
- tests/integration/multicluster/loadbalancing.go
- tests/integration/multicluster/telemetry.go
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/mirror_test.go
- tests/integration/security/authorization_test.go
- tests/integration/security/ca_custom_root/secure_naming_test.go
- tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go
- tests/integration/security/external_ca/basic_reachability.go
- tests/integration/security/jwt_test.go
- tests/integration/security/pass_through_filter_chain_test.go
- tests/integration/security/util/reachability/context.go
- tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go
- tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
- tests/integration/telemetry/tracing/opencensusagent/tracing_test.go
- tests/integration/telemetry/tracing/tracing.go
- tests/integration/telemetry/tracing/zipkin/clienttracing/client_tracing_test.go
- tests/integration/telemetry/tracing/zipkin/servertracing/tracing_test.go
If the underlying cluster names given to the test framework are dynamic (for example, using a pool of non-kind Kubernetes clusters), test grid won't be able to see that certain tests are actually the same since we include the cluster name in the test/subtest names. 
We generate the name using a combination of: 
- the order in which the cluster was added (for uniqueness)
- whether the cluster is a primary, remote, remoteconfig or externalistiod cluster
- if it is a non-kube cluster, simply use the cluster's Kind
examples:
- StaticVM-0
- primary-1
- remote-2
- primary-2
Unfortunately this prevents having very descriptive names like `cross-network-primary`. The network name may also be dynamic. We will log the real name next to the stable name in the "Built cluster" log message.
> use a deterministic cluster name for subtests

- tools/istio-clean-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/cmd/root.go
The `dry-run` flag is bound in init() across both `istio-iptables` and
`istio-clean-iptables` subcommands and will be overwritten by the last due to
https://github.com/spf13/viper/issues/233. This makes the cleaning up dry run
using e.g. `pilot-agent istio-clean-iptables --dry-run/-n` broken.
Binding the flag to Viper and defaulting it at the last possible moment by
moving it to the `PreRun` hook phase as part of the command execution.
[ ] Docs
[x] Networking
[ ] Security
[ ] …
> tools/istio-iptables: allow `dry-run` flag to be used across commands

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
This caused a bug in 1.8: https://github.com/istio/istio/pull/30443.
Today, the function does not actually end up mattering much, since we
only support 1.9 proxies in 1.10 (master) istiod. however, it will avoid
future bugs that assume proxy is non-nil.
additionally, copy the additional testing that was added in the original
PR. The tests pass before and after this change, which is expected as
this should have no impact
[ ] Docs
[ ] Networking
[ ] Security
> Properly pass proxy to inbound sidecar creation

- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
- pilot/pkg/networking/util/util.go
We have had some users that are complaining about the backwards
incompatible changes in 1.8 to the cluster name format. Technically, the
cluster name is an implementation detail for most users. However, some
users are using envoy native telemetry, which includes the cluster name.
The intent of this change is to give users some time to adopt Istio 1.8
first, *then* deal with the migration to the new cluster format.
Currently, the two are coupled so its hard to accomplish this.
Essentially, this makes the condition of the old cluster format to apply
to all proxy versions below 1.8, OR if the new option is set.
The same tests that are testing the 1.7 proxies apply here, so they are
copied and give the same coverage.
[ ] Docs
[ ] Networking
[ …
> Add option to enable legacy cluster name

- tests/integration/operator/install_test.go
add one integration test to make sure label map is initialized before hand.
> add one integration case to check nil label map for iop

- releasenotes/README.md
- releasenotes/notes/reliable-wasm-remote-load.yaml
Corresponding to https://github.com/istio/tools/pull/1445 which adds extensibility to release notes template.
> Fix Wasm reliable remote load release notes.

- tools/istio-clean-iptables/pkg/cmd/cleanup.go
- tools/istio-clean-iptables/pkg/cmd/root.go
- tools/istio-clean-iptables/pkg/config/config.go
- tools/istio-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/cmd/run.go
- tools/istio-iptables/pkg/cmd/run_test.go
This patch adds the support of cleaning up all DNS UDP rules in iptables tools,
by reusing the same logic on creation. This helps prevent them from being out
of sync. 
To allow multiple flags with the same name to be used across different
subcommands, this patch also moves all viper mutation and binding to `PreRun`
as part of the command execution so that no overwritten will take place.
Fixes https://github.com/istio/istio/issues/30674
[ ] Docs
[x] Networking
[ ] Security
[ ] …
> tools/istio-clean-iptables: clean up all DNS UDP rules

- istioctl/cmd/revision.go
Before this would panic when running `istioctl x revisions describe` without arguments since we were getting `args[0]` before checking length
[ ] Docs
[ ] Networking
[ ] Security
> [istioctl] fix panic in revision command without args

- pkg/test/util/retry/retry.go
* Record number of attempts. This helps show if we actually attempted
many times and it failed, or we just tried 1x but it was really slow
* Make timeout more reliable by pre-empting the Delay if the timeout
occurs during the delay.
[ ] Docs
[ ] Networking
[ ] Security
> Improve retry timeouts

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go
- releasenotes/notes/inbound-patch.yaml
After we renamed the inbound clusters not to have host name in it, the service match stopped working because we are trying to get host name from cluster name which is not available. This PR fixes that.
[ ] Docs
[ ] Security
> fix envoy filter service match for inbound clusters

- tests/integration/telemetry/stats/prometheus/stats.go
it's possible this could fix the flakes we see
> fix stats filter test: shadow var for goroutine

- pilot/pkg/security/authz/builder/extauthz.go
- pilot/pkg/security/authz/builder/testdata/action-custom-HTTP-for-TCP-filter-out2.yaml
- pilot/pkg/security/authz/builder/testdata/action-custom-grpc-provider-out2.yaml
This match the same timeout we had set for HTTP.
[ ] Docs
[ ] Networking
[x] Security
> ext-authz: fix to set the proper timeout for gRPC case

- pkg/envoy/proxy.go
When JSON is enabled, we log the scope directly. But with normal logs,
we prefix it with "envoy".
This makes the JSON log consistent.
[ ] Docs
[ ] Networking
[ ] Security
> Use consistent scope name in envoy json logs

- tests/integration/telemetry/tracing/opencensusagent/tracing_test.go
- tests/integration/telemetry/tracing/zipkin/clienttracing/client_tracing_test.go
- tests/integration/telemetry/tracing/zipkin/servertracing/tracing_test.go
we skipped some tests by hardcoding cluster name checks: https://github.com/istio/istio/issues/28890 
this should skip them properly, but we should see if the actual fix is possible to backport
> broken tracing test checks networks instead of hardcoded name

- pkg/test/framework/resource/flags.go
- pkg/test/framework/resource/matcher.go
- pkg/test/framework/resource/matcher_test.go
- pkg/test/framework/resource/settings.go
Otherwise its impossible to skip subtests sanely.
Instead of `--skip'TestFoo|TestBar'` we can do `--skip 'TestFoo' --skip 'TestBar/subtest'` and not skip the entire TestBar.
This is not possible with the current regex match
[ ] Docs
[ ] Networking
[ ] Security
> Allow multiple istio.test.skips

- tools/istio-docker.mk
It was just making the folder readable - we need the whole folder. This
is just testing certs, so we don't care about security here to need
strict isolation
[ ] Docs
[ ] Networking
[ ] Security
> Properly chown certs in docker build

- pilot/pkg/xds/debug.go
If response.WriteHeader is not called explicitly, the first call to
response.Write will trigger an implicit WriteHeader(http.StatusOK).
A WriteHeader is implicitly triggered in the index template execution for debug
endpoints. The explicit call at the end of `/debug` handler is redundant and can
thus be removed.
The status code is checked in `TestDebugHandlers` unit test.
Fixes https://github.com/istio/istio/issues/30785
[ ] Docs
[x] Networking
[ ] Security
[ ] Does not have …
> pilot-discovery: remove superfluous response.WriteHeader call in debug

- pilot/pkg/xds/ads.go
Currently, if we have an error in Recv before initialization completes,
we may hang forever, since we have `<-con.initialized` that blocks. This
fixes this by closing the initialized channel when recieve exits.
[ ] Docs
[ ] Networking
[ ] Security
> Fix ADS stream hanging on errors

- pkg/test/framework/components/namespace/kube.go
When running TestValidation with stable namespaces enabled:
1. both tests read the NS, see it doesn't exist
2. since it doesn't exist they both try to create it
3. one will succeed and one with fail out
This PR lets the failing one succeed if the error was due to the create succeeding on another thread.
> allow stable namespaces to be created/claimed in parallel

- go.mod
This will ensure if a build fails, users are notified that the build
requires 1.16. It does not actually make 1.16 *required*, although we
will make that requirement soon.
[ ] Docs
[ ] Networking
[ ] Security
> Update go.mod version

- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/kube/controller/endpoints.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
It looks like the endpoints controller was going to the trouble of
detecting tombstones and retrieving the object, but then passing the
unconverted interface object to the handler, which would then panic.
[ ] Docs
[ ] Networking
[ ] Security
> Fix tombstone handling in endpoints controller

- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/kube/controller/fake.go
- pilot/pkg/serviceregistry/kube/controller/filter/discoverynamespaces.go
Fixes #30877
The flake was caused by a race between the discovery namespace event handlers and the assertion of the registry's services. Specifically, [the creation of the test namespaces](https://github.com/istio/istio/blob/d706ab80df4b1742b299b6c38bf80cb967697efc/pilot/pkg/serviceregistry/kube/controller/controller_test.go#L1125-L1127) triggers [this discovery namespace event handler](https://github.com/istio/istio/blob/d706ab80df4b1742b299b6c38bf80cb967697efc/pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go#L53), which is required for [this assertion](https://github.com/istio/istio/blob/d706ab80df4b1742b299b6c38bf80cb967697efc/pilot/pkg/serviceregistry/kube/controller/controller_test.go#L1171) to pass. On failed runs, debug logs show that the namespace events have not …
> Fix flake in TestController_ServiceWithChangingDiscoveryNamespaces

- cni/cmd/istio-cni/iptables.go
- cni/cmd/istio-cni/main.go
- cni/pkg/taint/taint.go
- cni/pkg/taint/taintcontroller.go
- istioctl/pkg/validate/validate.go
- pilot/pkg/networking/apigen/apigen.go
- pilot/pkg/networking/grpcgen/grpcgen.go
- pilot/pkg/security/authz/model/generator.go
- pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
- pkg/config/event/router.go
- pkg/config/resource/serialization_test.go
- pkg/config/schema/schema_test.go
- pkg/kube/inject/webhook.go
- pkg/kube/mock_client.go
- pkg/test/echo/server/forwarder/dns.go
- tools/bug-report/pkg/bugreport/bugreport.go
- tools/istio-iptables/pkg/dependencies/implementation.go
- tools/istio-iptables/pkg/dependencies/stub.go
This is a forward compatible changes that makes our code pass the new
linter, so we can upgrade
[ ] Docs
[ ] Networking
[ ] Security
> Update formatting to be compatible with golangci-lint 1.37.0

- pilot/pkg/xds/v3/model.go
- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_test.go
This PR does the following
- Move rewriteAndForward to a go routine for every ECDS update so that does not depend on channels. Might scale better
- Validates typeURL before forwarding to Envoy
[ ] Docs
[ ] Networking
[ ] Security
> minor xds proxy cleanup

- tests/integration/pilot/main_test.go
This fixes a regression from a previous PR. We should not cleanup the
CRD, as it leaves Istio in a semi-broken state and may break existing
clusters. This should be treated at the same level as istio deployment
and not be removed with --nocleanup
[ ] Docs
[ ] Networking
[ ] Security
> Do not cleanup service-apis CRD

- pilot/pkg/security/authz/builder/builder.go
- pilot/pkg/security/authz/builder/extauthz.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
Fixes #30824 
If some extension provider is not used by any authz policy, it should not cause errors even if it might be invalid.
[ ] Docs
[ ] Networking
[x] Security
> ext-authz: return error for invalid extension provider only when it is being used

- pkg/test/framework/components/echo/util/traffic/generator.go
- pkg/test/framework/components/echo/util/traffic/result.go
- tests/integration/pilot/revisioned_upgrade_test.go
This makes it easy to write long-running traffic generation tests.
Also re-working the revisioned upgrade test to use it.
[ ] Docs
[ ] Networking
[ ] Security
> [Test Framework] Adding traffic generation utility

- tests/integration/security/ca_custom_root/trust_domain_validation_test.go
allows testgrid from exploding when we have dynamic cluster names
> use StableName in trust domain subtest

- pilot/pkg/bootstrap/server.go
- pilot/pkg/trustbundle/trustbundle.go
- pilot/pkg/trustbundle/trustbundle_test.go
Adding code to accumulate all the configured and implicit trust anchors of the mesh in one location.
Part of a larger commit - https://github.com/istio/istio/pull/30506. Splitting the PR into multiple parts.
Also related to commit - https://github.com/istio/api/pull/1848
Refer to [RFC](https://docs.google.com/document/d/1EFMQZNlyImLP0k0HIyoBINntchqeUq7QQgc9O_jDwZ8/edit#heading=h.io2z16q0yjxj)
[ ] Docs
[ ] Networking
[X] Security
> Adding TrustBundle package + Integration Hooks into Istiod

- pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
- pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
- security/pkg/nodeagent/cache/secretcache.go
Currently we already store services of service entry's that have wortload selectors. This PR stores all services (pointing to the same services in workload selector and additional services as well) to avoid reconversion when Services() and GetService() is called.
[ ] Docs
[ ] Security
> build converted service cache in service entry store

- pilot/pkg/model/push_context.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/gen.go
Currently, both a request from envoy and a push due to update logs
`PUSH ...`. This makes it hard to tell *why* we pushed.
This makes it so that pushes in response to requests add `PUSH for
request`.
Example:
```
2021-02-19T23:51:41.555516Z     info    ads     ADS: new connection for node:sidecar~10.0.0.14~.~.svc.cluster.local-1
2021-02-19T23:51:41.556925Z     info    ads     CDS: PUSH for request for node:. resources:21 size:13.4kB
2021-02-19T23:51:41.564607Z     info    ads     EDS: PUSH for request for node:. resources:17 size:3.2kB empty:7 cached:0/17
2021-02-19T23:51:41.610006Z     info    ads     LDS: PUSH for request for node:. resources:18 size:56.2kB
2021-02-19T23:51:41.629489Z     info    ads     RDS: PUSH for request for node:. resources:8 size:5.3kB
2021-02-19T23:51:46.942349Z …
```
> Add logging to distinguish pushes from requests

- security/pkg/nodeagent/cache/secretcache.go
This PR retries file watcher errors so that it helps to recover from transient errors.
[ ] Docs
[X ] Security
> retry file watcher errors

- pkg/kube/inject/inject.go
- pkg/kube/inject/inject_test.go
Since the traversal order of the map is unstable, the order of env after injection is unstable, resulting in different results of injecting the same Pod.
[ ] Docs
[ ] Networking
[ ] Security
> Fix the order of environment variables for injection

- pkg/test/echo/server/forwarder/protocol.go
Setting `HTTP_PROXY` or `HTTPS_PROXY` will allow the test runner to use the proxy on requests via ingress. gRPC lib should handle these already, so ForwardEcho calls should work.
> support http proxy from an echo forwarder

- istioctl/pkg/multicluster/remote_secret.go
- istioctl/pkg/multicluster/remote_secret_test.go
- releasenotes/notes/30723.yaml
Currently, when there are multiple secrets in the remote service account and the user specifies a non-existing one, it is silently ignored and the first secret is picked up.
This change adds an appropriate error message when this happens.
This is a follow up PR for: https://github.com/istio/istio/pull/30565
[ ] Docs
[ ] Networking
[ ] Security
> Catch user input error on remote secret creation.

- pilot/pkg/features/pilot.go
- pilot/pkg/model/validation.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/inbound-passthrough.yaml
- tests/integration/pilot/common/routing.go
This implements the design in https://docs.google.com/document/d/1j-5_XpeMTnT9mV_8dbSOeU7rfH-5YNtN_JJFZ2mmQ_w/edit#.
Tl;dr: change inbound cluster from `STATIC` to `ORIGINAL_DST`.
This is intended to be disabled by default in Istio 1.10 most likely. For review/testing, I have it enabled. I will swap it before merge.
Fixes https://github.com/istio/istio/issues/29940
> Switch inbound clusters to ORIGINAL_DST

- pilot/pkg/xds/debug.go
- releasenotes/notes/31075.yaml
Currently /adsz interface provides the list of clients along with watches. But it takes a lot of time to load and this is a quick way to get the current connections list
[ ] Docs
[ ] Security
> add connections debug interface

- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
- pilot/pkg/networking/core/v1alpha3/tls.go
TLS statefulsets/headless services with generated listeners bound to specific
endpoint addresses (defaultly enabled by `PILOT_ENABLE_HEADLESS_SERVICE_POD_LISTENERS`)
should not add unnecessary `sniHosts` into TLS matches. The impact is you MUST
call `curl https://svc.ns.svc.cluster.local` and not short names like
`curl https://svc.ns`.
Fixes https://github.com/istio/istio/issues/27677
[ ] Docs
[x] Networking
[ ] Security
[x] Does not have any changes that may affect Istio …
> pilot: fix TLS headless service requiring unnecessary SNI host

- galley/pkg/config/analysis/analyzers/all.go
- galley/pkg/config/analysis/analyzers/analyzers_test.go
- galley/pkg/config/analysis/analyzers/testdata/webhook.yaml
- galley/pkg/config/analysis/analyzers/webhook/webhook.go
- galley/pkg/config/analysis/msg/messages.gen.go
- galley/pkg/config/analysis/msg/messages.yaml
- galley/pkg/config/source/kube/rt/known.go
- pkg/config/schema/collections/collections.gen.go
- pkg/config/schema/gvk/resources.gen.go
- pkg/config/schema/metadata.gen.go
- pkg/config/schema/metadata.yaml
- releasenotes/notes/webhook-analyzer.yaml
- tests/integration/pilot/validation_test.go
This adds an analyzer for mutating webhooks. This checks 2 things:
* referenced Services exist. This is important if someone partially deletes a revision or otherwise misconfigures the webhooks
* Webhooks do not overlap. This could occur if someone set things up incorrectly (setting multiple revisions as "auto inject", etc)
There is a lot of extra stuff to add reading webhooks to the analyzer; today it doesn't read them at all.
> Add analyzer for webhook issues

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/networking/util/util_test.go
Metadata creation is massive contributor to pilot CPU utilization.
Currently, building the metadata takes ~15% of pilot CPU. An extra ~10%
is also hidden in MarshalToAny, as marshalling it is super slow as well.
A big chunk of this is in AddSubsetToMetadata. This does a proto.Clone
on the existing metadata. This is pretty wasteful, as we are already
creating a full copy of the metadata when we build the cluster.
Instead of a full copy, we can just insert the subset metadata (along
with the initial DR meta).
Results are 20% improvement in CPU.
```
name                     old time/op        new time/op        delta
ClusterGeneration/tls-6        26.7ms ± 2%        21.3ms ± 1%  -20.26%  (p=0.000 n=9+9)
name                     old kb/msg         new kb/msg         delta …
```
> Optimize cluster metadata creation

- pilot/pkg/serviceregistry/aggregate/controller.go
Previously, returning slice could conflict with dynamic update.
> Fix GetRegistries race

- pilot/pkg/model/context.go
- pilot/pkg/model/sidecar.go
- pilot/pkg/xds/ads_common.go
- pilot/pkg/xds/ads_common_test.go
- pilot/pkg/xds/ads_test.go
- releasenotes/notes/scope-push-by-sidecar-changes.yaml
[ ] Docs
[ * ] Networking
[ ] Security
I think we can consider Sidecar as `sidecarScopeKnownConfigTypes` rather than `clusterScopedConfigTypes`. And then only full-push raised by relevant Sidecar changes will be performed towards our proxies.
We can add the `kind+name+ns` of Sidecar config itself to `configDependencies` while `ConvertToSidecarScope`.
> Scope full push raised by Sidecar config changes

- istioctl/pkg/clioptions/control_plane.go
- istioctl/pkg/install/verify.go
Before:
```
$ istioctl verify-install -r 1-10-0
Error: unknown shorthand flag: 'r' in -r
```
After:
```
$ istioctl verify-install -r 1-10-0
✔ ClusterRole: istiod-istio-system.istio-system checked successfully
✔ ClusterRole: istio-reader-istio-system.istio-system checked successfully
...
Checked 12 custom resource definitions
Checked 2 Istio Deployments
✔ Istio is installed and verified successfully
```
> istioctl verify-install: add revision shortcut

- istioctl/cmd/proxyconfig.go
- istioctl/pkg/writer/envoy/configdump/configdump.go
- istioctl/pkg/writer/envoy/configdump/route.go
- releasenotes/notes/istioctl-pc-all.yaml
Fixes https://github.com/istio/istio/issues/28191
Open questions:
* Should we support filters? The behavior is a bit awkward
* Should we instead have kubectl semantics? ie we can do `pc all`, `pc
cluster`, or `pc cluster,listener,secret`. One downside is because these
would not be subcommands we would not have per-command filter flags, so
we have the same awkward flag support as we have here
[ ] Docs
[ ] Networking
[ ] Security
> Add istioctl proxy-config all

- istioctl/cmd/root.go
- istioctl/pkg/validate/validate.go
- istioctl/pkg/validate/validate_test.go
Resolves https://github.com/istio/istio/issues/31107
`istioctl validate -f <file>` did not set the namespace of CRs before validating them.  (This isn't a problem for the webhook, as `kubectl apply` sets the namespace from the current context before sending the CRs for validation.)
The implementation sets namespace to the value of the _istioctl_ `--namespace <ns>` if provided.  Note: If not, it uses `default`.  (_istioctl_ doesn't try to get the context namespace out of the $KUBECONFIG).
> Default namespace before 'istioctl validate'

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_test.go
For original DST cluster, we already handle it in applyTrafficPolicy. This is not needed now
[ ] Docs
[ ] Security
> remove unnecessary setting for original dst

- galley/testdatasets/validation/dataset.gen.go
- galley/testdatasets/validation/dataset/networking-v1alpha3-EnvoyFilter-invalid.yaml
- tests/integration/telemetry/policy/testdata/enable_envoy_local_ratelimit.yaml
- tests/integration/telemetry/policy/testdata/enable_envoy_local_ratelimit_per_route.yaml
Pre-emptive for https://github.com/istio/istio/pull/31126, which will
make validation detection better. This fixes an "invalid" config that
was not invalid, and makes an invalid config valid
[ ] Docs
[ ] Networking
[ ] Security
> Fix validation

- pilot/pkg/model/push_context.go
Before: `EDS: PUSHfor request for node...`
After: `EDS: PUSH request for node...
[ ] Docs
[ ] Networking
[ ] Security
> Fix spacing on ADS request log

- pkg/istio-agent/health/health_check.go
- pkg/istio-agent/health/health_check_test.go
when initial health check is failure, we will never send the event out.    This PR will fix the problem.
> fix health check logic when initial check is failure

- pilot/pkg/features/pilot.go
- pilot/pkg/security/authn/utils/utils.go
- pilot/pkg/security/authn/utils/utils_test.go
This has been there for couple of releases and no one complained. Moreover we now have a way to override with Envoy filters if needed. So removing this.
[ ] Docs
[ ] Networking
[ ] Security
> remove tlsv2 env var

- istioctl/cmd/proxyconfig.go
Minor fix for duplicate alias added in https://github.com/istio/istio/pull/30934
Before:
```
$ istioctl pc all
Usage:
istioctl proxy-config all [<type>/]<name>[.<namespace>] [flags]
Aliases:
all, all, a
```
> istioctl pc all: remove duplicate alias

- istioctl/cmd/analyze.go
To fix https://github.com/istio/istio/issues/30804
Before:
```
$ istioctl analyze -n bookinfo
✔ No validation issues found when analyzing namespace: bookinfo.
```
After:
```
$ istioctl analyze -n bookinfo
namespace "bookinfo" not found
```
> istioctl analyze: skip if namespace does not exists

- istioctl/cmd/analyze.go
To fix https://github.com/istio/istio/issues/30865
Before:
```
$ istioctl analyze samples/bookinfo/platform/kube/
✔ No validation issues found when analyzing namespace: default.
```
After:
When filename is provided
```
$ istioctl analyze samples/bookinfo/platform/kube/bookinfo-ingress.yaml
✔ No validation issues found when analyzing samples/bookinfo/platform/kube/bookinfo-ingress.yaml.
```
> istioctl analyze: display dir or file name when it is provided

- pkg/test/framework/components/echo/kube/instance.go
This fixes a panic that will occur if echo creation fails before the workload manager is created.
[ ] Docs
[ ] Networking
[ ] Security
> [Test Framework] Fix panic if echo creation fails

- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
Warn during validation and ignore the address for dns resolution serviceentry .
Fix: #30771
[ ] Docs
[ ] Networking
[ ] Security
> Warn service entry which has more than one host specified  simultaneously with address and https port

- pkg/bootstrap/platform/azure.go
- pkg/bootstrap/platform/azure_test.go
- releasenotes/notes/azureTags.yaml
As reported in https://github.com/istio/istio/issues/31176, there are situations in which the platform metadata for Azure can lead to Envoy crashes. This PR attempts to improve the handling so as to remove the crashes.
Note: I have no way of verifying behavior on Azure.
Fixes: https://github.com/istio/istio/issues/31176
> fix(azure bootstrap): handle tags with semicolons or without values

- istioctl/cmd/tag.go
- istioctl/cmd/tag_test.go
Allows dumping revision tag mutating webhook YAML to stdout with `istioctl tag generate prod --revision 1-8-3`, analogous to `istioctl manifest generate`.
[ ] Docs
[ ] Networking
[ ] Security
> [istioctl] Add generate subcommand and webhookName option to revision tag command

- pilot/pkg/config/kube/crdclient/client.go
- pilot/pkg/config/kube/crdclient/metrics.go
- pilot/pkg/features/pilot.go
This feature flag is not needed now as validating webhook is part of Istiod it self and can be enabled if CRD validation is needed.
[ ] Docs
[ ] Security
> cleanup enable crd validation feature flag

- pilot/pkg/features/pilot.go
- pilot/pkg/model/xds_cache.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/endpoint_builder.go
- pilot/pkg/xds/sds.go
- pilot/pkg/xds/xds_cache_test.go
- pkg/test/kube/dump.go
- tests/integration/pilot/ingress_test.go
This adds assertions that will panic at runtime to pilot. These will be
used only for development and are intended to never be enabled in
production clusters.
The first usage of this, implemented in this PR, is to ensure that our
cache eviction works properly. This is done by disabling the cache when
assertions are enabled, and ensuring all updates are NOP changes.
Motivations:
* Recently had a cache eviction bug that may have been caught by this
* I am hoping to add more caching soon, which I would look to test using
this
* For the Delta XDS work, we need to add logic to detect if a resource
change will impact XDS. This is a perfect usage to test, as we can
assert that our detection logic matches the actual XDS change.
* This found a bunch of bugs in this PR already
In addition, this …
> Add runtime assertions to Pilot

- Makefile.core.mk
- tools/build-base-images.sh
- tools/buildx-gen.sh
- tools/istio-docker.mk
The prior PR iterated over the comma separated hubs, and built and pushed each set of images. This could result in different images across the hubs.
This PR will build and push the first HUBs images, and for successive Hubs, retag the images using the new HUB and then push. This will result in matching images across the HUBs.
> Update build_base_images to only build one image, tag push others,

- pkg/kube/util.go
- pkg/test/kube/util.go
When running multiple suites with `--istio.test.stableNamespace` where each suite shares a namespace prefix (e.g. `echo`) and deployment names (e.g. `client` and `server`), echo's deployer will see Pods that are currently Ready but in a Terminating state and stop waiting for the new echo pods to be ready.
In master this is fixed with #30675 but we don't have an equiv in 1.9.
> [release-1.9] wait for pod deletion before echo is ready

- pilot/pkg/dns/dns.go
- pilot/pkg/dns/dns_test.go
Fixes https://github.com/istio/istio/issues/30131 by not requiring real
upstream (bing.com) and instead our own local DNS server. This still
exercises the same codepaths.
Fixes https://github.com/istio/istio/issues/29675 by ensuring we
properly truncate+compress messages.
Fixes https://github.com/istio/istio/issues/31250 by ensuring we do not
send NXDOMAIN when we find a host but don't have matching IP version.
[ ] Docs
[ ] Networking
[ ] Security
> dns: fix various issues with dns proxy

- pilot/pkg/dns/dns.go
- pilot/pkg/dns/dns_test.go
- pilot/pkg/networking/core/v1alpha3/name_table.go
- releasenotes/notes/dns-round-robin.yaml
* Load balance statefulset DNS response (#31067)
* dns: fix various issues with dns proxy (#31251)
The latter is basically a superset of the first one, just cherrypicked both so they cleanly apply
> Backport DNS fixes to 1.9

- pkg/test/framework/testcontext.go
Currently, we only dump in CIMode in another place. Sothis makes it
consistent. I thought about making it always dump, but this seems better
since usually local devs don't care about the dump and it just slows
things down.
[ ] Docs
[ ] Networking
[ ] Security
> Consistently only dump in CIMode

- pilot/pkg/networking/core/v1alpha3/serviceentry_simulation_test.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/networking/util/util_test.go
Partially solves https://github.com/istio/istio/issues/29197. The specific case laid out there has CIDRs that have a different prefix, but the prefix length only includes equal parts.
This will make sure we accurately detect conflicting filter chains.
> lds: cidr equality only checks significant bits

- tools/build-base-images.sh
For testing purposes, allow a user to specify DOCKER_TARGETS, else use the current as the default.
> Allow DOCKER_TARGETS as existing env var for build-base-images.sh

- istioctl/pkg/multicluster/remote_secret.go
Followup for https://github.com/istio/istio/pull/31290
> Fix missing server name for create-remote-secret warning

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- releasenotes/notes/api-server-cluster-local.yaml
[ ] Docs
[x] Networking
[ ] Security
> Make kubernetes.default.svc cluster-local by default.

- pkg/envoy/proxy.go
- pkg/envoy/proxy_test.go
Part of https://github.com/istio/istio/issues/31138
This is generally to simplify running multiple Envoy's on one pod. It
may have the side effect of reducing the work Envoy needs to do by
disablnig hot restart. It also drops privileges required by Envoy (write
access to /dev/shm).
We don't use hot restart today. A user with custom fork might, in which
case they can either comment these two lines out or send a PR upstream
to make this opt-in. Until then, I think we can just hard disable it as
I believe no users are using this without a fork.
[ ] Docs
[ ] Networking
[ ] Security
Please …
> Disable envoy hot restart

- pkg/test/echo/client/client.go
- pkg/test/echo/client/parsedresponse.go
- pkg/test/framework/components/echo/common/call.go
- tests/integration/pilot/cni/cni_test.go
- tests/integration/security/mtls_first_party_jwt/strict_test.go
- tests/integration/security/mtlsk8sca/strict_test.go
- tests/integration/security/reachability_test.go
- tests/integration/security/util/connection/checker.go
- tests/integration/security/util/reachability/context.go
Currently, our tests check only if traffic succeeds or fails. That is great, but it still leaves a lot of coverage missing. For example, auto mtls could send plaintext in permissive mode and we wouldn't catch it.
This just adds more coverage. No bugs were detected in this, so it is just test code changing. This will help with another PR I am working on that does change the real mTLS code.
> TestReachability: assert we actually send mtls when expected

- pkg/test/failer.go
- pkg/test/framework/components/istioctl/istioctl.go
- pkg/test/framework/components/istioctl/kube.go
- tests/integration/pilot/analysis/analysis_test.go
- tests/integration/pilot/analyze_test.go
- tests/integration/pilot/cni/cni_test.go
- tests/integration/pilot/common/apps.go
- tests/integration/pilot/common/traffic.go
- tests/integration/pilot/endpointslice/endpointslice_test.go
- tests/integration/pilot/gateway_topology/gw_topology_test.go
- tests/integration/pilot/ingress_test.go
- tests/integration/pilot/istioctl_test.go
- tests/integration/pilot/locality_test.go
- tests/integration/pilot/main_test.go
- tests/integration/pilot/mirror_test.go
- tests/integration/pilot/multi_version_revision_test.go
- tests/integration/pilot/original_src_addr_test.go
- tests/integration/pilot/revisioncmd/revision_view_test.go
- tests/integration/pilot/revisioned_upgrade_test.go
- tests/integration/pilot/revisions/revision_tag_test.go
- tests/integration/pilot/revisions/revisions_test.go
- tests/integration/pilot/revisions/uninstall_test.go
- tests/integration/pilot/routing_test.go
- tests/integration/pilot/validation_test.go
- tests/integration/pilot/vm_test.go
- tests/integration/pilot/webhook_test.go
Its incredibly common in our tests to see:
```go
ctx.NewTest().Run(ctx, func() {
t.Fatal()
}
```
This causes go to panic. They should instead be using ctx.Fatal.
Fixing and preventing all of these cases is hard. Instead, we can just
shadow t so its impossible to make this mistake. I strongly suspect
every new test is copy+pasting previous ones, so if we change all usages
of `ctx` to `t` I doubt more usages will pop up.
I did this only in one tests for now to get early feedback
> tf: shadow t var to avoid using wrong one

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- releasenotes/notes/api-server-cluster-local.yaml
Fixes #31369
[ ] Docs
[x] Networking
[ ] Security
> Make kubernetes.default.svc cluster-local by default. (#31347)

- pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
- pilot/pkg/simulation/traffic.go
- pilot/test/xdstest/test.go
Note: this impacts tests only
The logic for "Not" was implemented wrong (and more complicated than it
needed to be!). This doesn't impact current tests but impacts some I am
working on and wanted to submit it in isolation.
[ ] Docs
[ ] Networking
[ ] Security
> Fix listener filter predicate

- pilot/pkg/bootstrap/server.go
Moving trustbundle library after CA initializaton
[ ] Docs
[X] Networking
[X] Security
> Moving trustbundle library after CA initializaton

- tools/build-base-images.sh
This is a manual cherrypick of #29200 #31215 #31239 #31323 #31331 #31343. Those PRs make up the changes to tools/build-base-images.sh so that it can be called during a release-builder build to actually create new base images.
This PR along with a forthcoming cherry-pick of the release builder PR combine so that when a new release build is being done, and the base images contain a vulnerability, the automation should create a new base image using this script, and then a PR will be created containing the required update to have the new image be used. The RM should see the build failed, merge the new PR containing the image name update, and be able to kick off another build which should pass, removing the need to find someone who can build a new set of base images. …
> [release-1.8] Manual cherrypicks of build-base-images.sh PRs

- pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
- releasenotes/notes/28996.yaml
* Fix to enable choice of TLS parameters within Envoy Filters
* Core code generic: does not depend on tls package
* Clusters: condition in case auto mtls is enabled
Description:
Cherry pick of the commit 1461bd714e10aad760a2a7ad1c817004e3297be2 from master to release-1.9 branch.
[ ] Docs
[X] Networking
[ ] Security
> Cherry pick release 1.9 fix envoyfilter

- pilot/pkg/bootstrap/server.go
- pilot/pkg/model/jwks_resolver.go
- pilot/pkg/model/jwks_resolver_test.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/security/authn/v1beta1/policy_applier.go
- pilot/pkg/security/authn/v1beta1/policy_applier_test.go
- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/fake.go
- tests/util/leak/check.go
Currently any test that uses any part of pilot leaks because of this.
Using coding best practices and making this not a global object.
Fixes https://github.com/istio/istio/issues/29349
[ ] Docs
[x] Networking
[x] Security
> pilot: Make JwtKeyResolver non global

- pilot/pkg/security/authn/v1beta1/policy_applier.go
- pilot/pkg/security/authn/v1beta1/policy_applier_test.go
- tests/integration/security/reachability_test.go
- tests/integration/security/testdata/beta-mtls-permissive.yaml
- tests/integration/security/testdata/no-peer-authn.yaml
Previously, `composePeerAuthentication` returns nil which can be used to
indicate no applicable (beta) policy exist in order to trigger fallback to
alpha policy if the input config list is empty. This can be simplified as we've
deprecated alpha policy.
This patch defaults the peer authn to a PERMISSIVE if no effective config input.
It helps clarify the behavior when no beta peer authn policy applied.
Related: https://github.com/istio/istio/issues/22602
[ ] Docs
[ ] Networking
[x] Security
Please check any characteristics that apply to this …
> authn: default peer authn to a PERMISSIVE is none effective exists

- pilot/pkg/security/authn/v1beta1/policy_applier.go
- pilot/pkg/security/authn/v1beta1/policy_applier_test.go
This avoids needless `istio_authn` filters to be added with all mtls and
request auth disabled.
Fixes: https://github.com/istio/istio/issues/27057
Related: https://github.com/istio/istio/issues/22602
[ ] Docs
[ ] Networking
[x] Security
> authn: skip filter peer config when mtls is disabled

- pkg/envoy/proxy.go
- pkg/envoy/proxy_test.go
- releasenotes/notes/31403.yaml
resolves https://github.com/istio/istio/issues/31403
During drain Envoy notifies clients using GO-AWAY or connection:close (or other protocol specific methods).
The default is to gradually notify clients, this changes it to immediately notify clients.
The drain duration is unaffected, just that clients have more time to gracefully react to impending termination.
> Change the drain strategy to immediate

- pilot/pkg/config/kube/gateway/controller.go
k8s gateway controller actually contains the crd cache, but it is also added to istio config store. So for vs/gw/dr , there are 2 duplicate handlers registered
> Fix vs/gateway/dr event handler been registered twice

- istioctl/cmd/tag.go
- istioctl/cmd/tag_test.go
- tests/integration/pilot/revisions/revision_tag_test.go
Fixes #30701, makes it so that users are prompted for confirmation when creating a revision tag pointed to a revision that's too old to patch it
[ ] Docs
[ ] Networking
[ ] Security
> [istioctl] add version check to tag set command

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
Fixes https://github.com/istio/istio/issues/31317
Essentially a revert of https://github.com/istio/istio/pull/30885 because now we can not set `max_stream_duration` to 0s as it disables timeouts altogether.
[ ] Docs
[ ] Security
> do not set max stream duration

- pkg/test/echo/common/util.go
- pkg/test/framework/components/echo/call.go
I've seen some cases of test flakes where I think what happens is we hang for 15s on a bad connection and then we hit our total timeout too soon. If we had justretried earlier, we would have succeeded. 15s is super high anyways - even 5s is quite high
> Drop echo default timeout

- manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
- manifests/charts/istio-control/istio-discovery/templates/mutatingwebhook.yaml
- manifests/charts/istiod-remote/files/gen-istiod-remote.yaml
- manifests/charts/istiod-remote/templates/mutatingwebhook.yaml
- releasenotes/notes/add-default-revision-webhook.yaml
Makes it so that labeling namespace or workload `istio.io/rev=default` will result in injection for a non-revisioned install, blocker for https://github.com/istio/istio.io/pull/9192
[ ] Docs
[ ] Networking
[ ] Security
> Make istio.io/rev=default inject for default revision

- pkg/test/framework/analyzer.go
- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/components/echo/kube/deployment_test.go
- pkg/test/framework/components/echo/kube/instance.go
- pkg/test/framework/components/namespace/kube.go
- pkg/test/framework/resource/flags.go
- pkg/test/framework/resource/settings.go
- pkg/test/framework/resource/version.go
- pkg/test/framework/resource/version_test.go
- pkg/test/framework/test.go
Backport of [https://github.com/istio/istio/pull/31150](https://github.com/istio/istio/pull/31150)
[ ] Docs
[ ] Networking
[ ] Security
> [release-1.9] Make test framework version-aware (#31150)

- pilot/pkg/bootstrap/server_test.go
- pilot/pkg/model/cluster_local.go
- pilot/pkg/model/context.go
We've added an Init() method to Environment. Adding the defaulting of DomainSuffix there to avoid the need for a duplicate method.
[ ] Docs
[x] Networking
[ ] Security
> Cleanup domain suffix handling

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/core/v1alpha3/cluster_test.go
I felt MutableCluster is a better name compared to IstioCluster
[ ] Docs
[X] Networking
[ ] Security
> rename IstioCluster to MutableCluster

- tools/build-base-images.sh
This is a manual cherrypick of #31323 #31331 #31343. Those PRs, but two more cherrypicked earlier make up the changes to tools/build-base-images.sh so that it can be called during a release-builder build to actually create new base images.
This PR along with a forthcoming cherry-pick of the release builder PR combine so that when a new release build is being done, and the base images contain a vulnerability, the automation should create a new base image using this script, and then a PR will be created containing the required update to have the new image be used. The RM should see the build failed, merge the new PR containing the image name update, and be able to kick off another build which should pass, removing the need to find someone who can build a new set of base images.
Please check …
> [release-1.9] Manual cherrypick of #31323 #31331 #31343

- pilot/pkg/model/authentication.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
- pilot/pkg/security/authn/utils/utils.go
- pilot/pkg/security/model/authentication.go
- pilot/pkg/security/model/authentication_test.go
We are currently adding validation context for SIMPLE mode which is not needed if cacerts are not present and is failing if gateway specifies certs via files without caCertificate, as `model.GetRootResourceName` returns `ROOTCA` as cert is not provided and SDS fails to fetch.
[ ] Docs
[X] Networking
[X] Security
> do not add validation context for SIMPLE

- security/pkg/nodeagent/sds/sdsservice.go
[ ] Docs
[ ] Networking
[ X ] Security
The `ExponentialBackOff` has a default 15min's `MaxElapsedTime` which will bring the state to `STOP` after that time. And the use code will enter a nearly infinite loop and cause very high CPU. This change sets the `MaxElapsedTime` to 0 with no-stop semantic.
> Fix high cpu caused by early stop when generating secret

- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/networking/util/util_test.go
Would be useful in multi cluster multi network environment, to at least indicate the destination cluster when MX does not happen.
> Add telemetry endpoint metadata even when missing workload name

- tools/istio-iptables/pkg/cmd/run.go
Currently all environment variables that match the flags added in the `init()`
of `root` will be loaded into Viper as default, and further be used in the
execution.
The TODO is somewhat confusing as there is no actual `obsolete environment
variable` and the pointed `ISTIO_SERVICE_CIDR` should still be used in VM cases.
[ ] Docs
[x] Networking
[ ] Security
> istio-iptables: remove confusing todo

- pkg/bootstrap/config.go
- tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
Instead of attempting to contact the MD server directly, this redirects through the metadata exported by the platform. This should allow "proper" behavior when not directly on GCP envs.
Resolves https://github.com/istio/istio/issues/29268
> Support non-GCP envs for Stackdriver trace

- pkg/test/kube/util.go
This prevents a race condition where no pods are started yet - we should
wait until there is at least one pod AND the pods are ready
[ ] Docs
[ ] Networking
[ ] Security
> Block CheckPodsAreReady until there are pods

- istioctl/pkg/install/pre-check.go
To fix https://github.com/istio/istio/issues/31489
Before:
```
[istio]$ ./out/linux_amd64/istioctl install
[istio]$ ./out/linux_amd64/istioctl x precheck
"default" revision of Istio is already installed in "istio-system" namespace
```
After:
```
[istio]$ ./out/linux_amd64/istioctl install
[istio]$ ./out/linux_amd64/istioctl x precheck
"default" revision of Istio is already installed in "istio-system" namespace
Checking the cluster to make sure it is ready for Istio installation...
#1. Kubernetes-api
```
> istioctl x precheck: display precheck message in all the cases

- samples/extauthz/src/main.go
[ ] Docs
[ ] Networking
[ ] Security
Fix the sample code. 
```bash
[root@jump src]# pwd
/tmp/istio/samples/extauthz/src
[root@jump src]# go test
2021/03/17 08:12:19 Starting HTTP server at 127.0.0.1:36064
2021/03/17 08:12:19 Starting gRPC server at 127.0.0.1:33706
2021/03/17 08:12:19 [HTTP][allowed]: GET localhost:36064/check, headers: map[Accept-Encoding:[gzip] User-Agent:[Go-http-client/1.1] X-Ext-Authz:[allow]] …
```
> fix nil error

- pkg/test/framework/components/environment/kube/kube.go
Very few people have seen the wiki.. this will help encourage people to lean on local-development and hopefully get more eyes on the wiki so we can fill in any gaps.
> advertise test framework wiki when early setup fails

- pilot/pkg/config/kube/ingress/status.go
- pilot/pkg/config/kube/ingress/status_test.go
- pilot/pkg/config/kube/ingressv1/status.go
- pilot/pkg/config/kube/ingressv1/status_test.go
- releasenotes/notes/31336.yaml
Fixes #31336, probably want to cherry-pick back through 1.8
Still unclear to me how there could be 2000-18000 logs per minute with the queue rate limiting the errors without multiple status controller queues, which there don't seem to be from goroutine dump
[ ] Docs
[x] Networking
[ ] Security
> Fix runaway ingress status errors

- pkg/test/framework/components/echo/echotest/echotest.go
- pkg/test/framework/components/echo/echotest/filters.go
- pkg/test/framework/components/echo/echotest/filters_test.go
- pkg/test/framework/suite.go
- pkg/test/framework/testcontext.go
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/common/traffic.go
> make virtual service tests workload agnostic

- istioctl/cmd/admin.go
- istioctl/cmd/istiodconfig.go
- istioctl/cmd/istiodconfig_test.go
- istioctl/cmd/root.go
> istioctl x istiod log must become istioctl admin log or istioctl admin x log
Keeping `admin` as a separate command will be useful when we will have separate control plane and data plane commands (`istioctl admin proxy-status` and `istioctl proxy-status`).
Part of https://github.com/istio/istio/issues/29153
More details: https://docs.google.com/document/d/1raZOoeYz3APZdQRlJlFA-zgfmEJu2YLaGa4_3KwbNRs/edit#
> rename: x istiod log to admin log

- pkg/test/framework/components/echo/config.go
- pkg/test/framework/components/echo/echotest/echotest.go
- pkg/test/framework/components/echo/echotest/fake.go
- pkg/test/framework/components/echo/echotest/filters.go
- pkg/test/framework/components/echo/echotest/filters_test.go
- pkg/test/framework/components/echo/echotest/run.go
- pkg/test/framework/components/echo/echotest/setup.go
- pkg/test/framework/components/echo/instances.go
- pkg/test/framework/testcontext.go
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/common/traffic.go
cherry-pick of #31373 
fixes #31498 
this will help us keep coverage high as new tests are added without as much manual backporting/conversion
> [release-1.9] test framework: *echotest.T for enumerating subtests

- pilot/tools/debug/pilot_cli.go
[ ] Docs
[ ] Networking
[ ] Security
Lower version, such as istio 1.6.10, the labels is ` app=istiod, istio=istiod`. 
But the latest version, the labels changed to ` app=istiod,istio=pilot`. 
So we should use `app=istiod` instead to be compliant with different versions.
> fix labels

- pilot/pkg/bootstrap/server.go
- pilot/pkg/bootstrap/server_test.go
- pilot/pkg/bootstrap/servicecontroller.go
- pilot/pkg/server/instance.go
- pilot/pkg/server/instance_test.go
- pilot/pkg/serviceregistry/kube/controller/multicluster.go
- pilot/pkg/serviceregistry/kube/controller/multicluster_test.go
Server has a `addTerminatingStartFunc` method that is used to wait for gracefully shutdown of an elected k8s leader. Without this, shutting down the process could result in no leader being elected for 30-60s. This method is only accessible to the bootstrap package, however.
This PR refactors the server so that leader components dynamically created by the multicluster processing can also hook into the same shutdown logic.
[ ] Docs
[ ] Networking
[ ] Security
> Allow server to wait for multicluster components

- pkg/test/framework/components/cluster/kube/factory.go
- pkg/test/framework/components/environment/kube/flags.go
- pkg/test/framework/components/environment/kube/settings.go
- pkg/test/util/file/file.go
Without this change, if you specify multiple clusters that use '~' instead of an absolute path, we end up using `~/.kube/config` for every cluster, which will break the tests and possibly a cluster that shouldn't be touched. 
- Allow homedir via `~`
- Fail out if file isn't found
> test framework: make kubeconfig path in topology file more robust

- pkg/test/framework/components/istio/operator.go
This shouldn't affect CI, but when running the test framework in multicluster mode, with only 1 primary cluster, we will apply the remote secret for the local primary-cluster. 
This can cause kube service registry issues. The following log also occurs:
```
2021-03-18T20:16:21.258530Z	error	klog	error retrieving resource lock istio-system/istio-namespace-controller-election: configmaps "istio-namespace-controller-election" is forbidden: User "system:serviceaccount:istio-system:istio-reader-service-account" cannot get resource "configmaps" in API group "" in the namespace "istio-system"
```
> test framework: dont apply remote secret for self

- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_test.go
We are still seeing this stream terminated by RST_STREAM with error code: NO_ERROR in logs. Figured out that is is in a gRPC status but a regular error. So added message check.
[ ] Docs
[X] Networking
[ ] Security
> fix xds proxy logs

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
No one has responded yet on this https://github.com/envoyproxy/envoy/issues/15530. So instead of keeping master broken for long time - I am setting MaxStreamDuration to the value specified in VS. 
I will do a follow-up PR once a decision comes on that.
[ ] Docs
[ ] Security
> set max stream duration to the value specified in VS

- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/components/echo/kube/testdata/basic.yaml
- pkg/test/framework/components/echo/kube/testdata/healthcheck-rewrite.yaml
- pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions.yaml
- pkg/test/framework/components/echo/kube/testdata/multiversion.yaml
- pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml
I make it run as non-root by default, since I think this is the most cases in reality. I can make this an option if this is not desired. For https://github.com/istio/istio/issues/28256.
> Run echo as non root.

- Makefile.core.mk
Update base image. Will need to retest once images are pushed. Blocking the release of 1.9.2
> Update base image for image scanning issue

- pkg/test/echo/server/forwarder/instance.go
When making a call with echo app, the user can specify the # of requests as well as a timeout via CallOptions:
```go
echo.CallOptions{
Timeout: 5*time.Second,
Count: 50,
}
```
The current semantics are that _each_ of the 50 calls can take up to 5 seconds. 
In the echo forwarder, we make up to 20 concurrent requests:
https://github.com/istio/istio/blob/3f324e45a17d27e8660930cacfffeef2ea0de3e9/pkg/test/echo/server/forwarder/instance.go#L33
So for 50 requests, that timeout after 5 seconds each, the first set of 20 take 5 seconds, the second set of 20 takes 5 seconds, then the final set of 10 takes 5 seconds giving a total of 15 seconds. 
To allow a failure to occur while providing ample time for us to retry and converge on 3 sets of requests all succeeding, we should enforce this timeout at …
> echo app: call timeout applies to entire set of requests

- pkg/test/framework/components/echo/echotest/run.go
- pkg/test/framework/components/echo/echotest/setup.go
- pkg/test/framework/test.go
As #31365  points out, it's easy to run into issues where a subtest calls Fail or other methods on the root/parent test. 
This changes signatures and types that most IDEs would use for auto-complete to make user-defined funcs take `t` instead of `ctx` to help encourage shadowing.
> test framework: change signatures and types to encourage shadowing T

- tests/integration/pilot/multicluster_test.go
* actually call errG.Wait() on the cleanup func
* immediately run a second test that confirms we have cross-cluster LB re-enabled
> ensure cluster local config is torn down

- tests/integration/pilot/common/routing.go
I think these have failed before with errors like "header not found",
when really the request entirely failed so its a bit misleading?
Maybe we should also consider always validating OK unless explicitly
told not to as well? but that would be a much larger change
[ ] Docs
[ ] Networking
[ ] Security
> Add ExpectOk to a few tests

- pilot/pkg/networking/core/v1alpha3/cluster.go
This is a tiny optimization to skip patch logic if cluster patches are not there
[ ] Docs
[X] Networking
[ ] Security
> skip patch logic if there are no cluster patches

- galley/pkg/config/analysis/analyzers/injection/injection.go
- galley/pkg/config/analysis/analyzers/util/config.go
~~Resolves https://github.com/istio/istio/issues/30874~~
Starts work on https://github.com/istio/istio/issues/30874 by skipping _istio-system_ when checking for injection labels.
Because _istio-system_ does not have an injection label, yet also doesn't run user workloads, don't expect it to have an `istio-injection` label.
> Don't expect istio-system to have an injection label

- pilot/pkg/xds/debug.go
Responds with 
```json
{
"network-1": [
{"Addr": "1.2.3.4", "Port": 15443},
]
}
```
> add debug endpoint for multi-network gateways

- pkg/test/util/retry/retry.go
```
2021-03-23T16:29:20.449993Z	info	tf	=== BEGIN: Test: 'pilot[TestTraffic/instanceip/localhost_IP_without_sidecar]' ===
traffic.go:147: 1 error occurred:
* failed calling a->'http://b.echo-1-11405.svc.cluster.local:84/': call failed from a to http://b.echo-1-11405.svc.cluster.local:84 (using http): timeout while waiting after 6 attempts (last error: no responses received)
2021-03-23T16:29:40.814458Z	info	tf	=== DONE (failed):  Test: 'pilot[TestTraffic/instanceip/localhost_IP_without_sidecar] (20.364457751s)' ===
```
It would be helpful to know if we were consistently failing, or if we were close to succeeding and need to bump timeouts.
> retry: include successes/converge info in err

- pilot/pkg/model/context.go
- pkg/bootstrap/config.go
- pkg/bootstrap/config_test.go
- pkg/bootstrap/instance.go
- pkg/bootstrap/instance_test.go
- pkg/bootstrap/option/instances.go
- pkg/bootstrap/option/instances_test.go
- pkg/envoy/proxy.go
Simple refactor to converge on bootstrap generation that is driven by node structure.
This allows portable bootstrap generator that can be run outside the pod.
> envoy: simplify bootstrap generation

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
When useclient protocol is set in DR, we need to set usedownstream protocol to inbound clusters also. Otherwise that path will not use client protocol.
[ ] Docs
[X] Networking
[ ] Security
> set usedownstream protocol for inbound clusters also

- tests/integration/security/sds_tls_origination/egress_gateway_origination_test.go
- tests/integration/security/sds_tls_origination/util/util.go
Changes sds_tls_origination so that it checks response codes for each echo response. Also shadow `testing.T` with `framework.TestContext`.
[ ] Docs
[ ] Networking
[ ] Security
> Make sds_tls_origination suite work under multiversion tests

- tests/integration/security/authorization_test.go
- tests/integration/security/ca_custom_root/multi_root_test.go
- tests/integration/security/ca_custom_root/secure_naming_test.go
- tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go
- tests/integration/security/ca_custom_root/trust_domain_validation_test.go
- tests/integration/security/chiron/dns_cert_test.go
- tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
- tests/integration/security/external_ca/reachability_test.go
- tests/integration/security/file_mounted_certs/p2p_mtls_test.go
- tests/integration/security/filebased_tls_origination/destination_rule_tls_test.go
- tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go
- tests/integration/security/jwt_test.go
- tests/integration/security/mtls_first_party_jwt/strict_test.go
- tests/integration/security/mtls_healthcheck_test.go
- tests/integration/security/mtlsk8sca/strict_test.go
- tests/integration/security/pass_through_filter_chain_test.go
- tests/integration/security/reachability_test.go
- tests/integration/security/sds_egress/sds_istio_mutual_egress_test.go
- tests/integration/security/sds_ingress/ingress_test.go
- tests/integration/security/sds_ingress/util/util.go
- tests/integration/security/sds_ingress_k8sca/main_test.go
- tests/integration/security/util/rbac_util/util.go
- tests/integration/security/util/reachability/context.go
Shadows `t *testing.T` with `t framework.TestContext` in security tests. Refactors helpers to either take (1) `test.Failer` if `t.Error` and `t.Log` not used or (2) `framework.TestContext` if they are.
[ ] Docs
[ ] Networking
[ ] Security
> Shadow t *testing.T with framework.TestContext in security tests

- pilot/pkg/bootstrap/server.go
We are logging 8080 but it should be 15017
> Fix logging wrong address for webhook

- pilot/pkg/xds/ads.go
- pilot/pkg/xds/adstest.go
- pilot/pkg/xds/authentication.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/delta.go
- pilot/pkg/xds/deltaadstest.go
- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/gen.go
- pilot/pkg/xds/monitoring.go
- pilot/pkg/xds/sds.go
- pilot/pkg/xds/simple.go
- pilot/pkg/xds/statusgen.go
This makes it easier to use the correct scope (ads) by not requiring
developers to remember its supposed to be `adsLog` in this package.
[ ] Docs
[ ] Networking
[ ] Security
> Shadow `log` variable so its consistently used

- pilot/cmd/pilot-discovery/main.go
- pilot/cmd/pilot-discovery/options.go
- pilot/pkg/bootstrap/options.go
- pilot/pkg/bootstrap/server.go
- pilot/pkg/bootstrap/server_test.go
- pilot/pkg/bootstrap/webhook.go
Sometimes it is not allowed to support tls1.0/tls1.1 and also not allowed to use some cipher suites in production env.  So in this pr, I make cipher suites of istiod TLS server configurable.
> support config istiod server tls cipher suites

- istioctl/cmd/internal-debug.go
According to [istioctl/issue: 31703](https://github.com/istio/istio/issues/31703) to change the name of sub-command debug from **debug** to **internal-debug** 
[ ] Docs
[ ] Networking
[ ] Security
[ x ] User Experience
> change subcommand debug name for istioctl

- pkg/test/framework/components/echo/kube/deployment.go
- tests/integration/security/pass_through_filter_chain_test.go
This is a followup PR of https://github.com/istio/istio/pull/31663
- Fix missing `WorkloadOnlyPorts` in VM deployment 
- Add VM as server workload to the [security/pass_through_filter_chain_test.go](https://github.com/istio/istio/blob/master/tests/integration/security/pass_through_filter_chain_test.go)
[ ] Docs
[ ] Networking
[ ] Security
> Add vm as server workload to pass through filter chain security integration tests 

- pilot/pkg/networking/core/v1alpha3/name_table.go
With this https://github.com/istio/istio/pull/31067 we are skipping cross cluster endpoints. However for individual pod endpoints for stateful sets we do not need load balancing and we need to add it even for cross cluster
[ ] Docs
[X] Networking
[ ] Security
> dns: add individual pod endpoints cross cluster also

- security/pkg/nodeagent/sds/server.go
Fix backoff last time, even if listen succeeds, the service will not start.
[ ] Docs
[ ] Networking
[ ] Security
> Fix security/pkg/nodeagent/sds/Server.initWorkloadSdsService

- pilot/pkg/networking/core/v1alpha3/listener.go
Currently, our ALPN matching logic is not complete. As a result,
requests that come in with the wrong ALPN will be forwarded to the
application.
This changes our filter chains such that in permissive mode, Istio mTLS
traffic is *always* captured by a filter chain that will terminate the
TLS. Note that the traffic may not be valid - for example, raw TCP on a
filter chain with HCM, but we will fail at the Envoy level rather than
in the users application.
> Capture all mTLS traffic in permissive mode

- pilot/cmd/pilot-agent/options/agent.go
- pilot/cmd/pilot-agent/options/options.go
- pilot/pkg/bootstrap/server.go
- pilot/pkg/features/pilot.go
- pilot/pkg/xds/pcds.go
- pkg/istio-agent/agent.go
- pkg/istio-agent/xds_proxy.go
- tests/integration/security/ca_custom_root/main_test.go
Adding configurable knob for multiple TrustAnchor support.
Related to https://github.com/istio/istio/issues/31662
[ ] Docs
[ ] Networking
[X] Security
> Adding configurable knob for multiple TrustAnchor support

- pilot/cmd/pilot-agent/main.go
- pkg/istio-agent/agent.go
agent start up function not only starts up sds, but also xds proxy and dns server.
> Clean up pilot-agent start up error message.

- pilot/pkg/bootstrap/server_test.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/security/model/authentication.go
- pkg/bootstrap/instance.go
- pkg/bootstrap/testdata/all_golden.json
- pkg/bootstrap/testdata/auth_golden.json
- pkg/bootstrap/testdata/authsds_golden.json
- pkg/bootstrap/testdata/default_golden.json
- pkg/bootstrap/testdata/running_golden.json
- pkg/bootstrap/testdata/runningsds_golden.json
- pkg/bootstrap/testdata/stats_inclusion_golden.json
- pkg/bootstrap/testdata/tracing_datadog_golden.json
- pkg/bootstrap/testdata/tracing_lightstep_golden.json
- pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
- pkg/bootstrap/testdata/tracing_stackdriver_golden.json
- pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
- pkg/bootstrap/testdata/tracing_tls_golden.json
- pkg/bootstrap/testdata/tracing_zipkin_golden.json
- pkg/bootstrap/testdata/xdsproxy_golden.json
- security/pkg/nodeagent/util/util.go
- tools/packaging/common/envoy_bootstrap.json
Fixes https://github.com/istio/istio/issues/31818
This makes CDS,LDS,EDS, and RDS wait indefinitely for response. Without
this, if Istiod takes >15s to response, we may prematurely be marked as
ready. This is trivially reproduced by adding a sleep in Istiod - the
pod will be "ready" despite having no listeners
[ ] Docs
[ ] Networking
[ ] Security
> Avoid proxy being marked ready prematurely when fetch times out

- galley/pkg/config/analysis/msg/messages.gen.go
- galley/pkg/config/analysis/msg/messages.yaml
For https://github.com/istio/istio.io/pull/9239#issuecomment-805977238
> As an aside, the text at https://github.com/istio/istio/blob/master/galley/pkg/config/analysis/msg/messages.yaml#L378 should probably be updated for grammar and name.
>
> Today: description: "Two services selecting the same workload with same target port are MUST refer to the same port."
> Maybe: description: "Two services selecting the same workload with the same targetPort MUST refer to the same port."
/cc @ericvn
> Fix analyzer IST137 description

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- pkg/config/validation/virtualservice.go
- tests/integration/pilot/common/routing.go
Fixes https://github.com/istio/istio/issues/31844
Envoy will reject header options for `Host` or `:`-prefixed. This adds
validation to our webhook to capture these. Additionally, it allows
setting `host` or `:authority` specifically, by internally transforming
it to a `authorityRewrite`.
[ ] Docs
[ ] Networking
[ ] Security
> Properly validate header operations and allow host header modification

- cni/pkg/install-cni/cmd/root.go
- cni/pkg/install-cni/pkg/config/config.go
- cni/pkg/install-cni/pkg/install/kubeconfig.go
Add a bit more logs into install-cni, including logging for the initial configuration and the generated kubeconfig. Also simplify the kubeconfig generation, there is no need to write to a temp file for template execution.
> Add more logs to install-cni.

- istioctl/cmd/kubeinject.go
- tests/integration/pilot/istioctl_test.go
* When no pods available, fail instead of hanging forever. Example:
```
$ istioctl kube-inject -f ~/kube/apps/httpbin.yaml
Error: no pods matching selector "app=istiod,istio=pilot" found in namespace "istio-system"
```
* Allow --revision=default
* Make integration test respect revision flag
> kube-inject improvements

- istioctl/cmd/proxystatus.go
- istioctl/cmd/version.go
- pkg/adsc/adsc.go
I badly needed the ability to see what _istioctl_ was sending when logging at debug level while testing https://github.com/istio/istio/pull/31749
This adds outgoing discovery request logs.  The discovery requests are logged as JSON with `jsonpb` and as such are suitable for being passed to `grpcurl -d @ -plaintext <pilot> envoy.service.discovery.v3.AggregatedDiscoveryService/StreamAggregatedResources`
Note that I was able to determine that some of the fields set by istioctl are overwritten before sending, and I also eliminated those fields.
> Log discovery requests when logging at debug level

- tests/integration/pilot/common/routing.go
- tests/integration/pilot/common/traffic.go
prevent test failures in `--skipVM` mode
> shifting test: use 2 pods when vms are disabled

- tests/integration/helm/install_test.go
The current helm install verification test was not checking network traffic after installation.
[ ] Docs
[ ] Networking
[ ] Security
> Add Traffic Verification to Helm Install Test

- pilot/pkg/security/authz/builder/extauthz.go
Fix https://github.com/istio/istio/issues/31965
It looks like the we got non deterministic generated config due to the map, sent out a fix to sort the keys before generating the config.
cc @howardjohn 
[ ] Docs
[ ] Networking
[x] Security
> fix ext-authz flaky test

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Follow by #31929, this is a cleanup to remove duplicate calling of `setUpstreamProtocol `.
>  Move setUpstreamProtocol to buildDefaultCluster

- Makefile.core.mk
- common/scripts/gobuild.sh
Also clean up unnecessary `CGO_ENABLED=1` used for
`security/tools/generate_cert` in Makefile.
[ ] Docs
[ ] Networking
[ ] Security
> Make `CGO_ENABLED` configurable for gobuild script

- tests/integration/pilot/common/routing.go
- tests/integration/pilot/common/traffic.go
- tests/integration/pilot/vm_test.go
#31937 introduced a panic when `--istio.test.skipVM` is used – this includes logic to use available splits inside the template
> shifting test: use only available splits

- pilot/pkg/networking/core/v1alpha3/listener_builder.go
- pilot/pkg/xds/xds_test.go
There is no reason to allow external access.
Note: for virtualInbound listener, we could not set localhost or podIP.
> Bind localhost to virtualOutbound listener 

- pkg/kube/inject/webhook.go
- pkg/kube/inject/webhook_test.go
- releasenotes/notes/31797.yaml
The parseInjectEnvs() function in webhook.go uses / characters to separate
keys and values for environment variables passed through the injector webhook
URL path. This doesn't work if the value of an env variable includes slash
characters. For example, it's not possible to set an environment variable like:
FOO_LOCATION=/path/to/foo.
This should be possible and is also needed in the external control plane
multicluster configuration if the remote cluster name includes / characters.
Perhaps this could be fixed by accepting values that are urlencoded
(e.g., "/inject/FOO_LOCATION/%2Fpath%2Fto%2Ffoo") or some similar encoding.
This PR checks each value, if there are encoded slashes, then it will
replace the encoded slash with actual slash.
Signed-off-by: litong01 <litong01@us.ibm.com>
[ ] …
> Allow slash characters in env variable values passed to injector #31732

- pilot/cmd/pilot-agent/status/server.go
- pilot/cmd/pilot-agent/status/server_test.go
- pkg/kube/apimirror/probe.go
Revert "Fix allows repeated headers (#31866)"
Revert "Avoid duplicate HTTP headers for istio-proxy probe requests (#28537)"
Fix #23504
[ ] Docs
[x] Networking
[ ] Security
> Fix probe header

- pilot/pkg/bootstrap/server.go
Fixes https://github.com/istio/istio/issues/32023
We have existing test coverage to ensure this mode still works correctly.
> Do not write namespace configmap for k8s cert provider

- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/image/settings.go
- tests/integration/pilot/ingress_test.go
Allows (partially) running this test in environments where images are in a protected registry. 
I began to convert the helm test as well, but the options were: modify the templates, somehow patch the generated kube yaml. Neither seemed great (although it makes me wonder if our templates _should_ include the ability to set `imagePullSecrets`?)
> use test framework imagepullsecret in testcustomgateway

- pkg/test/framework/components/istio/config.go
- pkg/test/framework/components/istio/flags.go
- pkg/test/framework/components/istio/operator.go
- tests/integration/tests.mk
#31765 I would like to enable a CNI test suite at postsubmit first. If that looks good and not flaky, we can make it at presubmit.
> Add operator options flag into integration test framework.

- pkg/config/mesh/kubemesh/watcher.go
- pkg/config/mesh/watcher.go
Out of order updates may cause the callback to run out of order,
persisting an older version
Example test failure:
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1379065239072411648
[ ] Docs
[ ] Networking
[ ] Security
> Fix race condition in mesh config update

- tools/build-base-images.sh
Fix missing ROOT env var in build-base-images.sh
[ ] Docs
[ ] Networking
[ ] Security
> Add ROOT env var

- tests/integration/security/authorization_test.go
- tests/integration/security/testdata/authz/v1beta1-tcp.yaml.tmpl
- tests/integration/security/util/framework.go
This splits out of #31618.
Templatize the security policies and add VM to TestAuthorization_TCP.
Here is a mapping from workloads to parameters
| src | src0 | src1 | src2 | src3 |
|---- | ---- | ---- | ---- | ---- |
| before | a | b | c | x (ns2) |
| after | a | b | c | e (ns2) |
| dst | dst0 | dst1 | dst2 | dst3 | dst4 |
| ---- | ---- | ---- | ---- | ---- |  ---- | 
| before| b | c | d | a | e |
| after| b | c/vm | d | a | e |
| applied policy | yes | yes | yes | no | yes |
[ ] Docs
[ ] Networking
[ ] Security
[x] Does not …
> Add vm to TestAuthorization_TCP

- pilot/pkg/networking/core/v1alpha3/listener_builder.go
- pilot/pkg/xds/xds_test.go
Reverts istio/istio#31784
This breaks upgrades:
```
ADS:LDS: ACK ERROR sidecar~10.244.0.18~echo-local-849647c5bd-g9wxf.default~default.svc.cluster.local-2 Internal:Error adding/updating listener(s) virtualOutbound: error updating listener: 'virtualOutbound' has a different address '127.0.0.1:15001' from existing listener address '0.0.0.0:15001'
```
> Revert "Bind localhost to virtualOutbound listener "

- pilot/pkg/xds/gen.go
- pilot/pkg/xds/monitoring.go
- releasenotes/notes/istiod-config-size-bytes.yaml
There is a need to monitor config sizes, particularly as they approach limits. This would allow tracking of p99, etc., for config sizes by resource type.
Example output:
```
pilot_xds_config_size_bytes_bucket{type="type.googleapis.com/envoy.config.listener.v3.Listener",le="1"} 0
pilot_xds_config_size_bytes_bucket{type="type.googleapis.com/envoy.config.listener.v3.Listener",le="10000"} 0
pilot_xds_config_size_bytes_bucket{type="type.googleapis.com/envoy.config.listener.v3.Listener",le="1e+06"} 19
pilot_xds_config_size_bytes_bucket{type="type.googleapis.com/envoy.config.listener.v3.Listener",le="4e+06"} 19
pilot_xds_config_size_bytes_bucket{type="type.googleapis.com/envoy.config.listener.v3.Listener",le="1e+07"} 19
pilot_xds_config_size_bytes_bucket{type="type.googleapis.com/envoy.config.lis …
```
> Add metric for XDS config sizes by namespace and resource type.

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
Since we have upgraded the proxy with this fix https://github.com/envoyproxy/envoy/commit/ffa1680ae2619c8339733b9bd7071fc06f5179c9,  we not need max stream duration workaround. 
Also fixes https://github.com/istio/istio/issues/31616
[ ] Docs
[X] Networking
[ ] Security
> remove max stream duration

- pilot/pkg/model/gateway.go
Saw a user fail to validate, we should not panic but ignore the config.
> Do not panic on invalid Gateway config

- pkg/istio-agent/agent.go
- pkg/istio-agent/xds_proxy.go
- tests/integration/pilot/piggyback_test.go
There are already some usages of port 15009 (for BTS) that may lead to conflict. Switching now to be safe since it hasn't shipped yet
[ ] Docs
[ ] Networking
[ ] Security
> Switch XDS proxy tap to port 15004

- pkg/test/helm/helm.go
- tests/integration/helm/install_test.go
- tests/integration/helm/main_test.go
- tests/integration/helm/upgrade/util.go
- tests/integration/helm/util.go
Issue: Helm integration tests were always passing in `third-party-jwt` for
the `global.jwtPolicy` field. Fix the integration test to use
`first-party-jwt` when specified by not installing istio with helm in
main_test.go.
TODO: When first-party-jwt is no longer supported we should add back the
test to use the helm package inside of the test framework.
[ ] Docs
[ ] Networking
[ ] Security
> Fix helm integration test that uses first-party-jwt

- security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go
- security/pkg/util/jwtutil.go
- tests/integration/helm/install_test.go
- tests/integration/security/mtls_first_party_jwt/main_test.go
For https://github.com/istio/istio/issues/31964
Just add a warning to give users a hint.
This also cleans up a dead field.
> Allow, with warning, users using first-party-jwt with Kubernetes 1.21+

- pilot/pkg/xds/ads.go
- pilot/pkg/xds/v3/model.go
- tests/integration/telemetry/stats/prometheus/wasm/bad_wasm_filter_test.go
* Use short name in log and metrics
* Correctly identify it as a non-wildcard type. This alows us to fully
drop the type if envoy unsubscribes, instead of constantly pushing empty
responses to it.
> Add a few checks for ECDS type

- pkg/test/framework/components/cluster/staticvm/namespace.go
- pkg/test/framework/components/echo/echotest/fake.go
- pkg/test/framework/components/echo/echotest/run.go
- pkg/test/framework/components/namespace/kube.go
- pkg/test/framework/components/namespace/namespace.go
- tests/integration/security/authorization_test.go
The security tests deal with multiple namespaces often. The tests look like duplicates, but should be listed distinctly.
> echotest: include namespace in subtest when service exists in multiple

- pkg/test/helm/helm.go
- tests/integration/helm/install_test.go
- tests/integration/helm/main_test.go
- tests/integration/helm/upgrade/util.go
- tests/integration/helm/util.go
Cherry-pick of 54ba14c99b705694d2ec36ec7f9cfe52f6afdf1e from https://github.com/istio/istio/pull/32159
Issue: Helm integration tests were always passing in third-party-jwt for
the global.jwtPolicy field. Fix the integration test to use
first-party-jwt when specified by not installing istio with helm in
main_test.go.
[ ] Docs
[ ] Networking
[ ] Security
> [release-1.10] Fix helm integration test that uses first-party-jwt (#32159)

- galley/pkg/config/analysis/msg/messages.gen.go
- galley/pkg/config/analysis/msg/messages.yaml
IST0143 has: "A port exposed in by a Service is bound to a localhost address". Reword to "A port exposed in a Service is bound to a localhost address"
I went with the `in` wording used on the next line, but wonder if we should use `by` instead.
[ ] Docs
[ ] Networking
[ ] Security
> IST0143 - Fix `in by` to be `in`

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_test.go
Prior PR cleaned up the random sampling percentage; this PR handles it for disable span reporting as well.  With this PR, a user overriding the parent disable/enable choice will have to do so explicitly.
> Handle wrapper value properly for DisableSpanReporting

- release/downloadIstioCandidate.sh
- release/downloadIstioCtl.sh
To fix https://github.com/istio/istio/issues/32194
We use to trim the first 3 characters from the Istio version eg: `1.9.0-alpha.0 > 1.9`, but if the version is greater than 1.9 eg: `1.10.0-alpha.0 > 1.1` which breaks the download script. We should split with dot and consider the first 2 values.
> Fix downloading Istio version greater than 1.9

- pilot/pkg/bootstrap/server.go
Previously, we had the same listener serving two http servers. I don't
really know how this worked, but it somehow did - perhaps the last one
wins. Either way, it doesn't seem right.
Instead, we always have a single listener, and just switch the handler
if we determine we should multiplex. This is simpler and more reliable.
> More improvements to multiplexing

- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/security/authz/builder/builder.go
- pilot/pkg/security/authz/builder/extauthz.go
- pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-no-namespace-out1.yaml
- pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-no-namespace-out2.yaml
- pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-out1.yaml
- pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-out2.yaml
- pilot/pkg/security/authz/builder/testdata/http/custom-http-provider-out1.yaml
- pilot/pkg/security/authz/builder/testdata/http/custom-http-provider-out2.yaml
- pilot/pkg/security/authz/builder/testdata/tcp/custom-both-http-tcp-out1.yaml
- pilot/pkg/security/authz/builder/testdata/tcp/custom-both-http-tcp-out2.yaml
- pilot/pkg/security/authz/model/model.go
- pkg/bootstrap/config.go
- pkg/bootstrap/instance_test.go
- pkg/bootstrap/testdata/all_golden.json
- pkg/bootstrap/testdata/auth_golden.json
- pkg/bootstrap/testdata/authsds_golden.json
- pkg/bootstrap/testdata/default_golden.json
- pkg/bootstrap/testdata/running_golden.json
- pkg/bootstrap/testdata/runningsds_golden.json
- pkg/bootstrap/testdata/stats_inclusion_golden.json
- pkg/bootstrap/testdata/tracing_datadog_golden.json
- pkg/bootstrap/testdata/tracing_lightstep_golden.json
- pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
- pkg/bootstrap/testdata/tracing_stackdriver_golden.json
- pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
- pkg/bootstrap/testdata/tracing_tls_golden.json
- pkg/bootstrap/testdata/tracing_zipkin_golden.json
- pkg/bootstrap/testdata/xdsproxy_golden.json
- tools/packaging/common/envoy_bootstrap.json
This PR allows users to view the dry-run results in tracing and stats.
There are 3 main changes in the PR:
1. In tracing.go, added 4 new custom trace tags for dry run policies
2. In authz, updated to use a different stat prefix in the ext-authz so that it won't affect the dry run stats
3. In envoy_bootstrap.json and bootstrap/config.go: added 3 new tag extractors for authz policies and also include the rbac stats with suffix match  `allowed,denied`
Example Prometheus Stats, we will document the tags are not stable and should only be used for debugging for now:
```
envoy_http_inbound_0_0_0_0_80_rbac{authz_enforce_result="allowed"} 0
envoy_http_inbound_0_0_0_0_80_rbac{authz_enforce_result="denied"} 0
envoy_http_inbound_0_0_0_0_80_rbac{authz_dry_run_action="allow",authz_dry_run_result="allowe …
```
> add stats and tracing support for dry-run policy

- pkg/test/framework/analyzer_runtime.go
- pkg/test/framework/components/cluster/clusterboot/factory.go
- pkg/test/framework/components/cluster/clusterboot/factory_test.go
- pkg/test/framework/components/cluster/config.go
- pkg/test/framework/components/cluster/staticvm/staticvm.go
- pkg/test/framework/components/echo/kube/deployment_test.go
- pkg/test/framework/components/environment/kube/flags.go
- pkg/test/framework/components/environment/kube/settings.go
- pkg/test/framework/config/config.go
- pkg/test/framework/config/map.go
- pkg/test/framework/image/flags.go
- pkg/test/framework/resource/flags.go
- pkg/test/framework/resource/version.go
- pkg/test/framework/suite.go
* any flag beginning with `istio.test` registered via the built-in `flag`package can also be specified by a YAML config file
* by default we allow the `flag.Value` parsing behavior; if the value is `true` in YAML we give that to `value.Set` which in turn does `ParseBool`
* Optionally, whenusing `flag.Var` and a custom type, you can also implement `config.Value`, a superset of `flag.Value`. This means we can allow parsing strings like `0:1,1:1` OR simply reading map values. The `IstioVersions` `RevMap` is an example of this.
A follow will include allowing us to embed the `istio.test.topology` in this larger config file. 
I've tested these changes locally using different combinations. Here is an example that will exercise a simple boolean flag, and one of these more complex map-based flags: …
> allow specifying test framework flags via config file

- pilot/cmd/pilot-discovery/main.go
- pilot/pkg/bootstrap/options.go
- pilot/pkg/bootstrap/server.go
- releasenotes/notes/32201.yaml
fix typos and shutdownDuration of server assignments error.
If args.ShutdownDuration is equal to 20, s.shutdownDuration should also be 20, but s.shutdownDuration is 0.
[ ] Docs
[ ] Networking
[ ] Security
> shutdownDuration of server assignments error

- pilot/pkg/bootstrap/server.go
Fixes https://github.com/istio/istio/issues/32023
(cherry picked from commit 439c0ab15027113a70f8076e4c399bcb77532746)
[ ] Docs
[ ] Networking
[ ] Security
> Do not write namespace configmap for k8s cert provider (#32052)

- pilot/pkg/bootstrap/servicecontroller.go
- pilot/pkg/config/kube/crdclient/client.go
- pilot/pkg/features/pilot.go
- pilot/pkg/secrets/kube/multicluster.go
- pilot/pkg/secrets/kube/secrets_test.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/multicluster.go
- pkg/kube/secretcontroller/secretcontroller.go
- pkg/kube/secretcontroller/secretcontroller_test.go
- pkg/test/framework/components/cluster/cluster.go
- pkg/test/framework/components/istio/operator.go
- releasenotes/notes/30838.yaml
- tests/integration/iop-integration-test-defaults.yaml
- tests/integration/pilot/multicluster_test.go
initial fix for #30838 
[doc](https://docs.google.com/document/d/1eS72Ozu_tREk3Zw5PTrPA8oGeAMis1VwvkgTgLgUr7g/edit?usp=sharing&resourcekey=0-0OnlRQXkFqL09ZXyqMhpog)
* General `secretcontroller` refactor
* duplicated code in Update/Add path
* util methods for concurrent access to cluster store
* update/add share a type
* callbacks take a struct with: client, stop channel, timeout bool ptr
* `secretcontroller` now manages stop channels for each cluster, and calls RunAndWait
* we were calling RunAndWait synchronously, inside of callbacks, which blocked startup without getting to HasSynced
* `secretcontroller` exposes `HasSynced`
* requires us to _attempt_ to process the secrets local to the cluster
* makes sure `RunAndWait` has allowed caches to sync for remote clusters created so-far
* …
> add timeout for remote clusters to become ready

- tools/certs/Makefile.selfsigned.mk
concatenate the cert-chain for workload certs with right order: workload cert->intermediate ca cert ->root cert
> concatenate cert-chain using correct order

- pkg/bootstrap/config.go
- pkg/bootstrap/option/instances.go
Expose node type in bootstrap options so that custom bootstrap can have conditional bootstrap config only for ingress.
[ ] Docs
[X] Networking
[ ] Security
> expose node type to bootstrap options

- istioctl/cmd/describe.go
To fix https://github.com/istio/istio/issues/31874
Update helloworld sample to include container level securityContext and run
```
$ kubectl apply -f samples/helloworld/helloworld.yaml
```
```
$ istioctl x describe pod helloworld-v1-544fc955f5-2fk67
WARNING: Application pods should not run as user ID (UID) 1337\n
Pod: helloworld-v1-544fc955f5-2fk67
Pod Ports: 5000 (helloworld), 15090 (istio-proxy)
--------------------
Service: helloworld
Port: http 5000/HTTP targets pod port 5000
```
Update helloworld sample to include pod Level securityContext
```
$ istioctl x describe pod helloworld-v2-5b9c5cc9bc-qvpmn
Pod: helloworld-v2-5b9c5cc9bc-qvpmn
Pod Ports: 5000 (helloworld), 15090 (istio-proxy)
WARNING: Application pods should not run as user ID (UID) 1337\n
--------------------
Service: …
```
> istioctl describe: check UID 1337 for application pods

- pkg/test/framework/components/istio/operator.go
Without this, its impossible to run local tests as the secret is removed
after the first run, and subsequent installs fail due to longstanding
bugs in the webhook logic.
[ ] Docs
[ ] Networking
[ ] Security
> Do not cleanup remote secret

- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/security/authz/builder/builder.go
- pilot/pkg/security/authz/builder/extauthz.go
- pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-no-namespace-out1.yaml
- pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-no-namespace-out2.yaml
- pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-out1.yaml
- pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-out2.yaml
- pilot/pkg/security/authz/builder/testdata/http/custom-http-provider-out1.yaml
- pilot/pkg/security/authz/builder/testdata/http/custom-http-provider-out2.yaml
- pilot/pkg/security/authz/builder/testdata/tcp/custom-both-http-tcp-out1.yaml
- pilot/pkg/security/authz/builder/testdata/tcp/custom-both-http-tcp-out2.yaml
- pilot/pkg/security/authz/model/model.go
- pkg/bootstrap/config.go
- pkg/bootstrap/instance_test.go
- pkg/bootstrap/testdata/all_golden.json
- pkg/bootstrap/testdata/auth_golden.json
- pkg/bootstrap/testdata/authsds_golden.json
- pkg/bootstrap/testdata/default_golden.json
- pkg/bootstrap/testdata/running_golden.json
- pkg/bootstrap/testdata/runningsds_golden.json
- pkg/bootstrap/testdata/stats_inclusion_golden.json
- pkg/bootstrap/testdata/tracing_datadog_golden.json
- pkg/bootstrap/testdata/tracing_lightstep_golden.json
- pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
- pkg/bootstrap/testdata/tracing_stackdriver_golden.json
- pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
- pkg/bootstrap/testdata/tracing_tls_golden.json
- pkg/bootstrap/testdata/tracing_zipkin_golden.json
- pkg/bootstrap/testdata/xdsproxy_golden.json
- tools/packaging/common/envoy_bootstrap.json
Cherry-pick https://github.com/istio/istio/pull/32011
The API and feature is already in 1.10, this is a follow-up PR for better observability in master. This is the exact change in master, I will send a follow-up PR for release-note only.
[ ] Docs
[ ] Networking
[x] Security
> Cherry-pick dry-run observability support in 1.10

- tests/integration/pilot/common/routing.go
Without this, for the negative cases we make 135 calls (5 calls * 3
cluster * 3 retries in envoy * converge(3)). This seems to just end up
overloading the test and we end up with timeouts
[ ] Docs
[ ] Networking
[ ] Security
> Attempt to deflake instanceip test

- security/pkg/pki/ca/ca.go
- security/pkg/pki/ca/ca_test.go
- security/pkg/pki/ca/mock/fakeca.go
- security/pkg/pki/ra/k8s_ra.go
- security/pkg/server/ca/server.go
This patch proposes to simplify `Sign*` interfaces of `CertificateAuthority` by
passing a struct with cert field values instead. This may also help with further
extensions of the input options applied by the certificate generation.
[ ] Docs
[ ] Networking
[x] Security
> CA: simplify sign interfaces by passing a cert opts struct

- pkg/kube/secretcontroller/secretcontroller_test.go
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1384370286442319872
50ms seems too short to be reliable
[ ] Docs
[ ] Networking
[ ] Security
> Deflake sync timeout test

- tests/integration/pilot/multicluster_test.go
When testing external istiod, or running tests in any scenario where the test framework can/should not interact with istiod, we can ignore this test.
> skip bad remote secret when istiod is not in cluster

- pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
- pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
- security/pkg/k8s/configutil.go
- security/pkg/k8s/configutil_test.go
We are deploying istio in very large cluster, I reviewed current Istio code, and trying to see if there is unnecessary call to apiserver, and the only finding is in namespace controller istiod is getting namespace and configmap from apiserver directly even though the lister is there available in the code.
Our large cluster have around 15000 namespace now, and this PR change the kube client get to lister get to avoid thousands of get calls for namespaces and thousands of get calls for configmap.
[ ] Docs
[ ] Networking
[ ] …
> change kubeclient get call to lister call in namespace controller

- pkg/test/echo/common/util.go
- pkg/test/framework/components/echo/flags.go
Adds a flag --istio.test.echo.requestTimeout that applies for individual ForwardEcho calls (applies to all calls in the ForwardEcho, which may be > 1). 
Effectively we have
```
while totalTime < --istio.test.echo.callTimeout {
success := sendRequest{{timeout: --istio.test.echo.requestTimeout})
if success { break }
}
```
> add istio.test.echo.requestTimeout flag

- release/downloadIstioCandidate.sh
- release/downloadIstioCtl.sh
The downloads scripts use architecture starting with 1.6. The current download scripts don't support 1.10...
I'm not able to test the script in Linux.
Fixes: #32194
[ ] Docs
[ ] Networking
[ ] Security
> Update download scripts to support 1.10 as specified version

- tests/integration/tests.mk
Slightly improves compilation time. We already check vet in many other jobs (linter, etc).
> Disable vet in integration tests

- pkg/test/framework/components/istio/ingress.go
- pkg/test/framework/components/istio/ingress/interface.go
- pkg/test/framework/components/istio/util.go
- pkg/test/framework/components/opentelemetry/kube.go
- pkg/test/framework/components/opentelemetry/opentelemetry-collector.go
- pkg/test/framework/components/zipkin/kube.go
- pkg/test/framework/components/zipkin/zipkin.go
- tests/integration/pilot/ingress_test.go
- tests/integration/telemetry/stats/prometheus/nullvm/dashboard_test.go
- tests/integration/telemetry/tracing/opencensusagent/tracing_test.go
- tests/integration/telemetry/tracing/tracing.go
In environments such as AWS, `LoadBalancer` may be supported, but never set `LoadBalancer[0].IP` – instead it sets `Hostname`. 
Our framework should be robust to handle testing in such environments. 
We will also want to handle this for multicluster, this PR isn't concerned with that for now.
> test framework: support hostname loadbalancer in ingress

- pilot/pkg/model/push_context.go
This is already called in resolveVirtualServiceShortnames, which is
always called before getGatewayNames, so no need to resolve twice. In
the past we saw this function come up pretty high in profiles, so could
be worthwhile.
> Skip redundant call to resolveGatewayName

- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
Envoy's new timeout fields have multiple issues like timeouts not being honoured and wrong return codes etc. They are planning to revisit the design and implement it properly. So in the mean time, I am reverting to use deprecated fields (old  behaviour that we used to have) so that we can fix at our side till Envoy figures out the solution.
See https://github.com/envoyproxy/envoy/pull/16131 for more details.
Fixes https://github.com/istio/istio/issues/31317
https://github.com/istio/istio/issues/31616
[ ] Docs
[X] Networking
[ ] Security
Please check any characteristics that apply to this …
> revert to use deprecated values for timeouts

- tools/istio-iptables/pkg/dependencies/implementation.go
Instead of printing out stack trace when iptables fails, this patch provides
useful and actionable error messages by reusing the error hints from iptables
and exits gracefully.
Fixes https://github.com/istio/istio/issues/29487
[ ] Docs
[x] Networking
[ ] Security
> istio-iptables: gracefully exit on failure rather than panic

- pkg/test/framework/config.go
Currently, we don't log these at all unless there is an error, which
isn't too useful since we already return an error with the same info.
This changes moves it to always log, but at the debug level since it is
pretty spammy
[ ] Docs
[ ] Networking
[ ] Security
> tf: properly log apply/delete YAML, but at debug level

- pilot/pkg/bootstrap/server.go
Fixes https://github.com/istio/istio/issues/32023
(cherry picked from commit 439c0ab15027113a70f8076e4c399bcb77532746)
[ ] Docs
[ ] Networking
[ ] Security
> [1.8] Do not write namespace configmap for k8s cert provider (#32052)

- istioctl/cmd/tag.go
- istioctl/cmd/tag_test.go
* Allow external control plane to bypass in-cluster Istiod pod check
* Add check to ensure we don't have overlapping webhooks. For example:
```
$ grun ./istioctl/cmd/istioctl x revision tag generate istio-1611 --revision istio-1611
Error: creating tag would conflict:
Error [IST0139] (MutatingWebhookConfiguration istio-revision-tag-istio-1611 ) Webhook overlaps with others: [istio-sidecar-injector-istio-1611/sidecar-injector.istio.io]. This may cause injection to occur twice.
```
> Improvements to tag command

- pilot/pkg/model/sidecar_test.go
Adds a missing test case in sidecar that validates egress hosts by port and wildcard egress brings correct services.
[ ] Docs
[X] Networking
[ ] Security
> add additional test case for sidecar

- pilot/pkg/networking/plugin/authz/authorization.go
MeshConfig is already populated into the push context and passed to authz-plugin
callbacks as inputs. We can simply get trust domains from it instead to build
filters.
[ ] Docs
[ ] Networking
[x] Security
> authz-plugin: get trust domain from MeshConfig to build filters

- pilot/pkg/xds/debug.go
Currently there are some issues with the debug interface code. We have a
lot of code just dedicated to json output. This leads to lot so of code
duplication, slightly different error handling in each method, and hand
written json marshalling (which has some bugs resulting in incorrect
response).
This refactors this to clean things up a bunch. Common functions
extracted out:
* `writeJson` and protobuf variant write an object as json and handle
setting content type, etc while handling errors
* `getDebugConnection` handles getting a connection based on `proxyID`
query param, and associated error handling.
We don't have that great test coverage here. I did go through each endpoint and manually test.
> Improve debug interfaces json and general refactor

- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/components/namespace/kube.go
- pkg/test/framework/resource/flags.go
- pkg/test/framework/resource/settings.go
- pkg/test/framework/resource/version.go
- pkg/test/framework/resource/version_test.go
- pkg/test/framework/test.go
Should be able to run tests against multiple revisions without specifying versions for those revisions (unspecified revs are assumed to be latest versions). Now, we can express "I want to deploy echoes for revisions `A`, `B` and `C`. `A` and `B` are on 1.9.3 and `C` is on latest" as `--istio.test.revisions A=1.9.3,B=1.9.3,C`.
Renamed from `istio.test.versions` to `istio.test.revisions` since version is just one piece of config associated with a revision, in the future we probably want to pass other things like per-revision config overlays.
[ ] Docs
[ ] Networking
[ ] Security
Please check …
> test framework: move from IstioVersions to Revisions

- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/security/authz/builder/logger.go
- pkg/test/echo/client/parsedresponse.go
- pkg/test/framework/components/echo/kube/instance.go
- pkg/util/istiomultierror/util.go
- tests/integration/pilot/common/routing.go
Current we get horrible errors like:
```
traffic.go:180: 1 error occurred:
* failed calling a->'://fake.service.local?&protocol=tcp&server=127.0.0.1:0/': call failed from a to dns://fake.service.local?&protocol=tcp&server=127.0.0.1 (using dns): timeout while waiting after 20 attempts, 0/3 successes (last error: 1 error occurred:
* unexpected dns response: wanted [], got [1.2.3.4]
)
```
With this change, it looks instead like:
```
traffic.go:180: failed calling a->'http://b-alt-3:12345/': call failed from a to http://b-alt-3:12345 (using http): timeout while waiting after 5 attempts, 0/3 successes (last error: expected response code 123, got "200")
```
(different test failure, but same concept)
This is done using `multierror.ErrorFormat`. We used this in a few places, but I refactored it …
> Avoid bad multierror format

- cni/deployments/kubernetes/Dockerfile.install-cni
Added support for both 
distroless : gcr.io/istio-release/distroless
and 
default : gcr.io/istio-release/base
base image for install-cni
> Support for both distroless and default base image for install-cni

- pkg/test/framework/components/echo/echo.go
- pkg/test/framework/components/echo/echotest/filters.go
- pkg/test/framework/components/echo/echotest/filters_test.go
- pkg/test/framework/components/echo/echotest/run.go
- pkg/test/framework/components/echo/echotest/setup.go
- pkg/test/framework/components/echo/instances.go
- pkg/test/framework/components/istio/helm.go
- pkg/test/framework/components/istio/ingress.go
- pkg/test/framework/components/istio/ingress/interface.go
- pkg/test/framework/components/istio/istio.go
- pkg/test/framework/components/istio/operator.go
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/common/traffic.go
- tests/integration/pilot/ingress_test.go
- tests/integration/security/jwt_test.go
- tests/integration/security/pass_through_filter_chain_test.go
- tests/integration/security/sds_ingress/util/util.go
- tests/integration/security/sds_tls_origination/egress_gateway_origination_test.go
- tests/integration/security/util/authn/authn_util.go
- tests/integration/security/util/rbac_util/util.go
- tests/integration/telemetry/stats/prometheus/nullvm/dashboard_test.go
* add util to echotest to run from Ingress to each configured destination
* convert gatewayCases
* one test actually hits all destinations
* one test only hits one destination (pod a, no need to hit VMs)
* others do not care about workloads
* DRY up some of the logic for TrafficTestCase
> convert gateway test to be workload agnostic

- pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go
- pkg/kube/inject/inject.go
- pkg/kube/inject/webhook.go
- pkg/kube/util.go
From go pprof analysis, the metadata deepCopy has so much memory allocation.
> optimize GetDeployMetaFromPod

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
Follow by #31929, 
Previously we call `applyTrafficPolicy` twice for outbound cluster
1. in `buildDefaultCluster`
2. in `applyDestinationRule`
In this pr, the first call is removed, but the traffic policies are merged. So only the second call should be enough.
> Prevent twice calling applyTrafficPolicy for outbound cluster

- istioctl/cmd/internal-debug.go
- istioctl/cmd/proxystatus.go
- istioctl/cmd/version.go
- istioctl/pkg/multixds/gather.go
- istioctl/pkg/writer/pilot/status.go
- istioctl/pkg/xds/client.go
- pilot/pkg/xds/debug.go
- pkg/test/framework/components/istio/operator.go
- pkg/test/framework/components/istioctl/istioctl.go
- pkg/test/framework/components/istioctl/kube.go
- pkg/test/kube/dump.go
* Support external istiod without XDS Address. If no pod are found for
the revision, we will fetch the URL from the webhook as a fallback
mechanism.
* Improve the output. Currently, we always fetch from all istiods and
then emit some non-json output to distinguish the requests. This is hard
to read/parse in the case we do want all requests, and excessive
verbosity/performance when we only care about one. Instead, expose a
--all flag, off by default. When set, we will query all Istiod's, but
put the response in a structured JSON blob. When unset, we just output
the response from Istiod directly.
* Switch Dumping or configz and ndsz in test framework to use the new
command. This both tests the command and makes tf dumping work for
external Istiod tests. I would also like bug-report to do …
> Improve internal-debug and use it in tf Dump commands

- tests/integration/pilot/istioctl_test.go
Appears to just occasionally take more than 20s to fully terminate the
pod
https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot-k8s-tests_istio_postsubmit/1387950502116855808
as an example
[ ] Docs
[ ] Networking
[ ] Security
> Deflake TestAddToAndRemoveFromMesh

- pilot/pkg/serviceregistry/kube/controller/controller.go
These logs are useful when we debug issues in istio that revolve around stale endpoints and 503 upstream errors stemming from those. 
We have many pods in our clusters that have the same generic names and namespaces are the only way of reliably identifying the stale pods/endpoints
[ ] Docs
[X] Networking
[ ] Security
[ ] Does not have any changes that may affect …
> improve warn logs of getPodLocality

- pilot/pkg/model/context.go
- pilot/pkg/model/xds_cache.go
- pilot/pkg/networking/apigen/apigen.go
- pilot/pkg/networking/grpcgen/grpcgen.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/cds.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/debuggen.go
- pilot/pkg/xds/delta.go
- pilot/pkg/xds/delta_test.go
- pilot/pkg/xds/ecds.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/gen.go
- pilot/pkg/xds/lds.go
- pilot/pkg/xds/nds.go
- pilot/pkg/xds/pcds.go
- pilot/pkg/xds/rds.go
- pilot/pkg/xds/sds.go
- pilot/pkg/xds/sds_test.go
- pilot/pkg/xds/statusgen.go
- pilot/pkg/xds/xds_cache_test.go
- security/pkg/nodeagent/sds/sdsservice.go
XDS introduced a `discovery.Resource` wrapper a while back. This is required for delta XDS.
When using delta, we need to populate the `name` field. To do this, we marshaled the XDS response to inspect the name, which is hacky and extremely bad for performance.
Instead, all generators now return this wrapper. For Sotw, we simply unwrap it.
This of course has a performance cost, but IMO its worth it, only ~1% more memory allocated:
```
name                                     old time/op        new time/op        delta
RouteGeneration/gateways-6                     43.4ms ± 1%        43.4ms ± 1%    ~     (p=1.000 n=4+4)
RouteGeneration/gateways-shared-6               175ms ± 5%         171ms ± 3%    ~     (p=0.343 n=4+4)
RouteGeneration/empty-6                         829µs ± 4% …
```
> delta: use discovery.Resource wrapper instead of raw any

- pilot/pkg/model/context.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/core/v1alpha3/name_table.go
- pilot/pkg/xds/endpoint_builder.go
- pilot/pkg/xds/ep_filters.go
A few small future-proofing changes to better handle the unset ("") network value
* the change to name_table is probably required
* change to ep_filters will probably never matter, since we don't get a NetworkGatewaysByNetwork for `""` 
* added utils to wrap up this logic
* moved GetNetworkView() to be an instance method. This is mostly aesthetic. We could cache it on the Node or NodeMetadata if it gets called a lot.
> handle unset network

- pkg/test/framework/components/echo/echoboot/echoboot.go
- pkg/test/framework/components/echo/echoboot/flags.go
Allows specifying `--istio.test.echo.configs /path/to/echos.yaml`, which contains input similar to echogen (#32486). The provided `echo.Configs` will be appended as if calling `builder.WithConfig` in the setup for any suite/test. 
This is useful when we want to test against something very specific, that isn't necessarily worth pulling into every CI run, or to add custom CI jobs that test different workloads, without adding logic in the Go code to do so. 
Example:
```yaml
- Service: centosVM
Namespace: echo
DeployAsVM: true
VMDistro: Centos8
``` 
This is also compatible with #32216. The file given to `--istio.test.config` could contain:
```yaml
istio:
test:
echo:
configs:
- Service: centosVM
Namespace: echo
DeployAsVM: true
VMDistro: Centos8
```
or
```yaml
istio:
test:
echo:
configs: …
```
> allow specifying additional echo workloads

- pkg/test/framework/components/echo/echoboot/flags.go
- pkg/test/framework/components/environment/kube/flags.go
- pkg/test/framework/components/environment/kube/settings.go
- pkg/test/framework/config/config.go
- pkg/test/framework/config/map.go
- pkg/test/framework/resource/version.go
The last change required to configure pretty much any test framework flag completely in one file. I can run the tests with multiple clusters, and istiodless remotes via: `go test ./tests/integration/pilot/... --istio.test.config ~/test-config.yaml` + the following config file:
```yaml
istio:
test:
istio:
istiodlessRemotes: true
kube:
topology:
- kind: Kubernetes
clusterName: primary
meta:
kubeconfig: ~/kubeconf/cluster-1.yaml
- kind: Kubernetes
clusterName: remote
primaryClusterName: primary
meta:
kubeconfig: ~/kubeconf/cluster-2.yaml
fakeVM: false
```
If I have several sets of clusters for manual testing, I could just store the `topology` bit in separate files (e.g. `aws.yaml`, `gke.yaml`) then provide the path instead:
```yaml
istio:
test:
kube:
topology: ~/topologies/aws.yaml
```
> support embedding topolgoy in istio.test.config

- istioctl/cmd/kubeinject.go
For external istiod, this may not exist
Unfortunately we don't really have any way to test this since we don't
have full external istiod testing. I did manually test though
> Stop requiring configmap for `kube-inject`

- istioctl/cmd/dashboard.go
To fix https://github.com/istio/istio/issues/32600
The current default was `istio-system` which was aligned according to other addon components eg: Kiali, Jaeger. But as envoy dashboard can work for both core components as well as other pods, defaulting to the `default` namespace is more appropriate.
In default namespace.
```
$ istioctl dashboard envoy deployment/productpage-v1
http://localhost:15000
$ istioctl dashboard envoy deployment/productpage-v1.default
http://localhost:15000
$ istioctl dashboard envoy deployment/productpage-v1 -n default
http://localhost:15000
```
In another namespace.
```
$ istioctl d envoy istio-ingressgateway-758d94b574-mpc7x
Error: could not build port forwarder for Envoy sidecar istio-ingressgateway-758d94b574-mpc7x: failed retrieving pod: pods …
```
> Fix: istioctl dashboard envoy does not default namespace

- pilot/pkg/bootstrap/server.go
The k8s JWT authenticator requires the multicluster registry to be initialized, so we build it later.
[ ] Docs
[ ] Networking
[X ] Security
[X ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
> Adjust the order of authenticators

- pkg/istio-agent/agent.go
- pkg/istio-agent/xds_proxy.go
Adding additional checks for the existence of root CA certs for the XDS
connection. This helps XDS initialization to fail early, instead of obscure
envoy errors.
[ ] Docs
[x] Networking
[x] Security
> istio-agent: add checks for XDS root CA existence

- pilot/pkg/security/trustdomain/bundle.go
- pilot/pkg/security/trustdomain/bundle_test.go
This avoids an empty string to be added into the new principal list replaced
when the principal is not presented in a valid SPIFFE ID format.
[ ] Docs
[ ] Networking
[x] Security
> trustbundle: return error when replacing td in principal fails

- pilot/pkg/bootstrap/server.go
- pilot/pkg/secrets/kube/multicluster.go
For https://github.com/istio/istio/issues/32662
Eventually I'd like to refactor this such that:
```
remote secrets controller
/\
client, stop
/  \
k8s svc reg    secrets controller
```
1. To share a single k8s client, stop channel for the entire cluster
2. The remote secrets controller can be the one stop shop for checking if informers are synced (as long as we're checking _after_ registering informers)
With that structure, if we add more per-cluster components, we don't have to keep expanding our `cachesSynced` check.
> wait for secrets cache sync

- istioctl/pkg/util/handlers/handlers.go
- pkg/kube/portforwarder.go
To fix https://github.com/istio/istio/issues/32672
**Before**:
```
$ istioctl d envoy istio-ingressgateway-758d94b574-mpc7x
Error: could not build port forwarder for Envoy sidecar istio-ingressgateway-758d94b574-mpc7x: failed retrieving pod: pods "istio-ingressgateway-758d94b574-mpc7x" not found
$ istioctl d envoy productpage-v1-6b746f74dc-2xdzj.istio-system
Error: failed retrieving: deployments.apps "productpage-v1" not found
```
**After**:
```
$ istioctl d envoy istio-ingressgateway-758d94b574-mpc7x
Error: could not build port forwarder for Envoy sidecar istio-ingressgateway-758d94b574-mpc7x: failed retrieving: pods "istio-ingressgateway-758d94b574-mpc7x" not found in the "default" namespace
$ istioctl d envoy productpage-v1-6b746f74dc-2xdzj.istio-system
Error: failed retrieving: …
```
> istioctl dashboard: improve port-forward error message to mention namespace

- bin/retry.sh
This makes output nicer as commands are run with a tty so we can get
interactive mode for buildx, etc
> Preserve tty when running under `bin/retry.sh`

- pilot/pkg/bootstrap/certcontroller.go
- pilot/pkg/bootstrap/server.go
- pilot/pkg/bootstrap/server_test.go
Today, we bind to ports immediately, then later call `server.Serve`. The
result is that clients connecting will hang until .Serve is called.
Depending on the client (long or no timeout)  and the state of Istiod (single instance stuck not ready), this may
lead to clients being stuck on a bad instance instead of reconnecting to
a healthy one.
Additionally, this prevents any usage of TCP probes, as we mark
ourselves "ready" immediately when we may not actually be for quite a
while longer.
Implementation note: `ListenAndServe` is not used since it doesn't allow
us to fail synchronously if we fail to listen (typically port conflict).
[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API …
> Do not bind ports until we are ready

- pilot/pkg/bootstrap/istio_ca.go
- security/pkg/pki/ca/ca.go
Currently, the self generating key cert for testing or local (i.e., debug mode)
in non-K8s run are produced within the logic of plugged cert mode of Istio CA,
with the CA being considered as the `plugged` type too. This is not reasonable
and somewhat leads to confusions.
This patch separates the logic to create key cert and IstioCAOptions of Istio CA
in debug mode (using in-memory root CA, no K8S access and no ca key file) into
`NewSelfSignedDebugIstioCAOptions` and removes some unnecessary checks.
[ ] Docs
[x] Networking
[ ] …
> ca: separate self-signed debug mode without K8s from plugged cert mode

- tests/integration/pilot/common/routing.go
Without explicitly setting count=1, we default to sending 15 calls with
converge=3 meaning 45 calls must succeed in a row for the test to pass.
This leads to a lot of flakes. After analyzing 10+ of these, it seems
its just due to resource contention in CI, not any bugs in Istio,
triggering this.
This drops tests that can be exercised with a single request to do so.
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) …
> Deflake pilot mc tests by sending single requests

- istioctl/cmd/tag.go
- istioctl/cmd/tag_test.go
Prior to this PR we relied on the istiod for a given tag's revision to patch the CA bundles into the webhook. This PR makes it so that we use the CA bundle from the revision's webhook when first creating the tag webhook. This makes it so that we can use revision tags against arbitrarily old control planes that may not know how to patch newer webhooks.
The only problem I can think of here is if creating the tag webhook *right after* creating the CP (this could be a part of people's CI pipelines) we may pull out an empty webhook, and if the revision is older than 1.10 it would never get patched in
[ ] Docs
[ ] Networking
[ ] Security
[ ] …
> Make revision tags work against older versions

- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/httproute.go
Its common for a route request for a route we do not know about if a
Gateway is recently deleted (due to listener draining).
Pre 1.1, if we missed a route, we closed the ADS connection. This was
obviously wrong, so we introduced a patch to instead make it send a
route back, but with no VHosts defined:
https://github.com/istio/istio/pull/13924.
This seemed to work (and has been around for ~2 years now), but the
behavior isn't quite right. If you send continuous requests to a gateway
then remove the Gateway (triggering listener drain), you will see
requests go to 404 and only later is the connection eventually torn
down. This is because when the listener is removed we will trigger a RDS
push, which will find no route, and thus send an empty route config.
Envoy will treat that as VHosts …
> Switch handling of missing routes to send no response instead of empty

- bin/retry.sh
The error is already output to stdout/stderr, so no need to output it
again - and the file doesn't exist in error cases anyways so its not
useful to attempt it.
[ ] Docs
[ ] Networking
[ ] Security
> do not read empty file on retry.sh error

- pkg/test/echo/server/endpoint/grpc.go
- pkg/test/echo/server/endpoint/http.go
Try to help diagnose some cases where suddenly readiness probes fail with connection refused
> Log listener termination in echo server

- releasenotes/notes/19300.yaml
- releasenotes/notes/30067.yaml
- releasenotes/notes/30683.yaml
- releasenotes/notes/31075.yaml
- releasenotes/notes/31186.yaml
- releasenotes/notes/31403.yaml
- releasenotes/notes/31573.yaml
- releasenotes/notes/31779.yaml
- releasenotes/notes/31797.yaml
- releasenotes/notes/31853.yaml
- releasenotes/notes/auto-mtls-passthrough.yaml
- releasenotes/notes/inbound-passthrough.yaml
- releasenotes/notes/inbound-patch.yaml
- releasenotes/notes/pilot-discovery-scoped-namespaces.yaml
- releasenotes/notes/revision-tag-command.yaml
- releasenotes/notes/scope-push-by-sidecar-changes.yaml
- releasenotes/notes/vm-cleanup-iptables.yaml
- releasenotes/notes/vs-ineffective-warning.yaml
This fixes several release notes in 1.10 that don't match the schema.
@istio/release-managers-1-10 this should be all of the release notes that got missed in the generation.
> Fix broken release notes in 1.10 only

- pilot/pkg/config/kube/crdclient/client.go
As describing in [issue 32567](https://github.com/istio/istio/issues/32567), make sure the API of `/debug/resourcesz` and `Istiod logs` have the same behavior. 
[ ] Docs
[x] Networking
[ ] Security
> fixed issue#32567

- pilot/cmd/pilot-agent/status/server.go
Fixes https://github.com/istio/istio/issues/32760
What happens:
* IP silently parses wrong, causing us to use default LocalAddr
* Without ::6 address, our requests go through iptables
* In the test, we set mTLS strict mode. This causes health check
failures. If the test does not complete before the failureThreshold is
reached, the test fails since the pods are "not ready"
> Fix local address for ipv6 probes

- pilot/pkg/dns/proxy.go
Some times we are seeing 	
`upstream failure: read udp 10.110.244.222:54257->172.20.0.10:53: i/o timeout	protocol=udp edns=false`
in a busy pod. This PR increases the timeouts. Even though the client documentation https://github.com/miekg/dns/blob/40060b4a4b85b14867003343f64bfd5cd64ea256/client.go#L39 says it is disabled if it is not set, it enforcing 2s timeout https://github.com/miekg/dns/blob/40060b4a4b85b14867003343f64bfd5cd64ea256/client.go#L73
[ ] Docs
[X] Networking
[ ] Security
[X] Does not have any …
> increase dns timeouts

- pkg/config/mesh/watcher.go
- pkg/config/mesh/watcher_test.go
Basically what happens is at the end of the test, the file is removed.
The mesh watcher responds to DELETE events, but we ignore the error that
file is not found and call the handlers again.
Instead, if we cannot process the update, we should just ignore it (as
we did prior to recent changes).
The changes in _test.go are not required, just make things a bit
cleaner.
Fixes https://github.com/istio/istio/issues/32796
> Fix flakes in TestMultiWatcherShouldNotifyHandlers

- pilot/cmd/pilot-discovery/main.go
- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/bootstrap/server.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/fake.go
- pilot/pkg/serviceregistry/kube/controller/multicluster_test.go
Since d89c6a624cfd0962e2ed25238ec671baebda0ca5, this option was not respected.
It seems there is no complain, and maybe we can delete this option. And instead, using the new option `MeshConfig.DiscoverySelectors`
[ ] Docs
[ ] Networking
[ ] Security
> Remove watchedNamespace

- istioctl/cmd/dashboard.go
- pilot/docker/Dockerfile.proxyv2
- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
- pkg/config/validation/extensionprovider.go
- releasenotes/notes/32588.yaml
This PR introduces initial Apache SkyWalking support. This PR depends on istio-proxy which includes these fixes (https://github.com/envoyproxy/envoy/pull/16203, https://github.com/envoyproxy/envoy/pull/16264).
[ ] Docs
[ ] Networking
[x] Policies and Telemetry
[ ] Security
> initial Apache SkyWalking tracer support

- pilot/pkg/model/context.go
- pilot/pkg/networking/apigen/apigen.go
- pilot/pkg/networking/grpcgen/grpcgen.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/bootstrapds.go
- pilot/pkg/xds/cds.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/debuggen.go
- pilot/pkg/xds/delta.go
- pilot/pkg/xds/ecds.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/lds.go
- pilot/pkg/xds/nds.go
- pilot/pkg/xds/pcds.go
- pilot/pkg/xds/rds.go
- pilot/pkg/xds/sds.go
- pilot/pkg/xds/sds_test.go
- pilot/pkg/xds/statusgen.go
- pilot/pkg/xds/xdsgen.go
- security/pkg/nodeagent/sds/sdsservice.go
Moves xds generator logs to central place and individual generators return the metadta
[ ] Docs
[X] Networking
[ ] Security
> add log metadata for Xds Generators

- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/testdata/benchmarks/knative-gateway.yaml
This is to help optimize and track regressions for one of the largest usages of Istio. Their usages of routes have been performance sensitive for XDS in the past so a good test case
> Add benchmark config for example knative setup

- pkg/test/echo/server/forwarder/instance.go
When `Count > maxConcurrency`, a timeout will give us `failed acquiring semaphore: context deadline exceeded` if all requests in `Count` haven't at least started. This isn't very useful when trying to tune timeouts for the failing test. 
* Calculate the average response times for each call
* Include the # of requests that were completed even when all requests haven't been enqueued.
> get more info on echo timeouts

- bin/retry.sh
Otherwise in CI we try to output things that don't work. Now we get a
TTY IFF the caller has one
I think I finally got this right...
> Make bin/retry.sh only use TTY if parent has TTY

- pilot/pkg/serviceregistry/kube/controller/controller.go
fixes https://github.com/istio/istio/issues/32916
When cross-cluster workload entries are enabled, all service registries will have workload instances, so we don't exit early here. It's possible the registry doesn't have the service though, and it's easy enough to check.
> fix log spam when service won't exist

- pkg/test/framework/scope.go
I want to get more info about how much time dumps take, since we're doing it at every level of subtest (there is definitely some level of redundancy here).
Depending on the results. it may make sense to add a `NoDump` option to TestContext. We can use this in `echotest` in the cases where we know there isn't a config change per-cluster, and we can rely on the dump from the next level up. 
This PR: 
* dump every resource in parallel. not sure if this is a good idea – if the Dump impl has it's own concurrency, this may not give us any real gains
* log the time it takes to dump
> tf: attempt to speed up resource dump

- istioctl/pkg/verifier/verifier.go
- pilot/pkg/model/push_context.go
- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pkg/test/framework/components/echo/common/call.go
- tools/bug-report/pkg/cluster/cluster.go
This PR represents the first step towards upgrading the linter used in this project to be able to detect problematic references to loop variables.  This issue has caused a few known issues recently (example: integration test framework code). As a result, there is a desire to warn when issues potentially arise.
The fixes in this PR were guided by a local run of the linter, upgraded to version 1.40.1 with `exportloopref` enabled.  Output:
```
$ ./common/scripts/lint_go.sh 
INFO [config_reader] Used config file common/config/.golangci.yml 
INFO [lintersdb] Active 19 linters: [deadcode errcheck exportloopref gocritic gofumpt goimports golint gosimple govet ineffassign lll misspell staticcheck structcheck stylecheck typecheck unconvert unparam varcheck] 
INFO [loader] Using build tags: [integ] …
```
> fix (potential) loopref issues in codebase

- pilot/pkg/model/config.go
- pilot/pkg/model/sidecar.go
It may not be suitable to use crc32 in this scenario
``` shell
$ cat ./main.go 
package main
import (
"fmt"
"hash/crc32"
)
func main() {
a := crc32.ChecksumIEEE([]byte("xxx-c294f5b1"))
b := crc32.ChecksumIEEE([]byte("xxx-fc26498f"))
fmt.Println(a == b, a, b)
}
$ go run ./main.go  
true 2816933872 2816933872
```
[ ] Docs
[x] Networking
[ ] Security
[x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior …
> Avoid high-probability hash collisions, use md5 instead of crc32

- istioctl/pkg/writer/envoy/configdump/route.go
The `+ x more...` format is stolen from kubectl
BEFORE
```
NAME                                DOMAINS                    MATCH                  VIRTUAL SERVICE
http.80                             hello.default              /*                     hello-ingress.default
http.80                             hello.default              /*                     hello-ingress.default
http.80                             other.bar                  /*                     echo.default
http.8081                           hello-private.default      /*                     hello-private-ingress.default
http.8081                           hello-private.default      /*                     hello-private-ingress.default
http.8081                           hello.default              /* …
```
> Improve format of `istioctl pc r` with multiple domains

- pilot/pkg/xds/xdsgen.go
* We were always logging EDS incremental pushes at info level
* We never logged additional info
> Fix ADS logging

- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_simulation_test.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pilot/pkg/serviceregistry/serviceentry/conversion_test.go
This is intended to be a minimal, backport-able change to allow Knative to work; currently Istio+Knative is extremely fragile and breaks under situations when Services are created out of order.
The long term solution is in https://github.com/istio/istio/pull/32653, but will take many months to be adopted.
The tl;dr is that we add an explicit label on the service and then we no longer try to translate the Gateway port to a targetPort for that service. This avoids the ambiguity that Knative has as shown in the test. Without the change, the test will result in a NACK.
cc @arturenault
> Workaround conflicting port mapping in Gateway

- pilot/pkg/bootstrap/servicecontroller.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/multicluster.go
- pilot/pkg/serviceregistry/kube/controller/multicluster_test.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/eds_test.go
Fix a bug for sa update. Previously we may miss serviceaccount.
This can happen in this scenario. 
There is a hybrid env with multi-clusters, including pods and workload entries. 
Let's say cluster 1: pods all have serviceaccount `sa`, and workloadEntries has `sa-vm1`
cluster 2: pods all have serviceaccount `sa`, and workloadEntries has `sa-vm2`
1. When workloadEntries in cluster1 are all deleted, then serviceaccounts will be updated to only `sa` and miss `sa-vm2`.
2. When only part of workloadentry of cluster1 deleted,  then serviceaccounts will be updated to only `sa` and miss `sa-vm1` and miss `sa-vm2`. Also this will trigger a full push, which is unneccessary.
[ ] Docs
[ ] Networking
[ ] Policies and …
> Update serviceaccounts correctly when service delete or eds update

- tests/integration/tests.mk
This is to see if it improves our IO usage on our nodes, or if its not
the root cause. Currently we are hitting over 120mb/s writes which is
leading to massive IO throttling
This of course will make debugging test failures ~impossible so we should merge only for a day or 2 and revert
> Temporarily disable CI dumping

- pilot/pkg/secrets/kube/multicluster.go
- pkg/kube/secretcontroller/secretcontroller.go
- releasenotes/notes/istiod-cluster-metric.yaml
This PR adds a new gauge to `istiod`. The gauge monitors the number of total clusters known to `istiod`, dimensioned by `cluster_type` ([`local`, `remote`]).
This PR is intended to provide insight into MC scenarios beyond the workload logs (that also monitor these scenarios). At the moment, no counters are kept for failures to initialize remote clusters, etc.  Depending on reviewer taste, that can follow or be added to this PR.
> Add monitoring for clusters known to istiod

- pkg/envoy/agent.go
Running istio(pilot-agent and envoy) on virtual machine, when systemctl stop istio, the istio-pilot process is terminated, but the envoy process is still running.
(There is another fix about systemd #33040 )
`envoy.Agent` in istio-agent send `errAbort` to `a.abortCh`.
```go
func (a *Agent) terminate() {
log.Infof("Agent draining Proxy")
e := a.proxy.Drain()
if e != nil {
log.Warnf("Error in invoking drain listeners endpoint %v", e)
}
log.Infof("Graceful termination period is %v, starting...", a.terminationDrainDuration)
time.Sleep(a.terminationDrainDuration)
log.Infof("Graceful termination period complete, terminating remaining proxies.")
a.abortCh <- errAbort         //<--- sending errAbort to abortCh
log.Warnf("Aborted all epochs")
}
```
And expect envoy goroutine in istio-agent to kill …
> fix envoy process exit bug

- pilot/pkg/status/report.go
- pilot/pkg/status/reporter.go
- pilot/pkg/status/reporter_test.go
- pilot/pkg/status/resourcelock.go
- pilot/pkg/status/resourcelock_test.go
- pilot/pkg/status/state.go
Will be used for gateway controller as part of
https://docs.google.com/document/d/1wgYnCnypxYMc_nGPZsLr7JIqTe727TwKiNopPkrJ2-k/edit#
This changes to allow different types as the input, and stop using
pointers everywhere when we don't need to, to avoid excessive heap
allocations and un-ergonomic usage
> Refactor status resource queue to allow reuse

- pkg/test/framework/components/istio/operator.go
- pkg/test/kube/dump.go
On implementations of our `cluster.Cluster` interface in the test framework, such as `staticvm`, we embed a nil pointer for `kube.ExtendedClient` that we shouldn't interact with. 
Ideally we'd make this transparent via a mock but that comes with it's own problems: 
* How do callers handle empty responses, or "this is a mock" error
* Codegen may be required to generate such a mock/keep it up to date. 
This protects a few places from using the nil client, but our concept that a tf cluster is a place where workloads live is a bit confusing and will probably continue to be violated.
> avoid calling kubeclient methods on non kube clusters

- pkg/test/framework/components/echo/echotest/run.go
- pkg/test/framework/components/echo/echotest/setup.go
- pkg/test/framework/scope.go
- pkg/test/framework/testcontext.go
Related to https://github.com/istio/istio/issues/33034
We dump duplicate debug info, which is quite large, at each scope. For deeply nested subtests this gets big quick. If we're confident the setup doesn't change, we can just rely on the larger/later dump that comes from parent scopes. 
* Added `SkipDumping` to `TestContext` to disable dumping at a scope. 
* Automatically call `SkipDumping` in `echotest` when none of the `SetupX` methods are called. 
For now we only get benefit for echotest compliant tests. Other tests can either convert to echotest, or take the riskier approach of calling `SkipDumping` themselves in the right places.
> selectively skip dumping at subscopes with no additional setup

- pkg/istio-agent/agent_test.go
Avoid failures like
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1396890790558437376#1:build-log.txt%3A26542
causing 'subtest may have called FailNow on a parent test'
> Fail with correct t in TestAgent

- pkg/test/framework/components/echo/cmd/echogen/echogen_test.go
Previously this depended on an env var set in the makefile to generate
the intended result of the golden file
> Allow running echogen test outside of makefile

- pilot/pkg/config/memory/controller.go
- pilot/pkg/config/memory/store.go
- pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
- pkg/istio-agent/xds_proxy.go
Fixes https://github.com/istio/istio/issues/30510
This consists of two bugs, one impacting tests only and the other real:
* A race between access and write of initialRequest. Before we may hit
this sequence:
* Read initial request version 1
* Set and immediately send version 2
* Send version 1
Now we have consistent locking so we are always sending the latest
version
* Update the in-memory store to reject updates where resource version is
not set properly. This avoids races where an update occurs at the same
time as a patch and reverts a change. This matches Kubernetes behavior,
and thus is a test-only bug, as the memory store is only used for tests.
> Fix TestXdsProxyHealthCheck test flakes

- pilot/pkg/model/context_test.go
Otherwise test success is not reported
> Exit early instead of t.Skip

- bin/retry.sh
- tools/dump-docker-logs.sh
- tools/istio-docker.mk
* Only dump in CI to avoid spamming developers
* Dump a lot more info
* make bin/retry.sh slightly more flexible. Not used in this PR but in
another
I will also turn on debug logs in another PR (in tools)
[ ] Docs
[ ] Networking
[ ] Security
> Better docker log dump

- pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
- security/pkg/k8s/configutil.go
Basically, we were waiting for the configmap to exist in the real
client, but then reading from the informer. This leads to a rare case
where the two are temporarily out of sync.
Upon fixing this, I realized a deeper issue - we are mutating objects
from the informer cache. This fixes that as well.
Fixes https://github.com/istio/istio/issues/32511
> Fix TestNamespaceController issues

- pkg/test/echo/server/forwarder/http.go
- pkg/test/echo/server/forwarder/protocol.go
- tests/integration/pilot/common/routing.go
Before the PR, the test app will fail to parse the HTTP request if the path includes invalid encoded characters. After the PR, the test app is able to send whatever we put in the path part in the request.
[ ] Docs
[ ] Networking
[ ] Security
> update test app to use the raw path

- pkg/kube/inject/inject.go
Non-functional backport of https://github.com/istio/istio/pull/32928 to prevent breakage of 1.11 injector configmap on 1.10.
> injector: define empty template var

- pkg/test/util/file/file.go
We attempt to normalize `$ARTIFACTS` which is not there locally. I think
we can just make the function not fail for unset input
[ ] Docs
[ ] Networking
[ ] Security
> Hide error message when running test outside of CI

- pilot/pkg/xds/ads.go
> Redundant a

- pilot/pkg/xds/delta.go
- pilot/pkg/xds/xdsgen.go
Switch from `PUSH: CDS for ...` back to `CDS: PUSH for ...`. This
restores the old behavior we have had since 1.0.
This log is commonly parsed so I don't really want to break it, I think
it was an accidental change anyhow
[ ] Docs
[ ] Networking
[ ] Security
> Fix change in ads log format

- security/pkg/nodeagent/cache/secretcache.go
Because of this debounce logic we are seeing some events are missed (probably a race condition in debouncer) . I think debouncer is strictly not needed here because inotify will trigger write event after write is actually complete and we are checking for write events already.
[ ] Docs
[X] Networking
[X] Security
[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, …
> remove debounce logic from secret watcher

- tools/bug-report/pkg/bugreport/bugreport.go
- tools/bug-report/pkg/kubectlcmd/kubectlcmd.go
This avoids running this accidentally when something (istioctl) just
imports the package
[ ] Docs
[ ] Networking
[ ] Security
> Remove init polling task in bug-report

- pkg/test/framework/components/echo/kube/pod_controller.go
Calls are in goroutines. There is no reason to have this function block,
as we don't do anything after stop is closed. So we can save some
goroutines.
[ ] Docs
[ ] Networking
[ ] Security
> tf: Avoid not needed wait on stop channel

- tests/integration/pilot/vm_test.go
Now that we made some changes to the cluster, the autoscaling is faster
which seems to lead to this failing more often
Tracked in https://github.com/istio/istio/issues/33154
[ ] Docs
[ ] Networking
[ ] Security
> Skip flaky VM test that depends on Kubernetes being slow

- galley/pkg/config/analysis/analyzers/annotations/annotations.go
- galley/pkg/config/analysis/msg/messages.gen.go
- galley/pkg/config/analysis/msg/messages.yaml
This assists https://github.com/istio/api/pull/1997
Example:
```
Info [IST0135] (Pod shell-74bc57ff88-ptb6d.default) Annotation "sidecar.istio.io/discoveryAddress" has been deprecated and may not work in future Istio versions.
Info [IST0135] (Pod shell-74bc57ff88-ptb6d.default) Annotation "sidecar.istio.io/inject" has been deprecated in favor of the "sidecar.istio.io/inject" label and may not work in future Istio versions.
```
This has been replaced with a label of the same name. The label is
strictly more powerful since selection is done in Kubernetes, rather
than in Istio.
See
https://preliminary.istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy
> Allow specifying a reason for annotation deprecation

- istioctl/cmd/workload.go
related to #31624
This isn't a solution to the underlying problem, but it will make debugging more obvious.
> istioctl workload: warn if ingress ip is invalid

- pilot/pkg/networking/plugin/authn/authentication.go
- pilot/pkg/security/authn/policy_applier.go
- pilot/pkg/security/authn/v1beta1/policy_applier.go
- pilot/pkg/security/authn/v1beta1/policy_applier_test.go
- pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-out.yaml
- pilot/pkg/security/authz/builder/testdata/http/deny-and-allow-out1.yaml
- pilot/pkg/security/authz/builder/testdata/http/deny-and-allow-out2.yaml
- pilot/pkg/security/authz/builder/testdata/http/multiple-policies-out.yaml
- pilot/pkg/security/authz/builder/testdata/http/simple-policy-multiple-td-aliases-out.yaml
- pilot/pkg/security/authz/builder/testdata/http/simple-policy-principal-with-wildcard-out.yaml
- pilot/pkg/security/authz/builder/testdata/http/simple-policy-td-aliases-out.yaml
- pilot/pkg/security/authz/builder/testdata/http/single-policy-out.yaml
- pilot/pkg/security/authz/builder/testdata/http/td-aliases-source-principal-out.yaml
- pilot/pkg/security/authz/model/generator.go
- pilot/pkg/security/authz/model/generator_test.go
Currently, we are verifying mTLS attributes using the istio_authn HTTP
filter. This is already done by the TCP filter. Using the same method
for TCP simplifies the code (do things one way instead of two), is
likely slightly more performant, and allows easier usage for non
istio-proxy Envoy builds.
> Do not use istio_authn filter when not needed

- pilot/pkg/model/context.go
- pilot/pkg/model/gateway.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_test.go
- releasenotes/notes/auto-auto-passthrough.yaml
- samples/multicluster/gen-eastwest-gateway.sh
Fixes https://github.com/istio/istio/issues/33127
> Automatically detect ROUTER_MODE

- istioctl/cmd/precheck.go
Closes #32119
Improve error message when istioctl x precheck could not connect to K8s cluster.
Suggest reviewer: @howardjohn
[ ] Docs
[ ] Networking
[ ] Security
> Improve error msg of istioctl x precheck

- pkg/envoy/admin.go
When Istio is installed in the IPv6 environment, graceful shutdown of the sidecar fails. It skips the terminationDrainDuration period and terminates immediately. This is because the pilot-agent invokes Envoy (admin path) on the IPv4 address (127.0.0.1:15000) when Envoy is actually listening on the IPv6 address ([::1]:15000). This PR addresses this minor issue.
[ ] Docs
[X] Networking
[ ] Security
[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. …
> Fixes sidecar graceful shutdown issue in the IPv6 environment

- pilot/pkg/networking/core/v1alpha3/route/route.go
It is better to check if `in.Rewrite` is nil, to avoid unnecessary function calls when no rewrite rules.
[ ] Docs
[X] Networking
[ ] Security
> check if in.Rewrite is nil

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/networking/apigen/apigen.go
- pilot/pkg/networking/apigen/apigen_test.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/discovery.go
PushContext should only store intermediate cache for this epic push, but ServiceDiscovery and IstioConfigStore are global interfaces. 
This pr does not change any user-sensitive behavior. 
[ ] Docs
[ ] Networking
[ ] Security
> Dedup Pushcontext with ServiceDiscovery and IstioConfigStore

- istioctl/pkg/writer/envoy/configdump/route.go
Before:
```
NAME                                                          DOMAINS                                                                                                MATCH                  VIRTUAL SERVICE
*                                                                                                      /healthz/ready*  
*                                                                                                      /stats/prometheus*
InboundPassthroughClusterIpv6                                 *                                                                                                      /*               
inbound|9087||                                                * …
```
> Filter out some redundant domains in istioctl

- cni/cmd/istio-cni/main.go
- cni/cmd/istio-cni/main_test.go
- releasenotes/notes/33145.yaml
This PR is to add the crash revocer like Calico for CNI plugin. The PR is to fix the issue #33137. 
[ ] Docs
[x] Networking
[ ] Security
> add crash recover to CNI plugin

- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
- releasenotes/notes/route-collapse.yaml
Fixes https://github.com/istio/istio/issues/28659
Helps with https://github.com/knative-sandbox/net-istio/issues/630
Benchmarks (I removed ones with no change):
```
name                                   old time/op        new time/op        delta
RouteGeneration/gateways-6                   43.2ms ± 3%        30.3ms ± 3%  -29.79%  (p=0.000 n=10+10)
RouteGeneration/gateways-shared-6             175ms ± 4%          86ms ± 3%  -50.89%  (p=0.000 n=10+10)
RouteGeneration/knative-gateway-6            9.44ms ± 2%        4.02ms ± 1%  -57.41%  (p=0.000 n=10+9)
name                                   old kb/msg         new kb/msg         delta
RouteGeneration/gateways-6                    2.67k ± 0%         1.14k ± 0%  -57.34%  (p=0.000 n=10+10)
RouteGeneration/gateways-shared-6             12.6k ± …
```
> Optimize route generation by collapsing overlapping routes

- pkg/test/framework/runtime.go
- pkg/test/framework/scope.go
- pkg/test/framework/testcontext.go
```
2021-06-02T15:49:50.253240Z	debug	tf	Begin dumping testContext: "TestIngress/http"
2021-06-02T15:49:50.253249Z	debug	tf	Done dumping scope: [TestEmptyCluster] (672ns)
2021-06-02T15:49:50.253254Z	debug	tf	Done dumping scope: [TestFileOnly] (212ns)
2021-06-02T15:49:50.253260Z	debug	tf	Done dumping scope: [TestDirectoryWithoutRecursion] (200ns)
2021-06-02T15:49:50.253264Z	debug	tf	Done dumping scope: [TestDirectoryWithRecursion] (362ns)
...
```
The failed test should trigger a suite level dump, but we don't want it to dump the test contexts within the suite except for its own.
> avoid recursively dumping sibling test contexts

- pilot/pkg/model/context.go
- pilot/pkg/networking/core/v1alpha3/name_table.go
- pilot/pkg/xds/ep_filters.go
If for some reason we misconfigure CLUSTER_ID in some environment (e.g. VMs) we may end up excluding ALL headless services/statefulset info.
> ndsz: handle empty cluster id for headless svc

- security/pkg/nodeagent/sds/sdsservice.go
After some recent changes to ADS, we now handle logging for custom ADS
types, but never updated this code to not do its own logging as well
> Fix double logging in agent SDS

- pilot/pkg/config/memory/monitor.go
[ ] Docs
[ ] Networking
[ ] Security
Subject
change struct name from 'configstoreMonitor' to 'configStoreMonitor'
Problem
It's better to keep consistency of code style, declaring struct name `camelCase` or `CamelCase`.
> change struct name from 'configstoreMonitor' to 'configStoreMonitor'

- samples/bookinfo/README.md
- tests/integration/helm/util.go
[ ] Docs
[ ] Networking
[ ] Security
[X ] User Experience
Before:
const (
IstioNamespace      = "istio-system"
ReleasePrefix       = "istio-"
BaseChart           = "base"
DiscoveryChart      = "istio-discovery"
IngressGatewayChart = "istio-ingress"
EgressGatewayChart  = "istio-egress"
BaseReleaseName     = ReleasePrefix + …
> Change variable "retryDelay" into  "RetryDelay" to stay the same in (tests/integration/helm/util.go)

- pilot/cmd/pilot-agent/main.go
- pilot/cmd/pilot-agent/options/statusserver.go
- pilot/cmd/pilot-agent/status/server.go
- pilot/pkg/dns/dns.go
- pkg/istio-agent/agent.go
We currently can get it from pilot but its nice to have it on both sides for different cases.
Opening early for feedback, needs some work
Open questions:
* How can we/should we expose this in `istioctl pc dns`?
* Should we expose `nds.NameTable` or internal `LookupTable`? Probably NameTable, but I didn't implement that here
> Expose DNS config from agent

- pilot/cmd/pilot-agent/main.go
- pkg/envoy/proxy.go
- pkg/envoy/proxy_test.go
This preserves the existing field, but allows expressing all of the same
options in LogLevel. Then we can just not promote componentLogLevel to
beta
> Consolidate componentLogLevel into one field

- pilot/pkg/bootstrap/server.go
- pilot/pkg/serviceregistry/aggregate/controller.go
- pkg/kube/secretcontroller/secretcontroller.go
We are seeing cache sync taking more than 1 hour in some clusters. It is not clear which controller is taking time. This PR tries to add log lines to capture that information.
[ ] Docs
[X] Networking
[ ] Security
> add additional logging for cache sync

- pilot/pkg/serviceregistry/serviceentry/conversion.go
`buildServices` will do all the jobs for `out`, there is no need to make slice for out in `convertServices`.
[ ] Docs
[X] Networking
[ ] Security
> remove make of out

- pilot/pkg/model/context.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_test.go
For user specified SIMPLE and DISABLE TLS mode we should not try to build mutual tls settings.
[ ] Docs
[X] Networking
[ ] Security
> do not build auto MTLS settings for SIMPLE

- tests/integration/telemetry/stackdriver/stackdriver_filter_dry_run_test.go
- tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
For https://github.com/istio/istio/issues/33243
The `TestStackdriverAuthzDryRun_Allow` wants the `dry-run-allow` policy but a lot of the collected log entries are caused by the `dry-run-deny` policy that is used in the previous test case `TestStackdriverAuthzDryRun_Deny`. 
This seems indicating there are some slowness and delay in the stackdriver log entry update, This PR tries to fix the flaky by doubling the test timeout so that the stackdriver has more time to update the log entries for each test case.
[ ] Docs
[ ] Networking
[ ] Security
Please check any characteristics that apply to …
> Double the timeout to fix the authz dry-run test flaky

- pkg/test/framework/resource/version.go
- pkg/test/framework/resource/version_test.go
- tests/integration/pilot/common/traffic.go
Fails out when passing invalid version in `--istio.test.revisions`.
[ ] Docs
[ ] Networking
[ ] Security
> [tf] Add validation to IstioVersion when parsing revisions

- galley/pkg/config/analysis/msg/generate.main.go
- galley/pkg/config/analysis/msg/messages.yaml
This PR is to add the documentation url from istio.io to messages.yaml. The next step I'll do is to convert the current message structures using Analysis message api.
[ ] Docs
[ ] Networking
[ ] Security
> add documentation url to analysis messages

- pilot/pkg/model/envoyfilter.go
- pilot/pkg/model/envoyfilter_test.go
- pilot/pkg/model/push_context.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go
The name tag of envoy filter metrics is not populated correctly as we merge all the matching filters in to a single EnvoyFilterWrapper and that does not have name/namespace populated. This PR fixes it by populating the patch with the name/namespace and uses it to increment metrics.
[ ] Docs
[X] Networking
[ ] Security
[X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance …
> envoy filter metrics does not have name populated correctly

- pilot/pkg/config/kube/crdclient/cache_handler.go
- pilot/pkg/config/kube/crdclient/client.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/sync.go
this is the second half, based on #33247 to simplify review.
Prevent task enqueue before we SyncAll, this is to prevent double handling resources during bootstrap. 
In my test env, the istio ready time before is
```
2021-06-03T12:05:00.134841Z     error   ====waitForCacheSync: committed 28181, expected 24816
2021-06-03T12:05:00.134877Z     info    ads     All caches have been synced up in 31.57432894s, marking server ready
```
with this patch: 
```
2021-06-03T12:13:19.954575Z     error   ====waitForCacheSync: committed 18512, expected 18512
2021-06-03T12:13:19.954612Z     info    ads     All caches have been synced up in 22.187328946s, marking server ready
```
[ ] Docs
[ ] Networking
[ ] Policies and …
> Prevent meaningless enqueue before SyncAll

- pilot/pkg/util/sets/string.go
- pilot/pkg/util/sets/string_test.go
- pkg/test/echo/cmd/client/main.go
- pkg/test/echo/cmd/server/main.go
- pkg/test/echo/common/scheme/scheme.go
- pkg/test/echo/server/forwarder/protocol.go
- pkg/test/framework/components/echo/annotations.go
- pkg/test/framework/components/echo/common/call.go
- pkg/test/framework/components/echo/config.go
- pkg/test/framework/components/echo/echoboot/echoboot.go
- pkg/test/framework/components/echo/echotest/filters.go
- pkg/test/framework/components/echo/instances.go
- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/components/echo/kube/instance.go
- pkg/test/framework/components/echo/kube/util.go
- tests/integration/iop-integration-test-defaults.yaml
- tests/integration/pilot/common/apps.go
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/common/traffic.go
* Modifications to the `echo` forwarder app to support proxyless gRPC
* Test-only inject template pointing to istiod insecure (15010)
* Test framework will automatically swap `grpc://` with `xds:///` when the forwarder is a proxyless gRPC client
* Actually use a proxyless grpc app in our common set of apps (workload agnostic tests will automatically try to utilize)
* Skip several tests that aren't compatible
The main test that actually benefits here is `sniffing` which really acts as a reachability test. This PR mostly serves to lay groundwork for future tests/enhancements to proxyless gRPC support. 
Not 100% if we want to merge as-is or wait till we decide on how we want to handle some of the proxyless features (bootstrap with agent vs. custom injector etc).
> test proxyless gRPC with echo

- releasenotes/notes/30868.yaml
- tools/istio-iptables/pkg/cmd/run.go
- tools/istio-iptables/pkg/cmd/run_test.go
When an application is deployed in the IPv6 cluster with the annotation `traffic.sidecar.istio.io/includeOutboundPorts`, the corresponding IPv6 rule is missing in the ip6tables (as mentioned in issue #30868). This PR addresses this issue by adding the missing IPv6 rule. 
[ ] Docs
[X] Networking
[ ] Security
> Fixes #30868. Added the missing IPv6 rule.

- pilot/pkg/xds/delta_test.go
- pilot/pkg/xds/deltaadstest.go
ResponseNonce is set ONLY on ACK/NACK
[ ] Docs
[ ] Networking
[ ] Security
> Fix delta test to match Envoy

- bin/retry.sh
Signed-off-by: shaowenchen <mail@chenshaowen.com>
An error occurs while I compile the project under macos 11.2.3 (20D91).
```bash
BUILD_WITH_CONTAINER=0 make clean 
```
```bash
BUILD_WITH_CONTAINER=0 make init 
ISTIO_OUT=/Users/shaowenchen/Code/github/istio/out/darwin_amd64 ISTIO_BIN=/Users/shaowenchen/.gvm/pkgsets/go1.16/global/bin GOOS_LOCAL=darwin bin/retry.sh SSL_ERROR_SYSCALL bin/init.sh
script: illegal option -- -
usage: script [-adkpqr] [-t time] [file [command ...]]
Unexpected failure
make: *** [/Users/shaowenchen/Code/github/istio/out/darwin_amd64/istio_is_init] Error 1
```
It should use `script -q -r file cmd` of `script --flush --quiet --return file --command cmd` under macos.
[ ] Docs
[ ] Networking
[ ] Performance and …
> fix: script parameter error under macos

- pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
- pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
- pkg/kube/inject/initializer.go
- pkg/kube/inject/inject.go
- pkg/kube/inject/webhook.go
- pkg/kube/inject/webhook_test.go
We no need to apply `istio-root-ca-cert` configmap to special kubernetes system namespaces, because istio never use these namespaces, such as kube-system, kube-public.
[ ] Docs
[ ] Networking
[ ] Security
> No need to apply istio-root-ca-cert configmap to special kubernetes system namespaces.

- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/bootstrap/server.go
- pilot/pkg/status/state.go
No need to store rest config, it shouldn't be used in 99% of cases and
the one valid use case (different QPS) can just call .RestConfig.
BTW - the pointer change is safe since .RestConfig() already does a
copy.
[ ] Docs
[ ] Networking
[ ] Security
> pilot: cleanup server to only store kubeClient

- tests/integration/pilot/ingress_test.go
Deployments should not be cleaned up by the test. It is slow and more
importantly breaks the dumping logic. Instead, we should let them get
pruned by the namespace removal, which happens asyncronously after the
test completes.
[ ] Docs
[ ] Networking
[ ] Security
> Fix dump for TestCustomGateway

- pkg/bootstrap/platform/gcp.go
- pkg/bootstrap/platform/gcp_test.go
* Use same pattern of early-resolving and exporting publically so other
packages can override if needed, as we do in other parts of code
* Allow setting GCP_METADATA env var when not actually on GCE
[ ] Docs
[ ] Networking
[ ] Security
> Some improvements to GCP metadata

- pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch_test.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/ef-tls-regression.yaml
Fixes https://github.com/istio/istio/issues/33409
* Fix regression when using custom transport_socket envoyfilter
Fixes https://github.com/istio/istio/issues/33385
* do not patch TSM
* test and lint
* lint
* More comments
(cherry picked from commit 97d8df38eb725dc8acaaa9fceb714968d32dfe54)
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance …
> [1.10] Fix regression when using custom transport_socket envoyfilter (#33386)

- tests/integration/pilot/common/routing.go
The `localhost_without_sidecar` and `localhost_with_empty_sidecar` cases fail on pre-1.10 versions.
[ ] Docs
[ ] Networking
[ ] Security
> Add minIstioVersion for instance IP tests

- security/pkg/pki/util/generate_cert_test.go
This fails since we are using the wrong key here, and in 1.17 they made
it more strict
For https://github.com/istio/istio/issues/33382
Cherrypicking to 1.10 just in case anyone decides to run 1.10 in 1.17 in the future.
> Fix cert generation test for go 1.17 support

- istioctl/pkg/writer/envoy/configdump/listener.go
- istioctl/pkg/writer/envoy/configdump/listener_test.go
**ISSUE:** 
https://github.com/istio/istio/issues/33432
istioctl crashed when retrieving the listener config which is listening on an unix domain socket
100% percent re-produciable
**Root cause:**
retrieveListenerAddress call the GetSocketAddress() by default which would return nil in this case
and further reference would crash the code
**Solution:**
add GetPipe() to the logic to handle difference listeners
**Unit-test:**
issue cannot be re-produced with this fix following the re-producing procedure
before fix 
```
$ istioctl pc listeners python-6db574dd4d-6trft.uds
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x2608c0f]
goroutine 1 [running]: …
```
> istioctl crashed at retrieveListenerAddress 

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
fix normalizeClusters typo in comment. There is no func called `finalizeClusters`.
[ ] Docs
[X] Networking
[ ] Security
> fix normalizeClusters typo in comment

- cni/pkg/taint/taintcontroller.go
[ ] Docs
[ ] Networking
[ ] Security
Subject
change variable name from `podcontroller` to `podController` like following `nodeController`
Problem
It's better to keep consistency of code style, declaring variable name camelCase or CamelCase.
> code style, keep CamelCase: change variable name from `podcontroller` to `podController`

- pkg/istio-agent/xds_proxy.go
- pkg/wasm/cache.go
- pkg/wasm/cache_test.go
Signed-off-by: gy95 <1015105054@qq.com>
> fix typo from DefaultWasmModulePurgeInteval to DefaultWasmModulePurgeInterval

- istioctl/cmd/proxyconfig.go
- istioctl/cmd/root.go
When auto-completion is enabled, istioctl could auto complete most command, this is convenient.
However, for `istioctl proxyconfig` command, it wants users to fill in pod-name, but this command could not auto complete pod names in current namespace, so users have to use kubectl to get pods name first, then copy and paste to fill in istioctl command.
`istioctl proxy-config <clusters|listeners|routes|endpoints|bootstrap|log|secret> <pod-name[.namespace]>`
This is a little burdensome. This PR will add func to custom `istioctl proxy-config * ` to auto fill in pods name in current namespace, and will helps a lot.
```bash
$ istioctl proxy-config route <tab><tab>
debian-77dc9c5f4f-nscvz                      nginx-74f5bd857c-7dvkp …
```
> istioctl proxy-config command support pod-name auto-completion

- security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
https://github.com/istio/istio/pull/31859 updated the token exchange error message, but didn't convert byte array to string.
The fix is only in master branch https://github.com/istio/istio/pull/32111.
Add similar fix to release 1.10 branch.
[ ] Docs
[ ] Networking
[x] Security
> Fix token exchange error message

- tests/integration/helm/upgrade/main_test.go
- tests/integration/pilot/ingress_test.go
- tests/integration/pilot/multi_version_revision_test.go
- tests/integration/pilot/revisioned_upgrade_test.go
- tests/integration/security/chiron/main_test.go
- tests/integration/security/external_ca/main_test.go
- tests/integration/security/mtlsk8sca/main_test.go
- tests/integration/security/sds_ingress_k8sca/main_test.go
* Ingress old API version was removed, bump it up one versions we can
* legacy-unknown signer is removed. This disables 4 test suites. THESE
FEATURES ARE BROKEN - it is not just a testing issue.
* Upgrade tests are broken on 1.22, so disabled. This is not a big deal
right now, but when we update presubmit to 1.22 it likely will be.
I have tagged everyone that has features they worked on broken.
Fixes https://github.com/istio/istio/issues/33475
> Skip tests broken in 1.22

- tests/integration/pilot/common/routing.go
Select the `network` in the service to avoid hitting the gateway which makes consistent hashing unpredictable (we only perform it at the client, not the TCP gateway)
> fix consistent hashing test for multicluster

- pkg/test/framework/components/namespace/kube.go
Before we'd panic when using `SetLabel` on namespace running with `--istio.test.stableNamespaces`
[ ] Docs
[ ] Networking
[ ] Security
> [tf] Pass context to namespace when creating with stableNamespaces

- tests/integration/pilot/common/traffic.go
Smaller version of https://github.com/istio/istio/pull/33510
> Make consistent hash test only run in single network

- go.mod
- go.sum
This fixes the issue on using go mod vendor as well
[ ] Docs
[ ] Networking
[ ] Security
> Bump quic-go for go 1.17 support

- pilot/cmd/pilot-agent/config/config_test.go
- pkg/config/mesh/mesh.go
- pkg/config/mesh/mesh_test.go
- releasenotes/notes/pc-merge-metadata.yaml
This is useful for pod annotation overrides and for
shared_user_mesh_config. Basically if the top level sets a proxy
metadata, which may be for critical fields like CA_ADDRESS, anyone below
it will override them completely which will often lead to breakages.
This allows a deeper merge
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance …
> Improve merging of proxy config proxyMetadata

- pkg/config/labels/collection.go
- pkg/config/labels/instance.go
- pkg/config/labels/instance_test.go
Add short path check for `SubsetOf`, mainly for cases when `len(that) < len(i)`, to avoid meaningless map iteration.
[ ] Docs
[ ] Networking
[ ] Security
> short path check for SubsetOf

- pilot/pkg/model/config_test.go
- pkg/config/labels/instance.go
1. Add length check for maps with different length, to get result quickly.
2. As length has been checked, and the two maps have the same size, so we only need to check `i.SubsetOf(that)`.
I also add a small example to show the benchmark: https://play.golang.org/p/ZBC5Q9venNY
Run the example in local env, and will get the results:
```
--------- case 1 for length compare ------------
result false, original Equals cost time 233.469785ms
result false, new Equals cost time 162ns
--------- case 2 for one SubsetOf ------------
result true, new Equals 1 cost time 478.357971ms
result true, new Equals 2 cost time 232.908134ms
result true, new Equals 3 cost time 525.778057ms
2021-06-22 00:10:38.98496 +0800 CST m=+3.524822916
```
Case 1 shows two …
> improve Equals func performance 

- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/kube/controller/serviceexportcache_test.go
This is a follow on to https://github.com/istio/istio/pull/32863#discussion_r654679922
[ ] Docs
[x] Networking
[ ] Security
> Use common utility for comparing cluster strings

- pkg/test/echo/client/parsedresponse.go
We use "Cluster" to abstract anywhere we deploy to, but the things we deploy to consider themselves as being "attached" to one of the k8s clusters – this is what's validated in these checks.
> make reached clusters check only consider actual clusters

- pilot/pkg/model/network.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/aggregate/controller.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/network.go
- pilot/pkg/serviceregistry/memory/discovery.go
- pilot/pkg/serviceregistry/mock/discovery.go
- pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/endpoint_builder.go
- pilot/pkg/xds/ep_filters.go
- pilot/pkg/xds/ep_filters_test.go
- pilot/pkg/xds/mesh_network_test.go
The `PushContext` previously was manually merging `MeshNetworks` with the network gateways provided by the service registries.
Added a `Gateways` structure as an abstraction around the collection of gateways with methods for all current use cases.
Replaced `PushContext` methods with basic access to the `Gateways` object.
Also removed locking around access to `Gateways`. I don't think it's necessary since its already a snapshot in time of the gateways from `MeshNetworks` and the registries.
[ ] Docs
[x] Networking
[ ] Security
Please check any characteristics that apply to this pull …
> Refactoring network gateway storage.

- pkg/test/echo/client/parsedresponse.go
- tests/integration/pilot/ingress_test.go
This reverts commit 94758b7ed491b5557e7c4fec056836a3a5ca619e and uses more appropriate filtering logic, only checking the correct _app_'s clusters.
> fix cluster check for ingress test

- samples/addons/prometheus_vm.yaml
- samples/addons/prometheus_vm_tls.yaml
* Prometheus deployment update to enable VM telemetry and TLS.
* Prometheus configuration for VMs.
* The configuration adds VM service discovery based on the work in
https://github.com/istio-ecosystem/sd-for-vm-telemetry.
* Two configuration files: one with TLS settings for VMs, one without
TLS settings.
* Update file name.
* Remove duplicate file.
* Recover prometheus.yaml.
* change vm discovery container image to istioecosystem/vm-discovery:latest https://hub.docker.com/r/istioecosystem/vm-discovery/tags
Co-authored-by: xulingqing <linggg@google.com>
[ ] Docs
[ ] Networking
[ ] …
> [release 1.10 cherrypick] Prometheus configuration samples for VMs (#32865)

- pilot/pkg/features/pilot.go
Since Delta Xds is not fully implemented, registering this var adding to documentation and people wants to try it and see if it helps their config delivery. Either we should make it clear in the description that it is not ready for use or register it as hidden var so that docs are not generated. This PR moves it to hidden var.
[ ] Docs
[X] Networking
[ ] Security
[X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API …
> do not register delta xds env var

- pilot/pkg/model/context.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/lds_test.go
If proxy bootstrap does not provide labels in metadata(happens for noninjected proxies) and by that time pod connects to istiod if the pod is not available in istiod pod cache, we never set work load labels later -and any sidecar that is applied to it with workload selector does not work
[ ] Docs
[X] Networking
[ ] Security
[X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance …
> cleanup set workload labels

- istioctl/cmd/describe.go
Hi there, I was reading the code under istioctl, saw the [validatePort()](https://github.com/istio/istio/blob/fe710ef62f9c1cc8207f4643b48c3def28da7f95/istioctl/cmd/describe.go#L180) is pretty reduplicative with pilotcontroller.FindPort() after some changes and nowhere else is using it now, so I did some code clean up.
[ ] Docs
[ ] Networking
[ ] Security
[X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, …
> Do some code clean up under istioctl

- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/network.go
Now that `NetworkGateways` just returns a list of gateways, we can simplify the internal data structures.
[ ] Docs
[x] Networking
[ ] Security
> Simplify kube controller network gateway logic

- pilot/pkg/model/network.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/model/service.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/endpoint_builder.go
- pilot/pkg/xds/ep_filters.go
- pilot/pkg/xds/mesh_network_test.go
`NetworkGateways` implies a simpler collection than this is. `NetworkManager` can also allow us to expand the interface to provide a one-stop-shop for all networking related queries.
Also cleaning up the internal storage to reduce the total number of maps.
[ ] Docs
[x] Networking
[ ] Security
> Rename NetworkGateways to NetworkManager

- istioctl/cmd/dashboard.go
The error info produced by fw.Start() can't pass to the outer err because it's been redefined
[ ] Docs
[ ] Networking
[ ] Security
> Error produced by forworder.start can't return correctly

- pilot/cmd/pilot-agent/status/server.go
`appProberPattern` now is `^/app-health/[^/]+/(livez|readyz|startupz)$`, includes `startupz`, the error message is not complete.
We could print value of `appProberPattern` directly, as this [example](https://play.golang.org/p/AXSUVEMxYl3) shows.
And the `httpClient` is better to set close to the place where it is used.
[ ] Docs
[X] Networking
[ ] Security
[X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, …
> fix appProberPattern reg print

- pilot/pkg/util/sets/string.go
- pilot/pkg/util/sets/string_test.go
- pkg/test/framework/components/echo/echoboot/echoboot.go
When testing with multiple versions we should just take the intersection of injection templates available across revisions and deploy / not deploy based on that.
[ ] Docs
[ ] Networking
[ ] Security
> [tf] Use intersection of available injection templates in test framework

- security/pkg/stsservice/server/server.go
**when `sendSuccessfulResponse` failed, we cannot continue to print debug logs `sent out STS success response`**
[ ] Docs
[ ] Networking
[ ] Security
> fix: send reponse error cannot continue to log debug

- pilot/pkg/xds/fake.go
- pilot/pkg/xds/sds_test.go
Example:
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/batch/unit-tests_istio/1409552953903157248
The issue is the controller starts and then we mutate the reactor.
Instead, we mutate before starting.
```
980 runs so far, 0 failures (100.00% pass rate). 5.95599005s avg, 8.056962472s max, 2.234816493s min
```
> Fix race in SDS tests

- pkg/test/framework/components/echo/kube/deployment.go
- samples/extauthz/README.md
- samples/extauthz/ext-authz.yaml
- samples/extauthz/local-ext-authz.yaml
- samples/extauthz/src/Makefile
- samples/extauthz/src/main.go
- tests/integration/security/authorization_test.go
- tests/integration/security/main_test.go
- tests/integration/security/util/rbac_util/util.go
This PR extends the sample ext-authz server and add new e2e tests to cover the new `headersToUpstreamOnAllow`, `headersToDownstreamOnDeny` and `includeAdditionalHeadersInCheck` options in the extension provider.
[ ] Docs
[ ] Networking
[x] Security
> ext-authz: add e2e tests for related header options in authz extension provider

- pkg/bootstrap/platform/gcp.go
- pkg/bootstrap/platform/gcp_test.go
Sometimes, it is necessary to override the quota project for GCP (in addition to just the consumer project, as is done with GCP_METADATA). This PR provides a mechanism for that override.
> Add support for env var override of gcp quota project

- tools/istio-iptables/pkg/cmd/run.go
- tools/istio-iptables/pkg/cmd/run_test.go
- tools/istio-iptables/pkg/constants/constants.go
The problem this PR tries to solve is described in https://github.com/istio/istio/issues/33469
In cases where an application does a lot of DNS UDP requests, we have cases where a UDP requests picks a source port that is already defined inside the conntrack tables and its packet is routed directly to the DNS resolvers.
That makes the new packet to be also routed directly to DNS resolvers without traversing the NAT iptables and hence the REDIRECT rules to send it to the local Istio DNS port.
This way we get DNS resolution errors.
The fix that implements this commit is to use separate conntrack zones for different flows. One flow will be the communication with the application, and the other will be the communication with DNS resolver.
More specific zone 2 will be UDP DNS packets that are …
> Address UDP DNS issues due to conntrack

- tests/fuzz/oss_fuzz_build.sh
As requested in https://github.com/istio/istio/pull/33653#issuecomment-869776501 by @howardjohn, this PR adds the OSS-fuzz build script which currently is located on the OSS-fuzz side.
Moving it upstream will make modifications easier.
The build script is modified with:
- Changes that enable OSS-fuzz coverage build
- Build instructions for the 3 latest fuzzers that were merged in https://github.com/istio/istio/pull/33653 and https://github.com/istio/istio/pull/33652
[ ] Docs
[ ] Networking
[x] Security
[x] Does not have any …
> fuzzing: Move oss-fuzz build script upstream

- samples/bookinfo/policy/productpage_envoy_ratelimit.yaml
According to [routeMatch](https://github.com/istio/istio/blob/767767161b3b3350a30a4b7bb6b337857405c0ed/pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go#L364), `routeConfiguration.vhost.name` use empty string as wildcard, not `"*:80`.
```go
func routeMatch(httpRoute *route.Route, rp *model.EnvoyFilterConfigPatchWrapper) bool {
...
// check if httpRoute names match
if match.Name != "" && match.Name != httpRoute.Name {
return false
}
```
If we specify it to `"*:80`, `routeMatch` will do exactly string check, which will failed all the time.
As this is used by gateway, we could set empty string to `routeConfiguration.vhost.name`, to match all `vhost.name`.
Related to #32381
[ ] Docs
[ ] Networking
[X] …
> routeConfiguration.vhost.name use empty string as wildcard

- pkg/test/framework/components/istio/eastwest.go
- tests/integration/iop-integration-test-defaults.yaml
This was disabled only for ingress/egress, not istiod or eastwest.
[ ] Docs
[ ] Networking
[ ] Security
> Disable autoscaling in integration tests

- tests/fuzz/pilot_model_fuzzer.go
This PR adds a fuzzer that creates an `Environment` with a fuzzed `ServiceDiscovery`. That env is then passed to `pc.InitContext(env, nil, nil)`.
[ ] Docs
[ ] Networking
[x] Security
> Fuzzing: Add pilot model fuzzer

- pilot/pkg/xds/ads_test.go
- pilot/pkg/xds/adstest.go
- pilot/pkg/xds/cds_test.go
- pilot/pkg/xds/debug_test.go
- pilot/pkg/xds/ecds_test.go
- pilot/pkg/xds/eds_sh_test.go
- pilot/pkg/xds/eds_test.go
- pilot/pkg/xds/lds_test.go
- pilot/pkg/xds/nds_test.go
- pilot/pkg/xds/rds_test.go
- pkg/istio-agent/agent_test.go
- security/pkg/nodeagent/sds/sdsservice_test.go
Currently, most methods for XDS tests rely on a `testing.T` variable that is stored within a struct. This typically references the parent test and if it fails during a subtest, it will bring down all sibling tests with it.
[ ] Docs
[ ] Networking
[ ] Security
> Minor fix to xds tests to support subtests

- tests/integration/tests.mk
The target will later be used to add postsubmit or periodic job for the fuzz test.
related: https://github.com/istio/test-infra/pull/3402
[ ] Docs
[ ] Networking
[ ] Security
> add a new test target for fuzz integration tests

- pilot/pkg/model/xds_cache.go
When we generate a token, we do not add it to the indexes. This means
its not properly invalidated. This leads to the following sequence of
events:
* Generate token 1, while endpoint state is v1
* Endpoint update to v2. Invalidate cache // BUG - token 1 is not removed since its not in the index
* Write token 1 at v1
* Fetch token 1, while endpoint state is v2
* Write token 1 at v2 // This triggers the assertion, as the cache should not mutate
With the fix:
* Generate token 1, while endpoint state is v1
* Endpoint update to v2. Invalidate cache
* Write token 1 at v1 // SKIPPED - invalidated
* Fetch token 1, while endpoint state is v2
* Write token 1 at v2 // This triggers the assertion, as the cache should not mutate
> Fix incorrect indexing in xds cache

- tests/fuzz/oss_fuzz_build.sh
Enables `FuzzInitContext` to run continuously by OSS-fuzz.
[ ] Docs
[ ] Networking
[x] Security
> Fuzzing: Run FuzzInitContext on OSS-fuzz

- tests/integration/telemetry/stackdriver/stackdriver_filter_dry_run_test.go
- tests/integration/telemetry/stackdriver/stackdriver_filter_test.go
This could potentially fix the https://github.com/istio/istio/issues/33243, also reverted the previous change of doubling the dry-run test timeout.
[ ] Docs
[ ] Networking
[x] Policies and Telemetry
[x] Security
> fix authz dry-run test flaky by reducing the logWindowDuration

- pilot/pkg/model/network.go
- pilot/pkg/model/service.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/networking/util/util_test.go
- pilot/pkg/serviceregistry/kube/controller/network.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/eds_sh_test.go
- pilot/pkg/xds/endpoint_builder.go
- pilot/pkg/xds/ep_filters.go
- pilot/pkg/xds/ep_filters_test.go
- tests/integration/pilot/mcs/discoverability/discoverability_test.go
Previous logic was broken for the case when only some clusters export service endpoints (via MCS ServiceExport). In this case, it's possible that we can accidentally hit unexported endpoints that share the same network as exported endpoints.
Refactoring the load balancing logic to prefer gateways with the same cluster as the endpoint. Going forward, we should recommend installing east-west gateway in all clusters to support the MCS use case.
Fixes #33526
[ ] Docs
[x] Networking
[ ] Security
[ ] Does not have any …
> Fix split-horizon LB for MCS

- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- pilot/pkg/xds/fake.go
We should be reading from the cache which is more efficient and handles
deduplication properly, rather than recomputing.
The PR is basically a few lines of a code and a lot of refactoring to
get the test to work. The problem was the XdsUpdater isn't actually set
in FakeXdsServer; in the TestSameIPEndpointSlicing test which this is
based on the Wait() always times out (so its not actually waiting)
because we use a xdsUpdater that isn't actually wired up to the
controller.
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does not …
> Fix endpointslice duplicate IPs on service update

- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- pilot/pkg/xds/fake.go
We should be reading from the cache which is more efficient and handles
deduplication properly, rather than recomputing.
The PR is basically a few lines of a code and a lot of refactoring to
get the test to work. The problem was the XdsUpdater isn't actually set
in FakeXdsServer; in the TestSameIPEndpointSlicing test which this is
based on the Wait() always times out (so its not actually waiting)
because we use a xdsUpdater that isn't actually wired up to the
controller.
(cherry picked from commit 1274725f3d6d95c6ba638113ea503a6d04bda666)
Fixes https://github.com/istio/istio/issues/33762
[ ] Docs
[ ] Networking
[ ] Security
[ ] Developer …
> [1.9] Fix endpointslice duplicate IPs on service update (#33757)

- galley/pkg/config/mesh/defaults.go
These two parameters are initialized in the function DefaultMeshConfig
[x] Docs
[ ] Networking
[x] Security
> Repeat set value

- cni/cmd/istio-cni/main.go
- cni/pkg/plugin/plugin.go
cni plugin library does not check on nil before calling passed in cmd. Got a crash when pod sandbox gets cleaned up.
Also add stack printing to cni plugin crash recovery.
> Add back empty check & delete to cni plugin.

- tests/fuzz/analyzer_fuzzer.go
- tests/fuzz/oss_fuzz_build.sh
Adds a fuzzer for the analyzer. The fuzzer creates fuzzed config files and passes them to a `SourceAnalyzer` with which `Analysis` is run.
If https://github.com/istio/istio/pull/33739 is merged first, then this PR should hold until this fuzzer is added to `tests/fuzz/regression_test.go`.
Will also need a rebase if https://github.com/istio/istio/pull/33731 is merged first.
[ ] Docs
[ ] Networking
[ ] Security
[x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) …
> Fuzzing: Add analyzer fuzzer

- pkg/envoy/proxy.go
- pkg/envoy/proxy_test.go
This is a UX improvement, by making access logs more responsive. There
is a tradeoff in responsiveness in performance; we could go even lower
but I feel 1s strikes the best balance (10s is the default).
The max buffer size is 64k. Each log is ~256 bytes. This gives us 263 logs per flush if the internal doesn't triger it
If we have 1 QPS: we would write 6/minute before and 60/minute after
If we have 10 QPS: we would write 22/minute before and 60/minute after
If we have 100 QPS: we would write 227/minute before and after
If we have 1000 QPS: we would write 2270/minute before and after
So this has no impact on users with >250 QPS.
[ ] Docs
[ ] Networking
[ ] Security
[ ] Test and …
> Decrease flush interval of access logs

- tools/istio-iptables/pkg/cmd/run.go
- tools/istio-iptables/pkg/config/config.go
- tools/istio-iptables/pkg/dependencies/implementation.go
Follow up PR of https://github.com/istio/istio/pull/33808. After switching iptables log to istio log pkg, several log lines do not make much sense. Change including:
* Combine iptables env and variables into a single multiple lines log entry
* Log iptables command stdout/stderr output with istio log pkg.
* Hardening the xtables error message parsing to avoid possible out-of-range crashing.
Example log output after this change: https://gist.githubusercontent.com/bianpengyuan/42e21d8fe68f2ecc675d4f2dbcb8415e/raw/f89c18766e52564fd6e88be872ef32c80f62f195/istio-init.log
> Clean up istio-iptables log.

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_test.go
Does not change any functionality but to be consistent with other failure modes we have.
[ ] Docs
[X] Networking
[ ] Security
> add enforcing consecutive local origin failures

- tests/fuzz/oss_fuzz_build.sh
- tests/fuzz/xds_fuzzer.go
Adds a fuzzer that creates a `FakeDiscoveryServer` with a fuzzed `ConfigString` and then calls `Listeners` and `Routes` with the created `FakeDiscoveryServer`.
[ ] Docs
[ ] Networking
[ ] Security
> Fuzzing: Add xds fuzzer

- pkg/kube/client.go
fix `client.PodExecCommands` repeated error message if has stderr
[ ] Docs
[ ] Networking
[ ] Security
> pkg/kube: fix client.PodExecCommands repeated error message

- pkg/adsc/adsc.go
- pkg/adsc/adsc_test.go
Use `jsonpb` marshal to persistent mesh config and other resource config in JSON format instead of using `json` marshal. And I also updated the test case. Please refer to [here](https://github.com/golang/protobuf/issues/183) for more information on proto 3. 
[ ] Docs
[ ] Networking
[ ] Security
> Use jsonpb marshal to persistent mesh config and other resource config in JSON format instead of using json marshal

- tests/integration/pilot/common/routing.go
Adds retry conditions to existing virtual service to validate that config is not rejected by Envoy.
[ ] Docs
[X] Networking
[ ] Security
> add retry conditions to existing virtual service tests

- pkg/test/framework/components/echo/common/call.go
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/33891/integ-telemetry-mc-k8s-tests_istio/1412883536393801728
The problem is we are mutating the same map in many goroutines. Instead,
make a copy.
[ ] Docs
[ ] Networking
[ ] Security
> Avoid panic on concurrent map writes in test

- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/configgen.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/core/v1alpha3/fake.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/cds.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/endpoint_builder.go
- releasenotes/notes/cds-cache.yaml
I have placed a hold to allow all 3 "assignees" to review (and anyone interested) before merging, as this is a fairly complex change
Before:
After:
Cache hit rate is 95%+:
A single cluster is ~900B typically. With 60k max entries, this results in at most 60mb overhead.
Istiod is using ~6GB memory for this case so that is only 1% extra memory usage, well worth the CPU gains
> Add caching of CDS responses

- go.mod
- go.sum
- istioctl/cmd/completion.go
- istioctl/cmd/root.go
- releasenotes/notes/istioctl_completion-ns.yaml
Add namespace completion supports for `istioctl`.
```
$ istioctl -i <tab><tab>
istio-system          kube-public          istio-demo          metallb-system
$ istioctl -n <tab><tab>
istio-system          kube-public          istio-demo          metallb-system
```
[ ] Docs
[ ] Networking
[ ] Security
This PR needs [cobra 1.2.0](https://github.com/spf13/cobra/releases) for the PR [RegisterFlagCompletionFunc as a global var not working in multi-threaded programs](https://github.com/spf13/cobra/pull/1423), to fix `concurrent map writes errors` of tests in parallel of istio([here is an …
> add completion support for namespace

- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- pilot/pkg/xds/fake.go
We should be reading from the cache which is more efficient and handles
deduplication properly, rather than recomputing.
The PR is basically a few lines of a code and a lot of refactoring to
get the test to work. The problem was the XdsUpdater isn't actually set
in FakeXdsServer; in the TestSameIPEndpointSlicing test which this is
based on the Wait() always times out (so its not actually waiting)
because we use a xdsUpdater that isn't actually wired up to the
controller.
(cherry picked from commit 1274725f3d6d95c6ba638113ea503a6d04bda666)
Fixes https://github.com/istio/istio/issues/33761
[ ] Docs
[ ] Networking
[ ] Security
[ ] Developer …
> [1.10] Fix endpointslice duplicate IPs on service update (#33757)

- tests/fuzz/helm_reconciler_fuzzer.go
- tests/fuzz/oss_fuzz_build.sh
- tests/fuzz/regression_test.go
Adds a fuzzer that creates a fuzzed k8sobject, passes its unstructured object to a fake client, creates a helm reconciler, and then calls `ApplyObject` with the same unstructured object.
[ ] Docs
[ ] Networking
[ ] Security
> Fuzzing: Add helm reconciler fuzzer

- samples/bookinfo/policy/productpage_envoy_ratelimit.yaml
- tests/integration/telemetry/policy/testdata/enable_envoy_ratelimit.yaml
accroding [ratelimit config](https://github.com/envoyproxy/envoy/blob/d3a90127f8c408651e8ab44e961408ca1fd972b4/source/extensions/filters/http/ratelimit/config.cc#L27) timeout should use envoy::extensions::filters::http::ratelimit::v3::RateLimit.timeout
otherwise there will be some grpcstatus 14 error during high qps
[x] Docs
[ ] Networking
[ ] Security
[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, …
> fix ratelimt envoyfilter

- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/httproute_test.go
- pilot/pkg/networking/core/v1alpha3/name_table.go
- pkg/dns/server/name_table.go
- pkg/dns/server/name_table_test.go
- releasenotes/notes/mcs-host.yaml
- tests/integration/pilot/mcs/discoverability/discoverability_test.go
This is the first phase of work for #33949.
This PR adds `clusterset.local` as an alias for `cluster.local` and resolves to the same IP. Since we're using the same IP, this change only impacts HTTP listeners and their routes.
The MCS host is also supported for DNS lookup.
[ ] Docs
[x] Networking
[ ] Security
> Basic support for Kubernetes MCS host

- pkg/test/framework/components/echo/common/call.go
Without this, we will never retry, and could get stuck on the first attempt for the entire `retry` package duration. 
```
traffic.go:222: call failed from TestRunner to [redacted] (using https): timeout while waiting after 1 attempts (last error: <nil>)
```
> echo: apply timeout for ingress calls

- pkg/kube/secretcontroller/secretcontroller.go
only after fininsh range `remoteClusters` using `secretKey`, we could delete from  `remoteClusters` map using key `secretKey`, and delete only once
first delete using secretKey and clusterID
finally delete all using secretKey
[ ] Docs
[ ] Networking
[ ] Security
> fix delete secret bug: delete secretKey cluster only once

- go.mod
- go.sum
- licenses/github.com/cespare/xxhash/LICENSE.txt
- licenses/github.com/prometheus/prometheus/LICENSE
- pilot/cmd/pilot-agent/status/server.go
- pilot/cmd/pilot-agent/status/server_test.go
- releasenotes/notes/openmetrics-merging.yaml
Fixes #33474 by enhancing the metrics merging functionality to support the OpenMetrics format in addition to the standard text-based metrics format.
This is accomplished by passing through the `Accept` header on the agent's scrape request to the application metrics endpoint and respecting the metrics format returned via the `Content-Type`. If there are no app metrics, the merging will default to `FmtText`.
Additionally, some post-processing of the envoy metrics must be done, namely removing empty lines, as they are not compatible as-is with FmtOpenMetrics. Also, the application metrics must be rendered last to correctly follow the FmtOpenMetrics spec.
[ ] Docs
[ ] Networking
[ ] …
> Support OpenMetrics format for metrics merging

- tests/fuzz/operator_translate_fuzzer.go
- tests/fuzz/oss_fuzz_build.sh
- tests/fuzz/regression_test.go
Adds a fuzzer that targets `operator/pkg/translate.TranslateFromValueToSpec`.
__________________________________
[ ] Docs
[ ] Networking
[ ] Security
> Fuzzing: add operator/pkg/translate fuzzer

- tools/packaging/packaging.mk
The incorrect binary was removed before building the CentOS 7 RPM.
Remove the CentOS-7 RPM instead of the newer one.
[ X] Configuration Infrastructure
[ ] Docs
[ ] Networking
[ ] Security
[ X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
> Fix incorrect remove in the rpm-7/fpm build step

- Makefile.core.mk
The base image was updated by the release tooling and the PR create failed. This is a manual PR to update the image. We need to update the image else, the next failing scan will try and create these images again and fail resulting in a non-build.
[ ] Docs
[ ] Networking
[ ] Security
> [release-1.10] Update base image

- pkg/mcp/snapshot/snapshot.go
`StatusInfo` structure has a `RWMutex` lock, and its field `watches` and `lastWatchRequestTime` all have mutex locked when read or write, i think field `synced` read or write should also be protected just like two other fields
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add …
> fix: StatusInfo synced add Lock

- pilot/pkg/bootstrap/certcontroller.go
- pilot/pkg/bootstrap/istio_ca.go
- security/pkg/k8s/chiron/controller.go
- security/pkg/k8s/chiron/controller_test.go
- security/pkg/k8s/chiron/utils.go
- security/pkg/k8s/chiron/utils_test.go
- security/pkg/pki/ra/common.go
- security/pkg/pki/ra/k8s_ra.go
- security/pkg/pki/ra/k8s_ra_test.go
Add ability for chiron module of Istiod to use [Kubernetes v1 CSR api ](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/) to sign Istiod DNS certificates and optionally sign workload certificates when Istiod functions as an RA. Refer to [Issue](https://github.com/istio/istio/issues/34012) for context
[ ] Docs
[X] Networking
[X] Security
[] User Experience
[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI …
> chiron: Incorporating kubernetes csr v1 api

- cni/pkg/cmd/root.go
For #34099
This makes it possible to create command reference at istio.io for install-cni and refresh automatically by bot. To make all configuration options not only shows up as command line arg, but also env variable in the reference page, this change also registers all configuration option with istio env pkg.. Also clean up the command line option description a bit to make it more user friendly.
> Add collateral into install-cni.

- cni/pkg/cmd/root.go
Get a lint error when adding install-cni CLI reference: https://github.com/istio/istio.io/pull/10087 because of missing period.
> Fix lint error of install-cni CLI description.

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
1）if targetport is set, add validation for targetPort
2）move ports parameter validation to the same for loop
[ ] Docs
[ ] Networking
[ ] Security
> Add validation for service entry port.targetPort

- security/pkg/nodeagent/sds/sdsservice.go
when config is found, we should `break` the loop, but not to continue to the next loop
[ ] Docs
[ ] Networking
[ ] Security
> fix break the loop when config is found

- pilot/pkg/model/network.go
- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/kube/controller/network.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/ep_filters.go
- pilot/pkg/xds/ep_filters_test.go
Discovered while investigating #34051.
Enabling [UNSAFE_PILOT_ENABLE_RUNTIME_ASSERTIONS](https://github.com/istio/istio/blob/dbf6a9e1c123bf6abbab45683b1c6c1f7660916c/pilot/pkg/features/pilot.go#L461)
Revealed that recent changes to managing multi-network gateways caused issues with EDS caching.
This PR fixes a couple of things:
- Kube controller now correctly identifies when network gateways have changed
- EDS filtering logic for split horizon now generates deterministic results
[ ] Docs
[x] Networking
[ ] Security
[ ] Does …
> Fix non-deterministic behavior in multi-network code

- security/pkg/k8s/chiron/controller.go
- security/pkg/k8s/chiron/utils.go
1. modify some comments
2. There is no need to using `defer` func to Close Connection, just Close directly
3. fix some logs
[ ] Docs
[ ] Networking
[ ] Security
> modify some codes of k8s/chiron

- security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
There is no need to use `defer` func to release response Body, just Close it directly. And another codes that processing Closing the Body also Close directly
fix some comments of stsclient
[ ] Docs
[ ] Networking
[ ] Security
> no need to use defer to release response Body

- pilot/pkg/bootstrap/certcontroller.go
- pilot/pkg/bootstrap/istio_ca.go
- pilot/pkg/bootstrap/server.go
- pilot/pkg/features/pilot.go
- releasenotes/notes/31522.yaml
- security/pkg/pki/util/keycertbundle.go
Istiod picks plugged in cacerts while bootstrap. After that, if user deletes and add new set of secrets, istiod has to restart.
This PR avoids necessity of restating istiod. File watcher added at /etc/cacerts directory to observe cacerts files changes (ca-cert.pem, ca-key.pem, root-cert.pem, cert-chain.pem). If new files are created, watcher notifies an event and istiod updates key certs bundle and generates new DNS certs.
Detailed discussion about this feature is discussed [here](https://github.com/istio/istio/issues/30947).
Note: This PR currently supports only intermediate-CA. I am working on new ROOT-CA support as well.
[ ] Docs
[ ] Networking
[X] Security …
> Add support to istiod to notice cacerts changes

- tests/testdata/networking/envoyfilter-without-service/configs.yaml
v2 XDS version is deprecated, it is better to upgrade to v3.
current config will get complains from istiod and sidecar
```
Warning: using deprecated type_url(s); type.googleapis.com/envoy.config.filter.http.lua.v2.Lua
```
```
virtualInbound: The v2 xDS major version is deprecated and disabled by default. Support for v2 will be removed from Envoy at the start of Q1 2021. You may make use of v2 in Q4 2020 by following the advice in https://www.envoyproxy.io/docs/envoy/latest/faq/api/transition. (envoy.config.filter.http.lua.v2.Lua)
```
[ ] Docs
[X] Networking
[ ] Security
Please check any …
> upgrade envoy filter envoy.lua from v2 to v3

- pilot/test/xdstest/grpc.go
- pilot/test/xdstest/mock_discovery.go
- pkg/istio-agent/agent.go
- pkg/istio-agent/leak_test.go
- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_test.go
* Fix memory leak in xds_proxy when channels are blocked
* add test
* delta and test fixes
* fix logs
* fix other leak
(cherry picked from commit 7870103a91b8686ba24e807377227d804a03806d)
(cherry picked from commit 42a925dc015ace3357fc859a1285b02ba53f398d)
[ ] Docs
[ ] Networking
[ ] Security
> [1.9] Fix memory leak in xds_proxy when channels are blocked (#34098)

- istioctl/pkg/multicluster/remote_secret.go
- pkg/config/constants/constants.go
Changes `istioctl x create-remote-secret --config` to use the `istiod` service-account by default, since `istiod-service-account` is now legacy for backward compat, and not even installed on an external istiod config cluster.
> Align config cluster default remote-secret sa with istiod-remote install

- pilot/test/xdstest/grpc.go
- pilot/test/xdstest/mock_discovery.go
- pkg/istio-agent/agent.go
- pkg/istio-agent/leak_test.go
- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta.go
- pkg/istio-agent/xds_proxy_test.go
* Fix memory leak in xds_proxy when channels are blocked
* add test
* delta and test fixes
* fix logs
* fix other leak
(cherry picked from commit 7870103a91b8686ba24e807377227d804a03806d)
[ ] Docs
[ ] Networking
[ ] Security
> [1.10] Fix memory leak in xds_proxy when channels are blocked (#34098)

- pkg/test/framework/components/echo/echotest/echotest.go
An extra check to avoid using VMs when skip VM is specified. The only reason this doesn't matter is because we exclude the VM config in the echo builder; this adds another layer of safety and decouples from the current echo builder impl.
> echotest exlcudes vms for skipvm flag

- galley/pkg/config/source/inmemory/collection.go
- pilot/pkg/model/envoyfilter.go
- pilot/pkg/xds/ads.go
- pkg/adsc/adsc.go
- security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
- security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin.go
Function Debugf has the same judgment on enable debug as DebugEnabled
```
func (s *Scope) Debugf(args ...interface{}) {
if s.GetOutputLevel() >= DebugLevel {
......
}
}
func (s *Scope) DebugEnabled() bool {
return s.GetOutputLevel() >= DebugLevel
}
```
[ ] Docs
[ √] Networking
[ ] Security
> Remove duplicate judgment for debug log enable

- pkg/istio-agent/health/health_check.go
- security/pkg/pki/ca/ca.go
1. if time.ticker no longer in use ,stop it
[ ] Docs
[x] Networking
[ ] Security
> Time.tickers that are no longer in use should be closed

- tests/fuzz/Dockerfile.fuzz
- tests/fuzz/README.md
Adds a Dockerfile and documentation on running the go-fuzz fuzzers locally.
[ ] Docs
[ ] Networking
[ ] Security
> Fuzzing: Add documentation and Dockerfile

- tests/fuzz/oss_fuzz_build.sh
- tests/fuzz/pilot_model_fuzzer.go
- tests/fuzz/regression_test.go
Adds a fuzzer for the BootstrapNodeMetadata unmarshaling api.
[ ] Docs
[ ] Networking
[ ] Security
> Fuzzing: Add BootstrapNodeMetadata unmarshaling fuzzer

- pkg/test/framework/components/istio/operator.go
- tests/integration/multicluster/centralremotekubeconfig/main_test.go
- tests/integration/multicluster/gateway.go
- tests/integration/multicluster/testdata/gateway.yaml
Work on re-enabling this test with changes. The original test didn't ever work properly as its SUCCESS was a false positive. The test will verify that the test-gateway is actually running and is updated for the External Istiod changes that are in 1.11.
Thanks to many: @GregHanson, @frankbu, @howardjohn, and @stevenctl who contributed to getting this working.
[ ] Docs
[x] Networking
[ ] Security
[x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. …
> Fix external CP integration test

- tests/fuzz/regression_test.go
- tests/fuzz/testdata/FuzzAnalyzer/6169070276837376
This is not fixed, depends on upstream bug fix. Luckily, this is only used in istioctl client side so should not be exploitable.
> Add regression test for yamlv3 bug

- pilot/pkg/bootstrap/server.go
- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/fake.go
- pilot/pkg/xds/simple.go
When I use the master branch code to reproduce this issue https://github.com/istio/istio/issues/34126 ，I found a panic error
```
2021-07-22T01:41:10.072491Z	info	ads	RDS: PUSH for node:reviews-v3-84779c7bbc-246qn.default resources:15 size:11.6kB
2021-07-22T01:41:11.417046Z	info	ads	ADS: new connection for node:test-1.default-7
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x2b5a95a]
goroutine 683 [running]:
istio.io/istio/pilot/pkg/networking/apigen.(*APIGenerator).Generate(0xc0011ad9d0, 0xc00272e400, 0xc001036000, 0xc002717550, 0xc0018e2f50, 0xc00270d600, 0x29, 0xc00270d8c0, 0x2d, 0xd0, ...)
istio.io/istio/pilot/pkg/networking/apigen/apigen.go:108 +0x25a …
```
> Fix panic when use generators

- pilot/pkg/controller/workloadentry/workloadentry_controller.go
- pilot/pkg/controller/workloadentry/workloadentry_controller_test.go
- pilot/pkg/xds/ads.go
- releasenotes/notes/autoregistered-workload-entry-locality.yaml
During testing of VM autoregistration, we discovered that it is not
possible to override the WorkloadGroup template's locality from the
bootstrap node locality. The core issue is that istiod initializes the
proxy struct from the bootstrap node before passing it to the
autoregistration controller; however, the node's locality is not set on
the proxy at that time. This is fixed by passing the bootstrap node
along to autoregistration code in addition to the proxy.
Change-Id: Id9b1d2f0cc5d2cf9416670c26b0a490d302ea039
Reviewed-on: https://gerrit.musta.ch/c/public/istio/+/1391
Reviewed-by: Weibo He <weibo.he@airbnb.com>
Reviewed-by: Jungho Ahn <jungho.ahn@airbnb.com>
[ ] Docs
[ ] Networking
[ ] Policies and …
> autoregistration: allow bootstrap node to override locality

- pkg/test/kube/dump.go
Got a case where test log suggests container crash, but pod state and log does not have any indication about that: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/34202/integ-cni-k8s-tests_istio/1418257862072733696 feels like there might be a race between resource clean up and container crash detection, but before digging into that it would be great to print more terminate state and understand if it is just because container exited normally. We might want to filter out container with exit code 0 from crashed container.
> Filter container with exit code 0 from crashed container.

- manifests/charts/istio-cni/values.yaml
Typically `kube-system` will be excluded as well.
> Update exclude namespaces default for istio-cni.

- tools/istio-iptables/pkg/dependencies/implementation.go
This occurs when `err` is nil but there is stderr output
[ ] Docs
[ ] Networking
[ ] Security
> Fix panic in iptables when there is an error

- pilot/pkg/model/push_context.go
The less function used by `sort.SliceStable` will never be equal, as it uses name+namespace of envoy filter to compare at last. name+namespace of envoy filters wont be the same.
It is better to use `sort.Slice` than `sort.SliceStable`, as `sort.Slice` uses quick sort and `sort.SliceStable` uses insertion sort. This will improve performance when there are a lot of envoy filters.
```go
func (ps *PushContext) initEnvoyFilters(env *Environment) error {
envoyFilterConfigs, err := env.List(gvk.EnvoyFilter, NamespaceAll)
if err != nil {
return err
}
sort.SliceStable(envoyFilterConfigs, func(i, j int) bool {
ifilter := envoyFilterConfigs[i].Spec.(*networking.EnvoyFilter)
jfilter := envoyFilterConfigs[j].Spec.(*networking.EnvoyFilter)
if ifilter.Priority != jfilter.Priority {
return …
```
> no need to sort.SliceStable as no envoy filters are equal

- pilot/pkg/model/xds_cache.go
- pilot/pkg/networking/core/configgen.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/core/v1alpha3/fake.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/cds.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/delta.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/sds.go
- pilot/pkg/xds/sds_test.go
- pilot/pkg/xds/xds_cache_test.go
For the CacheToken added, it is to prevent stale cache.
But there are still cases that it can be stale, e.g. A thread generates eds for a proxy runs super slow, but other threads for the other proxies run super fast.
```
v1 --> proxy2 eds pushed--> v2 --> (proxy1 eds pushed for v1, cache stale endpoint) -> proxy2 eds pushed -> proxy 1 eds push for v2
```
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This …
> Prevent stale cache

- common/scripts/gobuild.sh
- pilot/pkg/features/pilot.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/xds/endpoint_builder.go
- tests/integration/security/reachability_test.go
Fix #34227
The root cause is because two xds stream are both operating on the same `endpointBuilder.IstioEndpoint (a pointer)`. When one stream is sending endpoints to sidecar the other one is mutating the Endpiont.Metadata.FilterMetadata （a map).
We avoid this by making a copy of the original one. The copy is only on demand when necessary. This is similar to what we did in  https://github.com/istio/istio/blob/e490aed372744254e622c6da27edd02f03dbe968/pilot/pkg/xds/endpoint_builder.go#L203
> Fix race condition for auto mTLS plus workload level peer authn.

- tests/integration/pilot/istioctl_test.go
It seems like `primary` is showing the results from `cross-network-primary`'s istiod... I captured the loop var in a new closure so I'm not sure why that's happening. Switching away from `RunParallel` to see if it fixes https://github.com/istio/istio/issues/34192
> fix TestRemoteClusters flake

- tools/istio-clean-iptables/pkg/cmd/cleanup.go
- tools/istio-iptables/pkg/builder/iptables_builder_impl.go
- tools/istio-iptables/pkg/builder/iptables_builder_test.go
- tools/istio-iptables/pkg/cmd/run.go
- tools/istio-iptables/pkg/cmd/run_test.go
- tools/istio-iptables/pkg/cmd/testdata/ipv6-dns-uid-gid.golden
This allows most calls (except ones with IPs) to use a single call for
v4 and v6. This will hopefully make things simpler and reduce drift.
Still not identical: tproxy and dns. Will do that in a followup
> Refactor ipv6 iptables to reduce code duplication

- pilot/cmd/pilot-agent/status/server.go
using http method const values, which have already been defined in package `net/http`,  to replace string literals
[ ] Docs
[ ] Networking
[ ] Security
> using http method defined in net/http to replace string literals

- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/bootstrap/options.go
- pilot/pkg/bootstrap/server.go
when k8s config is found, we could break the loop but not to continue.
simplify some codes, fix some comments and logs
[ ] Docs
[ ] Networking
[ ] Security
> fix break the looop when k8s config is found

- pilot/pkg/config/kube/gateway/conditions.go
when slice index out of range `len(gs.Listeners)`, we should append `until` length is big enough to store a new value, but not just append only once,  this may cause panic due to index out of range, for example, index is 10, and `len(gs.Listeners)` is 1.
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does not have any …
> fix possible panic of slice index out of range

- pilot/pkg/config/kube/ingress/controller.go
- pilot/pkg/config/kube/ingressv1/controller.go
- pilot/pkg/model/config.go
- pilot/pkg/model/context.go
similar to #34279
The less function used by `sort.SliceStable` will never be equal, as it uses name+namespace of resources to compare at last. name+namespace of resources wont be the same.
It is better to use `sort.Slice` than `sort.SliceStable`, as `sort.Slice` uses quick sort and `sort.SliceStable` uses insertion sort. This will improve performance when there are a lot of resources.
```go
func sortIngressByCreationTime(configs []interface{}) []*ingress.Ingress {
ingr := make([]*ingress.Ingress, 0, len(configs))
for _, i := range configs {
ingr = append(ingr, i.(*ingress.Ingress))
}
sort.SliceStable(ingr, func(i, j int) bool {
// If creation time is the same, then behavior is nondeterministic. In this case, we can
// pick an arbitrary but consistent ordering based on name and namespace, …
```
> no need to sort.SliceStable with name+namespace compared

- galley/pkg/config/analysis/analyzers/all.go
- galley/pkg/config/analysis/analyzers/analyzers_test.go
- galley/pkg/config/analysis/analyzers/injection/image-auto.go
- galley/pkg/config/analysis/analyzers/testdata/image-auto.yaml
- galley/pkg/config/analysis/msg/messages.gen.go
- galley/pkg/config/analysis/msg/messages.yaml
- releasenotes/notes/image-auto-analyzer.yaml
If we see `image: auto` in user manifests we know that the resource is intended to be injected. We should warn them if the resource doesn't match injection labels.
[ ] Docs
[ ] Networking
[ ] Security
> Add analyzer to detect "image: auto" on non-injected pods and deployments

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/weighted.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/zero.yaml.golden
- pilot/pkg/config/kube/ingress/conversion.go
- pilot/pkg/config/kube/ingress/conversion_test.go
- pilot/pkg/config/kube/ingress/testdata/simple.yaml.golden
- pilot/pkg/config/kube/ingressv1/conversion.go
- pilot/pkg/config/kube/ingressv1/conversion_test.go
- pilot/pkg/config/kube/ingressv1/testdata/simple.yaml.golden
- releasenotes/notes/kubernetes-ingress-prefix.yaml
- tests/integration/pilot/ingress_test.go
Imagine a Kubernetes Ingress with `path: /sample` and `pathType: Prefix`:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: minimal-ingress
annotations:
nginx.ingress.kubernetes.io/rewrite-target: /
spec:
rules:
- http:
paths:
- path: /sample
pathType: Prefix
backend:
service:
name: test
port:
number: 80
```
In our current implementation we append a `/` to  `/sample` which turns into an exact string prefix match for `/sample/`:
https://github.com/istio/istio/blob/db4afa01f9a696a2c77528d75dacccffa565ea13/pilot/pkg/config/kube/ingressv1/conversion.go#L166-L172
We do this to prevent `/sample` from matching `/samplerandomtext`. However, it also prevents us form matching on `/sample`, which must match per the Ingress spec. Need to use a smarter regex instead to make it so that …
> Fix Kubernetes Ingress and Gateway prefix match

- pilot/pkg/model/config.go
Before:
```
Push debounce stable[2] 1 for config networking.istio.io/v1alpha3/VirtualService/default/route:
```
After:
```
Push debounce stable[2] 1 for config VirtualService/default/route:
```
I do not feel we need to include the version - its actually misleading since users may use other versions externally and we just read a specific version. For group, there is only one case (Gateway) where it matters to distinguish and I don't feel that makes it worth so much extra log noise.
> Trim down long log lines:

- cni/pkg/install/server_test.go
- pkg/test/echo/server/endpoint/http.go
- security/pkg/stsservice/test/setup.go
Fix leaking `response.Body.Close()`.
[ ] Docs
[ ] Networking
[ ] Security
> fix leaking response.Body.Close

- pilot/pkg/model/gateway.go
- pilot/pkg/model/gateway_test.go
- pilot/pkg/model/push_context.go
- pilot/pkg/xds/sds.go
- pilot/pkg/xds/sds_test.go
This implements most of
https://docs.google.com/document/d/1gDhj058q2PKKI9SWpxE23ExEXdOkLiueT8JA_oEJ8Mo/edit#heading=h.bmkc9oooxqbj
Another PR will try to figure out the multicluster change
I tried to capture context in the comments in the code
> Allow gateway-api to function without Kubernetes RBAC

- pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go
- pilot/pkg/serviceregistry/kube/controller/filter/discoverynamespaces.go
- pilot/pkg/serviceregistry/kube/controller/filter/informer.go
- pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
- pilot/pkg/serviceregistry/kube/controller/pod.go
1. when `convertToConfigMap` failed, we should return, or may result in panic due to nil pointer.
2. fix some comments
[ ] Docs
[ ] Networking
[ ] Security
> fix some problems of pilot/serviceregistry

- pilot/pkg/config/aggregate/config.go
- pilot/pkg/config/kube/crdclient/cache_handler.go
- pilot/pkg/config/kube/crdclient/client.go
- pilot/pkg/config/kube/crdclient/client_test.go
- pilot/pkg/config/kube/gateway/controller.go
- pilot/pkg/config/kube/ingress/controller.go
- pilot/pkg/config/kube/ingressv1/controller.go
- pilot/pkg/config/memory/controller.go
- pilot/pkg/model/config.go
- pkg/config/schema/collections/collections.gen.go
- pkg/config/schema/metadata.gen.go
- pkg/config/schema/metadata.yaml
- pkg/kube/secretcontroller/secretcontroller.go
- tests/integration/pilot/ingress_test.go
- tests/integration/pilot/main_test.go
Fixes https://github.com/istio/istio/issues/30834
This is especially useful as we add support for more third party CRDs
(gateway-api and MCS). Currently, using these resources requires a
restart of Istiod. In normal cases, this is not ideal. In worst case
(external Istiod) this is impossible.
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, …
> Handle CRDs created after Istio starts

- pkg/test/echo/server/endpoint/http.go
- pkg/test/echo/server/endpoint/tcp.go
- pkg/test/echo/server/endpoint/util.go
This fixes ipv6 and --bind-ip, where we do not want to connect to
127.0.0.1.
This may look like it works today, but each echo actually has a 10s
delay at startup (we timeout the readiness), likely slowing tests down.
> Fix echo readiness probes when bound to other IPs

- pkg/test/framework/components/echo/call.go
- tests/integration/pilot/ingress_test.go
Fixes #34359.
Before we'd expect a `404` when hitting an ingress endpoint where the corresponding `Ingress` resource had a bogus ingress class. This is wrong since when the Ingress class doesn't match we shouldn't get a response at all (should not even have a generated Gateway). The test relies on a race condition and only passing when the new `Ingress` has not yet taken effect.
[ ] Docs
[x] Networking
[ ] Security
[x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release …
> Fix TestIngress update flake

- galley/testdatasets/validation/dataset/networking-v1alpha3-Sidecar-invalid.yaml
- galley/testdatasets/validation/dataset/networking-v1beta-Sidecar-invalid.yaml
In 1.21, they made this valid on OpenAPI, so it passed presubmit and failed in webhook validator.
For older versions, it is rejected by openapi and so the test fails
> Fix validation test on old k8s

- pilot/pkg/model/jwks_resolver.go
When `client.Get(uri)` is success, but `ioutil.ReadAll` is failed or `resp.StatusCode` is not 2xx, the defer function will only calls `networkFetchFailCounter.Increment()` and return, missing call to `resp.Body.Close()`.
This will result in a leaking of resp.Body.
[ ] Docs
[X] Networking
[ ] Security
> fix body close leaking when ioutil.ReadAll failed or response.StatusCode is not 2xx

- istioctl/pkg/writer/envoy/configdump/listener.go
Fixes #34344.
Makes it so that we don't print the regex engine type on `isitoctl pc route`. Does not implement the smarter prefix recognition.
[ ] Docs
[ ] Networking
[ ] Security
> Make istioctl pc route less verbose for regex match

- pilot/pkg/xds/ads.go
We observed that proxy_clients gauge could go negative in some cases, which based on code inspection could happen if `initConnection` errors out before incrementing the gauge, while `removeConn` is still called to decrement the gauge. This change make proxyClients gets incremented at `addCon`, which at least makes sure the proxy_clients gauge will be the same as `len(s.adsClients)` so that it won't be negative.
> Record proxy clients in addConn.

- pilot/pkg/model/jwks_resolver.go
As the `refreshTicker` has expired here, we could reset the ticker instead of stop and create a new Ticker. 
[ ] Docs
[ ] Networking
[ ] Security
> Reset refreshTicker instead of stop and create a new Ticker

- pkg/dns/server/name_table.go
- pkg/dns/server/name_table_test.go
ServiceEntry with resolution set to NONE, is similar to k8s headless service, the hostname should be resolved to workload instance ips.
Fix: #34224
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior …
> build name table for passthrough ServiceEntry

- pkg/wasm/cache.go
- pkg/wasm/cache_test.go
- pkg/wasm/imagefetcher.go
- pkg/wasm/imagefetcher_test.go
Follow up on #33812. Add support for OCI image fetch in istio-agent for Wasm plugins.
Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>
> wasm: support OCI image fetch in istio-agent.

- pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
- pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
field `refreshIndexes` is already `atomic bool` value, so we do not need to use mutex to protect its read/write.
[ ] Docs
[ ] Networking
[ ] Security
> remove duplicate mutex lock from atomic bool

- tests/integration/pilot/common/apps.go
Having `ISTIO_DELTA_XDS` enabled prior to version 1.10 causes the Delta deployment to hang.
> Require min Istio version 1.11 to deploy Delta app

- pilot/pkg/security/authn/v1beta1/policy_applier.go
- pilot/pkg/xds/endpoint_builder.go
1. a small typo
2. adjust comment format
> Fix a typo: parrent should be parent

- prow/config/mixedlb-service.yaml
Signed-off-by: su225 <suchithjn22@gmail.com>
Required for https://github.com/istio/istio/pull/33817
Updating existing configurations break post-submit test as `MixedProtocolLBService` feature gate was introduced in Kubernetes in 1.20 as documented [here](https://kubernetes.io/docs/concepts/services-networking/service/#load-balancers-with-mixed-protocol-types). So test infra should be updated to use this configuration for K8s >= 1.20.
> add kind configuration with `MixedProtocolLBService` feature flag turned on

- go.sum
- pilot/cmd/pilot-agent/options/security.go
- pkg/istio-agent/agent.go
- pkg/security/security.go
- security/pkg/nodeagent/caclient/providers/citadel/client.go
- security/pkg/nodeagent/caclient/providers/google-cas/client.go
- security/pkg/nodeagent/caclient/providers/google-cas/client_test.go
- security/pkg/nodeagent/caclient/providers/google-cas/mock/ca_mock.go
- security/pkg/nodeagent/caclient/providers/google/client.go
Preliminary effort to add a CA plugin to get certificates signed using[ Google CAS](https://cloud.google.com/certificate-authority-service). This is a manual cherry-pick from master branch 19fb530. 
Similar to Mesh CA integration, Google CAS issues  workload mTLS certificate using identity reflection.
* Istio - Google CAS Integration: Adding Google CAS Client plugin to istio-agent
* Google CAS: Add Mock Google CAS server and unit tests
* Fixing review comments
* Fixing more review comments
[ ] Docs
[ ] Networking
[ ] Security
Please check any characteristics that apply to this pull …
> Google Certificate Authority Service plugin (#33898)

- tools/packaging/common/istio-start.sh
- tools/packaging/common/istio.service
- tools/packaging/packaging.mk
virtual machine OS:  Ubuntu 20.04.1 LTS
istio version: 1.10.0
Running istio(pilot-agent and envoy) on virtual machine, when `systemctl stop istio`, the `istio-pilot` process is terminated,  but the envoy process is still there. I have to kill the envoy process by kill, otherwise `systemctl start istio` will failed as the old envoy process still listens on the port.
How to reproduce this bug:
1. install istio on virtual machine according to [Virtual Machine Installation](https://istio.io/latest/docs/setup/install/virtual-machine/)
2. ensure the istio-pilot and envoy process is running
3. run `systemctl stop isto`, and will find that the istio-pilot process is terminated, but the envoy process is still there, and it's farther process is pid 1 now.
```bash
istio-p+  108661       1  0 20:24 ? …
```
> fix envoy process leak when systemd stop istio

- pilot/pkg/model/xds_cache.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/delta.go
This is a small regression in the change to the token invalidation - .Start is not set on push requests so we lose out on one of the biggest sources of cache hits.
> Allow cached response in initial discovery request

- tests/integration/security/external_ca/main_test.go
https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/
Introduced in 1.19, not 1.18
Regression in https://github.com/istio/istio/pull/34353/files
> Fix CSR test to run on 1.19+

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
We should be adding nil entries when we miss, so we can get the count of
misses. Otherwise, we miscount, which occasionally leads to 0 hits and
not logging `cached:x/y` at all
> Properly count CDS cache miss

- pkg/test/framework/resource/version.go
- pkg/test/framework/resource/version_test.go
- pkg/test/framework/test.go
- tests/integration/pilot/common/apps.go
- tests/integration/pilot/common/traffic.go
Makes it much easier to deal with version-based skips, before had to do `Settings().Revisions.Minimum().Compare()` and deal with an int result.
Also fixes a backwards skip condition when deploying delta app (had the `Compare()` backwards and also had `skipDelta` where it should have been `!skipDelta`...)
cc @sergii-ssh 
> [tf] Add AtLeast to RevVerMap

- pilot/pkg/config/memory/store.go
- pkg/adsc/adsc.go
- pkg/adsc/adsc_test.go
Fixes #34126 
use the master branch code to reproduce this issue, there will also be these warn logs, but can receive update events
```
2021-07-22T07:25:58.033224Z	info	adsc	Received istiod.istio-system.svc:15010 type networking.istio.io/v1alpha3/VirtualService cnt=2 nonce=94AAXEWSWkU=5e49198f-e507-4e38-8d34-d0793609aaa7
2021-07-22T07:25:58.033555Z	info	config-controller	receive istio event update, curr istio-system/tcp-stats-filter-1.9
2021-07-22T07:25:58.033559Z	info	config-controller	receive istio event update, curr istio-system/metadata-exchange-1.10
2021-07-22T07:25:58.033562Z	info	config-controller	receive istio event update, curr istio-system/metadata-exchange-1.9
2021-07-22T07:25:58.033565Z	info	config-controller	receive istio event add, curr default/testwr …
```
> Fix unexpected error when using mcp-over-xds

- releasenotes/notes/cni-promote.yaml
https://github.com/istio/enhancements/issues/86 tracks cni beta promotion and will be closed once https://github.com/istio/enhancements/pull/94 is merged.
> Add release notes to promote CNI to beta.

- pilot/cmd/pilot-agent/status/server.go
- pilot/cmd/pilot-agent/status/server_test.go
- releasenotes/notes/probe-redirect.yaml
This is large copy+paste from kubelet code. Before, we would just
blindly follow redirects. This has some DOS implications (not a big deal
since it just kills your own pod, unlike kubelet which is shared) and
also breaks when the redirect goes external because sourceIP=127.0.0.6
does not work for external call.
The new logic, matching kubelet:
* If we exceed 10 redirects, the probe fails
* If we redirect somewhere external, the probe succeeds immediately
* If we redirect to the same address, the probe will follow the redirect
Fixes https://github.com/istio/istio/issues/29468
Fixes https://github.com/istio/istio/issues/34238
> Properly handle redirects in app prober

- galley/pkg/config/analysis/analyzers/analyzers_test.go
- galley/pkg/config/analysis/analyzers/injection/injection-image.go
- galley/pkg/config/analysis/analyzers/injection/injection.go
- galley/pkg/config/analysis/analyzers/testdata/common/sidecar-injector-enabled-nsbydefault.yaml
- galley/pkg/config/analysis/analyzers/util/config.go
- galley/pkg/config/analysis/analyzers/util/constants.go
- galley/pkg/config/analysis/msg/messages.gen.go
- galley/pkg/config/analysis/msg/messages.yaml
According to [doc](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy), namespaces or pods should be treated as injectable if Istio is installed with sidecarInjectorWebhook.enableNamespacesByDefault=true and there is no any injected label is set.
This bug fixed 2 issues:
1. removed unnecessary information for injection analysis for some systems namespaces, such as istio-system, kube-system etc.
2. check the injection option `sidecarInjectorWebhook.enableNamespacesByDefault` if no label is set.
There is also new unit test for `sidecarInjectorWebhook.enableNamespacesByDefault` case.
**Please check any characteristics that apply to …
> fixed bug for injection analysis if Istio is installed with sidecarInjectorWebhook.enableNamespacesByDefault=true

- pilot/pkg/xds/ads_test.go
- pilot/pkg/xds/cds.go
- pilot/pkg/xds/cds_test.go
VirtualService and Gateway both donot influence sidecar cds.
> Skip push cds for sidecar when virtualService updated

- pilot/cmd/pilot-discovery/app/cmd.go
The current path is `./etc/istio/config/mesh`, use absolute path instead, keep it consistent with `networksConfig`.
[ X ] Configuration Infrastructure
[ ] Docs
[ ] Networking
[ ] Security
[ X ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
> [FIX]default mesh config file path

- pkg/bootstrap/instance_test.go
- pkg/bootstrap/testdata/metrics_no_statsd.proxycfg
- pkg/bootstrap/testdata/metrics_no_statsd_golden.json
- tools/packaging/common/envoy_bootstrap.json
Due to the new Bootstrap Discovery Service, and how the template is rendered in transport, a formatting issue in bootstrap template related to the metrics service just surfaced. This fixes the issue for a strict JSON formatting.
When `envoyMetricsService` is present in the `MeshConfig`, the following warning can be observed in `istiod`
```2021-08-05T12:40:13.550596Z     warn       ads     failed to unmarshal bootstrap from JSON "": invalid character ']' looking for beginning of value```
Which corresponds to the following [line of code](https://github.com/istio/istio/blob/master/pilot/pkg/xds/bootstrapds.go#L58).
It seems that the way this was being rendered was not an issue before, but the jsonpb Unmarshal is stricter about commas. …
> fix metrics service render

- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go
- pilot/pkg/serviceregistry/kube/controller/endpoint_builder_test.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pilot/pkg/serviceregistry/serviceentry/conversion_test.go
- pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
- pilot/pkg/serviceregistry/util/label/label.go
With this, we can support weighted traffic routing to different networks.
```
metadata:
name: httpbin
spec:
host: httpbin
trafficPolicy:
loadBalancer:
simple: LEAST_CONN
subsets:
- name: network1
labels:
topology.istio.io/network: network1
- name: kubernetes
labels:
topology.istio.io/network: network2
```
> Added network label

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/testdata/zero.yaml.golden
Joined with https://github.com/kubernetes-sigs/gateway-api/pull/743,
this allows displaying non-empty results when there is no external IP
for the Gateway (ie its a cluster IP gateway)
> Report internal address if external address is not present

- pilot/pkg/xds/ads_test.go
- pilot/pkg/xds/cds.go
- pilot/pkg/xds/cds_test.go
Reverts istio/istio#34537
This is to add back https://github.com/istio/istio/pull/27651 which fixed https://github.com/istio/istio/issues/27650
We can probably filter many VS updates, but need a bit more complex logic I think
> Revert "Skip push cds for sidecar when virtualService updated"

- pilot/pkg/networking/core/v1alpha3/accesslog.go
- pilot/pkg/networking/core/v1alpha3/accesslog_test.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
- releasenotes/notes/34468.yaml
After reading the issue #34466, I found that the `SubstitutionFormatString_TextFormat` has been deprecated in Envoy v1.17.0 in favor of `SubstitutionFormatString_TextFormatSource`. This PR is to move the old syntax format to the newer API version.
> replace SubstitutionFormatString_TextFormat(deprecated) to SubstitutionFormatString_TextFormatSource for the accessLogFormat

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Causes excessive memory usage. I am almost certain this is fixed in `master` already because we got rid of the tokens; over 75% of the memory is spent on storing the tokens.
> [1.11] Fully disable CDS cache

- tools/packaging/postinst.sh
This change makes the evaluation of `useradd` and `groupadd` less dependant on the OS type and more reliant on the availability of the command itself. The current `if` statement does not work in SUSE distros since SUSE also uses  `groupadd` and `useradd` same as redhat and centos.
> Make the adduser evaluation in post-install less OS dependant

- pilot/pkg/util/sets/string.go
- pilot/pkg/util/sets/string_test.go
This is not used anywhere, so no impact yet -  but will break when somone tries to use it (like I did).
We implemented Union as Intersection
> Fix sets.Union

- pilot/pkg/xds/ads.go
- pilot/pkg/xds/delta.go
- pilot/pkg/xds/xdsgen.go
`versionInfo()` can get too newer version, previously `pushVersion` does not exist in PushContext
> use pushVersion instead of versionInfo()

- pilot/pkg/xds/README.md
Change istio-pilot address ($PILOT) - istiod.istio-system instead of istio-pilot.istio-system
istio-pilot.istio-system now working now
> Change istio-pilot address

- pilot/pkg/config/kube/ingressv1/conversion.go
- pilot/pkg/networking/grpcgen/grpcgen_test.go
- pkg/istio-agent/agent_test.go
- pkg/istio-agent/grpcxds/grpc_bootstrap.go
- pkg/istio-agent/testdata/grpc-bootstrap.json
The previous code used `Node.RawMetadata`
For everything except the following call, we extract into `untypedMeta`, but here we extract into typed meta.
https://github.com/istio/istio/blob/6da7a3193970e46ebe6cf748f6411f1de1d286ec/pkg/bootstrap/config.go#L492
This means the gRPC bootstrap ends up missing out on  a few critical fields:
* POD_NAME
* POD_NAMESPACE
* SERVICE_ACCOUNT
* ISTIO_METAJSON_LABELS
Without this fix we can't set namespace-level policy like PeerAuthn
> grpc xds bootstrap: include full node metadata

- pilot/pkg/xds/fake.go
- pilot/pkg/xds/xds_test.go
```
~/g/s/i/istio ❯❯❯ go test ./pilot/pkg/xds -run TestClusterLocal -count 50                                                                                                                                              ✘ 130 master ✭ ✱
ok      istio.io/istio/pilot/pkg/xds    2.101s
```
Previously we decided the "default" cluster based on which cluster in the `k8sObjects` map we saw first (which has inconsistent map ordering). 
This allows setting that cluster explicitly. This is the cluster that WorkloadEntry endpoints are considered "local" to. 
fixes https://github.com/istio/istio/issues/34638
> set default cluster for fake discovery server

- pkg/config/validation/validation_test.go
- pkg/config/validation/virtualservice.go
- pkg/config/validation/virtualservice_test.go
mirrorPercentage should not be negative number.
Current master branch allow users to set negative number and will not be effect, it looks alright but a little confused.
```
metadata:
name: httpbin
spec:
hosts:
- httpbin
http:
- mirror:
host: httpbin
subset: v2
mirrorPercentage:
value: -100
route:
- destination:
host: httpbin
subset: v1
weight: 100
```
> mirrorPercentage should not be negative number

- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/components/echo/kube/deployment_test.go
- pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions-no-proxy.yaml
This PR is part of future work to support istio skip-level upgrade testing from versions below 1.8 (which do not re-inject a pod if istio-proxy is already present).
> support istio skip ugrade testing

- pkg/kube/client.go
PortFowarder should be close as soon as being created successfully, but not only after start it successfully
[ ] Docs
[ ] Networking
[ ] Security
> fix portforwarder Close time

- istioctl/cmd/options.go
- istioctl/cmd/workload.go
- istioctl/cmd/workload_test.go
This PR fixed bug to extract clusterID from injector config for istioctl experimental workload entry configure.
In this PR, I imported a function named `validateFlagIsSetManuallyOrNot`  to validate that a persistent flag is set manually or not by user for given command. I think it should be a useful.
> extract clusterID from injector config for istioctl experimental workload entry configure

- pkg/kube/client.go
Reverts istio/istio#34034
not sure  whether istio/istio#34034 is correct or not, 
not sure when `func (f *forwarder) Close()` should be called? only when PortFowarder  `Start()` function is called successfully, or 
just when it being created successfully
https://github.com/istio/istio/blob/0ba661aea9d7e264b7b5f1670d2d3bbfe4fd569d/pkg/kube/portforwarder.go#L74-L78
> Revert "fix portforwarder Close time"

- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
In the scene where service entry select workload entry
The priority of the model.IstioEndPoint.EndpointPort port should be : unixAddress > we.ports > se.port.targetPort > se.port.number
[ ] Docs
[x] Networking
[ ] Security
> In the scene where service entry select workload entry：set up istio endpoint port

- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/httproute_test.go
Fix for https://github.com/istio/istio/issues/34533 . Brackets are added to ipv6 addresses while pushing envoy config.
>  Envoy expects IPv6 address within '[]' for domains under route_config #34533 

- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/kube/conversion.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
When I use the master branch code to reproduce this issue #34126 ，I found that service entry converted from k8s service does not have resource version. 
for client, function handles the received resources
https://github.com/istio/istio/blob/8efca561efcab2d1322ebd2d50b7ecc01bfe21e5/pkg/adsc/adsc.go#L1262
If the resource version is not set, the client store always updates the resource, even if the resource has not changed.
Add resource version: if service entry is converted from k8s service, it inherits the resource version of k8s service. update the client store only when the resource changed.
[ ] Docs
[ ] Networking
[ ] Security
[ ] …
> In the mcp-over-xds scene: add resource version for service entry

- tests/integration/istiodremote/base/main_test.go
- tests/integration/istiodremote/gateway.go
- tests/integration/istiodremote/multicluster/main_test.go
- tests/integration/multicluster/base/main_test.go
- tests/integration/multicluster/cluster_local.go
- tests/integration/multicluster/loadbalancing.go
- tests/integration/multicluster/reachability.go
- tests/integration/multicluster/telemetry.go
Signed-off-by: su225 <suchithjn22@gmail.com>
Part of #34517 - As mentioned in this issue, `multicluster` label is no longer required as `RequiresMinClusters > 1` implies that. It is redundant. So remove it. However, the label itself is not removed as tests fail because of "unknown label". It will be removed once job configs are fixed in test-infra repo.
> remove multicluster label as RequiresMinClusters > 1 implies that

- pilot/pkg/xds/debug.go
Since we are moving hash as cache keys we need a better way to represent them in debug. This PR displays typeUrl and resource names in debug mode.
> add resource names in debug cache

- Makefile.core.mk
Fixes https://github.com/istio/istio/issues/34705
https://github.com/istio/istio/issues/34705 notes an issue with brew creating the istioctl and completion files on the new 11.0 thread.  See the issue for more discussion, but the problem is that the hombrew make command uses a `-j6` parameter to use multiple threads and does not build in the build container. Because multiple threads are being used, the dependency for the targets are not yet completed and we get an error about a missing target. This PR adds the targets so there is no missing dependency.
> Add additional targets for use outside container with multiple threads.

- pkg/kube/spdy.go
- pkg/test/echo/server/forwarder/instance.go
- pkg/test/echo/server/forwarder/protocol.go
- pkg/test/framework/components/cluster/cluster.go
- pkg/test/framework/components/cluster/config.go
- pkg/test/framework/components/cluster/kube/factory.go
- pkg/test/framework/components/cluster/topology.go
- pkg/test/framework/components/echo/call.go
- pkg/test/framework/components/echo/common/call.go
- pkg/test/framework/components/istio/ingress.go
This PR is to extend the test framework to support connection via proxy. This is for testing with clusters which requires http proxy to connect to the kubernetes API server or connect to the ingress gateway.  
> test framework support connection via proxy

- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/grpcgen/grpcecho_test.go
- pilot/pkg/networking/grpcgen/grpcgen_test.go
- pilot/pkg/networking/grpcgen/lds.go
- pilot/pkg/networking/grpcgen/lds_test.go
When a proxyless client dials `xds:///foo:123`, it expects a listener named `foo:123` exactly. 
Currently, we look at egress listener services and generate a listener if the filtered name and port matches the FQDN of the service. 
To support making requests using shortnames (foo, foo.ns, foo.ns.svc) we generate the list of AltVirtualHost domains. If the requested listener matches one of these, we build the listener with that exact name. 
Since it's possible for a gRPC app to have watches against both `foo` and `foo.ns`, we must duplicate the listener with each of the requested names.
> grpc xds: support calling service using shortnames

- pilot/pkg/bootstrap/certcontroller.go
- pkg/config/constants/constants.go
- pkg/test/csrctrl/controllers/csr_controller.go
- pkg/test/csrctrl/signer/signer.go
- security/pkg/k8s/chiron/controller.go
- security/pkg/k8s/chiron/utils.go
- security/pkg/k8s/chiron/utils_test.go
- security/pkg/pki/ra/k8s_ra.go
user can specify the workload cert TTL via `SECRET_TTL`, however this option is ignored if we use K8s RA as cert provider. 
cert-manager supports to use `experimental.cert-manager.io/request-duration` annotation in  k8s CSR, So this PR will add the annotation to the CSR istio generated to support the eco-system.
> respect cert TTL in client side for k8s RA

- release/downloadIstioCandidate.sh
- release/downloadIstioCtl.sh
Fixes https://github.com/istio/istio/issues/34668. Change the sort parameter from --version-sort to -V as Alpine only supports the later. The Mac and looking at man pages for other Linux versions shows the -V is supported there as well.
> Change sort --version-sort to -V for alpine (other Linux/GNU supports)

- cni/pkg/install/install.go
- cni/pkg/util/util.go
`Installer.Run` of `install-cni` will watch `cfg.MountedCNINetDir`(`/host/etc/cni/net.d`), if config files in this dir have changed, `Installer.Run` will reinstall all files(binary, kube config, cni config, etc).
```go
func (in *Installer) Run(ctx context.Context) (err error) {
for {
if err = copyBinaries(
in.cfg.CNIBinSourceDir, in.cfg.CNIBinTargetDirs,
in.cfg.UpdateCNIBinaries, in.cfg.SkipCNIBinaries); err != nil {
cniInstalls.With(resultLabel.Value(resultCopyBinariesFailure)).Increment()
return
}
...
if err = sleepCheckInstall(ctx, in.cfg, in.cniConfigFilepath, in.isReady); err != nil {
return
}
// Invalid config; pod set to "NotReady"
installLog.Info("Restarting...")
}
}
```
When testing this feature I find that this only take effect when …
> fix fsnotify event proc missing for install-cni

- pilot/cmd/pilot-agent/options/agent.go
- pilot/cmd/pilot-agent/options/options.go
- pkg/istio-agent/agent.go
- pkg/istio-agent/xds_proxy.go
15004 is now apparently also hardcoded, so make it customizable.
> envoy: remove another hardcoded port

- pilot/pkg/model/virtualservice.go
- pilot/pkg/model/virtualservice_test.go
If the virtual service has same name across namespaces, the current SelectVirtualServices logic incorrectly skips that VS. This fixes it.
> add virtual service namespace to detect uniqueness

- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/config/memory/controller.go
- pilot/pkg/config/memory/controller_test.go
- pkg/adsc/adsc.go
- pkg/adsc/adsc_test.go
In current istio codebase, memory config controller does not impl the `HasSynced` method which means we will wait for readiness of config source using mem store (such as mcp-over-xds). And this will break the integrity of istiod state control.
This PR impl `HasSynced` for mem controller and use it in the XDS configsource case.
> Impl HasSynced for memory controller and improve HasSynced of ADSC

- pilot/pkg/xds/debug.go
Allows users to get proxy node metadata via /debug/adsz
> Add nodemetadata debug interface

- pkg/wasm/cache.go
- pkg/wasm/cache_test.go
This PR resolves a [TODO](https://github.com/istio/istio/blob/master/pkg/wasm/cache.go#L164) left in pkg/wasm, and adds the sanity-check for verifying fetched Wasm binaries have valid binary header.
Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>
cc @bianpengyuan
> wasm: check if fetched binaries are valid.

- istioctl/cmd/proxyconfig.go
- istioctl/pkg/util/configdump/secret.go
- istioctl/pkg/writer/envoy/configdump/configdump.go
This PR will add new subcommand for proxy-config of istioctl to check their ROOTCA between 2 given pods.
[ ] Docs
[ ] Networking
[ ] Security
> add new subcommand for proxy-config to check the ROOTCA between 2 given pods

- pilot/cmd/pilot-agent/options/options.go
- pilot/cmd/pilot-agent/options/security.go
- pkg/security/security.go
- security/pkg/nodeagent/cache/secretcache.go
> [release-1.11] make file debounce duration configurable

- cni/pkg/install/install.go
- cni/pkg/util/util.go
fix #34524
@bianpengyuan 
PR #34710 just fix watching for cni config dir, not the cni bin dir.
We should add cni bin dir to watcher, to make sure the cni bin file(istio-cni) is always correct.
> add watching for cni plugin bin dir

- pkg/test/kube/dump.go
On test failure we should dump all Kube clusters, including the external control plane cluster.
> [tf] Dump external control plane cluster

- tests/integration/pilot/common/routing.go
Getting hung on the initial request, either from test runner -> gw or gw -> endpoint can fail this test. This helps the test fail fast(er) and actually leverage retries.
> add timeout to autopassthrough test

- pkg/test/framework/components/istio/operator.go
- pkg/test/kube/dump.go
Dump mutating and validating webhooks on test failure. Can be helpful to debug failures in startup and tests covering validating webhook behavior.
> [tf] Dump webhooks in operator dump

- pilot/cmd/pilot-agent/metrics/metrics.go
Envoy is initialized way before the readiness succeeds. Make this explicit in the comment.
> envoy: fix confusing log

- pkg/kube/inject/template.go
- pkg/kube/inject/webhook.go
- pkg/kube/inject/webhook_test.go
Fixes https://github.com/istio/istio/issues/34799
Inspired by https://github.com/istio/istio/pull/34803 (we may still want that one as well)
```
$ cat /tmp/old
goos: linux
goarch: amd64
pkg: istio.io/istio/pkg/kube/inject
cpu: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
10        12302795235 ns/op       3494954690 B/op  7523207 allocs/op
10        12152944856 ns/op       3495193698 B/op  7523328 allocs/op
10        13032458981 ns/op       3495241792 B/op  7523395 allocs/op
PASS
ok      istio.io/istio/pkg/kube/inject  158.548s
$ cat /tmp/new
goos: linux
goarch: amd64
pkg: istio.io/istio/pkg/kube/inject
cpu: Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
10         858556624 ns/op        351448878 B/op    585319 allocs/op
10        1010176965 ns/op        351284525 B/op    585313 allocs/op
10 …
```
> Improve injection performance

- pilot/pkg/model/network.go
- pilot/pkg/xds/eds_sh_test.go
- pilot/pkg/xds/ep_filters.go
- pilot/pkg/xds/ep_filters_test.go
It could be this case, 
cluster1, neytwork1:
-  3 eastwest gateway
-  1 endpoint (10.0.0.1)
cluster2, network2:
-  2 eastwest gateway (20.0.0.1) (20.0.0.2)
-  1 endpoint (20.0.0.100)
Take this as an example, for a proxy in cluster1:
** Without this pr:
endpoints:
- 10.0.0.1 weight 3
- 20.0.0.1 weight 2
- 20.0.0.2 weight 1
We can see the two gateways of networks get unbalanced weight. As the real endpoints in network2 grows, the unbalance becomes severe. 
** With this pr:
endpoints:
- 10.0.0.1 weight 6
- 20.0.0.1 weight 3
- 20.0.0.2 weight 3
The gateways of network2 have equal lb weight
**Please check any characteristics that apply to this …
> Fix endpoint filter

- tests/fuzz/bootstrap_fuzzer.go
- tests/fuzz/oss_fuzz_build.sh
- tests/fuzz/regression_test.go
Adds fuzzer that creates a fuzzed `bootstrap.PilotArgs{}` and passes it on to `bootstrap.NewServer()`
> Fuzzing: Add bootstrap fuzzer

- pilot/pkg/networking/core/v1alpha3/route/retry/retry.go
- pilot/pkg/networking/core/v1alpha3/route/retry/retry_test.go
If retry policy specifies Http Status codes, we add them to retriable-status-codes. But if user does not add `retriable-status-codes`  in the retry policy but just adds Http status they will not be retries. This PR fixes it.
> add retriable status codes to retry policy

- security/pkg/k8s/chiron/utils.go
- security/pkg/k8s/chiron/utils_test.go
instead of return silently when no certificate has been returned for the k8s CSR, log an error out to user to let user know the failure reasons.
> return error if no certificate has been returned from signer for k8s CSR

- tests/integration/pilot/ingress_test.go
- tests/integration/security/sds_ingress/ingress_test.go
- tests/integration/security/sds_ingress/util/util.go
- tests/integration/security/sds_tls_origination/egress_gateway_origination_test.go
- tests/integration/security/sds_tls_origination/util/util.go
* Only pass in a single credential name. If they need multiple can
always just call the function in a loop
* Always delete it when create, instead of making all callers do it (and
some do it wrong)
* Allow specifying namespace explicitly. This is not used yet, but will
be in a near PR
* Reduce duplication of same logic in 2 places
> Refactor test framework certificate management

- pkg/config/mesh/mesh.go
- pkg/config/mesh/mesh_test.go
This is useful with the share mesh config feature, as it allows this
field to be essentially append-only. This follows the pattern used by
`providers`.
> Deep merge trust domain aliases

- istioctl/cmd/workload.go
- istioctl/cmd/workload_test.go
This removes the non-standard `INFO: ` output. It also makes the code
simpler.
Example output:
```
$ istioctl x workload entry configure --name vm --namespace default -o /tmp/vm
Error: failed to automatically determine the --clusterID: fetch injection template: configmaps "istio-sidecar-injector" not found
```
> cleanup clusterID detection a bit

- galley/pkg/config/analysis/analyzers/analyzers_test.go
- galley/pkg/config/analysis/analyzers/injection/injection-image.go
- galley/pkg/config/analysis/analyzers/testdata/injection-with-mismatched-sidecar.yaml
- galley/pkg/config/analysis/analyzers/testdata/sidecar-injector-configmap-with-revision-canary.yaml
Need to handle the injection configmaps with different revisions when doing analysis on injection container istio-proxy image.
Generally,  this case should be normal when user need to upgrade their Istio from lower version to higher. Unit test case added as well.
> fixed bug for analysis on injection container istio-proxy image

- pilot/pkg/networking/networking.go
- pilot/pkg/networking/networking_test.go
http_proxy should be as treated as http listener protocol
> Refactor `ModelProtocolToListenerProtocol` and added HTTP_PROXY

- pilot/pkg/bootstrap/mesh.go
- pkg/config/mesh/watcher.go
Same with this pr https://github.com/istio/istio/pull/19878, we use json format with indent instead of spew for readability.
> Use json format with indent for logging meshconfig instead of spew

- pilot/pkg/xds/lds.go
- releasenotes/notes/34944.yaml
Partial fix https://github.com/istio/istio/issues/34944 although this only affects a small number of cases. We should still have a way to optimize when there is no autopassthrough. 
This is better than config not being reflected though.
> DestinationRule triggers lds for gateways

- pkg/test/echo/server/endpoint/grpc.go
method RegisterService has been defined in the ServiceRegistrar
reflection.GRPCServer inherits ServiceRegistrar and grpcServer inherits reflection.GRPCServer,  so grpcServer inherits this method, does not need define this method again.
> Delete the duplicated definition method RegisterService

- samples/ratelimit/rate-limit-service.yaml
Enable ratelimit config reload automatically when the configMap has been updated.
How to do this?
- Set the RUNTIME_WATCH_ROOT environment variable to false, and let ratelimit update the contents inside RUNTIME_ROOT/RUNTIME_SUBDIRECTORY/config/ directly.
- Delete the subPath, because a container using a ConfigMap as a subPath volume mount will not receive ConfigMaps updates.
Related issue: https://github.com/istio/istio/issues/34890
> Enable ratelimit config reload automatically when the configMap has been updated

- galley/pkg/config/analysis/analyzers/analyzers_test.go
- galley/pkg/config/analysis/analyzers/injection/image-auto.go
- galley/pkg/config/analysis/analyzers/testdata/image-auto.yaml
Fixes #34929. Should ignore the namespace from the pod spec and use the namespace from the deployment spec when determining namespace selector matches for "image: auto" analyzer.
> Fix Deployment namespace bug in image: auto analyzer

- pkg/adsc/adsc.go
Our mcp resources server has lots of services with huge number of service instances. When we use mcp-over-xds protocol to get service entry resources by adsc client, we got the following error.
```
2021-09-01T20:13:39.787444Z info    adsc    Connection closed for node sidecar~22.1.72.106~test-
1.default~default.svc.cluster.local with err: rpc error: 
code = ResourceExhausted desc = grpc: received message larger than max (19542550 vs. 4194304)
```
The default received message size of grpc is 4mb which is really not enough for huge services. So I think we can simply set it to math.MaxInt32 which does same with `XdsProxy`.
https://github.com/istio/istio/blob/dceadfc91e5d7aafefd12cac87c7ffc27858dc9b/pkg/istio-agent/xds_proxy.go#L630-L655
> Bump up default grpc transport settings for adsc.

- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/route/route_cache.go
removes push version dependency from route cache
> remove pushVersion from route cache key

- pilot/pkg/features/pilot.go
- pilot/pkg/model/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
According to the comments, it can be removed in 1.12
> rm PILOT_USE_TARGET_PORT_FOR_GATEWAY_ROUTES

- pilot/pkg/model/context.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
So that ingress-gateway and egress-gateway can reuse the existing namespace sidecarscope when no `Sidecar` created in root namespace instead of generating one for each gateway.
> set gateway sidecarscope from getSidecarScope

- tests/integration/pilot/mcs/discoverability/discoverability_test.go
Feature was introduced in 1.11
> Require Istio 1.11 for MCS test

- tests/fuzz/oss_fuzz_build.sh
Brings back FuzzValidateClusters without the initialization of the jwt resolver to avoid having the fuzzer generate outgoing network traffic.
> Fuzzing: Bring back FuzzValidateClusters

- istioctl/cmd/istiodconfig.go
- istioctl/cmd/istiodconfig_test.go
- releasenotes/notes/34982.yaml
Currently, the `admin log` command will output something like:
```
➜  istio-1.11.1 istioctl admin log
active_scopes:
ads:info
adsc:info
analysis:info
authn:info
```
This PR is to revise the first line of the ouput, to be the format like below:
```
Active scopes:
ads:info
adsc:info
analysis:info
authn:info
```
> revise admin log to be more formatted like other commands

- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/util/util.go
This is not a huge perf impact but with many clusters (especially in large k8s clusters) this is adding some overhead. So adding a flag to control this behaviour. Ideally we can deprecate existing `PILOT_ENDPOINT_TELEMETRY_LABEL` and remove it later. For now I have added a new flag that works for both.
> add flag to control cluster telemetry metadata

- pilot/pkg/controller/workloadentry/workloadentry_controller.go
Instead of returning an Unknown error when the WorkloadEntry cannot be
found, return NOT_FOUND instead so clients recognize the error as a
client issue instead of an istiod issue.
> Return NOT_FOUND when WorkloadEntry cannot be found

- tests/fuzz/kube_fuzzer.go
- tests/fuzz/oss_fuzz_build.sh
- tests/fuzz/regression_test.go
Adds fuzzer that targets istio.io/istio/galley/pkg/config/source/kube/inmemory APIs
> Fuzzing: Add kube fuzzer

- pilot/pkg/xds/delta.go
- pilot/pkg/xds/monitoring.go
- pilot/pkg/xds/xdsgen.go
Currently, when send's fail, the logging is sparse. This makes it hard
to tell what is going on - was the push really large, causing a timeout?
Was it a small push and something else caused it? Etc.
This just adds the same logging info for success and failed pushes to
give a bit more details
> Add more details to Send Failure logs
