istio/istio

pilot/pkg/dns/dns.go, pilot/pkg/dns/monitoring.go
[ ] Docs
[X] Networking
[ ] Security
=> address dns metrics comments

tests/fuzz/regression_test.go
This ensures they pass at least a few simple inputs, and as we hit bugs
we can add regression test cases
@AdamKorcz
=> Add all current fuzzers to fuzz regression test

pkg/config/validation/validation.go, pkg/config/validation/validation_test.go
add validation for ControlPlaneAuthPolicy/StatusPort
add test
[ ] Docs
[ ] Networking
[ ] Security
=> Add more validation for ProxyConfig

pilot/pkg/bootstrap/configcontroller.go, pilot/pkg/features/pilot.go, pilot/pkg/status/reporter.go, releasenotes/notes/add_updateInterval_to_env_var.yaml
[ ] Docs
[ ] Networking
[ ] Security
=> Add statusUpdateInterval environment variable.

pilot/pkg/features/pilot.go
[ ] Docs
[X] Networking
[ ] Security
=> minor comment fix

pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/gateway.go
[ ] Docs
[ ] Networking
[ ] Security
=> removed defaultDestinationRule

tests/integration/security/authorization_test.go, tests/integration/security/main_test.go
[ ] Docs
[ ] Networking
[x] Security
=> update the CUSTOM authorization e2e test to use PatchMeshConfig

cni/pkg/cmd/root.go, cni/pkg/config/config.go, cni/pkg/constants/constants.go, cni/pkg/monitoring/monitoring.go, cni/test/install_cni.go
fix https://github.com/istio/istio/issues/33795
=> Disable monitoring in CNI install test.

pilot/pkg/bootstrap/configcontroller.go, pilot/pkg/config/kube/gateway/conditions.go, pilot/pkg/config/kube/gateway/controller.go, pilot/pkg/features/pilot.go, pilot/pkg/leaderelection/leaderelection.go
[ ] Docs
[ ] Networking
[ ] Security
=> Make gateway status writing optional and add leader election

pilot/pkg/grpc/grpc.go
This is due to recent gRPC upgrade. We get spam like `xdsproxy        upstream [1] terminated with unexpected error rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data:`
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance …
=> Fix spammy gRPC logs in agent

pilot/pkg/model/push_context.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, pkg/config/validation/validation.go
This is a regression recently introduced.
[ ] Docs
[x] Networking
[ ] Security
=> Fix ServiceInstance selection with labels

pkg/kube/client.go, pkg/kube/portforwarder.go, pkg/kube/rpc_creds.go
modify some comment to comply with programming specifications, and simplify some codes
[ ] Docs
[ ] Networking
[ ] Security
[ X] User Experience
=> do some cleanup in kube pkg

pkg/test/framework/components/echo/kube/deployment.go
[ ] Docs
[ ] Networking
[ ] Security
=> Enable debug log for security filters on VM for integration tests

pilot/pkg/networking/core/v1alpha3/route/route.go
[ ] Docs
[ ] Networking
[ ] Security
=> check BuildHTTPRoutesForVirtualService first

tests/fuzz/compare_fuzzer.go, tests/fuzz/oss_fuzz_build.sh, tests/fuzz/regression_test.go
Adds a fuzzer for `istioctl/pkg/writer/compare.Diff`
[ ] Docs
[ ] Networking
[ ] Security
=> Fuzzing: Add compare.Diff fuzzer

tests/integration/security/jwt_test.go, tests/integration/security/util/framework.go
[ ] Docs
[ ] Networking
[ ] Security
Fix #32392
=> Differentiate traffic by request path in test log

tests/integration/security/fuzz/README.md
[ ] Docs
[ ] Networking
[x] Security
=> update fuzz test documentation

istioctl/pkg/multicluster/remote_secret.go, istioctl/pkg/multicluster/remote_secret_test.go
Fix https://github.com/istio/istio/issues/33831
=> fix server warning message to stderr to avoid example yaml error

galley/pkg/config/analysis/analyzers/gateway/certificate.go
fix the TODO in gateway cert analyzer.
[ ] Docs
[ ] Networking
[ ] Security
=> add PILOT_SCOPE_GATEWAY_TO_NAMESPACE var check to gateway cert analyzer

pilot/pkg/status/reporter.go
use ` metav1.SchemeGroupVersion.WithKind("Pod")`, so we don't worry about the version.
[ ] Docs
[ ] Networking
[ ] Security
=> Use metav1.SchemeGroupVersion

pilot/pkg/networking/core/v1alpha3/route/retry/retry.go, pilot/pkg/networking/core/v1alpha3/route/retry/retry_test.go, releasenotes/notes/33737.yaml
Manual backport of #33793 
[ ] Docs
[X] Networking
[ ] Security
=> [release-1.10] - fix retry remote localities

pilot/pkg/model/sidecar.go, pilot/pkg/model/sidecar_test.go, releasenotes/notes/33387.yaml
Manual backport of https://github.com/istio/istio/pull/33820
[ ] Docs
[X] Networking
[ ] Security
=> [release-1.10]  fix sidecar scope when specific host is mentioned

cni/deployments/kubernetes/Dockerfile.install-cni, cni/pkg/install/install.go, cni/pkg/install/install_test.go, cni/pkg/plugin/iptables.go, cni/test/install_cni.go, tools/istio-iptables/pkg/cmd/root.go, tools/istio-iptables/pkg/cmd/run.go, tools/istio-iptables/pkg/config/config.go, tools/istio-iptables/pkg/constants/constants.go, tools/istio-iptables/pkg/dependencies/implementation.go
For #32901. Also add a file output path param to iptables, which will be used for CNI dry run test in later PRs.
=> Build istio-iptables into istio-cni.

security/pkg/credentialfetcher/plugin/gce_test.go
[ ] Docs
[ ] Networking
[x] Security
Fixes https://github.com/istio/istio/issues/32620
=> Raise retry timeout for unit test TestTokenRotationJob

tests/fuzz/inject_fuzzer.go, tests/fuzz/oss_fuzz_build.sh, tests/fuzz/regression_test.go, tests/fuzz/testdata/inject/fuzz_into_resource_file.dict
Adds fuzzer that targets inject.IntoResourceFile.
[ ] Docs
[ ] Networking
[ ] Security
=> Fuzzing: Add inject.IntoResourceFile fuzzer

tools/istio-iptables/pkg/cmd/run.go
Just some cleanup, the generated iptables is identical
=> Refactor some repetition in iptables UDP rules

cni/pkg/cmd/root.go, cni/test/install_cni.go
[ ] Docs
[ ] Networking
[ ] Security
=> Add controlz to install-cni.

pkg/kube/inject/inject_test.go, pkg/kube/inject/testdata/inject/traffic-annotations.yaml, pkg/kube/inject/testdata/inject/traffic-annotations.yaml.injected
[ ] Docs
[X] Networking
[ ] Security
=> add injection test with custom proxy config and override metadata

cni/pkg/install/binaries.go, cni/pkg/install/cniconfig.go, cni/pkg/install/install.go, cni/pkg/install/kubeconfig.go, cni/pkg/repair/repair.go, cni/pkg/repair/repaircontroller.go
[ ] Docs
[ ] Networking
[ ] Security
=> Add install and repair log scope to CNI.

manifests/charts/istio-operator/values.yaml
[ ] Docs
[ ] Networking
[ ] Security
=> delete one extra empty line from yaml in istio-operator charts

CODEOWNERS
[ ] Docs
[ ] Networking
[ ] Security
=> Adding codeowners for /pkg/dns

tests/integration/security/authorization_test.go, tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go, tests/integration/security/jwt_test.go, tests/integration/security/util/framework.go, tests/integration/security/util/reachability/context.go, tests/integration/telemetry/stackdriver/stackdriver_filter_dry_run_test.go
[ ] Docs
[ ] Networking
[x] Security
=> Add policy readiness check in tests

security/pkg/nodeagent/sds/server.go
Fixes https://github.com/istio/istio/issues/33958
This is not a real issue in prod but fails tests.
[ ] Docs
[ ] Networking
[ ] Security
=> fix goroutine leak in agent test

pilot/cmd/pilot-agent/status/server.go
Connection is not closed when unsuccessful
[ ] Docs
[ ] Networking
[ ] Security
=> pilot/cmd/pilot-agent/status: Connection is not closed when unsuccessful

pilot/pkg/networking/core/v1alpha3/cluster_builder.go
[ ] Docs
[X] Networking
[ ] Security
=> add warning if locality endpoints are missing for DNS clusters

security/pkg/nodeagent/cache/secretcache.go
We reset the total timeout on each iteration, so we never actually hit
it. Now we will properly timeout after 10s
=> Fix timeout issue on file certs

pilot/pkg/bootstrap/servicecontroller.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go, pilot/pkg/xds/debug.go, pilot/pkg/xds/discovery.go, pkg/cluster/debug.go, pkg/kube/secretcontroller/secretcontroller.go
related to https://github.com/istio/istio/issues/33799, not sure if the "sync status" is the best – timeout can be confusing and technically can switch from timeout -> synced.
=> add clusterz multicluster debug endpoint

pkg/config/crd/validator.go
[ ] Docs
[ ] Networking
[ ] Security
=> pkg/config/crd: Fix NewValidatorFromFiles forgot to close the files

tests/integration/security/jwt_test.go
[ ] Docs
[ ] Networking
[ ] Security
=> Check config readiness in tests

pkg/kube/apimirror/probe.go, pkg/kube/inject/app_probe.go, pkg/kube/inject/inject.go, pkg/kube/inject/validate.go, pkg/kube/secretcontroller/secretcontroller.go
1. fix some comment errors, comply with programming specifications
2. fix some log errors
[ ] Docs
[ ] Networking
[ ] Security
=> modify some codes of pkg/kube

pkg/kube/client.go, pkg/kube/portforwarder.go
1. fix some logs: should use `namespace/name` format but not use `name/namespace` format
[ ] Docs
[ ] Networking
[ ] Security
=> fix kube client logs format

cni/pkg/install/install.go, cni/pkg/install/monitoring.go, cni/pkg/install/server.go
for https://github.com/istio/istio/issues/32437
=> Add metrics for CNI installations and readiness.

go.mod, go.sum, tests/fuzz/inject_fuzzer.go
Removes a fuzz helper function to fuzz a map. The helper has been added to go-fuzz-headers.
[ ] Docs
[ ] Networking
[ ] Security
=> Fuzzing: Refactor inject fuzzer

pilot/pkg/networking/core/v1alpha3/httproute.go
The current code is a little hard to follow and isn't well documented. This PR attempts to restructure the method slightly to more clearly separate k8s and non-k8s scenarios.
There is a small amount of duplicate code in each `if` branch for the case when `len(uniqueHostnameParts) == 2`, but it's not much and is probably worth the duplication.
These changes also avoid a couple needless calls to `strings.Split` and `strings.Join`.
[ ] Docs
[x] Networking
[ ] Security
[ ] Does not have any …
=> Cleanup HTTP virtual host generation logic

pkg/config/validation/validation.go, pkg/config/validation/virtualservice.go, pkg/config/validation/virtualservice_test.go, releasenotes/notes/34065.yaml
Fix https://github.com/istio/istio/issues/34065
=> Add empty regex validator

Makefile.core.mk
Fixes #34090 
[ ] Docs
[ ] Networking
[ ] Security
=> Update istioctl completion file targets

cni/cmd/istio-cni/main.go, cni/pkg/cmd/root.go, cni/pkg/config/config.go, cni/pkg/constants/constants.go, cni/pkg/install/cniconfig.go, cni/pkg/log/uds.go, cni/pkg/log/uds_test.go, cni/pkg/plugin/intercept_rule_mgr.go, cni/pkg/plugin/iptables.go, cni/pkg/plugin/kubernetes.go, cni/pkg/plugin/plugin.go, cni/pkg/plugin/plugin_test.go, cni/pkg/plugin/redirect.go, cni/test/install_cni.go, manifests/charts/istio-cni/templates/configmap-cni.yaml, manifests/charts/istio-cni/templates/daemonset.yaml, releasenotes/notes/cni-uds-log.yaml
Cherry-pick https://github.com/istio/istio/pull/33926
fix https://github.com/istio/istio/issues/34094
=> [release-1.11] Add UDS log to CNI plugin. (#33926)

pkg/config/validation/validation.go, pkg/config/validation/validation_test.go
For https://github.com/istio/istio/pull/33766#issuecomment-872667419
=> Add sidecar egress hosts conflict warnings

pilot/cmd/pilot-agent/status/ready/probe.go, pilot/cmd/pilot-agent/status/ready/probe_test.go
Fixes https://github.com/istio/istio/issues/34108
=> Modify agent readiness failure logs to be more accurate

security/pkg/k8s/tokenreview/k8sauthn.go, security/pkg/k8s/tokenreview/k8sauthn_test.go
add unit test for function `getTokenReviewResult`, remove `TODO` flag
[ ] Docs
[ ] Networking
[ ] Security
=> add unit test for getTokenReviewResult

pilot/pkg/networking/core/v1alpha3/gateway.go, pkg/config/security/security.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, tests/integration/pilot/common/routing.go
Fixes https://github.com/istio/istio/issues/34084
=> Add validation to prevent invalid cipher suites

CODEOWNERS
[ ] Docs
[ ] Networking
[ ] Security
=> Update values.yaml CODEOWNERS to current environments leads

go.mod, go.sum, licenses/github.com/cespare/xxhash/LICENSE.txt, licenses/github.com/prometheus/prometheus/LICENSE, pilot/cmd/pilot-agent/status/server.go, pilot/cmd/pilot-agent/status/server_test.go, releasenotes/notes/openmetrics-merging.yaml
Cherry-pick of https://github.com/istio/istio/pull/33550
Fixes https://github.com/istio/istio/issues/33474
=> [release-1.11] Support OpenMetrics format for metrics merging (#33550)

pilot/test/xdstest/grpc.go, pilot/test/xdstest/mock_discovery.go, pkg/istio-agent/agent.go, pkg/istio-agent/leak_test.go, pkg/istio-agent/xds_proxy.go, pkg/istio-agent/xds_proxy_delta.go, pkg/istio-agent/xds_proxy_test.go
Fixes https://github.com/istio/istio/issues/34097
~I have some tests locally but its really hacky, will cleanup and add before submitting~ Tests added. This was a bit tricky to test, but the test fails without the PR and passes with it, so I think its all good.
=> Fix memory leak in xds_proxy when channels are blocked

pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/networking/core/v1alpha3/httproute_test.go, pilot/pkg/networking/core/v1alpha3/route/route.go
Only handle virtualServices related to this route, instead of all
[ ] Docs
[ ] Networking
[ ] Security
=> Added selecting virtualservice

pilot/pkg/model/push_context.go
Just a small typo.
[ ] Docs
[X] Networking
[ ] Security
=> fix a typo: prirority should be priority

pilot/pkg/model/push_context.go
[ ] Docs
[ ] Networking
[ ] Security
=> Extract method for duplicate code

pilot/pkg/model/gateway_test.go, pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/gateway_test.go, releasenotes/notes/33405.yaml
Manual backport of https://github.com/istio/istio/pull/33411
[ ] Docs
[X] Networking
[ ] Security
=> [release-1.10] fix gateway merge on same port

istioctl/cmd/clusters.go, istioctl/cmd/root.go, pkg/test/framework/features/features.yaml, releasenotes/notes/34086.yaml, tests/integration/pilot/istioctl_test.go
```
istioctl x remote-clusters
NAME            SECRET                 STATUS     ISTIOD
cluster-123     cluster-123-secret     synced     istiod-wxyz-123
```
fixes https://github.com/istio/istio/issues/33799
=> istioctl x remote-clusters

pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/util/sets/string.go, pkg/config/security/security.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, tests/integration/pilot/common/routing.go, tests/integration/security/sds_ingress/util/util.go
fixes https://github.com/istio/istio/issues/34148
=> [1.9] Add validation to prevent invalid cipher suites

tests/integration/pilot/istioctl_test.go
Mitigate https://github.com/istio/istio/issues/34192. This is a brand new test that is flaky
=> Skip new flaky test TestRemoteClusters

pkg/config/validation/validation.go
For: https://github.com/istio/istio/pull/33069#discussion_r660129490
=> fix add details message if jwks error

pilot/pkg/model/context.go, pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/networking.go, pilot/pkg/networking/plugin/authn/authentication.go
1.  a small typo
2.  adjust comment format
[ ] Docs
[ ] Networking
[ ] Security
=> Fix a typo: poxy should be proxy

pilot/pkg/xds/ads.go, pkg/test/framework/resource/flags.go, pkg/test/framework/resource/settings.go, tests/integration/pilot/common/apps.go
Should give us some good e2e testing, for pretty small cost
=> Add workload using delta xds

pkg/config/validation/validation.go
Delete non-essential temporary variables
[ ] Docs
[ ] Networking
[ ] Security
=> Remove non-essential flag parameters

istioctl/pkg/writer/pilot/status.go, istioctl/pkg/writer/pilot/status_test.go, istioctl/pkg/writer/pilot/testdata/multiXdsStatusMultiPilot.txt, istioctl/pkg/writer/pilot/testdata/multiXdsStatusSinglePilot.txt, pilot/pkg/xds/statusgen.go
This PR is to fix the issue #33980. The old struct is deprecated, and i just revise it to the new one.
[ ] Docs
[ ] Networking
[ ] Security
=> fix deprecated xds config struct

samples/bookinfo/src/ratings/ratings.js
Fixes #34205 
[x] Docs
[ ] Networking
[ ] Security
=> Fix connect to MongoDB in bookinfo ratings v2

pilot/pkg/model/context.go, pkg/istio-agent/agent.go, pkg/istio-agent/xds_proxy.go
[ ] Docs
[ ] Networking
[ ] Security
=> Add a small code optimization

tests/fuzz/oss_fuzz_build.sh, tests/fuzz/regression_test.go, tests/fuzz/v1alpha3_fuzzer.go
Adds a v1alpha3 fuzzer.
[ ] Docs
[ ] Networking
[ ] Security
=> Fuzzing: Add v1alpha3 fuzzer

pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/util.go, pilot/pkg/serviceregistry/serviceregistry_test.go
manual cherry-pick 
fixes https://github.com/istio/istio/issues/34180
=> [release-1.11] allow WorkloadEntry port mapping to use regular port name

cni/pkg/log/uds.go
It does some prechecks like removing the old file and
creating the parent directories.
=> cni: Use the method in uds package to create a listener

istioctl/cmd/revision.go, istioctl/cmd/root.go, istioctl/cmd/tag.go, releasenotes/notes/graudate-revision-tag-command.yaml, tests/integration/pilot/revisioncmd/revision_view_test.go, tests/integration/pilot/revisions/revision_tag_test.go
Discussed and approved in UX WG meeting.
[ ] Docs
[ ] Networking
[ ] Security
=> Graduate revision command from experimental

pilot/pkg/features/pilot.go, tests/integration/security/reachability_test.go
See https://github.com/istio/istio/issues/34227
[ ] Docs
[ ] Networking
[ ] Security
=> Disable EnableAutomTLSCheckPolicies due to race condition

pilot/pkg/model/gateway.go, pilot/pkg/model/push_context.go, pilot/pkg/networking/core/v1alpha3/gateway.go
=> add server to filtered cipher suites log

pkg/security/security.go, security/pkg/nodeagent/cache/secretcache.go, security/pkg/nodeagent/cache/secretcache_test.go, security/pkg/nodeagent/caclient/providers/citadel/client.go, security/pkg/nodeagent/caclient/providers/google/client.go, security/pkg/nodeagent/caclient/providers/mock/mockcaclient.go
=> Revert "[release-1.10] istio-agent csr flow: add api for caClient plugins to explicitly provide CA TrustAnchors if available"

pilot/pkg/xds/delta.go
This is only in delta which is why not much complaint before
=> Remove noisy log to debug in delta xds

pilot/cmd/pilot-agent/config/config.go, pilot/cmd/pilot-agent/options/util.go, pilot/cmd/pilot-agent/wait.go, pkg/bootstrap/config.go
fix the logs format of annotation
modify some comments
[ ] Docs
[ ] Networking
[ ] Security
=> modify some codes of pilot-agent

pilot/pkg/xds/bench_test.go
Broken by https://github.com/istio/istio/pull/33611 accidentally
=> Fix cluster benchmark to actually generate clusters

pilot/pkg/networking/core/v1alpha3/gateway.go, pkg/config/security/security.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, tests/integration/pilot/common/routing.go, tests/integration/security/sds_ingress/util/util.go
Fixes https://github.com/istio/istio/issues/34146
=> [1.10] Add validation to prevent invalid cipher suites

security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go, security/pkg/server/ca/authenticate/kubeauth/kube_jwt_test.go
Fixes https://github.com/istio/istio/issues/34293
[ ] Docs
[ ] Networking
[ ] Security
=> Fix 1p jwt on k8s 1.21+ (again)

pilot/pkg/model/sidecar.go, pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/networking/core/v1alpha3/route/route.go
carved out from https://github.com/istio/istio/pull/34247 to simplify review. No functional changes.
[ ] Docs
[X] Networking
[ ] Security
=> refactor route logic to reuse code

pilot/pkg/model/config.go, pilot/pkg/xds/discovery.go
Slightly alternate solution to https://github.com/istio/istio/pull/33576
[ ] Docs
[X] Networking
[ ] Security
=> add config to push log

pilot/pkg/model/authentication.go, pilot/pkg/model/config.go, pilot/pkg/model/context.go, pilot/pkg/model/envoyfilter.go, pilot/pkg/model/jwks_resolver.go, pilot/pkg/model/listener.go, pilot/pkg/model/push_context.go, pilot/pkg/xds/debug.go
1. add if judgement to avoid possible panic
2. add lock to protect variable ` LastPushStatus` read/write
3. simplify some codes
4. modify some comments
[ ] Docs
[ ] Networking
[ ] Security
[ ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, …
=> modify some codes of pilot/model

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go
[ ] Docs
[ ] Networking
[ ] Security
=> clusterID is not set when build cluster key

pilot/pkg/config/kube/gateway/conversion.go, pilot/pkg/config/kube/gateway/testdata/http.yaml.golden, pilot/pkg/config/kube/gateway/testdata/weighted.yaml.golden, pilot/pkg/config/kube/ingress/conversion.go, pilot/pkg/config/kube/ingress/conversion_test.go, pilot/pkg/config/kube/ingress/testdata/simple.yaml.golden, pilot/pkg/config/kube/ingressv1/conversion.go, pilot/pkg/config/kube/ingressv1/conversion_test.go, pilot/pkg/config/kube/ingressv1/testdata/simple.yaml.golden, releasenotes/notes/kubernetes-ingress-prefix.yaml, tests/integration/pilot/ingress_test.go
Manual cherry-pick of #34295 
[ ] Docs
[ ] Networking
[ ] Security
=> [release-1.11] Fix Kubernetes Ingress and Gateway prefix match

pilot/pkg/model/service.go, pilot/pkg/model/sidecar.go
there is one place where to forget add Mutex protect, add Mutex to protect read/write
[ ] Docs
[ ] Networking
[ ] Security
=> fix add mutex lock to protect ClusterVIPs read/write

galley/pkg/config/analysis/analyzers/all.go, galley/pkg/config/analysis/analyzers/analyzers_test.go, galley/pkg/config/analysis/analyzers/injection/image-auto.go, galley/pkg/config/analysis/analyzers/testdata/image-auto.yaml, galley/pkg/config/analysis/msg/messages.gen.go, galley/pkg/config/analysis/msg/messages.yaml, releasenotes/notes/image-auto-analyzer.yaml
Manual cherry-pick of #33951 
fixes #34321
=> [release-1.10] Add analyzer to detect "image: auto" on non-injected pods and deployments

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go
manually cherry-pick  #34327
[ ] Docs
[x] Networking
[ ] Security
=> [Release 1.11] Fix clusterID is not set when build cluster key

pilot/pkg/xds/discovery.go
Adjust log line for better readability
[ ] Docs
[X] Networking
[ ] Security
=> adjust log line

tests/fuzz/v1alpha3_fuzzer.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fuzzing: Add more targets to v1alpha3 fuzzer

manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml, manifests/charts/istio-control/istio-discovery/files/grpc-agent.yaml, pilot/pkg/networking/grpcgen/grpcecho_test.go
fixes https://github.com/istio/istio/issues/34364
=> [release-1.11] small fixes for proxyless grpc

pilot/pkg/networking/core/v1alpha3/httproute_test.go, pilot/pkg/networking/core/v1alpha3/route/route.go
Adds test case for https://github.com/istio/istio/issues/34171
[ ] Docs
[X] Networking
[ ] Security
=> add test case for virtual service hosts

go.mod, go.sum, istioctl/cmd/istioctl/main.go, istioctl/cmd/root.go, pilot/cmd/pilot-agent/main.go, pilot/cmd/pilot-discovery/main.go
[ ] Docs
[ ] Networking
[ ] Security
=> use vklog from istio/pkg, enable for pilot/agent

pilot/pkg/features/pilot.go
Related issue: #34356
[ ] Docs
[ ] Networking
[ ] Security
=> temparaily disable cds cache as there is potential inconsitence

operator/pkg/manifest/shared.go, releasenotes/notes/33864.yaml
This is a manual cherry-pick of #33864
=> [release-1.11] fix istioctl install display error

pilot/pkg/networking/core/v1alpha3/cluster.go
[ ] Docs
[X] Networking
[ ] Security
=> minor delta refactor

go.mod, go.sum
Updates to most recent version of the pkg libraries.
=> update istio.io/pkg to latest version

pkg/test/kube/dump.go
Fix #34345
[ ] Docs
[ ] Networking
[ ] Security
=> Only care about istio components restart

pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go, pilot/pkg/networking/core/v1alpha3/listener_builder.go
[ ] Docs
[ ] Networking
[ ] Security
=> cleanup unused params

security/pkg/nodeagent/caclient/providers/google-cas/client.go
[ ] Docs
[ ] Networking
[X] Security
=> Ca CAS plugin: Minor fix

pilot/pkg/features/pilot.go, pilot/pkg/security/authn/v1beta1/policy_applier.go, security/tools/jwt/samples/README.md
Find a few typos when reading the code.
[ ] Docs
[ ] Networking
[ ] Security
=> fix some typos

tests/integration/pilot/common/routing.go, tests/integration/pilot/common/traffic.go
Hoping this will detect https://github.com/istio/istio/issues/34356
[ ] Docs
[ ] Networking
[ ] Security
=> Add test for envoyfilter

tests/fuzz/v1alpha3_fuzzer.go
[ ] Docs
[ ] Networking
[ ] Security
=> Fuzzing: Fiz OSS-fuzz issue 36646

pkg/config/schema/collection/schema.go, pkg/config/schema/collection/schemas.go
some comments of functions are not correct, fix these errors.
=> fix not correct comments

pilot/pkg/simulation/traffic.go, pilot/pkg/status/reporter.go, pilot/pkg/status/resourcelock.go, pilot/pkg/status/state.go
fix some little problems
when found, should break the loop but not to continue to the next loop
use `%T` but not `%t` to format variable Type
fix some comments
=> fix some little problems

pkg/dns/server/name_table.go, pkg/dns/server/name_table_test.go
=> use the same logic for external registry in name table

pilot/cmd/pilot-agent/status/server.go
Simple attempt at fixing https://github.com/istio/istio/issues/34388
[ ] Docs
[ ] Networking
[x] Policies and Telemetry
[ ] Security
=> Check if application metrics are intended to be disabled

tests/fuzz/oss_fuzz_build.sh
Disables a fuzzer. It needs a bit more work before running continuously.
=> Fuzzing: Disable one fuzzer

pilot/pkg/config/kube/gateway/conversion.go, pilot/pkg/config/kube/gateway/testdata/http.yaml.golden, pilot/pkg/config/kube/gateway/testdata/weighted.yaml.golden, pilot/pkg/config/kube/ingress/conversion.go, pilot/pkg/config/kube/ingress/conversion_test.go, pilot/pkg/config/kube/ingress/testdata/simple.yaml.golden, pilot/pkg/config/kube/ingressv1/conversion.go, pilot/pkg/config/kube/ingressv1/conversion_test.go, pilot/pkg/config/kube/ingressv1/testdata/simple.yaml.golden, releasenotes/notes/kubernetes-ingress-prefix.yaml, tests/integration/pilot/ingress_test.go
=> [release-1.10] Fix Kubernetes Ingress and Gateway prefix match

pkg/test/framework/components/echo/call.go, tests/integration/pilot/ingress_test.go
=> [release-1.10] Manual cherry-pick of #34373

manifests/charts/istio-control/istio-discovery/NOTES.txt, operator/cmd/mesh/install.go
Add upgrade survey url to install command output.
=> Add upgrade survey 1.11

pilot/pkg/model/envoyfilter.go, pilot/pkg/model/push_context_test.go, pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Fix: #34356
[ ] Docs
[ ] Networking
[ ] Security
=> Added envoyfilters dependency to cds cache

pilot/pkg/xds/debug.go
=> Add debug command to clear cache

istioctl/pkg/multicluster/remote_secret.go
=> fix a comment in remote_secret.go

pilot/pkg/features/pilot.go
Since https://github.com/istio/istio/pull/34404
=> Re-enable CDS cache now that envoyfilter key is fixed

pilot/pkg/model/envoyfilter.go, pilot/pkg/model/push_context_test.go, pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go
* Add envoyfilter dependency to cluster cache
* Fix comments
Fix: #34503
=> [release-1.11] Added envoyfilters dependency to cds cache

pilot/pkg/features/pilot.go, pilot/pkg/model/envoyfilter.go, pilot/pkg/networking/core/configgen.go, pilot/pkg/networking/core/v1alpha3/fake.go, pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/networking/core/v1alpha3/httproute_test.go, pilot/pkg/networking/core/v1alpha3/route/route.go, pilot/pkg/networking/core/v1alpha3/route/route_cache.go, pilot/pkg/networking/core/v1alpha3/route/route_test.go, pilot/pkg/networking/grpcgen/rds.go, pilot/pkg/xds/debug.go, pilot/pkg/xds/debug_test.go, pilot/pkg/xds/rds.go
[ ] Docs
[x] Networking
[ ] Security
=> Added rds cache

pilot/pkg/config/kube/gateway/conversion.go, tests/integration/pilot/ingress_test.go
=> [release-1.10] Manual cherry-pick of #34378 

pilot/pkg/model/context.go, pilot/pkg/networking/core/configgen.go, pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/xds/cds.go
Carved out some pieces from https://github.com/istio/istio/pull/34464 that are agreed up on.
=> refactor build clusters logic

releasenotes/notes/cni-promote.yaml
=> Correct area for CNI beta graduation release notes.

pilot/pkg/model/context.go, pilot/pkg/networking/apigen/apigen.go, pilot/pkg/networking/grpcgen/grpcgen.go, pilot/pkg/xds/bootstrapds.go, pilot/pkg/xds/debuggen.go, pilot/pkg/xds/delta.go, pilot/pkg/xds/ecds.go, pilot/pkg/xds/eds.go, pilot/pkg/xds/lds.go, pilot/pkg/xds/nds.go, pilot/pkg/xds/pcds.go, pilot/pkg/xds/rds.go, pilot/pkg/xds/sds.go, pilot/pkg/xds/statusgen.go, security/pkg/nodeagent/sds/sdsservice.go
Attempt to avoid the boiler plate code for all generators. Does this make sense?
=> refactor xds resource generator interface

pilot/pkg/config/kube/gateway/conversion.go, pilot/pkg/config/kube/gateway/testdata/http.yaml, pilot/pkg/config/kube/gateway/testdata/http.yaml.golden, pilot/pkg/config/kube/gateway/testdata/zero.yaml.golden, pilot/pkg/config/kube/ingress/conversion.go, pilot/pkg/config/kube/ingressv1/conversion.go
=> Optimize simple / prefix case for ingress

pilot/cmd/pilot-agent/status/server.go, pilot/cmd/pilot-agent/status/server_test.go, releasenotes/notes/probe-redirect.yaml
Fixes https://github.com/istio/istio/issues/34528
Not critical for 1.11.0 but nice to have
=> Properly handle redirects in app prober (#34291)

pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
=> Fix unlimited retry when namespace is deleted earlier

pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
Fixes https://github.com/istio/istio/issues/34566
Regression from https://github.com/istio/istio/pull/33929
=> Fix subsets with no labels

pilot/pkg/features/pilot.go, pilot/pkg/model/envoyfilter.go, pilot/pkg/model/push_context.go, pilot/pkg/model/service.go
1. a small typo
2. adjust comment format
=> Fix a typo: isitod should be istiod

pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
Fixes https://github.com/istio/istio/issues/34574
=> Fix subsets with no labels (#34568)

pilot/pkg/networking/core/v1alpha3/cluster_builder.go
See https://github.com/istio/istio/pull/34589 for context
=> Fully disable CDS cache

pilot/pkg/networking/core/v1alpha3/cluster_builder.go
=> Fix disable cache

pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Fixes https://github.com/istio/istio/issues/34607
=> Fix disable cache (#34597)

pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go, pilot/pkg/serviceregistry/kube/controller/endpoint_builder_test.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go, pilot/pkg/serviceregistry/serviceentry/conversion.go, pilot/pkg/serviceregistry/serviceentry/conversion_test.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/workloadentry.go, pilot/pkg/serviceregistry/util/label/label.go
This is an improvement after #34487
FYI: https://github.com/istio/istio/pull/34487#discussion_r684020982
=> Unify workloadentry and pod topology label

samples/bookinfo/src/productpage/productpage.py
Remove redundant requests dependency import.
- [ X ] Installation
=> remove redundant requests dependency

tools/bug-report/pkg/content/content.go
Fix https://github.com/istio/istio/issues/34596
=> Add webhook and namespace resources in bug-report

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go
=> Cleanup：remove server metadata cert

pilot/pkg/networking/core/v1alpha3/route/retry/retry.go, pilot/pkg/networking/core/v1alpha3/route/route.go
=> simplify code of route proc

pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/components/echo/kube/deployment_test.go, pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions-no-proxy.yaml
=> support istio skip ugrade testing

pkg/adsc/adsc.go, releasenotes/notes/34633.yaml
This PR fix a bug in adsc. Which will cause adsc hang when having received initial resource push.
=> Fix adsc wrong syncCh size

pilot/pkg/bootstrap/server.go
=> change to debug log

pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/listener_test.go
add function EnableHTTP10() to increase readability
=> add function EnableHTTP10() to increase readability

tests/integration/README.md
native-environment-default and kubernetes-environment chapter has been deleted, update the table of contents.
=> update the table of contents

pkg/adsc/adsc_test.go, pkg/bootstrap/platform/gcp.go, pkg/config/constants/constants.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, pkg/test/echo/common/model.go, pkg/test/framework/components/cluster/topology.go, pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/components/echo/kube/workload_manager.go, pkg/test/framework/components/istio/helm.go, pkg/wasm/imagefetcher.go, pkg/wasm/imagefetcher_test.go
fix typo spelling grammar, replace the typo to correct words with reference from [merriam-webster](merriam-webster)
=> fix: typo spelling grammar

tests/integration/pilot/ingress_test.go
This PR was submitted for [Issue#34645](https://github.com/istio/istio/issues/34645).  `TestGateway` will apply `GatewayClass, HTTPRoute and TCPRoute` yaml files and call function `retry.UntilSuccessOrFail` to detect the CRDs creation via retry package.
=> TestGateway flake and wait for CRD creation about issue#34645

pilot/pkg/bootstrap/monitoring.go, pilot/pkg/bootstrap/server.go, pkg/istio-agent/xds_proxy.go, security/pkg/stsservice/server/server.go
=> Set timeout for http server

security/pkg/nodeagent/caclient/providers/citadel/client_test.go
ref: https://github.com/istio/istio/issues/34115
the root cause is the go routinue blocked by the serve function and is executed after the tests completed. add a waitgroup to sync the goroutine
=> fix data race issue

istioctl/cmd/root.go, istioctl/cmd/version.go, operator/cmd/mesh/profile-diff.go, operator/cmd/mesh/profile-dump.go, operator/cmd/mesh/profile.go, operator/cmd/mesh/root.go, operator/pkg/manifest/shared.go, releasenotes/notes/34325.yaml
This is a manual cherry-pick of #34325
=> [release-1.10] fix `istioctl profile dump` and `istioctl profile diff` have the extra info log

pilot/cmd/pilot-agent/options/agent.go, pilot/cmd/pilot-agent/options/options.go, pilot/pkg/model/context.go, pkg/bootstrap/config.go, pkg/bootstrap/instance_test.go, pkg/bootstrap/option/instances.go, pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/metrics_no_statsd_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json, pkg/istio-agent/agent.go, pkg/istio-agent/agent_test.go, pkg/istio-agent/grpcxds/grpc_bootstrap.go, pkg/istio-agent/testdata/grpc-bootstrap.json, tools/packaging/common/envoy_bootstrap.json
This has been stable for a number of releases now
I put a bunch of assignees since I am not sure if there is some usage of this I wasn't aware of
=> Remove proxy via agent option

pilot/pkg/xds/endpoint_builder.go
=> move endpoint builder to use md5 hash a cache key

pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/metrics_no_statsd_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json, tools/packaging/common/envoy_bootstrap.json
=> envoy: use new connection pool

pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/components/environment/kube/fake.go, pkg/test/framework/components/environment/kube/kube.go, pkg/test/framework/components/istio/config.go, pkg/test/framework/components/istio/operator.go, pkg/test/framework/resource/environment.go, pkg/test/framework/suitecontext.go, pkg/test/framework/testcontext.go, prow/config/topology/external-istiod.json, tests/integration/iop-externalistiod-remote-integration-test-gateways.yaml, tests/integration/istiodremote/base/main_test.go, tests/integration/istiodremote/multicluster/main_test.go
=> Test framework fixes to support pilot tests in external istiod topology

tests/integration/pilot/common/apps.go
=> Require 1.11 to deploy Delta app

tools/istio-iptables/pkg/cmd/run.go
Fix the iptables function name 
Signed-off-by: Yuchen Dai <silentdai@gmail.com>
=> iptables: fix function name

istioctl/cmd/dashboard.go
=> istioctl/cmd: Fix portForwarder close

istioctl/cmd/add-to-mesh.go, pilot/pkg/bootstrap/istio_ca.go, security/pkg/nodeagent/util/util.go
some typos of `kubernetes` is not correct, fix these wrong typos
[ ] Docs
[ ] Networking
[ ] Security
=> modify some wrong typos of kubernetes

pkg/test/framework/label/labels.go, pkg/test/framework/label/labels_test.go
Signed-off-by: su225 <suchithjn22@gmail.com>
Fixes https://github.com/istio/istio/issues/34517
=> remove multicluster label

pkg/config/mesh/mesh.go, pkg/config/mesh/mesh_test.go
Fixes https://github.com/istio/istio/issues/34657
Alternative to https://github.com/istio/istio/pull/34654/files
This is sent directly to 1.10 since it only impacts 1.10. I will add the test to master for regression test.
=> Fix overwriting proxy config

pilot/pkg/model/context.go, pilot/pkg/model/push_context.go, pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, pilot/pkg/networking/core/v1alpha3/cluster_test.go
Removes proxy dependency in cluster builder
=> remove proxy dependency in cluster builder

pkg/config/mesh/mesh_test.go
=> Add regression test for mutating mesh config

manifests/charts/gateways/istio-egress/values.yaml, manifests/charts/gateways/istio-ingress/values.yaml, samples/multicluster/gen-eastwest-gateway.sh
=> Remove unneeded env var on gateway

pilot/pkg/bootstrap/configcontroller.go, pilot/pkg/config/memory/controller.go, pilot/pkg/config/memory/controller_test.go
=> Simplify memory controller

pilot/cmd/pilot-agent/main.go, pkg/security/security.go, security/pkg/nodeagent/cache/secretcache.go
=> [release-1.9] make file debounce duration configurable

pilot/cmd/pilot-agent/options/options.go, pilot/cmd/pilot-agent/options/security.go, pkg/security/security.go, security/pkg/nodeagent/cache/secretcache.go
=> [release-1.10] make file debounce duration configurable

pilot/pkg/serviceregistry/kube/controller/controller_test.go, pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go, pilot/pkg/serviceregistry/kube/controller/endpoint_builder_test.go, pilot/pkg/serviceregistry/serviceentry/conversion.go, pilot/pkg/serviceregistry/serviceentry/conversion_test.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/util/label/label.go, releasenotes/notes/34672.yaml
Reverts istio/istio#34660 now 1.11.0 has been released
=> [release-1.11] Added network label

go.mod, go.sum, pilot/pkg/networking/grpcgen/grpcgen_test.go
=> Update grpc-go to v1.40.0

istioctl/cmd/root.go, istioctl/cmd/version.go, operator/cmd/mesh/profile-diff.go, operator/cmd/mesh/profile-dump.go, operator/cmd/mesh/profile.go, operator/cmd/mesh/root.go, operator/pkg/manifest/shared.go, releasenotes/notes/34325.yaml
This is a manual cherry-pick of #34325
=> [release-1.11] fix `istioctl profile dump` and `istioctl profile diff` have the extra info log

istioctl/cmd/remove-from-mesh.go
**Please provide a description for what this PR is for.**
when get deployments and services failed, it return `XXXXXXXX does not exist` error regardless of error types, but some another type error may occur.
So we should check error is notExist error or some other types error.
And only when notExist occurs, return `XXXXXXXX does not exist` error
**And to help us figure out who should review this PR, please 
put an X in all the areas that this PR affects.**
=> check whether if deploy or service exist or not

pilot/pkg/security/authn/v1beta1/policy_applier.go, pkg/istio-agent/agent.go, pkg/istio-agent/xds_proxy.go, pkg/test/framework/components/echo/echoboot/echoboot.go, pkg/test/framework/components/istio/istio.go
1. Delete unnecessary comments to prevent someone from doing repetitive and invalid work in the future
2. fix some spelling
=> Delete unnecessary comments

tests/fuzz/misc_fuzzers.go, tests/fuzz/oss_fuzz_build.sh, tests/fuzz/regression_test.go
Adds a misc of fuzzers that mostly target v1alpha1 apis.
=> Fuzzing: Add more fuzzers

pilot/pkg/serviceregistry/aggregate/controller.go
Previously it was for serviceentry, but after se 's cluster is set, this is not needed any more
=> remove clusterID empty check

pkg/test/csrctrl/signer/ca_provider.go, pkg/test/csrctrl/signer/signer.go, security/pkg/k8s/chiron/utils.go, security/pkg/pki/util/crypto.go
Take over from https://github.com/istio/istio/pull/34486 to fix https://github.com/istio/istio/issues/34218
Enhance integration test to sign cert with intermediate cert to cover this case.
=> istiod use cert-chain to verify cert

tests/fuzz/inject_fuzzer.go
Refactors `inject_fuzzer.go`:
1. Remove `UnmarshalConfig` which adds overhead.
2. Remove `requiredJSONFields` which aren't necessary.
3. Allow the fuzzer to pass a string to revision in `IntoResourceFile`
=> Fuzzing: Refactor inject_fuzzer

galley/pkg/config/analysis/analyzers/analyzers_test.go, galley/pkg/config/analysis/analyzers/deployment/services.go, galley/pkg/config/analysis/analyzers/testdata/deployment-multi-service-different-ns.yaml, releasenotes/notes/34847.yaml
This PR is to fix https://github.com/istio/istio/issues/34830
=> fix `istioctl analyze` deployment analyzer ignoring service namespaces

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_test.go, pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go, pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go, pilot/pkg/networking/util/util.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/eds.go, pilot/pkg/xds/endpoint_builder.go, pilot/pkg/xds/ep_filters.go, releasenotes/notes/failover-priority-lb.yaml, tests/integration/pilot/locality_test.go
Implement https://github.com/istio/api/pull/2043, more details there
=> Implement enhanced priority failover loadbalancing

istio.deps, pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-out.yaml, pilot/pkg/security/authz/builder/testdata/http/multiple-policies-out.yaml, pilot/pkg/security/authz/builder/testdata/http/single-policy-out.yaml, pilot/pkg/security/authz/matcher/header.go, pilot/pkg/security/authz/matcher/header_test.go, pilot/pkg/security/authz/model/generator.go, pilot/pkg/security/authz/model/generator_test.go, pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/metrics_no_statsd_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json, tests/integration/pilot/common/routing.go, tests/integration/security/authorization_test.go, tests/integration/security/normalization_test.go, tests/integration/security/testdata/authz/v1beta1-ingress-gateway.yaml.tmpl, tools/packaging/common/envoy_bootstrap.json
=> [release-1.11] August 2021 security patches

pkg/config/validation/validation.go
[ ] Docs
[x] Networking
[ ] Security
=> Refactor validateLocalities function for better readability

pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/gateway_test.go, tests/integration/pilot/common/routing.go
fix https://github.com/istio/istio/issues/34609
Signed-off-by: Zufar Dhiyaulhaq <zufardhiyaulhaq@gmail.com>
previously, we only create custom virtual hosts with 301 redirections when there is **no virtual service available** for a specific server in the Gateway object with HttpsRedirect set to true. 
**Gateway server** & **virtual service** will create a **virtual host**. **virtual host** for HTTP might be empty if we create something like this:
```
kind: Gateway
metadata:
name: my-gateway
namespace: my-namespace
spec:
selector:
istio: ingressgateway
servers:
- port:
number: 80
name: http
protocol: HTTP
hosts:
- "example.com"
- port:
number: 443
name: https
protocol: HTTPS
hosts:
- "example.com" …
```
=> 301 redirect in VirtualHost when server HttpsRedirect true 

pilot/pkg/networking/apigen/apigen.go, pilot/pkg/networking/grpcgen/lds.go, pilot/pkg/serviceregistry/aggregate/controller.go, pilot/pkg/serviceregistry/serviceentry/conversion.go
Fix: #34807 get the service address for the cluster
=> Fix service address misuse

security/pkg/k8s/chiron/utils.go
Current logic just returns and logs `unable to submit csr`. This change makes it return and log the real error from k8s server.
=> Make chiron CSR submission return real error.

pilot/pkg/model/push_context.go
=> Optimize `initSidecarScopes` by merging loops

go.mod, go.sum, pilot/docker/Dockerfile.proxyv2, prow/release-commit.sh
=> Bump dependencies for 1.11.2

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go
=> minor comment fixes in cluster builder

pilot/pkg/xds/lds.go, releasenotes/notes/34944.yaml
=> [release-1.9] Backport destination rule does not trigger LDS 1.9

tests/integration/security/sds_ingress/quic/ingress_test.go
=> Fix quic test on old k8s versions

tools/istio-iptables/pkg/cmd/root.go, tools/istio-iptables/pkg/cmd/run.go, tools/istio-iptables/pkg/cmd/testdata/basic-exclude-nic.golden, tools/istio-iptables/pkg/cmd/testdata/tproxy.golden, tools/istio-iptables/pkg/config/config.go
Signed-off-by: Yuchen Dai <silentdai@gmail.com>
=> iptables: fix OUTPUT chain for exclude nic

pilot/pkg/xds/ads.go, pilot/pkg/xds/delta.go
Cherrypick https://github.com/istio/istio/pull/31899
We are seeing this causing Istiod memory leaks
=> 1.10: clean up connections always (#31899)

pkg/envoy/agent.go
=> fix envoy agent exit bug

pilot/pkg/xds/debug.go
=> Keep adsz output in deterministic order

releasenotes/notes/gateway-v1alpha2.yaml
=> Add release note for gateway v1alpha2

pilot/pkg/model/push_context.go, pilot/pkg/model/service.go, releasenotes/notes/34900.yaml
=> [Release 1.11]  Fix misue service's pointer address in map 

tests/integration/pilot/locality_test.go
This test panics when `skipVM=true`, this should fix.
=> avoid using vm[0] in locality test

pilot/pkg/networking/core/v1alpha3/listener_builder.go, pilot/pkg/xds/filters/filters.go, poc/.gitignore, poc/client-l7.yaml, poc/client.yaml, poc/config.yaml, poc/up.sh
**Please provide a description of this PR:** Sharing progress on a remote proxy concept. The configuration for the client-l7 deployment config doesn't appear to be correct yet. cc @kyessenov @lambdai
=> remote poc: configure client + setup script

pilot/pkg/xds/ads.go
* clean up connections always
* fix delta
* move to function
* update comment
* cleanup connections in initConnections
* reorder defer
(cherry picked from commit 53660a782573bfa63aaa13215c7a0cb194cd0f5c)
Co-authored-by: Rama Chavali <rama.rao@salesforce.com>
(cherry picked from commit 1d2a02e552e752757750c75d08cecb15989ee286)
=> clean up connections always (#31899) (#35007)

samples/multicluster/gen-eastwest-gateway.sh
These fields are now injected (I think(
=> Cleanup eastwest gateway install

pilot/pkg/model/authentication.go, pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, pilot/pkg/xds/endpoint_builder.go
Removed dependency on pushVersion for cluster cache.
=> remove pushVersion from cluster cache key

pilot/pkg/controller/workloadentry/workloadentry_controller.go
Was a bit premature with my first PR, after some discussion it turns
out that FAILED_PRECONDITION is a better fit.
=> Change workload not found error to FAILED_PRECONDITION

pkg/adsc/adsc.go
We should remove the corresponding file when remove deleted resources from cache.
=> Remove the corresponding file when remove deleted resources from cache

pilot/pkg/bootstrap/configcontroller.go
When my MCP servers multiple istiods, I need to identify the specific istiod by nodeID.
=> Add name and namespace to adsc client.

istioctl/cmd/root.go
flag name uses public constants
=> flag name uses public constants

pilot/pkg/features/pilot.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/delta.go, pilot/pkg/xds/discovery.go
(cherry picked from commit 2af5bfd55ad08d25ba7de634a723194b3af1382a)
=> Add a rate limit to incoming XDS requests (#35046)

pilot/cmd/pilot-agent/main.go
=> clean up duplicate error logs

pilot/pkg/networking/util/util.go
=> remove port double check

pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/httproute_test.go, pilot/pkg/networking/core/v1alpha3/listener_test.go, pilot/pkg/networking/core/v1alpha3/networkfilter.go, pilot/pkg/networking/core/v1alpha3/networkfilter_test.go, pilot/pkg/networking/core/v1alpha3/tls.go, releasenotes/notes/35014.yaml, tests/integration/pilot/common/routing.go
Fixes https://github.com/istio/istio/issues/33558
=> add support for sourceip hashing in tcp proxy

security/pkg/util/certutil.go
Signed-off-by: TianTianBigWang <zilong.wang@daocloud.io>
=> fix comment in certutil.go

tools/bug-report/pkg/bugreport/bugreport.go
Not sure if this is the most efficient way to achieve this, but proposing a fix for https://github.com/istio/istio/issues/35097
=> Print CLI version in bug-report/versions

galley/pkg/config/source/kube/inmemory/kubesource.go
=> Do not panic in `istioctl analyze` with types without protos

pilot/pkg/networking/plugin/authn/util.go
prevent multiple memory allocations
=> prevent multiple memory allocations

pkg/adsc/adsc.go
=> redundant memory allocation

pilot/pkg/xds/lds.go, releasenotes/notes/34944.yaml
fixes https://github.com/istio/istio/issues/34970
=> [release-1.10] Backport destination rule does not trigger LDS 1.10 

pilot/pkg/trustbundle/trustbundle.go
=> Fix minor logging issue

pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_test.go, pilot/pkg/networking/core/v1alpha3/route/route_test.go, pilot/pkg/networking/util/util.go, pilot/pkg/security/authz/builder/builder.go, pilot/pkg/security/authz/builder/builder_test.go, pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-out.yaml, pilot/pkg/security/authz/builder/testdata/http/allow-host-before-111-in.yaml, pilot/pkg/security/authz/builder/testdata/http/allow-host-before-111-out.yaml, pilot/pkg/security/authz/builder/testdata/http/multiple-policies-out.yaml, pilot/pkg/security/authz/builder/testdata/http/single-policy-out.yaml, pilot/pkg/security/authz/matcher/header.go, pilot/pkg/security/authz/matcher/header_test.go, pilot/pkg/security/authz/model/generator.go, pilot/pkg/security/authz/model/generator_test.go, pilot/pkg/security/authz/model/model.go, pilot/pkg/security/authz/model/model_test.go, tests/integration/security/authorization_test.go, tests/integration/security/testdata/authz/v1beta1-ingress-gateway.yaml.tmpl
Merge in release-1.11.1-patch into master
=> [master] August 2021 security patches

tools/packaging/common/istio-start.sh, tools/packaging/common/istio.service, tools/packaging/packaging.mk
=> fix envoy process leak when systemd stop istio 

pilot/pkg/config/memory/store.go
=> Remove useless code and define the errUnknownType.

pilot/pkg/model/sidecar.go, pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go, releasenotes/notes/same-name-vs.yaml
Fixes https://github.com/istio/istio/issues/35127
This is sent directly to release-1.11. Its basically a cherrypick of https://github.com/istio/istio/pull/34766 but the code completely changed so cannot do a clean cherrypick
=> Fix regression with same-named virtual services

galley/pkg/config/analysis/analyzers/deprecation/deprecation.go, galley/pkg/config/analysis/analyzers/gateway/conflictinggateway.go, galley/pkg/config/analysis/analyzers/util/find_errorline_utils.go
This PR is to fix issue #35093. 
And two more fixes here:
1. if no selector in the gateway, there is no need to report the `NewReferencedResourceNotFound` msg.
2. If no match is provided, the error line function will cause panic because of index out of range.
=> fix analyzer test and conflicting gateway analyzer

istioctl/cmd/kubeinject.go
Signed-off-by: TianTianBigWang <tiantianbigwang@gmail.com>
avoid slice multiple memory allocations
=> avoid slice multiple memory allocations

tests/integration/security/ca_custom_root/secure_naming_test.go, tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go, tests/integration/security/util/cert/cert.go, tests/integration/security/util/dir/util.go
=> Fix TestStrictMTLS test to work in istiodremote topology

galley/pkg/config/analysis/analyzers/deprecation/deprecation.go, galley/pkg/config/analysis/analyzers/gateway/conflictinggateway.go, galley/pkg/config/analysis/analyzers/util/find_errorline_utils.go, releasenotes/notes/35095.yaml
This is a cherry-pick of #35095
=> [release-1.11] fix analyzer test and conflicting gateway analyzer

pkg/test/framework/analyzer.go, pkg/test/framework/suite.go, pkg/test/framework/test.go, tests/integration/pilot/analysis/analysis_test.go, tests/integration/pilot/cross_revision_test.go, tests/integration/pilot/istioctl_test.go, tests/integration/pilot/multi_version_revision_test.go, tests/integration/pilot/piggyback_test.go, tests/integration/pilot/revisioncmd/main_test.go, tests/integration/pilot/revisioncmd/revision_view_test.go, tests/integration/pilot/revisioned_upgrade_test.go, tests/integration/pilot/revisions/revision_tag_test.go, tests/integration/pilot/revisions/revisions_test.go
=> Enable more pilot-istiodremote integration tests

pilot/cmd/pilot-agent/options/security.go, security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go, security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient_test.go, security/pkg/stsservice/test/setup.go, security/pkg/stsservice/tokenmanager/sts_test.go, security/pkg/stsservice/tokenmanager/tokenmanager.go, security/pkg/stsservice/tokenmanager/tokensource.go
- When STS CreateTokenManager() fails, return the error.
- Add error detection to constructAudience().
- When NewSecureTokenServiceExchanger() fails, return the error.
- [X ] Networking
- [X ] Security
- [X ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> Improve the error handling of STS token manager

pilot/pkg/model/push_context.go
Not only is it unused it would be bad if it was used since I think it
has some bugs in it.
=> Remove unused function in push context

go.mod, go.sum
Manual update of istio/client go which includes an update of istio/api.
Supersedes: https://github.com/istio/istio/pull/35251 https://github.com/istio/istio/pull/35143 and https://github.com/istio/istio/pull/35185
=> Manual update of istio/client-go (includes api)

pilot/pkg/secrets/kube/secrets.go, releasenotes/notes/secret-watch.yaml
Fixes https://github.com/istio/istio/issues/35231
WIP because I need to clean it up + fix the .Run code
=> Filter secrets for TLS cert watcher

pilot/pkg/util/sets/string.go, pkg/test/framework/components/echo/config.go, pkg/test/framework/components/echo/echoboot/echoboot.go, pkg/test/framework/components/echo/echotypes/types.go, pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/resource/flags.go, pkg/test/framework/resource/settings.go
Alternative/addition to #35233
=> flag to skip arbitrary types of workloads

pilot/pkg/model/service.go, pilot/pkg/model/validation_test.go, pilot/pkg/model/virtualservice_test.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, pilot/pkg/networking/core/v1alpha3/cluster_test.go, pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/networking/core/v1alpha3/httproute_test.go, pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/listener_test.go, pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go, pilot/pkg/networking/core/v1alpha3/networkfilter_test.go, pilot/pkg/networking/core/v1alpha3/route/route_test.go, pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go, pilot/pkg/networking/core/v1alpha3/tls.go, pilot/pkg/networking/grpcgen/lds.go, pilot/pkg/serviceregistry/kube/controller/controller_test.go, pilot/pkg/serviceregistry/kube/conversion.go, pilot/pkg/serviceregistry/kube/conversion_test.go, pilot/pkg/serviceregistry/memory/discovery.go, pilot/pkg/serviceregistry/mock/discovery.go, pilot/pkg/serviceregistry/serviceentry/conversion.go, pilot/pkg/serviceregistry/serviceentry/conversion_test.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go, pilot/pkg/xds/ads_test.go, pilot/pkg/xds/eds_sh_test.go, pkg/dns/server/name_table.go, pkg/dns/server/name_table_test.go
Also cleaning up some of the usage.
=> Rename Service.Address to Service.DefaultAddress

pilot/pkg/networking/core/v1alpha3/route/retry/retry_test.go
This PR refactors `retry_test.go` to follow table driven tests.
=> Refactor retry_test.go to table driven tests

pilot/pkg/model/push_context_test.go, pilot/pkg/model/service.go, pilot/pkg/serviceregistry/aggregate/controller.go, pilot/pkg/serviceregistry/aggregate/controller_test.go, pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/controller_test.go, pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go, pilot/pkg/serviceregistry/kube/controller/endpoints.go, pilot/pkg/serviceregistry/kube/controller/endpointslice.go, pilot/pkg/serviceregistry/kube/controller/endpointslice_test.go, pilot/pkg/serviceregistry/kube/controller/serviceexportcache.go, pilot/pkg/serviceregistry/kube/controller/serviceexportcache_test.go, pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go, pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go, pilot/pkg/serviceregistry/memory/discovery.go, pilot/pkg/serviceregistry/mock/discovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
This has been a source of confusion in the code. No controller actually returns an error and there is no description in the interface for when an error should be returned.
=> Remove unused error from GetService method

pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/networking/core/v1alpha3/httproute_test.go, releasenotes/notes/headless-auto-http.yaml, tests/integration/pilot/common/routing.go, tests/integration/pilot/common/traffic.go
Fixes https://github.com/istio/istio/issues/34679
=> Do not check HTTP Hostname for single-VIP listeners (auto protocol) and add tests

tools/go-ordered-test
=> Fix unbound variable

security/pkg/stsservice/test/setup.go
=> Fix more tests to run off gcp

tests/integration/security/util/framework.go
I've only seen this once: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/35290/integ-security-multicluster-tests_istio/1440440567870787584
I'm assuming it's due to the fact that most of our istioctl code relies heavily on package-scoped vars. Calling it in parallel is bound to cause issues.
=> prevent rare panic in security tests

pilot/pkg/model/context.go, pilot/pkg/networking/core/v1alpha3/networkfilter.go
- [ X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> fix listener class comment

pilot/pkg/xds/ads.go
=> make computeProxyState more readable

samples/grpc-echo/grpc-echo.yaml
in the edits done in #34800 accidentally added duplicate ports
=> fix duplicate port in samples

tests/integration/telemetry/stats/prometheus/stats.go, tests/integration/telemetry/stats/prometheus/wasm/bad_wasm_filter_test.go
=> Fix failing telemetry istiod-remote tests

pilot/pkg/serviceregistry/kube/controller/autoserviceexportcontroller.go, pilot/pkg/serviceregistry/kube/controller/autoserviceexportcontroller_test.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go, pilot/pkg/serviceregistry/kube/controller/serviceexportcache.go, pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
=> Minor cleanup for MCS controllers

tests/integration/pilot/mcs/discoverability/discoverability_test.go
To aid investigation for #34051
=> Add debugging info for MCS test flakes 

pilot/pkg/model/push_context_test.go, pilot/pkg/model/service.go, pilot/pkg/serviceregistry/aggregate/controller.go, pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/serviceexportcache.go, pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go, pilot/pkg/serviceregistry/memory/discovery.go, pilot/pkg/serviceregistry/mock/discovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/xds/debug.go
This merges the importz and exportz into mcsz and adds the MCS clusterset host and VIPs to the output.
=> Expanding debug info for mcs

tests/integration/tests.mk
=> Cleanup unused path var

pkg/test/kube/dump.go
related to https://github.com/istio/istio/issues/33034
=> prevent writing large and identical core dumps in test artifacts

tests/integration/security/authorization_test.go, tests/integration/security/jwt_test.go
https://github.com/istio/istio/issues/35384
=> skip jwt test

tests/integration/pilot/common/traffic.go, tests/integration/pilot/gw_topology_test.go, tests/integration/pilot/mirror_test.go
=> Only apply Istio configs to config clusters

prow/integ-suite-kind.sh, tests/integration/security/authorization_test.go, tests/integration/security/jwt_test.go
Workaround https://github.com/istio/istio/issues/35384
=> Try random iptables command to fix jwt test

pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go, pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go, security/pkg/k8s/configutil.go
fix unlimited retries when namespace deleted immediately after istio-ca-root-cert changed (#35149)
=> fix unlimited retries when namespace deleted after cm changed

samples/grpc-echo/grpc-echo.yaml
=> [release-1.11] fix duplicate port in samples

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/grpcgen/cds.go, releasenotes/notes/35333.yaml, tests/integration/pilot/common/routing.go
~TODO: refactor `consistentHashCases` to cover this~ done
=> proxyless grpc: support ring-hash lb policy

tests/integration/telemetry/stackdriver/vm/main_test.go
=> Skip stackdriver vm test in istiodremote topology

tools/istio-iptables/pkg/validation/validator.go
This PR fixed the compatible IP format both for IPv4 and IPv6 for istio-iptables
=> fixed the compatible IP format both for IPv4 and IPv6 for istio-iptables

prow/integ-suite-kind.sh
Allegedly this is fixed. We will see..
=> Revert iptables hack for MTU

tools/istio-iptables/pkg/cmd/run.go, tools/istio-iptables/pkg/cmd/testdata/tproxy.golden
With this and a few other patches I will send a PR for, I have
IPv6+TPROXY+Distroless+CNI all working together. Currently we don't have
any tests of this but working to expand our environmental testing.
=> More fixes for TPROXY + ipv6

pilot/pkg/config/monitor/monitor_test.go
This is causing occasional flakes.
=> Fixing leaked goroutine in monitor_test

pkg/kube/client.go
=> Apply full informer wait to all client types

prow/release-commit.sh
=> Bump release-builder to fix postsubmit

prow/integ-suite-kind.sh
This reverts commit dc50711e3fb687c816215ea43751c9327336ae02.
Closes #35438.
=> Revert "[release-1.11] Try random iptables command to fix jwt test (#35399)"

pilot/docker/Dockerfile.proxyv2
=> Bump distroless image

go.mod, go.sum, pilot/pkg/networking/grpcgen/lds.go
=> Update to grpc 1.41

docker/Dockerfile.distroless, go.mod, go.sum, pilot/docker/Dockerfile.proxyv2, prow/release-commit.sh
Manually update dependencies. We have no automated task for this.
=> [release-1.11] run UPDATE_BRANCH=release-1.11 ./bin/update_deps.sh; make gen

pilot/test/xdstest/extract.go
Fix issue https://github.com/istio/istio/issues/35452
=> clean up unused code

pilot/pkg/model/context.go, pilot/pkg/networking/core/v1alpha3/route/route.go, pilot/pkg/networking/grpcgen/grpcecho_test.go, pilot/pkg/networking/grpcgen/lds.go
Change our response to include the filters required for https://github.com/grpc/proposal/blob/master/A33-Fault-Injection.md
=> proxyless grpc: support fault injection

pkg/kube/inject/inject.go, pkg/kube/inject/webhook_test.go, releasenotes/notes/inject-disabled.yaml
Fixes https://github.com/istio/istio/issues/35271
=> Fix label injection enabled with policy=disabled

docker/Dockerfile.distroless, go.mod, go.sum, istio.deps, prow/release-commit.sh
=> [release-1.12] Update deps

pilot/pkg/request/command.go
clean up codes, reduce unnecessary logic
=> clean up codes, reduce unnecessary logic

istioctl/cmd/kubeinject.go, tests/integration/pilot/istioctl_test.go
=> Enable TestKubeInject in istiodremote topology

releasenotes/notes/35480-ext-authz.yaml
Add release notes for upstream changes in ext-authz filter.
https://github.com/istio/istio/issues/35480#issuecomment-952420951
=> add release note for ext-authz changes in Envoy

pkg/test/echo/server/instance.go
Tested in https://github.com/istio/istio/pull/35354/
=> echo: support dualstack --bind-localhost

tests/integration/operator/switch_cr_test.go
Signed-off-by: dddddai <dddwq@foxmail.com>
Wait for pods to be deleted when cleaning up operators to avoid impacting `TestPostInstallControlPlaneVerification`
Fix #35821
=> Wait for pods to be deleted when cleaning up operators

tests/integration/pilot/gw_topology_test.go, tests/integration/pilot/ingress_test.go
This allows running as non-root
=> Use targetPort for gateway tests

pilot/pkg/controller/workloadentry/workloadentry_controller.go, pkg/test/framework/components/echo/kube/deployment.go
Tested in https://github.com/istio/istio/pull/35354
Fixes https://github.com/istio/istio/issues/35428
=> Support WE for IPv6

prow/lib.sh, tools/docker-builder/main.go
No specific changes I was interested in, just pick up any improvements
=> Bump buildkit version

tests/integration/pilot/mcs/discoverability/discoverability_test.go
Will continue debugging in https://github.com/istio/istio/pull/35767
For https://github.com/istio/istio/issues/34051
This test is blocking productivity
=> Skip flaky mcs test

pkg/test/echo/server/instance.go
=> Fix echo dualstack

samples/jwt-server/jwt-server.yaml, samples/jwt-server/src/Makefile
=> Bump jwt-server to 0.6

pilot/pkg/bootstrap/options.go
optimize codes, the logic that apply pilot default args should be placed together
=> optimize codes, the logic that apply pilot default args should be placed together

pilot/pkg/xds/ads.go, pkg/istio-agent/xds_proxy.go, pkg/istio-agent/xds_proxy_test.go
Fix https://github.com/istio/istio/issues/35860
=> Send healthcheck after lds request has been sent

go.mod, go.sum, pilot/pkg/networking/grpcgen/grpcecho_test.go, pilot/pkg/networking/grpcgen/lds.go
=> Bump gRPC to v1.42.0

releasenotes/notes/jwt-route.yaml
=> add release note for jwt claim routing

tests/integration/security/sds_ingress/util/util.go
=> Fix wrong ctx usage leading to panic on failure

pilot/pkg/model/push_context.go, pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go, pilot/pkg/xds/monitoring.go
For: https://github.com/istio/istio/issues/35867
=> Fix service and cluster update missing reason

istioctl/cmd/precheck.go
=> fix istioctl precheck unused code logic

pilot/pkg/config/kube/crdclient/cache_handler.go, pilot/pkg/config/kube/crdclient/client.go, pilot/pkg/config/kube/crdclient/gen/types.go.tmpl, pilot/pkg/config/kube/crdclient/types.gen.go, pkg/config/schema/fuzz_test.go, tests/fuzz/config_validation_fuzzer.go
As the event handler use `config.Config` value instead of pointer, so change the translation func
=> Config translate returns value type

tests/integration/pilot/piggyback_test.go
=> Support distroless in piggyback test

pilot/pkg/features/pilot.go, releasenotes/notes/35883.yaml, releasenotes/notes/35884.yaml, tests/integration/iop-integration-test-defaults-with-quic.yaml, tests/integration/iop-integration-test-defaults.yaml
=> enable multicluster headless by default (#35883)

pilot/pkg/model/extensions.go, pilot/pkg/networking/core/v1alpha3/extension/wasmplugin.go, pilot/pkg/networking/core/v1alpha3/extension/wasmplugin_test.go, tests/integration/telemetry/stats/prometheus/customizemetrics/testdata/attributegen_envoy_filter.yaml
Adds an integration test for WasmPlugin.
Also fixes https://github.com/istio/istio/issues/35948
=> Add WasmPlugin integration test

pilot/pkg/networking/core/v1alpha3/gateway.go
We did not set mesh config so it did nothing...
=> Fix DefaultHTTPRetryPolicy for gateways

pilot/pkg/serviceregistry/kube/controller/multicluster.go
Signed-off-by: dddddai <dddwq@foxmail.com>
It seems redundant to append service handler in `ClusterAdded`, because the handler has already been appended in `initRegistryEventHandlers`
This patch would reduce unnecessary push requests
related snippet:
https://github.com/istio/istio/blob/fe652368feb59068c6693452deaf5f6d8664c205/pilot/pkg/bootstrap/server.go#L861-L877
https://github.com/istio/istio/blob/fe652368feb59068c6693452deaf5f6d8664c205/pilot/pkg/serviceregistry/kube/controller/multicluster.go#L208
https://github.com/istio/istio/blob/fe652368feb59068c6693452deaf5f6d8664c205/pilot/pkg/serviceregistry/aggregate/controller.go#L71-L80
=> Delete redundant service handler

pkg/test/echo/client/parsedresponse.go, tests/integration/pilot/common/routing.go, tests/integration/security/util/cert/cert.go
Broken by https://github.com/istio/istio/commit/6900bf46cf3c48eec727fe4f728f8fa8bf7e499c
=> Ensure cert order is deterministic

pilot/pkg/config/kube/gateway/conversion.go
Per https://github.com/istio/istio/pull/35678#issuecomment-952213763
=> Document supported address values

pilot/pkg/xds/discovery.go
as described, the log message mismatch the function
=> make log more readable

prow/integ-suite-kind.sh
Since https://github.com/istio/common-files/pull/489
=> Start using metallb for IPv6

pilot/pkg/serviceregistry/kube/controller/filter/discoverynamespaces.go
Fixes https://github.com/istio/istio/issues/36014
=> Fix panic in discoverynamespaces.go

pilot/cmd/pilot-agent/request.go
=> pilot-agent request: add allowlist for debug ports

pilot/pkg/model/telemetry.go, pilot/pkg/model/telemetry_test.go
=> Fix bug in telemetry causing multiple duplicate filters

pilot/pkg/networking/grpcgen/grpcecho_test.go, pilot/pkg/networking/grpcgen/grpcgen.go, pilot/pkg/networking/grpcgen/lds.go, pkg/istio-agent/grpcxds/grpc_bootstrap.go, pkg/istio-agent/testdata/grpc-bootstrap.json
Change the config we send so we don't get NACK'd. 
https://github.com/grpc/grpc-go/blame/d61c7ae86d6a6a0d3fa46484e350cf9ee726025d/xds/internal/xdsclient/xdsresource/unmarshal_cds.go#L317
Surprised this didn't nack before.
May also want to make sure we don't send this in CDS, although serverside won't request the resource.
=> fix proxyless gRPC mTLS 

pilot/pkg/xds/debug.go
=> do not generate debug output for ndsz if dns is not enabled

tools/docker
Rebuilding docker-builder if code changed, especially for
development phase.
Signed-off-by: trevor.tao <trevor.tao@arm.com>
=> Rebuilding docker-builder if code changed

tests/integration/telemetry/stackdriver/api/stackdriver_filter_test.go, tests/integration/telemetry/stackdriver/common.go, tests/integration/telemetry/stackdriver/stackdriver_filter_dry_run_test.go, tests/integration/telemetry/stackdriver/stackdriver_filter_test.go, tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_policy_allow_matched.yaml.tmpl, tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_policy_both_matched.yaml.tmpl, tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_policy_deny_matched.yaml.tmpl, tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_server_access_log_allow_matched.json.tmpl, tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_server_access_log_both_matched.json.tmpl, tests/integration/telemetry/stackdriver/testdata/security_authz_dry_run/tcp_server_access_log_deny_matched.json.tmpl
=> add more e2e tests for authz dry-run with TCP traffic

pilot/pkg/model/context.go, pkg/bootstrap/config.go, pkg/bootstrap/instance_test.go, pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/metrics_no_statsd_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json, pkg/envoy/agent.go
add downstream_cx_active stats only when  ExitOnZeroActiveConnections is enabled.
=> add downstream_cx_active stats only when ExitOnZeroActiveConnections is used

tools/docker-builder/main.go
Fixes https://github.com/istio/istio/issues/36059
=> Fix docker.save having `-default` in tar name

cni/pkg/cmd/root.go
=> Add silence usage to CNI command.

pilot/pkg/model/network.go, pilot/pkg/model/push_context_test.go, pilot/pkg/model/service.go, pilot/pkg/serviceregistry/aggregate/controller.go, pilot/pkg/serviceregistry/kube/controller/network.go, pilot/pkg/serviceregistry/memory/discovery.go, pilot/pkg/serviceregistry/mock/discovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/xds/debug.go, pilot/pkg/xds/eds_sh_test.go, pilot/pkg/xds/ep_filters.go, pilot/pkg/xds/ep_filters_test.go, releasenotes/notes/35880.yaml
=> [release-1.11] Make use of NetworkGateway value (#35346)

cni/pkg/repair/repair.go, cni/pkg/repair/repair_test.go, cni/pkg/repair/repair_test_helpers.go, cni/pkg/repair/repaircontroller.go
fix https://github.com/istio/istio/issues/36108
=> CNI: filter pod event from different node and detect pod that needs to be repaired before adding it to work queue.

cni/pkg/cmd/root.go, manifests/charts/istio-cni/templates/daemonset.yaml
(cherry picked from commit 8dcf53141d6d50efef56da1506b3d1076a93450a)
Fixes: #35902
=> [release-1.11] revert /host prefix from CNI log volume mount path. (#36038)

releasenotes/notes/36107.yaml, tools/bug-report/pkg/bugreport/bugreport.go
Fix https://github.com/istio/istio/issues/36103
=> Fix cli version in bug-report

pkg/test/framework/label/filter.go, pkg/test/framework/label/labels.go, pkg/test/framework/label/labels_test.go, tests/integration/tests.mk
=> Remove flaky label from test framework

tests/integration/tests.mk
=> Fix quoting issue on environment tests

tests/fuzz/networking_core_v1alpha3_fuzzer.go, tests/fuzz/oss_fuzz_build.sh, tests/fuzz/pki_fuzzer.go
Fixes some small breakages in the fuzzers.
=> Fuzzing: Small fixes

pkg/dns/client/dns_test.go
Example:
https://storage.googleapis.com/istio-prow/logs/unit-tests_istio_postsubmit/1461380736610209792/build-log.txt
=> Fix issue causing dns test to hang forever on failure

pilot/pkg/networking/util/util.go
prevent convert to time duration to improve gogo duration convert to google duration
=> improve gogo duration convert performance

pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
Currently fail like
https://storage.googleapis.com/istio-prow/logs/benchmark-report_istio_postsubmit/1461348857731354624/artifacts/benchmark-log.txt
In this, we just disable the send on EDSUpdate so we don't have to worry
about complex drain
=> Fix benchmarks in SE leak

pkg/kube/util.go, pkg/kube/util_test.go, releasenotes/notes/cron-job-metadata.yaml
Manual cherry-pick of https://github.com/istio/istio/pull/35655 fix https://github.com/istio/istio/issues/36146
=> [release-1.10] Fix cronjob timestamp trimming.

operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go, operator/pkg/helmreconciler/prune.go, operator/pkg/helmreconciler/reconciler.go, releasenotes/notes/35657.yaml
cherrypick: https://github.com/istio/istio/pull/35662
resolve: https://github.com/istio/istio/issues/36164
- [ X ] Installation
=> [release-1.11]fix operator prune resources for action required case.

pilot/pkg/model/push_context.go
=> allocate capacity in advance

pilot/pkg/config/kube/gateway/deploymentcontroller.go, pilot/pkg/config/kube/gateway/templates/service.yaml
=> Improve validation for gateway types

cni/pkg/cmd/root.go, manifests/charts/istio-cni/templates/daemonset.yaml
(cherry picked from commit 8dcf53141d6d50efef56da1506b3d1076a93450a)
Fixes: #35902
=> [release-1.12] revert /host prefix from CNI log volume mount path. (#36038)

operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go, operator/pkg/helmreconciler/prune.go, operator/pkg/helmreconciler/reconciler.go, releasenotes/notes/35657.yaml
cherrypick: https://github.com/istio/istio/pull/35662
resolve: https://github.com/istio/istio/issues/36163
- [ X ] Installation
=> [release-1.10]fix operator prune resources for action required case.

tools/bug-report/pkg/archive/archive.go
=> tools/bug-report/pkg/archive: Fix not closing file when file write failed

pilot/pkg/xds/delta.go
=> optimized xds delta return error

tools/istio-docker.mk
Manual cherry-pick for #36041
Fix #36072
=> [release-1.12] Fix docker.save tar targets

pilot/pkg/xds/ads.go, pilot/pkg/xds/auth.go, pilot/pkg/xds/delta.go, pilot/pkg/xds/proxy_dependencies_test.go
Provide a common interface, to support extending authorize in future
And also prevent the identities from being persisted, so saves a little memory
=> Add explicit authorization interface

pilot/pkg/xds/ads.go, pilot/pkg/xds/delta.go, pilot/pkg/xds/delta_test.go
1. merge responseNonce=nil with `previousInfo =nil` processing
2. fix con.proxy lock for shouldRespondDelta
3. cleanup some comments
=> MInor cleanup and fix for delta xds

pilot/pkg/xds/ads.go, pilot/pkg/xds/discovery.go, pilot/pkg/xds/sds.go, pilot/pkg/xds/simple.go
fix incorrect use log ：pilot/pkg/xds/discovery.go
optimized log output：other
=> fix incorrect use log and optimized log output

pkg/config/validation/validation.go
=> Validation: do not warn if latter VS prefix match rule covers former one

tests/fuzz/oss_fuzz_build.sh
The OSS-fuzz currently breaks. This PR fixes that.
=> Fuzzing: Fix broken OSS-fuzz build

pilot/test/xdstest/mock_discovery.go, pkg/istio-agent/xds_proxy_delta_test.go
1. impl DeltaAggregatedResources() in pilot/test/xdstest/mock_discovery.go 
2. add xds_proxy_delta_test.go
=> implement delta mock discovery and add xds_proxy_delta_test

pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, releasenotes/notes/envoyfilter-patch-context.yaml
fix https://github.com/istio/istio/issues/36284
=> Do not skip adding clusters & listeners via EnvoyFilter at Gateway if context is ANY.

pkg/config/analysis/analyzers/util/config.go, tools/bug-report/pkg/bugreport/bugreport.go, tools/bug-report/pkg/cluster/cluster.go, tools/bug-report/pkg/cluster/cluster_test.go, tools/bug-report/pkg/config/config.go
Fix issue #36105, and the change list as below:
1. Enable --include/--exclude options for bug-report
2. Add timeout for **GetClusterResources** which retrieving cluster resources
3. Change **GetClusterResources** into just one query for retrieving cluster resources
4. Add some test cases for --include/--exclude options
=> enable --include/--exclude option for bug-report, fixed issue#36105

pilot/pkg/model/context.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/delta.go, pilot/pkg/xds/discovery_test.go
clean up Connection unused fields
=> remove unused attributes from Connection

pilot/pkg/xds/ads.go, pilot/pkg/xds/delta.go
https://github.com/istio/istio/pull/36269/files#r758456339
=> revert some delta request logic

pilot/pkg/model/addressmap.go, pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go, pkg/kube/mcs/register.go, pkg/test/framework/components/echo/call.go, pkg/test/framework/components/environment/kube/settings.go, tests/integration/pilot/mcs/autoexport/autoexport_test.go, tests/integration/pilot/mcs/common/common.go, tests/integration/pilot/mcs/discoverability/discoverability_test.go
=> Support integration with real MCS controller

pilot/pkg/features/pilot.go, pkg/kube/multicluster/secretcontroller.go, pkg/kube/multicluster/secretcontroller_test.go, releasenotes/notes/multicuster-secret-auth.yaml
=> multicluster: add allowlist for kubeconfig auth methods

istioctl/cmd/precheck.go
=> Fix precheck other control plane messages being omitted if the analyzer has messages

security/pkg/pki/util/verify_cert.go, tests/fuzz/oss_fuzz_build.sh, tests/fuzz/pki_fuzzer.go, tests/fuzz/regression_test.go
=> Add find root cert fuzzer to tests

tests/integration/pilot/common/routing.go
=> Add test for fault abort filter

pilot/pkg/xds/delta.go, pilot/pkg/xds/delta_test.go
=> added delta eds ut

tests/fuzz/kube_controller_fuzzer.go
This is an experimental fix for the broken OSS-fuzz coverage build.
=> Fuzzing: Change `context.TODO` to `context.Backgorund`

pilot/pkg/xds/ads.go, pilot/pkg/xds/delta.go
=> Move xds authz before register workload entry

galley/pkg/config/analysis/analyzers/webhook/webhook.go, releasenotes/notes/36336.yaml
This is a cherry-pick of https://github.com/istio/istio/pull/36336
=> [Release-1.12] Fix analysis nil pointer panic error

pilot/pkg/networking/core/v1alpha3/accesslog.go, pilot/pkg/networking/core/v1alpha3/accesslog_test.go
This PR make buildAccessLogFromTelemetry support multiple provider 
@douglas-reid @howardjohn PTAK
=> support multi provider

samples/sleep/README.md
=> Fix sleep sample readme

cni/pkg/cmd/root.go, cni/pkg/install/install.go
for https://github.com/istio/istio/issues/36363
=> Add more logs into CNI installer.

istioctl/cmd/precheck.go, releasenotes/notes/36253.yaml
This is cherry-pick of https://github.com/istio/istio/pull/36253
=> [release-1.12] Fix bug-report control plane messages may be omitted

pkg/kube/util.go, pkg/kube/util_test.go, releasenotes/notes/36220.yaml
This is a cherry-pick of https://github.com/istio/istio/pull/36220
=> [release-1.12] Fix DeploymentConfig name incorrectly worked

pkg/test/framework/components/echo/common/envoy.go, pkg/test/framework/components/istio/ingress.go, pkg/test/framework/components/istio/util.go, pkg/test/framework/components/prometheus/kube.go, pkg/test/kube/util.go, pkg/test/util/retry/retry.go
This is more of a low level function, but has the simplest name. Rename it a bit to discourage usage, and move a few usages over to the simpler functions
=> Refactor retry.Do

pkg/config/crd/validator.go
Courtesy of https://danielmangum.com/posts/how-kubernetes-validates-custom-resources/
=> Remove workaround in crd validator

pilot/pkg/xds/cds.go, pilot/pkg/xds/eds.go
=> Skip cds/eds update when telemetry and wasmplugin update

pilot/pkg/status/resourcelock.go
=> Fix log spam for Gateway status controller

pilot/pkg/config/kube/gateway/controller.go, pilot/pkg/config/kube/gateway/conversion.go, pilot/pkg/config/kube/gateway/conversion_test.go, pilot/pkg/model/push_context.go
* Fix https://github.com/istio/istio/issues/36075
* Support to.Name
* Properly update PushContext on change
=> gateway: improvements to reference policy

tests/fuzz/ca_server_fuzzer.go
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=41589
=> Fuzzing: Fix OSS-fuzz issue 41589

istioctl/cmd/proxyconfig.go
Fix https://github.com/istio/istio/issues/36182
=> Fix  label selector not select default pod

pkg/kube/client.go, pkg/kube/client_test.go, pkg/kube/mock_client.go
=> Fix extended client get istio version error

pilot/pkg/serviceregistry/kube/controller/pod.go
=> build workload instance outside of loop

pkg/kube/fakemirror.go
Does not impact real world cases, just bad tests
=> Make fake testing mirror more robust

prow/integ-suite-kind.sh
=> Move to v1.23.0 for main tests

bin/update_deps.sh, docker/Dockerfile.distroless, go.mod, go.sum, prow/release-commit.sh, security/pkg/pki/ca/ca.go
Run bin/update_deps.sh
Use crane now that it is part of the build image
=> Run update_deps; migrate to use crane

pkg/kube/client.go, pkg/kube/client_test.go, pkg/kube/mock_client.go, releasenotes/notes/36409.yaml
This is a cherry-pick of #36409 
=> [release-1.12] Fix extended client get istio version error

pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go, pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go, pkg/config/analysis/analyzers/util/config.go, pkg/kube/inject/initializer.go, pkg/kube/inject/initializer_test.go, pkg/kube/inject/inject.go, pkg/kube/inject/webhook.go, pkg/kube/inject/webhook_test.go, tools/bug-report/pkg/bugreport/bugreport.go, tools/bug-report/pkg/bugreport/flags.go
=> Combine system namespaces using set

pilot/pkg/networking/core/v1alpha3/accesslog.go, pilot/pkg/networking/core/v1alpha3/accesslog_test.go
Refer to https://github.com/envoyproxy/envoy/pull/19193, add grpc http provider support
=> add grpc http provider support

pilot/pkg/xds/delta.go
I saw the pr #33156，aware of the delta XDS needs to be synchronized.
=> Sync ADS: Ignore NACK for unwatched resources

pilot/pkg/networking/core/v1alpha3/accesslog.go, pilot/pkg/networking/core/v1alpha3/accesslog_test.go
1. add grpc tcp als provider
2. respect `FilterStateObjectsToLog` in `MeshConfig`
=> add grpc tcp als support

samples/jwt-server/src/main_test.go, tools/docker-builder/types.go
=> remove deprecated ioutil usages

go.mod, go.sum, pilot/pkg/networking/grpcgen/grpcgen_test.go, pilot/pkg/xds/fake.go, pilot/tools/debug/pilot_cli.go, pkg/adsc/adsc.go, pkg/istio-agent/xds_proxy.go, pkg/istio-agent/xds_proxy_test.go, pkg/test/echo/client/client.go, pkg/test/echo/server/forwarder/protocol.go, pkg/uds/listener_test.go, samples/extauthz/src/main_test.go, security/pkg/nodeagent/caclient/providers/citadel/client.go, security/pkg/nodeagent/caclient/providers/google-cas/client_test.go, security/pkg/nodeagent/caclient/providers/google/client.go, security/pkg/nodeagent/sds/sdsservice_test.go, security/pkg/nodeagent/test/setup.go, security/pkg/testing/sdsc/sdsclient.go
=> Bump to gRPC v1.43.0

pilot/pkg/leaderelection/leaderelection.go, releasenotes/notes/36541.yaml
fix https://github.com/istio/istio/issues/36541
=> Guard triggering of default watch go routine with enablement flag.

operator/cmd/mesh/operator-init.go, operator/cmd/mesh/shared.go, operator/pkg/helmreconciler/reconciler.go, releasenotes/notes/36570.yaml
Fix https://github.com/istio/istio/issues/36572
=> [release-1.12] operator init `--dry-run` should not create ns

pkg/test/framework/components/stackdriver/google.go
for https://github.com/istio/istio/issues/29284
Fix stackdriver test with real backend. Once this is merged, we can enable sd test with real backend: https://github.com/istio/test-infra/pull/3718.
=> Fix stackdriver integ test with real backend.

tests/fuzz/networking_core_v1alpha3_fuzzer.go
Avoid generate invalid Service and do insert into list at index 0
=> Fix misconfig in InternalFuzzbuildSidecarInboundListeners

tools/istio-docker.mk
=> Small fix to local envoy docker build comment.

pilot/pkg/serviceregistry/kube/controller/endpointslice.go, pilot/pkg/serviceregistry/kube/controller/endpointslice_test.go, releasenotes/notes/endpointslice-cache-memory-leak.yaml
This is a manual cherry-pick of #36518
Fix #36556
=> [release-1.11] Fix endpoint slice cache memory leak

releasenotes/notes/authz-dry-run-alpha.yaml
=> add release note for authz dry-run alpha promotion

pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
Addresses one minor comment in https://github.com/istio/istio/pull/36404
=> fix allocation length in listener patch removal

pilot/pkg/networking/core/v1alpha3/accesslog.go, pilot/pkg/networking/core/v1alpha3/listener_builder.go, pilot/pkg/networking/core/v1alpha3/listener_test.go, pilot/pkg/networking/core/v1alpha3/networkfilter.go
This PR fix setTCPAccessLog which should consider Telemetry API, and also pre-step of fixing  https://github.com/istio/istio/issues/36513
=> fix setTCPAccessLog

pkg/test/framework/components/zipkin/kube.go
=> Do not panic if we cannot start zipkin

pkg/kube/multicluster/secretcontroller.go, pkg/queue/instance.go
Alternative of #36310 with minor change
=> Gracefully delete cluster

releasenotes/notes/endpointslice-cache-memory-leak.yaml
Add release note for [#36558](https://github.com/istio/istio/pull/36558#pullrequestreview-838246169)
Sorry for my oversight, @dgn PTAL, thanks!
=> [release-1.12] Add release note for endpoint slice cache memory leak

pkg/envoy/agent.go
=> add additional logging for termination drain logic

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Keep Alive settings logic checks the same conditions at multiple places. This PR simplifies that logic. There is no functional change.
=> refactor keep alive settings

pilot/pkg/networking/core/v1alpha3/accesslog.go, pilot/pkg/networking/core/v1alpha3/accesslog_test.go
fix https://github.com/istio/istio/issues/36513
=> Implement EnvoyFileAccessLogProvider.logFormat

pilot/pkg/networking/core/v1alpha3/accesslog.go
fix mistake in https://github.com/istio/istio/pull/36586, will fix https://github.com/istio/istio.io/pull/10681
=> fix setTCPAccessLog refactor error

pkg/config/analysis/analyzers/util/config.go
=> Cleanup unused simple code

pilot/pkg/xds/endpoint_builder.go
Reverts istio/istio#36657
fixes https://github.com/istio/istio/issues/36658
=> Revert "Use read lock when building endpoints from shards"

tools/bug-report/pkg/bugreport/bugreport.go, tools/bug-report/pkg/cluster/cluster.go, tools/bug-report/pkg/config/config.go
There was as regression in `istioctl bug-report`. It was currently not working at all.
Using git bisect I was able to track it down to https://github.com/istio/istio/pull/36356
Output currently in master:
```
The following Istio control plane revisions/versions were found in the cluster:
The following proxy revisions/versions were found in the cluster:
Fetching proxy logs for the following containers:
Fetching Istio control plane information from cluster.
Running istio analyze on all namespaces and report as below:
Analysis Report:
```
Output along with this PR
```
The following Istio control plane revisions/versions were found in the cluster:
Revision default:
&version.MeshInfo{
{
Component: "pilot",
Info: …
```
=> Fix istioctl bug-report

pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
- [x ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> Dedup c.GetTransportSocketMatches() length check

pilot/pkg/networking/core/v1alpha3/accesslog_test.go
improve accesslog ut to avoid mistake like https://github.com/istio/istio/pull/36661
=> improve accesslog ut

tools/bug-report/pkg/bugreport/bugreport.go
Fixes https://github.com/istio/istio/issues/36700
=> Sort list of excludes in help to limit changes in help text

security/pkg/server/ca/server.go
=> Fix an erroneous function comment.

pilot/pkg/xds/cds.go, pilot/pkg/xds/delta.go, pilot/pkg/xds/delta_test.go, pilot/pkg/xds/deltaadstest.go, pilot/pkg/xds/eds.go
=> support delta eds, currently only support serviceentry

pkg/istio-agent/xds_proxy.go, pkg/istio-agent/xds_proxy_delta.go
Increase metric when xds connection error, fix https://github.com/istio/istio/issues/36507
=> Increase metric when xds connection error

releasenotes/notes/36277.yaml
Add releasenote for pr #36277
request by https://github.com/istio/istio/pull/36721#issuecomment-1007725310
=> Add releasenote for pr 36277

tests/integration/pilot/grpc_probe_test.go
=> Skip gRPC probe tests if k8s version<1.23

cni/pkg/plugin/iptables.go, cni/pkg/plugin/plugin_dryrun_test.go, cni/pkg/plugin/redirect.go, cni/pkg/plugin/testdata/invalid-drop.txt.golden, releasenotes/notes/36566.yaml, tools/istio-iptables/pkg/capture/run.go, tools/istio-iptables/pkg/capture/run_test.go, tools/istio-iptables/pkg/capture/testdata/drop-invalid.golden, tools/istio-iptables/pkg/cmd/root.go, tools/istio-iptables/pkg/config/config.go, tools/istio-iptables/pkg/constants/constants.go
Manual cherry-pick of #36566 and #36667
=> [release-1.12] Drop packets in INVALID state to avoid intermittent connection reset from sidecar

pkg/istio-agent/agent.go, pkg/istio-agent/xds_proxy.go, security/pkg/nodeagent/caclient/providers/citadel/client.go, security/pkg/nodeagent/caclient/providers/citadel/client_test.go, security/pkg/nodeagent/test/setup.go
Try to address https://github.com/istio/istio/issues/36709
=> unify key/certs process used to connect to Citadel and xds server

prow/config/default.yaml, prow/integ-suite-kind.sh
Fixes the [failing test](https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-120_istio_postsubmit/1480730775941812224)
Address https://github.com/istio/istio/issues/36757#issuecomment-1009137680
Associate with https://github.com/istio/test-infra/pull/3758
=> Add a new cluster config for kubernetes 1.23

pkg/test/envoy/setup.go
Can be a string (and is in new Envoy build due to
d050420b6e8ebbe144e6548a616e65a0d873c27 which fixed `usedonly`).
=> Do not fail test if envoy stats has non-float value

pilot/pkg/networking/util/util.go, pilot/pkg/security/authz/builder/builder.go, pilot/pkg/security/authz/model/generator.go, pilot/pkg/security/authz/model/generator_test.go, pilot/pkg/security/authz/model/model.go
=> update version check for config generate

pilot/pkg/networking/core/v1alpha3/listener_builder.go, pkg/istio-agent/xds_proxy_delta.go, pkg/wasm/convert.go
=> Reuse MaybeConvertWasmExtensionConfig

istioctl/cmd/proxystatus_test.go, istioctl/pkg/writer/pilot/status.go, istioctl/pkg/writer/pilot/status_test.go, istioctl/pkg/writer/pilot/testdata/multiStatusMultiPilot.txt, istioctl/pkg/writer/pilot/testdata/multiStatusSinglePilot.txt, istioctl/pkg/writer/pilot/testdata/singleStatus.txt, istioctl/pkg/writer/pilot/testdata/singleStatusFallback.txt, pilot/pkg/xds/debug.go, releasenotes/notes/36290.yaml
=> The output of "istioctl ps" cmd show the cluster(k8s) name which a pod belongs

tools/packaging/common/istio-start.sh
Fixes https://github.com/istio/istio/issues/36822
=> vm: append logs instead of overwriting

pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/gateway_test.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go
Fix https://github.com/istio/istio/issues/36805
=> Ignoring duplicated cipher suites

go.mod, go.sum, istioctl/cmd/describe.go, pilot/pkg/networking/core/v1alpha3/extension/wasmplugin.go, pilot/pkg/networking/core/v1alpha3/extension/wasmplugin_test.go, pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/listener_builder_test.go, pilot/pkg/networking/core/v1alpha3/tracing.go, pilot/pkg/security/authz/builder/builder.go, pilot/pkg/security/authz/builder/extauthz.go, pilot/pkg/security/authz/model/model.go, pilot/pkg/xds/filters/filters.go, pkg/config/xds/filter_types.gen.go, pkg/config/xds/filter_types.go, security/pkg/stsservice/mock/xdsserver.go
=> Use filter names in envoy api

tools/build-base-images.sh, tools/docker-builder/main.go, tools/docker-builder/types.go
Non breaking subset of https://github.com/istio/istio/pull/35989/. I think we can merge that one soon, but need a few more days.
Alternative to https://github.com/istio/istio/pull/36832 (sorry for not syncing up with you @Monkeyanator )
=> Improvements to docker builder

pilot/pkg/networking/core/v1alpha3/networkfilter.go, pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
=> Added Inbound networkfilter idletimeout

istioctl/cmd/kubeinject.go, istioctl/cmd/kubeinject_test.go, istioctl/cmd/testdata/deployment/hello.yaml.iop.injected, istioctl/cmd/testdata/inject-config-inline-iop.yaml, istioctl/cmd/testdata/inject-config-iop.yaml, istioctl/cmd/testdata/istio-operator.yaml, releasenotes/notes/36634.yaml
Fix https://github.com/istio/istio/issues/36472
=> Add iop file support to kube-inject

pilot/pkg/networking/grpcgen/grpcecho_test.go
fixed https://github.com/istio/istio/issues/36732
=> fix grpcgen tests

pkg/dns/client/dns.go, tools/istio-iptables/pkg/builder/iptables_builder_impl.go
=> minor comment fixes

istioctl/pkg/install/k8sversion/version.go, istioctl/pkg/install/k8sversion/version_test.go
When running the precheck command before installing Istio,  the `MinK8SVersion`
we are using to test is still the older 1.17. Istio 1.12 is officially supported
on Kubernetes versions 1.19 to 1.22.
Added the following changes:
- updated the `MinK8SVersion` from 1.17 to 1.19
- added a new testcase in the version unit test to check the kubernetes version
=> Istio install precheck only checks the min k8s version supported

pilot/pkg/config/kube/arbitraryclient/client.go, pkg/config/schema/ast/ast.go, pkg/config/schema/codegen/collections.go, pkg/config/schema/codegen/collections_test.go, pkg/config/schema/collections/collections.agent.gen.go, pkg/config/schema/collections/collections.gen.go, pkg/config/schema/metadata.yaml
To help with https://github.com/istio/istio/pull/36416
=> Add builtin collection for non-CRD types

pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go, pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
Fixes https://github.com/istio/istio/issues/36823
`28265 runs so far, 0 failures (100.00% pass rate). 1.379571661s avg, 2.703746358s max, 709.820229ms min`
=> Move namespace controller to new queue type

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/listener_builder.go, pilot/pkg/networking/core/v1alpha3/networkfilter.go, pilot/pkg/networking/util/util.go, releasenotes/notes/36796.yaml
=> [release-1.12] Only inject metadata exchange filters when proxy version is GE 1.12.

pilot/pkg/networking/core/v1alpha3/fake.go, pilot/pkg/xds/fake.go
Fix https://github.com/istio/istio/issues/36804
=> Fix grpcgen TestMtls

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
=> Add serviceentry log scope

istioctl/cmd/metrics.go, istioctl/cmd/metrics_test.go, istioctl/cmd/root.go
istioctl x metrice support custom duration
=> istioctl x metrice support custom duration

pilot/pkg/serviceregistry/aggregate/controller.go
=> remove aggregator AppendWorkloadHandler implement to prevent misuse

pilot/pkg/security/authn/policy_applier.go, pilot/pkg/server/instance.go
=> fix some typo

go.mod, go.sum, pilot/pkg/networking/core/v1alpha3/accesslog.go, pilot/pkg/networking/core/v1alpha3/accesslog_test.go, releasenotes/notes/36817.yaml
fix https://github.com/istio/istio/issues/36637
API: https://github.com/istio/api/pull/2175
=> add open telemetry provider

pilot/pkg/credentials/kube/secrets.go, pilot/pkg/xds/sds.go
=> Cleanup sds generator

istioctl/cmd/workload.go, istioctl/cmd/workload_test.go, releasenotes/notes/correct-virtualmachine-config-format.yaml
ref: https://github.com/istio/istio/issues/36358
=> Fix: correct error format after json marshal

pilot/pkg/model/controller.go, pilot/pkg/serviceregistry/aggregate/controller.go, pilot/pkg/serviceregistry/aggregate/controller_test.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go, pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go, pilot/pkg/serviceregistry/mock/discovery.go
This is a bug fix, and I will add a test if this way works.
fix https://github.com/istio/istio/issues/36907
cc @stevenctl @nmittler
=> Remove cluster handlers from aggregate controller when cluster deleted

pilot/pkg/bootstrap/mesh.go, pilot/pkg/bootstrap/server.go, pilot/pkg/model/context.go, pilot/pkg/model/network.go, pilot/pkg/networking/core/configgen.go, pilot/pkg/networking/core/v1alpha3/configgen.go, pilot/pkg/serviceregistry/kube/controller/network.go, pilot/pkg/xds/eds_sh_test.go, pkg/config/mesh/kubemesh/watcher.go, pkg/config/mesh/networks_watcher.go, pkg/config/mesh/watcher.go, pkg/config/mesh/watcher_test_utils.go, pkg/kube/configmapwatcher/configmapwatcher.go, pkg/kube/configmapwatcher/configmapwatcher_test.go
=> Remove duplicate networks handler registeration

pilot/pkg/features/pilot.go, pilot/pkg/model/service.go, pilot/pkg/serviceregistry/kube/controller/endpoints.go, pilot/pkg/serviceregistry/kube/controller/endpointslice.go, pilot/pkg/xds/eds.go, pilot/pkg/xds/eds_test.go, pilot/pkg/xds/endpoint_builder.go, releasenotes/notes/36274.yaml
Reverts istio/istio#36274
Revert while we explore test failures
=> Revert "send unready endpoints as unhealthy"

pkg/test/loadbalancersim/histogram/histogram.go, pkg/test/loadbalancersim/lb_test.go, pkg/test/loadbalancersim/loadbalancer/edf.go, pkg/test/loadbalancersim/loadbalancer/leastrequest.go, pkg/test/loadbalancersim/loadbalancer/priority.go, pkg/test/loadbalancersim/loadbalancer/roundrobin.go, pkg/test/loadbalancersim/loadbalancer/weight.go, pkg/test/loadbalancersim/locality/locality.go, pkg/test/loadbalancersim/locality/match.go, pkg/test/loadbalancersim/mesh/client.go, pkg/test/loadbalancersim/mesh/mesh.go, pkg/test/loadbalancersim/mesh/node.go, pkg/test/loadbalancersim/network/connection.go, pkg/test/loadbalancersim/network/helper.go, pkg/test/loadbalancersim/timer/queue.go
=> Simulation for LB algorithm evaluation

samples/open-telemetry/README.md, samples/open-telemetry/otel.yaml
add open-telemetry sample
related PR: https://github.com/istio/istio/pull/36817
=> add open-telemetry sample

tests/integration/security/https_jwt/main_test.go
See https://github.com/istio/istio/issues/36829. This is a brand new test so we are not regression on coverage
=> Skip flaky TestJWTHTTPS

pkg/test/echo/docker/Dockerfile.app_sidecar_base_centos
=> Workaround Centos 8 death

tests/integration/pilot/istioctl_test.go
See https://github.com/istio/istio/issues/37051
Also fixed some usage of InvokeOrFail in retry loop - this negates the
retry entirely
=> Fix and skip istiodless istioctl tests

manifests/profiles/openshift.yaml
`privileged` must be true in openshift profile.
=> Fix installation on OpenShift

pilot/pkg/features/pilot.go, releasenotes/notes/max-rps-xds.yaml
Fixes https://github.com/istio/istio/issues/35263
=> Change default `PILOT_MAX_REQUESTS_PER_SECOND` to 25

cni/pkg/plugin/plugin_test.go, istioctl/cmd/tag_test.go, istioctl/cmd/workload.go, pkg/kube/client.go
=> istioctl: fix order dependant tests

pilot/pkg/model/network_test.go
=> TestGatewayHostnames: use non-priv port

releasenotes/notes/36806.yaml
Add release note for PR https://github.com/istio/istio/pull/36806
Requested by https://github.com/istio/istio/pull/36851#issuecomment-1025973006
=> add release note for PR 36806

samples/kind-lb/README.md, samples/kind-lb/setupkind.sh
A utility script to help developers and users setup k8s cluster with load balancer installed.
=> Added setupkind.sh script

pkg/test/loadbalancersim/lb_test.go, pkg/test/loadbalancersim/loadbalancer/roundrobin.go, pkg/test/loadbalancersim/loadbalancer/weight.go, pkg/test/loadbalancersim/mesh/client.go, pkg/test/loadbalancersim/mesh/node.go, pkg/test/loadbalancersim/network/connection.go, pkg/test/loadbalancersim/network/helper.go, pkg/test/loadbalancersim/timeseries/data.go, pkg/test/loadbalancersim/timeseries/instance.go
=> Various fixes/cleanup to the loadbalancer simulation

pilot/pkg/networking/core/v1alpha3/accesslog.go
Fixes https://github.com/istio/istio/issues/37130
=> fix request without query access log formatter

istioctl/cmd/wait.go, pkg/test/framework/components/echo/echo.go, pkg/test/framework/components/echo/kube/sidecar.go, pkg/test/framework/components/echo/kube/workload.go, pkg/test/framework/components/istioctl/kube.go, pkg/test/framework/testcontext.go, tests/integration/pilot/istioctl_test.go, tests/integration/security/jwt_test.go, tests/integration/security/util/framework.go
* fix flake: queue.TestClosed
Change-Id: Ibddc488302badd9ef2c8568640e9bdff68ad99f5
* wait for close then push
Change-Id: I4cda8cefe325622a26e18920e8b2fb8fd4514bc8
=> Various test framework improvements

pilot/pkg/networking/apigen/apigen_test.go, pilot/pkg/networking/grpcgen/grpcecho_test.go, pilot/pkg/networking/grpcgen/grpcgen_test.go, pilot/pkg/xds/simple.go
=> Make grpc tests runnable in parallel and improve logging

pilot/pkg/networking/core/v1alpha3/envoyfilter/extension_configuration_patch.go, pilot/pkg/networking/core/v1alpha3/extension/wasmplugin.go
=> Minor clean up to use sets pkg.

tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
See
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/37162/integ-security-istiodremote_istio/1489422915270086656
=> Add more robust calls to ecc_signature test

tests/integration/iop-externalistiod-config-integration-test-defaults.yaml, tests/integration/iop-externalistiod-primary-integration-test-defaults.yaml
Temporary workaround for https://github.com/istio/istio/issues/37169
Might want this long term anyways, to match other jobs
=> Turn off autoscaling on externalistiod

pkg/bootstrap/instance_test.go, pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/metrics_no_statsd_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json
Sometimes we would write to the same file concurrently and cause issues
=> Fix race conditions with bootstrap unit test

pkg/kube/inject/inject.go, pkg/kube/inject/testdata/inject/prometheus-scrape.yaml, pkg/kube/inject/testdata/inject/prometheus-scrape.yaml.injected, pkg/kube/inject/testdata/inject/prometheus-scrape2.yaml, pkg/kube/inject/testdata/inject/prometheus-scrape2.yaml.injected, pkg/kube/inject/webhook.go, releasenotes/notes/36959.yaml
=> respect prometheus annotations

pkg/test/echo/cmd/client/main.go, pkg/test/framework/components/echo/cmd/echogen/testdata/golden.yaml, pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/components/echo/kube/testdata/basic.yaml, pkg/test/framework/components/echo/kube/testdata/healthcheck-rewrite.yaml, pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions-no-proxy.yaml, pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions.yaml, pkg/test/framework/components/echo/kube/testdata/multiversion.yaml, pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml, pkg/test/framework/components/prometheus/kube.go, pkg/test/framework/components/prometheus/prometheus.go, pkg/test/framework/resource/context.go, pkg/test/framework/telemetry.go, tests/integration/pilot/analyze_test.go, tests/integration/security/sds_egress/sds_istio_mutual_egress_test.go, tests/integration/telemetry/outboundtrafficpolicy/helper.go, tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go, tests/integration/telemetry/stats/prometheus/stats.go, tests/integration/telemetry/stats/prometheus/util_prometheus.go, tests/integration/telemetry/util.go
This cleans up the code a bit and drops tests times from ~28 min -> ~20 min.
=> tf: speed up telemetry tests

pilot/pkg/bootstrap/server.go, pilot/pkg/credentials/kube/multicluster.go, pilot/pkg/credentials/kube/secrets.go, pilot/pkg/credentials/model.go
This is to prevent adding handler after secret informer has been started.
=>  Credential controller: make use of generic event handler wrapper

tests/integration/security/jwt_test.go, tests/integration/security/main_test.go, tests/integration/security/testdata/requestauthn/headers-params.yaml.tmpl
Added additional tests in request authentication. Added jwt token in  `fromHeaders` and `fromParams` and tested it against jwksuri.
=> added tests for fromHeader and fromParams in request authentication

samples/helloworld/src/app.py
Helloworld app should listen ipv6 address for some test cases.
=> Make helloworld app listen both ipv6 and ipv4 addresses

istioctl/cmd/authz.go
=> Fix x authz check example

pkg/kube/inject/webhook.go
=> minor refactor `util/sets`

cni/pkg/taint/taint.go, istioctl/pkg/validate/validate.go, pilot/pkg/controller/workloadentry/workloadentry_controller.go
Signed-off-by: kerthcet <kerthcet@gmail.com>
When reading source code, found some typo and did some refactoring works by the way.
=> fix typo and do some refactoring work

pkg/test/echo/docker/Dockerfile.app_sidecar_base_centos
Cherrypick https://github.com/istio/istio/pull/37090
=> Workaround centos repo removal

pilot/cmd/pilot-agent/options/agent.go, pilot/cmd/pilot-agent/options/options.go, pkg/istio-agent/agent.go, pkg/istio-agent/xds_proxy.go, pkg/wasm/cache.go, pkg/wasm/cache_test.go, pkg/wasm/imagefetcher.go
fixed https://github.com/istio/istio/issues/36571
=> add insecure oci support

pkg/bootstrap/config.go, pkg/bootstrap/option/convert.go, pkg/bootstrap/option/instances.go, pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/metrics_no_statsd_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json, releasenotes/notes/runtime-values.yaml, tools/packaging/common/envoy_bootstrap.json
=> Implement `runtimeValues` in proxy config

pilot/pkg/model/extensions.go, pilot/pkg/model/extensions_test.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, releasenotes/notes/37227.yaml
implement of `WasmPlugin.VmConfig`
=> support Wasmplugin vmconfig

istioctl/cmd/describe.go
=> Fix describe pod PeerAuthentication info

cni/pkg/plugin/plugin_test.go, istioctl/cmd/tag_test.go, istioctl/cmd/workload.go
* istioctl: fix order dependant tests
* Fix cni and pilot test as well
(cherry picked from commit b872e512c22166a3dc338f37d45f20728b37c48c)
Fixes https://github.com/istio/istio/issues/37245
=> istioctl: fix order dependant tests (#37045)

pilot/pkg/serviceregistry/serviceentry/store.go
=> refactoring: remove code duplication in `serviceregistry/serviceentry`

pilot/pkg/networking/networking.go, pkg/config/protocol/instance.go, tests/fuzz/pilot_model_fuzzer.go
=> remove thrift protocol references

pkg/test/framework/suite.go, tests/integration/helm/main_test.go, tests/integration/helm/upgrade/main_test.go, tests/integration/operator/main_test.go, tests/integration/pilot/cni/cniversionskew_test.go, tests/integration/pilot/endpointslice/endpointslice_test.go, tests/integration/pilot/mcs/autoexport/autoexport_test.go, tests/integration/pilot/revisioncmd/main_test.go, tests/integration/pilot/revisions/revisions_test.go, tests/integration/security/chiron/main_test.go, tests/integration/security/external_ca/main_test.go, tests/integration/security/file_mounted_certs/main_test.go, tests/integration/security/filebased_tls_origination/main_test.go, tests/integration/security/mtlsk8sca/main_test.go, tests/integration/security/sds_egress/main_test.go, tests/integration/security/sds_ingress/quic/ingress_test.go, tests/integration/security/sds_ingress_k8sca/main_test.go, tests/integration/telemetry/outboundtrafficpolicy/traffic_test.go, tests/integration/telemetry/policy/envoy_ratelimit_test.go, tests/integration/telemetry/stackdriver/vm/main_test.go
=> Deprecate some test skip options for multicluster

pilot/pkg/xds/delta.go
Rest of the logs start with ADS:. This is PR makes log lines consistent. Since only one of ADS/Delta ADS is used, using ADS consistently is better
=> log consistency in delta

pilot/pkg/xds/delta.go
=> reduce lock duration in delta

pkg/wasm/imagefetcher.go
`remote.Image` respect `fetchOpts`
=> `remote.Image` respect `fetchOpts`

pilot/pkg/config/file/store.go
=> fix type assertion

pkg/test/framework/components/istioctl/istioctl.go, pkg/test/framework/components/istioctl/kube.go, pkg/test/framework/config.go, pkg/test/framework/resource/context.go, tests/integration/security/authorization_test.go, tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go, tests/integration/security/https_jwt/https_jwt_test.go, tests/integration/security/jwt_test.go, tests/integration/security/util/framework.go, tests/integration/security/util/reachability/context.go, tests/integration/telemetry/stackdriver/api/stackdriver_filter_test.go, tests/integration/telemetry/stackdriver/common.go, tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go, tests/integration/telemetry/stackdriver/stackdriver_filter_dry_run_test.go, tests/integration/telemetry/stackdriver/stackdriver_filter_test.go, tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go, tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
Security tests have a custom implementation to deal with issues related to WaitForConfig. Moving to a common implementation.
=> [TF] Create common WaitForConfig implementation

pkg/test/echo/cmd/client/main.go
=> Fix invalid flag definition in echo

pkg/config/validation/validation.go, pkg/config/validation/validation_test.go
=> Add warning when setting certs with PASSTHROUGH mode

pkg/test/framework/components/istioctl/kube.go
=> [TF] Prevent concurrent istioctl invoke

pkg/test/framework/components/istio/operator.go
small issue from https://github.com/istio/istio/commit/908d3fb4768e103e4d949dcc2a2cb2badce9d627
=> Fix regression in istioctl install logic

pilot/pkg/xds/cds.go, pilot/pkg/xds/eds.go, pilot/pkg/xds/lds.go, pilot/pkg/xds/rds.go
=> Ignore proxyconfig for all xds push and ignore wle for lds

pilot/pkg/xds/sds.go
=> abstract pem decode and x509.ParseCertificates

pilot/pkg/model/context.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/delta.go, security/pkg/nodeagent/sds/sdsservice.go
=> fix map locking issue in ads properly

pkg/test/framework/components/stackdriver/stackdriver.yaml
Saw some strange issues, probe might help.
=> Add readiness probe to SD

pkg/test/framework/testcontext.go
=> Do not dump to same folder on tf failed retry

pkg/kube/client.go
=> Add api extensions v1 to IstioSchemas

security/pkg/nodeagent/sds/sdsservice.go
Fixes panic in https://storage.googleapis.com/istio-prow/logs/unit-tests_istio_postsubmit/1494151328618778624/build-log.txt
=> fix panic in sds service

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/xds/delta.go
=> Introduce delta xds log scope to distinguish ads logs

pilot/pkg/features/pilot.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go
=> add EnableServiceEntrySelectPods flag back

pilot/pkg/model/envoyfilter.go
=> Bump "temporary" hack

tools/docker-builder/main.go, tools/docker-builder/types.go
=> Allow pushing to multiple tags

pilot/pkg/networking/grpcgen/lds.go
=> cleanup commented out function

pilot/pkg/xds/endpoint_builder.go
=> remove nit log

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go, pilot/pkg/model/sidecar.go
https://github.com/istio/istio/pull/37413/files#r809621216
=> retain DestinationRule func name in push context

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go, pilot/pkg/model/sidecar.go, pilot/pkg/networking/apigen/apigen.go, pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/grpcgen/lds.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/eds.go, pkg/dns/server/name_table.go, pkg/dns/server/name_table_test.go
=> Refactor Services to remove dummy proxy

pilot/pkg/model/context.go
update comment as mentioned in https://github.com/istio/istio/pull/37452#discussion_r810872235
=> update  comment

pkg/config/gateway/gateway_test.go
Adding unit tests for pkg/config/gateway/gateway_test.go
Ref: https://github.com/istio/istio/issues/37354
=> tests: covers pkg/config/gateway/gateway_test.go

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_test.go
=> add more tests for delta clusters

go.mod, pilot/pkg/networking/core/v1alpha3/accesslog.go, pilot/pkg/networking/core/v1alpha3/accesslog_test.go, releasenotes/notes/36817.yaml
fix https://github.com/istio/istio/issues/37199
=> add open telemetry provider (#36817)

pilot/pkg/xds/debug.go
right now ecds is not a part of configdump, this PR make you can debug with endpoint `/debug/ecdsz` 
demo usage:
```console
kubectl exec -it istiod-7db4959cf9-btrj2 -nistio-system -- pilot-discovery request get /debug/ecdsz?proxyID=httpbin-74fb669cc6-mxhpx
```
```json
[
{
"config": {
"name": "default.httpbin-rate-limiting",
"Vm": {
"VmConfig": {
"runtime": "envoy.wasm.runtime.v8",
"code": {
"Specifier": {
"Remote": {
"http_uri": {
"uri": "oci://ghcr.io/tetratelabs/wasm-rate-limiting:v1",
"HttpUpstreamType": {
"Cluster": "_"
},
"timeout": {
"seconds": 30
}
}
}
}
}
}
},
"configuration": {}
}
},
{
"config": {
"name": "default.display-metadata",
"Vm": {
"VmConfig": {
"runtime": "envoy.wasm.runtime.v8",
"code": {
"Specifier": {
"Remote": { …
```
=> add `/debug/ecdsz`

pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/networking.go
This pull request just removes unnecessary fields from `FilterChain` struct. Some of them are set, but not read and some are not used at all.
=> Remove unused fields from FilterChain struct

pilot/pkg/networking/core/v1alpha3/cluster.go
While detecting deleted clusters, we go through watchedResourceNames for every configUpdated and parse cluster name. This PR does it only once and reuses it for all configUpdates.
=> eliminate n^2 loop while detecting deleted clusters

pkg/test/framework/components/echo/kube/deployment.go
=> Reduce spammy log message in test framework

pkg/test/framework/resource/flags.go
=> tf: allow multiple workload skips in single flag

tests/integration/pilot/common/traffic.go
=> tf: skip tests early, before applying YAMLs

tests/integration/security/authorization_test.go, tests/integration/security/jwt_test.go
We have enabled the authz and reqauth integration tests in multicluster environment.
=> enabled authz tests in multicluster env

pilot/pkg/model/context.go
=> minor xds comments

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go, pilot/pkg/serviceregistry/serviceentry/store.go
=> Revert #36697 auto allocate ip while updating the store

prow/lib.sh
=> Trim images built for tests

pilot/pkg/model/service.go
=> remove copystructure Mutex rewrite

samples/open-telemetry/README.md
=> fix doc nit

pilot/pkg/networking/util/util.go
=> remove unused functions

tests/integration/base.yaml
=> Disable Envoy retries in tests

pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch_test.go, releasenotes/notes/replace-virtualhost.yaml
=> Support REPLACE for virtual host in envoy filter

pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, releasenotes/notes/upstream-tls-version.yaml
=> Set upstream max tls version to TLS 1.3

pilot/pkg/networking/core/v1alpha3/httproute.go
Fix https://github.com/istio/istio/issues/37529
=> Clone catch all vhost to prevent it from being mutated

pkg/wasm/cache.go, pkg/wasm/cache_test.go
The last touch time of the wasm cache entry was never updated.
=> fix a bug that cache entries were never updated

pilot/pkg/xds/discovery.go
=> Pilot debounce: log reason when there is no config

pilot/pkg/xds/ads_test.go
Seen some flakes. So increasing the timeout
=> increase test timeout for ads push scoping

pilot/pkg/model/sidecar.go, pilot/pkg/serviceregistry/aggregate/controller.go
=> [release-1.12] deepcopy before merging port (#37536)

cni/pkg/plugin/iptables_linux.go, cni/pkg/plugin/iptables_unspecified.go, cni/pkg/plugin/plugin_dryrun_test.go
Fixes https://github.com/istio/istio/issues/37625
=> Update to split linux for building on Macs

tools/docker-builder/main.go
=> Restrict another hub to prevent accidents

pkg/wasm/cache.go, pkg/wasm/cache_test.go, pkg/wasm/imagefetcher.go, pkg/wasm/imagefetcher_test.go
=> Use image's digest instead of binary's checksum 

pkg/envoy/agent.go, pkg/envoy/agent_test.go
=> skip active connections check when downstream cx stats are not available

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/store.go, pilot/pkg/serviceregistry/serviceentry/store_test.go
=> optimize: auto allocate addresses only when services updated

tests/integration/operator/switch_cr_test.go
[**Please provide a description of this PR:**
](https://github.com/istio/istio/issues/37661)
=> Log remaining names in operator test

tests/integration/security/util/reachability/context.go
=> Remove duplicate test case

pkg/test/env/istio.go, pkg/test/fakes/imageregistry/main.go, pkg/test/framework/components/containerregistry/container_registry_server.yaml, pkg/test/framework/components/containerregistry/containerregistry.go, pkg/test/framework/components/containerregistry/kube.go
=> Add fake container registry component for Wasm pulling integration test.

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go, pilot/pkg/serviceregistry/serviceentry/store.go
cherry-pick #37539
fix https://github.com/istio/istio/issues/37557
=> [release-1.13] Revert #36697 auto allocate ip while getting services from the store

pkg/test/framework/components/echo/kube/deployment.go, tests/integration/telemetry/outboundtrafficpolicy/traffic_test.go, tests/integration/telemetry/policy/envoy_ratelimit_test.go, tests/integration/telemetry/stackdriver/vm/main_test.go
Make all telemetry tests support multiple clusters
=> Make all telemetry tests support multiple clusters

security/pkg/nodeagent/cache/monitoring.go
update description
https://github.com/istio/istio/pull/37372#discussion_r818290499
=> update metric description

pilot/pkg/model/context.go, pilot/pkg/model/push_context.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/bench_test.go, pilot/pkg/xds/debug.go, pilot/pkg/xds/delta.go, pilot/pkg/xds/discovery.go
Attempt to fix https://github.com/istio/istio/issues/36791
=> Pilot: store latest push instead of global

pilot/pkg/xds/debuggen.go
Avoid assuming this is set
Cherrypick from https://github.com/istio/istio/pull/37696/files#diff-e467bd4280640c71cb611d762055baee7f1778eddd025dcaa1e2b5ffcb74c712R91
=> debuggen: check verified identity presence explicitly

tools/build-kind-image.sh
Now that we will do multi-arch builds its a bit more complex than a
single command, so check in a script to make it easy
=> Add script to build kind node image

pilot/pkg/model/sidecar.go, pilot/pkg/serviceregistry/aggregate/controller.go
fix https://github.com/istio/istio/issues/37563
=> [release-1.13] [Bug Fix] no mutating service when merging port

go.mod, go.sum, istio.deps
=> UPDATE_BRANCH=master ./bin/update_deps.sh

Makefile.core.mk
=> Bump 1.11 base image

pilot/pkg/networking/core/v1alpha3/fake.go, pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go, pilot/test/xdstest/extract.go
Part of https://github.com/istio/istio/issues/37691.
Encoding cases where we behave incorrectly; we can flip the behavior with https://github.com/istio/istio/pull/37721
=> Add tests for virtual services

pilot/pkg/model/context.go, pilot/pkg/model/push_context.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/bench_test.go, pilot/pkg/xds/debug.go, pilot/pkg/xds/delta.go, pilot/pkg/xds/discovery.go, tests/integration/pilot/multicluster_test.go
This reverts commit 6b93316d353d9e00f7ecd23ab5c83f9ec91c5a74.
Seems to be a regression
=> Revert "Pilot: store latest push instead of global (#37604)"

pilot/pkg/security/authz/model/generator.go, pilot/pkg/security/authz/model/generator_test.go
=> Make AuthorizationPolicy parsing more robust

go.mod, go.sum
=> go dependencies: bump protobuf library

tools/go-compile-verbose
=> Add new `go-compile-verbose` tool to help debug build times

pkg/kube/inject/webhook.go, pkg/kube/util.go, pkg/webhooks/validation/server/server.go
Cherrypick https://github.com/istio/istio/pull/37785
=> [release-1.11] pilot: limit reads from untrusted inputs

pilot/pkg/serviceregistry/kube/controller/multicluster.go
=> Enable serviceentry wles cross clusters

go.mod, go.sum
Manual merge to fix https://github.com/istio/istio/issues/37789
=> [release-1.12] go dependencies: bump protobuf library

prow/integ-suite-kind.sh, tools/packaging/packaging.mk
=> Do not waste time compressing VM packages in tests

tests/integration/pilot/common/apps.go, tests/integration/pilot/common/routing.go, tests/integration/pilot/common/traffic.go, tests/integration/pilot/ingress_test.go, tests/integration/security/authorization_test.go, tests/integration/security/ca_custom_root/secure_naming_test.go, tests/integration/security/external_ca/reachability_test.go, tests/integration/security/https_jwt/https_jwt_test.go, tests/integration/security/jwt_test.go, tests/integration/security/util/reachability/context.go
=> [TF] Removing some multi-cluster specific logic

security/pkg/nodeagent/cache/secretcache_test.go
Fixes https://github.com/istio/istio/issues/37592. Ran multiple times locally and it passed.
=> fix test file secrets flake

tests/integration/pilot/ingress_test.go
Currently its inside the Ingresses loop; but we are deploying a stand
alone gateway, so it doesn't make sense to deploy it 3 times
=> Move managed gateway our of loop

samples/kind-lb/setupkind.sh
latest metallb master branch is broken. Switch to use the latest
working version v0.12
=> Fixed metallb master branch issue

go.mod, go.sum
=> Bump to grpc v1.45

pilot/pkg/bootstrap/server_test.go, pilot/pkg/model/network_test.go, pilot/pkg/serviceregistry/kube/controller/endpointslice_test.go, pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go, pilot/pkg/trustbundle/trustbundle.go, pilot/pkg/trustbundle/trustbundle_test.go, pkg/wasm/cache_test.go, pkg/wasm/httpfetcher.go, pkg/wasm/httpfetcher_test.go, security/pkg/k8s/chiron/utils.go, security/pkg/k8s/chiron/utils_test.go, security/pkg/pki/ra/k8s_ra.go
For https://github.com/istio/istio/issues/37555
=> Speed up some of the slowest pilot tests

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
run eds cache update in serial and wait for completion
fix https://github.com/istio/istio/issues/37756
=> Fix TestEdsCache flake

release/downloadIstioCandidate.sh, release/downloadIstioCtl.sh, tests/integration/create_cluster_gke.sh
Updating shellcheck dependency
=> Update scripts to pass shellcheck 0.8

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
=> remove reflect.DeepEquals for label equality

release/downloadIstioCandidate.sh, release/downloadIstioCtl.sh
osx arm64 support added to download release scripts.
=> arm64 for osx added to download scripts

pilot/pkg/networking/core/v1alpha3/fake.go, pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/networking/core/v1alpha3/httproute_test.go, pilot/pkg/networking/core/v1alpha3/route/route.go, pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go, pilot/pkg/xds/fake.go, pilot/test/xdstest/extract.go, releasenotes/notes/vs-regression.yaml
Fixes https://github.com/istio/istio/issues/37898
=> 1.13: fix VirtualService regression

pilot/pkg/networking/core/v1alpha3/fake.go, pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/networking/core/v1alpha3/httproute_test.go, pilot/pkg/networking/core/v1alpha3/route/route.go, pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go, pilot/test/xdstest/extract.go, releasenotes/notes/vs-regression.yaml
Fixes https://github.com/istio/istio/issues/37899
=> 1.12: Fix VS regression

pilot/pkg/features/pilot.go
=> pilot: minor improvement to flag comment

Makefile.core.mk
noticed some deadcode, clean up a bit
=> misc: cleanup makefile a bit

go.mod, pkg/test/shell/shell.go
=> tf: more robust shell parsing

pkg/kube/rpc_creds_test.go, pkg/queue/instance.go, tests/integration/pilot/mirror_test.go, tests/integration/telemetry/stats/prometheus/nullvm/accesslogs_test.go, tests/util/common_utils.go
=> using k8s rand string and cleanup unused utils

pilot/pkg/model/addressmap.go, pilot/pkg/model/service.go, pilot/pkg/model/service_test.go
=> Add fuzz test for deepcopy

tools/docker
Re-use common logic for setting up environment
=> docker: simplify build script

pilot/pkg/networking/core/v1alpha3/tls.go
=> eliminate deep equals in route build

pilot/pkg/config/kube/gateway/conversion.go, pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/network.go, pilot/pkg/xds/mesh_network_test.go
=> use api repo constants

pilot/pkg/xds/eds.go, pilot/pkg/xds/eds_test.go
FIx https://github.com/istio/istio/issues/37809
=> do not send initial unhealthy endpoints on full push

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
=> clarify some comments in service discovery

pilot/pkg/features/pilot.go, pilot/pkg/networking/core/v1alpha3/listener.go
Useful when using envoyproxy/envoy builds without Istio filters compiled
in
=> pilot: add feature flag to opt out of ALPN filter

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
=> refactor eds functions

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
Fix  https://github.com/istio/istio/issues/37981
=> Fix se delete cause endpoints shard deleted

go.mod, go.sum, licenses/github.com/felixge/fgprof/LICENSE.txt, licenses/github.com/google/pprof/LICENSE, licenses/github.com/google/pprof/third_party/svgpan/LICENSE, pkg/test/profile/fgprof.go
This is something I have copied into tests many times for debugging,
really helpful to have integrated fully I think.
=> test: add -fullprofile flag option for tests

pilot/pkg/networking/core/v1alpha3/accesslog.go, pilot/pkg/networking/core/v1alpha3/listener_builder.go, pilot/pkg/networking/core/v1alpha3/listener_test.go, pilot/pkg/networking/core/v1alpha3/networkfilter.go, releasenotes/notes/38032.yaml
fixed: https://github.com/istio/istio/issues/37723
manual cherry-pick of https://github.com/istio/istio/pull/36586 and https://github.com/istio/istio/pull/36661
=> fix setTCPAccessLog (#36586)

pkg/test/echo/server/endpoint/tcp.go
=> echo: add Hostname key to tcp response

pilot/pkg/xds/eds.go, pilot/pkg/xds/eds_test.go
See https://github.com/istio/istio/pull/38069#discussion_r832581477
=> eds: correct (and test) always pushing

pilot/pkg/networking/core/v1alpha3/tracing.go, pilot/pkg/networking/core/v1alpha3/tracing_test.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go
=> improve telemetry validation

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/store.go, pilot/pkg/serviceregistry/serviceentry/store_test.go
=> access auto allocate flag directly

cni/pkg/plugin/kubernetes.go, pilot/cmd/pilot-agent/config/config.go, pilot/cmd/pilot-agent/config/config_test.go, pilot/pkg/model/context.go, pilot/pkg/model/proxy_config.go, pilot/pkg/model/proxy_config_test.go, pkg/config/mesh/mesh.go, pkg/config/mesh/mesh_test.go, pkg/envoy/proxy_test.go, pkg/istio-agent/agent_test.go, pkg/istio-agent/xds_proxy_test.go, pkg/kube/inject/inject_test.go, pkg/kube/inject/validate.go, pkg/kube/inject/webhook.go
This is a followup to https://github.com/istio/istio/pull/38056 for the
same reasons
=> proxy config: pass around as a pointer

pkg/test/framework/components/echo/deployment/builder.go, pkg/test/framework/components/echo/kube/builder.go, pkg/test/framework/components/echo/kube/instance.go, pkg/test/framework/config.go, pkg/test/framework/resource/context.go
Adding some concurrency and additional cleanup.
=> [TF] Some optimizations for building echo

go.mod, go.sum
The post-submit job failed for istio/client-go to update istio/istio after golang/protobuf changes were merged in
=> Update istio/pkg and istio/client-go dependencies

tests/integration/telemetry/stats/prometheus/nullvm/accesslogs_test.go
=> tf: set provider properly in access log file test

pilot/pkg/model/telemetry.go, pilot/pkg/model/telemetry_test.go
fixed https://github.com/istio/istio/issues/37724
actually, this PR will not fix the `EnvoyFilter` part, get more info here https://github.com/istio/istio/issues/37724#issuecomment-1067464435 .
=> not installing the stats filter when diabled all metrics

pilot/pkg/model/cluster_local.go, pilot/pkg/model/config.go, pilot/pkg/model/config_test.go, pilot/pkg/model/destination_rule.go, pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go
=> Refactor `MostSpecificHostMatch`

tests/fuzz/networking_core_v1alpha3_fuzzer.go
Our code makes an assumption this list is >0 and validates that in one
place rather than every callsite
=> fuzz: validate Proxy before calling functions

releasenotes/notes/gogo-protobuf.yaml, releasenotes/notes/xds-partial-full.yaml
=> Add a few missed release notes

pkg/test/framework/components/echo/instances.go, pkg/test/framework/components/istio/operator.go
=> Fixing CNI test

tools/packaging/packaging.mk
=> Fix TODO for non-compression deb files

operator/cmd/mesh/upgrade.go
Removes redundant code introduced in the latest [fix.](https://github.com/istio/istio/pull/37933)
=> Remove double generation of IstioOperatorSpec in istioctl upgrade

pilot/pkg/xds/debug.go, pilot/pkg/xds/nds.go
fix: https://github.com/istio/istio/issues/38162
=> fix debug panic

cni/pkg/cmd/root.go, cni/pkg/config/config.go, cni/pkg/constants/constants.go, cni/pkg/install/install.go, cni/pkg/install/install_test.go
Change-Id: I9e303287bbdb82c22b40590fef9092e77b7d9df4
add another env var for CNI installation to skip the install entirely.
=> add enable install env var to be able to skip installation entirely

pilot/cmd/pilot-agent/main.go, pilot/cmd/pilot-agent/options/agent.go, pilot/cmd/pilot-agent/options/statusserver.go, pilot/pkg/model/context.go, pilot/pkg/util/network/ip.go, pilot/pkg/util/network/ip_test.go, pkg/bootstrap/config.go, pkg/envoy/proxy.go
=> Revert "use same ipv6 detection logic every where"

README.md
Shriram set up our CII badge in 2017, so I figured it was about time to update it.
=> Update openssf badge

pkg/test/framework/components/echo/common/deployment/echos.go
The 2-namespace echo deployment view will be used by up-coming security tests.
=> [TF] Echo: add 2-ns view and fix delta XDS version

prow/lib.sh
=> Fix date command in logging

Makefile.core.mk, pkg/test/echo/docker/Dockerfile.app_sidecar, pkg/test/echo/docker/Dockerfile.app_sidecar_base, pkg/test/echo/docker/Dockerfile.app_sidecar_base_centos, pkg/test/echo/docker/Dockerfile.app_sidecar_centos_7, pkg/test/echo/docker/Dockerfile.app_sidecar_centos_8, pkg/test/framework/components/echo/config.go, pkg/test/framework/components/echo/kube/deployment.go, prow/lib.sh, tests/integration/pilot/vm_test.go, tools/build-base-images.sh, tools/docker-builder/main.go, tools/docker-builder/types.go, tools/docker.yaml, tools/istio-docker.mk
Fixes https://github.com/istio/istio/issues/38009
This changes the set of OS's we test to improve coverage while decreasing test count.
Before merging, I will need to build the new bases; I put a hold to do that. Will do so after approval.
There were a number of related fixes to make this (easily) work; comments inline describing why.
Testing: we only test all of these in postsubmit; I manually tested.
=> vm tests: update and deprcated OS's tested

pkg/test/framework/components/echo/kube/deployment.go, prow/lib.sh, tools/docker.yaml
See https://github.com/istio/istio/issues/38224
=> Skip CentOS 8 tests for VMs

pkg/wasm/convert.go
Address https://github.com/istio/istio/pull/37161#discussion_r840839068.
=> Add comment about Wasm env clean up.

tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
Fix https://github.com/istio/istio/issues/38229
This makes sure the container registry is ready to serve in the cluster when test runs.
=> Deploy container registry before echo at customize metric test.

tools/istio-iptables/pkg/cmd/root.go, tools/istio-iptables/pkg/cmd/root_test.go
mock net.InterfaceAddrs to make its unit test become available
=> mock net.InterfaceAddrs to make its unit test become available

tests/fuzz/networking_core_v1alpha3_envoyfilter_fuzzer.go, tests/fuzz/networking_core_v1alpha3_fuzzer.go
Fixes the broken OSS-fuzz build.
@howardjohn
=> Fix broken OSS-fuzz build

pilot/pkg/xds/ecds.go
this will fix https://github.com/istio/istio/pull/38165
=> only get secretcontroller when needed

pkg/istio-agent/xds_proxy.go
=> fix: Fix the typo comment

pilot/docker/Dockerfile.proxyv2
=> Bump iptables image

istioctl/cmd/proxystatus_test.go, istioctl/pkg/writer/pilot/status.go, istioctl/pkg/writer/pilot/status_test.go, istioctl/pkg/writer/pilot/testdata/multiStatusMultiPilot.txt, istioctl/pkg/writer/pilot/testdata/multiStatusSinglePilot.txt, istioctl/pkg/writer/pilot/testdata/multiXdsStatusMultiPilot.txt, istioctl/pkg/writer/pilot/testdata/multiXdsStatusSinglePilot.txt, istioctl/pkg/writer/pilot/testdata/singleStatus.txt, istioctl/pkg/writer/pilot/testdata/singleStatusFallback.txt, pilot/pkg/xds/statusgen.go, releasenotes/notes/38273.yaml
make `istioctl ps` support ECDS
=> istioctl ps support ECDS

releasenotes/notes/38158.yaml
=> add release note for #38158

pkg/test/framework/resource/context.go, pkg/test/framework/scope.go
Reverts istio/istio#38270
See https://github.com/istio/istio/pull/38270#issuecomment-1093271326, causing some issues in stability. Revert while we investigate
=> Revert "[tf] Optimize scope close"

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go
=> clean up cluster builder

tests/fuzz/fuzz.go, tests/fuzz/networking_core_v1alpha3_envoyfilter_fuzzer.go, tests/fuzz/pilot_networking_fuzzer.go, tests/fuzz/workloadentry_controller_fuzzer.go
=> fuzz: exit early on more invalid inputs

pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
=> Fix TestWorkloadEntryOnlyMode

pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/tls.go
=> Clean up unused destinationCIDR  param

security/pkg/k8s/configutil_test.go
Address comment https://github.com/istio/istio/pull/38231/files#r841539862
=> Add test for InsertDataToConfigMap

docker/Dockerfile.distroless
Use prebuilt static distroless image with 1337:1337 user/group
=> Use prebuilt static image from distroless mirror

go.mod, go.sum, tests/integration/pilot/gateway_conformance_test.go
=> Re-enable Gateway conformance tests

pilot/docker/Dockerfile.proxyv2
=> Pull in recent iptables updates

tools/docker-builder/builder/crane.go
=> Fix concurrent map write

pilot/pkg/bootstrap/istio_ca.go
fix https://github.com/istio/istio/issues/38366
=> Fix cacerts file watch

istio.deps, pkg/bootstrap/config.go, pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/metrics_no_statsd_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json, pkg/envoy/instance_test.go, pkg/envoy/testdata/envoy_bootstrap_v2.tmpl.json, prow/release-commit.sh
Test for pulling in latest Envoy. Comment of change needed here: https://github.com/istio/istio/pull/38310#issuecomment-1094511914
Run update-reps.sh script to get latest dependencies including Envoy.
=> Test envoy update

pilot/pkg/bootstrap/configcontroller.go, pilot/pkg/bootstrap/servicecontroller.go, pilot/pkg/model/authentication_test.go, pilot/pkg/model/authorization_test.go, pilot/pkg/model/config.go, pilot/pkg/model/context.go, pilot/pkg/model/proxy_config_test.go, pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go, pilot/pkg/model/telemetry_test.go, pilot/pkg/networking/apigen/apigen.go, pilot/pkg/networking/apigen/apigen_test.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go, pilot/pkg/networking/core/v1alpha3/fake.go, pilot/pkg/networking/core/v1alpha3/listener_test.go, pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go, pilot/pkg/networking/grpcgen/grpcgen_test.go, pilot/pkg/security/authz/builder/builder_test.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go, pilot/pkg/xds/debug.go, pilot/pkg/xds/discovery.go, pilot/pkg/xds/simple.go, pkg/adsc/adsc.go, pkg/kube/inject/webhook_test.go, tests/fuzz/pilot_model_fuzzer.go
This was basically ConfigStore + Helpers. But we never used the Helpers.
Remove it
=> refactor: remove unused IstioConfigStore

tests/integration/security/authorization_test.go, tests/integration/security/testdata/authz/v1beta1-ingress-gateway.yaml.tmpl, tests/integration/security/testdata/authz/v1beta1-jwt.yaml.tmpl, tests/integration/security/testdata/authz/v1beta1-negative-match.yaml.tmpl
**Added new authz tests to improve the test coverage**
AuthZ.rules.to.operation.notPorts
AuthZ.rules.to.operation.notHosts
AuthZ.rules.to.operation.notMethods
Authz.rules.from.source.notRequestPrincipals
AuthZ.rules.from.source.ipBlocks
AuthZ.rules.from.source.notIpBlocks
=> added new authz tests
