istio/istio

pilot/pkg/features/pilot.go, pilot/pkg/grpc/grpc.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/delta.go, pilot/pkg/xds/discovery.go
In a cluster we saw thundering herd problem. When a new istiod spins up, it instantly receives 1k requests and attempts to process them all. This leads to OOM, so all of them disconnect and try again to new instance. While the instance can handle 1k connections, it cannot handle 1k requests all at once. Requests are the most expensive (always total full push) and there is no limiting.
With rate limit, we can limit max memory and avoid throttling, allowing us to slowly ramp up number of connections.
An alternative or addition we can do is to have a semaphore limiting max *concurrent* requests. The reason I went with this is:
* Rate limit makes it easier to block requests immediately - before we do anything expensive at all or cause churn with connects+disconnects, workload entry …
=> Add a rate limit to incoming XDS requests

pkg/config/crd/validator.go, pkg/config/schema/fuzz_test.go, pkg/kube/client.go, pkg/kube/util.go, tests/fuzz/config_validation_fuzzer.go
Alternative to https://github.com/istio/istio/pull/35023
See kubernetes-sigs/controller-runtime#1654
This makes a single Scheme with all Istio types. This should be used by anyone that needs a scheme like this. Aside from refactoring, this ensures the NegotiatedSerializer uses this Scheme which is the core fix.
=> Share complete scheme in all usages

tests/fuzz/oss_fuzz_build.sh, tests/fuzz/regression_test.go, tests/fuzz/security_fuzzer.go
Adds a fuzzer that targets `istio.io/istio/security/pkg/pki/util.GenCSR`
=> Fuzzing: Add security fuzzer

pilot/pkg/networking/core/v1alpha3/envoyfilter/monitoring.go, pilot/pkg/xds/discovery.go
We did a trial run of these stats in dev clusters and this being a counter is getting incremented on every push and the skip counter is almost useless as it is being skipped on every listener/filter chain.
So I am proposing to change that stat to gauge and set only if it ever applied once so we can easily track filters that were never applied (which was our usecase)
=> change envoy filter metrics from counter to gauge

pilot/pkg/xds/endpoint_builder.go, pilot/pkg/xds/ep_filters.go
make use of `computeForEndpoint` calculated result instead of call mtlsDisabledByPeerAuthentication again
=> Optimize: reduce calling mtlsChecker.mtlsDisabledByPeerAuthentication

istio.deps, pkg/envoy/proxy.go, pkg/envoy/proxy_test.go, security/pkg/nodeagent/test/setup.go
Drop --bootstrap-version flag for envoy binary. Flag has been deprecated https://github.com/envoyproxy/envoy/pull/17724
- [ x ] Installation
- [ x ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> Drop --bootstrap-version flag

pilot/pkg/xds/simple.go
This is kind of clean up. Since `ServiceEntryStore` is already a registry, no need to convert it to simple registry.
=> Clean up for simple server

tests/fuzz/oss_fuzz_build.sh
Applies the sed command instead of just printing the result out.
=> Fuzzing: Add missing `-i` in sed command in oss-fuzz build script

pilot/pkg/serviceregistry/aggregate/controller.go
The aggregate controller performs a merge of service VIPs when it iterates across the service registries. This logic is protected by a mutex. However, we recently added the copying of `hostname` to this logic as well, which is not protected. This shouldn't be needed, however, since the first service should already have the correct hostname.
Fixes #35079
=> Fixing data race in aggregate controller

security/pkg/pki/util/verify_cert.go
Signed-off-by: TianTianBigWang <zilong.wang@daocloud.io>
Since the previous error has been captured, the use of err here may result in a nil pointer.
=> fix nil error return

pilot/pkg/xds/pushqueue.go, pilot/pkg/xds/pushqueue_test.go, pkg/queue/instance.go, releasenotes/notes/pq-memory-leak.yaml, tests/util/leak/check.go
Currently, the queue has a memory leak. This leads to retaining
Connection objects after the proxy has disconnected. This object
includes references to PushContext, gRPC rw buffers (100kb), and can
store the DiscoveryResp/DiscoveryRequest as well. Overall, this adds up
a LOT - in many cases memory usage over 2gb wasted.
https://github.com/grpc/grpc-go/issues/4758 discusses this a bit more in
depth.
The root cause is the queue using `slice[1:]`. While this moves the
slice, it the underlying array may still store a reference to the
`Connection` at (formerly) `slice[0]`. This will get freed only if the
slice is completely copied to a new array (during an append, for
example), allowing the underlying array to be freed.
Before (memory not freed after client disconnect):
After (memory freed …
=> Fix pushqueue memory leak

pkg/adsc/adsc.go
Because the adsc has default reconnect mechanism, so it is possible to fill the `errChan` channel , and will block the adsc reconnects to the MCP server.
=> Fix the adsc may be blocked by the errChan

pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, pilot/pkg/networking/core/v1alpha3/cluster_test.go, pilot/pkg/networking/core/v1alpha3/fake.go, pilot/pkg/networking/util/util.go
cluster.MaxRequestsPerConnection has been deprecated for long
=> make use of new CommonHttpProtocolOptions.MaxRequestsPerConnection

istioctl/cmd/testdata/vmconfig/simple/mesh.yaml.golden, istioctl/cmd/workload.go, istioctl/cmd/workload_test.go, tests/integration/pilot/revisions/revisions_test.go
If the revision is set, we try to use the same discovery address that we setup in /etc/hosts
fixes https://github.com/istio/istio/issues/34058
=> istioctl workload sets discovery address for revision

tests/integration/security/ca_custom_root/secure_naming_test.go, tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go, tests/integration/security/ca_custom_root/trust_domain_validation_test.go
These three tests, which fail in a multicluster topology, are also failing with a remoteistiod topology. Same errors as described in the open issues referenced in the TODO comments.
=> Skip security tests that fail in multicluter and external-controlplane topologies

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go
Fixes https://github.com/istio/istio/issues/32034
This is both an optimization and fix for ^.
Before, we iterated over all namespaces that had services and computed
sidecar scopes for them. This is inaccurate and inefficient: a namespace
may have 0 services (inaccurate), and it may have services but no
proxies (inefficient).
This changes it such that on each request, we lazy load the sidecar
scope for that namespace.
NOTE: this represents a fairly substantial change to push context in
that its not as much of a "snapshot" anymore. It still is deterministic
what the output is given a push version (ie computing this up front, or
lazy loaded will return the same result), but the actual PushContext
object is mutated. While I don't love this, I think its ok because its
an optimization matter …
=> Lazy-ily compute sidecar scope for namespaces without Sidecar

pilot/pkg/model/push_context.go, pilot/pkg/xds/bench_test.go, pilot/pkg/xds/monitoring.go
While this is a seemingly innocent code path, it shows up in pprof's a lot - like 5-10%+ of CPU and allocs.
```
name           old time/op    new time/op    delta
PushRequest-6    6.15ms ± 1%    5.42ms ± 8%  -11.87%  (p=0.002 n=6+6)
name           old alloc/op   new alloc/op   delta
PushRequest-6    4.24MB ± 0%    3.48MB ± 0%  -17.94%  (p=0.002 n=6+6)
name           old allocs/op  new allocs/op  delta
PushRequest-6     85.1k ± 0%     60.1k ± 0%  -29.39%  (p=0.000 n=5+6)
```
This will get faster with the fixes in https://github.com/census-instrumentation/opencensus-go/issues/1265 as well
=> Benchmark and optimize PushRequest

pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/listener_builder.go
Envoy 1.17 `listener: added the Listener.bind_to_port field.`
https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.17.0
=> make use of new Listener.bind_to_port

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/delta.go, pilot/pkg/xds/pushqueue.go
On a cluster with ~10k configs (svcs, eps, etc):
Before: `All caches have been synced up in 7.978471048s, marking server ready`
After: `All caches have been synced up in 2.101581551s, marking server ready`
Currently all usages already are safe, so mutation should not cause any issue.
This is so much faster mostly because ConfigUpdates; before we are allocating a ton of maps
=> perf: reuse PushRequest object during Merge

pkg/test/framework/components/echo/echoboot/echoboot.go, pkg/test/framework/resource/flags.go, pkg/test/framework/resource/settings.go, tests/integration/pilot/common/apps.go, tests/integration/pilot/original_src_addr_test.go
In some env, like GKE autopilot, TProxy mode cannot work (Echo cannot become ready) because NET_ADMIN is disallowed. This follows VM and Delta xDS to add a flag to skip TProxy echo set up and test.
=> Add flag to skip TProxy related parts in test.

cni/pkg/monitoring/monitoring.go
`SetupMonitoring` should return immediately when error occurred, otherwise we will use nil value In the following processing.
=> SetupMonitoring should return immediately when error occurred

pilot/pkg/xds/discovery.go
if `PILOT_ENABLE_EDS_DEBOUNCE` equals false , commitupdate should also be increased.
otherwise pilot server may not be ready.
``` go
func (s *DiscoveryServer) ConfigUpdate(req *model.PushRequest) {
inboundConfigUpdates.Increment()
s.InboundUpdates.Inc()
s.pushChannel <- req
}
```
During `ConfigUpdate` inboundUpdate++,then push model.request,
``` go
push := func(req *model.PushRequest, debouncedEvents int) {
pushFn(req)
updateSent.Add(int64(debouncedEvents))
freeCh <- struct{}{}
}
```
but when enableEDSDebounce, only do `pushFn`.  So InboundUpdates is greater than CommittedUpdates.
``` go
if !opts.enableEDSDebounce && !r.Full {
// trigger push now, just for EDS
go pushFn(r)
continue
}
```
**To help us figure out who should review this PR, please …
=> Fix eds debounce CommittedUpdates

pilot/pkg/secrets/kube/multicluster.go, pilot/pkg/secrets/kube/secrets.go, pilot/pkg/secrets/kube/secrets_test.go, pilot/pkg/secrets/model.go, pilot/pkg/xds/sds.go
Before:
```
failed to fetch key and certificate for kubernetes://sds-credential
```
After (various error states):
```
failed to fetch key and certificate for kubernetes://sds-credential: secret "sds-credential" not found
failed to fetch key and certificate for kubernetes://sds-credential: found keys "tls.crt" and "tls.key", but they were empty
failed to fetch key and certificate for kubernetes://sds-credential: found secret, but didn't have expected keys (cert and key) or (tls.crt and tls.key); found: tls.crt
```
=> Add error messages on failure to fetch SDS creds

security/pkg/stsservice/tokenmanager/sts_test.go
This was relying on real GCP metadata. Should be using all mock data for
tests
=> Fix tests so they can run off-GCP

cni/pkg/plugin/testdata/basic.txt.golden, cni/pkg/plugin/testdata/dns.txt.golden, cni/pkg/plugin/testdata/include-exclude-ip.txt.golden, cni/pkg/plugin/testdata/include-exclude-ports.txt.golden, cni/pkg/plugin/testdata/tproxy.txt.golden, tools/istio-iptables/pkg/builder/iptables_builder_impl.go, tools/istio-iptables/pkg/cmd/testdata/basic-exclude-nic.golden, tools/istio-iptables/pkg/cmd/testdata/dns-uid-gid.golden, tools/istio-iptables/pkg/cmd/testdata/empty.golden, tools/istio-iptables/pkg/cmd/testdata/inbound-ports-include.golden, tools/istio-iptables/pkg/cmd/testdata/inbound-ports-tproxy.golden, tools/istio-iptables/pkg/cmd/testdata/inbound-ports-wildcard-tproxy.golden, tools/istio-iptables/pkg/cmd/testdata/inbound-ports-wildcard.golden, tools/istio-iptables/pkg/cmd/testdata/ip-range.golden, tools/istio-iptables/pkg/cmd/testdata/ipnets-with-kube-virt-interfaces.golden, tools/istio-iptables/pkg/cmd/testdata/ipnets.golden, tools/istio-iptables/pkg/cmd/testdata/ipv6-dns-uid-gid.golden, tools/istio-iptables/pkg/cmd/testdata/ipv6-empty-inbound-ports.golden, tools/istio-iptables/pkg/cmd/testdata/ipv6-inbound-ports.golden, tools/istio-iptables/pkg/cmd/testdata/ipv6-ipnets.golden, tools/istio-iptables/pkg/cmd/testdata/ipv6-outbound-ports.golden, tools/istio-iptables/pkg/cmd/testdata/ipv6-uid-gid.golden, tools/istio-iptables/pkg/cmd/testdata/ipv6-virt-interfaces.golden, tools/istio-iptables/pkg/cmd/testdata/kube-virt-interfaces.golden, tools/istio-iptables/pkg/cmd/testdata/logging.golden, tools/istio-iptables/pkg/cmd/testdata/loopback-outbound-iprange.golden, tools/istio-iptables/pkg/cmd/testdata/outbound-ports-include.golden, tools/istio-iptables/pkg/cmd/testdata/tproxy.golden
We are already emiting the logs which has the command name as part of
it, so its a bit redundant to store the full comment in the kernel. This
has caused some compatibility issues with kernels not supporting
`comment` module
We never shipped this so its backwards compat
=> Remove `-m comment` from iptables output

pilot/pkg/xds/ads.go, releasenotes/notes/35293.yaml
When service entry and gateway are added at the same time, service entry is not sent. Regression from this https://github.com/istio/istio/commit/ec1766dd7e315b2e43bb5497e008a8cd36271a9c.
=> compute sidecar for gateway when service entry is added

pilot/pkg/leaderelection/leaderelection.go
This is only used in cases when pod name is not set, to help with
debugging. Typically this would happen in a local dev setting, but could
happen in external control plane.
=> Add Hostname to leader election name for improve visibility

istioctl/cmd/testdata/vmconfig/simple/mesh.yaml.golden, istioctl/cmd/testdata/vmconfig/simple/sidecar.env.golden, istioctl/cmd/workload.go, istioctl/cmd/workload_test.go, pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/components/istio/eastwest.go, pkg/test/framework/components/istio/operator.go, pkg/test/framework/components/namespace/kube.go, pkg/test/framework/components/namespace/namespace.go, pkg/test/framework/components/namespace/static.go, releasenotes/notes/35290.yaml, samples/multicluster/expose-istiod-rev.yaml, samples/multicluster/expose-istiod-rev.yaml.tmpl, tests/integration/pilot/revisions/revisions_test.go, tools/packaging/common/istio-start.sh
similar to #34060 – need to do more investigation on the safety and triple check the test does what I think it does 
* This should make `CA_ADDR`, `PILOT_ADDRESS` and `ISTIO_PILOT_PORT` vars still work in a backward compatible way, but avoid overriding with the default if the user didn't customize the envs. 
* The workload command now properly sets the port for the discovery address
* The workload command sets the CA_ADDR to match the discovery address (if rev is specified)
* The tests actually copy `sidecar.env` 
* The tests actually deploy a VM
* The test send traffic from the VM to make sure it connected to istiod properly
* The tests deploy a VirtualService pointing to the revisioned version of the eastwest gateway (this may need some cleanup to match the specific SNI)
=> allow discoveryAddress to be set via proxyConfig for VMs with revision

pkg/kube/portforwarder.go
there is error message showing as below when doing port forward in IPv6 only k8s cluster,
```
Error: failed to execute command on productpage-v1-6b746f74dc-rj7dn.default sidecar: failure allocating port: address x:x:x:x:x:x:x:x:0 too many colons in address
```
Should use `net.JoinHostPort` to allocate port which can dynamically support for both IPv4 and IPv6 format.
=> failure allocating port when doing port forward in IPv6 only k8s cluster

pkg/test/framework/components/istio/config.go, tests/integration/pilot/revisions/revisions_test.go
With changes for #35290 we now set the eastwest gateway to expose individual istiod revisions. 
This should allow us to easily test having multiple revisions per-cluster.
=> multicluster revisions test

Makefile.core.mk
This was broken by https://github.com/istio/istio/pull/34720 accidentally
=> Fix `BUILD_ALL=false` on linux

tools/istio-iptables/pkg/dependencies/implementation.go
Right now, we return `nil` when its not an xtables lock issue. This
swallows any other errors.
=> Properly return error when iptables command fails

pilot/pkg/model/service.go, pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go, pilot/pkg/serviceregistry/kube/controller/endpoints.go, pilot/pkg/serviceregistry/kube/controller/endpointslice.go, pilot/pkg/serviceregistry/kube/controller/serviceexportcache.go, pilot/pkg/serviceregistry/kube/controller/serviceexportcache_test.go, pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go, pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go, tests/integration/pilot/mcs/discoverability/discoverability_test.go
When receiving a `ServiceExport`, the `serviceExportCache` calls into the kube endpoint controller to build the endpoints. However, when in `EndpointSlice` mode, this simply returns the pre-built endpoints in an internal cache. This means that the endpoints will never get the updated `EndpointDiscoverabilityPolicy`, allowing them to be discovered across the mesh.
This PR allows the `serviceExportCache` to request a rebuild of the cache for the service.
Also does some other minor improvements around debuggability (mcsz), etc.
=> Fixing MCS for EndpointSlice mode

prow/integ-suite-kind.sh
The `iptables` command (workaround) isn't needed, but fails, when running the integration tests locally on a Mac:
```
build-tools:/work# ARTIFACTS=$PWD/artifacts ./prow/integ-suite-kind.sh --topology MULTICLUSTER --skip-build --skip-cleanup --topology-config prow/config/topology/external-istiod.json
+ iptables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
getsockopt failed strangely: Operation not permitted
```
This PR prevents the bash script from exiting in this case.
=> Ignore failing workaround iptables command

pilot/pkg/bootstrap/servicecontroller.go, pilot/pkg/model/controller.go, pilot/pkg/serviceregistry/aggregate/controller.go, pilot/pkg/serviceregistry/aggregate/controller_test.go, pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/fake.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go, pilot/pkg/serviceregistry/kube/controller/multicluster_test.go, pilot/pkg/serviceregistry/kube/controller/pod.go, pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go, pilot/pkg/serviceregistry/serviceregistry_test.go
Currently, the MCS `serviceImportCache` requires that the kube `Service` exist in each cluster containing a `ServiceImport` resource. This is an overly strict requirement and goes against the spirit of the MCS spec.
This PR modifies the `serviceImportCache` to use the merged, mesh-wide `Service` from the `aggregate.Controller` instead. This means that as long as the service exists somewhere in the mesh, it can be imported in any cluster and can generate the synthetic MCS service for the `clusterset.local` host.
=> Generate MCS service from merged Service

Makefile.core.mk
Seems like the build pipeline failed to create new base image `1.10-dev.10` but that `1.10-dev.11` ([build log](https://storage.googleapis.com/istio-prow/logs/build-release_release-builder_release-1.10_postsubmit/1442709735399755776/build-log.txt)) was manually created ~a month ago, so updating base to that image.
=> Bump 1.10 base image

pkg/config/schema/collections/collections.gen.go, pkg/config/schema/metadata.gen.go, pkg/config/schema/metadata.yaml
Split out of another PR. This is broken but doesn't impact anything since nothing uses it (yet).
=> Fix metadata with wrong plural type

pkg/test/framework/components/istio/operator.go
The integration test framework needs to cleanup primary clusters before remote clusters. Otherwise istiod will recreate
some of the resources (e.g., `istio-ca-root-cert`) that we delete on the remote cluster before it's deleted.
=> Cleanup primary clusters before remotes

pkg/test/framework/components/echo/common/envoy.go, pkg/test/framework/components/echo/flags.go, pkg/test/framework/components/echo/kube/instance.go, pkg/test/framework/components/echo/kube/workload.go, pkg/test/framework/components/istio/ingress.go, pkg/test/framework/components/istio/operator.go, pkg/test/kube/util.go, pkg/test/util/retry/retry.go, tests/integration/pilot/common/traffic.go
Right now every call has a 1s backoff. 99% of the time, the first call
fails because the config has *just* been sent and there is a 100ms
debounce time in Istiod.
This drops down the delay. At the same time, we make it respect the
existing callDelay flag, and switch some other slow usages over to using
a lower time but with exponential backoff. This allows fast cases to
finish quickly without overloading things.
=> Reduce delay on tf call, and introduce backoff

samples/bookinfo/src/ratings/ratings.js
If the mongo db was empty, the ratings service would throw the following error:
TypeError: Cannot read property 'rating' of undefined
at /opt/microservices/ratings.js:155:37
=> Handle empty ratings collection when using Mongo

pkg/test/echo/cmd/server/main.go, pkg/test/echo/common/model.go, pkg/test/echo/server/endpoint/http.go, pkg/test/echo/server/endpoint/instance.go, pkg/test/echo/server/instance.go, pkg/test/framework/components/echo/kube/deployment.go, tests/integration/security/ca_custom_root/main_test.go
Sad we have to resort to this but I don't see any other good options 
This is required for Go 1.17. They removed the ability to have unknown ALPN treated as HTTP 1 *and* h2 negotiation at the same time. For our tests, we rely on one or the other of these functionalities, so we can just make the test opt-in. Needing unknown ALPN is very rare (only when we are simulating Envoy mTLS via echo app) so its not a huge burden
=> Allow turning off ALPN in echo server

tools/istio-docker.mk
I don't fully understand how but this is somehow breaking our internal build. The problem is `DOCKER_BUILD_VARIANTS ?= ""` sets the variable to bash equivalent of `'""'` (ie length 2 double quotes, not empty string). We then call `buildx bake ""` which is broken.
I have no clue how it works in one place and not the other TBH. But might as well do it right; with this approach it works in both places
=> Fix default DOCKER_BUILD_VARIANTS

tests/integration/pilot/multicluster_test.go
Earlier PR skipped cluster local test in `pilot/mcs/discoverability`, need to also skip here in `pilot/multicluster_test.go`.
=> Skip TestClusterLocal on pre-1.11 versions

pilot/pkg/leaderelection/leaderelection.go, pilot/pkg/leaderelection/leaderelection_test.go, pkg/revisions/default_watcher.go, pkg/revisions/default_watcher_test.go
Makes it so that we wait for caches to sync before proceeding with leader election. This prevents a race condition where revision with name "" would steal the leader lock on startup
fixes #35765
=> Wait for cache sync before proceeding with leader election

tools/istio-docker.mk
`INCLUDE_UNTAGGED_DEFAULT` is not implemented for a `docker.save` and hence `default` needs to be added at  `DOCKER_BUILD_VARIANTS` but in this case duplicate `ISTIO_DOCKER_TAR` are created and `gzip` needs to force overwrite tars.
=> Force gzip to overwrite existing archives in docker.save target

pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
Fixing incorrectly matched filterchain if `lMatch.FilterChain==nil`.
This moves filtering unrelated to `lMatch.FilterChain` before the nil check.
Signed-off-by: Mandar U Jog <mjog@google.com>
In absence of this PR, If a patch has only listener match but no filterchain match, it is incorrectly applied since missing filterchain match-clause was treated as a positive match.
=> Fix filterchain match's incorrect early match

pkg/test/framework/components/echo/call.go, pkg/test/framework/components/istio/ingress.go
When using nodeport, we mutate the Calloptions port (a pointer). This
means on subsequent retries things get messed up.
Tested in https://github.com/istio/istio/pull/35354
=> Add DeepCopy to echo CallOptions

pkg/config/labels/instance.go, pkg/config/labels/instance_test.go
Signed-off-by: dddddai <dddwq@foxmail.com>
If there is a label whose value is `""`, `Instance.SubsetOf` will return true though the key does NOT exist in the other
It may lead to inconsistency when the label value is an empty string, so this PR fixes it
Fix #35722
=> `Instance.SubsetOf` should check if key exists

tests/integration/pilot/mcs/discoverability/discoverability_test.go
Might help with https://github.com/istio/istio/issues/34051
I think we just retry to much, exhausting all ephemeral ports...
Also make it so you can rerun the test for local dev
=> mcs test: backoff more aggresively

pkg/test/util/retry/retry.go
Currently we only backoff 2x, since we always use `base * 2` instead of
`previous * 2`. This leads to most calls occuring every 20ms for tests
not overriding defaults, which is a bit fast.
Might help with https://github.com/istio/istio/issues/34051, which is
caused by overloading
=> tf: fix backoff

pilot/pkg/features/pilot.go, releasenotes/notes/35883.yaml, tests/integration/iop-integration-test-defaults-with-quic.yaml, tests/integration/iop-integration-test-defaults.yaml
This has been enabled since January in integration tests, it should be proven stable.
=> enable multicluster workload entry by default

pilot/cmd/pilot-agent/options/agent.go
Currently its 100% broken. SupportsIPv6 ALWAYS returns false since we
never called DiscoverIPVersions. Even if we fix that, we still should
not use it since we need to be consistent with the code that selects
where Envoy admin server binds, which uses `network.IsIPv6Proxy`
=> ipv6: fix VM healthcheck ipv6 detection

pilot/pkg/features/pilot.go, releasenotes/notes/35883.yaml, releasenotes/notes/35884.yaml, tests/integration/iop-integration-test-defaults-with-quic.yaml, tests/integration/iop-integration-test-defaults.yaml
We've had this integration tested for some time, and it has been tried by [some users](https://istio.slack.com/archives/C01AT2S8B7B/p1630861283017700).
The only concern is users who relied on these being cluster-local, the release note partially covers that. Some of the docs for multi-cluster in 1.12 will show better mechanisms to do cluster-local settings on a per-service basis.
=> enable multicluster headless by default

pkg/istio-agent/agent.go
This function was called in 2 places so we got 2x logs which looked like
a bug. So just clean it up
=> Cleanup duplicate pilot SAN log

pkg/test/env/istio.go, tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go, tools/docker, tools/docker-builder/main.go, tools/docker-builder/types.go, tools/docker-copy.sh, tools/istio-docker.mk
This rewrites the amalgamation of make+bash that we use to build docker files today into a fairly simple go program. The bash and make combination is horrible to use - it has a bash HCL generation, and some extreme make complexity (example: `${ISTIO_DOCKER_TAR}/$(subst docker.,,$(TGT))$(call variant-tag,$(VARIANT)).tar $(HUB)/$(subst docker.,,$(TGT)):$(subst -$(DEFAULT_DISTRIBUTION),,$(TAG)-$(VARIANT)) && \`). This has caused a few issues:
* Code is hard to understand
* Code is even harder to change. I tried to make a simple change and it took all day, and popped up many new bugs. When we fix one bug, a new one pops up. This is directly related to the complexity of the code.
* Code is not optimal because its too painful to do the right thing. This leads to people like me having tons of …
=> docker: rewrite make+bash with a simple golang tool

samples/bookinfo/src/productpage/Dockerfile
Testing hadolint 2.7.0 and this change was identified.
```
./samples/bookinfo/src/productpage/Dockerfile:17 DL3045 warning: `COPY` to a relative destination without `WORKDIR` set.
./samples/bookinfo/src/productpage/Dockerfile:20 DL3045 warning: `COPY` to a relative destination without `WORKDIR` set.
```
=> Update to fix hadolint warning

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Otherwise we cannot use DNS resolution at all.
probably we should use `V4_PREFERRED` if it supports both but I was
pretty concerned by past attempts:
* https://github.com/istio/istio/pull/27296
* https://github.com/istio/istio/pull/26409
* https://github.com/istio/istio/pull/27306
Tested in https://github.com/istio/istio/pull/35354/files
=> Use v6 DNS resolution when we are on a ipv6 *only* proxy

pilot/pkg/networking/core/v1alpha3/accesslog.go
Configures access log formatter for REQ_WITHOUT_QUERY - Without this if user specifies it access log format, the listener will be rejected.
=> configure request without query access log formatter

pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/networking/core/v1alpha3/httproute_test.go, releasenotes/notes/vhost-name-generation.yaml
For example, a service `foo.bar.local` behaves incorrectly because we
incorrectly match the `.local` up with `.cluster.local`
Fixes https://github.com/istio/istio/issues/35676
=> Fix alt-host generation when hostname has a partial overlap with cluster domain

istioctl/pkg/tag/util.go
delete `GetValidatingWebhooksWithRevision` func
`GetValidatingWebhooksWithRevision` unused
NONE
=> Delete GetValidatingWebhooksWithRevision func

tools/docker
When DOCKER_V2_BUILDER=true, the build on arm64 would get an error:
./tools/docker: line 29: out/linux_amd64/docker-builder: cannot execute
binary file: Exec format error
which is due to lack of arch and os information in tools/docker when
building with common/scripts/gobuild.sh(so it would lead to an amd64
binary on arm64 platform).
Now we set the right OS and Arch to enable and fix the building both
on arm64 and amd64.
Signed-off-by: trevor.tao <trevor.tao@arm.com>
=> Enable/Fix multi-arch build for DOCKER_V2_BUILDER

galley/testdatasets/validation/dataset/networking-v1beta1-ProxyConfig-invalid.yaml, galley/testdatasets/validation/dataset/networking-v1beta1-ProxyConfig-valid.yaml, pilot/cmd/pilot-agent/config/config.go, pilot/pkg/config/kube/crdclient/gen/main.go, pilot/pkg/config/kube/crdclient/gen/types.go.tmpl, pilot/pkg/config/kube/crdclient/types.gen.go, pkg/config/mesh/mesh_test.go, pkg/config/schema/collections/collections.agent.gen.go, pkg/config/schema/collections/collections.gen.go, pkg/config/schema/gvk/resources.gen.go, pkg/config/schema/metadata.gen.go, pkg/config/schema/metadata.yaml, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, pkg/kube/inject/validate.go, pkg/webhooks/validation/server/server.go
Completes the proxy config revert, otherwise https://github.com/istio/api/pull/2147 can't be brought into release-1.12.
=> [release-1.12] Revert "Scaffolding for ProxyConfig implementation (#35602)"

pkg/test/echo/common/scheme/scheme.go, pkg/test/echo/server/forwarder/protocol.go, pkg/test/echo/server/forwarder/tls.go, pkg/test/framework/components/echo/call.go, pkg/test/framework/components/echo/common/call.go, tests/integration/pilot/common/routing.go, tests/integration/security/ca_custom_root/secure_naming_test.go, tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go, tests/integration/security/util/cert/cert.go
This allows tests to run in environments that do not have an openssl binary in the istio-proxy container. A new protocol is implemented for echo that basically does the same thing openssl did - connect to an endpoint and dump the tls handshake info.
=> Replace openssl with echo client

tests/integration/pilot/ingress_test.go
This is broken since we do the port -> nodeport translation twice in the
original code.
=> Fix TestGateway for TCP services

pilot/pkg/config/monitor/file_snapshot.go, pilot/pkg/config/monitor/monitor.go
This is useful when users are trying to aggregate multiple sources into
a single folder to watch all of them. For example, mount multiple
configmaps to a common parent directory.
=> Add support for recursive file watch to pilot

tests/integration/pilot/multicluster_test.go
After looking through the code a bit, I think the suggestion [here](https://github.com/istio/istio/issues/29335#issuecomment-950967806) is already possible due to:
https://github.com/istio/istio/blob/57b27bfceb507d56fa59b46917a44eb60524c3ae/pilot/pkg/xds/ads.go#L621
=> test cluster-local config using service subsets

pilot/pkg/serviceregistry/kube/controller/endpointslice.go, pilot/pkg/serviceregistry/serviceregistry_test.go
If I understand the comments in https://github.com/kubernetes/kubernetes/issues/105172 and #34995 , we should be able to safely ignore these EndpointSlices for now, so `PILOT_USE_ENDPOINT_SLICE` doesn't cause NACKs.
=> ignore FQDN endpointslice

tests/integration/pilot/common/apps.go
We do not clean up Service's, so cleaning up the ServiceEntry that is
for the same goals doesn't really make sense.
This only really impacts local debugging
=> tf: do not cleanup external ServiceEntry

pkg/test/echo/server/forwarder/dns.go, tests/integration/pilot/common/routing.go
Currently we silently ignore them. This makes things a bit more explicit
=> echo: return errors in dns

tools/docker-builder/main.go
Now for DOCKER_V2_BUILDER, it does not support the explicit building for
base images, for example, when building with
make dockerx.app_sidecar_base_ubuntu_xenial
it would show some error information for the wrong VM_IMAGE_NAME and
VM_IMAGE_VERSION, now we just fix it here.
And add other base images in the istio-docker.mk in the default list too.
Signed-off-by: trevor.tao <trevor.tao@arm.com>
=> Enable building for base images

tools/bug-report/pkg/common/common.go
See https://github.com/istio/istio/pull/26406, `/debug/cdsz` has been removed.
=> Fix cdsz endpoint not found

pilot/docker/Dockerfile.proxyv2
This builds on `static`+libc rather than `base` which is bloated for our
use case
Tested in https://github.com/istio/istio/pull/35354
=> Update proxyv2 distroless image to reduce surface

pkg/kube/portforwarder.go, pkg/test/framework/components/echo/staticvm/workload.go, pkg/test/framework/components/gcemetadata/kube.go, pkg/test/framework/components/istio/operator.go, pkg/test/framework/components/opentelemetry/kube.go, pkg/test/framework/components/stackdriver/kube.go, pkg/test/framework/components/zipkin/kube.go, pkg/test/framework/label/labels.go, samples/ratelimit/rate-limit-service.yaml, tests/integration/pilot/common/traffic.go, tests/integration/security/authorization_test.go, tests/integration/security/ca_custom_root/trust_domain_validation_test.go, tests/integration/security/jwt_test.go, tests/integration/telemetry/stackdriver/api/stackdriver_filter_test.go, tests/integration/telemetry/stackdriver/stackdriver_filter_test.go, tests/integration/telemetry/stackdriver/vm/main_test.go, tests/integration/telemetry/stats/prometheus/api/stats_wasm_filter_test.go, tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go, tests/integration/telemetry/stats/prometheus/nullvm/stats_filter_test.go, tests/integration/telemetry/stats/prometheus/wasm/stats_wasm_filter_test.go
Currently our IPv6 tests a tiny subset of our tests. I have recently
gotten it running on almost all of them, with the ones it doesn't work
with excluded. This testing is done in
https://github.com/istio/istio/pull/35354.
This doesn't yet expand our coverage, but we will in
https://github.com/istio/istio/issues/34387.
=> Tweaks to test code to support IPv6

tools/istio-docker.mk
Similar to https://github.com/istio/istio/pull/35761 if building non-dockerX targets with `DOCKER_BUILD_VARIANTS=debug distroless default` builder attempts to save `<REPO>:<TAG>-default` tar which doesn't exist
=> Fix docker.save tar targets

pilot/pkg/bootstrap/server.go, pilot/pkg/features/pilot.go, pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go, pkg/test/framework/components/istio/operator.go, releasenotes/notes/endpoint-slice.yaml, tests/integration/pilot/endpointslice/endpointslice_test.go
Not sure if we have other examples changing default behavior conditionally on the k8s version, this seems like it would wor.
=> use EndpointSlices by default in 1.21

tools/bug-report/pkg/bugreport/flags.go
To validate if the `--end-time` flag is set to be after the `--start-time` flag.
- [] Configuration Infrastructure
=> Add time flag validation to bug-report

RELEASE_BRANCHES.md
Set expectations for what can be merged in post-branch cutting (feature freeze, bug fixes, etc.) for a given Istio release.
The TOC asked for a PR to live closer to the code than a document on the Istio community drive (see https://docs.google.com/document/d/1Bns4gulQnM3sOcysxDTZvwboU0r_0TOPwqpgO314Vrc).
This document was started as a discussion in the T&R group and from previous release managers for expectations about PRs and the release management process.
=> Address branch cutting expectations

pkg/test/framework/components/echo/common/config.go, pkg/test/framework/components/echo/flags.go
In case of deployment of echo workload happens at the same time as cluster upgrade/repair events, it could take quite long before the echo app become schedulable. cc @ZhengzheYang
=> [echo] Make readiness check timeout configurable.

tools/docker
Fixes https://github.com/istio/istio/issues/36052
A prior PR, https://github.com/istio/istio/pull/35965, updated the `docker` script to use the TARGET_OS and TARGET_ARCH env vars, however these point to the host's OS/ARCH and not that running locally in the container (or locally if not in the container). This causes the `docker-builder` to be built as a darwin executable which isn't able to be run locally in the container. This PR changes the script to use LOCAL_OUT which is the architecture where we are currently running in and should be used for build related artifacts.
=> Fix `make docker` related target on MacOS

pilot/pkg/serviceregistry/util/label/label.go
By removing dependency on k8s core/v1, it reduces  size by 4M
=> reduce pilot-agent binary size

tests/fuzz/aggregate_controller_fuzzer.go, tests/fuzz/analyzer_fuzzer.go, tests/fuzz/ca_server_fuzzer.go, tests/fuzz/kube_crd_fuzzer.go, tests/fuzz/kube_gateway_controller_fuzzer.go, tests/fuzz/oss_fuzz_build.sh, tests/fuzz/pkg_util_fuzzer.go, tests/fuzz/pki_fuzzer.go, tests/fuzz/regression_test.go, tests/fuzz/status_fuzzer.go, tests/fuzz/workloadentry_controller_fuzzer.go
Adds more fuzzers to improve test coverage.
From a high level, more coverage is being added for the following areas of the code:
- Kube CRD
- Aggregate controller
- Kube gateway controller
- Status reconciler
- Workload entry controller
- CA Server
- Security utilities
- Security pki utilities
- Pilot status
This PR does not modify any production code. It only adds new fuzz tests.
The PR does remove the analyzer fuzzer from the regression tests since it broke it because of the recent major refactoring. I will take it upon myself to add it back but would prefer to do this in a separate PR, since I have some things to add to this fuzzer as well.
=> Fuzzing: Improve coverage

cni/pkg/taint/taint.go
Fix incorrect use of read-write lock in `cni/pkg/taint/taint.go`
=> Fix incorrect use of read-write lock

pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
Fixes https://github.com/istio/istio/issues/36126
Make timeout for expected case higher as we are hitting timeout in
extreme rare case. Make timeout for unexpected case (IE in success we
wait AT LEAST this long) to make test faster.
=> Tune TestNamespaceController timeouts

pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/metrics_no_statsd_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json, pkg/config/validation/validation.go, pkg/config/validation/virtualservice.go, tools/packaging/common/envoy_bootstrap.json
Currently, regex over 1024 program size will NACK envoy.
This introduces a new validation error if the program *length* exceeds
1024. Length is always less than program size. This ensures that anyone
this validation error fails for is already broken (by NACKs); we must
approximate as golang doesn't expose a program size.
In order to ensure that users with length<1024 but size>1024, we also
bump the max size enforced by envoy. This is set to a number 4x higher
than I was able to make any regex with length<1024, but with some margin
in case I missed some cases where there are larger sizes, while also not
being so high to allow absurdly high regexs in the worst case.
Overall, this should result in:
* All users with working config: continue to work
* Users with NACK and length<1024: will …
=> validation: add validation for re2 max regex size

releasenotes/notes/36044.yaml, tools/bug-report/pkg/bugreport/flags.go
`--duration` flag is never used in the `istioctl bug-report` command. Although it has been parsed to `since` parameter, the `since` parameter never gets called. This PR is to fix this issue, and correctly handle the error situation when users try to input `--duration` and `--start-time` flags at the same time.
=> Fix bug-report --duration flag never gets used

istioctl/cmd/describe.go, istioctl/cmd/kubeinject.go, pilot/pkg/security/authn/v1beta1/policy_applier.go, pilot/pkg/security/authn/v1beta1/policy_applier_test.go
This PR is to add PeerAuthentication debug info into `istioctl x describe pod` command. 
1. If client has access to root namespace, debug info will includes all applied PA to the specified pod the active mTLS mode.
2. If client doesn't have access to root namespace, debug info will only includes all applied PA in the workload's namespace.
Related design doc: [link](https://docs.google.com/document/d/1apxj7duekYneZL3BCczCfQM0cpTJARdsYswNC7EIG8c)
=> Istioctl x describe add PeerAuthentication debug info

go.mod
I thought about upgrading my go version to 1.17.
The description in go.mod seems to have changed a bit since 1.17.
https://golang.org/doc/go1.17#go-command
So I run `go mod tidy -go=1.17` for updating go.mod.
=> update go.mod for go1.17

pkg/config/validation/virtualservice.go
redundant login in  validateHTTPRouteMatchRequest . 
for name, header := range match.Headers {
if header == nil {
errs = appendErrors(errs, fmt.Errorf("header match %v cannot be null", name))
}
errs = appendErrors(errs, ValidateHTTPHeaderName(name))
errs = appendErrors(errs, validateStringMatchRegexp(header, "headers"))
}
=> remove redundant logic in validateHTTPRouteMatchRequest

pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/listener_test.go
Fault Injection should be added as the first filter https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/fault_filter.html?highlight=fault%20injection#configuration
This PR fixes that ordering
- [X ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> add fault filter to top of filters

pilot/pkg/networking/core/v1alpha3/tracing.go, pilot/pkg/networking/core/v1alpha3/tracing_test.go
work with @micalgenus
fix #35750
If jaeger is registered as zipkin for distributed tracking with telemetry api, the envoy setting is as follows.
```
...
extensionProviders:
- name: jaeger
zipkin:
port: 9411
service: jaeger-collector.istio-system.svc.cluster.local
...
```
```
"provider": {
"name": "jaeger",
"typed_config": {
"@type": "type.googleapis.com/envoy.config.trace.v3.ZipkinConfig",
"collector_cluster": "outbound|9411||jaeger-collector.istio-system.svc.cluster.local",
"collector_endpoint": "/api/v2/spans",
"trace_id_128bit": true,
"shared_span_context": false,
"collector_endpoint_version": "HTTP_JSON"
}
}
```
The mesh sends an http request as below for distributed tracking records.
```
POST /api/v2/spans HTTP/1.1
host: …
```
=> Add host header into ZipkinConfig for jaeger when using telemetry api 

tools/bug-report/pkg/bugreport/bugreport.go, tools/bug-report/pkg/content/content.go
Currently the `istioctl bug-report` timeout only works for the processes without the analysis process. The analysis process has a fixed timeout 5mins. This PR is to fix it by changing the default 5mins to the time left after doing other processes.
=> Fix bug-report timeout is not honored

tools/certs/Makefile.k8s.mk
There was an issue with the Makefile for the k8s cert generations using an already deployed CA cert flow. It had an invalid target location that was not changed from the self-signed flow. It was changed to use the proper root certificate pulled from the cluster.
=> Fixing invalid target for  k8s cert generation makefile

pilot/pkg/features/pilot.go, pkg/kube/multicluster/secretcontroller.go, pkg/kube/multicluster/secretcontroller_test.go, releasenotes/notes/multicuster-secret-auth.yaml
Cherrypick https://github.com/istio/istio/pull/36307
Custom 1.12-only parts are in a split commit.
=> 1.12: multicluster: add allowlist for kubeconfig auth methods

CODEOWNERS
Rationale:
* Eric is on TOC and T&R. Top level primarily deals with these areas
* Active PR reviewer
* Currently we have some bottlenecks in the owners reviews
* Maintain more company distribution
=> Add ericvn to top level OWNERS

go.mod, go.sum
This is not actually used, just a 100 step removed indirect dependency
that upstreams are not accepting fixes to remove. So we can just
explicitly drop it.
=> Remove dependency on k8s.io/kubernetes

pkg/config/analysis/analyzers/webhook/webhook.go
Can only do forloop when `webhook.NamespaceSelector` is not nil.
=> Fix analysis nil pointer panic error

tests/fuzz/crd_roundtrip_fuzzer.go, tests/fuzz/oss_fuzz_build.sh, tests/fuzz/regression_test.go
Adds 1 fuzzer.
The crd roundtrip fuzzer is a slightly reduced version of this roundtrip fuzzer. How it has been reduced:
The fuzzer will not check if deep copying is altering the object. The reason here is that I have simply not found an good way to ignore the `XXX_` fields.
The test for the internal and external types are removed with the expectation that it will be added later.
The reason for adding a new version of this fuzzer is that the one in this PR will be able to run continuously through OSS-fuzz.
=> Fuzzing: Add CRD roundtrip fuzzer

pilot/pkg/networking/core/v1alpha3/accesslog_test.go, pilot/pkg/networking/core/v1alpha3/listener_builder.go, pilot/test/xdstest/extract.go
Fixes https://github.com/istio/istio/issues/35778
```
name                                             old time/op        new time/op        delta
ListenerGeneration/gateways-6                          17.3ms ± 3%        17.1ms ± 3%    ~     (p=0.222 n=5+5)
ListenerGeneration/gateways-shared-6                   39.1µs ± 5%        38.6µs ± 2%    ~     (p=0.548 n=5+5)
ListenerGeneration/empty-6                             1.45ms ± 2%        1.46ms ± 2%    ~     (p=0.421 n=5+5)
ListenerGeneration/tls-6                               1.40ms ± 1%        1.41ms ± 1%    ~     (p=0.841 n=5+5)
ListenerGeneration/telemetry-6                         1.69ms ± 1%        1.71ms ± 1%    ~     (p=0.151 n=5+5)
ListenerGeneration/telemetry-api-6                     1.52ms ± 1%        1.61ms ± 2%  +5.84% …
```
=> Fix patching virtualOutbound-blackhole

pilot/pkg/bootstrap/certcontroller.go, pilot/pkg/bootstrap/istio_ca.go, pilot/pkg/bootstrap/server.go, pkg/config/constants/constants.go, pkg/test/csrctrl/controllers/csr_controller.go, pkg/test/csrctrl/controllers/start_csrctrl.go, pkg/test/csrctrl/signer/signer.go, security/pkg/pki/ca/ca.go, security/pkg/pki/ca/ca_test.go, security/pkg/pki/ca/mock/fakeca.go, security/pkg/pki/ra/common.go, security/pkg/pki/ra/k8s_ra.go, security/pkg/pki/ra/k8s_ra_test.go, security/pkg/pki/util/verify_cert.go, security/pkg/server/ca/server.go, tests/integration/security/external_ca/main_test.go
- do not create istio ca if `PILOT-CERT-PROVIDER` is `k8s.io/**` and `EXTERNAL_CA` is `ISTIOD_RA_KUBERNETES_API`
- Use root certs specified in meshconfig for workloads and istiod
- validate the root cert for signed cert from cert-chain against root cert specified in meshconfig
=> support root cert specified in mesh config

pkg/config/analysis/analyzers/util/config.go, tools/bug-report/pkg/bugreport/bugreport.go, tools/bug-report/pkg/cluster/cluster.go, tools/bug-report/pkg/cluster/cluster_test.go, tools/bug-report/pkg/config/config.go
Fixed logic bug in --include option for issue#36317.
This issue relates to that golang map is nondeterministic as @howardjohn mentioned in issue #36317. And the root cause is really that wrong flag setting for label and annotation maps. 
Moreover, I paste the different below:
```
@@ -124,13 +124,12 @@ func shouldSkip(deployment string, config *config2.BugReportConfig, pod *corev1.
}
if len(ild.Labels) > 0 {
-                               isLabelsMatch := false
+                               isLabelsMatch := true
for kLabel, vLable := range ild.Labels {
if evLable, exists := pod.Labels[kLabel]; exists {
if vLable != evLable {
isLabelsMatch = false
-                                               } else {
- …
```
=> fixed logic bug in --include option for issue#36317

Makefile.core.mk, tools/istio-docker.mk
Current USE_LOCAL_PROXY option does not work. This change removes existing options, and rework it to replace envoy binary at docker build time.
=> Update build with local envoy

pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/store.go, pilot/pkg/serviceregistry/serviceentry/store_test.go
These two sorts are not needed as we sort all service before processing in push_context
=> remove unnecessary sort

pilot/pkg/networking/core/v1alpha3/accesslog_test.go, pilot/pkg/networking/core/v1alpha3/listener_builder.go, pilot/test/xdstest/extract.go, releasenotes/notes/envoyfilter-patch-duplicate.yaml
* Fix patching virtualOutbound-blackhole
Fixes https://github.com/istio/istio/issues/35778
```
name                                             old time/op        new time/op        delta
ListenerGeneration/gateways-6                          17.3ms ± 3%        17.1ms ± 3%    ~     (p=0.222 n=5+5)
ListenerGeneration/gateways-shared-6                   39.1µs ± 5%        38.6µs ± 2%    ~     (p=0.548 n=5+5)
ListenerGeneration/empty-6                             1.45ms ± 2%        1.46ms ± 2%    ~     (p=0.421 n=5+5)
ListenerGeneration/tls-6                               1.40ms ± 1%        1.41ms ± 1%    ~     (p=0.841 n=5+5)
ListenerGeneration/telemetry-6                         1.69ms ± 1%        1.71ms ± 1%    ~     (p=0.151 n=5+5)
ListenerGeneration/telemetry-api-6 …
```
=> Fix patching virtualOutbound-blackhole (#36329)

pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/store.go, pilot/pkg/serviceregistry/serviceentry/store_test.go
Reverts istio/istio#36382
This broke a bunch of tests. Some were obvious like https://github.com/istio/istio/pull/36388 but for the NDS I am not sure. May be more complex
=> Revert "remove unnecessary sort"

pilot/cmd/pilot-agent/status/server.go
This fixes an issue where a blank Content-Type header would
be returned in cases where application metrics were disabled 
as would be the case pilot-agent is running as a gateway.
This addresses https://github.com/istio/istio/issues/3633
=> Specify a default metrics format

pilot/pkg/networking/core/v1alpha3/accesslog_test.go, pilot/pkg/networking/core/v1alpha3/listener_builder.go, pilot/test/xdstest/extract.go, releasenotes/notes/envoyfilter-patch-duplicate.yaml
* Fix patching virtualOutbound-blackhole (#36329)
* Fix patching virtualOutbound-blackhole
Fixes https://github.com/istio/istio/issues/36391
Fixes https://github.com/istio/istio/issues/35778
```
name                                             old time/op        new time/op        delta
ListenerGeneration/gateways-6                          17.3ms ± 3%        17.1ms ± 3%    ~     (p=0.222 n=5+5)
ListenerGeneration/gateways-shared-6                   39.1µs ± 5%        38.6µs ± 2%    ~     (p=0.548 n=5+5)
ListenerGeneration/empty-6                             1.45ms ± 2%        1.46ms ± 2%    ~     (p=0.421 n=5+5)
ListenerGeneration/tls-6                               1.40ms ± 1%        1.41ms ± 1%    ~     (p=0.841 n=5+5)
ListenerGeneration/telemetry-6                         1.69ms ± 1% …
```
=> 1.11 Fix patching virtualOutbound-blackhole (#36329) (#36366)

tests/fuzz/networking_core_v1alpha3_fuzzer.go
Use the `utils.Noptester{}` instead of `&testing.T{}` in `InternalFuzzbuildSidecarOutboundListeners`
=> Fuzzing: Use NopTester

tools/bug-report/pkg/bugreport/bugreport.go
After #36356 got merged, when executing `istioctl bug-report`, there will always be one line printed at the end of the bug-report like:
```
xxxxxxxxxxxx
Done.
Timeout when get cluster resources, please using --include or --exclude to filter
```
Added a condition check to prevent it always being printed.
Also, the cancel function should not use the fixed 30min timeout. Instead, it should use the flag value `--timeout` user passed in.
=> Fix bug-report always prints timeout, and has a fixed context cancel time

pilot/cmd/pilot-agent/status/server.go, pilot/cmd/pilot-agent/status/server_test.go, releasenotes/notes/agent-probe-keepalives.yaml
Fixes https://github.com/istio/istio/issues/36390
This mirrors Kubernetes behavior
=> Disable connection re-use for health probes

tests/fuzz/misc_fuzzers.go, tests/fuzz/oss_fuzz_build.sh, tests/fuzz/regression_test.go
This PR provides 2 fixes:
1)
The `FuzzNewControlplane` runs into a nil-deref (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37993&q=istio&can=1).
The crash occurs on [this line](https://github.com/istio/istio/blob/master/operator/pkg/component/component.go#L161) in case `opts.Translator.ComponentMaps[name.PilotComponentName]`  does not exist in the map. It looks like this will never happen in the wild, however, so the fuzzer gets adjusted in this PR to always include that.
2)
Remove the `FuzzVerify` fuzzer. The `StatusVerifier` is missing a client which I don't see an trivial fix for at this moment, so I'd rather just delete and add later when fixed.
=> Fuzzing: Refactor misc fuzzers

pilot/pkg/features/pilot.go, pkg/kube/secretcontroller/secretcontroller.go, pkg/kube/secretcontroller/secretcontroller_test.go, releasenotes/notes/multicuster-secret-auth.yaml
* multicluster: add allowlist for kubeconfig auth methods (#36307)
* multicluster: add allowlist for kubeconfig auth methods
* typo
(cherry picked from commit fa9c7da220190a896992c1aa1cdb1f5481603c99)
* 1.12 tweaks
(cherry picked from commit e3c1f50219d4bde6829245968c36c99d3cbb0c12)
Fixes https://github.com/istio/istio/issues/36421
=> 1.11: multicluster: add allowlist for kubeconfig auth methods (#36316)

pkg/kube/inject/inject.go, pkg/kube/inject/inject_test.go, pkg/kube/inject/testdata/inject/hello.yaml.proxyImageName.injected
- `imageName` is hardcoded to "proxyv2" as introduced in this PR -> https://github.com/istio/istio/pull/35996
- This PR fixes the bug and derives `imageName` from `values.global.proxy.image` if it exist
- Added unit test to verify the same
=> Derive proxy image from values.global if it exist

pkg/bootstrap/platform/aws.go, pkg/bootstrap/platform/discovery.go, pkg/bootstrap/platform/platform.go
This PR
- Adds env var support for specifying platform. So if user specifies a platform which he knows what platform is better, we do not have to discover and rely on user given value.
- Fixes AWS detection and treats permission error as AWS so that we can use metadata client rather than treating it as non AWS. This is needed for proxy running as  non root.
Fixes https://github.com/istio/istio/issues/32880
=> add env var for platform and fix aws

pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/controller_test.go
There is no need to update eds cache on service add/update if `K8S_SELECT_WORKLOAD_ENTRIES` is disabled, as the cache would be updated by k8s endpoints events
=> Update eds cache on service add/update only if `K8S_SELECT_WORKLOAD_ENTRIES` is enabled

pilot/pkg/xds/delta.go
=> > Fix: error's params value is no corresponding

pilot/pkg/model/service.go, pilot/pkg/serviceregistry/serviceentry/conversion.go, pilot/pkg/serviceregistry/serviceentry/conversion_test.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
Fix https://github.com/istio/istio/issues/36468
For a workload entry, it won't be added to workload instances if address is not IP, which will cause it not being selected if a ServiceEntry being added later. This change will add WorkloadEntry with host and UDS address to workload instances, and mark it explicitly only selectable by ServiceEntry.
=> Fix ServiceEntry selecting WorkloadEntry with host & UDS address.

pkg/config/validation/validation.go, pkg/config/validation/validation_test.go
config locality loadbalance of failover always config invalid config like: region1/zone1
should add validate notes with locality failover 
=> Validate locality lb setting: failover only specify region

pkg/istio-agent/agent.go
The channel used with signal.Notify should be buffered.
=> Use buffered channel with signal.Notify

tools/bug-report/pkg/bugreport/bugreport.go, tools/bug-report/pkg/config/config.go, tools/bug-report/pkg/config/config_test.go
Signed-off-by: dddddai <dddwq@foxmail.com>
bug-report `--include|--exclude` params order seems incorrect, which may result in parse error
The correct order should be: namespaces/deployments/pods/labels/annotations/**containers**
Please refer to:
https://github.com/istio/istio/blob/03dff9ab756a3058145349d5c52659a3b69bb6b0/tools/bug-report/pkg/config/config.go#L28-L31
https://github.com/istio/istio/blob/03dff9ab756a3058145349d5c52659a3b69bb6b0/tools/bug-report/pkg/config/config.go#L213-L217
=> Correct bug-report `--include|--exclude` params order

pilot/pkg/config/kube/crd/conversion.go, pilot/pkg/config/kube/crd/conversion_test.go, pilot/pkg/config/monitor/file_snapshot_test.go, pilot/pkg/config/monitor/monitor_test.go, pkg/config/model.go, pkg/config/model_test.go
When DeepCopy is called on objects that have gone through this conversion, they may panic as DeepCopy doesn't handle non-pointers, and the conversion logic has Status as a non-pointer.
This PR does two things:
* Make Status a pointer, which I think it should be since we are expected to always have pointers for protos. golang/protobuf makes this requirement more explicit which we will likely move to soon anyways
* Makes DeepCopy robust to non-pointer types and adds a bunch of tets.
=> Fix panic when passing empty status field

pilot/pkg/serviceregistry/kube/controller/endpointslice.go, pilot/pkg/serviceregistry/kube/controller/endpointslice_test.go
If an endpoint was deleted or the endpoint key was updated (e.g. `ServicePortName` changed), then the old endpoint would always remain in `endpointByKey` and never get freed
You can reproduce it with [this test](https://github.com/dddddai/istio/blob/memory-leak/pilot/pkg/serviceregistry/kube/controller/endpointslice_test.go#L125-L154)
So this pr drops `endpointByKey` to fix the problem
=> Fix endpoint slice cache memory leak

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, releasenotes/notes/36499.yaml
fix #36499 
currently mesh config tcp keepalive is ignored if there is no destination rule for a cluster.
=> Fix mesh tcp keepalive setting.

pilot/pkg/networking/core/v1alpha3/fake.go, pilot/pkg/serviceregistry/kube/controller/controller_test.go, pilot/pkg/serviceregistry/kube/controller/fake.go, pilot/pkg/xds/fake.go
It seems we're calling the kubecontrollers `Run` method 2x  in our tests.
=> configgentest: avoid running kubecontroller 2x

cni/test/install_cni.go
Example failure: https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/36564/unit-tests_istio/1472733363956617216/build-log.txt
=> Deflake CNI TestInstall by prolonging timeout.

pilot/pkg/bootstrap/istio_ca.go
Otherwise istiod pod will spam with file watch error:
```
2021-12-20T00:52:36.229935Z     info   Failed to catch events on cacerts files
2021-12-20T00:52:36.229938Z     info   Failed to catch events on cacerts files
2021-12-20T00:52:36.229942Z     info   Failed to catch events on cacerts files
2021-12-20T00:52:36.229946Z     info   Failed to catch events on cacerts files
2021-12-20T00:52:36.229950Z     info   Failed to catch events on cacerts files
2021-12-20T00:52:36.229954Z     info   Failed to catch events on cacerts files
2021-12-20T00:52:36.229957Z     info   Failed to catch events on cacerts files
```
=> Stop plugin certs watch when server shuts down.

pilot/pkg/model/push_context.go, pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/networking/core/v1alpha3/route/route_cache.go, pilot/pkg/networking/core/v1alpha3/route/route_cache_test.go, releasenotes/notes/refresh-rds-cache.yaml
The root cause is that the rds cache is not cleared when delegate virtual services were updated
This pr adds delegate virtual services to dependent configs of the rds cache entry, so that we can clear the cache when delegate virtual services are updated
Fix #36525
=> Bugfix: changes in delegate virtual service do not take effect

tools/bug-report/pkg/cluster/cluster.go, tools/bug-report/pkg/cluster/cluster_test.go
From the bug-report help command:
```
istioctl bug-report -h
bug-report selectively captures cluster information and logs into an archive to help diagnose problems.
Proxy logs can be filtered using:
--include|--exclude ns1,ns2.../dep1,dep2.../pod1,pod2.../cntr1,cntr.../lbl1=val1,lbl2=val2.../ann1=val1,ann2=val2...
where ns=namespace, dep=deployment, cntr=container, lbl=label, ann=annotation
The filter spec is interpreted as 'must be in (ns1 OR ns2) AND (dep1 OR dep2) AND (cntr1 OR cntr2)...'
```
Labels and annotations should be matched with `OR` condition. If the pod has one of the label satisfied in the `--include`, and no label matched in the `--exclude`, it should not be skipped.
=> Fix bug-report label and anno match

pilot/pkg/model/context.go, pilot/pkg/xds/delta.go
This is a minor improvement, instead of generating all watched resources, it only generates the new subscribed ones.
=> Refactor deleta xds subscribed resource names handling

pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/filter/discoverynamespaces.go
Before sync Services,pods,endpoints, discoveryNamespacesFilter.discoveryNamespaces should be updated first. Otherwise 
if we have many namespaces,some resources may be ignored when namespace have not been inserted into discoveryNamespacesFilter.discoveryNamespaces.
=> During SyncAll(), do syncDiscoveryNamespaces before sync pods,services,endpoints

releasenotes/notes/36566.yaml, tools/istio-iptables/pkg/capture/run.go, tools/istio-iptables/pkg/capture/run_test.go, tools/istio-iptables/pkg/capture/testdata/drop-invalid.golden, tools/istio-iptables/pkg/cmd/root.go, tools/istio-iptables/pkg/config/config.go, tools/istio-iptables/pkg/constants/constants.go
Please provide a description of this PR:
This is to fix bug #36489
Similar upstream issue in k8s https://kubernetes.io/blog/2019/03/29/kube-proxy-subtleties-debugging-an-intermittent-connection-reset/
We find the root cause that sidecar will intermittent reset the connection to ingress gateway during high throughput request(like upload large files 300MB) and the root cause is that there are some out of order packet comes to backend application directly without being DNAT by iptables, so the application reset it directly.
Here is the overflow:
- [ x] Networking
- [ x] Performance and Scalability
=> Drop packets in INVALID state to avoid intermittent connection reset from sidecar

pilot/pkg/xds/endpoint_builder.go
It should improve performance when multiple goroutines are generating eds resource
=> Use read lock when building endpoints from shards

pilot/pkg/serviceregistry/kube/controller/endpointslice.go, pilot/pkg/serviceregistry/kube/controller/endpointslice_test.go, releasenotes/notes/36510.yaml
Fix #36510.
When an endpoint slice gets removed, the corresponding service could also be removed, and query service registry for the service for that service would not return anything and some stale endpoint will be kept in the cache. This change make removal logic go through all possible host names for a slice removal.
=> Only get hostnames at endpoint removal.

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
If a workload was deleted, it would still remain in `serviceInstances.instancesBySE`
It does leak memory when users enable `ServiceEntrySelectPods`(which is enabled by default) and rely on it
You can reproduce it with [the test](https://github.com/dddddai/istio/blob/aca3a467528e02a1099235652d46cc4a2307d5c7/pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go#L984) in this pr
=> Fix service entry instances store memory leak

pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
No functional change. Just refactors merge transport logic to simplify if conditions and also when the cluster does not have transport socket avoids proto.Merge call.
=> refactor transport socket merge logic

pilot/pkg/networking/grpcgen/grpcecho_test.go, pkg/test/echo/common/model.go, pkg/test/echo/server/endpoint/grpc.go
Currently these block for 10s each because the readiness probe is not
valid. This probe has a 10s timeout.
Even with this running multiple tests back-to-back adds a 1s delay where
it fails the first connection with a 1s timeout then tries again. I
don't know why - might be a real bug.
=> Speed up grpc tests

pilot/pkg/config/kube/gateway/conditions.go, pilot/pkg/config/kube/gateway/conversion.go, pilot/pkg/config/kube/gateway/deploymentcontroller.go, pilot/pkg/model/kstatus/helper.go
Two bugs:
* `setOnce` was supposed to only set status once. The problem is the
status is always set by Kubernetes by default due to CRD defaulting.
Handle that using the special NotReconciled status reason
* GatewayClass only looks at the *name*, not the *controller*. Update
this to use the same (correct) logic the main code uses.
We definitely need more test coverage here. I am looking into how we can get
defaults for the first case, for the latter we just need more time.
Thanks @robscott for finding these
=> gateway: fix bug with managed gateway status and class

cni/pkg/plugin/iptables.go, cni/pkg/plugin/plugin_dryrun_test.go, cni/pkg/plugin/redirect.go, cni/pkg/plugin/testdata/invalid-drop.txt.golden, releasenotes/notes/36566.yaml, tools/istio-iptables/pkg/capture/run.go, tools/istio-iptables/pkg/cmd/root.go
This is related with https://github.com/istio/istio/pull/36566 which introduced a flag `ISTIO_META_INVALID_DROP` to enable the invalid drop iptables rule while there was a bug that this flag won't be passed from Pod environment variable to istio CNI.
**Steps to reproduce the bug:**
1. Install istio with cni and deploy the istio-cni DaemonSet with the cherry-picked fix https://github.com/istio/istio/pull/36566
2. Config the ISTIO_META_INVALID_DROP into proxyMetaData :
```
mesh: |-
accessLogEncoding: JSON
accessLogFile: /var/log/proxy/access.log
defaultConfig:
concurrency: 40
discoveryAddress: istiod.istio-pre-production.svc.87.tess.io:15012
proxyMetadata:
ISTIO_META_DNS_AUTO_ALLOCATE: "true"
ISTIO_META_DNS_CAPTURE: "true" …
```
=> Added flag to enable capture of invalid drop into CNI

pilot/cmd/pilot-agent/status/server.go, pilot/cmd/pilot-agent/status/server_test.go, pkg/kube/apimirror/probe.go, pkg/kube/inject/app_probe.go, pkg/kube/inject/app_probe_test.go, pkg/kube/inject/webhook.go, pkg/test/echo/server/endpoint/grpc.go, pkg/test/framework/components/echo/config.go, pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/features/features.yaml, prow/config/mixedlb-service.yaml, releasenotes/notes/grpc-probe.yaml, tests/integration/pilot/grpc_probe_test.go
Support rewriting gRPC probes for Kubernetes v1.23
Fix #36314
I'm not very familiar with the integration test, but I've tested it in my local environment, and here's the result:
```sh
kubectl apply -f - <<EOF
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
name: "default"
namespace: "istio-system"
spec:
mtls:
mode: STRICT
EOF
```
Before rewriting([an example in k8s doc](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe "example in k8s doc")):
```yaml
apiVersion: v1
kind: Pod
metadata:
name: etcd-with-grpc
spec:
containers:
- name: etcd
image: k8s.gcr.io/etcd:3.5.1-0
command: [ "/usr/local/bin/etcd", "--data-dir",  "/var/lib/etcd", …
```
=> Support rewriting gRPC probes

pilot/cmd/pilot-agent/status/server.go, pilot/cmd/pilot-agent/status/server_test.go
We should not use `net.JoinHostPort` to build destination addr, otherwise there would be 2 brackets since the `appProbersDestination` has already been wrapped with "[]"
https://github.com/istio/istio/blob/7c6403332f5044f78d8f541ce983066c8357bd90/pilot/cmd/pilot-agent/status/server.go#L186
https://github.com/istio/istio/blob/7c6403332f5044f78d8f541ce983066c8357bd90/pilot/cmd/pilot-agent/status/server.go#L841-L851
Fix [the failing test](https://prow.istio.io/view/gs/istio-prow/logs/integ-ipv6-k8s-tests_istio_postsubmit/1479643573191184384)
=> Fix: grpc probe is not working with ipv6

pilot/pkg/model/telemetry_test.go, pilot/pkg/networking/core/v1alpha3/tracing.go
The Telemetry API documents that the default value for `randomSamplingPercentage` is `0.0`. This change will allow the control plane to respect that documentation (and user intent).
With this PR, Telemetry API users will no longer fallback to pilot environment variables, etc., when the value is not specified.
Related issue: https://github.com/istio/istio/issues/36750
=> tracing: allow specification of no sampling with reporting via Telemetry API

pilot/pkg/model/telemetry.go, pilot/pkg/model/telemetry_test.go
Stackdriver extension support for CEL filters (part of the Telemetry API) was added in https://github.com/istio/proxy/pull/3630. This PR adds configuration support for the extension in the control plan. 
This PR cannot be completed and merged until https://github.com/istio/api/pull/2206 has been merged.
=> telemetry api: add support for stackdriver CEL filtering in pilot

cni/pkg/install/cniconfig.go
Context: https://github.com/istio/istio/issues/36821
Pod removal is stuck with network plugin cannot find error. This suggests that the cni config file has istio-cni configure, but the istio-cni binary does not present. Based on the logic, this can only happen if cni config file update errors out after updating the config file. This change makes those error returns also return config file path, which will go through the final clean up code path.
=> [CNI] Returns config file path for clean up even cni config write errors out.

pilot/pkg/serviceregistry/serviceentry/conversion.go, pilot/pkg/serviceregistry/serviceentry/conversion_test.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go, pilot/pkg/serviceregistry/serviceentry/store.go
Auto allocate IPs during store update to avoid DeepCopy in Services() call as Services() is frequently used.
=> auto allocate ip while updating the store

pkg/adsc/adsc.go, pkg/config/mesh/mesh.go
in the todo list
we shoud replace cluster.local with  constant DefaultKubernetesDomain to avoid if it changed
=> replace explicit usages of cluster.local with this constant

common-protos/google/api/auth.proto, pilot/pkg/model/jwks_resolver.go, releasenotes/notes/35723.yaml
* Fixes #35663 
* Limits log output to 100 bytes of the first line of response body to reduce log verbosity.
* Refined take on https://github.com/istio/istio/pull/35723
=> JWKS: No longer print entire response body on error

pkg/dns/client/dns.go, pkg/dns/client/dns_test.go
If the hostname ends with a period, agent not append a period.
Fixes #36885
=> fix: when service entry's host has tailing period, smart dns can not resolve it

pilot/pkg/config/kube/ingress/conversion.go, pilot/pkg/config/kube/ingress/conversion_test.go, pilot/pkg/config/kube/ingress/testdata/simple.yaml.golden, pilot/pkg/config/kube/ingressv1/conversion.go, pilot/pkg/config/kube/ingressv1/conversion_test.go, pilot/pkg/config/kube/ingressv1/testdata/simple.yaml.golden, pilot/pkg/features/pilot.go, releasenotes/notes/ingress-routes.yaml
Sort generated vs routes to meet ingress route precedence requirements, please refer to https://kubernetes.io/docs/concepts/services-networking/ingress/#multiple-matches
> In some cases, multiple paths within an Ingress will match a request. In those cases **precedence will be given first to the longest matching path. If two paths are still equally matched, precedence will be given to paths with an exact path type over prefix path type.**
Fixes #35033
=> Correct route precedence logic for k8s ingress

pilot/pkg/networking/core/v1alpha3/listener_builder.go, pilot/pkg/networking/core/v1alpha3/listener_builder_test.go, releasenotes/notes/36912.yaml
Quick fix for mtls check while building tls listener context for sidecar proxy. Related to this PR comment
https://github.com/istio/istio/pull/36210#discussion_r784420273 
- [ x] Networking
=> fixed the mtls check for tls on sidecar

istioctl/cmd/proxyconfig.go, istioctl/cmd/root.go, releasenotes/notes/istioctl-proxy-config-stats.yaml
Adds a stats command to istioctl proxy-config to grab envoy stats `http://localhost:15000/stats`
Example output
```txt
istioctl proxy-config stats --namespace ns-1 backend-00001-deployment-574bd5b4fd-97xtw
cluster_manager.cds.version_text: "2021-11-30T18:41:37Z/56"
listener_manager.lds.version_text: "2021-11-30T18:41:37Z/56"
cluster.xds-grpc.assignment_stale: 0
cluster.xds-grpc.assignment_timeout_received: 0
cluster.xds-grpc.bind_errors: 0
cluster.xds-grpc.circuit_breakers.default.cx_open: 0
cluster.xds-grpc.circuit_breakers.default.cx_pool_open: 0
cluster.xds-grpc.circuit_breakers.default.rq_open: 0
cluster.xds-grpc.circuit_breakers.default.rq_pending_open: 0
cluster.xds-grpc.circuit_breakers.default.rq_retry_open: 0 …
```
=> istioctl proxy-config stats

istioctl/pkg/writer/compare/sds/util.go
This is a state Envoy can get into when it fails to parse a secret.
Today, everything in istioctl reports its fine, when it really is just
as blocking as `WARMING`
Can reproduce with a cert that has the cert field in both the cert AND key section. which is not valid of course
=> Add UNINITIALIZED state to `istioctl proxy-config secret`

pilot/pkg/xds/eds.go, pilot/pkg/xds/eds_test.go, releasenotes/notes/36465.yaml
fix https://github.com/istio/istio/issues/36465 and https://github.com/istio/istio/issues/31534.
The sequence to trigger the issue:
1. Scale down a service's workloads to zero, either manually, or some upgrade or reschedule event. This will trigger an EDS push, which does not update Cluster / push CDS.
2. Update any istio config or any service, which will trigger a Cluster update and CDS push for all services (Note CDS cache is invalidated at step 1, which means Cluster for this service will be recomputed), and for this service, since there is no endpoint, the default validation context / SAN match will be empty `"default_validation_context": {}`.
3. Now scale up the workloads, this will trigger another EDS push, and we have the logic to check if the service accounts have any update …
=> Recompute service account at endpoint shard when all endpoints are removed

pilot/pkg/features/pilot.go, pilot/pkg/networking/core/v1alpha3/gateway_test.go, pilot/pkg/networking/core/v1alpha3/listener.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, releasenotes/notes/istio-mutual-cred-name.yaml
Currently, if a user sets both of these, there is no validation or
warning. What ends up happening is the `ISTIO_MUTUAL` part is completely
ignored, and you get one way TLS using the `credentialName` configs.
This is highly unexpected and may lead to misconfigurations where users
expect mTLS to be used/enforce, but it is not.
This modifies the behavior to reject this in validation, and if are both
somehow set then the ISTIO_MUTUAL has precedence. This mirrors the
behavior for file-mounted cert references in the original PR 2.5 years
ago:
https://github.com/istio/istio/commit/fd80f5d11d0ad527d0c3de73f06aa0c2d4501c8e#diff-1488ede8a94d615faf5bbbd17f81fdb16b0409a3cc21ae6525a91991e55df34fR381.
Because this represents a backwards incompatible change, and there are
known users with this …
=> Fix usage of `ISTIO_MUTUAL` with `credentialName`.

pkg/config/validation/validation.go, pkg/config/validation/validation_test.go
This hides errors when we hit warnings - we should send both the errors
and warnings.
Broken out of https://github.com/istio/istio/pull/36933 to make it more backport-able
=> validation: do not exit early on gateway TLS warnings

pilot/pkg/model/push_context.go
This can reduce a bit of computation and memory consumption if `ScopeGatewayToNamespace` is disabled (disabled by default)
=> Compute gateways per namespace only if `ScopeGatewayToNamespace` is enabled

pilot/pkg/features/pilot.go, pilot/pkg/networking/core/v1alpha3/gateway.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, releasenotes/notes/istio-mutual-cred-name.yaml
Currently, if a user sets both of these, there is no validation or
warning. What ends up happening is the `ISTIO_MUTUAL` part is completely
ignored, and you get one way TLS using the `credentialName` configs.
This is highly unexpected and may lead to misconfigurations where users
expect mTLS to be used/enforce, but it is not.
This modifies the behavior to reject this in validation, and if are both
somehow set then the ISTIO_MUTUAL has precedence. This mirrors the
behavior for file-mounted cert references in the original PR 2.5 years
ago:
https://github.com/istio/istio/commit/fd80f5d11d0ad527d0c3de73f06aa0c2d4501c8e#diff-1488ede8a94d615faf5bbbd17f81fdb16b0409a3cc21ae6525a91991e55df34fR381.
Because this represents a backwards incompatible change, and there are
known users with this …
=> [1.12] Fix usage of `ISTIO_MUTUAL` with `credentialName`. (#36935)

pilot/pkg/features/pilot.go, pilot/pkg/networking/core/v1alpha3/gateway.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, releasenotes/notes/istio-mutual-cred-name.yaml
Currently, if a user sets both of these, there is no validation or
warning. What ends up happening is the `ISTIO_MUTUAL` part is completely
ignored, and you get one way TLS using the `credentialName` configs.
This is highly unexpected and may lead to misconfigurations where users
expect mTLS to be used/enforce, but it is not.
This modifies the behavior to reject this in validation, and if are both
somehow set then the ISTIO_MUTUAL has precedence. This mirrors the
behavior for file-mounted cert references in the original PR 2.5 years
ago:
https://github.com/istio/istio/commit/fd80f5d11d0ad527d0c3de73f06aa0c2d4501c8e#diff-1488ede8a94d615faf5bbbd17f81fdb16b0409a3cc21ae6525a91991e55df34fR381.
Because this represents a backwards incompatible change, and there are
known users with this …
=> [1.11] Fix usage of `ISTIO_MUTUAL` with `credentialName`. (#36935)

pkg/kube/multicluster/secretcontroller.go
This will prevent a `xxx` cluster from being registered again from a different multicluster secret.
If registered again, we will give a warning.
=> Warn and ignore the cluster when it from another secret to mesh

docker/Dockerfile.distroless, prow/release-commit.sh
distroless fixed a CVE recently (we aren't affected, but should update our packages accordingly)
=> [release-1.13] run UPDATE_BRANCH=release-1.13 ./bin/update_deps.sh

pkg/queue/instance_test.go
fixes #37085 
The way this is written now better matches the impl. 
Older impls would fail this (running 1 more task after close, or trying to drain the queue). 
This should be good enough, and at least it isn't flaky.
=> fix flake: queue.TestClosed

pkg/istio-agent/xds_proxy.go, pkg/istio-agent/xds_proxy_delta.go
Otherwise xds proxy will just stop if for some reason control plane is passing empty resource, which is catastrophic.
=> Break instead of return on empty resources at xds proxy.

pkg/test/framework/components/environment/kube/flags.go, pkg/test/framework/components/environment/kube/settings.go, tests/integration/tests.mk
Flag has been deprecated for a while and hasn't been used. Remove it.
=> Remove minikube flag from testing infrastructure

pilot/pkg/features/pilot.go, pilot/pkg/model/push_context.go, pilot/pkg/model/virtualservice.go, pkg/config/validation/validation.go, pkg/config/validation/virtualservice.go
This has been defaulted to true for more than 3 release and is stable. So removing the feature flag.
=> remove feature flag for virtual service delegates

tools/docker-builder/main.go
Fixes https://github.com/istio/istio/issues/37069
In the past, the user would see:
```
022-01-28T14:39:07.101176Z	info	Running command: docker buildx bake -f /tmp/istio-release/work/src/istio.io/istio/out/linux_amd64/dockerx_build/docker-bake.json all
[+] Building 0.0s (0/0)
error: Docker exporter feature is currently not supported for docker driver. Please switch to a different driver (eg. "docker buildx create --use")
Error: exit status 1
make[1]: *** [tools/istio-docker.mk:379: dockerx.save] Error 255
make[1]: Leaving directory '/tmp/istio-release/work/src/istio.io/istio'
Error: failed to build: failed to build Docker: failed to create istio docker archives: exit status 2
exit status 1
```
This change helps explain the issue, hopefully in a …
=> Output message with explanation when using --save

tools/go-ordered-test, tools/go-stress-test
TestMain may cause `-list` to print out anything. So make sure we just
capture what we want
=> Fix go test tools

istioctl/cmd/metrics.go, istioctl/cmd/metrics_test.go
there's no `istio_request_duration_seconds` metics in /stats/prometheus
fix `istioctl x mertics` not working
cc @douglas-reid ptal
=> fix istioctl x metrics

go.mod, go.sum, prow/release-commit.sh
The new _release-builder_ commit will generate Bill of Materials. Grab the latest of the other deps minus proxy whose latest release doesn't work.
=> Update release-builder dep + others (-proxy)

pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/controller_test.go, pilot/pkg/serviceregistry/kube/controller/util.go
This PR fixes incorrect behaviour of the [hydrateWorkloadInstance()](https://github.com/istio/istio/blob/ab754b274dd9beabdbd9e183bebb4d6502dd62d3/pilot/pkg/serviceregistry/kube/controller/controller.go#L1129-L1131).
According to the godoc of [GetProxyServiceInstances()](https://github.com/istio/istio/blob/ab754b274dd9beabdbd9e183bebb4d6502dd62d3/pilot/pkg/model/service.go#L599):
> GetProxyServiceInstances returns the service instances that co-located with a given Proxy
However, `hydrateWorkloadInstance()` was returning all service instances, no matter whether they are co-located with a given Proxy or not.
One side-effect of the incorrect behaviour was that a Proxy would get inbound listeners of all service instances rather than only its own. …
=> vm support: fix incorrect behaviour of the `hydrateWorkloadInstance()`

pilot/pkg/util/network/ip.go, releasenotes/notes/fix-eks-ipv6.yaml, tools/istio-iptables/pkg/cmd/root.go
EKS clusters on IPv6 map a host-local NAT interface to each pod for IPv4 egress. For that the pod will be assigned an IP from the link-local reserved CIDR range (more specifcally, from `169.254.172.0/22`) that is unique only to the host. These IPs are not advertised to Kubernetes in any way, they are just available within the pod as the `v4if0` network interface. For proper IPv6 detection we need to exclude these IPs from the discovery mechanisms, otherwise Istio thinks that it is in an IPv4 cluster when it sees this network interface.
More details on the EKS IPv6 networking can be found in the [official blog post](https://aws.amazon.com/de/blogs/containers/amazon-eks-launches-ipv6-support/).
Unfortunately, I did not find existing tests for …
=> Fix IPv6 detection for EKS

prow/lib.sh
Otherwise the credential helpers will be installed globally and this
might mess with pulls from `gcr.io`.
=> Only setup the credentials if there is one

prow/lib.sh
Reverts istio/istio#37219
This broke releases https://prow.istio.io/view/gs/istio-prow/logs/release_istio_postsubmit/1491187672352296960.
I think we now use workload identity, so we need some other check I guess
=> Revert "Only setup the credentials if there is one"

tests/integration/pilot/istioctl_test.go
See https://github.com/istio/istio/issues/29315. This is flaky and known
to be a real bug in an experimental feature. Disable until fixed.
Note: this is flaky enough that even on jobs where we retry jobs, it sometimes fails _both times_: https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-120_istio_postsubmit/1490698318555123712. So I think worth skipping for now.
=> Skip flaky TestWait

pkg/test/kube/dump.go
Currently we use the real cluster name. This is hard to debug, as we
will see a test like `from_primary-1`, but then folder is
`foo-cluster-1236`. We may not know which is which.
Granted, there may be cases the opposite is true. However, I think its less likely and the test logs do show the mapping so its still possible
=> Use stable name for dumping

istioctl/cmd/proxyconfig.go
`configDumpFile` not inited in this cmd... we should not use it...
=> Fix rootca-compare cmd validate logic error

pilot/pkg/networking/core/v1alpha3/listener.go
=> Make use of Listener.EnableReusePort to replace deprecated ReusePort

pkg/config/kube/conversion_test.go
This PR covers `pkg/config/kube/conversion.go` at unit level as it isn't.
=> tests: covers pkg/config/kube/conversion.

pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/listener_builder.go, pilot/pkg/networking/core/v1alpha3/networkfilter.go, pilot/pkg/networking/util/util.go
For proxy >=1.12 metadata exchange filter is injected, so remove the check in 1.14
=> remove CheckProxyVerionForMX in 1.14

pkg/test/framework/components/echo/cmd/echogen/testdata/golden.yaml, pkg/test/framework/components/echo/common/defaults.go, tests/integration/pilot/common/routing.go
Ensure that `useClientProtocol` works with ports named "auto", "http",
and "http2"
=> client protocol jobs: expand coverage to more port names

pilot/pkg/networking/core/v1alpha3/accesslog_test.go, pilot/pkg/networking/core/v1alpha3/listener_builder.go, pilot/pkg/networking/core/v1alpha3/listener_test.go
This PR turns off generation of virtual inbound/outbound listeners for proxies that are not using Iptables redirection.
The purpose of this PR is to remove configuration Istio sidecar doesn't need, minimize potential for conflicts over ports, get closer to the support of multiple Istio Sidecars per VM.
=> vm support: don't generate virtual inbound/outbound listeners for proxies that are not using Iptables redirection

cni/pkg/plugin/plugin_test.go, istioctl/cmd/tag_test.go, istioctl/cmd/workload.go
* istioctl: fix order dependant tests
* Fix cni and pilot test as well
(cherry picked from commit b872e512c22166a3dc338f37d45f20728b37c48c)
(cherry picked from commit d98d84fb7fddab6c331cb0998520bb6a3c355982)
=> [1.11] istioctl: fix order dependant tests (#37045)

pkg/test/framework/components/echo/flags.go, tests/integration/pilot/common/traffic.go
We're already using `retry.Converge(3)` for all networking traffic tests. This PR promotes this to a default for all echo-based tests.
=> [TF] echo.Call use retry.Converge by default

pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/networking/core/v1alpha3/route/route_cache.go, releasenotes/notes/37356.yaml
Fix https://github.com/istio/istio/issues/37356
Route cache uses a copy of services when constructing key, which does not have attributes populated. Also cache assertion does not really work for rds cache for now and this PR fixes that.
=> Fix route cache service key.

tests/integration/security/main_test.go
Currently all other tests use text log, and this is read by humans which makes test based more readable.
=> tf: use consistent log format

cni/pkg/plugin/iptables.go, cni/pkg/plugin/plugin_dryrun_test.go, releasenotes/notes/fix-cni-ipv6-detection.yaml
Currently there is a disparity in IP detection when using the CNI vs. regular usage of the proxy. Since the latter runs on the host, IP detection will also be based on the host network (vs the pod network interfaces for the latter). This is for example an issue when you have dual-stack hosts, but a single-stack IPv6 cluster. In this case the CNI should setup for IPv6, but instead thinks it is running on an IPv4 cluster. A prominent example of this is EKS in IPv6 mode.
This change will make the CNI run its iptables code in the pod network namespace, just like it would when running without the CNI.
Fixes #36871.
=> Fix local IP discovery in CNI

pkg/test/echo/docker/Dockerfile.app_sidecar_base_centos
Seeing a failure trying to build the centos image. It looks like they moved from http to https
```
curl http://vault.centos.org/centos/8/AppStream/x86_64/os/repodata/repomd.xml
...
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://vault.centos.org/centos/8/AppStream/x86_64/os/repodata/repomd.xml">here</a>.</p>
```
=> Fix centos sidecar

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go, pilot/pkg/model/sidecar.go, pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, pilot/pkg/networking/core/v1alpha3/fake.go, pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/networkfilter.go, pilot/pkg/networking/core/v1alpha3/route/route.go, pilot/pkg/networking/core/v1alpha3/route/route_test.go, pilot/pkg/networking/core/v1alpha3/tls.go, pilot/pkg/networking/grpcgen/cds.go, pilot/pkg/xds/endpoint_builder.go, pilot/pkg/xds/ep_filters_test.go, pilot/pkg/xds/fake.go, pilot/pkg/xds/xds_test.go
Currently, we actually have two distinct code paths in a single
function. This is pretty confusing to follow, and makes other PRs more
complex (https://github.com/istio/istio/pull/37174/files).
This splits out to an internal function, which is to be called when
creating SidecarScope, and a method on SidecarScope to be called by
consumers (eg Cluster builder code).
This can be cleaned up further to stop doing the `dummyNode` thing,
which is a major source of bugs historically, if we do the same with
Service. But trying to keep this minimal.
This PR also has a lot of testing changes, as many of our tests do
things that are not realistic.
=> push context: refactor DestinationRule to split usages

tests/integration/pilot/istioctl_test.go
Currently it will only try 1x since the command is pretty slow
see
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/37414/integ-pilot_istio/1494713565586657280/build-log.txt
=> Bump timeout on TestAuthZCheck

pilot/pkg/model/telemetry.go, pilot/pkg/xds/debug.go
fix https://github.com/istio/istio/issues/37218
sample output:
```console
kubectl exec -it istiod-6d985c8cc5-8fg28 -nistio-system -- pilot-discovery request get /debug/telemetryz 
````
``` json
{"telemetries":{"namespace_to_telemetries":{"istio-system":[{"name":"mesh-default","namespace":"istio-system","spec":{"accessLogging":[{"providers":[{"name":"file-log"}],"filter":{"expression":"response.code \u003e= 500"}}]}}]},"root_namespace":"istio-system"}}
```
=> fix `/debug/telemetryz`

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_test.go, pilot/pkg/networking/core/v1alpha3/fake.go
When a service ports has been updated, for the removed port, its cluster is still there.
- [] Networking
=> Fix Delta CDS: cluster not removed when port changed

pkg/test/framework/components/echo/echoboot/echoboot.go
This doesn't actually make a difference as most of our tests already use `.WithClusters` but it's a good default.
=> echoboot: deploy to multi-cluster by default

pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/store.go, pilot/pkg/serviceregistry/serviceentry/store_test.go, pilot/pkg/serviceregistry/util/workloadinstances/index_test.go, pilot/pkg/serviceregistry/util/workloadinstances/selector.go
This PR refactors `serviceregistry/serviceentry` to reuse the same code as `serviceregistry/kube`.
=> refactoring: reuse `workloadinstances.Index` in `serviceregistry/serviceentry`

pilot/pkg/bootstrap/istio_ca.go
Following the docs for [custom-ca-k8s](https://istio.io/latest/docs/tasks/security/cert-management/custom-ca-k8s/) I've found out that the external CA secret was ignored during `createIstioRA`.
Based on the comment 
```
// createIstioRA initializes the Istio RA signing functionality.
// the caOptions defines the external provider
// ca cert can come from three sources, order matters:
// 1. Define ca cert via kubernetes secret and mount the secret through `external-ca-cert` volume
// 2. Use kubernetes ca cert `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` if signer is
//    kubernetes built-in `kubernetes.io/legacy-unknown" signer
// 3. Extract from the cert-chain signed by other CSR signer.
```
> Define ca cert via kubernetes secret and …
=> fix an issue where the mounted external CA secret was ignored

common/scripts/kind_provisioner.sh, prow/integ-suite-kind.sh
Kind setup is a consistent ~1/200 test failure flake. Make it more
robust
Note: this needs to go to common files. Will send there after CI passes (can merge as well)
=> Add retries to kind setp

prow/integ-suite-kind.sh
The e2 nodes we use get a ~random CPU type. Add logging so we can see if
this correlates to flakes
=> tf: log CPU info on test run

pkg/test/echo/check/checkers.go, pkg/test/echo/fields.go, pkg/test/echo/parse.go, pkg/test/echo/response.go, pkg/test/echo/responses.go, pkg/test/echo/server/endpoint/grpc.go, pkg/test/echo/server/endpoint/http.go, pkg/test/echo/server/endpoint/tcp.go, pkg/test/echo/server/endpoint/util.go, pkg/test/echo/server/forwarder/http.go, tests/integration/pilot/common/routing.go, tests/integration/pilot/ingress_test.go, tests/integration/security/authorization_test.go, tests/integration/security/egress_gateway_origination_test.go, tests/integration/security/file_mounted_certs/p2p_mtls_test.go, tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go, tests/integration/security/normalization_test.go, tests/integration/security/sds_ingress/ingress_test.go, tests/integration/security/sds_ingress/util/util.go, tests/integration/security/util/authn/authn_util.go, tests/integration/security/util/cert/cert.go, tests/integration/security/util/rbac_util/util.go, tests/integration/telemetry/outboundtrafficpolicy/helper.go, tests/integration/telemetry/outboundtrafficpolicy/traffic_allow_any_test.go, tests/integration/telemetry/outboundtrafficpolicy/traffic_registry_only_test.go
We currently don't have a way to distinguish between request and response headers when checking echo results. This promotes request and response headers to a top-level field in echo.Response and provides tools for validating headers.
=> [TF] Top-level header fields in echo response

pkg/test/framework/components/istio/config.go, pkg/test/framework/components/istio/operator.go, tests/integration/base.yaml, tests/integration/iop-externalistiod-config-integration-test-defaults.yaml, tests/integration/iop-externalistiod-primary-integration-test-defaults.yaml, tests/integration/iop-integration-test-defaults-with-quic.yaml, tests/integration/iop-integration-test-defaults.yaml
Currently we duplicate everything across 6 files. Clean it up a bit to consolidate the config and ensure they are only different when we intentionally make them so
=> Add base IOP for tf to avoid duplicate configs

pkg/test/framework/components/echo/echoboot/echoboot.go, pkg/test/framework/components/echo/echotest/echotest.go, pkg/test/framework/resource/flags.go, pkg/test/framework/resource/settings.go, tests/integration/pilot/common/apps.go, tests/integration/pilot/common/traffic.go, tests/integration/pilot/locality_test.go, tests/integration/pilot/original_src_addr_test.go, tests/integration/pilot/vm_test.go, tests/integration/security/sds_ingress/util/util.go, tests/integration/security/sds_ingress_k8sca/main_test.go, tests/integration/security/util/framework.go
These did not work with --skipWorkloads. Make it so we have one way to
do things that works for all cases.pick
:
=> Cleanup usages of SkipXX in test framework

security/pkg/k8s/tokenreview/k8sauthn_test.go, security/pkg/pki/util/generate_csr_test.go
Using errors library API instead of DeepEqual as the errors equal judgment condition:
Since the reflect.DeepEqual() does not support error type compare, replace it with the Is function in the golang errors standard library.
=> Using errors library API instead of DeepEqual as the judgment condition

pkg/test/framework/components/prometheus/kube.go, pkg/test/framework/components/prometheus/prometheus.go, tests/integration/security/sds_egress/sds_istio_mutual_egress_test.go, tests/integration/telemetry/outboundtrafficpolicy/helper.go, tests/integration/telemetry/outboundtrafficpolicy/traffic_allow_any_test.go, tests/integration/telemetry/outboundtrafficpolicy/traffic_registry_only_test.go, tests/integration/telemetry/stackdriver/api/stackdriver_filter_test.go, tests/integration/telemetry/stackdriver/common.go, tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go, tests/integration/telemetry/stackdriver/stackdriver_filter_dry_run_test.go, tests/integration/telemetry/stackdriver/stackdriver_filter_test.go, tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go, tests/integration/telemetry/stackdriver/vm/main_test.go, tests/integration/telemetry/stackdriver/vm/vm_test.go, tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go, tests/integration/telemetry/stats/prometheus/stats.go, tests/integration/telemetry/stats/prometheus/util_prometheus.go, tests/integration/telemetry/stats/prometheus/wasm/bad_wasm_filter_test.go, tests/integration/telemetry/util.go
Example output:
```
stats.go:130: query "istio_requests_total" returned 2 series, but none matched our query exactly.
stats.go:130: Series 0
stats.go:130:   for label "reporter", wanted "destination" but got "source"
stats.go:130: Series 1
stats.go:130:   for label "reporter", wanted "destination" but got "source"
stats.go:130:   for label "destination_app", wanted "server" but got "unknown"
stats.go:130:   for label "destination_service", wanted "server.echo.svc.cluster.local" but got "server-no-sidecar.echo.svc.cluster.local"
stats.go:130:   for label "destination_version", wanted "v1" but got "unknown"
stats.go:130:   for label "destination_service_name", wanted "server" but got "server-no-sidecar"
```
As part of this, refactored how we pass around Queries to make things more useable …
=> tf: show prometheus/SD diff on failure instead of dump

pilot/pkg/model/sidecar.go, pilot/pkg/serviceregistry/aggregate/controller.go
Otherwise, if a service with unique port deleted, we can still get stale service port. 
=> [Bug Fix] no mutating service when merging port

pilot/pkg/xds/ads_test.go
Improves perf of AdsPushScoping test. Tested this 100 times in my local with out flakes. If updates come in 100ms, we can safely assume if an update does not come in 100ms, it will never come (unexpected cases).
=> speed up ads push scoping test

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_test.go
- This PR configures slow start warmup duration for `ROUND_ROBIN` and `LEAST_REQUEST` loadbalancer when user sets `warmup_duration_secs` in DestinationRule trafficPolicy based on this api -> https://github.com/istio/api/pull/2153.
- Adds unit test to validate slowStart config is applied in above scenario.
=> Configure warmupDurationSecs for slow start mode

pkg/bootstrap/config.go, pkg/bootstrap/config_test.go, pkg/istio-agent/agent.go
Without this the "downstream_cx_*" stats are not added by default if this feature is enabled.
Refer https://github.com/istio/istio/issues/34855#issuecomment-1053441642
=> fix passing exit on zero active connections to metadata

pilot/pkg/bootstrap/configcontroller.go
We should not skip validation for CR configs via mcp-over-xds.
We always do this check in previous versions until this pr https://github.com/istio/istio/pull/31356 has been merged.
PTAL @hzxuzhonghu
=> Enable validation for mcp-over-xds store.

security/pkg/nodeagent/caclient/providers/google-cas/mock/ca_mock.go, security/pkg/nodeagent/caclient/providers/google/mock/ca_mock.go
Reduce the sleep delay for the mock CA server. The reason for the flakiness is the time it takes until the [first listener accept call](https://github.com/grpc/grpc-go/blob/v1.44.0/server.go#L779) which should not take over 1 second.
Tested on 1000 retries on my local machine.
=> Reduce test duration for google mock CA

tests/integration/telemetry/constants.go, tests/integration/telemetry/outboundtrafficpolicy/helper.go, tests/integration/telemetry/outboundtrafficpolicy/traffic_allow_any_test.go, tests/integration/telemetry/outboundtrafficpolicy/traffic_registry_only_test.go, tests/integration/telemetry/policy/envoy_ratelimit_test.go, tests/integration/telemetry/stackdriver/api/stackdriver_filter_test.go, tests/integration/telemetry/stackdriver/common.go, tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go, tests/integration/telemetry/stackdriver/stackdriver_filter_dry_run_test.go, tests/integration/telemetry/stackdriver/stackdriver_filter_test.go, tests/integration/telemetry/stackdriver/stackdriver_tcp_filter_test.go, tests/integration/telemetry/stackdriver/vm/vm_test.go, tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go, tests/integration/telemetry/stats/prometheus/nullvm/dashboard_test.go, tests/integration/telemetry/stats/prometheus/nullvm/istioctl_metrics_test.go, tests/integration/telemetry/stats/prometheus/nullvm/stats_tcp_filter_test.go, tests/integration/telemetry/stats/prometheus/stats.go, tests/integration/telemetry/stats/prometheus/util_prometheus.go, tests/integration/telemetry/stats/prometheus/wasm/bad_wasm_filter_test.go, tests/integration/telemetry/stats/prometheus/wasm/stats_wasm_tcp_filter_test.go, tests/integration/telemetry/tracing/opencensusagent/tracing_test.go, tests/integration/telemetry/tracing/tracing.go, tests/integration/telemetry/tracing/zipkin/clienttracing/client_tracing_test.go, tests/integration/telemetry/tracing/zipkin/servertracing/tracing_test.go
The telemetry tests are incorrectly using subtests. This cleans things up and avoids this confusion in the future by renaming all the `testing.T` and `framework.TestContext` variables to `t` in order to allow scoping to choose the correct one.
=> [TF] Fixing telemetry test nesting

security/pkg/k8s/chiron/utils.go, security/pkg/pki/ra/k8s_ra_test.go, security/pkg/pki/ra/leak_test.go
for https://github.com/istio/istio/issues/37555
Before this test took 25s. Now its ~instant. This was because we used Watches incorrectly, so it always hit 5s timeout
=> Speed up TestK8sSignWithMeshConfig

pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go, pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go
Delete mcs only when all "real" services are deleted
Fixes #36906
=> Fix: mcs incorrectly deleted

pkg/wasm/cache.go, pkg/wasm/cache_test.go
Fix https://github.com/istio/istio/issues/37631
* fix a bug that cache entries were never updated
* change cacheEntry to point
* add UT
=> [release-1.12] fix a bug that cache entries were never updated (#37578)

pilot/pkg/config/kube/gateway/templates.go, pilot/pkg/config/kube/gateway/templates/deployment.yaml, pilot/pkg/config/kube/gateway/templates/service.yaml
Currently, kubectl apply annotation from Gateway is propogated to
Deployment which triggers a restart everytime we change any field.
=> gateway: avoid recreating Deployment on each kubectl apply

tools/build-base-images.sh, tools/docker-builder/main.go
Job build-base-images_release-builder_periodic of type periodic ended with state failure fails with:
```
Error: image "docker.io/istio/app_sidecar_base_centos_7:latest" already exists
```
This was caused by a recent change to create :latest tags of the images (#https://github.com/istio/istio/pull/37417)
=> Update --no-clobber to not check existence of tag `latest`

pilot/pkg/bootstrap/monitoring.go, security/pkg/nodeagent/cache/monitoring.go, security/pkg/nodeagent/cache/secretcache.go
add a Gauge metric of `default` cert expiry minutes on `pilot-agent`
```console
istio_agent_cert_expiry_minutes{resource_name="default"} 701
```
fixed: https://github.com/istio/istio/issues/37291
***warning***
see from 
https://github.com/census-instrumentation/opencensus-go/blob/49838f207d61097fc0ebb8aeef306913388376ca/metric/registry.go#L237
the registry use metric.Name as key, I think we can not have multi DerivedGauge (same name but different in labels) before we modify the implement of upstream.
In short-term, this PR will allow user monitor `default` cert.
for a long-term, we should make `DerivedGauge ` support metrics with different labels.
BTW, `opencensus-go` is merged to `OpenTelemetry`, so that would take a little more time to …
=> pilot-agent add cert expiry metric

pkg/test/util/retry/retry.go
Before we set max to the base. Instead set it to 16*base, just like
explicit calls
=> retry: fix default backoff

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go
To prevent cluster patch mutating the sharing default transport socket match
=> build default transport socketmatch each time instead of using shared

tests/integration/pilot/multicluster_test.go, tests/integration/security/util/reachability/context.go
TestClusterLocal has a known fix which will land within a week.
The other one does not; we are not skipping though just making the test
slightly less exhaustive. This also reverts us to where we were 2 weeks ago,which added the converge.
=> mitigate flaky tests temporarily

tools/docker-builder/main.go
Prior fix tried comparing `latest` with whole image name. Change to see if the suffix is `:latest`
=> Fix --no-clobber ignoring of `latest` images

pilot/pkg/model/telemetry.go, pilot/pkg/model/telemetry_test.go, releasenotes/notes/37708.yaml
The deprecated field `disable_server_access_logging` in Stackdriver configuration still impacts logging enablement. In particular, if not explicitly set to `true`, logging will be enabled for inbound traffic if the Stackdriver extension is configured. For situations in which metrics-only behavior has been enabled, this is incorrect behavior.
This PR sets the appropriate flag in the configuration to disable logging in these scenarios. Follow-on work should be pursued to remove the deprecated field's impact on logging decisions. This may require work in managed Istio packages that rely on the deprecated behavior.
Fixes: https://github.com/istio/istio/issues/37667
=> TelemetryAPI: Disable Stackdriver logging if not configured (by default, or otherwise) 

security/pkg/nodeagent/cache/secretcache.go, security/pkg/nodeagent/cache/secretcache_test.go
Currently we only watch cert and assume when cert changes key is also changed (wait for some debounce duration) and send it to Envoy. We have seen in some cases cert changes, but key is not changed with in the debounce period, leading to sending incorrect cert and key combination to Envoy resulting in cluster/listener NACKs.
This PR validates that key and cert form a correct combination with a retry (starting with debounce , upto max 1min). If the  key and cert are not a valid combination it returns error - to avoid NACKs.
=> check key and cert are valid before sending to Envoy

pilot/pkg/config/kube/gateway/deploymentcontroller.go
Removes error logs like:
```
error   gateway unable to fetch Gateway: gateway.gateway.networking.k8s.io "gateway" not found  gateway=istio-ingress/gateway
```
Seems the intent here is to ignore not found errors.
=> gateway: fix error log when deleting a Gateway

tests/integration/tests.mk
Some did not have `-vet=false`
=> Standardize run commands for integ tests

pilot/pkg/config/file/store.go
The analyze errors are messy before, like:
```
Error(s) adding files: 21 errors occurred:
* cannot store config {apps/v1/Deployment  conflicting-ports bookinfo  map[app:conflicting-ports version:v1] map[istiofilefieldmap:{"{.apiVersion}":74,"{.kind}":75,"{.metadata.labels.app}":80,"{.metadata.labels.version}":81,"{.metadata.namespace}":78,"{.metadata.name}":77,"{.spec.replicas}":83,"{.spec.selector.matchLabels.app}":86,"{.spec.selector.matchLabels.version}":87,"{.spec.template.metadata.labels.app}":91,"{.spec.template.metadata.labels.version}":92,"{.spec.template.spec.containers[0].imagePullPolicy}":98,"{.spec.template.spec.containers[0].image}":97,"{.spec.template.spec.containers[0].name}":96,"{.spec.template.spec.containers[0].ports[0].contain …
```
=> Improve config store error return

pilot/pkg/model/telemetry_test.go, pilot/pkg/networking/core/v1alpha3/accesslog.go, pilot/pkg/networking/core/v1alpha3/accesslog_test.go, releasenotes/notes/default-json-logging-envoy-telemetry-api.yaml
Currently, with the Telemetry API and EnvoyFileAccessLogger extension provider, there is no easy way to select the Istio-default JSON logging format. This PR attempts to add support for that behavior by treating an empty `labels` set as an indication of selection of default behavior (as there is no point to having an empty access log).
Fixes: #37663
=> telemetry api: allow default json format for envoy file logger

pkg/dns/client/dns.go, pkg/dns/client/dns_test.go
Only call roundRobinResponse when there are answers to reduce on unnecessary allocations in roundRobinResponse function and additional tests in wildcards
=> minor dns fix and additional tests

pkg/test/echo/server/endpoint/util.go, pkg/test/echo/server/instance.go
Modify the Echo Server to support Dual Stack. Based on the IP addresses of the Pod, Echo server will listen IPv4 or IPv6 addresses.
Part of https://github.com/istio/istio/issues/37533
- [x ] Networking
- [x ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> add dual stack support for echo server [TF]

pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
The MCS serviceImportCacheImpl.onServiceEvent is called concurrently from every service update in the mesh. This logic needs to be processed synchronously as a unit to avoid races.
This PR moves the processing for this method onto the local cluster's queue.
=> Synchronize MCS even handling

tools/packaging/common/istio-start.sh
This PR refactors `istio-start.sh` to make default file paths relative.
The goal is to minimise amount of configuration a user has to override to be able to run Istio Sidecar with a working directory other than `/` (default).
=> vm support: make default file paths in `istio-start.sh` relative

tools/packaging/common/gcp_envoy_bootstrap.json
This PR fixes outdated config in `gcp_envoy_bootstrap.json`:
1. use Envoy Bootstrap API `v3` (`typed_config`)
2. sync configuration style with `envoy_bootstrap.json`
=> bootstrap: fix outdated config in `gcp_envoy_bootstrap.json`

pilot/pkg/networking/core/v1alpha3/tracing.go, pkg/bootstrap/instance_test.go, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, tools/packaging/common/envoy_bootstrap.json, tools/packaging/common/gcp_envoy_bootstrap.json
This PR refactors Envoy config to make file path `/var/run/secrets/tokens/istio-token` relative.
=> bootstrap: make file path `/var/run/secrets/tokens/istio-token` relative

pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, releasenotes/notes/ip-sni-hosts.yaml
Follow-up to discussion in here https://github.com/istio/istio/issues/33401#issuecomment-971788146, to prevent users from specifying an IP address in the `sniHosts` field of [VirtualService.TLSRoute.Match](https://github.com/istio/api/blob/0511549a0fae34380fdf1399075ccf51bc240be8/networking/v1alpha3/virtual_service.pb.go#L2131) since most clients will not include an IP address in the SNI.  Example of a VirtualService that will no longer pass validation:
```yaml
metadata:
name: direct-cnn-through-egress-gateway
spec:
hosts:
- 1.2.3.4
tls:
- match:
- gateways:
- mesh
port: 443
sniHosts:
- 1.2.3.4.  ## no longer valid
route:
- destination:
host: …
```
=> Add Warning for IPs in SNI Hosts in TLSRoute.Match criteria

pilot/pkg/networking/core/v1alpha3/fake.go, pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/networking/core/v1alpha3/httproute_test.go, pilot/pkg/networking/core/v1alpha3/route/route.go, pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go, pilot/pkg/xds/fake.go
Revert https://github.com/istio/istio/pull/33764 to fix https://github.com/istio/istio/issues/37691. Alternative is https://github.com/istio/istio/pull/37721.
This was primarily to get the new tests I wrote passing. These same tests pass on the release-1.11 branch, ensuring we have no behavioral regression. I am ok moving forward with https://github.com/istio/istio/pull/37721 if we pull in these tests there and they all pass (currently they do not).
=> Revert selecting virtual services

tests/integration/tests.mk
We previously ran all tests. In
https://github.com/istio/istio/commit/3421f15fe499fc4c09d4a476b6fdd80a2c75bfa0,
8 days ago, we accidentally changed this to only `security/` for about 7
jobs.
This restores those jobs to their former glory, testing all of
`tests/integration/...`.
=> tf: fix regression in tests run

pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
This is because the queue is not run. 
https://prow.istio.io/view/gs/istio-prow/logs/benchmark-report_istio_postsubmit/1503179335081660416
=> Fix benchmark

pilot/pkg/serviceregistry/serviceentry/conversion.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
Before we do not merge labels when selecting se. Not consistent with `convertWorkloadEntryToServiceInstances`
https://github.com/istio/istio/blob/2a38aca26bf6d41dbd93ff9f3089eb1918d69a6e/pilot/pkg/serviceregistry/serviceentry/servicediscovery.go#L208-L214
=> Fix selecting serviceentry by wle labels

pkg/test/framework/analyzer.go, pkg/test/framework/resource/setup.go, pkg/test/framework/suite.go, tests/integration/telemetry/stackdriver/vm/main_test.go
This test only makes sense when VMs are enabled. Currently it will fail in weird ways otherwise
=> tf: skip VM suite when VM is disabled

pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go, releasenotes/notes/37903.yaml
Found this bug in this PR https://github.com/istio/istio/pull/36404. Http filter removal does not work correctly.
=> fix filter removal for http filter

pilot/pkg/model/context.go, pilot/pkg/networking/apigen/apigen.go, pilot/pkg/networking/grpcgen/grpcgen.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/bench_test.go, pilot/pkg/xds/bootstrapds.go, pilot/pkg/xds/cds.go, pilot/pkg/xds/debug.go, pilot/pkg/xds/debuggen.go, pilot/pkg/xds/delta.go, pilot/pkg/xds/ecds.go, pilot/pkg/xds/eds.go, pilot/pkg/xds/lds.go, pilot/pkg/xds/nds.go, pilot/pkg/xds/pcds.go, pilot/pkg/xds/rds.go, pilot/pkg/xds/sds.go, pilot/pkg/xds/sds_test.go, pilot/pkg/xds/statusgen.go, pilot/pkg/xds/xdsgen.go, security/pkg/nodeagent/sds/sdsservice.go, tests/fuzz/pilot_networking_fuzzer.go
Curently we take a `push` and a `PushRequest`. PushRequest already has
push, so we can just use that everywhere. This avoids mistakes wher we
may accidentally set one but not the other, etc.
There are no (known) bugs this fixes; this is intended to be a
refactoring only.
=> xds: refactor Generator signature

tools/istio-docker.mk
Based on
https://www.cncf.io/blog/2021/09/14/how-to-secure-containers-with-cosign-and-distroless-images/
we should verify the distroless images before we build images from them.
=> Verify distroless base images before building

pilot/pkg/xds/eds.go
Currently we log 3x for each new Service. This drops it down to just 1x
=> pilot: drop excess EDS logging

pkg/bootstrap/platform/aws.go, pkg/bootstrap/platform/aws_test.go
Looks like in some other cloud provider the same instance-id url is used. This PR actually verifies "aws" exists in arnInfo from "/iam/info" endpoint.
Fixes https://github.com/istio/istio/issues/37995
=> fix aws platform detection

pilot/pkg/xds/ads.go, pilot/pkg/xds/delta.go
https://github.com/istio/istio/pull/37800 changed which PushContext we
use; however, it had a bug which caused some rare test instability,
primarily in TestTraffic. In the initiate attempt at the change above, a
similar issue occurred, but with a much higher rate of error
(https://github.com/istio/istio/pull/37604).
Unfortunately, we forgot to apply the same fix to the Delta code path.
This PR does that, eliminating the last test flakes.
I ran this PR and `master` against the assertion tests 100s of times
overnight. Without this change it failed about 5% of the time; with it
0% (due to this issue - a few unrelated test flakes did occur).
Long term, this split code path with Delta and SotW is a risk. This was
a known risk, intentionally favoring possible code drift over
destabilizing the …
=> pilot: use correct Request.Start for Delta XDS

pilot/pkg/features/pilot.go, pilot/pkg/xds/eds.go, pilot/pkg/xds/eds_test.go
This mirrors the Delta EDS code.
Basically, this allows the case of a Full push for a service to only
send the endpoints request. This happens when we create a new Service,
for example.
Note: "Delta EDS" and "Incremental EDS" are essentially exactly
identical other than the gRPC service. In both cases, its impossible to
remove resources (its all based on parent Cluster being removed). In
both cases, we can chose to send as many or as few resources as we want.
The same applies to RDS I believe.
=> EDS: send incremental pushes on full with only services changed

pilot/pkg/features/pilot.go, pilot/pkg/model/context.go, pilot/pkg/xds/delta.go, pilot/pkg/xds/deltatest.go, pilot/pkg/xds/eds.go
This adds a new test -- disabled by default -- which adds a bunch of consistency checks in Delta XDS by comparing responses to SotW responses. This is intended to have 0 impact on production code, as all changes are behind a `UNSAFE` flag.
These tests have found a number of bugs in the past, as I have maintained this in my fork for a while. I think its useful to upstream though.
=> Add test for Delta XDS vs SotW

tools/istio-docker.mk
BUILD_WITH_CONTAINER=0 make docker.* on a Mac (and maybe other platforms) yields:
```
make: *** No rule to make target `docker.*'.  Stop.
```
It seems the various docker targets aren't being created when run locally.
I notice an extra `=` on the new define, and removing that fixes the issue on the Mac.
=> Fix BUILD_WITH_CONTAINER=0 make docker.*

pkg/bootstrap/platform/aws.go, pkg/bootstrap/platform/discovery.go
This PR changes the log level from error to 'debug' for AWSInfo error messages. It is not preferred to see these error logs everytime during startup. 
Fixed typo in "Cloud Platform"
=> Changes log level to debug while fetching AWS info and typo fix

tools/docker-copy.sh
All files will be 644 or 755, depending on if they are executable or
not.
Fixes https://github.com/istio/istio/issues/37151.
This was made worse in https://github.com/istio/istio/pull/37935, which
accidentally removed `chmod` on the echo certs; this makes anyone not
running as root not able to build functional images
=> docker: standardize file permissions of files in container

pkg/test/echo/server/endpoint/grpc.go, pkg/test/echo/server/forwarder/config.go, pkg/test/echo/server/forwarder/dns.go, pkg/test/echo/server/forwarder/grpc.go, pkg/test/echo/server/forwarder/http.go, pkg/test/echo/server/forwarder/instance.go, pkg/test/echo/server/forwarder/protocol.go, pkg/test/echo/server/forwarder/tcp.go, pkg/test/echo/server/forwarder/tls.go, pkg/test/echo/server/forwarder/util.go, pkg/test/echo/server/forwarder/websocket.go, pkg/test/echo/server/forwarder/xds.go
Headless tests fail for multicluster in #37914 because only the headless workload in the local cluster is reached.
When making individual forward requests from the command line, the requests toggle properly. This means that there must be some caching of DNS lookup within the Dialer.
This change forces the creation of a new Dialer and Resolver for each request.
With this change, the headless tests correctly reach all clusters.
Fixes #38023
=> [TF] Make Echo resolve DNS for each request

tools/docker-copy.sh
https://github.com/istio/istio/pull/38068 contains `find -executable` which is not Mac friendly. This PR removes that code and instead does a chmod 644 on the non `ELF 64-bit LSB` files.
The original code just made sure to chmod 755 ELF files and other files might have been left with the read flag unset. This code chmod 644's the non-ELF files, so all files will be readable.
Looking into the behavior of `-executable` when looking for a Mac equivalent, `-executable` doesn't actually check that the file is an executable, just that the various executable attributes are set such that the current user can execute it.
=> Make docker-copy Mac friendly and more executable correct

tools/docker-copy.sh
Running release-builder locally, I ran into a problem:
```
cp: cannot stat 'tests/testdata/certs/README.md': Permission denied
cp: cannot stat 'tests/testdata/certs/cert.crt': Permission denied
cp: cannot stat 'tests/testdata/certs/cert.key': Permission denied
cp: cannot stat 'tests/testdata/certs/default': Permission denied
cp: cannot stat 'tests/testdata/certs/dns': Permission denied
cp: cannot stat 'tests/testdata/certs/generate.sh': Permission denied
cp: cannot stat 'tests/testdata/certs/mountedcerts-client': Permission denied
cp: cannot stat 'tests/testdata/certs/mountedcerts-server': Permission denied
cp: cannot stat 'tests/testdata/certs/pilot': Permission denied
```
The issue is that we are removing the execute attribute on a directory. …
=> Update to do chmod on files after copy. Add read for non ELF files.

pilot/pkg/model/credentials/resource.go, pilot/pkg/model/credentials/resource_test.go, pilot/pkg/security/model/authentication.go, pilot/pkg/xds/sds_test.go
There are various times when users need to deploy TLS on a workload, but
doesn't care at all what certificate is used. One example could be
istio.io docs, but that is a minor case. The more important is things
like
https://aws.amazon.com/blogs/containers/secure-end-to-end-traffic-on-amazon-eks-using-tls-certificate-in-acm-alb-and-istio/.
Folks will run `client ---TLS---> Cloud LB (terminate) --TLS---> Istio
Ingress (terminate) ---> backend`.
The connection between cloud LB and Istio Ingress doesn't do any
verification, which leads to using self signed certs. While there is
technically nothing wrong with this, it adds extra steps and draws
scrutiny from security-conscious users.
As a step to make this easier, we can allow using the workloads mTLS
certs. This works in `MUTUAL` and `SIMPLE` …
=> gateway: expose mechanism to use spiffe workload cert at gateway

pilot/pkg/model/push_context.go, pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/delta.go, pilot/pkg/xds/delta_test.go, pilot/pkg/xds/deltatest.go, pilot/pkg/xds/discovery_test.go, pilot/pkg/xds/eds.go, pilot/pkg/xds/eds_test.go, pilot/pkg/xds/lds_test.go, pilot/pkg/xds/xdsgen.go, pkg/util/sets/string.go, security/pkg/nodeagent/sds/sdsservice_test.go
Currently:
* SotW always does a full push on request
* Delta does a partial push only on subscribe, but not on unsubscribe.
* SotW will never skip a push, and will instead send a push with 0
resources. Delta will skip a push only for EDS
New behavior:
* Both Delta and SotW will do partial pushes for subscribes.
* Both Delta and SotW, If there are only unsubcribes, we will not send a response at all
This optimizes request cases. For example, say we have 100 listeners and
remove 10. 45s later, those listeners will drain. This results in an XDS
requests with 99 routes, 98, 97 ... 90 routes - about 1000 routes
generated in total. With this optimization, we will send 0.
On the other side, say we add 1 listener. Before, we would push RDS
(100), and then immediately get a RDS request and send …
=> pilot: unify and improve sub/unsub in delta and sotw

pilot/pkg/util/network/ip.go, pilot/pkg/util/network/ip_test.go
Reverts istio/istio#37654
This introduces a breaking change to pilot-agent localhost listeners. Previously, these listened on 127.0.0.1; now they listen on `::1`. This represents a non-flag protected breaking change. I do not think we should break users accessing admin interfaces over IPv4.
=> Revert "The enhancement for function IsIPv6Proxy"

prow/lib.sh
Do we just want OSX users to alias `date` -> `gdate`? 
An alternative would be like:
```
date <some set of GNU date flags that we know work> || echo "Warning: use gdate as your standard date command"
```
=> prow scripts: workaround lack of GNU date on OSX

pkg/istio-agent/agent_test.go
This check is both wrong (input of fake ca authenticator expects an identity instead of a file) and meaningless (since cert will be fetched from the cache instead of connecting to the CA). IIUC the `reboot` case below will test out mTLS based authentication, so no need to deal with it in the `initial run` case, which has no way to clean up cache at secret client.
cc @stevenctl
=> Remove meaningless CA authentication check at agent unit test.

samples/kind-lb/README.md, samples/kind-lb/setupkind.sh
setupkind script can only successfully setup kind
with metallb in Linux environment. This PR will warn
a user if this script gets run in an envrionment other
than Linux
=> Added warning for setupkind script

tests/integration/pilot/gateway_conformance_test.go
Upstream PR should merge soonish, but for now lets get our tests green again
=> Skip GW conformance for now

pilot/pkg/bootstrap/server.go, pilot/pkg/xds/fake.go, pilot/pkg/xds/sds.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, pkg/istio-agent/agent.go, pkg/istio-agent/agent_test.go, releasenotes/notes/37681.yaml, security/pkg/nodeagent/sds/sdsservice.go, security/pkg/nodeagent/sds/sdsservice_test.go, security/pkg/nodeagent/sds/server.go
When the PrivateKeyProvider configuration information is provided through Istio operator yaml file, parse and pass it to gateway or sidecars. Envoy will act based on the information provided by the configuration.
To set the mesh wide defaults, configure the `defaultConfig` section of `meshConfig`.
For example:
```
meshConfig:
defaultConfig:
privateKeyProvider:
cryptomb:
pollDelay: 0.01s
```
This can also be configured on a per-workload basis by configuring the `proxy.istio.io/config`
annotation on the pod.
For example:
```
annotations:
proxy.istio.io/config: |
privateKeyProvider:
cryptomb:
pollDelay: 0.01s
```
This requires https://github.com/istio/api/pull/2261
=> Handle PrivateKeyProvider configuration

pilot/pkg/model/config.go, pilot/pkg/model/destination_rule.go, pilot/pkg/model/destination_rule_test.go, pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go, pilot/pkg/model/sidecar.go, releasenotes/notes/38088.yaml
Fix https://github.com/istio/istio/issues/38082
For merged DRs, currently we have only one DR meta(name/namespace) and add only one DR dependency.  
And so we will miss xds push for some update.
The pr solves this by recording all DRs' meta, and adding all dependencies.
=> Fix dr dependency miss

pilot/pkg/config/kube/gateway/controller.go, pilot/pkg/config/kube/gateway/conversion.go, pilot/pkg/model/push_context.go, pilot/pkg/model/service.go, pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/xds/delta.go, pilot/pkg/xds/deltatest.go, pkg/config/analysis/analyzers/webhook/webhook.go, pkg/test/framework/components/echo/deployment/builder.go, pkg/util/sets/string.go, tools/docker-builder/main.go, tools/docker-builder/types.go
This was removed by https://github.com/istio/istio/pull/38140, but should not have been. The Insert/InsertAll separation avoids a needless array allocation for the vast majority of Insert calls.
=> Restore Set.InsertAll

prow/lib.sh
In a recent PR, we fixed the VM tests to actually run the different
images - previously they always ran the same image. This exposed another
bug, that we skipped building these images entirely as well. Start
building them again.
=> Fix VM postsubmit jobs

pilot/pkg/xds/debug.go, pilot/pkg/xds/debug_test.go
```json
[
{
"cluster_id": "Kubernetes",
"proxy": "sleep-557747455f-ntclb.default",
"istio_version": "1.14-dev",
"cluster_sent": "H/Wuh8XL+DI=acda010e-b2f3-4ea3-99d7-3175f5448242",
"cluster_acked": "H/Wuh8XL+DI=acda010e-b2f3-4ea3-99d7-3175f5448242",
"listener_sent": "H/Wuh8XL+DI=799ac99c-1f49-45a0-9d44-b6485483c0a2",
"listener_acked": "H/Wuh8XL+DI=799ac99c-1f49-45a0-9d44-b6485483c0a2",
"route_sent": "H/Wuh8XL+DI=ea566798-bad5-49aa-a434-62465e4fa34d",
"route_acked": "H/Wuh8XL+DI=ea566798-bad5-49aa-a434-62465e4fa34d",
"endpoint_sent": "H/Wuh8XL+DI=ee385484-be99-4b39-8f43-d0b044869c5f",
"endpoint_acked": "H/Wuh8XL+DI=ee385484-be99-4b39-8f43-d0b044869c5f"
},
{
"cluster_id": "Kubernetes",
"proxy": "fortio-deploy-687945c6dc-h9gw8.default", …
```
=> syncz support ECDS

pkg/test/framework/resource/context.go, pkg/test/framework/scope.go
We currently synchronously run all added closers, which can take a long time. Common use case for a closer is deleting a YAML file that was applied during a test.
This PR runs all closers in parallel. Significantly improves shutdown time on hosted k8s (e.g. GKE).
=> [tf] Optimize scope close

pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, releasenotes/notes/auto-sni-support.yaml
[RFC auto-sni support](https://docs.google.com/document/d/1pTUl-Ng3nXAWJb7UGJtalftznpxQEfID/edit#)
- [X ] Networking
=> Add auto-sni support

releasenotes/notes/auto-sni-support.yaml
The environment variable was wrongly spelled in the release notes.
- [ X] Docs
=> Fix typo in auto-sni-support releasenotes

istioctl/pkg/writer/envoy/configdump/route.go, istioctl/pkg/writer/envoy/configdump/route_test.go
istioctl miss to append ipv6 domain when using istioctl pc route
IPv4 or dual-stack cluster
IPv6 only cluster
=> istioctl miss to append ipv6 domain when using istioctl pc route

istioctl/pkg/multicluster/env_test.go, istioctl/pkg/multicluster/remote_secret.go, istioctl/pkg/multicluster/remote_secret_test.go, pkg/config/analysis/analyzers/multicluster/istio_reader.go
A fix for https://github.com/istio/istio/issues/38246 that maintains current behavior. 
IIUC, this part doesn't break us:
> In 1.21+ secret-based tokens are no longer used for mounting into pods (ephemeral time-limited tokens are).
wip: need to add tests and release note
=> create-remote-secret: handle k8s 1.24+ sa token behavior

tools/packaging/common/gcp_envoy_bootstrap.json
TD use the following format for mesh resource and gateway resource respectively
- mesh: /projects/project-name/networks/mesh:mesh-name/nodes/<node>
- gateway: /projects/project-name/networks/scope:scope-name/nodes/<node>
However a valid k8s label must be an empty string or consist of alphanumeric characters, '-', '_' or '.' Thus we could not include the entire string `mesh:mesh-name`. The workaround is to add `mesh:` prefix here. And only include mesh-name in the label.
=> Add the prefix to td mesh name in gcp_envoy_bootstrap.json

Makefile.core.mk
Fixes https://github.com/istio/istio/issues/38216
Doing some investigation on the subject issue, and debated about simply including the earlier removed snippet. One issue with just including the earlier snippet is it uses `go get` which no longer installs the binary. This was a change in Go 1.18. The new method is to use `go install`.
Another con to simply replacing the snippet is we are updating the host environment. This may or may not be a good thing.
This only affects users who are doing builds outside of our build container which includes the binary.
I propose that in the case where the `go-junit-report` is not found we instead ask the user to install it.
If the binary is missing:
```
BUILD_WITH_CONTAINER=0 make racetest
go-junit-report …
```
=> Fix Makefile missing target for go-junit-report

pilot/pkg/bootstrap/server.go, pilot/pkg/bootstrap/servicecontroller.go, pilot/pkg/networking/core/v1alpha3/fake.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go, pilot/pkg/serviceregistry/serviceentry/conversion.go, pilot/pkg/serviceregistry/serviceentry/conversion_test.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go, pilot/pkg/serviceregistry/serviceentry/workloadentry.go, pilot/pkg/serviceregistry/serviceregistry_test.go, pilot/pkg/xds/simple.go
- Rename service entry store -> Controller 
- Remove DisableServiceEntryProcessing option and add new method for WorkloadEntryController
=> rename service entry store to controller

pkg/config/analysis/analyzers/all.go, pkg/config/analysis/analyzers/analyzers_test.go, pkg/config/analysis/analyzers/envoyfilter/envoyfilter.go, pkg/config/analysis/analyzers/testdata/absolute-envoy-filter-operation.yaml, pkg/config/analysis/analyzers/testdata/relative-envoy-filter-operation.yaml, pkg/config/analysis/analyzers/util/find_errorline_utils.go, pkg/config/analysis/analyzers/util/find_errorline_utils_test.go, pkg/config/analysis/msg/messages.gen.go, pkg/config/analysis/msg/messages.yaml, releasenotes/notes/37415.yaml
Fixes #37415 
Checks an envoy filter patch operation to see if the envoy filter has a priority set or if its using a relative instead of absolute patch operation.  It issues a warning if a relative patch operation (INSERT_BEFORE/INSERT_AFTER) is being used and no priority is being set.
=> Add istioctl analyzer for envoyFilter patch operation

pilot/pkg/model/context.go, pilot/pkg/model/proxy_view.go, pilot/pkg/model/proxy_view_test.go, pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, pilot/pkg/xds/endpoint_builder.go, pilot/pkg/xds/ep_filters.go
This adds an abstraction `ProxyView` to restrict which endpoints are visible to a given gateway.
This was originally going to be used to additionally restrict views to same-cluster, but we decided against it for now.
So this is just a minor cleanup for now, but will make future changes to proxy view easier.
=> Cleanup proxy view logic

go.mod, go.sum
https://nvd.nist.gov/vuln/detail/CVE-2022-21698
This doesn't impact Istio's usage but makes scanners angry - easier to just update it than convince folks the scanner messages can be ignored
=> Bump prometheus client for CVE-2022-21698 update

tools/build-base-images.sh
Update build-base-images.sh to use python3.
The current periodic `build-base-images_release-builder_periodic` is failing (see defaultTargets is empty):
```
++ jq '[.images[] | select(.base) | .name] | join(",")' -r
tools/build-base-images.sh: line 27: python: command not found
tools/build-base-images.sh: line 27: python: command not found
+ defaultTargets=
```
The build-tools image only has python3 installed:
```
make shell
build-tools:/work$ python
bash: python: command not found
build-tools:/work$ python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
build-tools:/work$ python
bash: python: command not found
build-tools:/work$ exit
exit
make: *** …
```
=> Update build-base-images.sh to use python3

go.mod, go.sum
Otherwise, running go mod vendor will get an error.
There is a reported issue: https://github.com/distribution/distribution/issues/3590
```
go mod vendor
go: downloading istio.io/api v0.0.0-20220412170844-98b86b0a79ee
go: downloading istio.io/client-go v1.12.0-alpha.5.0.20220412171342-f891b6af6bd5
go: downloading sigs.k8s.io/gateway-api v0.4.1-0.20220411164207-d6bbc338d351
go: downloading github.com/docker/distribution v2.8.0+incompatible
verifying github.com/docker/distribution@v2.8.0+incompatible: checksum mismatch
downloaded: h1:u9vuu6qqG7nN9a735Noed0ahoUm30iipVRlhgh72N0M=
go.sum:     h1:l9EaZDICImO1ngI+uTifW+ZYvvz7fKISBAKpg+MbWbY=
```
=> Upgrade  github.com/docker/distribution to 2.8.1

istioctl/cmd/kubeinject.go, pkg/kube/inject/inject.go
This fix will make `istioctl kube-inject` respect proxyconfig CR if the deployment has namespace defined
=> use deployment's namespace for AdmissionRequest in istioctl kube-inject

pkg/test/framework/components/echo/calloptions.go, pkg/test/framework/components/echo/check/checkers.go, pkg/test/framework/components/echo/echotest/filters_test.go, pkg/test/framework/components/echo/instance.go, pkg/test/framework/components/echo/kube/instance.go, pkg/test/framework/components/echo/match/matchers_test.go, pkg/test/framework/components/echo/port.go, pkg/test/framework/components/echo/staticvm/instance.go, tests/integration/pilot/common/routing.go, tests/integration/security/authorization_test.go, tests/integration/security/ca_custom_root/trust_domain_validation_test.go, tests/integration/security/pass_through_filter_chain_test.go, tests/integration/telemetry/stats/prometheus/stats.go
This introduces a new TargetWorkload entry to call *pods* rather than
*services*. And cleans up a bunch of usages where we use to do things
the hard way
=> tf: cleanup usages of Workload

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, pilot/pkg/xds/sds.go, pilot/pkg/xds/sds_test.go, releasenotes/notes/credential-name-support-egress-sidecar.yaml
RFC: [Simplify sidecar egress mTLS](https://docs.google.com/document/d/1UXpT3rZpE2uFeMh5KffAZAPAoZBLNSHc/)
Currently egress mTLS configuration on sidecar does not allow supplying credentialName. This PR
tries to allow the same, provided the credentials are available in the same namespace as the workload with
proper RBAC.
Phase 2 of the solution would allow cross namespace access of secrets, which would be pursued later.
I had pursued the work in a previous PR at https://github.com/istio/istio/pull/36746.
However there were comments from the maintainers about performance concerns on the PR, as the changes introduced
would delay the pod bring up time for pods who are not having access to the secrets specified in the DR.
A suggestion was given to …
=> Support CredentialName configuration in DR for sidecars

pilot/pkg/model/endpointshards.go, pilot/pkg/model/push_context.go, pilot/pkg/networking/core/v1alpha3/fake.go, pilot/pkg/serviceregistry/kube/controller/fake.go, pilot/pkg/serviceregistry/memory/discovery.go, pilot/pkg/xds/debug.go, pilot/pkg/xds/discovery.go, pilot/pkg/xds/eds.go, pilot/pkg/xds/eds_test.go, pilot/pkg/xds/endpoint_builder.go, pilot/pkg/xds/ep_filters_test.go
1. Allows passing a reference to the formerly names EndpointShardsByService to generators living outside `xds` package. 
2. Prework for https://github.com/istio/istio/issues/36365. This will help in creating some way to write to one set of shards and swap in the new ones after sync (in updating remote secret). 
not 100% convinced this is needed for the latter case; hope the cleanup is worthwhile regardless. Only concern is some indirection that preserves some concurrency cache invalidation behavior.
=> refactor endpointshards index into model

Makefile.core.mk, manifests/charts/istiod-remote/values.yaml
Updated yq in tooling to v4 since `v3 is now deprecated, critical bug fixes and security fixes will still be applied until August 2021.` 
This needs an update our Makefile for the newer command syntax.
=> Update yq commands for v4

pilot/pkg/xds/lds.go, tests/integration/pilot/common/routing.go
Fixes test flakes like
https://prow.istio.io/view/gs/istio-prow/logs/integ-ipv6_istio_postsubmit/1514637916112949248
We recently added TCP sourceIP consistent hash. Even more recently, this
test started to fail often. I believe this is due to a change to apply
YAML in parallel, exposing this bug.
The root cause is that we do not push LDS for DR changes, but the config
impacts LDS.
=> Fix consistent hash based on source IP for TCP proxy

pkg/config/xds/filter_types.go
Fix for error message which appears when using Ubuntu `jammy`:
```
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
```
This still works with `focal`.
=> Update xargs removing -n1 when using -I

pkg/config/validation/extensionprovider.go, pkg/config/validation/extensionprovider_test.go
add validation 
```console
root@ecs-istiodev:~/GoProjects/src/istio.io/istio# out/linux_amd64/istioctl --log_output_level=all:info tag set canary --revision 1-14-0 --overwrite
2022-04-20T01:41:23.110642Z	warn	validation	found invalid extension provider (can be ignored if the given extension provider is not used): invalid extension provider otel: unsupported provider: &{service:"otel-collector.istio-system.svc.cluster.local" port:4317 log_format:{labels:{fields:{key:"hostname" value:{string_value:"%HOSTNAME%"}} fields:{key:"spanID" value:{string_value:"%REQ(X-B3-Spanid)%"}} fields:{key:"traceID" value:{string_value:"%REQ(X-B3-Traceid)%"}}}}} of type *v1alpha1.MeshConfig_ExtensionProvider_EnvoyOtelAls
```
**To help us figure out who should review …
=> add OTel provider validation

tests/integration/pilot/analysis/analysis_test.go
Since test setup has
```
Setup(istio.Setup(nil, func(_ resource.Context, cfg *istio.Config) {
cfg.ControlPlaneValues = `
values:
pilot:
env:
PILOT_ENABLE_STATUS: true
global:
istiod:
enableAnalysis: true
`
})).
```
should be marked as requiring custom setup
=> Mark TestAnalysisWritesStatus as requiring custom setup

pkg/wasm/cache_test.go, pkg/wasm/imagefetcher.go
In current implementation, to get OCI image for WASM, there are at least five times http/https calls happen.
By this patch, it is reduced to 3 times if the registry supports "https" which is usually expected. 
In details, `remote.Get` is always called two times. 
* [first](https://github.com/istio/istio/blob/7c583c4600decefc6bf7f8216dcd65edb0ed095a/pkg/wasm/imagefetcher.go#L162)
* [second](https://github.com/google/go-containerregistry/blob/570ba6c88a5041afebd4599981d849af96f5dba9/pkg/v1/remote/image.go#L53).
(each `remote.Get` calls two times http/https calls: `ping` and real request.)
- [ *] Policies and Telemetry
=> Reduce https/http calls for getting an OCI image manifest for WASM plugin

prow/lib.sh
Post submit tests are failing:
```
+ DOCKER_TARGETS='docker.pilot docker.proxyv2 docker.operator docker.install-cni  docker.app docker.app_sidecar_ubuntu_jammy docker.ext-authzdocker.app_sidecar_ubuntu_xenial docker.app_sidecar_debian_11  docker.app_sidecar_centos_7 '
```
Note the lack of a space, and two targets being concatenated: `docker.ext-authzdocker.app_sidecar_ubuntu_xenial docker.app`
=> Missing space causing post submit test failures

istioctl/cmd/kubeinject.go, releasenotes/notes/38083.yaml
Fixes #38083 
When providing an injection configmap specifically without a revision flag passed, non-default revisions cause a nil pointer exception panic. This patch applies a check for the configmap revision label to provide a cleaner error message.
=> Kubeinject revision check

pilot/pkg/bootstrap/server_test.go, pilot/pkg/config/kube/crdclient/client_test.go, pilot/pkg/model/push_context_test.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, pilot/pkg/networking/core/v1alpha3/cluster_test.go, pilot/pkg/networking/core/v1alpha3/gateway_test.go, pilot/pkg/networking/core/v1alpha3/listener_builder_test.go, pilot/pkg/networking/core/v1alpha3/listener_test.go, pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go, pilot/pkg/networking/networking_test.go, pilot/pkg/networking/util/util_test.go, pilot/pkg/security/authn/v1beta1/policy_applier_test.go, pilot/pkg/serviceregistry/kube/controller/multicluster_test.go, pilot/pkg/serviceregistry/kube/controller/serviceexportcache_test.go, pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go, pilot/pkg/serviceregistry/serviceregistry_test.go, pilot/pkg/xds/bench_test.go, pilot/pkg/xds/deltaadstest.go, pkg/config/gateway/gateway_test.go, pkg/config/validation/validation_test.go, pkg/istio-agent/xds_proxy_test.go, pkg/kube/inject/inject_test.go, pkg/kube/multicluster/secretcontroller_test.go, pkg/test/util.go
Currently we have a ton of boilerplate and/or incorrect attempts to
mutate global vars (generally feature flags) for a test.
This introduces new helpers for this use case and uses them throughout
the codebase.
=> tests: create helper functions to safely mutate global variables

pilot/pkg/networking/core/v1alpha3/accesslog_test.go, pilot/pkg/networking/core/v1alpha3/httproute_test.go, pilot/pkg/networking/core/v1alpha3/listener_builder_test.go, pilot/pkg/networking/core/v1alpha3/listener_test.go, pilot/pkg/networking/core/v1alpha3/listenertest/match.go, pilot/pkg/networking/core/v1alpha3/networkfilter_test.go, pilot/test/xdstest/extract.go
currently, Pilot listener tests are in a bit of disarray. We have a lot
of tests that are doing really hard to understand and not-useful checks
like `l[3].filters[4].chains[2] == xyz`. We use a bunch of legacy test
code paths that do not accurately resemble real world code paths.
This tries to clean things up a bit. It is a prereq for a few other PRs
I am working on.
The biggest change is a new listenertest package which adds declarative
testing logic for listeners.
=> pilot: cleanup listeners unit tests

releasenotes/notes/38429.yaml, samples/bookinfo/src/productpage/templates/productpage.html, samples/bookinfo/src/reviews/reviews-application/src/main/java/application/rest/LibertyRestEndpoint.java
Closes #38429 
Useful for multicluster setups, this has reviews pass its pod name as well as a cluster name (taken from the environment variable `CLUSTER_NAME`) in its response. Productpage will display this information (if no cluster name, it's omitted) below the reviews.
=> add pod and cluster information for reviews

pilot/pkg/networking/core/v1alpha3/listener_builder.go, pilot/pkg/networking/core/v1alpha3/listener_test.go
This is fixing a small regression in
https://github.com/istio/istio/pull/37198, which has not been shipped in
any Istio versions yet. Basically that accidentally added the ALPN
filter to inbound. This technically does nothing, since it only impacts
TLS origination which we don't do for inbound, but still better to keep
it out to retain old state + smaller config.
=> pilot: do not add ALPN filter to inbound filters

pilot/pkg/config/kube/gateway/controller.go
=> gateway-api: add lock when reading `AllowedReferences`

pkg/test/framework/components/echo/common/deployment/echos.go, pkg/test/framework/components/echo/common/deployment/namespace.go, pkg/test/framework/components/namespace/kube.go, pkg/test/framework/components/namespace/namespace.go
The echos are currently restricted to just the other echo namespaces, which prevents egress to the external authz server, if it's in another namespace.
This PR changes the logic so that egress is allowed to any namespace that has been allocated by the test framework up to the point the echos are created.
Fixes #38451
=> [tf] Support echo egress to ext-authz

docker/Dockerfile.distroless
Changes in #38344  result in a failure when building new pause images, pushing them to gcr.
Ex: https://storage.googleapis.com/istio-prow/logs/build-base-images_release-builder_periodic/1515042325611417600/build-log.txt
```
> [distroless-default] exporting to image:
------
error: failed to solve: failed commit on ref "index-sha256:d6409fdd8268333f8ed10ec1e07810e759278eee0c4c5cf78222228bb7d9e94a": cannot reuse body, request must be retried
```
=> Manual revert of #38344

go.mod, go.sum, pilot/pkg/config/kube/gateway/conditions.go, tests/integration/pilot/gateway_conformance_test.go
Without this, the Gateway will not come up when using revisions.
This also changes the behavior - the test apps will also be injected
with sidecars. This seems like a reasonable side effect.
=> gateway conformance: enable injection namespace labels

Makefile.core.mk
Based on an offline discussion with @ericvn @GregHanson, due to the 1.14 release timeline and the fact that Ubuntu Jammy is only released a week ago, we plan to leaving the transition to Ubuntu Jammy for Istio 1.15. The Ubuntu Focal currently used has an EOL until April 2025. Hence this PR to revert istio/istio#38575.
=> Revert "Update BASE_VERSION to master-2022-04-25T21-27-27"

pilot/pkg/networking/core/v1alpha3/gateway_test.go, pilot/pkg/networking/core/v1alpha3/listener.go
TCP MX filter looks for [`istio-peer-exchange` alpn](https://github.com/istio/istio/blob/master/pilot/pkg/xds/filters/filters.go#L153) before exchanging metadata. At gateways, for TCP transport protocol as well, `"h2", "http/1.1"` is being configured as alpn, which means tcp metadata exchange does not work between any sidecar and the (tcp)gateway.
This PR is configuring `istio-peer-exchange` as alpn for tcp case at gateways.
=> For TCP listeners at gateways, configure ALPNDownstreamWithMxc (istio-peer-exchange)

pkg/test/framework/integration/framework_test.go, pkg/test/framework/suitecontext.go, pkg/test/framework/test.go, pkg/test/framework/testcontext.go
I ran into a deadlock condition when running a number of nested parallel tests. Basically, some tests were stuck logging `Stuck waiting for parent test suites to terminate...`.
I recreated the issue in framework_test.go and the fix in this PR also fixes this test.
=> [tf] Fix deadlock for Parallel tests

pilot/pkg/features/pilot.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, releasenotes/notes/auto-sni-support.yaml
A later discussion concluded that it makes better sense
to introduce a new feature flag for enabling auto_sni,
and only auto_san_validation should be clubbed with existing VERIFY_CERT_AT_CLIENT feature flag.
[RFC](https://docs.google.com/document/d/1pTUl-Ng3nXAWJb7UGJtalftznpxQEfID/) has been updated accordingly.
- [ X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, …
=> introduce new feature flag for auto_sni

samples/bookinfo/src/details/details.rb, samples/bookinfo/src/productpage/productpage.py, samples/bookinfo/src/productpage/requirements.txt, samples/bookinfo/src/reviews/reviews-application/src/main/java/application/rest/LibertyRestEndpoint.java
This PR enhances the bookinfo sample application to propagate three headers containing potential token data:
- cookie
- jwt
- authorization
This was done to enable testing of more complex RequestAuthentication and AuthorizationPolicy logic with the sample apps.
In addition, I made a change to the productpage requirements for gevent (from 1.4.0 to 1.5.0) and greenlet (from 0.4.15 to 0.4.17).  This was to accommodate the latest version of Python (3.9) on Mac OSX 11.5.  
=> Added headers to propagate for token data

pilot/pkg/model/telemetry.go, pilot/pkg/model/telemetry_test.go, pilot/pkg/networking/core/v1alpha3/tracing.go, pilot/pkg/networking/core/v1alpha3/tracing_test.go, releasenotes/notes/38250.yaml
Adds control plane support for the new TracingSelector in the Telemetry API. This is needed to allow users to control differing sampling rates, providers, etc., for traffic that a workload originates rather than receives.
NOTE: I have not validated the behavior of this PR in cluster yet. This is being sent right now to allow for review and discussion over approach (as there is a parallel effort underway for logs).
Initial testing with:
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
name: mesh-default
spec:
tracing:
- match:
mode: SERVER
providers:
- name: zipkin
randomSamplingPercentage: 100
- match:
mode: CLIENT
providers:
- name: zipkin
randomSamplingPercentage: 13
```
Seems to indicate that proper `WorkloadMode` support exists and works.
- …
=> telemetry api: add support for TracingSelector

pkg/test/framework/components/echo/config.go, pkg/test/framework/components/echo/echotest/filters_test.go, pkg/test/framework/components/echo/instances.go, pkg/test/framework/components/echo/kube/instance.go, pkg/test/framework/components/echo/match/matchers_test.go, pkg/test/framework/components/echo/namespacedname.go, pkg/test/framework/components/echo/staticvm/instance.go
This is in support of https://github.com/istio/istio/pull/37914. This helps when using echo `instance`/`instances` within YAML templates.
=> [tf] Add test helper methods for echo

pilot/pkg/model/context.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go, pilot/pkg/networking/core/v1alpha3/networkfilter.go, pilot/pkg/networking/core/v1alpha3/networkfilter_test.go, pilot/pkg/networking/util/util.go, pkg/proto/merge/merge.go
The proto.Merge logic is problematic in a number of cases. In this instance, Duration does a blind merge of the `{Seconds, Nanoseconds}` struct, which means we end up adding these together. We have seen other areas where proto.Merge has caused problems as well.
This PR follows the path Kuma took, vendoring in the proto.Merge functinon from the protobuf library with support added for custom per-type merge functions. Code is mostly copied from them with attribution in the code (thanks!!). 
Currently, the only custom logic is Duration, but this gives us future flexibility
Fixes https://github.com/istio/istio/issues/38501
Fixes https://github.com/istio/istio/issues/38500 and reverts the original fix in https://github.com/istio/istio/pull/38522
cc @zirain @diranged
=> EnvoyFilter: use custom merge logic

istioctl/cmd/add-to-mesh.go, istioctl/cmd/describe.go, pilot/cmd/pilot-agent/main.go, pilot/cmd/pilot-discovery/app/cmd.go, pilot/pkg/bootstrap/server_test.go, pilot/pkg/model/context.go, pilot/pkg/security/trustdomain/bundle.go, pkg/adsc/adsc.go, pkg/config/analysis/analyzers/util/constants.go, pkg/config/analysis/analyzers/util/hosts.go, pkg/config/constants/constants.go, pkg/config/mesh/mesh.go, pkg/spiffe/spiffe.go, pkg/test/framework/components/echo/config.go, releasenotes/notesRelease/38597.yaml
Renamed DefaultKubernetesDomain to DefaultClusterLocalDomain as mentioned TODO in the **istio/pkg/config/constants/constants.go**
=> Fix: renamed DefaultKubernetesDomain to DefaultClusterLocalDomain

istioctl/cmd/proxystatus.go, pkg/kube/client.go, pkg/kube/client_factory.go
For https://github.com/istio/istio/issues/38621 (fixes 2/3 TODOs there).
Fixes a regression in istioctl runtime from 1.13->1.14, and improves on
the old 1.13 state.
Before: 15s to run a command
After: 3s
=> istioctl: optimized discovery time

pilot/pkg/model/sidecar.go, pilot/pkg/model/sidecar_test.go
If a service does not match the egress with an explicit namespace, fall back to match the wildcard one
Fixes #38556
=> Correct service matching logic of sidecar egress listeners

pilot/pkg/bootstrap/servicecontroller.go, pilot/pkg/config/kube/crdclient/client.go, pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go, pkg/kube/multicluster/cluster.go, pkg/kube/multicluster/clusterstore.go, pkg/kube/multicluster/secretcontroller.go
Before, every cluster use the same timeout boolean value, this is not right, thinking that a cluster can be added after the the boolean has been set
This pr also split the cluster and clusterstore out from secret controller, for good readability.
=> Fix cluster and kube controller sync

pilot/pkg/serviceregistry/serviceentry/controller.go, pilot/pkg/serviceregistry/serviceentry/conversion.go, pilot/pkg/serviceregistry/serviceregistry_test.go
Fix https://github.com/istio/istio/issues/38642
This is to make a determined order consistent with workload handler.
The priority is:
1. when see port name = wle port name. use the wle port.
2. use se target port
3. use se port number.
=> Fix ServiceEntry endpoint port setting order

pkg/wasm/cache.go, pkg/wasm/cache_test.go, releasenotes/notes/wasm-cache-with-tag-stripped-url.yaml
This PR is proposing use of URL which the tag or digest suffix is trimmed as a cache key in terms of OCI image cache.
In terms of URL for OCI images, two forms can be used.
- tagged form: docker.io/foo/image:bar
- digest form: docker.io/foo/image@sha256:1234567890abcdef
Basically, since the tag is just an alias for a specific version or digest, using (URL having no tag/digest + Digest) is much natural approach. Even in current implementation, the cached file is named with the digest.
Of course, to provide cache functionality for tagged URL as well, we additionally need to keep the map from the tagged URL to the digest according to the original meaning of tag.
Practically, there are two benefits:
1. In current implementation, without use of the digest(sha256) field in WasmPlugin, tagged …
=> Using tag/digest trimmed URL for OCI images and having tagged URL to digest

pkg/config/schema/collections/collections.gen.go, pkg/config/schema/metadata.gen.go, pkg/config/schema/metadata.yaml, releasenotes/notes/38496.yaml
fixes: #36114
This is a manual change instead of clean cherry-pick because this is a fix in the galley code which got removed with the[ removal of legacy galley code in 1.13](https://github.com/istio/istio/commit/d0748d7c46c02e1fddf77d7a38f90cb3620e4358)
- Reconcile invokes [analyzeWebhooks](https://github.com/istio/istio/blob/1.12.6/operator/pkg/helmreconciler/reconciler.go#L168) 
- analyzeWebhooks creates an instance of source analyzer, `sa`, with config schema, resources read from[ `metadata.yaml`](https://github.com/istio/istio/blob/a0c7a3355331ef20354e3e1682dc13b7e6bcf4c1/pkg/config/schema/metadata.yaml#L276-L281). In this file, webhooks are not mentioned as `clusterScoped: true` and this is the cause of the issue. 
- …
=> [release-1.12] Fix mutatingwebhook analysis

pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/gateway_test.go, pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/listener_inbound.go, pkg/config/gateway/gateway.go
This is a follow-up PR on https://github.com/istio/istio/pull/38499. In that PR we added `istio-peer-exchange` as the additional alpn in the downstreamTlsContext at the gateways. We ended up doing this alpn change for both the http and tcp servers.
As pointed out by @howardjohn [here](https://github.com/istio/istio/pull/38499#discussion_r862968318), this was a divergence from the inbound listeners at sidecars istio-peer-exchange is added only in the tcp case.
This PR has changes to ensure that inbound listeners are consistent at gateways and sidecars and no new alpn gets added for http servers at gateways.
=> Telemetry: make sure istio-peer-exchange is configured only at terminating tcp servers

pilot/pkg/model/virtualservice.go, pilot/pkg/model/virtualservice_test.go, pkg/config/validation/virtualservice.go, pkg/config/validation/virtualservice_test.go
This PR allows regex in delegates when there is one regex either at root or delegate and if regex is specified in either delegate or root, no other matching condition can be specified.
=> allow regex in delegates

pilot/pkg/model/extensions.go, pilot/pkg/model/extensions_test.go, pkg/istio-agent/xds_proxy_test.go, pkg/wasm/cache.go, pkg/wasm/cache_test.go, pkg/wasm/convert.go, pkg/wasm/convert_test.go, releasenotes/notes/wasm-pull-policy.yaml
https://github.com/istio/istio/issues/35607
Implement [WasmPlugin image pull policy ](https://github.com/istio/api/blob/b6a03a9e477eb918b7e3105aaa00529183e4f82a/extensions/v1alpha1/wasm.proto#L241).
Similar with [ImagePullSecret of Wasm](https://github.com/istio/istio/pull/37161), ImagePullPolicy of Wasm is sent to istio-agent through the environment variables of ECDS. 
The policy is used in the internal Wasm binary cache of istio-agent to follow the [definition](https://github.com/istio/api/blob/b6a03a9e477eb918b7e3105aaa00529183e4f82a/extensions/v1alpha1/wasm.proto#L234-L240)
=> Implement WasmPlugin image pull policy

pilot/cmd/pilot-agent/options/options.go, pkg/wasm/cache.go, pkg/wasm/cache_test.go, pkg/wasm/httpfetcher.go, pkg/wasm/httpfetcher_test.go, releasenotes/notes/wasm-https-insecure-support.yaml
Supports InsecureSkipVerify of TLSClientConfig option in http fetcher as well.
In addition, instead of setting timeout on HTTP Client, use context-based timeout in order to match the API pattern with image fetcher.
- [ * ] Policies and Telemetry
=> Support TLSVerifySkip in http fetcher, and use context-based timeout

pkg/kube/controllers/common.go, pkg/kube/controllers/common_test.go
Currently we use the object name, but supposed to be parent name
This doesn't matter in all current usages as they are always the same,
but for some in-development stuff it is important to use the right one.
=> Fix name used in EnqueueForParentHandler

pkg/test/env/istio.go, pkg/test/framework/components/echo/cmd/echogen/testdata/golden.yaml, pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/components/echo/kube/testdata/basic.yaml, pkg/test/framework/components/echo/kube/testdata/healthcheck-rewrite.yaml, pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions-no-proxy.yaml, pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions.yaml, pkg/test/framework/components/echo/kube/testdata/multiversion.yaml, pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml, pkg/test/framework/resource/flags.go, pkg/test/framework/resource/settings.go
This PR updates the integration tests to prepare for tests with gRPC C++
- Changed the flag format because C++'s flag parsing library only supports `--a=b`.
- Added a new environment variable `ECHO_IMAGE` for echo image, so it can be changed to point to the C++ image
- Changed readiness probe to use TCP instead of HTTP when echo image is set because C++ doesn't have an easy way to start an HTTP server
=> tests: update deployment.yaml for gRPC C++ PSM tests

pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go, releasenotes/notes/38750.yaml
Found a bug where HTTP and Network Filters are not removed when a patch first creates a filter, and subsequently another patch removes the filter.
Use Case: Adding a namespace filter followed by a subsequent filter excluding the first with a workloadSelector label.
=> pilot: fix EnovyFilter inline patch removal

pilot/pkg/features/pilot.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/serviceregistry/serviceentry/conversion.go, pilot/pkg/serviceregistry/serviceentry/conversion_test.go, releasenotes/notes/38650.yaml
This CL attempts to ensure that the metadata for outgoing traffic to mesh-external services represented by ServiceEntry includes canonical service information. This will allow treatment (in client-side metrics/logs/etc.) of external services with Service Entries as proper "Istio Canonical Services" (in a fashion). NOTE: the labeling is not applied to the ServiceEntries themselves.
Here is a worked example with this code:
In a 1.13.3 mesh, with no service entry, using a sleep pod with queries like:
`k exec -it deploy/sleep -- curl http://httpbin.org/status/202`
Base: Without a ServiceEntry and Without this CL (unimportant labels redacted):
```
istio_requests_total{
response_code="202",
reporter="source",
source_workload="sleep",...
destination_workload_namespace="unknown", …
```
=> service entry: add canonical service information

pkg/test/framework/resource/flags.go
Otherwise something like `--istio.test.skipWorkloads=vm,tproxy,delta`
will not work which leads to obscure errors
=> tf: allow CSV inputs to skip workloads

pkg/kube/client.go
Protobuf is more efficient compared to json. Currently crd does not support protobuf  content type.
=> Make use protobuf codec for k8s api resources

pkg/test/framework/components/istio/operator.go, tests/integration/security/ca_custom_root/secure_naming_test.go, tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go, tests/integration/security/ca_custom_root/trust_domain_validation_test.go, tests/integration/security/util/cert/cert.go
**We are updating the cacerts even if it is present in istiod, that creates conflict and the main reason for a lot of ca custom root multicluster test failure. In this PR, I have removed the logic for updating the cacerts if it is present in the istio-system**
=> fixed the multicluster tests failure for ca custom root tests

istioctl/pkg/util/handlers/handlers.go, istioctl/pkg/util/handlers/handlers_test.go, pilot/pkg/config/kube/gateway/conversion.go, pilot/pkg/config/kube/gateway/deploymentcontroller.go
This allows things like `istioctl proxy-config listeners gateway/my-gateway`. Also
included some bug fixes for namespace resolution (which is valid even
without the Gateway part).
=> istioctl: support `gateway` as input type

pkg/test/env/istio.go, pkg/test/fakes/imageregistry/Dockerfile, pkg/test/fakes/imageregistry/Makefile, pkg/test/fakes/imageregistry/main.go, pkg/test/framework/components/registryredirector/container_registry_server.yaml, pkg/test/framework/components/registryredirector/kube.go, pkg/test/framework/components/registryredirector/registry_redirector_server.yaml, pkg/test/framework/components/registryredirector/registryredirector.go, tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go
To give more flexibility and clarity, this PR proposes following changes:
1. Renaming from `containerregistry` to `registryredirector` to prevent misconception.
2. Re-org Makefile for `fake/imageregistry`
3. Using JSON format for setting/retrieving the tag map
4. Providing a way to set the target registry (previously, fixed to `gcr.io`)
=> Refactoring and extending `registryredirector` (formerly `containerregistry`) integration test component

pilot/pkg/model/service.go, pilot/pkg/model/validation.go, pkg/bootstrap/option/instances.go, pkg/config/constants/constants.go
1. Add necessary constants for dual stack support 
2. Add new field `DefaultAddresses` and behavior for Istio service
=> [Istio dual stack support] Add constants and new field for Istio service

pilot/pkg/model/gateway.go, pilot/pkg/model/gateway_test.go, pilot/pkg/networking/core/v1alpha3/gateway.go, pkg/config/gateway/gateway.go, pkg/config/gateway/gateway_test.go
1,  IsTLSServer is very hard to understand.  Rename to IsTLSServerForNonHTTP
2. Add IsHTTPSServerWithTLSTermination to replace gateway.IsTLSServer(server) && gateway.IsHTTPServer(server)
=> Refactor gateway server tls adjugement 

pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/metrics_no_statsd_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json, tools/packaging/common/envoy_bootstrap.json
access_log_path in admin is deprecated in 1.18 https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.18/v1.18.0.html?highlight=access_log_path#deprecated.
=> remove deprecated access_log_path in bootstrap

pkg/test/framework/components/namespace/kube.go
Currently, the logic for creating a namespace is slightly different in `newKube` vs `claimKube`, but it shouldn't be. This change extracts the logic into a common function. Also does some general cleanup to consolidate code.
=> [tf] Consistent namespace creation

pilot/pkg/serviceregistry/kube/controller/autoserviceexportcontroller.go, pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/util.go
It is confusing to see `convertToService` (which extracts obj from interface) and `CovertService` which actually converts to istio service called one after the other. This PR renames the first one as "extractService"
=> minor renaming of function

pkg/wasm/cache.go, pkg/wasm/cache_test.go
Currently, when the module cache of WasmPlugin hits, the checksum cache is not updated.
This may cause inefficiency when the same image was referenced by the two different tags as well as is not an intended behavior.
This PR fixes it by adding `touchEntry` to update the checksum cache when the module cache hits.
=> WasmPlugin: Fix to update the checksum cache when the module cache hits

pkg/istio-agent/agent.go, security/pkg/nodeagent/sds/server.go
initWorkloadSdsService checks for uds path async and before it returns we log the message "SDS server started". This PR fixes that along with other minor refactor.
=> fix incorect sds logs

pilot/pkg/bootstrap/webhook.go
Reduce log level for the webhook server's TLS handshake error to debug to avoid flooding the log in case multiple probes are hitting :8080/ready concurrently.
Background: Pilot-discovery invokes its own webhook readiness server at :15017/httpsReady when receiving a readiness request on :8080/ready. This is done using the webhook readiness client based on http.Client.
The default behavior of http.Client is to reuse an already established TCP connection to the host if possible or otherwise to initiate one. When multiple readiness requests coincide, such as when both readiness and liveness probes are hitting the same endpoint, the webhook readiness client can encounter situations where the initial TCP connection is busy serving the first probe. …
=> Add custom ErrorLog handler to webhook server

pilot/pkg/networking/core/v1alpha3/listener_builder.go, pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
The function _patchOneListener,_ that applies the EnvoyFilter patches in the listener, is called in [buildHTTPProxyListener()](https://github.com/istio/istio/blob/bb93b2a69c73c0b3cbdb2f262e36a3e67bb369f5/pilot/pkg/networking/core/v1alpha3/listener_builder.go#L91). However, the _envoyFilterWrapper_ is only populated in the [patchListener()](https://github.com/istio/istio/blob/bb93b2a69c73c0b3cbdb2f262e36a3e67bb369f5/pilot/pkg/networking/core/v1alpha3/listener_builder.go#L145), so the call to _patchOneListener_ in _buildHTTPProxyListener()_ do not apply any changes to the listener created for the HTTP Proxy.
So, to fix this bug, the _patchOneListener_ for the HTTP Proxy listener moved to inside the _patchListener()_, where the other listener are patched. A new test were added to ensure that …
=> EnvoyFilter is also applied to HTTP Proxy Listener

pkg/test/echo/docker/Dockerfile.app_sidecar_base, pkg/test/echo/docker/Dockerfile.app_sidecar_base_centos
This is in part to force a rebuild of the base images, now that the regex has been expanded to detect changes to the echo base images (https://github.com/istio/test-infra/pull/4047).
=> [tf] Add more utils to echo containers

pkg/test/framework/resource/config/apply/option.go
If we do this long term we should probably remove the option entirely.
For now, just hack it out to see the impact.
Currently wait is broken, so each wait waits 5s. This adds up 14minutes on security MC tests
=> tf: disable wait on YAML

pkg/test/echo/server/endpoint/grpc.go, pkg/test/echo/server/endpoint/http.go, pkg/test/echo/server/endpoint/tcp.go, pkg/test/echo/server/endpoint/util.go
PR https://github.com/istio/istio/pull/37914 is seeing VMs crashing due to file descriptor exhaustion. This PR attempts to improve the way that the echo servers are handling server-side connections, allowing connections to close more quickly.
=> [tf] Improve echo server connection handling

pkg/test/framework/components/echo/calloptions.go
This is really more of an RFC. The attempt here is to help reduce the overall test time and the amount of traffic we're sending for each test.
Many of our tests attempt to hit all clusters, and they do this by setting `count = 5 * num workloads`. However, the default converge value is 3 and the number of clusters in our multi-cluster setup is also 3, which means that the number of actual requests on the wire would be `converge * 5 * num workloads` = `3 * 5 * 3` = `45`.
In these cases it's not clear if converge is helpful. If we're already sending enough traffic to guarantee we're hitting each cluster and everything passes, do we need to do it all over again?
This PR disables converge for cases where `count > converge`. In the previous example, that would mean that a typical call would …
=> [tf] Reduce test traffic from converge

pilot/pkg/networking/util/util.go, pilot/pkg/security/authn/utils/utils.go
While investigating how the selection of ALPN protocols for inbound listeners is implemented, I noticed that the conditions could be simplified, because we have duplicated variables with the protocol list.
=> Simplify ALPN protocols selection for inbound listener

pilot/cmd/pilot-agent/status/server.go, pilot/pkg/xds/xdsgen.go, pkg/istio-agent/agent.go
Change-Id: I8c9d3a77bb59f19fe223b291781b8d5e102f4bd0
Fix few critical gRPC bugs:
- no certificate rotation
- attempt to send delta which is not supported by gRPC, resulting in lost listener.
Less critical:
- keep scraping envoy which doesn't exist.
Merged manually since cherry-pick didn't work.
=> Backport gRPC fixes to 1.14 branch

pilot/pkg/serviceregistry/aggregate/controller.go
Without this log does not include providerID
2022-05-19T00:59:28.748040Z	info	Registry for the cluster processing-cluster has been deleted.
=> fix log line in aggregate controller

pkg/wasm/cache.go, pkg/wasm/cache_test.go, releasenotes/notes/wasm-insecure-all.yaml
This PR proposes to add a feature to allow all insecure servers when one of the host name in the environment variable WASM_INSECURE_REGISTRIES is *.
Originally proposed as a part of https://github.com/istio/istio/pull/38918, but split as a feature PR.
cc: @zirain
=> Allow all the insecure servers when WASM_INSECURE_REGISTRIES has a "*"

pilot/pkg/networking/core/v1alpha3/gateway.go, pkg/wasm/cache.go, pkg/wasm/cache_test.go
This PR proposes to change the file path scheme of the cached wasm module.
Currently, the filename of the wasm module is determined by its checksum.
But, the cache itself uses checksum & canonicalized URL as a key of the cached module, there might be inconsistency.
For example, if the same image is downloaded from the different URL, the wasm file can be purged while one of the cache entry is still pointing the wasm file.
This solves the first issue in https://github.com/istio/istio/issues/39063:
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1527648505185701888
=> WasmPlugin: Change the file path scheme of the cached wasm modules

tests/integration/telemetry/stats/prometheus/customizemetrics/customize_metrics_test.go, tests/integration/telemetry/stats/prometheus/nullvm/dashboard_test.go, tests/integration/telemetry/stats/prometheus/nullvm/istioctl_metrics_test.go, tests/integration/telemetry/stats/prometheus/stats.go, tests/integration/telemetry/stats/prometheus/wasm/bad_wasm_filter_test.go, tests/integration/telemetry/stats/prometheus/wasm/stats_wasm_filter_test.go, tests/integration/telemetry/util.go
This brings consistency with the security and pilot tests of using the
same core deployment everywhere. In particular, I was motivated by
https://github.com/istio/istio/pull/38495/files#diff-b3848f393e9a44a4e5f8cdb34f9f5715eab5fa22f975870ddce60ee29cddab86R224
which is doing external traffic -- the common deployment has a
standardized (and, IMO, safer) way of doing this that can easily be
utilized with this change.
=> telemetry tests: use standard deployment for echo

tests/integration/telemetry/stats/prometheus/stats.go
Removing remaining `appNsInst`. The original PR is https://github.com/istio/istio/pull/39051.
=> Use `apps cdeployment.SingleNamespaceView` instead of appNsInst

pilot/pkg/model/push_context.go, pilot/pkg/model/sidecar.go, pilot/pkg/model/sidecar_test.go, pkg/util/sets/int.go, pkg/util/sets/int_test.go
Fixes issue: https://github.com/istio/istio/issues/38725
When constructing the SidecarScope, if a sidecar listed a dependency
on a virtual service, istio will currently add a dependency for the
sidecar on each transitive dependency of that virtual service,
including all ports that each transitive dependency exposes. This
change now filters the ports on those transitive dependencies down
to only those to which the virtual service will route. This allows users
to have services that expose hundreds of ports, but set a specific
hostname for a specific subset of those ports using a virtual service,
and istio will only propagate the configuration needed to route to
that subset of ports.
@hzxuzhonghu @howardjohn 
@yingzhuivy 
Contins behavior changes …
=> sidecar: filter service ports to VS ports

pilot/pkg/leaderelection/leaderelection.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go
Namespace controller is an optional component only started when kubernetes CA is used but webhook patching is needed in all cases.
https://github.com/istio/istio/pull/38283 combined both of them. 
This PR fixes it.
=> separate webhook patching from namespace controller

pkg/test/framework/resource/flags.go, pkg/test/framework/resource/settings.go, pkg/test/framework/runtime.go, pkg/test/framework/suitecontext.go, pkg/test/framework/testcontext.go
When a suite has a lot of tests and there is some change that causes a number of tests to fail, the test output can be so large that prow will fail to show the results.
This PR limits the maximum number of test dumps allowed per test suite to 10 by default (settable via a new flag).
=> [tf] Limit number of test dumps

pilot/pkg/credentials/kube/multicluster.go, pilot/pkg/model/virtualservice.go, pkg/kube/multicluster/secretcontroller.go
The `localCluster` is confusing in external istiod model.  #38654 is trying to add local secret watch, which makes the` localCluster `especially confusing.
Actually, local cluster means primary cluster. And primary is also widely used in official docs.
=> Refactor: renaming localCluster to configCluster

pkg/istio-agent/xds_proxy.go
This PR prevent using `forwardToEnvoy` function in multiple threads.
Potentially, calling from multiple threads may cause blocking the loop in `handleUpstreamResponse`.
In details, as commented in https://github.com/grpc/grpc-go/blob/e41f868588c99493b35169e258a11b2ce128e139/stream.go#L1416-L1418, we should not call `SendMsg`, which is called by `forwardToEnvoy` at last, in multiple threads.
This fixes the second/third issues in https://github.com/istio/istio/issues/39063 .
=> [BugFix] WasmPlugin: Call forwardToEnvoy in the same thread

pilot/pkg/autoregistration/controller.go, releasenotes/notes/39201.yaml
when WorkloadEntry.Annotations is nil , pilot panic
The premise condition：
Istio official recommended workloadEntry automatic registration, but also supports user-defined.
When the user custom WorkloadEntry and WorkloadEntry.Annotations is nil , then cause the pilot panic.
test release > 1.10+
=> > fix pilot panic with vm workload entry: assignment to entry in nil map

pilot/pkg/model/service.go, pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/route/route.go
Fixed issues:
1. Symbols of `inbound6` and `outbound6` can only be used by IPv6 only service if dual stack is enable
2. Symbols of `inbound` and `outbound` can be used by IPv4/IPv6 only service if dual stack is disable
Old version with dual stack enabled:
New version with dual stack enabled:
As seen above, both the ipv4(simpleserver-ipv4) and ipv6(simpleserver-ipv6) services use the same symbols `outbound6` for the cluster resource in old version, and they use the different symbols in new version.
=> [Dual Stack] Fixed issues for inbound and outbound routes and clusters configurations

pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/route/route.go
Fix issues for gateway to make dual stack enable. 
If dual stack is enable in k8s cluster, but deploy applications are deployed without setting the IP families (the service of applications would be single stack as IPv4 by default)
Old version:
the route configuration of applications  virtual service may randomly be 404 which depends on the RDS sync situation, showing as below:
It is fixed in new version,
=> [Dual Stack] Fix issues for gateway to make dual stack enable

pilot/pkg/xds/endpoint_builder.go, releasenotes/notes/38704.yaml
fixes https://github.com/istio/istio/issues/39227
=> [release-1.13] multi-network: fix eastwest gateway endpoint filtering (#38762)

tests/integration/security/authz/main_test.go
See https://github.com/istio/istio/issues/39255
Currently 25-40% of jobs are failing on this:
https://prow.istio.io/?job=integ-security-multicluster_istio which is
slowing down development
=> Skip authz tests while flakes are investigated

pilot/pkg/leaderelection/k8sleaderelection/k8sresourcelock/leaselock.go, pilot/pkg/leaderelection/k8sleaderelection/leaderelection_test.go
Time: Compound literals should use key-value fields
=> Time: Compound literals should use key-value fields

istioctl/cmd/google.go, istioctl/cmd/kubeinject.go, istioctl/pkg/clioptions/central.go, istioctl/pkg/multixds/gather.go, istioctl/pkg/multixds/google.go, istioctl/pkg/xds/client.go, istioctl/pkg/xds/google.go, pilot/pkg/model/context.go
This makes istioctl:
a) Recognize proxied ASM Managed Control Plane webhook URLs
b) Use both ADC and K8s credentials to call ADS when proxied by ASM Managed Control Plane
c) Pass the Cloud Run URL in proxied ADS requests
d) Use ADS to call webhook when proxied by the ASM Managed Control Plane
=> Support double authentication in istioctl

cni/pkg/log/uds.go, cni/pkg/log/uds_test.go
Currently the UDS logger defaults to `info` logs and is not configurable to increase the logging level.  Because the UDS logger is simply a relay for the CNI plugin, it should default to the highest level the plugins allows (`debug`).
This PR sets the UDS logger to debug by default.
=> CNI UDS logger should accept log level of sender

pkg/test/framework/components/istio/eastwest.go, pkg/test/framework/components/istio/ingress.go, pkg/test/framework/components/istio/ingress/interface.go, pkg/test/framework/components/istio/istio.go, pkg/test/framework/components/istio/operator.go, pkg/test/framework/components/istio/util.go
Right now it can only be used in istio-system with the `istio=...`
label. This allows arbitrary namespaces and labels to be used. Also
cleans up some dead code.
=> tf: make Ingress component more flexible

tests/integration/security/authz/authz_test.go, tests/integration/security/authz/main_test.go
Based on [recent flakes](https://github.com/istio/istio/issues/39255) the egress test appears to be very flaky.
As a temporary fix, we accidentally [disabled](https://github.com/istio/istio/pull/39280) all authz tests.
This PR re-enables the authz test suite, but disables only the egress test.
=> [tf] re-enable authz tests except for egress

pilot/cmd/pilot-agent/status/server.go, pilot/cmd/pilot-agent/status/util/stats.go, pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/security/authn/v1beta1/policy_applier.go
Fixed issues for IPv4 and IPv6 compat for prometheus and applications stats metrics scraping
Get following error when enable pilot-agent stats metrics scraping:
```
2022-06-07T03:43:01.067302Z     error   failed scraping envoy metrics: error scraping http://localhost:15090/stats/prometheus: Get "http://localhost:15090/stats/prometheus": dial tcp [::1]:15090: connect: connection refused\
2022-06-07T03:43:14.939616Z     error   failed scraping envoy metrics: error scraping http://localhost:15090/stats/prometheus: Get "http://localhost:15090/stats/prometheus": dial tcp [::1]:15090: connect: connection refused\
2022-06-07T03:43:26.783580Z     info    Agent draining Proxy\
2022-06-07T03:43:26.783582Z     info    Status server has successfully terminated\
```
=> [Dual Stack] Fixed issues for IPv4 and IPv6 compat for prometheus and applications stats metrics scraping

pilot/pkg/features/pilot.go, pkg/kube/multicluster/secretcontroller.go, pkg/test/framework/components/istio/operator.go, pkg/test/framework/components/istio/util.go, releasenotes/notes/31946.yaml, tests/integration/pilot/localwatcher/localsecretwatcher_test.go
Fixes #31946 Allow Istiod to watch for local secret resources
Currently when Istiod runs as an external control plane, Istiod
only watches for secrets in a namespace of the config cluster. This
fix will also allow Istiod to watch for the secrets created in the
namespace where Istiod is actually running on the external control
plane cluster.
=> Fixes #31946 Allow external Istiod to watch for local secret resources

tests/integration/pilot/multicluster_test.go
In some environments outside of KinD, just getting to the container start step may be delayed. This waits for that first before imposing the smaller timeout on readiness.
=> TestBadRemoteSecret: wait for containers to ready before status check

pilot/pkg/config/kube/crd/conversion.go
We recently added support for multi-version yaml reading, but didn't update this part
=> pilot test: allow version aliases in CRD reader

tools/docker
This was original turned off to fine-tune the crane builder; the thought
was size of RAM > size on images, so we don't really need to GC and we
shave off a few ms. However, this actually propogates down to a lot of
other calls, including the buildx call. This results in OOMs in some
environments trying to build. IMO the perf improvements are so small its
not really worth keeping it at all.
=> docker: enable GC

pilot/pkg/serviceregistry/kube/controller/multicluster.go
We have two problems with multi cluster add/update events because we are using Add + Delete for Update
- For Update we are triggering push (because we reuse Delete)
- The locks are inconsistent between ClusterDeleted and ClusterAdded calls in ClusterUpdated as those functions take locks independently - there is no unified locking in update.
This PR fixes both
=> refactor multi cluster add and update events

pilot/cmd/pilot-agent/main.go, pilot/cmd/pilot-agent/status/server.go
Fixed bug for istio-agent status server, should respect the value of InstanceIP for the pod when new a status server.
=> [Dual Stack] Fixed bug for istio-agent status server

pkg/wasm/cache_test.go, pkg/wasm/httpfetcher.go, pkg/wasm/httpfetcher_test.go, releasenotes/notes/wasm-decompress.yaml
Decompress or/and untar the wasm binary when it is pulled via HTTP/HTTPS.
By this, we can support the compressed stream as well (even with the wrong `content-type`)
In details, when pulling bytes from HTTP/HTTPS server, if the bytes do not have proper magic number for Wasm Binary, 
tries to ungzip or untar based on the magic numbers of each fileformat.
In case of `untar`, this PR assumes that there is only one file in the same sense that OCI Image specification for Wasm binary.
Basically, it does the best effort based on the magic number of bytes.
If it fails to decompress or untar, just uses the original bytes.
Basically, the original idea came from https://github.com/istio/istio/pull/39225#issuecomment-1144207752.
=> Decompress or untar the wasm binary if it is needed when pulling it via HTTP/HTTPS

pilot/pkg/xds/ecds.go
In ECDS we verify proxy's VerifiedIdentity for sending config for pulling secrets. But if Istiod runs behind gateway/proxy that terminates TLS, people disable XdsAuth but the proxy is still trusted. So we should only verify identity if XdsAuth is enabled.
=> only check for verified identify if xds auth is enabled

pkg/kube/multicluster/secretcontroller.go, releasenotes/notes/39366.yaml
Fix: #39366
The root cause is that we never stop the previous remote cluster when updating the secret.
=> Stop previous remote cluster when updating secret

pkg/channels/unbounded.go, pkg/channels/unbounded_test.go, pkg/istio-agent/xds_proxy.go, pkg/istio-agent/xds_proxy_delta.go, releasenotes/notes/xds-push-deadlock.yaml
Fixes https://github.com/istio/istio/issues/39209.
This is a pretty complex issue; see the comments in the PR and the
original issue for more discussion
I had a really hard time adding a test for this. I tried for a while. What I did manually was to deploy 8 test namespaces at once (this is a large load, XDS is like 5mb each...). Before, it was almost always 5-10 pods stuck. With this, only delta pods got stuck because I hadn't yet fixed delta xds.
=> Fix potentional deadlock between xdsproxy and Istiod

pilot/pkg/xds/endpoint_builder.go, releasenotes/notes/38704.yaml
This reverts commit 097fed9817564fbb9ee33c55db245c2c226f52b9.
Fix https://github.com/istio/istio/issues/39334.
=> Revert "multi-network: fix eastwest gateway endpoint filtering (#38762) (#39275)"

pkg/test/fakes/imageregistry/Makefile, pkg/test/fakes/imageregistry/main.go, pkg/test/framework/components/registryredirector/registry_redirector_server.yaml
This PR introduces new API on the registry redirector:
- A request comes with the form of `/layer/v1/<image_name>:<tag>`.
- If the tag is registered in `tagMap`, it is converted to the mapped one.
- Getting the manifest corresponding to the converted tag and image name
- Returns the first layer's URL
This is a preparation stop for adding the integration test of "Loading Wasm via HTTP".
=> Add new API on the registry redirector which redirects to URL for the first layer

pkg/kube/multicluster/secretcontroller.go, releasenotes/notes/39366.yaml
=> [Release-1.14] Stop previous remote cluster when updating secret 

istioctl/cmd/wait.go
Running the example will have the error:
```
istioctl experimental wait --for=distribution --threshold=.99 --timeout=300 virtualservice bookinfo.default
Error: invalid argument "300" for "--timeout" flag: time: missing unit in duration "300"
```
=> Fix x wait example

Makefile.core.mk
Removes a comment referencing `dep` in the Makefile.
I noticed this while trying to understand the Makefile, there isn't any Gopkg.lock file presumably since the repo was migrated from dep to go.mod at some point. The target just seems to be an alias for `init` now.
=> Remove dep reference from Makefile.core.mk

pkg/test/env/istio.go, pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/components/echo/kube/deployment_test.go, pkg/test/framework/components/echo/kube/testdata/proxyless-custom-image.yaml, pkg/test/framework/components/echo/kube/testdata/proxyless.yaml, pkg/test/framework/resource/flags.go, pkg/test/framework/resource/settings.go
Usage: Set `GRPC_ECHO_IMAGE` env to some image that implements `echo` + a special flag --forwarding_address (https://github.com/grpc/grpc/pull/30005).
Effect: Any proxyless gRPC echo app will split the Echo across two containers, one for gRPC, one for everthing else. 
---
This is to support testing Proxyless gRPC implementations in other languages (C++, Java). We have to implement `echo` to use Istio's integration tests, but it would be a burden to implement all of the echo protocols in these languages and keep implementations in sync across languages. 
What we do here is described in this [doc](https://docs.google.com/document/d/1YVod8JoQhQ3zRRM1mVsuy006bjEMIm71dGx_PX2V2B4/edit#). TL;DR: running a second container with the the normal Go app to handle non-gRPC. 
cc @yashykt
=> [tf] allow using custom image for echo gRPC

pkg/test/framework/components/registryredirector/registry_redirector_server.yaml, tests/integration/telemetry/stats/prometheus/wasm/imagepullpolicy_test.go, tests/integration/telemetry/stats/prometheus/wasm/stats_wasm_filter_test.go, tests/integration/telemetry/stats/prometheus/wasm/testsetup.go
Adding new integration test case for testing the remote load of Wasm and Image Pull Policy when using HTTP.
Basically, the test scenario is exactly the same with OCI Image case except consideration of `latest` tag.
=> WasmPlugin: Add the integration test for remote load of Wasm & image pull policy through HTTP

pilot/cmd/pilot-agent/main.go, pilot/cmd/pilot-agent/status/server.go
Fixed bug for stats metrics scraping errors when using different IP families, InstanceIP is the pod ip the gateway pod IP, such as ingress gateway
1. Let InstanceIP decide the IP family when initializing the StsServer
2. Let InstanceIP decide the IP family when initializing the Status Server
=> [Dual Stack] Fixed bug for stats metrics scraping errors when using different IP families

tests/integration/iop-remote-integration-test-gateways.yaml, tests/integration/security/sds_ingress/quic/ingress_test.go
**QUIC based tests are failing for GKE 1.21, reverting it to the original configuration**
=> rollback QUIC tests to previous configuration

pkg/test/framework/analyzer.go, pkg/test/framework/suite.go, tests/integration/pilot/localwatcher/localsecretwatcher_test.go
Added RequireExternalControlPlaneTopology method so that only
the tests which test external control plane will run, other
tests can be skipped to save some CPU cycles.
=> Optimize test so that some tests can be skipped

pkg/test/framework/analyzer-allowlist.yaml, pkg/test/framework/analyzer.go
This can't catch `if len(clusters) > 1 {skip}` but its a step
=> [tf] don't allow new single cluster suites

pilot/pkg/model/xds_cache.go, pilot/pkg/xds/bench_test.go, pkg/util/sets/string_pointer.go, pkg/util/sets/string_pointer_test.go
This reduces memory for case when n configs influence one xds key.
Inner struct is 👍 
C(0)->key0(copied)
C(1)->key1(copied)
C(n-1)->key n-1(copied)
A string struct holds 16 bytes, and here the total mem is n * 16 bytes
With the patch, the total mem will be n * 8 
=> Optimize: make use of string pointer map to reduce mem cost of xds keys

tools/docker-builder/builder/crane.go, tools/docker-builder/common.go, tools/docker-builder/crane.go, tools/docker-builder/docker.go, tools/docker-builder/main.go, tools/docker-builder/types.go
Fixes https://github.com/istio/istio/issues/37877
This introduces support in the docker builder to orchestrate multi-arch
docker builds. Previously, it was required to call the builder twice
with each arch; this doesn't allow aggregating into a single multi-arch
image though.
For docker builder, this is fairly straightforward. We mostly need
changes to allow plan file to be arch-specific, and to call make
multiple times per-arch.
For crane builder, a little more complex since we need to allow passing
multiple plans to it and then deciding whether to make a Index or direct
Image.
For https://github.com/istio/istio/issues/26652#issuecomment-1155682106
=> docker: support multi/cross-architecture builds

istioctl/cmd/proxyconfig.go, istioctl/pkg/util/configdump/endpoint.go, istioctl/pkg/util/configdump/util.go, istioctl/pkg/writer/envoy/configdump/endpoint.go
This introduces new functionality into `istioctl proxy-config` to pull from EDS. This is subtly different from the current `endpoints` which pulls from /clusters. Unfortunately, neither is a superset of the other -- `/clusters` has the Outlier Detection status which we output, while EDS has locality, metadata, etc. To avoid breaking changes by simply moving, or confusion by two similar commands, this introduces a new `eds` mode but _hides it_ - open to other ideas here.
=> istioctl: initial eds dump

pilot/pkg/model/service.go, pilot/pkg/xds/eds.go, pilot/pkg/xds/eds_test.go, pilot/pkg/xds/endpoint_builder.go, pilot/pkg/xds/ep_filters.go
This was initially added to support HBONE, but hasn't been used since implemented. I think the real implementation direction is going for a different approach, so we can clean this up.
Essentially reverts https://github.com/istio/istio/commit/86b87f2f923c62344a1887b47adbc69bd6c2ddaa
=> pilot: drop tunnel-ability implementation

tests/integration/pilot/forwardproxy/envoy_config_generator.go
This change should fix failing [integ-ipv6_istio_postsubmit](https://prow.istio.io/view/gs/istio-prow/logs/integ-ipv6_istio_postsubmit/1537216363188195328) job.
=> Fix tunneling tests on IPv6 stack

tests/integration/telemetry/stats/prometheus/wasm/wasm_modules/header_injector/plugin.cc
Fix the wrong stringify macro. It was mistakenly not included in the previous PR.
=> Wasm: Fix improper stringify, which was omitted in previous commit

tests/integration/pilot/forwardproxy/envoy_config_generator.go, tests/integration/pilot/testdata/tunneling/destination-rule.tmpl.yaml, tests/integration/pilot/tunneling_test.go
This change aims to fix failing [integ-ipv6_istio_postsubmit](https://prow.istio.io/view/gs/istio-prow/logs/integ-ipv6_istio_postsubmit/1537798303050108928). My previous PR was not enough to fix broken tests, but I dived deeper and tested it locally, and now I'm sure that this change will fix failing tests.
There were 2 reasons why tunneling was failing on dual stack:
1. Envoy should listen on `::` when dual-stack is enabled.
2. DNS lookup works differently for IPv4 and IPv6 - I am not sure why, but I captured DNS queries with wireshark and I observed that for IPv6 address the DNS resolver sends queries for all search domains, but not for the received FQDN as is. On the other hand, when IPv4 is used, the DNS resolver query for all …
=> Fix failing tunneling tests on IPv6 stack

pilot/pkg/bootstrap/certcontroller.go, pilot/pkg/bootstrap/configcontroller.go, pilot/pkg/config/kube/crdclient/cache_handler.go
Thanks to istio and related work. It helped us a lot.
I found some points that maybe could be optimized while reading the code,
and sorry for not being able to provide case to verify.
- With crdclient, we should take tombstone into consideration?
- When init kube config controller, why use err2? I don't find reason for releated pr.
=> feat(crdclient): crdclient take tombstone into consideration

samples/bookinfo/build_push_update_images.sh
Signed-off-by: xin.li <xin.li@daocloud.io>
This script seems to be missing instructions for "--help" and "-h"
```shell
~/istio/samples/bookinfo/src/productpage ~/istio/samples/bookinfo
invalid argument "istio/examples-bookinfo-productpage-v1:-h" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
```
Below is the modified test result:
```shell
$ ./build_push_update_images.sh -h
USAGE: ./build_push_update_images.sh <version> [-h|--help] [--prefix=value] [--scan-images]
version : Version of the sample app images (Required)
-h|--help : Prints usage information
--prefix: Use the value as the prefix for image names. By default, 'istio' is used
--scan-images : Enable security vulnerability scans for docker images 
related to …
```
=> Print usage information for help

samples/bookinfo/src/ratings/package.json
Signed-off-by: xin.li <xin.li@daocloud.io>
There is a warning, when build the bookinfo/rating image. This PR for remove the warning:
=> remove ratings build warning

pilot/cmd/pilot-agent/app/cmd.go, pkg/test/framework/components/echo/kube/deployment.go
The test VM pods have occasionally been crashing under heavy load. The envoy logs show that the crash is due to exhaustion of file descriptors.
Comments and code in `istio-start.sh` points to the problem. When you run sudo, the forked process ends up with a very small (1024) ulimit for file descriptors.
The TF startup logic for the VM (in `deployment.go`) introduces a second level of sudo that does not take ulimit into consideration, so the work-around inside `istio-start.sh` does not help.
This PR changes the call site of `istio-start.sh` to use the same `ulimit` workaround. It also adds logging within the echo application to indicate both the maximum number of file descriptors as well as current usage.
=> [tf] Fix max file descriptors for VM

pilot/cmd/pilot-agent/main.go, pilot/cmd/pilot-agent/status/server.go, pilot/cmd/pilot-agent/status/server_test.go, pilot/cmd/pilot-agent/status/util/stats.go, pilot/pkg/security/authn/v1beta1/policy_applier.go, pkg/istio-agent/health/health_probers.go, pkg/istio-agent/xds_proxy.go, security/pkg/stsservice/server/server.go
1. Make istio-proxy's sub-server can be compatible both for IPv4 and IPv6
>  status server
>  sts server
>  prober for health checking, readiness and liveness
2. Remove unnecessary wrapped IPv6 localhost
> Change wrapped IPv6 localhost from `[::1]` to `::1`,  this wrapped IPv6 localhost is specified as node.IPaddresses in some place , and then this IP address will be parsed by `net.ParseIP`, this will caused a IPv6 address can not be detected.
=> [Dual Stack] Make istio-proxy's sub-server and prober can be uniform and compatible both for IPv4 and IPv6

prow/config/default.yaml
The flag is now removed, blocking startup on 1.25+
This is not needed since its been default for many versions, and older
verisons that *do* need the flag are using another config which does
have it set still.
=> prow: disable EndpointSlice feature flag

tools/docker-builder/builder/crane.go, tools/docker-builder/common.go, tools/docker-builder/crane.go, tools/docker-builder/docker.go, tools/docker-builder/main.go, tools/docker-builder/types.go
This introduces support in the docker builder to orchestrate multi-arch
docker builds. Previously, it was required to call the builder twice
with each arch; this doesn't allow aggregating into a single multi-arch
image though.
For docker builder, this is fairly straightforward. We mostly need
changes to allow plan file to be arch-specific, and to call make
multiple times per-arch.
For crane builder, a little more complex since we need to allow passing
multiple plans to it and then deciding whether to make a Index or direct
Image.
(cherry picked from commit 13de462d7adbeff491d89e7ac17684adedf80ce8)
Fixes https://github.com/istio/istio/issues/39557
=> [1.14] docker: support proper multi-architecture builds (#39278)

istioctl/cmd/proxyconfig.go, pkg/kube/client.go, pkg/kube/mock_client.go, releasenotes/notes/istioctl-proxy-config-stats-prom-merged.yaml
Adds support for pulling Prometheus merged metrics via `istioctl x envoy-stats --output prom-merged <pod_name>.<namespace>`
https://github.com/istio/istio/issues/39454
=> istioctl x envoy-stats --output prom-merged

pilot/pkg/model/xds_cache.go, pilot/pkg/util/sets/string.go, pilot/pkg/xds/delta.go
* clear index on cache evict
* add comment
* provide a more efficient Delete function for string set
* create new lru store on clearall
* populate dependencies on write
* newLru takes evict callback
* avoid creating dependencies multiple times
* remove dead function
* fix merge
* add missing methods to set
* evict previous cache entry if already present
* add comment
=> [1.13] Clear index on cache evict (#39435)

pilot/pkg/model/xds_cache.go, pilot/pkg/xds/delta.go, pkg/util/sets/string.go
* clear index on cache evict
* add comment
* provide a more efficient Delete function for string set
* create new lru store on clearall
* populate dependencies on write
* newLru takes evict callback
* avoid creating dependencies multiple times
* remove dead function
* fix merge
* add missing methods to set
* evict previous cache entry if already present
* add comment
=> [1.14]Clear index on cache evict (#39435)

pkg/wasm/cache.go, pkg/wasm/convert.go, pkg/wasm/imagefetcher.go, pkg/wasm/monitoring.go
- Adds more debug logging
- Adds default timeout of 5s - without this if user does not specify timeout, getting context deadline exceeded
=> add more debug logging to wasm image fetcher

pkg/test/framework/components/echo/echotest/filters.go, pkg/test/framework/components/echo/echotest/filters_test.go, tests/integration/pilot/common/traffic.go, tests/integration/pilot/mcs/discoverability/discoverability_test.go, tests/integration/security/authz/authz_test.go, tests/integration/security/egress_gateway_origination_test.go, tests/integration/security/external_ca/reachability_test.go, tests/integration/security/sds_ingress/util/util.go
We currently have some logic to filter out "not useful" tests (a->b and
b->c are the same). However, we have some tests that need many
source/destinations. If we filter out these too early, we may lose the
ability to run the test at all.
Instead, we run this filter last and ensure we leave enough
destinations.
Change-Id: I12496b05c20b5b3a1333076e164ea76dba3779a2
=> tf: filter extra workloads after test filters run

common/scripts/kind_provisioner.sh, pkg/test/framework/components/echo/kube/deployment.go, pkg/test/framework/components/echo/kube/testdata/proxyless-custom-image.yaml
Use 17171 as the port for probes for the custom grpc app, since 3333 would be listened on by the Go server
=> Echo Test: Use 17171 as the port for probes for custom grpc app

pilot/pkg/serviceregistry/serviceentry/controller.go, pilot/pkg/serviceregistry/serviceentry/controller_test.go, releasenotes/notes/update-se-instances.yaml
Now we don't update service instances per SE in `workloadEntryHandler`, causing we are not able to [clean up old instances](https://github.com/istio/istio/blob/84d9f86021c64c65bc5cdc0b236da85d2f525907/pilot/pkg/serviceregistry/serviceentry/controller.go#L356-L359) on SE update, which potentially leaks memory
=> Update SE instances on WE change

pilot/pkg/config/kube/gateway/conversion.go, pilot/pkg/config/kube/gateway/conversion_test.go, pilot/pkg/config/kube/gateway/testdata/benchmark-httproute.yaml
Shallow-copy `spec.Rules` instead of deep-copying the whole object
Trying to make further optimization based on https://github.com/istio/istio/pull/37139#discussion_r799075531
=> gateway-api: avoid deep copy when converting http routes

pkg/istio-agent/agent_test.go, pkg/test/framework/components/authz/kube.go, pkg/wasm/httpfetcher.go, tools/docker-builder/builder/crane.go, tools/docker-builder/main.go
As of Go 1.16, the same functionality is now provided by package io or
package os, and those implementations should be preferred in new code.
So replacing all usage of ioutil pkg with io & os.
More of a code quality chore.
=> Replace deprecated ioutil pkg with os & io

tests/integration/security/ca_custom_root/multi_root_test.go, tests/integration/security/ca_custom_root/secure_naming_test.go, tests/integration/security/ca_custom_root/trust_domain_alias_secure_naming_test.go, tests/integration/security/external_ca/reachability_test.go, tests/integration/security/https_jwt/https_jwt_test.go, tests/integration/security/jwt_test.go, tests/integration/security/util/reachability/context.go, tests/integration/security/util/scheck/checkers.go
Just minor formatting. This is less of a good idea than I originally
thought since we are often passing from customizeCall which has a
pointer, but I still think its useful to pass a non-pointer since
otherwise it looks like we are going to mutate things.
=> tf: avoid using pointer when no mutation is used

tests/integration/pilot/tunneling_test.go
cc @jewertow This is blocking a lot of prs, so lets skip for now
=> Temporarily skip new flaky test TestTunnelingOutboundTraffic

pkg/test/framework/components/echo/check/checkers.go
We recently introduced additional logic to optionally limit the clusters checked for headless services based on MeshConfig settings.
This PR adds additional protection to avoid a potential panic when inspecting the MeshConfig.
=> [tf] Avoid potential panic in ReachedTargetClusters

operator/pkg/helmreconciler/prune.go
istioctl uninstall command missing component marked as IstiodRemote
=> Fixes#39007 x uninstall not removing everything (#39612)

pilot/pkg/serviceregistry/memory/discovery.go, pilot/pkg/xds/delta_test.go, pilot/pkg/xds/eds_test.go, pilot/pkg/xds/fake.go
This impacts tests only.
In https://github.com/istio/istio/pull/39133 we changed to notify on
writes; this ended up triggering a ton of test flake. Instead, just add
explicit functions to notify (new test needs them) and revert the other changes
=> Revert changes to always notify XdsUpdater in mem discovery

pkg/test/kube/dump.go
Currently our logic is too restrictive, making it so we will only grab
core dumps if the container hasn't restarted yet.
Example miss:
https://prow.istio.io/view/gs/istio-prow/logs/integ-security-multicluster_istio_postsubmit/1542617360051998720
=> tf: enable core dumps even if the pod has restarted

pkg/test/echo/server/forwarder/util.go, pkg/test/echo/server/instance.go
* Log metrics requests
* Fix bug where we hang when `qps*count>timeout`
* Add (debug) logs for each request, useful with high count+low qps
where we want to run long periods of traffic
=> Minor fixes on echo app

pkg/test/echo/server/forwarder/util.go
We already do this at a higher level in `(i *Instance) ForwardEcho`
So I think https://github.com/istio/istio/pull/39645 had issues since although this always was called 2x, only in that PR is it not idempotent. I will see if that part is fixable as well.
=> echo: avoid filling defaults twice

pilot/pkg/networking/core/v1alpha3/accesslog.go, pilot/pkg/networking/core/v1alpha3/accesslog_test.go
As mentioned https://github.com/istio/istio/pull/36604#issuecomment-1165182725 Istio behaviour is changed when telemetry specifies default accesslog provider("envoy"). We loose the benefit of using mesh config defaults when logFormat is not specified.
This PR brings back that behaviour.
Also changed some function names to avoid confusion.
=> use mesh config defaults when log formatter is not specified

pilot/pkg/model/xds_cache.go, pilot/pkg/xds/xds_cache_test.go
Otherwise the key's configIndex is not right, and later if a `Clear` call to clear a stale key may do nothing
=> Not really evict a key that is added later after LRU evict bt before the evict handler run by istio

pkg/bootstrap/config.go
Fix the bug for installing Istio in IPv4 only k8s cluster and the ingress gateway pod can not be running if dual stack feature is enabled.
Before this PR, Istio ingress gateway pod can not be running in IPv4 only k8s cluster due to the invalid argument for **dns_lookup_family**, the error message may be like below:
=> [Dual Stack] Fix the bug for installing Istio in IPv4 only k8s cluster with dual stack feature is enabled

pilot/pkg/model/xds_cache.go, pilot/pkg/networking/core/v1alpha3/route/route_cache_test.go, pilot/pkg/xds/bench_test.go, pilot/pkg/xds/discovery.go, pilot/pkg/xds/xds_cache_test.go
This reverts commit 898d16769875b7241a37ebfa9b087a7e911547b9.
This is base on now we have made use of hash code to represent dependents, assume in the case of 60_000 keys, each key has 100 dependents, the whole additional memory is very low about 6MB.
And keeps the `evicted` flag to indicate whether it is actively cleared to prevent clearing twice.
=> Revert "do not cache dependent configs in xds cache store (#39688)"

pkg/istio-agent/agent.go
If there is currently a FileMounted Certificate and Key, we only need to enable the `secretManagerClient` in Istio, and this can still can be implemented by calling the `newSecretManager` uniformly, which can unify the interface to provide better encapsulation.
=> Agent: Unified use of NewSecretManager func

istioctl/cmd/injector-list.go
When the command is executed, some special system namespaces are listed. Those namespaces should be ignored like the auto injection part.
=> Filter system namespaces for injector list

pkg/test/framework/components/echo/deployment/builder.go, pkg/test/framework/components/echo/deployment/flags.go, pkg/test/framework/resource/flags.go, pkg/test/framework/resource/settings.go, prow/integ-suite-kind.sh
For workload agnostic tests, this allows targeting specific types of deployments. Example usage:
```
go test tests/integration/pilot/... --istio.test.onlyWorkloads proxyless
```
Not very useful on it's own without ways to skip tests that aren't workload agnostic
=> [tf] flag to only deploy specific apps istio.test.onlyWorkloads

istioctl/cmd/istiodconfig.go, istioctl/cmd/istiodconfig_test.go, releasenotes/notes/desc-to-admin-log-scope.yaml
To make the scopes in `admin log` better understanding like the controlZ.
From 
```
Active scopes:
ads:info
adsc:info
analysis:info
```
To
```
SCOPE                  DESCRIPTION                                  LOG LEVEL
ads                    ads debugging                                info
adsc                   adsc debugging                               info
analysis               Scope for configuration analysis runtime     info
```
=> Add description to admin log, and reformat the display

pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/util.go, pilot/pkg/serviceregistry/kube/controller/util_test.go
node topology label has been GA and beta has been deprecated since k8s 1.17, we can safely do this.
=> Respect GA topology label first

pilot/pkg/model/xds_cache.go
=> add type to xds cache evictions stat

istioctl/cmd/injector-list.go, istioctl/cmd/injector-list_test.go, releasenotes/notes/39525.yaml
The pod revision was compared wrong, which lead to inaccurate info. Actually those pods are injected and the control plane is the default:
```
istioctl x injector list
NAMESPACE                     ISTIO-REVISION POD-REVISIONS
default                       default        <non-Istio>: 8 NEEDS RESTART: 8
istio-io-tcp-traffic-shifting default        <non-Istio>: 3 NEEDS RESTART: 3
istio-operator                default        <no pods>
sample-namespace              MISSING/1-14-0 <no pods>
test                          default        <non-Istio>: 3 NEEDS RESTART: 3
```
After the revision it will be like:
```
istioctl x injector list
NAMESPACE                     ISTIO-REVISION POD-REVISIONS
default                       default        default: 8 …
```
=> Fix x injector ns pod info not accurate when use default

pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, releasenotes/notes/27990.yaml
Signed-off-by: LexusLee <lexuscyborg103@gmail.com>
Considering empty protocol might remove PassthroughCluster routing, add protocol validation when address is unset in ServiceEntry
Issue related: 
- https://github.com/istio/istio/issues/27990
we already have an analyzer for this case, I think we should also add a validation.
[ ] Docs
[ ] Networking
[ ] Security
=> Add protocol check for empty address in Service Entry

pkg/test/framework/components/cluster/cluster.go, pkg/test/framework/components/cluster/config.go, pkg/test/framework/components/cluster/topology.go, pkg/test/framework/components/istio/ingress.go
PR to create a new test framework flag. This flag toggles the behavior for HTTPProxy so that only kubectl traffic (that which needs to connect to the API server) traverses the proxy.
This is useful in situations where the API server of the kubernetes cluster under test is not directly accessible, but a publicly accessible ingress gateway can be reached during the actual test runs.
=> Create topology flag to proxy only kubectl traffic through HTTPProxy

pilot/pkg/xds/delta.go, pilot/pkg/xds/sds.go, pilot/pkg/xds/xdsgen.go
Currently, we do not log incremental pushes at Info level. The intent
behind this is to avoid spam when we have large endpoint churn. However,
because we also do incremental pushes for Full pushes now, we are also
hiding these logs. These logs are both critical to debugging (things
like https://github.com/istio/istio/issues/39720, etc) and not spammy --
while the `Full=false` pushes may add thousands of messages, this change
only adds at most 1 log per push/proxy. For these types of pushes I
don't see a benefit to excluding only EDS.
Additionally, fix SDS to correctly assert it is incremental (when it
is).
=> xds: improve incremental logging

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go, pilot/pkg/networking/core/v1alpha3/cluster_test.go
=> initialize commonLbConfig in default cluster

pkg/test/echo/server/endpoint/http.go, tests/integration/pilot/forwardproxy/envoy_config_generator.go, tests/integration/pilot/tunneling_test.go
Related issue: #39586
I investigated config dumps from few failed tests and I can't find any misconfiguration. I didn't encounter similar problem on my computer - the tests always pass. So the first step to understand the problem better is adding access log to the forward proxy. I would like to know what status code and flag are returned.
After merging this PR I will look for failing post-submit tests and will try to solve to cause of the problem (I have some ideas, but I am not sure at the moment) or disable test again.
=> Enable TestTunnelingOutboundTraffic and configure access log in forward proxy

istioctl/pkg/multicluster/remote_secret.go, istioctl/pkg/tag/generate.go, istioctl/pkg/verifier/verifier.go, operator/cmd/mesh/manifest_shared_test.go, operator/cmd/mesh/operator-common.go, operator/pkg/component/component.go, operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go, operator/pkg/controlplane/control_plane.go, operator/pkg/controlplane/control_plane_test.go, operator/pkg/helm/helm.go, operator/pkg/helm/renderer.go, operator/pkg/helmreconciler/prune.go, operator/pkg/helmreconciler/prune_test.go, operator/pkg/helmreconciler/render.go, operator/pkg/manifest/shared.go, pkg/kube/client.go, releasenotes/notes/k8s-125.yaml, tests/fuzz/misc_fuzzers.go, tests/integration/operator/switch_cr_test.go, tests/integration/pilot/revisions/uninstall_test.go
For https://github.com/istio/istio/issues/34479. I think this is critical to backport since 1.25 comes out before 1.14
=> 1.14: Support Kubernetes 1.25

pilot/cmd/pilot-agent/app/wait.go
Fix bug for the istio-agent wait command to make sure that it is really timeout.
In old code, both `time.Now().Before(timeoutAt)` and `time.Sleep(time.Duration(periodMillis) * time.Millisecond)` determine the istio-agent wait command is time out or not. Whatever the `periodMillis` user sets, there may be a situation that wait command is not really timeout, but timeout because current time may be `After` the `timeoutAt` due to `time.Sleep`
In new code, introduce a channel for time counter and `select` for this timeout check, then remove `periodMillis` option.
=> fix bug for the istio-agent wait command to make sure that it is really timeout

pkg/test/kube/dump.go
Lately a bunch of issues have been caused by things stuck warming. This
makes these obvious to see without poking through 10000s of lines of
artifacts
=> tf: add explicit loggs when stuck in warming state

security/pkg/k8s/configutil.go
Fix typo of InsertDataToConfigMap func description which is stale and not suitable for current implementation.
=> Fix typo of InsertDataToConfigMap func description

tests/integration/security/external_ca/main_test.go
This flag requires the control plane to also have support, and its not
enabled. This also breaks a (test only) assertion added in
https://github.com/istio/istio/pull/39916.
=> tf: drop unused feature in external_ca

pilot/pkg/model/push_context.go, pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/xdsgen.go
The bug (example failure:
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39896/integ-cni_istio/1546984256612339712)
* ingressgateway has 1 Gateway
* Gateway is removed
* envoy disconnects
* Envoy reconnects, requests RDS. This hits the INIT/RECONNECT flow.
* RDS hits 'Gateway missing for route' path and gives no response at all
* Next RDS request, we get a "stale nonce" since we have no previously
sent nonce
* Envoy stuck forever
The fix:
* Remove code path to return empty route instead of no route (matching
other paths)
* Add assertions to ensure that we don't send empty response to requests
and that we never count a "stale nonce" if we somehow have no
previously sent nonce, to ensure there aren't any other issues
=> xds: fix issue when skipping first request

pkg/kube/client.go, pkg/kube/mock_client.go, pkg/kube/portforwarder.go, pkg/test/framework/components/cluster/kube/factory.go, pkg/test/framework/components/istio/config.go, pkg/test/framework/components/namespace/kube.go, pkg/test/framework/components/namespace/namespace.go, pkg/test/framework/resource/context.go, pkg/test/framework/scope.go, pkg/test/framework/suitecontext.go, pkg/test/framework/testcontext.go, pkg/test/kube/dump.go
This was initially a bug fix but then I realized I was misguided.
However, along the way I made some improvements to the dumping logic.
* We were dumping istio-system 2x; fix that
* We were using PodExec which is slow. Switch to port forward which is
10x+ faster. Also use a more robust mechanism to resrve ports
* Dump in parallel
* Add some better logging around dumping
* Clear managedFields from events for size/readability
=> tf: improve dumping

pilot/pkg/model/context.go, pilot/pkg/xds/ads.go, pilot/pkg/xds/ads_test.go, pilot/pkg/xds/discovery_test.go
This fixes an edge case that happens to be triggering many test flakes. https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/39896/integ-security-multicluster_istio/1547605105740615680 for example.
What happens is:
```
1. Envoy connect
2. Envoy REQ EDS, nonce=e1
3. Istiod pushes EDS, nonce=e2
4. Envoy REQ CDS
5. Istio pushes CDS
6. Envoy REQ EDS, nonce=e2
7. Istiod treats this as an ACK (from push (3))
```
Then envoy cluster is struck warming.
This solution seems super hacky, but it seems to work (in https://github.com/istio/istio/pull/39896 tested 6x without flakes - prior to this it fails like 50%+ of the time). Basically, if we get a CDS request, we always respond to the next EDS request. This ONLY occurs when EDS is the first request and at worst causes 1 extra EDS push …
=> xds: always respond to EDS request after CDS requests

pkg/test/framework/components/stackdriver/stackdriver.go
This removes the requirement that testing that uses the production Cloud Monitoring endpoint be run on GCP. There are configurations of Istio that enable the CA to provide auth to GCP endpoints. This should allow testing on off-GCP platforms when configured in that manner.
- [ X ] Test and Release
=> tf: loosen restrictions on 'real stackdriver' testing

tests/integration/telemetry/stats/prometheus/stats.go
Previous to this PR, the TestStatsFilter testcase checks the stats filter and also tests if a mocked prometheus app can call the app metrics endpoint.
This PR moves the mocked prometheus test to a subtest so that it can be skipped if required.
=> Convert mockprom to metrics endpoint test to a subtest

pkg/kube/portforwarder.go
Without this, when err happens it will be stuck sending to errCh, so cause the goroutine hanging
When ` fw.ForwardPorts()` returns without err, we should actually retry
=> Fix resiliience port-forward

prow/integ-suite-kind.sh
A portion of an earlier cherrypick of #38885 was ignored since an older version of kind was being used. Now that kind was upgraded, we need to pick up that additional change.
=> [release-1.14] Updated kind image needed for kind update (part of #38885)

go.mod, go.sum, istio.deps, prow/release-commit.sh
For Istio 1.14.2 release, run update_deps on the Istio 1.14 branch.
- [X ] Test and Release
- [X ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> Run update_deps on the Istio 1.14 branch

pkg/dns/client/dns_test.go, pkg/dns/client/proxy.go
Two issues:
* Port conflict on 15053. Pretty simple, bind to port 0
* We want to test servers supporting TCP+UDP on one port, but we cannot
atomically reserve a free tcp and udp port. Currently we reserve UDP
first then bind to TCP. This just swaps the order. In practice we have
less UDP listeners, so much less chance of conflict. This dropped flakes
from 1/10 to 1/1000 on my machine
=> Mitigate TestDNS flakes

pkg/istio-agent/xds_proxy.go
When debugging the CDs warming issue, there are spammy logs sending response to closed proxy connection
```
2022-07-15T23:16:14.575052Z	error	xdsproxy	downstream [6] send error: rpc error: code = Canceled desc = context canceled
2022-07-15T23:16:16.718426Z	info	xdsproxy	connected to upstream XDS server: istiod.istio-system.svc:15012
2022-07-15T23:18:19.791902Z	error	xdsproxy	downstream [7] send error: rpc error: code = Canceled desc = context canceled
2022-07-15T23:18:19.792239Z	error	xdsproxy	downstream [7] send error: rpc error: code = Canceled desc = context canceled
2022-07-15T23:18:20.690916Z	info	xdsproxy	connected to upstream XDS server: istiod.istio-system.svc:15012
```
**To help us figure out who should review this PR, please put an X …
=> Skip forward when the proxy connection is closed

pkg/test/framework/components/echo/common/deployment/namespace.go, tests/integration/telemetry/stats/prometheus/stats.go
This avoids spammy logs about overlapping hostnames. This also makes it
so we actually send to the per-namespace external service I think. This
shouldn't really matter much in practice.
=> tf: export external service to same namespace only

pilot/pkg/networking/core/v1alpha3/cluster_builder.go
We added max concurrent streams default when Envoy's default value was 100. Now it has been increased https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-msg-config-core-v3-http2protocoloptions - so it is better to default it to Envoy rather than our own number.
This PR fixes it.
=> remove max concurrent streams default

pilot/pkg/xds/monitoring.go
pushContextInitTime metric is missing because it is not registered,
this CL registers it.
=> register init push context metric

pilot/pkg/config/kube/gateway/context.go, pilot/pkg/config/kube/gateway/controller.go, pilot/pkg/config/kube/gateway/controller_test.go, pilot/pkg/config/kube/gateway/conversion.go, pilot/pkg/config/kube/gateway/conversion_test.go, pilot/pkg/model/context.go, pilot/pkg/model/push_context.go
`GatewayContext` should be private to k8s gateway implement, so this pr does a refactor of move it from pilot/pkg/model to pilot/pkg/config/kube/gateway
=> Abstract gateway context implement outside of model package

pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/networking/core/v1alpha3/route/route_cache.go, releasenotes/notes/rds-cache-allow-any.yaml
* Check AllowAny mode in RDS cache key
Fixes https://github.com/istio/istio/issues/40043
https://github.com/istio/istio/issues/39794#issuecomment-1189140847
* Add note
=> [release-1.14] Check AllowAny mode in RDS cache key (#40014)

pkg/test/framework/components/echo/kube/flags.go, pkg/test/framework/components/echo/kube/workload.go, tests/integration/pilot/mirror_test.go
For some workloads the container name is different and the logs are written slower. So the verification of mirroring test cases is retried for 20 seconds.
=> Add a flag for app container name and retry verifyTrafficMirror

pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/networking/core/v1alpha3/route/route_cache.go, releasenotes/notes/rds-cache-allow-any.yaml
* Check AllowAny mode in RDS cache key
Fixes
https://github.com/istio/istio/issues/39794#issuecomment-1189140847
* Add note
=> [release-1.13] Check AllowAny mode in RDS cache key (#40014)

pkg/test/framework/components/echo/check/checkers.go, tests/integration/pilot/common/routing.go, tests/integration/pilot/ingress_test.go, tests/integration/pilot/mcs/discoverability/discoverability_test.go, tests/integration/pilot/multicluster_test.go, tests/integration/security/reachability_test.go
**Check the DNS Proxying requirement before making calls to headless svc in cross cluster environment**
=> check DNS Proxying for headless svc

istioctl/pkg/multixds/gather.go
Kubernetes doesn't require port, but ADSC does. Set a default if its not
there yet.
=> istioctl: set default port from webhook

prow/release-commit.sh
Release integration test uses this file and it should be updated to use the proper branches
=> [release-1.14] Fix release-commit.sh to use release-1.14 branch instead of master

pkg/test/framework/components/echo/kube/flags.go, pkg/test/framework/components/echo/kube/workload.go, tests/integration/pilot/mirror_test.go
Reverts istio/istio#40053
I don't know why but this introduced a lot of flakes
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-123_istio_postsubmit/1550681311402790912, https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-116_istio_postsubmit/1550614369828605952, etc. Revert for now
=> Revert "Add a flag for app container name and retry verifyTrafficMirror"

pilot/pkg/networking/core/v1alpha3/networkfilter_test.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, tests/integration/pilot/testdata/tunneling/destination-rule.tmpl.yaml
This PR adapts implementation of tunneling to the specification of Istio API **1.14.2** that makes `TunnelSettings.Protocol` optional and specifies that `CONNECT` is used by default.
This is a follow-up to PR #37968 and [comment](https://github.com/istio/istio/pull/37968#discussion_r883698226).
=> Make `CONNECT` a default value of `TunnelSettings.Protocol`

pilot/pkg/model/network.go
This is a follow-up to https://github.com/istio/istio/pull/38781
This PR refactors the function that performs the resolution of network gateway hostnames:
* removes redundant nil checks and slice allocations introduced in the previous PR, to improve code readability
* replaces the type switch with type assertions, as we now always know what type of the DNS record we receive in a reply
* reintroduces parallel DNS resolution for A and AAAA records
As for the parallel resolution that was a point of concern in the previous PR: on each [DNS request](https://github.com/istio/istio/blob/1.14.1/pilot/pkg/model/network.go#L550) to an upstream DNS server, [when connecting](https://github.com/miekg/dns/blob/v1.1.50/client.go#L164) to that upstream, the …
=> Refactor resolution of network gateway names for more efficiency

pkg/kube/inject/webhook.go, pkg/kube/inject/webhook_test.go
Provide alternative and deprecate the `:ENV:` path syntax since it is not recommended and doesn't work when setting the path (vs URL) in the webhook.
Fixes #40116
=> Simpler injectionPath format for cluster env value with / char

pilot/pkg/xds/ecds.go, pilot/pkg/xds/ecds_test.go, releasenotes/notes/40093.yaml
remove secret incremental update, display-metadata will fetch failed if secret `ghcr-zirain2` updated.
```yaml
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
name: display-metadata
namespace: default
spec:
selector:
matchLabels:
app: httpbin
url: oci://ghcr.io/zirain/display-metadata:latest
imagePullSecret: ghcr-zirain
imagePullPolicy: Always
vmConfig:
env:
- name: POD_NAMESPACE
valueFrom: HOST
---
apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
name: display-metadata2
namespace: default
spec:
selector:
matchLabels:
app: httpbin
url: oci://ghcr.io/zirain/display-metadata:latest
imagePullSecret: ghcr-zirain2
imagePullPolicy: Always
vmConfig:
env:
- name: POD_NAMESPACE
valueFrom: HOST
```
=> fix multi WasmPlugin with different imagePullSecrets

pkg/test/framework/components/echo/check/checkers.go, tests/integration/pilot/common/routing.go, tests/integration/pilot/ingress_test.go, tests/integration/pilot/mcs/discoverability/discoverability_test.go, tests/integration/pilot/multicluster_test.go, tests/integration/security/reachability_test.go
**Exposed DNSProxying method and created a separate method to check the response in the same cluster only**
=> refactor response checker

cni/pkg/plugin/plugin_dryrun_test.go, pilot/pkg/config/kube/ingress/status_test.go, pilot/pkg/config/kube/ingressv1/status_test.go, pilot/pkg/networking/core/v1alpha3/route/route_test.go, pkg/bootstrap/config_test.go, pkg/bootstrap/instance_test.go, pkg/bootstrap/platform/gcp_test.go, pkg/kube/util_test.go, security/pkg/nodeagent/caclient/providers/google/client_test.go
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
This saves us at least 2 lines (error check, and unsetting the env var) on every instance.
=> test: use `T.Setenv` to set env vars in tests

pkg/config/analysis/analyzers/injection/injection.go, pkg/config/analysis/analyzers/testdata/injection.yaml
```
Warning [IST0103] (Pod default/reviews-v2-5b5dc658c5-z4c9s) The pod default/reviews-v2-5b5dc658c5-z4c9s is missing the Istio proxy. This can often be resolved by restarting or redeploying the workload.
Error: Analyzers found issues when analyzing namespace: default.
```
```
kubectl get deploy reviews-v2 -oyaml | grep sidecar. -B2
labels:
app: reviews
sidecar.istio.io/inject: "false"
```
=> Fix ist0103 msg incorrect displaying when injection label is set to false

pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/listener_test.go, pilot/test/xdstest/validate.go, releasenotes/notes/tls-tcp-conflict.yaml
Currently, tls_inspector is only added if its the first Service. If its
after TCP, it is missed.
example config:
```yaml
metadata:
name: tcp
spec:
addresses:
- 10.10.10.10/24
exportTo:
- .
hosts:
- '*.tcp'
ports:
- name: tcp-443
number: 443
protocol: TCP
---
metadata:
name: tls
spec:
exportTo:
- .
hosts:
- tls.example.com
location: MESH_EXTERNAL
ports:
- name: https-443
number: 443
protocol: HTTPS
resolution: DNS
```
depending on the order of creation it will work/not work.
=> pilot: fix issue with TLS and TCP order dependency

security/pkg/nodeagent/cache/secretcache.go, security/pkg/nodeagent/cache/secretcache_test.go
Fixes: https://github.com/istio/istio/issues/39985
Given there exists a DestinationRule with mode: MUTUAL, and paths for the private key, certificate and ca certificate of the form:
```
metadata:
name: bad-dr
namespace: foobar
spec:
exportTo:
- .
host: service-mesh-debug
trafficPolicy:
tls:
caCertificates: /etc/certs/root-cert.pem
clientCertificate: /etc/certs/cert-chain.pem
mode: MUTUAL
privateKey: /etc/certs/key.pem
```
When the listeners are configured to listen on `etc/certs/cert-chain.pem` (notice there is no slash `/` before etc), then there are two sets of file watch add events:
1. One for files with path starting from `etc/certs`
2. and another for files with path starting …
=> Use absolute path when adding file watcher

istioctl/cmd/analyze.go, istioctl/pkg/writer/compare/comparator.go, pilot/cmd/pilot-agent/status/server_test.go, pilot/pkg/model/push_context_test.go, pilot/pkg/networking/core/v1alpha3/gateway_simulation_test.go, pilot/pkg/networking/core/v1alpha3/serviceentry_simulation_test.go, pilot/pkg/serviceregistry/serviceregistry_test.go, pilot/pkg/xds/proxy_dependencies_test.go, pkg/kube/multicluster/secretcontroller_test.go
The new linter fixes `go vet` to properly detect these, so update the
code to match
=> Fix new linter version

Makefile.core.mk, bin/init.sh, pkg/test/echo/docker/Dockerfile.app_sidecar, prow/integ-suite-kind.sh, prow/lib.sh, prow/release-commit.sh, samples/jwt-server/jwt-server.yaml, samples/jwt-server/src/Dockerfile, samples/jwt-server/src/Makefile, tools/docker-builder/builder/crane.go, tools/docker-builder/common.go, tools/docker-builder/crane.go, tools/docker-builder/docker.go, tools/docker-builder/main.go, tools/docker-builder/types.go, tools/docker-copy.sh, tools/docker.yaml, tools/packaging/packaging.mk
For https://github.com/istio/istio/issues/26652#issuecomment-1155682106
This PR nearly finalizes arm64 support in Istio. With this, release-builder will publish amd64 and arm64 builds. We also have e2e tests using arm64 which works as well.
Changes required to get this to work:
* Refactor env vars (split into https://github.com/istio/istio/pull/40252)
* Update kind image to multi-arch one
* Update jwt-server to be multi-arch
* Update docker build to pull the correct base image per-arch for crane builder, as well as tag the final image with the correct architecture
* Update docker builder to allow building for multiple platforms without multi-arch builds. For --load and --save, multi-arch is not supported. Instead, if these cases are detect we will make single-arch images with an `-arch` …
=> Support pulling multi-arch envoy binaries

prow/release-commit.sh, tools/docker-builder/types.go
VMs currently require emulation to cross compile. We previously just
skipped them, but then you cannot simply run `go test
./tests/integration/...` with `gcr.io/istio-testing` since we don't have
the VM images.
Instead, try emulation.
=> Add qemulation to release builder

pilot/pkg/xds/ep_filters.go, pilot/pkg/xds/ep_filters_test.go
For AUTO_PASSTHROUGH gateway, typically istio-eastwestgateway, the endpoints of SNI-dnat cluster will be filtered by mtls checker. Yet the filtered `LocalityLbEndpoints` results have empty `LoadBalancingWeight`, that would cause LB error in sidecar.
=> fix empty endpoints weight for AUTO_PASSTHROUGH gateway

pilot/pkg/xds/ep_filters.go, pilot/pkg/xds/ep_filters_test.go
Manual cherrypick of #40243
This cannot be done by a bot because there are different struct names on the two branches, according to #40226 , which changes `LocLbEndpointsAndOptions` to `LocalityEndpoints` on master branch.
=> [release-1.14] fix empty endpoints weight for AUTO_PASSTHROUGH gateway

pilot/cmd/pilot-agent/status/server.go, pilot/cmd/pilot-agent/status/server_test.go, pkg/test/echo/server/endpoint/http.go, releasenotes/notes/http2-probes.yaml
Fixes https://github.com/istio/istio/issues/40173
This aligns with kubelet probe, to support http2 for `HTTPS` probes.
Note: the request from kubelet->agent will always be HTTP/1.1 still,
just the upstream is changed.
=> Respect ALPN negotiation in agent prober

pilot/pkg/networking/core/v1alpha3/route/route.go, pilot/pkg/networking/core/v1alpha3/route/route_test.go, releasenotes/notes/40299.yaml
There is discrepancy in how we set timeout when a VS is defined (without timeout) and VS is not defined at all. We should be consistently setting the timeouts to `notimeout` in both cases.
This PR fixes it.
Fixes https://github.com/istio/istio/issues/40299
=> unify timeout logic across service and virtual service

pilot/pkg/xds/ep_filters.go, pilot/pkg/xds/ep_filters_test.go
Manual cherrypick of #40243
This cannot be done by a bot because there are different struct names on the two branches, according to #40226 , which changes `LocLbEndpointsAndOptions` to `LocalityEndpoints` on master branch.
=> [release-1.15] fix empty endpoints weight for AUTO_PASSTHROUGH gateway

prow/release-commit.sh
Update release-commit to use the release-1.15 branches instead of master.
=> [release-1.15] Fix release-commit to use 1.15 instead of master

pkg/bootstrap/config.go, pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/metrics_no_statsd_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json
This flag was removed in Envoy `1.22` as described in the changelog:
> http: removed envoy.reloadable_features.require_strict_1xx_and_204_response_headers and envoy.reloadable_features.send_strict_1xx_and_204_response_headers and legacy code paths.
https://www.envoyproxy.io/docs/envoy/latest/version_history/v1.22/v1.22.0.html#removed-config-or-runtime
=> Remove old Envoy runtime flag

samples/bookinfo/src/details/details.rb, samples/bookinfo/src/productpage/productpage.py, samples/bookinfo/src/productpage/tests/unit/test_productpage.py, samples/bookinfo/src/reviews/reviews-application/src/main/java/application/rest/LibertyRestEndpoint.java
SkyWalking has its own tracing context header `sw8`, this patch adds propagation of this header to sample application
=> Propagate SkyWalking tracing header in sample application

pilot/pkg/bootstrap/server.go, pilot/pkg/xds/debug.go, pilot/pkg/xds/debuggen.go, pilot/pkg/xds/discovery.go, pilot/pkg/xds/fake.go, pilot/pkg/xds/simple.go
Fixes https://github.com/istio/istio/issues/40384
The issue is before we had some somewhat odd ordering to apply the
DebugMux to the debugGen. This changes it to be more explicit - and more
importantly correct as we correctly pass it a non-nil mux
=> debug interface: fix crash regression

pilot/pkg/networking/core/v1alpha3/route/route.go, pilot/pkg/networking/core/v1alpha3/route/route_test.go, releasenotes/notes/40299.yaml
=> [release-1.14] unify timeout logic across service and virtual service

pilot/pkg/networking/util/util.go, pilot/pkg/xds/endpoint_builder.go, pilot/pkg/xds/endpoint_builder_test.go, releasenotes/notes/40198.yaml
Fixes https://github.com/istio/istio/issues/40198
The root cause is that istiod caches the same endpoints regardless of failover priority labels of each proxy, this pr adds them to eds cache key
=> Add failover priorities to eds cache key

pilot/pkg/networking/core/v1alpha3/route/route.go
#40320 has moved the maxstream duration condition outside of condition which if it is not used assumes some defaults at HCM. this PR moves it inside.
=> move maxstream duration creation inside condition

samples/bookinfo/build_push_update_images.sh
The files that should be replaced are all located in the platform directory. If they all match, other files will be affected, such as networking/bookinfo-gateway.yaml
=> resovle redundant match for build_push_update_images.sh

Makefile.core.mk, common/scripts/check_clean_repo.sh, go.sum, pkg/test/framework/suite.go, pkg/test/kube/dump.go, pkg/test/prow/util.go
=> Allow linking to artifact directly in prow logs

pilot/pkg/model/proxy_config.go, pilot/pkg/model/proxy_config_test.go, releasenotes/notes/proxyconfig-global-mutate.yaml
The issue was we were overriding things by setting them to pointers.
These pointers are then shared, and when `proto.merge` is used they are
all mutated.
Instead, take deepcopies and add a test
Fixes https://github.com/istio/istio/issues/40445
=> Fix ProxyConfig merge impacting shared state

pilot/pkg/features/pilot.go, pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/gateway_test.go, pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/networking/core/v1alpha3/httproute_test.go, pilot/pkg/simulation/traffic.go, pkg/test/util/assert/assert.go, releasenotes/notes/ignore-port.yaml, tests/integration/pilot/common/routing.go
Fixes https://github.com/istio/istio/issues/40474
This is finally available in Envoy so we can drop our hacks of adding
the port, adding `:*`, etc.
=> Ignore port number in domain matching entirely

pkg/test/framework/components/namespace/kube.go, tests/integration/pilot/gateway_conformance_test.go
Precreates the namespaces used by the GatewayConformance tests (which are sourced from upstream Kubernetes). Then creates the ImagePullSecrets for each of the GC namespaces, and modifies the default ServiceAccount to use them.
This allows the test to correctly work when the images under test are stored in a private docker registry.
=> Creating image pull secrets for GatewayConformance test namespaces.

pkg/test/echo/cmd/client/main.go
This matches the proto. Its helpful for local testing since spiffe
certificate verification is typically not happening
=> hbone: add `hboneInsecureSkipVerify` to CLI

pilot/pkg/model/context.go, pilot/pkg/xds/endpoint_builder.go, pilot/pkg/xds/endpoint_builder_test.go
This is to fix misuse of labels because of rebase issue
=> Make use of Proxy.Labels instead of Meatdata.Labels

pkg/istio-agent/agent.go, pkg/istio-agent/xds_proxy.go, security/pkg/nodeagent/caclient/providers/citadel/client.go
Fix when CAEndpoint uses a different address, the ServerName will be empty
=> CA client tls config ServerName first set to CAEndpoint host

pkg/istio-agent/tap_proxy.go, pkg/istio-agent/xds_proxy.go, tests/integration/pilot/piggyback_test.go
https://github.com/istio/istio/pull/31749 introduced that the ability to tap into istio-agent to route debug messages to istiod.
While https://github.com/istio/istio/pull/31749 uses gRPC to `Istiod`, 
it uses HTTP + JSONPB to send the `DiscoveryResponse` to the downstreams.
But, we can also use gRPC to the downstreams.
This may have following benefits:
* istioctl can be used to access the endpoint. For example,
```
kubectl port-forward -n httpbin httpbin-788cfbd7d5-flrm4 15004:15004
istioctl x ps --plaintext --xds-address localhost:15004
```
* Much faster/lighter than HTTP+JSONPB because JSONPB is pretty slow.
So, this PR proposes to add gRPC tap handler which has the same functionality with https://github.com/istio/istio/pull/31749, but just uses gRPC instead of HTTP+JSONPB.
=> Add Tap gRPC handler to Istio Agent.

pilot/pkg/xds/statusgen.go
https://github.com/istio/istio/pull/36835 introduces "NodeMetadata" in the response of `debug/syncz`.
But, among the NodeMetadata, only `ClusterID` is used in [istioctl](https://github.com/istio/istio/blob/8cc2dd65d82d2ab0bc931dba9fcaefa17abf3545/istioctl/pkg/writer/pilot/status.go#L191)
Since the total size of NodeMetadata is pretty huge comparing with the required information from `istioctl x ps` command, 
this PR proposes to send only the `ClusterID` instead of the entire metadata.
Please note that the total size of xds responses was reduced to around 1/6 by this PR in my experiment.
When I ran `istioctl x ps` command with 4000 replica of `httpbin` and 10 replica of `istiod`, 
* Before this PR, 
* Elapsed Time: 10.xxx seconds (for querying & parsing, excluding printing out)
* Total …
=> Send only the Cluster ID in the response of debug/syncz

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go
When a PushRequest doesn't have Service/VirtualService/DestinationRule/Sidecar change,
in PushContext.updateContext(), initSidecarScopes() will not be invoked, new PushContext
only copies sidecarIndex.sidecarsByNamespace from old one, sidecarIndex.rootConfig becomes
nil.
When workload namespace doesn't have Sidecar resource, this causes new ADS connection's
SidecarScope being created by DefaultSidecarScopeForNamespace(), the global default
sidecar in istio root namespace is not respected.
=> Fix PushContext.sidecarIndex.rootConfig flipping issue

samples/helloworld/README.md, samples/helloworld/gen-helloworld.sh
Add help output for gen-helloworld
The test result:
```shell
$ ./gen-helloworld.sh -h
USAGE: ./gen-helloworld.sh [--version] [--includeService value] [--includeDeployment value]
-h|--help: Prints usage information
--version: Specifies the version that will be returned by the helloworld service, default: 'v1'
--includeService: If 'true' the service will be included in the YAML, default: 'true'
--includeDeployment: If 'true' the deployment will be included in the YAML, default: 'true'
```
=> add help output for gen-helloworld

samples/bookinfo/src/build-services.sh
Add help output for build-services
The test result:
```shell
$ ./build-services.sh 
Incorrect parameters
USAGE: ./build-services.sh <version> <prefix> [-h|--help]
-h|--help: Prints usage information
version:   Version of the sample app images (Required)
prefix:    Use the value as the prefix for image names (Required)
$
$ ./build-services.sh -h
USAGE: ./build-services.sh <version> <prefix> [-h|--help]
-h|--help: Prints usage information
version:   Version of the sample app images (Required)
prefix:    Use the value as the prefix for image names (Required)
```
=> add help output for build-services

pkg/test/framework/components/echo/common/deployment/namespace.go, tests/integration/security/filebased_tls_origination/destination_rule_tls_test.go, tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go, tests/integration/security/filebased_tls_origination/main_test.go, tests/integration/security/https_jwt/https_jwt_test.go, tests/integration/security/https_jwt/main_test.go, tests/integration/security/mtls_first_party_jwt/main_test.go, tests/integration/security/mtls_first_party_jwt/strict_test.go, tests/integration/security/mtlsk8sca/main_test.go, tests/integration/security/mtlsk8sca/strict_test.go, tests/integration/security/sds_egress/sds_istio_mutual_egress_test.go, tests/integration/security/sds_ingress/ingress_test.go, tests/integration/security/sds_ingress/quic/ingress_test.go, tests/integration/security/sds_ingress/util/util.go, tests/integration/security/sds_ingress_k8sca/main_test.go, tests/integration/security/util/framework.go, tests/integration/security/util/reachability/context.go
**This PR refactor some of the security tests to align with new test framework**
=> security tests refactoring - part 3

releasenotes/notes/40405.yaml, samples/bookinfo/build_push_update_images.sh, samples/bookinfo/src/build-services.sh, samples/bookinfo/src/mongodb/Dockerfile, samples/bookinfo/src/mysql/Dockerfile, samples/bookinfo/src/productpage/Dockerfile, samples/bookinfo/src/productpage/requirements.txt, samples/bookinfo/src/reviews/reviews-wlpcfg/Dockerfile
* Allows the user to pass a `--multiarch-images` flag
to `build_push_update_images.sh` which builds and pushes
a multiarch(`linux/amd64`, `linux/arm64`) image using
`docker buildx build`
Signed-off-by: Arko Dasgupta <arko@tetrate.io>
Raising this PR in anticipation of https://github.com/istio/istio/issues/35176 ( which is taking the route of faster native builds for multi arch rather than this approach of emulated builds using `docker buildx`. 
This could also be made faster with [cross compiled builds](https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/)
Fixes: https://github.com/istio/istio/issues/40405
=> Build multiarch images for bookinfo

pilot/pkg/model/cluster_local.go, pilot/pkg/model/config.go, pilot/pkg/model/config_test.go
=> make use of go generics to remove MostSpecificHostMatch2

istioctl/pkg/util/configdump/route.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go, pilot/pkg/networking/core/v1alpha3/extension/wasmplugin.go, pilot/pkg/networking/core/v1alpha3/extension/wasmplugin_test.go, pilot/pkg/networking/core/v1alpha3/tracing.go, pilot/pkg/networking/core/v1alpha3/tracing_test.go, pilot/pkg/networking/util/util.go, pkg/adsc/adsc_test.go, pkg/config/model.go
Use the `MessageToAny `function defined by Istio to convert other proto type messages into Any types, thereby simplifying the code and unifying the interface
=> Replace anypb.New with MessageToAny

pilot/pkg/networking/grpcgen/lds.go
This mirrors Envoy XDS code. It does seem a bit suspicisious skipping
rules, but I think this will not occur in real world since they will be
validated previously.
=> grpcgen: fix failed rules in Authz builder

pilot/pkg/features/pilot.go, pilot/pkg/serviceregistry/kube/controller/controller.go, pilot/pkg/serviceregistry/kube/controller/controller_test.go, pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go, releasenotes/notes/workload-entry-service-select.yaml
This reverts commit 2ffbf677e1b0bd202dfaa44783494279848fda5e.
feature flags `PILOT_ENABLE_SERVICEENTRY_SELECT_PODS` and `PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES` were removed in https://github.com/istio/istio/pull/37374.  `PILOT_ENABLE_SERVICEENTRY_SELECT_PODS` was re-added in https://github.com/istio/istio/pull/37407.  This PR re-adds `PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES`
=> Revert "remove feature flags for se selecting pods (#37374)"

pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
It does not affect any functionality. But these are not valid CIDRs. Rejected by validating webhook.
=> fix cidr value in test case

pilot/pkg/bootstrap/server.go, pilot/pkg/bootstrap/server_test.go
Fixes https://github.com/istio/istio/issues/40720
Instead of later swapping the h1 server with a multiplexed server, build
the correct one the first time. This avoids the logical race in the
issue, and a legitimate data race (swap unprotected handler).
=> Fix h2 multiplexing race

CODEOWNERS
This avoids all of the smaller helper libraries we have been adding
lately requiring top level owner approval. Most of these are generic
utils that seem reasonable to be under T&R. For anything not, they
should be explicily catagorized anyways - not top level.
=> Make top level pkg/ default to T&R

pilot/pkg/model/telemetry.go, pilot/pkg/model/telemetry_logging_test.go, releasenotes/notes/40809.yaml
bring in https://github.com/istio/istio/pull/39521
=> accesslog: not fallback to meshconfig when telemetry.spec.accesslogs is empty

tests/integration/pilot/testdata/forward-proxy/configmap.tmpl.yaml, tests/integration/pilot/testdata/forward-proxy/service.tmpl.yaml, tests/integration/pilot/tunneling_test.go
This change fixes TestTunnelingOutboundTraffic that sometimes fails with the following error:
```
{Failed      tunneling_test.go:234: failed to create config map external-forward-proxy-config: configmaps "external-forward-proxy-config" already exists}
```
It was not necessary to create configmap and service from file to fix this error, but I did it for the sake of consistency.
**Related issue:** #40812
=> Fix creating configmap and service in TestTunnelingOutboundTraffic

pilot/pkg/config/aggregate/config.go, pilot/pkg/model/gateway.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/core/v1alpha3/gateway.go, pilot/pkg/networking/core/v1alpha3/httproute.go, pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/plugin/authn/util.go, pilot/pkg/trustbundle/trustbundle.go, pilot/test/xdstest/validate.go, pkg/bootstrap/config.go, pkg/config/validation/validation.go, pkg/test/framework/components/echo/namespacedname.go, pkg/test/framework/suitecontext.go, pkg/util/sets/string.go, pkg/util/sets/string_test.go, security/pkg/nodeagent/caclient/providers/google-cas/client.go, tests/fuzz/regression_test.go, tests/integration/telemetry/stackdriver/common.go
it is a common pattern to build a set as we iterate, to check for
duplicates. This introduces a new function to ease this pattern.
No behavior change expected, just simpler code.
=> sets: add `InsertContains` to handle common dedupe cases

pkg/adsc/adsc.go
Regarding https://github.com/istio/istio/issues/40824, to prevent the infinite "ack" loop, 
this PR proposes to skip to "ack" for the debug type response.
Please note that, currently, the debug type is handled with the special way in `pilot`, so `pilot` generates responses  regardless of whether it is a request or ack.
Alternative way is that `pilot` does not send any responses if "nonce" is prefixed by `pilot` own way, because ADSC generates a nonce for a request (not ack) with a form of "date/time".
=> adsc: Skip to ack for debug type responses 

pilot/pkg/xds/debuggen.go, pilot/pkg/xds/discovery.go, pilot/pkg/xds/statusgen.go, pilot/pkg/xds/xdsgen.go, pkg/istio-agent/tap_proxy.go, pkg/istio-agent/xds_proxy.go, tests/integration/pilot/piggyback_test.go
Use constants instead of hard coded "istio.io/debug*" string.
=> Use constants for "istio.io/debug" strings

pkg/config/validation/validation.go, pkg/config/validation/validation_test.go
Istio CRDs like EF, SE, Sidecar allows specifying workloadSelector without labels - which could be unintentional. The present behavior is to apply CRDs to all proxies in the namespace. This PR does not change that behavior, but adds a warning if a workload selector is specified without the labels.
=> Add validations for workload selector

pilot/pkg/bootstrap/server.go, pilot/pkg/model/context.go, pkg/bootstrap/config.go, pkg/bootstrap/option/instances.go, pkg/istio-agent/agent.go
This (obscure) setup was broken recently:
https://blog.howardjohn.info/posts/local-gateway/
This fixes it. See https://github.com/istio/istio/issues/40867
=> Fix regressions in using plaintext control plane without kubeclient

pilot/pkg/networking/core/v1alpha3/tracing.go
Use protobuf getter to avoid nil pointer errors in the configuration logic of the tracing provider.
=> use protobuf getter functions for nil-safe in tracing provider config

bin/init.sh
https://github.com/istio/istio/issues/40890 was opened for an issue on Macs where the `make init` target fails. It fails since the old (1.0.2) Mac binary is no longer available. I do not necessarily know why the releases got removed from the repo.
The change is to simply copy the Linux binary as a place holder (at least to get things working). I don't know if anyone is actually trying to run the local Envoy binary on the Mac as it was very old, so just using the Linux binary as a placeholder should work. If this fails, as someone is using the Envoy binary, we can revise this later.
=> Quick fix to get builds working on a Mac

pilot/pkg/model/endpointshards.go, pilot/pkg/xds/eds_test.go, releasenotes/notes/full-push-regression.yaml
Fixes https://github.com/istio/istio/issues/39652
This reverts https://github.com/istio/istio/pull/36882. At the time,
that PR was needed because EDS ServiceAccounts and CDS ServiceAccounts
were decoupled; Since https://github.com/istio/istio/pull/39133, this is
no longer true, and the fix in 36882 is not needed any longer.
This PR *removes* the test added in 36882 (since it tests low level
details that are not relevant anymore). It improves the existing
TestEndpointFlipFlops test -- while that test *would* have caught the
regression, it didn't actually set any service accounts so it was
missed. The update changes it to correctly detect the behavior (it now
fails without this PR, passes with it).
=> Disable full push on scale from 1->0->1

tests/integration/tests.mk
Add dual stack checking logic for integration test.
See https://github.com/istio/istio/pull/40634
=> fix issue on integration test select flag for dual stack and IPv6

tests/integration/pilot/common/routing.go, tests/integration/pilot/tunneling_test.go, tests/integration/security/reachability_test.go
We are adding min istio version for tests related to below PRs as this functionalities were not there in previous revisions :-
a. gRPC fault
injection(https://github.com/istio/istio/pull/39295)
b. Ignore port number in domain
matching(https://github.com/istio/istio/pull/40475)
c. Tunneling outbound traffic :- new tunnel field got
introduced(https://github.com/istio/istio/pull/37968)
d. Fix consistent hash based on source IP for TCP
proxy(https://github.com/istio/istio/pull/38438)
e. Traffic policy load balancer API
changes(https://github.com/istio/istio/pull/39742)
- [X ] Test and Release
**Please check any characteristics that apply to …
=> Adding min istio version for new features to avoid running on older revisions

samples/security/spire/istio-spire-config.yaml, samples/security/spire/spire-quickstart.yaml
Update the [SPIFFE CSI driver](https://github.com/spiffe/spiffe-csi) version used in the `spire-quickstart` configuration. 
Add `readOnly` to the CSI volumes in `istio-spire-config` as the driver now enforces that the CSI volume is declared read-only in the PodSpec.
Signed-off-by: Max Lambrecht <max.lambrecht@hpe.com>
=> Update SPIFFE-CSI driver version in SPIRE quickstart config

pilot/pkg/model/telemetry_logging.go, pilot/pkg/model/telemetry_logging_test.go
Currently, order changes on every new push. This leads to draining all connections
=> otel: ensure stable XDS generation

pilot/pkg/networking/core/v1alpha3/listener_inbound.go
Fix the bug described in #40854
This PR changes [buildInboundChainConfigs()](pilot/pkg/networking/core/v1alpha3/listener_inbound.go) to not add any inbound listener if the interception mode is NONE and there is no ingress listener defined in the sidecar.
=> Do not add the inbound listener if the InterceptionMode is NONE 

tests/integration/pilot/common/traffic.go
Some tests in routing.go uses echo.Port.Protocol only. But in traffic.go it doesn't check for that to identify as optsSpecified. So added a check to allow protocol as well. 
Also it allows tests to have neither optsSpecified nor children which will show as the test passed even if it did not run. Added a check for that as well.
=> Fix for Traffic tests which are not running

pilot/pkg/networking/ambientgen/ztunnelgen.go
The chains have no real differences. Naming them identically will dedupe them (line 464)
=> ambient l4: reduce pod ip chains from SA*Pod to per-SA

pilot/pkg/networking/core/v1alpha3/tracing.go
Adds comments for sections of `tracing` configuration code that could lead to issues with dynamic control of provider config. This will serve mainly to document issues that will also be documented in the provider configurations.
This also fixes a related potential issue with OC configuration changes related to the token path used by Stackdriver tracing.
=> tracing: add warnings in code for potential OC pitfalls

pilot/pkg/networking/plugin/authz/authorization.go, pilot/pkg/security/authz/builder/builder.go, pilot/pkg/security/authz/builder/builder_test.go, pilot/pkg/security/authz/builder/logger.go
We were building the log but never reporting it. This was lost in a refactoring that moved authz building from per-proxy to being more cached and reused. This required a bit more refactoring since we build HTTP/TCP once and parse it.
=> authz: add logging back

pilot/pkg/networking/plugin/authz/authorization.go, pilot/pkg/security/authz/builder/builder.go, pilot/pkg/security/authz/builder/builder_test.go, pilot/pkg/security/authz/builder/logger.go
We were building the log but never reporting it. This was lost in a refactoring that moved authz building from per-proxy to being more cached and reused. This required a bit more refactoring since we build HTTP/TCP once and parse it.
fix: #40968
=> [release-1.14] authz: add logging back (#40964)

pilot/pkg/networking/core/v1alpha3/accesslog.go, pilot/pkg/networking/core/v1alpha3/accesslog_test.go
Currently, order changes on every new push. This leads to draining all connections
(cherry picked from commit 76a8be91904b97ace6d2b18ba4c02d833a304177)
Fixes https://github.com/istio/istio/issues/40932
=> [1.14] otel: ensure stable XDS generation (#40930)

pilot/pkg/model/service.go
our istiod CPU profile shows that 10% of time is spent on DeepCopy of ServiceAttribute, so removing the use of copystructure. We already have fuzz test and benchmark for Service DeepCopy, which covers this part since ServiceAttribute is part of Service.
Benchmark results:
(before)
```goos: darwin
goarch: amd64
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
BenchmarkServiceDeepCopy
BenchmarkServiceDeepCopy-16    	  132760	      8190 ns/op
PASS
```
(after)
```goos: darwin
goarch: amd64
cpu: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
BenchmarkServiceDeepCopy
BenchmarkServiceDeepCopy-16    	 1213035	      1019 ns/op
PASS
```
=> istio: improve deep copy for ServiceAttribute

go.mod, go.sum, pilot/pkg/networking/core/v1alpha3/tracing.go
Possible fix for https://github.com/istio/istio/pull/40965 failing lint test. This ignores the lint message about calling a deprecated method.
@douglas-reid
=> Update api (via client-go) and ignore deprecated method calls

pilot/pkg/xds/debug.go
/ndsz endpoint is not displaying any data. That is because https://github.com/istio/istio/issues/38162 changed the last parameter and passed PushRequest. Generate is skipping from https://github.com/istio/istio/blob/f8baff38c9b4129c0a6a1b24e31881f90a2c11e6/pilot/pkg/xds/nds.go#L54 and returning empty list.
=> fix ndsz debug endpoint

istioctl/pkg/writer/envoy/clusters/clusters.go, istioctl/pkg/writer/envoy/configdump/endpoint.go
before:
```console
envoy://tunnel                                                    HEALTHY     OK                outbound|80||notsleep.default.svc.cluster.local
envoy://tunnel                                                    HEALTHY     OK                outbound|80||sleep.default.svc.cluster.local
envoy://tunnel                                                    HEALTHY     OK                outbound|80||sleep.sidecar.svc.cluster.local
envoy://tunnel                                                    HEALTHY     OK                outbound|9080|v1|reviews.default.svc.cluster.local
envoy://tunnel                                                    HEALTHY     OK                outbound|9080|v2|reviews.default.svc.cluster.local
envoy://tunnel …
```
=> istioctl: make pc ep support internal address

pilot/pkg/networking/core/v1alpha3/accesslog.go, pilot/pkg/networking/core/v1alpha3/accesslog_test.go
Currently, order changes on every new push. This leads to draining all connections
(cherry picked from commit 76a8be91904b97ace6d2b18ba4c02d833a304177) (cherry picked from commit 4e46398b05e346366641b1a81a7e953de646e4ff)
Fixes https://github.com/istio/istio/issues/40931
=> [1.13] otel: ensure stable XDS generation (#40930)

pilot/pkg/security/authn/v1beta1/policy_applier.go, releasenotes/notes/40997.yaml
Fixes a bug where remote JWKS URI's specified without a host port fail to parse into their host and port components.
Example: https://go.dev/play/p/vtXEUwF8s7S
- jwtRule.JwksUri = "http://istio.io/jwks"
- net.SplitHostPort would error, and host would be empty.
=> pilot: fix remote JWKS endpoint host assignment

istioctl/cmd/internal-debug.go, istioctl/cmd/proxystatus.go, istioctl/pkg/clioptions/central.go, istioctl/pkg/multixds/gather.go, pkg/kube/client.go, pkg/kube/mock_client.go
This PR proposes an experimental option `--xds-via-agents` only for `istioctl x proxy-status` command, which sends a query for `istioctl x proxy-status` via istio agents, instead of direct query to `istiod`.
`istioctl x proxy-status` try to find all the istiod instances by searching pods in `istio-system` namespace.
But, if we use the external istiods, this way may not work.
For example, `istiod` can be deployed in the other cluster or out of K8S. Moreover, in front of the istiod instances, some sort of load balancer can be set to distribute the connections to multiple istiods. This kind of configuration may happen when the customer want to isolate their control plane from the workloads, or when they are using some managed control plane.
In such case, `istioctl x proxy-status` cannot …
=> `istioctl x proxy-status` via istio agents.

pilot/pkg/config/aggregate/config.go, pilot/pkg/config/file/store.go, pilot/pkg/config/kube/crdclient/client.go, pilot/pkg/config/kube/gateway/controller.go, pilot/pkg/config/kube/ingress/controller.go, pilot/pkg/config/kube/ingressv1/controller.go, pilot/pkg/config/memory/controller.go, pilot/pkg/model/config.go, pkg/config/analysis/local/istiod_analyze.go, pkg/kube/client.go, pkg/kube/mock_client.go, releasenotes/notes/40727.yaml
Signed-off-by: hejianpeng <hejianpeng2@huawei.com>
1. add `HasStarted() bool` to model.ConfigStoreController
2. do not can SetWatchErrorHandler if it's started
=> operator: should not call `SetWatchErrorHandler` if store has started

istioctl/cmd/proxystatus.go
Just a small typo
limitting -> limiting
Typo is located in the comment
- [√] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
=> Fix Typo in istioctl proxystatus

go.mod
master and release-1.15 are built in go1.19, keep gomod same with build image
https://github.com/istio/tools/blob/8ca918567e0c0178e98df7c78f0425ef21885be5/docker/build-tools/Dockerfile#L28
=> move gomod to 1.19

pilot/pkg/model/telemetry_logging.go, pilot/pkg/model/telemetry_logging_test.go, releasenotes/notes/40851.yaml
this's a follow up of https://github.com/istio/istio/pull/39521#discussion_r920547732
cc @douglas-reid @ramaraochavali
=> accesslog: fallback to meshconfig when built-in provider's format is unset

pkg/adsc/adsc.go, pkg/adsc/adsc_test.go, pkg/adsc/util.go
Currently, the HasSynced of ADSC doesn't work. When the istio starts running, the adsc has synced immediately even if the adsc hasn't received any mcp resources.  The logic of the following code trying to determine whether the MCP resource is ready is wrong.
https://github.com/istio/istio/blob/e062bfd7025369d4aca5a1fe6711faca01ea5bdd/pkg/adsc/adsc.go#L449
The type url of mcp resource, such as ServiceEntry, is `networking.istio.io/v1alpha3/ServiceEntry`. So the result of above code is always not equal to 3. All MCP resources will be ignored by the above code. Besides, checking the mcp resources by the count of '/' in type url is tricky.  Instead, we should check whether the type url is mcp resource explicitly.
This pr try to fix this issue to make sure the istio turn to be synced after all …
=> Improve HasSynced of ADSC

README.md
We know that Ambient on kind on Mac M1s does not work, even if you build and use ARM images. For example:
```
+ ip rule add priority 20000 fwmark 0x400/0xfff lookup 100
Cannot talk to rtnetlink: Operation not supported
```
=> add kind on Mac M1 to known not to work in Ambient README

pilot/pkg/model/fuzz_test.go, pkg/fuzz/util.go, pkg/test/failer.go, tests/fuzz/oss_fuzz_build.sh
There are some issues around using `testing.F` directly due to the hacks in oss-fuzz, so replace them with interface
=> Fix fuzzer build

pilot/pkg/model/push_context.go, pilot/pkg/model/sidecar.go, pilot/pkg/model/virtualservice.go, pilot/pkg/model/virtualservice_test.go
Our production init push context time is very long (roughly 40s), and CPU profile shows that more than 20% of cpu time is spent on the VirtualServicesForGateway function:
https://github.com/istio/istio/blob/1.14.4/pilot/pkg/model/push_context.go#L863-L875
This function is called for every sidecar's egress host, for calculating the virtual services that are imported by the egress host. We have more than 10k sidecars and suppose each sidecar has 10 egress hosts, this function is called 100k times. This "make slice" and "slice copy" are expansive on such magnitude.
Such copy is unnecessary though. Instead of passing in the copied and merged version of the virtual services, just pass the virtualServiceIndex into the select function directly. From …
=> avoid unnecessary copy virtual services for sidecar scope calculation

pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go, pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch_test.go
fix https://github.com/istio/istio/issues/40950
In our scenario, there are more than 5000 routers. When the router is in the merge filter, it will use proto.clone in a loop nested in the large array of routers. This modification moves the deep copy method to the outside of a loop,I think it is unnecessary to deep copy every time in the inner loop, a full deep copy can be made before the loop, so that the original A large number of calculations of n*n become n times
=> Let the double-layer loop deep copy object of large array change to once

pilot/pkg/serviceregistry/kube/controller/util.go
This is a hot path in our code on some occasions. This improves the performance substantially by using simpler check of the map labels.
```
name               old time/op    new time/op    delta
GetPodServices-48    35.3µs ± 1%    10.0µs ± 1%  -71.66%  (p=0.000 n=9+9)
name               old alloc/op   new alloc/op   delta
GetPodServices-48    21.4kB ± 0%     4.2kB ± 0%  -80.63%  (p=0.000 n=10+10)
name               old allocs/op  new allocs/op  delta
GetPodServices-48       468 ± 0%        18 ± 0%  -96.15%  (p=0.000 n=10+10)
```
Behavior is identical, this is purely an optimization
=> Optimize getPodServices

pilot/pkg/xds/debug.go, pilot/pkg/xds/v3/model.go
follow up: https://github.com/istio/istio/issues/37504
```console
root@ecs-zirain:~/go/src/playground/go/wasm-extensions/display-metadata# kubectl exec -it `kubectl get po -nistio-system| grep istiod | grep Running | awk '{print $1}'` -nistio-system -- pilot-discovery request get '/debug/ecdsz?proxyID=httpbin-847f64cc8d-kmlxg'
[{"config":{"name":"default.display-metadata","Vm":{"VmConfig":{"runtime":"envoy.wasm.runtime.v8","code":{"Specifier":{"Remote":{"http_uri":{"uri":"oci://ghcr.io/zirain/display-metadata:latest","HttpUpstreamType":{"Cluster":"_"},"timeout":{"seconds":30}}}}},"environment_variables":{"host_env_keys":["POD_NAMESPACE"],"key_values":{"ISTIO_META_WASM_PLUGIN_RESOURCE_VERSION":"4333"}}}},"configuration":{"type_url":"type.googleap …
```
=> move `/debug/ecdsz` to `/debug/config_dump?types=ecds`

tests/integration/tests.mk
if support ipv6 is yes, then let's skip ipv4 test which may lead to the job failed.
=> support ipv6 is yes, then let's skip ipv4 test

pilot/pkg/ambient/ambient.go, pilot/pkg/ambient/ambientpod/podutil.go, pilot/pkg/networking/ambientgen/ztunnelgen.go
Fixes #41097 by skipping workload's with hostNetwork: true when building listeners for ztunnel.
=> Don't include hostNetwork pods in ztunnel's config

tests/integration/security/egress_gateway_origination_test.go
Previously the targets were always empty, and test was not really running.
Fixes https://github.com/istio/istio/issues/41048
=> Fix egress gateway tls origination test

pilot/pkg/config/memory/controller.go
The `started` bool in the controller struct currently does not get set when the controller run function is called
=> Set started bool for memory controller

pilot/pkg/model/push_context.go, pilot/pkg/model/virtualservice.go
In a few places, we use `map[]map[]x`. Unless we need to be able to iterate over all the inner maps, this is much slower than using a struct as a key
See tests below:
```go
func BenchmarkMulti(b *testing.B) {
b.Run("nested-outer", func(b *testing.B) {
var m map[string]map[string]struct{}
for n := 0; n < b.N; n++ {
m = map[string]map[string]struct{}{}
for outer := 0; outer < 100; outer++ {
o := strconv.Itoa(outer)
for inner := 0; inner < 1; inner++ {
i := strconv.Itoa(outer)
if _, f := m[o]; !f {
m[o] = map[string]struct{}{}
}
m[o][i] = struct{}{}
}
}
}
})
b.Run("nested-inner", func(b *testing.B) {
var m map[string]map[string]struct{}
for n := 0; n < b.N; n++ {
m = map[string]map[string]struct{}{}
for outer := 0; outer < 1; outer++ {
o := strconv.Itoa(outer)
for inner := 0; inner < 100; …
```
=> Optimize double nested maps

releasenotes/notes/bug-report-rps-limit.yaml, tools/bug-report/pkg/bugreport/bugreport.go, tools/bug-report/pkg/bugreport/flags.go, tools/bug-report/pkg/config/config.go, tools/bug-report/pkg/content/content.go, tools/bug-report/pkg/kubeclient/kubeclient.go, tools/bug-report/pkg/kubectlcmd/kubectlcmd.go
Add a flag to change the requests per second limit when running
`istioctl bug-report`.
For my test cluster with ~600 pods and the default request limit
of 10, it takes ~5 minutes to collect a bug report. With a 50 rps
limit it takes ~1 minute, and with 100 rps ~35s.
This has become a blocker for collecting bug reports from very
large clusters with thousands of pods.
=> Add flag for changing rps limit in istioctl bug-report

tests/integration/pilot/testdata/tunneling/gateway/tls/istio-mutual/mtls.tmpl.yaml, tests/integration/pilot/testdata/tunneling/gateway/tls/istio-mutual/virtual-service.tmpl.yaml
This change just simplifies two configs used in `TestTunnelingOutboundTraffic` which are unnecessarily complicated.
=> Simplify configs for TestTunnelingOutboundTraffic

pilot/pkg/features/pilot.go, releasenotes/notes/41171.yaml
What
----
Pilot: Add a guard against empty value for `TRUSTED_GATEWAY_CIDR` feature
Refer to original implementation PR #39405
Context
--------
In my multi cluster istio set up on 1.15 I observe logs with the following error
```
caller from [an RFC 1918 IP address from one of my clusters] is not in the trusted network
```
In Go, splitting the empty string will result in a string slice of length 1, ie `[""]` and splitting the delimiter string (eg `strings.Split(",", ",")`) will result in a string slice of length 2, ie `["", ""]`. Refer to playground https://go.dev/play/p/mFXBRg-AnkL
If this environment variable `TRUSTED_GATEWAY_CIDR` is not set, then `features.TrustedGatewayCIDR` defaults to `[""]`
Later this feature is used in the following code:
```
if …
```
=> Pilot: Add a guard against empty TRUSTED_GATEWAY_CIDR feature

pilot/pkg/serviceregistry/serviceentry/conversion.go, pilot/pkg/serviceregistry/serviceentry/servicediscovery.go, pilot/pkg/serviceregistry/serviceregistry_test.go
This was never back ported to 1.14 due to proximity to branch cut
manual cherry-pick of #38661
=> Fix ServiceEntry endpoint port setting order (#38661)

pilot/pkg/model/cluster_local.go
To avoid nil-pointer exception, this PR guards the nil-pointer for MeshConfig.ServiceSettings.Settings.
=> Guarding nil-pointer for MeshConfig.ServiceSettings.Settings

istioctl/cmd/kubeinject.go, istioctl/cmd/kubeinject_test.go, istioctl/cmd/testdata/deployment/hello-with-proxyconfig-anno.yaml, istioctl/cmd/testdata/deployment/hello-with-proxyconfig-anno.yaml.injected, pkg/config/mesh/mesh.go, releasenotes/notes/40778.yaml
MeshConfig is nil if injector exists. Set it to default proxyconfig to avoid of nil pointer panic.
=> Fix proxyconfig annotation lead to kube-inject panic

cni/README.md
The CNI plugin repo is not correct because its branch is renamed from master to main
=> fix: Fix the link address

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go, releasenotes/notes/sidecar-flipflop.yaml
When a PushRequest doesn't have Service/VirtualService/DestinationRule/Sidecar change, in PushContext.updateContext(), initSidecarScopes() will not be invoked, new PushContext only copies sidecarIndex.sidecarsByNamespace from old one, sidecarIndex.rootConfig becomes nil.
When workload namespace doesn't have Sidecar resource, this causes new ADS connection's SidecarScope being created by DefaultSidecarScopeForNamespace(), the global default sidecar in istio root namespace is not respected.
(cherry picked from commit 5da33de3c7ff42e2993f7a91b1af2586fe7de48c)
=> [1.13] Fix PushContext.sidecarIndex.rootConfig flipping issue (#40575)

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go, releasenotes/notes/sidecar-flipflop.yaml
When a PushRequest doesn't have Service/VirtualService/DestinationRule/Sidecar change, in PushContext.updateContext(), initSidecarScopes() will not be invoked, new PushContext only copies sidecarIndex.sidecarsByNamespace from old one, sidecarIndex.rootConfig becomes nil.
When workload namespace doesn't have Sidecar resource, this causes new ADS connection's SidecarScope being created by DefaultSidecarScopeForNamespace(), the global default sidecar in istio root namespace is not respected.
(cherry picked from commit 5da33de3c7ff42e2993f7a91b1af2586fe7de48c) (cherry picked from commit 348b5e9a442f580361e319265e012729807809f7)
=> [1.14] Fix PushContext.sidecarIndex.rootConfig flipping issue (#40575)

go.mod, go.sum, pilot/pkg/config/kube/gateway/deploymentcontroller_v1alpha2.go, pilot/pkg/config/kube/gateway/deploymentcontroller_v1alpha2_test.go, pilot/pkg/config/kube/gateway/testdata/deployment/alpha-cluster-ip.yaml, pilot/pkg/config/kube/gateway/testdata/deployment/alpha-manual-ip.yaml, pilot/pkg/config/kube/gateway/testdata/deployment/alpha-multinetwork.yaml, pilot/pkg/config/kube/gateway/testdata/deployment/alpha-simple.yaml, pkg/kube/controllers/common.go, releasenotes/notes/gateway-v1beta1.yaml
This picks up https://github.com/kubernetes-sigs/gateway-api/pull/1439. Unfortunately we need to fork since the main branch in gateway-api has diverged too much.
Also fixes release note which was from master
=> [1.15] gateway-api: fix an issue causing Informers to fail

go.mod, go.sum, pilot/pkg/config/kube/gateway/deploymentcontroller_v1alpha2.go, pilot/pkg/config/kube/gateway/deploymentcontroller_v1alpha2_test.go, pilot/pkg/config/kube/gateway/testdata/deployment/alpha-cluster-ip.yaml, pilot/pkg/config/kube/gateway/testdata/deployment/alpha-manual-ip.yaml, pilot/pkg/config/kube/gateway/testdata/deployment/alpha-multinetwork.yaml, pilot/pkg/config/kube/gateway/testdata/deployment/alpha-simple.yaml, pkg/kube/controllers/common.go, releasenotes/notes/gateway-v1beta1.yaml
This picks up https://github.com/kubernetes-sigs/gateway-api/pull/1439. Unfortunately we need to fork since the main branch in gateway-api has diverged too much.
(cherry picked from commit 7d37334ba2c95a96d2a3ae4c47ecd10f02510428)
Also fixes release note which was from master
=> [1.14] gateway-api: fix an issue causing Informers to fail

go.mod, go.sum, pilot/pkg/config/kube/gateway/deploymentcontroller_v1alpha2.go, pilot/pkg/config/kube/gateway/deploymentcontroller_v1alpha2_test.go, pilot/pkg/config/kube/gateway/testdata/deployment/alpha-cluster-ip.yaml, pilot/pkg/config/kube/gateway/testdata/deployment/alpha-manual-ip.yaml, pilot/pkg/config/kube/gateway/testdata/deployment/alpha-multinetwork.yaml, pilot/pkg/config/kube/gateway/testdata/deployment/alpha-simple.yaml, pkg/kube/controllers/common.go, releasenotes/notes/gateway-v1beta1.yaml
This picks up https://github.com/kubernetes-sigs/gateway-api/pull/1439. Unfortunately we need to fork since the main branch in gateway-api has diverged too much.
(cherry picked from commit https://github.com/istio/istio/commit/7d37334ba2c95a96d2a3ae4c47ecd10f02510428)
Also fixes release note which was from master
=> [1.13] gateway-api: fix an issue causing Informers to fail

tools/packaging/common/gcp_envoy_bootstrap.json
I am following up on if this file is still needed, since clearly it had a major bug for a while undetected.
=> Remove my 15 minutes of fame in gcp_bootstrap

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go, releasenotes/notes/sidecar-flipflop.yaml
When a PushRequest doesn't have Service/VirtualService/DestinationRule/Sidecar change, in PushContext.updateContext(), initSidecarScopes() will not be invoked, new PushContext only copies sidecarIndex.sidecarsByNamespace from old one, sidecarIndex.rootConfig becomes nil.
When workload namespace doesn't have Sidecar resource, this causes new ADS connection's SidecarScope being created by DefaultSidecarScopeForNamespace(), the global default sidecar in istio root namespace is not respected.
(cherry picked from commit 5da33de3c7ff42e2993f7a91b1af2586fe7de48c) (cherry picked from commit 348b5e9a442f580361e319265e012729807809f7)
=> [1.15] Fix PushContext.sidecarIndex.rootConfig flipping issue (#40575)

pilot/pkg/networking/core/v1alpha3/listener_builder.go, pilot/pkg/networking/core/v1alpha3/networkfilter_test.go, releasenotes/notes/41066.yaml
Fixes https://github.com/istio/istio/issues/41066
RBAC filter shows up before metadata exchange filter for both network and HTTP (subfilters of http_connection_manager) filters. This was preventing the metadata to be populated for requests that were denied (403 in case of HTTP or dial failed for TCP) in OAP access logs. 
This PR fixes the order by putting `istio.metadata_exchange` filter before RBAC filter for HTTP filters. For TCP however, the ordering was correct (after changes introduced by https://github.com/istio/istio/pull/38652), so this PR just adds a unit test for the TCP case.
This exists in istio 1.13, 1.14 and 1.15 as well. Will raise backports once this is merged.
=> Place `istio.metadata_exchange` before RBAC filters for network and HTTP filters

pkg/config/visibility/visibility.go
`~` is not allowed. However if the input is not valid it shows:
```
error: destinationrules.networking.istio.io "reviews" could not be patched: admission webhook "validation.istio.io" denied the request: configuration is invalid: only .,*,~, or a valid DNS 1123 label is allowed as exportTo entry
```
=> Fix exportTo field validation

pilot/pkg/credentials/kube/multicluster.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go
Using mutex to protect the remote kube controllers in multicluster case.
=> Fix data race in multicluster case.

pilot/pkg/xds/ads.go, pilot/pkg/xds/discovery.go, security/pkg/nodeagent/sds/sdsservice.go
When DiscoveryServer is instantiated as a SDS Service in agent, it applies default rate limit of 1 which prints log lines like this in agent
```
2022-09-29T03:33:23.234076Z	warn	ads	ADS: "@" exceeded rate limit: rate: Wait(n=1) would exceed context deadline
2022-09-29T03:33:23.234092Z	warn	ads	ADS: "@" exceeded rate limit: rate: Wait(n=1) would exceed context deadline
2022-09-29T03:33:23.234052Z	warn	ads	ADS: "@" exceeded rate limit: rate: Wait(n=1) would exceed context deadline
2022-09-29T03:33:23.234060Z	warn	ads	ADS: "@" exceeded rate limit: rate: Wait(n=1) would exceed context deadline
2022-09-29T03:33:23.234010Z	warn	ads	ADS: "@" exceeded rate limit: rate: Wait(n=1) would exceed context deadline
2022-09-29T03:33:23.234077Z	warn	ads	ADS: "@" exceeded rate limit: rate: Wait(n=1) would …
```
=> do not apply rate limits for sds server

pilot/pkg/networking/core/v1alpha3/serviceentry_simulation_test.go
This is a follow-up to the PR #40165 and a [comment](https://github.com/istio/istio/pull/40165#discussion_r933345677) about tests.
To make sure that this test verifies implementation from #40165, I reverted that commit and then got the error below.
```
traffic.go:261: Full Diff:   simulation.Result{
  	Error:              nil,
- 	ListenerMatched:    "240.240.0.1_443",
+ 	ListenerMatched:    "virtualOutbound",
  	FilterChainMatched: "virtualOutbound-catchall-tcp",
  	RouteMatched:       "",
  	RouteConfigMatched: "",
  	VirtualHostMatched: "",
- 	ClusterMatched:     "outbound|443||istio.io",
+ 	ClusterMatched:     "PassthroughCluster",
  	StrictMatch:        false,
  	Skip:               "", …
```
=> Add missing unit test for #40165

pilot/pkg/networking/core/v1alpha3/listener.go, pilot/pkg/networking/core/v1alpha3/listener_test.go
When proxy metadata DNSCapture and DNSAutoAllocate are enabled, if Sidecar egress listener for TCP service is defined with port number, the generated sidecar outbound listener doesn't bind to auto allocated address(240.240.x.x).
=> Fix Sidecar egress TCP listener doesn't use auto allocated address

pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go, pkg/config/mesh/mesh.go, pkg/config/mesh/mesh_test.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, releasenotes/notes/failover-validation.yaml
Adds validation and logging in the event Failover is specified in a DestinationRule without configuring OutlierDetection.  Istiod is currently silently not applying any failover settings if outlier detection settings are not provided:
[link](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/cluster.go#L854)
```
// Failover should only be applied with outlier detection, or traffic will never failover.
enabledFailover := cluster.OutlierDetection != nil
if cluster.LoadAssignment != nil {
// TODO: enable failoverPriority for `STRICT_DNS` cluster type
loadbalancer.ApplyLocalityLBSetting(cluster.LoadAssignment, nil, locality, proxyLabels, localityLB, enabledFailover)
}
```
**To help us figure out who should review this PR, …
=> Failover validation

pkg/test/echo/cmd/server/main.go, pkg/test/echo/common/scheme/scheme.go, pkg/test/echo/server/endpoint/instance.go, pkg/test/echo/server/endpoint/udp.go, pkg/test/echo/server/endpoint/util.go, pkg/test/echo/server/forwarder/instance.go, pkg/test/echo/server/forwarder/udp.go, pkg/test/echo/server/instance.go
While we don't support UDP today, it is still useful to have in our standard client/server to test various UDP things (in the future, Istio sidecars proxying the UDP, of course).
=> echo: add UDP support

pkg/kube/client.go
This makes tests 4x faster on my machine (kind).
I have no clue why a *Cached*DiscoveryClient implements OpenAPISchemaGetter in an uncached manner, while this method is cached, but its out of our control. This mirrors kubectl, which uses an in memory cached variant.
=> tf: cache open api schema fetch

pilot/pkg/model/envoyfilter.go, pilot/pkg/model/envoyfilter_test.go, pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/httproute.go
In our environment we are using several envoy filters applying to `NETWORK_FILTER/HTTP_FILTER`. Each time these filters get updated, they invalidate the CDS/RDS cache even though they are not patching clusters/routes
This pr scopes the envoy filters used for CDS/RDS cache, so the cache won't be invalidated ineffectively
=> Scope envoy filters for CDS/RDS

pkg/config/validation/validation.go
Warn should provide valid cihersuites for tls version < 1.2
=> validate tls ciphersuite below 1.2 version

pkg/bootstrap/testdata/all_golden.json, pkg/bootstrap/testdata/auth_golden.json, pkg/bootstrap/testdata/authsds_golden.json, pkg/bootstrap/testdata/default_golden.json, pkg/bootstrap/testdata/metrics_no_statsd_golden.json, pkg/bootstrap/testdata/running_golden.json, pkg/bootstrap/testdata/runningsds_golden.json, pkg/bootstrap/testdata/stats_inclusion_golden.json, pkg/bootstrap/testdata/tracing_datadog_golden.json, pkg/bootstrap/testdata/tracing_lightstep_golden.json, pkg/bootstrap/testdata/tracing_opencensusagent_golden.json, pkg/bootstrap/testdata/tracing_stackdriver_golden.json, pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json, pkg/bootstrap/testdata/tracing_tls_golden.json, pkg/bootstrap/testdata/tracing_zipkin_golden.json, pkg/bootstrap/testdata/xdsproxy_golden.json, releasenotes/notes/40729.yaml, tools/packaging/common/envoy_bootstrap.json
fixes: #39903 
wait for ~~https://github.com/envoyproxy/envoy/pull/22791~~ https://github.com/envoyproxy/envoy/pull/23024
support multiple regexes to populate the same tag name.
before:
```
envoy_cluster_internal_upstream_rq_200{cluster_name="xds-grpc"} 1
envoy_cluster_internal_upstream_rq{response_code_class="2xx",cluster_name="xds-grpc"} 1
envoy_cluster_upstream_rq{response_code_class="2xx",cluster_name="xds-grpc"} 1
istio_requests_total{response_code="200",reporter="source",source_workload="sleep",source_workload_namespace="default",source_principal="spiffe://cluster.local/ns/default/sa/sleep",source_app="sleep",source_version="unknown",source_cluster="Kubernetes",destination_workload="httpbin",destination_workload_namespace="default",destina …
```
=> stats: correct response_code regex

pkg/config/mesh/mesh.go, pkg/config/mesh/mesh_test.go, pkg/config/validation/validation.go, pkg/config/validation/validation_test.go, releasenotes/notes/failover-validation.yaml
* log warning if failover is not configured due to missing outlier detection policy
* add validation logic for failover policy without outlier detection
* uncomment out test scenarios
* switch to warning message instead of error
* remove log message
* fix missing validation references
* add releasenote for new warning validation message
* lint fix
manual cherrypick of PR #41272
fixes https://github.com/istio/istio/issues/41407
=> Failover validation (#41272)

cni/pkg/plugin/plugin.go
No need to checkAmbient when pod's namespace is in the excluded namespaces(istio-system, kube-system)
=> ambient: no checkAmbient if pod is in excluded namespaces

pilot/pkg/model/push_context.go, pilot/pkg/model/push_context_test.go, pilot/pkg/xds/proxy_dependencies.go, pilot/pkg/xds/proxy_dependencies_test.go
For https://github.com/istio/istio/issues/39110#issuecomment-1139661877
If `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG` is enabled, just skip the push when unrelated services change
=> `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG`: don't push xds when unrelated services are updated

pilot/pkg/features/pilot.go, pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/listener_inbound.go, pilot/pkg/networking/core/v1alpha3/listener_test.go, releasenotes/notes/41018.yaml
Fixes: https://github.com/istio/istio/issues/40919
Helps in cases where port is present in service as well as sidecar ingress.
As a result ports in service are not added to passthrough clusters.
If port number is same in service and sidecar ingress, sidecar takes precedence as expected for that port
Signed-off-by: Aliasgar Ginwala aginwala@ebay.com
=> Create inbound listener from both sidecar and service

samples/kind-lb/README.md, samples/kind-lb/setupkind.sh
fixes #41423 
1. Added dual stack support
2. Upgraded metallb to 0.13.5
3. Allow kind to hook up with local image repo
=> Added dual stack support for setting up kind cluster

pilot/pkg/xds/ads.go
For having more fine-granular view for the error, 
PR proposes to return the "invalid argument" error code for the parsing error of node metadata.
=> pilot: return the 'InvalidArgument' error code when parsing the node metadata fail

istioctl/cmd/precheck.go
When we execute `istioctl experimental -h`, the help short is shown as follows. Except for the short of precheck, all the other subcommands start with uppercase letters. This pr modifiers it
```shell
Experimental commands that may be modified or deprecated
Usage:
istioctl experimental [command]
Aliases:
experimental, x, exp
Available Commands:
add-to-mesh          Add workloads into Istio service mesh
authz                Inspect Istio AuthorizationPolicy
config               Configure istioctl defaults
create-remote-secret Create a secret with credentials to allow Istio to access remote Kubernetes apiservers
describe             Describe resource and related Istio configuration
envoy-stats          Retrieves Envoy metrics in the specified pod …
```
=> istioctl experimental: change the short of the precheck subcommand to start with uppercase

pilot/pkg/networking/core/v1alpha3/tls.go, pilot/pkg/networking/util/util.go
Since
https://github.com/istio/istio/commit/d8ca966bdb326f77d901ad02b1f542ec3d082804, we start logging if CIDR fails to convert. Originally, I thought we should just drop the log, but upon further inspection we are actually passing `[]string{""}` as the cidr which is a bit confusing. This changes it to pass empty list if we have no CIDR (we already do this in some callsites, just not all).
The end result here should be the same as all older releases, and the same as master but without spammy logs.
=> pilot: avoid spam from unset CIDR

pkg/envoy/proxy.go, pkg/envoy/proxy_test.go
Revert logging format to standard Envoy format. There's no good reason to drop important debugging information (worker thread, source location, etc).
=> envoy: use standard logging format

pilot/pkg/bootstrap/istio_ca.go, security/pkg/pki/ca/ca.go
When with external Istiod, we want to beable to load cacerts from a remote cluster, the secrest name is a string literals, we'd better use a constants instread.
=> Use contants string instead of string literals as cacerts secrect name

istioctl/cmd/checkinject.go
When executing `istioctl x check-inject -h`, the following information is displayed, the format is found to be incorrect, this pr modifies it
```shell
Checks associated resources of the given resource, and running webhooks to examine whether the pod can be or will be injected or not.
Usage:
istioctl experimental check-inject [<type>/]<name>[.<namespace>] [flags]
Examples:
istioctl experimental check-inject details-v1-fcff6c49c-kqnfk.test
istioctl x check-inject deployment/details-v1
istioctl x check-inject deployment/details-v1 -n test
istioctl x check-inject -n test -l app=helloworld,version=v1
```
=> istioctl experimental: modify the example display format of 'istioctl x check-inject -h'

pilot/pkg/config/memory/store.go, pilot/pkg/config/memory/store_test.go
We are using MCP-over-XDS to include external resources, where istiod uses memory store. Given the store operations are locked by the global mutex, we don't need to use `sync.Map`, which does not scale well under frequent updates
=> Replace `sync.Map` in memory store

pilot/pkg/model/credentials/resource.go, pilot/pkg/model/gateway.go, pilot/pkg/security/model/authentication.go
Fix bug where `mode: MUTUAL` rejects `-cacert` resource when using Gateway API syntax `kubernetes-gateway://namespace/name` for credentialName/Refs.
=> gateway-api: cacert resource in same ns is valid

pkg/kube/controllers/index.go, pkg/kube/controllers/index_test.go, pkg/test/util/assert/assert.go, security/pkg/server/ca/node_auth.go
The Index we previously used MUST be added before the informer starts. This is challenging when we use a shared index informer, especially if we consider this is not always used, multicluster, possible future usage of indexes, etc.
Previously, there were race conditions where sometimes the indexer was added after the informer started.
Instead, we re-implement the Index concept on *top* of informers, to work around this issue. This also allows us to expose a much easier to use API.
=> Fix pod Index

tests/integration/pilot/multicluster_test.go
Slight improvement that decouples this test from our integration test IstioOperator that sets the env. The env really only needs to be set for this test. 
The test should work better in environments that don't set this.
=> improve TestBadRemoteSecret portability

pilot/pkg/bootstrap/configcontroller.go, pkg/config/analysis/incluster/controller.go, pkg/config/analysis/local/istiod_analyze.go
This fix ensures that the client in the analysis controller is initialized with the revision istiod is running with.
Without this fix, the analysis controller would erroneously report the following error if Istio is installed with any revision other than `default`:
```
Error [IST0101] (Gateway default/bookinfo-gateway) Referenced selector not found: "istio=ingressgateway"
```
A pod with the label `istio=ingressgateway` exists, but the analysis controller ignores it because its revision isn't `default`.
=> Ensure analysis client is configured with actual revision

pilot/pkg/bootstrap/servicecontroller.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go, pilot/pkg/serviceregistry/kube/controller/multicluster_test.go
The `configController` field of `Multicluster` is not used. Remove it for simplicity and readability.
=> Remove unused configController field of Multicluster

pilot/pkg/bootstrap/configcontroller.go, pilot/pkg/config/kube/crdclient/client.go, pilot/pkg/config/kube/gateway/controller.go, pilot/pkg/config/kube/gateway/controller_test.go, pilot/pkg/xds/fake.go
Not fixing any known bugs, but I think this could possible have issues in real world with multicluster (read CRD in one cluster, try to watch it in all clusters). But in general this is a code hygene improvement to not use globals
=> Make WaitForCRD scoped to struct, not global

pkg/wasm/cache_test.go
Slightly change a test case to not rely on dns resolution.
My system has a slow dns and this test fails because every attempt to reach `https://dummyurl` takes between 3 and 5 seconds. The test case timeout is 10s, which gives room to approximately 2 attempts, not 5 as the test expects.
We could also increase the timeout, but I don't think it's the correct approach.
Changing the test case URL to an invalid one gives us the same result (i.e., testing a download failure) whithout relying on DNS resolution.
=> wasm test: do not rely on dns resolution

pilot/pkg/status/distribution/reporter.go
Prior to this commit, the status reporter tried to create an ownerReference with an invalid API group, causing the following error:
Error writing Distribution Report: unable to create ConfigMap: configmaps "istiod-78c5bd88d-72m8k-distribution" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion meta.k8s.io/v1 Kind Pod: no matches for kind "Pod" in version "meta.k8s.io/v1"
This commit fixes the API group/version to "v1"
=> Fix API group in distribution report configmap ownerReference

pilot/pkg/ambient/controller/workloadcache.go
gateway API CR create after VS, ztunnel will not be updated, request will not send to waypoint.
```console
[2022-10-29T06:51:33.462Z] "- - -" 0 - - - "-" 249 199 10012 - "-" "-" "-" "-" "envoy://outbound_tunnel_lis_spiffe://cluster.local/ns/default/sa/bookinfo-reviews/10.244.1.32:9080" spiffe://cluster.local/ns/default/sa/bookinfo-reviews_to_http_ratings.default.svc.cluster.local_outbound_internal envoy://internal_client_address/ 10.96.254.139:9080 10.244.1.37:57826 - - capture outbound (no waypoint proxy)
```
=> ambient: fix CI

security/pkg/k8s/chiron/controller.go
Increase watch timeout only for Istiod DNS certs generated by K8s CA
=> chiron: amend cert watch timeout for DNS certificates

pilot/pkg/networking/core/v1alpha3/cluster.go, pilot/pkg/networking/core/v1alpha3/cluster_builder.go, pilot/pkg/networking/util/util.go
Refactor HBone cluster code. Main goal was to move it to single place
=> refactor and move hbone cluster code

istioctl/pkg/multixds/gather.go
This PR proposes to skip the pod inaccessible for the command `istioctl ps --xds-via-agent`.
When there is a pod which is terminating or not running yet, such pod can cause an error when creating a port-forward.
During traversing pods for `istioctl ps --xds-via-agent`, it blocks to go with the other healthy pods.
So, this PR skips such inaccessible pods in the traversing loop.
=> [bug fix] Skip the pod inaccessible for `istioctl ps --xds-via-agent`

pkg/config/validation/validation.go, pkg/config/validation/validation_test.go
Fix the nack of eds as following:
```
embedded message failed validation | caused by LbEndpointValidationError.Endpoint: embedded message failed validation | caused by EndpointValidationError.Address: embedded message failed validation | caused by AddressValidationError.SocketAddress: embedded message failed validation | caused by SocketAddressValidationError.PortValue: value must be less than or equal to 65535)
```
=> Add endpoint check for ServiceEntry.

pkg/test/framework/components/echo/kube/deployment.go
Increasing the restart timeout to 60s.
When all workloads are restarted in the integration test, it takes more than 20s . (in local, it took around 25~30s)
=> [fix] Increase the timeout for restarting to 60s

pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Reduce the amount of time an idle HTTP connection to ORIGINAL_DST host stays resident in memory.
Context: https://github.com/envoyproxy/envoy/issues/22218.
=> original_dst: set idle timeout to 5min

pilot/pkg/model/config.go, pilot/pkg/model/config_test.go
Now, the hashcode of config whose namespace is ns-foo and name is abc is equal to the config  whose namespace is cns-foo and name is ab. The reason is that we can't distinguish the boundary between namespace and name.
This pr add separator / to avoid collision. For better readable, I move namespace in the front of name.
=> Fix config key hashcode collision issue.

pilot/pkg/model/xds_cache.go, pilot/pkg/model/xds_cache_test.go
This may occur when multi goroutines building same xds (like clusterXXX) for different proxy.
1. all go routines get() returns nil
2. one goroutine build its own and add().
3. another goroutinebuild its own and add()
the above two tokens are the same, so we can break fast instead of updating indexes
=> No need to cache when the token is equal to the cached one

bin/update_deps.sh
Update to make prow/release-commit.sh executable after sed in update_deps.sh
Running updates_deps.sh yields a prow/release-commit.sh that isn't executable as the sed -i creates a tmp file and copies it over the original replacing the attributes. This makes the script executable again.
=> Update to make prow/release-commit.sh executable after sed

pilot/pkg/bootstrap/sidecarinjector.go, pilot/pkg/serviceregistry/kube/controller/multicluster.go, pkg/webhooks/util/util.go, pkg/webhooks/validation/controller/controller.go, pkg/webhooks/webhookpatch.go, pkg/webhooks/webhookpatch_test.go, releasenotes/notes/scope-webhook-cert-patching.yaml
This has some open converations still around https://github.com/istio/istio/pull/41789/files . Hence thinking it would be better to revert on 1.16
Reverts istio/istio#41781
=> Revert "[release-1.16] Limit webhook patcher to patch owned webhooks"

samples/kind-lb/setupkind.sh
kind latest version v0.17.0 will fail to create cluster when EndpointSlice presents in the configuration.
Please see this issue
https://github.com/kubernetes-sigs/kind/issues/2997
=> Fixed kind issue

pkg/test/framework/resource/flags.go, pkg/test/framework/resource/settings.go, tests/integration/ambient/baseline_test.go
The rest pass, allowing us to run the subset of currently working tests locally and/or in CI
The tests pass only with a couple local PRs I have, but those should be merged soonish
=> Allow skipping tests not yet working on Rust ztunnel

pkg/bootstrap/platform/gcp.go, pkg/bootstrap/platform/gcp_test.go
Manual cherry picks of https://github.com/istio/istio/pull/40105 and https://github.com/istio/istio/pull/40700. These were backported into 1.13, are in 1.16.. so this PR provides consistency.
=> Manual cherrypick: "Check if metadata endpoint is available and trigger GCP requests concurrently" 40105
