istio/istio

- go.mod
- go.sum
Update prometheus client library
> [release-1.12] Update prometheus client

- pilot/cmd/pilot-agent/main.go
- pilot/cmd/pilot-agent/options/agent.go
- pilot/cmd/pilot-agent/options/statusserver.go
- pilot/pkg/model/context.go
- pilot/pkg/model/context_test.go
- pilot/pkg/networking/core/v1alpha3/fake.go
- pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
- pilot/pkg/util/network/ip.go
- pilot/pkg/util/network/ip_test.go
- pilot/pkg/xds/ads.go
- pkg/bootstrap/config.go
- pkg/envoy/proxy.go
Follow-up to this https://github.com/istio/istio/pull/38100
> use same ipv6 detection logic every where (take 2)

- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
> minor test fixes

- pilot/docker/Dockerfile.proxyv2
> manual cherry-pick 38211

- tests/integration/security/util/reachability/context.go
For https://github.com/istio/istio/issues/37629
> Disable parallel testing for TestReachability

- samples/custom-bootstrap/custom-bootstrap.yaml
Updated the bootstrap customization sample to v3
> updating bootstrap config sample to v3

- tools/packaging/common/gcp_envoy_bootstrap.json
TD use the following format for gateway resource
gateway: /projects/project-name/networks/scope:scope-name/nodes/
We need to add this support in gcp_envoy_bootstrap.json
> Add support to td gateway in gcp_envoy_bootstrap.json

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
> minor fix SetDestinationRules

- pilot/pkg/features/pilot.go
> add description for gateway config env var

- pilot/pkg/networking/core/v1alpha3/httproute.go
> remove unnecessary hostsbynamespace in route generation

- pilot/pkg/networking/core/v1alpha3/route/route.go
> fix comment in prefix match code

- pilot/pkg/model/telemetry.go
- pilot/pkg/networking/core/v1alpha3/extension/wasmplugin.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/filters/filters.go
- pkg/config/constants/filters.go
- pkg/config/xds/filters.go
- pkg/wasm/convert.go
- pkg/wasm/convert_test.go
refactor constants to one place
> refactor constants

- pilot/pkg/leaderelection/leaderelection_test.go
Followup to #38219
Just noticed that we missed adding the remote prefix ("^") to the revision key in the cycle test when the new comp function is used, so remote instances always look like local ones, missing several cases where an initial lock steal should occur.
> Add revision prefix to cycle test comp key

- pilot/pkg/networking/core/v1alpha3/listener_builder.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
fix: https://github.com/istio/istio/issues/38413
> fix passthrough idle timeout

- pkg/config/mesh/mesh.go
- releasenotes/notes/dns-nxdomain.yaml
Fixes https://github.com/istio/istio/issues/35603
> Bump DNS refresh rate for DNS failures

- pilot/cmd/pilot-discovery/app/cmd.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/fake.go
- pilot/pkg/serviceregistry/kube/controller/multicluster.go
- pilot/pkg/serviceregistry/kube/controller/multicluster_test.go
SyncInterval is never set and ResyncPeriod is never used
> Remove SyncInterval and ResyncPeriod

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/route/retry/retry.go
- pilot/pkg/xds/filters/filters.go
- pkg/bootstrap/config.go
- pkg/bootstrap/testdata/all_golden.json
- pkg/bootstrap/testdata/auth_golden.json
- pkg/bootstrap/testdata/authsds_golden.json
- pkg/bootstrap/testdata/default_golden.json
- pkg/bootstrap/testdata/metrics_no_statsd_golden.json
- pkg/bootstrap/testdata/running_golden.json
- pkg/bootstrap/testdata/runningsds_golden.json
- pkg/bootstrap/testdata/stats_inclusion_golden.json
- pkg/bootstrap/testdata/tracing_datadog_golden.json
- pkg/bootstrap/testdata/tracing_lightstep_golden.json
- pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
- pkg/bootstrap/testdata/tracing_stackdriver_golden.json
- pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
- pkg/bootstrap/testdata/tracing_tls_golden.json
- pkg/bootstrap/testdata/tracing_zipkin_golden.json
- pkg/bootstrap/testdata/xdsproxy_golden.json
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- pkg/test/util/assert/assert.go
Account for https://github.com/envoyproxy/envoy/pull/20397
> Update proxy binary

- pilot/pkg/bootstrap/mesh.go
Fix https://github.com/istio/istio/issues/38444#issuecomment-1103781049
> Fix panic when kubeClient is nil

- istioctl/cmd/tag.go
- pkg/config/analysis/local/context.go
- pkg/config/analysis/local/istiod_analyze.go
fix https://github.com/istio/istio/issues/38453
> istioctl tag respect revision

- pilot/pkg/bootstrap/server.go
- pilot/pkg/features/pilot.go
We have a requirement in grayscale release. The control plane needs to support multiple custom hosts. And we can separate multiple values ​​with commas. Of course it is still compatible with only one custom host.
> support multiple custom hosts

- pkg/http/headers/builder.go
- pkg/test/framework/components/echo/calloptions.go
- pkg/test/framework/components/echo/check/checkers.go
- pkg/test/framework/components/echo/common/deployment/echos.go
- pkg/test/framework/components/echo/common/deployment/namespace.go
- pkg/test/framework/components/echo/config.go
- pkg/test/framework/components/echo/match/matchers.go
- pkg/test/framework/components/echo/services.go
- pkg/test/framework/components/echo/workload.go
- pkg/test/framework/components/istio/util.go
- pkg/test/framework/config.go
- pkg/test/framework/resource/context.go
- tests/integration/pilot/cni/cniversionskew_test.go
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/endpointslice/endpointslice_test.go
- tests/integration/pilot/main_test.go
- tests/integration/pilot/multicluster_test.go
- tests/integration/pilot/revisions/revisions_test.go
- tests/integration/security/authorization_test.go
- tests/integration/security/ca_custom_root/secure_naming_test.go
- tests/integration/security/external_ca/reachability_test.go
- tests/integration/security/normalization_test.go
- tests/integration/security/pass_through_filter_chain_test.go
- tests/integration/security/testdata/authz/v1beta1-conditions.yaml.tmpl
- tests/integration/security/util/reachability/context.go
- tests/integration/security/util/scheck/checkers.go
A number of improvements around the testing framework to help with work on https://github.com/istio/istio/pull/37914.
> [tf] Various improvements

- pilot/pkg/model/context.go
- pilot/pkg/networking/core/v1alpha3/networkfilter.go
- pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
fix: https://github.com/istio/istio/issues/38500
> make redis op timeout configurable

- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
Fixes https://github.com/istio/istio/issues/38295
> fix unprivileged pod check in gateway listeners

- pkg/test/framework/components/authz/headers.go
- pkg/test/framework/components/authz/kube.go
- pkg/test/framework/components/authz/kubelocal.go
- pkg/test/framework/components/authz/provider.go
- pkg/test/framework/components/authz/server.go
- pkg/test/framework/components/echo/common/deployment/echos.go
- pkg/test/framework/components/echo/common/deployment/namespace.go
- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/components/istio/util.go
- tests/integration/pilot/cni/cniversionskew_test.go
- tests/integration/pilot/endpointslice/endpointslice_test.go
- tests/integration/pilot/main_test.go
- tests/integration/security/authorization_test.go
- tests/integration/security/testdata/authz/v1beta1-custom.yaml.tmpl
Moving the authz server creation to a new test component that can be easily reused.
This is supporting the work on https://github.com/istio/istio/pull/37914.
> [tf] New authz server component

- docker/Dockerfile.base
Update base image to use ubuntu jammy
> Switch Istio base image to use Ubuntu Jammy

- pkg/istio-agent/agent.go
Fixes https://github.com/istio/istio/issues/38568
> fix panic in agent ndsz

- istioctl/pkg/tag/generate.go
- istioctl/pkg/tag/generate_test.go
fix: https://github.com/istio/istio/issues/38153
> istiod-default-validator not respect custom istioNamespace

- docker/Dockerfile.base
Long live iptables
Fixes https://github.com/istio/istio/pull/38583
DNM until https://github.com/istio/test-infra/pull/4023 so we can get it auto built
> base: use iptables_legacy

- pilot/pkg/serviceregistry/kube/controller/filter/discoverynamespaces.go
Cherry-picking bot failed to put this in 1.12
Co-authored-by: Douglas Jordan <douglas.jordan@airbnb.com>
> [release-1.12] Fix panic in discoverynamespaces.go (#36015)

- pkg/test/framework/components/echo/config/builder.go
- pkg/test/framework/components/echo/config/param/params.go
- pkg/test/framework/components/echo/config/param/template.go
- pkg/test/framework/components/echo/config/param/template_test.go
- pkg/test/framework/components/echo/config/param/wellknown.go
- pkg/test/framework/components/echo/config/source.go
- pkg/test/framework/components/echo/echotest/config.go
- pkg/test/framework/components/echo/echotest/echotest.go
- pkg/test/framework/components/echo/echotest/run.go
This supports https://github.com/istio/istio/pull/37914. Allows the echotest framework to automatically determine when to apply configuration.
> [tf] Add config to echotest framework

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_test.go
- pilot/pkg/networking/core/v1alpha3/accesslog.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_builder.go
- pilot/pkg/networking/core/v1alpha3/networkfilter.go
- releasenotes/notes/38192.yaml
part of https://github.com/istio/istio/issues/37665
> implement Telemetry LoggingSelector

- pilot/cmd/pilot-discovery/app/cmd.go
- releasenotes/notes/38543.yaml
THis will make backward campatible
> Allow UnknownFlags

- tools/docker-builder/types.go
> docker: always run `make init`

- go.mod
- go.sum
- pkg/config/xds/filter_types.gen.go
- prow/release-commit.sh
> run update deps

- pilot/pkg/networking/core/v1alpha3/accesslog_test.go
- pilot/pkg/networking/core/v1alpha3/httproute_test.go
- pilot/pkg/networking/core/v1alpha3/listener_builder.go
- pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
- pilot/pkg/networking/core/v1alpha3/listenertest/match.go
- pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
- pilot/test/xdstest/extract.go
resolves https://github.com/istio/istio/issues/38579
manual cherry-pick of https://github.com/istio/istio/pull/38482 and dependency https://github.com/istio/istio/pull/38533
> Cherrypick 38482

- pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
> Fix log format

- pkg/config/analysis/local/istiod_analyze.go
- releasenotes/notes/38659.yaml
fix https://github.com/istio/istio/issues/38148
> istioctl analyze should add kube sources in all revisions

- tools/docker-builder/builder/tar.go
> docker builder: handle missing file error

- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pilot/pkg/serviceregistry/serviceentry/conversion_test.go
- pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
Backport #38661 to fix https://github.com/istio/istio/issues/38642 in 1.13
> [release-1.13] Fix serviceentry endpoint setting order

- istioctl/pkg/multicluster/options.go
remove comment https://github.com/istio/api/pull/2335#issuecomment-1113154205
> remove comment

- pkg/config/schema/generate.go
> fix bad comment

- pilot/pkg/xds/eds_test.go
- pilot/pkg/xds/lds_test.go
> do not persist temporary test files to output

- istioctl/cmd/describe.go
- istioctl/cmd/describe_test.go
- releasenotes/notes/38641.yaml
fix https://github.com/istio/istio/issues/38636
> istioctl x describe pod should respect revision

- istioctl/pkg/writer/envoy/configdump/configdump_test.go
- istioctl/pkg/writer/envoy/configdump/testdata/bootstrapdump.json
Fix the TODO's, enable the testconfigwriter test case conditions
> Fix todo testconfigwriter

- tools/docker-builder/builder/crane.go
> crane builder: conditionally use compression based on upstream

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_test.go
- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
- releasenotes/notes/38250.yaml
alternative to https://github.com/istio/istio/pull/38711
* telemetry api: add support for TracingSelector
* fix lint issue
> telemetry api: add support for TracingSelector (#38250)

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/networkfilter.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/security/authn/utils/utils.go
- releasenotes/notes/38754.yaml
fix: https://github.com/istio/istio/issues/38601 and https://github.com/istio/istio/issues/38520
> [release-1.12] add listener tcp metadata exchange filter only when enabled (#36756)

- pkg/istio-agent/agent.go
- pkg/istio-agent/agent_test.go
- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta.go
- pkg/istio-agent/xds_proxy_test.go
> add some comments for xds proxy

- pilot/cmd/pilot-discovery/app/cmd.go
As we have allow unknown flags, this can be safely removed
> rm plugins completely

- pkg/istio-agent/agent.go
- pkg/istio-agent/xds_proxy.go
Comment says to block but blockoption is not added.
> remove unnecessary comment in xds proxy

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/envoyfilter/envoyfilter.go
- pkg/config/analysis/analyzers/testdata/absolute-envoy-filter-operation.yaml
- pkg/config/analysis/analyzers/testdata/envoy-filter-add-operation.yaml
- pkg/config/analysis/analyzers/testdata/envoy-filter-merge-operation.yaml
- pkg/config/analysis/analyzers/testdata/envoy-filter-patch-operation.yaml
- pkg/config/analysis/analyzers/testdata/envoy-filter-remove-operation.yaml
- pkg/config/analysis/analyzers/testdata/envoy-filter-replace-operation.yaml
- pkg/config/analysis/analyzers/testdata/relative-envoy-filter-operation.yaml
- pkg/config/analysis/msg/messages.gen.go
- pkg/config/analysis/msg/messages.yaml
- releasenotes/notes/37415.yaml
additional fixes for 37415
Changes to improve the istioctl analyzer for the envoyFilter Patch operations.  Makes checks to see what the filters are applied to and provides warnings/errors against the ADD, MERGE, REMOVE, REPLACE operations
> Additional changes for istioctl analyzer when checking envoyFilter patch operations

- pilot/cmd/pilot-discovery/app/cmd.go
Reverts istio/istio#38803
Cannot be merged without https://github.com/istio/istio/pull/38543
> Revert "[release-1.14] rm plugins completely"

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/xds/filters/filters.go
kind of clean up of redundant definition
> Make use oftransport socket name directly from envoy api

- pilot/pkg/networking/plugin/authz/authorization.go
> add nil check to authz builder

- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/httproute_test.go
- releasenotes/notes/38678.yaml
- releasenotes/notes/38713.yaml
Backport of #38713 that didn't seem to happen automatically.
> [release-1.13] backport only expand vhost for local services

- pkg/config/schema/collection/schemas.go
- pkg/config/schema/resource/schema.go
Make it more easier to use to contain both the original GVK and its alias.
> Revise groupversionaliaskind

- pilot/pkg/features/pilot.go
no more report about https://github.com/istio/istio/issues/28315, remove comments
> fix outdate comments

- pilot/pkg/model/push_context.go
> initSidecarScopes: remove the unused variable

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/testdata/envoy-filter-merge-operation.yaml
- pkg/config/analysis/analyzers/testdata/envoy-filter-replace-operation.yaml
fix to issue #38806 
merged test inputs into single test to reduce race condition on which input would get run
> update flaky testcases for envoy filter

- pilot/pkg/serviceregistry/serviceentry/controller_test.go
Was cleaning up for another bigger change I abandoned. But might as well
push up this part.
> pilot: minor test simplification

- Makefile.core.mk
> Update BASE_VERSION to 1.14-2022-05-12T19-01-30

- pkg/util/sets/string.go
> style: remove unused code

- pilot/pkg/networking/telemetry/telemetry_test.go
Increase 100% test coverage for telemetry_test.go
Ref: https://github.com/istio/istio/issues/37354
> fix: increase 100% test coverage for telemetry_test.go

- pkg/config/analysis/local/istiod_analyze.go
- releasenotes/notes/38659.yaml
fix https://github.com/istio/istio/issues/38850
> revert PR #38659 (#38826)

- pkg/wasm/cache.go
- pkg/wasm/cache_test.go
fixes https://github.com/istio/istio/issues/38915
> Cherrypick #38911

- samples/security/spire/README.md
- samples/security/spire/istio-spire-config.yaml
- samples/security/spire/sleep-spire.yaml
- samples/security/spire/spire-quickstart.yaml
Adds supporting example deployment for #37947 that allows the user easily test the newly implemented feature.
> Adds example under /samples for envoy SDS integration

- pilot/pkg/serviceregistry/kube/controller/controller.go
Added more comments so that one someone like me does not come along in future and remove this :-)
> add more comments on full push when network change

- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
Fix https://github.com/istio/istio/issues/38932
> Fix pod label panic

- pkg/test/framework/components/namespace/kube.go
Reverts istio/istio#38875
This broke namespace cleanup. This is only exposed in postsubmit since cleanup errors are silently dropped (see logs:
```
2022-05-16T09:45:46.285934Z	error	tf	Error during close: 1 error occurred:
* resource name may not be empty
```
And only postsubmit has enough tests run that we hit max pods per node
> Revert "[tf] Consistent namespace creation"

- pilot/pkg/serviceregistry/kube/controller/fake.go
- pilot/pkg/xds/fake.go
Fixes https://github.com/istio/istio/issues/36503#issuecomment-1127865955
> Fix double run of controller

- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
Seems we forgot to filter endpointslice before.
> Add filter to endpointslice

- pilot/pkg/model/proxy_config.go
- pilot/pkg/model/proxy_config_test.go
- releasenotes/notes/proxy-config-image-type.yaml
Fixes https://github.com/istio/istio/issues/38959
> Fix: ProxyConfig image type not taking effect

- pkg/util/identifier/util_test.go
> add ut for util

- pilot/cmd/pilot-agent/status/server.go
- pilot/pkg/xds/xdsgen.go
Fixes https://github.com/istio/istio/issues/38916 - grpc listener gets disabled by delta.
Also removes the continuous error message about pulling envoy metrics.
> No delta for grpc XDS, no envoy prometheus fetching.

- pkg/test/framework/components/istio/operator.go
- pkg/test/kube/dump.go
Adding cluster information to a number of error logs. Also avoiding errors when attempting to dump control plane debugging information for non-primary cluster.
> [tf] Cleanup test dump operations

- istioctl/pkg/tag/generate.go
- istioctl/pkg/tag/generate_test.go
- operator/cmd/mesh/install.go
Fixes #38974 
Manual cherry-pick of #38600
> [release-1.14] Cherry-pick of #38600 - Fix bad validatingwebhookconfiguration gen

- pkg/test/framework/components/authz/kube.go
- pkg/test/framework/components/echo/common/deployment/namespace.go
- pkg/test/framework/components/echo/kube/deployment.go
> [tf] Add local authz server for vms

- go.mod
- go.sum
- licenses/k8s.io/apiserver/LICENSE
- pilot/pkg/credentials/kube/secrets.go
- pilot/pkg/xds/fake.go
- pilot/pkg/xds/sds_test.go
> Sds cleanup

- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice_test.go
As EndpointSlice v1 topology is deprecated
> rm getLocalityFromTopology

- istioctl/pkg/multicluster/remote_secret.go
- istioctl/pkg/multicluster/remote_secret_test.go
- prow/integ-suite-kind.sh
- releasenotes/notes/38885.yaml
A version of  https://github.com/istio/istio/pull/38726/ that fixes https://github.com/istio/istio/issues/38246
> prow: update default image to 1.24.0 and fix remote-secret creation

- istioctl/pkg/writer/pilot/status.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/debug_test.go
- releasenotes/notes/wasm-pull-policy.yaml
Simple fix of typo and release note.
> Fix typos in code and the release note.

- tests/integration/security/reachability_test.go
- tests/integration/security/util/reachability/context.go
**Enabled Reachability tests in multi-cluster environment**
> enabled reachability tests in multi-cluster env

- pkg/util/strcase/camelcase_test.go
improve test coverage for camelcase
> Improve test

- manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
- manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.11.yaml
- manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.12.yaml
- manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.13.yaml
- manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.14.yaml
- manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.15.yaml
- manifests/charts/istiod-remote/templates/telemetryv2_1.11.yaml
- manifests/charts/istiod-remote/templates/telemetryv2_1.13.yaml
- manifests/charts/istiod-remote/templates/telemetryv2_1.14.yaml
- manifests/charts/istiod-remote/templates/telemetryv2_1.15.yaml
- releasenotes/notes/38676.yaml
Fix https://github.com/istio/istio/issues/39010.
> Fix https://github.com/istio/istio/issues/39010

- samples/bookinfo/platform/kube/bookinfo-db.yaml
- samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
- samples/bookinfo/platform/kube/bookinfo-details.yaml
- samples/bookinfo/platform/kube/bookinfo-mysql.yaml
- samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
- samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
- samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
- samples/bookinfo/platform/kube/bookinfo-ratings.yaml
- samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
- samples/bookinfo/platform/kube/bookinfo.yaml
> Update bookinfo images

- istioctl/pkg/multicluster/remote_secret.go
- istioctl/pkg/multicluster/remote_secret_test.go
- prow/integ-suite-kind.sh
- releasenotes/notes/38885.yaml
* prow: update default image to 1.24.0
* wait for token data to be available
* fix lint and release note
* unit test coverage
> [release-1.14] update prow to 1.24 and fix remote-secret creation

- pkg/test/echo/docker/Dockerfile.app_sidecar_base
In particular, adds DNS utilities to aid in debugging.
> [tf] Adding more utils to echo vms

- pkg/wasm/cache.go
- pkg/wasm/cache_test.go
- releasenotes/notes/wasm-insecure-all.yaml
Fixes https://github.com/istio/istio/issues/39044
> Cherrypick 39024

- pkg/test/kube/dump.go
Fixes the dumping of VMs pods that have an authz container. Also does some general cleanup around the handling of container names.
> [tf] Fix dump of echo vm

- pkg/test/echo/server/endpoint/tcp.go
- pkg/test/echo/server/endpoint/util.go
This adds better logging for the TCP server and also avoids forceClose when the request completes normally.
> [tf] Echo cleanup tcp server

- pilot/pkg/util/network/ip_test.go
Increase test coverage : ip_test.go
Ref: https://github.com/istio/istio/issues/37354
/release-notes-none
> fix: update test cases

- pilot/pkg/xds/ads.go
Add a log line to indicate envoy has sent a discovery request
> add log line to indicate envoy discovery request

- pilot/pkg/serviceregistry/aggregate/controller.go
- pilot/pkg/serviceregistry/provider/providers.go
> add String function in provider id

- pkg/test/framework/components/echo/kube/workload.go
- tests/integration/pilot/cni/cniversionskew_test.go
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/common/traffic.go
- tests/integration/pilot/endpointslice/endpointslice_test.go
- tests/integration/pilot/routing_test.go
- tests/integration/pilot/vm_test.go
> TestTraffic: use a new TrafficContext instead of list of cases

- pkg/test/framework/components/echo/config/builder.go
- pkg/test/framework/components/echo/config/param/wellknown.go
- pkg/test/framework/components/echo/match/matcher.go
> [tf] Improvements to echo component lib

- pkg/util/sets/string_test.go
improve test coverage for string
> improve test coverage

- tests/fuzz/autoregistration_controller_fuzzer.go
- tests/fuzz/fuzz.go
- tests/fuzz/kube_controller_fuzzer.go
- tests/fuzz/networking_core_v1alpha3_envoyfilter_fuzzer.go
- tests/fuzz/networking_core_v1alpha3_fuzzer.go
- tests/fuzz/oss_fuzz_build.sh
- tests/fuzz/pilot_networking_fuzzer.go
- tests/fuzz/security_authz_builder_fuzzer.go
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46710#c6
@howardjohn
> Fuzzing: Fix OSS-fuzz build

- pilot/pkg/model/service_test.go
> fix FuzzServiceDeepCopy

- pilot/pkg/serviceregistry/aggregate/controller.go
- pilot/pkg/serviceregistry/aggregate/controller_test.go
- pilot/pkg/serviceregistry/memory/discovery.go
Fix https://github.com/istio/istio/issues/39039
> Fix stale svc clusterVIP fo multicluster

- pilot/pkg/serviceregistry/serviceentry/controller_test.go
fix: https://github.com/istio/istio/issues/39099
@howardjohn please have a test
> Fix test flake by using sync controller

- pilot/pkg/features/pilot.go
- pilot/pkg/xds/eds_test.go
- security/pkg/nodeagent/sds/sdsservice_test.go
For https://github.com/istio/istio/issues/38709. This was a new feature to be shipped in 1.14 but has some issues,
> 1.14: disable PILOT_PARTIAL_FULL_PUSHES

- CODEOWNERS
I think I am qualified to most of the code, so add myself to help review.
Prs reviewed by me https://github.com/istio/istio/pulls?q=is%3Apr+reviewed-by%3Ahzxuzhonghu+
cc @costinm @linsun @howardjohn @nmittler @ericvn
> Add myself to reviewers of some mis code

- pilot/pkg/networking/core/v1alpha3/listener.go
> minor optimization: reduce parse listenerProtocol

- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
- pilot/pkg/networking/core/v1alpha3/listenertest/match.go
Fixes https://github.com/istio/istio/issues/39148
Fixes https://github.com/istio/istio/issues/39000
> pilot: remove authz policies accidentally added to outbound paths

- pilot/pkg/bootstrap/certcontroller.go
- pilot/pkg/bootstrap/istio_ca.go
- pilot/pkg/bootstrap/istio_ca_test.go
- pilot/pkg/bootstrap/server.go
- security/pkg/k8s/chiron/controller.go
- security/pkg/k8s/chiron/utils.go
- security/pkg/k8s/chiron/utils_test.go
the target is to make the code more readable, this includes:
1. args cleanup
2. function abstraction
> Cleanup bootstrap ca/certs init

- tests/integration/security/authz/authz_test.go
This is to help address failing post-submits for ipv6. Restores missing `IPv4` label for methods that had it in the old authz tests.
There are still 2 failing tests, however they will be addressed separately.
> [tf] Skip some authz tests for ipv6

- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
> Rename CombineVhostRoutes to SortVhostRoutes

- pilot/pkg/serviceregistry/kube/controller/multicluster.go
- pkg/kube/multicluster/secretcontroller.go
After https://github.com/istio/istio/pull/39103#pullrequestreview-987744310, it was not complete
> rename to configCluster

- pilot/pkg/serviceregistry/aggregate/controller.go
- pilot/pkg/serviceregistry/aggregate/controller_test.go
- pilot/pkg/serviceregistry/memory/discovery.go
- releasenotes/notes/39039.yaml
manually cherry-pick of https://github.com/istio/istio/pull/39058
> [release-1.12] Fix stale svc clusterVIP fo multicluster

- pkg/test/fakes/imageregistry/Makefile
- pkg/test/framework/components/registryredirector/kube.go
- pkg/test/framework/components/registryredirector/registry_redirector_server.yaml
- pkg/test/framework/features/features.yaml
- tests/integration/telemetry/stats/prometheus/wasm/imagepullpolicy_test.go
- tests/integration/telemetry/stats/prometheus/wasm/registry_setup.go
- tests/integration/telemetry/stats/prometheus/wasm/stats_wasm_filter_test.go
- tests/integration/telemetry/stats/prometheus/wasm/testdata/registry-secret.yaml
- tests/integration/telemetry/stats/prometheus/wasm/testdata/wasm-filter.yaml
- tests/integration/telemetry/stats/prometheus/wasm/wasm_modules/header_injector/.gitignore
- tests/integration/telemetry/stats/prometheus/wasm/wasm_modules/header_injector/BUILD
- tests/integration/telemetry/stats/prometheus/wasm/wasm_modules/header_injector/Dockerfile
- tests/integration/telemetry/stats/prometheus/wasm/wasm_modules/header_injector/Makefile
- tests/integration/telemetry/stats/prometheus/wasm/wasm_modules/header_injector/WORKSPACE
- tests/integration/telemetry/stats/prometheus/wasm/wasm_modules/header_injector/plugin.cc
- tests/integration/telemetry/stats/prometheus/wasm/wasm_modules/header_injector/plugin.h
Merge back https://github.com/istio/istio/pull/38918, which was reverted by https://github.com/istio/istio/pull/39069, with the changes below:
Reduce delay between retries
Increase total timeout
> Merge back "WasmPlugin: Add the integration test for wasm in OCI Images."

- pilot/pkg/controller/workloadentry/workloadentry_controller.go
- releasenotes/notes/39201.yaml
manually cherry-pick of https://github.com/istio/istio/pull/39201
> [Release-1.12] Fix pilot panic with vm workload entry: assignment to entry in nil map 

- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta.go
This PR is analogous to https://github.com/istio/istio/pull/39172, but just for delta xDS.
> [BugFix] WasmPlugin: Call forwardDeltaToEnvoy in the same thread

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_internal_test.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- releasenotes/notes/39188.yaml
Fix https://github.com/istio/istio/issues/39188
Very likely it is broken since #19592 and #27449
> Fix vhost routes orders with catch all

- manifests/charts/istio-control/istio-discovery/templates/NOTES.txt
- operator/cmd/mesh/install.go
> Add install/upgrade survey

- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta.go
Fix https://github.com/istio/istio/issues/39231
> Cherrypick #39230

- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/route/route.go
Checkt the gateway routes before generating virtual hosts.
This PR is a patch for [Fix issues for gateway to make dual stack enable](https://github.com/istio/istio/pull/39264)
> [Dual Stack] Checkt the gateway routes before generating virtual hosts

- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/route/route.go
> Revert "[Dual Stack] Fix issues for gateway to make dual stack enable"

- pilot/pkg/networking/core/v1alpha3/gateway.go
> Revert "[Dual Stack] Checkt the gateway routes before generating virtual hosts"

- operator/pkg/util/merge_iop.go
- operator/pkg/util/merge_iop_test.go
- operator/pkg/util/testdata/overlay-iop.yaml
- releasenotes/notes/39146.yaml
- tests/fuzz/misc_fuzzers.go
fix: https://github.com/istio/istio/issues/39242
manual cherry-pick of https://github.com/istio/istio/pull/39146
> run istioctl verify-install fail on demo profile

- pilot/pkg/xds/endpoint_builder.go
- pkg/test/framework/components/echo/check/checkers.go
- releasenotes/notes/38704.yaml
fixes https://github.com/istio/istio/issues/39229
> [release-1.14] multi-network: fix eastwest gateway endpoint filtering 

- prow/lib.sh
- tools/docker-builder/docker.go
> Update buildkit driver

- pilot/pkg/networking/core/v1alpha3/httproute.go
Reduce pilot CPU usage. Based on the assumption that the number of wildcarded service hosts usually much less than others.
In my environment: 200+ services and 100+ virtualservices, it will reduce CPU usage by 20% when `pushXDS`.
Before:
After:
> reduce loop count in selectVirtualServices

- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
> minor comment in sidecar inbound tls listener

- pilot/pkg/bootstrap/mesh.go
- pilot/pkg/model/network.go
> unify network handlers

- tests/integration/pilot/common/routing.go
Networking Features Proxyless gRPC supports:
* Fault injection
* Traffic shifting/routing
* Retries
> restore some proxyless gRPC test coverage

- pilot/pkg/config/kube/crdclient/client.go
- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/config/kube/ingress/controller.go
- pilot/pkg/config/kube/ingressv1/controller.go
- pilot/pkg/credentials/kube/secrets.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/filter/informer.go
- pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
- pilot/pkg/serviceregistry/kube/controller/serviceexportcache.go
- pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
- pkg/kube/multicluster/secretcontroller.go
- pkg/kube/util.go
- pkg/kube/util_test.go
- pkg/revisions/default_watcher.go
For https://github.com/istio/istio/issues/37092
Remove `metadata.managedFields` since it's large and we never use it
> Adopt transform func to save memory

- pilot/pkg/networking/core/v1alpha3/httproute.go
Add comments for https://github.com/istio/istio/pull/39182
> add comments for optimization of selectVirtualServices

- pilot/cmd/pilot-agent/main.go
dual stack code change for pilot-agent and reset the commit to 40f3a2fa68ee3368583b5b0b29577af4010a39e4
Co-authored-by: jacob-delgado <jacob.delgado@volunteers.acasi.info>
Co-authored-by: irisdingbj <irisdingbj@gmail.com>
Co-authored-by: ycai-aspen <yingchun.cai@volunteers.acasi.info>
> [Dual Stack] dual stack code change for pilot-agent and reset the commit to 40f3a2fa68ee3368583b5b0b29577af4010a39e4

- pilot/pkg/xds/endpoint_builder.go
- pkg/test/framework/components/echo/check/checkers.go
- releasenotes/notes/38704.yaml
- tests/integration/security/authz/testdata/v1beta1/egress-gateway.yaml.tmpl
This reverts commit 7f8c1c102840af1d2df65077be6fb08a446a94dd.
> Revert "multi-network: fix eastwest gateway endpoint filtering (#38762)"

- tests/integration/security/authz/authz_test.go
This should pass now that https://github.com/istio/istio/pull/39332 has landed.
> [tf] Re-enable authz egress test

- pilot/cmd/pilot-agent/main.go
dual stack code change for pilot-agent and reset the commit to 40f3a2fa68ee3368583b5b0b29577af4010a39e4
Co-authored-by: jacob-delgado <jacob.delgado@volunteers.acasi.info>
Co-authored-by: irisdingbj <irisdingbj@gmail.com>
Co-authored-by: ycai-aspen <yingchun.cai@volunteers.acasi.info>
> dual stack code change for pilot-agent and reset the commit to 40f3a2fa68ee3368583b5b0b29577af4010a39e4

- pilot/pkg/networking/core/v1alpha3/accesslog_test.go
bad UT naming may confuse folks
> better UT naming

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/serviceentry/protocoladresses.go
- pkg/config/analysis/analyzers/testdata/serviceentry-missing-addresses-protocol-mesh-cfg.yaml
- releasenotes/notes/38833.yaml
Fix https://github.com/istio/istio/issues/38828
> Fix IST0134 ignore ISTIO_META_DNS_AUTO_ALLOCATE

- pilot/cmd/pilot-agent/main.go
- pilot/cmd/pilot-agent/status/server.go
- pilot/cmd/pilot-agent/status/util/stats.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/security/authn/v1beta1/policy_applier.go
revert code change to gateway issue fixing and re-fix the gateway issues
> revert code change to gateway issue fixing and re-fix the gateway issues

- pilot/pkg/xds/debug.go
Fix https://github.com/istio/istio/issues/39302
> Fix debug race with ads 

- pkg/config/validation/extensionprovider.go
- pkg/config/validation/extensionprovider_test.go
fix: https://github.com/istio/istio/issues/39324
> fix validateExtensionProvider missing implementation

- pilot/pkg/model/sidecar.go
- pilot/pkg/model/sidecar_test.go
- releasenotes/notes/multi-service-merge.yaml
I checked back to release-1.12 and the bug existed there, so I don't think its new (or at least not that new).
> pilot: fix a bug when merge >2 Services together

- pilot/pkg/xds/delta.go
- pilot/pkg/xds/deltatest.go
> Ignore false positive in delta test

- pkg/test/fakes/imageregistry/main.go
Not requires the authentication for the blob retrieval to re-use this in Remote Wasm Loading via HTTP.
Because the OCI registry is using HTTP for retrieval of each blobs, we can share the uploaded Wasm Image for testing HTTP as well.
For the details, please refer to the discussion starting with https://github.com/istio/istio/pull/39225#issuecomment-1144207752
> [WasmPlugin Integration Test] RegistryRedirector: Relax the authentication for blob retrieval

- pilot/pkg/xds/ads.go
- pilot/pkg/xds/delta.go
This does not fully fix https://github.com/istio/istio/issues/39209, but was inspired by analyzing the problem there.
> ads: prefer requests over pushes

- pilot/pkg/xds/ecds.go
Reverts istio/istio#39370
See https://github.com/istio/istio/pull/39370#issuecomment-1151126447, this is insecure
> Revert "only check for verified identify if xds auth is enabled"

- Makefile.core.mk
> Add warning about docker

- pilot/pkg/credentials/kube/multicluster.go
Same as previous refactor done to other multi cluster
> fix cluster updated logic in credential multi cluster

- pilot/pkg/networking/core/v1alpha3/gateway.go
Co-authored-by: zhanghw0354 <zhanghaiwencmss@139.com>
Finally fix the bugs for gateway route configuration generation. The issue relates to the invalid cluster name created by `buildGatewayHTTPRouteConfig` once the dual-stack feature is enabled.
> Finally fix the bugs for gateway route configuration generation.

- istio.deps
Merge the commit c6abaf5e5fd6488d4b654ac7b6a8d4cb44a96316 from release-1.13.5-patch to release 1.13.
- [ x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
> [release-1.13] Update proxy sha (#101)

- istio.deps
Merge the commit f59ce19ec6b63bbb70a65c43ac423845f1129464 from release-1.14.1-patch to release 1.14.
- [X ] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
> [release-1.14] Update proxy sha (#102)

- istio.deps
> [release-1.12] Update proxy sha (#100)

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_test.go
- releasenotes/notes/39430.yaml
Fixes https://github.com/istio/istio/issues/39430
> fix default load balancer with warmup duration

- istioctl/cmd/google.go
- istioctl/cmd/kubeinject.go
- istioctl/pkg/clioptions/central.go
- istioctl/pkg/multixds/gather.go
- istioctl/pkg/multixds/google.go
- istioctl/pkg/xds/client.go
- istioctl/pkg/xds/google.go
- pilot/pkg/model/context.go
Support double authentication in istioctl
Cherry-pick #39424.
> Support double authentication in istioctl

- pilot/pkg/networking/core/v1alpha3/cluster_cache.go
- pilot/pkg/networking/core/v1alpha3/route/route_cache.go
- pilot/pkg/xds/endpoint_builder.go
Optimize various cache key generations by directly appending to hash and not allocating a slice.
Related to https://github.com/istio/istio/issues/39368
> Optimize cache key generation

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_internal_test.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- releasenotes/notes/39188.yaml
This is an manually cherry-pick of https://github.com/istio/istio/pull/39218
Fix: https://github.com/istio/istio/issues/39250
> [release-1.12] Fix vhost routes orders with catch all 

- pilot/cmd/pilot-agent/main.go
- pilot/cmd/pilot-agent/status/server.go
> Revert "[Dual Stack] Fixed bug for stats metrics scraping errors when using different IP families"

- pilot/pkg/model/network_test.go
This is a minor fix observed in google/gvisor#7721.
> pilot/pkg/model: make synchronization canonical

- pkg/kube/multicluster/secretcontroller.go
- releasenotes/notes/39366.yaml
fix https://github.com/istio/istio/issues/39388
> [Release 1.12] Stop previous remote cluster when updating secret 

- pilot/pkg/model/jwks_resolver.go
- tests/integration/security/jwt_test.go
** Tests could become flaky sometime because jwt-server is not active
> Improvement in jwt-test

- pkg/bootstrap/config.go
- pkg/bootstrap/config_test.go
- pkg/istio-agent/agent.go
> manual backport of 37573

- pilot/pkg/networking/core/v1alpha3/accesslog.go
- pilot/pkg/networking/core/v1alpha3/accesslog_test.go
- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
take over https://github.com/istio/istio/pull/39473
fix: https://github.com/istio/istio/issues/39196
> Telemetry: propogate hostname where possible

- samples/open-telemetry/otel.yaml
fixed: https://github.com/istio/istio/issues/39196
> do not inject OTel-collector

- pkg/kube/client.go
- Warn if read yaml file error
- Remove unused function `extractExecResult()`
> kubeclient: Warn if read yaml file error

- pilot/pkg/model/sidecar.go
- pilot/pkg/xds/lds.go
Just fix some style and unnecessary code when i read source
> style(model): avoid compare array with nil, if we will compare it's len

- tools/docker-builder/builder/crane.go
WaitGroup will not done if there are some error during executeing go func
> style(crane) move wg.Done to defer

- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta.go
- pkg/istio-agent/xds_proxy_test.go
> xds proxy minor changes

- pilot/pkg/networking/core/v1alpha3/accesslog.go
- pilot/pkg/networking/core/v1alpha3/accesslog_test.go
- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
- releasenotes/notes/39476.yaml
manual cherry pick https://github.com/istio/istio/pull/39476
fix: https://github.com/istio/istio/issues/39494
> manual cherry pick 39476

- samples/bookinfo/build_push_update_images.sh
Signed-off-by: xin.li <xin.li@daocloud.io>
At the end of executing this script, an error about sed will occur:
Adjusted execution result:
> fix sed error in script

- release/downloadIstioCtl.sh
Changes the output of the downloadIstioCtl script to match documentation. Ref: https://github.com/istio/istio.io/pull/11448
> update downloadIstioCtl script output to match docs

- samples/sleep/sleep-vault.yaml
- samples/sleep/sleep.yaml
Signed-off-by: xin.li <xin.li@daocloud.io>
A small optimization for sleep
> a small optimization for sleep

- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/components/echo/kube/testdata/proxyless-custom-image.yaml
- pkg/test/framework/components/echo/kube/testdata/proxyless.yaml
Update deployment for echo test to include the annotation `proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'`
> Echo Test: Update deployment to hold application until proxy starts

- pilot/cmd/pilot-agent/status/server_test.go
fix defer in loop, maybe resource leak
> improve server_test

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_internal_test.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- releasenotes/notes/39188.yaml
manually cherry-pick of https://github.com/istio/istio/pull/39218
Fix https://github.com/istio/istio/issues/39248
> [release-1.13] Fix vhost routes orders with catch all

- pkg/kube/multicluster/secretcontroller.go
- releasenotes/notes/39366.yaml
fix https://github.com/istio/istio/issues/39389
> [Release 1.13] Stop previous remote cluster when updating secret

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Signed-off-by: Zhonghu Xu <xuzhonghu@huawei.com>
> cleanup: remove h2UpgradeMap

- pilot/pkg/xds/debug.go
- pkg/config/model.go
> pretty print json in debug endpoints

- pilot/pkg/bootstrap/server.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
> add debug logs for config events

- samples/open-telemetry/otel.yaml
upgrade otel image, fix https://github.com/istio/istio.io/pull/11496
> upgrade otel image

- pilot/pkg/model/xds_cache.go
- pilot/pkg/networking/core/v1alpha3/route/route_cache.go
We missed to add this here. Made few function renaming and moved them part of struct.
> add delegate virtual services to cache key

- tests/integration/security/mtls_first_party_jwt/strict_test.go
- tests/integration/security/mtlsk8sca/strict_test.go
- tests/integration/security/reachability_test.go
- tests/integration/security/util/framework.go
- tests/integration/security/util/reachability/context.go
> tf: do not depend on `apps` to determine type of echo

- pkg/test/framework/components/echo/kube/deployment.go
> Fix missing closed files

- pilot/pkg/networking/core/v1alpha3/accesslog_test.go
Fixes https://github.com/istio/istio/issues/39619
> fix listener access log test

- pilot/pkg/xds/bench_test.go
Make the 100 svc + 100 dr compose a rds, which is to simulate more real case
> make benchmark to align with real case

- tests/integration/pilot/gateway_conformance_test.go
- tests/integration/pilot/ingress_test.go
- tests/integration/pilot/main_test.go
> Fix gateway tests on old versions

- pilot/pkg/networking/core/v1alpha3/cluster.go
> minor renaming of methods to avoid confusion in cluster patcher

- pkg/test/framework/components/authz/kube.go
- pkg/test/framework/components/jwt/kube.go
- pkg/test/util/yml/apply.go
- samples/jwt-server/jwt-server.yaml
**Updated the deployment of external authz and jwt-server by adding ImagePullSecrets **
> added imagePullSecret in extauthz and jwt server deployment

- security/pkg/nodeagent/sds/sdsservice_test.go
> Allow running TestSDS concurrently

- tests/integration/security/testdata/beta-mtls-on.yaml
- tests/integration/security/testdata/beta-mtls-permissive.yaml
- tests/integration/security/testdata/no-peer-authn.yaml
> tf: prevent blocking eastwest gateway with test policies

- pilot/pkg/features/pilot.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/ads_test.go
- pilot/pkg/xds/discovery_test.go
- releasenotes/notes/double-ack.yaml
- tests/integration/base.yaml
See https://github.com/envoyproxy/envoy/issues/13009 for details
Fixes #38709 (previously 'fixed', but really the fix was a workaround)
Fixes https://github.com/istio/istio/issues/39720
> xds: respond to requests previously miscategorized as ACKs

- go.mod
- go.sum
> mod: bump quic-go dependency

- pkg/test/framework/components/authz/kube.go
**Updated the ImagePullSecret logic to directly used the secret name instead of path**
> updated the pullsecret logic

- pkg/config/mesh/kubemesh/watcher_test.go
- pkg/test/framework/components/istio/configmap.go
To help debug https://github.com/istio/istio/issues/39747. The test, I
thought, would reproduce it -- but it didn't
> Improve tests and logs around meshconfig update

- pilot/pkg/model/xds_cache.go
> add metrics for dependent config size

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/core/v1alpha3/networkfilter.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/39765.yaml
Implements https://github.com/istio/api
Fixes https://github.com/istio/istio/issues/22635
> implement max connection duration

- istioctl/pkg/tag/util.go
> Fix a multierr usage

- istioctl/cmd/injector-list.go
Checking annotation is not enough, should also check label. If label is present, prefer to use label
> Fix injection check in x injector list

- pilot/pkg/bootstrap/certcontroller.go
- pilot/pkg/bootstrap/istio_ca.go
- pilot/pkg/bootstrap/istio_ca_test.go
- releasenotes/notes/k8s-tls-secret-cacerts.yaml
- security/pkg/nodeagent/caclient/providers/mock/mockcaclient.go
- security/pkg/pki/ca/ca.go
- security/pkg/pki/ca/ca_test.go
- security/pkg/pki/util/generate_cert_test.go
- security/pkg/pki/util/keycertbundle.go
- security/pkg/pki/util/keycertbundle_test.go
- tests/fuzz/pki_fuzzer.go
cherry pick https://github.com/istio/istio/pull/39732
> cherrypicked from master tls secrets format

- pkg/test/framework/components/echo/kube/deployment.go
This makes sure that the flags are parsed and the new values mentioned in the flags are used.
> [tf] load templates outside of init func

- pkg/spiffe/spiffe.go
update the typo for pkg spiffe
> fix: update the typo for pkg spiffe

- go.mod
- go.sum
> gateway-api: bump dependency to fix flakes

- tests/fuzz/kube_gateway_controller_fuzzer.go
> Fix KubernetesResources builder for fuzzer

- istioctl/cmd/analyze.go
- istioctl/cmd/root.go
- istioctl/cmd/workload.go
Fix code comment typos in the source code.
> fix: update the typo code comment for pkg istioctl/cmd

- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/core/v1alpha3/cluster_test.go
- pilot/pkg/xds/eds_test.go
- releasenotes/notes/39825.yaml
Fixes https://github.com/istio/istio/issues/39825
> disable sending unhealthy endpoints by default

- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_test.go
- pilot/pkg/xds/eds_test.go
- releasenotes/notes/39825.yaml
Manual BP of https://github.com/istio/istio/pull/39834
> [release-1.14] disable sending unhealthy endpoints by default #39871

- tests/integration/operator/switch_cr_test.go
> Fix operator test on 1.25

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
> validation: do not warn about ECDS types

- pkg/test/framework/components/istio/configmap.go
This is cherrypicked from release-1.8 branch. Fixes
https://github.com/istio/istio/issues/39747
> tf: fast mesh config update for Istiodless

- pilot/pkg/model/endpointshards.go
> Fix bug blocking JSON marshal of endpointShardz

- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/testdata/benchmarks/telemetry-api.yaml
this's part of https://github.com/istio/istio/issues/39472
cc @howardjohn
> improve telemetry bench test

- pilot/pkg/xds/ads.go
This mirrors the PUSH log syntax to make it easier to read
> xds: improve req log consistency

- pkg/hbone/dialer_test.go
> Prevent illegal logs in goroutines in hbone test

- pkg/queue/delay.go
- pkg/queue/delay_test.go
- pkg/queue/util.go
- security/pkg/server/ca/authenticate/cert_authenticator.go
- security/pkg/server/ca/server_test.go
Removed from few left over files
> remove year from copyright

- pilot/cmd/pilot-agent/options/agent.go
- pilot/cmd/pilot-agent/options/options.go
- pkg/dns/client/dns.go
- pkg/dns/client/dns_test.go
- pkg/istio-agent/agent.go
- releasenotes/notes/agent-dns-forward-parallel.yaml
> dns: added DNSForwardParallel to support sending parallel queries to all name servers

- docker/Dockerfile.distroless
Update base version of the distroless image
> Bump distroless base

- bin/update_deps.sh
Update branch used in update_deps
> [release-1.13] Update branch for update_deps

- pilot/pkg/features/pilot.go
- pilot/pkg/model/context.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/ads_test.go
- pilot/pkg/xds/discovery_test.go
Attempt for a generic fix for https://github.com/istio/istio/pull/39937
> handle non wildcard resources during reconnect

- pilot/pkg/networking/core/v1alpha3/gateway_simulation_test.go
I was working on a fix but don't have time to complete for now. At least
we can check in the test case to codify the bug and make it simpler when
we fix it eventually.
> Add test for unfixed SNI overlapping bug

- tests/integration/security/reachability_test.go
I think this may effectively work around
https://github.com/istio/istio/issues/38982 by ensuring we don't send to
multiple ports in parallel anymore. Runtime and coverage should be the
same, only order changed.
> test reachability: make protocol on outer loop

- pilot/pkg/xds/ads.go
- pilot/pkg/xds/delta.go
In testing we confirmed the same thing applies to delta, and the same
fix should work. Adding it there.
Also bumping the main one down to only apply if its already an ACK to
avoid confusing logs. The behavior, aside from logs, is the same.
> Add AlwaysRespond logic to Delta XDS as well

- pkg/test/framework/components/jwt/kube.go
**This PR adds the imagePullSecret option for custom jwt-server used in jwt tests**
> added imagePullSecret in custom jwt-server

- tests/integration/pilot/gateway_conformance_test.go
- tests/integration/pilot/ingress_test.go
> tf: wait for CRDs to be established before Gateway tests

- tests/integration/telemetry/stats/prometheus/nullvm/accesslogs_test.go
add telemetry e2e test with default provider
> [e2e test]add telemetry e2e test with default provider

- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/route/route_cache.go
- releasenotes/notes/rds-cache-allow-any.yaml
Fixes
https://github.com/istio/istio/issues/39794#issuecomment-1189140847
> Check AllowAny mode in RDS cache key

- operator/pkg/helmreconciler/prune.go
git cherry-pick d6b560d25480a19b8f653ae537d06607ce6b4cf2
Fixed: https://github.com/istio/istio/issues/40025
> Change the warning message to debug message

- tests/fuzz/kube_gateway_controller_fuzzer.go
- tests/fuzz/pilot_model_fuzzer.go
> Ensure a few fields are non-null for fuzz tests

- pilot/pkg/model/context.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/delta.go
- pilot/pkg/xds/discovery_test.go
Remove `VersionSent NonceNacked LastSent`
> Remove unused attributes of WatchedResource to reduce memory

- pkg/test/framework/components/jwt/kube.go
Signed-off-by: yxxhero <aiopsclub@163.com>
cleanup ioutil
> cleanup ioutil

- pilot/pkg/model/push_context.go
Signed-off-by: Zhonghu Xu <xuzhonghu@huawei.com>
FIx https://github.com/istio/istio/pull/40035#discussion_r927576239
> Minor comments fix

- pilot/pkg/features/pilot.go
authenication -> authentication
> fix typo in pilot.go

- pilot/pkg/xds/ads.go
- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta.go
> use same xds types every where

- pkg/istio-agent/metrics/metrics.go
These two variables should be defined as constants
> Update constant definitions for metrics

- go.mod
- licenses/golang.org/x/exp/LICENSE
- pilot/pkg/networking/core/v1alpha3/gateway_simulation_test.go
- pilot/test/xdstest/extract.go
> xdstest: use some generic functions instead of hacks

- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_test.go
- pilot/pkg/serviceregistry/kube/controller/endpoints.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/eds_test.go
- pkg/test/util.go
Fixes https://github.com/istio/istio/issues/39925
> move send unhealthy endpoint flag to atomic bool

- pilot/pkg/xds/ecds.go
- pilot/pkg/xds/ecds_test.go
- releasenotes/notes/40093.yaml
manual cherry-pick #40093 
fix: #40147
> [release-1.14] fix multi WasmPlugin with different imagePullSecrets

- go.mod
- go.sum
- istio.deps
- prow/release-commit.sh
Run update_deps before building new patch
> [release-1.14] Run update_deps.sh

- docker/Dockerfile.distroless
- go.mod
- go.sum
- istio.deps
- pilot/docker/Dockerfile.proxyv2
- prow/release-commit.sh
Run update_deps.sh for 1.13. The proxy build isn't done so the test may fail until that proxy artifact is available.
> [release-1.13] Run update_deps.sh

- samples/bookinfo/build_push_update_images.sh
improve build_push_update_images.sh
> improve build_push_update_images.sh

- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- releasenotes/notes/39505.yaml
resolves https://github.com/istio/istio/issues/39505
> workload instance cause stale CDS clusters of type STRICT_DNS

- pilot/pkg/config/kube/gateway/controller.go
- pilot/pkg/config/kube/gateway/controller_test.go
- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/model/context.go
- pilot/pkg/model/push_context.go
- Minor function renaming
- Remove unnecessary call to convertReferencePolicies
> minor refactor in gateway api

- pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
- pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
- releasenotes/notes/39505.yaml
manual cherry-pick of https://github.com/istio/istio/pull/39947
> Cherrypick 39947

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/testdata/virtualservice_conflictingmeshgatewayhosts.yaml
- pkg/config/analysis/analyzers/testdata/virtualservice_conflictingmeshgatewayhosts_with_exportto.yaml
- pkg/config/analysis/analyzers/util/exportto.go
- pkg/config/analysis/analyzers/util/exportto_test.go
- pkg/config/analysis/analyzers/virtualservice/conflictingmeshgatewayhosts.go
- releasenotes/notes/39729.yaml
https://github.com/istio/istio/pull/39841 failed. Manual cherry-pick and fix ut.
@GregHanson PTAl. https://github.com/istio/istio/pull/39841 This one failed because I didn't cherry-pick https://github.com/istio/istio/pull/37581, and I used `v1beta1` in the test. Just revised the ut to `v1alpha3`.
> [release-1.14] manual cherry pick 39729

- CODEOWNERS
- pkg/fuzz/util.go
> fuzz: attempt to fix build by working around fuzzing limitation

- go.mod
- go.sum
- istio.deps
- prow/release-commit.sh
Created with `DRY_RUN=false STEP=1 ./release/branch.sh`
> Automated branching step 1

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/testdata/virtualservice_destinationhosts.yaml
- pkg/config/analysis/analyzers/util/service_lookup.go
- pkg/config/analysis/analyzers/virtualservice/destinationhosts.go
- releasenotes/notes/40244.yaml
Fix https://github.com/istio/istio/issues/39629
> Fix export to logic lead to not found logic

- pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
- pilot/pkg/xds/eds.go
> fix eds comments

- cni/pkg/plugin/testdata/basic.txt.golden
- cni/pkg/plugin/testdata/dns.txt.golden
- cni/pkg/plugin/testdata/include-exclude-ip.txt.golden
- cni/pkg/plugin/testdata/include-exclude-ports.txt.golden
- cni/pkg/plugin/testdata/invalid-drop.txt.golden
- cni/pkg/plugin/testdata/tproxy.txt.golden
- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/listener_builder.go
- pilot/pkg/networking/core/v1alpha3/tls.go
- pilot/pkg/xds/eds.go
- pkg/bootstrap/config.go
> [Experimental dual-stack] Run make gen

- istioctl/pkg/validate/validate.go
> Fix fake v1beta1 conversion in validate

- pkg/envoy/agent.go
> Remove unused fields of Agent

- pkg/config/analysis/local/context.go
- releasenotes/notes/40184.yaml
introduced by PR #38467, this cause a lot of  noise in #38148 and #38986
change log level to debug before found a completed solution to fix that.
> change log level

- bin/update_deps.sh
Change `UPDATE_BRANCH` to release-1.15
> [release-1.15] Change update_deps.sh with release-1.15

- pilot/pkg/model/push_context.go
- pkg/spiffe/spiffe.go
> do not repeat trust id in logs

- pilot/pkg/bootstrap/server.go
- pilot/pkg/xds/debug.go
In some scenarios, it would be very useful to call debug functions before the server is ready to debug startup issues.
> start admin interface earlier

- Makefile.core.mk
- tools/docker-builder/main.go
- tools/docker.yaml
> Support debug building mode

- pkg/test/framework/components/echo/common/deployment/echos.go
- pkg/test/framework/components/echo/common/deployment/namespace.go
- pkg/test/framework/components/echo/config.go
- pkg/test/framework/components/echo/deployment/builder.go
- pkg/test/framework/components/istio/config.go
- pkg/test/framework/components/istio/eastwest.go
- pkg/test/framework/components/istio/kube.go
- tests/integration/security/ca_custom_root/main_test.go
- tests/integration/security/ecc_signature_algorithm/main_test.go
- tests/integration/security/ecc_signature_algorithm/mtls_strict_test.go
- tests/integration/security/file_mounted_certs/main_test.go
- tests/integration/security/file_mounted_certs/p2p_mtls_test.go
**Refactored few security tests to support new test framework, added support for customizable east-west gateway configuration**
> security tests refactor

- security/pkg/k8s/configutil_test.go
Fix https://github.com/istio/istio/issues/40199
> Fix TestInsertDataToConfigMap flake

- pilot/pkg/model/validation.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
Fix [issue#40245](https://github.com/istio/istio/issues/40245) for Sidecar's defaultEndpoint is IPv6 format
> Fix bug for for Sidecar's defaultEndpoint is IPv6 format

- samples/security/spire/sleep-spire.yaml
> improve sleep-spire.yaml

- pkg/config/analysis/analyzers/injection/injection.go
- pkg/config/analysis/analyzers/testdata/injection.yaml
- releasenotes/notes/40220.yaml
manual cherrypick of https://github.com/istio/istio/pull/40220, and dependent PR https://github.com/istio/istio/pull/40164
> Cherrypick 40220

- pilot/pkg/model/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
- releasenotes/notes/40268.yaml
fix https://github.com/istio/istio/issues/40268
- [x ] Networking
> fix gateway with different bind to have same host

- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/config/kube/crdclient/client.go
- pilot/pkg/config/kube/crdclient/client_test.go
- pilot/pkg/serviceregistry/kube/controller/multicluster.go
- pkg/config/analysis/incluster/controller.go
- pkg/config/analysis/local/istiod_analyze.go
To clearly distinguish controller logs
> add identifier to crd client logs

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- releasenotes/notes/40299.yaml
Manual backport of https://github.com/istio/istio/pull/40320
> [release-1.13] unify timeout logic across service and virtual service

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_logging_test.go
- pilot/pkg/model/telemetry_test.go
- pilot/pkg/networking/core/v1alpha3/accesslog.go
- releasenotes/notes/39521.yaml
fix: https://github.com/istio/istio/issues/39468
> fix multi accesslogging not working

- pilot/pkg/model/telemetry_logging.go
- pilot/pkg/model/telemetry_logging_test.go
> telemetry logging: insert newlines in format, per spec

- tests/integration/pilot/istioctl_test.go
- tests/integration/pilot/piggyback_test.go
This is failing recently since we made proxy disconnect from control
plane more often. This exposed that these tests fail if they happen to
run when not connected.
Fixes https://github.com/istio/istio/issues/37169
Fixes https://github.com/istio/istio/issues/40273
> tf: Fix Istioctl XDS flakes

- manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
- manifests/charts/istio-control/istio-discovery/files/grpc-agent.yaml
- pkg/kube/inject/testdata/inject/grpc-agent.yaml.injected
- pkg/kube/inject/testdata/inputs/custom-template.yaml.34.template.gen.yaml
- pkg/kube/inject/testdata/inputs/default.template.gen.yaml
- pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
- pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
- pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
- pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
* Merge changes from istio template
* Remove security section
* Missing end
* Make gen, remove the ifs and add lifecycle - grpc starts very fast
* Few debug statements to figure out why wait doesn't work
* Use the agent ready port
* Rever the deugging changes
* make gen
> Merge changes from istio template (#38837)

- pilot/pkg/security/authz/builder/testdata/tcp/allow-both-http-tcp-in.yaml
- pilot/pkg/security/authz/builder/testdata/tcp/allow-both-http-tcp-out.yaml
- pilot/pkg/security/authz/builder/testdata/tcp/deny-both-http-tcp-in.yaml
- pilot/pkg/security/authz/builder/testdata/tcp/deny-both-http-tcp-out.yaml
**This PR tests the behavior of TCP Filter when we add  a policy which has both http and tcp attributes**
> added few more test scenarios in authz builder

- pkg/queue/instance_test.go
> Add benchmarks for queue

- pilot/pkg/model/telemetry_logging.go
- pilot/pkg/model/telemetry_logging_test.go
- pilot/pkg/networking/core/v1alpha3/accesslog.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
follow https://github.com/istio/istio/pull/40411
> telemetry logging: refactor fileAccessLogFormat

- tools/istio-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/validation/validator.go
currently the logging is not user friendly -- we just report validation
failed, but not what it is validating or why
> cni: improve logging of istio-validation

- pkg/queue/instance.go
To better understand and segregate get and process functions of queue
> refactor get and process functionality of queue

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
after https://github.com/istio/istio/pull/39521  we should loose telemetry accesslogging validation
> loose telemetry accesslogging validation 

- pilot/pkg/autoregistration/controller.go
- pilot/pkg/config/kube/crdclient/client.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pkg/kube/inject/webhook.go
- pkg/kube/multicluster/secretcontroller.go
- pkg/kube/multicluster/secretcontroller_test.go
- pkg/test/csrctrl/controllers/csr_controller.go
- pkg/test/failer.go
- pkg/test/framework/components/environment/kube/flags.go
- pkg/test/kube/dump.go
- security/pkg/nodeagent/cache/secretcache.go
> Fix invalid use of formatting in logs

- istioctl/cmd/wait.go
> Update message for number of sidecars

- tools/docker-builder/main.go
No need to log a bunch on each call
> docker: remove redundant logs

- pkg/test/fakes/imageregistry/.gitignore
- pkg/test/fakes/imageregistry/Dockerfile
- pkg/test/fakes/imageregistry/Makefile
- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/components/environment/kube/flags.go
- pkg/test/framework/components/environment/kube/settings.go
- pkg/test/framework/components/opentelemetry/opentelemetry-collector.yaml
- pkg/test/framework/components/stackdriver/stackdriver.yaml
- samples/ratelimit/rate-limit-service.yaml
- tests/integration/pilot/vm_test.go
- tests/integration/tests.mk
> Update test images to multiarch supported versions

- pilot/cmd/pilot-agent/status/server.go
- pilot/cmd/pilot-agent/status/server_test.go
- pkg/test/echo/server/endpoint/http.go
- releasenotes/notes/http2-probes.yaml
manual cherry-pick of PR #40307
> Respect ALPN negotiation in agent probe

- pkg/test/framework/components/namespace/namespace.go
- tests/integration/pilot/gateway_conformance_test.go
manual cherry-pick of https://github.com/istio/istio/pull/39583
> dump gateway conformance suite (#39583)

- pkg/test/framework/components/echo/common/deployment/echos.go
- pkg/test/framework/components/echo/common/deployment/namespace.go
- pkg/test/framework/components/namespace/kube.go
- pkg/test/framework/components/namespace/namespace.go
Manual cherry-pick of https://github.com/istio/istio/pull/38969, also includes dependent PR https://github.com/istio/istio/pull/38540
> Cherrypick 38969

- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/httproute_test.go
- pilot/pkg/simulation/traffic.go
- pkg/test/echo/cmd/client/main.go
- pkg/test/util/assert/assert.go
- releasenotes/notes/ignore-port.yaml
- tests/integration/pilot/common/routing.go
Cherrpick b271cf01fc65bce1e9b5e5726db45b1563b8cf93
> Ignore port number in domain matching entirely (#40475)

- pkg/test/fakes/gce_metadata_server/Dockerfile
- pkg/test/fakes/gce_metadata_server/Makefile
- pkg/test/framework/components/gcemetadata/gce_metadata_server.yaml
- pkg/test/framework/components/registryredirector/registry_redirector_server.yaml
> Bump gce metadata fake with arm64

- pilot/pkg/bootstrap/server_test.go
- pilot/pkg/model/network_test.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/model/xds_cache_test.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/core/v1alpha3/cluster_test.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
- pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
- pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
- pilot/pkg/networking/networking_test.go
- pilot/pkg/networking/util/util_test.go
- pilot/pkg/security/authn/v1beta1/policy_applier_test.go
- pilot/pkg/serviceregistry/kube/controller/multicluster_test.go
- pilot/pkg/serviceregistry/kube/controller/serviceexportcache_test.go
- pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go
- pilot/pkg/serviceregistry/serviceentry/conversion_test.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/deltaadstest.go
- pkg/config/gateway/gateway_test.go
- pkg/config/validation/validation_test.go
- pkg/kube/inject/inject_test.go
- pkg/kube/multicluster/secretcontroller_test.go
- pkg/test/util.go
- pkg/test/util_test.go
> Cleanup `SetForTest` types

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- pkg/bootstrap/config.go
- pkg/bootstrap/instance_test.go
- pkg/bootstrap/testdata/all_golden.json
- pkg/bootstrap/testdata/auth_golden.json
- pkg/bootstrap/testdata/authsds_golden.json
- pkg/bootstrap/testdata/default_golden.json
- pkg/bootstrap/testdata/metrics_no_statsd_golden.json
- pkg/bootstrap/testdata/running_golden.json
- pkg/bootstrap/testdata/runningsds_golden.json
- pkg/bootstrap/testdata/stats_inclusion_golden.json
- pkg/bootstrap/testdata/tracing_datadog_golden.json
- pkg/bootstrap/testdata/tracing_lightstep_golden.json
- pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
- pkg/bootstrap/testdata/tracing_stackdriver_golden.json
- pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
- pkg/bootstrap/testdata/tracing_tls_golden.json
- pkg/bootstrap/testdata/tracing_zipkin_golden.json
- pkg/bootstrap/testdata/xdsproxy_golden.json
adds support for https://github.com/istio/api/pull/2405
> add stat_prefix support for virtual service api

- pilot/cmd/pilot-discovery/app/cmd.go
> fix typos in pilot-discovery cmd

- pkg/istio-agent/agent.go
> istio-agent reuse fileExists

- pilot/pkg/xds/endpoint_builder.go
> minor rename to avoid confusion

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/model/sidecar_test.go
- pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go
To not mixup prod code with test code
> change SetDestinationRules for testing only

- pkg/bootstrap/config.go
- pkg/bootstrap/testdata/all_golden.json
- pkg/bootstrap/testdata/auth_golden.json
- pkg/bootstrap/testdata/authsds_golden.json
- pkg/bootstrap/testdata/default_golden.json
- pkg/bootstrap/testdata/metrics_no_statsd_golden.json
- pkg/bootstrap/testdata/running_golden.json
- pkg/bootstrap/testdata/runningsds_golden.json
- pkg/bootstrap/testdata/stats_inclusion_golden.json
- pkg/bootstrap/testdata/tracing_datadog_golden.json
- pkg/bootstrap/testdata/tracing_lightstep_golden.json
- pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
- pkg/bootstrap/testdata/tracing_stackdriver_golden.json
- pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
- pkg/bootstrap/testdata/tracing_tls_golden.json
- pkg/bootstrap/testdata/tracing_zipkin_golden.json
- pkg/bootstrap/testdata/xdsproxy_golden.json
fixes regex expression for stat_prefix added in https://github.com/istio/istio/pull/40503
> fix regex expression for stat_prefix

- pilot/pkg/xds/ads.go
- pilot/pkg/xds/discovery.go
> cleanup some comments in ads

- pilot/pkg/networking/core/v1alpha3/route/route.go
> refactor hashbydestination to a separate function

- pilot/pkg/xds/bootstrapds.go
- pilot/pkg/xds/discovery.go
- pkg/istio-agent/agent.go
- pkg/istio-agent/bootstrap_client.go
- pkg/istio-agent/bootstrap_stream.go
The logic of bootstrap config discovery can lead to goroutine leak if it times out.
And also separate the bootstrap discovery stream.
> Fix bootstrap discovery service 

- pilot/pkg/serviceregistry/kube/controller/controller.go
- tests/fuzz/README.md
Fix fuzz issue, and document how to reproduce
> Always set endpoints controller

- pkg/bootstrap/platform/gcp.go
- pkg/bootstrap/platform/gcp_test.go
This PR resolves issue #39950. By implementing these two changes:
- Execute queries to the GCP Metadata API as a batch whenever possible.
- Checking if the API is accessible in the first place.
> Gcp concurrent requests

- pilot/pkg/model/xds_cache.go
> use registerIf to disable metrics in xds cache

- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta.go
As discovered https://github.com/istio/istio/issues/35263
> improve xds proxy logs

- go.mod
- go.sum
Prior we bumped to master to pick up a needed fix; now we can use
release version.
> Switch to official gRPC release version

- prow/integ-suite-kind.sh
> Switch kind image in testing to 1.25.0

- pkg/kube/apimirror/probe.go
- tests/integration/security/fuzz/fuzz_test.go
> Lint fixes for golangci-lint 1.49.0

- pilot/pkg/xds/monitoring.go
Fixes https://github.com/istio/istio/issues/39147
> Fix stale comments

- pkg/backoff/exponential.go
- pkg/backoff/exponential_test.go
For https://github.com/istio/istio/issues/40626
> Backoff wrapper

- samples/kind-lb/setupkind.sh
> improve kind-lb/setupkind

- docker/Dockerfile.distroless
- go.mod
- go.sum
- prow/release-commit.sh
> [release-1.15] Run update_deps.sh

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
> add additional test cases for service visibility

- prow/config/metrics/metrics.yaml
- samples/health-check/liveness-command.yaml
- samples/security/spire/spire-quickstart.yaml
> Update k8s registry

- pkg/config/analysis/analyzers/injection/injection-image.go
- pkg/config/analysis/incluster/controller.go
Two fixes:
1. We are infinite loop on stop when it triggers. `break` is for the
switch, not the `for`.
2. No need to use regex
Fixes https://github.com/istio/istio/issues/40580
> analysis: optimize performance and fix dead loop

- pilot/pkg/config/kube/gateway/conditions.go
- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/testdata/route-binding.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/route-binding.yaml
> Gateway api route kind status fixes

- samples/kind-lb/setupkind.sh
> improve setupkind.sh

- pkg/bootstrap/platform/gcp.go
Fix issue with SyncOnlyOnce being global.
- [ X] Configuration Infrastructure
- [ X] Test and Release
> Fix sync issue in GCP platform

- tests/integration/pilot/istioctl_test.go
We missed a retry; this fails when the a pod hapens to be temporarily
disconnected
> tf: properly retry in TestProxyStatus

- samples/bookinfo/build_push_update_images.sh
improve exit code for build_push_update_images.sh help
> improve exit code for build_push_update_images.sh help

- tools/go-compile-verbose
> Improve go-compile-verbose to output to a file

- go.mod
- go.sum
- pilot/pkg/config/kube/gateway/conditions.go
- tests/integration/pilot/gateway_conformance_test.go
> gateway-api: skip GatewaySecretMissingReferencedSecret for now

- pilot/pkg/config/file/store.go
> Fix analyze list index may be out of bound

- CODEOWNERS
Because samples are primarily aligned with the English docs and their READMEs are written in English, PRs should get sign-off from an English doc maintainer before merging.
> Update ownership of samples directory

- pilot/pkg/config/kube/crdclient/client.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pkg/kube/client.go
- pkg/kube/controllers/queue.go
- pkg/kube/multicluster/secretcontroller.go
> Retry for adding remote cluster

- pkg/channels/unbounded.go
- pkg/channels/unbounded_test.go
- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta.go
> Avoid type casts in channels package

- pilot/pkg/networking/core/v1alpha3/httproute.go
When building RDS, cache get is always conducted not respecting the
PILOT_ENABLE_RDS_CACHE flag. This PR fixes that.
Cache add already respects the flag:
https://github.com/istio/istio/blob/1.14.3/pilot/pkg/networking/core/v1alpha3/httproute.go#L212
> fix PILOT_ENABLE_RDS_CACHE flag not working

- pilot/pkg/features/pilot.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
- pilot/pkg/serviceregistry/kube/controller/multicluster.go
- releasenotes/notes/workload-entry-service-select.yaml
resolves https://github.com/istio/istio/issues/40762
> [Release-1.14] Manual cherrypick #40716

- tests/integration/pilot/piggyback_test.go
> Properly retry in TestPiggyback

- pilot/pkg/features/pilot.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
- pilot/pkg/serviceregistry/kube/controller/multicluster.go
- releasenotes/notes/workload-entry-service-select.yaml
resolves https://github.com/istio/istio/issues/40761
> [Release-1.15] Manual cherry-pick #40716

- samples/bookinfo/src/ratings/Dockerfile
- samples/bookinfo/src/ratings/ratings.js
Without this the pod sticks around for 30s; it should shutdown once its
done serving traffic
> bookinfo ratings: graceful shutdown

- pilot/pkg/serviceregistry/kube/controller/controller.go
Fixes https://github.com/istio/istio/issues/38562
> fix weird error message when networks is used

- istioctl/pkg/writer/envoy/clusters/clusters.go
- istioctl/pkg/writer/envoy/configdump/endpoint.go
> Add support for internal address in istioctl commands

- istioctl/cmd/kubeuninject.go
- istioctl/cmd/testdata/uninject/cronjob-with-app.yaml
- istioctl/cmd/testdata/uninject/cronjob.yaml
- istioctl/cmd/testdata/uninject/daemonset.yaml
- istioctl/cmd/testdata/uninject/deploymentconfig-app-probe.yaml
- istioctl/cmd/testdata/uninject/deploymentconfig-multi.yaml
- istioctl/cmd/testdata/uninject/deploymentconfig.yaml
- istioctl/cmd/testdata/uninject/enable-core-dump.yaml
- istioctl/cmd/testdata/uninject/hello.yaml
- istioctl/cmd/testdata/uninject/job.yaml
- istioctl/cmd/testdata/uninject/list.yaml
- istioctl/cmd/testdata/uninject/pod.yaml
- istioctl/cmd/testdata/uninject/replicaset.yaml
- istioctl/cmd/testdata/uninject/replicationcontroller.yaml
- istioctl/cmd/testdata/uninject/statefulset.yaml
- releasenotes/notes/uninject-not-work.yaml
> Fix un-inject cannot remove injection

- security/pkg/k8s/chiron/utils.go
- security/pkg/pki/util/crypto.go
- security/pkg/pki/util/crypto_test.go
- security/pkg/pki/util/verify_cert.go
- tests/fuzz/pki_fuzzer.go
> Simplify the logic of verifying cert expire and getting root

- pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
- pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
- releasenotes/notes/update-se-instances.yaml
[release-1.14] manual backport of https://github.com/istio/istio/pull/39570
> [release-1.14] update SE instances on WE change

- samples/open-telemetry/README.md
A little improve for open-telemetry/readme
> A little improve for open-telemetry/readme

- pkg/test/framework/components/echo/kube/workload.go
> Fix missing unlock

- pkg/backoff/exponential.go
- pkg/istio-agent/agent_test.go
- pkg/istio-agent/fake_bootstrap_generator.go
> Backoff cleanup

- pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
- pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
- releasenotes/notes/update-se-instances.yaml
[release-1.13] manual backport of https://github.com/istio/istio/pull/39570
> [release-1.13] update SE instances on WE change

- pilot/pkg/model/gateway.go
> simplify GetSNIHostsForServer function using sets

- samples/bookinfo/platform/kube/bookinfo-db.yaml
- samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
- samples/bookinfo/platform/kube/bookinfo-details.yaml
- samples/bookinfo/platform/kube/bookinfo-mysql.yaml
- samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
- samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
- samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
- samples/bookinfo/platform/kube/bookinfo-ratings.yaml
- samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
- samples/bookinfo/platform/kube/bookinfo.yaml
The individual PRs already have release notes
> bookinfo: rebuild to pull in multi-arch support

- samples/helloworld/src/Dockerfile
improve sample/helloworld/dockerfile
> improve helloworld/dockerfile

- pkg/istio-agent/xds_proxy.go
- security/pkg/nodeagent/caclient/providers/citadel/client.go
Fixes https://github.com/istio/istio/pull/40452, which is not on any release branch
> agent: fix regression in SAN check for agent

- tools/docker-builder/docker.go
This was incorrectly parsing before; simplify with new command
> docker: fix check for buildx instance

- pilot/pkg/networking/core/v1alpha3/accesslog.go
- pilot/pkg/networking/core/v1alpha3/accesslog_test.go
> Cleanup duplicate EnvoyJSONLogFormatIstio

- tests/integration/pilot/locality_test.go
- tests/integration/security/filebased_tls_origination/egress_gateway_origination_test.go
- tests/integration/security/sds_ingress/util/util.go
> tf: cleanup old usages of template

- istioctl/cmd/precheck.go
> istioctl precheck: disable slow check when not needed

- pilot/pkg/security/authz/matcher/header_test.go
Add more unit tests for header matching
> Add prefix and * header match tests

- pilot/pkg/networking/ambientgen/ztunnelgen.go
> Fix buildInboundPlaintextCaptureListener statPrefix

- pilot/pkg/networking/core/v1alpha3/tracing.go
Fixes https://github.com/istio/istio/issues/40907
> [release-1.14] use protobuf getter functions for nil-safe in tracing provider config

- pilot/pkg/networking/core/v1alpha3/tracing.go
Fixes https://github.com/istio/istio/issues/40908
> [release-1.15] use protobuf getter functions for nil-safe in tracing provider config #40908

- pilot/pkg/networking/core/v1alpha3/tracing.go
Fixes https://github.com/istio/istio/issues/40906
> [release-1.13] use protobuf getter functions for nil-safe in tracing provider config

- Makefile.core.mk
- bin/init.sh
Manual cherrypick of #40913 - Quick fix to get builds working on a Mac
> [release-1.14] Manual cherrypick of #40913 - Quick fix to get builds working on a Mac

- istioctl/cmd/precheck.go
manual  cherry pick
fixes: https://github.com/istio/istio/issues/40883
> [release-1.15] istioctl precheck: disable slow check when not needed (#40602)

- pilot/pkg/model/endpointshards.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/core/v1alpha3/cluster_cache.go
- pilot/pkg/networking/grpcgen/cds.go
- pilot/pkg/xds/cds_test.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/eds_test.go
- pkg/util/sets/string.go
- releasenotes/notes/dr-san-validation.yaml
- releasenotes/notes/full-push-regression.yaml
Cherrypicks two commits together since they are dependant
> [1.15] Cherrypick SubjectAltName processing improvements

- pilot/docker/Dockerfile.proxyv2
fix: https://github.com/istio/istio/issues/40937
> [release-1.13] Bump iptables image (#40928)

- pilot/docker/Dockerfile.proxyv2
fix: https://github.com/istio/istio/issues/40938
> [release-1.14] Bump iptables image (#40928) 

- pilot/docker/Dockerfile.proxyv2
fix: https://github.com/istio/istio/issues/40939
> [release-1.15] Bump iptables image (#40928)

- cni/pkg/ambient/informers.go
- fix nit comment
- rename `newPodInformer` to `podHandler`
- improve log
- minor code refactor
> ambient: improve cni informer

- pilot/pkg/ambient/controller/workloadcache.go
> ambinent: use lister in workloadcache 

- pilot/pkg/networking/ambientgen/ztunnelgen.go
I think this was due to s/remote/waypoint. Could be very confusing.
> rename: outbound service cluster

- istioctl/cmd/config_test.go
- istioctl/cmd/options.go
- istioctl/cmd/options_test.go
- istioctl/cmd/root.go
- releasenotes/notes/38236.yaml
Reverts istio/istio#38236
See https://github.com/istio/istio/pull/38236#pullrequestreview-1106554433
cc @hanxiaop
> Revert "Improve istioctl options command description"

- pilot/pkg/model/service.go
followup https://github.com/istio/istio/pull/40966#discussion_r970241476
> remove comments

- pilot/pkg/model/fuzz_test.go
> Add full fuzz tests for deepcopy

- pilot/pkg/model/push_context_test.go
> Add tests for destinationrule

- pilot/pkg/config/kube/gateway/fuzz_test.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/fuzz_test.go
- pilot/pkg/networking/core/v1alpha3/fuzz_test.go
- pilot/pkg/security/authz/builder/fuzz_test.go
- pilot/pkg/serviceregistry/kube/controller/fuzz_test.go
- pkg/fuzz/skip.go
- pkg/fuzz/skip_gofuzz.go
- pkg/fuzz/util.go
- security/pkg/server/ca/fuzz_test.go
> fuzzers: workaround lack of t.Skip() in oss-fuzz

- samples/helloworld/README.md
- samples/helloworld/gateway-api/README.md
- samples/helloworld/gateway-api/helloworld-gateway.yaml
- samples/helloworld/gateway-api/helloworld-route.yaml
- samples/helloworld/gateway-api/helloworld-versions.yaml
> Add gateway-api configuration to helloworld sample

- cni/pkg/ambient/informers.go
- pilot/pkg/ambient/controller/aggregate.go
- pilot/pkg/ambient/controller/autolabel.go
- pilot/pkg/ambient/controller/waypoint_controller.go
- pilot/pkg/ambient/controller/workloadcache.go
- pilot/pkg/bootstrap/leak_test.go
- pilot/pkg/bootstrap/server.go
- pilot/pkg/networking/ambientgen/workload_metadata.go
- pilot/pkg/xds/ecds.go
- pilot/pkg/xds/fake.go
- pkg/kube/controllers/queue.go
- pkg/revisions/default_watcher.go
> Add leader election for ambient waypoint controller

- samples/bookinfo/src/build-services.sh
improve build-services script usage exit code
> improve build-services script usage exit code

- pilot/pkg/model/extensions.go
- pilot/pkg/model/extensions_test.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_builder.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pkg/config/validation/validation.go
- releasenotes/notes/wasm-traffic-selector.yaml
This PR implements https://github.com/istio/api/pull/2412
With the PR for API, this PR fixes https://github.com/istio/istio/issues/39345 and https://github.com/istio/istio/issues/36238.
For the details and discussion, please refer to the [draft design doc](https://docs.google.com/document/d/1qknaZqXItogEmROVnQD61144pEW1X47bEQraI5D52uY/edit?usp=sharing&resourcekey=0-wHAgrakvVaMcnBm40bKuSg), too.
> wasm: Implement "TrafficSelector" of WasmPlugin

- pkg/istio-agent/metrics/metrics.go
> register xds proxy request and response metrics

- pilot/pkg/model/proxy_config.go
- pilot/pkg/model/proxy_config_test.go
Fix https://github.com/istio/istio/issues/41046
> use custom merge logic for ProxyConfig

- samples/kind-lb/setupkind.sh
Improve setupkind script for not support parameter output
> improve setupkind script for not support parameter output

- samples/helloworld/gen-helloworld.sh
improve gen-helloworld exit code
> improve gen-helloworld exit code

- istioctl/cmd/internal-debug.go
- istioctl/cmd/proxystatus.go
- istioctl/pkg/multixds/gather.go
- pkg/kube/client.go
- pkg/kube/mock_client.go
Fixes https://github.com/istio/istio/issues/41040
> [release-1.15] istioctl x proxy-status via istio agents. (#40623)

- pilot/pkg/model/push_context_test.go
When user namespace does not have a sidecar resource defined but a root sidecar resource is, the user namespace must inherit the root's sidecar resource. This was broken in the updateContext path when no changes were detected. #40575 fixed that issue. Adding another test case that specifically tests this scenario.
> Unit tests to test root sidecar propogation to user namespace

- istioctl/cmd/internal-debug.go
- istioctl/cmd/proxystatus.go
- istioctl/pkg/multixds/gather.go
- pilot/pkg/xds/statusgen.go
- pkg/istio-agent/tap_proxy.go
- pkg/istio-agent/xds_proxy.go
- pkg/kube/client.go
- pkg/kube/mock_client.go
- tests/integration/pilot/piggyback_test.go
Cherrypicking the PRs  regarding "istioctl x ps --xds-via-agents".
* https://github.com/istio/istio/pull/40477
* https://github.com/istio/istio/pull/40566
* https://github.com/istio/istio/pull/40623
> [release-1.14] cherrypick for "istioctl x ps --xds-via-agents"

- operator/pkg/helmreconciler/prune.go
- releasenotes/notes/40797.yaml
> [release-1.13] operator: check pilot exist before get proxy info

- operator/pkg/helmreconciler/prune.go
- releasenotes/notes/40797.yaml
> [release-1.14] operator: check pilot exist before get proxy info

- operator/pkg/helmreconciler/prune.go
- releasenotes/notes/40797.yaml
fix https://github.com/istio/istio/pull/41072
> [release-1.15] operator: check pilot exist before get proxy info

- tests/integration/security/reachability_test.go
Fix the job randomly failed based on https://prow.istio.io/?job=integ-ds_istio_postsubmit
by commenting out the IPFamilies and IPFamilyPolicy specification.
> Comment out the IPFamilies and IPFamilyPolicy specification

- pilot/pkg/model/proxy_config.go
- pilot/pkg/model/proxy_config_test.go
> [release-1.14] use custom merge logic for ProxyConfig

- pilot/pkg/networking/core/v1alpha3/cluster_waypoint.go
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/networking/util/internal_upstream.go
- pilot/pkg/xds/filters/filters.go
Some refactoring I did for another PR that wasn't merged eventually.
> Shared definitions of common filters

- tests/integration/pilot/common/routing.go
**Added new regex based tests for jwt claim based routing**
> regex match test for claim based routing

- pkg/test/framework/components/jwt/kube.go
- pkg/test/framework/components/namespace/kube.go
- tests/integration/security/https_jwt/https_jwt_test.go
- tests/integration/security/https_jwt/main_test.go
**Previously somehow there was no destination coming up in the test runs, which stated we were not actually running the test. This PR has the fix.**
> fix for https jwt test

- pilot/pkg/networking/core/v1alpha3/listener_builder.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
- releasenotes/notes/41114.yaml
Fix https://github.com/istio/istio/issues/41114
> not change default idleTimeout for passthrough cluster

- pilot/pkg/bootstrap/servicecontroller.go
- pilot/pkg/networking/core/v1alpha3/fake.go
- pilot/pkg/networking/grpcgen/grpcgen_test.go
- pilot/pkg/serviceregistry/kube/controller/multicluster.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- pilot/pkg/xds/simple.go
> redundant ConfigStore param for serviceentry controller's construction 

- pilot/pkg/xds/bench_test.go
> Compute IP modes of proxy for benchmarks

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
> gateway-api: add appProtocol to gateway svc ports

- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/model/authentication_test.go
- pilot/pkg/model/authorization_test.go
- pilot/pkg/model/config.go
- pilot/pkg/model/proxy_config_test.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/model/telemetry_test.go
- pilot/pkg/networking/apigen/apigen_test.go
- pilot/pkg/networking/core/v1alpha3/accesslog_test.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
- pilot/pkg/networking/core/v1alpha3/fake.go
- pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go
- pilot/pkg/security/authz/builder/builder_test.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- pilot/pkg/xds/simple.go
- pkg/adsc/adsc_test.go
- pkg/kube/inject/webhook_test.go
- tests/fuzz/pilot_model_fuzzer.go
- [ x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
> cleanup istioconfigStore

- pilot/pkg/model/fuzz_test.go
- pkg/fuzz/README.md
> Fix fuzz case not properly handling oss-fuzz workarounds

- operator/cmd/mesh/manifest-generate_test.go
- operator/cmd/mesh/testdata/manifest-generate/input/autoscaling_v2.yaml
- operator/cmd/mesh/testdata/manifest-generate/input/autoscaling_v2beta1_k8s_and_values.yaml
- operator/cmd/mesh/testdata/manifest-generate/output/autoscaling_v2.golden.yaml
- operator/cmd/mesh/testdata/manifest-generate/output/autoscaling_v2beta1_k8s_and_values.golden.yaml
- operator/cmd/mesh/testdata/manifest-generate/output/pilot_override_values.golden.yaml
- operator/pkg/translate/translate_value.go
- operator/pkg/translate/translate_value_test.go
manual cherry-pick of https://github.com/istio/istio/pull/41079
fixes: #41151
> [release-1.14] fix handling of the deprecated autoscaling settings

- pkg/kube/client.go
See https://github.com/istio/istio/pull/36350#discussion_r980240016
> Fix kubeclient version retry

- pilot/pkg/model/cluster_local.go
Fixes https://github.com/istio/istio/issues/41179
> [release-1.13] Guarding nil-pointer for MeshConfig.ServiceSettings.Settings

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
- pilot/pkg/config/kube/gateway/templates/service.yaml
- pilot/pkg/config/kube/gateway/testdata/deployment/cluster-ip.yaml
- pilot/pkg/config/kube/gateway/testdata/deployment/manual-ip.yaml
- pilot/pkg/config/kube/gateway/testdata/deployment/multinetwork.yaml
- pilot/pkg/config/kube/gateway/testdata/deployment/simple.yaml
> gateway-api: appProtocol lower case and add to template

- cni/pkg/cmd/root.go
install-cni: Extract function registerEnvironment to reduce duplication
> install-cni: Extract function registerEnvironment to reduce duplication

- istioctl/pkg/multicluster/remote_secret.go
`create-remote-secret` has been moved out of x
> Revise create-remote-secret example

- security/pkg/server/ca/authenticate/xfcc_authenticator.go
- security/pkg/server/ca/authenticate/xfcc_authenticator_test.go
DO NOT CHERRYPICK WITHOUT https://github.com/istio/istio/pull/41171
> fix localhost address check in xfcc authenticator

- cni/pkg/plugin/plugin.go
- cni/pkg/plugin/plugin_test.go
- istioctl/cmd/injector-list.go
- istioctl/cmd/kubeuninject.go
- istioctl/cmd/remove-from-mesh.go
- pkg/config/analysis/analyzers/annotations/annotations.go
- pkg/config/analysis/analyzers/injection/injection.go
- pkg/config/analysis/analyzers/util/in_mesh.go
- pkg/kube/inject/inject.go
- pkg/kube/inject/webhook_test.go
- pkg/test/framework/components/echo/annotations.go
> Make use of sidecar inject label across repos

- pilot/pkg/config/kube/crdclient/client.go
> Remove log line

- samples/bookinfo/gateway-api/bookinfo-gateway.yaml
- samples/helloworld/gateway-api/helloworld-gateway.yaml
- samples/helloworld/gateway-api/helloworld-route.yaml
> gateway-api: update samples v1alpha2 -> v1beta1

- pilot/pkg/config/kube/crdclient/cache_handler.go
- pilot/pkg/config/kube/crdclient/client.go
- pilot/pkg/config/kube/crdclient/client_test.go
> Fix issue with GVK in event handlers

- pilot/pkg/xds/monitoring.go
These were added a while ago, they no longer do anything.
> Remove metrics that do nothing

- pkg/config/schema/collections/collections.gen.go
- pkg/config/schema/metadata.yaml
- releasenotes/notes/41322.yaml
fixes: #40876
wrong schema config cause:
```
KubeSource.parseChunk: namespace not specified for "admissionregistration.k8s.io/v1/MutatingWebhookConfiguration" "istio-sidecar-injector", using "istio-system"
```
> operator: fix schema cluster scoped

- tools/istio-iptables/pkg/capture/run.go
- tools/istio-iptables/pkg/capture/run_test.go
> replace the net.ParseCIDR for pkg/capture

- security/pkg/server/ca/authenticate/xfcc_authenticator.go
> replace the net.ParseCIDR for pkg/server/ca/authenticate

- pilot/pkg/serviceregistry/serviceentry/servicediscovery.go
- pilot/pkg/serviceregistry/serviceentry/servicediscovery_test.go
- releasenotes/notes/serviceentry-ip-auto-allocation.yaml
> [release-1.13] Manual cherry-pick of #40165

- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
- releasenotes/notes/41212.yaml
fixes: https://github.com/istio/istio/issues/38573
> tracing: set datadog ServiceName

- common/config/.golangci.yml
- pilot/pkg/bootstrap/config_compare.go
- pilot/pkg/model/virtualservice.go
- pkg/config/analysis/local/helpers_test.go
- pkg/config/model.go
- pkg/config/resource/instance_test.go
- pkg/config/schema/collection/schema_test.go
- pkg/config/schema/collection/schemas_test.go
- pkg/kube/fakemirror.go
- pkg/util/gogoprotomarshal/protomarshal.go
- tests/integration/telemetry/stackdriver/vm/main_test.go
> Drop unneeded `gogo` imports and add lint

- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
- releasenotes/notes/41212.yaml
manual cherry-pick of https://github.com/istio/istio/pull/41212
fix: #41356
> [release-1.15] tracing: set datadog ServiceName

- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
- releasenotes/notes/41212.yaml
manual cherry-pick of https://github.com/istio/istio/pull/41212
fix: #41355
> [release-1.14] tracing: set datadog ServiceName

- pilot/pkg/config/kube/ingress/status.go
- pilot/pkg/config/kube/ingressv1/status.go
- pilot/pkg/model/config.go
- pilot/pkg/model/context.go
- pilot/pkg/model/network.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/xds/debug.go
- pkg/config/validation/validation.go
- pkg/util/net/ip.go
partially implement issue https://github.com/istio/istio/issues/39348
> partially replace the net by the netip for ip validate

- pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
- pilot/pkg/serviceregistry/mock/discovery.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
> partially replace the net by the netip for the pilot/pkg/serviceregistry

- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/serviceregistry/kube/controller/fuzz_test.go
> Make endpointslice fuzzing work

- istioctl/cmd/precheck.go
- istioctl/cmd/workload.go
- pilot/cmd/pilot-agent/app/cmd.go
- pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pkg/config/validation/validation.go
- security/pkg/pki/util/san.go
- security/pkg/pki/util/san_test.go
- tools/istio-iptables/pkg/capture/run.go
- tools/istio-iptables/pkg/cmd/root_test.go
>  partially replace the net by the netip for istioctl san istio-iptables

- pkg/dns/client/dns.go
- pkg/dns/client/dns_test.go
- pkg/dns/server/name_table.go
- pkg/istio-agent/agent.go
- pkg/util/net/ip.go
- tools/istio-clean-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/capture/run.go
- tools/istio-iptables/pkg/cmd/root.go
> refactor: replace the net.IP by the netip.Addr for the pkg/dns

- tests/integration/security/egress_gateway_origination_test.go
> Remove unused secret creation step in egress gateway tls test

- tests/integration/helm/upgrade/util.go
- tools/bug-report/pkg/bugreport/bugreport.go
> Make use of rev label in some files

- pilot/pkg/xds/delta.go
- pilot/pkg/xds/delta_test.go
- pilot/pkg/xds/fake.go
- pilot/test/xdstest/extract.go
Fixes https://github.com/istio/istio/issues/41494
> delta: ensure proper resource handling on reconnect

- tests/integration/telemetry/api/accesslogs_test.go
- tests/integration/telemetry/api/setup_test.go
- tests/integration/telemetry/api/testdata/accesslog-filter.yaml
add e2e tests for accesslogging filter
> telemetry: add e2e tests for accesslogging filter

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
> Prevent hardcoding filter name from HBONE

- pilot/pkg/xds/delta.go
Minor comment improvements https://github.com/istio/istio/pull/41496
> minor comment improvements

- security/pkg/pki/ca/ca.go
Follow https://github.com/istio/istio/pull/41488/files#r998850853
> update commenst for  cacerts secret

- tests/integration/security/sds_ingress/util/util.go
> Small correction in code comment in integration test

- bin/update_deps.sh
- go.mod
- go.sum
- istio.deps
- prow/release-commit.sh
> [release-1.16] update deps

- manifests/charts/ztunnel/templates/daemonset.yaml
- pilot/pkg/networking/ambientgen/waypointgen.go
- pilot/pkg/networking/ambientgen/ztunnelgen.go
- pkg/security/security.go
- security/pkg/nodeagent/cache/secretcache.go
- security/pkg/nodeagent/caclient/providers/citadel/client.go
See https://github.com/istio/istio/issues/41281#certificates
> ambient: switch ztunnel to use Citadel node authoriation

- tests/integration/helm/util.go
> e2e: add error log

- operator/pkg/util/merge_iop.go
> Fix error running verify-install on ambient

- istioctl/cmd/precheck.go
- pkg/config/analysis/msg/messages.gen.go
- pkg/config/analysis/msg/messages.yaml
> precheck: validate Gateway API version

- pilot/pkg/xds/ads.go
- pilot/pkg/xds/delta.go
> Cleanup for xds push

- samples/extauthz/README.md
- samples/tcp-echo/README.md
update the docs about the output of create deployment
> update the docs about the output of create deployment

- pilot/pkg/xds/nds.go
Skip pushing nds on un related changes like secret etc.
> do not push nds on unrelated change

- pilot/pkg/grpc/grpc.go
- pilot/pkg/networking/grpcgen/lds_test.go
- pilot/pkg/xds/deltatest.go
- pkg/kube/inject/initializer.go
- pkg/kube/inject/webhook.go
- tools/istio-iptables/pkg/dependencies/implementation.go
> remove unnecessary type from set initialization

- go.sum
- pilot/pkg/model/envoyfilter.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/monitoring.go
- pkg/config/xds/xds.go
implement https://github.com/istio/api/pull/2514
> Support listener filter patch

- pilot/pkg/ambient/controller/waypoint_controller.go
- pilot/pkg/ambient/controller/workloadcache.go
- tests/integration/ambient/bookinfo_test.go
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/41680/integ-ambient_istio_experimental-ambient/1585917866119532544/artifacts/ambient-f3c542a7846a407aa483c00/TestBookinfo/_test_context/istio-state122022325/primary-0/istiod-776f7475b9-lwsxn_discovery.log
```console
2022-10-28T09:12:58.543854Z	info	waypoint proxy	adding waypoint proxy waypoint-waypoint-proxy	gateway=echo-1-82265/waypoint
2022-10-28T09:12:58.578637Z	error	controllers	error handling echo-1-82265/waypoint, retrying: pod create: deployments.apps "waypoint-waypoint-proxy" already exists	controller=waypoint proxy
2022-10-28T09:12:58.584211Z	info	waypoint proxy	reconcile: remove 0, add 1. Have 0	gateway=echo-1-82265/waypoint
2022-10-28T09:12:58.584251Z	info	waypoint proxy	adding waypoint proxy …
```
> ambient: wait informer sync before run

- pilot/pkg/bootstrap/istio_ca.go
- security/pkg/k8s/secret/secret_util.go
- security/pkg/k8s/secret/secret_util_test.go
- security/pkg/pki/ca/ca.go
- security/pkg/pki/ca/ca_test.go
- security/pkg/pki/ca/selfsignedcarootcertrotator_test.go
> Clean self-signed ca

- pilot/cmd/pilot-agent/status/server.go
Fix missing close body when failed scraping envoy metrics
> Fix missing close body

- operator/pkg/helmreconciler/prune.go
- operator/pkg/helmreconciler/prune_test.go
- pkg/kube/mock_client.go
- pkg/test/framework/features/features.yaml
- releasenotes/notes/41644.yaml
- tests/integration/operator/uninstall_test.go
manual cherry-pick of https://github.com/istio/istio/pull/41644
fixes: #41698
> [release-1.15] fix pilotExists regression

- tests/integration/helm/install_test.go
For https://github.com/istio/istio/issues/41593
> Dump helm failures

- pilot/pkg/networking/core/v1alpha3/loadbalancer/fuzz_test.go
Signed-off-by: AdamKorcz <adam@adalogics.com>
> loadbalancer: add fuzzer

- pilot/pkg/model/listener.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pilot/pkg/networking/plugin/authn/authentication.go
- pilot/pkg/xds/endpoint_builder.go
- pilot/pkg/xds/filters/filters.go
> refactor hbone listener code

- pkg/test/framework/components/echo/kube/deployment.go
- tests/integration/telemetry/api/wasmplugin_test.go
Fix the issues in https://github.com/istio/istio/pull/41416#issuecomment-1302227805
The timestamp was not correctly generated and add more checks for detecting the restart completion.
> [bugfix] Fix restarting logic of deployment in the test framework

- pkg/config/analysis/analyzers/all.go
- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/telemetry/providers.go
- pkg/config/analysis/analyzers/testdata/telemetry-invalid-provider.yaml
- pkg/config/analysis/msg/messages.gen.go
- pkg/config/analysis/msg/messages.yaml
- releasenotes/notes/41785.yaml
fixes: https://github.com/istio/istio/issues/41170
add telemetry analyzer
> add telemetry analyzer

- pilot/pkg/security/model/authentication.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
Keep all that are used:  Labels, Container Ports, Status.Conditions,  Status.PodIPs
> strip pod unused fields

- pilot/pkg/config/kube/gateway/conversion.go
- tests/integration/pilot/ingress_test.go
> gateway-api: enable mesh ingress tests

- pilot/pkg/xds/sds.go
- pilot/pkg/xds/sds_test.go
- releasenotes/notes/41761.yaml
fix the problem mentioned in https://github.com/istio/istio/issues/41760
> Fix PrivateKeyProvider's problem with proxy-config

- security/pkg/pki/ca/ca.go
- security/pkg/pki/ra/common.go
Check the signatures from CSRs
> Verify signature from CSRs

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
Fixes https://github.com/istio/istio/issues/41773
> do not push dns round robin cluster with incorrect lb endpoints

- pkg/config/analysis/README.md
Correcting few markdown broken links.
> Broken links corrections

- pkg/kube/client.go
Fix https://github.com/istio/istio/issues/41790
This related code in Release-1.16 and master have been refactorred, so need to manually fix release-1.15 and even 1.14
> Fix GetKubernetesVersion

- manifests/charts/istio-control/istio-discovery/templates/NOTES.txt
- operator/cmd/mesh/install.go
> Add Install/Upgrade Survey for 1.16

- pkg/h2c/wrapper.go
> rename to denyH2cUpgrade

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
> Revert "do not push dns round robin cluster with incorrect lb endpoints"

- docker/Dockerfile.distroless
- go.mod
- go.sum
- prow/release-commit.sh
> [release-1.15] run UPDATE_BRANCH=release-1.15 ./bin/update_deps.sh

- docker/Dockerfile.distroless
- go.mod
- go.sum
- prow/release-commit.sh
> [release-1.14] run UPDATE_BRANCH=release-1.14 ./bin/update_deps.sh

- pilot/pkg/networking/core/v1alpha3/extension/wasmplugin.go
- pkg/config/xds/filters.go
- pkg/test/framework/components/echo/kube/deployment.go
- pkg/wasm/convert.go
- pkg/wasm/convert_test.go
- releasenotes/notes/wasm-download-fallback.yaml
- tests/integration/telemetry/stats/prometheus/wasm/bad_wasm_filter_test.go
- tests/integration/telemetry/stats/prometheus/wasm/testdata/bad-wasm-envoy-filter-fail-open.yaml
Fixes https://github.com/istio/istio/issues/41750
> [release-1.15] wasm: enhance fallback logic for the Wasm module download failure (#41416)

- istioctl/pkg/validate/validate.go
- istioctl/pkg/validate/validate_test.go
- pkg/url/url.go
- pkg/url/url_test.go
- releasenotes/notes/validate-appprotocol.yaml
> Fix validate ignore service port appProtocol

- pkg/wasm/httpfetcher.go
- pkg/wasm/imagefetcher.go
> add a size check on wasm module

- pilot/pkg/serviceregistry/serviceentry/conversion_test.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
> add validation for dns round robin endpoints

- pilot/pkg/model/push_context.go
Signed-off-by: chaunceyjiang <chaunceyjiang@gmail.com>
fix https://github.com/istio/istio/issues/41918
> fix istio crashes with memory nil pointer

- operator/pkg/helmreconciler/prune.go
- operator/pkg/helmreconciler/prune_test.go
- operator/pkg/helmreconciler/testdata/iop-test-gw-1.yaml
- operator/pkg/helmreconciler/testdata/iop-test-gw-2.yaml
- releasenotes/notes/40578.yaml
Fixes https://github.com/istio/istio/issues/41927
Manual cherry pick of #40578
> [release-1.15] Manual cherry-pick of #40578

- operator/pkg/helmreconciler/prune.go
- operator/pkg/helmreconciler/prune_test.go
- operator/pkg/helmreconciler/testdata/iop-test-gw-1.yaml
- operator/pkg/helmreconciler/testdata/iop-test-gw-2.yaml
- releasenotes/notes/40578.yaml
Fixes https://github.com/istio/istio/issues/41928
Manual cherry pick of #40578
> [release-1.16] Manual cherry-pick of #40578

- samples/bookinfo/gateway-api/route-reviews-50-v3.yaml
- samples/bookinfo/gateway-api/route-reviews-v1.yaml
- samples/bookinfo/gateway-api/route-reviews-v3.yaml
> gateway-api: more bookinfo config yamls

- releasenotes/notes/41431.yaml
- tools/istio-clean-iptables/main_test.go
- tools/istio-clean-iptables/pkg/cmd/cleanup.go
- tools/istio-clean-iptables/pkg/cmd/cleanup_test.go
- tools/istio-clean-iptables/pkg/cmd/root.go
- tools/istio-clean-iptables/pkg/cmd/testdata/inbound-interception-mode.golden
- tools/istio-clean-iptables/pkg/config/config.go
- tools/istio-iptables/pkg/constants/constants.go
Signed-off-by: cobb-tx <464693850@qq.com>
clean iptables need consider inbound Interception mode
- [ x ] Networking
> feat:clean-iptables consider InboundInterceptionMode

- go.mod
- go.sum
- tests/integration/pilot/gateway_conformance_test.go
- tests/integration/pilot/testdata/gateway-api-crd.yaml
Pulls in some conformance test fixes
> Bump Gateway-API dependency

- go.mod
- go.sum
- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
- releasenotes/notes/41908.yaml
envoy: https://github.com/envoyproxy/envoy/pull/23910
fixes: #41829
> telemetry: fix datadog hostname

- samples/bookinfo/gateway-api/route-all-v1.yaml
- samples/bookinfo/platform/kube/bookinfo-versions.yaml
> More bookinfo yamls

- pkg/kube/client.go
> [release-1.14] Fix GetKubernetesVersion

- security/pkg/stsservice/server/server.go
> limit memory in sts debug mode

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/25832.yaml
**Warning message for L7 Deny rule which will block all the tcp traffic under the scope of the policy having that rule**
> L7 deny rule check in authz validation

- security/pkg/k8s/configutil_test.go
This is broken because it isn't properly waiting for the informer to sync. Using the standard client this is trivially handled.
> Fix TestInsertDataToConfigMap flakes

- pilot/pkg/networking/core/v1alpha3/extension/wasmplugin.go
- pkg/config/xds/filters.go
- pkg/test/framework/components/echo/kube/deployment.go
- pkg/wasm/convert.go
- pkg/wasm/convert_test.go
- releasenotes/notes/wasm-download-fallback.yaml
- tests/integration/telemetry/stats/prometheus/wasm/bad_wasm_filter_test.go
- tests/integration/telemetry/stats/prometheus/wasm/testdata/bad-wasm-envoy-filter-fail-open.yaml
Fixes https://github.com/istio/istio/issues/41749
> [release-1.14] wasm: enhance fallback logic for the Wasm module download failure (#41416)

- prow/integ-suite-kind.sh
Update to the latest 1.25 k8s image for testing default
> Update to the latest 1.25 k8s image for testing default

- pilot/pkg/config/kube/gateway/controller.go
- pilot/pkg/config/kube/gateway/controller_test.go
We should check if the namespace labels are changed, otherwise there will be unncessary pushes(e.g. due to namespace status updates) refreshing the push context and xds cache
> gateway-api: scope namespace events

- pkg/kube/inject/webhook.go
fixed: https://github.com/istio/istio/issues/41998
> fix: panic when inject serve

- pilot/pkg/ambient/controller/waypoint_controller.go
To make it consistent with other log scopes, and easier to be set in command line
> Revise waypointProxy log name

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_test.go
- releasenotes/notes/41996.yaml
implement: https://github.com/istio/api/pull/2556
fixed: https://github.com/istio/istio/issues/41763
> telemetry: support reporting_interval

- istioctl/cmd/istiodconfig.go
- releasenotes/notes/fix-revision-admin-log.yaml
Otherwise it will randomly pick one istiod
> Add revision flag to admin log cmd

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_test.go
follow up https://github.com/istio/istio/pull/41996#discussion_r1022925172
related to https://github.com/istio/proxy/pull/4206
> improve reporting_interval

- samples/bookinfo/src/build-services.sh
improve bookinfo/build-services
> improve bookinfo/build-services

- pkg/file/file.go
- pkg/file/file_test.go
This mirrors logic in other libraries, ensuring we read + stat the file in one open
> file Copy: more reliable Stat() mechanism

- samples/tcp-echo/gateway-api/tcp-echo-20-v2.yaml
- samples/tcp-echo/gateway-api/tcp-echo-all-v1.yaml
> gateway-api: add config yamls for tcp-echo sample

- samples/open-telemetry/README.md
Add missing space in install command.
> Add missing space

- istio.deps
This is probably changing too fast to automate,but the current one is 100% broken so probably good to update this
> Bump ztunnel image

- security/pkg/pki/ra/k8s_ra.go
Signed-off-by: chaunceyjiang <chaunceyjiang@gmail.com>
fix #42115
> fix CSR signing panic

- pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
- pilot/pkg/xds/nds.go
> avoid calling servicesForNamespacedName for headless services

- go.mod
- go.sum
> update grpc and go-control-plane

- pilot/pkg/networking/core/v1alpha3/listener.go
- tests/integration/security/sds_ingress/util/util.go
fixes https://github.com/istio/istio/issues/42118
> Fix QUIC regression in integ test

- pkg/istio-agent/agent.go
> agent: remove useless comments

- pilot/pkg/serviceregistry/kube/controller/pod.go
- pilot/pkg/serviceregistry/kube/controller/pod_test.go
https://github.com/kubernetes/kubernetes/blob/133be895e0de2994353703e082f92b6b946ac0e2/pkg/controller/util/endpoint/controller_utils.go#L141
> update ShouldPodBeInEndpoints with latest k8s

- pkg/istio-agent/agent.go
> fix empty ips in alt hosts of agent /ndsz output

- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta.go
- pkg/istio-agent/xds_proxy_test.go
- pkg/wasm/cache.go
- pkg/wasm/cache_test.go
- pkg/wasm/convert_test.go
- releasenotes/notes/42167.yaml
> wasm: improve wasm cache

- pilot/pkg/networking/core/v1alpha3/tracing.go
- releasenotes/notes/42104.yaml
- samples/open-telemetry/otel.yaml
- tests/integration/telemetry/tracing/otelcollector/testdata/otel-tracing.yaml
- tests/integration/telemetry/tracing/otelcollector/tracing_test.go
- tests/integration/telemetry/tracing/tracing.go
> [release-1.16] tracing: fix opentelemetry service name

- istioctl/cmd/proxyconfig.go
- istioctl/pkg/util/configdump/workload.go
- istioctl/pkg/writer/ztunnel/configdump/configdump.go
- istioctl/pkg/writer/ztunnel/configdump/workload.go
Part of https://github.com/istio/ztunnel/issues/87
> first pass of istioctl proxy-config workload command

- manifests/charts/ztunnel/values.yaml
> Enable prometheus scraping for ztunnel

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/42184.yaml
Fixes https://github.com/istio/istio/issues/42184
> Fix ServiceEntries using DNS_ROUND_ROBIN

- istio.deps
- manifests/charts/ztunnel/templates/daemonset.yaml
- manifests/charts/ztunnel/values.yaml
- pkg/test/framework/resource/settings.go
- tests/integration/ambient/main_test.go
easier than i thought.. don't know what i was missing at first
fixes https://github.com/istio/ztunnel/issues/90
> rust tests in CI

- go.mod
- go.sum
- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/testdata/alias.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/delegated.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/eastwest.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/mcs.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/mesh.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/multi-gateway.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/reference-policy-service.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/route-binding.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/route-precedence.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/serviceentry.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/tcp.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/tls.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/weighted.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/zero.status.yaml.golden
- tests/integration/pilot/testdata/gateway-api-crd.yaml
Change is small since we were already on pre-release which had most of the changes
> gateway-api bump to v0.6.0-rc1

- tests/integration/ambient/baseline_test.go
Expands integration testing coverage of authorization policy testing.
> add waypoint integration tests for authz coverage

- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
- pilot/pkg/serviceregistry/kube/controller/multicluster.go
- pilot/pkg/serviceregistry/serviceentry/namespace_handler.go
- releasenotes/notes/42173.yaml
Fix #42173
when ENABLE_ENHANCED_RESOURCE_SCOPING enabled, namespace selected/deselected we should  trigger full push so that the CRs within the namespace will be handled correctly
> Fix ENABLE_ENHANCED_RESOURCE_SCOPING bug

- pilot/pkg/serviceregistry/kube/controller/controller.go
> ignore non tcp port and figure out named port

- pilot/pkg/bootstrap/server.go
- pilot/pkg/features/pilot.go
- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
- pilot/pkg/serviceregistry/kube/controller/multicluster.go
- pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
https://github.com/istio/istio/issues/42354
> Fix TestControllerEnableResourceScoping  data race 

- istioctl/pkg/writer/envoy/configdump/configdump.go
> migrate to protojson

- pilot/pkg/model/config.go
- pilot/pkg/model/config_test.go
- pilot/pkg/xds/ecds.go
- pilot/pkg/xds/ecds_test.go
- pilot/pkg/xds/sds.go
> remove redundant config check in ecds

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/42119.yaml
Signed-off-by: chaunceyjiang <chaunceyjiang@gmail.com>
fix #42094
> add partial wildcard checks to Gateway and Sidecar

- pilot/pkg/serviceregistry/kube/controller/controller.go
> Fix nil pointer check on ambient controller

- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/conversion_test.go
- pilot/pkg/serviceregistry/serviceentry/store.go
- pilot/pkg/serviceregistry/serviceentry/store_test.go
Fixes https://github.com/istio/istio/issues/42368
> fix dns round robin discovery

- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/store.go
- pilot/pkg/serviceregistry/serviceentry/store_test.go
> move to struct and handle delete

- CONTRIBUTING.md
> Add two more tips for Mac OS users

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/listener_address.go
- pilot/pkg/networking/util/util.go
fix ds post submit integration test issues:
1. add the feature flag for change code in PR: https://github.com/istio/istio/pull/41618
2. change the code based on comments
> fix ds post submit integration test issues

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/xds/deltatest.go
Go on to fix the integ-ds_istio_postsubmit job failed for PR: https://github.com/istio/istio/pull/41618
> go on to fix the integ-ds_istio_postsubmit job failed

- pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
> fix namepace controller leader election event handler leak

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
> fix gateway deployment controller leader election event handler leak

- CONTRIBUTING.md
Minor update to CONTRBUTING.md
> Minor CONTRIBUTING update

- istio.deps
- manifests/charts/base/crds/gateway-api-crds.yaml
- manifests/charts/base/files/gen-istio-cluster.yaml
- manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
- manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
- pkg/kube/inject/testdata/inputs/custom-template.yaml.34.template.gen.yaml
- pkg/kube/inject/testdata/inputs/default.template.gen.yaml
- pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
- pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
- pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
- pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
- tests/integration/pilot/testdata/gateway-api-crd.yaml
With new beta API, we need to tweak the listener field again (we fork the API - to be fixed soon) and update the parentRef
> Fix gateway deployment

- samples/bookinfo/src/reviews/reviews-application/src/main/java/application/rest/LibertyRestEndpoint.java
> fix incorrect code style

- pilot/pkg/model/context.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- pilot/pkg/xds/endpoint_builder.go
Right now we're doing tunnel for proxies that don't have this enabled, disallowing opt-out AFAICT.
> ep builder: check invidual proxy has hbone

- pilot/cmd/pilot-agent/app/cmd.go
- pkg/istio-agent/agent.go
- pkg/istio-agent/agent_test.go
- pkg/istio-agent/xds_proxy_test.go
> close all servers of agent properly

- samples/bookinfo/platform/kube/cleanup.sh
- tools/packaging/common/istio-start.sh
Update scripts to be compatible with shellcheck 0.9.0. See https://github.com/koalaman/shellcheck/releases/tag/v0.9.0
> Fixes for shellcheck 0.9.0

- samples/bookinfo/platform/kube/cleanup.sh
- tools/packaging/common/istio-start.sh
fixes https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/42528/lint_istio_exp/1605311138063454208
cherry-pick [PR#42506](https://github.com/istio/istio/pull/42506) to ambient branch
> Fix for shellcheck 0.9.0 (#42506)

- pkg/proto/merge/merge.go
- releasenotes/notes/fix-42533.yaml
Fix https://github.com/istio/istio/issues/42533
> Fix merge map losing source content

- pilot/pkg/networking/core/v1alpha3/route/route.go
fix typo merged in https://github.com/istio/istio/pull/42538
> fix typo in useGatewaySemantics

- istio.deps
- pilot/pkg/networking/ambientgen/waypointgen.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/listener_builder.go
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/xds/endpoint_builder.go
- pkg/test/framework/components/ambient/waypoint.go
- tests/integration/ambient/baseline_test.go
Removing consumer waypoint code per https://docs.google.com/document/d/1QdpTl0y2snASOPo8GEKapuwDD-Mfoy2zz8hPVbgRexA/edit. Related to #42220 
> Drop consumer waypoint

- pilot/pkg/model/gateway.go
- pkg/config/gateway/gateway.go
- pkg/config/gateway/gateway_test.go
> rename IsNonHTTPTLSServer to IsTLSServer

- pilot/pkg/xds/nds_test.go
> add test for nds generate

- pilot/pkg/xds/endpoint_builder.go
- releasenotes/notes/fix-42598.yaml
Fix https://github.com/istio/istio/issues/42598
> Fix trafficPolicyTLSModeForPort() func cause pilot push XDS panic

- pkg/bootstrap/config.go
- releasenotes/notes/42591.yaml
> close file fd

- samples/tcp-echo/src/Dockerfile
Signed-off-by: yanggang <gang.yang@daocloud.io>
Upgraded golang version in the dockerfile to build.
/label release-notes-none
```release-note
None
```
> upgraded golang image version to latest.

- go.mod
- go.sum
- istioctl/cmd/wait.go
- pilot/pkg/config/kube/gateway/conditions.go
- pilot/pkg/config/kube/gateway/controller_test.go
- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
- tests/integration/pilot/testdata/gateway-api-crd.yaml
will remove hold after https://github.com/istio/istio/pull/42545 is merged since I depend on that
> Bump gateway to 0.6.0

- tests/integration/telemetry/envoyfilter/customizemetrics/customize_metrics_test.go
fixes: https://github.com/istio/istio/issues/42128
> add e2e for MetricDefinition

- istioctl/cmd/proxyconfig.go
> Support `istioctl pc log` for ztunnel

- manifests/profiles/ambient.yaml
part of https://github.com/istio/istio/issues/42457
> Move ambient over to use delta xds

- istioctl/cmd/proxyconfig.go
bug fix for `istioctl pc workload` command
follow up to https://github.com/istio/ztunnel/pull/243 changes due to port change in ztunnel
> fixes to istioctl for ztunnel port change

- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/xds/workload.go
- pilot/pkg/xds/workload_test.go
Fixes https://github.com/istio/istio/issues/42610
> wds: fix subscriptions when node name is set

- pilot/cmd/pilot-agent/status/server_test.go
Small regression to the benchmark
> Fix missing struct initialization

- pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go
- pilot/pkg/serviceregistry/kube/controller/endpoint_builder_test.go
- releasenotes/notes/fix-42675.yaml
Fix https://github.com/istio/istio/issues/42675
> Fix pod's network label priority incorrect

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/aggregate/controller.go
- pilot/pkg/serviceregistry/aggregate/controller_test.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
- pilot/pkg/serviceregistry/kube/controller/endpoints.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice_test.go
- pilot/pkg/serviceregistry/memory/discovery.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/eds.go
> Remove `labels` from InstancesByPort (deadcode)

- pilot/pkg/model/context.go
Fixes https://github.com/istio/istio/issues/42684
> allow unknown fields in proxy config

- tests/integration/ambient/baseline_test.go
add an integration test for EnvoyFilter. Part of https://github.com/istio/istio/issues/42223
> add minimal envoyfilter testing

- cni/pkg/ambient/iptables.go
- cni/pkg/ambient/net.go
- cni/pkg/ambient/server.go
We sometimes ran this before setting the global. Instead, use a Lazy var so it MUST be initialized.
> ambient cni: consistent fetch iptables command

- pilot/pkg/model/push_context.go
- pilot/pkg/xds/proxy_dependencies.go
- pilot/pkg/xds/proxy_dependencies_test.go
For https://github.com/istio/istio/pull/42721#discussion_r1065273707
@hzxuzhonghu
> Follow up #42721

- pilot/pkg/model/push_context.go
- pilot/pkg/xds/proxy_dependencies.go
- pilot/pkg/xds/proxy_dependencies_test.go
- pkg/config/host/name.go
- releasenotes/notes/auto-passthrough-regression.yaml
Manual cherry-pick of #42721 and #42735
Fixes https://github.com/istio/istio/issues/42733
> [release-1.16] `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG`: fix false negatives for AUTO_PASSTHROUGH

- pilot/pkg/networking/core/v1alpha3/fake.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/eds_sh_test.go
- pilot/pkg/xds/eds_test.go
Builds on https://github.com/istio/istio/pull/42687
> Remove test-only code UpdateServiceShards from production codepath

- istioctl/pkg/writer/ztunnel/configdump/workload.go
indicate whether a workload has a waypoint deployed for it in `istioct pc workload` output
- [ X  ] Ambient
> add column to istioctl pc workload output

- pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
ingress listener port is the target port, so should compare with service targetport
> fix service port and ingress listener port merge

- pilot/pkg/grpc/grpc.go
- pilot/pkg/grpc/tls.go
- pkg/istio-agent/xds_proxy.go
- security/pkg/nodeagent/caclient/providers/citadel/client.go
For https://github.com/istio/istio/issues/36709
> Unify xds proxy and citadel client grpc dial options

- istio.deps
- pilot/pkg/model/telemetry.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/xds/filters/filters.go
- tests/integration/ambient/baseline_test.go
> telemetry: fix waypoint back

- pkg/bootstrap/platform/gcp.go
- pkg/bootstrap/platform/gcp_test.go
- pkg/lazy/lazy.go
- pkg/lazy/lazy_test.go
- pkg/test/framework/components/echo/kube/templates/vm_deployment.yaml
- pkg/test/util/assert/assert.go
Manual cherry pick of #42450 with cherry pick of lazy pkg from #40386, fixes #42645.
> [release-1.15] Manual Cherrypick 42450: fix VM DNS in tests

- pilot/pkg/autoregistration/controller.go
We have met spammy logs on line, the cause is user delete the WLE manually.
But I think we still need to return an error when WLE not found, there can be small case it is not propagated
> reduce workload entry unregistration retry times

- istio.deps
- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/v3/model.go
- pilot/pkg/xds/workload_test.go
We recently renamed the proto but forgot to update the type to match
See https://github.com/istio/ztunnel/pull/324 (probably depends on this)
> Finish renaming RBAC proto

- pilot/pkg/model/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
Fixes https://github.com/istio/istio/issues/39921
> Check sni overlaps across gateway severs

- pilot/pkg/autoregistration/controller.go
manually cherry-pick (#42757)
fix https://github.com/istio/istio/issues/42782
> reduce workload entry unregistration retry times (#42757)

- istioctl/cmd/proxyconfig.go
part of https://github.com/istio/istio/issues/42809
> improve istioctl pc workload CLI instructions and help message

- samples/security/spire/spire-quickstart.yaml
> upgrade spire-server version to supprt holdApplicationUntilProxyStarts of istio

- pilot/pkg/model/network.go
- releasenotes/notes/42818.yaml
Fixes https://github.com/istio/istio/issues/42818
> fix reload network endpoints

- prow/release-commit.sh
Update instances of master to 1.17
> [release-1.17] Update master to 1.17

- pilot/pkg/xds/ecds.go
I only added these comments earlier :-). But I get confused reading them again. So an attempt to improve
> improve wasm ecds comments

- bin/update_deps.sh
- go.mod
- go.sum
- prow/release-commit.sh
Run update_deps.sh after the branch cut in prep for a build
> [release-1.17] Run update_deps.sh

- prow/release-commit.sh
Another update_deps after release_builder update.
> [release-1.17] Update_deps.sh

- pkg/test/framework/components/echo/calloptions.go
- pkg/test/framework/components/echo/kube/instance.go
- tests/integration/pilot/common/traffic.go
- tests/integration/pilot/ingress_test.go
- tests/integration/security/authz_test.go
- tests/integration/security/util/cert/cert.go
- tests/integration/telemetry/envoyfilter/nullvm/dashboard_test.go
- tests/integration/telemetry/policy/envoy_ratelimit_test.go
This is to avoid cases where we do not test anything when we thought we might have
> tf: ensure Check is always set

- pilot/pkg/xds/delta_test.go
Fixes https://github.com/istio/istio/issues/42801
> Fix TestDeltaEDS flake

- pkg/test/util/yml/apply.go
- tests/integration/pilot/cni_race_test.go
- tools/bug-report/pkg/cluster/cluster.go
Improve appsv1 package import statement
> improve appsv1 package import statement

- pilot/pkg/security/authn/v1beta1/policy_applier.go
- pilot/pkg/security/authz/model/generator.go
- pilot/pkg/security/authz/model/util.go
- pilot/pkg/security/model/authentication.go
- pilot/pkg/xds/filters/filters.go
> use authn filter constant every where

- pilot/pkg/serviceregistry/serviceregistry_test.go
- pilot/pkg/xds/endpoint_builder.go
> use shared var for outbound-tunnel

- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta.go
- pkg/wasm/convert.go
- pkg/wasm/convert_test.go
- pkg/wasm/monitoring.go
Refactoring the `pkg/wasm/convert.go` based on the review from https://github.com/istio/istio/pull/42928#discussion_r1084368557
> Refactor wasm convert.go

- istio.deps
- tests/integration/ambient/baseline_test.go
Needs https://github.com/istio/ztunnel/pull/333
> ambient: test original src

- pilot/pkg/features/pilot.go
- pilot/pkg/security/authn/v1beta1/policy_applier.go
- pilot/pkg/security/authn/v1beta1/policy_applier_test.go
- pkg/jwt/jwt.go
- tests/integration/security/remote_jwks/main_test.go
- tests/integration/security/remote_jwks/remote_jwks_test.go
- tests/integration/security/remote_jwks/testdata/requestauthn-no-se.yaml.tmpl
- tests/integration/security/remote_jwks/testdata/requestauthn-with-se.yaml.tmpl
This PR is to config remote jwks to three modes: istiod, hybrid and envoy. 
Design doc: https://docs.google.com/document/d/1utsAOK1QwbORlOIyTUwXOHR0miire3vVs7OyxXR1oQo
> add fully remote jwks mode

- samples/bookinfo/platform/kube/bookinfo.yaml
- samples/bookinfo/src/productpage/productpage.py
- samples/bookinfo/src/productpage/requirements.txt
This simple change will make it possible to test merged metrics or scrape metrics with mTLS.
> samples: Expose some metrics from productpage app

- istio.deps
- tests/integration/ambient/baseline_test.go
For https://github.com/istio/ztunnel/issues/73
> ambient: implement hairpinning tests

- pilot/cmd/pilot-agent/status/dialer_others.go
- pilot/cmd/pilot-agent/status/dialer_windows.go
- pilot/cmd/pilot-agent/status/server.go
- pkg/istio-agent/health/health_probers.go
Fixes https://github.com/istio/istio/issues/42979
> Mirror k8s probe dialers

- docker/Dockerfile.distroless
- go.mod
- go.sum
- istio.deps
- prow/release-commit.sh
In preparation for a new build for 1.17 release.
> Run bin/update_deps.sh in preparation for second build for 1.17

- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/serviceexportcache.go
- pilot/pkg/serviceregistry/kube/controller/serviceexportcache_test.go
- pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
- pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go
With this it will not block istiod ready, and it is aligned with gateway API
Fix: https://github.com/istio/istio/issues/42596
> Support delaying mcs controller start until mcs CRD installed

- istioctl/cmd/describe.go
- istioctl/cmd/describe_test.go
- istioctl/cmd/injector-list.go
- istioctl/cmd/revision.go
- istioctl/pkg/tag/revision.go
Improve corev1 package import statement
> Cleanup: improve corev1 package import statement

- pkg/istio-agent/xds_proxy.go
do like
https://github.com/istio/istio/blob/e2d1da734ca56fe5a06b78c4fd418bb0a14acf45/pkg/istio-agent/xds_proxy_delta.go#L324-L333
> fix:tapRequest rwlock weak.

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
part of https://github.com/istio/istio/issues/42866
> update effected eds endpoints on waypoint deploy/delete

- cni/pkg/repair/repair.go
- cni/pkg/repair/repair_test.go
- cni/pkg/repair/repair_test_helpers.go
- cni/pkg/repair/repaircontroller.go
- cni/pkg/taint/taint.go
- cni/pkg/taint/taint_test.go
Improve package import statement
> Cleanup: improve package import statement

- pilot/pkg/model/push_context.go
- pilot/pkg/networking/core/v1alpha3/tracing.go
- pkg/bootstrap/config.go
- pkg/config/validation/extensionprovider.go
manual cherry-pick of https://github.com/istio/istio/pull/43055
fixes: https://github.com/istio/istio/issues/43057
pre-step of https://github.com/istio/api/pull/2663
> [release-1.17] Lightstep deprecated

- tests/integration/telemetry/common/stats.go
> e2e: fix histogram bucket flaky

- istioctl/cmd/proxyconfig.go
- istioctl/pkg/util/handlers/handlers.go
- releasenotes/notes/42919.yaml
part of https://github.com/istio/istio/issues/42919
> Log all pods in istioctl pc log for deployment

- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta_test.go
- pkg/istio-agent/xds_proxy_test.go
> cleanup legacy var and remove copy dial options slice

- manifests/charts/ztunnel/values.yaml
This was changed, align with new selection.
> Update ztunnel stats port

- istioctl/cmd/proxyconfig.go
- releasenotes/notes/43064.yaml
> istioctl: proxy-config support custom proxy admin port

- security/pkg/pki/ra/common.go
A small optimization to make `contains` validation more readable.
Unit tests are covered and do not need to be modified.
> make `contains` validation more readable.

- pkg/config/model.go
specify map size for better performance.
> specify map size

- docker/Dockerfile.distroless
- go.mod
- go.sum
- istio.deps
- prow/release-commit.sh
> [release-1.17] UPDATE_BRANCH=release-1.17 ./bin/update_deps.sh

- manifests/charts/ztunnel/templates/daemonset.yaml
Fixes https://github.com/istio/istio/issues/42197
> Cleanup unused bits in redirection logic

- samples/extauthz/cmd/extauthz/main_test.go
> fix:resp.body should be closed

- istioctl/pkg/install/verify.go
- pilot/pkg/config/kube/gateway/conditions.go
- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- pkg/config/mesh/mesh.go
- pkg/ptr/pointer.go
- tools/docker-builder/crane.go
- tools/docker-builder/docker.go
Port from ambient branch. This adds some simple helper functions for pointers
> Add new  helper package for `ptr`

- manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
- manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
- pkg/kube/inject/testdata/inputs/custom-template.yaml.34.template.gen.yaml
- pkg/kube/inject/testdata/inputs/default.template.gen.yaml
- pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
- pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
- pkg/kube/inject/testdata/inputs/merge-probers.yaml.38.template.gen.yaml
- pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
- pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
Implements https://github.com/istio/istio/issues/32569
Also move to the proper port
> waypoint: better probing

- istioctl/cmd/proxyconfig.go
- releasenotes/notes/43045.yaml
Fix https://github.com/istio/istio/issues/43045
> Fix `istioctl pc ep -f -` returns `Error: open -: no such file or directory`

- istio.deps
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/xds/filters/filters.go
> waypoint: update connect_authority filter

- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
> Remove obsolete header in hbone

- istioctl/cmd/root.go
- istioctl/cmd/waypoint.go
- pkg/test/framework/components/ambient/waypoint.go
- tests/integration/ambient/bookinfo_test.go
Fixes https://github.com/istio/istio/issues/43279
> istioctl: add command to generate/apply waypoints more easily 

- istio.deps
- manifests/charts/ztunnel/values.yaml
- tests/integration/ambient/baseline_test.go
> Ambient: fix l4 telemetry and add tests

- pilot/pkg/model/context.go
- pilot/pkg/model/push_context.go
- pilot/pkg/networking/core/v1alpha3/cluster_waypoint.go
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/xds/endpoint_builder.go
- tests/integration/ambient/baseline_test.go
Fixes https://github.com/istio/istio/issues/43189
> ambient: test split service

- tests/fuzz/oss_fuzz_build.sh
> Cleanup dead fuzzing targets

- pilot/pkg/model/sidecar.go
- pilot/pkg/model/sidecar_test.go
- pilot/pkg/xds/proxy_dependencies_test.go
to reduce unnecessary LDS/ECDS pushes
> Add WasmPlugin to scoped config types

- cni/pkg/repair/repair.go
- go.mod
- go.sum
The use of the uber package is very minimal and we can replace it with the one more commonly used in the project.
> Replace uber multierr with the hashicorp one

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
Minor correction of a user-facing validation error message.
> Correction of validation error message

- CONTRIBUTING.md
> Add gateway CRD and waypoint deploy instruction

- pilot/pkg/features/pilot.go
- pilot/pkg/security/authn/v1beta1/policy_applier.go
- pilot/pkg/security/authn/v1beta1/policy_applier_test.go
- pkg/jwt/jwt.go
- pkg/test/util.go
- tests/integration/security/remote_jwks/main_test.go
- tests/integration/security/remote_jwks/remote_jwks_test.go
- tests/integration/security/remote_jwks/testdata/requestauthn-no-se.yaml.tmpl
- tests/integration/security/remote_jwks/testdata/requestauthn-with-se.yaml.tmpl
Cherry pick https://github.com/istio/istio/pull/42756.
Resolved conflicts with some changes.
> [release-1.15] add fully remote jwks mode (#42756)

- pilot/docker/Dockerfile.ztunnel
For https://github.com/istio/istio/issues/43249
> Remove envoy version from ztunnel dockerfile

- manifests/charts/ztunnel/templates/daemonset.yaml
Fixes https://github.com/istio/istio/issues/43247
> ztunnel: minimize privileges

- pkg/config/validation/fuzz_test.go
- pkg/config/validation/header_value_validator.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/42778.yaml
> validate: improve ValidateHTTPHeaderValue

- pilot/pkg/model/service.go
- pilot/pkg/model/sidecar_test.go
> add additional test cases for sidecar with multiple ports in sidecar

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pkg/kube/controllers/common.go
- pkg/kube/controllers/common_test.go
- releasenotes/notes/gateway-handler.yaml
Fixes https://github.com/istio/istio/issues/43362
> [release-1.16] gateway-api: fix `EnqueueForParentHandler`

- tests/integration/ambient/main_test.go
https://github.com/istio/istio/issues/43418
> Temporarily skip ambient in postsubmit

- pkg/bootstrap/platform/gcp.go
- pkg/bootstrap/platform/gcp_test.go
> use gcp metadata for all the cases

- istioctl/cmd/proxyconfig.go
Short format is supported but not listed in the supported formats.
> Add missing supported format of ECDS config dump

- pilot/pkg/extensionproviders/cluster_lookup.go
> improve error output of cluster lookup

- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
> Optimize: reduce convertion on previous k8s service

- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
- releasenotes/notes/43453.yaml
> telemetry: support to control trace id length on Zipkin

- prow/lib.sh
> test: build ztunnel for postsubmit jobs

- tests/integration/ambient/main_test.go
> Skip unsupported ambient envs
