istio/istio

- pkg/kube/client.go
- pkg/kube/mock_client.go
This is going to be useful when we need to change CRD's but cannot call `ApplyYAMLFiles()` because our CRD is too big and k8s apply complains about it. So, after changing the CRD through other means, we can call this new `InvalidateDiscovery()` just like `ApplyYAMLFile()` does.
> Add InvalidateDiscovery() to the Client interface

- cni/pkg/install/install.go
- releasenotes/notes/41858.yaml
```release-note
only print warning if istio-cni is not default cni plugin when cni is used as a standalone plugin
```
Signed-off-by: Fei Su <sofat1989@126.com>
When we use istio-cni as a standalone plugin, we must have another one cni plugin to set up the network (create eth0 and set the ip address) for the containers before calling the istio-cni.
```
00-tnet.conf YYY-istio-cni.conf
```
So the first file `00-tnet.conf` will be treated as the defaultCNIConfigFilename here. But it is expected. 
https://github.com/istio/istio/blob/master/cni/pkg/install/install.go#L230
```
defaultCNIConfigFilename, err := getDefaultCNINetwork(cfg.MountedCNINetDir)
```
It should not return error in the func `func checkInstall(cfg *config.InstallConfig, …
> only print warning if istio-cni is not default cni plugin when cni is used as a standalone plugin

- pkg/config/validation/extensionprovider.go
- pkg/config/validation/extensionprovider_test.go
Opentelemetry tracing provider in istio `1.16.0` is not working as the validation is missing.
>2022-11-18T11:36:58.850898Z	warn	validation	found invalid extension provider (can be ignored if the given extension provider is not used): invalid extension provider otel: unsupported provider: &{service:"collector.otel.svc.cluster.local"  port:4317} of type *v1alpha1.MeshConfig_ExtensionProvider_Opentelemetry
used config:
```yaml
meshConfig:
enableTracing: true
extensionProviders:
- name: otel
opentelemetry:
service: collector.otel.svc.cluster.local
port: 4317
defaultProviders:
tracing:
- otel
defaultConfig:
tracing:
sampling: 100
```
> validate opentelemetry tracing extension provider

- pilot/pkg/bootstrap/istio_ca.go
- security/pkg/util/jwtutil.go
- security/pkg/util/jwtutil_test.go
Per the JWT spec, all three parts of the token are to be base64url encoded.  The JWT spec (RFC7519) defers to the JWS spec (RFC7515) on the implementation of base64url encoding. The JWS spec calls for `=` padding characters to be removed during encoding.  The current istio implementation for JWT payload decoding uses the raw base64 decoder which causes an error if the encoded payload contains underscore or dash characters from the base64url alphabet.  This PR changes the payload decoding to expect URLEncoding without padding.
- [] Does not have any …
> Decode payload with URLEncoding per the JWT spec

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
Setting maxstream duration for cases where VS does not specify timeout, does not allow to set timeout via envoy filters. Since max stream duration has some regressions, use the deprecated "MaxGrpcTimeout" similar to how we do for actual timeout cases.
> avoid using max stream duration for no timeout cases

- pilot/pkg/config/kube/gateway/conversion.go
This is a followup to #41742 which fixed the `less` function used by `sortHTTPRoutes`, but not quite right. The current and corrected behavior is as follows:
```
i.len   j.len   current      corrected
-----   -----   -------      ---------
!0      !0      cmp match    cmp match
!0      0       true         true
0       !0      cmp match    false
0       0       false        false
```
> gateway-api: fix sorting of merged httproutes

- .gitignore
- CONTRIBUTING.md
Add instructions for how to retrieve the `local-test-utils` directory, and document some of the overrides necessary to build Rust ztunnel using Docker Desktop for macOS.
> Clarify documentation for Ambient on macOs

- tools/certs/Makefile.selfsigned.mk
When using LibreSSL 2.8.3 the generated certs are using SHA1. This causes istiod to fail to start up due to changes in go 1.18 (see https://github.com/golang/go/issues/41682).
This also fixes the instructiosn for
https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/
> Always use sha256 when generating self-signed certs (sample code)

- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta.go
- pkg/istio-agent/xds_proxy_test.go
- pkg/wasm/cache.go
- pkg/wasm/cache_test.go
- pkg/wasm/convert_test.go
- releasenotes/notes/42167.yaml
#42167 won't fix the issue, unlike LDS, ECDS do not contains all modules every time.
> Revert "wasm: improve wasm cache"

- pilot/pkg/model/push_context.go
- pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
- pilot/pkg/xds/nds.go
- pilot/pkg/xds/proxy_dependencies.go
Continuing on https://github.com/istio/istio/pull/42089, when headless service endpoints change, but features. EnableHeadlessService is off, DNS is enabled, NDS will have stale endpoints.
This PR fixes it.
> push headless endpoint change when headless enabled or dns is enabled

- pilot/pkg/xds/sds.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/42203.yaml
- security/pkg/nodeagent/sds/sdsservice.go
When the PrivateKeyProvider configuration information is provided through Istio operator yaml file, parse and pass it to gateway or sidecars. Envoy will act based on the information provided by the configuration.
To set the mesh wide defaults, configure the `defaultConfig` section of `meshConfig`. For example:
```
meshConfig:
defaultConfig:
privateKeyProvider:
qat:
pollDelay: 0.01s
```
This can also be configured on a per-workload basis by configuring the `proxy.istio.io/config` annotation on the pod.
For example:
```
annotations:
proxy.istio.io/config: |
privateKeyProvider:
qat:
pollDelay: 0.01s
```
API addition PR https://github.com/istio/api/pull/2565
Note: Users should request QAT resources through k8s:resources.
> Handle QAT PrivateKeyProvider configuration

- pilot/pkg/serviceregistry/kube/controller/pod.go
- pilot/pkg/serviceregistry/kube/controller/pod_test.go
When a pod is created/deleted, it gets updated several times before it's ready/removed. We can skip those unnecessary events that build endpoints and notify workload handlers
> Reduce unnecessary workload handler calls on pod updates

- releasenotes/notes/deprecate-k8sca-upto-v1.20.yaml
- tests/integration/security/mtlsk8sca/main_test.go
- tests/integration/security/sds_ingress_k8sca/main_test.go
PR #42111 adds support for mounting k8s root cert when cert provider is kubernetes. This fixes issues caused when automountServiceAccountToken is false. This uses a configmap kube-root-ca.crt. This configmap is supported from k8s version 1.20 onwards. This means we cannot run the new version of istio with pilot cert provider as kubernetes for k8s version < 1.20
> Add min version required to 20 for tests using k8sca

- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/controller_test.go
The behavior of stripping pod/node unused fields is overridden by the `FilteredSharedIndexInformer`. The new added unit tests will be failed without this pr.
CC @hzxuzhonghu
> Make pod/node unused fields removed.

- pilot/pkg/serviceregistry/kube/controller/controller.go
- releasenotes/notes/42252.yaml
Currently, the informerInit marker doesn't work for remote cluster sync timeout case. Remove it and use the initialSync marker.
CC @hzxuzhonghu
> Fix remote cluster sync timeout issue

- pilot/pkg/util/network/ip_test.go
This fails between go1.19 and go1.20 and is not needed to be this strict
> Make TestResolveAddr err check less strict

- cni/pkg/plugin/plugin_test.go
- cni/pkg/plugin/redirect.go
- releasenotes/notes/42381.yaml
excludeInterfaces was originally added by https://github.com/istio/istio/pull/34832 and annotation was added by https://github.com/istio/istio/pull/39404. Noticed related feature was not added in cni plugin. This PR adds missing pieces to cni plugin.
> Add excludeInterfaces support to istio cni plugin

- pilot/pkg/model/push_context_test.go
- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/aggregate/controller.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/memory/discovery.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/xds/delta.go
- pilot/pkg/xds/workload.go
- pilot/pkg/xds/workload_test.go
2 bugs:
* On reconnect we ignored the initial resource
* On a subscription to a Service, we missed new pods in the service
For https://github.com/istio/istio/issues/42314
> xds: fix reconnect on-demand XDS in ambient and Service subscriptions

- pkg/config/analysis/analyzers/testdata/misannotated.yaml
The apiversion `extensions/v1beta1` has been deprecated for k8s ingress for a long time.
Although it does not affect the test results, I think it is better to replace them from the test cases.
> fix deprecate apiversion for ingress in testdata

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/testdata/alias.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/delegated.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/invalid.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/mesh.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/reference-policy-service.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/route-binding.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/route-precedence.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/serviceentry.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/tls.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/weighted.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/zero.yaml.golden
Add a default name for the routes generated in Gateway/GAMMA - it allows better debugging and EnvoyFilters
targeting such routes.
> Auto-name the VS routes in HTTPRoute auto-generated  

- pilot/cmd/pilot-agent/status/server.go
Currently, we join all errors. Its better to fail on first because:
* Prometheus does this: https://github.com/prometheus/client_golang/blob/main/prometheus/promhttp/http.go#L205-L207
* Without it we get logs like
```
2022-12-16T21:54:52.211619Z     error   failed scraping and writing agent metrics: 28 errors occurred:
* write tcp 10.244.0.46:15020->10.244.0.27:53666: write: broken pipe
* write tcp 10.244.0.46:15020->10.244.0.27:53666: write: broken pipe
* write tcp 10.244.0.46:15020->10.244.0.27:53666: write: broken pipe
* write tcp 10.244.0.46:15020->10.244.0.27:53666: write: broken pipe
* write tcp 10.244.0.46:15020->10.244.0.27:53666: write: broken pipe
* write tcp 10.244.0.46:15020->10.244.0.27:53666: write: broken pipe
* write tcp 10.244.0.46:15020->10.244.0.27:53666: write: broken …
```
> agent: fail fast on first error

- pilot/pkg/config/kube/crd/config.go
- pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
- pilot/pkg/xds/fake.go
- pkg/kube/client.go
- pkg/kube/util.go
As part of the GAMMA impl, this was removed because we can't attach to arbitrary hostnames. However, nothing in the test actually applies to arbitrary hostnames -- we can do the same test using Service, but in a way to support both modes.
There are a few tests with wildcards we genuinely can't do with gateway (yet), so those are skipped.
This also introduces some helper functions to make it easier to use K8s and Istio types in a single YAML, for tests.
cc @frankbu
> TestSidecarRoutes: re-enable for Gateway API

- manifests/charts/ztunnel/templates/daemonset.yaml
related ztunnel PR:
https://github.com/istio/ztunnel/pull/296
sets env var for ztunnel that istiod checks for in internal `IsZTunnel()` logic
> set AMBIENT_TYPE env var for ztunnel

- istioctl/cmd/analyze.go
- releasenotes/notes/istioctl-analyze-revision.yaml
add revision flag to istioctl analyze to allow it to analyze deployments that use revisions. today this is not supported
Issue: https://github.com/istio/istio/issues/38148
PR1: https://github.com/istio/istio/pull/38659
PR2: https://github.com/istio/istio/pull/38826
> istioctl analyze revision

- pilot/pkg/networking/grpcgen/grpcgen_test.go
- pilot/pkg/networking/grpcgen/lds.go
This is an enhancement over the previous PR #40660 to add cookie path support via the label configuration
> add cookie path support to config via label istio.io/persistent-session

- pkg/config/model.go
Currently indent is only for non-protobuf, so the function is inconsistent
> ToPrettyJSON: ident even for protobuf

- pilot/pkg/bootstrap/istio_ca.go
- pkg/kube/inject/watcher.go
- security/pkg/nodeagent/cache/secretcache.go
Signed-off-by: yanggang <gang.yang@daocloud.io>
As [fsnotify v1.6.0](https://github.com/fsnotify/fsnotify/releases/tag/v1.6.0) mentioned , 
```
if event.Op&Write == Write && !(event.Op&Remove == Remove) {
}
```
can become 
```
if event.Has(Write) && !event.Has(Remove) {
}
```
```release-note
None
```
/label release-notes-none
> make fsnotify event more readable.

- pkg/test/framework/components/echo/kube/instance.go
- releasenotes/notes/42590.yaml
```go
pod, err := wl.Cluster().Kube().CoreV1().Pods(c.NamespaceName()).Get(context.TODO(), pod.Name, metav1.GetOptions{})
if err != nil {
return fmt.Errorf("get pod %s/%s failed: %v", pod.Namespace, pod.Name, err)
}
```
When err.`pod` will be override by default `fmt.Errorf("get pod %s/%s failed: %v", pod.Namespace, pod.Name, err)` . No more access to the most original names and spaces.
> Repair value override

- istioctl/cmd/clusters.go
- istioctl/cmd/proxystatus.go
- pilot/cmd/pilot-agent/status/server.go
- pilot/cmd/pilot-agent/status/server_test.go
- pkg/kube/client.go
- pkg/proxy/proxyinfo.go
- pkg/test/kube/dump.go
Using a single shared client risks other parts of the code (or dependencies) modifying the client and breaking things. See https://github.com/kubernetes-sigs/gateway-api/pull/1617 for an exmaple where this happened.
Also fix up paths to avoid `//debug` requests which always get a 301.
> Drop `http.DefaultClient`

- pilot/pkg/xds/delta.go
pilot/pkg/xds/ads.go:133
```go
func (s *DiscoveryServer) receive(con *Connection, identities []string) {
defer func() {
close(con.errorChan)
close(con.reqChan)
// Close the initialized channel, if its not already closed, to prevent blocking the stream.
select {
case <-con.initialized:
default:
close(con.initialized)
}
}()
firstRequest := true
for {
req, err := con.stream.Recv()
if err != nil {
if istiogrpc.IsExpectedGRPCError(err) {
log.Infof("ADS: %q %s terminated", con.peerAddr, con.conID)
return
}
con.errorChan <- err
log.Errorf("ADS: %q %s terminated with error: %v", con.peerAddr, con.conID, err)
totalXDSInternalErrors.Increment()
return
}
// This should be only set for the first request. The node id may not be set - for example malicious …
```
> handle HealthInfoType

- pilot/pkg/model/virtualservice.go
- pilot/pkg/model/virtualservice_test.go
- releasenotes/notes/bug-fix-virtualservice-visibilty-private.yaml
For `defaultVirtualServiceExportTo: ["."]`, defaultExportTo is a map containing a key `visibility.Instance(".")` which doesn't match the key `visibility.Instance(root.Namespace)`. 
This PR fixes that check by adding a key `visibility.Instance(vs.Namespace)`, similar to what is done while processing exportTo within VirtualServices.
Fixes #42602
> Fix delegate VirtualService merging for visibility.Private

- pilot/pkg/bootstrap/config_compare.go
- pilot/pkg/bootstrap/config_compare_test.go
Currently we just check whether "curr" has istio.io labels/annotations. But if current does not have and previous has then also we need to push (e.g. exportTo annotation has been removed in current, so we need to apply defaults and push)
> fix config compare logic

- pkg/bootstrap/platform/gcp.go
- pkg/bootstrap/platform/gcp_test.go
- pkg/test/framework/components/echo/kube/templates/vm_deployment.yaml
Fixes  https://github.com/istio/istio/issues/42449
Fixes https://github.com/istio/istio/issues/42452
Note because of #42452 this test has been broken of GCP forever. It only recently broke on GCP due to #42449 
> Fix VM DNS in tests

- istioctl/cmd/analyze.go
https://github.com/istio/istio/pull/42435 caused an error when using `istioctl analyze` in the istio.io tests as the revision was not being set to `default`. 
See https://github.com/istio/istio.io/pull/12417.
No new release note since this is just correcting the default revision to being `default`.
> Fix revision variable in istioctl analyze

- tests/integration/telemetry/envoyfilter/customizemetrics/customize_metrics_test.go
Reverts istio/istio#42563
This is causing flaky tests; @kyessenov is looking into it (I think?) but in the meantime we should revert to unblock other PRs as it fails >50% of the time
> Revert "add e2e for MetricDefinition"

- pilot/pkg/xds/debug.go
- releasenotes/notes/configdump-query-types.yaml
`/debug/config_dump?types=ecds` was implemented but none of the other config_dump type
> implement config dump query by resource type for missing types

- pilot/pkg/config/kube/crdclient/cache_handler.go
- pilot/pkg/config/kube/gateway/controller.go
- pilot/pkg/serviceregistry/kube/controller/autoserviceexportcontroller.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
- pilot/pkg/serviceregistry/kube/controller/endpoints.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/serviceregistry/kube/controller/pod.go
- pilot/pkg/serviceregistry/kube/controller/serviceexportcache.go
- pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
- pilot/pkg/serviceregistry/kube/controller/util.go
- pkg/kube/controllers/common.go
- pkg/kube/controllers/common_test.go
- pkg/kube/namespace/filter.go
- pkg/test/framework/components/echo/kube/pod_controller.go
- security/pkg/k8s/chiron/controller.go
- security/pkg/k8s/chiron/controller_test.go
Currently, we have this logic spread throughout the codebase, introducing boilerplate and risk of bugs. This unifies the implementation
> Consolidate tombstone handling

- pkg/util/sets/set.go
- pkg/util/sets/set_test.go
1. Optimize `SupersetOf` func performance
2. Add an alias func `ContainsAll` of `SupersetOf`
3. Add more test cases
benchmark:
```shell
$ go test -bench="BenchmarkSupersetOf" -test.benchmem -count=10 . >> old.txt # old code
$ go test -bench="BenchmarkSupersetOf" -test.benchmem -count=10 . >> new.txt # new code
name                      old time/op    new time/op    delta
SupersetOf/SupersetOf-12    1.28µs ± 4%    1.17µs ± 6%    -8.44%  (p=0.000 n=9+10)
name                      old alloc/op   new alloc/op   delta
SupersetOf/SupersetOf-12     48.0B ± 0%      0.0B       -100.00%  (p=0.000 n=10+10)
name                      old allocs/op  new allocs/op  delta
SupersetOf/SupersetOf-12      1.00 ± 0%      0.00 …
```
> optimize SupersetOf func performance

- pilot/pkg/model/context.go
- pilot/pkg/model/virtualservice.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
- pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
Refactored to replace the use of the deprecated [jsonpb](https://pkg.go.dev/github.com/golang/protobuf/jsonpb) package with the `protojson` equivalent.
> Replace deprecated jsonpb package

- pilot/pkg/model/push_context.go
- pilot/pkg/xds/proxy_dependencies.go
- pilot/pkg/xds/proxy_dependencies_test.go
- pkg/config/host/name.go
- releasenotes/notes/auto-passthrough-regression.yaml
Auto-passthrough gateways do not require virtual services, we should push when related services are changed
> `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG`: fix false negatives for AUTO_PASSTHROUGH

- pilot/pkg/serviceregistry/mock/discovery.go
- pilot/pkg/serviceregistry/mock/discovery_test.go
Signed-off-by: yanggang <gang.yang@daocloud.io>
/kind bug
Fix panic , when the netip.ParseAddr is null.
As test code below:
> Fix panic when netip.ParseAddr is nil return.

- samples/tcp-echo/src/main.go
Signed-off-by: yanggang <gang.yang@daocloud.io>
Build the sample ```samples/tcp-echo/src/main.go```, run it without parms, it panic without hint.
Fix it with parms valid and give hint for user..
/label release-notes-none
```release-note
None
```
> Fix tcp-echo sample run panic.

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
- releasenotes/notes/42712.yaml
- tests/integration/pilot/common/routing.go
Change to support dual stack for statefulsets/headless, service entry and gateway, this PR is for [issue#40394](https://github.com/istio/istio/issues/40394)
1. Support to generate configuration for Istio gateway with dual stack enabled
2. use `getWildcardsAndLocalHost` instead of `getActualWildcardAndLocalHost` for inbound cluster building
> Change to support dual stack for gateway to generate configuration and use getWildcardsAndLocalHost for inbound cluster building

- pilot/pkg/networking/core/v1alpha3/serviceentry_simulation_test.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- pilot/pkg/xds/nds_test.go
To prevent unnecessary listener draining and to have a stable IP allocated for service entries.
> auto allocate ips based on hashing

- README.md
Adds the CNCF logo to the Istio readme as recommended by the project onboarding guidelines.
> Add CNCF logo to Istio readme

- CONTRIBUTING.md
Since rust based ztunnel is default now.
- [ x ] Ambient
> Clean up the instructions a bit

- pilot/pkg/model/extensions.go
- pkg/istio-agent/xds_proxy_test.go
- pkg/wasm/cache.go
- pkg/wasm/cache_test.go
- pkg/wasm/convert.go
- pkg/wasm/convert_test.go
- pkg/wasm/options.go
This PR proposes refactoring Wasm related codes for readability and extensibility.
Highlights are two folds.
1. Simplify `Cache.Get` method by adopting `GetOptions`.
2. `Cache.addEntry` and `Cache.getEntry` now return `cacheEntry` instead of `modulePath`.
> wasm: Refactor Wasm related codes in Istio Agent

- pkg/config/analysis/analyzers/envoyfilter/envoyfilter.go
- releasenotes/notes/42832.yaml
https://github.com/istio/istio/issues/42831
Before the change `istioctl analyze` was throwing SIGSEGV when optional field 'filter' was missing under EnvoyFilter.ListenerMatch.FilterChainMatch section.
Fixes SIGSEGV istioctl analyze issue described here  https://github.com/istio/istio/issues/42831
> Fix analyzing envoy filter when 'filter' field is missing

- pilot/pkg/xds/eds.go
- pilot/pkg/xds/eds_test.go
When checking incremental EDS, we can ignore irrelevant resource updates merged by debounce. This happens in cases like [creating a VS right after a service](https://istio.io/v1.15/docs/ops/best-practices/traffic-management/#set-default-routes-for-services), which is a common practice I think
> incremental EDS: take debounce into account

- prow/release-commit.sh
Update master to release-1.16. This appears to have been missed during branch cut.
> [release-1.16] Update master to 1.16

- manifests/charts/ztunnel/templates/daemonset.yaml
I don't think we need these, it spams 10+ kernel logs on each packet
> ambient: drop iptables debug logs

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
This was for the old old "BTS" implementation, unused.
> Cleanup unused metadata

- pilot/pkg/xds/debug.go
- pilot/pkg/xds/statusgen.go
Allows users to get proxy node locality via /debug/adsz. This can help debug the feature of [locality failover](https://istio.io/latest/docs/tasks/traffic-management/locality-load-balancing/failover/).
> Add locality info to debug interface

- pkg/wasm/convert.go
- pkg/wasm/convert_test.go
Change-Id: I8143ba8bc8c292ce2de5abda0a4f0c70c111bf80
In current impl, if ECDS resource message is not well-formed (e.g., fail to unmarshal or absence of required fields), the ECDS is just passed to Envoy.
This would just defer the error to Envoy and makes debugging harder.
This proposes to send Nack in that case.
In addition, to help debugging, Debugf is changed to Errorf for the cases that the message is not well-formed.
> wasm: Send nack when there is not well-formed resource messages

- pilot/pkg/leaderelection/k8sleaderelection/leaderelection_test.go
Opening a draft PR for #37555, to check if the direction is good.
I reduced the times configured for the LeaderElector, so to shorten the waiting times for the tests.
- `TestReleaseOnCancellation_ConfigMaps`
- `TestReleaseOnCancellation_Lease`
- `TestReleaseOnCancellation_Endpoints`
now execute in 0.01s.
[stress test](https://github.com/istio/istio/wiki/Test-Flakes#reproducing-test-flakes) applied to the 3 methods are reporting 0 failures (ran for 12 minutes)
Eager to have feedback / suggestions.
> reducing leaseduration, renewdeadline and retryperiod

- prow/integ-suite-kind.sh
- prow/lib.sh
- tools/docker-builder/docker.go
Update the default k8s for pre-submit to 1.26.1. This requires an equal change in istio/test-infra to move the post-submit test from 1.26 to 1.25.4. A PR in istio/test-infra for that is forthcoming.
Also update buildkit to v0.11.0
> Update default k8s for test and buildkit

- security/pkg/stsservice/tokenmanager/google/mock/mockserver.go
This PR proposes to remove 1 second sleep from Start method of AuthorizationServer (mock).
This speeds up `TestTokenExchangePluginWithCache` described in #37555 .
> removed sleep from mock of AuthorizationServer

- pilot/pkg/ambient/ambientpod/podutil.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pkg/config/constants/constants.go
- tests/integration/ambient/bookinfo_test.go
- tests/integration/ambient/main_test.go
add constant for `istio.io/dataplane-mode` namespace label
> use common var for ambient namespace label

- pkg/hbone/dialer.go
- pkg/hbone/dialer_test.go
This PR adds the option of configuring a timeout for `hbone` dialer, and makes use of it in the tests:
- `TestDialerError` (previously 75s, with this modification is 0.5s)
- `TestDialer` (previously 0.01s, with this modification is still 0.01s)
The change is backward compatible.
related to #37555
> added timeout option for hbone dialer

- istioctl/pkg/install/k8sversion/version.go
- istioctl/pkg/install/k8sversion/version_test.go
- operator/cmd/mesh/testdata/manifest-generate/output/all_on.golden-show-in-gh-pull-request.yaml
- operator/cmd/mesh/testdata/manifest-generate/output/pilot_default.golden.yaml
- operator/pkg/helm/helm.go
- releasenotes/notes/42513.yaml
Manual cherry-pick https://github.com/istio/istio/pull/42513.
Also, combine this one https://github.com/istio/istio/pull/41838, which unblocks the former PR.
From https://istio.io/latest/docs/releases/supported-releases/, the min supported version is 1.22.
Fix https://github.com/istio/istio/issues/42945.
> [release-1.16] Fix `manifest generate` generates deprecated versions of templates

- istioctl/cmd/revision.go
- istioctl/cmd/revision_test.go
- releasenotes/notes/fix-istioctl-revision.yaml
- tests/integration/pilot/revisioncmd/revision_view_test.go
```bash
[root@controller-node-1 ~]# kubectl  get iop -n istio-system nicole-mesh -oyaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
labels:
app.kubernetes.io/managed-by: Helm
name: nicole-mesh
spec:
status:
componentStatus:
Base:
status: HEALTHY
IngressGateways:
status: HEALTHY
Pilot:
status: HEALTHY
status: HEALTHY
[root@controller-node-1 ~]# istioctl  x  revision list
REVISION TAG      ISTIO-OPERATOR-CR                     PROFILE REQD-COMPONENTS
default  <no-tag> istio-system/nicole-mesh default
```
DO:
- fix  the data is not accurate of cloume `REQD-COMPONENTS`
- optimize output format  of `-o table` code
- uniform output style with pkg `operator/pkg/name/name.go fuc: …
> Fixed `istioctl x revision list` the output the data is not accurate of enabled components

- go.mod
- go.sum
- pilot/pkg/model/push_context.go
- pilot/pkg/networking/core/v1alpha3/tracing.go
- pkg/bootstrap/config.go
- pkg/config/validation/extensionprovider.go
Supersedes https://github.com/istio/istio/pull/43051
Lightship was deprecated in https://github.com/istio/api/pull/2635 and pulling the client-go changes into istio/istio requires some lint changes. The release-notes are in the istio/api PR.
> Lightstep deprecated

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/config/kube/gateway/templates/deployment.yaml
- pilot/pkg/config/kube/gateway/templates/service.yaml
Small clean-up. We currently define the managed-by label of the deploymentcontroller both in the template and the code, which is error-prone and leads to hard coupling between templates and controller code. Moving it only to the controller code will allow us to have user-defined templates for the deployment-controller without the danger that the user accidentally breaks the managed-by functionality.
> gateway-api: use constants for deploymentcontroller's managed-by label

- pkg/kube/multicluster/secretcontroller.go
- pkg/kube/multicluster/secretcontroller_test.go
If we delete remote cluster A and re-add remote cluster A, we will get the following warn message and the re-add action is failed.
```
warn  cluster has already been registered  cluster=c0-1 secret=istio-system/s0
```
The added unit test can show this case. The reason is that when we remove cluster A, we forget to delete cluster A from cluster set.
This pr also refactors codes by reusing the method `deleteCluster`.
CC @howardjohn @hzxuzhonghu
> Fix re-add remote cluster case.

- tests/integration/pilot/common/routing.go
Signed-off-by: Benjamin Leggett <benjamin.leggett@solo.io>
Fixes https://github.com/istio/istio/issues/43070 - CI doesn't run a complete battery of IPv6 tests, so this slipped thru.
> Build fix for issue #43070

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/config/kube/gateway/templates/deployment.yaml
- pilot/pkg/config/kube/gateway/templates/service.yaml
Follow-up on #43067 - this is a simpler version, now entirely independent of the templates. We simply add the managed-by label after generating the resources, directly in `ApplyTemplate()`. Sorry for the noise- I came up with this one only after the previous PR was already merged.
> gateway-api: completely decouple template from code for managed-by label

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/pod.go
Ran across a bug where a Pod that makes outbound calls to the k8s API as part of its readiness/liveness checks gets permanently stuck due to ztunnel dropping the connection, leading to the Pod never entering a Ready state (Pod has a phase of Running but never reaches a condition of Ready).
This is exposed by the fact that ztunnel explicitly drops the connection if it cannot find the _source_ workload in the xDS workload API - and indeed the source workload is _not_ present in the xDS workload API from ztunnel's perspective, because we currently only add a workload entry if the Pod has a condition of Ready.
This PR fixes that by adding more granularity to the lifecycle checks:
1. Allow creation of workload entries for pods in the Running phase, regardless of their Readiness (meaning they …
> Pods in unReady state must generate workload entries

- pkg/wasm/cache.go
Fixes https://github.com/istio/istio/issues/42502.
There seems to be a race condition for making directories for Wam module, concurrently.
To prevent it, this PR proposes to just try to create the directory regardless of its existence, 
and then if there is an error, check if it is an "exist" error.
> wasm: fix a race condition on making directories for wasm binaries.

- security/pkg/nodeagent/caclient/providers/google-cas/client.go
See https://pkg.go.dev/math/rand#Seed
> go 1.20 doesn't require rand.Seed

- pilot/test/xdstest/validate.go
This PR proposes to refactor `validateFilterChainMatch` to make it linear.
This brings `istio.io/istio/pilot/pkg/networking/core/v1alpha3` package test execution from ~30s to ~7s
Contributes to #37555
> Optimise validate filter chain match

- pilot/pkg/model/push_context.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_waypoint.go
- tests/integration/ambient/baseline_test.go
This fixes + tests cross-waypoint load balancing. Previously we ALWAYS filtered outbound clusters. Now we selectively include them IFF they are referenced
> ambient: test cross-waypoint load balancing

- pilot/pkg/model/push_context.go
- pilot/pkg/model/xds_cache.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/grpcgen/cds.go
- pilot/pkg/serviceregistry/kube/controller/pod.go
- pilot/pkg/serviceregistry/util/workloadinstances/map.go
- pilot/pkg/status/distribution/reporter.go
- pkg/util/sets/set.go
- pkg/util/sets/set_test.go
- tools/bug-report/pkg/bugreport/bugreport.go
This introduces two new helper functions to add and remove to map of
sets. These are simpler to use and help ensure all callers are correct +
efficient.
> sets: Add utilities for map of sets

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
Release 1.24 of Envoy [deprecated](https://www.envoyproxy.io/docs/envoy/v1.24.2/version_history/v1.24/v1.24.0#deprecated) this field. So removing it now
> remove deprecated use of 'Append' in header value options

- pkg/test/framework/components/echo/common/ports/ports.go
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/tunneling_test.go
- tests/integration/security/authz_test.go
- tests/integration/security/pass_through_filter_chain_test.go
- tests/integration/security/reachability_test.go
- tests/integration/telemetry/common/stats.go
Today, we have access to constants for the port name, but then need to jump through hoops to use the name to lookup the port. This avoids that.
> tf: refactor ports to store full object

- pilot/pkg/networking/core/v1alpha3/route/route.go
Release 1.24 of Envoy [deprecated](https://www.envoyproxy.io/docs/envoy/v1.24.2/version_history/v1.24/v1.24.0#deprecated) this field. So removing it now
> remove deprecated use of 'TotalWeights' in routes

- go.mod
- go.sum
- pilot/pkg/config/kube/gateway/conditions.go
- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/invalid.yaml
- tests/integration/pilot/gateway_conformance_test.go
- tests/integration/pilot/testdata/gateway-api-crd.yaml
This is mostly just adding more tests, but one they added we failed. This is properly reporting Port and SectionName. This is a bit harder than it sounds due to the old code structure. The changes support this by:
* Have primary key not include port and sectionName; we need to bind to them even with mismatch, just not successfully
* Have error messages order the messages appropriately
> Bump gateway-api to v0.6.1

- istioctl/pkg/writer/envoy/configdump/listener.go
- pilot/pkg/util/protoconv/protoconv.go
Example:
```
LISTENER                          CHAIN                                                          MATCH                        DESTINATION
envoy://inbound_CONNECT_originate                                                                ALL                          Cluster: inbound_CONNECT_originate
envoy://internal                  inbound-vip|443||echo.default.svc.cluster.local-tcp            ip=10.96.238.42 -> port=443  Cluster: inbound-vip|443|tcp|echo.default.svc.cluster.local
envoy://internal                  inbound-vip|9090||echo.default.svc.cluster.local-tcp           ip=10.96.238.42 -> port=9090 Cluster: inbound-vip|9090|tcp|echo.default.svc.cluster.local
envoy://internal                  inbound-vip|9091||echo.default.svc.cluster.local-tcp           ip=10.96.238.42 …
```
> istioctl: support ip matcher in match tree

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/credentials/kube/multicluster.go
- pilot/pkg/credentials/kube/secrets.go
- pilot/pkg/credentials/kube/secrets_test.go
- pilot/pkg/credentials/model.go
- pilot/pkg/xds/sds.go
This PR adds capability to forward OCSP staple from kubernetes secret to Envoy.
PR covers Stage 1 of following design: https://docs.google.com/document/d/15wwYyVyOluubL2KIM89b2X8NFwyhMVxq2_I1MESrZdI/edit?pli=1
Where:
* Stage 1 - implement OCSP staple forwarding to Envoy proxy
* Stage 2 - implement control mechanism allowing to choose Envoy stapling mode via secret annotations
**Brief**
OSCP staple is DER encoded response provided by OSCP server as a reply to OSCP request.
Such response is stapled to TLS Certificate and provided to client on https handshake.
This PR implements forwarding of the OCSP staple to Envoy proxy.
OSCP staple is expected to be found inside kubernetes secret under field named `tls.ocsp-staple`.
Pre-fetching OSCP response and storing it in kubernetes secret is left …
> Add OCSP stapling support.

- pilot/pkg/bootstrap/configcontroller.go
- releasenotes/notes/pilot-status-too-many-logs.yaml
Fix https://github.com/istio/istio/issues/42612
After https://github.com/istio/istio/pull/40561 disabled the PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING env, pilot status controller keeps logging the error in a very small time interval:
```
2023-02-09T05:52:04.663205Z     error   status  Encountered error retrieving version 732d02fd-79e of key gateway.networking.k8s.io/v1beta1/gatewayclasses//istio/1 from Store: distribution tracking is disabled
2023-02-09T05:52:04.663207Z     error   status  Encountered error retrieving version 5d0e9369-e17 of key gateway.networking.k8s.io/v1beta1/gatewayclasses//istio/1 from Store: distribution tracking is disabled
2023-02-09T05:52:04.663209Z     error   status  Encountered error retrieving version 18491e2d-ef2 …
```
> Fix pilot status has too many logs

- samples/bookinfo/networking/bookinfo-gateway.yaml
Signed-off-by: nshankar <nshankar@microsoft.ghe.com>
Updates the bookinfo-gateway selector with a comment on what the default ingress k8s pod selector is for Helm.
> Update bookinfo gateway selector for Helm

- manifests/profiles/ambient.yaml
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pilot/pkg/xds/filters/filters.go
This brings sidecars back to the correct behavior (following https://istio.io/latest/blog/2021/upcoming-networking-changes/). This was a workaround due to limitations in the HBONE implementation previously
> ambient: add back orig_dst for inbound sidecars

- go.mod
- go.sum
- pilot/pkg/config/kube/gateway/conditions.go
- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/invalid.yaml
- tests/integration/pilot/gateway_conformance_test.go
- tests/integration/pilot/testdata/gateway-api-crd.yaml
This is a manual cherry pick required to move the gateway-api implementation in 1.17 to the latest 0.6.1 Gateway API.
Depends on #43281 (cherry-pick of an earlier PR).
Fixes #43280
> [Release 1.17] Manual cherry-pick of #43218

- pkg/dns/server/name_table.go
- pkg/dns/server/name_table_test.go
- releasenotes/notes/nds-merging.yaml
When a SE has multiple vips, we should merge those ips into the DNS name info instead of overriding
```yaml
metadata:
name: svc
spec:
hosts:
- foo.bar
addresses:
- 10.0.0.5
- 10.0.0.6
ports:
- name: tcp
number: 33333
protocol: tcp
location: MESH_EXTERNAL
```
> NDS: merge name info by hostname

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
This is the partly cherrypick for Istio 1.17 release based on [PR#43099](https://github.com/istio/istio/pull/43099).
And just merge code changes on bug fixing of `UpstreamBindConfig` configuration, exclude the `DNSlookupFamily` setting.
In fact, these code changes was added in Istio 1.16 via [PR#41618](https://github.com/istio/istio/pull/41618), and I added the assertion of `len(instExtraSvcAddr) > 0` when adding feature flag. It's unnecessary and caused bug described as below:
_The UpstreamBindConfig configuration will be incorrect if the service is deployed with a sing stack ip family in a dual stack cluster. And correct if the service is deployed with dual stack ip family in a dual stack cluster._
> fix bug for Istio 1.17 release when generating UpstreamBindConfig configuration 

- pilot/pkg/bootstrap/server.go
- releasenotes/notes/43318.yaml
This is a follow-up to #42248.
> Fix ignoring default CA cert by PeerCertVerifier

- Makefile.core.mk
- bin/build_ztunnel.sh
- istio.deps
- tools/docker.yaml
To do it properly, need https://github.com/istio/ztunnel/issues/394. For now this is a hack to unblock amd64 release.
> Include ztunnel in release

- tools/docker-builder/docker.go
The existing regex only matches a literal space character whereas [docker buildx prints a \t character](https://github.com/docker/buildx/blob/master/commands/inspect.go#L52). This will result in a false negative when checking for a docker-container builder on a save operation. This PR fixes the regex to match on any number of space characters to account for variations in environments and terminal settings (at least until https://github.com/docker/buildx/issues/381 is addressed)
> Update regex to match multiple space characters

- manifests/charts/ztunnel/README.md
- manifests/charts/ztunnel/templates/NOTES.txt
- manifests/charts/ztunnel/templates/daemonset.yaml
- manifests/charts/ztunnel/templates/rbac.yaml
- manifests/charts/ztunnel/values.yaml
- operator/pkg/translate/translate.go
The ztunnel chart - like most other Istio charts - is currently implemented in a non-standard way. Due to how the operator works, charts are currently nested. A user configures `.values.global.foo=bar` or `.values.ztunnel.foo=bar` to set values.
Neither of those really make sense in Helm -- we don't need a "global" when we are dealing with a single chart, and we don't need to specify "ztunnel" before everything when we already know we are installing ztunnel.
This PR moves to a more standard approach, flattening out the values. It also moves some trivial differences to align with the `gateway` chart (which takes the same approach!!). A README and NOTES.txt is added for documentation during install, and prepares it for eventual inclusion in artifacthub.
To make the operator work, we need a …
> ztunnel: move chart over to standard helm mechanism

- pilot/pkg/bootstrap/server.go
- pilot/pkg/bootstrap/server_test.go
- releasenotes/notes/42248.yaml
This is a manual cherry-pick of #42248.
> [release-1.16] pilot: ensure initialization of secure grpc server also when serving (#42248)

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/injection/injection-image.go
- pkg/config/analysis/analyzers/testdata/injection-with-mismatched-sidecar.yaml
- pkg/config/analysis/msg/messages.gen.go
- pkg/config/analysis/msg/messages.yaml
- releasenotes/notes/dedupe-mismatch-output.yaml
Related to https://github.com/istio/istio/issues/28511
Just upgraded Istio, and there's too many pod mismatch warning messages. Since the message needs to be based on resource, this PR optimizes the message to be displayed in namespace level instead of pod level.
The sample output contains three messages, otherwise it will display ~20 pod warning messages:
Warning [IST0158] (Namespace default) The Istio proxy images of the pods running in the namespace do not match the image defined in the injection configuration (pod names: [reviews-v3-c9c4fb987-rjknk details-v1-5ffd6b64f7-dkd24 reviews-v2-65c4dc6fdc-lcv5s sleep-78ff5975c6-p6frx helloworld-v2-54dddc5567-sgdm8 reviews-v1-85c9cf744f-htp9d helloworld-v1-78b9f5c87f-c6j68 …
> Analyze: dedupe proxy image mismatched outputs

- pilot/pkg/model/authorization.go
- pilot/pkg/model/service.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_waypoint.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_builder.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/networking/plugin/authz/authorization.go
- pilot/pkg/security/authz/builder/builder.go
- pilot/pkg/security/authz/builder/builder_test.go
- pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-ambient-out.yaml
- pilot/pkg/security/authz/builder/testdata/http/multiple-policies-ambient-out.yaml
- pilot/pkg/security/authz/model/model.go
- tests/integration/ambient/baseline_test.go
Ref https://github.com/istio/istio/issues/43009.
Enables sniffed HTTP processing on direct pod IP chain.
Enables general filters on waypoints using waypoint labels. Filters are applied uniformly across all HTTP chains.
> waypoint: re-enable authz

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_waypoint.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/security/model/authentication.go
- pilot/pkg/xds/endpoint_builder.go
- pkg/bootstrap/testdata/all_golden.json
- pkg/bootstrap/testdata/auth_golden.json
- pkg/bootstrap/testdata/authsds_golden.json
- pkg/bootstrap/testdata/default_golden.json
- pkg/bootstrap/testdata/metrics_no_statsd_golden.json
- pkg/bootstrap/testdata/running_golden.json
- pkg/bootstrap/testdata/runningsds_golden.json
- pkg/bootstrap/testdata/stats_inclusion_golden.json
- pkg/bootstrap/testdata/tracing_datadog_golden.json
- pkg/bootstrap/testdata/tracing_lightstep_golden.json
- pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
- pkg/bootstrap/testdata/tracing_stackdriver_golden.json
- pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
- pkg/bootstrap/testdata/tracing_tls_golden.json
- pkg/bootstrap/testdata/tracing_zipkin_golden.json
- pkg/bootstrap/testdata/xdsproxy_golden.json
- tools/packaging/common/envoy_bootstrap.json
Minor improvements to waypoint xDS:
* set internal watermark buffer size to 64kb;
* remove passthrough clusters in waypoints - they would never do the right thing;
* rename to shorter symbols "connect_terminate" and "connect_originate";
* fully convert to typed SAN validation;
* remove unnecessary filters from CONNECT termination.
> waypoint: simplification jumbo

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_metric_test.go
- releasenotes/notes/43179.yaml
Signed-off-by: hejianpeng <hejianpeng2@huawei.com>
fixes: #43178
> fix disabling ALL_METRICS does not work as expected

- pilot/pkg/bootstrap/server.go
- releasenotes/notes/43318.yaml
This is a manual cherry-pick of #43318. Related issue: #43336.
> [release-1.16] Fix ignoring default CA cert by PeerCertVerifier (#43318)

- istioctl/cmd/proxyconfig.go
- istioctl/cmd/root.go
- istioctl/cmd/waypoint.go
- istioctl/pkg/util/configdump/workload.go
- istioctl/pkg/writer/envoy/configdump/listener.go
- istioctl/pkg/writer/ztunnel/configdump/configdump.go
- istioctl/pkg/writer/ztunnel/configdump/workload.go
- pilot/pkg/util/protoconv/protoconv.go
- pkg/config/constants/constants.go
For https://github.com/istio/istio/issues/40879
This PR imports the istioctl/ changes from ambient. This consists of:
* A new `x waypoint` command. This is experimental, so should not be an issue
* `pc workloads` and a new `--waypoint` flag for `pc listener`. These are both *hidden* (since we don't have experimental within subcommands), so should be fine
* Minor tweaks to existing commands with no expected user changes
Overall, we expect no changes to non-ambient istioctl users.
Quoting from the issue:
> **Reviewer guide**
> 
> It is suggested that reviewers treat these PRs differently than normal, as the code has already been reviewed. PRs _should_ be thoroughly reviewed for risk to non-ambient users, ensuring any new/risky/expensive code is disabled by default. However, code quality …
> ambient upstream: new istioctl commands

- pilot/pkg/config/kube/ingress/controller_test.go
Somehow this test got removed accidentally when we remove the old API version support. Adding it back.
> ingress: add back test

- pkg/keepalive/options.go
- releasenotes/notes/42398.yaml
This is a manual cherry pick of #42398, for adding env variables related to gRPC keepalive configuration
Fixes #43373
> [release-1.17] Manual cherry-pick of #42398

- pilot/pkg/networking/grpcgen/grpcgen_test.go
- pilot/pkg/networking/grpcgen/lds.go
For statefulSesion affinithy support a new http-filter was added at the end which violates the condition that the router filter has to be the last filter (see https://github.com/grpc/proposal/blob/master/A39-xds-http-filters.md#http-filter-registry and https://www.envoyproxy.io/docs/envoy/v1.25.1/intro/arch_overview/http/http_filters.html#filter-ordering)
So this PR fixes it by inserting stateful session filter at the beginning
> grpcgen: make sure router filter is always last: insert statefulSessionAffinity filter at the beginning

- pilot/pkg/networking/grpcgen/lds.go
- pilot/pkg/security/authn/factory/factory.go
- pilot/pkg/security/authn/policy_applier.go
- pilot/pkg/security/authn/v1beta1/policy_applier.go
- pilot/pkg/xds/endpoint_builder.go
- pilot/pkg/xds/mtls_checker.go
Previously mtls checker currently couples with PolicyApplier to use only one of its method `GetMutualTLSModeForPort`, but actually policyapplier will do other work like processing `requestAuthentication`
In this PR, introduce a new mtlsChecker, which only checks inbound mtls mode of a proxy, and does not process any jwt rules. more efficient from performance view
> Added mtlsPolicy to be singleton 

- pilot/pkg/model/service.go
- pilot/pkg/model/service_test.go
- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/kube/conversion.go
- pilot/pkg/serviceregistry/kube/conversion_test.go
- releasenotes/notes/svc-external-name.yaml
In 1.17 we filter service events by comparing services(https://github.com/istio/istio/pull/42617). However the comparison does not take ExternalName into account since `model.Service` does not include it. It does matter because ExternalName is used to generate endpoints for DNS clusters.
This bug is breaking Knative
Fixes https://github.com/istio/istio/issues/43440
> Add ExternalName to `model.Service`

- tools/packaging/common/istio-start.sh
- tools/packaging/common/istio.service
`/var/run/secrets` is deleted on reboot but required to restart the service, see #42603
Also `[Serivce].StartLimitInterval` is deprecated and has moved/renamed to `[Unit].StartLimitIntervalSec`
> Create required directory on service start

- pkg/config/mesh/mesh.go
This is currently always set as default in install code but not in Go, unlike the rest
> Move default mesh config value into Go code

- pilot/pkg/networking/grpcgen/grpcgen_test.go
- pilot/pkg/networking/grpcgen/lds.go
For statefulSesion affinithy support a new http-filter was added at the end which violates the condition that the router filter has to be the last filter (see https://github.com/grpc/proposal/blob/master/A39-xds-http-filters.md#http-filter-registry and https://www.envoyproxy.io/docs/envoy/v1.25.1/intro/arch_overview/http/http_filters.html#filter-ordering)
So this PR fixes it by inserting stateful session filter at the beginning (backport of https://github.com/istio/istio/pull/43420)
> grpcgen: make sure router filter is always last: insert statefulSessionAffinity filter at the beginning (backport of #43420)

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- releasenotes/notes/43436.yaml
When creating a `Cluster` object, clone `Push.Mesh.ConnectTimeout` to avoid unintended mutation by `EnvoyFilter`.
Fixes: #43435 
**Additional notes:**
This patch has also effect on  #43383, which becomes no longer reproducible when applied on `Istio 1.14.x` - `Istio 1.17.x`.
I wasn't able to reproduce #43383 on `master`, so I cannot say about effect on it.
> cluster: clone Push.Mesh.ConnectTimeout to avoid unintended mutation by EnvoyFilter

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/testdata/alias.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/delegated.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/eastwest.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/mcs.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/mesh.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/multi-gateway.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/reference-policy-service.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/route-binding.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/route-precedence.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/serviceentry.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/tcp.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/tls.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/weighted.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/zero.status.yaml.golden
- releasenotes/notes/43498.yaml
Gateway API is now testing for the Programmed status on Gateways in conformance tests (since kubernetes-sigs/gateway-api#1732). This PR adds the Programmed Status to Gateways (not just listeners within Gateways) and fixes a couple of other Gateway API [conventions](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io%2fv1beta1.GatewayConditionReason).
> Add Programmed condition to Gateways

- pilot/pkg/model/xds_cache.go
```
name                     old time/op    new time/op    delta
Cache/key-48               7.71µs ± 1%    7.77µs ± 0%   +0.85%  (p=0.001 n=9+8)
Cache/insert-48            3.88ms ± 7%    0.19ms ± 6%  -95.18%  (p=0.000 n=9+10)
Cache/get-48               7.70µs ± 1%    7.86µs ± 2%   +2.03%  (p=0.000 n=9+9)
Cache/insert_and_get-48    3.28ms ± 3%    0.20ms ± 3%  -93.87%  (p=0.000 n=8+10)
name                     old alloc/op   new alloc/op   delta
Cache/key-48                40.0B ± 0%     40.0B ± 0%     ~     (all equal)
Cache/insert-48            95.3kB ± 0%    94.8kB ± 0%   -0.53%  (p=0.000 n=9+9)
Cache/get-48                40.0B ± 0%     40.0B ± 0%     ~     (all equal)
Cache/insert_and_get-48    92.6kB ± 0%    93.1kB ± 0%   +0.50%  (p=0.000 n=9+9)
name                     old allocs/op …
```
> xds cache: skip expensive work when metrics disabled

- security/pkg/pki/ra/k8s_ra_test.go
This PR proposes to add a small delay before the fake client "signs" the cert request.
I don't like it, but is a cheap option to make sure we don't have a race condition in the test, where the update happens [between the list and the watch](https://github.com/istio/istio/blob/master/security/pkg/k8s/chiron/utils.go#L437), and goes undetected; in this case, we need to wait for a full 60 sec before the `certWatchTimeout` expires, to perform a read. This happens randomly, but often enough to be caught on test.
I reckon that the best option would be making `certWatchTimeout` configurable from external packages, so I'm asking @howardjohn to help with the tradeoff.
the fake clientset doesn't actually set `ResourceVersion`, which doesn't help either. …
> added small delay before updating status

- manifests/charts/ztunnel/values.yaml
This could be fixed in release-builder but easier to just do it here. There are some regex replacers in the release that don't like these
> ztunnel chart: remove quotes

- tests/integration/telemetry/envoyfilter/customizemetrics/customize_metrics_test.go
Use a fixed released artifact SHA instead of tracking master.
> wasm: use fixed SHA for attribute gen

- pilot/pkg/xds/endpoint_builder.go
We need to filter before we construct the LB map, otherwise we get a weight of 0 if we filter all endpoints which gets a NACK
fixes https://github.com/istio/istio/issues/43544
> Fix endpoint filtering for ambient

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_logging_test.go
- pilot/pkg/networking/core/v1alpha3/accesslog.go
- pilot/pkg/networking/core/v1alpha3/accesslog_test.go
- releasenotes/notes/43372.yaml
> fix unexpected behavior of multi accesslogging filters

- pilot/pkg/networking/plugin/authn/util.go
- pilot/pkg/networking/plugin/authn/util_test.go
- releasenotes/notes/add_trust_domans_san_validator.yaml
As discussed in https://github.com/istio/istio/issues/41666, if additional federated trust domains are configured via meshConfig's caCertificates, those trustDomains are not passed to the SAN validation, which means that to effectively istio in a multi trustDomain world, one has to either a) use trustDomainAliases or b) completely disable this validation with the PILOT_SKIP_VALIDATE_TRUST_DOMAIN env var. This PR adds those additional trust domains to the SAN verification.
> Include trustDomains from CaCertificates in SAN Validation

- pilot/pkg/model/sidecar.go
- pilot/pkg/model/sidecar_test.go
use local variable instead of struct field for better performance.
benchmark:
```code
$  go test -bench="ConvertIstioListenerToWrapper$" -test.benchmem -count=5 > old.txt # old code
$  go test -bench="ConvertIstioListenerToWrapper$" -test.benchmem -count=5 > new.txt # new code
name                                               old time/op    new time/op    delta
ConvertIstioListenerToWrapper/small-exact-12          752ns ± 3%     614ns ± 0%  -18.32%  (p=0.008 n=5+5)
ConvertIstioListenerToWrapper/small-wildcard-12       780ns ± 9%     611ns ± 0%  -21.60%  (p=0.008 n=5+5)
ConvertIstioListenerToWrapper/small-match-all-12      470ns ± 9%     291ns ± 1%  -38.08%  (p=0.008 n=5+5)
ConvertIstioListenerToWrapper/middle-exact-12        1.70µs ± 4%    1.48µs ± 2%  -12.52% …
```
> optimize convertIstioListenerToWrapper performance

- prow/release-commit.sh
In prow/release-commit.sh, bump release-builder hash to grab https://github.com/istio/release-builder/commit/fc4fd75a62e0021d62b4823d5ed780c581b5493c (which added ztunnel as a release artifact), and adds ztunnel to the manifest with `auto: deps`. This ensures that the ztunnel dependency is listed in the generated manifest.yaml file with the commit hash that is included in the build. Useful for debugging alpha builds to track which ztunnel is included.
> Add ztunnel to dependencies

- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
Make this function more reabable by moving `buildHCMTracing` out of switch case and only build what is necessary in switch case
> make configureFromProviderConfig more readable

- cni/pkg/ambient/net_linux.go
- cni/pkg/ambient/server.go
- cni/pkg/cmd/root.go
Fix for https://github.com/istio/istio/issues/43601
1. Prior to https://github.com/istio/istio/pull/43578, we were doing the exact same cleanup of node-level networking rules in two spots
- Within the CNI ambient watchserver (intended to happen on watchserver termination).
- In the `daemonset` definition itself, as a `preStop` hook
2. https://github.com/istio/istio/pull/43578 removed that preStop hook, and it was noted that the CNI watchserver cleanup wasn't happening on daemonset termination (which could be verified by jumping into the node and checking `ip route/ip rule/ip link show`)
3. This fixes the CNI watchserver cleanup so it actually works on daemonset termination, and actually cleans up node-level rules properly at that point, in …
> CNI uninstall doesn't clean up rules

- samples/bookinfo/src/productpage/productpage.py
- samples/bookinfo/src/reviews/reviews-application/src/main/java/application/rest/LibertyRestEndpoint.java
Ports were hard-coded. This PR adds a default value for the posts and offers the possibility to override it through env vars.
Being the port hardcoded and always the same for all apps implied that a dev could not run more than one of the apps in local. 
> Move ports as envvars

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/deployment/services.go
- pkg/config/analysis/analyzers/testdata/deployment-service-no-selector.yaml
- releasenotes/notes/43652.yaml
Found here: https://github.com/istio/istio/pull/43626#pullrequestreview-1315927487
When there's any service with no selector in a namespace, `DeploymentRequiresServiceAssociated` message won't be reported because the no selector service will match all the deployments which actually have no associated service.
> Fix analyzing not caught some messages in default namespace

- pilot/pkg/model/context.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_waypoint.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- pilot/pkg/xds/endpoint_builder.go
CONNECT termination/origination xDS generation shares resources between waypoints and sidecars, with the same limits (<100 streams per connection) and policy (TLS 1.3, validation).
> connect: consolidate HCM configs

- pilot/pkg/networking/core/v1alpha3/accesslog.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_waypoint.go
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/networking/util/internal_upstream.go
List of changes:
* delete dead or duplicated code;
* report different server name header for waypoints;
* **major**: disable forwarding XFCC, that doesn't work for CONNECT termination;
* **major**: require client certificates for mTLS in CONNECT termination listener.
> connect: delete and consolidate more code

- samples/httpbin/README.md
- samples/httpbin/httpbin.yaml
Most of our images work for both arm64/amd64 linux. 
`httpbin` is frequently used in testing, but upstream (now https://github.com/postmanlabs/httpbin) is infrequently updated and doesn't publish multiarch docker images.
This switches to a drop-in replacement fork (https://github.com/Kong/httpbin) which does nothing but build and publish multiarch `httpbin` images, to avoid `exec format error` when testing with `httpbin` in otherwise-supported linux/arm64 envs.
> samples: use multiarch httpbin image

- cni/pkg/ambient/server.go
We autodetect the iptables command present on the host node, and this requires some init logic.
That init logic was skipped for eBPF ambient mode even though it still requires (minor) iptables config, 
which would result in the CNI DS segfaulting/crashlooping during init with eBPF mode enabled.
> Fix: Initialize iptables helpers for both ambient CNI modes

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_logging_test.go
- pilot/pkg/networking/core/v1alpha3/accesslog.go
- pilot/pkg/networking/core/v1alpha3/accesslog_test.go
Fix a bug introduced in #43372
This configuration did not take effect.
```yaml
accessLogging:
- disabled: true
providers:
- name: envoy
```
> AccessLogging: fix the issue where disable accesslogging does not take effect

- cni/pkg/ambient/net_linux.go
Fix ip rule/route flush hanlder for ebpf redirection mode for case istio-cni restart after ztunnel running.
> Fix ip rule/route flush for ebpf redirection

- istioctl/cmd/proxyconfig.go
- istioctl/cmd/proxyconfig_test.go
Fix https://github.com/istio/istio/issues/43588
```
./out/linux_amd64/istioctl pc log ztunnel-9v7nw.istio-system --level=ztunnel=debug
ztunnel-9v7nw.istio-system:
current log level is ztunnel=debug,info
./out/linux_amd64/istioctl pc log ztunnel-9v7nw.istio-system --level=warning
ztunnel-9v7nw.istio-system:
current log level is ztunnel=debug,warn
./out/linux_amd64/istioctl pc log ztunnel-9v7nw.istio-system --reset
2023-02-27T03:21:44.209092Z	warn	unable to get logLevel from ConfigMap istio-sidecar-injector, using default value "warning" for envoy proxies and "info" for ztunnel
ztunnel-9v7nw.istio-system:
current log level is info
```
> Fix `istioctl pc log` ztunnel pod not working

- go.mod
- go.sum
The pipeline is having some issues, it seem with doing `go get`s with a full commit sha. Need to watch and see if that's a continuing issue (may move to the shortened sha if it is since that seems to still work). In the mean time, here is a manual update for the failing pipeline job.
> Manually update latest client-go and api

- pkg/queue/delay.go
- pkg/queue/instance.go
- pkg/queue/instance_test.go
Split out of https://github.com/istio/istio/pull/43725. This mirrors the queue in controllers package. HasSynced allows a safe mechanism to do a full synco f a controller (see
https://github.com/istio/istio/blob/821a703e4d0f954d363a13297f00debe75bbe778/pkg/kube/controllers/example_test.go#L107 for details).
> pkg/queue: add HasSynced

- istioctl/pkg/writer/compare/sds/util.go
- releasenotes/notes/43765.yaml
Change the output of `istioctl pc secret` to show the cert serial number as hex, instead of a number. Ref: #43765
> change the cert serial number output to hex

- pkg/test/framework/components/istio/cleanup.go
- pkg/test/framework/components/istio/config.go
- pkg/test/framework/components/istio/flags.go
- pkg/test/framework/components/istio/kube.go
- pkg/test/kube/dump.go
- pkg/test/kube/util.go
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/common/traffic.go
- tests/integration/pilot/ingress_test.go
Several integration tests assume that the system namespace is istio-system and that the ingress gateway service name is istio-ingressgateway. Since the integration tests suite can run on pre-existing istio installs (via the kube.deploy flag), the tests should also allow for customizing these fields for a test run.
Part of #43717
> Break system namespace and ingressgateway assumptions 

- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- releasenotes/notes/43858.yaml
Istio 1.17 introduces a change to IP allocation, to make them more stable. If the same hostname is used in multiple namespaces that are created and deleted frequently, like developer "workspaces", IPs are not as stable as they could be. This leads to BlackHoleClusted when DNS in the main application does not detect the new IP quickly.
This update introduces a small helper function makeServiceKey to make
sure the same key is used both places for stable allocation. A
regression test has also been added.
Fixes #43858
> ServiceEntry IP allocation: Stable IP when used in multiple namespaces

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/security/authn/v1beta1/policy_applier.go
Refactor TLS Settings logic
- Rename methods to be generic
- Apply MinTLSVersion when TLSDefaults has value specified in Mesh config
> refactor mesh tls settings

- pilot/pkg/bootstrap/server.go
Currently, "httpServer" of pilot is configured with "ReadTimeout: 30s".
When it is used with the config "multiplexGRPC", gRPC stream connection is disconnected after 30s. 
It is because "ReadTimeout" is a timeout for reading a request body, so gRPC stream is closed by the timeout. 
To avoid this situation, this PR proposes to use "ReadHeaderTimeout" instead of "ReadTimeout" based on the guidance in https://github.com/golang/go/blob/f5c7416511de979433a500735c1617cf03dc46c2/src/net/http/server.go#L2638-L2641
To minimize the impact, "ReadHeaderTimeout" is only used when gRPC multiplexing is used.
Change-Id: I807c886152b57e48a2a7102ad543b70eb9d359d8
> [bugfix] Use ReadHeaderTimeout instead of ReadTimeout when gRPC is multiplexed

- tests/integration/pilot/endpointsmode/endpointslice_test.go
We dropped support for this, endpointslice now requires 1.21
> Drop EndpointSlice test on 1.20

- pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go
- pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go
- releasenotes/notes/43535.yaml
Provision to provide overridden/explicit value for failoverPriority label. 
This provided value is used while assigning priority for endpoints instead of the client's value.
A usecase for this enhancement is discussed in https://github.com/istio/istio/issues/39111
> Provision to provide overridden/explicit value for failoverPriority label

- pkg/test/framework/components/namespace/kube.go
The image pull secret is added to the default service account just after the namespace creation. The service account creation might get delayed. So adding a retry for the patch command.
> [TF] add retry to default service account patch command

- cni/pkg/plugin/iptables.go
- cni/pkg/plugin/iptables_linux.go
- cni/pkg/plugin/plugin_dryrun_test.go
- releasenotes/notes/43945.yaml
- tools/istio-clean-iptables/pkg/cmd/cleanup.go
- tools/istio-clean-iptables/pkg/cmd/cleanup_test.go
- tools/istio-iptables/pkg/capture/run.go
- tools/istio-iptables/pkg/capture/run_linux.go
- tools/istio-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/config/config.go
- tools/istio-iptables/pkg/constants/constants.go
- tools/istio-iptables/pkg/dependencies/implementation.go
- tools/istio-iptables/pkg/dependencies/implementation_linux.go
- tools/istio-iptables/pkg/dependencies/interface.go
- tools/istio-iptables/pkg/dependencies/stub.go
This fixes the SELinux issue on RHEL9 where iptables-restore isn't allowed to open files in /tmp.
Fixes #42485
> Pass rules to iptables-restore via stdin instead of a file

- samples/helloworld/src/Dockerfile
The current helloworld app images are 6 years old. The previous base image is old and was throwing a lot of errors so I am updating the python base image.
The reason for this update so that helloworld sample app can work with IPv6 and dual stack. Currently all our multi-cluster verification is based on helloworld sample app and it doesn't work in IPv6/dual stack environment.
I build the images and tested these images in both IPv4 and IPv6 environment. The images are available in my repo. I wasn't sure about what tags to use so I am using latest tag.
abasitt/examples-helloworld-v1:latest
abasitt/examples-helloworld-v2:latest
This will fix the issue [here ](https://github.com/istio/istio/issues/42855)
**To help us figure out who should review this PR, please put an X in all the areas that …
> Updating the sample helloworld python base image

- samples/bookinfo/src/productpage/requirements.txt
There are 1 security vulnerabilities found in tornado 4.5.3
- [CVE-2018-1000518](https://www.oscs1024.com/hd/CVE-2018-1000518)
Upgrade tornado from 4.5.3 to 5.1 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade tornado to 5.1

- samples/bookinfo/src/productpage/productpage.py
- samples/bookinfo/src/reviews/reviews-application/src/main/java/application/rest/LibertyRestEndpoint.java
The previous PR introduced an issue.
The env vars (i.e. DETAILS_PORT) is used by kubernetes. It was needed to use different env var to make it work in kubernetes with default port.
Below the env vars when deploying productpage on kubernetes. Notice that `DETAILS_PORT` is populated already by kubernetes. This is due to [this](https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables). Easiest solution is to change the name for the envvar.
```
I have no name!@productpage-v1-5fcf6f85b-88c8f:/opt/microservices$ env | grep -i details_port
DETAILS_PORT_9080_TCP_PORT=9080
DETAILS_PORT=tcp://10.1.76.19:9080
DETAILS_PORT_9080_TCP_PROTO=tcp
DETAILS_PORT_9080_TCP=tcp://10.1.76.19:9080
DETAILS_PORT_9080_TCP_ADDR=10.1.76.19
```
> fix env vars since they collide with kubernetes

- pkg/wasm/convert.go
Istiod places some `ISTIO_META` env vars to be consumed by agent.  We do not clean them all.
This PR cleans them all and additionally minor refactor (complex if..else to switch) for better readability
> remove ISTIO_META env vars from wasm

- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/config/kube/ingress/status.go
- pilot/pkg/config/kube/ingress/status_test.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pkg/kube/util.go
This adds missing filters that only applied to the status controller but not even the main controller. In particular, this fixes an assertion error where we do not properly filter Pods globally (https://prow.istio.io/view/gs/istio-prow/logs/integ-assertion_istio_postsubmit/1636591136808112128)
> Properly respect discovery filter in ingress status controller

- pilot/pkg/autoregistration/controller.go
- releasenotes/notes/43951.yaml
fixes https://github.com/istio/istio/issues/43950
Could also use the `autoregisteredWorkloadEntryName` with less validation. 
This keys the resource to be cleaned up as well as the input. 
If there were already multiple same network/IP workloadentries, that's it's own problem. This just keeps it from being worse with stuck resources.
> fix cleaning up workloadentry with same ip and network

- samples/extauthz/local-ext-authz.yaml
- samples/httpbin/httpbin-nodeport.yaml
- samples/httpbin/httpbin-vault.yaml
This is a minor followon/tidy to https://github.com/istio/istio/pull/43759
I somehow missed that we have `httpbin` image refs in a few other samples. Fix those too.
> Followup/minor tidy on #43759 - forgot some image refs

- pilot/pkg/security/authz/builder/extauthz.go
- pilot/pkg/security/authz/builder/testdata/http/custom-http-provider-out2.yaml
The old field is deprecated in https://github.com/envoyproxy/envoy/pull/22877. The new field maintains the same behavior as the old one.
Verified it is working as expected.
> Revise IncludeRequestHeadersInCheck to use new envoy allowed_headers field

- manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
- manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
- manifests/charts/istiod-remote/files/gateway-injection-template.yaml
- pkg/kube/inject/testdata/inputs/custom-template.yaml.34.template.gen.yaml
- pkg/kube/inject/testdata/inputs/default.template.gen.yaml
- pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
- pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
- pkg/kube/inject/testdata/inputs/merge-probers.yaml.38.template.gen.yaml
- pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
- pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
- releasenotes/notes/33237.yaml
This is a follow-up to #43433, but this is not a cherry-pick, because in that PR I removed `istio.io/rev` from gateway injection template, and I think we shouldn't remove labels in patch releases.
> [release-1.17] Fix gateway injection when istio.io/rev=<tag>

- prow/integ-suite-kind.sh
`ISTIO_DOCKER_BUILDER` can be set to crane or docker but it currently is hardcoded.
> Crane env var

- tests/integration/security/authz_test.go
- tests/integration/security/jwt_test.go
- tests/integration/security/normalization_test.go
- tests/integration/security/pass_through_filter_chain_test.go
This PR moves securiyt tests to use sequential mode instead of parallel. This seems to have no impact on test runtime:
Security MC test run, 4 attempts:
This PR: 46m,38m,37m,33m
Master: 37m,39m,45m,44m
(lots of noise)
This seems to reduce the likelihood that we hit https://github.com/envoyproxy/envoy/issues/22583 which should reduce flakiness while we debug it.
> Run test sequentially

- pilot/pkg/autoregistration/controller.go
- pilot/pkg/xds/vm_test.go
- releasenotes/notes/vm-label.yaml
https://github.com/istio/istio/commit/1b214cea711412973d49aa759aef3ac626017894 introduces a regression, as we changed from computingl labels from proxy.Metadata.Labels to proxy.Labels. This works for all parts of the code *except* the auto registration, which happens before we compute proxy.Labels.
This reverts to using the metadata labels and adds a test
> vm: fix assigning label from metadata

- pilot/docker/Dockerfile.proxyv2
- pilot/docker/Dockerfile.ztunnel
Convert ztunnel Dockerfile base registry to ISTIO_BASE_REGISTRY ARG.
And add the same one in at the proxyv2.
- Test and Release
- Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
> Convert ztunnel Dockerfile registry to ARG

- pilot/pkg/config/kube/gateway/conditions.go
- pilot/pkg/config/kube/gateway/conditions_test.go
- pilot/pkg/model/kstatus/helper.go
- pilot/pkg/model/kstatus/helper_test.go
We should not always set `LastTransitionTime` to now because it
- unnessarily refreshes all routes' status to the api server when one service/route/gateway is updated. These status updates can trigger reconciliation again and we will end up with an infinite loop. In practice this process is usually fast enough that `LastTransitionTime` still keeps the same(the protobuf is accurate to a second IIRC) and breaks the loop, but it's still problematic and leads to pushing xDS at least 2x
- does not conform the API semantics anyways
ref: https://github.com/kubernetes/kubernetes/blob/v1.26.3/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/helpers.go#L38-L39
> gateway-api: set LastTransitionTime properly

- pkg/wasm/convert.go
This specific delete is not needed. Below we are deleting all ISTIO_META keys
> remove unnecessary delete

- pkg/config/schema/codegen/collections.go
- pkg/config/schema/kubeclient/resources.gen.go
- pkg/kube/kclient/clienttest/test_helpers.go
Use concrete struct when we don't need an interface to reduce duplication. Fix a few of the generated code for some types that we do not yet use (but would be broken if we tried)
> kclient: various improvements

- pilot/pkg/model/push_context.go
- pkg/spiffe/spiffe.go
- pkg/spiffe/spiffe_test.go
For service entries, SANs may not be in SPIFFE format. So skip validating them
> skip non spiffee uris for trust domain expansion

- pilot/pkg/config/kube/gateway/controller_test.go
- pilot/pkg/model/network_test.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/kube/controller/fake.go
- pilot/pkg/serviceregistry/kube/controller/pod_test.go
- pilot/pkg/serviceregistry/kube/controller/serviceexportcache_test.go
- pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- pilot/pkg/serviceregistry/util/xdsfake/updater.go
- pilot/pkg/xds/fake.go
Today we have 3 xds updaters, which do the same thing, but each one does some things poorly. Instead, just use a single one that does things the "right" way
> controllers: unify xds updater

- samples/bookinfo/gateway-api/route-reviews-90-10.yaml
Adds sample manifest for Gateway API weight-based routing for the bookinfo reviews v1/v2 service.
In support of https://github.com/istio/istio.io/issues/12803.
> Adds Gateway API Weighted Routing Bookinfo Example

- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- pilot/pkg/xds/fake.go
We have two endpoint models - incremental updates and InstancesByPort. This adds a check that the two are in sync.
In doing so, it fixes a few bugs:
* ServiceEntry didn't copy HealthStatus properly
* EndpointSlice could return duplicate addresses
> controller: assert EDS event consistency

- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
This tests the performance of the EnvoyFilter in the helm chart. This could stillbe tested today, but its a lot harder since we need to generate the chart, as the default generated yaml no longer includes them. Since we expect most users to not have them anymore, remove the benchmark entirely instead of dealing with the major complexity required to fix up the benchmark
> bench: drop obsolete test

- cni/pkg/ambient/server.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/util.go
- Directly list pods by the label selector
- `ValidatedSetSelector` is more efficient than `SelectorFromValidatedSet`
> ambient: use ValidatedSetSelector

- Makefile.overrides.mk
- common/config/.golangci.yml
- tools/commonfiles-postprocess.sh
- tools/golangci-override.yaml
This is part of this, rest is in common-files. Basically, move per-repo settings into the repo. This allows us to expand our checks more aggresively where they don't make sense outside the repo.
This is done by overriding the actual stored file which is a bit more managageble than overriding it on the fly since golangci-lint doesn't support config from stdin.
> lint: allow repo specific configs

- istioctl/cmd/dashboard.go
- releasenotes/notes/dashboard-custom-port.yaml
Allow users to specify component ports.
And also fix default skywalking port.
> Add port flags to different dashboard cmds

- pilot/pkg/serviceregistry/serviceregistry_test.go
- pilot/pkg/xds/fake.go
Fix issue https://github.com/istio/istio/issues/44107.
The svc `outbound|80||service.namespace.svc.cluster.local` has already been delete in last check. If we check again, it will return from `UntilSuccessOrFail` immediately and cause that the update of eds happens at the same time as checking the eds shard.
> Fix unit test expectEndpoints potential issue

- pilot/pkg/model/envoyfilter.go
- pilot/pkg/model/envoyfilter_test.go
The `IncrementEnvoyFilterMetric` function repeatedly calls `EnvoyFilterConfigPatchWrapper.Key()`, and each call needs to concatenate the string.
When there are a large number of envoyfilters, even if the envoyfilter metric is not enabled, a lot of cpu will be consumed. This PR adds a field named `FullName` to store the results of pre-computation, which is used to reduce cpu consumption, at the cost of adding very little memory.
before:
after:
> reduce cpu consumption when calculating envoyfilter metric name

- pkg/test/framework/components/istio/config.go
- pkg/test/framework/components/istio/flags.go
- pkg/test/framework/components/istio/kube.go
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/istioctl_test.go
- tests/integration/pilot/testdata/authz-b.yaml
- tests/integration/security/authz_test.go
- tests/integration/security/jwt_test.go
- tests/integration/security/main_test.go
- tests/integration/security/sds_ingress/ingress_test.go
- tests/integration/security/sds_ingress/util/util.go
- tests/integration/security/testdata/authz/ingress-gateway.yaml.tmpl
- tests/integration/security/testdata/authz/not-host.yaml.tmpl
- tests/integration/security/testdata/requestauthn/global-jwt.yaml.tmpl
- tests/integration/security/testdata/requestauthn/ingress.yaml.tmpl
The Istio E2E tests still assume a lot about a pre-existing environment when running integration tests, specifically around the ingress gateway deployments. This PR allows the test runner to change the expected namespace and labels during the e2e tests
Similar to #43809
> Add more flexibility for running E2E tests

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
- pilot/pkg/config/kube/gateway/testdata/deployment/cluster-ip.yaml
- pilot/pkg/config/kube/gateway/testdata/deployment/manual-ip.yaml
- pilot/pkg/config/kube/gateway/testdata/deployment/manual-sa.yaml
- pilot/pkg/config/kube/gateway/testdata/deployment/multinetwork.yaml
- pilot/pkg/config/kube/gateway/testdata/deployment/simple.yaml
- pilot/pkg/config/kube/gateway/testdata/deployment/waypoint.yaml
- pkg/test/util/assert/assert.go
For https://github.com/istio/istio/issues/44164
This is the master version; we will backport similar changes to older branches.
This introduces a mechanism to tell older versions to stop managing a Gateway.
How this works:
* 1.17 controls all Gateways. Users will upgrade to a patched version (basically this PR backported) which annotates all Gateways with version=1. It also has logic to not control Gateways with version>1
* User installs 1.18 as canary revision. Any Gateways in canary revision will get version=2 set; at this point, the 1.17 controller will stop trying to manage it. Warning: if a user needs to remove 1.18 at this point, they would need to manual set the version label back to 1. This is not ideal, but it is the best we can do I think.
* User makes 1.18 the "default …
> gateway deployment controller: handle backwards compatibility

- pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
Add mexRetries in namespace Controller to avoid the following problems:
```
2023-03-30T07:01:03.836412Z	info	ads	XDS: Pushing:2023-03-30T07:01:03Z/1 Services:5 ConnectedEndpoints:0 Version:2023-03-30T07:01:03Z/1
2023-03-30T07:01:03.849081Z	info	ads	All caches have been synced up in 594.470143ms, marking server ready
2023-03-30T07:01:03.849196Z	info	starting secure gRPC discovery service at [::]:15012
2023-03-30T07:01:03.849237Z	info	starting webhook service at [::]:15017
2023-03-30T07:01:03.849196Z	info	starting gRPC discovery service at [::]:15010
2023-03-30T07:01:03.922389Z	info	controllers	starting	controller=namespace controller
2023-03-30T07:01:03.941166Z	error	controllers	error handling istio-system/istio-ca-root-cert, and retry budget …
```
> Add mexRetries in namespace Controller

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
- pilot/pkg/config/kube/gateway/testdata/deployment/cluster-ip.yaml
- pilot/pkg/config/kube/gateway/testdata/deployment/manual-ip.yaml
- pilot/pkg/config/kube/gateway/testdata/deployment/manual-sa.yaml
- pilot/pkg/config/kube/gateway/testdata/deployment/multinetwork.yaml
- pilot/pkg/config/kube/gateway/testdata/deployment/simple.yaml
- pkg/test/util/assert/assert.go
- releasenotes/notes/gateway-futureproof.yaml
This introduces a mechanism to tell older versions to stop managing a Gateway.
How this works:
1.17 controls all Gateways. Users will upgrade to a patched version (basically this PR backported) which annotates all Gateways with version=1. It also has logic to not control Gateways with version>1
User installs 1.18 as canary revision. Any Gateways in canary revision will get version=2 set; at this point, the 1.17 controller will stop trying to manage it. Warning: if a user needs to remove 1.18 at this point, they would need to manual set the version label back to 1. This is not ideal, but it is the best we can do I think.
User makes 1.18 the "default revision". At this point it does the same as above, but to a wider set of gateways.
Eventually, if we somehow run into the same circumstance, …
> [1.17] gateway deployment controller: handle backwards compatibility

- istioctl/pkg/writer/ztunnel/configdump/configdump.go
- istioctl/pkg/writer/ztunnel/configdump/testdata/dump.json
- istioctl/pkg/writer/ztunnel/configdump/testdata/secretsummary.txt
The summary of the secret dump will be difficult to read when the `Unavailable` state contains long messages. The message may be useful for other formats, so I have truncated it only in the summary.
/cc @GregHanson
> Fix ztunnel secret state in configdump

- pilot/pkg/autoregistration/controller.go
- pilot/pkg/autoregistration/controller_test.go
This PR speeds up `TestAutoregistrationLifecycle` (contributes to #37555 ), reducing `WorkloadEntryCleanupGracePeriod` from 200 milliseconds to 25 milliseconds.
stress tests also were executed and reliable 100% success was observed
> Speed up autoregistration lifecycle test

- istio.deps
This is a big change, so important to get in testing/ for 1.18
> Bump ztunnel to hyper 1.0.0

- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/util.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/util.go
- pilot/pkg/serviceregistry/util/workloadinstances/selector.go
- pkg/config/labels/instance.go
- pkg/config/labels/instance_test.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/44159.yaml
In the following code snippet, se.WorkloadSelector != nil, but se.Selector.WorkloadSelector is nil or an empty map, the se will select all workload instance.
https://github.com/istio/istio/blob/4157e1887071037b369fd82cb4559dc7628bb57b/pilot/pkg/serviceregistry/serviceentry/controller.go#L513-L521
However, in normal logic, any WorkloadInstance and Endpoint should not be selected when se's selector is empty.
> Fixes selector logic of service and endpoint

- pilot/cmd/pilot-agent/status/server.go
- pilot/cmd/pilot-agent/status/server_test.go
This is a regression of https://github.com/istio/istio/issues/28466 from https://github.com/istio/istio/pull/31866
The 31866 fixed the k8s spec having duplicates, but we end up duplicating all headers twice - the kubelet adds the header from HTTPHeaders and we also add from HTTPHeaders, resulting in 2x every header.
Instead, we simply copy the incoming request headers and host, making us a fairly transparent proxy.
cc @Monkeyanator @wzshiming
> kube-probe: avoid duplicate probe headers

- pilot/pkg/bootstrap/servicecontroller.go
- pilot/pkg/model/network.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/fake.go
- pilot/pkg/serviceregistry/kube/controller/network.go
- pilot/pkg/xds/debug.go
- pkg/config/mesh/networks_watcher.go
Actually it does:
1. remove duplicate handler for meshnetwork change
2. move service registry gateway network handling into controller/network.go
3. rename some structs
> Refactor multi network manage

- pkg/test/framework/components/echo/common/deployment/namespace.go
- pkg/test/framework/components/istio/eastwest.go
- pkg/test/framework/features/features.yaml
- pkg/test/framework/resource/settings.go
- tests/integration/pilot/multiple_cp/main_test.go
- tests/integration/pilot/multiplecontrolplanes/main_test.go
- setup multiple control planes in single cluster with revisions, discoverySelectors and ENABLE_ENHANCED_RESOURCE_SCOPING feature flag
- Add tests to verify traffic isolation
- Add tests to verify CR scoping
> Integration tests for ENABLE_ENHANCED_RESOURCE_SCOPING feature

- istioctl/pkg/multicluster/remote_secret_test.go
This PR reduces `TestCreateRemoteSecrets` execution from 5sec to 0.07sec by changing `tokenWaitBackoff` from 1s to 10millis for the duration of the test.
Contributes to #37555
> reduced tokenWaitBackoff from 1 second to 10 millis

- prow/release-commit.sh
Redo of #44347 due to incorrect committer email address making CLA check fail
> update_deps.sh prior to release-1.18 branch cut

- pilot/pkg/features/pilot.go
- pkg/kube/client.go
- pkg/kube/util.go
This was attempted in #38658 but the `config` set is never used there.
Also add an opt-out and AcceptContentTypes to allow json fallback as recommended by k8s
In a 40k pod cluster this reduced Istiod memory by 50%
> kube: use protobuf in client

- CODEOWNERS
Fixes https://github.com/istio/istio/issues/44378
Remove the requirement for release managers to approval relate notes within a PR. The release notes will be edited at release time.
> Remove release note approval by release-managers

- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
- releasenotes/notes/44388.yaml
This PR prevents duplicate `istio_authn` network filter in the filter chain.
Fixes: #44385
> gateway: prevent duplicate `istio_authn` network filter in the filter chain

- prow/integ-suite-kind.sh
Test on k8s 1.27.0 as the default node image
> Use k8s 1.27.0 as the default node image for integration testing

- pilot/pkg/serviceregistry/serviceentry/conversion.go
When the label is empty, we should set the workloadselector of SE to nil.
Related to https://github.com/istio/istio/pull/44159#issuecomment-1489589957
cc @howardjohn
> Set the WorkloadSelector of ServiceEntry only if the label is not empty

- cni/pkg/ambient/iptables.go
When the CNI initially runs on a node that is
clean of the ztunnel chains errors and warnings
are logged that are extraneous. This change reduces the severity and adds comments in the code.
> Temper severity of extraneous errors

- pkg/config/analysis/msg/messages.gen.go
- pkg/config/analysis/msg/messages.yaml
The link is unnecessary to be recorded, it will be auto-generated in the analyze.
The message `IstioProxyImageMismatch ` has been replaced by `PodsIstioProxyImageMismatchInNamespace `
> Cleanup message.yaml

- istioctl/cmd/istiodconfig.go
The `-r` parameter is used to specify the revision, and `--reset` should be used here.
> fix wrong example for admin log

- pkg/config/validation/validation_test.go
- pkg/config/validation/virtualservice.go
- pkg/config/validation/virtualservice_test.go
- releasenotes/notes/44424.yaml
Adds validation for empty prefix header match. This fails silently when VS is applied, and the istioctl validate doesn't catch the issue either. 
Fixes: https://github.com/istio/istio/issues/44424
> add validation for empty prefix header match

- .github/ISSUE_TEMPLATE/bug_report.yml
According to https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#attributes-1 and https://github.com/github/linguist/blob/master/lib/linguist/languages.yml
`prose` is not a valid render type.
> Fix error render type in bug-report issue form

- pkg/test/framework/components/echo/common/deployment/echos.go
Testing multiple istio versions involves older istio versions which doesn't support sidecars with disable automount SA token. This was enabled form 1.16 onwards.
> disable automount SA token only on tests with min istio revisions >= 1.16

- istioctl/cmd/proxyconfig.go
The activeLoggers slice has not been maintained for a while, and it's hard to maintain manually. Many logger components are missing. Revised to use command or see the logger page like Envoy doc does in the tip (https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/run-envoy#debugging-envoy). Are there any other suggestions?
> Fix `pc log -h` listed active loggers out of date

- tests/integration/pilot/gw_topology_test.go
- tests/integration/pilot/ingress_test.go
TestXFFGateway sets the image to auto which will cause the sidecar injector to automatically select the image to use, but in the current implementation, the sidecar injection is getting disabled for the compatibility tests
This PR sets inject to true for compatibility tests as the namespace creation implementation have a special condition for the compatibility tests which disables injection at the namespace (when inject is false), which ignores object selectors.
https://github.com/istio/istio/blob/master/pkg/test/framework/components/namespace/kube.go#L294
Made the similar fix for TestCustomGateway and TestProxyProtocolTCPGateway
> Set inject true for compatibility tests

- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- releasenotes/notes/drop-legacy-lb-flag.yaml
This has been around for 1 year and was added for backwards compat opt-out; time to remove
> Cleanup legacy ENABLE_LEGACY_LB_ALGORITHM_DEFAULT flag

- tests/integration/telemetry/stackdriver/stackdriver_filter_audit_test.go
For https://github.com/istio/istio/issues/44503.
From the logs, as far as I can tell we are sending the right audit logs. So might just be taking a bit longer than expected... Will see if this clears things up
> Attempt to deflake audit log tests

- tests/integration/telemetry/api/accesslogs_test.go
https://prow.istio.io/view/gs/istio-prow/pr-logs/directory/integ-telemetry_istio/1652008195079540736
It looks like the XDS push is just causing too much load and it takes more than 10s to process. We see during XDS push /stats/prometheus also times out.
> telemetry: deflake access log tests

- samples/bookinfo/platform/kube/bookinfo-details-dualstack.yaml
- samples/bookinfo/platform/kube/bookinfo-dualstack.yaml
- samples/bookinfo/platform/kube/bookinfo-ratings-discovery-dualstack.yaml
- samples/bookinfo/platform/kube/bookinfo-ratings-dualstack.yaml
Add yaml files for users to deploy of bookinfo running in dual-stack mode
This requires a dual stack k8s cluster and also for Istio to be configure in dual-stack mode. There will be changes to documentation later to support this.
Productpage: IPv4 first, IPv6
Details: IPv6 first, IPv4
Reviews: IPv4 first, IPv6
Ratings: IPv6 first, IPv4
This was tested and is known to work
> Setup bookinfo in dual-stack mode

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/grpcgen/cds.go
Without it envoy will drop the draining endpoints and scale down will break.
Istiod does generate the DRAINING endpoints - and proxyless gRPC can use them, but in
envoy they don't show up in the EDS. This per-cluster flag allows them to be held - they will
not show up as DRAINING but as UNHEALTHY ( called 'coarse state' in envoy, quite confusing ).
> Fix persistent sessions scale down with envoy

- pilot/pkg/features/pilot.go
> Remove deadcode ISTIO_METADATA_DISCOVERY flag

- pilot/pkg/config/aggregate/config.go
This is just appending them, there is no guarantee of conflicts being avoided
Fixes https://github.com/istio/istio/issues/44520
(cherry picked from commit 3b7ca81a32ee6d091b9a1779736e5484ea65b4e4)
> [1.17] Use safer dedupe for config (#44502)

- pilot/pkg/config/kube/crdclient/client.go
When a new secret is added, a watcher will be created based on the remote secret. The process can fail if the API server doesn't respond in 10 seconds which can be the case if the cluster contains a lot of CRDs. This PR bumps the timeout to 60 seconds which is the default timeout value (specified in --request-timeout) for requests to API server.
> Fix multi-cluster issue by increasing the timeout of listing CRDs

- pilot/pkg/networking/core/v1alpha3/listener.go
This is by default to true in Envoy. So we can remove this
> remove enable reuse port for quic

- Makefile.core.mk
- istioctl/cmd/authz.go
- istioctl/cmd/checkinject.go
- istioctl/cmd/dashboard.go
- istioctl/cmd/kubectl_factory.go
- istioctl/cmd/mock_test.go
- istioctl/cmd/proxyconfig.go
- istioctl/cmd/proxystatus.go
- pkg/kube/client.go
- pkg/kube/client_factory.go
- tests/binary/binaries_test.go
Trims 10mb off the istiod binary by removing kubectl dependency.
Also update the binary test to "lock in" the improvement.
> Refactor kube pkg a bit to drop binary sizes

- pkg/test/kube/dump.go
* Remove "logs:" when its not logs
* Always emit "Crashed" when it restarts, so we can just grep "Crashed"
> tf: minor improvements to test logs

- pilot/pkg/serviceregistry/kube/controller/multicluster.go
Currently when we get namespace failed, we may enter a bad state, that istiod wrongly lead remote clusters
> Improve resilience for bootstrap

- pkg/bootstrap/testdata/all_golden.json
- pkg/bootstrap/testdata/auth_golden.json
- pkg/bootstrap/testdata/authsds_golden.json
- pkg/bootstrap/testdata/default_golden.json
- pkg/bootstrap/testdata/metrics_no_statsd_golden.json
- pkg/bootstrap/testdata/running_golden.json
- pkg/bootstrap/testdata/runningsds_golden.json
- pkg/bootstrap/testdata/stats_inclusion_golden.json
- pkg/bootstrap/testdata/tracing_datadog_golden.json
- pkg/bootstrap/testdata/tracing_lightstep_golden.json
- pkg/bootstrap/testdata/tracing_none_golden.json
- pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
- pkg/bootstrap/testdata/tracing_stackdriver_golden.json
- pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
- pkg/bootstrap/testdata/tracing_tls_golden.json
- pkg/bootstrap/testdata/tracing_zipkin_golden.json
- pkg/bootstrap/testdata/xdsproxy_golden.json
- tools/packaging/common/envoy_bootstrap.json
This fixes an issue when running with an old (1.14) sidecar:
```
critical    envoy main    error initializing configuration 'etc/istio/proxy/envoy-rev.json': Tag name 'response_code' specified twice.
```
It mixes the two regular expressions into one to avoid the error. A [different approach was merged in master](https://github.com/istio/istio/pull/44154), but it's not compatible with 1.16.
Related issue: https://github.com/istio/istio/issues/42716
> [release-1.16] Fix duplicate response_code entry in envoy_bootstrap.json

- istioctl/cmd/analyze_test.go
- istioctl/cmd/testdata/analyze-file/public-gateway.yaml
- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/local/istiod_analyze.go
- pkg/config/legacy/util/kuberesource/resources.go
- releasenotes/notes/44506.yaml
- tests/integration/pilot/analyze_test.go
Cherry-Pick of #44506
Fixes #44662 
* Skip runtime resources when analyzing files
* add test data and fmt
* add support for tests to analyze pods
* update analyze test to respect file exclusions
* show failed json in message
* fix json formatting
* differentiate json analyzer tests
> [Cherry-Pick] Skip runtime resources when analyzing files 

- manifests/charts/istio-control/istio-discovery/templates/role.yaml
- manifests/charts/istiod-remote/templates/role.yaml
- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/leaderelection/leaderelection.go
This is needed in 1.18 to avoid a regression in 1.18; this is new code in 1.18.
* Add per-revision leader election
* Add leader election for deployment controller
(cherry picked from commit acd30f96ef24f8bfc0cdd72a996ee90c27cea8d5)
Fixes https://github.com/istio/istio/issues/44763
> [1.18] deployment controller: add leaderelection back (#44746)

- istioctl/pkg/writer/envoy/configdump/listener.go
- istioctl/pkg/writer/envoy/configdump/listener_test.go
- releasenotes/notes/istioctl-additional-address.yaml
Support for dual-stack listeners.
Add `ADDITIONAL ADDRESSES` column and support additional listeners in `--address` flag.
```bash
$ ./out/linux_amd64/istioctl pc listeners sleep-645b966fc4-w2xgk  --address "::"                                                                                                                                            130 ↵
ADDRESS PORT  ADDITIONAL ADDRESSES MATCH                                                                                           DESTINATION
0.0.0.0 80    ::                   Trans: raw_buffer; App: http/1.1,h2c                                                            Route: 80
0.0.0.0 80    ::                   ALL …
```
> Support additional address in listeners output

- cni/pkg/ambient/informers.go
As mentioned in https://github.com/istio/istio/issues/44762, spurious eventdeletes are fired for ztunnels during namespace reconciliation - this is incorrect (ztunnel pods are never "removed from the mesh"), functionally harmless, but confusing, and causes ztunnel reconciliation to (potentially) trigger more often than it should, which isn't ideal.
> Don't fire mesh removal events for ztunnel (#44762)

- pkg/config/analysis/incluster/controller.go
This aligns with the `istioctl analyze` behavior. We don't want all schemas, only ones used by analyzers.
In particular we are getting CertificateSigningRequest today which is not desired.
> Fix analysis schemas

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
The variable name is inconsistent with the comment "L7 policies ...", so I think the variable name should be `l4` not `l7`.
> fix variable name

- pilot/pkg/model/push_context.go
This PR contains 2 commits, both for optimizing slice growth:
- commit 1: Calculate the capacity in two cases, and then use `make` to allocate at one time
- commit 2: Use two for loops instead of splitting into "sidecarConfigWithSelector" and "sidecarConfigWithoutSelector" and then merging. In this way, slice growth and GC consumption during splitting are omitted
> optimize slice growth

- pilot/cmd/pilot-agent/app/cmd.go
- releasenotes/notes/44777.yaml
This PR helps to provide an option to scenarios/issues such as #41271 where the user can choose to exclude interfaces handled by proxy in a pod with multiple interfaces. The current behaviour fails to start the pilot-agent where ipv6 is expected to be primary but ipv4 is selected instead by proxy as primary.
Excludeinterfaces option via annotations is available for istio-iptables. So, added workflow in pilot-agent startup to handle excluded interfaces.
cc: @abasitt (reporter of the issue)
> Add excludeInterfaces support in pilot-agent (#41271)

- pilot/pkg/model/network_test.go
In this test we want to check the condition after 30ms in 60ms(timeout). It should use fixed delay instead of 2x backoff(default)
```
Before:
check -> 10ms -> check -> 20ms -> check(flaky) -> timeout
After:
check -> 10ms -> check -> 10ms -> check -> 10ms -> check(flaky) -> 3 more retries(should succeed)
```
For https://github.com/istio/istio/issues/44776
> tf: set fixed delay between retry attempts

- pilot/pkg/bootstrap/server.go
- pilot/pkg/bootstrap/validation.go
- pilot/pkg/config/kube/crd/conversion.go
- pilot/pkg/config/kube/crdclient/client.go
- pilot/pkg/config/kube/crdclient/client_test.go
- pilot/pkg/config/kube/gateway/conversion_test.go
- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/v1alpha3/fake.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
- pilot/pkg/xds/fake.go
- pkg/config/schema/codegen/collections.go
- pkg/config/schema/collections/collections.agent.gen.go
- pkg/config/schema/collections/collections.gen.go
- pkg/config/schema/collections/extras.go
- releasenotes/notes/drop-gateway-alpha.yaml
- tests/integration/base.yaml
This is problematic because most providers will not install Alpha CRDs. So once these promote to Beta, clusters will have *only* beta version in the CRD. We would detect the CRD and attempt to watch, but fail as alpha does not exist.
This makes the alpha enablement an explicit opt-in to avoid this.
An alternative could be to read the actual CRD to check it has the version we want. However, this is not safe -- a user may silently stop reading critical configurations.
This is not needed for Istio CRDs as we don't remove old versions.
> istiod: drop Alpha Gateway API types by default

- cni/pkg/ambient/informers.go
- cni/pkg/ambient/net.go
Each time a pod is deleted, istio-cni reports an error:
```
failed to annotate pod unenrollment: pods "xxx" not found
```
We should not annotate the pod if it no longer exists
> ambient: don't annotate pods on delete

- prow/config/ambient-sc.yaml
- prow/config/default.yaml
I don't know why it fails hard in some case and works in others, but the current config is invalid so it makes sense to make it valid
> kind: fix cluster config

- pkg/spiffe/spiffe.go
- pkg/spiffe/spiffe_test.go
- releasenotes/notes/spiffe-bundle-multiple-certs.yaml
In the existing implementation, we were overriding the `cert` while iterating over doc.Keys. This commit fixes that.
Further, there was an unnecessary check for the existence of `ret[trustDomain]`. We are iterating over a map with `trustDomain` as keys, maps don't have duplicate keys, and so `ret[trustDomain]` would never have had a key before we set it in this iteration.
> spiffe: fix handling of trust bundles with multiple keys

- istioctl/pkg/writer/envoy/configdump/cluster.go
- istioctl/pkg/writer/envoy/configdump/endpoint.go
- istioctl/pkg/writer/envoy/configdump/listener.go
- istioctl/pkg/writer/envoy/configdump/route.go
Replace package alias 'protio' with package name 'proto'.
**AS-IS**
```go
import (
protio "istio.io/istio/istioctl/pkg/util/proto"
)
filteredClusters := make(protio.MessageSlice, 0, len(clusters))
```
**TO-BE**
```go
import (
"istio.io/istio/istioctl/pkg/util/proto"
)
filteredClusters := make(proto.MessageSlice, 0, len(clusters))
```
> istioctl: Replace package alias 'protio' with package name 'proto'

- Makefile.core.mk
- pkg/test/echo/server/endpoint/grpc.go
- pkg/test/echo/server/endpoint/grpcbootstrap.go
- tests/binary/binaries_test.go
This cuts about 20mb off the binary. There was some concern from k8s folks, who are now using this in gateway-api, about bloat.
> echo: trim dependencies

- pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch_test.go
keep [`cloneVhostRouteByRouteIndex`](https://github.com/istio/istio/pull/40986) when patch http_route, also see https://github.com/istio/istio/pull/44823#discussion_r1190077374
> envoyfilter: reduce unnecessary deepcopy when patching to single http_route

- cni/pkg/cmd/root.go
- cni/pkg/config/config.go
- cni/pkg/constants/constants.go
- cni/pkg/install/binaries.go
- cni/pkg/install/binaries_test.go
- cni/pkg/install/cniconfig.go
- cni/pkg/install/cniconfig_test.go
- cni/pkg/install/install.go
- cni/pkg/install/install_test.go
- cni/pkg/install/kubeconfig.go
- cni/pkg/install/kubeconfig_test.go
- cni/pkg/install/monitoring.go
- cni/pkg/install/server.go
- cni/pkg/install/testdata/kubeconfig-skip-tls
- cni/pkg/install/testdata/kubeconfig-tls
- cni/pkg/util/util.go
- cni/test/install_cni.go
- pkg/test/util/file/file.go
- releasenotes/notes/cni-refactor.yaml
Since the PR https://github.com/istio/istio/pull/39801 (1.15), there is a bug only when CNI_ENABLE_INSTALL is set. Actually there is a few bugs working together.
First, we enter a loop that is basically for { sleepCheckInstall }: https://github.com/istio/istio/blob/b7ffd8eae26583f234a8113412db8a1c1aa5022d/cni/pkg/install/install.go#L91-L105
We see sleepCheckInstall always returning quickly, causing the loop to spin.
Inside sleepCheckInstall, watchSAToken spawns a goroutine which only exits once the entire process shuts down. This is bug #1 and why this is presented as a memory leak.
In sleepCheckInstall we have another loop: https://github.com/istio/istio/blob/b7ffd8eae26583f234a8113412db8a1c1aa5022d/cni/pkg/install/install.go#L200-L221. This will exit immediately due to the watchSAToken …
> CNI: refactor and fix memory leak/infinite loops

- istioctl/cmd/istiodconfig.go
- releasenotes/notes/44931.yaml
Add yaml format output for istioctl admin log
The test result:
> Add support for yaml output to istioctl admin log

- pilot/pkg/config/kube/crdclient/cache_handler.go
- pilot/pkg/config/kube/crdclient/cache_handler_test.go
- pilot/pkg/config/kube/crdclient/client.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/serviceexportcache.go
- pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
- pkg/config/schema/codegen/templates/clients.go.tmpl
- pkg/config/schema/kubeclient/common.go
- pkg/config/schema/kubeclient/resources.gen.go
- pkg/config/schema/kubetypes/common.go
- pkg/kube/client.go
- pkg/kube/informerfactory/factory.go
- pkg/kube/inject/watcher_test.go
- pkg/kube/kclient/client.go
- pkg/kube/kclient/interfaces.go
- pkg/kube/kubetypes/types.go
- pkg/kube/multicluster/secretcontroller.go
- pkg/kube/multicluster/secretcontroller_test.go
- pkg/kube/watcher/configmapwatcher/configmapwatcher.go
- pkg/kube/watcher/crdwatcher/crdwatcher.go
This PR is a bit of a rabbit hole but I think ends up in a good state.
The original intent was to fix a race condition in our existing code. Calling SetTransform and SetErrorHandler is racy against other threads calling Run(): https://github.com/kubernetes/kubernetes/issues/117869. In that issue, a great idea was to start using `newFunc` of the informer factory.
This led to a few issues:
* Not all the factory types can do this
* We were already doing this, but always using the core `KubeInformer()` instead of the per-type one, which was inconsistent. We also missed features.InformerWatchNamespace in some places
I thought of just fixing these, but upstreaming the fix takes 4mo to land here, and there have actually been other things I have wanted out of the factory. I realized the factory …
> kube: use our own informer factory

- pilot/pkg/config/kube/ingress/conversion.go
- pilot/pkg/config/kube/ingress/conversion_test.go
- pilot/pkg/config/kube/ingress/testdata/overlay.yaml.golden
- pilot/pkg/config/kube/ingress/testdata/tls-no-secret.yaml.golden
- pilot/pkg/config/kube/ingress/testdata/tls.yaml.golden
Updates Ingress to VirtualService translation to not create an HTTPRequestMatch when the URI is nil. The URI is nil when the path is a wildcard or is empty and the pathType is nil or ImplementationSpecific. This change prevents an Envoy failure. Envoy regex fails when the path separated prefix is empty or has a trailing "/".
Resolves #44882
**Reproducing Error:**
Reproduced the error seen in #44882 by applying the following Ingress after installing Istio with the demo profile:
```yaml
kubectl apply -f - <<EOF
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
annotations:
kubernetes.io/ingress.class: istio
name: ingress
spec:
rules:
- host: httpbin.example.com
http:
paths:
- path: /*
pathType: ImplementationSpecific
backend:
service: …
```
> Fix invalid XDS configuration for wildcard Ingress HTTP path

- tools/bug-report/pkg/content/content.go
The current envoy config dump will skip all when detecting one err from one envoy config debug url. Change the logic to iterate them all.
> Missing Envoy config dump info 

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
If LABEL_CANONICAL_SERVICES_FOR_MESH_EXTERNAL_SERVICE_ENTRIES is set to true tests are failing with `panic: assignment to entry in nil map`
> Fix nil map for cluster builder

- pkg/kube/client.go
- security/pkg/k8s/chiron/utils.go
- security/pkg/k8s/chiron/utils_test.go
- tests/integration/security/util/secret/secret.go
This PR updates to use the v1 CSR API exclusively. This has been available since Kubernetes 1.19, and stopped supporting 1.19 a while back.
In addition, there are a few misc improvements. I will comment inline the motivation behind them
> csr: modernize to v1 API

- tests/integration/security/egress_gateway_origination_test.go
- tests/integration/security/egress_sidecar_tls_origination_test.go
This step seems to be unnecessary.
> sds egress test : Remove TrimSuffix on credentialName

- pilot/pkg/bootstrap/server.go
- pkg/kube/multicluster/secretcontroller.go
- pkg/kube/namespace/filter.go
This is refactoring after https://github.com/istio/istio/commit/16ff353b180a1f461bd380be6ef2d1809b8c1fba.
* No need to sync namespaces, if the namespace informer is synced then the filter is as well
* I did not feel great about using the exit vs returning error, signals something is wrong with our startup sequence. Instead, just explicitly start the namespace informer and wait for it, then we do not need to run in a goroutine
> kube: refactor multicluster startup

- pkg/kube/informerfactory/factory.go
Example
https://storage.googleapis.com/istio-prow/logs/integ-assertion_istio_postsubmit/1659456885373276160/artifacts/pilot-analysis-426d538e8d6e41fa/_suite_context/istio-state-3871476243/primary-0/istiod-58dc66d79d-bgvxg_discovery.previous.log
> kube: fix assertion failure due to analysis

- istioctl/cmd/waypoint.go
- tests/integration/ambient/gateway_conformance_test.go
- tests/integration/ambient/main_test.go
We run all the Gateway API core conformance tests for sidecars, but not yet for ambient. This PR adds runs those tests for ambient as well.
Fixes #44742
> Add Gateway conformance tests to ambient

- pilot/pkg/features/pilot.go
- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_test.go
- releasenotes/notes/44605.yaml
This is a cherry-pick of #44605
fixes: #44995
> [release-1.18] telemetry: enable experimental mertic expiry

- pkg/bootstrap/config.go
- pkg/bootstrap/option/instances.go
To give more extensibility to the function `LoadStatsConfigJSONStr`, the entire Node is given instead of "RawMetadata".
Based on this, platform specific codes may be able to fill `load_stats_config_json_str` with more flexibility.
Change-Id: I21117025bb99b62c18484d2f1598a001751faaa4
> Change to use Node instead of RawMetadata in LoadStatsConfigJSONStr

- pilot/pkg/model/context.go
- pilot/pkg/model/virtualservice.go
if strings.Split have not substring. it will return [""],so it is unnecessary use 
```
if len(parts) > 1 {
return parts[0]
}
return ""
```
in addition, add len(knn) to avoid panic
> clean and fix string split

- pkg/backoff/exponential.go
With https://github.com/istio/istio/pull/44993/ the NextBackOff() wrapper was modified to handle certain negative scenarios where the NextBackOff() provided by cenkalti/backoff/v4 was returning -1. RetryWithContext() should also use the wrapped NextBackoff in order to prevent issue when -1 is raised.
**Before this PR:** RetryWithContext uses proper backoff until MaxElapsedTime is reached (15 min). After MaxElapsedTime has passed, RetryWithContext retries with a -1 backoff duration (no waiting time) negatively impacting performance. 
**After this PR**: if MaxElapsedTime has been reached in RetryWithContext, it will continue retrying with MaxInterval duration as waiting time.
> RetryWithContext should use the new NextBackOff()

- istioctl/cmd/proxyconfig.go
- istioctl/cmd/proxyconfig_test.go
Fixes Issue #44541.
- We were creating new Kube Clients every time `isZtunnelPod` was called. This PR changes that by initializing a Kube Client one time and using that for `isZtunnelPod`.
- This PR also adds a check during log parsing to ensure that we account for namespaces being added to the logger. Instead of invalidating valid logger level combinations, we now validate them properly.  **Below is a replication of the bug and an example of how it works now**:
**Note for Reviewer:** Formatting is off for the terminal output examples since it doesn't copy/paste easily to GitHub. Apologies in advance!
*Before fix*:
```
jmorris@jeremymorris:~/Dev/istio/istioctl/cmd/istioctl$ ./istioctl -n istio-system pc log ztunnel-8r6kp …
```
> Ztunnel logging improvements

- pilot/pkg/xds/sds.go
> populate crl only when the key is present in secret

- security/pkg/k8s/chiron/utils.go
Istiod DNS certificate doesn't need Client Auth Permissions
> Reduce istiod dns cert usages: remove client certificate

- pilot/pkg/xds/sds.go
I think this was introduced due to https://github.com/istio/istio/pull/45104/files#diff-304c91dfb9b2487f0bb78e849baf67e7255bcea0bbd0e1b632a17b74b85bf9eaL237
> skip empty ocsp staple configuration

- istioctl/cmd/authz.go
- istioctl/cmd/checkinject.go
- istioctl/cmd/clusters.go
- istioctl/cmd/completion.go
- istioctl/cmd/dashboard.go
- istioctl/cmd/dashboard_test.go
- istioctl/cmd/describe.go
- istioctl/cmd/injector-list.go
- istioctl/cmd/internal-debug.go
- istioctl/cmd/istiodconfig.go
- istioctl/cmd/metrics.go
- istioctl/cmd/metrics_test.go
- istioctl/cmd/proxyconfig.go
- istioctl/cmd/proxyconfig_test.go
- istioctl/cmd/proxystatus.go
- istioctl/cmd/revision.go
- istioctl/cmd/root.go
- istioctl/cmd/tag.go
- istioctl/cmd/version.go
- istioctl/cmd/wait.go
- istioctl/cmd/waypoint.go
- istioctl/cmd/waypoint_test.go
- istioctl/cmd/workload.go
- istioctl/cmd/workload_test.go
This PR is a follow up to a comment thread from another PR: https://github.com/istio/istio/pull/45022#discussion_r1204898447
The goal of this PR is to remove the re-initialization of the kubeclient if it's already been initialized using the root command [defined values for `kubeconfig` and `configContext`](https://github.com/istio/istio/blob/e4afd9a7b1c642930e1460e3a1d388768824339a/istioctl/cmd/root.go#L152-L156) . It's relied upon so often and since these values are the only ones being used (there are a few exceptions where kubeClient is made by passing in revisions, so those aren't in scope for this PR) it makes sense to only initialize kubeclient the first time it's called and share that initialized client across the package.
> Share an initialized kubeclient instead of re-initializing it everytime kubeclient is needed

- pilot/pkg/status/resource.go
Found this when somehow in the test, a struct with a nil value was inputted, and the type assertion passed. However, later on, its self function `SetObservedGeneration` panicked because of this passed nil value.
> Fix status writer potential nil panic

- cni/pkg/repair/repair_test.go
- pilot/pkg/util/informermetric/informerutil.go
- pkg/kube/client.go
- pkg/kube/kclient/client_test.go
- pkg/monitoring/monitoring_test.go
- pkg/monitoring/monitortest/test.go
This started out small and then got a bit larger than I wanted. The issue was we have a informer error handler per-cluster, but we forgot to set the cluster field. After fixing, I wanted to test it and found this was hard to do - we have some ad-hoc metrics testing in various places, but nothing common. So I made a new library to handle this and used it everywhere. One nice part about this is it is not tied to opencensus, so if/when we move it will not require test changes.
Then (thanks to the test) I also noticed the `label` is not correctly registered, fixed that as well
> Fix and test cluster metrics

- pilot/pkg/xds/ads.go
- pilot/pkg/xds/ads_test.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/eds_test.go
Minor refactoring, no need to use globals here. Also clean up to use
atomics instead of mutex for simplicity
> pilot: refactor version to avoid globals

- pilot/pkg/model/addressmap.go
- pilot/pkg/model/addressmap_test.go
- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/aggregate/controller.go
This is kind of improvement. No additional memory allocation is necessary when determining the size of the address map.
> Avoid memory allocation within address map

- pilot/pkg/model/push_context.go
- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
~Builds on https://github.com/istio/istio/pull/45058~
Fixes https://github.com/istio/istio/issues/45057
In VirtualService oldest one wins - even if its in a random namespace. That is, Namespace A -> Namespace B can be impacted by Namespace C's VirtualService.
In gamma, it is more strict. Consumer Namespace > Producer Namespace > Nothing (no fallback to arbitrary namespace).
This PR implements this precedence and updates our tests to match the new behavior (previously they were 'TODO's). There are no e2e tests since that is part of conformance which has an open PR; will pull it in soon.
> Gamma: fix consumer overrides

- go.mod
- pkg/test/env/istio.go
- pkg/util/image/registry.go
- tests/integration/helm/upgrade/helm_upgrade_test.go
- tests/integration/helm/upgrade/main_test.go
- tools/docker-builder/docker.go
Instead, rely on the contents of the VERSIOn file
> Don't hardcode versions in upgrade test

- tools/golangci-override.yaml
xref: https://github.com/istio/tools/pull/2490 and https://github.com/istio/common-files/pull/844
> golangci-lint: add depguard/v2 settings

- pilot/pkg/model/config.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/aggregate/controller.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/authorization.go
- pilot/pkg/xds/endpoint_builder.go
- pilot/pkg/xds/workload.go
- pkg/slices/slices.go
* Consistently use resource key as `network/foo`. Use string instead of
NamespaceName and remove logic that assumes other key formats
* Add a helper to avoid so many type switches
* Move out authz rules to its own file; no changes, just moving
* A few other nit fixes as followup from PR
> ambient: refactor controller implementation a bit

- cni/pkg/ambient/server.go
Fixes #45304
I am not sure this pr can fix it totally, But it is useful for the error :
```
error ambient Failed to write config file: open /etc/ambient-config/config.json.tmp: permission denied
```
file.AtomicWrite try to chmod tmp file ,but atomicWrite not
> use file.AtomicWrite to chmod auth

- pkg/config/schema/codegen/templates/types.go.tmpl
- pkg/config/schema/kubetypes/resources.gen.go
This is useful when constructing clients from type. WE don't do this
yet, but splitting out to avoid larger PR.
> Allow lookup of GVK from client-go types

- istioctl/cmd/proxyconfig.go
`istioctl x envoy-stats` support `prom-merged` format output, but not reflect in usage.
> Add missing outputformat usage for istioctl envoy-stats

- pkg/monitoring/monitoring_test.go
will help when we measure compared to other implementations
> monitoring: make benchmark more robust

- pkg/envoy/proxy.go
- releasenotes/notes/45331.yaml
- security/pkg/nodeagent/cache/secretcache.go
- Correctly return the exception information caused by the cmd kill error when envoy stops, and print the correct log to facilitate troubleshooting
- Use defer to release the lock, so we will never forget unlock it
> use defer to unlock

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_test.go
- releasenotes/notes/check-disabled-status.yaml
By checking the disabled status when adding a log provider, this PR fixes an issue where disabling a log provider through Istio telemetry API would not work. Otherwise, a disabled log provider may still be added to the log configuration and cause the disabling to not work as expected. The test case in this PR verifies that with the fix this PR, a disabled log provider will not be added to the log configuration.
- [X ] Policies and Telemetry
> Check the disabled status when adding a log provider

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/httpregexrewrite.yaml
This PR implements the API change here https://github.com/istio/api/pull/2753. Regarding issue: https://github.com/istio/istio/issues/22290
- Adds support for `uriRegexRewrite` under HTTPRewrite in Virtual Service. 
- Update validation webhook to understand the new field. URI rewrite and uriRegexRewrite cannot be used together
> Implement support for Regex Rewrite for URI's

- pilot/pkg/config/kube/gateway/conversion.go
A situation when Ambient was enabled, and the GatewayClass functioned well. 
However, after reinstallation with a minimal profile, Ambient was disabled. Despite this, the GatewayClass remains included since its status has not changed, which results in waypoint GatewayClass being unnecessarily included.
> Fix getGatewayClasses has waypoint after Ambient is disabled

- tests/testdata/certs/generate.sh
root-cert.srl does not seem to be created in this script, and the script prints error saying file is not present.
> generate-certs: Remove unnecessary cleanup step

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/testdata/http.yaml
- pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
Now that UriRegexRewrite is supported in HTTPRewrite https://github.com/istio/istio/pull/45398, the previous hack https://github.com/istio/istio/pull/42605 used to support full path rewrite from Gateway API is no longer needed.
> Use UriRegexRewrite to implement full path rewrite in Gateway API

- samples/helloworld/helloworld-dual-stack.yaml
- samples/helloworld/src/Dockerfile
- samples/helloworld/src/app.py
- samples/helloworld/src/requirements.txt
- update helloworld to use gunicorn
- gunicorn is standard practice for deploying flask apps
- bind TCP6 by default but offer a fallback option if necessary
- at this stage most any systems in use will probably handle translation of IPv4 to applications which are listening IPv6 in Kubernetes but I included instructions in the Dockerfile to fall back to IPv4 explicitly
- went ahead an moved the app itself to listening on localhost (IPv4) since gunicorn is handling IPv6 traffic coming from outside the container. This is to simplify overriding runtime config to use (only) IPv4 if for some reason it's required.
- introduce a dual stack manifest for helloworld on k8s
> helloworld sample update

- pilot/pkg/model/config.go
Clean code, use insert on set, but not = struct{}{}
> use insert on set

- tests/integration/security/egress_sidecar_tls_origination_test.go
- Sidecar Egress TLS Origination Integration Tests for CRL Support.
- Enhanced existing tests to properly verify the error messages along with response code
Implementation PR: https://github.com/istio/istio/pull/45104
API PR: https://github.com/istio/api/pull/2796
Ingress Integration tests PR: https://github.com/istio/istio/pull/45237
> CRL: integration tests sidecar egress tls origination

- pkg/config/labels/instance.go
- pkg/config/labels/instance_test.go
```
name                 old time/op    new time/op    delta
LabelString/small-8     481ns ± 4%     169ns ± 1%  -64.96%  (p=0.008 n=5+5)
LabelString/big-8      12.2µs ± 3%     4.9µs ± 3%  -59.29%  (p=0.008 n=5+5)
name                 old alloc/op   new alloc/op   delta
LabelString/small-8      216B ± 0%       56B ± 0%  -74.07%  (p=0.008 n=5+5)
LabelString/big-8      6.01kB ± 0%    2.30kB ± 0%  -61.67%  (p=0.008 n=5+5)
name                 old allocs/op  new allocs/op  delta
LabelString/small-8      10.0 ± 0%       2.0 ± 0%  -80.00%  (p=0.008 n=5+5)
LabelString/big-8         158 ± 0%         3 ± 0%  -98.10%  (p=0.008 n=5+5)
```
This is shown to be a hot path in some scenarios (https://github.com/istio/istio/issues/44985)
> Optimize labels.String()

- istioctl/pkg/multicluster/env_test.go
The func createFakeKubeconfigFileOrDie create a temp file by os.CreateTemp. But does not remove it.
https://github.com/istio/istio/blob/d8b21e02e754b6e93bf259ff7e226fafaa9c16d3/istioctl/pkg/multicluster/env_test.go#L53
> remove temp file after use

- samples/helloworld/src/app.py
I was informed that some users are testing using the sample's source outside of the image and wish for the flask server to continue to bind on [::] in support of those uses. Switching back to [::] for flask.
> bind helloworld flask app on IPv6

- pilot/pkg/config/kube/gateway/conversion.go
fix #45565 
Using `fmt.Sprint` to convert the reference type will get the address, so the ordering is random.
> fix parentRefs sort

- pkg/version/cobra_test.go
This breaks some experimental Go builds, no need to be so strict
> TestVersion: be less restrictive about go versions

- pilot/pkg/security/authn/v1beta1/policy_applier_test.go
Contributes to #37555 .
This PR shortens the retryInterval to 10 millis for jwtresolver, bringing down the testing time from 7s to ~.40s
However, I found that the duration of the test fluctuates, depending on a "race condition" (probably an inaccurate expression) between `closeChan` and `jwksuriChannel` receiving values:
https://github.com/cebernardi/istio/blob/91c957436b75554ba4ad514ec00e182ff7040b0b/pilot/pkg/model/jwks_resolver.go#L402-L408
If `jwksuriChannel` receives a value before `closeChan`, the `Close` function waits for 8 attempts to be made to resolve the jwk uri before returning (thus, the test takes longer).
Is it something that should be addressed? If yes, would it be in this PR, or in another PR?
> Change retry interval in jwtkeyresolver to 10 millis for testing

- prow/release-commit.sh
use Docker_HUB env variable instead
> quemu-use-env - use DOCKER_HUB

- pilot/pkg/model/push_context_test.go
- pilot/pkg/model/service.go
- pilot/pkg/model/service_test.go
- pilot/pkg/model/validation_test.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pilot/pkg/serviceregistry/util/workloadinstances/index_test.go
- pilot/pkg/xds/endpoint_builder.go
- pilot/pkg/xds/ep_filters_test.go
This PR reduces lock contention in EDS. Primarily discovered/discussed/tested in https://github.com/istio/istio/issues/44985. I was also able to reproduce the same
We see very little impact on the raw microbenchmarks:
```
name                          old time/op        new time/op        delta
EndpointGeneration/1/100-48          642µs ± 2%         653µs ± 2%  +1.78%  (p=0.002 n=9+10)
EndpointGeneration/10/10-48          300µs ± 1%         306µs ± 2%  +2.11%  (p=0.000 n=10+10)
EndpointGeneration/100/10-48        2.68ms ± 1%        2.69ms ± 1%    ~     (p=0.218 n=10+10)
EndpointGeneration/1000/1-48        2.66ms ± 1%        2.70ms ± 3%  +1.57%  (p=0.017 n=9+10)
name                          old kb/msg         new kb/msg         delta
EndpointGeneration/1/100-48           10.1 ± 0% …
```
> pilot: reduce lock contention in EDS

- pilot/pkg/model/service.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/grpcgen/lds.go
Covered the function of `GetExtraAddressesForProxy` via flag.
Related to PR: https://github.com/istio/istio/pull/45564
> Covered the function of GetExtraAddressesForProxy via flag

- tests/integration/telemetry/api/accesslogs_test.go
Existing testcase for TestAccessLogsMode/server was set to expect no logs from server and client even though the setting applied had a MATCH set to server.
Fix: TestAccessLogsMode/server case, is fixed to expect server logs.
> Fix AccesslogsMode server testcase

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- releasenotes/notes/cipher_suites.yaml
Allow users to specify the ciphers they want sidecars to use within their sidecars.
> Add cipher suites support in meshConfig for mesh-wide cipher

- pkg/bootstrap/config.go
- pkg/bootstrap/testdata/all_golden.json
- pkg/bootstrap/testdata/auth_golden.json
- pkg/bootstrap/testdata/authsds_golden.json
- pkg/bootstrap/testdata/default_golden.json
- pkg/bootstrap/testdata/lrs_golden.json
- pkg/bootstrap/testdata/metrics_no_statsd_golden.json
- pkg/bootstrap/testdata/running_golden.json
- pkg/bootstrap/testdata/runningsds_golden.json
- pkg/bootstrap/testdata/stats_inclusion_golden.json
- pkg/bootstrap/testdata/tracing_datadog_golden.json
- pkg/bootstrap/testdata/tracing_lightstep_golden.json
- pkg/bootstrap/testdata/tracing_none_golden.json
- pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
- pkg/bootstrap/testdata/tracing_stackdriver_golden.json
- pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
- pkg/bootstrap/testdata/tracing_tls_golden.json
- pkg/bootstrap/testdata/tracing_zipkin_golden.json
- pkg/bootstrap/testdata/xdsproxy_golden.json
- releasenotes/notes/no_extension_lookup_by_name.yaml
- tests/integration/pilot/gw_topology_test.go
The runtime flag is being deprecated and has issued warnings by istioctl for quite some time already.
Ref: https://github.com/envoyproxy/envoy/issues/23598
> envoy: remove extension lookup by name

- pkg/config/analysis/analyzers/service/portname.go
- pkg/config/analysis/analyzers/testdata/service-port-name.yaml
- pkg/config/kube/conversion.go
- releasenotes/notes/45644.yaml
Analyze has the message for port name of waypoint:
```
Info [IST0118] (Service ambient/httpbin-istio-waypoint) Port name mesh (port: 15008, targetPort: 15008) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service ambient/productpage-istio-waypoint) Port name mesh (port: 15008, targetPort: 15008) doesn't follow the naming convention of Istio port.
Info [IST0118] (Service ambient/ratings-istio-waypoint) Port name mesh (port: 15008, targetPort: 15008) doesn't follow the naming convention of Istio port.
```
Since this is implemented internally, I think we can avoid reporting these messages.
> Fix analyze waypoint hbone portname warning

- istioctl/pkg/proxyconfig/proxyconfig.go
- releasenotes/notes/45643.yaml
Ztunnel component cannot be parsed since it's different config. This fix is similar to other proxy-config config parts.
Tests:
```bash
istio git:(master) ✗ istioctl pc rootca-compare ztunnel-dt9pp.istio-system ztunnel-hzfbf.istio-system                               
Both [ztunnel-dt9pp.istio-system] and [ztunnel-hzfbf.istio-system] have the identical ROOTCA, theoretically the connectivity between them is available
➜  istio git:(master) ✗ istioctl pc rootca-compare reviews-v2-56c97865cc-vwqgk.bookinfo reviews-v3-5cc6876f4f-n247b.bookinfo
Both [reviews-v2-56c97865cc-vwqgk.bookinfo] and [reviews-v3-5cc6876f4f-n247b.bookinfo] have the identical ROOTCA, theoretically the connectivity between them is available
```
> Fix proxy-config root-compare ztunnel component parse error

- istioctl/cmd/root.go
- releasenotes/notes/45640.yaml
Uninstall has been graduated almost a year ago. I think we can remove it from experimental commands for the next release.
> Move uninstall out of experimental commands

- pkg/config/schema/codegen/collections.go
- pkg/config/schema/codegen/common.go
- pkg/config/schema/codegen/templates/gvr.go.tmpl
- pkg/config/schema/gvr/resources.gen.go
- pkg/kube/kclient/client.go
- pkg/kube/kclient/client_test.go
When using `ISTIO_WATCH_NAMESPACE`, I got: 
```
k8s.io/client-go@v0.27.0/tools/cache/reflector.go:231: 
failed to list *v1.PartialObjectMetadata: the server could not find the requested resource
```
We should not set watch namespace for cluster scoped resources
Maybe related to https://github.com/istio/istio/issues/45512
> Don't set InformerWatchNamespace for cluster scoped resources

- pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/fake.go
Contributes to #37555 
This PR proposes to run TestSidecarRoutes (~5.8s) in parallel, reducing the execution time to less than a second.
Running the tests in parallel exposed a data race, so I moved `processStartTime` into the scope of `DiscoveryService`.
I tried to exclude, at the best of my knowledge, that there are side effects to this change, but we need the opinion of someone with a deeper understanding of the code. 
My understanding is that the condition created by running the test in parallel is sort of artificial, and normally we wouldn't have multiple instances of `DiscoveryService`, so no data race on `processStartTime`. 
On the other hand, it doesn't seem to hurt moving it from a package scope to a structure scope.
thoughts?
> Run TestSidecarRoutes in parallel

- tests/integration/pilot/gateway_conformance_test.go
As we have upgraded the gateway API version.
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
> Remove IPv4 workaround in gateway conformance test

- pkg/test/framework/components/echo/config.go
This is cosmetic issue only, I think -- we are correctly testing debian
11 before still... I think.
> tf: fix mismatch in debian version

- tools/bug-report/pkg/archive/archive.go
- tools/bug-report/pkg/bugreport/bugreport.go
- tools/bug-report/pkg/cluster/cluster.go
- tools/bug-report/pkg/common/common.go
Issue https://github.com/istio/istio/issues/45466
Fetch Cni logs from `kube-system` namespace pods selected by `k8s-app=istio-cni-node`. 
The logs are written into `cni.log` file per pod (not per container)
> Capture CNI logs in istioctl bug-report

- pilot/pkg/model/service.go
portMapEquals can be replaced by maps.Equals.
> remove portMapEquals in service

- pkg/config/analysis/analyzers/gateway/gateway.go
- pkg/config/analysis/analyzers/testdata/gateway-custom-ingressgateway-badport.yaml
- pkg/config/analysis/analyzers/testdata/gateway-custom-ingressgateway.yaml
- releasenotes/notes/fix-analysis-gatewayport.yaml
The Analyzer for GatewayPortNotOnWorkload was producing incorrect results due to associating the gateway.servers[].port (the port for ingress listeners) with the `Port` of the Service.
The correct association should be with the `TargetPort` of the Service.
> fix gateway server port analysis result of GatewayPortNotOnWorkload is incorrect

- pkg/test/framework/components/istio/config.go
- pkg/test/framework/components/istio/flags.go
- tests/integration/pilot/testdata/tunneling/gateway/tcp/gateway.tmpl.yaml
- tests/integration/pilot/testdata/tunneling/gateway/tcp/virtual-service.tmpl.yaml
- tests/integration/pilot/testdata/tunneling/gateway/tls/istio-mutual/gateway.tmpl.yaml
- tests/integration/pilot/testdata/tunneling/gateway/tls/istio-mutual/mtls.tmpl.yaml
- tests/integration/pilot/testdata/tunneling/gateway/tls/istio-mutual/virtual-service.tmpl.yaml
- tests/integration/pilot/testdata/tunneling/gateway/tls/passthrough/gateway.tmpl.yaml
- tests/integration/pilot/testdata/tunneling/gateway/tls/passthrough/originate-tls.tmpl.yaml
- tests/integration/pilot/testdata/tunneling/gateway/tls/passthrough/virtual-service.tmpl.yaml
- tests/integration/pilot/tunneling_test.go
- tests/integration/security/authz_test.go
- tests/integration/security/testdata/authz/egress-gateway.yaml.tmpl
The Istio E2E tests still assume a lot about a pre-existing environment when running integration tests, specifically around the egress gateway deployments. This PR allows the test runner to change the expected service name, namespace and labels during the e2e tests
Part of: #45663
> Add flexibility to Istio egress labels, name and namespace for E2E tests

- pilot/pkg/model/context.go
- pilot/pkg/model/endpointshards.go
- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/fake.go
- tests/fuzz/pilot_model_fuzzer.go
Move cache to env so that we build it once and use it every where. Otherwise we have to keep checking `cache != nil` many places. 
Ref https://github.com/istio/istio/pull/45800#discussion_r1252506861
> move cache to environment

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_workloadentry_test.go
- pilot/pkg/serviceregistry/kube/controller/authorization.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
The ambient controller currently accesses fields in `AmbientIndex` directly, which has already led to at least one data race.
This establishes a new interface `AmbientIndex` that is used by the controller. The implementation correctly handles locking as needed.
Fixes #45816
> Refactor ambient controller to avoid race conditions

- istioctl/pkg/proxyconfig/proxyconfig.go
Secret dump has been used for a while, and it has been improved for years. I think we can remove the experimental message now.
> Remove experiemental message of proxy-config secret

- tests/integration/tests.mk
- tools/go-compile-without-link
See https://blog.howardjohn.info/posts/go-build-times/#integration-tests
for more context. tl;dr this makes the integration tests compile 2x
faster.
> Compile integration tests faster

- tools/docker-builder/docker.go
We use `container-builder` for the build container everywhere but in the one error message. Update the message.
> Update build container name for consistency

- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/xds/delta.go
`extractNames` and `ListContains` can be replaced and I think we can clean them up.
> remove extractNames and ListContains

- releasenotes/notes/45866.yaml
- tools/packaging/packaging.mk
The init script (istio-start.sh) uses the hostname command which isn't always installed in certain distros (e.g. CentOS 8).
> vm/packaging: add hostname package as a dependency

- pkg/bootstrap/config.go
- pkg/bootstrap/option/instances.go
- pkg/bootstrap/testdata/all_golden.json
- pkg/bootstrap/testdata/auth_golden.json
- pkg/bootstrap/testdata/authsds_golden.json
- pkg/bootstrap/testdata/default_golden.json
- pkg/bootstrap/testdata/lrs_golden.json
- pkg/bootstrap/testdata/metrics_no_statsd_golden.json
- pkg/bootstrap/testdata/running_golden.json
- pkg/bootstrap/testdata/runningsds_golden.json
- pkg/bootstrap/testdata/stats_inclusion_golden.json
- pkg/bootstrap/testdata/tracing_datadog_golden.json
- pkg/bootstrap/testdata/tracing_lightstep_golden.json
- pkg/bootstrap/testdata/tracing_none_golden.json
- pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
- pkg/bootstrap/testdata/tracing_stackdriver_golden.json
- pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
- pkg/bootstrap/testdata/tracing_tls_golden.json
- pkg/bootstrap/testdata/tracing_zipkin_golden.json
- pkg/bootstrap/testdata/xdsproxy_golden.json
Fixes https://github.com/istio/istio/issues/45462
I think this is the best we can do without Envoy reverting
> Stop using deprecated Envoy runtimes flags

- pkg/proxy/proxyinfo.go
- pkg/version/version.go
This recent change made the docker-builder bloat from ~20mb to ~80mb
> Remove dependency on `model` from `pkg/version`

- pilot/cmd/pilot-agent/status/server.go
- pilot/cmd/pilot-agent/status/server_test.go
Resolves #45482.
This change removes the overwrite of the host of the application request created by the istio-agent status server. Previously, the host was overwritten to the host of the original request from Kubelet to the istio-agent status server. Unless a host header was specified, the host would always be set to the status port, 15020, rather than the application port used for health checks.
Testing:
- Modified unit tests to remove explicit port override. Without the override in the unit tests, the existing workflow fails as expected. The unit test override did not reflect the actual workflow and values of a health check request.
> Fix health probe port overwrite

- istioctl/pkg/precheck/precheck.go
- releasenotes/notes/fix-istioctl-x-precheck-missing-revision.yaml
`revision` flag missing in `istioctl x precheck`
> >fix missing revision flag in precheck

- istioctl/pkg/describe/describe.go
- istioctl/pkg/validate/validate.go
- istioctl/pkg/validate/validate_test.go
- pkg/kube/labels/labels.go
- releasenotes/notes/45749.yaml
istioctl commands are still doing the only `app` and `version` check for pod labels, which is inaccurate and should be updated
> istioctl: support available telemetry service name and version labels

- cni/pkg/ambient/informers.go
Currently, if you restart CNI the rules are removed and never added.
This ensures they are at least added back. Its still pretty broken to have CNI exit -> drop all policies, but we can handle that later.
> ambient: fix cni restart

- releasenotes/notes/artifact-naming.yaml
Work was done in https://github.com/istio/release-builder/pull/1560 to create additional artifacts with the architecture in the name for consistency. That repo doesn't have release notes, so adding a note here to not the the change and deprecation.
> Create a release note for the adding of amd64 to MacOS and Windows artifacts

- pilot/pkg/serviceregistry/kube/controller/ambientindex_serviceentry_test.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_workloadentry_test.go
The ambient tests are very long and complex, making them hard to understand and expand.
This attempts to break apart some (not all) of the long tests and also creates a `ambientTestServer` that provides methods to help remove some of the boilerplate code.
> Refactor ambient tests

- pilot/pkg/security/authn/utils/utils.go
- pilot/pkg/security/authn/utils/utils_test.go
- pilot/pkg/security/authn/v1beta1/policy_applier.go
- releasenotes/notes/cipher_suites_mesh_to_mesh.yaml
Added code changes to support meshconfig to configure cipher suites on sidecars for mesh to mesh traffic. 
- [x ] Security
Testing :
meshConfig.Yaml 
```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
name: istiocontrolplane-default
spec:
meshConfig:
meshMTLS:
ecdhCurves:
- P-256
cipherSuites:
- ECDHE-RSA-AES128-GCM-SHA256
```
With above mesh config, verified cipher suites used in the tls negotiation between sidecars. And tls negotiation failed if we used any cipher suites other than configured cipher suites.
> Add cipher suites support in meshConfig for mesh to mesh traffic

- release/downloadIstioCandidate.sh
- release/downloadIstioCtl.sh
Sometimes we may download Istio on a personal/work computer (Mac) and then transfer it to a test environment (Linux) for installation, in which case we need to specify the target OS.
> downloadIstioCandidate.sh supports passing env TARGET_OS

- samples/bookinfo/networking/bookinfo-gateway.yaml
This lead to the test failure mentioned in https://github.com/istio/istio/pull/45726#issuecomment-1629790045.
After https://github.com/istio/istio/pull/45726 corrected the port selection, running `istioctl analyze` from the steps on the Getting Started page produces a new warning. This PR addresses this by replacing the gateway's port from 80 to 8080. This fixes the warning message and doesn't change the actual Envoy listener port.
/cc @ericvn
> Fix gateway server port in bookinfo sample

- cni/pkg/ambient/constants/constants.go
- cni/pkg/ambient/net_linux.go
- cni/pkg/ambient/server.go
- releasenotes/notes/45831.yaml
This small change fixes one of the issues of ambient on OpenShift with ovn-kubernetes CNI.
By default, ovn-kubernetes creates an external geneve link named "ovn_sys_6081", and therefore istio-cni fails to create links for geneve tunnels `istioin` and `istioout`, because "**There already exists an externally controlled device on this destination port**" - this is the error message from `ip link add` command. The port conflict occurs, because istio-cni does not specify destination ports for created links and therefore it uses the same port - 6081.
I also noticed that similar error may occur when a node has a geneve link with the same VNI and remote IP as `istioin` and `istioout`. This is probably unlikely to happen, but it's at least …
> ambient: dynamically determine dstport for geneve link

- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/bootstrap/server.go
- pilot/pkg/config/kube/gateway/controller_test.go
- pilot/pkg/model/network.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/authorization.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/serviceregistry/kube/controller/multicluster.go
- pilot/pkg/serviceregistry/kube/controller/network.go
- pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
- pilot/pkg/serviceregistry/memory/discovery.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/delta.go
- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/eds_test.go
- pilot/pkg/xds/fake.go
- pilot/pkg/xds/monitoring.go
- pilot/pkg/xds/nds.go
- pilot/pkg/xds/nds_test.go
- security/pkg/nodeagent/sds/server.go
Previously, Reason []TriggerReason was used in the PushRequest to record the reasons for triggering the push. However, we have a debounce mechanism to aggregate a large number of changes that occur within a short period of time. This aggregation operation also aggregates Reason, but only concatenates the arrays, which leads to a lot of array resizing when a large number of changes occur in a short period of time. For example: EndpointUpdate -> EndpointUpdate,ConfigUpdate -> EndpointUpdate,ConfigUpdate,ConfigUpdate -> EndpointUpdate,ConfigUpdate,ConfigUpdate,ConfigUpdate -> … This can lead to a lot of memory allocation.
In our actual scenario, when the amount of configuration is large, the above aggregation operation for Reason will bring …
> PushRequest.Reason change to map to optimize mem/merge cost

- samples/security/spire/spire-quickstart.yaml
The spire sample seems to be failing at this point, but obviously worked in the past (part of istio.io testing). I notice there is a `nightly` image specified in the sample. Let's pin this to an older image.
> Update a spire image from `nightly` to a pinned version

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
Fixes Istiod crash when FILTER_GATEWAY_CONFIG is enabled, when virtual service has no destinations.
```
goroutine 556 [running]:
istio.io/istio/pkg/util/sets.Set[...].Insert(...)
istio.io/istio/pkg/util/sets/set.go:40
istio.io/istio/pilot/pkg/model.addHostsFromMeshConfig(0x2c3a120?, 0xc021a7ebd0?)
istio.io/istio/pilot/pkg/model/push_context.go:844 +0x153
istio.io/istio/pilot/pkg/model.(*PushContext).initVirtualServices(0xc000b72fc0, 0xc000e3fef0)
istio.io/istio/pilot/pkg/model/push_context.go:1561 +0xe67
istio.io/istio/pilot/pkg/model.(*PushContext).createNewContext(0xc000b72fc0, 0xc000e3fef0)
istio.io/istio/pilot/pkg/model/push_context.go:1211 +0xb3
istio.io/istio/pilot/pkg/model.(*PushContext).InitContext(0xc000b72fc0, 0xc000e3fef0, 0xc019578540, 0xc0067e8900) …
```
> fix istiod crash when filter gateway config is enabled with no virtual service destinations

- cni/pkg/ambient/net.go
- cni/pkg/plugin/ambient.go
- cni/pkg/plugin/plugin.go
Pod should not start if it can't be added
Note this is not handling the errors loading the Namespace and Pod to identify the annotation - it can
be addressed in a separate PR, it is more complicated than just failing, we may want to use the 
cached info in the daemon so if API server is down kubelet can still restart the pod. 
The eventual goal is to have ambient enabled by default - in which case there is no need to check with K8S,
that error path is mainly for migration. 
> Better error handling on ambient CNI

- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pkg/config/mesh/watcher_test_utils.go
Package should not accept a duration and then multiple it by seconds. Caller should do that
> pkg: cleanup misleading usage of time.Duration

- bin/build_ztunnel.sh
This will fail as "shell" is not a command in the build-tools images.
> Fix build_ztunnel to not try to call shell

- istioctl/pkg/proxystatus/proxystatus.go
- releasenotes/notes/45641.yaml
Ztunnel pods are displayed in `proxy-status`, however envoy xDS configs are not available for them, and they should not be included for sync diff. Currently there are also some errors when we do 
```
istioctl ps ztunnel-dt9pp.istio-system
```
because of the missing config.
> Fix proxy-status diff for ztunnel pod

- pilot/pkg/model/service.go
- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/httproute_test.go
- releasenotes/notes/45564-virtualHost-Domains-for-dual-stack.yaml
fixes #45557
Adds the additional IP from services spec.clusterIPs into the virtualHost.Domains
> virtualHost.Domains for dual stack

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/security/model/authentication.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/35357.yaml
The original pr is https://github.com/istio/istio/pull/35357.
The relative issuse is https://github.com/istio/istio/issues/45611.
The InsecureSkipVerify only works on the case that the tls mode is simple or mutual. When the InsecureSkipVerify is enabled true, the below behaviors are expected.
1. If the env `VERIFY_CERTIFICATE_AT_CLIENT` is enabled true and tls mode of service A is simple，envoy will not check server cert signature (system ca when ca cert is not supplied) and SAN. Even if env `ENABLE_AUTO_SNI` is enabled true, envoy will not use the automic SAN mode.
2. If the env `VERIFY_CERTIFICATE_AT_CLIENT` is enabled true and tls mode of service A is mutual，envoy will only use the client key and cert to do mutual tls but not check server cert signature (system ca when ca cert is not …
> Implement InsecureSkipVerify from DestinationRule.

- pilot/cmd/pilot-agent/status/server.go
- pilot/cmd/pilot-agent/status/server_test.go
Currently this isn't really a big difference, just a minor refactoring
to use best practices and avoid global/init().
In future (https://github.com/istio/istio/pull/45341) it may be more
important.
> agent: avoid global metrics initialization

- pilot/cmd/pilot-agent/options/agent.go
- pilot/cmd/pilot-agent/options/options.go
- pkg/istio-agent/agent.go
- pkg/istio-agent/agent_test.go
- releasenotes/notes/exit-if-sds-socket-not-found.yaml
* adding - exit if sds socket not found
Cherry-pick c52c2ed1d0dd9c6a904428d54719383a1b1ac74e
fix: https://github.com/istio/istio/issues/45963
> Exit if sds socket not found (#45941)

- pilot/pkg/model/service.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/networking/util/util_test.go
- pilot/pkg/xds/endpoint_builder.go
- pilot/pkg/xds/ep_filters.go
This is a cherrypick of [44473](https://github.com/istio/istio/pull/44473). Auto cherrypick was resulting into conflicts [46020](https://github.com/istio/istio/issues/46020). 
Why is this needed :- 
pull/43560 is available in release-1.18 and causing issues for our internal Istio fork. It seems pull/44470 and pull/44473 are not merged in release-1.18. I merged [cherrypick](https://github.com/istio/istio/pull/46017) of pull/44470, this is the cherrypick of pull/44473.
> [release-1.18] fix concurrent map access in endpoint metadata (#44473)

- pilot/cmd/pilot-agent/app/cmd.go
- pilot/pkg/util/network/ip.go
- releasenotes/notes/46016.yaml
- tools/istio-iptables/pkg/cmd/root.go
This will fix issue #45335. This issues happens only if there are secondary interfaces in the POD.
We are ignoring linklocal addresses for proxy mode detection (Singlestack or dual). There was a previous fixed done in PR#37164 that hardcoded ignoring IPv4 linklocal address for EKS and on top of that users have to exlude 0.0.0.0 so the init consider don't redirect IPv4 traffic to the proxy. This PR will streamline both proxymode and excluding the specific interface from iptables and there will be no need to specify 0.0.0.0 via range.
Recently we have another fixed which is more flexible and cleaner by ignoring the excluded interface. E.g. If primary interface is IPv6 and secondary interface is IPv4, user can decide below.
- Install istio in singlestack mode and exclude IPv4 interface
- …
> Dualstack: fixing to not ignore link local addresses in proxy detection

- istio.deps
- tests/binary/binaries_test.go
The `TestBinarySizes/envoy` test is failing with the latest proxy (see https://github.com/istio/istio/pull/46028). The binary size has increased beyond the 110 limit. This PR updates the limit to 115.
> Update proxy and slightly increase allowed binary size

- istioctl/pkg/proxystatus/proxystatus.go
- pilot/pkg/xds/debug.go
- releasenotes/notes/45919.yaml
- tests/integration/pilot/istioctl_test.go
The current debugging interface for proxy status may display too much information. This PR enables filtering of proxy status by namespace using the `?namespace=` query. This also allows `istioctl proxy-status -n` to function correctly.
> Support namespace filtering for proxy status

- istioctl/pkg/checkinject/checkinject.go
Improve the clarity of the reason when `.values.sidecarInjectorWebhook.enableNamespacesByDefault` is enabled.
> Improve the clarity of the reason in check-inject

- istioctl/cmd/root.go
- releasenotes/notes/46051.yaml
They have been moved to `istioctl` almost two years ago, and I just submitted https://github.com/istio/istio.io/pull/13589 to update the doc instructions.
> istioctl: remove `create-remote-secret` and `remote-clusters` in experimental

- pilot/pkg/serviceregistry/util/xdsfake/updater.go
- pkg/istio-agent/xds_proxy.go
The underlying Timer is not recovered by the garbage collector until the timer fires. We should not wait long for select using time.After, This will create many timers in memory
> fix time after memory leak

- cni/pkg/install/binaries.go
- cni/pkg/install/binaries_test.go
- cni/pkg/install/install.go
- cni/pkg/install/install_test.go
- cni/pkg/util/util.go
-------
The CNI agent copies CNI binaries to well-known paths on the node, where the CNI subsystem in use will invoke them, if configured.
It then starts a file watch on those paths, and re-copies the binaries if changes are detected, as a self-healing mechanism.
However, the current code watches the *entire* destination directory for change events, not just the Istio-owned files that are copied there - this makes the Istio CNI plugin slightly poorly behaved if other CNI plugins are in the chain, in that Istio's watcher will uselessly fire if non-Istio binaries are copied to the same spot, causing it to redeploy the binaries even if they are unchanged.
This PR changes that behavior so that the watcher only watches the binaries it _actually installs_ in the destination path, rather than …
> Don't fire CNI installer watch events unless Istio binaries are changed.

- pkg/test/echo/server/forwarder/tcp.go
- pkg/test/framework/components/authz/kube.go
- pkg/test/framework/components/cluster/clusterboot/factory_test.go
- pkg/test/framework/components/echo/deployment/builder.go
- pkg/test/framework/components/echo/echotest/setup.go
- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/components/echo/kube/workload_manager.go
- pkg/test/framework/components/echo/staticvm/instance.go
- pkg/test/framework/components/environment/kube/flags.go
- pkg/test/framework/components/istio/istio.go
- pkg/test/framework/features/README.md
- pkg/test/framework/features/features.yaml
- pkg/test/framework/resource/flags.go
- pkg/test/loadbalancersim/loadbalancer/edf.go
- pkg/test/loadbalancersim/timer/queue.go
- pkg/test/util/retry/retry_test.go
This PR fix typos in `pkg/test` directory.
> tf: fix spelling typos

- pilot/pkg/networking/core/v1alpha3/cluster_cache.go
AFAICT this is all that is needed to fix #46081 
* EDS disables caching by setting `needToCompute = true`
* RDS codepath doesn't seem to reference HBONE/Ambient status
* LDS doesn't use cache
If we're nervous that it's not enough, maybe we can do something like
```golang
func (c *clusterCache) Cacheable() bool {
return !c.hbone
}
```
> CDS cache key includes hbone status

- pilot/pkg/bootstrap/server.go
- pilot/pkg/bootstrap/sidecarinjector.go
Make sure the readiness probe returns ready when the sidecar injector is not used, or not configured.
Fix #45990
Resolves the bug reported in #45990 by making sure the readiness probe for the sidecar injector is true when the injector is not used.  This prevents istiod from getting stuck in the non-ready state.
> Fix readiness probe when sidecar injector is disabled

- tools/istio-iptables/pkg/cmd/root.go
Currently, istio-iptables command flag usage sentences don't have a good alignment, some of them ends with a period, but some of them don't, this PR aim to align command flag usage sentence ends with a period.
> Align command flag usage sentence ends with a period

- pilot/pkg/features/pilot.go
- pkg/queue/instance.go
- pkg/queue/instance_test.go
- pkg/queue/metrics.go
- pkg/queue/metrics_test.go
- releasenotes/notes/45734.yaml
The PR adds metrics to the K8s worker queue. The metrics really helped to discover a lock contention issue mentioned in https://github.com/istio/istio/issues/44985.
The metrics are kept behind the flag, so that they can be enabled explicitly as adding them does result in impacted benchmarks.
> Queue metrics

- go.mod
- go.sum
In addition to other fixes, this unblocks Go 1.21 (and will never block a new Go version again - yay)
> Bump quic-go to v0.37.0

- bin/build_ztunnel.sh
`bin/build_ztunnel.sh` was copying the debug binary regardless of `BUILD_ZTUNNEL_PROFILE`.
I've tested this with `make build` and `make docker`. Not sure how else I can test this.
> Copy correct Ztunnel build

- pilot/pkg/server/instance_test.go
this PR proposes to change `shortDuration` from 1 second to 10 millis, reducing the execution time from ~1s to 0.02s
contributes to #37555
> reduced shortDuration from 1 sec to 10 millis

- pilot/pkg/model/network.go
- pilot/pkg/model/network_test.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/endpoint_builder.go
- pilot/pkg/xds/ep_filters.go
- releasenotes/notes/46088.yaml
When the cluster uses DNS resolution, we can just send the hostname rather than doing in-control plane resolution.
I could see an argument that this should only occur when ResolveHostnameGateways is off, but I think it should also be possible to use that for EDS, and this for CDS(DNS)
solves #45506 along with #45733
> allow unresolved gateway addresses

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/networkfilter.go
- pilot/pkg/networking/core/v1alpha3/tls.go
- pilot/pkg/networking/telemetry/telemetry.go
- pilot/pkg/networking/telemetry/telemetry_test.go
Use endpoint port for inbound stat prefix instead of service port
> use endpoint port for inbound stat name prefix

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
- pilot/pkg/config/kube/gateway/gatewayclass.go
- pilot/pkg/config/kube/gateway/testdata/deployment/custom-class.yaml
Today, we don't actually support custom GatewayClass names, violating
the spec. This makes use support them and adds tests.
Thi also improves the test to be more of a blackbox and test more parts
of the code.
> gateway-api: proper gateway class lookup

- common/scripts/tracing.sh
Should be the last pass of this.
I tested with the following script (key was setting nonuser to get the failure we are seeing before the fix):
```
#!/bin/bash
set -o nounset
if [[ -n "${PULL_NUMBER:-}" ]]
then
set +o nounset
url="https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/${REPO_OWNER}_${REPO_NAME}/${PULL_NUMBER}/${JOB_NAME}/${BUILD_ID},"
else
set +o nounset
url="https://prow.istio.io/view/gs/istio-prow/pr-logs/${JOB_NAME}/${BUILD_ID},"
fi
set -o nounset
echo ${url}
echo "ci.pipeline.run.pull_number=${PULL_NUMBER:-none},"
```
> Fix tracing in postsubmit tests

- cni/pkg/plugin/plugin.go
Current istio-cni prints the following log message:
```
$ kubectl logs -n istio-system istio-cni-node-95f24
...
2023-07-27T03:08:35.936079Z	info	cni	excluded because it has proxy type istio-system%!(EXTRA string=ztunnel-9fgjp, string=ztunnel)
```
It is obviously contains wrong log format. 
> Fix log format for non sidecar type in CNI

- tests/integration/pilot/gateway_test.go
This check happens in https://github.com/istio/istio/blob/8f378324c05a945ab1cceafe714e79546c91dd85/pkg/test/framework/components/crd/gateway.go#L68 while deploying the APIs. There is also a subtest to check the status.
> remove  gatewayclass since its already present

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/networking/util/util_test.go
By setting tls.mode SIMPLE, the user is signaling that they want to opt out of mTLS, Istio managed or otherwise. Since ALPN rewrite exists solely for the purpose of starting Istio mTLS, it violates the user’s intent to perform said rewrite.
This PR checks if the TLS mode is simple and then adds a field to the filter metadata to indicate whether the proxy should proceed with the alpn header rewrite.
Partially fixes #40680
Istio/proxy change: https://github.com/istio/proxy/pull/4783
> Set alpnOverride depending on TLS Mode

- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/testdata/benchmarks/authorizationpolicy.yaml
- pilot/pkg/xds/testdata/benchmarks/auto.yaml
- pilot/pkg/xds/testdata/benchmarks/disabled.yaml
- pilot/pkg/xds/testdata/benchmarks/http.yaml
- pilot/pkg/xds/testdata/benchmarks/strict.yaml
- pilot/pkg/xds/testdata/benchmarks/tcp.yaml
- pilot/pkg/xds/testdata/benchmarks/telemetry.extra.yaml
A variety of fixes
* Currently, the main test is totally broken for listeners since we
don't set a VIP. So 99% of the listeners conflict and are just ignored
entirely. Instead, properly set a vip.
* Split TCP, TLS, HTTP, and Auto so we can accurately measure the
differences between them and not be skewed
* Remove legacy Telemetry v2 Envoyfilter stuff; its not used or working
anymore
* Cleanup PA tests to only test clusters, rest is a waste
* Simplify NDS tests, no need to run the same test over and over
> xds: improve benchmark tests

- pkg/slices/slices.go
- pkg/slices/slices_test.go
Was going to use this in another PR. Ultimately decided no need for Delete, but still a good improvement for when/where we do use it.
> slices: Ensure GC on Delete(), per upstream recommendation

- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
Always enable continue_on_listener_filter timeout, so that we do not need to distinguish Listener filter timeout nil with 0.
Actually, this field only take effect when timeout set.
> Always enable listener.ContinueOnListenerFiltersTimeout

- pilot/pkg/model/virtualservice.go
- pilot/pkg/model/virtualservice_test.go
There's a new field `mirrors` after the client-go is merged, which results in the test flake.
See https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46241/unit-tests_istio/1686266642125819904
> Fix test flake TestFuzzMergeHttpRoute

- pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_workloadentry_test.go
- releasenotes/notes/46267.yaml
Resolves https://github.com/istio/istio/issues/46267. 
If you have an existing workload entry and update the spec, ztunnel will not receive the updated WDS information. This PR fixes that.
> Fix ambient `WorkloadEntry` update xds events

- istioctl/pkg/precheck/precheck.go
- releasenotes/notes/46072.yaml
Since precheck is using analyze messages, it can be specified with format option like json,yaml as well to gather more information from the output instead of only logs.
> Add output format option to precheck

- istioctl/pkg/verifier/verifier.go
- releasenotes/notes/46104.yaml
When using verify-install and Istiod is not ready, the output results are incorrect:
```
istioctl verify-install                                         
1 Istio control planes detected, checking --revision "default" only
✔ ClusterRole: istiod-istio-system.istio-system checked successfully
...
✘ Deployment: istiod.istio-system: Istio installation failed, incomplete or does not match "generated from in cluster operator installed-state": waiting for deployment "istiod" rollout to finish: 0 of 1 updated replicas are available
✔ ConfigMap: istio-sidecar-injector.istio-system checked successfully
✔ MutatingWebhookConfiguration: istio-sidecar-injector.istio-system checked successfully
...
Checked 15 custom resource definitions
Checked 0 Istio …
```
> Fix incorrect verify-install deployment count

- pilot/pkg/autoregistration/controller.go
- pilot/pkg/autoregistration/controller_test.go
- pilot/pkg/features/pilot.go
- pilot/pkg/xds/vm_test.go
- pkg/adsc/adsc.go
- pkg/istio-agent/xds_proxy_test.go
(cherry picked from commit b6eefaf3045227431b60384002e5b0c57740288d) (cherry picked from commit 0183f2886bc078e8df4d6bbd21fa452a3a23481d)
This is a cherrypick from a CVE release. This is its first time on master. Feel free to suggest changes, but not this is already merged + shipped on all release branches so its a bit atypical
> Add validation of workload entry identity (#117)

- istioctl/pkg/validate/validate.go
The flag is not being used anywhere in the project, and I guess it's been related to the mixer migration.
> Mark validate referential flag as hidden because of no usage

- istioctl/pkg/install/k8sversion/version.go
- istioctl/pkg/install/k8sversion/version_test.go
Based on https://github.com/istio/istio.io/commit/ab9c5afdc7770986b41b32fa017b21c1372b782b for istioctl to generate warnings for 1.19 release, similar to what we've done in the past.
~I'll try to do a follow-up that set up a script to automatically update it from the doc site.~
I think sometimes the supported version was updated for the release at the last minute, which result in it not being updated on time. It might be better to just update it manually.
> Update min k8sversion to 1.25

- istioctl/pkg/revision/revision.go
- releasenotes/notes/46257.yaml
The tag command has been graduated for 2 years, and we don't need this command to be in two different places.
> Remove experimental revision tag command

- pilot/pkg/networking/core/v1alpha3/fake.go
- pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
- pilot/pkg/serviceregistry/aggregate/controller_test.go
- pilot/pkg/serviceregistry/memory/discovery.go
- pilot/pkg/xds/eds_sh_test.go
- pilot/pkg/xds/eds_test.go
- pilot/pkg/xds/fake.go
These tests have been using some hacky code to workaround bugs in the
memory registry where it does not call the proper `*Update` callbacks on
XDSUpdater. This fixes up all these cases.
No user facing changes, just making the tests more realistic.
> Cleanup legacy EDS tests

- pilot/pkg/networking/core/v1alpha3/fake.go
- pilot/pkg/serviceregistry/aggregate/controller_test.go
- pilot/pkg/serviceregistry/instance.go
- pilot/pkg/serviceregistry/memory/discovery.go
- pilot/pkg/serviceregistry/mock/discovery.go
- pilot/pkg/xds/delta_test.go
- pilot/pkg/xds/eds_sh_test.go
- pilot/pkg/xds/eds_test.go
- pilot/pkg/xds/fake.go
- pilot/pkg/xds/simple.go
- tests/fuzz/aggregate_controller_fuzzer.go
followup to https://github.com/istio/istio/pull/46333
This fixes EDS flakes, by making the mem registry more compliant with how controllers should behave. Mostly just around calling the right handlers at the right time.
This impacts tests only
All tests now pass >1000 iterations (except https://github.com/istio/istio/issues/46361, broken before my other PR)
> Fix EDS test flakes

- pilot/pkg/model/service.go
- pilot/pkg/model/service_test.go
- pilot/pkg/serviceregistry/aggregate/controller.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/eds_test.go
- pkg/bootstrap/config.go
- pkg/test/util/assert/assert.go
- releasenotes/notes/locality-service.yaml
Split out from https://github.com/istio/istio/pull/46295/files
This *is* user facing. If a user had a pod without Service before, we would ignore locality. Now we do not. I *think* this is the last case of "You must have a service" requirement, but need more investigation before we fully drop that from
https://istio.io/latest/docs/ops/deployment/requirements/
The primary change is to use GetProxyWorkloadLabels instead of GetProxyServiceInstances. An issue with this is that the SE and k8s controller are behaving differently - one sets istio-locality label (synthetic) and the other the 3 k8s labels (also synthetic). This moves the k8s controller to use labelutil.AugmentLabels (and thus the 3 k8s labels), and the SE controller to properly respect the istio-locality label. This makes the two …
> locality: refactor and drop Service dependency

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/filterchain_options.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_builder.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
- pilot/pkg/networking/core/v1alpha3/networkfilter.go
- pilot/pkg/networking/core/v1alpha3/tls.go
- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
- pilot/pkg/networking/grpcgen/lds.go
- pilot/pkg/networking/networking.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/xds/testdata/benchmarks/empty.yaml
This PR does a major refactoring of outbound listener generation. My original motivation was to enable some changes to the XDS generation, which I have decided not to do.
As a result, this should be purely a refactoring that simplifies code and improves performance. **There is no intended behavior changes**.
**Overview of old code:**
For each service/explicit entry, we build a full Listener. This may conflict with another one, stored in a ListenerMap. During each conflict, we merge the listeners into a single one (if possible), or throw it out entirely.
This is extremely inefficient: we build a ton of things that we immediately throw away. For example, consider 1000 HTTP services on port 80. We build one HCM in the end, but we setup 1000 Listener objects then throw away 999 of them.
This …
> Cleanup listener generation

- go.mod
- go.sum
Update go-control-plane to match commit prior to envoy 1.27 release
> Use go-control-plane from last 1.27 cut

- pkg/kube/client.go
- pkg/kube/portforwarder.go
- pkg/test/framework/components/cluster/kube/factory.go
Currently we use our own PortManager, which is known to be best-effort
and often runs into port conflicts. With this, we let the OS assign us a
port which cannot fail (unless we run out of ports, of course).
This should have no impact on users of port-forward; they always had to
call Address() after running.
> tf: properly assign available port for port-forward

- pilot/pkg/serviceregistry/serviceregistry_test.go
This was flaky because we do not trigger ProxyUpdate on node changes. Instead make the objects present when we start. This is sort of a real bug, but triggering proxy update on node changes seems expensive and cannot really happen in real world anyways
> Fix flake in new TestLocality test

- pkg/test/framework/components/echo/common/call.go
The deferred call's arguments are evaluated immediately, but the function call is not executed until the surrounding function returns.
see example in https://go.dev/play/p/cyhhUBcZUJj
> [Test Framework] Fix incorrect duration in log

- tools/bug-report/pkg/bugreport/bugreport.go
The deferred call's arguments are evaluated immediately, but the function call is not executed until the surrounding function returns.
There's a quick way to tell if the runtime is correct: manually add a 1s delay using `time.Sleep(time.Second)` in each function that needs to log time, and if the time is still less than 1s in the log, then it must be wrong.
The diff is as follows:
```diff
diff --git a/tools/bug-report/pkg/bugreport/bugreport.go b/tools/bug-report/pkg/bugreport/bugreport.go
index 33cbd7db7b..9c01fc3610 100644
--- a/tools/bug-report/pkg/bugreport/bugreport.go
+++ b/tools/bug-report/pkg/bugreport/bugreport.go
@@ -213,6 +213,7 @@ func runBugReportCommand(ctx cli.Context, _ *cobra.Command, logOpts *log.Options
func …
```
> Fix some time measurement for istioctl bug-report command

- prow/release-commit.sh
I'm running this to allow any 1.19 RM to approve this.
This is an update_dps.sh run after all the latest PRs were merged. The only difference from the prior PR is likely a common-files update to release-builder to pick up the Go 1.21.0 image.
> [release-1.19] Run update_deps

- istioctl/pkg/writer/envoy/configdump/listener.go
Before we duplicate the object, so we end up printing
`listener/listener/listener/...`
> Avoid mutating object in `istioctl pc all` to avoid duplicate prefix

- pilot/pkg/model/fuzz_test.go
- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/util/workloadinstances/index_test.go
- pkg/test/util/assert/assert.go
This allows each type to specify how they should be compared, rather
than forcing each test to do remember to do so. This should make testing
objects more straightforward.
> testing: better cmp opts

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
- releasenotes/notes/46465.yaml
LoadBalancer ingress IPs are explicitly optional - so `getVIPs` should exclude empty IP strings to avoid MustParse panics
> Fix MustParse crash if ingress doesn't have an IP

- istioctl/pkg/cli/mock_client.go
- pkg/kube/portforwarder.go
- pkg/test/framework/components/echo/deployment/builder.go
- pkg/test/framework/components/echo/kube/workload.go
- pkg/test/framework/components/echo/kube/workload_manager.go
Port forward is not 100% reliable and actually fails a decent amount.
When this happens, we just break forever.
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46400/integ-pilot-multicluster_istio/1689018314652651520
is an example.
In this PR, we have a (somewhat crude) mechanism to detect the
port-forward was terminated and reconnect.
I also considered making the port-forwarder do this transparently, but
its too complex because that means the Address() can change dynamically
which makes it harder to consume - best to do it explicitly.
To test this, I ran a fake test that just sends in a loop:
```go
func TestPortForward(t *testing.T) {
framework.
NewTest(t).
Run(func(t framework.TestContext) {
for {
time.Sleep(time.Second)
t.Logf("howardjohn: sending...")
t0 := …
```
> test framework: detect and reconnect if port-forward is terminated

- bin/update_proxy.sh
https://github.com/istio/proxy/pull/4891 removed the Wasm metadata exchange from the build. The update_proxy script verifies that it is there so it is now failing (ex: https://prow.istio.io/view/gs/istio-prow/logs/update-istio_proxy_postsubmit/1690592966046912512). This remove the check.
> wasm metadata exchange removed from proxy build

- pkg/test/framework/components/opentelemetry/kube.go
- pkg/test/framework/components/zipkin/kube.go
- tests/integration/telemetry/tracing/tracing.go
Reverts istio/istio#46502
This breaks ipv6. Not sure a better way to handle it for now...
> Revert "test framework: drop sslip.io dependencyfor tracing tests"

- pilot/pkg/serviceregistry/kube/controller/network.go
- pilot/pkg/serviceregistry/kube/controller/network_test.go
- releasenotes/notes/46437.yaml
This PR fixes https://github.com/istio/istio/issues/46435
We no longer want to short circuit our NetworkGateways logic based on if there are no `networkGatewaysBySvc`, because there could still be `networkGatewaysByResource`.
> NetworkGateways no longer short circuits if no networkGatewaysBySvc

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_logging.go
- pilot/pkg/model/telemetry_logging_test.go
- pilot/pkg/model/telemetry_metric_test.go
- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
- pilot/pkg/xds/debug.go
```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
name: default
spec:
tracing:
- providers:
- name: envoy
```
causes a crash.
This fixes the crash. In addition, it adds a per-proxy debug interface to `telemetryz` for better debugging, and tries to improve the exhaustiveness checks to prevent future bugs (Go can't handle this well :shrug: )
> telemetry: fix crash with bad provider config

- pilot/pkg/config/kube/gateway/controller.go
- pilot/pkg/features/pilot.go
- releasenotes/notes/46553.yaml
By setting the environment variable PILOT_ENABLE_GATEWAY_API_GATEWAYCLASS_CONTROLLER to false, users can instruct pilot not to create and manage the default GatewayClass objects. This lets other controllers manage these (or different) GatewayClasses.
> Add option to disable creation and management of default GatewayClasses

- go.mod
- go.sum
Update  github.com/docker/docker to include fixes for CVE-2023-28840, CVE-2023-28842 and CVE-2023-28841
> Update docker/docker dep for latest CVE fixes

- pilot/pkg/config/kube/gateway/context.go
- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/deploymentcontroller.go
This changes waypoint Gateway's to report IP address as status instead of Hostname. This will allow us to ready Gateway's for waypoints instead of Service, helping with things like https://github.com/istio/istio/issues/46495.
This moves towards the goal of having Waypoints solely configured based on Gateway, with the Service/Pods being an implementation detail that is not depended on. This would allow, for example, running the waypoint via a different mechanism.
hold: discussing with gateway community if this makes sense
> Improve address configuration for waypoints

- pilot/pkg/model/network.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_serviceentry_test.go
Fixes the wrong nil check in `pilot/pkg/model/network.go` and fixes a potential test race that reads memory that should be behind a read lock.
> Fix potential test flake and wrong map nil check

- pkg/config/analysis/analyzers/testdata/virtualservice_destinationhosts.yaml
- pkg/config/analysis/analyzers/util/service_lookup.go
- releasenotes/notes/46597.yaml
Fixes https://github.com/istio/istio/issues/46597
When a ServiceEntry exports to a namespace by name (rather than wildcard `"*"`), any VirtualService in that target namespace which references the ServiceEntry's hostname was showing as an error.
<details open>
<summary>Example Config showing the issue</summary>
```yaml
metadata:
name: external-svc-virtualdestination
namespace: foo
spec:
hosts:
- foobar.staging.mesh
location: MESH_INTERNAL
ports:
- number: 80
name: https
protocol: HTTP
targetPort: 80
resolution: DNS
exportTo:
- "bar" # Note exporting to the bar namespace of the VS below
---
metadata:
name: foo-route
namespace: …
```
> Fix Istioctl Analyze not consistently respecting Exports for ServiceEntry used by VirtualService

- pkg/platform/platform.go
Istiod reports this at initialization:
```
warn	Invalid environment variable value `gcp` defaulting to "": invalid character 'g' looking for beginning of value
```
No matter the value this variable is assigned.
Using the type `string` directly fixes it.
> Fix platform type

- pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_serviceentry_test.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
Wrong key used when adding a WorkloadEntry to the ambient index caused duplicated entries with similar UIDs but different keys in some scenarios.
> Fix wrong key when adding a WE to Ambient index

- security/pkg/pki/ca/ca.go
Set root-cert.pem when creating istios generated self-signed ca cert.
Resolves #46600
**Testing:**
- This regression may have been caught by the downgrade equivalent of `revisioned_upgrade_test.go`. It might be worth revisiting https://github.com/istio/istio/pull/46213
**Open Questions:**
- What was the reasoning behind not setting `root-cert.pem` in the self-signed istiod generated ca secret? Will setting this field have any unintended consequences for the user?
> Set root-cert.pem to ca-cert.pem in ca secret

- go.mod
- pkg/adsc/adsc.go
- pkg/adsc/adsc_test.go
`sync.WaitGroup` is only present because tests depend on this. Tests can be written in a way that will not require this by using retry with backoff. This is a much safer solution with a built in timeout. This will remove the risk of production code changing in a way that will cause this particular test to wait forever.
> Remove sync.WaitGroup from production code in adsc

- pilot/pkg/serviceregistry/kube/controller/controller.go
- releasenotes/notes/46614.yaml
It seems strange and incorrect to me to perform the update when the ambient label is changed - without checking the value. I think all of the resources have been processed when the namespace or pod is added.
> Ambient: fix incorrect updates when ambient namespace label is changed

- cni/pkg/ambient/net_linux.go
Fix istio-cni-node crash when the Kubernetes pod network is not implemented using veth
> Fix istio-cni-node crash when the Kubernetes pod network is not implemented using veth

- pkg/test/framework/components/echo/cmd/echogen/testdata/golden.yaml
- pkg/test/framework/components/echo/common/deployment/echos.go
- pkg/test/framework/components/echo/config.go
- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/components/echo/kube/templates/deployment.yaml
- pkg/test/framework/components/echo/kube/testdata/basic.yaml
- pkg/test/framework/components/echo/kube/testdata/disable-automount-sa.yaml
- pkg/test/framework/components/echo/kube/testdata/healthcheck-rewrite.yaml
- pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions-no-proxy.yaml
- pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions.yaml
- pkg/test/framework/components/echo/kube/testdata/multiversion.yaml
- pkg/test/framework/components/echo/kube/testdata/proxyless-custom-image.yaml
- pkg/test/framework/components/echo/kube/testdata/proxyless.yaml
- pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml
- pkg/test/framework/resource/flags.go
- pkg/test/framework/resource/settings.go
- tests/integration/ambient/main_test.go
- tests/integration/pilot/common/traffic.go
fixes #43508 
I wanted to preserve the ability to use the `ambientEverywhere` flag (renamed) to force existing tests to use ambient. That could use some more cleanup, but this removes the need to pass anything special to run ambient tests.
We still need a ~global signal that ambient is in use so we can skip stuff. Maybe in the future we can make it more workloadClass oriented.
> tf: cleanup ambient flag

- pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_serviceentry_test.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_workloadentry_test.go
When applying an authz policy with selector it currently doesn't apply to WE that were inlined in SE ([endpoints](https://istio.io/latest/docs/reference/config/networking/service-entry/#ServiceEntry)).
> Authz for Inlined WorkloadEntries in Ambient

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- tests/integration/pilot/main_test.go
- tests/integration/tests.mk
Even though we have a dual-stack pre-submit job, the dual-stack flag seems to be set only in the security tests. See: https://github.com/istio/istio/blob/3e8f29a160c06d57dc0436f8d9ce7db72f3de4b1/tests/integration/security/main_test.go#L52
> Enable dual-stack for pilot integration tests

- tests/integration/pilot/gateway_conformance_test.go
Reverts istio/istio#46642 because apparently Gateway API changes didn’t fix it
> Revert "Remove skip for ipv6 gateway api"

- tests/integration/pilot/common/traffic.go
The cleanup condition in the traffic tests cause CRs between contexts to not be cleaned up if `istio.test.nocleanup` is set. The expected behavior should be that only deployments and services are preserved, whereas CRs and configs are always cleaned up regardless.
> Remove conditional cleanup from traffic test

- pilot/pkg/config/kube/gateway/conversion.go
Set it to `Hostname` when reporting an external address.
Otherwise we get:
```
2023-09-01T14:34:05.859797Z	error	status	Encountered unexpected error updating status for &{{gateway.networking.k8s.io/v1beta1/Gateway bdf115cc-e417-4f14-ba45-216caaa5c133 bookinfo-gateway book cluster.local map[] map[gateway.istio.io/controller-version:5 kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"gateway.networking.k8s.io/v1beta1","kind":"Gateway","metadata":{"annotations":{},"name":"bookinfo-gateway","namespace":"book"},"spec":{"gatewayClassName":"istio","listeners":[{"allowedRoutes":{"namespaces":{"from":"Same"}},"name":"http","port":80,"protocol":"HTTP"}]}}
] 91705 2023-09-01 14:33:56 +0000 UTC [] 1} 0xc004fcb488 0xc00396ec80}, will try again later: Gateway.gateway.networking.k8s.io …
```
> gateway api: Fix the status address type

- pilot/pkg/xds/statusgen.go
Fix #42448.
When istioctl invoke `proxy status` connect right when the envoy disconnects, `debugConfigDump` func will print fail log as in issue, and return nil resource, nil resource will not send response so istioctl hang to timeout.
Fix it by returning empty resource when encountering error, it's reasonable for debug interface returning empty response when encountering error(I don't find a proper way to return an error response).
> fix TestXdsProxyStatus flake: race condition in connection

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_workloadentry_test.go
- pilot/pkg/serviceregistry/kube/controller/network.go
- releasenotes/notes/46540.yaml
- gateway status updater avoids populating the address field if there are no pods in the deployment ready
- gateway status updater prevents removing this if deployment become unready
- move waypoint configuration from svc to kube gateway
- new kube gateway handler only configures waypoint once the address field is populated on the kube gateway resource
addresses #46495
> adding waypoints should be non-disruptive

- tools/bug-report/pkg/content/content.go
These can often cause dropped requests
> Report networkpolicies in bug-report

- pilot/pkg/serviceregistry/kube/controller/controller_test.go
If an error occurs, the value of svc will be overwritten and the print error message will be empty
> If an error occurs, the value of svc will be overwritten and the print error message will be empty

- pilot/pkg/xds/endpoints/endpoint_builder.go
This line assumes we will hit this logic later:
https://github.com/istio/istio/blob/93758c226683acea24867e365386ab4da567444f/pilot/pkg/xds/endpoints/ep_filters.go#L96-L101
But that logic is skipped if there are 0 gateways total:
https://github.com/istio/istio/blob/93758c226683acea24867e365386ab4da567444f/pilot/pkg/xds/endpoints/ep_filters.go#L40-L43
> guarantee we don't end up with empty address endpoints

- pkg/kube/watcher/configmapwatcher/configmapwatcher.go
- releasenotes/notes/mesh-sync.yaml
We do not check the handler is synced, so we can return too early and
miss the config. This results in using the default MC instead of the one
from configmap.
for https://github.com/istio/istio/issues/45739 (not fixes, there is
some followup).
1.19 is already fixed by a larger refactor, so this is a targetted fix.
> Fix mesh config sync

- pkg/test/framework/components/istio/kube.go
- tests/integration/pilot/main_test.go
- tests/integration/security/main_test.go
- tests/integration/tests.mk
Currently the tests are run without enabling this flag for majority of tests. Only some of the pre-submit
tests were enabling the flag. So, let us try to enable the required DUAL_STACK flags at the framework level.
> Enable DUAL_STACK flags at test framework level

- istioctl/pkg/proxyconfig/proxyconfig.go
- releasenotes/notes/fix-proxyconfig-endpoints-json.yaml
- tests/integration/pilot/istioctl_test.go
Fix the output of `istioctl proxy-config all` to include EDS configuration when the `--json` or `--yaml` flags are used. Also add a test
> Add endpoints to proxy-config all output

- go.mod
- go.sum
Manual cherry pick of #46883.
Fixes https://github.com/istio/istio/issues/46891
> [release-1.17] Manual cherrypick of #46883 - Bump github.com/cyphar/filepath-securejoin from 0.2.3 to 0.2.4

- pkg/test/framework/components/istio/config.go
- pkg/test/framework/components/istio/configmap.go
- pkg/test/framework/components/istio/flags.go
* Add shared mesh config option to e2es
* rm artifacts files
* Update methods
* Remove extra flag
* Adjust spacing
* Import istio
* fix return
* Fix nil check
* Fix var assignment
* Fix flag
---------
Resolves: https://github.com/istio/istio/issues/46788
> [cherry-pick 1.18] Add E2E option to patch SHARED_MESH_CONFIG (#46074)

- pilot/pkg/bootstrap/istio_ca.go
- security/pkg/pki/ra/common.go
Value `ISTIOD_RA_ISTIO_API` is no longer supported for `EXTERNAL_CA`. `ISTIOD_RA_KUBERNETES_API` is the only supported value.
> Remove unused external CA type ISTIOD_RA_ISTIO_API

- cni/pkg/ambient/net_linux.go
-------
Tighten the conditions under which we skip packets with a HostIP src (only healthcheck probes). 
Only skip packets coming from a local node socket, versus anything with the node IP.
This should catch HOSTIP-src packets coming from `kubelet` (probes) but not HOSTIP-src packets coming from `kube-proxy` (everything else) 
Previously, we excluded everything with SRC == HostIP from ambient capture and ztunnel proxy. This was done to prevent healthchecks from the node `kubelet` from being proxied thru ztunnel.
The problem with this is that it would allow *any* packet with a HostIP SRC to bypass capture. Including forwarded packets (potentially `kube-proxy` packets, say from a LoadBalancer type Service). This change modifies that so only …
> Ambient/CNI: be more selective about hostIP skips

- istioctl/pkg/analyze/analyze.go
If using kube environment, we can just stop when the get request fails instead of proceeding to next steps, otherwise it continues trying to establish a watch:
```
2023-09-04T02:45:49.407365Z     error   watch error in cluster : failed to list *v1.Pod: Get "https://127.0.0.1:42643/api/v1/pods?limit=500&resourceVersion=0": dial tcp 127.0.0.1:42643: connect: connection refused
2023-09-04T02:45:49.475099Z     error   watch error in cluster : failed to list *v1.MutatingWebhookConfiguration: Get "https://127.0.0.1:42643/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations?limit=500&resourceVersion=0": dial tcp 127.0.0.1:42643: connect: connection refused
2023-09-04T02:45:51.676395Z     error   watch error in cluster : failed to list …
```
> Fix analyze keep watching resources when api server cannot be connected

- go.mod
- pkg/adsc/adsc_test.go
This PR removes the direct dependency `github.com/stretchr/testify` because it's not needed. The package `pkg/test/util/assert` already contains `EventuallyEqual` function which can be used instead.
> Remove github.com/stretchr/testify dependency

- tests/integration/ambient/baseline_test.go
Unskip some ambient sidecar integ tests which were skipped pending merging of completed issues
> unskip some sidecar integ tests in the ambient suite

- architecture/ambient/ztunnel.md
This introduces a new doc giving an overview of ztunnel. This is all around in various places, but spread out through like 20 design docs...
> architecture: add ztunnel.md

- tests/integration/operator/switch_cr_test.go
- tests/integration/operator/uninstall_test.go
1. fail fast
2. reduce `retryTimeOut` to `5m`, this will make test fail fast if there's a network issue.
> e2e: improve operator test

- pkg/config/resource/name.go
Correct typo from 'ParseFullName' to 'ParseFullNameWithDefaultNamespace' in comment.
> Fix typo at name.go

- pilot/pkg/security/authz/builder/builder.go
- pilot/pkg/security/authz/builder/extauthz.go
- pilot/pkg/security/authz/builder/testdata/http/custom-bad-out.yaml
- releasenotes/notes/46968.yaml
Fix https://github.com/istio/istio/issues/46951.
I think this will loose the rbac, however it makes sense to only deny rules that are delegated to the ext authz provider.
> Fix ext authz deny all traffic if encountering error with the provider

- pkg/test/framework/components/echo/config.go
- pkg/test/framework/components/istio/config.go
- pkg/test/framework/components/istio/installer.go
- pkg/test/framework/components/namespace/kube.go
- tests/integration/ambient/main_test.go
- tests/integration/iop-ambient-test-defaults.yaml
`./prow/integ-suite-kind.sh test.integration.ambient.kube` passes just fine. No logner needs a special flag.
It also allows using the flag to turn on ambient in other suites.
> move ambient install into framework

- pilot/pkg/networking/core/v1alpha3/extension/wasmplugin.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
- pilot/pkg/networking/core/v1alpha3/networkfilter.go
- pilot/pkg/networking/core/v1alpha3/networkfilter_test.go
- pilot/pkg/networking/core/v1alpha3/tls.go
- releasenotes/notes/filter-order.yaml
This fixes a few bugs introduced in https://github.com/istio/istio/pull/46514 and adds consistency to the ordering of filters with inbound, outbound, and gateways.
The order is as-follows:
- **Metadata Exchange**
- Custom Authz (ext authz)
- WASM Authn
- **Builtin Authn**
- WASM Authz
- **Builtin Authz**
- WASM Stats
- **Builtin Stats**
- WASM Rest
- **Terminal (TCP/HCM)**
Bugs fixed:
* Wasm outbound network was not implemented for HTTP protocols
* Wasm outbound network for weighted clusters does double appends, so we have many copies of every filter
* Inconsistent filter ordering between inbound, outbound, and gateways. Now all of them follow the above
* Inbound network: MX now comes before istio_authn
* Gateway network: before: [mx, wasm authn, wasm authz, stats, wasm authn, authn, wasm …
> Fix filter ordering and WASM NETWORK implementation

- tests/integration/pilot/common/routing.go
This reverts commit 4e873ff46c2975e2c4d3190a9813087dbbb46825.
Causing flakes: https://prow.istio.io/view/gs/istio-prow/logs/integ-pilot-istiodremote_istio_postsubmit/1702695243045933056
> Revert "add http cookie test case (#46989)"

- tests/integration/ambient/baseline_test.go
> Revert "unskip some sidecar integ tests in the ambient suite"

- tests/integration/pilot/gateway_test.go
- tools/packaging/common/envoy_bootstrap.json
Allows envoy metric scraping (:15090/stats/prometheus) using either pod IP family in dual-stack clusters.
Similar updates to readiness probe listeners done here: https://github.com/istio/istio/pull/47022
> Dual-stack: /stats/prometheus should have both v4/v6 listeners

- pilot/pkg/autoregistration/connections.go
- pilot/pkg/autoregistration/controller.go
- pilot/pkg/autoregistration/controller_test.go
- pilot/pkg/autoregistration/internal/health/controller.go
- pilot/pkg/model/context.go
- pilot/pkg/xds/ads.go
- releasenotes/notes/45329.yaml
- tests/fuzz/autoregistration_controller_fuzzer.go
If I have a few connected proxies before I create the WorkloadGroup we can end up in a state where the entries are never registered. 
This is mostly a UX improvement. A user might not realize the order matters. 
Accidental deletion of a WorkloadGroup can trigger cleanup due to owner refs. Recreating the WorkloadEntries would be delayed without either this patch, or forcing a reconnect to ads from each VM.
> auto-register connected proxies at WorkloadGroup creation

- cni/cmd/istio-cni/main.go
- cni/pkg/config/config.go
- cni/pkg/plugin/iptables_linux.go
- cni/pkg/plugin/plugin.go
- cni/pkg/plugin/redirect.go
- tools/istio-iptables/pkg/capture/run_linux.go
- tools/istio-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/config/config.go
- tools/istio-iptables/pkg/constants/constants.go
- tools/istio-iptables/pkg/dependencies/implementation.go
- tools/istio-iptables/pkg/dependencies/implementation_linux.go
This was added as a temporary feature flag, not intended as a long term
feature. Since we haven't heard any issues with the new approach (which
is used by many other projects) it makes sense to do some cleanup
> iptables: cleanup legacy host nsenter flag

- pkg/kube/client.go
The components are not existing anymore for years. I think later the code can also be removed if we can auto-detect the debug interface port after https://github.com/istio/istio/pull/47045.
> Cleanup some client code

- pilot/pkg/networking/core/v1alpha3/httproute.go
Although it is unusual to disable caching, but from the code perspective it is unnecessary to copy and sort `services` when caching is not enabled.
> do not copy and sort `services` when caching is not enabled

- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go
- pilot/pkg/networking/core/v1alpha3/httproute.go
`FilterInPlace` uses `mutated in place`, so it avoids allocating temporary space during execution.
> optimize envoyfilter REMOVE operation performance

- releasenotes/notes/46935.yaml
- tools/istio-clean-iptables/pkg/cmd/testdata/dns-uid-gid.golden
- tools/istio-iptables/pkg/capture/run.go
- tools/istio-iptables/pkg/capture/testdata/dns-uid-gid.golden
- tools/istio-iptables/pkg/capture/testdata/ip-range.golden
- tools/istio-iptables/pkg/capture/testdata/loopback-outbound-iprange.golden
- tools/istio-iptables/pkg/capture/testdata/tproxy.golden
Fixes https://github.com/istio/istio/issues/46935. Also cleaned up a couple places where comments did not match code that I saw when trying to track this down originally.
> Correctly assign conntrack zone to return packets from upstream DNS resolvers.

- pilot/pkg/model/sidecar.go
Fixes https://storage.googleapis.com/istio-prow/logs/integ-distroless_istio_postsubmit/1706750269011791872/artifacts/pilot-24ed18b8836d4a0e86dad5350/_suite_context/istio-state-620402818/primary-0/istiod-f7f8bfb76-t25br_discovery.previous.log. This can happen when DR references a removed service
> delta xds: fix panic when service is not found

- cni/pkg/ambient/iptables.go
- cni/pkg/ambient/server.go
- tests/integration/ambient/main_test.go
One step closer to distroless support. However, we still use `ip` which isn't in the image.
> cni: move ambient iptables detection off bash

- pilot/pkg/bootstrap/server.go
fix for https://github.com/istio/istio/pull/46536 which adds an empty DNS name to the SAN list.
> fix Istiod DNS names

- releasenotes/notes/iptables-lock.yaml
- tools/istio-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/config/config.go
- tools/istio-iptables/pkg/constants/constants.go
- tools/istio-iptables/pkg/dependencies/implementation.go
- tools/istio-iptables/pkg/dependencies/implementation_linux.go
- tools/istio-iptables/pkg/dependencies/implementation_test.go
Our current iptables locking strategy is "retry a few times if we fail to get the lock". This is broken in a number of different ways, depending on the environment.
For background, iptables execution is network namespace scoped, but the lock is in the filesystem. We want exclusive access in the network namespace when we do any writes.
iptables 1.6.2 adds locking to iptables-restore. Before then, there is no locking in this command since its atomic -- but the lock ensures that others using raw `iptables` commands do not cause issues.
In CNI, we are in the host filesystem. So the lock we acquire is the host lock -- the same one kube-proxy and others acquire. This can cause extreme contention - in some cases we have seen users effectively unable to schedule any pods for hours due to this. …
> Improve iptables locking

- tests/integration/security/jwt_test.go
- tests/integration/security/policy_attachment_only/jwt_gateway_test.go
We were deploying like 5 gateways; that's too much and unnecessary. Now we'll just apply 2
> Don't deploy a bunch of gateways uncessarily for RA tests

- pilot/pkg/config/kube/gateway/context.go
Fixes #44850 by not checking port instance existence for managed gateways. If they're managed, we can be pretty confident that endpoints for the port will eventually exist as long as the endpointslice controller is functioning
> Don't check port updates for managed gateways

- pilot/pkg/autoregistration/controller.go
- pilot/pkg/config/aggregate/config.go
- pilot/pkg/model/destination_rule.go
- pilot/pkg/model/virtualservice.go
- pilot/pkg/networking/apigen/apigen.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- pilot/pkg/serviceregistry/serviceentry/store_test.go
- pilot/pkg/serviceregistry/serviceentry/util.go
- pkg/config/model.go
Optimizations to SelectVirtualServices which is a very hot method:
- use `types.NamespacedName` as `set` type to avoid string concatenation and allocations
- move `vsset.Contains` to the top, to prevent multiple checks for each non-matched rule
- use `return` instead of `break` to break both loops instead of only one
> optimize: select virtual services

- pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
- pkg/config/mesh/kubemesh/watcher_test.go
Somehow is fine in CI, but on my machine this times out like 100% of the
time. 1s is pretty tight window
> bump some test timeouts

- tools/istio-iptables/pkg/dependencies/implementation.go
- tools/istio-iptables/pkg/dependencies/implementation_linux.go
on mac:
```
GOOS=darwin GOARCH=arm64 LDFLAGS='-extldflags -static -s -w' common/scripts/gobuild.sh /Users/xiaopenghan/go/src/istio.io/istio/out/darwin_arm64/ -tags=agent ./pilot/cmd/pilot-agent
tools/istio-iptables/pkg/dependencies/implementation.go:94:41: undefined: IptablesRestoreLocking
make: *** [build] Error 1
```
> Fix istioctl build failed

- istioctl/pkg/root/root.go
If using crd watcher in the code, there will be unexpected logs to the output like:
```
istioctl analyze -A
2023-10-08T03:26:17.713436Z     info    controllers     starting        controller=crd watcher
Warning [IST0158] (Namespace default) The Istio proxy images of the pods running in the namespace do not match the image defin
```
> Fix istioctl using crd watcher logging issue

- pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go
- pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer_test.go
- pilot/pkg/serviceregistry/util/label/label.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/47099.yaml
Related to https://github.com/istio/istio/issues/47068
Failover and FailoverPriority can't be used together at the moment. There is no validation as such to prevent this but `FailoverPriority` takes precedence in case it is defined. There could be a requirement such that failoverPriority should be considered for calculating priorities of endpoint and at the same time of failover is defined it can be taken into account for determining priorities of the endpoints remaining.
The example is given in the issue attached.
This PR needs a document change if merged
> regional failover to work with failover priority

- istioctl/pkg/proxyconfig/proxyconfig.go
- releasenotes/notes/47252.yaml
1. Currently there's no mention of how to set all loggers to a level in `proxy-config log`. Upon looking through the code I found it could be set directly with `istioctl pc log pod-name --level debug`, added an explaination to the flag description.
2. Also, this can not be configured intuitively like the Envoy style - other separate loggers are conforming this format:
```
curl localhost:15000/logging?level=debug
```
So the defaultLogger check to set all active loggers has been excluded.
3. The `output` flag is a persistent flag of proxy-config, and it's not funcioning in this command, added an info log.
> Improve proxy-config log command with envoy all loggers format

- pkg/dns/client/dns.go
- pkg/dns/client/dns_test.go
- releasenotes/notes/47290.yaml
As reported on #47264, the DNS Proxy component is capable of returning a CNAME chained response for wildcard `ServiceEntry` objects. Unfortunately, this only worked for `musl` based DNS resolution leading to a few inconsistent reports of DNS resolution issues, likely on `glibc` based systems.
The issue on `glib` was a long-standing [problem reported in 2010](https://sourceware.org/bugzilla/show_bug.cgi?id=12154) and fixed in `glibc 2.37` in 2022-08-30. Considering the DNS Proxy feature was added in Istio 1.11 back in 2021, it was only possible to validate the DNS Proxy wildcard feature in `musl`, which is also the default on the contaienrs used on the sample.
Now that `glibc` fix has been backported to `glibc 2.34+` and picked up by a few distros (eg: [Debian …
> Adjust DNS Proxy CNAME wildcard response to be compatible with glibc and musl

- samples/security/spire/spire-quickstart.yaml
The image used for spire-agent is old and using that https://github.com/istio/istio/blob/9efde960c9150864cda1c5384a111cca510fb5f0/samples/security/spire/spire-quickstart.yaml#L848-L853 is not working as expected. This PR matches the image of spire-agent with that of spire-server.
> Update spire-agent image to match spire-server

- samples/open-telemetry/otel.yaml
- samples/open-telemetry/tracing/README.md
I was going through the sample and got stuck with spans not being exported to the OTel collector. In discussions on Slack, it was pointed that the `Telemetry` resource needs to be either deployed on the `istio-system` namespace or on the same namespace where the apps are running. 
The OTel guide here uses the sample apps from the getting started guide https://istio.io/latest/docs/setup/getting-started/#bookinfo, which are deployed on the default namespace, thus if you follow it as is, it does not work. 
This PR does:
- ~~Update the OTel collector image, which is very old. Adapts some minor things that changed~~
- Make it clear that the Telemetry resource needs to be deployed on the default namespace, if you are following the getting started guide
> Clarify telemetry deployment namespace

- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_internal_test.go
- tests/integration/pilot/common/routing.go
[RouterAction.Cors](https://github.com/envoyproxy/envoy/blob/main/api/envoy/config/route/v3/route_components.proto#L154) is deprecated. This PR moves is to Routes' perFilterConfig similar to Fault
> move cors policy to typed per filter config

- cni/cmd/istio-cni/main.go
- cni/pkg/config/config.go
- cni/pkg/plugin/iptables_linux.go
- cni/pkg/plugin/plugin.go
- cni/pkg/plugin/redirect.go
- releasenotes/notes/iptables-lock.yaml
- tools/istio-clean-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/capture/run_linux.go
- tools/istio-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/config/config.go
- tools/istio-iptables/pkg/constants/constants.go
- tools/istio-iptables/pkg/dependencies/implementation.go
- tools/istio-iptables/pkg/dependencies/implementation_linux.go
- tools/istio-iptables/pkg/dependencies/implementation_test.go
Cherrypicks of some CNI changes, the most important of which is avoiding taking the host level iptables file lock, which was leading to some significant lock contention and scaling issues. Also includes a couple prior adjacent changes that made the cherrypick cleaner.
> cni: 1.19 cherrypicks

- pkg/config/analysis/analyzers/all.go
- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/externalcontrolplane/externalcontrolplane.go
- pkg/config/analysis/analyzers/testdata/externalcontrolplane-missing-urls.yaml
- pkg/config/analysis/analyzers/testdata/externalcontrolplane-using-ip-addr.yaml
- pkg/config/analysis/analyzers/testdata/externalcontrolplane-valid-urls.yaml
- pkg/config/analysis/msg/messages.gen.go
- pkg/config/analysis/msg/messages.yaml
- releasenotes/notes/47269.yaml
Closes: https://github.com/istio/istio/issues/47269
This PR adds a new analyzer for Istio installations that use an External Control Plane: https://istio.io/latest/docs/setup/install/external-controlplane/
The unique aspect of an installation that uses an External Control Plane is that there is both a remote and external cluster. This analyzer works to ensure that [the address of the external `istiod`](https://istio.io/latest/docs/setup/install/external-controlplane/#set-up-the-remote-config-cluster) that the user provides for the remote cluster is valid. We are not checking that the `istiod` service is actually running in the external cluster, but rather that the value provided is a valid address that can be resolved.
> Add `istioctl` Analyzer for External Control Plane Installations

- cni/cmd/istio-cni/main.go
- cni/pkg/config/config.go
- cni/pkg/plugin/iptables_linux.go
- cni/pkg/plugin/plugin.go
- cni/pkg/plugin/redirect.go
- releasenotes/notes/iptables-lock.yaml
- tools/istio-clean-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/capture/run_linux.go
- tools/istio-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/config/config.go
- tools/istio-iptables/pkg/constants/constants.go
- tools/istio-iptables/pkg/dependencies/implementation.go
- tools/istio-iptables/pkg/dependencies/implementation_linux.go
- tools/istio-iptables/pkg/dependencies/implementation_test.go
Cherrypicks of some CNI changes, the most important of which is avoiding taking the host level iptables file lock, which was leading to some significant lock contention and scaling issues.  Also includes a couple prior adjacent changes that made the cherrypick cleaner.
> cni: 1.18 cherrypicks

- pkg/test/framework/components/istio/kube.go
When integration tests are run in dual-stack cluster, gateways should be deployed
as dual-stack. Currently it is run as single stack svcs.
> [dual-stack integration tests] gateway should be a dual-stack svc

- tests/integration/pilot/gateway_test.go
Now that gateway is deployed as a dual-stack service, let us use the service ips for readiness probe tests, instead of podIPs
> update readiness-probe test to use gateway svc ips

- pilot/pkg/model/policyattachment.go
There are too many warning logs for a single gateway-api resource in istiod's log. Maybe the alternative is to move it to a more appropriate location.
> Drop gateway api ignore log to debug

- pkg/bootstrap/platform/gcp.go
To get the info of GCPMetadata, we are logging it in a global variable initialization.
But, since it happen in the global variable initialization, `--log_target` option is not working because the log is running before configuring the flag.
This causes some output mixing up in stdout(e.g., pilot-agent request GET), which is not desired.
This PR simply delete the log because the logging in init is not prefereable.
Change-Id: I9e207e058d6842e021523b6d473670d80c2d114e
> Remove the log being called in init phase

- go.mod
- go.sum
- pkg/config/xds/filter_types.gen.go
Update to the latest go-control plane. This commit is currently on the release-1.20 branch.
> [release-1.20] Update go-control-plane

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_serviceentry_test.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_workloadentry_test.go
- pilot/pkg/serviceregistry/kube/controller/authorization.go
Rewrote the implementation for the SE with endpoints auth policy support.
Previous implementation added an additional WE with the name of the SE to the index. 
This was unnecessary because in the new implementation it is taking into account that there is already a SE entry for each endpoint address and it just makes sure that auth policy for those entries are updated when the SE is selected by an auth policy.
Previous implementation was also incorrect as if there are multiple endpoints defined in the SE it still added only a single WE.
> Modify SE with inlined WE auth policy support

- pkg/kube/mock_client.go
- pkg/kube/portforwarder.go
- pkg/test/framework/components/echo/kube/workload.go
- pkg/test/framework/components/echo/kube/workload_manager.go
Port forward is not 100% reliable and actually fails a decent amount. When this happens, we just break forever.
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/46400/integ-pilot-multicluster_istio/1689018314652651520 is an example.
In this PR, we have a (somewhat crude) mechanism to detect the port-forward was terminated and reconnect.
I also considered making the port-forwarder do this transparently, but its too complex because that means the Address() can change dynamically which makes it harder to consume - best to do it explicitly.
(cherry picked from commit c4c004270ee24e66c52dd6bdc9b2ebfba3eaf471)
**Please check …
> [release-1.18] test framework: detect and reconnect if port-forward is terminated

- pkg/test/framework/components/echo/match/matchers.go
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/common/traffic.go
I took a look at the existing Traffic test cases to confirm which cases need to skip Ambient still and which don't. I've identified `jwt-claim-route` and `autopassthrough` as not having to skip ambient anymore. Basically, there is no difference when changing to `RunCase` from `RunSkipAmbient` for those particular test cases. Also, added a matcher for a `waypointed service` and a `captured service` to validate these cases actually run through Ambient.
Related to #43698
> Unskip ambient tests for jwt-claim-route and autopassthrough.

- pilot/pkg/model/endpointshards.go
- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/xds/eds_test.go
- pilot/pkg/xds/endpoints/endpoint_builder.go
- releasenotes/notes/terminating-headless.yaml
Fixes https://github.com/istio/istio/issues/47348.
In previous versions, we used a different mechanism to get service instances that didn't filter unhealthy endpoints. We then switched to use the unified EDS source.
This fixes this by passing unhealthy endpoints through far enough to include them in SA computation, and filtering later.
This probably needs to be backported.
> Fix traffic to terminating headless services

- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
- releasenotes/notes/envoyfilter-app-protocals-match.yaml
We want to patch filter chains using `EnvoyFilter.ListenerMatch.FilterChainMatch.ApplicationProtocols`, but found it's not working
This field was introduced in https://github.com/istio/api/pull/1026 but not implemented
> EnvoyFilter: support matching ApplicationProtocols

- Makefile.core.mk
Supersedes https://github.com/istio/istio/pull/47588.
New BASE_VERSION images were created across the board yesterday. Unfortunately, the pipeline tried updating the master branch with the 1.20 (https://github.com/istio/istio/pull/47585)  and master (https://github.com/istio/istio/pull/47588) BASE_VERSION images. The 1.20 PR merged first causing a rebase issue with the master PR.
I fixed the pipeline so this own't happen again, and for now the pipeline will find a "good" image (since it was created yesterday) in the master branch although it happens to have a release-1.20 in the name. This will fix itself when the next set of base image are built.
However, since we have the master image already, I just recreated the PR since I can't rebase the …
> Update BASE_VERSION to point to master image

- pilot/pkg/features/pilot.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/model/service.go
- pilot/pkg/model/sidecar.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/httproute_test.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_cache.go
- pilot/pkg/networking/core/v1alpha3/route/route_cache_test.go
- pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
- pilot/pkg/networking/core/v1alpha3/tls.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/kube/conversion.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/fake.go
- pilot/pkg/xds/testdata/benchmarks/externalname.yaml
- pkg/test/framework/components/istio/ingress.go
- releasenotes/notes/external-name.yaml
- tests/integration/base.yaml
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/common/traffic.go
Github won't let me use my old PR (https://github.com/istio/istio/pull/37365) so making a new one...
Fixes https://github.com/istio/istio/issues/37331
Example config:
```yaml
apiVersion: v1
kind: Service
metadata:
name: b-ext
namespace: echo
spec:
ports:
- name: tcp
port: 80
targetPort: 18080
type: ExternalName
externalName: b.echo.svc.cluster.local
```
Kubernetes behavior: `b-ext` creates a CNAME record for `b`. Port is not relevant.
Istio (today): Create a DNS cluster for each port, which ends up resolving to Cluster IP. Match on Host header (http), SNI (tls), or just port (TCP) (meaning it captures all traffic on that port).
Issues:
* Port matters in Istio but not Kubernetes
* We get minimal functionality because we only have the cluster IP. No load balancing, auto mtls, etc
* TCP …
> Better ExternalName support

- prow/release-commit.sh
So that given a commit SHA we can reference an image without having to know which version that commit belongs to.
> Publish the raw commit SHA as a tag to gcr.io/istio-testing

- bin/update_crds.sh
In the release-1.20 branch, the RMs ran `go get istio/api@release-1.20` as part of the update_deps. This updated the go.mod to have a version like:
```
istio.io/api v1.20.0-beta.0
```
The update_crds script failed with this trying to checkout the `beta.0` branch (which doesn't exist). The code was updated for rc and beta similar to the istio/istio code later in the script (noting we have a `.` after beta and rc in our labels) to fix the issue in the release-1.20 branch in https://github.com/istio/istio/pull/47625.
This is a manual cherry pick of the script change only to the main branch.
> Fix update_crds for istio/api having a beta.0 label

- pilot/pkg/model/sidecar.go
- pilot/pkg/model/virtualservice.go
Improve some usages to optimize `ConvertToSidecarScope`'s performance.
```code
goos: darwin
goarch: amd64
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
ConvertIstioListenerToWrapper/small-exact-12        3.353µ ± 0%   3.200µ ± 1%   -4.55% (p=0.002 n=6)
ConvertIstioListenerToWrapper/small-wildcard-12     1.827µ ± 2%   1.785µ ± 1%   -2.30% (p=0.009 n=6)
ConvertIstioListenerToWrapper/small-match-all-12    5.760µ ± 1%   5.272µ ± 1%   -8.46% (p=0.002 n=6)
ConvertIstioListenerToWrapper/middle-exact-12       33.00µ ± 1%   32.35µ ± 1%   -1.98% (p=0.002 n=6)
ConvertIstioListenerToWrapper/middle-wildcard-12    30.70µ ± 2%   30.18µ …
```
> optimize performance

- bin/update_crds.sh
- go.mod
- go.sum
- prow/release-commit.sh
If https://github.com/istio/istio/pull/47633 is merged, the separate update_deps PR could be merged as well instead of this PR which combines the two PRs. The benefit of this PR is that it only requires a single RM approval, where using https://github.com/istio/istio/pull/47614 would require and RM besides @hanxiaop.
The 1.20 RMs opened a PR running update_deps and it failed in a `make gen`
```
error: pathspec 'beta.0' did not match any file(s) known to git
```
This failure is because the update_crds.sh doesn't not understand istio/api on the go.mod with a rc or beta label without a sha.
I updated the code to calculate the correct label. We should copy the script update to the main branch as well.
> release-1.20] Run  update_deps and fix make update-crds (api has beta label)

- pilot/pkg/model/service.go
- pilot/pkg/model/service_test.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
This PR to actually run through service comparison test cases, and ensure model.Service.Resolution is taken into account when comparing model.Services, which is a regression introduced in https://github.com/istio/istio/commit/81ad7b8fcae
> Actually run through TestServicesDiff cases and fix regression

- LICENSE
The "LICENSE" file is supposed to be our inclusion of an exact copy of https://www.apache.org/licenses/LICENSE-2.0.txt as required by section 4(a) of the Apache 2 license.
> Update the license file to be unmodified apache license

- cni/pkg/repair/repaircontroller.go
- pkg/kube/kclient/events.go
The CNI repair is a potentionally very distructive action: deleting
pods. This ought to be as visibile as possible.
Kubernetes defines a standard way to do this, via writing Events. The
controller already has this permission actually, presumably it was
intended to be used but never actually came to fruition.
This PR emits an event for each pod that we label or delete.
> cni repair: add events writing

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_test.go
- releasenotes/notes/47412.yaml
Fixes https://github.com/istio/istio/issues/47412
> Sidecar resources using defaultEndpoint can use ::1 in all cases

- cni/pkg/plugin/iptables_linux.go
- cni/pkg/plugin/plugin_dryrun_test.go
- cni/pkg/plugin/redirect.go
- pkg/flag/flag.go
- pkg/flag/flag_test.go
- tools/istio-clean-iptables/pkg/cmd/root.go
- tools/istio-clean-iptables/pkg/config/config.go
- tools/istio-iptables/pkg/capture/run_linux.go
- tools/istio-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/config/config.go
- tools/istio-iptables/pkg/config/config_test.go
- tools/istio-iptables/pkg/constants/constants.go
- tools/istio-iptables/pkg/validation/validator.go
Currently, we have a complete mess of configuration for the iptables commands. This is driven a few issues:
* It was designed to be *byte for byte* compatible with the original Bash script years ago, so it has a ton of weird bash-isms.
* It is designed exclusively as a command line, but now its used beyond that (in CNI, etc)
* Uses lots of globals, and each config item ends up in 3-4 places.
This PR refactors this to simplify the configuration surface. The actual goal of this is to make it safe to run the iptables setup multiple times in a long running fashion; due to global variable usage this was extremely hard to do so safely previously.
As part of this, a new package `pkg/flag` is introduced. This replaces our minimal usage of viper with ~3 lines of code to allow setting a flag's …
> iptables: refactor to avoid global variables

- pilot/pkg/features/pilot.go
- releasenotes/notes/external-name-on.yaml
As discussed in networking WG, we will be
1.20: off by default
1.21: on by default
As master branch is now for 1.21, turning this on by default as
discussed
> pilot: enable external name alias on-by-default

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- releasenotes/notes/header-present.yaml
According to https://istio.io/latest/docs/reference/config/networking/virtual-service/
```
The header keys must be lowercase and use hyphen as the separator, e.g. x-request-id.
Header values are case-sensitive and formatted as follows:
exact: "value" for exact string match
prefix: "value" for prefix-based match
regex: "value" for RE2 style regex-based match (https://github.com/google/re2/wiki/Syntax).
If the value is empty and only the name of header is specified, presence of the header is checked. To provide an empty value, use {}, for example:
- match:
- headers:
myheader: {}
```
Without this, the generated route match does not contain ` presentMatch: true` .
```
- match:
- headers:
myheader: {}
```
```
routes:
- decorator:
operation: …
```
> Fix header present match

- tools/istio-clean-iptables/pkg/cmd/cleanup_test.go
- tools/istio-iptables/pkg/capture/run.go
- tools/istio-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/dependencies/implementation.go
- tools/istio-iptables/pkg/dependencies/interface.go
- tools/istio-iptables/pkg/dependencies/stub.go
General best practice is for all functions to return `error`, and only
panic or os.Exit at top level command (or panic if invariant is
violated, but it isn't the case here).
This refactors to align with that practice. In particular, this makes it
reasonable to use this code outside of a single one-off CLI.
> iptables: stop panicing in leaf functions

- releasenotes/notes/bug-report-speedup.yaml
- tools/bug-report/pkg/bugreport/bugreport.go
- tools/bug-report/pkg/bugreport/flags.go
- tools/bug-report/pkg/config/config.go
- tools/bug-report/pkg/kubeclient/kubeclient.go
- tools/bug-report/pkg/kubectlcmd/kubectlcmd.go
The `istioctl bug-report` currently limits the request rate to the kube API to 10 RPS. This is rather conservative and causes the bug report generation to take an unreasonable amount of time in some cases. This patch speeds things up by limiting request **concurrency** instead of request **rate**. It results in dramatic speed increases in my local testing (1:12 -> 0:15).
To protect the api server from overload in cases where request concurrency is low and the rate is high, the bug-report will rely on server-side rate limiting to mitigate the overload risk.
Before:
```
istioctl bug-report  9.38s user 3.41s system 17% cpu 1:12.19 total
```
After:
```
out/linux_amd64/istioctl bug-report  10.54s user 3.70s system 97% cpu 14.566 total
```
> istioctl bug-report: Speed improvement from concurrency limiting

- pilot/pkg/serviceregistry/kube/controller/ambientindex_serviceentry_test.go
Fix https://github.com/istio/istio/issues/47739.
From the log, it seems like the pod event was not added successfully before adding the serviceentry. Assert the event before adding the new object.
> Fix TestAmbientIndex_ServiceEntry_DisableK8SServiceSelectWorkloadEntries flake

- pilot/pkg/serviceregistry/serviceentry/controller_test.go
A config name cannot change. Droping redundant `same config with different name` case
> Drop redundant test case in `TestServicesDiff`

- pilot/pkg/serviceregistry/kube/controller/ambientindex_workloadentry_test.go
Fix https://github.com/istio/istio/issues/47786.
The pod may be added to the ambientindex after `assertWorkloads`, so we should make sure they are added into the ambientindex.
> Fix TestAmbientIndex_WorkloadEntries_DisableK8SServiceSelectWorkloadEntries flake

- istioctl/pkg/internaldebug/internal-debug.go
- tests/integration/pilot/piggyback_test.go
Currently if I do:
```
istioctl x internal-debug syncz  --xds-address localhost:15004 --plaintext
```
I get no response.
Also, replace `x ps` with `x internal-debug syncz`. This is a prerequisite of https://github.com/istio/istio/pull/47740.
> Fix internal-debug syncz not working with agent, and add support for debug type `config_dump `

- istioctl/pkg/validate/validate.go
Add a file path prefix to the decode error, to let users know which file has format error.
```
istioctl validate -f samples/
...
Error: 4 errors occurred:
* failed to decode file samples/ambient-argo/tag-chart/templates/mutatingwebhooks.yaml:  yaml: did not find expected node content
* failed to decode file samples/ambient-argo/tag-chart/templates/shimservice.yaml:  yaml: did not find expected node content
* failed to decode file samples/ambient-argo/tag-chart/templates/validatingwebhook.yaml:  yaml: did not find expected node content
* failed to decode file samples/bookinfo/src/mongodb/ratings_data.json:  yaml: line 1: did not find expected <document start>
```
> Improve validate error message

- pilot/pkg/model/sidecar.go
- pilot/pkg/model/virtualservice.go
Benchmark test results show that the performance of exact host matching has been significantly improved.
```
goos: darwin
goarch: amd64
│   old.txt    │               new.txt               │
│    sec/op    │    sec/op     vs base               │
ConvertIstioListenerToWrapper/small-exact-12         3.204µ ± 1%   2.737µ ±  1%  -14.56% (p=0.002 n=6)
ConvertIstioListenerToWrapper/small-wildcard-12      1.827µ ± 1%   1.887µ ±  1%   +3.31% (p=0.002 n=6)
ConvertIstioListenerToWrapper/small-match-all-12     5.413µ ± 2%   5.447µ ± 19%        ~ (p=0.240 n=6)
ConvertIstioListenerToWrapper/middle-exact-12        32.62µ ± 2%   17.08µ ± 25%  -47.64% (p=0.002 n=6) …
```
> reduce fallback scope

- istioctl/pkg/dashboard/dashboard.go
- istioctl/pkg/dashboard/dashboard_test.go
- releasenotes/notes/47877.yaml
There are several sub-namespace flags in the dashboard command, which may lead to the incorrect usage of the default namespace or other namespaces. 
This PR fixes a regression where the envoy dashboard command defaulted to the `default` namespace, but it has since changed to `istio-system` - I suspect it's a result of refactoring. 
Additionally, the PR removes all the namespace flags from the dashboard and its sub-commands, and updates the addonNamespace (formerly istio-system) to ctx.IstioNamespace(), and sets the envoyDashNs to the default namespace. This will not change the previous behavior.
> istioctl: fix dashboard namespace flag usage

- istioctl/pkg/util/configdump/workload.go
- istioctl/pkg/writer/ztunnel/configdump/testdata/dump.json
- istioctl/pkg/writer/ztunnel/configdump/testdata/workloadsummary.txt
- istioctl/pkg/writer/ztunnel/configdump/workload.go
To make the network more clearly visible, we currently use the network/address as the key. Otherwise, we would need to locate the network in the configdump.
> istioctl: support displaying network info in workload configdump summary

- pkg/test/echo/docker/Dockerfile.app
- pkg/test/framework/components/echo/cmd/echogen/testdata/golden.yaml
- pkg/test/framework/components/echo/kube/templates/deployment.yaml
- pkg/test/framework/components/echo/kube/testdata/basic.yaml
- pkg/test/framework/components/echo/kube/testdata/disable-automount-sa.yaml
- pkg/test/framework/components/echo/kube/testdata/healthcheck-rewrite.yaml
- pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions-no-proxy.yaml
- pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions.yaml
- pkg/test/framework/components/echo/kube/testdata/multiversion.yaml
- pkg/test/framework/components/echo/kube/testdata/proxyless-custom-image.yaml
- pkg/test/framework/components/echo/kube/testdata/proxyless.yaml
- pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml
- samples/grpc-echo/grpc-echo.yaml
They're not strictly required and do not play well with OpenShift.
> Remove runAs from test deployment files

- cni/pkg/ambient/informers.go
- cni/pkg/ambient/net_linux.go
- cni/pkg/ebpf/server/redirectionServer_linux.go
massive unexpected error log in istio-cni while using eBPF redirect mode
```
│ 2023-11-17T06:54:58.937501Z    error    ambient    Failed to list ipset entries: failed to list ipset ztunnel-pods-ips: no such file or directory                                                                                                                                 │
│ 2023-11-17T06:55:00.951899Z    error    ambient    Failed to list ipset entries: failed to list ipset ztunnel-pods-ips: no such file or directory
```
In eBPF mode, ipset is not involved, thus wraps to `IsPodEnrolledInDp` for both mode instead of `IsPodInIpset`
> Wrap IsPodEnrolledInDp for iptables and ebpf mode

- pkg/kube/inject/testdata/inject/proxy-override.yaml
- pkg/kube/inject/testdata/inject/proxy-override.yaml.injected
- pkg/kube/inject/webhook.go
- releasenotes/notes/fix-custom-injection-openshift.yaml
Use of custom injection (i.e., providing a custom `istio-proxy` container) is broken on OpenShift.
This is because OpenShift sets the `RunAs` field to be the a pseudo-random value that varies by namespace. We rely on the `RunAs` field to be a well-known value, and it's calculated upon injection. We should stick with that value. `iptables` rules were created based on that value.
Even if the user provides another value (i.e., it's not set by OpenShift, but b the user), that's wrong. We should ignore what's in the original pod and use the calculated one, for these two fields only.
> Fix the custom injection on OpenShift

- pkg/dns/client/dns.go
- pkg/dns/client/dns_test.go
- releasenotes/notes/47290.yaml
**cherry-pick https://github.com/istio/istio/pull/47290**
As reported on #47264, the DNS Proxy component is capable of returnin……g a CNAME chained response for wildcard `ServiceEntry` objects.
Unfortunately, this only worked for `musl` based DNS resolution leading to a few inconsistent reports of DNS resolution issues, likely on `glibc` based systems.
The issue on `glib` was a long-standing [problem reported in 2010](https://sourceware.org/bugzilla/show_bug.cgi?id=12154) and fixed in `glibc 2.37` in 2022-08-30. Considering the DNS Proxy feature was added in Istio 1.11 back in 2021, it was only possible to validate the DNS Proxy wildcard feature in `musl`, which is also the default on the contaienrs used on the sample.
Now that `glibc` fix has been backported to `glibc 2.34+` and picked up …
> [release-1.18] Adjust DNS Proxy CNAME wildcard response to be compatible with glibc and musl 

- istioctl/pkg/dashboard/dashboard.go
- istioctl/pkg/dashboard/dashboard_test.go
/cc @GregHanson 
The command should accept the `--namespace` flag instead of the `--istioNamespace` flag like before. In this approach, if we find a pod in the `istio-system` namespace, which is the typical namespace for applying addons in samples/addons/*.yaml, then we use it. Otherwise, we use the namespace specified by the `--namespace` flag.
> istioctl: fix dashboard namespace

- pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
- pilot/pkg/serviceregistry/kube/controller/pod.go
- pilot/pkg/serviceregistry/kube/controller/pod_test.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- pilot/pkg/serviceregistry/serviceentry/store.go
- pilot/pkg/serviceregistry/serviceentry/store_test.go
- pkg/kube/kclient/client_test.go
- pkg/test/util/assert/tracker.go
- pkg/util/sets/set.go
- releasenotes/notes/we-memory-leaks.yaml
This fixes three leaks in workload handling:
* Most critical one, found in production: rolling restart of hostNetwork pods leaks an endpoint. 
Sequence that it hits:
In PodCache.onEvent:
* first hostnet pod comes up, all good
* Second hostnet pod comes up, replaces the pod stored for the IP (same IP as first pod)
* first pod is removed. delete() doesn't remove it, since the IP is mapped to second pod. We `return nil`
Result: notifyWorkloadHandlers never gets a delete event
* WorkloadEntry changing IP never removes the old IP
* instancesBySE doesn't remove the key when we remove a SE
> service entry: fix leak in workload addesses

- releasenotes/notes/47957.yaml
- tools/istio-clean-iptables/pkg/cmd/root.go
Fix #47957
I added the `--capture-all-dns` parameter to `pilot-agent istio-clean-iptables`. In the parameter description and usage, make it consistent with the `--capture-all-dns` parameter of `pilot-agent istio-iptables`.
> Fix the command `ipilot-agent istio-clean-iptables` cannot clean up the iptables rules generated for istio dns proxy

- pilot/pkg/xds/delta.go
This is when delta xds client is connected with debug, istiod will panic.
> Fix a delta xds logic that will cause panic for debug interface

- releasenotes/notes/47211.yaml
- tools/istio-iptables/pkg/capture/run.go
- tools/istio-iptables/pkg/capture/run_test.go
- tools/istio-iptables/pkg/capture/testdata/host-ipv4-loopback-cidr.golden
- tools/istio-iptables/pkg/config/config.go
- tools/istio-iptables/pkg/config/validation.go
- tools/istio-iptables/pkg/constants/constants.go
**Please provide a description of this PR:** implements support for https://github.com/istio/istio/issues/47211
Currently, this PR applies the configuration in a blanket fashion for consistency purposes. If this is not desirable, perhaps the changes can be trimmed down to just this rule: https://github.com/istio/istio/blob/master/tools/istio-iptables/pkg/capture/run.go#L373-L378.
> allow configuration of outbound IPv4 loopback CIDR 

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
So that on normal installations we don't end up with two gateway classes. This minimizes confusion as users might wonder what the extra gateway class is for, and avoid they accidentally pick it for their gateways.
> Only create the remote gateway class when MultiNetworkGatewayAPI is enabled

- istioctl/pkg/version/version.go
- releasenotes/notes/48021.yaml
Pilot generate response with
https://github.com/istio/istio/blob/141104caec71593378094d789a47e1da7979b57b/pilot/pkg/xds/statusgen.go#L76-L81
where TypeURLConnect is `istio.io/connect`
> Fix experimental version has no proxy info shown

- cni/pkg/log/uds.go
- pkg/log/default_test.go
- pkg/log/scope.go
- pkg/log/uds_test.go
- pkg/log/zapcore_handler.go
Fixing #47965 
Change:
- Add a `LogWithTime` to `log.Scope` to support custom timestamp.
> fix uds log timestamp

- prow/config/ambient-sc.yaml
- prow/config/default.yaml
- prow/integ-suite-kind.sh
Will pair with a test-infra PR with +1.27,-1.28,+1.29.
> Move default tests over to k8s 1.28

- pilot/cmd/pilot-agent/status/server.go
- releasenotes/notes/48047-probe-return-body.yaml
Some times the app probe return failed, and the user want to get some error information from the probe return body, so I think istio-pilot agent shout return the probe body as well as the statuscode.
> probe return body as well as statuscode

- pilot/pkg/bootstrap/server.go
`s.clusterID` has been processed by the `getClusterID` function. `kubelib.NewClient` should not use the `ClusterID` of the original `args`, but should use the processed one, otherwise the two may be inconsistent.
https://github.com/istio/istio/blob/3902626360adab4b712a4391809dc7b6913a609c/pilot/pkg/bootstrap/server.go#L219
https://github.com/istio/istio/blob/3902626360adab4b712a4391809dc7b6913a609c/pilot/pkg/bootstrap/server.go#L547
> fix inconsistent clusterid

- pilot/pkg/bootstrap/certcontroller.go
- pilot/pkg/bootstrap/istio_ca.go
- security/pkg/pki/ca/ca.go
- security/pkg/pki/ca/selfsignedcarootcertrotator.go
- security/pkg/util/certutil.go
- security/pkg/util/certutil_test.go
- security/pkg/util/mock/fakecertutil.go
Self-signed root cert rotator does not work when it rotates root cert. It should trigger istiod to resign the certs for its grpc server.
And should update the namespace scoped root cert configmap
> self-signed root cert rotate should also trigger istiod server to reload certificate

- cni/pkg/ambient/informers.go
This is a regression in https://github.com/istio/istio/pull/47843
`IsPodInIpset` does not work when eBPF redirection is enabled
> ambient: fix a regression in pod update handler

- istioctl/pkg/internaldebug/internal-debug.go
- tests/integration/pilot/piggyback_test.go
Reverts istio/istio#47801
See https://github.com/istio/istio/issues/48109
I am not sure I fully understand the original PR. Maybe some context I am missing that can forward-fix instead of revert, LMK @hanxiaop
The config_dump already worked before the PR, and seems to not work with the PR (along with everything else; the command now does not work at all). `~/istio/istio-1.20.0-rc.0/bin/istioctl x internal-debug config_dump?proxyID=echo-istio-6c4d855455-6xn55` works for example.
> Revert "Fix internal-debug syncz not working with agent, and add support for debug type `config_dump `"

- pilot/pkg/serviceregistry/kube/controller/network_test.go
Fix https://github.com/istio/istio/issues/48085.
Add a notifier to the test, to make sure the namespace has already be handled by the controller before assert.
> Fix TestSyncAllWorkloadsFromAmbient flake

- cni/pkg/ambient/constants/constants.go
- cni/pkg/ambient/net_linux.go
- cni/pkg/ebpf/server/redirectionServer_linux.go
- releasenotes/notes/fix-peer-veth-lookup-on-openshift.yaml
Istio CNI fails to apply ip and iptables rules on OpenShift with OVN-Kubernetes and OpenShift-SDN, because these CNIs do not create routes for veth interfaces.
On KinD cluster I see the following routes:
```
kubectl exec istio-cni-node -n istio-system -- ip route   
default via 172.18.0.1 dev eth0 
10.244.0.0/24 via 172.18.0.2 dev eth0 
10.244.1.0/24 via 172.18.0.3 dev eth0 
10.244.2.2 dev vethb80b7ad6 scope host 
10.244.2.3 dev veth3af6af4b scope host 
172.18.0.0/16 dev eth0 proto kernel scope link src 172.18.0.4 
192.168.126.0/30 dev istioin proto kernel scope link src 192.168.126.1 
192.168.127.0/30 dev istioout proto kernel scope link src 192.168.127.1
```
and function [getLinkWithDestinationOf](https://github.com/istio/istio/blob/master/cni …
> ambient: fix veth lookup for ztunnel pod on OpenShift

- pilot/pkg/autoregistration/controller.go
- releasenotes/notes/48089.yaml
fixes #44640
The race:
* Start processing a WorkloadGroup Add
* Start processing a proxy disconnect
* If the disconnect update is written first, the WG Add event overwrites it
User impact:
If a user connects their VM, has a WorkloadEntry created then quickly disconnects their VM shortly after the initial WorkloadGroup is created, they will wait for the "periodic" cleanup (based on maxConnectionAge) rather than getting quick cleanup. 
The fix:
* Check that the connection timestamp is newer than the disconnect
* Use `Update` instead of `Patch` to make sure we knew about the timestamps before writing
We're relying on timestamps from different controllers which isn't great, but I don't see a better option. For the case where we have one controller, we could hold locks for longer or lock …
> autoregistration: fix marking entries as connected after disconnect

- pkg/envoy/agent.go
- releasenotes/notes/skip-graceful-termination.yaml
Currently, there is ambiguity in the behavior when both the pilot-agent and Envoy receive a SIGTERM signal "at around the same time". If the pilot-agent detects the SIGTERM before detecting the termination of the Envoy process, it initiates a graceful termination logic, waiting for X seconds. On the other, if it identifies the termination of the Envoy process before initiating the graceful logic, it terminates immediately.
This pull request change the behavior by skipping the remaining graceful waiting time in case Envoy terminates prematurely.
It's important to note that if the exitOnZeroActiveConnections flag is in use, this PR will not alter the behavior (but it will alter the logging messages). When exitOnZeroActiveConnections=true, the graceful termination logic already aborts …
> Skip graceful termination if Envoy ended prematurely

- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_builder.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pilot/pkg/xds/endpoints/endpoint_builder.go
These are called by listener and endpoint builder, which is deemed to be not for ztunnel. So we can only check waypoint.
> remove checking ztunnel

- releasenotes/notes/istioctl-sort-events-by-creation.yaml
- tools/bug-report/pkg/content/content.go
Events gathered by `istio bug-report` are not sorted by date, which makes difficult to correlate data. Sort events by creation timestamp to more easily identify the last generated events.
Tested locally by running:
```
go run tools/bug-report/main.go
```
> bug-report: sort events by creation date

- pilot/pkg/model/service.go
- pilot/pkg/model/service_test.go
- pilot/pkg/xds/eds.go
I wouldn't have thought so, but this is looking like a hotpath for some setups. I don't think its typically this high, but in a high-churn environment I see 12% total CPU here(!): https://pprof.me/726e9dfa265282e0cb2857cdc13e9770/?profileType=profile%3Acpu%3Ananoseconds%3Acpu%3Ananoseconds%3Adelta
```
name \ time/op    /tmp/old     /tmp/new2   /tmp/new
T-8                137µs ±56%   59µs ±15%   28µs ±19%
name \ alloc/op   /tmp/old     /tmp/new2   /tmp/new
T-8               64.0kB ± 0%  0.0kB       0.0kB     
name \ allocs/op  /tmp/old     /tmp/new2   /tmp/new
T-8                1.00k ± 0%  0.00k       0.00k     
```
* Old = master
* New2 = optimized ParseSubsetKey
* New = specialized ParseSubsetKeyHostname
> Optimize model.ParseSubsetKey

- cni/pkg/cmd/root.go
https://github.com/istio/istio/pull/48198#issuecomment-1842186555
Correct typo from 'ace' to 'race' at `cni/pkg/cmd/root.go`.
> cni: fix typo at root.go

- pilot/pkg/serviceregistry/kube/controller/network_test.go
now it has used channel notification, so we donot need retry anymore
> remove retry in TestNetworkUpdateTriggers

- pilot/cmd/pilot-agent/app/cmd.go
- pilot/cmd/pilot-agent/app/request.go
This PR contains two small refactors:
1. simplify validate allowedPorts
See file: pilot/cmd/pilot-agent/app/request.go
2. simplify building proxy.IPAddresses
Modifications other than pilot/cmd/pilot-agent/app/request.go
> refactor: use sets to simplify code logic

- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
Should not take a parameter that we don't use and return it
> Minor cleanup of cluster inbound code

- pkg/envoy/proxy.go
- pkg/envoy/proxy_test.go
- pkg/envoy/testdata/bootstrap.yaml
Envoy accepts both JSON and YAML string as `--config-yaml` command line parameter. In operation, When ISTIO_BOOTSTRAP_OVERRIDE used together with a YAML config for overriding, it will lead to long process command difficult to read or parse. What makes it worse is comment strings within YAML file.
This PR standardizes custom bootstrap config on JSON string for Envoy, while continue to allow ISTIO_BOOTSTRAP_OVERRIDE file with either YAML or JSON.
Ref: https://www.envoyproxy.io/docs/envoy/latest/operations/cli.html#command-line-options
> envoy: always use json as as Envoy custom bootstrap config

- pilot/pkg/features/pilot.go
- pilot/pkg/model/config.go
- pilot/pkg/model/sidecar.go
- pilot/pkg/model/sidecar_test.go
- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
- pkg/config/model.go
- releasenotes/notes/45415-overlapping-wildcards.yaml
> [release-1.19] Dedupe wildcard routes based on the virtualservice with the most specific match (#48071)

- cni/pkg/ambient/informers_test.go
This PR tries to fix https://github.com/istio/istio/issues/48247
From the error log here https://storage.googleapis.com/istio-prow/logs/unit-tests_istio_postsubmit/1733170613905788928/build-log.txt,
```
informers_test.go:207: found diff:   bool(
- 	true,
+ 	false,
)
Left: true
Right: false
add app-2
add app-2
del app-2
```
this failure could be reproduced when executing thousands of times `go test -race -run ^TestServerReconcilePod$ istio.io/istio/cni/pkg/ambient -v --count=1000 > debug.log`.
Just realized the previous test code has bug, it should return false in the for loop,
```go
assert.EventuallyEqual(t, func() bool {
skippedEvents := 0
for i, event := range c.expectedEvents {
...
+++ return false +++
}
return true
}, true, …
```
> Try to fix flake TestServerReconcilePod

- pilot/pkg/model/sidecar.go
- pilot/pkg/model/sidecar_test.go
Bugfix #48071; I realized while reading #10464 that I didn't account for the duplicate hostname case. We still must make sure the oldest deployed VS wins for backwards compat purposes. I added a test case to make sure this nuance isn't missed in the future
> Make sure we still take the oldest VS when we have actual duplicate hosts

- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/util/util.go
- releasenotes/notes/48334.yaml
- tests/integration/security/sds_ingress/quic/ingress_test.go
This will address a DS-exclusive issue: #48336
As I mentioend in the issue, when both DS and QUIC listeners are enabled we end up using different socket type between the address and additional_addresses.
Because we end up with both an UDP and a TCP address in the same listener, Envoy will correctly rejects the configuration.
I have updated the code to ensure a proper listener configuration.
> Fix wrong socket type for extra addresses in QUIC listeners

- pkg/bootstrap/platform/gcp.go
- pkg/bootstrap/platform/gcp_test.go
In the past, we had made it so this will behave correctly if the env var
is set and we cannot reach the metadata server. This could be an outage
or netpol blocking, etc.
however, we have begun to see issues where the metadata server is around
enough to pass the "is alive", but not stable enough to respond quickly.
This results in massive (20s+) startup latencies. This is for
effectively useless information, as the `gce_*` metadata is unused on
GKE where the variable is used anyways.
This PR makes the logic even more robust, and short circuits entirely if
the var is set
> gcp: drop reliance on metadata server entirely when GCP_METADATA is set

- pilot/pkg/networking/core/v1alpha3/listener.go
- releasenotes/notes/48334.yaml
> [release-1.19] Fix wrong socket type for extra addresses in QUIC listeners

- pilot/pkg/networking/core/v1alpha3/listener.go
- releasenotes/notes/48334.yaml
- tests/integration/security/sds_ingress/quic/ingress_test.go
Manual cherry-pick of https://github.com/istio/istio/pull/48334
> [release-1.20] Fix wrong socket type for extra addresses in QUIC listeners

- pilot/pkg/networking/core/v1alpha3/cluster_tls.go
- pilot/pkg/networking/core/v1alpha3/cluster_tls_test.go
- releasenotes/notes/auto-san-validation.yaml
As per envoy docs, auto-san-validation is supposed to be set with auto-sni, however in our current implementation, the logic sets auto-san-validation, even if the DR has an explicit SNI set, but SAN is not set.
Please see: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-upstreamhttpprotocoloptions-auto-san-validation
> Fix auto san validation

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- releasenotes/notes/48312.yaml
resolves https://github.com/istio/istio/issues/48349
With the change below, I observed an issue that if exportTo includes workload's current namespace (not '.'), other namespaces are ignored from ExportTo.
- https://github.com/istio/istio/blob/master/pilot/pkg/model/push_context.go#L1917
> Fix ExportTo behavior if workload's namespace is included

- pilot/pkg/model/endpointshards.go
- pilot/pkg/xds/eds_test.go
- releasenotes/notes/endpoints-false-negative.yaml
We should always send new healthy endpoints. This typically happens when EndpointSlices are manually managed or pods are selected by a ServiceEntry
Fixes https://github.com/istio/istio/issues/48373
> Always send new healthy endpoints

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/model/sidecar.go
make pushContext `HostnameAndNamespace` init obey the rule oldest first and k8s first.
> update init service registry

- pkg/slices/slices.go
- pkg/slices/slices_test.go
- tests/util/leak/check.go
When we move right elements to left, we should assgin emtpy value to useless elements for gc.
> Fix potential memory leak in slice when using FilterInPlace

- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/authorization.go
This addresses a specific issue, and attempts to future-proof the
implementation from similar bugs.
The specific issue is CalculateUpdatedWorkloads fails to update the
`byService` index. This can result in new pods failing to get authz
policies configured.
The general prevention is a new `assertIndexConsistency` that runs for
all tests, that detects this class of problems. A targetted test is
added for this specific case, but `assertIndexConsistency` found bugs in
a variety of existing tests as well.
Rather than a vary narrow fix, this pulls the index update logic into
some common code so its harder to mis-use.
Long term, https://github.com/istio/istio/pull/47891 would be a great
fit here. However, that is a much much larger change, so for now a
minimal fix is implemented.
> ambient: fix inconsistencies in indexes

- pilot/pkg/features/pilot.go
- releasenotes/notes/pilot-autoscale.yaml
This is an attempt to improve the defaults here.
25 for RL is decent, but for giant clusters we have seen folks report
its too small.
The bigger issue is 100 throttle. This is way to high for most
environments, 100 concurrent CPU-intensive operations on 1-2 cores is
terrible. We see much better results with lower values. Internally we
have run with 25 here for years.
I definitely want to lower the throttle. In the process, I thought it
might be nice to have more dynamicism here instead of just statically
changing.
Relevant prior discussion:
* https://github.com/istio/istio/issues/35263
* https://github.com/istio/istio/issues/44985
> pilot: autoscale concurrency and rate limit on xds

- tests/integration/pilot/common/routing.go
As found while debugging https://github.com/istio/istio/pull/48201, the test framework is not passing the cookies back for gRPC calls. For now I am skipping these tests. Will think about how to pass them in gRPC.
> skip consistent hash ttl test cases

- pilot/pkg/model/config.go
- pilot/pkg/model/typed_xds_cache_test.go
- pilot/pkg/networking/core/v1alpha3/cluster_cache.go
- pilot/pkg/networking/core/v1alpha3/route/route_cache.go
- pilot/pkg/xds/endpoints/endpoint_builder.go
- pkg/util/hash/hash.go
- pkg/util/hash/hash_test.go
Use xxhash `WriteString` when dealing with strings to avoid allocations
> optimize: use writestring to avoid copying

- pilot/pkg/networking/core/v1alpha3/listener_test.go
- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
- releasenotes/notes/48471.yaml
- tests/integration/telemetry/stackdriver/vm/main_test.go
- tests/integration/telemetry/stackdriver/vm/testdata/trace.prototext.tmpl
inspired by [kiali's doc](https://kiali.io/docs/configuration/multi-cluster/), I think it's good to enable it by default.
> tracing: always enable cluster id

- pilot/pkg/util/network/ip.go
- pkg/adsc/adsc.go
After the changes in https://github.com/istio/istio/pull/41624, the function now returns an IPv6 link-local unicast address `fe80::1` for my client. I have no dual-stack feature enabled.
> Fix get private ip in adsc

- istioctl/pkg/util/configdump/ecds.go
- istioctl/pkg/util/configdump/util.go
- istioctl/pkg/writer/envoy/configdump/testdata/ecds/configdump.json
- istioctl/pkg/writer/envoy/configdump/testdata/ecds/output.json
- istioctl/pkg/writer/envoy/configdump/testdata/ecds/output.txt
- istioctl/pkg/writer/envoy/configdump/testdata/ecds/output.yaml
- releasenotes/notes/48526.yaml
mismatched before following output:
```console
istioctl pc ecds sleep-7656cf8794-kqc52.default
ECDS NAME                                                    TYPE
istio.io/telemetry/stats/prometheus/sidecar/Inbound/TCP
istio.io/telemetry/stats/prometheus/sidecar/Outbound/TCP
```
```console
istioctl x internal-debug "config_dump?types=ecds&proxyID=sleep-7656cf8794-kqc52.default" | jq '.configs | length'
4
```
```console
istioctl pc all sleep-7656cf8794-kqc52 -ojson | grep -c "type.googleapis.com/envoy.admin.v3.EcdsConfigDump"
```
> istioctl: fix pc ecds

- pilot/pkg/config/aggregate/config.go
- pilot/pkg/config/memory/store.go
- pilot/pkg/config/memory/store_test.go
This PR aims to optimize the memory allocation overhead in the List method of configstore. Considering the extensive use of this method in the Istio codebase, which constitutes a critical code path, optimizing it holds significant value.
Specific changes include:
1. Optimizing memory config store `List` method to pre-allocate a slice of appropriate size based on the actual returned data, avoiding multiple slice expansions caused by repeated `append`s.
2. Implementing similar optimizations for the aggregate config store.
3. Adding a `BenchmarkStoreList` test case to observe the actual impact of the optimization.
Optimization results:
```sh
BenchmarkStoreList-8           7071        147289 ns/op      786132 B/op         12 allocs/op …
```
> Optimize config store `List`

- pilot/pkg/model/sidecar.go
- pilot/pkg/model/sidecar_test.go
Third time's the charm? @hzxuzhonghu correctly points out that the previous patch in #48330 [changes the precedence order
](https://github.com/istio/istio/pull/48330#discussion_r1426120302) because the list is presorted. We should maintain that ordering when handling duplicate hostnames before dealing with overlapping wildcards
> Assume virtualService map is already sorted by the precedence order desired with respect to duplicates

- pilot/pkg/model/envoyfilter.go
- pilot/pkg/model/envoyfilter_test.go
- releasenotes/notes/48544.yaml
While the content of EnvoyFilter can be validated to ensure its validity, from an engineering perspective, it is also necessary to mitigate the risk of this code not spreading or exacerbating. Assuming a scenario where there is no validation or a validation miss, [performing an actual patch](https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch.go#L256) could lead to a null pointer exception (NPE).
So it is considered better practice to employ defensive programming here.
> convertToEnvoyFilterWrapper skip invalid patch

- releasenotes/notes/48545.yaml
- tools/certs/Makefile.k8s.mk
In the makefile, the top-level `if` actually operates in a manner similar to macros, so the source code `ifeq ($(res), 1)` cannot access the expected result from the previous line, but rather results in a constant **empty value**. 
In terms of business impact, when `istio-ca-cert` does not exist, it incorrectly assumes a successful result, leading to the execution of the `else` block and obtaining incorrect content.
> fix Makefile.k8s.mk fetch-root-ca if-condition not work

- pkg/config/analysis/msg/messages.gen.go
- pkg/config/analysis/msg/messages.yaml
An analysis code is no longer generated by Istio. See #22706 and [ist0119 comments](https://github.com/istio/istio.io/pull/14382/files#r1437327758).
Removing these dead codes will remove them from http://istio.io/latest/docs/reference/config/analysis/
cc @hanxiaop
> Remove an analysis code that is no longer used: ist0119

- pkg/config/analysis/msg/messages.gen.go
- pkg/config/analysis/msg/messages.yaml
Removing the unused `IST0113` analysis message.
[Documentation](https://istio.io/latest/docs/reference/config/analysis/) update to remove it: https://github.com/istio/istio.io/pull/14403.
> Remove unused analysis message

- pilot/pkg/xds/endpoints/ep_filters.go
- pilot/pkg/xds/endpoints/ep_filters_test.go
- releasenotes/notes/network-gw-metadata.yaml
It's incorrect to set the ClusterID of network gateways to the proxy's ClusterID, which can generate wrong stas
> EDS metadata: fix ClusterID of network gateways

- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta.go
This bug will cause log and metric error (Not set means `OK`, in fact it has an error). see
https://github.com/istio/istio/blob/dc36b426b96b84f36bbbf47273c4d3f33e5db905/pilot/pkg/xds/ads.go#L379
> fix ECDS NACK error code

- pkg/log/scope.go
- pkg/log/scope_test.go
Otherwise we end up printing the same value twice
> log: override values instead of adding when multiple k/v pairs

- pilot/pkg/features/pilot.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
Currently, SidecarScope conversion is the main performance bottleneck of istiod. In the past year(see [here](https://github.com/istio/istio/issues/41453#issuecomment-1860290719)), we have optimized this many times, but we still have not reversed the situation. It is still the main performance bottleneck.
I think its performance problems mainly come from:
1. Large amount of calculation
In order to select CR resources related to egress host, use egress host to match VS, Service, DR, etc. Most of the ideas in the past were to improve speed by reducing calculations. Although some results have been achieved, configuration push is still very slow, taking about 1 minute in our production environment.
2. Inability to fully utilize the CPU
Currently, only one goroutine calculation is supported, …
> Supports concurrent SidecarScope conversions

- istioctl/pkg/injector/injector-list.go
- releasenotes/notes/48595.yaml
The webhook can contains several webhooks that is matching the namespace, and currently the namespace may be duplicated: 
```
istioctl x injector list                    
...
NAMESPACES          INJECTOR-HOOK              ISTIO-REVISION SIDECAR-IMAGE
...
hello               istio-revision-tag-default default        hanxiaop/proxyv2:1.21.0-1226
...
hello               istio-revision-tag-default default        hanxiaop/proxyv2:1.21.0-1226
```
this is to remove the duplications per revisioned webhook.
> Fix duplicate rev namespace in injector list

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/testdata/grpc.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/grpc.yaml
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
Previous, the GRPCRoute can't attach to the Gateway when allowedRoutes.kinds.Kind is given.
> Fix GRPCRoute's kind passed to the parent reference solver

- .github/ISSUE_TEMPLATE/bug_report.yml
> Flag `--short` has been deprecated, and will be removed in the future.
It was removed in 1.28 - https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md#deprecation
> Update version portion of bug template

- pilot/pkg/model/context.go
- pilot/pkg/model/context_test.go
The old logic doesn't handle json escaping. As a result, we could send
out invalid strings like `"foo"bar"`. This confuses the json processor
*which can lead to panics in json marshal library*.
> Make json processing more robust

- pkg/config/analysis/analyzer.go
- pkg/config/analysis/analyzers/schema/validation.go
- pkg/config/analysis/analyzers/schema/validation_test.go
- pkg/config/analysis/local/istiod_analyze.go
Fix https://github.com/istio/istio/issues/48665#issuecomment-1880316526, optimize `mapassign` and `fmt.Sprintf` performance issues.
Benchmark Metadata result: 
```code
goos: darwin
goarch: amd64
pkg: istio.io/istio/pkg/config/analysis/analyzers/schema
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
Metadata-12   348.0n ± 6%   146.3n ± 7%  -57.96% (p=0.002 n=6)
│  old.txt   │              new.txt              │
│    B/op    │    B/op     vs base               │
Metadata-12   208.0 ± 0%   176.0 ± 0%  -15.38% (p=0.002 n=6)
│  old.txt   │              new.txt              │
│ allocs/op  │ allocs/op   vs base               │
Metadata-12   5.000 ± 0%   3.000 ± 0% …
```
> optimize schema analysis performance

- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/core/v1alpha3/cluster_traffic_policy.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/max-concurrent-streams.yaml
istiod changes to support the [max concurrent streams](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-field-config-core-v3-http2protocoloptions-max-concurrent-streams) setting added in https://github.com/istio/api/pull/2952 in a traffic policy definition in a DestinationRule.  
Resolves #47166 
Outstanding Questions:
- Should http2 specific settings apply to clusters upgraded to HTTP2? With the current change, the max concurrent streams field is ignored unless the upstream protocol is explicitly set to HTTP2.
Testing:
- Verified envoy config is updated in response to a DestinationRule being applied with maxConcurrentStreams set on a service with `appProtocol: http2`
- Verified maxConcurrentStream …
> Add support for DestinationRule max concurrent streams setting

- pilot/pkg/xds/ads.go
- pilot/pkg/xds/delta.go
- pilot/pkg/xds/statusgen.go
These are unused; the types are not part of generators so its impossible to query.
Ill have another PR cleaning up more, but splitting out the non-controversial bits
> Cleanup deadcode in StatusGen

- .github/ISSUE_TEMPLATE/bug_report.yml
- README.md
From my understanding [discuss.istio.io](https://discuss.istio.io) is removed. This updates the two references I found to point to Github discussions.
> replace discuss.istio.io references with github

- istioctl/pkg/version/version.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/ads_test.go
- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/statusgen.go
Builds on https://github.com/istio/istio/pull/48706
This has two usage:
1. Real usage in istioctl to serve `istioctl x version`.
2. Theoretical use case to subscribe to Connection events. I don't think
there are any actual users of this
This PR moves (1) to use the Syncz mechanism. This already reports all
proxies, so the info is pretty much redundant. We can just use that.
Typically we would make istioctl change first then Istiod in future
release, but since this is experimental I think its fine to change
together.
> Remove "Connect" type URL

- tools/istio-iptables/pkg/config/validation.go
- tools/istio-iptables/pkg/config/validation_test.go
replace net.ParseCIDR with pkg/config in ValidateIPv4LoopbackCidr
refer to #39348
> refactor: replace net.ParseCIDR with pkg/config in ValidateIPv4LoopbackCidr

- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/core/v1alpha3/cluster_traffic_policy.go
- releasenotes/notes/set-tcp-idle-timeout-in-http-clusters.yaml
This is a follow-up to #48009 and this [comment](https://github.com/istio/api/pull/2999#discussion_r1427584062).
As the [documentation](https://istio.io/latest/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings-TCPSettings) says, `connectionPool.tcp` settings are common to both HTTP and TCP upstream connections, so I added missing logic to the cluster builder.
> networking: add support for setting TCP idle timeout for HTTP services

- tests/integration/pilot/common/routing.go
Cherrypicking the following commit : https://github.com/istio/istio/commit/db18352c179eafec8feb4f1943123df9b1f21062
> skip consistent hash ttl test cases (#48501)

- pilot/cmd/pilot-agent/config/config.go
- pkg/envoy/agent.go
These can cause outages if misconfigured, so good to warn
> agent: warn about harmful concurrency settings

- cni/cmd/istio-cni/main.go
Previously the `defer() { ... }` block which calls `_ = log.Sync()` would not exec if an error happened, because `skel.PluginMain` calls `os.Exit(1)` on error. This should ensure that `log.Sync` gets called regardless of the result of calling the CNI plugin skeleton.
> handle errors from skel gracefully

- istioctl/pkg/tag/generate.go
- istioctl/pkg/tag/util.go
I think the revisioned validator has been used in many releases, and there will not be any old VWC to clean up.
> Cleanup dead code about deleting deprecated validator

- pilot/pkg/bootstrap/discovery.go
- pilot/pkg/bootstrap/server.go
- pilot/pkg/networking/core/configgen.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/cds.go
- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/ecds.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/lds.go
- pilot/pkg/xds/nds.go
- pilot/pkg/xds/pcds.go
- pilot/pkg/xds/rds.go
- pilot/pkg/xds/workload.go
- pilot/test/xds/fake.go
This trims 2MB off istio-agent binary
Probably an ideal structure would have the generators entirely decoupled
from the DiscoveryServer/xds package, but its a high cost so I am not
going that far right now
Builds on https://github.com/istio/istio/pull/48710
> Drop direct dependency on xds to networking/v1alpha3

- tests/integration/ambient/main_test.go
Running the tests locally it seems like Ambient integration tests don't require IPv4-only anymore.
Verifying no prow fails with this PR.
> Remove IPv4-only requirement from Ambient integ tests

- pkg/slices/slices.go
- pkg/slices/slices_test.go
- adds tests to `pkg/slices` as part of #37354 
- modifies `slices.Flatten` to explicitly handle a `nil` slice as an argument
- modifies `slices.MapFilter` to add quick return in the case of a `nil` filter function, preventing a panic
> adds unit tests to pkg/slices

- pilot/pkg/xds/sds.go
- pilot/pkg/xds/sds_test.go
- releasenotes/notes/48843.yaml
- security/pkg/nodeagent/sds/sdsservice.go
- security/pkg/nodeagent/sds/sdsservice_test.go
Envoy recently add support for fallback in PrivateKeyProvider as in https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#extensions-transport-sockets-tls-v3-privatekeyprovider
Add the related support into Istio.
corresponding API change is in https://github.com/istio/api/pull/3045
> add fallback support for privateKeyProvider

- tests/integration/ambient/main_test.go
Reverts istio/istio#48839
Postsubmit fails
> Revert "Remove IPv4-only requirement from Ambient integ tests"

- istioctl/pkg/install/k8sversion/version.go
- istioctl/pkg/install/k8sversion/version_test.go
This will be needed once we transition to the new supported window for the next release.
> Update min k8s version to 1.26

- pkg/bootstrap/config.go
- pkg/bootstrap/testdata/all_golden.json
- pkg/bootstrap/testdata/auth_golden.json
- pkg/bootstrap/testdata/authsds_golden.json
- pkg/bootstrap/testdata/default_golden.json
- pkg/bootstrap/testdata/lrs_golden.json
- pkg/bootstrap/testdata/metrics_no_statsd_golden.json
- pkg/bootstrap/testdata/running_golden.json
- pkg/bootstrap/testdata/runningsds_golden.json
- pkg/bootstrap/testdata/stats_compression_brotli_golden.json
- pkg/bootstrap/testdata/stats_compression_gzip_golden.json
- pkg/bootstrap/testdata/stats_compression_unknown_golden.json
- pkg/bootstrap/testdata/stats_compression_zstd_golden.json
- pkg/bootstrap/testdata/stats_inclusion_golden.json
- pkg/bootstrap/testdata/tracing_datadog_golden.json
- pkg/bootstrap/testdata/tracing_lightstep_golden.json
- pkg/bootstrap/testdata/tracing_none_golden.json
- pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
- pkg/bootstrap/testdata/tracing_stackdriver_golden.json
- pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
- pkg/bootstrap/testdata/tracing_tls_golden.json
- pkg/bootstrap/testdata/tracing_zipkin_golden.json
- pkg/bootstrap/testdata/xdsproxy_golden.json
- releasenotes/notes/envoy-eds-cache.yaml
This allows envoy to use eds cache when control plane response times out and helps to finish warming without a eds update after cds update
> add use eds cache run time flag

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/testdata/mesh.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/serviceentry.yaml.golden
Mesh TLSRoutes should use parent Service hosts for CNI matching.
> gateway-api: use parent hosts for mesh TLSRoute CNI

- pilot/pkg/model/telemetry_logging.go
- pilot/pkg/model/telemetry_logging_test.go
- pilot/pkg/model/telemetry_test.go
- pilot/pkg/networking/core/v1alpha3/accesslog_test.go
- releasenotes/notes/json-log-sort.yaml
This makes the log format quite a bit nicer, since the keys are not scrambled each time. 
Performance WITH sort:
```
DEST          CLIENT  QPS   CONS  DUR  SUCCESS  THROUGHPUT   P50     P90     P99
http://hyper  fortio  0     8     2    24583    12288.40qps  0.63ms  0.79ms  1.21ms
http://hyper  fortio  1000  8     2    2000     996.04qps    0.30ms  0.43ms  0.59ms
```
WITHOUT sort (master):
```
DEST          CLIENT  QPS   CONS  DUR  SUCCESS  THROUGHPUT   P50     P90     P99
http://hyper  fortio  0     8     180  1920049  10666.91qps  0.78ms  1.13ms  1.71ms
http://hyper  fortio  1000  8     180  180000   999.96qps    0.29ms  0.42ms  0.60ms
```
So overall we see equivalent performance here. It would probably be better to microbench this instead of macrobenchmark if we are worried about the …
> logging: ordered json keys

- pilot/pkg/model/sidecar.go
- pilot/pkg/model/sidecar_test.go
- pilot/pkg/xds/proxy_dependencies.go
- pilot/pkg/xds/proxy_dependencies_test.go
- pkg/dns/server/name_table_test.go
Now we merge services that are from SE and in same namespace.
And k8s service takes priority, we donot merge k8s services' ports before and after. 
I am not sure of any regression by this, open for feedback first
> Make default sidecar scope services merge consistent with sidecar

- pilot/pkg/xds/ads.go
- pilot/pkg/xds/delta.go
- pilot/pkg/xds/xdsgen.go
This pr does some mis cleanup on xds:
1. For Stow remove depend on `ResourceDelta.Unsubscribed`, maybe we can do similar for delta.
2. For delta,  it is very common that request.ResponseNonce != previousInfo.NonceSent because of spontaneous requests, so remove the logging
3. remove hard understanding code in delta `newAck != oldAck`
> Misc xds cleanup

- pkg/config/mesh/kubemesh/watcher.go
As described in https://github.com/istio/istio/issues/48991 when configmap can't be parsed there is a warning message about it which is easy to miss.
Changing those to errors.
Fixes https://github.com/istio/istio/issues/48991
> Change messages about failed config map parsing to errors

- Makefile.core.mk
Continuing almost whole-workday storyline from #48990: updating Arch package for istioctl. (..and cutting usage from the part my previous PR fixed :upside_down_face:)
Just building ctl does seemingly not need the dependencies marked as dependants for pretty much all targets in Makefiles. Let's cut down on waste. AFAIK, the component is rather decoupled from the others, and I couldn't find anything breaking.
***
tested:
- docker istioctl-all
- non-docker istioctl-all
- manual search in `istioctl/` for any embeds + glaze through mentions of the deps
tried to test:
- go …
> Makefile: drop istioctl dependency: envoy, ztunnel

- istioctl/pkg/wait/wait.go
- istioctl/pkg/wait/wait_test.go
- pilot/pkg/xds/debug.go
- releasenotes/notes/48985.yaml
As mentioned in #48985 the endpoint is currently not part of the debug config distribution report.
Fixes #48985
> Added endpoint to the debug config distribution report

- istioctl/pkg/proxyconfig/proxyconfig.go
The (default) `short` output is missing from the `istioctl x envoy-stats --output` flag description.
> Add missing short (also the default) format type to istioctl

- istioctl/pkg/wait/wait.go
- istioctl/pkg/wait/wait_test.go
- releasenotes/notes/48958.yaml
This closes #48696.
A `--proxy` flag will be added, via that flag you can provide one proxyID and the distribution condition of the resource will be checked only for that workload instance.
Additional tests have been added
> Add proxy flag to istioctl experimental wait command

- common/config/.golangci.yml
- pkg/test/framework/resource/flags.go
- pkg/test/framework/resource/settings.go
- tests/integration/pilot/gateway_conformance_test.go
Running a pre-existing Istio installation with PILOT_ENABLE_ALPHA_GATEWAY_API set to false (the default) leads to failing Gateway API conformance tests. We should allow running these tests without experimental resources.
> Add option to only run gateway conformance tests with standard resources

- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
- releasenotes/notes/47835-otlp-http-exporter.yaml
- samples/open-telemetry/otel.yaml
- tests/integration/telemetry/tracing/otelcollector/testdata/otel-tracing-http.yaml
- tests/integration/telemetry/tracing/otelcollector/tracing_test.go
Closes #47835
This PR uses the [newly added API configs](https://github.com/istio/api/pull/2998) to allow exporting OpenTelemetry traces via OTLP/HTTP. As of now, it is only possible to export traces via gRPC, but there is several use cases where only HTTP is available. (e.g. a back-end only offers HTTP ingest endpoints)
Reference: [OpenTelemetry Protocol Exporter](https://opentelemetry.io/docs/specs/otel/protocol/exporter/)
CC @zirain
> Add support to export OpenTelemetry traces via HTTP

- cni/pkg/nodeagent/netns_linux.go
close netns before err return to avoid potential leak in OpenNetns implementation
> ambient: close netns before err return to avoid potential leak

- CODEOWNERS
Reviewers for https://github.com/istio/istio/pull/49139 seems not right.
> correct CODEOWNER for /pkg/adsc

- pilot/pkg/serviceregistry/kube/controller/authorization.go
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-and-disable-port-mtls.yaml
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-and-permissive-port-mtls.yaml
- releasenotes/notes/49098.yaml
ztunnel Authorization resources are different than Istio's AuthorizationPolicy resources in the sense that there's an extra level of nesting. PeerAuthentication port-level exclusions should result in policy blocks that are AND'd with the top-level policy, not OR'd.
NOTE: This would've been caught with an integration tests, but we still don't have a way to do check the existence of a peer identity with Ambient tests. 
> Ambient PeerAuthentication should use AND semantics instead of OR

- cni/pkg/nodeagent/cni-watcher.go
- cni/pkg/nodeagent/cni-watcher_test.go
- cni/pkg/nodeagent/informers.go
Fixup for #48253
- Fix dorked conditional to avoid log spam
- WaitForCacheSync on the informer side, as it already has backoff logic for this
> Ambient CNI: Fix informer reconciliation logs

- pkg/adsc/delta.go
- pkg/adsc/delta_test.go
- releasenotes/notes/49139.yaml
1） when received a response that contains RemoveResources, it would cause the client crash.  Because the remove resource only has a name.
```go
for _, r := range d.RemovedResources {
key := resourceKey{
Name:    r,
TypeURL: d.TypeUrl,
}
removed := &discovery.Resource{
Name: r,
}
err := c.trigger(ctx, d.TypeUrl, removed, EventDelete)
if err != nil {
return err
}
if _, f := allRemoves[key.TypeURL]; !f {
allRemoves[key.TypeURL] = set.New[string]()
}
allRemoves[key.TypeURL].Insert(key.Name)
c.drop(key)
}
```
2）Modified the HandlerFunc to add a resourceName parameter to identify the name of being deleted resource.
> Fix delta ADS client

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
No need to exist `topology.istio.io/network: ""` when the network is not set.
> Fix network label exists on waypoint when no network config is set

- pilot/pkg/features/experimental.go
This is no longer relevant or used anywhere
> Remove unused flag NATIVE_METADATA_EXCHANGE

- cni/pkg/nodeagent/cni-watcher.go
- cni/pkg/nodeagent/ztunnelserver.go
- pilot/pkg/status/resourcelock.go
- pilot/pkg/xds/adstest.go
- pilot/pkg/xds/deltaadstest.go
This should be functionally identical but doesn't waste a goroutine and
is simpler
> context: utilize new AfterFunc to avoid unneeded goroutines

- pilot/pkg/model/sidecar.go
- pilot/pkg/model/virtualservice.go
Minor refactoring:
1. Extract the VS matching logic into `VSMatches` function to be consistent with `Service` matching.
https://github.com/istio/istio/blob/e011f1aec5cdcc0780768aaa31328cad1412f6e8/pilot/pkg/model/sidecar.go#L66
2. Determine whether to use gateway semantics before the for loop (see L46). No need to determine in every loop.
> refactor: extract VSMatches function

- cni/pkg/nodeagent/net.go
- cni/pkg/nodeagent/server.go
duplicated logs output for one event while deleting Pods in ambient mode
```
2024-02-05T02:08:04.497005Z    debug    ambient    Pod is now stopped or opt out... cleaning up.    ns=default name=httpbin-worker1-7b47f9576c-vt8mh                                                                                                       ??
2024-02-05T02:08:04.497028Z    info    ambient    in pod mode - deleting pod from ztunnel    ns=default name=httpbin-worker1-7b47f9576c-vt8mh                                                                                                              ??
2024-02-05T02:08:04.497034Z    debug    ambient    Pod is now stopped or opt out... cleaning up.    ns=default name=httpbin-worker1-7b47f9576c-vt8mh …
```
> ambient: cleanup dup logs while del/opt-out Pods

- pilot/pkg/model/sidecar.go
Use `SidecarScope` as the receiver and extract the `collectImportedServices` and `selectDestinationRules` methods from `convertToSidecarScope`. It is just a modification of the extraction method, no business logic modification.
**Why do this?**
1. Improve readability: `convertToSidecarScope` is large and has many layers of nested `for` and `if` statements, which is not easy to read.
2. Prepare for subsequent refactoring: Although the changes in #49197 are small, "Files changed" on github seems not very smart. Splitting into two PRs will help review.
> Extract method

- istioctl/pkg/wait/wait_test.go
Regression in a new test added in
https://github.com/istio/istio/pull/48958, for negative case we need to
set a low timeout or it takes 30s
> istioctl: avoid 30s Istioctl test

- istioctl/pkg/util/handlers/handlers.go
We used to only have alpha, and no v1. Alpha is long removed, so now
just switch to v1 support. This makes `istioctl pc gtw/foo` work
> istioctl: support v1 Gateway API

- cni/pkg/plugin/plugin.go
cni-plugin: fix plugin execution broken by ambient
cni cmdADD will not take any effect for legacy sidecar mode while cni configuration enabling ambient.
Fortunately/unfortunately, redirection still works in sidecar because we have the repair/reconcile mechanism for sidecar mode.
> cni-plugin: fix plugin execution broken by ambient

- pilot/pkg/networking/core/v1alpha3/httproute_test.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/networking/util/util_test.go
Current hardcoded 2-min value is not very useful - a client can ignore the MaxAge completely, there is no 
verification on the server side. Pods don't have persistence so large MaxAge are also not working properly.
Envoy is moving to add the expiration in the cookie value - which combined with signing or encrypting the 
cookie can provide the proper semantics. There are other factors - like  GDPR treatment of session vs persistent
cookies.
Depends on https://github.com/envoyproxy/envoy/pull/32093
Opening the PR early to get feedback on adding an option to still support 'persistent cookies' with custom 
age - I don't think it's going to be useful . The Gateway API implementation ( which is not yet started ) will
require some expiration - but it …
> Use session cookies instead of 2-min hardcoded persistent cookies

- pkg/kube/krt/recomputetrigger.go
- pkg/kube/krt/recomputetrigger_test.go
Split out of https://github.com/istio/istio/pull/49162
This allows an escape hatch to safely rely on external state from within
krt.
> krt: add new recompute trigger

- cni/deployments/kubernetes/Dockerfile.install-cni
Now the daemonset applies iptables.
See
https://storage.googleapis.com/istio-prow/logs/integ-distroless_istio_postsubmit/1755298748407222272/artifacts/helm-32e3a0798b3b4348b9b6df52a1/TestAmbientInstall/_test_context/istio-system-state2556513034/primary-0/istio-cni-node-dqbl4_install-cni.previous.log
for failure
> cni: use iptables distroless variant

- pkg/kube/kclient/client.go
Currently, if we add a handler after the informer has stopped, it will
crash. This is not great, though it rarely happens.
Better handling of this is to just not add the handler.
Note this cannot be handled by clients, since there would be TOCTOU race
conditions (and we don't expose HasStopped anyways)
> kclient: do not panic on handlers after stopped

- pkg/kube/multicluster/secretcontroller.go
This just makes the output a bit more robust so we can see all clusters
in one place
> debug: include config cluster in clusterz

- pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
- pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
- releasenotes/notes/istio-ca-root-cert-kube-system.yaml
- security/pkg/k8s/configutil.go
- security/pkg/k8s/configutil_test.go
This is a simplified approach to #49129, which we discussed on WG ambient meeting. We agreed that istiod will try to create `istio-ca-root-cert` in the `kube-system` namespace. I did not add any special handling of an error that might be returned for kube-system, because I don't know how different distros restrict it. I guess it would be a permission error, but then it couldn't be distinguished from missing permissions on any other cluster.
I created another PR to not lose the context of the previous approach.
> pilot: do not skip creating istio-ca-root-cert in kube-system namespace

- cni/pkg/pluginlistener/listener_test.go
This allows parallel invocations to run
> cni: use dedicated test tmpdir

- pkg/istio-agent/xds_proxy_delta.go
- pkg/istio-agent/xds_proxy_delta_test.go
This was caused by only sending the `Resource`, and ignoring the other
fields (Name, version, etc).
Fixes https://github.com/istio/istio/issues/47227
> Fix empty ECDS with Delta XDS

- pilot/pkg/grpc/grpc.go
We have code to treat RST_STREAM as expected, but not if there is a
prior GOAWAY. See
https://storage.googleapis.com/istio-prow/pr-logs/pull/istio_istio/49260/integ-security_istio/1755799139888664576/artifacts/security-sds-ingress-dae3bc96b8/TestSingleTlsGateway_SecretRotation/to_a/new_cert_should_succeed/_test_context/istio-state1328832520/primary-0/istio-ingressgateway-6d88cf45d6-zvf6l_istio-proxy.log
for when this happens in Istio
> agent: treat GOAWAY as expected

- cni/pkg/plugin/kubernetes.go
- cni/pkg/plugin/plugin.go
- cni/pkg/plugin/plugin_cni_conformance.go
- cni/pkg/plugin/plugin_dryrun_test.go
- cni/pkg/plugin/plugin_test.go
- cni/pkg/plugin/sidecar_intercept_rule_mgr.go
- cni/pkg/repair/repaircontroller.go
Some of the CNI plugin tests that predate ambient make heavy use of global state (which naturally creates ordering and concurrency bugs) and generally do confusing/intrusive DIY mocking.
As part of inpod ambient I had added more tests to this suite, and added some FIXME nags to the existing machinery that clearly needed some TLC, but https://github.com/istio/istio/issues/49278 reminded me that I had punted on actually fully reworking this suite and the existing plugin code so it's less problematic/tests don't have loads of global state/don't do confusing mocking/don't have mysterious ordering or concurrency bugs.
> Clean up old plugin tests

- pilot/pkg/config/monitor/file_snapshot.go
- pilot/pkg/config/monitor/monitor.go
- security/pkg/pki/util/san_test.go
Fix lint errors updating golangci-lint-version to 1.56 in https://github.com/istio/common-files/pull/987.
> Fix lint errors updating linter to 1.56

- pkg/kube/util.go
- pkg/kube/util_test.go
This makes it so the detected "workload name" is the rollout name, not
the autogenerated replicaset name
> inject: detect deployment metadata for ArgoCD Rollout

- samples/jwt-server/src/Makefile
- samples/jwt-server/src/main.go
This will add an option to delay responses of the jwt server.
Needed for integration tests for per-jwtrule timeout in #48203
> Add delay parameter to jwt server sample

- go.mod
Go 1.22 includes changes to the language (see https://tip.golang.org/doc/go1.22#language). It's possible that some unit tests may break or bugs appear. Let's start testing this early before 1.22.
> Use go 1.22

- istioctl/pkg/precheck/precheck.go
- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- releasenotes/notes/49364.yaml
VirtualServices have special behavior when configuring outbound routes on port 80. Therefore, we need to make sure that wildcard hosts _not_ matching any service in the service registry get added to the generated set of routes
> Make sure unknown vhosts fall through and get added eventually (if on port 80)

- pilot/pkg/features/xds.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- releasenotes/notes/drop-headless.yaml
This has been enabled by default for many years
> Cleanup legacy PILOT_ENABLE_HEADLESS_SERVICE_POD_LISTENERS flag

- go.mod
- tools/istio-iptables/pkg/dependencies/implementation_linux_test.go
use direct netns compare instead of inferring equality from interface listing
> update TestRunInSandbox checks

- tests/integration/pilot/headers_test.go
Tests are failing in Anthos when ran for multiversion clusters. Setting the MinVersion of Istio will run the ProxyHeaders test only for clusters with minimum Istio version 1.19
> Adding MinIstioVersion for TestProxyHeaders

- pilot/pkg/model/config.go
- pilot/pkg/xds/discovery.go
To prevent the use of Service by mistake, we all use ServiceEntry now
> Assert kind.Service is disallowed in ConfigKey

- pkg/dns/client/dns.go
- pkg/dns/client/dns_test.go
- releasenotes/notes/47340.yaml
Fixes #47340
If we already have an unambigous name, don't generate additional alternatives hosts.
Otherwise we will end up with something like istio-egressgateway.istio-system.svc..
> dns: don't generate alt-hosts for FQDN

- istioctl/pkg/util/configdump/wrapper.go
- istioctl/pkg/writer/envoy/configdump/configdump.go
- pkg/util/protomarshal/protomarshal.go
- releasenotes/notes/49511.yaml
Currently If a proxy has the ECDS config synced, `x ps` will fail with something like:
```
istioctl x ps httpbin-5f646964cb-ftj22.bookinfo
Error: can't unmarshal Any nested proto type.googleapis.com/envoy.admin.v3.EcdsConfigDump: can't unmarshal Any nested proto type.googleapis.com/envoy.config.core.v3.TypedExtensionConfig: can't unmarshal Any nested proto type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm: Any JSON doesn't have '@type'
```
Since ps will be replaced with `experimental ps` soon, I'd just fix the `experimental ps` command.
Also, this PR improves `pc` to handle unknown types that may caused by envoy mismatch.
> istioctl: fix commands rely on config dump may not work due to the presence of ECDS config or unknown config

- pkg/config/validation/virtualservice.go
- pkg/config/validation/virtualservice_test.go
fix #49607
Validation logic is copied from the validation headers (except with minor adjustments), see:
https://github.com/istio/istio/blob/e09586dc04198cda05224b7d26b6be237a37e7a3/pkg/config/validation/virtualservice.go#L141
> withoutHeaders supports verification

- pilot/pkg/model/push_context_test.go
**Adding missing priority field in the push_context test data**
Test data `a-medium-priority` should have priority 10. It is currently relying on the default priority.
> Fixing the priority of the test data in the `push_context`

- istio.deps
This reverts commit c204ecaff7af64f905cd51c6fc75844993b2dc1b.
See https://github.com/istio/istio/issues/49561 for more info.
> Revert "use correct proxy sha (#49568)"

- istio.deps
This reverts commit cec0ca7a46b9bace7781b5c5a9046962a079d9d7.
See https://github.com/istio/istio/issues/49561 for more info.
> Revert "use correct proxy sha"

- pilot/pkg/networking/core/v1alpha3/cluster.go
```
2024-03-01T00:48:03.248589Z	info	ads	Push Status: {
"pilot_duplicate_envoy_clusters": {
"connect_originate": {
"proxy": "waypoint-istio-waypoint-675bfdb76c-xtbmg.echo-1-909",
"message": "Duplicate cluster connect_originate found while pushing CDS"
}
},
```
> fix gen duplicate clusters

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/helpers.go
- pilot/pkg/serviceregistry/kube/controller/ambient/services.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pkg/slices/slices.go
This protects against theoretical errors, and 2 real ones that can cause a panic: SE with CIDR, and weird Pods
> ambient: make IP handling safe

- pilot/pkg/bootstrap/sidecarinjector.go
- pkg/kube/inject/webhook.go
Fix nil-pointer dereference on OpenShift introduced in #49336. A `MultiCluster` field was introduced that is only accessed on the OpenShift platform, but it was never initialized.
cc @howardjohn
> Fix nil-pointer dereference on OpenShift introduced in #49336

- pilot/pkg/bootstrap/sidecarinjector.go
- pkg/kube/inject/webhook.go
We're retrieving the client from the MultiCluster object now.
This is a leftover from https://github.com/istio/istio/pull/49336 and https://github.com/istio/istio/pull/49689
> Remove KubeClient from webhookParameters

- istioctl/pkg/proxyconfig/proxyconfig.go
- releasenotes/notes/envoy-stats-proxy-admin-port.yaml
> istioctl: `experimental envoy-stats` supports custom proxy admin port

- pilot/pkg/model/telemetry_logging.go
- pilot/pkg/model/telemetry_logging_test.go
- pilot/pkg/model/telemetry_test.go
- pilot/pkg/networking/core/v1alpha3/accesslog_test.go
- releasenotes/notes/json-log-sort.yaml
This reverts commit 232df85afd85ebcabe3208e3149047893177f14f.
> 1.21: Revert "logging: ordered json keys (#48882)"

- pilot/pkg/features/tuning.go
The pilot xds send timeout is removed in https://github.com/istio/istio/pull/48543, we think we can remove the env parameter PILOT_XDS_SEND_TIMEOUT safely.
> remove unused parameter PILOT_XDS_SEND_TIMEOUT
