istio/istio

- pilot/pkg/networking/core/v1alpha3/httproute.go
This causes a NACK in Envoy
Fixes https://github.com/istio/istio/issues/42510
> Fix large direct response

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
- pkg/kube/controllers/informer.go
> controllers: add abstraction to easier handle cleanup of informers

- pilot/pkg/model/xds_cache.go
- pilot/pkg/xds/xds_cache_test.go
> rm lenientxdscache

- pilot/pkg/model/telemetry_metric_test.go
> telemetry: add metric ut

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- releasenotes/notes/43436.yaml
This is a manual cherry pick of #43436
Fixes #43559
> [release-1.15] Manual cherry-pick of #43436

- pilot/pkg/model/service.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/networking/util/util_test.go
- pilot/pkg/xds/endpoint_builder.go
- pilot/pkg/xds/ep_filters.go
> add endpoint metadata struct

- pilot/pkg/model/service.go
- pilot/pkg/xds/ads_test.go
> Cleanup unused namespace constant

- pilot/cmd/pilot-agent/status/server_test.go
- pilot/pkg/xds/debug_test.go
- pilot/pkg/xds/eds_test.go
- pkg/bootstrap/platform/azure.go
- pkg/istio-agent/health/health_probers.go
- pkg/kube/inject/webhook_test.go
- pkg/spiffe/spiffe_test.go
- samples/extauthz/cmd/extauthz/main_test.go
- samples/jwt-server/src/main_test.go
- security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
- security/pkg/stsservice/server/server_test.go
- security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin.go
- security/pkg/stsservice/tokenmanager/sts_test.go
Use http constants to replace numbers
> Use http constants to replace strings

- istio.deps
The ztunnel was from 2/14, didn't have the latest few changes, including @ymesika 's L4 metrics change.
- [x ] Ambient
> Update to latest ztunnel

- pilot/pkg/features/pilot.go
- pilot/pkg/model/xds_cache.go
- pilot/pkg/model/xds_cache_test.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/discovery.go
For https://github.com/istio/istio/issues/43431
> Async clearing config index

- bin/init.sh
- istio.deps
- pilot/docker/Dockerfile.proxyv2
- tools/docker.yaml
- tools/packaging/packaging.mk
> cleanup build

- pilot/pkg/networking/core/v1alpha3/tracing.go
follow up: https://github.com/istio/istio/pull/43453#discussion_r1112038814
cc @ramaraochavali
> tracing: reuse `buildHCMTracing`

- istioctl/cmd/waypoint.go
- tests/integration/ambient/bookinfo_test.go
To make it more convenient to control the waypoint, use the same mechanism as `apply` instead of searching for the Gateway resource to delete.
> Add waypoint delete cmd

- pilot/pkg/networking/core/v1alpha3/tracing.go
xref: https://github.com/istio/istio.io/pull/12784
> tracing: remove TODO

- go.mod
- pilot/pkg/xds/sds.go
- pilot/pkg/xds/sds_test.go
- releasenotes/notes/41761.yaml
Manual cherrypick of #41761, fixes #43520.
> [release-1.16] Fix PrivateKeyProvider's problem with proxy-config

- go.mod
- pilot/pkg/xds/sds.go
- pilot/pkg/xds/sds_test.go
- releasenotes/notes/41761.yaml
Manual cherry pick of PR #41761 fixes #43519.
> [release-1.15] Fix PrivateKeyProvider's problem with proxy-config

- istioctl/cmd/waypoint.go
Mainly to have a better error message for the users if the CRDs don't exist.
> Check for K8S GW CRDs before applying waypoint

- istioctl/cmd/describe.go
- istioctl/cmd/describe_test.go
- istioctl/cmd/testdata/describe/http_config.json
- releasenotes/notes/43398.yaml
Fix https://github.com/istio/istio/issues/43368
> Fix x describe do not work with weighted routes to different hosts

- pilot/cmd/pilot-agent/status/server.go
Upstream: https://github.com/kubernetes/kubernetes/pull/115321
> Mirror k8s grpc probes

- pkg/config/analysis/analyzers/injection/injection.go
- pkg/config/analysis/analyzers/testdata/injection.yaml
part of https://github.com/istio/istio/issues/43589
> fix namespace injection warning when ambient is enabled

- istioctl/pkg/util/handlers/handlers.go
- pilot/pkg/config/kube/gateway/conversion.go
updated reference missed in earlier PR's
> use the same constants value for managed gateway label name

- istioctl/cmd/waypoint.go
Addressing a late review comment: https://github.com/istio/istio/pull/43620#discussion_r1118978570
of previous PR.
> Use errors.IsNotFound instead of message check

- pkg/test/kube/util.go
- tests/integration/ambient/bookinfo_test.go
> Fix bookinfo deleteWaypoints test

- pilot/pkg/model/config.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/aggregate/controller.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/memory/discovery.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/lds.go
Fixes https://github.com/istio/istio/issues/42318
> ambient: use incremental push on pod update

- tests/integration/ambient/bookinfo_test.go
creates and deletes a waypoint in front of productpage to verify ingress gateway is receiving endpoint updates on waypoint change
related to https://github.com/istio/istio/issues/42866#issuecomment-1406572832
- [ X  ] Ambient
> add integ test for testing waypoint changes in ingress gateway

- pilot/pkg/model/context_test.go
Signed-off-by: tanberBro [pengfei.song@daocloud.io](mailto:pengfei.song@daocloud.io)
/cleanup
> remove redundant types conversion

- pilot/pkg/model/typed_xds_cache.go
- pilot/pkg/model/typed_xds_cache_test.go
- pilot/pkg/model/xds_cache.go
> move cache eviction loop to xds cache impl

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
> ambient handle pod cleanups

- pkg/config/analysis/analyzers/all.go
- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/telemetry/defaultselector.go
- pkg/config/analysis/analyzers/telemetry/selector.go
- pkg/config/analysis/analyzers/telemetry/util.go
- pkg/config/analysis/analyzers/testdata/telemetry-default-selector.yaml
- pkg/config/analysis/analyzers/testdata/telemetry-selector.yaml
- pkg/config/analysis/analyzers/util/find_errorline_utils.go
- pkg/config/analysis/msg/messages.gen.go
- pkg/config/analysis/msg/messages.yaml
- releasenotes/notes/43706.yaml
xref: https://github.com/istio/istio/issues/43705
@zirain @howardjohn  @hzxuzhonghu
> add two telemetry analyzers

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_waypoint.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_builder.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
follow https://github.com/istio/istio/pull/43723
It includes 
- hbone transport socket sharing
- decouple waypoint listener build from sidecar
- hardcoding elimination
> cleanups for hbone and ambient

- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/networking/core/v1alpha3/route/route.go
Fixes https://github.com/istio/istio/issues/43722
Maybe we should merge this with `pilot/pkg/networking/core/v1alpha3/route` in the future
> Support DirectResponse for waypoints

- pilot/pkg/model/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
- releasenotes/notes/43688.yaml
fix https://github.com/istio/istio/issues/43688
- [ x] Networking
> fix gateway bind with same port and different protocol

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- releasenotes/notes/43710.yaml
Fix https://github.com/istio/istio/issues/43710.
cc @hzxuzhonghu
> Add prefix matching on query parameter

- cni/pkg/ambient/informers.go
I have no clue yet how this passed tests before. Will followup on that, but for now fixing it at least
> ambient: fix wrong namespace usage

- pkg/kube/controllers/queue.go
Currently we may spam an entire huge 10000 byte k8s object with some usage. Instead, try to extract to a simple key
> queue: do not expose spammy logs

- release/downloadIstioCtl.sh
- releasenotes/notes/43771.yaml
Currently at the end of the script the directory changes to home.
> Download and install istioctl without path change

- pilot/pkg/features/pilot.go
Fix a typo in the environment variable description.
> fix a typo in the SPIFFE_BUNDLE_ENDPOINTS description

- cni/pkg/install/binaries.go
use struct{}{} and determine whether it is a folder in advance
> copyBinaries: use struct{} and isDir

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/deployment/services.go
- pkg/config/analysis/analyzers/testdata/deployment-service-no-selector.yaml
- releasenotes/notes/43652.yaml
Fix https://github.com/istio/istio/issues/43677
> [release-1.16] Manual cherry-pick of https://github.com/istio/istio/pull/43652

- pilot/pkg/serviceregistry/serviceentry/controller.go
> Replace `reflect.DeepEqual` with `service.Equals`

- pilot/pkg/networking/util/util.go
- pilot/pkg/networking/util/util_test.go
Fix MaybeApplyTLSModeLabel function which have potential risk of crash.
I've encountered this crash in 1.15 and 1.16 Istio environments, but I don't quite know how to reproduce it
> Fix  MaybeApplyTLSModeLabel function

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_logging_test.go
- pilot/pkg/networking/core/v1alpha3/accesslog.go
- pilot/pkg/networking/core/v1alpha3/accesslog_test.go
Manual cherry-pick, fix #43784
> [release-1.17] AccessLogging: fix the issue where disable accesslogging does not take effect

- tests/fuzz/oss_fuzz_build.sh
Flags the parameters to the instrumentation utility in the OSS-Fuzz build script based on recent upstream changes.
> fuzzing: flag parameters in instrumentation utility

- pilot/pkg/serviceregistry/kube/controller/fake.go
- pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go
- pilot/pkg/xds/fake.go
- pkg/kube/client.go
> pilot: wait for queue to complete in test

- istioctl/pkg/writer/ztunnel/configdump/workload.go
- releasenotes/notes/43311.yaml
> Print waypoint name in istioctl pc workloads

- pilot/pkg/serviceregistry/kube/controller/controller.go
This just cleans up the code a bit, no need to store functions in struct
instead of using standard methods
> controller: minor refactor of function to method

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_logging_test.go
- pilot/pkg/networking/core/v1alpha3/accesslog.go
- pilot/pkg/networking/core/v1alpha3/accesslog_test.go
- releasenotes/notes/43372.yaml
> [release-1.16]  Manual cherry-pick to fix #43590 and #43783

- istioctl/pkg/util/handlers/handlers.go
- istioctl/pkg/util/handlers/handlers_test.go
- releasenotes/notes/43709.yaml
Fix https://github.com/istio/istio/issues/43691
Should use the inferred namespace https://github.com/hanxiaop/istio/blob/b247ddba7aeb041b4fc6e47256e15323f7e4be4e/istioctl/pkg/util/handlers/handlers.go#L140 instead of the default namespace.
> Fix name resolution in istioctl command

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/authz/authorizationpolicies.go
- pkg/config/analysis/analyzers/testdata/authorizationpolicies.yaml
- pkg/config/analysis/analyzers/util/in_mesh.go
Before it was only including those with sidecars. Needs to include pods in ambient mode.
> Fix analyzing ambient mode authorizationpolicy has no matching workload message error

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
> refactor: move cb(handleService/handlePod) as method of ambient index

- pkg/config/schema/codegen/collections.go
- pkg/config/schema/codegen/common.go
- pkg/config/schema/kubeclient/resources.gen.go
- pkg/config/schema/kubetypes/resources.gen.go
- pkg/kube/kubetypes/types.go
This is part 1 of https://github.com/istio/istio/pull/43725, splitting out the code generation part. This is no-risk; the code is unused.
> kube: wrapper around informer PART 1: codegen

- releasenotes/notes/43850.yaml
- tools/bug-report/pkg/bugreport/bugreport.go
- tools/bug-report/pkg/bugreport/flags.go
Fix https://github.com/istio/istio/issues/43842
> Add output dir option to bug-report

- pkg/test/framework/components/istio/cleanup.go
- pkg/test/framework/components/istio/config.go
- pkg/test/framework/components/istio/flags.go
- pkg/test/framework/components/istio/kube.go
- pkg/test/kube/dump.go
- pkg/test/kube/util.go
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/common/traffic.go
Cherry-pick of #43809 due to merge conflicts. Fixes #43864
> [release-1.17] Break system namespace and ingressgateway assumptions

- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- releasenotes/notes/43853.yaml
> ServiceEntry deletion - trigger endpoint shard update when some endpoints are remaining

- pkg/kube/client.go
> port forward return error if status code is not 200

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
When a pod is just created, the pod handler will be triggered several times where it scans all authorization policies in the namespace. 
We should skip the process for pending pods given this is a hot path
> Optimize AmbientIndex pod handler

- pilot/pkg/features/pilot.go
- releasenotes/notes/43104.yaml
Resolves https://github.com/istio/istio/issues/43104
To answer the common need to reload intermediate cert.
> Enable AUTO_RELOAD_PLUGIN_CERTS by default

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/testdata/envoy-filter-filterchain.yaml
add UT for https://github.com/istio/istio/pull/42832
fixes: https://github.com/istio/istio/issues/43957
> add UT for envoyfilter analyze

- tools/istio-iptables/pkg/dependencies/implementation_unspecified.go
Broken due to https://github.com/istio/istio/pull/43945
> Fix MacOS build

- cni/pkg/ambient/net_linux.go
Resolves https://github.com/istio/istio/issues/43942
> Change iptables chain name to capitals

- pilot/pkg/serviceregistry/kube/controller/fuzz_test.go
if its an unknown one, it defaults to Endpoints, not EndpointSlice
> fuzz: fix default endpoints controller

- samples/kind-lb/setupkind.sh
```
kind-lb/setupkind.sh --cluster-name istio --k8s-release 1.25.3 --mode ambient
```
> samples: support setup multi nodes mode cluster

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
> Only handle pod on pod labels, annotation or phase update

- istioctl/cmd/proxyconfig.go
> istioctl: proxyconfig all support ztunnel

- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/kube/controller/fake.go
This got broken in
https://github.com/istio/istio/commit/6d06a6d99b01b1daf6278c890fba1e1c05b8cc38
> controller: properly fail on timeout

- pkg/config/schema/codegen/collections.go
- pkg/config/schema/kubeclient/resources.gen.go
- pkg/config/schema/kubetypes/resources.gen.go
Simple refactoring, we can do better than reflection
> kube: drop reflection usage

- pilot/pkg/model/proxy_config.go
- pilot/pkg/model/proxy_config_test.go
- pkg/bootstrap/instance_test.go
- pkg/bootstrap/testdata/tracing_none.proxycfg
- pkg/bootstrap/testdata/tracing_none_golden.json
- pkg/config/mesh/mesh.go
- pkg/kube/inject/inject_test.go
- pkg/kube/inject/testdata/inject/hello-tracing-disabled.yaml
- pkg/kube/inject/testdata/inject/hello-tracing-disabled.yaml.injected
- releasenotes/notes/42518.yaml
> [release-1.16] tracing: Update proxyConfig.Tracing merge logic (#42518)

- istioctl/pkg/writer/pilot/status.go
- istioctl/pkg/writer/pilot/status_test.go
- istioctl/pkg/writer/pilot/testdata/multiStatusMultiPilot.txt
- istioctl/pkg/writer/pilot/testdata/multiXdsStatusMultiPilot.txt
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/statusgen.go
Fix https://github.com/istio/istio/issues/43877
- [ X] User Experience
> Fix the istioctl x ps is missing ztunnel statuses 

- bin/update_deps.sh
Distroless images should be updated periodically. 
Add Ztunnel Dockerfilecapability to update_deps.sh so it gets updated.
- Test and Release
- Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
> Add Ztunnel Dockerfile to update_deps script

- pilot/pkg/model/proxy_config.go
- pilot/pkg/model/proxy_config_test.go
- pkg/bootstrap/instance_test.go
- pkg/bootstrap/testdata/tracing_none.proxycfg
- pkg/bootstrap/testdata/tracing_none_golden.json
- pkg/config/mesh/mesh.go
- pkg/kube/inject/inject_test.go
- pkg/kube/inject/testdata/inject/hello-tracing-disabled.yaml
- pkg/kube/inject/testdata/inject/hello-tracing-disabled.yaml.injected
- releasenotes/notes/42518.yaml
> [release-1.17] tracing: Update proxyConfig.Tracing merge logic (#42518)

- tools/bug-report/pkg/content/content.go
This is now the default, and soon to be only method for endpoint config. So we need to collect it.
> Add endpointslices to bug-report dump

- istioctl/cmd/proxyconfig.go
Namespace inferring should use istioNamespace instead of defaultNamespace
> Fix pc workloads ztunnel workload namespace guess

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/telemetry/lightstep.go
- pkg/config/analysis/msg/messages.gen.go
- pkg/config/analysis/msg/messages.yaml
follow up: https://github.com/istio/istio/pull/43998#discussion_r1142214655
> reuse msg.NewDeprecated

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/config/kube/ingress/controller.go
- pilot/pkg/config/kube/ingress/status.go
- pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
- pkg/kube/controllers/common.go
> controllers: ensure we shutdown handlers in more places

- pkg/config/labels/instance.go
> optimize labels.Equal

- pilot/pkg/networking/core/v1alpha3/gateway.go
> remove stale comment in gateway code

- pilot/pkg/serviceregistry/kube/controller/autoserviceexportcontroller.go
- pkg/kube/controllers/example_test.go
This includes all the fixes in kclient, such as proper syncing.
Also update the example to show properly shutting down
> controllers: move auto export over to kclient

- manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
- manifests/charts/istio-control/istio-discovery/files/gen-istio.yaml
- manifests/charts/istiod-remote/files/gateway-injection-template.yaml
- pkg/kube/inject/testdata/inputs/custom-template.yaml.34.template.gen.yaml
- pkg/kube/inject/testdata/inputs/default.template.gen.yaml
- pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
- pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
- pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
- pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
- releasenotes/notes/33237.yaml
This is a manual cherry-pick of #43668.
> [release-1.16] Fix gateway injection when istio.io/rev=<tag>

- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- pilot/pkg/serviceregistry/util/xdsfake/updater.go
Ensure we do not have extra events, which can be major regressions
> se: perform stricter XDS event validation

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/serviceexportcache.go
- pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
- pkg/kube/kclient/client.go
- pkg/kube/kclient/index_test.go
Very minor changes - no functional impact
> minor changes in kclient

- pkg/kube/util.go
> Strip more unused pod fields

- istioctl/cmd/proxyconfig.go
- istioctl/pkg/util/configdump/workload.go
- istioctl/pkg/writer/configwriter.go
- istioctl/pkg/writer/ztunnel/configdump/configdump.go
- istioctl/pkg/writer/ztunnel/configdump/configdump_test.go
- istioctl/pkg/writer/ztunnel/configdump/testdata/dump.json
- istioctl/pkg/writer/ztunnel/configdump/testdata/secretsummary.txt
part of https://github.com/istio/ztunnel/issues/166
> first pass implementing istioctl pc secret for ztunnel

- samples/open-telemetry/tracing/README.md
The extensionProvider should not be in the defaultConfig.
> Fix otel tracing sample

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/fake.go
- pilot/pkg/serviceregistry/kube/controller/multicluster.go
- pilot/pkg/xds/fake.go
> Fix workload in remote clusters missing authz policy

- pilot/pkg/model/telemetry_logging.go
- pilot/pkg/model/telemetry_logging_test.go
- pilot/pkg/model/telemetry_test.go
- releasenotes/notes/44105.yaml
fixes: #44074
cc @kyessenov @lei-tang
> accesslog: support METADATA command operator

- pkg/config/analysis/analyzers/telemetry/lightstep.go
As a supplement to https://github.com/istio/istio/pull/40887
> `sets`: move to generic set

- go.mod
- go.sum
See https://github.com/grpc/grpc-go/releases/tag/v1.54.0
> Update grpc lib

- pilot/pkg/serviceregistry/kube/controller/pod.go
- pkg/wasm/imagefetcher.go
> refactor: cleanup some DeepEqual usages

- pilot/pkg/model/endpointshards.go
This impacts both the new AssertEndpointsConsistency and the shardz debug
endpoint on Istiod
Fixes https://github.com/istio/istio/issues/44136
Alternative to https://github.com/istio/istio/pull/44112
> Endpoints: fix shardz races

- pilot/pkg/config/kube/gateway/conditions.go
- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/testdata/alias.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/delegated.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/eastwest.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/mcs.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/mesh.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/multi-gateway.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/reference-policy-service.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/route-binding.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/route-precedence.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/serviceentry.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/tcp.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/tls.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/waypoint.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/weighted.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/zero.status.yaml.golden
This is still in flux a bit (https://github.com/kubernetes-sigs/gateway-api/issues/1832#issuecomment-1487167378), but this will unblock docs at least and I am committed to resolving the disputes upstream before 1.18.
> gateway-api: fix Programmed to wait until there is an address

- istioctl/cmd/testdata/waypoint/all-gateway
- istioctl/cmd/testdata/waypoint/combined-gateway
- istioctl/cmd/testdata/waypoint/default-gateway
- istioctl/cmd/testdata/waypoint/no-gateway
- istioctl/cmd/waypoint.go
- istioctl/cmd/waypoint_test.go
To list available waypoints, convenient before doing deletion.
Also, extend `x waypoint delete` to support deleting by names
> Add waypoint list cmd

- istioctl/cmd/revision.go
- istioctl/cmd/revision_test.go
- releasenotes/notes/44002.yaml
fix https://github.com/istio/istio/issues/44002
> >fix istioctl x revision describe, error output

- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
> Remove deprecated flag ISTIO_GATEWAY_STRIP_HOST_PORT.

- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/v1alpha3/listener_builder.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
> always enable grpc stats filter

- bin/update_deps.sh
- docker/Dockerfile.distroless
- go.mod
- go.sum
- istio.deps
- pilot/docker/Dockerfile.ztunnel
- prow/release-commit.sh
Update the ztunnel commit as part of update_deps.sh
First commit is script update, second commit is changes from running the script.
> Add ztunnel updating to update_deps.sh

- pkg/dns/client/dns.go
- releasenotes/notes/44151.yaml
> fix: increment failures in dns serverFailure function

- pilot/pkg/bootstrap/configcontroller.go
Add and improve log format output.
> Add and improve log format output.

- istioctl/cmd/dashboard.go
Which cause test failure https://github.com/istio/istio.io/pull/12962.
More details in https://github.com/istio/istio/pull/43177#issuecomment-1487894417
> Fix skywalking default port

- pilot/pkg/config/kube/gateway/controller_test.go
Fixes
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1641066377626259456
> Fix test flake in namespace controller

- pkg/kube/kclient/client.go
- pkg/kube/kclient/client_test.go
I think its logically correct to trigger Updates to/from filtering as Add/Delete. K8s does this too; we should adopt their behavior and simplify our code by using theirs.
> kclient: fix filtering

- releasenotes/notes/grpc-stats.yaml
fixes: #43908
add release-notes for https://github.com/istio/proxy/pull/4547
> add release-notes for grpc stats

- pilot/pkg/serviceregistry/serviceentry/controller.go
Align with logic in GetProxyServiceInstances. Noticed this during a refactor
> GetProxyWorkloadLabels: check namespace properly

- istioctl/cmd/waypoint.go
- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
- pkg/revisions/tag_watcher.go
- tests/integration/ambient/bookinfo_test.go
- tests/integration/ambient/main_test.go
Needs default tag handling and tests.
> Add Tag and Revision support to waypoints, gateway API.

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/44195.yaml
Fixes https://github.com/istio/istio/issues/44195
> reject partial wildcard hosts in service entry for HTTPS protocol

- releasenotes/notes/gateway-api118.yaml
> add release note for gateway deployment changes

- pilot/pkg/config/kube/gateway/templates/deployment.yaml
- pilot/pkg/config/kube/gateway/templates/service.yaml
Fixes https://github.com/istio/istio/issues/44223
No notes as it is a bug-fix for an unreleased patch.
> [1.17] gateway: remove internal annotation from propogating (#44220)

- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/test/xdstest/validate.go
This causes a NACK in Envoy
Fixes #44280
> fix(networking): support large direct response on gateways

- tests/integration/telemetry/envoyfilter/customizemetrics/customize_metrics_test.go
> Integration Test for Istio custom GRPC count metrics

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
We should also match `/` only.
> gateway: fix replacefullpath when request is to /

- pilot/pkg/model/network.go
- pilot/pkg/model/network_test.go
- releasenotes/notes/gw-hostname-resolution.yaml
Fixes https://github.com/istio/istio/issues/44155
> Retry when east-west gateway hostname resolution fails

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
fixes https://github.com/istio/istio/issues/43439
This adds a check to apply that the resource either does not exist or has the managed label. This ensures that we do not overwrite users existing resources, which could cause an outage, etc.
A few concerns though...:
* Its racy; if a user deploys a folder of YAML with a Gateway and a Service, depending on the ordering we may manage it or may not. With Apply semantics, their `apply service.yaml` will NOT make it unmanaged since it would merge labels with the controller
* Its also racy even if user is careful due to implementation. We are using Apply, which cannot do preconditions. So we have a TOCTOU race where we may see it is "managed" (or not existing) and decide to apply, but that changes before we actually Apply. AFAIK k8s can't do …
> gateway: skip un-managed types in deploymentcontroller

- pkg/config/validation/validation.go
> Add nil-check for WASM validation

- pkg/config/analysis/analyzers/maturity/maturity.go
- pkg/config/analysis/analyzers/testdata/misannotated.yaml
It is not created by users, should not send any messages.
> Skip gateway.istio.io/controller-version annotation message in analyzer

- pkg/test/framework/features/features.yaml
- tests/integration/telemetry/api/stats_test.go
- tests/integration/telemetry/common/stats.go
- tests/integration/telemetry/envoyfilter/customizemetrics/customize_metrics_test.go
- tests/integration/telemetry/envoyfilter/nullvm/stats_filter_test.go
reuse test in EnvoyFilter and Telemetry API
> e2e: refactor grpc stats test

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/conversion_test.go
- pilot/pkg/config/kube/gateway/deploymentcontroller.go
Fixes https://github.com/istio/istio/issues/44363
> gateway-api: fix naming override

- pkg/config/validation/validation.go
> validation: add small nil check

- istioctl/cmd/proxyconfig.go
- istioctl/cmd/proxyconfig_test.go
- istioctl/pkg/util/ambient/util.go
- tools/bug-report/pkg/bugreport/bugreport.go
> Add a better check for ztunnel pod guess

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/conversion_test.go
- pilot/pkg/config/kube/gateway/deploymentcontroller.go
Fixes https://github.com/istio/istio/issues/44375
> [release-1.17] gateway-api: fix naming override

- pkg/test/echo/server/forwarder/grpc.go
For session affinity testing it is useful to see the response headers ( metadata )
- [ x] Networking
> Add response headers for grpc

- samples/bookinfo/src/productpage/requirements.txt
When I build the productpage, it will be fail:
The test result after the change:
> fix:productpage build fail

- go.mod
- go.sum
- istio.deps
- prow/release-commit.sh
Run update_deps to fix up everything after the various commmon-files updates today.
> Run update_deps.sh

- pilot/pkg/xds/xdsgen.go
This PR proposes the lazy evaluation of `controlPlane`.
By this way, "POD_NAME" being set after the process start can be properly used for "ID" of the control plane.
Change-Id: I31adfcb808d04aef51c42ddaed5b3473db2397a5
> Lazy evaluation of `controlPlane` to allow the lazy POD_NAME env var setting

- go.mod
- go.sum
- pkg/config/xds/filter_types.gen.go
- prow/release-commit.sh
Re-opened to fix incorrect committer ID / CLA failures.  As per previous PR, I've checked that all the changes are roll-forwards, not back
> update_deps for 1.18 branch cut

- pkg/config/analysis/analyzers/gateway/conflictinggateway.go
- releasenotes/notes/fix-44318.yaml
fix bug: https://github.com/istio/istio/issues/44318
> >fix `istioctl analyze` to panic when the server port in gateway is nil.

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- releasenotes/notes/44439.yaml
Fixes https://github.com/istio/istio/issues/44439
This bug also impacts ambient mode
> Fix missing gateway services

- tools/bug-report/pkg/bugreport/bugreport.go
Currently the dry run logic of bug-report still write files and create the archive
> bug report: fix dry-run logic

- istioctl/cmd/istiodconfig.go
> update admin log Use

- cni/pkg/log/uds.go
- cni/pkg/monitoring/monitoring.go
- pilot/pkg/bootstrap/server.go
- pkg/istio-agent/xds_proxy.go
- pkg/network/error.go
- security/pkg/stsservice/server/server.go
> Check expected http error

- istioctl/cmd/checkinject.go
Previous output：
Output after adjustment：
> improve check-inject example output

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/gateway/conflictinggateway.go
- pkg/config/analysis/analyzers/testdata/conflicting-gateways-invalid-port.yaml
fix bug https://github.com/istio/istio/issues/44318,
and add ut
> fix confilict gateway analysis and add ut

- istioctl/cmd/workload.go
> improve istioctl workload example

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- releasenotes/notes/44439.yaml
Fixes https://github.com/istio/istio/issues/44452
> [release-1.17] Fix missing gateway services

- tests/integration/pilot/gateway_conformance_test.go
> enable GatewayConformance on multicluster

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- releasenotes/notes/44439.yaml
Fixes https://github.com/istio/istio/issues/44451
> [release-1.16] Fix missing gateway services

- CODEOWNERS
> Make analysis owned by networking and UX

- istioctl/cmd/waypoint.go
Didn't notice the example field very carefully. Also added missing examples of new commands to the waypoint management example.
> istioctl: format waypoint cmd and add more examples

- istioctl/pkg/validate/validate.go
- istioctl/pkg/validate/validate_test.go
- releasenotes/notes/44293.yaml
> Support validate directory for istioctl validate

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- tests/integration/pilot/gateway_test.go
https://github.com/istio/istio/pull/43541 didn't work quite right due to a rebasing issue. Fix it and add better tests
> gateway: fix and test unmanaged skipping

- pilot/docker/Dockerfile.proxyv2
- pilot/docker/Dockerfile.ztunnel
> Bump distroless iptables image

- samples/bookinfo/src/productpage/requirements.txt
Fix https://github.com/istio/istio/security/dependabot/10 manually.
https://github.com/istio/istio/pull/42814 has been closed.
> Bump productpage future requirements to 0.18.3

- pilot/pkg/config/aggregate/config.go
This is just appending them, there is no guarantee of conflicts being avoided
> Use safer dedupe for config

- pilot/pkg/model/controller.go
- pilot/pkg/serviceregistry/aggregate/controller.go
This was added recently, was deadcode from the start.
> Cleanup deadcode in AppendWorkloadHandlerForCluster

- pilot/pkg/model/push_context.go
- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/aggregate/controller.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/xds/endpoint_builder.go
To return slice directly and prevent convert again
> update Waypoint interface

- cni/pkg/ambient/ambientpod/podutil.go
- cni/pkg/ambient/informers.go
> Cleanup ambient dead code

- pilot/pkg/model/service.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/networking/util/util_test.go
- pilot/pkg/xds/endpoint_builder.go
- pilot/pkg/xds/ep_filters.go
> revert https://github.com/istio/istio/pull/43560

- tests/integration/pilot/gateway_test.go
There is no distroless app container
> Fix new test which was broken on distroless

- istioctl/cmd/analyze_test.go
- istioctl/cmd/testdata/analyze-file/public-gateway.yaml
- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/local/istiod_analyze.go
- pkg/config/legacy/util/kuberesource/resources.go
- releasenotes/notes/44506.yaml
- tests/integration/pilot/analyze_test.go
Fixes #40861.
I think this is a simpler alternative to #43712
> Skip runtime resources when analyzing files

- pkg/config/validation/validation.go
> typo fix for failover validation

- bin/update_deps.sh
- bin/update_ztunnel.sh
- prow/release-commit.sh
Update references from master to release-1.18
> [release-1.18] Update master to 1.18

- istioctl/cmd/precheck.go
- pilot/pkg/config/kube/crdclient/types.gen.go
- pkg/config/schema/collections/collections.gen.go
- pkg/config/schema/gvk/resources.gen.go
- pkg/config/schema/gvr/resources.gen.go
- pkg/config/schema/kubeclient/resources.gen.go
- pkg/config/schema/kubetypes/resources.gen.go
- pkg/config/schema/metadata.yaml
- releasenotes/notes/gateway-rg-beta.yaml
> gateway-api: start reading ReferenceGrant beta

- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- releasenotes/notes/drop-default-request-timeout.yaml
> remove default timeout feature flag

- pkg/kube/multicluster/cluster.go
- pkg/kube/multicluster/secretcontroller.go
- releasenotes/notes/add-cluster-id-for-cluster-sync-metrics.yaml
Fix https://github.com/istio/istio/issues/44489
> Add cluster label for remote_cluster_sync_timeouts_total metric

- istioctl/cmd/tag.go
Improve istioctl tag example output
Previous output：
Output after adjustment：
> improve istioctl tag example output

- pilot/pkg/bootstrap/certcontroller.go
- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/bootstrap/monitoring.go
- pilot/pkg/bootstrap/server.go
- pilot/pkg/bootstrap/servicecontroller.go
- pilot/pkg/bootstrap/sidecarinjector.go
- pilot/pkg/bootstrap/validation.go
- pilot/pkg/server/instance.go
- pilot/pkg/server/instance_test.go
- pilot/pkg/serviceregistry/kube/controller/multicluster.go
This is purely for debugging
* Name each task
* Log it, at debug level
* If its slow, give a warning
> pilot: log startup tasks

- docker/Dockerfile.distroless
- go.mod
- go.sum
- pilot/docker/Dockerfile.proxyv2
- pilot/docker/Dockerfile.ztunnel
- prow/release-commit.sh
**Please provide a description of this PR:** Output of update_deps.sh prior to 1.18beta0 build
> update_deps output prior to beta0 build

- pilot/pkg/networking/grpcgen/cds.go
https://github.com/istio/istio/issues/44701
> grpcgen: skip clusters with no service 

- bin/init.sh
- pilot/pkg/features/pilot.go
- pilot/pkg/model/telemetry.go
- pilot/pkg/model/wasm.go
- pilot/pkg/xds/filters/filters.go
This doesn't actually work anyways, so no release note needed
> Cleanup dead ENABLE_WASM_TELEMETRY

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pkg/kube/kclient/index.go
- pkg/kube/kclient/index_test.go
- pkg/revisions/tag_watcher.go
- security/pkg/server/ca/node_auth.go
This makes it more like a `Map[k, v]` instead of `Map[v, k]` which is confusing
> index: refactor parameter order

- tests/integration/pilot/mcs/discoverability/discoverability_test.go
This is a simplified version of #44711.
> Fix MCS integration tests that were implictly skipped

- pkg/test/framework/components/echo/echotest/run.go
An example of skipped tests: https://github.com/istio/istio/pull/44711.
> Check source and destination echos to prevent implictly skipping tests

- pilot/pkg/model/config.go
- pilot/pkg/model/telemetry.go
> move to kubernetes NamespacedName

- pilot/pkg/bootstrap/server.go
- pilot/pkg/xds/debug.go
> cleanup useless param of InitDebug

- pilot/pkg/bootstrap/server.go
- pilot/pkg/bootstrap/server_test.go
- pilot/pkg/bootstrap/sidecarinjector.go
- pilot/pkg/bootstrap/validation.go
- pilot/pkg/bootstrap/webhook.go
Manual cherry-pick 44526
Fix https://github.com/istio/istio/issues/44630
>  [release-1.17] Fix pilot using wrong readinessprobe check, should check if /validate and /inject endpoints are ready.

- pilot/pkg/autoregistration/controller.go
- pilot/pkg/autoregistration/controller_test.go
Fixes https://github.com/istio/istio/issues/44640
> fix auto registration flake

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/credentials/kube/multicluster.go
- pilot/pkg/credentials/kube/secrets.go
- pilot/pkg/credentials/kube/secrets_test.go
- pilot/pkg/credentials/model.go
- pilot/pkg/xds/sds.go
- pkg/config/analysis/analyzers/gateway/secret.go
Doing this refactoring in preparation for CRL support.
[RFC](https://docs.google.com/document/d/13LNbJnLHe_prlOg7sPr77PjLiIuGj452/edit)
> refactor KeyCertAndStaple

- manifests/charts/gateway/values.yaml
> Disable gateway PDB by default and add description

- pkg/config/analysis/analyzer.go
Using slices leads to numerous duplicated inputs; only unique ones should be included.
> Improve analysis combineInputs

- pkg/ptr/pointer.go
- pkg/ptr/pointer_test.go
Breaking this out of another PR. Just expand test coverage here
> ptr: add unit test coverage

- pilot/pkg/autoregistration/controller_test.go
Follow-up to https://github.com/istio/istio/pull/44712
* Cleanup unit test (per [code review](https://github.com/istio/istio/pull/44712#discussion_r1187712660))
> vm: cleanup unit test

- pkg/config/analysis/analyzers/annotations/annotations.go
- pkg/config/analysis/analyzers/maturity/maturity.go
- pkg/config/analysis/analyzers/testdata/misannotated.yaml
These messages should not be displayed in `precheck or `analyze`.
> Fix precheck and analysis messages

- Makefile.core.mk
- samples/bookinfo/src/build-services.sh
- samples/bookinfo/src/productpage/requirements.txt
- samples/bookinfo/src/ratings/Dockerfile
So it can be used by CI to trigger a build of the images
> Add bookinfo.build make target

- tests/integration/pilot/istioctl_test.go
Regarding https://github.com/istio/istio/issues/42448,
Adding a timeout for each call of istioctl from TestXdsProxyStatus test case.
> Adding a timeout for each call of istioctl in the test

- pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
A cluster can have many config maps. It's wasteful to store all of them in the informer cache
> Only watch root cert ConfigMap

- .github/SECURITY.md
Document organization affiliation of the individuals on the security alias.
> [CNCF Graduation]: Clarify Product Security group Membership

- cni/pkg/cmd/root.go
- cni/pkg/config/config.go
- cni/pkg/constants/constants.go
- cni/pkg/repair/repair.go
- cni/pkg/repair/repair_test.go
- cni/pkg/repair/repair_test_helpers.go
- cni/pkg/repair/repaircontroller.go
- cni/test/install_cni.go
Currently this is using some of the old controller methods. Clean up to modern standards.
Should have no use facing behavior except RunAsDaemon is now always `true` since there isn't a good use case for other modes.
> cni: modernize repair controller

- security/pkg/nodeagent/cache/secretcache.go
Fixes https://github.com/istio/istio/issues/44824
> remove file from file certs before triggering call backs

- go.mod
- go.sum
- pilot/pkg/config/kube/gateway/conversion.go
- tests/integration/pilot/gateway_conformance_test.go
- tests/integration/pilot/testdata/gateway-api-crd.yaml
~Needs https://github.com/kubernetes-sigs/gateway-api/pull/1880/files, so its not ready to merge yet.~
> gateway-api: update redirects to match spec

- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
- pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
- pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
- pkg/kube/namespace/filter.go
Fix https://github.com/istio/istio/issues/44675
It need further refactor
> when discovery selector changed, it should sync namespace ca configmap

- pilot/pkg/xds/debuggen.go
Return an error with a precise status code in debuggen.
Change-Id: Ia2654e18006b7cc2d54bb86ff9c9a2abe9e28bf5
> Return a specific status code in debuggen

- cni/pkg/ebpf/server/redirectionServer_linux.go
* using replace instead of add for case isito-cni(eBPF prog) upgrade
> Hook eBPF prog with replace instead of add

- pilot/pkg/model/sidecar.go
Ref https://github.com/istio/istio/pull/44913
> address followup review comments

- go.mod
- go.sum
- tests/integration/pilot/gateway_conformance_test.go
- tests/integration/pilot/testdata/gateway-api-crd.yaml
Only trivial changes, but puts us on official release
> gateway-api: move to official release

- pilot/pkg/config/kube/ingress/status.go
- pilot/pkg/config/kube/ingress/status_test.go
> Sync ingress status on ingress class updates

- pkg/kube/inject/inject_test.go
- pkg/kube/inject/webhook_test.go
This is for https://github.com/istio/istio/issues/44933.
> injection: add benchmark

- pkg/spiffe/spiffe.go
- pkg/spiffe/spiffe_test.go
- releasenotes/notes/spiffe-bundle-multiple-certs.yaml
This is a cherry-pick for #44831 (with modifications in the tests to avoid conflicts).
> [release-1.17] spiffe: fix handling of trust bundles with multiple keys

- prow/integ-suite-kind.sh
This was built with new kind version which changes the base image
> prow: bump kind image tested

- pilot/pkg/config/aggregate/config.go
- pkg/config/model.go
Manual cherry pick of https://github.com/istio/istio/pull/44698 which needed some backporting of code from https://github.com/istio/istio/pull/42689
> [release-1.16] Manual cherry-pick of Use safer dedupe for config (#44502)

- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
- pilot/pkg/config/kube/gateway/testdata/deployment/proxy-config-crd.yaml
- pilot/pkg/model/context.go
- pkg/kube/inject/webhook.go
- releasenotes/notes/44916.yaml
This is a manual cherry-pick of #44916.
> [release-1.18] deploymentcontroller: add support for ProxyConfig CRD

- pkg/kube/client.go
- pkg/kube/kclient/client.go
- pkg/kube/kclient/clienttest/direct.go
- pkg/kube/kclient/clienttest/test_helpers.go
Pull fixes out of https://github.com/istio/istio/pull/44201 and https://github.com/istio/istio/pull/44145
Fixing some locking mostly, and minor test-helper fixes.
The main change is working around a k8s bug/limitation: https://github.com/kubernetes/kubernetes/issues/117869
> kube client: cherrypick some fixes from other PRs

- tests/integration/pilot/workloadentry_test.go
- Adds a multi-cluster integration test to provide coverage for WorkloadEntry
> Testing workloadentry

- pkg/backoff/exponential.go
- releasenotes/notes/44986.yaml
- security/pkg/nodeagent/cache/secretcache.go
Set the maxElaspedTime = 0, which means it never stop. This is intended for the package
> fix backoff and read ca file interval

- istioctl/cmd/testdata/waypoint/all-gateway
- istioctl/cmd/testdata/waypoint/combined-gateway
- istioctl/cmd/testdata/waypoint/default-gateway
- istioctl/cmd/waypoint.go
- istioctl/cmd/waypoint_test.go
Ready is reserved now, and add revision since it's supported
> Fix waypoint list summary and add revision

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/conversion.go
We can see there was error handling cronjob
> resue existing wl meta function

- manifests/charts/gateway/templates/poddisruptionbudget.yaml
- manifests/charts/gateway/values.schema.json
- manifests/charts/gateway/values.yaml
- releasenotes/notes/44481.yaml
https://github.com/istio/istio/pull/44775 is a follow-up of https://github.com/istio/istio/pull/44481, they are both merged into master, and fixed the PDB parity issue of different install methods.
> [release-1.16]Manual cherry-pick of 44481 and 44775

- manifests/charts/gateway/templates/poddisruptionbudget.yaml
- manifests/charts/gateway/values.schema.json
- manifests/charts/gateway/values.yaml
- releasenotes/notes/44481.yaml
https://github.com/istio/istio/pull/44775 is a follow-up of https://github.com/istio/istio/pull/44481, they are both merged into master, and fixed the PDB parity issue of different install methods.
> [release-1.17]Manual cherry-pick of 44481 and 44775

- pilot/pkg/xds/debug.go
- pkg/hbone/dialer.go
- pkg/istio-agent/health/health_check_test.go
- pkg/wasm/httpfetcher_test.go
- security/pkg/stsservice/server/server.go
Replace the string with constants from the http package
> Replace the string with constants from the http package

- pilot/pkg/networking/util/util.go
> Clean up unused var and function

- go.mod
- go.sum
- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/networking/core/v1alpha3/extension/wasmplugin_test.go
https://github.com/istio/api/pull/2577 merged and the automation failed creating the istio/istio PR with the updated client-go changes.
This PR adds annual int64->int32 changes to reflect theistic/api PR.
> Update client-go (requires manual changes)

- pilot/pkg/model/kstatus/helper_test.go
add ut for pilot/pkg/model/kstatus/helper_test.go
> add ut for pilot/pkg/model/kstatus/helper_test.go

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_waypoint.go
> refactor waypoint inbound cluster build

- pilot/pkg/credentials/kube/multicluster.go
- pilot/pkg/credentials/kube/secrets.go
- pilot/pkg/credentials/kube/secrets_test.go
- pilot/pkg/credentials/model.go
- pilot/pkg/xds/sds.go
- pilot/pkg/xds/sds_test.go
- releasenotes/notes/crl_support.yaml
[Istio RFC for CRL support](https://docs.google.com/document/d/13LNbJnLHe_prlOg7sPr77PjLiIuGj452/edit)
[Istio certificate revocation support feature request](https://github.com/istio/istio/issues/17763)
> Certificate Revocation List(CRL) support

- tools/bug-report/pkg/content/content.go
Similar to https://github.com/istio/istio/pull/44970. Apply the fix to current skipping checking the other Urls when there's one error found.
> Fix missing info dump 

- istioctl/cmd/wait.go
- pilot/pkg/model/jwks_resolver_test.go
- pkg/envoy/agent.go
- pkg/test/echo/server/forwarder/util.go
fix create time.NewTicker but not stop
> fix ticker without stop

- pilot/pkg/leaderelection/leaderelection_test.go
regression from
https://github.com/istio/istio/commit/412a7b58e8e25720570fa3262368b47b045b0288;
now we always set prioritized=true so we needed to update the test.
> Fix test flake in TestMulticlusterLeaderElection

- pilot/pkg/bootstrap/monitoring.go
- pilot/pkg/bootstrap/server.go
> use unified monitoring package

- go.mod
- go.sum
- istio.deps
- prow/release-commit.sh
Do not remove the dnm tag until we are ready to proceed with the build
> [1.18-rc.0 Step 1] Update Deps

- tools/bug-report/pkg/bugreport/bugreport.go
Add time measurement for each block process time to the log.
> Add time measurement for istioctl bug-report command

- istioctl/cmd/injector-list.go
clean code: this println seem unnecessary
> clean unuse print

- pkg/test/framework/components/ambient/waypoint.go
- pkg/test/framework/components/echo/annotations.go
- pkg/test/framework/components/echo/common/deployment/echos.go
- pkg/test/framework/components/echo/common/deployment/namespace.go
- pkg/test/framework/components/echo/config.go
- pkg/test/framework/components/echo/deployment/builder.go
- pkg/test/framework/components/echo/echotest/filters.go
- pkg/test/framework/components/echo/kube/deployment_test.go
- pkg/test/framework/components/echo/kube/templates/vm_deployment.yaml
- pkg/test/framework/components/echo/match/matchers.go
- pkg/test/framework/components/echo/workloadclass.go
- pkg/test/framework/components/namespace/kube.go
- pkg/test/framework/components/namespace/namespace.go
- pkg/test/framework/components/namespace/static.go
- pkg/test/framework/resource/flags.go
- pkg/test/framework/resource/settings.go
- tests/integration/ambient/main_test.go
- tests/integration/ambient/traffic_test.go
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/common/traffic.go
This tests "ambient L7" and adds a fair bit of coverage. 
While a lot of things are skipped in this mode, I still think it's super valuable to know that those things need looking at.
> TestTraffic for ambient

- istioctl/pkg/tag/generate.go
- istioctl/pkg/tag/generate_test.go
- operator/cmd/mesh/install.go
- operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
- operator/pkg/helmreconciler/common.go
- operator/pkg/helmreconciler/prune.go
- operator/pkg/helmreconciler/reconciler.go
- releasenotes/notes/43897.yaml
Manual cherry-pick of https://github.com/istio/istio/pull/43897
> [release-1.16] Operator: Fix webhooks reconciled by operator are inconsistent with istioctl install's

- istioctl/pkg/tag/generate.go
- istioctl/pkg/tag/generate_test.go
- operator/cmd/mesh/install.go
- operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
- operator/pkg/helmreconciler/common.go
- operator/pkg/helmreconciler/prune.go
- operator/pkg/helmreconciler/reconciler.go
- releasenotes/notes/43897.yaml
Manual cherry-pick of https://github.com/istio/istio/pull/43897
> [release-1.17] Operator: Fix webhooks reconciled by operator are inconsistent with istioctl install's

- security/pkg/server/ca/server.go
Fix https://github.com/istio/istio/issues/44830
> add debug info when generating certs for workloads

- istioctl/pkg/util/configdump/wrapper.go
proto.MessageType is deprecated，use protoregistry.GlobalTypes.FindMessageByName replace it
> remove deprecated MessageType

- pkg/slices/slices_test.go
add ut for pkg/slices/slices_test.go
> add ut for pkg/slices/slices_test.go

- security/pkg/server/ca/server.go
Auto cherry-pick failed: https://github.com/istio/istio/issues/45187
> cherry-pick: add debug info when generating certs for workloads #45183

- istioctl/pkg/tag/generate.go
- istioctl/pkg/tag/generate_test.go
- operator/cmd/mesh/install.go
- operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
- operator/pkg/helmreconciler/common.go
- operator/pkg/helmreconciler/prune.go
- operator/pkg/helmreconciler/reconciler.go
- releasenotes/notes/43897.yaml
Reverts istio/istio#45121
https://github.com/istio/istio/issues/45204
> Revert "[release-1.17] Operator: Fix webhooks reconciled by operator are inconsistent with istioctl install's"

- istioctl/pkg/tag/generate.go
- istioctl/pkg/tag/generate_test.go
- operator/cmd/mesh/install.go
- operator/pkg/controller/istiocontrolplane/istiocontrolplane_controller.go
- operator/pkg/helmreconciler/common.go
- operator/pkg/helmreconciler/prune.go
- operator/pkg/helmreconciler/reconciler.go
- releasenotes/notes/43897.yaml
Reverts istio/istio#45124
https://github.com/istio/istio/issues/45204
> Revert "[release-1.16] Operator: Fix webhooks reconciled by operator are inconsistent with istioctl install's"

- pkg/version/cobra_test.go
> Update cobra test to include boringcrypto to golang_version

- pkg/kube/kclient/client_test.go
- pkg/kube/kclient/delayed.go
Fixes https://github.com/istio/istio/issues/45200
> kube: fix flake in delayed test

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/networking/core/v1alpha3/waypoint.go
- pilot/pkg/networking/core/v1alpha3/waypoint_test.go
Services without LabelSelectors match nothing. We are building incorrect waypoint listeners/clusters for these services(which are heavily used in Knative)
> waypoint: fix service matching

- pilot/pkg/config/kube/crdclient/client.go
- pilot/pkg/config/kube/crdclient/client_test.go
- tests/integration/pilot/multiplecontrolplanes/main_test.go
fix #45137 crd part
And also fix the integration test 
> Fix crd filter

- security/pkg/server/ca/server.go
Address comments at #45183 
Log output:
```
generating a certificate for [spiffe://cluster.local/ns/default/sa/bookinfo-details], requested ttl: 24h0m0s
```
> remove signer and change ttl to a human friendly format

- prow/config/modern.yaml
> prow: add new kind config for 1.28+

- istioctl/pkg/util/configdump/workload.go
- istioctl/pkg/writer/ztunnel/configdump/configdump_test.go
- istioctl/pkg/writer/ztunnel/configdump/testdata/dump.json
- istioctl/pkg/writer/ztunnel/configdump/workload.go
follow up to https://github.com/istio/istio/pull/44199
> update istioctl pc workload command for latest ambient wds

- pkg/kube/inject/webhook.go
> injection: correctly exit early on error

- cni/pkg/ambient/server.go
- pilot/pkg/model/cluster_local.go
- pkg/adsc/adsc.go
- pkg/kube/inject/webhook.go
use rwmutex replace mutex and use RLock when get
> use rwmutex replace mutex and use RLock when get

- pkg/adsc/adsc.go
> return error info if read file have error

- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/listener_patch_test.go
- releasenotes/notes/45216.yaml
Fix https://github.com/istio/istio/issues/45089
If the EnvoyFilter has a delete operation, there will be problems in the following scenarios:  
1. Delete filter A and then add filter A, the added filter A will still be deleted
> fix envoyFilter order

- pkg/slices/slices_test.go
increase ut coverage for pkg/slices
> increase ut coverage for pkg/slices

- pilot/pkg/networking/core/v1alpha3/gateway.go
Since we set IgnorePortInHostMatching this is obsolete
> gateway: cleanup wildcard port matcher

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_test.go
- releasenotes/notes/telemetry-implicit-match-all.yaml
Fixes https://github.com/istio/istio/issues/45292
> Fix Telemetry disablement matching

- pilot/pkg/config/kube/gateway/controller.go
> use istio pkg.slices

- go.mod
- go.sum
- prow/release-commit.sh
> [release-1.18][step 0] Update deps prior to 1.18.0 GA

- pilot/pkg/xds/workload_test.go
This is caused by the pod may not be ready. Rather than retry logic just ensure pod is created before we connect
Fixes https://github.com/istio/istio/issues/45317
> ambient: fix TestWorkloadReconnect flake

- pkg/kube/multicluster/clusterstore.go
- pkg/kube/multicluster/secretcontroller.go
This was originally going to be a larger change but decided against it, so just a minor refactor to move out some logic to common function
> multicluster: minor refactoring

- pilot/pkg/config/kube/gateway/controller.go
- pilot/pkg/serviceregistry/aggregate/controller.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/ep_filters.go
> Cleanup: improve the use of maps

- pilot/pkg/model/context.go
- pilot/pkg/model/virtualservice.go
> Revert "clean and fix string split"

- manifests/charts/gateway/templates/poddisruptionbudget.yaml
- manifests/charts/gateway/values.schema.json
- manifests/charts/gateway/values.yaml
- releasenotes/notes/44481.yaml
#44775 is a follow-up of #44481, they are both merged into master, and fixed the PDB parity issue of different install methods.
> [release-1.18]Manual cherry-pick of 44481 and 44775

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/credentials/kube/multicluster.go
- pilot/pkg/credentials/kube/secrets.go
- pilot/pkg/credentials/kube/secrets_test.go
- pilot/pkg/credentials/model.go
- pilot/pkg/xds/sds.go
- pilot/pkg/xds/sds_test.go
- pkg/config/analysis/analyzers/gateway/secret.go
- releasenotes/notes/crl_support.yaml
This is a manual cherry-pick of CRL support and includes the below 3 PRs from master:
https://github.com/istio/istio/pull/44764
https://github.com/istio/istio/pull/45104
https://github.com/istio/istio/pull/45112
Fixes https://github.com/istio/istio/issues/45129
> [release-1.18] Certificate Revocation List support

- pilot/pkg/config/kube/ingress/conversion.go
- pilot/pkg/config/kube/ingress/conversion_test.go
- pilot/pkg/config/kube/ingress/testdata/overlay.yaml.golden
- pilot/pkg/config/kube/ingress/testdata/tls-no-secret.yaml.golden
- pilot/pkg/config/kube/ingress/testdata/tls.yaml.golden
Backport of #44898. Resolves #45007
> [release-1.18] Fix invalid XDS configuration for wildcard Ingress HTTP path (#44898)

- CODEOWNERS
> change CODEOWNERS of pkg/monitoring

- go.mod
- pkg/test/framework/components/echo/kube/sidecar.go
- pkg/test/framework/components/echo/sidecar.go
> Cleanup deadcode in tf Stats

- pilot/pkg/serviceregistry/serviceentry/controller.go
simplify and optimize servicesDiff
> simplify and optimize servicesDiff

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
> Return ealier when the key contains hostname

- pkg/util/net/ip_test.go
add ut for pkg/util/net/ip_test.go
I want to contribute a little code.
> add ut for pkg/util/net/ip_test.go

- pilot/pkg/config/memory/controller.go
Just a minor improvement to show the correct error message, minimal functional changes show
> memory controller: propogate correct error

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_test.go
- releasenotes/notes/check-disabled-status.yaml
Fix https://github.com/istio/istio/issues/45371
> [release-1.16] Check the disabled status when adding a log provider

- common/config/.golangci.yml
- tools/golangci-override.yaml
cc @howardjohn 
fixes: https://github.com/istio/istio/pull/45379
> depguard: add guard for OpenCensus

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
Per PR comments in https://github.com/istio/istio/pull/45398, the Validation webhook should check for presence of all required fields in UriRegexRewrite
> Validation webhook should ensure in UriRegexRewrite both match and rewrite fields present

- istioctl/pkg/install/k8sversion/version.go
- istioctl/pkg/install/k8sversion/version_test.go
- releasenotes/notes/45275.yaml
Similiar to what we've done in https://github.com/istio/istio/pull/43236
> Update min supported k8s version to 1.24

- security/pkg/server/ca/server.go
> Add more log for istio ca for trouble shooting

- pilot/pkg/xds/ads.go
> xds: replace map with set 

- security/pkg/server/ca/server.go
https://github.com/istio/istio/issues/45186
> [release-1.18] cherry-pick: add debug info when generating certs for workloads

- pilot/pkg/model/sidecar.go
> use set replace map

- tools/bug-report/pkg/content/content.go
> Fix bug-report was hanging during analysis.

- pilot/pkg/config/kube/crdclient/client.go
- pkg/config/analysis/local/istiod_analyze.go
> Analyze: exclude useless secrets to reduce execution time

- cni/pkg/plugin/ambient.go
- cni/pkg/plugin/kubernetes.go
- cni/pkg/plugin/plugin.go
- cni/pkg/plugin/plugin_dryrun_test.go
- cni/pkg/plugin/plugin_test.go
* Fix https://github.com/istio/istio/issues/44938
* Split out fix for https://github.com/istio/istio/issues/44537
* General refactoring to avoid deep nesting and improve logging
> cni: cleanup exclusion logic

- pilot/pkg/autoregistration/controller.go
- pilot/pkg/autoregistration/controller_test.go
- releasenotes/notes/45413.yaml
fix https://github.com/istio/istio/issues/45413
> Fix auto register WLE with invalid istio-locality label

- tests/integration/telemetry/api/accesslogs_test.go
fixes: https://github.com/istio/istio/issues/44759
> improve accesslog mode e2e tests

- pilot/pkg/xds/cds.go
- pilot/pkg/xds/lds.go
- pilot/pkg/xds/nds.go
- pilot/pkg/xds/rds.go
> move skipped configs to sets

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/model/cluster_local.go
- pilot/pkg/model/config_test.go
- pilot/pkg/model/destination_rule.go
- pilot/pkg/model/gateway.go
- pilot/pkg/model/network.go
- pilot/pkg/model/push_context.go
- pilot/pkg/networking/core/v1alpha3/envoyfilter/rc_patch_test.go
- pilot/pkg/networking/core/v1alpha3/loadbalancer/loadbalancer.go
- pilot/pkg/serviceregistry/kube/controller/network.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/xds/ads_test.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/pushqueue_test.go
- pkg/adsc/adsc.go
- pkg/config/analysis/local/istiod_analyze.go
- pkg/config/schema/collection/schemas.go
- pkg/config/validation/extensionprovider.go
- pkg/config/validation/validation.go
- pkg/dns/client/dns.go
- pkg/test/framework/components/cluster/clusters.go
Fix https://github.com/istio/istio/issues/45537
> Make use istio sets in all places

- pkg/file/file_test.go
> add file_test.go UT

- CODEOWNERS
It's best to leave manifests to the wg-environments-maintainers instead of a few people
> Update CODEOWNERS to add some UX maintainers for helm chart values files

- prow/integ-suite-kind.sh
> Use prow image built with kind 0.20

- pilot/pkg/model/jwks_resolver.go
- pilot/pkg/model/jwks_resolver_test.go
- releasenotes/notes/45549.yaml
Fix https://github.com/istio/istio/issues/45546
> Improve jwk resolver to handle trailing slash

- tests/integration/telemetry/api/accesslogs_test.go
Fix https://github.com/istio/istio/issues/45530, https://github.com/istio/istio/issues/45529, https://github.com/istio/istio/issues/45527, https://github.com/istio/istio/issues/45522.
- [X ] Policies and Telemetry
> [release-1.17] improve accesslog mode e2e tests

- istioctl/pkg/authz/authz.go
- istioctl/pkg/authz/authz_test.go
- istioctl/pkg/authz/listener.go
- istioctl/pkg/authz/testdata/configdump.yaml
> istioctl: fix authz check file flag not working, and add authz tests

- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
for https://github.com/istio/istio/pull/45553#issuecomment-1600460100
> Add bench mark for autoallocate ip

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/authorization.go
- pilot/pkg/serviceregistry/kube/controller/multicluster.go
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-permissive-in.yaml
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-permissive-port-mtls-strict-in.yaml
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-permissive-port-mtls-strict.yaml
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-and-permissive-port-mtls-in.yaml
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-and-permissive-port-mtls.yaml
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-and-strict-port-mtls-in.yaml
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-in.yaml
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-workload-in.yaml
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-unset-port-mtls-permissive-in.yaml
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-unset-port-mtls-permissive.yaml
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-unset-port-mtls-strict-in.yaml
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-unset-port-mtls-strict.yaml
- pilot/pkg/serviceregistry/kube/controller/util.go
- pilot/pkg/serviceregistry/kube/controller/util_test.go
- pilot/pkg/xds/deltaadstest.go
- pilot/pkg/xds/workload.go
- pkg/test/framework/components/echo/match/matcher.go
- pkg/workloadapi/security/authorization.pb.go
- pkg/workloadapi/security/authorization.proto
- releasenotes/notes/ambient-peer-authentication.yaml
- tests/integration/ambient/baseline_test.go
This PR adds support for PeerAuthentication policies. It does this by translating PAs into Ambient-style Authorization policies (not to be confused with the `AuthorizationPolicy` CRD). Note that this PR does NOT change the semantics for HBONE sidecars as described in the [Ambient APIs doc](https://docs.google.com/document/d/1Lk1I1qB-XwVWFP0sVcIN5JMJZHjuF3j8lGWtUeDK6pY/edit#heading=h.xw1gqgyqs5b). The implementation works as follows:
1. `PeerAuthentications` are translated into DENY Authorizations (since ALLOWs are OR'd; it's prohibitively difficult to ensure that a PeerAuthentication doesn't actually become an ALLOW policy that is TOO permissive). The converted policy has a prefix appended to prevent name collisions with AuthorizationPolicies …
> Ambient support for PeerAuthentication

- pkg/envoy/proxy.go
- pkg/test/framework/components/echo/kube/templates/vm_deployment.yaml
- pkg/test/kube/dump.go
I feel terrible about this solution, but its the best I came up with
after hours of work
> tf: enable core dumps for VM pods

- bin/build_ztunnel.sh
- bin/init.sh
> prow: move to use WI for auth_header in private

- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/authorization.go
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-disable-in.yaml
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-disable-port-mtls-strict-in.yaml
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-disable-port-mtls-strict.yaml
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-and-disable-port-mtls-in.yaml
- pilot/pkg/serviceregistry/kube/controller/testdata/peer-authn-strict-and-disable-port-mtls.yaml
Add support for PeerAuthentication DISABLE in Ambient
> Add support for DISABLE PeerAuthentications (equal to PERMISSIVE)

- bin/init.sh
Fixes https://github.com/istio/istio/issues/45607
> prow: move to use WI for auth_header in private (#45606)

- tests/integration/telemetry/tracing/otelcollector/tracing_test.go
fixes: https://github.com/istio/istio/issues/45624
> e2e:fix TestProxyTracingOpenCensusMeshConfig

- istioctl/pkg/proxyconfig/proxyconfig.go
this's introduced for a long time, and didn't see  any bug-report.
cc @hanxiaop @howardjohn
> istioctl: remove experimental from log command message

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_test.go
This is was missed in my previous PR
> fix delta cluster when multiple config types are updated

- pilot/pkg/xds/lds.go
- pilot/pkg/xds/rds.go
> minor changes in lds and rds

- istioctl/pkg/describe/describe.go
- istioctl/pkg/wait/wait.go
- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/xds/ads_test.go
- pilot/pkg/xds/eds_test.go
- pkg/config/analysis/analyzers/annotations/annotations.go
Clean up the `contains` function to use the one inside `slices` package instead.
> reusing the `contains` function

- pilot/pkg/model/service.go
> atomic pointer store endpoint.LbEndpoint

- pilot/pkg/config/file/store.go
- pilot/pkg/config/memory/controller.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
improve the use of slices.Filter
> cleanup: improve the use of filter

- istioctl/pkg/writer/envoy/configdump/configdump.go
> Cleanup unused func

- pkg/bootstrap/platform/gcp.go
- pkg/bootstrap/platform/gcp_test.go
Fixes https://github.com/istio/istio/issues/43185 by removing the log to
debug level; it previously was not logged at all.
Additionally, refactored to make this substantially simpler.
This should have no user facing changes beyond the logging being
removed.
> gcp metadata: refactor and fix confusing logs

- pilot/pkg/serviceregistry/kube/conversion.go
Kubernetes service field "clusterIPs"  hold  a maximum of two entries (dual-stack IPs).  
And ensure clusterIPs[0] and clusterIP have the same value.
So extraddrs can optimize.
according to the [clusterips definition](https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/)
> optimize service extraddrs

- releasenotes/notes/45577.yaml
Address a comment in https://github.com/istio/istio/pull/45577#discussion_r1245599651
> Update a releasenotes description

- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/httproute_test.go
- releasenotes/notes/45719.yaml
Fixes https://github.com/istio/istio/issues/45719
> improve domain dedupe logic with case sensitivity

- pkg/bootstrap/platform/gcp.go
- pkg/bootstrap/platform/gcp_test.go
This is a cherrypick of https://github.com/istio/istio/pull/45314, but minimal only for release branch
> gcp metadata: compute GCPClusterURL from metadata

- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/fake.go
Followup for #45715 
As agreed, adding a `discoveryStartTime` variable to `DiscoveryService` and override it during the tests.
> added discoveryStartTime

- tests/integration/security/sds_ingress/ingress_test.go
this block all PR, temporarily skip
xref: https://github.com/istio/istio/issues/45766
> e2e: temporarily skip CRL test

- tests/integration/pilot/gateway_conformance_test.go
Reverts istio/istio#45721
https://github.com/istio/istio/pull/45721#issuecomment-1613603734
> Revert "Remove IPv4 workaround in gateway conformance test"

- pilot/pkg/features/pilot.go
- pilot/pkg/model/service.go
- pilot/pkg/networking/core/v1alpha3/httproute.go
- pkg/slices/slices.go
> add EqualFunc and Reverse functions to slices

- pilot/pkg/model/endpointshards.go
- releasenotes/notes/45800.yaml
Fix https://github.com/istio/istio/issues/45798
> Fix a potential nil panic of endpointindex

- pkg/kube/inject/template.go
> remove unused legacy template function

- tools/go-compile-verbose
This outputs in a structured format that can be parsed.
> tools: improve go-compile-verbose

- pilot/pkg/model/envoyfilter.go
- pilot/pkg/model/envoyfilter_test.go
address comments:  
https://github.com/istio/istio/pull/44183#discussion_r1153455723
https://github.com/istio/istio/pull/44183#issuecomment-1620949236
> replace string builder with concat

- istioctl/pkg/tag/tag.go
- istioctl/pkg/version/version.go
Unify the format of istioctl examples
> Unify the format of istioctl examples

- releasenotes/notes/45842.yaml
- tools/bug-report/pkg/cluster/cluster.go
- tools/bug-report/pkg/cluster/cluster_test.go
Fix https://github.com/istio/istio/issues/45839
> Fix bug report include option not working as expected

- istioctl/pkg/describe/describe.go
- pkg/kube/util.go
https://github.com/istio/istio/pull/44835 will allow sidecar as init
container
> istioctl: future proof Sidecar KEP

- releasenotes/notes/45842.yaml
- tools/bug-report/pkg/cluster/cluster.go
- tools/bug-report/pkg/cluster/cluster_test.go
> [release-1.17] Manual cherry-pick 45842 

- releasenotes/notes/45842.yaml
- tools/bug-report/pkg/cluster/cluster.go
- tools/bug-report/pkg/cluster/cluster_test.go
> [release-1.16] Manual cherry-pick 45842

- tests/integration/pilot/testdata/external-forward-proxy-deployment.yaml
Just reduce permission required to run the test
> tf: Drop root on forward proxy test

- pilot/pkg/model/context.go
- pilot/pkg/model/sidecar.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
fix https://github.com/istio/istio/issues/41239
> prevent port conflict with sidecar static listener like 15021 15090

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_workloadentry_test.go
- releasenotes/notes/45758.yaml
Ambient: Add support for WEs without addresses for multi network. Resolves https://github.com/istio/istio/issues/45758.
cc @bleggett @dhawton
> Ambient: Add support for WEs without addresses for multi network

- pilot/pkg/networking/core/v1alpha3/gateway_test.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/security/model/authentication.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/optional_mutual.yaml
- tests/integration/pilot/common/routing.go
Implements https://github.com/istio/api/pull/2820
> add support for optional MTLS

- pilot/cmd/pilot-agent/options/agent.go
- pilot/cmd/pilot-agent/options/options.go
- pkg/istio-agent/agent.go
- pkg/istio-agent/agent_test.go
- releasenotes/notes/exit-if-sds-socket-not-found.yaml
fix: https://github.com/istio/istio/issues/45534
- [ x] Security
> Exit if sds socket not found

- pilot/pkg/networking/core/v1alpha3/gateway_test.go
- pilot/pkg/networking/core/v1alpha3/listener.go
> add mesh tls defaults for optional mtls

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/injection/injection-image.go
- pkg/config/analysis/analyzers/injection/injection.go
- pkg/config/analysis/analyzers/testdata/injection-with-mismatched-sidecar.yaml
- pkg/config/analysis/analyzers/util/in_mesh.go
Looking through the commands, I think the analyze command should be the only thing left for the sidecar container support in istioctl.
> istioctl: analyze support sidecar container

- pilot/cmd/pilot-agent/status/server_test.go
Since https://github.com/istio/istio/pull/45993 there is a regression,
we need to init the registry.
In the meantime, I noticed this takes minutes to run. Use a
stringbuilder for more efficiency, and properly ResetTimer.
> agent: fix benchmark and improve it

- pilot/pkg/networking/core/v1alpha3/gateway.go
for https://github.com/istio/istio/issues/46004
> Add warning for gateway missing network filters

- istio.deps
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/xds/filters/filters.go
- tests/binary/binaries_test.go
Picks up the renames and the ambient refactor in https://github.com/istio/proxy/pull/4789.
> metadata exchange: sync to proxy change

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
Followup to #45791 
- Simplify if condition
- Update tests to cover for both modes
> simplify if condition and update tests

- pkg/kube/controllers/queue.go
> Tiny fix for cluster scoped resource key

- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/util/util.go
> fix remove proxy 116 checks

- pilot/pkg/model/context.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/discovery.go
sort response for debug apis： `/debug/syncz &  /debug/config_distributio&  /debug/connections&  /debug/adsz`
> optimization: sort response for debug `syncz & config_distributio& connections&adsz`

- pilot/pkg/bootstrap/server.go
- pilot/pkg/bootstrap/sidecarinjector.go
Manual cherry-pick of https://github.com/istio/istio/pull/46003.
> [release-1.17] Fix readiness probe when sidecar injector is disabled

- pkg/util/net/ip.go
- pkg/util/net/ip_test.go
> test: add iputil unit test

- pkg/bootstrap/platform/gcp_test.go
Just add one missing test case
> gcp: expand metadata test

- istioctl/pkg/authz/analyzer_test.go
Adds unit test coverage
Issue #37354
> Added test file for istio/istioctl/pkg/authz/analyzer.go

- tools/gen_istio_image_list.sh
gen_istio_image_list.sh  Version check for some errors Only single digits are supported in this version
#46008
> fix_version_check

- pkg/test/framework/features/features.yaml
- tests/integration/security/sds_ingress/ingress_test.go
- tests/integration/security/sds_ingress/util/util.go
> add client test for optional mtls

- pilot/pkg/model/virtualservice.go
- pilot/pkg/model/virtualservice_test.go
> remove unneccessary deepcopy

- pilot/pkg/bootstrap/server.go
- pilot/pkg/bootstrap/sidecarinjector.go
Manual cherry-pick of https://github.com/istio/istio/pull/46003
Fixes https://github.com/istio/istio/issues/46099
> [release-1.18]  Fix readiness probe when sidecar injector is disabled

- pilot/pkg/autoregistration/controller.go
- pilot/pkg/autoregistration/controller_test.go
- pilot/pkg/features/pilot.go
- pilot/pkg/xds/vm_test.go
- pkg/adsc/adsc.go
- pkg/istio-agent/xds_proxy_test.go
(cherry picked from commit 0658207e10cef9ac564b31567a05750624a54941)
(cherry picked from commit 00136097767eec680da8749837a8d79adf110b1a)
> Add validation of workload entry identity (#119)

- pilot/pkg/autoregistration/controller.go
- pilot/pkg/autoregistration/controller_test.go
- pilot/pkg/features/pilot.go
- pilot/pkg/xds/vm_test.go
- pkg/adsc/adsc.go
- pkg/istio-agent/xds_proxy_test.go
(cherry picked from commit b6eefaf3045227431b60384002e5b0c57740288d)
(cherry picked from commit 0183f2886bc078e8df4d6bbd21fa452a3a23481d)
> Add validation of workload entry identity (#117)

- pilot/pkg/networking/core/v1alpha3/gateway.go
These are not ints so cannot use %d
> Pilot: fix minor log issues

- pilot/pkg/autoregistration/controller.go
- pilot/pkg/autoregistration/controller_test.go
- pilot/pkg/features/pilot.go
- pilot/pkg/xds/vm_test.go
- pkg/adsc/adsc.go
- pkg/istio-agent/xds_proxy_test.go
(cherry picked from commit 263b96bde2a61ffc706dcdf0202b93cd6b56d955)
(cherry picked from commit 681b4f65a7526175c1b7a4d2c7bd84e827c20d18)
> Add validation of workload entry identity (#118)

- pkg/dns/client/monitoring.go
xhref: https://github.com/istio/istio/issues/46142
> correct distribution buckets

- pkg/test/env/istio.go
- tools/docker-builder/common.go
- tools/docker-builder/main.go
- tools/docker-builder/types.go
Print the Ztunnel sha (from `istio.deps` being used in builds).
For convenience.
> Print the Ztunnel SHA being used

- common/scripts/tracing.sh
As result of #46082 running the prow scripts (e.g. integration tests) locally is failing.
Fixing for both local runs or build systems without the `otel-cli`.
> Fix running prow scripts locally

- common/scripts/tracing.sh
The integration tests are failing since PULL_NUMBER and PULL_PULL_SHA are not set. Add some defaults.
> Fix tracing in integration tests

- pilot/pkg/model/virtualservice.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pkg/maps/maps.go
> use maps.MergeCopy

- common/scripts/tracing.sh
Missed a PULL_NUMBER
However the URL will be incorrect. Looking into that some more.
> Fix tracing in postsubmit tests

- pilot/pkg/autoregistration/controller.go
- pilot/pkg/autoregistration/controller_test.go
- pilot/pkg/config/kube/ingress/conversion.go
- pilot/pkg/config/kube/ingress/status_test.go
- pilot/pkg/serviceregistry/kube/controller/util.go
- pilot/pkg/serviceregistry/kube/conversion.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/xds/mesh_network_test.go
- tests/integration/pilot/vm_test.go
> reuse annotation from api

- pilot/cmd/pilot-agent/status/server.go
- pilot/cmd/pilot-agent/status/server_test.go
- releasenotes/notes/46087.yaml
https://github.com/istio/istio/issues/46087
> Fix HTTP probe `Host` propagation

- istioctl/pkg/config/config.go
`istioctl config list` is a invaild command.
> Fixed List istio configurable defaults example

- istioctl/pkg/precheck/precheck.go
- istioctl/pkg/workload/workload.go
correct some typos in istioctl/pkg/
> correct some typos in istioctl/pkg/

- Makefile.core.mk
See https://blog.howardjohn.info/posts/go-build-times/#building-multiple-binaries, this is faster
> Consolidate to 2 build steps

- pilot/pkg/model/sidecar_test.go
- pilot/pkg/model/virtualservice_test.go
This PR contains two commits:
1. commit 1: add wildcard scene unit test.
2. commit 2: fix benchmark not covering `SelectVirtualServices` and `selectServices`.
> Add more test cases

- tests/integration/telemetry/envoyfilter/nullvm/dashboard_test.go
This makes the logs confusing and it isn't needed
> tf: make dashboard test not send errors

- pilot/pkg/config/kube/crdclient/client_test.go
- pkg/config/analysis/local/analyze_test.go
- pkg/config/analysis/local/istiod_analyze.go
- pkg/config/model.go
- pkg/config/schema/collection/schemas.go
- releasenotes/notes/46241.yaml
Fix https://github.com/istio/istio/issues/46239.
> Fix revisioned default resources being filtered during analysis

- pilot/cmd/pilot-agent/status/server_test.go
adds reference to kuberentes probe req host override, removes incorrect comment, and updates error log
> cleanup app probe test

- cni/pkg/cmd/root.go
- pilot/pkg/bootstrap/istio_ca.go
Fix 2 typos in:
```
modified:   cni/pkg/cmd/root.go
modified:   pilot/pkg/bootstrap/istio_ca.go
```
> Fix two text typos

- releasenotes/notes/46277.yaml
fixes: #46277 
wait: https://github.com/istio/proxy/pull/4855
> add release notes for #46277

- istioctl/pkg/describe/describe.go
- istioctl/pkg/describe/describe_test.go
- releasenotes/notes/46161.yaml
Originally it uses the service label selector, which injected gateway doesn't have. This PR revises it to use pod selector.
> Fix describe with injected gateway not working

- tests/integration/pilot/gateway_test.go
This PR fix issuse #45865 by deploy the cross namespace secrets into the correct namespace, and then add two cases for tls gateway routing.
1. Fix cross namespace secrets deployment and add a test case for cross namespace
- use `ingressutil.CreateIngressKubeSecretInNamespace` func to create credential into correct namesapce
- add a `ReferenceGrant` to allow cross namespace secrets reference
2. Add a test case for same namespace
> fix: cross namespace gateway test cases

- tests/integration/pilot/multi_version_revision_test.go
Fix in https://github.com/istio/istio/pull/46213 is under discussion
> Temporarily skip version test that is broken

- bin/update_deps.sh
- bin/update_ztunnel.sh
- prow/release-commit.sh
> [release-1.19] Replace master with release-1.19

- istioctl/pkg/completion/completion.go
- istioctl/pkg/waypoint/waypoint.go
We currently only complete the NS.
> Add service account completion to waypoint command

- go.mod
- go.sum
- pilot/pkg/features/pilot.go
- pilot/pkg/model/telemetry_logging.go
- pilot/pkg/model/telemetry_logging_test.go
- releasenotes/notes/46339.yaml
Alternative for https://github.com/istio/api/pull/2872
> accesslog: disable builtin resource labels

- pilot/pkg/security/authz/builder/extauthz.go
- pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-no-namespace-out2.yaml
- pilot/pkg/security/authz/builder/testdata/http/custom-grpc-provider-out2.yaml
- pilot/pkg/security/authz/builder/testdata/tcp/custom-both-http-tcp-out2.yaml
to make authority aligns with otel and trace reporting.
Otherwise, we could meet https://istio.slack.com/archives/C382V8Q92/p1691034317554989?thread_ts=1691033025.465709&cid=C382V8Q92
> Set extAuth authority to hostname 

- pilot/pkg/config/kube/gateway/conversion_test.go
> add test for gateway route merge preferences

- tests/integration/pilot/revisioned_upgrade_test.go
https://github.com/istio/istio/pull/46291 but missed one case
> Temporarily skip version test that is broken (again)

- pkg/config/crd/validator.go
> make CRD validator support CEL validation

- pkg/bootstrap/platform/aws.go
- pkg/http/get.go
- releasenotes/notes/46312.yaml
fixes: https://github.com/istio/istio/issues/45825
> support aws IMDSv2

- pilot/pkg/xds/sds.go
Just a tiny cleanup, to avoid others wasting time on this like I did
> sds: remove TODO that is already done

- pkg/config/validation/validation.go
> validation: fix edge case in new mirror validation

- tests/integration/telemetry/envoyfilter/nullvm/dashboard_test.go
> correct flaky test comment

- pilot/pkg/bootstrap/server_test.go
> fix port conflict

- pilot/pkg/bootstrap/server_test.go
This makes the test actually check that we enable the server as well
> Reduce flakiness of TestNewServer

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/deployment/services.go
- pkg/config/analysis/msg/messages.gen.go
- pkg/config/analysis/msg/messages.yaml
Based on https://github.com/istio/istio/pull/46295
https://github.com/istio/istio.io/pull/13717
> Fix IST0117 message false positive in 1.20

- pilot/pkg/config/kube/crdclient/client.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/network.go
- pilot/pkg/serviceregistry/kube/controller/serviceexportcache.go
- pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
- pkg/kube/kclient/client.go
- pkg/kube/kclient/client_test.go
* Create in constructor like other types
* Allow delayed informer to be typed and make it so
* Make NetworkManager a pointer; it stores a mutex so using it w/o
pointer is unsafe.
> Minor improvements to network gateway

- pilot/pkg/model/endpointshards.go
- pilot/pkg/networking/core/v1alpha3/fake.go
- pilot/pkg/xds/eds.go
> rm clearcache param

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/networking/util/util_test.go
- releasenotes/notes/40680.yaml
> [release-1.19] pilot: set istio.alpn_override: false in subset clusters

- istioctl/pkg/cli/mock_client.go
- pkg/kube/client.go
- pkg/kube/portforwarder.go
- pkg/test/framework/components/cluster/kube/factory.go
- pkg/test/framework/components/echo/deployment/builder.go
- pkg/test/framework/components/echo/kube/workload.go
- pkg/test/framework/components/echo/kube/workload_manager.go
Fixes https://github.com/istio/istio/issues/46519
> [release-1.19] test framework: detect and reconnect if port-forward is terminated

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/telemetry/providers.go
- pkg/config/analysis/analyzers/testdata/telemetry-disable-provider.yaml
- releasenotes/notes/46531.yaml
> fix IST0157 warn

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/testdata/http.yaml
- pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/invalid.yaml.golden
blocked by https://github.com/istio/istio/pull/46368
> gateway: implement multiple mirrors

- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/xds/filters/filters.go
> ambient: remove baggage in waypoints

- tests/integration/pilot/common/routing.go
Add test for https://github.com/istio/istio/issues/40680
> Add tls re-encrypt test

- pilot/pkg/model/typed_xds_cache.go
> cache: use a single HashCode() call

- pilot/pkg/xds/debug.go
Before we were appending strings...
> debug: fix cachez size

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/telemetry/providers.go
- pkg/config/analysis/analyzers/testdata/telemetry-disable-provider.yaml
- releasenotes/notes/46531.yaml
> fix IST0156 warn (#46531)

- go.mod
- go.sum
- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/invalid.yaml
- pilot/pkg/config/kube/gateway/testdata/mesh.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/mesh.yaml
- pilot/pkg/config/kube/gateway/testdata/route-precedence.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/route-precedence.yaml
- pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
- releasenotes/notes/2309-gateway-api.yaml
- tests/integration/pilot/gateway_test.go
> Manual cherrypick of #46559

- go.mod
- go.sum
- istio.deps
- prow/release-commit.sh
Run bin/update_deps.sh  and make gen to prep for beta.1 build
> Update deps for beta.1

- pilot/pkg/config/kube/crdclient/types.gen.go
- pkg/config/schema/collections/collections.gen.go
- pkg/config/schema/gvk/resources.gen.go
- pkg/config/schema/gvr/resources.gen.go
- pkg/config/schema/kind/resources.gen.go
- pkg/config/schema/kubeclient/resources.gen.go
- pkg/config/schema/kubetypes/resources.gen.go
- pkg/config/schema/metadata.yaml
No current use, but we are using in the leaderelection now so for some
tests, etc will want to have this in some followup work.
> Add Leases to known types

- pilot/pkg/model/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/networking.go
Mainly removed `istionetworking.FilterChain`, and moved the filter to be under `filterChainOpts `
> Gateway listener cleanup

- pilot/pkg/serviceregistry/kube/controller/controller_test.go
These depend on syncronous handling, missed them in my PR
> Fix followup flakes from #46556

- pkg/config/analysis/local/istiod_analyze.go
- releasenotes/notes/46584.yaml
Fix https://github.com/istio/istio/issues/46563
> Analysis: exclude non Istio configmap

- go.mod
- go.sum
- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
- pilot/pkg/networking/util/util.go
client-go postsubmit was not able to update this dependency. I noticed that istio/api was also out of date.
Some of these changes are related to https://github.com/istio/api/pull/2240
> Update istio/api and istio/client-go

- pilot/pkg/model/authentication.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/authorization.go
- pilot/pkg/xds/workload.go
- pilot/pkg/xds/workload_test.go
Delta xDS requests were asking for the synthetic PeerAuthentication policy, but our RBAC xDS handlers was telling ztunnel to remove it because it was expecting the actual PeerAuthentication's resource (since that's the configuration that changed/created)
Fixes #46570
> Fix xDS logic for synthetic PeerAuthentications

- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/listener.go
> build tcp authz network filter together with other filters

- pilot/pkg/networking/core/v1alpha3/gateway_test.go
Recently had some questions around our behavior here, ideas to change it, and some refactorings, so want to codify in test
> Expand Gateway listener tests

- pilot/pkg/model/sidecar.go
fix the comment mistake in the function DestinationRuleConfig
> fix comment mistake

- pilot/pkg/model/network.go
I _think_ this is enough for https://github.com/istio/istio/issues/46361
```
❯ go test -race ./pilot/pkg/xds -run "TestMeshNetworking" -count 100
ok  go tistio.io/istio/pilot/pkg/xdsun "92.861shNetworking" -count 100
```
> make network gateway update less racy

- pilot/pkg/model/jwks_resolver.go
https://github.com/istio/istio/issues/46623
> fix TestConvertToEnvoyJwtConfig test flake

- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
Fix https://github.com/istio/istio/issues/46633
> [Release 1.19] fix listener additional address conflict for dualstack proxy

- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/v3/model.go
- pilot/pkg/xds/workload.go
See https://github.com/istio/ztunnel/pull/659, ztunnel only request for workload address now
> remove service resource handling

- tests/integration/telemetry/tracing/zipkin/client_tracing_test.go
- tests/integration/telemetry/tracing/zipkin/server_tracing_test.go
fixed in https://github.com/istio/istio/pull/30799
> remove obsolete comments

- go.mod
- go.sum
- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
- pilot/pkg/networking/util/util.go
https://github.com/istio/istio/pull/46598 was done on the main branch for some changes in istio/api which required changes in istio. The api PR was cherry-picked to release-1.19 and merged. To get those working in istio, we need to either revert the first istio/api change or manually cherry-pick the istio changes. This PR is for the later.
> [release-1.19] Manual cherry-pick of changes in #46958

- pilot/pkg/xds/endpoints/mtls_checker.go
- releasenotes/notes/46678.yaml
- tests/integration/pilot/common/routing.go
> mtlsChecker: filter out SIMPLE 

- go.mod
- go.sum
- prow/release-commit.sh
Run bin/update_deps.sh  to prep for rc.0 build
> Update deps for rc.0

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
See https://github.com/istio/bots/pull/724
> Add dual stack label to issues/prs

- releasenotes/notes/2309-gateway-api.yaml
- samples/bookinfo/gateway-api/route-all-v1.yaml
- samples/bookinfo/gateway-api/route-reviews-50-v3.yaml
- samples/bookinfo/gateway-api/route-reviews-90-10.yaml
- samples/bookinfo/gateway-api/route-reviews-v1.yaml
- samples/bookinfo/gateway-api/route-reviews-v3.yaml
Removes gateway group from samples
> Update Gateway API samples to use core group

- go.mod
- go.sum
- pilot/pkg/networking/core/v1alpha3/tracing.go
> Bump go-control-plane

- go.mod
- go.sum
- prow/release-commit.sh
Updating deps in preparation for 1.19.0 release
> Update deps for 1.19.0

- releasenotes/notes/43508.yaml
- tests/integration/README.md
fixes https://github.com/istio/istio/issues/43508
add ambient test framework flag for quick running integration test.
> add ambient test framework flag

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_test.go
- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
- releasenotes/notes/46711.yaml
fixes: https://github.com/istio/istio/issues/46653
> respect meshConfig.defaultConfig.sampling

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_test.go
- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
- releasenotes/notes/46711.yaml
fixes: https://github.com/istio/istio/issues/46732
manual cherry pick of https://github.com/istio/istio/pull/46711
> [release-1.18] respect meshConfig.defaultConfig.sampling

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_test.go
- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
- releasenotes/notes/46711.yaml
fixes: https://github.com/istio/istio/issues/46731
manual cherry pick of https://github.com/istio/istio/pull/46711
> [release-1.17] respect meshConfig.defaultConfig.sampling

- istioctl/cmd/istioctl_test.go
The test didn't test correctly since the commands were updated or removed.
> Fix TestBadParse test

- istioctl/pkg/checkinject/checkinject.go
> Add pod name completion to check-inject command

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/discoverycontrollers.go
- pilot/pkg/serviceregistry/kube/controller/multicluster.go
> only handle configStore from config cluster to prevent duplicate workload from remote clusters

- pkg/test/framework/components/echo/cmd/echogen/testdata/golden.yaml
- pkg/test/framework/components/echo/common/deployment/echos.go
- pkg/test/framework/components/echo/config.go
- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/components/echo/kube/templates/deployment.yaml
- pkg/test/framework/components/echo/kube/testdata/basic.yaml
- pkg/test/framework/components/echo/kube/testdata/disable-automount-sa.yaml
- pkg/test/framework/components/echo/kube/testdata/healthcheck-rewrite.yaml
- pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions-no-proxy.yaml
- pkg/test/framework/components/echo/kube/testdata/multiple-istio-versions.yaml
- pkg/test/framework/components/echo/kube/testdata/multiversion.yaml
- pkg/test/framework/components/echo/kube/testdata/proxyless-custom-image.yaml
- pkg/test/framework/components/echo/kube/testdata/proxyless.yaml
- pkg/test/framework/components/echo/kube/testdata/two-workloads-one-nosidecar.yaml
- pkg/test/framework/resource/flags.go
- pkg/test/framework/resource/settings.go
- tests/integration/ambient/main_test.go
- tests/integration/pilot/common/traffic.go
Reverts istio/istio#46730
This broke postsubmit
> Revert "tf: cleanup ambient flag"

- pilot/pkg/model/context.go
- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
> fix serviceTarget comment

- pilot/pkg/networking/core/v1alpha3/gateway.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pilot/pkg/networking/plugin/authz/authorization.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/security/authz/builder/builder.go
> Remove Istio 1.17 version check

- pkg/test/framework/components/echo/common/deployment/namespace.go
- tests/integration/pilot/headers_test.go
This breaks ipv6 and is no longer hermetic
> Use fake external service instead of httpbin in test

- samples/ratelimit/local-rate-limit-service.yaml
Istio's local rate limiting features with the use of envoy can be a little hard to implement at first, so why I decided to add a more in-depth example.
Wanted to added a small example of Istio local rate limited due to #42664, Just added an easy example some with comments to help understand how the Local rate limit filter and reduce any further issues on the topic. Can also add more detailed description to istio.io to showcase the different features to istio local rate limiting.
> Adding Example for Istio Local rate limits 

- istio.deps
- tests/binary/binaries_test.go
Supersedes https://github.com/istio/istio/pull/46793 updating the proxy reference but also increasing the allowed binary size.
> Update proxy and allow larger binary size

- tools/docker.yaml
For https://github.com/istio/istio/pull/46814
> Temporarily add xenial and bionic base images

- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/kube/controller/fake.go
> Clean up some unused code

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_test.go
- pilot/pkg/networking/core/v1alpha3/tracing.go
- pilot/pkg/networking/core/v1alpha3/tracing_test.go
- releasenotes/notes/46711.yaml
fixes: #46733 
manual cherry pick of #46711
> [release-1.19] respect meshConfig.defaultConfig.sampling

- pkg/test/framework/components/echo/config.go
- pkg/test/framework/components/echo/kube/deployment.go
- prow/lib.sh
- tools/docker.yaml
We intentionally raised the minimum OS
I think once https://github.com/istio/istio/pull/46816 merges it will push new base images and then this will just work, but maybe not. Probably will be a merghe conflict anyhow
> Raise minimum OS in VM tests

- pilot/pkg/model/extensions.go
ref https://github.com/istio/istio/pull/46514#discussion_r1317630052
> return http plugin type for default

- pkg/test/util/yml/file.go
fix: close the file fd when it indeed
> fix: close the file fd when it indeed

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_builder.go
- pilot/pkg/xds/filters/filters.go
- pkg/test/framework/components/echo/common/deployment/namespace.go
- releasenotes/notes/skip-mx-headers.yaml
- tests/integration/pilot/headers_test.go
manual cherrypick of https://github.com/istio/istio/pull/46579 with follow-up integ test fix https://github.com/istio/istio/pull/46767
bug fix for https://github.com/istio/istio/issues/17635
final part of https://github.com/istio/api/pull/2924 and  https://github.com/istio/proxy/pull/4933
> Cherrypick 46579

- pkg/test/framework/components/istio/kube.go
- tests/integration/pilot/main_test.go
- tests/integration/security/main_test.go
Reverts istio/istio#46860 as there are post submit failures : https://prow.istio.io/view/gs/istio-prow/logs/integ-ds_istio_postsubmit/1699845759966384128
> Revert "Enable DUAL_STACK flags at test framework level"

- pilot/pkg/model/endpointshards.go
- pilot/pkg/xds/eds_test.go
Fixes https://github.com/istio/istio/issues/46892
> send initial unready endpoints when SendUnhealthyEndpoints is enabled

- pilot/pkg/model/telemetry_test.go
ref: https://github.com/istio/istio/issues/46858
> telemetry: add test for TestTelemetryFilters

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
To make it simple, split from  https://github.com/istio/istio/pull/46882
> dedup addressInfo

- istioctl/pkg/verifier/verifier.go
- releasenotes/notes/46880.yaml
Fix https://github.com/istio/istio/issues/46859
> Fix verify install kinds for kind NetworkAttachmentDefinition

- pilot/pkg/config/kube/gateway/context.go
- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/config/kube/gateway/testdata/eastwest-labelport.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/eastwest-tlsoption.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/eastwest.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/multi-gateway.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/serviceentry.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/waypoint.status.yaml.golden
This PR cherry picks three fixes for gateway api from master that didn't have a chance to reach 1.19.0.
Closes #46932.
> [release-1.19] Gateway API cherrypicks

- pilot/pkg/model/push_context.go
- releasenotes/notes/46963.yaml
> fix DNSNoEndpointClusters metric

- docker/Dockerfile.distroless
- go.mod
- go.sum
- istio.deps
- prow/release-commit.sh
> Run bin/update_bin.sh on release-1.17

- pilot/pkg/networking/core/v1alpha3/cluster_builder.go
> move missing endpoints log to buildCluster

- pkg/monitoring/gauge.go
- pkg/monitoring/monitoring_test.go
- pkg/monitoring/monitortest/test.go
- releasenotes/notes/gauge-empty-metrics.yaml
Fixes https://github.com/istio/istio/issues/46977
> Fix issue with emiting uninitialized Guage metrics

- pilot/pkg/bootstrap/server.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
> move filter before to prevent unneeded processing

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
Fixes https://github.com/istio/istio/issues/46922. Will update API docs after this is merged.
> relax ttl validation to allow passive cookies

- tools/istio-clean-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/cmd/root.go
Refactor a bit, should have no changes
> Cleanup viper flag definitions

- tests/integration/pilot/common/routing.go
> add http cookie test case

- tests/integration/pilot/common/routing.go
> remove min istio version

- pkg/test/framework/suite.go
- tests/integration/ambient/main_test.go
this should fix post submit.. still figuring out why distroless isn't getting skipped.
> min k8s version for ambient suite

- go.mod
- go.sum
- tests/integration/ambient/gateway_conformance_test.go
- tests/integration/pilot/gateway_conformance_test.go
> gateway-api: re-enable multi-mirrors conformance tests

- pilot/pkg/xds/sds.go
- releasenotes/notes/46868.yaml
fix https://github.com/istio/istio/issues/46868
> Push back invalid secret to prevent sds fetching timeout

- pilot/pkg/model/endpointshards.go
fix https://github.com/istio/istio/issues/47016
> fix shardKey comment

- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/aggregate/controller.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/memory/discovery.go
- pilot/pkg/xds/delta.go
- pilot/pkg/xds/delta_test.go
- pilot/pkg/xds/workload.go
Fixed 
2. missing removed resources when full push happens, because we do not record all the resources that has been pushed.
> Fix delta workload bugs

- pilot/pkg/serviceregistry/kube/controller/controller.go
Fix https://github.com/istio/istio/issues/47001
> Fix TestMeshNetworking flake

- pilot/pkg/bootstrap/istio_ca.go
> update addCACertsFileWatcher log

- cni/pkg/plugin/iptables_linux.go
- cni/pkg/plugin/plugin_test.go
- cni/pkg/plugin/redirect.go
- releasenotes/notes/46625.yaml
- tools/istio-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/cmd/root_test.go
- tools/istio-iptables/pkg/config/config.go
- tools/istio-iptables/pkg/constants/constants.go
Fixes https://github.com/istio/istio/issues/46625
> Fix issue with dual-stack iptables6 rules when using istio-cni plugin

- pilot/pkg/networking/core/v1alpha3/cluster_builder_test.go
- pilot/pkg/networking/core/v1alpha3/cluster_test.go
This is part of an ongoing attempt to improve unit test coverage around code paths affected by the features.EnableDualStack flag.  I'm hoping to improve test coverage in small, targeted PRs to prevent regressions in the future.
> Improve cluster builder dual stack unit testing

- samples/extauthz/README.md
Previous there is a defect, namespace is missing, the sample cannot works successfully
Fix this typo.
> Update extauthz example

- releasenotes/notes/envoy-filter-removal.yaml
Change-Id: Iab46e26769b366a5ca8ddce45f93e203f1257862
> envoy: filter removal note

- security/pkg/server/ca/server.go
> minor improve server ca log

- istio.deps
- pilot/pkg/networking/core/v1alpha3/cluster_tls.go
- pilot/pkg/networking/core/v1alpha3/cluster_waypoint.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/networking/util/internal_upstream.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/xds/endpoints/endpoint_builder.go
- pilot/pkg/xds/filters/filters.go
- pilot/test/xdstest/extract.go
Fixes https://github.com/istio/istio/issues/46982
Issue https://github.com/envoyproxy/envoy/issues/29681
Change-Id: I7748857c6950f830e0e679649a49a70feed615f4
> envoy: replace with upstream original_dst

- tests/integration/pilot/testdata/tunneling/gateway/tcp/gateway.tmpl.yaml
- tests/integration/pilot/testdata/tunneling/gateway/tcp/virtual-service.tmpl.yaml
- tests/integration/pilot/testdata/tunneling/gateway/tls/istio-mutual/gateway.tmpl.yaml
- tests/integration/pilot/testdata/tunneling/gateway/tls/istio-mutual/mtls.tmpl.yaml
- tests/integration/pilot/testdata/tunneling/gateway/tls/istio-mutual/virtual-service.tmpl.yaml
- tests/integration/pilot/testdata/tunneling/gateway/tls/passthrough/gateway.tmpl.yaml
- tests/integration/pilot/testdata/tunneling/gateway/tls/passthrough/originate-tls.tmpl.yaml
- tests/integration/pilot/testdata/tunneling/gateway/tls/passthrough/virtual-service.tmpl.yaml
- tests/integration/pilot/tunneling_test.go
- tests/integration/security/testdata/authz/egress-gateway.yaml.tmpl
Backport original egress e2e changes to 1.18
> [cherry-pick 1.18] backport original egress e2e changes

- go.mod
- go.sum
- pilot/pkg/networking/grpcgen/grpcgen_test.go
- pkg/config/xds/filter_types.gen.go
- pkg/test/echo/server/endpoint/grpc.go
Update go-control-plane. The auto update failed.
> Update go control plane

- tests/integration/ambient/baseline_test.go
Still seeing some hairpinning tests fail on master; skip them for now until permanent solution is in place
> Skip Ambient hairpinning test cases

- pilot/pkg/networking/core/v1alpha3/httproute.go
Extract function and reduce `if...else` to improve readability
> refactor extract listenerPort

- pilot/docker/Dockerfile.proxyv2
- pilot/docker/Dockerfile.ztunnel
- prow/release-commit.sh
Update dependencies to prep for 1.19.1 release
> Update deps for 1.19.1

- tests/integration/ambient/main_test.go
TBH don't understand why the first didn'
t work, but try this
> tf: fix distroless ambient skip

- architecture/networking/pilot.md
> docs: update pilot.md

- pilot/pkg/networking/core/v1alpha3/gateway_test.go
> add gateway mirrors test

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_serviceentry_test.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_workloadentry_test.go
In the long-term the feature flag is planned to be removed (or replaced by config value) (#37374) but until then I'm adding the support for this behavior in Ambient mode so that the future work on this flag will also cover Ambient.
> EnableK8SServiceSelectWorkloadEntries in Ambient

- samples/kind-lb/README.md
- samples/kind-lb/setupkind.sh
> Add more options for setting up kind clusters

- tests/integration/ambient/baseline_test.go
Removes a weakened assertion for ambient sidecar to waypoint test
> minor update to allow stronger assertion about sidecar to waypoint

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
> Improve various validations

- istioctl/pkg/writer/envoy/configdump/listener.go
- istioctl/pkg/writer/envoy/configdump/listener_test.go
- releasenotes/notes/istioctl-additional-address.yaml
Cherry-pick of https://github.com/istio/istio/pull/44648
Fixes https://github.com/istio/istio/issues/44784
> [release-1.18] Support additional address in listeners output (#44648)

- pilot/cmd/pilot-agent/options/agent.go
link https://github.com/istio/istio/pull/47126
> fix insecureRegistries set

- pilot/pkg/bootstrap/server_test.go
> add test for empty customHost

- pkg/kube/client.go
Originally the logic would go through proxy and then fall back to exec in case of errors, I think we can simplify this by using port-forward directly to the debug API.
> Fix client get istio version logic

- pilot/pkg/model/virtualservice.go
- pilot/pkg/model/virtualservice_test.go
- releasenotes/notes/47148.yaml
Fixes https://github.com/istio/istio/issues/47148
> fix multiple header matches in root vs

- istioctl/pkg/multicluster/remote_secret.go
- istioctl/pkg/tag/generate.go
- pkg/kube/client.go
the yamlFile was created by writeToTempFile,But it is not be clean.If the yamlFile apply success,we should clean it.
> Fix the problem of creating temp files but not deleting them by directly applying yaml string

- pilot/pkg/serviceregistry/serviceentry/controller.go
> improve auto allocation comments

- pilot/pkg/xds/delta.go
- pilot/pkg/xds/workload.go
> clean up delta xds

- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
> don't trigger full push for none visibility K8s service

- tests/integration/iop-wds.yaml
Change-Id: Id980209b98ad803006f3416c11bc273c621dd908
> fix telemetry discovery test

- pilot/pkg/model/network_test.go
with this '337553 runs so far, 0 failures (100.00% pass rate). 502.487047ms avg, 707.254874ms max, 477.959715ms min'
> Fix DNS resolution flakes

- tests/integration/pilot/gateway_test.go
> Add gateway integration tests for dual-stack services

- bin/update_deps.sh
- bin/update_ztunnel.sh
- cni/test/install_k8s_test.go
- istio.deps
- manifests/charts/istio-cni/Chart.yaml
- prow/release-commit.sh
Update instances of `master` to `release-1.20` as part of the branch cut.
> [release-1.20] Update master to release-1.20 plus update-deps

- go.mod
- go.sum
- tests/integration/ambient/gateway_conformance_test.go
- tests/integration/pilot/gateway_conformance_test.go
> gateway-api: re-enable skipped conformance tests

- tests/integration/pilot/common/routing.go
> try fix consistent hash ttl

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_logging_test.go
- pilot/pkg/model/telemetry_test.go
- releasenotes/notes/46844.yaml
- tests/integration/telemetry/api/accesslogs_test.go
- tests/integration/telemetry/api/testdata/accesslog/targetref.yaml
Telemetry implementation for targetRef.
Fixes: #46844
> Telemetry target ref

- pilot/docker/Dockerfile.proxyv2
- pilot/docker/Dockerfile.ztunnel
https://github.com/istio/istio/pull/47339
> 1.19: Bump iptables image to fix glibc (#47339)

- manifests/charts/gateway/templates/deployment.yaml
- manifests/charts/gateway/values.schema.json
- manifests/charts/gateway/values.yaml
Allow setting priorityClassName in Istio gateway helm chart. 
Cherry-picked #47152
Fixes #47459
> Allow setting priorityClassName in Istio gateway helm chart

- bin/update_crds.sh
- tests/integration/pilot/testdata/gateway-api-crd.yaml
> Automate generate of gateway-api CRDs

- istio.deps
- prow/release-commit.sh
> [release-1.20] Run update-deps.sh

- pkg/config/validation/validation.go
This seems to be introduced in https://github.com/istio/istio/pull/47342.
> Fix validation with unexpected output validateHTTPRouteDestinations

- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_serviceentry_test.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_workloadentry_test.go
- pilot/pkg/serviceregistry/kube/controller/authorization.go
Added a test (and a fix) for a case of a ServiceEntry having multiple endpoints.
> Test and a fix for SE with multiple endpoints

- pilot/pkg/security/trustdomain/bundle.go
reduces logging level to DEBUG when trustdomain don't match but SkipValidateTrustDomain is enabled
fixes #47426
> adjust logging for SkipValidateTrustDomain

- go.mod
- go.sum
- tests/integration/pilot/testdata/gateway-api-crd.yaml
https://github.com/kubernetes-sigs/gateway-api/pull/2508 fixes the issue described in https://github.com/istio/istio/pull/47521.
Bumping the GW API version to include this change.
> Bump the k8s Gateway API

- pilot/pkg/model/gateway.go
- pilot/pkg/networking/core/v1alpha3/gateway_test.go
Fixes https://github.com/istio/istio/issues/47511
Regression from https://github.com/istio/istio/pull/43690
> Skip+Warn instead of NACK on invalid TLS gateway

- istioctl/pkg/waypoint/waypoint.go
- releasenotes/notes/47539.yaml
Right now we only accept deleting one waypoint at a time in `istioctl x waypoint delete` command, and this adds the support to delete multiple.
> istioctl: support deleting multiple waypoints in one command

- go.mod
- go.sum
- tests/integration/pilot/testdata/gateway-api-crd.yaml
> [release-1.20] Manual cherry-pick of #47537

- pkg/test/framework/components/istio/installer.go
Change-Id: I78f137745dd268a6f5826d70e2d8285b75acbc6f
> telemetry discovery test fix

- bin/update_crds.sh
> [release 1.20] Manual cherry-pick of #47503

- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/eds_test.go
- pilot/pkg/xds/endpoint_builder.go
- releasenotes/notes/terminating-headless.yaml
> 1.19: Fix traffic to terminating headless services (#47379)

- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/config/kube/crdclient/client.go
fix https://github.com/istio/istio/issues/47564
> [Release 1.19] prevent running crdclient twice 

- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/config/kube/crdclient/client.go
fix https://github.com/istio/istio/issues/47565
> [Release 1.20] prevent running crdclient twice

- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/config/kube/crdclient/client.go
fix  https://github.com/istio/istio/issues/47563
> [Release 1.18] prevent running crdclient twice

- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/eds_test.go
- pilot/pkg/xds/endpoint_builder.go
- releasenotes/notes/terminating-headless.yaml
> 1.18: Fix traffic to terminating headless services (#47379)

- pilot/pkg/serviceregistry/kube/controller/network_test.go
> remove test invalid print

- prow/release-commit.sh
> Publish a GCS alias for the current tag

- pilot/pkg/bootstrap/certcontroller.go
- pilot/pkg/bootstrap/istio_ca.go
- security/pkg/pki/ca/ca.go
- security/pkg/pki/ca/ca_test.go
Addresses some logic simplifications, and inconsistent logs, and adds an additional feature flag check
to ensure correct logging and improve readability.
Logic simplifications suggested in https://github.com/istio/istio/pull/47256
> Cleanup cacerts feature flag use

- go.mod
- go.sum
This is a manual cherrypick of the dependably update in https://github.com/istio/istio/pull/47643 (and earlier).
Fixes https://github.com/istio/istio/issues/47657
> [release-1.20] Cherry-pick dependabot updates of docker/docker

- pilot/pkg/model/context.go
- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
- pkg/config/constants/constants.go
- releasenotes/notes/serviceentry-dualstack.yaml
Fixes https://github.com/istio/istio/issues/46743 and https://github.com/istio/istio/issues/47406
Cherry-pick of https://github.com/istio/istio/pull/46795
> [release-1.18] Add IPv6 wildcard for dualstack proxies and correct ipv6 wildcard

- go.mod
> remove legacy exclude 

- manifests/charts/istio-control/istio-discovery/values.yaml
- manifests/charts/istiod-remote/values.yaml
- releasenotes/notes/add-tolerations-field-to-istiod.yaml
This is a pull request created from this comment.
- https://github.com/istio/istio/pull/47639#discussion_r1377295460
> [add] tolerations field to istiod

- tools/bug-report/pkg/cluster/cluster.go
Currently bug report cannot get proxy container info if it's injected with the sidecar container feature.
> Support sidecarContainers for bug-report

- pilot/pkg/serviceregistry/kube/controller/namespacecontroller_test.go
- pkg/config/mesh/watcher.go
- pkg/config/mesh/watcher_test_utils.go
AFAIK this is correct already, but best to leave unsafe to the experts...
> Drop unsafe usage in mesh config

- pilot/cmd/pilot-agent/options/options.go
Fix typo 'proxywhen'
Related: https://github.com/istio/istio.io/pull/14089
> Fix typo 'proxywhen'

- go.mod
- go.sum
- tests/integration/ambient/gateway_conformance_test.go
- tests/integration/pilot/gateway_conformance_test.go
- tests/integration/pilot/testdata/gateway-api-crd.yaml
> gateway-api: attached routes conformance test fix

- go.mod
- go.sum
- licenses/github.com/gorilla/mux/LICENSE
- licenses/github.com/gorilla/websocket/LICENSE
Update dependency gorilla. This frame had been archived for 2 years and just release its new version.
Ref: 
- https://github.com/gorilla/mux/releases/tag/v1.8.1
- https://github.com/gorilla/websocket/releases/tag/v1.5.1
Signed-off-by: Icarus9913 [icaruswu66@qq.com](mailto:icaruswu66@qq.com)
> update dependency gorilla

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- releasenotes/notes/header-present.yaml
> [release-1.19] Fix header present match (#47704)

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- releasenotes/notes/header-present.yaml
> Fix header present match (#47704)

- manifests/charts/istio-control/istio-discovery/templates/configmap.yaml
- manifests/charts/istiod-remote/templates/configmap.yaml
- releasenotes/notes/helm_chart_istiodiscovery_defaultvalues.yaml
> 1.18: Handle null values in istio-discovery template (#45955)

- pilot/pkg/networking/core/v1alpha3/listener.go
> remove never enetered code

- pkg/dns/client/monitoring.go
> fix dns failure comment

- tests/integration/pilot/common/routing.go
> add more logs to consistent hash tests

- docker/Dockerfile.distroless
- istio.deps
- prow/release-commit.sh
Updating dependencies for 1.19.4
> Update deps for 1.19.4

- pilot/pkg/config/kube/gateway/context.go
- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/testdata/eastwest-labelport.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/eastwest-tlsoption.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/eastwest.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/multi-gateway.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/serviceentry.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/waypoint.status.yaml.golden
- tests/integration/pilot/gateway_conformance_test.go
> gateway-api: enable static addresses conformance test

- pilot/pkg/serviceregistry/aggregate/controller.go
For https://github.com/istio/istio/issues/46105
> Add logging for service difference across clusters

- tests/integration/ambient/bookinfo_test.go
- tests/integration/ambient/waypoint_test.go
Follow-up to https://github.com/istio/istio/pull/47539. I know we have `apply/delete` commands tested in other tests, but this is for the entire command which covers all of its features, to ensure that further changes don't break any functionnalities like other istioctl commands.
> istioctl: add waypoint integration test

- pkg/istio-agent/xds_proxy_delta.go
This is to sync logics with xds proxy. Found the inconsistencies when I was debugging.
> Fix some delta xds proxy logics

- go.mod
- go.sum
- istio.deps
- prow/release-commit.sh
This probably need to be updated when it's close to the release date, I just send this in case it won't be approved on time.
> [release-1.20] Update deps

- tests/integration/security/cacert_rotation/main_test.go
fixes: https://github.com/istio/istio/issues/47829
> fix cacert_rotation TestReachability flake

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/networking/core/v1alpha3/cluster_cache.go
- pilot/pkg/networking/grpcgen/cds.go
- pkg/spiffe/spiffe.go
> Improve initServiceaccount by calculating once per service and reducing the lock time

- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- releasenotes/notes/header-present.yaml
> [release-1.20] Fix header present match (#47704)

- cni/pkg/ambient/informers.go
- cni/pkg/ambient/net.go
- cni/pkg/ambient/net_linux.go
- cni/pkg/ambient/server.go
- cni/pkg/ebpf/server/redirectionServer_linux.go
- cni/pkg/install/binaries.go
- cni/pkg/install/install.go
- cni/pkg/install/install_test.go
- cni/pkg/plugin/plugin.go
- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/model/network_test.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/service.go
- pkg/revisions/tag_watcher.go
- pkg/revisions/tag_watcher_test.go
- pkg/util/sets/set.go
- pkg/util/sets/set_test.go
- tools/bug-report/pkg/kubectlcmd/kubectlcmd.go
Only internal changes:
- replace all sets.Set[string] by sets.String 
- add String() function to Set
> Use sets.String replace sets.Set[string]

- pilot/pkg/leaderelection/leaderelection.go
- pilot/pkg/leaderelection/leaderelection_test.go
Fixes https://github.com/istio/istio/issues/47792
> leader election: fix lease locks stealing each other

- pilot/pkg/leaderelection/leaderelection.go
- releasenotes/notes/multicluster-leader-election.yaml
fix https://github.com/istio/istio/issues/47901
> fix multicluster leader election regression

- pilot/pkg/networking/core/v1alpha3/envoyfilter/cluster_patch.go
> cleanup ts merge

- pkg/istio-agent/agent.go
- pkg/istio-agent/bootstrap_stream.go
Fix https://github.com/istio/istio/issues/47880
> Added Bootstrap  ack/nack

- pilot/pkg/serviceregistry/kube/controller/pod.go
Regression in https://github.com/istio/istio/pull/47893
I am not really sure how to test this since it should be quite hard to simulate in a unit test... We detected this from a real world environment
> Fix race in pod reading

- pilot/pkg/networking/core/v1alpha3/listener.go
This fixes an edge case where a client connects to a gateway and takes
>15s to finish the TLS handshake. Regression from #46235. Note this PR
is not simply reverting that; the code has changed since that PR, and
this codepath is now exclusive to gateways (at the time, it was also
used for outbound)
> Do not allow listener filter timeout on gateway

- pilot/pkg/trustbundle/trustbundle.go
- pilot/pkg/trustbundle/trustbundle_test.go
> replace isEqSliceStr with slices.Equal

- pilot/pkg/serviceregistry/kube/controller/endpointcontroller.go
- pilot/pkg/serviceregistry/kube/controller/pod.go
- pilot/pkg/serviceregistry/kube/controller/pod_test.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- pilot/pkg/serviceregistry/serviceentry/store.go
- pilot/pkg/serviceregistry/serviceentry/store_test.go
- pkg/kube/kclient/client_test.go
- pkg/test/util/assert/tracker.go
- releasenotes/notes/we-memory-leaks.yaml
> [release-1.18] service entry: fix leak in workload addesses (#47974)

- pilot/pkg/networking/core/v1alpha3/listener.go
cherrypick of #47970
fixes #47993
> Do not allow listener filter timeout on gateway (#47970)

- tests/integration/operator/switch_cr_test.go
The `operator/` tests run after verifying the deletion of Istio pods. However, they currently check all pods in the `istio-system` namespace. When I execute the integration test locally, with some addons like Jaeger in my istio-system, the test is blocked because it considers the cluster as not being fully cleaned up. This PR has been revised to include only the pods with Istio revision labels.
> Fix a test issue running in local

- pilot/pkg/model/policyattachment_test.go
> refactor: remove duplicated test case

- pilot/pkg/trustbundle/trustbundle.go
> Added String() to better log CA source 

- pkg/test/kube/util.go
The logic should be inverted. We need to search for the webhook names against the list of webhooks. If one is not found, then return false.
Currently this test fails if the cluster already has another webhook previously deployed.
> Fix the logic when validating the creation of webhooks

- pilot/pkg/leaderelection/leaderelection.go
- pilot/pkg/leaderelection/leaderelection_test.go
> leader election: fix lease locks stealing each other (#47848)

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/injection/injection-image.go
- pkg/config/analysis/analyzers/testdata/common/meshconfig.yaml
- pkg/config/analysis/analyzers/testdata/injection-image-distroless.yaml
- releasenotes/notes/48017.yaml
Fix https://github.com/istio/istio/issues/47964
> Fix image analyzer report false positive messages when the imageType is distroless

- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
- releasenotes/notes/47946.yaml
Fix https://github.com/istio/istio/issues/45137
> make discoverySelector work on gateway deployment controller

- pilot/pkg/security/authn/v1beta1/policy_applier.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/jwt-from-cookies.yaml
Fix https://github.com/istio/istio/issues/47847
> Implement extract JWT from cookies

- pkg/kube/portforwarder.go
> Remove spurious log message from istioctl output

- pkg/istio-agent/xds_proxy_delta.go
- releasenotes/notes/47302.yaml
Fix https://github.com/istio/istio/issues/47227
This revised config after fetching was not updated to the response before forwarding.
> Fix ecds config not correct for delta response

- pilot/pkg/networking/core/v1alpha3/listener_builder.go
remove the four layers of `if` branch, to make it readable
For https://github.com/istio/istio/pull/48141#discussion_r1413643744
> refactor append metadata exchange filter

- pilot/pkg/model/telemetry_logging.go
> fix comment nit

- pilot/pkg/xds/debuggen.go
- pilot/pkg/xds/statusgen.go
I think this should resolve https://github.com/istio/istio/pull/48031 test failure when we have the new istio-testing build.
This shares the same logic with generate but with a generateDeltas func.
> Implement delta response for internal request and debug API

- pilot/pkg/serviceregistry/kube/controller/network_test.go
https://github.com/istio/istio/pull/48125#discussion_r1412436298
> Improve network tests

- pilot/pkg/util/protoconv/protoconv.go
Envoy tracking issue:
https://github.com/envoyproxy/go-control-plane/issues/824
This will be a NOP until go-control-plane completes ^. Once that
happens, we will get the optimizations for free
> proto: use vtprotobuf optimized functions when available

- go.mod
- go.sum
> [release-1.19] Cherrypick #47643 - dependabot docker/docker update

- pilot/pkg/networking/util/util.go
- pilot/pkg/xds/endpoints/endpoint_builder.go
> cleanup envoy endpoint building for tunnel

- pilot/pkg/serviceregistry/kube/controller/network_test.go
Made a mistake in the `expectGateways`. /cc @hzxuzhonghu 
Fix https://github.com/istio/istio/pull/48157#issuecomment-1840042807
> Fix test flake TestNetworkUpdateTriggers

- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/bootstrap/server.go
Fixes https://github.com/istio/istio/issues/48164
> Make EnableDistributionTracking really disable things

- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
> reduce redudant cal for autoAllocateIPs

- prow/release-commit.sh
> [release-1.20 ]Update deps

- pilot/pkg/config/kube/crdclient/client_test.go
Move repeated blocks of code into a function
> Small refactor to crdclient test

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/xds/cds.go
- pilot/pkg/xds/proxy_dependencies_test.go
- releasenotes/notes/jwks-cluster.yaml
For https://github.com/istio/istio/issues/29131#issuecomment-1845681375
We should build JWKS clusters for gateways to fetch remote JWKS
> `PILOT_FILTER_GATEWAY_CLUSTER_CONFIG`: build JWKS clusters

- pilot/pkg/serviceregistry/kube/controller/pod_test.go
- pkg/test/util/assert/tracker.go
> Fix TestHostNetworkPod flake

- tests/integration/telemetry/api/accesslogs_test.go
fixes: https://github.com/istio/istio/issues/48243
> e2e: increase accesslog retry timeout

- pilot/pkg/features/pilot.go
- pilot/pkg/model/config.go
- pilot/pkg/model/sidecar.go
- pilot/pkg/model/sidecar_test.go
- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
- pkg/config/model.go
- releasenotes/notes/45415-overlapping-wildcards.yaml
> Dedupe wildcard routes based on the virtualservice with the most specific match

- pilot/pkg/model/extensions.go
- pkg/wasm/convert.go
- pkg/wasm/imagefetcher.go
- tests/integration/telemetry/api/stats_test.go
fix some comment when debuging https://github.com/istio/istio/issues/48254
> fix some comment

- pilot/pkg/networking/util/util.go
- pilot/pkg/networking/util/util_test.go
> Fix merge traffic policy

- pilot/pkg/networking/core/v1alpha3/cluster_tls.go
- pilot/pkg/networking/core/v1alpha3/cluster_traffic_policy.go
- pilot/pkg/networking/core/v1alpha3/cluster_traffic_policy_test.go
- pkg/config/validation/validation.go
- releasenotes/notes/destination-rule-proxyprotocol
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/gw_topology_test.go
Implement https://github.com/istio/api/pull/3007
> Implement upstream proxy protocol

- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
> use discovery v1 labels

- pilot/pkg/model/gateway.go
- pkg/config/gateway/gateway.go
the nil TLS check is performed in `IsPassthroughServer` and most places where this function is called, the nil check is also performed.  Just removing the duplication
> code cleanup, remove duplicated checks

- pilot/pkg/features/pilot.go
- pilot/pkg/model/config.go
- pilot/pkg/model/sidecar.go
- pilot/pkg/model/sidecar_test.go
- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
- pkg/config/model.go
- releasenotes/notes/45415-overlapping-wildcards.yaml
> [release-1.20] Dedupe wildcard routes based on the virtualservice with the most specific match (#48071)

- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- releasenotes/notes/48207.yaml
part of https://github.com/istio/istio/issues/48207
> limit full pushes when pure http headless service endpoints add/delete

- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- pilot/pkg/serviceregistry/util/xdsfake/updater.go
> Fix missing push nds for headless pure http svc

- pkg/config/analysis/analyzers/all.go
- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/k8sgateway/workloadselector.go
- pkg/config/analysis/analyzers/testdata/k8sgateway-selector.yaml
- pkg/config/analysis/msg/messages.gen.go
- pkg/config/analysis/msg/messages.yaml
- releasenotes/notes/48318.yaml
Fix https://github.com/istio/istio/issues/48273.
> Add selector analyzer to k8s gateway

- tools/istio-iptables/pkg/dependencies/implementation_linux.go
We are already in the network namespace as this point, no need to enter
again (see `plugin.Program`)
> iptables: avoid `nsenter`ing twice

- pilot/pkg/xds/eds.go
- pilot/pkg/xds/eds_test.go
- releasenotes/notes/endpoints-false-negative.yaml
> [release-1.19] Always send new healthy endpoints

- pilot/pkg/grpc/tls.go
- security/pkg/nodeagent/cache/secretcache.go
- security/pkg/nodeagent/caclient/providers/citadel/client.go
> Remove `reconnectIfNeeded` and add loging for CSRSign failure

- tests/integration/pilot/common/traffic.go
related to https://github.com/istio/istio/issues/43161 and https://github.com/istio/istio/issues/45923
Issues were closed and tests are passing
> unskip ambient tests for closed issues

- manifests/charts/istio-control/istio-discovery/templates/_helpers.tpl
- manifests/charts/istio-control/istio-discovery/templates/configmap.yaml
- manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.16.yaml
- manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.17.yaml
- manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.18.yaml
- manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.19.yaml
- manifests/charts/istiod-remote/templates/_helpers.tpl
- manifests/charts/istiod-remote/templates/configmap.yaml
- manifests/charts/istiod-remote/templates/telemetryv2_1.16.yaml
- manifests/charts/istiod-remote/templates/telemetryv2_1.17.yaml
- manifests/charts/istiod-remote/templates/telemetryv2_1.18.yaml
- manifests/charts/istiod-remote/templates/telemetryv2_1.19.yaml
- releasenotes/notes/fix-stackdriver-install.yaml
> 1.19: Fix telemetry templates (#47894)

- manifests/charts/istio-control/istio-discovery/templates/_helpers.tpl
- manifests/charts/istio-control/istio-discovery/templates/configmap.yaml
- manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.16.yaml
- manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.17.yaml
- manifests/charts/istio-control/istio-discovery/templates/telemetryv2_1.18.yaml
- manifests/charts/istiod-remote/templates/_helpers.tpl
- manifests/charts/istiod-remote/templates/configmap.yaml
- manifests/charts/istiod-remote/templates/telemetryv2_1.16.yaml
- manifests/charts/istiod-remote/templates/telemetryv2_1.17.yaml
- manifests/charts/istiod-remote/templates/telemetryv2_1.18.yaml
- releasenotes/notes/fix-stackdriver-install.yaml
> 1.18: Fix telemetry templates (#47894)

- pilot/pkg/serviceregistry/kube/controller/controller.go
- pkg/config/mesh/networks_watcher.go
- pkg/config/mesh/watcher.go
> Cleanup WatcherHandlerRegistration

- tools/istio-iptables/pkg/dependencies/implementation_linux.go
Fixes https://github.com/istio/istio/issues/48416
Please read the issue, it has a lots of details on this bizarre case.
> cni: fix on GKE with oslogin

- manifests/charts/istio-cni/templates/clusterrole.yaml
Fixes #48472
This does not impact master branch, so only sending to 1.20
> Fix indentation of CNI helm chart

- pilot/pkg/xds/eds.go
- pilot/pkg/xds/eds_test.go
- releasenotes/notes/endpoints-false-negative.yaml
> [release-1.18] Always send new healthy endpoints

- pkg/test/framework/components/istio/cleanup.go
- pkg/test/framework/components/istio/config.go
- pkg/test/framework/components/namespace/kube.go
- pkg/test/framework/components/namespace/namespace.go
- tests/integration/ambient/main_test.go
potential post submit test failure fix for https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-124_istio_postsubmit/1735702436804300800
follow up to https://github.com/istio/istio/pull/48168
> fix slow ztunnel uninstall for post submit jobs

- manifests/charts/istio-cni/templates/clusterrole.yaml
Fixes https://github.com/istio/istio/issues/48472
fixes: https://github.com/istio/istio/issues/48493
> [Release-1.18] Fix indentation of CNI helm chart (#48476)

- go.mod
- go.sum
- prow/release-commit.sh
replace https://github.com/istio/istio/pull/48549
> [Release-1.18] update deps

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- pkg/config/validation/virtualservice.go
- releasenotes/notes/48530.yaml
fixes: https://github.com/istio/istio/issues/48529 https://github.com/istio/istio/issues/48534
> add validation for  StringMatch

- istioctl/pkg/proxyconfig/proxyconfig.go
It might be better to set the example here to a full command
> istioctl: adapt the example to be correctly

- pilot/pkg/xds/delta.go
- pkg/slices/slices.go
> fix some comments

- pilot/pkg/features/pilot.go
- pilot/pkg/model/config.go
- pilot/pkg/model/sidecar.go
- pilot/pkg/model/sidecar_test.go
- pilot/pkg/networking/core/v1alpha3/httproute.go
- pilot/pkg/networking/core/v1alpha3/route/route.go
- pilot/pkg/networking/core/v1alpha3/route/route_test.go
- pilot/pkg/networking/core/v1alpha3/sidecar_simulation_test.go
- pilot/pkg/xds/discovery.go
- pilot/pkg/xds/fake.go
- pkg/config/model.go
- releasenotes/notes/45415-overlapping-wildcards.yaml
Backporting #48071, #48330, and #48361 to 1.18. Fixes #48558
> [release-1.18] Wildcard Disambiguration

- pkg/config/schema/codegen/collections.go
- pkg/config/schema/kubeclient/resources.gen.go
- pkg/kube/client.go
This was not being respected for filtered informers like our Secret one.
This issue only is on 1.18, hence the direct PR
> Fix ISTIO_WATCH_NAMESPACE

- pilot/pkg/xds/ads.go
- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta.go
To  facilitate xds connection error debugging
> Enhance xds logging

- tests/integration/pilot/revisions/uninstall_test.go
> Cleanup unused var

- architecture/networking/pilot.md
Fix typo at pliot.md from coverts to converts
> Fix typo at pilot.md

- pilot/pkg/model/service.go
- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
- pilot/pkg/networking/core/v1alpha3/waypoint.go
- pilot/pkg/networking/core/v1alpha3/waypoint_test.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go
- pilot/pkg/serviceregistry/kube/controller/authorization.go
Currently, the order of waypoint listeners' config is changing instead of a consistent list.
> Fix undefined order of waypoint listener config

- pkg/log/config_test.go
Fix: https://github.com/istio/istio/issues/48566
The problem is because the synchronization issue, os.ReadDir returns a deleted ratate file. 
So let use an custom Eventually(cycle import with test pkg)
> Fix the flake test

- tests/integration/telemetry/api/setup_test.go
> remove useless config

- docker/Dockerfile.distroless
- go.mod
- go.sum
- prow/release-commit.sh
Update dependencies for 1.19.6
> Update deps for 1.19.6

- cni/pkg/plugin/plugin.go
See manifests/charts/istio-cni/templates/configmap-cni.yaml 
https://github.com/istio/istio/blob/b30e8f559f07efb62cbccc67f2c0ee2b9a4b1e39/manifests/charts/istio-cni/templates/configmap-cni.yaml#L20-L32
> istio-cni legacy args cleanup

- pilot/pkg/networking/core/v1alpha3/gateway_test.go
- pkg/maps/maps.go
> add test case for gateway stateful set config

- tests/integration/pilot/common/traffic.go
See https://github.com/istio/istio/issues/48614
Enabled in https://github.com/istio/istio/pull/48440
> Revert new ambient test that is broken

- istioctl/pkg/proxyconfig/proxyconfig.go
- istioctl/pkg/proxyconfig/proxyconfig_test.go
- istioctl/pkg/proxyconfig/testdata/config_dump.json
- istioctl/pkg/proxyconfig/testdata/config_dump_summary.txt
- istioctl/pkg/writer/envoy/configdump/configdump.go
- istioctl/pkg/writer/envoy/configdump/configdump_test.go
- releasenotes/notes/48557.yaml
This is to make it easier to see things like the envoy build sha for custom builds.
Also adds a test for the all config dump summary.
> Add bootstrap to all config dump summary

- pilot/pkg/features/pilot.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/sidecar.go
- pilot/pkg/model/sidecar_test.go
- pkg/dns/server/name_table_test.go
> unexport ConvertToSidecarScope

- pilot/pkg/model/push_context.go
- releasenotes/notes/48461.yaml
Supplement release note for #48461
> Add releasenote

- pilot/pkg/bootstrap/server_test.go
- pkg/adsc/delta.go
- pkg/test/util.go
- samples/extauthz/cmd/extauthz/main.go
- security/pkg/nodeagent/sds/sdsservice_test.go
- security/pkg/server/ca/authenticate/cert_authenticator_test.go
- security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go
- security/pkg/server/ca/authenticate/kubeauth/kube_jwt_test.go
- security/pkg/server/ca/authenticate/xfcc_authenticator_test.go
- security/pkg/server/ca/server.go
- security/pkg/server/ca/server_test.go
Use context int he standard library
> Change import of golang.org/x/net/context to context

- istioctl/pkg/admin/istiodconfig.go
- istioctl/pkg/authz/authz.go
- istioctl/pkg/metrics/metrics.go
- istioctl/pkg/proxystatus/proxystatus.go
- releasenotes/notes/48603.yaml
> Add auto completion for commands that can select pods

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/48621.yaml
- tests/integration/pilot/common/routing.go
Allow weighted cluster host rewrite from both `:authority` and `host`
> allow :authority host rewrite

- prow/release-commit.sh
> pkg is no longer a depdency

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/externalcontrolplane/externalcontrolplane.go
- pkg/config/analysis/analyzers/testdata/externalcontrolplane-missing-urls-custom-ns.yaml
- pkg/config/analysis/analyzers/testdata/externalcontrolplane-valid-urls-custom-ns.yaml
- releasenotes/notes/fix-47270.yaml
fixed https://github.com/istio/istio/pull/47270#discussion_r1352520471
>  Fixed Webhook Configuration Hardcoding in External Control Plane Analyzer

- pkg/config/analysis/local/istiod_analyze.go
- releasenotes/notes/48689.yaml
Fix https://github.com/istio/istio/issues/44844
https://github.com/istio/istio/blob/9bbd778d60ff7b4702d165c4bc69a003d3fc34b2/pilot/pkg/config/aggregate/config.go#L130-L136
> Fix file analysis not working when same resource exists in cluster

- Makefile.core.mk
- prow/benchtest.sh
Depends on https://github.com/envoyproxy/envoy/pull/31675 and
https://github.com/envoyproxy/envoy/pull/31172, although we can merge
before if we want.
> Optimize binary size and performance tradeoffs with build flags

- pilot/pkg/networking/core/v1alpha3/listener.go
- pilot/pkg/networking/core/v1alpha3/listener_inbound.go
- pilot/pkg/networking/core/v1alpha3/listener_test.go
- pilot/test/xdstest/validate.go
The same reason as https://github.com/istio/istio/pull/45670
> prevent port conflict with sidecar virtual listener like 15001 15006

- tests/integration/security/policy_attachment_only/main_test.go
- tests/integration/security/remote_jwks/main_test.go
add customsetup label for policy attachment only test
> add customsetup label for policy attachment only test

- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta.go
> send err to channel without block
