pilot/pkg/xds/ads.go
pilot/pkg/xds/delta.go

delta xds: make Workload behave like Address

---

pilot/pkg/networking/core/v1alpha3/listener_builder.go
pilot/pkg/xds/filters/filters.go

Change-Id: I66556eb42ed7261f849114ec967ee681b431a47a

xds: remove wasm metadata exchange fallback

---

tests/integration/operator/install_test.go

Resolves https://github.com/istio/istio/issues/48740

Fix TestController test flake

---

pilot/pkg/serviceregistry/kube/controller/controller_test.go
pilot/pkg/serviceregistry/kube/controller/endpointslice.go
releasenotes/notes/48814.yaml

add ip filter logic in GetProxyServiceTargets

---

istioctl/pkg/tag/generate.go
istioctl/pkg/tag/generate_test.go
releasenotes/notes/48780.yaml

Fix https://github.com/istio/istio/issues/47423

Fix webhooks created by `tag set` being deleted after re-installation

---

go.mod
go.sum
pilot/pkg/networking/core/v1alpha3/fake.go
tests/binary/binaries_test.go

For https://github.com/istio/istio/issues/48715

Update go-control-plane to drop PGV

---

pilot/pkg/serviceregistry/kube/controller/controller_test.go
pilot/pkg/serviceregistry/kube/controller/endpointslice.go
releasenotes/notes/48814.yaml

[release-1.19] add ip filter logic in GetProxyServiceInstances

---

istio.deps
pilot/pkg/xds/filters/filters.go

Fixes https://github.com/istio/istio/pull/48759

envoy: update set_filter_state config for ambient

---

pilot/pkg/networking/core/v1alpha3/tracing.go

lightstep is coverted to OTel, correct the provide name.

correct lightstep providerName

---

tests/integration/telemetry/stackdriver/api/stackdriver_filter_test.go
tests/integration/telemetry/stackdriver/common.go
tests/integration/telemetry/stackdriver/stackdriver_filter_test.go

stackdriver: add trace validation

---

tests/binary/binaries_test.go

updating binary size for ztunnel

---

pilot/pkg/networking/core/v1alpha3/cluster_builder.go
pilot/pkg/networking/grpcgen/cds.go
pilot/pkg/networking/util/util.go
pilot/pkg/networking/util/util_test.go
pilot/pkg/xds/endpoints/endpoint_builder.go

Split MergeTrafficPolicy and make it more readable and easy to maintain

---

istioctl/pkg/writer/envoy/configdump/configdump.go
pkg/dns/client/dns.go
security/pkg/nodeagent/caclient/providers/citadel/client.go
security/pkg/pki/util/crypto.go
security/pkg/pki/util/crypto_test.go
security/pkg/pki/util/keycertbundle.go
security/pkg/pki/util/keycertbundle_test.go

return with error infomation

---

istioctl/pkg/install/k8sversion/version.go

point the istio support release docs for k8s support warning

istioctl: point the istio support release docs for k8s support warning

---

pkg/config/analysis/msg/messages.gen.go
pkg/config/analysis/msg/messages.yaml

fixes https://github.com/istio/istio/issues/48897

Fix warning message for compatibilityVersion

---

releasenotes/notes/cni-no-sh.yaml
tools/istio-iptables/pkg/dependencies/implementation_linux.go

cni: allow running in environments without sh/mount

---

pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/controller_test.go
pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
releasenotes/notes/48580.yaml

Fixes https://github.com/istio/istio/issues/48580

Push xDS when target ports are changed

---

pilot/pkg/bootstrap/server.go
pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/controller_test.go
pilot/pkg/serviceregistry/kube/controller/serviceimportcache.go
releasenotes/notes/48580.yaml

Fixes https://github.com/istio/istio/issues/48944
Also cherry-picked https://github.com/istio/istio/pull/46718 to resolve conflicts

[release-1.19] Push xDS when target ports are changed

---

releasenotes/notes/enable-auto-sni.yaml
releasenotes/notes/enable-verify-certificate-at-client.yaml

Add upgrade notes for auto-sni and verify-cert-at-client

---

bin/update_deps.sh
bin/update_ztunnel.sh
cni/test/install_k8s_test.go
manifests/charts/istio-cni/Chart.yaml
prow/release-commit.sh

- [ x] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.

update release 1.21 deps

---

istio.deps
prow/release-commit.sh

update deps for 1.21beta0

---

istioctl/pkg/workload/workload.go

Added completion support to the service account flag of `istioctl x workload group create` command.

Added completion to service account flag of istioctl workload command

---

go.mod
go.sum

for https://nvd.nist.gov/vuln/detail/CVE-2024-21664

bump lestrrat-go/jwx

---

pilot/pkg/util/protoconv/protoconv.go

Clean up unused func

---

istioctl/pkg/cli/context.go
istioctl/pkg/cli/option.go

Cleanup cli options

---

pilot/pkg/config/file/store.go
releasenotes/notes/fix-45653.yaml

Fixed Analyze has parse error for empty resource

---

SUPPORT.md

Update support page to use github discussion

---

pilot/pkg/model/typed_xds_cache.go
pilot/pkg/model/typed_xds_cache_test.go

duplicate with https://github.com/istio/istio/blob/75bf323a797d3fe2f831278271ee860c52ba74dc/pilot/pkg/model/typed_xds_cache.go#L359

cleanup duplicate func

---

pilot/pkg/model/typed_xds_cache.go
pilot/pkg/model/typed_xds_cache_test.go

This is a theoretical issue, not something encountered in production environment, so I'm not sure how much this PR can reduce the memory footprint.

fix xds cache memory leak

---

pilot/pkg/serviceregistry/kube/controller/ambientindex_external.go
pilot/pkg/serviceregistry/kube/controller/ambientindex_test.go

The workload config may have incorrect waypoint, for example: 
```
istioctl x waypoint apply -s bookinfo-productpage    # workload waypoint will be bookinfo-productpage-istio-waypoint
istioctl x waypoint apply   # workload waypoint will be changed to namespace-istio-waypoint
istioctl x waypoint delete   # workload waypoint will be nil
```

Fix workload waypoint

---

common/config/.golangci.yml
pkg/test/framework/resource/flags.go
pkg/test/framework/resource/settings.go
tests/integration/pilot/gateway_conformance_test.go

[release-1.19] Add option to only run gateway conformance tests with standard resources (#49085)

---

pilot/pkg/config/kube/crdclient/types.gen.go
pkg/config/schema/collections/collections.gen.go
pkg/config/schema/gvk/resources.gen.go
pkg/config/schema/gvr/resources.gen.go
pkg/config/schema/kind/resources.gen.go
pkg/config/schema/kubeclient/resources.gen.go
pkg/config/schema/kubetypes/resources.gen.go
pkg/config/schema/metadata.yaml

adds DaemonSets type which will help istioctl analyze properly with ztunnel
manual cherrypick of https://github.com/istio/istio/pull/48181

add DaemonSets and StatefulSets to known types

---

pilot/pkg/xds/ads.go

reuse push order for known ordered typeurls

---

common/config/.golangci.yml
prow/release-commit.sh
tests/integration/pilot/gateway_conformance_test.go

Run update_deps.sh
lint test failed. Pulling in change noted in https://github.com/istio/istio/pull/49137 (basically a manual cherry-pick in this PR).

[release-1.21] Run update_deps.sh

---

common/config/.golangci.yml
tests/integration/pilot/gateway_conformance_test.go

xref: https://github.com/istio/istio/pull/49130

lint depguard

---

cni/pkg/nodeagent/net.go

remove irrational code block and probably stale comments

ambient: remove irrational code block for ns scan

---

go.mod
go.sum

[release-1.20] Manual cherry-pick of 49127

---

tests/integration/ambient/baseline_test.go

Should hopefully cover some aspects of #49131 - DNM until that goes in.

Add peerauth test to cover port-level PERMISSIVE.

---

go.mod
go.sum
licenses/github.com/klauspost/compress/snappy/xerial/LICENSE

[release-1.19] Manual cherry-pick of 49127

---

go.mod
go.sum

[release-1.21] Manual cherry-pick of 49127

---

istioctl/pkg/proxyconfig/proxyconfig.go
istioctl/pkg/writer/ztunnel/configdump/configdump_test.go
istioctl/pkg/writer/ztunnel/configdump/testdata/workloadsummary_default.txt
istioctl/pkg/writer/ztunnel/configdump/workload.go
releasenotes/notes/49049.yaml

This can make the workload config dump easier to be read.

istioctl: add namespace filtering to workload configdump

---

tests/integration/ambient/bookinfo_test.go

add enroll/off ambient test for bookinfo
https://github.com/istio/istio/issues/48386

add off/in ambient test for bookinfo

---

cni/pkg/nodeagent/informers.go
cni/pkg/nodeagent/informers_test.go

numerous err/warning log outputs unexpected while label/unlabel the ambient mode :
```
2024-02-03T13:43:47.988707Z    warn    ambient    failed to find pod netns    ns=default name=details-v1-5f4d584748-ddk86                                                                                                                                  ??
2024-02-03T13:43:47.988730Z    error    ambient    failed to remove pod to ztunnel: failed to find pod netns    ns=default name=details-v1-5f4d584748-ddk86                                                                                                ??
2024-02-03T13:43:47.988772Z    warn    ambient    failed to find pod netns    ns=default name=httpbin-worker1-7b47f9576c-m27vp …
```

ambient: fix: use lastest pod status to determine the action

---

tests/integration/ambient/bookinfo_test.go

Reverts istio/istio#49134
See https://github.com/istio/istio/issues/49182

Revert "add off/in ambient test for bookinfo"

---

pilot/pkg/config/kube/gateway/controller.go

Fixes https://github.com/istio/istio/issues/49120

gateway-api: fix a race condition when updating status

---

pilot/pkg/model/sidecar.go

This PR doesn't have any optimizations other than improving readability, but it makes sense to me. If you have any suggestions, please feel free to leave a comment. Thank you for your review.

refactor collectImportedServices func

---

pkg/kube/kclient/client.go
pkg/kube/kclient/interfaces.go

Inspired by https://github.com/istio/istio/pull/48818 (and I have a PR that will use it as well)

kclient: support patch operation

---

pilot/pkg/networking/core/v1alpha3/envoyfilter/util_test.go

remove deepequals in tests

---

cni/pkg/nodeagent/informers.go

Logically equivalent but with more obvious boolean comparisons.

Improves further on PR #49189

---

pkg/test/framework/features/features.yaml
tests/integration/helm/install_test.go
tests/integration/helm/upgrade/helm_upgrade_test.go
tests/integration/helm/upgrade/util.go
tests/integration/helm/util.go

Attempt to add integration tests as per https://preliminary.istio.io/latest/docs/ops/ambient/upgrade/helm-upgrade/
Fixes: https://github.com/istio/istio/issues/48388

Ambient Helm Install/Upgrade Integration Tests

---

cni/pkg/install/install.go
cni/pkg/nodeagent/cni-watcher.go

err logging for plugin listener exit and cosmetic change for sleepWatchInstall

istio-cni: err loging for plugin listener exit

---

.github/ISSUE_TEMPLATE/feature_request.md

closes #https://github.com/istio/istio/issues/49302

Replace discuss link in FR template

---

istioctl/pkg/admin/istiodconfig.go

istioctl: improve  admin log flag description

istioctl: improve  admin log flag description

---

docker/Dockerfile.distroless
istio.deps
prow/release-commit.sh

update deps for rc build for 1.21

---

pilot/pkg/serviceregistry/serviceentry/store.go
pilot/pkg/serviceregistry/serviceentry/store_test.go

Fixes https://github.com/istio/istio/issues/49315
Broken in https://github.com/istio/istio/pull/41831

Fix creation of new DNS_ROUND_ROBIN entries

---

pkg/test/framework/features/features.yaml
tests/integration/helm/install_test.go
tests/integration/helm/upgrade/helm_upgrade_test.go
tests/integration/helm/upgrade/util.go
tests/integration/helm/util.go

Reverts istio/istio#49258
Seeing post submit failures, and do not want to block :  https://prow.istio.io/view/gs/istio-prow/logs/integ-distroless_istio_release-1.21_postsubmit/1758281244338032640

Revert "[release-1.21] Ambient Helm Install/Upgrade Integration Tests"

---

istioctl/pkg/wait/wait.go
istioctl/pkg/wait/wait_test.go

Example race: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/49183/unit-tests-arm64_istio/1753570614968324096

istioctl: fix race in wait test

---

pilot/pkg/model/push_context.go
pilot/pkg/xds/ads.go

Fixes https://github.com/istio/istio/issues/49373

gateway-api: reconcile grpc routes

---

samples/open-telemetry/als/README.md
samples/open-telemetry/tracing/README.md

This is a folllow-up of https://github.com/istio/istio/pull/49143, to make the otel samples working with the demo profile.

Fix otel samples

---

pkg/config/validation/validation.go
pkg/config/validation/validation_test.go

fix https://github.com/istio/istio/issues/49345

warning when se is set workloadSelector with resolution NONE or DNS

---

releasenotes/notes/add-openshift-profile.yaml
tools/dump_kubernetes.sh

cleanup: modify some broken and error links

---

pilot/pkg/networking/core/v1alpha3/gateway_test.go
pilot/pkg/networking/core/v1alpha3/listener.go
pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
pilot/pkg/security/authn/utils/utils.go
pilot/pkg/security/model/authentication.go
pilot/pkg/security/model/authentication_test.go
pkg/config/validation/validation.go
pkg/config/validation/validation_test.go

Part of https://github.com/istio/api/pull/3052 . Implements for Gateways. Will followup with another PR for sidecars

add CRL support for gateways

---

pilot/pkg/networking/core/v1alpha3/listener_test.go
pilot/pkg/networking/core/v1alpha3/tls.go
releasenotes/notes/49476.yaml

Fix ipv6 wilcard evaluation

---

pilot/pkg/networking/core/v1alpha3/route/route.go
pilot/pkg/networking/core/v1alpha3/route/route_test.go
releasenotes/notes/49364.yaml

[release-1.20] Make sure unknown vhosts fall through and get added eventually (if on port 80) 

---

istio.deps

update patch branch to pull in correct proxy SHA
see: https://github.com/istio/istio/issues/49561

use correct proxy sha

---

pilot/pkg/xds/eds.go

not sure why we missed this var

make use of set

---

pilot/pkg/model/push_context.go
pilot/pkg/model/push_context_test.go

add comments in code and fix test comment

---

pilot/pkg/model/authorization.go

Make authz policy update log less noisy

---

pilot/cmd/pilot-agent/app/cmd.go
releasenotes/notes/49602.yaml
tools/istio-clean-iptables/pkg/cmd/root.go
tools/istio-iptables/pkg/cmd/root.go

Fix https://github.com/istio/istio/issues/44352

Fix init container does not honor log options

---

pilot/pkg/bootstrap/server.go
pkg/kube/inject/inject.go
pkg/kube/inject/webhook.go
pkg/kube/multicluster/component.go

I think the current logic is not quite right for a case where we inject cross-cluster.
This builds on https://github.com/istio/istio/pull/49260, just look at the last commit for now.

Make injection namespace check multicluster aware

---

pkg/config/validation/validation.go
pkg/config/validation/validation_test.go

https://github.com/istio/istio/pull/49596#issuecomment-1970711760

add crl validation for passthrough mode

---

pkg/test/framework/components/echo/kube/deployment.go
pkg/test/framework/components/istio/ingress.go
pkg/test/framework/components/istio/ingress/interface.go
pkg/test/framework/components/istio/kube.go
pkg/test/framework/components/istio/util.go
tests/integration/ambient/baseline_test.go
tests/integration/ambient/bookinfo_test.go
tests/integration/pilot/ingress_test.go
tests/integration/pilot/workloadentry_test.go
tests/integration/telemetry/api/dashboard_test.go
tests/integration/telemetry/tracing/otelcollector/tracing_test.go
tests/integration/telemetry/tracing/tracing.go
tests/integration/telemetry/tracing/zipkin/client_tracing_test.go
tests/integration/telemetry/tracing/zipkin/server_tracing_test.go

Add support for multiple IPs in ingress test framework

---

pilot/pkg/features/pilot.go
pilot/pkg/features/telemetry.go

move to telemetry file

---

istioctl/pkg/precheck/precheck.go
releasenotes/notes/49379.yaml

FIx https://github.com/istio/istio/issues/49379. Use resources instead of kinds to interact with the api-server.

Fix precheck resource using incorrect name

---

tests/integration/telemetry/tracing/otelcollector/tracing_test.go
tests/integration/telemetry/tracing/tracing.go
tests/integration/telemetry/tracing/zipkin/client_tracing_test.go
tests/integration/telemetry/tracing/zipkin/server_tracing_test.go

Fixes #49641
I'm reverting for now the change to have multiple zipkin instances as setting up multiple instances led to issues although only one is used.
It is not clear to me why it failed, I will continue to investigate the issue but for now at least we get a working postsubmit.

Fix postsubmit tracing tests in DS

---

pilot/pkg/networking/core/v1alpha3/route/route.go
pilot/pkg/networking/core/v1alpha3/route/route_internal_test.go
releasenotes/notes/49620.yaml
tests/integration/pilot/common/routing.go

regex * is not valid for URI, we should check .*

Fix catchall route check

---

pkg/kube/multicluster/cluster.go
pkg/kube/multicluster/secretcontroller.go
pkg/kube/multicluster/secretcontroller_test.go

We need to create the discovery filter before we call components.
Regression from https://github.com/istio/istio/pull/49262, which has
not shipped yet, so no backport is needed.

multicluster: fix and test filter creation

---

pilot/pkg/networking/core/v1alpha3/route/route.go

fix wildcard comments

---

istioctl/pkg/dashboard/dashboard.go
pkg/kube/client.go
pkg/kube/client_test.go
releasenotes/notes/49443.yaml

Provide a convenient way to see the Istio debug endpoints.

Add istio debug endpoints page to dashboard

---

pkg/kube/multicluster/secretcontroller_test.go

The component is added asyncronously now

multicluster: fix flaky test

---

pilot/pkg/networking/util/util.go

remove unused version check function

---

pilot/pkg/networking/core/v1alpha3/cluster_tls.go
pilot/pkg/networking/core/v1alpha3/cluster_tls_test.go
pkg/config/validation/validation.go
pkg/config/validation/validation_test.go
releasenotes/notes/file-mounted-crl.yaml

Followup #49346 for https://github.com/istio/api/pull/3052

add file mounted crl support for client tls settings

---

security/pkg/nodeagent/cache/secretcache.go
security/pkg/nodeagent/cache/secretcache_test.go

Fixes https://github.com/istio/istio/issues/49575

validate root cert before sending to Envoy

---

pilot/pkg/networking/core/v1alpha3/listener_waypoint.go
pilot/pkg/networking/core/v1alpha3/route/route.go
pilot/pkg/networking/core/v1alpha3/route/route_internal_test.go

cleanup waypoint listener

---

pkg/url/url.go
pkg/url/url_test.go

Cleanup unused urls

---

pkg/kube/multicluster/cluster.go
pkg/kube/multicluster/secretcontroller.go

I also feel buildComponents is confusing

cleanup: not to pass cb, improve readability

---

pkg/istio-agent/xds_proxy.go

We have 2 logs for each error, and one is missing the filter. Now just
one log, with the correct filter

xds proxy: avoid double logging errors

---

pkg/istio-agent/xds_proxy_delta.go

avoid duplicate error logging for delta xds proxy

---

pilot/test/util/diff.go
pkg/kube/client.go

Cleanup some unused codes

---

istioctl/pkg/precheck/precheck.go
pilot/pkg/networking/core/v1alpha3/route/route.go
pilot/pkg/networking/core/v1alpha3/route/route_test.go
releasenotes/notes/49364.yaml

[release-1.21]  Make sure unknown vhosts fall through and get added eventually (if on port 80)

---

pilot/pkg/model/push_context.go
pilot/pkg/networking/core/v1alpha3/name_table.go
pilot/pkg/serviceregistry/kube/controller/endpointslice.go
pilot/pkg/serviceregistry/serviceregistry_test.go
pilot/pkg/xds/cds.go
pilot/pkg/xds/eds.go
pilot/pkg/xds/lds.go
pilot/pkg/xds/rds.go
pkg/config/schema/codegen/common.go
pkg/config/schema/codegen/templates/kind.go.tmpl
pkg/config/schema/kind/resources.gen.go
pkg/dns/server/name_table.go
releasenotes/notes/headless-stale-nds

fix https://github.com/istio/istio/issues/49704
Cherry pick #49463

[release-1.21] fix headless service ep update without updating new endpoint for nds

---

pilot/pkg/model/envoyfilter.go
pilot/pkg/model/push_context.go
pilot/pkg/model/push_context_test.go
releasenotes/notes/49555.yaml

Fixes https://github.com/istio/istio/issues/49555

fix envoy filter ordering in root namespace and proxy namespace

---

pkg/kube/multicluster/cluster.go
pkg/kube/multicluster/component.go
pkg/kube/multicluster/secretcontroller.go
pkg/kube/multicluster/secretcontroller_test.go

Fixes https://github.com/istio/istio/pull/49657#discussion_r1512056303
The test fails without this PR (c0 is not synced when it should be).

multicluster: sync only the specific cluster

---

prow/release-commit.sh

[release-1.19] update deps

---

pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/helpers.go
pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go

Fixes https://github.com/istio/istio/issues/48854

Fix podWorkloadBuilder (#48854)

---

pilot/pkg/model/push_context.go
pilot/pkg/model/sidecar.go

This is a kind of improvement on performance.

Added a function for Gateway sidecar scope inititation because it only need services and destinationrules

---

pkg/test/kube/dump.go

15020 includes envoy+agent, 15090 is just envoy

test: include agent metrics in dump

---

tools/istio-iptables/pkg/dependencies/implementation_linux.go

This PR updates the log message as discussed in the [following PR.](https://github.com/istio/istio/pull/49703#discussion_r1519612928)

Update log message to include iptablesSaveBin name

---

CODEOWNERS

See https://docs.google.com/document/d/13lxJqtlaQhmV2EwsNnS6h-_O4pobZQZuMjrzOeMgVI0/edit on date 2024-03-11

Add networking maintainers to co-own ux code base

---

pkg/filewatcher/worker.go

Change-Id: I948a96951b61176996b75a2a1b5d10e1437adc6f
File watching might be used for potentially sensitive data (e.g. secret watch).
sha256 is practically equivalent to md5 but more secure.

crypto: use sha256

---

pilot/pkg/xds/delta.go
tests/integration/telemetry/api/setup_test.go

Fixes https://github.com/istio/istio/issues/49847

delta xds: never remove ECDS explicitly

---

pilot/pkg/model/push_context.go

fix https://github.com/istio/istio/pull/49800/files#r1524179247
cc @hzxuzhonghu 

add sidecar cache for gateway/waypoint

---

pilot/pkg/serviceregistry/kube/controller/network.go

Tidy up the code by deleting the redundant line.

Deleting the redundant line of code.

---

cni/pkg/nodeagent/netns_other.go

Fix Compilation errors on non-linux platforms

---

pkg/test/framework/components/echo/common/deployment/echos.go

integration tests: make SotW workload actually use SotW xDS

---

istioctl/pkg/waypoint/waypoint.go
pkg/config/analysis/analyzers/maturity/maturity.go
pkg/config/constants/constants.go
releasenotes/notes/49896.yaml
tests/integration/ambient/waypoint_test.go

Adds `--for` flag to the `istioctl x waypoint apply` command to allow for specification of address type. This is just the set up for the actual functionality, right now it doesn't actually do anything. A follow up PR will be done to wire it up fully and update the integration tests.
Related to #49437

Istioctl waypoint for annotation

---

manifests/charts/base/values.yaml

helm: clean up an unused value

---

istioctl/pkg/internaldebug/internal-debug.go
istioctl/pkg/internaldebug/internal-debug_test.go
istioctl/pkg/writer/pilot/status.go

Regression from https://github.com/istio/istio/pull/47740. I added a
test

istioctl: fix issue causing ps header for internal-debug

---

istioctl/pkg/describe/describe_test.go
istioctl/pkg/internaldebug/internal-debug_test.go
istioctl/pkg/proxyconfig/proxyconfig_test.go
istioctl/pkg/proxystatus/proxystatus_test.go
istioctl/pkg/wait/wait_test.go

Clean up unused test vars

---

pilot/pkg/networking/core/v1alpha3/cluster.go

minor delta cluster delete refactor

---

pilot/pkg/networking/core/v1alpha3/cluster.go

because inbound clusters always use Stow pattern, we can always cal deleted inbound clusters via: `{watched inbound clusters} differentiate  {built clusters}`

Simplify Inbound clusters deletion cal 

---

releasenotes/notes/49896.yaml

Recent PR got merged without me addressing this comment about improving the release note wording. This is a quick follow up to address that.
cc/ @dhawton @howardjohn  
Refactors release note wording to be more specific about the change to istioctl.

Update the release note for recent istioctl change to waypoint to be more specific

---

pilot/pkg/networking/core/v1alpha3/cluster_builder.go
pilot/pkg/networking/util/fuzz_test.go
pilot/pkg/networking/util/util.go

I think this helps detect #48292 issues.

add fuzz test for dr traffic policy merge and copy

---

pilot/pkg/serviceregistry/serviceentry/controller.go
pilot/pkg/serviceregistry/serviceentry/controller_test.go
releasenotes/notes/49965.yaml

Fix for https://github.com/istio/istio/issues/49809

Fix IP reshuffling when add/remove duplicated hostname

---

common/config/.golangci.yml
tools/golangci-override.yaml

sets pkg path be changed, so need update lint config
istio.io/istio/pkg/sets -> istio.io/istio/pkg/util/sets

update istio's sets pkg path lint

---

releasenotes/notes/38158.yaml
releasenotes/notes/45695.yaml
releasenotes/notes/destination-rule-proxyprotocol
releasenotes/notes/pc-merge-metadata.yaml
releasenotes/notes/wasm-cache-with-tag-stripped-url.yaml
releasenotes/notes/xds-partial-full.yaml

chore: fix some typos

---

pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/serviceentry/controller.go
pilot/pkg/serviceregistry/serviceentry/controller_test.go
releasenotes/notes/se-target-port.yaml

Fixes https://github.com/istio/istio/issues/49878

Push xDS when SE TargetPort is changed

---

operator/cmd/mesh/manifest-generate_test.go
operator/cmd/mesh/testdata/manifest-generate/input-extra-resources/envoyfilter.yaml
operator/pkg/helmreconciler/prune.go
releasenotes/notes/49960.yaml

[release-1.21] install: add envoyfilter to prune list

---

operator/cmd/mesh/manifest-generate_test.go
operator/cmd/mesh/testdata/manifest-generate/input-extra-resources/envoyfilter.yaml
operator/cmd/mesh/testdata/manifest-generate/input/default.yaml
operator/cmd/mesh/testdata/manifest-generate/input/empty.yaml
operator/pkg/helmreconciler/prune.go
releasenotes/notes/49960.yaml

[release-1.20] install: add envoyfilter to prune list

---

istioctl/pkg/waypoint/waypoint.go
pkg/config/constants/constants.go

refactor istioctl waypoint cmd

---

pkg/kube/inject/inject_test.go
pkg/kube/inject/testdata/inject/hello-openshift.yaml
pkg/kube/inject/testdata/inject/hello-openshift.yaml.injected
pkg/kube/inject/testdata/inputs/hello-openshift.yaml.44.mesh.gen.yaml
pkg/kube/inject/testdata/inputs/hello-openshift.yaml.44.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello-openshift.yaml.44.values.gen.yaml
pkg/kube/inject/webhook.go
pkg/kube/multicluster/component.go
pkg/platform/platform.go

By using a default value for the cluster ID.
Add a basic unit test covering injection in OpenShift.

Fix injection on OpenShift

---

pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
releasenotes/notes/50110.yaml

Prevent creating a policy in WDS based on an authz which is targeting waypoint/gateway

check for waypoint targeted authz policy in ambient controller

---

pilot/pkg/xds/discovery.go
pilot/test/xdstest/mock_discovery.go
pkg/istio-agent/xds_proxy_delta_test.go
pkg/istio-agent/xds_proxy_test.go

I don't see it being used anywhere, so I think it can be removed.

cleanup SendResponse

---

pilot/pkg/model/endpointshards.go

minor optimization:
If `needPush=true`, no loop is needed,
once `needPush` is assigned true in the loop, you can break out of the loop.

loop as needed

---

pkg/config/schema/collections/collections.agent.gen.go
pkg/config/schema/collections/collections.gen.go
pkg/config/schema/gvk/resources.gen.go
pkg/config/schema/gvr/resources.gen.go
pkg/config/schema/metadata.yaml
pkg/test/datasets/validation/dataset/security-v1-PeerAuthentication.yaml

Similar to https://github.com/istio/istio/pull/50171

Recognize peerauthentication v1

---

pkg/kube/krt/core.go
pkg/kube/krt/helpers.go
pkg/kube/krt/informer.go
pkg/kube/krt/join.go

Additional documentation for `krt`

Document additional krt exported identifiers

---

pilot/pkg/model/sidecar.go
pilot/pkg/model/sidecar_test.go
pilot/pkg/networking/core/serviceentry_simulation_test.go

Default  EgressListener services should also be merged

---

bin/build_ztunnel.sh

Mostly plan to use this to build musl as my OS has a too new glibc
version to run in our containers

ztunnel: allow building custom target

---

pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go

Follow up PR from [comment thread](https://github.com/istio/istio/pull/49970#discussion_r1549847364) on waypoint-for PR. This is a refactor to improve the annotateService helper function by making sc (the service test client) a full test client (read/write) as opposed to just write. This gives us things like the `Get()` method to retrieve a service using a namespace and name. Allows for a more uniform and cleaner way to annotate a service in a test. Also, useful for anything else that may want to benefit from doing a `svc.Get("svc-name", testNS)`.
cc/ @ilrudie

Make Service a full test client in ambientTestServer and update annotateService

---

pkg/config/analysis/analyzer.go
pkg/config/analysis/analyzers/all.go
pkg/config/analysis/local/istiod_analyze.go

No new features added, only tweaking interface for extension
Backport, manual cherry pick of https://github.com/istio/istio/pull/50187

[release-1.20] Implement CombinedAnalyzer interface

---

pkg/config/schema/collections/collections.agent.gen.go
pkg/config/schema/collections/collections.gen.go
pkg/config/schema/gvk/resources.gen.go
pkg/config/schema/gvr/resources.gen.go
pkg/config/schema/metadata.yaml
pkg/test/datasets/validation/dataset/telemetry-v1-Telemetry.yaml

Part of #46720
Follow up to [#3133](https://github.com/istio/api/pull/3133)

Recognize Telemetry v1

---

pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go

This was meant to run independantly, but re-uses IPs, etc without
properly clearing out events. Create a new server per test to make
things run properly

ambient: fix flake in new TestAmbientIndex_WaypointForWorkloadTraffic test

---

tools/bug-report/pkg/bugreport/bugreport.go

Fixes https://github.com/istio/istio/issues/37235

bug-report: ignore expected errors on distroless

---

samples/custom-bootstrap/README.md

Had a few questions about this in the past

docs: add note about custom bootstrap off-k8s

---

Makefile.core.mk
pilot/cmd/pilot-agent/app/cmd.go
pilot/cmd/pilot-agent/app/cmd_test.go
pilot/cmd/pilot-agent/main.go
pilot/cmd/pilot-agent/options/agent.go
pilot/cmd/pilot-agent/options/agent_proxy.go
pilot/cmd/pilot-agent/options/security_test.go
pilot/cmd/pilot-agent/options/statusserver.go
pilot/pkg/model/context.go
pilot/pkg/model/context_test.go
pkg/envoy/proxy_test.go
pkg/istio-agent/agent.go
pkg/istio-agent/agent_test.go
pkg/model/proxy.go

Change-Id: Ic27af05c1f8e7401791019f466eac619dde1ff0c
Completes #50134 except for SDS and sets up the dependency checks that should hopefully prevent another SDS problem again.

proxy: slim pilot-agent cmd

---

Makefile.core.mk
go.mod
go.sum
pilot/pkg/features/pilot.go

Fixes https://github.com/istio/istio/issues/49790

Enable vtprotobuf by default

---

istio.deps
tests/integration/ambient/baseline_test.go

Change testing to handle the ztunnel svc-addressed traffic changes in https://github.com/istio/ztunnel/pull/873

test changes to support revised ztunnel logic

---

tests/integration/helm/install_test.go
tests/integration/helm/upgrade/util.go
tests/integration/helm/util.go

Fixes https://github.com/istio/istio/issues/49242

Move helm tests to use --profile=ambient

---

pkg/config/analysis/analyzer.go
pkg/config/analysis/analyzers/all.go
pkg/config/analysis/local/istiod_analyze.go

No new features added, only tweaking interface for extension
Backport, manual cherry pick of https://github.com/istio/istio/pull/50187
Merged 1.20 backport https://github.com/istio/istio/pull/50229

[release-1.21] Implement CombinedAnalyzer interface

---

pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pkg/kube/controllers/common.go
pkg/kube/krt/collection.go
pkg/kube/krt/core.go
pkg/kube/krt/informer.go
pkg/kube/krt/internal.go
pkg/kube/krt/join.go
pkg/kube/krt/singleton.go
pkg/kube/krt/singleton_test.go
pkg/kube/krt/static.go
pkg/kube/krt/util.go

https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/49794/unit-tests_istio/1767212848146026496
honestly the fix is a little gross but it works... with a few other open PRs to fix bad tests, this is looking 100% stable on local runs

krt: fix register and sync race cause double events

---

tests/integration/helm/upgrade/util.go

Tracking in https://github.com/istio/istio/issues/50387

Fix ambient helm test

---

pilot/pkg/networking/core/listener_inbound.go

TBH not sure this is a great fix, but seems to work and better than NACKing?

hbone listener: allow pods with no service

---

pkg/config/validation/validation.go
pkg/config/validation/validation_test.go

Fixes https://github.com/istio/istio/issues/50381

validation: increase max connection timeout

---

prow/config/metrics/metrics.yaml

No strong reason, just picking up various improvements. It does have a faster latency of metrics updates now I think

prow: update metrics server

---

cni/pkg/cmd/root.go
pkg/ctrlz/ctrlz.go
pkg/ctrlz/options.go
pkg/file/file.go
releasenotes/notes/cni-pprof.yaml

Fixes https://github.com/istio/istio/issues/50399

cni: enable pprof, stop memory spikes (#50393)

---

istioctl/pkg/precheck/precheck.go

istioctl: handle DISABLE in TLS types for precheck

---

go.mod
go.sum
pilot/pkg/config/kube/crdclient/types.gen.go
pilot/pkg/config/kube/gateway/conversion.go
pilot/pkg/config/kube/gateway/conversion_test.go
pilot/pkg/config/kube/gateway/testdata/grpc.status.yaml.golden
pkg/config/model_test.go
pkg/config/schema/codegen/templates/collections.go.tmpl
pkg/config/schema/collections/collections.agent.gen.go
pkg/config/schema/collections/collections.gen.go
pkg/config/schema/gvk/resources.gen.go
pkg/config/schema/gvr/resources.gen.go
pkg/config/schema/kubeclient/resources.gen.go
pkg/config/schema/kubetypes/resources.gen.go
pkg/config/schema/metadata.yaml
tests/integration/ambient/gateway_conformance_test.go
tests/integration/pilot/gateway_conformance_test.go
tests/integration/pilot/testdata/gateway-api-crd.yaml

Phase 1 of https://github.com/istio/istio/issues/50408. Blocked by https://github.com/kubernetes-sigs/gateway-api/pull/2968

Initial update to Gateway API 1.1

---

tests/integration/ambient/gateway_conformance_test.go

ambient: drop conformance test skip

---

pilot/pkg/model/push_context.go
pilot/pkg/model/service.go
pilot/pkg/networking/util/util.go
pilot/pkg/serviceregistry/aggregate/controller.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
pilot/pkg/xds/endpoints/endpoint_builder.go
tests/integration/ambient/baseline_test.go

Replaces https://github.com/istio/istio/pull/50323 which replaced https://github.com/istio/istio/pull/50182
See code for description; I think I documented pretty well

 ambient: implement workload and service waypoints for EDS

---

pilot/pkg/controllers/untaint/nodeuntainter.go
pilot/pkg/controllers/untaint/nodeuntainter_test.go

Fixes https://github.com/istio/istio/issues/50444

node tainter: fix test flakes

---

istioctl/pkg/admin/istiodconfig.go
istioctl/pkg/authz/authz.go
istioctl/pkg/checkinject/checkinject.go
istioctl/pkg/completion/completion.go
istioctl/pkg/describe/describe.go
istioctl/pkg/metrics/metrics.go
istioctl/pkg/proxyconfig/proxyconfig.go
istioctl/pkg/proxystatus/proxystatus.go
istioctl/pkg/ztunnelconfig/ztunnelconfig.go

its used everywhere, might as well make it a 1-liner

istioctl: cleanup ValidArgsFunction

---

pilot/pkg/model/push_context.go
pilot/pkg/model/push_context_test.go
pilot/pkg/networking/core/cluster.go
pilot/pkg/networking/core/waypoint.go

Fixes https://github.com/istio/istio/issues/50398

ambient: include extra services to allow extensions to work

---

tests/integration/helm/install_test.go
tests/integration/helm/upgrade/helm_upgrade_test.go
tests/integration/helm/upgrade/util.go
tests/integration/helm/util.go

Tests helm installation and verification of ztunnel and istio-cni charts in non `istio-system` namespace
Begins #49924

Helm install tests for ambient multi-namespace deployment scenarios

---

pkg/kube/kclient/client.go

See
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/50471/unit-tests_istio/1779977024102731776
Comments for info

kclient: fix race condition in TestFilterNamespace

---

.github/dependabot.yml

remove  dependa bot 1.18 branch config

---

pilot/pkg/serviceregistry/serviceentry/conversion.go

remove unnecessary comments

---

pilot/pkg/config/kube/gateway/conditions.go
pilot/pkg/config/kube/gateway/conditions_test.go

Fixes https://github.com/istio/istio/issues/50484

gateway-api: check gateway controller when updating route status

---

tests/integration/ambient/waypoint_test.go

may fix https://github.com/istio/istio/issues/50184

wait for simple http waypoint to be ready

---

pilot/pkg/features/pilot.go

chore: warn EnableUnsafeDeltaTest like other unsafe features

---

go.mod
go.sum
pilot/pkg/config/kube/gateway/supported_features.go
tests/integration/pilot/gateway_conformance_test.go
tests/integration/pilot/testdata/gateway-api-crd.yaml

Fixes https://github.com/istio/istio/issues/49688
Thanks @hanxiaop

mod: bump gateway-api

---

tests/integration/ambient/baseline_test.go

Updates to istio testing to validate the policy capability of workload-attached waypoint proxies

tests for workload-attached-waypoint policies

---

pkg/config/analysis/analyzers/externalcontrolplane/externalcontrolplane.go

Fixes https://github.com/istio/istio/issues/50533

analyzer: do not depend on local network (#50528)

---

pilot/pkg/model/push_context.go
pilot/pkg/xds/delta.go
pilot/pkg/xds/delta_test.go

Should fix some of the MTLSOrigination flakes we've been seeing

Always push EDS after CDS

---

bin/update_crds.sh

Fix update_crds for istio/api having a alpha.1 label

---

istioctl/pkg/writer/ztunnel/configdump/api.go
istioctl/pkg/writer/ztunnel/configdump/connections.go
istioctl/pkg/ztunnelconfig/ztunnelconfig.go

Depends on https://github.com/istio/ztunnel/pull/939
Ultimately this enables istioctl to give us:
```
WORKLOAD                                      DIRECTION LOCAL                                              REMOTE                                             REMOTE TARGET
cartservice-bffc98bf4-bmqsg.anthos            Inbound   cartservice-bffc98bf4-bmqsg.anthos:7070            checkoutservice-c58746cd5-prxg9.anthos:41903
cartservice-bffc98bf4-bmqsg.anthos            Inbound   cartservice-bffc98bf4-bmqsg.anthos:7070            frontend-86c4744d65-f6xwb.anthos:50955
cartservice-bffc98bf4-bmqsg.anthos            Outbound  cartservice-bffc98bf4-bmqsg.anthos:50320           redis-cart-7ff8f4d6ff-lmlwg.anthos:6379            redis-cart.anthos.svc.cluster.local:6379 …
```

istioctl ztunnel: add connections command

---

istioctl/pkg/waypoint/waypoint.go

fixes #50569 
new message will look like:
```text
namespace default labeled with "istio.io/use-waypoint: waypoint"
```

improved enroll-namespace message

---

pilot/pkg/model/push_context.go
pilot/pkg/xds/delta.go

Minor changes to https://github.com/istio/istio/pull/50579

minor comment updates and reason name change

---

pilot/pkg/features/ambient.go

The name as it stands is a bit confusing.

bikeshed: AUTO_ALLOW_WAYPOINT_POLICY

---

bin/update_deps.sh
bin/update_ztunnel.sh
cni/test/install_k8s_test.go
docker/Dockerfile.distroless
prow/release-commit.sh

[release-1.22] Update master to release-1.22 plus update-deps

---

tests/integration/helm/install_test.go

This is causing some postsubmit failures: https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-123_istio_postsubmit/1782529993344028672

Make sure VAP-based tests are limited to k8s 1.30+

---

pilot/pkg/networking/core/cluster_traffic_policy.go
pilot/pkg/networking/core/loadbalancer/fuzz_test.go
pilot/pkg/networking/core/loadbalancer/loadbalancer.go
pilot/pkg/networking/core/loadbalancer/loadbalancer_test.go
pilot/pkg/xds/endpoints/endpoint_builder.go

Minor renaming + more comments to make this more readable

minor rename to locality load balancer code

---

security/pkg/nodeagent/caclient/providers/citadel/client.go
security/pkg/nodeagent/caclient/providers/citadel/client_test.go
security/pkg/nodeagent/caclient/providers/citadel/leak_test.go
security/pkg/nodeagent/caclient/providers/google-cas/client.go
security/pkg/nodeagent/caclient/providers/google-cas/client_test.go
security/pkg/nodeagent/caclient/providers/google/client.go
security/pkg/nodeagent/caclient/providers/google/client_test.go

Change-Id: I276ce58ff0a35b1db29b285ebe38c2f72efc84eb
Use the conventional package names.

proxy: fix package names

---

pilot/pkg/model/context.go
pilot/pkg/model/push_context.go
pilot/pkg/xds/ads.go
pilot/pkg/xds/delta.go
pilot/pkg/xds/discovery_test.go
pilot/pkg/xds/pushqueue_test.go
pilot/pkg/xds/xdsgen.go
pkg/xds/server.go

In-place refactor to decouple xDS server from pilot.
Complete change: https://github.com/istio/istio/pull/50515
Issue: #50134

xDS server: define interfaces

---

go.mod
go.sum

bump github.com/envoyproxy/go-control-plane to main version
This will also help confirm the modifications done in xds have no impact

envoy: bump github.com/envoyproxy/go-control-plane to main version

---

pkg/config/validation/validation.go

Similar PR seems to be a lengthy process.

Fix use set

---

pilot/pkg/leaderelection/leaderelection_test.go
pilot/pkg/leaderelection/leak_test.go
pilot/pkg/server/instance_test.go
pilot/pkg/server/leak_test.go
pilot/pkg/serviceregistry/aggregate/controller_test.go
pilot/pkg/serviceregistry/aggregate/leak_test.go
pkg/kube/inject/leak_test.go
pkg/kube/inject/watcher_test.go
pkg/kube/kclient/client_test.go
pkg/kube/kclient/leak_test.go
pkg/kube/krt/collection_test.go
pkg/kube/krt/leak_test.go

Add some goroutine leak checks and fix some incorrect test cases.

Add some goroutine leak checks

---

pilot/pkg/xds/endpoints/endpoint_builder.go
pilot/pkg/xds/endpoints/ep_filters_test.go
releasenotes/notes/50688.yaml

fixes: #50717 
Manual pick: #50690

[release-1.20] Fix eds cluster loadassignment with invalid endpoint

---

pkg/config/validation/validation.go

Added http3-post-connect-failure to the retryOn condition and moved them to Set

add new retryon condition in validation code

---

releasenotes/notes/50195.yaml

release notes for 50195

---

pilot/pkg/xds/ads.go
pilot/pkg/xds/auth.go
pilot/pkg/xds/debug.go
pilot/pkg/xds/delta.go
pilot/pkg/xds/discovery.go
pilot/pkg/xds/discovery_test.go
pilot/pkg/xds/monitoring.go
pilot/pkg/xds/pushqueue_test.go
pilot/pkg/xds/xdsgen.go
pkg/xds/monitoring.go
pkg/xds/server.go
pkg/xds/server_test.go

Follow-up to #50652 to move files into another package. No code changes.
Issue: #50134

xds server: move files

---

pilot/pkg/server/instance_test.go

Fix test flake in TestRunComponentsAfterStart

---

tests/integration/pilot/common/routing.go

```
--- FAIL: TestTrafficWithCNIRepair/jwt-claim-route/matched_with_nested_claim_and_single_claim_using_claim_to_header:200 (33.81s)
--- PASS: TestTrafficWithCNIRepair/jwt-claim-route/matched_with_nested_claim_and_single_claim_using_claim_to_header:200/to_b (0.31s)
--- PASS: TestTrafficWithCNIRepair/jwt-claim-route/matched_with_nested_claim_and_single_claim_using_claim_to_header:200/to_captured (0.16s)
--- PASS: TestTrafficWithCNIRepair/jwt-claim-route/matched_with_nested_claim_and_single_claim_using_claim_to_header:200/to_naked (0.15s)
--- FAIL: TestTrafficWithCNIRepair/jwt-claim-route/matched_with_nested_claim_and_single_claim_using_claim_to_header:200/to_waypoint (31.33s)
```
`.08s` is very fast for us to push a new VirtualService and have it kick in. We're actually continuing to test …

fix jwt-claim-route flake

---

tests/integration/helm/util.go

By using a map. Also, added `Set()` for completeness. It will be needed in a follow up change.

helm tests: Simplify the implementation of `NamespaceConfig`

---

istio.deps
tests/integration/ambient/baseline_test.go

[release-1.22] fix ambient telemetry test

---

manifests/charts/base/files/profile-openshift.yaml
manifests/charts/default/files/profile-openshift.yaml
manifests/charts/gateway/README.md
manifests/charts/gateway/files/profile-openshift.yaml
manifests/charts/gateway/templates/deployment.yaml
manifests/charts/gateways/istio-egress/files/profile-openshift.yaml
manifests/charts/gateways/istio-ingress/files/profile-openshift.yaml
manifests/charts/istio-cni/files/profile-openshift.yaml
manifests/charts/istio-control/istio-discovery/files/profile-openshift.yaml
manifests/charts/istio-operator/files/profile-openshift.yaml
manifests/charts/istiod-remote/files/profile-openshift.yaml
manifests/charts/ztunnel/files/profile-openshift.yaml
manifests/helm-profiles/openshift.yaml

Manual backport of https://github.com/istio/istio/pull/50042
Fixes #50801

[release-1.21] Fix gateway deployment on OpenShift

---

pilot/pkg/model/endpointshards.go
pilot/pkg/model/push_context.go
pilot/pkg/model/service.go
pilot/pkg/serviceregistry/serviceentry/conversion.go
pilot/pkg/serviceregistry/serviceentry/conversion_test.go
pilot/pkg/xds/cds_test.go
releasenotes/notes/se-conflict.yaml

fixes: https://github.com/istio/istio/issues/50774
cherry-pick https://github.com/istio/istio/pull/50711

[release-1.20] Fix service entry merge

---

pilot/pkg/model/endpointshards.go
pilot/pkg/model/push_context.go
pilot/pkg/model/service.go
pilot/pkg/serviceregistry/serviceentry/conversion.go
pilot/pkg/serviceregistry/serviceentry/conversion_test.go
pilot/pkg/xds/cds_test.go
releasenotes/notes/se-conflict.yaml

fixes:  #50775
cherry-pick  https://github.com/istio/istio/pull/50711

[release-1.21] Fix service entry merge

---

pilot/pkg/security/authz/builder/testdata/http/extended-allow-full-rule-out.yaml
pilot/pkg/security/authz/model/generator.go
releasenotes/notes/jwt-aud.yaml

Change-Id: If445377fde7c16b4ad9ef71c8000aba16f1be688
Fixes: #49913

jwt: fix list audience claim matching

---

pkg/config/analysis/analyzers/deployment/services.go
pkg/config/analysis/analyzers/gateway/conflictinggateway.go
pkg/config/analysis/analyzers/injection/injection-image.go
pkg/config/analysis/analyzers/sidecar/selector.go
pkg/config/analysis/analyzers/sidecar/util.go
pkg/config/analysis/analyzers/telemetry/selector.go
pkg/config/analysis/analyzers/telemetry/util.go
pkg/config/analysis/analyzers/virtualservice/conflictingmeshgatewayhosts.go
pkg/config/analysis/analyzers/webhook/webhook.go

map iteration order is random, this will cause the output random.

istioctl: make analyze params in result message stable

---

istio.deps
tests/integration/ambient/baseline_test.go

[release-1.22] bump proxy and ambient test

---

istio.deps
tests/integration/ambient/baseline_test.go

bump proxy and ambient test

---

istioctl/pkg/waypoint/waypoint.go

changes the behavior of istioctl waypoint generation/creation to avoid adding the istio.io/waypoint-for label if the user did not specify a value. istiod already defaults to service if the label is not present and if we explicitly set a value with istioctl then accepting the default from the gateway class in the future becomes more difficult.

stop default for istio.io/waypoint-for in istioctl

---

cni/pkg/iptables/iptables.go
tools/istio-iptables/pkg/dependencies/implementation.go

A few debug logs to make diagnosing `iptables` selection behavior in different environments easier.

Add some more useful logging around iptables selection in ambient CNI

---

cni/deployments/kubernetes/Dockerfile.install-cni
pilot/docker/Dockerfile.proxyv2
pilot/docker/Dockerfile.ztunnel

Includes patches for glibc CVEs
CVE-2024-33602 
CVE-2024-33599		
CVE-2024-33601		
CVE-2024-2961
CVE-2024-33600

Update iptables image SHA

---

cni/deployments/kubernetes/Dockerfile.install-cni
pilot/docker/Dockerfile.proxyv2
pilot/docker/Dockerfile.ztunnel

[release-1.20] Update iptables image SHA

---

pilot/test/xds/fake.go

Splitting this out of some larger work, where I am incorporating the
fake into some larger testing infra which already has a kube-client

discovery fake: allow kube-client override

---

releasenotes/notes/no-1p-jwt.yaml

wrong kind broken `gen-release-notes`

fix release-notes kind

---

pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go

cleanup rename p to wle

---

docker/Dockerfile.base
docker/Dockerfile.distroless
releasenotes/notes/noble-base.yaml

This just bumps the base. Should be negligible change for users

docker: use `ubuntu:noble`

---

pkg/kube/krt/fetch.go

In a test of how long it takes to reconcile a massive setup:
Baseline: 16.8s https://flamegraph.com/share/8177d161-0cc2-11ef-a542-36adf59c1176
With this PR: 8.8s https://flamegraph.com/share/9af9343d-0cc2-11ef-8204-e6b38c1ccd74

krt: optimize FilterKey

---

tests/integration/pilot/common/routing.go

see why
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/50921/integ-pilot-multicluster_istio/1788245480619118592
fails

exp: add more logs

---

pilot/pkg/serviceregistry/kube/controller/controller.go

(cherry picked from commit 20086bca0bb86156fd5929d33e2deb99798ba37e)

performance: optimize metrics in kube controller

---

pkg/test/framework/resource/flags.go
pkg/test/framework/resource/settings.go
tests/integration/README.md
tests/integration/helm/install_test.go
tests/integration/helm/upgrade/util.go
tests/integration/helm/util.go

And make the helm tests to pass on OpenShift by using this flag.

Add an openshift flag to integration tests

---

pilot/pkg/xds/cds.go

Follow up to https://github.com/istio/istio/pull/50757. This makes the
check only occur if the GW actually changed.

xds: avoid computation when not needed for CDS

---

istio.deps

[release-1.22] bump deps

---

pilot/pkg/config/kube/crdclient/client_test.go

Test to ensure https://github.com/istio/api/issues/3127 work doesn't
cause regressions

Add a test to ensure we can handle alt client-go versions

---

tests/integration/pilot/cni/cniversionskew_test.go

Take 2... this time I tested myself a lot

Fix TestCNIVersionSkew 2.0

---

pilot/pkg/model/endpointshards.go
pilot/pkg/model/service.go
pilot/pkg/serviceregistry/serviceregistry_test.go

[release-1.21] pilot: fix bug in endpoint updates

---

pilot/pkg/xds/workload.go

Auth policy generator cleanup

---

pkg/kube/version.go
pkg/kube/version_test.go

Fixes https://github.com/istio/istio/issues/51114

Workaround weird cluster versions

---

pkg/kube/namespace/filter.go

[release-1.21] Fix data race in discovery filter

---

pilot/pkg/networking/core/cluster_waypoint.go
pkg/test/framework/components/echo/common/deployment/echos.go
pkg/test/framework/components/echo/common/deployment/external.go
pkg/test/framework/components/echo/common/deployment/namespace.go
tests/integration/ambient/main_test.go
tests/integration/ambient/waypoint_test.go
tests/integration/pilot/headers_test.go

Today these are EDS clusters with 0 endpoints.
Added a test that excercises the full flow

Ambient: support DNS backends with waypoint

---

go.mod
go.sum

Bump docker to address https://nvd.nist.gov/vuln/detail/CVE-2024-24557

Bump docker

---

security/pkg/pki/util/keycertbundle.go
security/pkg/server/ca/monitoring.go
security/pkg/server/ca/server.go

add time remaining before cert expires metrics

---

istioctl/cmd/root.go
istioctl/pkg/ztunnelconfig/ztunnelconfig.go

I think we have, and will certainly by 1.23, gotten enough usage on this
for promotion.

istioctl: promote ztunnel-config (for 1.23)

---

samples/ratelimit/rate-limit-service.yaml
samples/tcp-echo/tcp-echo-ipv4.yaml

Update some example imagepullpolicy to IfNotPresent

update some example imagepullpolicy to IfNotPresent

---

pilot/pkg/networking/util/util.go
pilot/pkg/networking/util/util_test.go
pilot/pkg/xds/endpoints/ep_filters.go
pilot/pkg/xds/endpoints/ep_filters_test.go
pilot/test/xdstest/endpoints.go

Fixes https://github.com/istio/istio/issues/51202

Send HBONE endpoints in the local network

---

istioctl/pkg/injector/injector-list_test.go

While going through `injector-list.go`,found out that there was no unit test case available for `injectionDisabled` function so  added a unit testcase for `injectionDisabled` function in `injector-list_test.go`.

added a unit test for function injectionDisabled

---

samples/bookinfo/src/productpage/templates/productpage.html

Follow-up to #51239 so as not to leak HTML when grepping in examples.
```
craigbox@solo-system-craigbox:/tmp/istio-1.22.0$ kubectl exec deploy/sleep -- sh -c "for i in \$(seq 1 100); do curl -s http://productpage:9080/productpage | grep reviews-v.-; done"
<div class="mt-0.5 text-gray-600 font-mono">Reviews served by: reviews-v3-65dd8f9b89-88qkz
<div class="mt-0.5 text-gray-600 font-mono">Reviews served by: reviews-v3-65dd8f9b89-88qkz
<div class="mt-0.5 text-gray-600 font-mono">Reviews served by: reviews-v1-79655c5f69-5zclt
<div class="mt-0.5 text-gray-600 font-mono">Reviews served by: reviews-v1-79655c5f69-5zclt
<div class="mt-0.5 text-gray-600 font-mono">Reviews served by: reviews-v2-c5965fd69-2h82n
<div class="mt-0.5 text-gray-600 …
```

put review service on its own line

---

pkg/kube/inject/inject.go
pkg/kube/inject/inject_test.go

Fixes https://github.com/istio/istio/issues/51071
Not ideal fix, longer term is in https://github.com/istio/istio/issues/48991

istiod: improve error message when values.yaml is invalid

---

pilot/pkg/features/pilot.go
pilot/pkg/serviceregistry/kube/controller/network.go
tests/integration/base.yaml

This has been around and tested since last July without issues
Fixes https://github.com/istio/istio/issues/51010

Enable PILOT_MULTI_NETWORK_DISCOVER_GATEWAY_API by default

---

cni/pkg/nodeagent/informers.go
cni/pkg/nodeagent/informers_test.go
cni/pkg/nodeagent/net.go
cni/pkg/nodeagent/pod_cache.go
cni/pkg/nodeagent/server.go
cni/pkg/util/podutil.go

Manual cherry of https://github.com/istio/istio/pull/51321
Fixes https://github.com/istio/istio/issues/51337

[release-1.22] Fix bug with initial snapshot create

---

cni/pkg/nodeagent/informers.go

Attempting to delete stuff we haven't added is strictly safe, but we should be able to be more targeted, and this reduces log spam/potentially confusing log messages.

`istio-cni` - fix a TODO around removal

---

pilot/docker/Dockerfile.proxyv2
pilot/docker/Dockerfile.ztunnel

update deps for 1.21.3

---

pilot/cmd/pilot-agent/options/agent.go
pkg/envoy/proxy.go
pkg/istio-agent/agent.go

remove unused dual option in agent

---

istioctl/cmd/root.go
istioctl/pkg/waypoint/waypoint.go
pkg/test/framework/components/ambient/waypoint.go
tests/integration/ambient/baseline_test.go
tests/integration/ambient/waypoint_test.go

This mirrors `istioctl ztunnel-config` which is also promoted in 1.23

istioctl: promote `istioctl x waypoint`

---

cni/pkg/nodeagent/informers.go

Few cosmetic (but useful) fixes spun out of comments on https://github.com/istio/istio/pull/51429 - no logical changes, just trying to make the logic there a bit less confusing.

istio-cni: cosmetic + comment fixups (no logical changes)

---

.github/dependabot.yml

dependabot: add release-notes-none label

---

pilot/pkg/features/telemetry.go

part of https://github.com/istio/istio/issues/50808

cleanup unused flags

---

pkg/kube/krt/informer.go

krt: add informer dump

---

pilot/pkg/features/telemetry.go
pilot/pkg/model/telemetry_logging.go
releasenotes/notes/otel-builtin-labels.yaml

this has been default false for a long time, no report about this, use should not depend on this, let's remove it.

remove ENABLE_OTEL_BUILTIN_RESOURCE_LABELS

---

pkg/kube/namespace/filter.go
releasenotes/notes/ns-filter.yaml
tests/integration/ambient/baseline_test.go
tests/integration/ambient/main_test.go
tests/integration/iop-ambient-test-defaults.yaml

Went through all the skips and audited if we needed to skip them --
often they were just stale

Improve ambient e2e coverage

---

pilot/pkg/config/kube/crdclient/client.go
pkg/kube/kclient/client_test.go
pkg/kube/namespace/filter.go
releasenotes/notes/ns-filter.yaml

(cherry picked from commit 71a1cafbc570665d7dd78655265a7b5637d8939a)

Fix discovery selectors and GC bug

---

tools/istio-iptables/pkg/builder/iptables_builder_impl.go
tools/istio-iptables/pkg/builder/iptables_builder_test.go
tools/istio-iptables/pkg/builder/testdata/append-insert-multi-restore.golden
tools/istio-iptables/pkg/builder/testdata/append-insert-multi.golden
tools/istio-iptables/pkg/builder/testdata/append-multi-restore.golden
tools/istio-iptables/pkg/builder/testdata/append-multi.golden
tools/istio-iptables/pkg/builder/testdata/append-single-restore.golden
tools/istio-iptables/pkg/builder/testdata/append-single.golden
tools/istio-iptables/pkg/builder/testdata/insert-multi-restore.golden
tools/istio-iptables/pkg/builder/testdata/insert-multi.golden
tools/istio-iptables/pkg/builder/testdata/insert-single-restore.golden
tools/istio-iptables/pkg/builder/testdata/insert-single.golden
tools/istio-iptables/pkg/builder/testdata/multi-rules-new-chain-v4-restore.golden
tools/istio-iptables/pkg/builder/testdata/multi-rules-new-chain-v4.golden
tools/istio-iptables/pkg/builder/testdata/multi-rules-new-chain-v6-restore.golden
tools/istio-iptables/pkg/builder/testdata/multi-rules-new-chain-v6.golden

Fixes #51491
I also fixed some comments/error messages  in the existing tests

Add consistent table order in iptables-restore input and expand builder test coverage

---

tests/integration/ambient/baseline_test.go
tests/integration/ambient/main_test.go

Broken in https://github.com/istio/istio/pull/51446. These manifested as
flaky tests so they were able to merge

Ambient: fix two broken tests

---

go.mod
go.sum
pilot/pkg/model/telemetry_logging.go
pilot/pkg/model/telemetry_logging_test.go
releasenotes/notes/otel-accesslog-formatter.yaml

OpenTelemetry access log support formatter

---

pkg/config/validation/validation.go
pkg/config/validation/virtualservice.go

Actually check they are valid values
ReqAuth -- this is a header *name* not a header *value*. Change check
accordingly

validation: improve header validation

---

cni/cmd/istio-cni/main.go
cni/pkg/cmd/root.go
cni/pkg/plugin/plugin.go

Currently if you set `--log_output_level=cni-plugin:debug` it is ignored

Fix plugin debug logging

---

pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go

Its nice to have "Class" be defaults but allow overrides at per-gw level
for things, since making new classes is challenging and error prone.

Allow setting bind mode at Gateway level instead of just class level

---

prow/release-commit.sh

There was a circular dep of pushing it the first time and getting the
ID. So now filling it in

Update ztunnel dashboard with real ID

---

pilot/pkg/model/destination_rule.go

We have resolved it in `setDestinationRules`

Remove duplicate resolve host name in destination rule

---

pilot/pkg/config/kube/crdclient/client.go
pkg/revisions/tag_watcher.go

fix issue https://github.com/istio/istio/issues/51558

fix type assertion panic for controllers.Object

---

istioctl/pkg/writer/ztunnel/configdump/api.go
pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
releasenotes/notes/ambient-ns-policy.yaml

ambient: filter cross-namespace authz policies (#51557)

---

pkg/config/analysis/analyzers/analyzers_test.go
pkg/config/analysis/analyzers/destinationrule/ca-certificates.go
pkg/config/analysis/analyzers/testdata/destinationrule-simple-destination-credentialname-selector.yaml
pkg/config/analysis/analyzers/testdata/destinationrule-simple-destination-credentialname.yaml
pkg/config/analysis/analyzers/testdata/destinationrule-simple-port-credentialname-selector.yaml
pkg/config/analysis/analyzers/testdata/destinationrule-simple-port-credentialname.yaml
releasenotes/notes/51568.yaml

Fix false positives for IST0128 and IST0129

---

cni/pkg/log/uds.go
cni/pkg/log/uds_test.go

[release-1.22] cni: fix k/v pairs in UDS logging from plugin

---

pilot/pkg/serviceregistry/kube/controller/endpointslice.go

Do not import v1beta1 API just for a label

---

pkg/test/echo/server/instance.go
pkg/test/framework/components/echo/kube/templates/deployment.yaml

echo server: bind to multiple pod IPs

---

manifests/addons/gen.sh
samples/addons/kiali.yaml

At the request of Kiali maintainers

Bump Kiali to 1.86

---

pilot/pkg/model/context.go
pilot/pkg/model/gateway.go
pilot/pkg/model/gateway_test.go
pilot/pkg/xds/cds.go
releasenotes/notes/push-cds-on-auto-passthrough-gateway-change.yaml

This is a manual cherry-pick of #50757 and #50963. These commits must be merged together and additionally I had to adjust the unit test, because it did not compile.

[release-1.20] xds: push CDS on AUTO_PASSTHROUGH Gateway change

---

pkg/bootstrap/config.go
pkg/bootstrap/config_test.go
pkg/bootstrap/testdata/all_golden.json
pkg/bootstrap/testdata/auth_golden.json
pkg/bootstrap/testdata/authsds_golden.json
pkg/bootstrap/testdata/default_golden.json
pkg/bootstrap/testdata/deferred_cluster_creation_golden.json
pkg/bootstrap/testdata/lrs_golden.json
pkg/bootstrap/testdata/metrics_no_statsd_golden.json
pkg/bootstrap/testdata/running_golden.json
pkg/bootstrap/testdata/runningsds_golden.json
pkg/bootstrap/testdata/stats_compression_brotli_golden.json
pkg/bootstrap/testdata/stats_compression_gzip_golden.json
pkg/bootstrap/testdata/stats_compression_unknown_golden.json
pkg/bootstrap/testdata/stats_compression_zstd_golden.json
pkg/bootstrap/testdata/stats_inclusion_golden.json
pkg/bootstrap/testdata/tracing_datadog_golden.json
pkg/bootstrap/testdata/tracing_lightstep_golden.json
pkg/bootstrap/testdata/tracing_none_golden.json
pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
pkg/bootstrap/testdata/tracing_tls_golden.json
pkg/bootstrap/testdata/tracing_zipkin_golden.json
pkg/bootstrap/testdata/xdsproxy_golden.json
releasenotes/notes/51640.yaml

Fix #51639
Signed-off-by: spacewander <spacewanderlzx@gmail.com>

fix statsMatcher's regex which didn't match route's stat_prefix

---

pilot/pkg/model/context.go
pilot/pkg/model/gateway.go
pilot/pkg/model/gateway_test.go
pilot/pkg/xds/cds.go
releasenotes/notes/push-cds-on-auto-passthrough-gateway-change.yaml

Follow-up to https://github.com/istio/istio/pull/51644.

[release-1.21] xds: push CDS on AUTO_PASSTHROUGH Gateway change

---

pilot/pkg/features/experimental.go
pilot/pkg/networking/core/gateway_test.go
pilot/pkg/networking/core/httproute_test.go
pilot/pkg/networking/core/listener_builder.go
pilot/pkg/networking/grpcgen/grpcgen_test.go
pilot/pkg/networking/util/util.go
pilot/pkg/networking/util/util_test.go

only add StatefulSession on RDS when PersistentSessionFilter is enabled

---

releasenotes/notes/50781.yaml

spot a release note pretending to be from the future

---

pilot/pkg/model/service.go
pkg/dns/server/name_table.go
pkg/dns/server/name_table_test.go

Fixes https://github.com/istio/istio/issues/51608

Fix sidecar DNS proxying with dual stack

---

manifests/charts/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml
manifests/charts/istiod-remote/templates/istiod-injector-configmap.yaml
operator/pkg/util/merge_iop.go
pkg/kube/inject/testdata/inputs/custom-template.yaml.40.values.gen.yaml
pkg/kube/inject/testdata/inputs/default.values.gen.yaml
pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.0.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.1.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.10.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.12.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.13.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.14.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.17.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.3.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.4.values.gen.yaml
pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.values.gen.yaml
pkg/kube/inject/testdata/inputs/merge-probers.yaml.43.values.gen.yaml
pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.34.values.gen.yaml
pkg/kube/inject/testdata/inputs/status_params.yaml.8.values.gen.yaml
pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.values.gen.yaml

[release-1.20] manifests: fix gateways.securityContext not work

---

manifests/charts/istio-control/istio-discovery/templates/istiod-injector-configmap.yaml
manifests/charts/istiod-remote/templates/istiod-injector-configmap.yaml
operator/pkg/util/merge_iop.go
pkg/kube/inject/testdata/inputs/custom-template.yaml.40.values.gen.yaml
pkg/kube/inject/testdata/inputs/default.values.gen.yaml
pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.0.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.1.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.10.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.12.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.13.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.14.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.17.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.3.values.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.4.values.gen.yaml
pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.values.gen.yaml
pkg/kube/inject/testdata/inputs/merge-probers.yaml.43.values.gen.yaml
pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.34.values.gen.yaml
pkg/kube/inject/testdata/inputs/status_params.yaml.8.values.gen.yaml
pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.values.gen.yaml

[release-1.21] manifests: fix gateways.securityContext not work

---

istio.deps
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go

[release-1.22] ambient: support explicit EndpointSlice endpoints

---

pkg/adsc/adsc.go

Cleanup adsc

---

cni/pkg/nodeagent/informers.go
cni/pkg/nodeagent/informers_test.go
cni/pkg/nodeagent/net.go
cni/pkg/nodeagent/net_test.go
pkg/kube/util.go
releasenotes/notes/51429.yaml

Fixes https://github.com/istio/istio/issues/51687
Manual backport of https://github.com/istio/istio/pull/51429

[release-1.22] Ambient CNI informer: K8S job pods must be handled uniquely

---

pilot/pkg/model/context.go

remove get node name from labels

---

cni/pkg/util/podutil.go

Fixes https://github.com/istio/istio/discussions/51701

ambient: do not attempt to enroll hostNetwork pods

---

pilot/pkg/model/telemetry_test.go

add a test to help understanding for #51697

telemetry: add a test to help understand

---

pilot/pkg/model/context.go
pilot/pkg/xds/ads.go

[release-1.22] Fix race

---

pilot/pkg/serviceregistry/aggregate/controller.go
pilot/pkg/serviceregistry/aggregate/controller_test.go
pkg/slices/slices.go
releasenotes/notes/serviceregistry-order.yaml

* add kubernetes registry infront of serviceentry
* add test
* address comments
* fix lint
* fix lint

[release-1.21] Add kubernetes registry in front of ServiceEntry (#51003)

---

cni/pkg/plugin/sidecar_iptables_linux.go

Notably, this makes IPv6 work with CNI

Fix CNI environmental detection

---

pkg/config/validation/validation_istiod.go

chore: don't create CEL Env everytime

---

cni/pkg/iptables/iptables_linux.go

Fixes issue in https://github.com/istio/istio/issues/51622#issuecomment-2188233310

cni: auto-detect partial IPv6 support

---

cni/pkg/nodeagent/fakes_test.go
cni/pkg/nodeagent/net.go
cni/pkg/nodeagent/net_test.go

Manual backport of https://github.com/istio/istio/pull/51796 (preempting bot, as I know it's not a clean merge)

[release-1.22] Make sure we always Take the netns, always remove the IP, and fence with more tests

---

pilot/pkg/networking/core/envoyfilter/listener_patch.go

I think that `listener.Name == ""` and `filterchain.Filters == nill` are enough to indicate that they are removed, and the removed flag  are not necessary.

cleanup envoyfilter remove flag

---

pilot/pkg/model/gateway.go
pilot/pkg/model/gateway_test.go
pilot/pkg/model/push_context.go
pilot/pkg/networking/core/gateway.go
pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/xds/ads.go
releasenotes/notes/51726.yaml
tests/integration/pilot/ingress_test.go

Fix https://github.com/istio/istio/issues/51833

[Release-1.22] Fixed when a router associated service created, the proxy.MergeGateways

---

pilot/pkg/autoregistration/controller.go
pilot/pkg/autoregistration/controller_test.go
releasenotes/notes/51800.yaml

Fixes https://github.com/istio/istio/issues/51800.

autoregistration: fix xdsNode locality bug

---

pilot/pkg/xds/debug.go

This is just helper for debugging issues

debug: add interface to expose direct ambient computed state

---

pilot/pkg/model/gateway.go
pilot/pkg/model/gateway_test.go
pilot/pkg/model/push_context.go
pilot/pkg/networking/core/v1alpha3/gateway.go
pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/xds/ads.go
releasenotes/notes/51726.yaml
tests/integration/pilot/ingress_test.go

Fix https://github.com/istio/istio/issues/51836

[release-1.21] Fixed when a router associated service created, the proxy.MergeGateways

---

prow/integ-suite-kind.sh

This change aims to fix IPv6 postsubmit jobs.

tests: fix kind-registry resolution in prow

---

pilot/pkg/features/experimental.go
pilot/pkg/model/push_context.go
pilot/pkg/model/push_context_test.go
releasenotes/notes/51898.yaml

remove optimized config rebuild

---

tests/integration/ambient/baseline_test.go

https://github.com/istio/proxy/pull/5653 is merged, so let us try testing this on ipv6 now

Test TestL7Telemetry on ipv6

---

pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pilot/pkg/serviceregistry/kube/controller/ambient/helpers.go
pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
pkg/kube/kclient/interfaces.go
pkg/kube/krt/collection.go
pkg/kube/krt/core.go
pkg/kube/krt/filter.go
pkg/kube/krt/index.go
pkg/kube/krt/index_test.go
pkg/kube/krt/informer.go
pkg/kube/krt/join.go
pkg/kube/krt/singleton.go
pkg/kube/krt/static.go

KRT side of https://github.com/istio/istio/pull/51576

Re-implement KRT indexes as native

---

pilot/pkg/model/context.go
pilot/pkg/model/sidecar_test.go
pilot/pkg/networking/core/listener.go
pilot/pkg/networking/core/listener_inbound.go
pilot/pkg/networking/core/listener_test.go

remove duplicate static listener conflict checks

---

pilot/pkg/xds/filters/filters.go

Fixes https://github.com/istio/istio/issues/51910

configure tls inspector initial buffer size

---

pkg/config/validation/validation.go

These should be validated like normal, but we missed adding any validation for them

validation: add a few missed duration validations

---

pilot/pkg/serviceregistry/kube/controller/controller_test.go

Fixes https://github.com/istio/istio/issues/51892
The issue is the namespaces are not fully synced so we get things out of order

Fix TestController_ServiceWithChangingDiscoveryNamespaces flake

---

pilot/pkg/xds/bench_test.go

Add benchmark for concurrent GET with xds cache
Fixes https://github.com/istio/istio/issues/40752.
As a followup, I have 2 experimental PRs to switch to caches that use less/no locks:
* https://github.com/istio/istio/compare/master...howardjohn:istio:exp/xds-cache-freelru?expand=1
* https://github.com/istio/istio/compare/master...howardjohn:istio:exp/xds-cache-otter?expand=1
```
name \ time/op       /tmp/old     /tmp/otter   /tmp/freelru
Cache/concurrent-16  27.8ms ± 4%   3.5ms ±15%    5.9ms ± 6%
```

Concurrent xds cache benchmark

---

pilot/pkg/networking/core/cluster_builder.go

Fixes https://github.com/istio/istio/issues/51929

disable cleanup for inbound original dst cluster

---

pkg/kube/inject/testdata/inject/cronjob.yaml
pkg/kube/inject/testdata/inject/cronjob.yaml.injected
tests/fuzz/testdata/inject/fuzz_into_resource_file.dict

Remove deprecated cronjob api batch/v2alpha1

remove deprecated cronjob api batch/v2alpha1

---

pilot/pkg/networking/core/route/retry/retry_test.go
pkg/config/validation/validation.go
releasenotes/notes/reset-before-request.yaml
tests/integration/pilot/common/routing.go

Add validations and tests for reset-before-request retry policy envoyproxy/envoy#35074

Retry reset before request integration

---

pilot/pkg/model/context.go
pilot/pkg/networking/core/route/route.go

rename function to match its behaviour

---

pilot/pkg/xds/workload.go
pilot/pkg/xds/workload_test.go

[release-1.22] ambient: fix accidental deletion on NOP PA change

---

tests/integration/security/cacert_rotation/main_test.go

reenable cacert rotation test

---

prow/release-commit.sh

Need one more RB sha to publish one of the charts we have said we want to publish for 1.23

Automated branching for 1.23 missed https://github.com/istio/release-builder/tree/c4b2830c95b537e3a70b1b5c83b529ab3eb2d3ae

---

bin/update_deps.sh
bin/update_ztunnel.sh
cni/test/install_k8s_test.go
istio.deps
prow/release-commit.sh

run update-deps to update shas

[release-1.23] Update master to release-1.23 plus update-deps

---

pilot/pkg/serviceregistry/serviceentry/conversion.go
pilot/pkg/serviceregistry/serviceentry/ip_autoallocation.go

adds consuming v2 autoallocated IPs from service entry status during conversion of the service entry
**reviewer note** this presently contains a version of https://github.com/istio/istio/pull/52095 which will be removed once that review is completed. I believe you can basically ignore the changes in pilot/pkg/controllers/ipallocate/ipallocate.go as a result. Sorry for the hassle.

xds gen with autoallocated ip v2

---

istio.deps

Rebased after changes in #52126, replaces #52131

Automator: update ztunnel@release-1.23 in istio/istio@release-1.23

---

pilot/pkg/controllers/ipallocate/ipallocate_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/services_test.go
pilot/pkg/serviceregistry/serviceentry/ip_autoallocation.go
pkg/config/constants/constants.go

aligns v2 autoallocate behavior with existing behavior

align v2 autoallocate behavior with existing behavior

---

pilot/pkg/features/pilot.go
pilot/pkg/networking/core/httproute.go
pilot/pkg/networking/core/route/route.go
pilot/pkg/networking/core/route/route_test.go
pilot/pkg/networking/util/util.go

Manual backport of https://github.com/istio/istio/pull/52055

[release-1.23] add default retry policy for inbound routes

---

pilot/pkg/serviceregistry/serviceentry/conversion.go
pilot/pkg/serviceregistry/serviceentry/ip_autoallocation.go

manual cherry-pick of #52125 to resolve merge conflict
fix: https://github.com/istio/istio/issues/52181

[release-1.23] xds gen with autoallocated ip v2

---

pilot/pkg/networking/core/httproute.go
pilot/pkg/networking/core/httproute_test.go
releasenotes/notes/52192.yaml

This is a follow-up to https://github.com/istio/istio/pull/51967.

networking: match multiple VIPs in HTTP route

---

pilot/pkg/model/endpointshards.go
pilot/pkg/model/service.go
pilot/pkg/serviceregistry/serviceregistry_test.go
releasenotes/notes/pilot-dupe-ip.yaml

[release-1.22] Fix missed EDS push when overlapping IPs are found between WEs

---

istioctl/pkg/tag/tag.go
istioctl/pkg/util/constants.go

istioctl: support yaml output format for tag list

istioctl: support yaml output format for tag list

---

pilot/pkg/controllers/ipallocate/ipallocate_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/services_test.go
pilot/pkg/serviceregistry/serviceentry/ip_autoallocation.go

manual cherry-pick of #52171
fixes #52175

[release-1.23]align v2 autoallocate behavior with existing behavior (#52171)

---

pilot/pkg/model/endpointshards.go
pilot/pkg/model/service.go
pilot/pkg/serviceregistry/serviceregistry_test.go
releasenotes/notes/pilot-dupe-ip.yaml

[release-1.23] Fix missed EDS push when overlapping IPs are found between WEs

---

pilot/pkg/serviceregistry/kube/controller/endpointslice_test.go

Part of https://github.com/istio/istio/issues/52107

Add basic unit tests for endpointslices

---

pilot/pkg/model/context.go
pilot/pkg/xds/ads.go
pilot/pkg/xds/debug.go
pilot/pkg/xds/statusgen.go

Fixes https://github.com/istio/istio/issues/51340
Without:
```
320 runs so far, 2 failures (99.38% pass rate). 967.566671ms avg, 1.226643055s max, 884.929565ms min
```
With this PR:
```
2100 runs so far, 0 failures (100.00% pass rate). 971.239798ms avg, 1.396573106s max, 872.21202ms min
```

Fix race in syncz

---

pilot/pkg/serviceregistry/serviceentry/controller.go
pilot/pkg/serviceregistry/serviceregistry_test.go

Similar to https://github.com/istio/istio/pull/51226 and #52189.
This case occurs when we have multiple SE selecting the same WEs. Today,
we are incorrectly setting the `{se} -> WEs for SE` to be `{se} -> WEs
for all SEs we have seen so far`.
This fix uses the correct set of instances (the ones from the specific
SE), and adds a unit test covering this case.
Obviously, as we have had 3 fixes in this area, this is a pervasive
issue. I want to extend this to either (or both) migrate to `krt` or to
introduce a controller fuzzing engine. Both of these are long term
efforts though, and would be tricky to backport.

pilot: fix multiple SEs selecting overlapping workload entries

---

pilot/pkg/model/service.go
pilot/pkg/serviceregistry/kube/controller/endpointslice.go
pilot/pkg/serviceregistry/kube/controller/endpointslice_test.go

Fix: prevent duplicate istioEndpoints generated

---

pilot/pkg/model/service.go
pilot/pkg/model/service_test.go
pilot/pkg/networking/core/listener.go
pilot/pkg/networking/core/tls.go
pilot/pkg/serviceregistry/serviceentry/conversion.go
pilot/pkg/serviceregistry/serviceentry/conversion_test.go
pilot/pkg/xds/eds_test.go
releasenotes/notes/51967.yaml
tests/integration/pilot/common/routing.go
tests/integration/pilot/common/traffic.go

This is a manual cherry-pick of #51967, because the automated [one](https://github.com/istio/istio/pull/52148) can't be merged due to a conflict.

[release-1.23] networking: match multiple VIPs in sidecar outbound listener

---

istioctl/pkg/writer/ztunnel/configdump/api.go
istioctl/pkg/writer/ztunnel/configdump/services.go
istioctl/pkg/writer/ztunnel/configdump/testdata/workloadsummary.txt
istioctl/pkg/writer/ztunnel/configdump/testdata/workloadsummary_default.txt
istioctl/pkg/writer/ztunnel/configdump/workload.go

* Support multiple IPs being shown for dual stack
* Support hostname waypoints (not currently used, yet)
* Add a few missing fields and omitempty some

istioctl: various ztunnel-config improvements

---

pilot/pkg/xds/delta.go
pilot/pkg/xds/delta_test.go
releasenotes/notes/delta-xds-stale.yaml

[release-1.22] pilot: fix treating spontaneous request as ACK

---

pilot/pkg/model/gateway.go

Fixes https://github.com/istio/istio/issues/52311
Since this is just avoiding a log, I don't really know how to test
this... obviously I manually verified. The behavior aside from logs is
unchanged here.

Fix spurious logs when using `builtin://`

---

cni/pkg/nodeagent/server.go

Follow-on from https://github.com/istio/istio/pull/52320/files/e12db068d33674d333193fcaf468f437348ec264#r1690613692

Aggregate pod removal errors at both levels, so everything is best-effort

---

cni/pkg/nodeagent/cni-watcher_test.go
cni/pkg/nodeagent/informers_test.go
cni/pkg/nodeagent/net.go
cni/pkg/nodeagent/net_test.go
cni/pkg/nodeagent/server.go
cni/pkg/nodeagent/server_test.go
releasenotes/notes/52320.yaml

Manual backport of https://github.com/istio/istio/pull/52320
Fixes https://github.com/istio/istio/issues/52328

[release-1.22] Do not add pod to ipset if we have a "partial failure" adding to the dataplane.

---

pilot/pkg/model/service.go
pilot/pkg/model/service_test.go
pilot/pkg/networking/core/listener.go
pilot/pkg/networking/core/tls.go
pilot/pkg/serviceregistry/serviceentry/controller.go
pilot/pkg/serviceregistry/serviceentry/controller_test.go
pilot/pkg/serviceregistry/serviceentry/conversion.go
pilot/pkg/serviceregistry/serviceentry/conversion_test.go
pilot/pkg/serviceregistry/serviceentry/store_test.go
pilot/pkg/xds/eds_test.go
releasenotes/notes/51967.yaml
tests/integration/pilot/common/routing.go
tests/integration/pilot/common/traffic.go
tests/integration/pilot/dns_auto_allocation_test.go

This PR is a manual cherry-pick of #51967 and #52147.
Fixes #51747.

[release-1.22] networking: match multiple VIPs in sidecar outbound listener

---

pilot/pkg/config/kube/crdclient/client.go
pkg/revisions/tag_watcher.go

Manual cherry-pick of https://github.com/istio/istio/pull/51580, fixes https://github.com/istio/istio/issues/52341

[release-1.21] fix type assertion panic for controllers.Object

---

pkg/bootstrap/platform/azure.go
pkg/bootstrap/platform/azure_test.go

For https://github.com/istio/istio/discussions/52369
1. avoid unmarshall issue when `169.254.169.254` is not accessable.
2. change log level

less noisy log for azure

---

prow/lib.sh

correct DOCKER_ARCHITECTURES on m1

---

cni/pkg/nodeagent/ztunnelserver.go

During development where i have had protocol mismatches in ztunnel, I
have crashed my machine many times from this infinite loop. Add some
safe guards here. Its always a good idea to not allow unbounded loops
that spin goroutines.

Add safegaurd into ZDS

---

pkg/kube/kclient/client_test.go
pkg/kube/namespace/filter.go
releasenotes/notes/namespace-filter-deadlock.yaml

[release-1.22] Fix a deadlock when using `discoverySelectors`

---

tests/integration/helm/util.go

This speeds up tests after helm by ~30s. This is currently breaking postsubmit due to a recent change
So the old test order: [ helm test that left broken state, a test that runs uninstall --purge and wipes the entire clsuter state, some random test]
New test order: [ helm test that left broken state, some random test]
So before we would timeout
fixes https://github.com/istio/istio/issues/52417

Cleanup helm tests fully [fixes postsubmit]

---

pkg/kube/util.go
pkg/kube/util_test.go

Remove deadcode for pkg/kube

---

security/pkg/server/ca/server.go

Small bug from my last PR #52316

Wrong expiration times

---

pilot/pkg/networking/core/cluster_tls.go
pilot/pkg/networking/core/cluster_tls_test.go
pilot/pkg/networking/core/cluster_waypoint.go
releasenotes/notes/backend-tls.yaml
tests/integration/ambient/baseline_test.go

Fixes https://github.com/istio/istio/issues/52396 which was reported by
a user.
This makes the fix, adds unit tests, and adds e2e tests

ambient: support clients sending TLS

---

security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go
security/pkg/server/ca/authenticate/kubeauth/kube_jwt_test.go

cleanup after https://github.com/istio/istio/pull/49520Drop support for legacy first-party-jwt
/cc @howardjohn

remove unneeded func isAllowedKubernetesAudience

---

security/pkg/k8s/configutil.go

https://github.com/istio/istio/pull/43870 changed it but forget to update the comment.

Fix typo of InsertDataToConfigMap func description

---

pilot/pkg/features/telemetry.go
pilot/pkg/networking/core/cluster_builder.go
pilot/pkg/networking/core/cluster_builder_test.go
pilot/pkg/networking/core/cluster_test.go
pilot/pkg/networking/core/cluster_waypoint.go
pilot/pkg/networking/core/gateway.go
pilot/pkg/networking/core/listener.go
pilot/pkg/networking/core/listener_inbound.go
pilot/pkg/networking/grpcgen/cds.go
pilot/pkg/networking/util/util.go

[release-1.23] respect cluster statname pattern if provided

---

releasenotes/notes/dual-stack-alpha.yaml

Add release notes for dual-stack support promotion

---

pilot/pkg/networking/core/listener_waypoint.go

See https://github.com/istio/istio/issues/52554

Bind waypoint HBONE listener to dual stack

---

pilot/pkg/model/fuzz_test.go
pkg/fuzz/util.go
pkg/fuzz/util_test.go

Add MutateStruct function for fuzz deepcopy testing

Add MutateStruct function for fuzz test

---

pilot/pkg/model/fuzz_test.go
pkg/fuzz/util.go
pkg/fuzz/util_test.go

1. fix mutate: support circular data structure 
2. update the Demo's field name and cover struct private field test

fix mutate circular data structure and improve test case

---

pilot/pkg/model/service.go

fix deepcopy lost copy field

---

pkg/istio-agent/xds_proxy.go

Revert "Return nil if the upstream error is io.EOF in istio-agent"

---

cni/pkg/install/install.go

This is a UX improvement for users. Note this is not just logging, but also limiting to 1 loop per second. This ensures when we do trigger the condition, we don't spin at max CPU and log 100s of times per second

Auto detect cilium incompatibility during cni loop

---

go.mod
pkg/slices/slices.go
pkg/util/sets/set.go
pkg/util/smallset/smallset.go

replace pkg exp/constraints with cmp

---

releasenotes/notes/refactor-keycertbundle.yaml

Forgot how release notes worked

Fix typo and file naming

---

pkg/test/echo/server/forwarder/util.go

This can be used for testing Ztunnel's proxy support

Add support for proxy (based on env vars) to echo

---

tests/fuzz/oss_fuzz_build.sh

I am working on fixing the missing things in the build infrastructure that Istios fuzzing suite needs. I am at a stage where upstream changes fix the build for me locally, and with this PR I would like to test it out. 
Also remove the `FuzzReconcileStatuses` fuzzer which is no longer there.

fuzz: fix build

---

pilot/pkg/model/service.go
pilot/pkg/serviceregistry/serviceentry/controller.go
pilot/pkg/serviceregistry/serviceentry/controller_test.go
pilot/pkg/serviceregistry/serviceentry/conversion.go
pilot/pkg/serviceregistry/serviceentry/conversion_test.go
pilot/pkg/serviceregistry/serviceentry/store_test.go
releasenotes/notes/52612.yaml
tests/integration/ambient/main_test.go

respect DNS capture for proxy with auto-assigned addresses

---

pilot/pkg/model/service.go
tests/integration/ambient/main_test.go

adding ds support for autoallocated IP in getAllAddressesForProxy
fixes #52678

adding ds support for autoallocated IP in getAllAddressesForProxy

---

tests/integration/ambient/baseline_test.go

See https://github.com/istio/istio/issues/52719

Workaround calico issue in integration test

---

manifests/charts/base/files/profile-compatibility-version-1.21.yaml
manifests/charts/base/files/profile-compatibility-version-1.22.yaml
manifests/charts/default/files/profile-compatibility-version-1.21.yaml
manifests/charts/default/files/profile-compatibility-version-1.22.yaml
manifests/charts/gateway/files/profile-compatibility-version-1.21.yaml
manifests/charts/gateway/files/profile-compatibility-version-1.22.yaml
manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.21.yaml
manifests/charts/gateways/istio-egress/files/profile-compatibility-version-1.22.yaml
manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.21.yaml
manifests/charts/gateways/istio-ingress/files/profile-compatibility-version-1.22.yaml
manifests/charts/istio-cni/files/profile-compatibility-version-1.21.yaml
manifests/charts/istio-cni/files/profile-compatibility-version-1.22.yaml
manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.21.yaml
manifests/charts/istio-control/istio-discovery/files/profile-compatibility-version-1.22.yaml
manifests/charts/istio-operator/files/profile-compatibility-version-1.21.yaml
manifests/charts/istio-operator/files/profile-compatibility-version-1.22.yaml
manifests/charts/istiod-remote/files/profile-compatibility-version-1.21.yaml
manifests/charts/istiod-remote/files/profile-compatibility-version-1.22.yaml
manifests/charts/ztunnel/files/profile-compatibility-version-1.21.yaml
manifests/charts/ztunnel/files/profile-compatibility-version-1.22.yaml
manifests/helm-profiles/compatibility-version-1.21.yaml
manifests/helm-profiles/compatibility-version-1.22.yaml

Manual backport of https://github.com/istio/istio/pull/52655

fix compatibility version for stat regex (#52655)

---

pilot/pkg/config/kube/gateway/conversion.go
pilot/pkg/config/kube/gateway/deploymentcontroller.go
pilot/pkg/model/service.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/helpers.go
pilot/pkg/serviceregistry/kube/controller/ambient/services.go
pilot/pkg/serviceregistry/kube/controller/ambient/services_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
tests/integration/ambient/waypoint_test.go

Fixes https://github.com/istio/istio/issues/52318

Support hostname waypoints

---

pilot/pkg/model/fuzz_test.go

Just minor improvement, mostly future proofing for
https://github.com/istio/istio/issues/52446 if we do it

fuzzing: check our Equals() functions as well

---

pilot/pkg/model/service.go
pilot/pkg/model/service_test.go
pilot/pkg/networking/core/httproute_test.go
pilot/pkg/serviceregistry/serviceentry/controller.go
pilot/pkg/serviceregistry/serviceentry/controller_test.go
pilot/pkg/serviceregistry/serviceentry/conversion.go
pilot/pkg/serviceregistry/serviceentry/conversion_test.go
pilot/pkg/serviceregistry/serviceentry/store_test.go
pkg/dns/server/name_table_test.go
releasenotes/notes/52612.yaml
tests/integration/ambient/main_test.go
tests/integration/ambient/waypoint_test.go

- manual cherry pick https://github.com/istio/istio/pull/52680
- manual cherry pick https://github.com/istio/istio/pull/52612
- changes required to tests to allow passing ds ambient tests

[release-1.23] manual cherry-picks

---

pkg/bootstrap/testdata/all_golden.json
pkg/bootstrap/testdata/auth_golden.json
pkg/bootstrap/testdata/authsds_golden.json
pkg/bootstrap/testdata/default_golden.json
pkg/bootstrap/testdata/deferred_cluster_creation_golden.json
pkg/bootstrap/testdata/legacy_stats_tags_regex_golden.json
pkg/bootstrap/testdata/lrs_golden.json
pkg/bootstrap/testdata/metrics_no_statsd_golden.json
pkg/bootstrap/testdata/running_golden.json
pkg/bootstrap/testdata/runningsds_golden.json
pkg/bootstrap/testdata/stats_compression_brotli_golden.json
pkg/bootstrap/testdata/stats_compression_gzip_golden.json
pkg/bootstrap/testdata/stats_compression_unknown_golden.json
pkg/bootstrap/testdata/stats_compression_zstd_golden.json
pkg/bootstrap/testdata/stats_inclusion_golden.json
pkg/bootstrap/testdata/tracing_datadog_golden.json
pkg/bootstrap/testdata/tracing_lightstep_golden.json
pkg/bootstrap/testdata/tracing_none_golden.json
pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
pkg/bootstrap/testdata/tracing_tls_golden.json
pkg/bootstrap/testdata/tracing_zipkin_golden.json
pkg/bootstrap/testdata/xdsproxy_golden.json
releasenotes/notes/52743.yaml
tools/packaging/common/envoy_bootstrap.json

fix: https://github.com/istio/istio/issues/52731

extract watchdog metric

---

pkg/test/framework/components/echo/calloptions.go
pkg/test/framework/components/echo/kube/instance.go
tests/integration/ambient/baseline_test.go

Will fail until https://github.com/istio/istio/pull/52753 merges

Exercise and simplify DNS lookup in ambient tests

---

pilot/pkg/networking/core/cluster_builder.go

Fixes https://github.com/istio/istio/issues/50823

Fix upstream DNS for AWS ipv4 link local

---

pilot/pkg/networking/core/cluster_waypoint.go
releasenotes/notes/ambient-waypoint-portlevel.yaml
tests/integration/ambient/baseline_test.go

waypoint: Respect port level DR settings (#52747)

---

pilot/pkg/model/authentication.go
pilot/pkg/model/authorization.go
pilot/pkg/model/authorization_test.go
pilot/pkg/model/extensions_test.go
pilot/pkg/model/policyattachment.go
pilot/pkg/model/policyattachment_test.go
pilot/pkg/model/service.go
pilot/pkg/networking/core/listener_waypoint.go
pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
pilot/pkg/serviceregistry/serviceentry/controller_test.go
pilot/pkg/serviceregistry/serviceentry/conversion.go
pilot/pkg/serviceregistry/serviceentry/conversion_test.go
pilot/pkg/serviceregistry/serviceentry/store_test.go
tests/integration/ambient/baseline_test.go
tests/integration/ambient/waypoint_test.go

This adds a new test for cross-namespace waypoints with ServiceEntry, and introduces a number of fixes for them. Fixes are commented inline

Test and improve cross-namespace waypoint

---

pkg/config/analysis/analyzers/analyzers_test.go
pkg/config/analysis/analyzers/testdata/virtualservice_destinationhosts.yaml
pkg/config/analysis/analyzers/util/service_lookup.go
pkg/config/analysis/analyzers/virtualservice/destinationhosts.go

fixed https://github.com/istio/istio/issues/52806

fix analyze vs trriger panic when  spec.routes.destinations[].destination null

---

releasenotes/notes/52835.yaml
tools/istio-clean-iptables/pkg/cmd/cleanup.go
tools/istio-clean-iptables/pkg/cmd/testdata/dns-uid-gid.golden
tools/istio-clean-iptables/pkg/cmd/testdata/dns.golden
tools/istio-clean-iptables/pkg/cmd/testdata/empty.golden
tools/istio-clean-iptables/pkg/cmd/testdata/inbound-interception-mode.golden
tools/istio-clean-iptables/pkg/cmd/testdata/outbound-owner-groups-exclude.golden
tools/istio-clean-iptables/pkg/cmd/testdata/outbound-owner-groups.golden

Running `pilot-agent istio-clean-iptables` would leave the ISTIO_OUTPUT chain in existance that was added by https://github.com/istio/istio/pull/50915.
Tests covered by https://github.com/istio/istio/pull/52860
Fixes https://github.com/istio/istio/issues/52835
cc: @howardjohn

make sure we clean up the ISTIO_OUTPUT chain

---

pilot/pkg/xds/debug.go

add omit empty for labels in ads connections

---

pilot/pkg/bootstrap/server.go

Fixes https://github.com/istio/istio/issues/52803

pilot: fix to ensure we only use mesh config after it is initialized

---

pilot/pkg/model/telemetry.go
pilot/pkg/model/telemetry_logging_test.go
pilot/pkg/model/telemetry_test.go
releasenotes/notes/ambient-telemetry.yaml
tests/integration/ambient/baseline_test.go
tests/integration/telemetry/api/accesslogs_test.go

Fixes https://github.com/istio/istio/issues/52725. Additionally, applicableTelemetries was not properly selecting targetRef of service which is now fixed.

waypoint: add telemetry metrics configuration support and fix Telemetry selection

---

pilot/pkg/networking/core/listener_waypoint.go

Envoy's default connection balancing mode interacts somewhat poorly with HBONE specifically.
ztunnel uses HTTP/2 connect to tunnel N number (~100 max usually because of Envoy limitations) of regular connections over a single connection, and also uses connection pooling to parallelize several of these HBONE connections at once to the same dest.
This tends to produce undesirable distribution of these few, long-lived connections among available Envoy workers, given envoy's threading model - it is often quite easy to end up with multiple long-lived HBONE connections all on  one Envoy worker. 
Ex with an Envoy waypoint under loadgen with `concurrency=2`, I got this:
```
listener.0.0.0.0_15008.worker_0.downstream_cx_total: 4 …
```

Use exact connection balancing for waypoint HBONE listeners

---

tools/bug-report/pkg/common/common.go

bug-report: include ambientz in debug output

---

istioctl/pkg/cli/context.go
istioctl/pkg/cli/option.go
releasenotes/notes/impersonate-flags-in-cli.yaml

This PR adds support for the impersonate flags used in kube client in the istioctl. 
Related issue https://github.com/istio/istio/issues/52285

Support impersonate flags in istioctl

---

pilot/pkg/features/experimental.go
pilot/pkg/networking/core/cluster_test.go
pilot/pkg/networking/core/cluster_traffic_policy.go
pilot/pkg/networking/core/loadbalancer/loadbalancer.go
pilot/pkg/networking/core/loadbalancer/loadbalancer_test.go

Otherwise it will influence of LeastRequest policy even no locality setting applied
From https://github.com/istio/istio/issues/47804#issuecomment-2261523250

Apply local weight lb only when locality lb is enabled

---

releasenotes/notes/51987.yaml

Add a release note for operator API field removals

---

pilot/pkg/model/service.go
pilot/pkg/serviceregistry/serviceregistry_test.go

cherry-pick of #52963 
fixes: https://github.com/istio/istio/issues/52970

[release-1.23] fix endpoint comparision logic in UpdateServiceEndpoints

---

pilot/pkg/model/endpointshards.go
pilot/pkg/model/service.go
pilot/pkg/serviceregistry/serviceregistry_test.go

Fixes https://github.com/istio/istio/issues/53006
cherry-pick of #52963

[release-1.21] fix endpoint comparision logic in UpdateServiceEndpoints

---

tests/integration/pilot/testdata/external-forward-proxy-deployment.yaml
tests/integration/pilot/tunneling_test.go

Fixes: https://github.com/istio/istio/issues/53008

Fix TestTunnelingOutboundTraffic failure on OCP

---

tests/fuzz/oss_fuzz_build.sh

This is part of ongoing work to fix the OSS-Fuzz infrastructure that causes Istios build to break. It looks like I have fixed the main parts, and a single fuzzer breaks the build. 
For debugging purposes - i.e. to see if we can get this running on OSS-Fuzz - I suggest replacing the current loop with a list of the fuzzers covered in the loop with the broken fuzzer commented out. 
This works on my end.
@howardjohn

fix oss-fuzz build

---

tests/integration/pilot/gateway_test.go
tests/integration/pilot/istioctl_test.go

Fix tests when ingress gateway deployed in custom namespace

---

pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go

Fixes regression in https://github.com/istio/istio/pull/51945. This is
only on the master branch. Most of the change is adding test-

ambient: fix bug in waypoint attachment to SE endpoints

---

cni/pkg/nodeagent/cni-watcher_test.go
cni/pkg/nodeagent/informers_test.go
istioctl/pkg/multicluster/remote_secret_test.go
istioctl/pkg/tag/tag_test.go
pilot/pkg/xds/bench_test.go
pilot/pkg/xds/testdata/benchmarks/waypoint.yaml
pilot/test/xds/fake.go
pkg/config/schema/kubetypes/common.go
pkg/kube/client.go

Fixes https://github.com/istio/istio/issues/42315. A few structural
changes to the tet setup needed to make this work

xds benchmarks for waypoint

---

pilot/pkg/networking/core/tracing.go
pilot/pkg/networking/core/tracing_test.go
releasenotes/notes/53086.yaml

This PR aims to support customized endpoint of this feature request https://github.com/istio/istio/issues/53086.

Support zipkin collector endpoint configuration 

---

RELEASE_BRANCHES.md

Minor docs nit, and it doesn't seem to be common knowledge that there are 2 ways to do this.

Mention how to cherry-pick in the release branch guide

---

pilot/pkg/credentials/kube/secrets.go

This was the one missing spot for the filter

Apply missing secret filter for discoverySelector

---

cni/pkg/iptables/iptables.go
cni/pkg/iptables/iptables_e2e_test.go

This currently fails due to improper cleanup. Fix it and add a test to
cover it.

ambient: fix add+remove+add of iptables

---

tests/integration/ambient/baseline_test.go

Fixes https://github.com/istio/istio/issues/48386
Depends on https://github.com/istio/istio/pull/53063
Relates to https://github.com/istio/istio/issues/53064

Test ambient enroll/unenroll dynamically

---

pilot/pkg/config/kube/gateway/deploymentcontroller.go

Fixes https://github.com/istio/istio/issues/53200

gateway: sanitize listener names

---

pilot/pkg/networking/core/v1alpha3/listener_builder.go
pilot/pkg/networking/core/v1alpha3/listener_builder_test.go
pkg/bootstrap/instance_test.go
pkg/bootstrap/testdata/explicit_internal_address.proxycfg
pkg/bootstrap/testdata/explicit_internal_address_golden.json

Security fixes related to https://istio.io/latest/news/security/istio-security-2024-006/

[release-1.21] Backport fixes for 1.21.6

---

pilot/pkg/model/typed_xds_cache.go

hope this will save people's time, xref: https://github.com/istio/istio/pull/53199

address comment

---

istioctl/pkg/proxyconfig/proxyconfig.go

istioctl: Add missing options `ecds` to `proxyconfig` example

---

pkg/spiffe/spiffe_test.go

Add test cases for ParseIdentity function
- Added coverage for wrong separator scenarios

Add test cases for ParseIdentity function

---

pkg/kube/inject/inject.go
pkg/kube/inject/webhook.go

follow: https://github.com/istio/istio/pull/53106

inject log with labels

---

pilot/cmd/pilot-agent/options/agent.go
pilot/cmd/pilot-agent/options/options.go
pkg/istio-agent/agent.go

enable dns server on gateways

---

pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/xds/v3/model.go

Donot set statusQueue when disabled

---

pilot/pkg/networking/core/listener_builder.go
pilot/pkg/networking/core/listener_builder_test.go
pkg/bootstrap/instance_test.go
pkg/bootstrap/testdata/explicit_internal_address.proxycfg
pkg/bootstrap/testdata/explicit_internal_address_golden.json

Cherry-pick commits for 1.23.2

[release-1.23] cherry-pick 1.23 patch commits

---

pilot/pkg/networking/core/listener_builder.go
pilot/pkg/networking/core/listener_builder_test.go
pkg/bootstrap/instance_test.go
pkg/bootstrap/testdata/explicit_internal_address.proxycfg
pkg/bootstrap/testdata/explicit_internal_address_golden.json

Cherry-pick commits for 1.22.5

[release-1.22] cherry-pick 1.22 patch commit

---

pilot/pkg/bootstrap/configcontroller.go
pilot/pkg/features/ambient.go
pilot/pkg/leaderelection/leaderelection.go
pilot/pkg/model/notifier.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/queue.go
pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/queue_test.go
pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/fake.go
pkg/activenotifier/notifier.go
tests/integration/ambient/waypoint_test.go

Follow up to
https://github.com/istio/istio/pull/51945#issuecomment-2292479411, adds
leader election. See the comment there for details on why this is not
trivial.
for https://github.com/istio/istio/issues/52699

ambient status: add leader election

---

pilot/pkg/model/service.go
pilot/pkg/xds/endpoints/endpoint_builder.go

Saw 2.7% usage in a CPU profile. We can fast-path it.

Minor optimization around SupportsTunnel

---

pilot/pkg/model/addressmap.go

example https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/52985/unit-tests_istio/1840809938268459008

Partial revert of #53348 to fix race

---

pilot/pkg/model/service.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/conversion.go
pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/queue_test.go
releasenotes/notes/53091.yaml

AuthorizationPolicy status for waypoint attachment

---

tools/certs/README.md

…tificate management
closes #53409

docs: Add Makefile.k8s.mk Usage

---

pilot/pkg/xds/discovery.go

A common troubleshooting exercise is
https://github.com/istio/istio/wiki/Troubleshooting-Istio#high-istiod-cpu-usage--excessive-pushes.
However, because of the logs currently losing info, its hard to use in
some cases. This adds an off by default debug log to log the full info
on push.

Add debug logs for full push

---

architecture/tests/integration.md

docs: add architectural documentation describing integration test setup

---

samples/bookinfo/src/details/Dockerfile
samples/bookinfo/src/details/Gemfile.lock

* Bump to fix a CVE
* Actually use the lockfile

bookinfo: bump details lock and actually use it

---

pkg/file/fadvise_linux.go
pkg/file/fadvise_unspecified.go
pkg/file/file.go
releasenotes/notes/cni-memory.yaml

Fixes #53493; see that issue for lots of details

cni: optimize memory footprint

---

tests/integration/pilot/headers_test.go

add x-envoy-attempt-count to proxy headers

---

tests/integration/helm/upgrade/helm_upgrade_test.go
tests/integration/helm/upgrade/util.go
tests/integration/helm/util.go
tests/util/sanitycheck/sanity_check.go

Fixes #52701 Adding cross-version compat tests for ztunnel with CNI and Istiod

Add initial ztunnel cross-version test

---

pilot/pkg/networking/core/listener_waypoint.go
pilot/pkg/networking/core/route/route.go
releasenotes/notes/waypoint-mirror.yaml

Fixes https://github.com/istio/istio/issues/52713

Fix mirroring from waypoints

---

pilot/pkg/model/service.go
pilot/pkg/serviceregistry/kube/conversion.go
pkg/dns/server/name_table.go
releasenotes/notes/53572.yaml

Regression from https://github.com/istio/istio/pull/47379

do not send unhealthy endpoints in nds for headless

---

pilot/pkg/networking/core/extension_config_builder.go

fixes: https://github.com/istio/istio/issues/52272

chore: less noise

---

pilot/pkg/features/xds.go
pilot/pkg/networking/core/listener_builder.go
pilot/pkg/networking/core/listener_builder_test.go
pkg/bootstrap/instance_test.go
pkg/bootstrap/testdata/explicit_internal_address.proxycfg
pkg/bootstrap/testdata/explicit_internal_address_golden.json

https://github.com/istio/istio/pull/53254

Cherry-pick security fixes to master

---

docker/Dockerfile.distroless
go.mod
go.sum
prow/release-commit.sh

release-1.24 Automation step 1

---

pilot/pkg/model/authorization_test.go
pilot/pkg/model/service.go
pilot/pkg/networking/core/cluster_builder.go
pilot/pkg/networking/core/cluster_traffic_policy.go
pilot/pkg/networking/core/cluster_waypoint.go
pilot/pkg/networking/core/envoyfilter/rc_patch.go
pilot/pkg/networking/core/envoyfilter/rc_patch_test.go
pilot/pkg/security/authn/policy_applier_test.go
pilot/pkg/serviceregistry/serviceentry/controller.go
pilot/pkg/xds/debug.go
pilot/pkg/xds/endpoints/ep_filters.go
pkg/config/mesh/mesh.go
pkg/config/model.go
pkg/config/validation/agent/validation_test.go
pkg/config/validation/validation.go
pkg/dns/client/dns_test.go
pkg/istio-agent/agent.go
pkg/kube/inject/template.go
pkg/util/protomarshal/protomarshal.go

Fixes https://github.com/istio/istio/issues/53590
We apply the same to a lot of other places

Fix crash due to shared mutable state in EnvoyFilter

---

istioctl/pkg/analyze/analyze.go
istioctl/pkg/cli/context.go
releasenotes/notes/51934.yaml
tests/integration/pilot/analyze_test.go

Addressing pending comments from https://github.com/istio/istio/pull/53057
- https://github.com/istio/istio/pull/53057#discussion_r1809136455
- https://github.com/istio/istio/pull/53057#discussion_r1809161132
@howardjohn @bleggett PTAL

Change istioctl analyze --remote-cluster-context flag to --remote-contexts

---

pilot/pkg/features/pilot.go
pilot/pkg/networking/core/cluster_builder.go
pilot/pkg/networking/core/cluster_builder_test.go
releasenotes/notes/52877.yaml

#52877
I know we said to put it within a feature flag, but we can do the same thing by setting the env var to 0.
- [ x] Performance and Scalability

DNS jitter

---

prow/release-commit.sh

https://github.com/istio/istio/issues/53462

I think this might be all we need to OCI-publish dev build charts

---

istioctl/pkg/precheck/precheck.go

fix precheck output

---

pilot/pkg/model/config.go
pilot/pkg/xds/workload.go

pilot: minor deduplication of code

---

istioctl/pkg/proxyconfig/proxyconfig.go

improve the code format for istioctl x es output

improve the code format for istioctl x es output

---

istioctl/pkg/analyze/analyze.go

improve istioctl analyze output
Before the change:
After the change:

improve istioctl analyze output

---

pilot/pkg/networking/core/cluster_builder.go
pilot/pkg/networking/core/cluster_builder_test.go

#53623 merged before I could address all comments

Updated tests and docs for jitter

---

istioctl/pkg/analyze/analyze.go
releasenotes/notes/53582.yaml
tests/integration/pilot/analyze_test.go

The discussion: https://github.com/istio/istio/pull/53339#issuecomment-2391849332

Remove --recursive flags for istioctl analyze

---

pilot/pkg/serviceregistry/kube/controller/controller.go

Detected by unit test -race flag

multi-network: fix data race on service update

---

pkg/adsc/delta.go
pkg/adsc/delta_test.go
pkg/test/util/assert/assert.go

This mirrors the SotW one where we can show when we have actually gotten
everything we watched

Expose a `Synced` indication on Delta ADSC

---

pkg/dns/server/name_table_test.go

Unit test for https://github.com/istio/istio/pull/53572

add unit test for unhealthy endpoints in dns

---

tools/build-kind-image.sh

kind: document and recommend building kind from upstream releases

---

istioctl/pkg/analyze/analyze.go

The message code is not a piece of information that is easy for users to remember and understand. Adding relevant documentation will help improve the user experience.

Added documentation for message code for istioctl analyze

---

pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go

* Support Hostname network gateways instead of just IP
* Make all workload types use the same logic to determine waypoint
enablement
Both of these have a new test case associated

Minor fixes for niche cases of ambient controller

---

pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/network.go
pkg/adsc/adsc.go

prevent double lock

---

pilot/pkg/features/experimental.go

Improve clarity of the ISTIO_DELTA_XDS configuration description.
Originally tried changing the docs here: https://github.com/istio/istio.io/pull/15856

Clarify description of ISTIO_DELTA_XDS env variable in pilot-discovery docs

---

pilot/pkg/features/pilot.go
pilot/pkg/networking/core/cluster_builder.go
pilot/pkg/networking/core/cluster_builder_test.go
releasenotes/notes/52877.yaml

[release-1.24] Undo DNS jitter

---

pilot/pkg/networking/core/listener_waypoint.go

This is caused by an issue where we have the (almost) same code to translate
routes in 2 places, and we did not update one of them. This is a
terrible code smell and we should address it. However, given the release
is ~today, doing a small fix.
Manually tested

ambient: fix a bug preventing rewrite from working

---

tests/integration/telemetry/api/accesslogs_test.go
tests/integration/telemetry/api/setup_test.go
tests/integration/telemetry/api/testdata/accesslog/enable-filter-state-log.yaml

xref: https://github.com/istio/istio/issues/53769

add e2e for FILTER_STATE accesslog command

---

pilot/pkg/networking/core/cluster_builder.go
pkg/proto/merge/merge.go
pkg/proto/merge/merge_test.go
releasenotes/notes/53801.yaml

FIx https://github.com/istio/istio/issues/53800

Fix merging duration influence dst duration

---

tests/integration/telemetry/api/accesslogs_test.go
tests/integration/telemetry/api/setup_test.go

fix TestFilterStateAccessLog not working as expected

---

pkg/kube/inject/validate.go

Drop core dump annotation

---

pilot/pkg/features/pilot.go
pilot/pkg/networking/core/cluster_builder.go
pilot/pkg/networking/core/cluster_builder_test.go
releasenotes/notes/52877.yaml

This was originally reverted in #53760 because of a bug in envoy. Now that the bug is fixed https://github.com/envoyproxy/envoy/pull/36953, we should be gtg.

dns jitter (again)

---

samples/ratelimit/rate-limit-service.yaml

update envoyproxy ratelimit version, and disable DISABLE_STATS since it bring huge log

update envoyproxy ratelimit version

---

pkg/workloadapi/security/authorization.pb.go
pkg/workloadapi/security/authorization.proto

Fix https://github.com/istio/istio/issues/53938

fix authorization APIs are not consistent in istio and ztunnel

---

pilot/pkg/networking/core/listener_waypoint.go
pilot/pkg/networking/core/route/route.go
tests/integration/ambient/baseline_test.go

Service may be nil, so  refactor to prevent panics

Fix nil pointer when processing invalid waypoint backendrefs

---

pkg/log/options.go

I think the error message is not very accurate.

log: fix the wrong error message

---

pilot/pkg/xds/debug.go

```
istioctl x internal-debug "config_dump?types=wds&proxyID=sleep-668646db99-85x2m.sidecar"
```

pilot: fix `types=wds` not working in `/debug/config_dump`

---

go.mod
go.sum
tests/integration/pilot/testdata/gateway-api-crd.yaml

Fixes https://github.com/istio/istio/issues/53846

1.24: pick up fix for gateway API breaking change

---

cni/pkg/iptables/iptables.go

Change-Id: Id3b1f4aa9212688ae0906b1a8cbcbcb2d4dd9b9f
Follow-up of #53951 based on the [comments](https://github.com/istio/istio/pull/53951#discussion_r1848958143).
There is no need to backport this to 1.24.

Make all inpod delete rules optional

---

pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/policies.go

fix issue with getting targetRef/targetRefs in authz pol status for waypoint

fix authz pol waypoint status

---

pkg/adsc/delta.go

Right now we are just replacing the connection, never closing it. This
means we end up with infinite connections eventually

adsc: close connection when we reconnect

---

istioctl/pkg/proxyconfig/proxyconfig.go
releasenotes/notes/53974.yaml

fix https://github.com/istio/istio/issues/53931

istioctl: fix pc secret performance issue

---

pilot/pkg/networking/core/listener_test.go

only log the listener dump incase of failure

---

pilot/pkg/model/service.go
pilot/pkg/serviceregistry/kube/controller/ambient/services.go
pilot/pkg/serviceregistry/kube/controller/ambient/services_test.go
releasenotes/notes/53845-condition-for-ingress-waypoint.yaml

This PR resolves https://github.com/istio/istio/issues/53845 by adding new messages to represent a service binding to a waypoint proxy for ingress.

Represent service waypoint ingress binding in service condition

---

pilot/pkg/config/kube/crdclient/client.go
pilot/pkg/config/kube/gateway/deploymentcontroller.go
pilot/pkg/credentials/kube/secrets.go
pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
pkg/kube/client.go

call directly ObjectFilter

---

pilot/pkg/serviceregistry/kube/controller/controller.go
pilot/pkg/serviceregistry/kube/controller/pod.go
pilot/pkg/serviceregistry/kube/controller/pod_test.go

make pod label update event handle in order within a queue

---

pilot/pkg/model/authentication.go
pilot/pkg/model/authentication_test.go
pilot/pkg/xds/waypoint_test.go
releasenotes/notes/54071.yaml

fixes #54051 
adds searching svc namespace to enable cross-namespace reqauthn

Fix: Cross-namespace RequestAuthentication

---

pilot/pkg/networking/core/cluster_builder.go
pkg/proto/merge/merge.go
pkg/proto/merge/merge_test.go
releasenotes/notes/53801.yaml

[release-1.23] Fix merging duration influence dst duration

---

pilot/pkg/serviceregistry/kube/controller/network_test.go

Alternative to https://github.com/istio/istio/pull/54157
#53703 adds a second service creation, so introduces a race -- the 2nd event may come in later, but we assert after 1 event
Fixes https://github.com/istio/istio/issues/54156

Fix TestNetworkUpdateTriggers flake

---

release/downloadIstioCandidate.sh

Update install script to link guides for ambient

---

pkg/kube/kclient/client.go
pkg/kube/kclient/client_test.go

https://github.com/istio/istio/pull/54181 merged without a key change as well as no tests, this adds those

make NewDelayedInformer call registered type codepath and add tests

---

tests/integration/ambient/cni/main_test.go
tests/integration/ambient/cniupgrade/main_test.go
tests/integration/ambient/util.go
tests/integration/pilot/cni_race_test.go

I don't think this is will fix the recent CNI-related test flake yet but fixing in passing.

Remove some duplicated test fns, and explicitly wait for DS pods to ready up

---

pilot/pkg/model/telemetry_logging.go

Fixes https://github.com/istio/istio/issues/54219

use upstream_cluster_raw for json access log

---

pilot/pkg/model/telemetry_logging.go

Revert "[release-1.22] use upstream_cluster_raw for json access log"

---

pkg/istio-agent/health/health_check.go
pkg/istio-agent/health/health_probers.go
pkg/istio-agent/health/health_probers_test.go

New feature: GRPC probes based health checking for workload groups. 
Related API PR istio/api#3372
Related issue #53085

Support grpc probes for workload group health checks

---

pilot/pkg/config/kube/gateway/conditions.go
pilot/pkg/config/kube/gateway/conversion.go
pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
pilot/pkg/config/kube/gateway/testdata/invalid.yaml
pilot/pkg/features/experimental.go

Fixes https://github.com/istio/istio/issues/54163
Helps with https://istio.slack.com/archives/C01TBTKLA9Z/p1732287553156109
This adds error messages on unsupported protocols, with a helper to
guide users towards using the proper casing.

Gateway: better handling of invalid protocols

---

istioctl/pkg/proxyconfig/proxyconfig.go
releasenotes/notes/54292.yaml

`istioctl proxyconfig` other flags seems also have performance issue, related Issues: https://github.com/istio/istio/issues/53931

fix istioctl proxyconfig performance issue

---

pilot/pkg/serviceregistry/kube/controller/endpointslice.go

add comments to endpoint slice and remove additional loop

---

pilot/pkg/model/context.go
pilot/pkg/model/telemetry_logging.go
pilot/pkg/networking/core/route/route.go
pilot/pkg/networking/core/route/route_internal_test.go
pilot/pkg/networking/util/util.go

remove 1.23 version checks

---

pkg/kube/kclient/index.go
pkg/revisions/tag_watcher.go
pkg/revisions/tag_watcher_test.go
releasenotes/notes/54280.yaml

fix tagwatcher with revisions

---

pilot/pkg/config/kube/gateway/deploymentcontroller.go
pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
pilot/pkg/config/kube/gateway/testdata/deployment/istio-upgrade-to-1.24.yaml
releasenotes/notes/54145.yaml

Fix https://github.com/istio/istio/issues/54145

Fix patching deployment when upgrade to istio 1.24

---

pilot/pkg/model/authentication.go
pilot/pkg/model/authentication_test.go
pilot/pkg/model/authorization.go
pilot/pkg/model/authorization_test.go
pilot/pkg/model/config.go
pilot/pkg/model/extensions.go
pilot/pkg/model/policyattachment.go
pilot/pkg/model/policyattachment_test.go
pilot/pkg/model/push_context.go
pilot/pkg/networking/core/listener_waypoint.go
pilot/pkg/networking/core/networkfilter.go
pkg/slices/slices.go
tests/integration/ambient/wasm_test.go

Please provide a description of this PR:
https://github.com/istio/istio/issues/51288
Fix empty image pull secret in ambient mode when wasmplugin targetRefs are services.
This PR is same as #53781.
Apologies for the confusion caused by an accidental rebase in the previous PR. I’ve created a new one to resolve this.

fix empty imagePullSecret for service scope wasmplugin in ambient

---

pilot/pkg/config/kube/gateway/conversion.go
pilot/pkg/config/kube/gateway/testdata/http.yaml.golden
pilot/pkg/networking/core/route/route.go
releasenotes/notes/54357.yaml

Fixes https://github.com/istio/istio/issues/54357

fix mirror percentage calculation in gateway apis

---

pilot/pkg/networking/core/gateway.go

minor optimization in gateways

---

pilot/pkg/networking/core/gateway.go
pilot/pkg/networking/core/gateway_test.go
releasenotes/notes/49638.yaml

[release-1.24] fix mixed case host with tls redirect

---

pilot/pkg/bootstrap/servicecontroller.go
pilot/pkg/serviceregistry/kube/controller/multicluster.go
pilot/pkg/serviceregistry/kube/controller/multicluster_test.go

All of this is handled in other parts of the code now so this was dead

Cleanup deadcode in multicluster controller

---

pilot/pkg/model/service.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pilot/pkg/serviceregistry/kube/controller/ambient/services_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/conversion.go
pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/conversion_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/queue.go
pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/queue_test.go

Fixes https://github.com/istio/istio/issues/54356

ambient: make status writer not write when not needed

---

pilot/pkg/model/service.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/conversion.go
pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/conversion_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/queue.go
pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/queue_test.go

fixes https://github.com/istio/istio/issues/54452

ambient: make status writer not write when not needed (#54438)

---

pilot/pkg/serviceregistry/kube/controller/endpointslice.go

change log level to debug

---

pilot/pkg/xds/ads.go
pilot/pkg/xds/bench_test.go
pilot/pkg/xds/debug.go
pilot/pkg/xds/delta_test.go
pilot/pkg/xds/waypoint_test.go
pilot/pkg/xds/workload.go
pilot/pkg/xds/workload_test.go
pilot/test/xds/fake.go
pkg/kube/krt/collection.go

fixes https://github.com/istio/istio/issues/54467

debug: test and fix race conditions in debug endpoints (#54463)

---

istioctl/pkg/workload/workload.go
releasenotes/notes/54043.yaml

fix https://github.com/istio/istio/issues/54022

istioctl: support network parameter for workload group command

---

pilot/pkg/config/kube/gateway/conditions.go
pilot/pkg/networking/serviceentry/ip_autoallocation.go
pkg/file/file.go

removed unused const

---

pilot/pkg/model/push_context.go
pilot/pkg/model/service.go
pilot/pkg/networking/core/listener_waypoint.go
pilot/pkg/networking/core/waypoint.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pilot/pkg/serviceregistry/kube/controller/ambient/helpers.go
pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop.go
pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
pilot/pkg/xds/delta_test.go

Part of https://github.com/istio/istio/issues/54482

ambient: do not embedd types in WDS

---

pilot/pkg/model/extensions.go
pilot/pkg/model/extensions_test.go
pilot/pkg/networking/core/extension/wasmplugin.go
pilot/pkg/networking/core/extension/wasmplugin_test.go
pilot/pkg/networking/core/extension_config_builder.go
pkg/wasm/convert.go

fix: https://github.com/istio/istio/issues/53902

adopt envoy.extensions.wasm.v3.PluginConfig.fail_policy

---

pilot/pkg/serviceregistry/kube/controller/endpointslice.go
pilot/pkg/xds/cds.go
pilot/pkg/xds/ecds.go
pilot/pkg/xds/eds.go
pilot/pkg/xds/lds.go
pilot/pkg/xds/nds.go
pilot/pkg/xds/nds_test.go
pilot/pkg/xds/rds.go
pilot/pkg/xds/xdsgen.go

Unify Xds push needed checks in to a single place

unify xds push needed checks

---

pilot/pkg/xds/delta.go
pilot/pkg/xds/util_test.go
pkg/util/sets/set.go

This was caught by e2e tests but not unit tests. I fixed the bug and
added proper unit tests (we previously had this test for sotw but not
delta!)

delta xds: fix regression in pushing on unsubscribe

---

pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
pkg/maps/maps.go

Should fix the issues we're seeing on master

Sort portlevel mtls before converting

---

pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-port-mtls-strict-and-permissive-in.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-port-mtls-strict-and-permissive.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-permissive-namespace-strict-workload-ports-in.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-permissive-namespace-strict-workload-ports.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-unset-namespace-mixed-workload-ports-in.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-unset-namespace-mixed-workload-ports.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-port-mtls-strict-and-permissive-in.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-port-mtls-strict-and-permissive.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-unset-workload-port-mtls-strict-and-permissive-in.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-unset-workload-port-mtls-strict-and-permissive.yaml
releasenotes/notes/54146.yaml
tests/integration/ambient/baseline_test.go

[release-1.24] Fix Ambient Peer Authn flake (#54566)

---

cni/pkg/nodeagent/net.go
cni/pkg/nodeagent/server.go
cni/pkg/util/podutil.go

Mostly just wanna shrink https://github.com/istio/istio/pull/53906, this just does some tidies/reorgs of struct vs local funcs so `net.go/server.go` aren't such a mess to read from top to bottom, no behavioral changes

Mostly cosmetic tidies split out from #53906

---

pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-port-mtls-strict-and-permissive-in.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-port-mtls-strict-and-permissive.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-permissive-namespace-strict-workload-ports-in.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-permissive-namespace-strict-workload-ports.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-unset-namespace-mixed-workload-ports-in.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-unset-namespace-mixed-workload-ports.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-port-mtls-strict-and-permissive-in.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-port-mtls-strict-and-permissive.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-unset-workload-port-mtls-strict-and-permissive-in.yaml
pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-unset-workload-port-mtls-strict-and-permissive.yaml
releasenotes/notes/54146.yaml
tests/integration/ambient/baseline_test.go

[release-1.23] Fix Ambient Peer Authn flake (#54566)

---

pilot/pkg/features/telemetry.go
pilot/pkg/networking/core/gateway_test.go
pilot/pkg/xds/filters/filters.go
pilot/pkg/xds/filters/filters_test.go
releasenotes/notes/54000.yaml
tests/integration/base.yaml
tests/integration/telemetry/api/setup_test.go
tests/integration/telemetry/api/stats_test.go
tests/integration/telemetry/api/testdata/additional-labels.yaml

telemetry: support additional labels in metadata exchange

---

pilot/pkg/networking/core/cluster_builder.go
pilot/pkg/networking/core/cluster_cache.go
pilot/pkg/networking/core/listener_builder.go
releasenotes/notes/preserve-http1-header-case.yaml
tests/integration/pilot/preserve_http_header_case_test.go

Preserve HTTP 1 Header Case

---

pilot/pkg/model/telemetry.go
pilot/pkg/model/telemetry_logging_test.go
releasenotes/notes/54680.yaml

fixes: https://github.com/istio/istio/issues/54672

make accesslog order stable

---

tools/bug-report/pkg/common/common.go

Critical for ambient debugging

Include krtz in bug-report

---

pilot/pkg/networking/core/cluster_cache.go

Use preserveHeaderCase when calculating cache key

---

cni/pkg/nodeagent/informers_test.go

Fix flaky test introduced in https://github.com/istio/istio/pull/54729
ex: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/54715/unit-tests_istio/1882432338244145152

Fix unit test flake

---

releasenotes/notes/opencensus-removal.yaml

Should've been in #54803 but we have removed all of opencensus now

Add release note from #54803

---

tests/integration/ambient/util.go
tests/integration/pilot/cni_race_test.go

Fixes: https://github.com/istio/istio/issues/54580
During the TestCNIRaceRepair test execution, the test deletes the CNI configuration and restarts the deployment.
In Kind environment, the container at some point a "Failure" status with validation exit error code of 126.
The test checks for that error and continues.
But in Openshift, the container gets stuck in init container status forever and not sets any exit error code.
But in Openshift we are able to check the container stuck/failure reason by looking at the events of the container.
In Openshift, the container will show the following message in the events - "err in GetCNIConfigFromFile".
That could be our indication for the right error status and continue the test.
Set check of the …

Fix TestCNIRaceRepair test for Openshift

---

pilot/pkg/networking/core/accesslog.go

Due to a rebase this got dropped

Fix reset for hboneTerminationAccessLog

---

cni/README.md

Inspired by, but doesn't fix per se #54900

Add note to CNI readme to clarify supported OS

---

pilot/pkg/model/service.go
pilot/pkg/xds/endpoints/endpoint_builder.go
pilot/pkg/xds/waypoint_test.go

fixes https://github.com/istio/istio/issues/54818

[1.24] ambient: fix ingress-use-waypoint with ServiceEntry (#54765)

---

pilot/pkg/networking/core/cluster.go
pilot/pkg/networking/core/cluster_builder.go

See https://github.com/istio/istio/pull/54515 for more details

only dedupe envoy filter clusters

---

pkg/config/validation/validation.go

Update validation message to not reference deprecated feature

fix validation message suggesting deprecated feature

---

tests/integration/helm/upgrade/util.go

Fixes https://github.com/istio/istio/issues/50387

tests: use distroless for ambient helm upgrade test

---

pilot/pkg/networking/core/gateway.go
pilot/pkg/networking/core/listener_builder.go
releasenotes/notes/53402.yaml

https://github.com/istio/istio/issues/53402

Add upgradeNote for default change to internalAddressConfig

---

pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go

ref https://github.com/istio/istio/pull/55032

fix function name

---

tests/integration/ambient/main_test.go

...on https://github.com/istio/istio/issues/54645

Enable CNI logging temporarily to try and catch better context 

---

tests/integration/telemetry/api/stats_test.go

e2e: fix telemetry flaky test

---

pilot/pkg/config/file/store.go
pilot/pkg/config/kube/crdclient/types.gen.go
pkg/config/analysis/analyzers/all.go
pkg/config/analysis/analyzers/analyzers_test.go
pkg/config/analysis/analyzers/conditions/conditions.go
pkg/config/analysis/analyzers/testdata/condition-analyzer.yaml
pkg/config/analysis/msg/messages.gen.go
pkg/config/analysis/msg/messages.yaml
pkg/config/resource/instance.go
pkg/config/resource/serialization.go
pkg/config/schema/collections/collections.gen.go
pkg/config/schema/metadata.yaml
releasenotes/notes/55055.yaml

Create an analyzer to surface negative conditions found on resources

initial conditions analyzer

---

pkg/kube/krt/static.go

krt: register static collections into debugger

---

pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pilot/pkg/serviceregistry/kube/controller/ambient/nodes.go
pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go

Some examples of high CPU usage from frequent node changes: https://github.com/istio/istio/issues/54889#issuecomment-2619992584

ambient: optimize node utilization

---

cni/pkg/install/kubeconfig.go
cni/pkg/nodeagent/server.go
cni/pkg/plugin/plugin.go
pilot/pkg/model/jwks_resolver.go
pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
pilot/pkg/xds/sds.go
pkg/bootstrap/config.go
pkg/bootstrap/platform/gcp.go
tests/integration/pilot/common/routing.go
tests/integration/pilot/revisions/revision_tag_test.go
tools/istio-iptables/pkg/dependencies/implementation.go

Not sure how to get CI to detect this, these were found with GoLand
analysis

Fix log message with incorrect formatting

---

pilot/pkg/bootstrap/configcontroller.go
pilot/pkg/bootstrap/configcontroller_test.go

Implement CRL and SAN validation for certs in SIMPLE TLS mode.
Related #33143 
Follow up for #54427

mcp: implement CRL and SAN validation for certs

---

manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
manifests/charts/istiod-remote/files/gateway-injection-template.yaml
pkg/kube/inject/testdata/inject/gateway-with-default-container.yaml
pkg/kube/inject/testdata/inject/gateway-with-default-container.yaml.injected
pkg/kube/inject/testdata/inputs/custom-template.yaml.40.template.gen.yaml
pkg/kube/inject/testdata/inputs/default.template.gen.yaml
pkg/kube/inject/testdata/inputs/enable-core-dump.yaml.5.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.16.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.15.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.11.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.48.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello-openshift.yaml.47.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.20.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello-probes.yaml.18.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.10.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.14.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.17.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.9.template.gen.yaml
pkg/kube/inject/testdata/inputs/merge-probers.yaml.43.template.gen.yaml
pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.34.template.gen.yaml
pkg/kube/inject/testdata/inputs/status_params.yaml.8.template.gen.yaml
pkg/kube/inject/testdata/inputs/traffic-params.yaml.7.template.gen.yaml
releasenotes/notes/55152.yaml

fixes: https://github.com/istio/istio/pull/55162

[release-1.23] algin default container for gateway injection with sidecar

---

manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
pkg/kube/inject/testdata/inject/gateway-with-default-container.yaml
pkg/kube/inject/testdata/inject/gateway-with-default-container.yaml.injected
pkg/kube/inject/testdata/inputs/custom-template.yaml.43.template.gen.yaml
pkg/kube/inject/testdata/inputs/default.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.15.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.14.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.10.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.51.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello-openshift.yaml.50.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.19.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello-probes.yaml.17.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.11.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.16.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
pkg/kube/inject/testdata/inputs/hello.yaml.9.template.gen.yaml
pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.8.template.gen.yaml
pkg/kube/inject/testdata/inputs/merge-probers.yaml.46.template.gen.yaml
pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.33.template.gen.yaml
pkg/kube/inject/testdata/inputs/status_params.yaml.7.template.gen.yaml
pkg/kube/inject/testdata/inputs/traffic-params.yaml.6.template.gen.yaml
releasenotes/notes/55152.yaml

[release-1.24] algin default container for gateway injection with sidecar

---

tests/integration/ambient/main_test.go

Reverts https://github.com/istio/istio/pull/54827 and should close out https://github.com/istio/istio/issues/54645

Revert #54827 now that #54645 has been root-caused

---

istioctl/pkg/internaldebug/internal-debug.go

Improve istioctl x internal-debug syncz output

improve istioctl x internal-debug syncz output

---

pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
pkg/config/analysis/analyzers/analyzers_test.go
pkg/config/analysis/analyzers/conditions/conditions.go
pkg/config/analysis/analyzers/testdata/condition-analyzer.yaml
releasenotes/notes/55194.yaml

#55055 missed a state which is Accepted but PartiallyInvalid. Report this and add a test case to cover.

Refine conditions analyzer

---

cni/pkg/iptables/iptables.go

As a consequence of https://github.com/istio/istio/pull/54845, we need to wrap our `iptables` detection in
a netns jump, to ensure we are checking host versions.
https://github.com/istio/istio/issues/55215

Wrap iptables detect in namespace check

---

pilot/pkg/config/file/store.go
pilot/pkg/config/file/store_test.go

Fixes https://github.com/istio/istio/issues/55219

analyzer: fix unknown schema handling

---

pkg/kube/krt/collection.go
pkg/kube/krt/core.go
pkg/kube/krt/static.go
pkg/kube/krt/status.go
pkg/kube/krt/status_test.go

This is not yet in use as I broke the PR out, but this will be useful in
the ambient controller as well as the gateway-api one

krt: add a new Status collection helper

---

pilot/pkg/networking/core/route/retry/retry.go
pilot/pkg/networking/core/route/retry/retry_test.go
releasenotes/notes/retry-hosts.yaml

https://github.com/istio/api/pull/3432

implement retry host predicate api

---

pilot/pkg/networking/core/gateway_test.go
pilot/pkg/networking/core/listener_test.go

fixes: https://github.com/istio/istio/issues/53094

add test for listener filter timeout

---

cni/pkg/iptables/iptables_e2e_test.go
common/scripts/run.sh
tools/istio-iptables/pkg/capture/run_test.go

Manual cherry-pick of #55228
Closes #55248

[release-1.24] Fix execution of e2e iptables TCs in build-tools container (#55228)

---

istioctl/pkg/describe/describe.go
releasenotes/notes/55258.yaml

Fix https://github.com/istio/istio/issues/55243

support namespace parameter for istioctl experimental describe

---

pilot/pkg/model/proxy_view.go

pilot: fix type display error in idle

---

istioctl/pkg/waypoint/waypoint.go

improve `istioctl waypoint status` example format

improve istioctl waypoint status example format

---

istioctl/pkg/install/k8sversion/version.go
istioctl/pkg/install/k8sversion/version_test.go

Refs https://github.com/istio/istio/issues/54707

bump min k8s version to 1.29

---

pkg/kube/controllers/queue.go

Just helps with debugging a bit

controllers: pass name through to kubernetes queue

---

pkg/config/analysis/local/istiod_analyze.go

Fixes https://github.com/istio/istio/issues/55375

analyzer: stop unconditionally watching secrets/services/xyz

---

pilot/pkg/model/telemetry_logging.go
pilot/pkg/model/telemetry_logging_test.go
releasenotes/notes/54930.yaml

xref: https://github.com/istio/api/pull/3426
fixes: #54930

accesslog: support `omit_empty_values`

---

pkg/test/framework/components/cluster/clusters.go
tests/integration/telemetry/api/customize_metrics_test.go
tests/integration/telemetry/api/registry_setup_test.go
tests/integration/telemetry/api/setup_test.go

The PR contains the following cherry-picks:
- https://github.com/istio/istio/pull/54348
- https://github.com/istio/istio/pull/54392
- https://github.com/istio/istio/pull/54507

[release 1.24] telemetry tests fixes for Openshift

---

pilot/cmd/pilot-agent/options/statusserver.go
pilot/cmd/pilot-agent/status/server.go
pilot/cmd/pilot-agent/status/server_test.go
pkg/envoy/agent.go
pkg/istio-agent/agent.go

disable draining when quitquitquit is called

---

pilot/pkg/networking/core/listener_waypoint.go
releasenotes/notes/waypoint-tcproute.yaml
tests/integration/ambient/waypoint_test.go

Fixes https://github.com/istio/istio/issues/54119
~WIP until testing is added.~
Note: there is still no TLSRoute. Adding that is a bit more awkward, since today we make an HTTP and TCP filter chain but there is no TLS chain. Its certainly possible to do, just not something we are doing today. I think we would use the same TCP filter chain though

Implement TCPRoute for waypoints

---

pkg/kube/krt/index.go

krt: add debug to index collection

---

tests/integration/ambient/util.go
tests/integration/pilot/cni_race_test.go

This PR cherry-picks the following change - https://github.com/istio/istio/pull/54581
During the TestCNIRaceRepair test execution, the test deletes the CNI configuration and restarts the deployment.
In Kind environment, the container at some point gets a "Failure" status with validation exit error code of 126.
The test checks for that error and continues.
But in Openshift, the container gets stuck in init container status forever and not sets any exit error code.
But in Openshift we are able to check the container stuck/failure reason by looking at the events of the container.
In Openshift, the container will show the following message in the events - "err in GetCNIConfigFromFile".
That could be our indication for the right error status and …

Fix TestCNIRaceRepair test for Openshift (#54581)

---

pilot/pkg/config/kube/crd/conversion.go
pilot/pkg/config/kube/gateway/testdata/delegated.status.yaml.golden
pilot/pkg/config/kube/gateway/testdata/grpc.status.yaml.golden
pilot/pkg/config/kube/gateway/testdata/http.status.yaml.golden
pilot/pkg/config/kube/gateway/testdata/invalid.status.yaml.golden
pilot/pkg/config/kube/gateway/testdata/mesh.status.yaml.golden
pilot/pkg/config/kube/gateway/testdata/mismatch.status.yaml.golden
pilot/pkg/config/kube/gateway/testdata/multi-gateway.status.yaml.golden
pilot/pkg/config/kube/gateway/testdata/reference-policy-tls.status.yaml.golden
pilot/pkg/config/kube/gateway/testdata/route-binding.status.yaml.golden
pilot/pkg/config/kube/gateway/testdata/route-precedence.status.yaml.golden
pilot/pkg/config/kube/gateway/testdata/tcp.status.yaml.golden
pilot/pkg/config/kube/gateway/testdata/tls.status.yaml.golden
pilot/pkg/config/kube/gateway/testdata/valid-invalid-parent-ref.status.yaml.golden
pilot/pkg/config/kube/gateway/testdata/weighted.status.yaml.golden
pilot/pkg/config/kube/gateway/testdata/zero.status.yaml.golden

Only impacts tests in our current usage

Do not assign namespace to cluster scoped resources

---

pilot/pkg/networking/core/cluster_builder.go
pkg/test/echo/server/forwarder/grpc.go
releasenotes/notes/waypoint-auto-http2.yaml
tests/integration/ambient/baseline_test.go
tests/integration/ambient/waypoint_test.go

Fixes https://github.com/istio/istio/issues/55495

[1.25] waypoints: fix HTTP auto-protocol detection (#55421)

---

samples/kind-lb/setupkind.sh

samples: make setupkind work on mac

---

tools/istio-iptables/pkg/README.md

I grouped the information that was shared in the original PRs and put it into the README.
Closes #54794

Document reconciliation and idempotency logic for iptables wrapper

---

releasenotes/notes/55567.yaml

Fix a minor issue in releasenote by https://github.com/istio/istio/pull/55567

Fix a minor issue in releasenote

---

pkg/test/framework/components/istio/ingress.go
pkg/test/framework/components/zipkin/kube.go
pkg/test/kube/util.go
tests/integration/telemetry/tracing/otelcollector/tracing_test.go
tests/integration/telemetry/tracing/zipkin/client_tracing_test.go
tests/integration/telemetry/tracing/zipkin/server_tracing_test.go

This PR is a cherry-pick of the following PRs:
https://github.com/istio/istio/pull/55028
https://github.com/istio/istio/pull/55325

Release 1.24 fix test services reachability and flackiness

---

samples/kind-lb/setupkind.sh

sample: update metallb for kind-lb

sample: update metallb for kind-lb

---

pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
releasenotes/notes/ap-gateway-class-status.yml

Closes #55673
Refs #55667
Cherry-picking ea1c52093caef86b859045fa28dbda34037b0d5a onto release-1.25 since the automation failed.

Bug Fix - Add Handling of `GatewayClass` to `WaypointPolicyStatusCollection` (#55667)

---

pilot/pkg/bootstrap/server.go

Init trust bundle when multi root enabled

---

pilot/pkg/networking/core/route/route.go

nit: fix https://github.com/istio/istio/pull/55683/files#r2016749294
/cc @howardjohn

ensure inference route name list has all the parts

---

pkg/kube/krt/collection.go
pkg/kube/krt/debug.go
pkg/kube/krt/index.go
pkg/kube/krt/informer.go
pkg/kube/krt/singleton.go
pkg/kube/krt/static.go

This is useful to understand the state of the collection

krt debug: add synced status

---

pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
releasenotes/notes/ap-not-in-root-ns-gwclass-targetref.yml

Cherry-pick of 3808a9f5678d3cd63e900e6714b179eb5dc7d36d.

cherrypick commit -  authorizationpolicy gateway class targetRef root ns status

---

pilot/pkg/features/telemetry.go
pilot/pkg/networking/core/tracing.go
pkg/test/framework/components/zipkin/zipkin.go
releasenotes/notes/55676.yaml
tests/integration/telemetry/tracing/otelcollector/testdata/echo-gateway-tracing.yaml
tests/integration/telemetry/tracing/otelcollector/testdata/echo-gateway.yaml
tests/integration/telemetry/tracing/otelcollector/tracing_test.go
tests/integration/telemetry/tracing/tracing.go

fixes: https://github.com/istio/istio/issues/55637

tracing: support spawn upstream span for gateway

---

istioctl/pkg/waypoint/waypoint.go

istioctl: improve waypoint delete example

istioctl: improve waypoint delete example

---

istioctl/pkg/admin/istiodconfig.go
releasenotes/notes/55742.yaml

Fix https://github.com/istio/istio/issues/55741

fix istioctl admin log cannot modify the log level of ingress status

---

istioctl/pkg/precheck/precheck.go
pkg/config/analysis/msg/messages.gen.go
pkg/config/analysis/msg/messages.yaml

Part of https://github.com/istio/istio/issues/55718

istioctl: warn if using legacy Gateway API versions

---

istioctl/pkg/waypoint/waypoint.go
releasenotes/notes/55236.yaml

Fix https://github.com/istio/istio/issues/55235

fix istioctl waypoint delete gateway which is not waypoint

---

istioctl/pkg/writer/ztunnel/configdump/api.go
istioctl/pkg/writer/ztunnel/configdump/connections.go

Goes with https://github.com/istio/ztunnel/pull/1496

istioctl: include protocol in connection dump

---

architecture/ambient/peer-authentication.md

Small PR - Commit f8e65a004769b88a66fec27fbee6245dd99626b3 moved `ambientindex_test.go`. This PR adjusts sources to changes.

Update ambient test case

---

Makefile.core.mk

It's been dysfunctional for 4 years (see #29963), so should be safe to remove now.

remove obsolete gen-charts Make target

---

common/config/.golangci.yml
tools/golangci-override.yaml

wait https://github.com/istio/tools/pull/3180 and https://github.com/istio/common-files/pull/1167

bump to golangci-lint v2

---

istioctl/pkg/proxyconfig/proxyconfig.go
istioctl/pkg/writer/compare/sds/util.go
istioctl/pkg/writer/envoy/configdump/testdata/secret/istio/config_dump.json
istioctl/pkg/writer/envoy/configdump/testdata/secret/istio/output

https://github.com/istio/istio/pull/54292 broke by filtering from envoy
directly
https://github.com/istio/istio/pull/53650 additionally broke by not
rendering them if we do get them from envoy
Get this working again and add a test to help catch this.

istioctl: fix a regression(s) around warming resources

---

tools/build-base-images.sh

Ensure we do not accidentally pull in unexpected images

Add some sanity checks for distroless image

---

pkg/test/framework/test.go

This PR does a minor improvement in the logging message by printing `skipped` instead of printing `passed` in case test is skipped.

Improve test logging

---

pilot/pkg/model/gateway.go
pilot/pkg/model/gateway_test.go
releasenotes/notes/55859.yaml

Fixes https://github.com/istio/istio/issues/55623
Add `<secret name>-cacerts` to verify Certificate when mtls and referencegrants are satisfied.

pilot: fix verified certificate when mtls and referencegrants

---

pilot/pkg/model/push_context.go
releasenotes/notes/warn-deprecated-provider.yaml

xref: https://github.com/istio/istio/issues/54002

telemetry: add warn messge for Lightstep/Opencensus

---

pilot/pkg/networking/core/route/route.go
pilot/pkg/networking/util/util.go

remove 1.24 version checks

---

pilot/pkg/model/envoyfilter.go
pilot/pkg/model/push_context.go
pilot/pkg/networking/core/cluster.go
pilot/pkg/networking/core/httproute.go
pilot/pkg/networking/core/listener_builder.go
tests/integration/ambient/baseline_test.go

manually cherry-pick of https://github.com/istio/istio/pull/56114
fixes: #56127

[release-1.26] revert ambient: disable accidental EnvoyFilter implementation

---

pilot/pkg/networking/core/cluster.go

Fixes https://github.com/istio/istio/issues/55812

handle filtergatewayclusterconfig in delta

---

istioctl/pkg/dashboard/dashboard.go

improve istioctl dashboard example

improve istioctl dashboard example

---

pilot/pkg/features/experimental.go
pkg/bootstrap/config.go
pkg/bootstrap/option/instances.go
pkg/bootstrap/testdata/all_golden.json
pkg/bootstrap/testdata/ambient_golden.json
pkg/bootstrap/testdata/auth_golden.json
pkg/bootstrap/testdata/authsds_golden.json
pkg/bootstrap/testdata/default_golden.json
pkg/bootstrap/testdata/explicit_internal_address_golden.json
pkg/bootstrap/testdata/lrs_golden.json
pkg/bootstrap/testdata/metrics_no_statsd_golden.json
pkg/bootstrap/testdata/running_golden.json
pkg/bootstrap/testdata/runningsds_golden.json
pkg/bootstrap/testdata/stats_compression_brotli_golden.json
pkg/bootstrap/testdata/stats_compression_gzip_golden.json
pkg/bootstrap/testdata/stats_compression_unknown_golden.json
pkg/bootstrap/testdata/stats_compression_zstd_golden.json
pkg/bootstrap/testdata/stats_inclusion_golden.json
pkg/bootstrap/testdata/tracing_datadog_golden.json
pkg/bootstrap/testdata/tracing_lightstep_golden.json
pkg/bootstrap/testdata/tracing_none_golden.json
pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
pkg/bootstrap/testdata/tracing_tls_golden.json
pkg/bootstrap/testdata/tracing_zipkin_golden.json
pkg/bootstrap/testdata/xdsproxy_golden.json
tools/packaging/common/envoy_bootstrap.json

remove deferred stats creation flag

---

tools/packaging/common/envoy_bootstrap.json

https://github.com/istio/istio/pull/55206 remove this but missed to remove the check from bootstrap config

remove unnecessary check from bootstrap

---

pkg/config/analysis/analyzers/serviceentry/protocoladdresses.go
pkg/config/analysis/msg/messages.gen.go
pkg/config/analysis/msg/messages.yaml
releasenotes/notes/56083.yaml

resolved https://github.com/istio/istio/issues/56083

Check for PILOT_ENABLE_IP_AUTOALLOCATE for vip-less service entries.

---

pilot/pkg/features/experimental.go
pkg/bootstrap/config.go
pkg/bootstrap/option/instances.go
pkg/bootstrap/testdata/all_golden.json
pkg/bootstrap/testdata/ambient_golden.json
pkg/bootstrap/testdata/auth_golden.json
pkg/bootstrap/testdata/authsds_golden.json
pkg/bootstrap/testdata/default_golden.json
pkg/bootstrap/testdata/explicit_internal_address_golden.json
pkg/bootstrap/testdata/lrs_golden.json
pkg/bootstrap/testdata/metrics_no_statsd_golden.json
pkg/bootstrap/testdata/running_golden.json
pkg/bootstrap/testdata/runningsds_golden.json
pkg/bootstrap/testdata/stats_compression_brotli_golden.json
pkg/bootstrap/testdata/stats_compression_gzip_golden.json
pkg/bootstrap/testdata/stats_compression_unknown_golden.json
pkg/bootstrap/testdata/stats_compression_zstd_golden.json
pkg/bootstrap/testdata/stats_inclusion_golden.json
pkg/bootstrap/testdata/tracing_datadog_golden.json
pkg/bootstrap/testdata/tracing_lightstep_golden.json
pkg/bootstrap/testdata/tracing_none_golden.json
pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
pkg/bootstrap/testdata/tracing_tls_golden.json
pkg/bootstrap/testdata/tracing_zipkin_golden.json
pkg/bootstrap/testdata/xdsproxy_golden.json
tools/packaging/common/envoy_bootstrap.json

remove bypass overload manager check for static listeners

---

pkg/config/analysis/analyzers/all.go
pkg/config/analysis/analyzers/analyzers_test.go
pkg/config/analysis/analyzers/telemetry/providers.go

fix typo: Prodiver -> Provider

---

istioctl/pkg/waypoint/waypoint.go
releasenotes/notes/56454.yaml

Fix https://github.com/istio/istio/issues/56453

Support customizing the timeout of istioctl waypoint status

---

pkg/test/echo/cmd/client/client_test.go
pkg/test/echo/cmd/client/main.go

fixes https://github.com/istio/istio/issues/56400
/cc @howardjohn

support colon in header value

---

istioctl/pkg/admin/istiodconfig.go
releasenotes/notes/56500.yaml

Fix https://github.com/istio/istio/issues/56465

support displaying stack-trace-level for admin log

---

pilot/pkg/networking/core/envoyfilter/listener_patch.go
pilot/pkg/networking/core/envoyfilter/listener_patch_test.go
releasenotes/notes/envoyfilter-listenerfilter-merge.yaml

Xref: https://github.com/istio/istio/discussions/56446
this's ignored without any warn message, we'd better to support it for a consistent experience.
cc @ramaraochavali

implement merge option for LISTENER_FILTER in EnvoyFilter

---

pilot/pkg/model/envoyfilter.go
pilot/pkg/model/push_context.go
pilot/pkg/model/push_context_test.go
releasenotes/notes/56476.yaml
tests/integration/ambient/baseline_test.go

fixes: https://github.com/istio/istio/issues/56417
Part from https://github.com/istio/istio/pull/55149

fix EnvoyFilter targetRefs match

---

tests/integration/ambient/registry_setup_test.go

Fix the Ambient TestWasmPluginConfigurations test by making the "registry-redirector" config agnostic to any platform, including Openshift.
Kind environment require to keep the images in "kind-registry" to avoid DNS issues in IPv6.
This patch is similar to the fix patch in the telemetry api tests.
https://github.com/istio/istio/pull/54348

Fix Ambient TestWasmPluginConfigurations test for Openshift

---

manifests/charts/istio-control/istio-discovery/files/injection-template.yaml
pkg/kube/inject/inject_test.go
pkg/kube/inject/testdata/inject/hello-openshift-tproxy.yaml
pkg/kube/inject/testdata/inject/hello-openshift-tproxy.yaml.injected
releasenotes/notes/56577.yaml

This is a cherry-pick of https://github.com/istio/istio/pull/56577

[release-1.26] injection: fix sidecar template for TPROXY mode on OpenShift

---

security/pkg/pki/util/keycertbundle_test.go

Fixes: https://github.com/istio/istio/issues/56633

fix: fixes flaky 'invalid crl' test case

---

istioctl/pkg/describe/describe.go

- be specific `istioctl x describe` example
- remove duplicate code

Update istioctl x describe examples and remove dead code.

---

pilot/pkg/networking/core/cluster_builder.go
pilot/pkg/networking/core/cluster_test.go
pilot/pkg/xds/endpoints/endpoint_builder.go

cleanup and align tests based on https://github.com/istio/istio/pull/56623

cleanup and tests for inference-lb-policy

---

pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_serviceentry_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop_test.go
releasenotes/notes/56477.yaml

* In ambient index, filter configs by revision
* release notes
* Address feedback

[release-1.26] Ambient: In ambient index, filter configs by revision (#56477)

---

pilot/pkg/config/kube/clustertrustbundle/controller.go
pilot/pkg/config/kube/clustertrustbundle/controller_test.go
pilot/pkg/config/kube/crdclient/types.gen.go
pkg/config/schema/collections/collections.gen.go
pkg/config/schema/gvk/resources.gen.go
pkg/config/schema/gvr/resources.gen.go
pkg/config/schema/kubeclient/resources.gen.go
pkg/config/schema/kubetypes/resources.gen.go
pkg/config/schema/metadata.yaml
releasenotes/notes/56306.yaml

Fixes #56306
Support ClusterTrustBundle using the v1beta1 API

support ClusterTrustBundle to v1beta1 API

---

manifests/charts/istio-control/istio-discovery/files/gateway-injection-template.yaml
manifests/charts/istio-control/istio-discovery/files/grpc-agent.yaml
manifests/charts/istio-control/istio-discovery/files/injection-template.yaml

manually cherry pick of #56676
fix: #56745

[release-1.26] fix clusterTrustBundle template

---

releasenotes/notes/cluster-trust-bundle.yaml

add release notes for ClusterTrustBundle

---

prow/config/clustertrustbundles.yaml

follow up: https://github.com/istio/istio/pull/56727

enable v1beta1.clustertrustbundle

---

pkg/config/validation/validation_test.go

add additional tests for server tls settings

---

docker/Dockerfile.distroless
go.mod
go.sum
prow/release-commit.sh

step 1 branch cut 1.27 - update_deps

---

bin/update_deps.sh
bin/update_ztunnel.sh
common/Makefile.common.mk
istio.deps
prow/release-commit.sh

[release-1.27] update UPDATE_BRANCH and deps

---

pkg/test/framework/components/echo/deployment/builder.go
pkg/test/framework/components/echo/kube/deployment.go
pkg/test/framework/components/echo/kube/templates/deployment.yaml
pkg/test/framework/components/echo/kube/templates/service.yaml

This is a manual cherry-pick of #56799.

[release-1.24] tests: assign privileged SCC to tproxy SA on OpenShift

---

istioctl/pkg/describe/describe.go

Improve example format for  istioctl x describe
As a supplement to https://github.com/istio/istio/pull/56643

improve example format for  istioctl x describe

---

pkg/kube/inject/webhook.go

Fix for the failing CI: https://prow.istio.io/view/gs/istio-prow/logs/integ-assertion_istio_postsubmit/1943757841240166400

Use default node transform in webhook

---

pilot/pkg/networking/core/route/route.go

See https://github.com/envoyproxy/envoy/blob/9739df72fc281dadfd52a542e2ffdc5f8074122c/source/extensions/filters/http/ext_proc/config.cc#L50

fix ExtProcPerRoute

---

pilot/pkg/config/kube/gateway/deploymentcontroller_test.go

Fixes https://github.com/istio/istio/issues/57011

fix TestHandlerEnqueueFunction flake

---

pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_multicluster_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/multicluster.go
pilot/pkg/serviceregistry/kube/controller/ambient/networks.go
pilot/pkg/serviceregistry/kube/controller/ambient/services.go
pilot/pkg/serviceregistry/kube/controller/ambient/services_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
pkg/kube/krt/join.go
pkg/kube/krt/nestedjoin.go

Pre and post submit tests are flaky. This should partially fix it. See https://github.com/istio/istio/pull/57019 and #56926 for more

Nested join refactor

---

pilot/pkg/networking/core/gateway.go
pilot/pkg/networking/core/gateway_test.go
pilot/pkg/networking/core/listener.go
pilot/pkg/networking/core/listener_inbound.go
pilot/pkg/networking/core/listener_test.go
pilot/pkg/security/model/authentication.go
pilot/pkg/security/model/authentication_test.go
releasenotes/notes/56522.yaml

Fixes https://github.com/istio/istio/issues/56522

add support for external sds provider for serverTLSSettings

---

pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_multicluster_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
pilot/pkg/serviceregistry/util/xdsfake/updater.go
pkg/kube/krt/collection.go

Cherry pick for https://github.com/istio/istio/issues/56981

[release-1.27] remove flaky test

---

pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_multicluster_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/multicluster.go
pilot/pkg/serviceregistry/kube/controller/ambient/networks.go
pilot/pkg/serviceregistry/kube/controller/ambient/services.go
pilot/pkg/serviceregistry/kube/controller/ambient/services_test.go
pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
pkg/kube/krt/join.go
pkg/kube/krt/nestedjoin.go

cherry-pick for https://github.com/istio/istio/issues/57058

[release-1.27] Nested join refactor

---

pilot/pkg/config/kube/gateway/deploymentcontroller.go

Fixes https://github.com/istio/istio/issues/57105

xlistenerset: use delayed informer

---

pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_multicluster_test.go

these tests flaky too often, disable it now, tracked in https://github.com/istio/istio/issues/57126.
cc @Stevenjin8 @keithmattix

disable TestMulticlusterAmbientIndex

---

tests/binary/binaries_test.go

xref: https://github.com/istio/istio/pull/57111

fix TestBinarySizes for envoy

---

pkg/kube/krt/nestedjoin_test.go

xref: https://github.com/istio/istio/issues/57126

disable TestNestedJoinWithMergeSimpleCollection

---

security/pkg/pki/util/crypto.go
security/pkg/pki/util/crypto_test.go

propagate parse certificate errors

---

tests/binary/binaries_test.go

fixes: https://github.com/istio/istio/issues/57178

[release-1.26] fix TestBinarySizes for envoy

---

tests/binary/binaries_test.go

fixes: https://github.com/istio/istio/issues/57181

[release-1.26] fix TestBinarySizes for envoy arm64

---

releasenotes/notes/56626.yaml
tools/istio-iptables/pkg/capture/helper.go
tools/istio-iptables/pkg/capture/run_test.go

Manual backport of #56626 
Closes #57251

[release-1.25] Fix VerifyIptablesState ignoring IPv4 state in favor of the IPv6 one

---

pilot/pkg/serviceregistry/kube/controller/ambient/multicluster.go
pilot/pkg/serviceregistry/kube/controller/ambient/nodes.go

remove unused arg

---

istioctl/pkg/internaldebug/internal-debug.go
istioctl/pkg/internaldebug/internal-debug_test.go

Improve `istioctl x internal-debug syncz --all` output format

improve istioctl x internal-debug syncz --all output format

---

pkg/config/validation/validation.go
releasenotes/notes/27419.yaml
releasenotes/notes/retry-budget-validation.yaml

fix retry budget validation when only retry budget is set

---

pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop_test.go

Verify that updates for EDS occur for MultiNetwork as well.

Add test for Service bound waypoints with MultiNetwork

---

pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop_test.go

When enabling AmbientMultiNetwork, the service update can take time. Allow for the delay by switching to EventuallyEqual.
Improve the event assertions so we are aligned on the event sequencing.

Improve waypoint interop testing

---

pilot/pkg/networking/core/cluster_builder.go
pilot/pkg/networking/core/cluster_cache.go
pilot/pkg/networking/core/cluster_waypoint.go
pilot/pkg/networking/core/listener_builder.go
tests/integration/pilot/preserve_http_header_case_test.go

preserve header case for passthrough clusters

---

pkg/test/echo/parse.go
pkg/test/echo/response.go
pkg/test/framework/components/echo/common/deployment/external.go
pkg/test/framework/components/echo/common/ports/ports.go
pkg/test/framework/components/echo/kube/deployment.go
pkg/test/framework/components/echo/kube/templates/deployment.yaml
pkg/test/framework/components/echo/port.go
tests/integration/security/egress_gateway_origination_test.go

Building off #57335:
- adds mTLS to the echo framework
- adjust mTLS tests to assert client subject

add new mTLS echo capability to our testing

---

pkg/typemap/map.go

pkg/typemap: refactor to use reflect.TypeFor

---

pkg/revisions/tag_watcher.go
releasenotes/notes/56767.yaml
tests/integration/helm/install_test.go

Fixes https://github.com/istio/istio/issues/57498

[release-1.27] Add defaultRevision logic to tagWatcher (#57467)

---

pkg/revisions/tag_watcher.go
releasenotes/notes/56767.yaml
tests/integration/helm/install_test.go

[release-1.26] Add defaultRevision logic to tagWatcher (#57467)

---

pilot/pkg/networking/core/listener_builder.go
pilot/pkg/networking/core/listener_builder_test.go
releasenotes/notes/57528.yaml

not override http protocol options by preserve header case

---

pilot/pkg/networking/core/listener_builder.go
pilot/pkg/networking/core/listener_builder_test.go
releasenotes/notes/57528.yaml

[release-1.25] not override http protocol options by preserve header case

---

architecture/networking/pilot.md
cni/pkg/install/install.go
cni/pkg/iptables/iptables.go
pkg/zdsapi/zds.pb.go
pkg/zdsapi/zds.proto
samples/bookinfo/src/productpage/productpage.py
samples/sleep/README.md
security/pkg/nodeagent/cache/secretcache.go
security/pkg/nodeagent/caclient/providers/citadel/client.go
security/pkg/pki/error/error.go
security/pkg/pki/ra/common.go
security/pkg/pki/ra/k8s_ra_test.go
security/pkg/pki/testdata/multilevelpki/certs.sh
security/pkg/pki/util/san.go
security/pkg/pki/util/san_test.go
security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go
security/pkg/server/ca/authenticate/xfcc_authenticator.go

chore: fix typos

---

cni/README.md

Related to: https://github.com/istio/istio/issues/56484

Clarify ambient mode HOST_PROBE_SNAT_IP usage

---

pkg/config/analysis/local/istiod_analyze.go

The old analysis logic has its own object transforms and I guess it fell out of date for nodes. This changeset doesn't surface the failures locally, so I think this should be sufficient

Add assertions analysis test

---

tests/integration/ambient/cni/main_test.go
tests/integration/ambient/cnirepair/main_test.go
tests/integration/ambient/cniupgrade/main_test.go

Enable ambient tests previously skipped for dual-stack

---

pkg/istio-agent/xds_proxy_delta_test.go
pkg/istio-agent/xds_proxy_test.go
pkg/wasm/convert.go
pkg/wasm/convert_test.go

move stat prefix to constants
