- pilot/pkg/xds/endpoints/endpoint_builder.go
filterIstioEndpoint is called within generate(), which is shared by both CDS and EDS builder.
CDS uses, and it has already checked portname and labels. So here it moved these two checks to be only used by EDS. 
```
func (b *EndpointBuilder) FromServiceEndpoints() []*endpoint.LocalityLbEndpoints {
if b == nil {
return nil
}
svcEps := b.push.ServiceEndpointsByPort(b.service, b.port, b.subsetLabels)
// don't use the pre-computed endpoints for CDS to preserve previous behavior
return ExtractEnvoyEndpoints(b.generate(svcEps, true))
}
```
> move port name and labels check outside of filterIstioEndpoint

- pilot/cmd/pilot-agent/app/cmd.go
- pilot/cmd/pilot-agent/app/fds.go
- pilot/cmd/pilot-agent/app/fds_unix.go
When using distroless istio images, since there is not bash it always log a warning about "failed running ulimit command: ".
This PR avoid using bash, instead using golang to get the fd limit directly in unix systems.
> fix warnings getting fd limit in distroless

- pilot/cmd/pilot-agent/app/cmd.go
- pilot/cmd/pilot-agent/app/fds.go
- pilot/cmd/pilot-agent/app/fds_unix.go
- pkg/test/framework/components/echo/kube/templates/vm_deployment.yaml
- tools/packaging/common/istio-start.sh
Follow up to
https://github.com/istio/istio/pull/49761#issuecomment-1981362376.
Before, we hack around limits in bash to make VMs work fine. Majority of
k8s platforms do not need this, since they always have
softlimit==hardlimit and a reasonable value, but VMs usually have 1024.
With this fix, we ensure from the agent that Envoy always has the
highest limit, so we can remove all our bash hacks.
If we do not do this, we need to revert
https://github.com/istio/istio/pull/49761
> Increase NOFILE limit for Envoy

- pkg/bootstrap/config.go
- pkg/bootstrap/testdata/all_golden.json
- pkg/bootstrap/testdata/auth_golden.json
- pkg/bootstrap/testdata/authsds_golden.json
- pkg/bootstrap/testdata/default_golden.json
- pkg/bootstrap/testdata/lrs_golden.json
- pkg/bootstrap/testdata/metrics_no_statsd_golden.json
- pkg/bootstrap/testdata/running_golden.json
- pkg/bootstrap/testdata/runningsds_golden.json
- pkg/bootstrap/testdata/stats_compression_brotli_golden.json
- pkg/bootstrap/testdata/stats_compression_gzip_golden.json
- pkg/bootstrap/testdata/stats_compression_unknown_golden.json
- pkg/bootstrap/testdata/stats_compression_zstd_golden.json
- pkg/bootstrap/testdata/stats_inclusion_golden.json
- pkg/bootstrap/testdata/tracing_datadog_golden.json
- pkg/bootstrap/testdata/tracing_lightstep_golden.json
- pkg/bootstrap/testdata/tracing_none_golden.json
- pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
- pkg/bootstrap/testdata/tracing_stackdriver_golden.json
- pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
- pkg/bootstrap/testdata/tracing_tls_golden.json
- pkg/bootstrap/testdata/tracing_zipkin_golden.json
- pkg/bootstrap/testdata/xdsproxy_golden.json
- releasenotes/notes/eds-cache.yaml
Revert as there seems to be some issues https://github.com/envoyproxy/envoy/pull/32767 in Envoy and we also dont fully utilize this as we set init_fetch_timeout to zero
> revert eds cache in ads

- go.mod
- go.sum
per email:
```
In addition, version 1.33.0 of google.golang.org/protobuf inadvertently introduced an incompatibility with the older github.com/golang/protobuf module. (https://github.com/golang/protobuf/issues/1596) Users of the older module should update to github.com/golang/protobuf@v1.5.4.
```
> google.golang.org/protobuf@v1.33.0 incompatability

- pkg/istio-agent/xds_proxy.go
This avoids hanging for 15s if you get unlucky and connect during a
reconnect
> piggyback: close immediately if the connection closes

- pkg/util/istiomultierror/util.go
- pkg/wasm/convert.go
* Avoid double newline, which is excessive for logs
* Use istiomultierror somewhere we forgot it
> Improve formatting of multierror

- Makefile.core.mk
- pilot/pkg/features/pilot.go
This is not ready to be enabled, so save the binary size by removing it.
> build: disable vtprotobuf by default

- manifests/charts/base/values.yaml
- manifests/charts/istio-control/istio-discovery/values.yaml
- manifests/charts/istiod-remote/values.yaml
This is inconsistent to istioctl, where has a default webhook installed, and a webhook per revision.
> helm: fix validation webhook not installed by default

- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta.go
- pkg/test/framework/components/registryredirector/kube.go
- tests/integration/telemetry/api/customize_metrics_test.go
- tests/integration/telemetry/api/setup_test.go
- tests/integration/telemetry/api/testdata/attributegen.yaml
- tests/integration/telemetry/api/testdata/bad-wasm-envoy-filter-fail-open.yaml
- tests/integration/telemetry/api/wasmplugin_test.go
The actual primary change fixing test flakes: disable delta xds due to https://github.com/istio/istio/issues/49847
Other changes to help improve things:
* Enable debug logs to make investigation easier
* Make components not cleanup during local testing
* Avoid using the same tag between tests to test caching; this makes it
impossible to run the test multiple times. Also remove the redundant
test for `latest` vs `explicit` tag, which is pretty redundant -- we
have plenty of unit test coverage for the trivial `latest` special
behavior
> Improve WASM integration tests

- istioctl/pkg/describe/describe.go
when ` istioctl x describe svc httpbin` is executed, and the httpbin service includes both an http and http2 port,
but the http port is ignored and not outputted.
```bash
$  istioctl x describe svc httpbin
Service: httpbin
Port: http 8000/HTTP targets pod port 80
VirtualService: httpbin
1 HTTP route(s)
Exposed on Ingress Gateway http://10.6.136.31
VirtualService: httpbin
1 HTTP route(s)
```
Both HTTP and HTTP2 should be outputted, there shouldn't be any distinction.
```
$ kubectl get svc httpbin -oyaml
apiVersion: v1
kind: Service
metadata:
name: istio-ingressgateway
loadBalancer:
ingress:
- ip: 10.6.136.31
spec:
ports:
- name: http2
protocol: TCP
port: 80
targetPort: 80
nodePort: 30557
- name: http
protocol: TCP
port: …
```
> fix istioctl describe ingress svc ignore http port

- pkg/bootstrap/config.go
- pkg/bootstrap/option/instances.go
- pkg/bootstrap/testdata/all_golden.json
- pkg/bootstrap/testdata/auth_golden.json
- pkg/bootstrap/testdata/authsds_golden.json
- pkg/bootstrap/testdata/default_golden.json
- pkg/bootstrap/testdata/lrs_golden.json
- pkg/bootstrap/testdata/metrics_no_statsd_golden.json
- pkg/bootstrap/testdata/running_golden.json
- pkg/bootstrap/testdata/runningsds_golden.json
- pkg/bootstrap/testdata/stats_compression_brotli_golden.json
- pkg/bootstrap/testdata/stats_compression_gzip_golden.json
- pkg/bootstrap/testdata/stats_compression_unknown_golden.json
- pkg/bootstrap/testdata/stats_compression_zstd_golden.json
- pkg/bootstrap/testdata/stats_inclusion_golden.json
- pkg/bootstrap/testdata/tracing_datadog_golden.json
- pkg/bootstrap/testdata/tracing_lightstep_golden.json
- pkg/bootstrap/testdata/tracing_none_golden.json
- pkg/bootstrap/testdata/tracing_opencensusagent_golden.json
- pkg/bootstrap/testdata/tracing_stackdriver_golden.json
- pkg/bootstrap/testdata/tracing_tls_custom_sni_golden.json
- pkg/bootstrap/testdata/tracing_tls_golden.json
- pkg/bootstrap/testdata/tracing_zipkin_golden.json
- pkg/bootstrap/testdata/xdsproxy_golden.json
- pkg/envoy/proxy.go
- pkg/envoy/proxy_test.go
- pkg/istio-agent/agent.go
- tools/packaging/common/envoy_bootstrap.json
Before/After JSON:
```
{"level":"debug","time":"2024-03-04T12:11:46.931655Z","scope":"envoy connection","msg":"[Tags: \"ConnectionId\":\"2\"] closing socket: 1","caller":"external/envoy/source/common/network/connection_impl.cc:281","thread":947194}
{"time":"2024-03-04T12:15:57.204132Z","level":"debug","scope":"envoy connection","msg":"closing socket: 0","caller":"connection_impl.cc:281 closeSocket","thread":"956652","ConnectionId":"2"}
```
Before/After plain:
```
2024-03-04T12:21:24.654824Z     debug   envoy connection external/envoy/source/common/network/connection_impl.cc:281    [Tags: "ConnectionId":"2"] closing socket: 0    thread=963777
2024-03-04T12:21:00.256847Z     debug   envoy connection connection_impl.cc:281 closeSocket     [Tags: "ConnectionId":"2"] closing socket: 0 …
```
> Envoy: improve logging format configuration

- istioctl/pkg/describe/describe.go
- istioctl/pkg/describe/describe_test.go
- releasenotes/notes/49802.yaml
`istioctl x describe` supports displaying the details of policies for `PortLevelSettings`
the feature from #49802
output demo:
```yaml
$ istioctl x describe pod httpbin-658bfff985-v75g7 
Pod: httpbin-658bfff985-v75g7
Pod Revision: default
Pod Ports: 80 (httpbin), 15090 (istio-proxy)
--------------------
Service: httpbin
Port: http 8000/HTTP targets pod port 80
DestinationRule: httpbin for "httpbin"
Matching subsets: v1
Traffic Policy TLS Mode: ISTIO_MUTUAL
Policies: load balancer/connection pool/outlier detection
Port Level Settings:
8080:
TLS Mode: DISABLE
Policies: connection pool/outlier detection
VirtualService: httpbin
1 HTTP route(s)
```
> istioctl describe supports displaying portlevelsettings

- tools/istio-iptables/pkg/dependencies/implementation_linux.go
https://github.com/istio/istio/pull/49850 attempted to fix issues where older, Debian-wrapped versions of `iptables-save` do not support the `--version` flag.
Unfortunately, in addition to not supporting the `--version` flag, these particular versions of `iptables-save` still return 0 (success) even if it fails to execute due to bad arguments.
So, we cannot rely on `os/exec` returning an error if the command fails, and must check process stderr ourselves to see if it did, for these cases.
(I have confirmed that e.g. 1.8.7/nftables DOES return a nonzero code with a bad argument - this appears to be unique to old versions + old Debian wrapper)
> `iptables-save` does not always return 0 if it fails

- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
This seems to be a regression introduced by the ambient krt PR. Originally, the workloads were sorted by creation time, but after the rewrite, `SortWorkloadsByCreationTime` has become an unused function.
> Fix waypoint listener order

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
This is just a small QOL adjustment to ensure user are appropriately
aware of the risks involved with EnvoyFilter usage. This is *just a
warning* and does not block any usage.
> envoy filter: warn about instability on usage

- pilot/pkg/networking/core/v1alpha3/cluster.go
- pilot/pkg/networking/core/v1alpha3/cluster_test.go
- pilot/pkg/serviceregistry/memory/discovery.go
- pilot/pkg/xds/delta.go
- pilot/pkg/xds/delta_test.go
- pilot/pkg/xds/deltatest.go
- pkg/test/framework/components/echo/common/deployment/echos.go
Due to this bug, clusters and listeners are basically never deleted.
There are two distinct bugs here:
* Our `ResourceNames` computation was wrong, which is used to determine deletes, causing misses. I also removed the lock here, since its not needed (we are operating on a clone of the WatchedResources that we write back later
* We just did not account for inbound in delta CDS at all
Fixes https://github.com/istio/istio/issues/49814
> delta xds: fix deletion of clusters and listeners

- pkg/kube/inject/inject.go
- pkg/kube/inject/webhook.go
- pkg/kube/util.go
- pkg/kube/util_test.go
We don't need the full meta, only the name/namespace
> kube: cleanup GetDeployMetaFromPod

- pkg/istio-agent/xds_proxy.go
- pkg/istio-agent/xds_proxy_delta.go
- xds proxy: avoid double logging errors (#49697)
- avoid duplicate error logging for delta xds proxy (#49706)
> [release-1.21] logs fix

- cni/pkg/log/uds_test.go
- pkg/log/uds.go
Fixes flakes like
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/49644/unit-tests-arm64_istio/1768401500075200512
We only see these on ARM. I have no clue why.
Basically, at 100ms we see timeouts. 100ms is a pretty aggressive
timeout anyways, so bump to 1s
Without PR:
```
39 runs so far, 4 failures (90.70% pass rate). 496.701448ms avg, 651.035779ms max, 310.556531ms min
```
With PR:
```
63781 runs so far, 0 failures (100.00% pass rate). 92.626708ms avg, 376.347405ms max, 13.924519ms mi
```
fixes https://github.com/istio/istio/issues/43115 and https://github.com/istio/istio/issues/42451
> log: increase timeout to reduce UDS test flakes

- pilot/pkg/grpc/tls.go
- pkg/istio-agent/agent.go
- security/pkg/nodeagent/caclient/providers/google/client.go
- security/pkg/nodeagent/plugin/providers/google/stsclient/stsclient.go
- security/pkg/stsservice/tokenmanager/google/tokenexchangeplugin.go
Change-Id: I585090775a978bc8774a7ec0925bb7e8f395b2ab
Extends https://github.com/istio/istio/issues/49081 to support:
* MeshCA
* STS (both implementations), which includes `iamcredentials`.
* GoogleCA
* Citadel
> fips: enforce security services transport algorithms

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/duplicate-subset-names.yaml
Problem:
East-west gateways return NACKs due to [duplicate DR subset names](https://github.com/istio/istio/blob/ab194331988d8740237ee12e5036df7b6d017e88/pilot/pkg/networking/core/v1alpha3/gateway.go#L994):
```bash
warning    envoy config    gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: 
Error adding/updating listener(s) 0.0.0.0_15443: error adding listener '0.0.0.0:15443': 
filter chain '' has the same matching rules defined as ''
```
We already [skip duplicate subsets](https://github.com/istio/istio/blob/ab194331988d8740237ee12e5036df7b6d017e88/pilot/pkg/model/destination_rule.go#L94) when merging DRs. I think a single DR with duplicate subsets should be rejected as well.
**To help us figure out who should …
> validation: check duplicate DR subset names

- istio.deps
- istioctl/pkg/util/configdump/workload.go
- istioctl/pkg/writer/ztunnel/configdump/configdump.go
- istioctl/pkg/writer/ztunnel/configdump/testdata/dump.json
- tests/integration/ambient/cacert_rotation_test.go
This PR addresses the istio integration failures noticed here: https://github.com/istio/istio/pull/49964#issuecomment-2010577377
This was a result of the recent changes to[ migrate to rustls](https://github.com/istio/ztunnel/pull/820) where a struct was modified in ztunnel and removed a field (ca_cert) that gets checked for an istio integration test called TestIntermediateCertRefresh. 
Here is the struct in it's current state:
```
pub struct CertsDump {
identity: String,
state: String,
cert_chain: Vec<CertDump>,
}
```
instead of:
```
pub struct CertsDump {
identity: String,
state: String,
ca_cert: Vec<CertDump>,
cert_chain: Vec<CertDump>,
}
```
This failure is preventing ztunnel from getting updated in istio.deps because the integration tests …
> Update istio integration tests to account for removal of cacert field from config dump

- pilot/pkg/model/context.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/service.go
- pilot/pkg/networking/core/v1alpha3/cluster_waypoint.go
- pilot/pkg/networking/core/v1alpha3/waypoint.go
- pilot/pkg/serviceregistry/aggregate/controller.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/helpers.go
- pilot/pkg/serviceregistry/kube/controller/ambient/services.go
- pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
- pilot/pkg/serviceregistry/memory/discovery.go
- pilot/pkg/xds/cds.go
- pilot/pkg/xds/endpoints/endpoint_builder.go
- pkg/config/constants/constants.go
- pkg/test/framework/components/ambient/waypoint.go
- pkg/test/framework/components/echo/annotations.go
- releasenotes/notes/49700.yaml
- tests/integration/ambient/bookinfo_test.go
- tests/integration/ambient/cacert_rotation_test.go
- tests/integration/ambient/gateway_conformance_test.go
- tests/integration/ambient/main_test.go
implements basic use-waypoint logic:
- removes waypoint scope from _most_ places but not entirely (yet) although I'm not opposed to just getting that fully removed if we want
- adds parsing of use-waypoint on svc and wl types as well a namespace
- adjusts unit and integ tests to reflect the new waypoint attachment method
- adjusts how SA are selected for waypoints since scope became largely vestigial and fully namespace scoping a waypoint that isn't actually namespace in scope was problematic for several test scenarios
- allows for wds configuration of service attached waypoints
> handling use-waypoint

- pkg/config/analysis/analyzers/util/proxyconfig.go
ImageAnalyzer ImageType() misuse maps.Contains to matched pod labels
https://github.com/istio/istio/blob/master/pkg/maps/maps.go#L64-L71
> ImageAnalyzer  imageType  matched the  pod labels error

- cni/pkg/nodeagent/net_test.go
- istioctl/pkg/root/root.go
- pilot/pkg/networking/grpcgen/grpcgen_test.go
- pkg/log/config.go
- pkg/log/config_test.go
- pkg/log/default.go
- pkg/log/default_test.go
- pkg/log/options.go
- pkg/log/options_test.go
- pkg/test/framework/components/istio/installer.go
- pkg/test/framework/logging.go
- tools/bug-report/pkg/bugreport/bugreport.go
Various fixes here
* Make the SetDefaultOutputLevel set defaults, and --log_output_level
overrides those. Before, ANY --log_output_level flag completely
override SetDefaultOutputLevel. So if I set `foo:warn`, I may
accidentally change every scope to `info`.
* Fix gRPC log to respect levels
* Fix a bunch of inconsistencies around gRPC logs
* Remove a bunch of functions only used in tests
> log: revamp logging options

- tests/integration/ambient/cacert_rotation_test.go
See https://github.com/istio/istio/issues/49648. This test is 100% broken, but we have no assertions. Worse, though, its masking other real (crashing) issues. Skip for now; I have another PR but it is not ready
> Temporarily skip broken test

- istioctl/pkg/describe/describe.go
- istioctl/pkg/describe/describe_test.go
- releasenotes/notes/fix-istioctl-describe-ingressinfo.yaml
- tests/integration/pilot/istioctl_test.go
If service be exposed by non `istio-system`(default system namespace) gateway, we not found any informations form `istioctl x describe`.
so  we need to exposed those ingress informations by `istioctl x describe`.
- some ref issue: https://github.com/istio/istio/issues/46160#issuecomment-1979973885
> fixed istioctl describe output ingress info ignore non istio-system

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/model.go
- pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
- pkg/config/constants/constants.go
- pkg/test/framework/components/echo/config.go
- releasenotes/notes/50132.yaml
- tests/integration/ambient/waypoint_test.go
* Remove the GatewayClass == istio-waypoint requirement for Waypoints. We don't really need it now that we have use-waypoint, although it will fill the krt.Collection with some unneeded items. Later could be reduced based on registered classes/GatewayCapabilities. 
* Add `networking.istio.io/address-type` to allow forcing `ClusterIP` for `istio` class Gateways
* Test use-waypoint sends traffic through this gateway
related to (but doesn't resolve) #48362
> use istio gateways as basic HTTP waypoints

- pilot/pkg/config/kube/gateway/context.go
- pilot/pkg/config/kube/gateway/controller.go
- pilot/pkg/config/kube/gateway/conversion_test.go
- releasenotes/notes/50138.yaml
The current behavior could have a Gateway defined in cluster-1 that writes VIPs from all clusters. Perhaps this is valid for some kind of cross-cluster routing. 
My thought is: If we were to have a waypoint in cluster-1 AND cluster-2, we likely only want the cluster-local VIPs being sent to zTunnels.
> gateway api: scope service VIPs to cluster

- cni/pkg/nodeagent/net.go
- pilot/pkg/config/kube/gateway/controller.go
- pilot/pkg/model/typed_xds_cache.go
- pilot/pkg/networking/core/cluster.go
- pilot/pkg/xds/workload.go
- pkg/util/sets/set.go
- pkg/util/sets/set_test.go
Operate in place to save copies and temporary space.
```
$ go test -run=^$ -bench=BenchmarkOperateInPlace -test.benchmem -count=1
os: darwin
goarch: amd64
pkg: istio.io/istio/pkg/util/sets
BenchmarkOperateInPlace/Difference-12         	  215138	      5794 ns/op	    1522 B/op	      12 allocs/op
BenchmarkOperateInPlace/DifferenceInPlace-12  	  909678	      1351 ns/op	       0 B/op	       0 allocs/op
BenchmarkOperateInPlace/Intersection-12       	  860622	      1391 ns/op	      48 B/op	       1 allocs/op
BenchmarkOperateInPlace/IntersectInPlace-12   	361817298	         3.302 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	istio.io/istio/pkg/util/sets	6.857s
```
> Add set functions with better performance

- pilot/pkg/model/virtualservice.go
These scenarios are matching conflicts or configuration errors and cannot be detected by webhooks. It makes sense to change to printing warning logs so that we can detect problems through logs in time when applying configuration, because we do not enable debug logs by default.
> print warning log when virtual service config error

- pkg/util/concurrent/debouncer.go
- releasenotes/notes/50157.yaml
Resolves https://github.com/istio/istio/issues/49340.
I think the root cause is that the set will never be nil, but rather an empty initialized set, which results in the analysis being stuck in a push loop forever.
> Fix high CPU consumption on pilot when in-cluster analysis is enabled

- Makefile.core.mk
- pilot/cmd/pilot-agent/status/ready/probe.go
- pkg/bootstrap/option/convert.go
Change-Id: Ifdd99ff6f939273888de0e9aab4d4c26e573dcd5
Tighten proto imports further for the agent and remove cluster, listener, and admin xDS.
Protobuf are known to bloat the binary, especially when the validation code is linked.
Issue: #50134
> proxy: eliminate most xDS

- Makefile.core.mk
- pkg/wasm/convert.go
Change-Id: I3342815b328de9af8bdbab3112de7e73d5fbba58
I realized we don't even need RBAC/route because the hard-coded proto is empty.
Issue: #50134
> proxy: remove unnecessary rbac and route imports

- pilot/pkg/config/kube/gateway/conversion.go
A few are only present in alpha/beta, so use those.
This is prep for
https://github.com/kubernetes-sigs/gateway-api/pull/2920/
> Move most gateway-api imports to v1

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
fixes #50175 
```shell
$ stress ./ambient.test -test.v -test.run TestAmbientIndex_Policy
...
10m0s: 3571 runs so far, 0 failures
```
> assert all events in TestAmbientIndex_Policy to reduce flakiness

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pkg/kube/krt/collection.go
- pkg/kube/krt/sync.go
Example
https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1775278590686924800
3 issues:
* Race on Dump()
* Failure in the test
* Lack of syncing leads to flakes
Failure comes from not waiting for the waypoint to be applied yet
Also fixes https://github.com/istio/istio/issues/50192
> ambient: fix flake on waypoint

- istioctl/pkg/waypoint/testdata/waypoint/all-gateway
- istioctl/pkg/waypoint/testdata/waypoint/combined-gateway
- istioctl/pkg/waypoint/testdata/waypoint/default-gateway
- istioctl/pkg/waypoint/waypoint.go
- istioctl/pkg/waypoint/waypoint_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
- pkg/config/analysis/analyzers/maturity/maturity.go
- pkg/config/analysis/analyzers/testdata/misannotated.yaml
- pkg/config/analysis/analyzers/testdata/service-port-name.yaml
- pkg/config/constants/constants.go
- pkg/test/framework/components/ambient/waypoint.go
- releasenotes/notes/50221.yaml
- samples/ambient-argo/application/details-waypoint.yaml
- samples/ambient-argo/application/reviews-waypoint.yaml
- tests/integration/ambient/bookinfo_test.go
- tests/integration/ambient/waypoint_test.go
Closes #50173 - removes unused WaypointServiceAccount concept
Closes #49915 - adds waypoint name to istioctl
With https://github.com/istio/istio/pull/49700, WaypointServiceAccount "istio.io/for-service-account" has been useless, because the annotation is not checked anymore.
> Remove istio.io/for-service-account

- pkg/config/schema/kubeclient/common.go
- pkg/config/schema/kubeclient/common_test.go
- pkg/config/schema/kubetypes/common.go
- pkg/kube/kclient/client.go
- pkg/kube/krt/informer_test.go
Provide a mechanism within `kube.Client` to create informers for arbitrary types. This enables `krt.Collection` resources to be created from informers on types not registered in `resources.gen.go`
> Enable kube.Client to create informers for registered types

- pilot/pkg/model/telemetry_test.go
This PR tests [AccessLogging.Match ](https://istio.io/latest/docs/reference/config/telemetry/#AccessLogging)
Part of #46720
> Test the Telemetry API Access logging match feature

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
https://storage.googleapis.com/istio-prow/logs/unit-tests-arm64_istio_postsubmit/1773396921478549504/build-log.txt
```
2267 runs so far, 14 failures (99.39% pass rate). 418.905338ms avg, 766.491613ms max, 320.787806ms min
```
vs with this PR
```
3007 runs so far, 0 failures (100.00% pass rate). 435.21344ms avg, 675.333504ms max, 328.187762ms min\
```
Its from `features` being accessed concurrently. Cannot happen in prod as they do not change at runtime in real code
> ambient: shutdown client in test to prevent races

- pkg/test/framework/analyzer.go
- pkg/test/framework/scope.go
- pkg/test/framework/suitecontext.go
- pkg/test/framework/test.go
- pkg/test/framework/testcontext.go
- tests/integration/ambient/traffic_test.go
```go
framework.NewTest(t).
TopLevel().
Features("traffic.routing", "traffic.reachability", "traffic.shifting").
Run(func(t framework.TestContext) {
apps := deployment.NewOrFail(t, t, deployment.Config{
NoExternalNamespace: true,
IncludeExtAuthz:     false,
})
common.RunAllTrafficTests(t, i, apps.SingleNamespaceView())
})
```
Marking this test  means any descendent `this_test/subtest_group/individual_case` will dump the resources created at this level. Previously we had this behavior for `Suite` level resources. For tests like this that are essentially suites, we should get the same behavior. 
fixes #50238
> tf: allow dumping resources from container tests

- pkg/kube/inject/inject.go
This is typically handled during install, where `.Values.global.variant`
automatically configures mesh config.
But to be more robust, also handle the case its set here directly
> injection: use values default as base

- pilot/pkg/networking/core/listener_builder.go
- pilot/pkg/networking/core/tracing.go
- pilot/pkg/networking/core/tracing_test.go
xref: https://github.com/envoyproxy/envoy/pull/29659
TODO: consider enable `SpawnUpstreamSpan` for all trace provider?
> use SpawnUpstreamSpan instead of startChildSpan

- istioctl/pkg/waypoint/waypoint.go
- pkg/config/constants/constants.go
- releasenotes/notes/50221.yaml
- releasenotes/notes/50267.yaml
- tests/integration/ambient/waypoint_test.go
This PR adds an istioctl flag for enrolling a namespace for a specific waypoint. This was done in addition to a few other things that in order to clean up the istioctl waypoint logic:
- Add `--enroll-namespace` flag with default value set. A user can now specify a namespace to enroll with the waypoint when they create/update a waypoint.
- `trafficType` and `waypointName` had default checks where if it wasn't set and `makeGateway` was called it would get set to the default values specified in `constants.go`. This PR initializes those variables ahead of time and lets the user override them but if the flag is never used, we already have the default value set.
- `waypointName` flag should have an accurate default value in it's flag description …
> istioctl: add enrolled namespace flag for users to enroll waypoints for a namespace

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
We have test assertion that ensures we use the same filter everywhere;
make sure we use it here as well.
See
https://storage.googleapis.com/istio-prow/logs/integ-assertion_istio_postsubmit/1777414345316110336/artifacts/ambient-e522794887874c3bb2a1d78/_suite_context/istio-state-1166045208/primary-0/istiod-764d6c499b-wmqfc_discovery.previous.log
> ambient: fix node filter

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
- pilot/pkg/serviceregistry/kube/controller/ambient/meshconfig.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
- pkg/kube/krt/bench_test.go
- pkg/kube/krt/collection.go
- pkg/kube/krt/collection_test.go
- pkg/kube/krt/core.go
- pkg/kube/krt/fetch.go
- pkg/kube/krt/filter.go
- pkg/kube/krt/index.go
- pkg/kube/krt/index_test.go
- pkg/kube/krt/informer.go
- pkg/kube/krt/informer_test.go
- pkg/kube/krt/internal.go
- pkg/kube/krt/join.go
- pkg/kube/krt/join_test.go
- pkg/kube/krt/singleton.go
- pkg/kube/krt/static.go
This PR introduces a few changes:
* Allow Fetching by an Index. This is going to be used directly in some followup work
* Rewrite Namespace lookup/list to use an Index on Namespace. Before, the namespace was just a post-applied filtering anyways. We also didn't use any listing by a certain namespace anyways
A modest perf improvement (though the benchmark doesn't use it as effectively as future PR will, so its not the primary motivation):
```
name                   old time/op    new time/op    delta
Controllers/krt-16       14.7ms ± 4%    12.2ms ± 6%  -17.40%  (p=0.000 n=10+9)
name                   old alloc/op   new alloc/op   delta
Controllers/krt-16       16.0MB ± 0%    14.9MB ± 0%   -6.41%  (p=0.000 n=10+9)
name                   old allocs/op  new allocs/op  delta
Controllers/krt-16 …
```
> krt: allow lookup by Index, replace Namespace logic with Index

- pilot/pkg/networking/core/gateway.go
- pilot/pkg/networking/core/gateway_simulation_test.go
- releasenotes/notes/vs-overwrite-fix.yaml
Make sure that each host has its own slice of routes to not overwrite routes added by other virtual services.
In the test case the `foobar-vs` will allocate memory to hold 4 routes, but will only be using 3. The same slice will be used for both hosts when added to the `vHostDedupMap`.
`foo-vs` and `bar-vs` virtual services will both append to the same slice resulting in that the last of the two (`bar-vs`) will overwrite the path already added by `foo-vs`.
This will result in that the path added by `foo-vs` will be lost and the path added by `bar-vs` will be added to both hosts.
This change will create a copy of the  routes slice for each host so that subsequential appends to the slice only affects the current host.
> Fix bug when virtual services overwrites routes

- istio.deps
- tests/integration/ambient/baseline_test.go
Adjust tests to account for removal of hairpin logic from ztunnel in https://github.com/istio/ztunnel/pull/913
> revised tests to account for removal of hairpin

- istioctl/cmd/root.go
- istioctl/pkg/proxyconfig/proxyconfig.go
- istioctl/pkg/proxyconfig/proxyconfig_test.go
- istioctl/pkg/ztunnelconfig/ztunnelconfig.go
- istioctl/pkg/ztunnelconfig/ztunnelconfig_test.go
- releasenotes/notes/50347.yaml
Resolves: #49841 
Removes the workload command from `istioctl proxy-config` and puts it in a new command called `istioctl ztunnel-config`.
`istioctl proxy-config` and `istioctl pc` no longer work when calling `w` or `workload`:
e.g.
```
azureuser@dev-2024:~/istio$ ./out/linux_amd64/istioctl pc w ztunnel-5kq4t -n istio-system
A group of commands used to retrieve information about proxy configuration from the Envoy config dump
Usage:
istioctl proxy-config [command]
```
`istioctl ztunnel-config` and `istioctl zc` now take its place for getting ztunnel info (`w` or `workload`):
**short (or no -o provided) snippet:**
```
azureuser@dev-2024:~/istio$ ./out/linux_amd64/istioctl zc w ztunnel-5kq4t -n istio-system
NAMESPACE          NAME …
```
> Split istioctl pc ztunnel info into zc

- release/downloadIstioCtl.sh
Currently, when the `curl -fsL -o "${tmp}/${filename}" "$ARCH_URL"` failed, the download will continue with msg `istioctl-xxx download complete!` and exit successfully. This behavior reports a successful download even when it failed.
> download script should fail early when the download failed

- cni/pkg/cmd/root.go
- pkg/ctrlz/ctrlz.go
- pkg/ctrlz/options.go
- pkg/file/file.go
- releasenotes/notes/cni-pprof.yaml
Turns out once you can see whats going on, its really simple to optimize
functions that are obviously inefficient and have been around for ~5
years!
Fixes https://github.com/istio/istio/issues/49053
> cni: enable pprof, stop memory spikes

- pilot/pkg/networking/plugin/authz/authorization.go
- tests/integration/ambient/baseline_test.go
- tests/integration/ambient/testdata/requestauthn/waypoint-jwt.yaml.tmpl
All other types set IsWaypoint, we missed it for ambient. Also move all
tests over to use targetRef
> ambient: fix targetRef for Authz, move all tests over

- tests/integration/security/testdata/requestauthn/timeout.yaml.tmpl
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/batch/integ-security_istio/1778890737706864640
I think the tight window on the timeout may trigger it to occasionally
work unexpectedly (Envoy gets paused for ~20ms, etc)
> tests: make security timeout test more resiliant

- pilot/pkg/features/experimental.go
- pilot/pkg/xds/sds.go
This has been true for more than 2 years and no one complained. No reason to turn it off either
> remove VERIFY_SDS_CERTIFICATE feature flag

- istioctl/pkg/waypoint/waypoint.go
Sort the values to stop randomly updating the reference docs.
Looking at https://github.com/istio/istio.io/pull/14879/files, we will routinely update the reference docs as the validTrafficTypes.String() is random:
```
// String returns a string representation of the set.
// Be aware that the order of elements is random so the string representation may vary.
```
> Sort values for validTrafficType

- pilot/pkg/model/policyattachment.go
- pilot/pkg/model/policyattachment_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
- tests/integration/ambient/baseline_test.go
- tests/integration/ambient/testdata/requestauthn/waypoint-jwt.yaml.tmpl
We expect to push all users to use targetRefs in all cases. Both work,
but uses copy+paste from tests so its best to use best practices here.
Unit tests provide sufficient coverage that singular and plural are the
same.
> ambient: test `targetRefs` instead of singular

- istioctl/pkg/waypoint/waypoint.go
- releasenotes/notes/50395.yaml
Resolves: #50396
We are not checking if a namespace is labeled ambient before we enroll a waypoint with a namespace. This PR adds that check that returns early before we apply the waypoint if `--enroll-namespace` flag is used and the namespace does not have that `ambient` label.
This is what the UX will look like now:
```
azureuser@dev-2024:~/istio$ istioctl x waypoint apply --enroll-namespace                                            
Warning: namespace is not enrolled in ambient. Consider running `kubectl label namespace default istio.io/dataplane-mode=ambient`     
azureuser@dev-2024:~/istio$ istioctl x waypoint apply --enroll-namespace                                            
Warning: namespace is not enrolled in ambient. Consider …
```
> istioctl: we should warn when namespace is not labeled ambient

- pilot/pkg/xds/delta.go
- pilot/pkg/xds/sds.go
- tests/integration/security/main_test.go
Related to https://github.com/istio/istio/issues/50361; I am not sure if
its a fix or not.
This mirrors EDS and RDS. When we have nothing to push, do not respond
rather than an empty response.
> sds: do not send empty responses

- pilot/pkg/autoregistration/controller.go
- pilot/pkg/autoregistration/controller_test.go
This flag would currently cause Istiod to panic if its ever set. Fix it
and add a simple test
> autoregistration: fix regression in PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION

- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/pod.go
- pilot/pkg/serviceregistry/kube/controller/pod_test.go
- tests/integration/pilot/label_test.go
Fixes https://github.com/istio/istio/issues/43694
Fixes https://github.com/istio/istio/issues/50431
> pilot: update pods in EndpointShardz when labels change

- istioctl/pkg/waypoint/testdata/waypoint/all-gateway
- istioctl/pkg/waypoint/testdata/waypoint/combined-gateway
- istioctl/pkg/waypoint/testdata/waypoint/default-gateway
- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/conversion_test.go
- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/config/kube/gateway/testdata/deployment/waypoint-no-network-label.yaml
- pilot/pkg/config/kube/gateway/testdata/deployment/waypoint.yaml
- pilot/pkg/config/kube/gateway/testdata/waypoint.status.yaml.golden
- pkg/config/constants/constants.go
- tests/integration/ambient/baseline_test.go
Before: `default-namespace`, which ends up suffixing to `default-namespace-istio-waypoint`
Now: `waypoint`, with suffix disabled. So its just `waypoint`.
From discussion with @louiscryan
> ambient: rename default waypoint (again)

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
Some protocols needs more drain duration it seems https://github.com/istio/istio/discussions/50477. Envoy does not have max - So not sure if we should have one
> remove max drain duration

- pkg/config/model.go
- pkg/config/schema/codegen/templates/types.go.tmpl
- pkg/config/schema/kubeclient/common.go
- pkg/config/schema/kubeclient/common_test.go
- pkg/config/schema/kubetypes/common.go
- pkg/config/schema/kubetypes/resources.gen.go
- pkg/kube/kclient/client.go
- pkg/kube/krt/informer_test.go
- pkg/typemap/map.go
- pkg/typemap/map_test.go
1. Use a map for lookup instead of O(1) lookup
2. Check the core types first, to favor performance of core types over extended. This is likely a trivial difference
3. Pass list and watch instead of ListWatch so the common library can set the standard fields.
cc @jmcshane lmk what you think. Ill un-draft once yours merges
> Simplify dynamic informer registration

- pkg/config/analysis/analyzers/externalcontrolplane/externalcontrolplane.go
This analyzer depending on doing DNS resolution from the analyzer. This is pretty problematic.
1. Analysis is often run locally. Local network != kubernetes network
2. Unbounded outbound network requests from istiod is bad
3. We don't even use the result anyways
4. This makes unit tests depend on network connectivity, which has been causing failures (due to prow cluster networking issues, fwiw)
This PR removes it entirely
> analyzer: do not depend on local network

- cni/pkg/plugin/sidecar_iptables_linux.go
- tools/istio-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/config/config.go
Panic is ~ok for a CLI, but terrible for a long-running daemon (CNI).
Replace with proper error handling.
We did this for most `panic` in the past ,but missed these Fatal calls
> iptables: remove a few panics instead of errors

- releasenotes/notes/49911.yaml
fixes: #49911 
xref: https://github.com/envoyproxy/envoy/pull/33281
this's fixed on upstream, just add release notes to highligh.
**Should not be backported unless envoy did**
> EnvoyOpenTelemetryLogProvider should set TraceId

- pilot/pkg/features/ambient.go
- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
- pilot/pkg/serviceregistry/kube/controller/ambient/services.go
- pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pkg/kube/krt/filter.go
When the feature flag is enabled, automatically add an ALLOW policy to attached to workloads that _could_ flow through the Waypoint. This includes Workloads that are part of a Service that has a Waypoint.
> generate implicit policies to allow from waypoint

- pilot/pkg/networking/core/route/route.go
- pilot/pkg/networking/core/sidecar_simulation_test.go
- releasenotes/notes/fix-external-name.yaml
This was a regression caused in the initial introduction of `ENABLE_EXTERNAL_NAME_ALIAS`. This section was not properly feature flagged, leading to accidental partial enablement when the flag was off. This leads to an inconsistent state, where routes point to non-existing clusters.
Reproducer config:
```yaml
apiVersion: v1
kind: Service
metadata:
name: external
spec:
externalName: something.example.com
ports:
- name: tcp-1234
port: 1234
type: ExternalName
---
metadata:
name: example
spec:
hosts:
- external
tcp:
- match:
- port: 1234
route:
- destination:
host: external
```
Results in:
```
NAME                                                          SERVICE FQDN                           PORT     SUBSET     DIRECTION     TYPE …
```
> pilot: fix invalid destination clusters with ENABLE_EXTERNAL_NAME_ALIAS=false

- istioctl/pkg/waypoint/waypoint.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
- pkg/config/constants/constants.go
- pkg/test/framework/components/ambient/waypoint.go
- pkg/test/framework/components/echo/annotations.go
- pkg/test/framework/components/echo/config.go
- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/components/echo/kube/templates/service.yaml
- releasenotes/notes/50572.yaml
- tests/integration/ambient/gateway_conformance_test.go
- tests/integration/ambient/main_test.go
- tests/integration/ambient/waypoint_test.go
This changes `istio.io/use-waypoint`  to be a label, and not an annotation.
Why? 
1. It's not consistent with the other ambient labels, which feels weird:
```
apiVersion: v1
kind: Namespace
metadata:
annotations:
istio.io/use-waypoint: waypoint
creationTimestamp: "2024-04-04T18:13:55Z"
labels:
istio.io/dataplane-mode: ambient
kubernetes.io/metadata.name: default
```
vs
```
apiVersion: v1
kind: Namespace
metadata:
creationTimestamp: "2024-04-04T18:13:55Z"
labels:
istio.io/use-waypoint: waypoint
istio.io/dataplane-mode: ambient
kubernetes.io/metadata.name: default
```
2. In general, following a maxim of "labels are for user intent, annotations are for status" gets more consistent results.
3. We will probably want to query this (since it is user …
> `use-waypoint` is user intent, so should be label

- pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-in.yaml
- pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-out.yaml
- pilot/pkg/security/authz/builder/testdata/http/allow-path-in.yaml
- pilot/pkg/security/authz/builder/testdata/http/allow-path-out.yaml
- pilot/pkg/security/authz/builder/testdata/http/extended-allow-full-rule-out.yaml
- pilot/pkg/security/authz/builder/testdata/http/extended-allow-path-out.yaml
- pilot/pkg/security/authz/matcher/template.go
- pilot/pkg/security/authz/matcher/template_test.go
- pilot/pkg/security/authz/model/generator.go
- pilot/pkg/security/authz/model/generator_test.go
- pilot/pkg/security/authz/model/permission.go
- pkg/config/security/security.go
- pkg/config/security/security_test.go
- pkg/config/validation/validation.go
- releasenotes/notes/16585.yaml
- tests/integration/security/authz_test.go
- tests/integration/security/testdata/authz/path-templating.yaml.tmpl
Updates `paths` and `notPaths` in the AuthorizationPolicy resource to support a limited set of templating based on envoy's [uri templating](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/path/match/uri_template/v3/uri_template_match.proto). 
https://github.com/istio/istio/issues/16585
Adds support for:
- `{*}`
- `{**}` 
If a path contains `{*}` or `{**}` it will be interpreted as a uri template rather than a string match. `{*}` will be converted to `*` and `{**}`  will be convert to `**` when applied in the envoy config.
Open questions: 
1. If a path contains an invalid template (ie. `{}`, `{*`, etc) should we return an error or interpret the path as a string match?
2. If a path contains `*` or `**` (invalid chars in uris, but …
> Add one/many path templating support for AuthPolicy

- CODEOWNERS
This has been a continued source of friction by requiring approvals from
a variety of folks no longer actively working on the project. Instead,
make it all env WG.
> Drop individual requirements for helm chart values.yaml

- istioctl/pkg/waypoint/waypoint.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
- pkg/config/constants/constants.go
Use a label for defining what kinds of traffic a waypoint will accept because it is an expression of user-intent and not a status.
fixes #50606
> waypoint-for switched from annotation to label

- pilot/pkg/xds/ads.go
> xds: use consistent ordering for Ztunnel types

- go.mod
- go.sum
ping release-1.22 to https://github.com/envoyproxy/go-control-plane/commit/57c85e1829e6fe6e73fb69b8a9d9f2d3780572a5
> [release-1.22] pin envoyproxy/go-control-plane

- istioctl/pkg/writer/ztunnel/configdump/certificates.go
- istioctl/pkg/writer/ztunnel/configdump/configdump.go
- istioctl/pkg/writer/ztunnel/configdump/policies.go
- istioctl/pkg/writer/ztunnel/configdump/services.go
- istioctl/pkg/writer/ztunnel/configdump/testdata/secretsummary.txt
- istioctl/pkg/writer/ztunnel/configdump/testdata/workloadsummary.txt
- istioctl/pkg/writer/ztunnel/configdump/testdata/workloadsummary_default.txt
- istioctl/pkg/writer/ztunnel/configdump/workload.go
fixes #50573 
This PR attempts to clarify the output of `istioctl c ztunnel-config all` by adding type information to the name column header. It also adds verbose workload output so that waypoint and protocol are visible.
new output looks like:
```shell
❯ ./out/linux_amd64/istioctl x zc all
NAMESPACE          POD NAME                                IP          NODE                  WAYPOINT PROTOCOL
default            details-v1-f556b5996-vs7dk              10.244.2.13 ambient-worker2       None     HBONE
default            notsleep-847d8464fc-h9vmn               10.244.2.14 ambient-worker2       None     HBONE
default            productpage-v1-65cd959b64-p6xzq         10.244.2.15 ambient-worker2       waypoint HBONE
default …
```
> clarify zc output by adding type info to headers

- pkg/envoy/agent.go
- releasenotes/notes/50596.yaml
Fixed (#50596)
I turned on the exit on zero active connection feature in istio 1.19. I've been waiting for this feature because the preStop loop we implemented was hacky
After applying the feature, it worked well for a while. We received a report from engineer that the application was occasionally crashing when it terminated. The following error logs were captured:
...
2024-04-17 17:22:36.687	2024-04-17T08:22:36.687060Z	info	There are still 5630 active connections
2024-04-17 17:22:37.376	2024-04-17T08:22:37.376249Z	warn	Envoy proxy is NOT ready: server is not live, current state is: DRAINING
2024-04-17 17:22:38.608	2024-04-17T08:22:38.608674Z	error	**unable to get listener stats from Envoy : Get …
> Add retry on EXIT_ON_ZERO_ACTIVE_CONNECTIONS loop

- istioctl/pkg/writer/ztunnel/configdump/api.go
- istioctl/pkg/ztunnelconfig/ztunnelconfig.go
The log examples were invalid/misleading, and config dump was missing a
field.
> istioctl: update ztunnel log examples and config dump API

- bin/update_crds.sh
- go.mod
- go.sum
- pilot/pkg/config/kube/crdclient/client_test.go
- pkg/config/schema/codegen/templates/collections.go.tmpl
- pkg/config/schema/collections/collections.agent.gen.go
- pkg/config/schema/collections/collections.gen.go
- pkg/kube/client.go
- pkg/kube/kclient/clienttest/crd.go
- pkg/kube/kclient/crdwatcher.go
- pkg/kube/kclient/crdwatcher_test.go
- tests/integration/ambient/gateway_conformance_test.go
- tests/integration/pilot/gateway_conformance_test.go
- tests/integration/pilot/testdata/gateway-api-crd.yaml
This won't work until GW api actually official launches 1.1, where the bundle-version will be "1.1".
Part of https://github.com/istio/istio/issues/50408
> Gateway v1.1: support gRPC route v1

- istioctl/pkg/writer/ztunnel/configdump/certificates.go
- istioctl/pkg/writer/ztunnel/configdump/testdata/secretsummary.txt
We were showing the leaf as "CA", and intermediates as "CA".
Now show them properly: Root, Intermediate(s), Leaf
> istioctl: fix certificate view

- pilot/pkg/networking/core/cluster.go
- pilot/pkg/xds/endpoints/endpoint_builder.go
- pkg/model/proxy.go
- tests/integration/ambient/waypoint_test.go
Currently the sandwich is sending waypoint in envoy AND adding another
layer in ztunnel. This lets us disable it
> ambient: make sandwich test not do double HBONE

- architecture/ambient/ztunnel.md
This PR does some refactoring of the Ztunnel documentation that I noticed while going through it recently.
- grammatical error
- inconsistent references to xDS and XDS
- updated information about what service proto definition has given the [recent changes](https://github.com/istio/ztunnel/pull/823) I added to the API to support waypoint capture
> Refactor ztunnel architecture doc

- pilot/pkg/xds/endpoints/endpoint_builder.go
- pilot/pkg/xds/endpoints/ep_filters_test.go
- releasenotes/notes/50688.yaml
> Fix eds cluster loadassignment with invalid endpoint

- pilot/pkg/xds/endpoints/endpoint_builder.go
- pilot/pkg/xds/endpoints/ep_filters_test.go
- releasenotes/notes/50688.yaml
fixes: #50718 
Manual pick: #49629 and #50690
> [release-1.21] Fix eds cluster loadassignment with invalid endpoint

- pilot/pkg/networking/core/listener_waypoint.go
- releasenotes/notes/50737.yaml
In https://github.com/istio/ztunnel/pull/931 we added keepalives to the serverside of the HBONE tunnel to work around a hyper client bug: https://github.com/hyperium/hyper/pull/3647
This just adds the same things to the waypoint, for the same reasons.
IMO keepalives are probably worth having even if the hyper client bug is fixed, as a safety valve to keep misbehaving clients (even if they are ours) from hanging connections.
> Add keepalives to waypoint HBONE endpoint to mimic ztunnel

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pkg/test/framework/components/echo/config.go
- pkg/test/framework/components/echo/echotest/filters.go
- pkg/test/framework/components/echo/match/matchers.go
- pkg/test/framework/components/echo/workloadclass.go
- tests/integration/ambient/baseline_test.go
- tests/integration/ambient/main_test.go
- tests/integration/pilot/common/routing.go
> ambient: fix auto-allow waypoint

- tests/binary/binaries_test.go
Fixes a failure in https://github.com/istio/istio/pull/50740 where the ztunnel binary is smaller than the minimum size specified in the test.
Also fix the message to use the correct variable for minimum size allowed.
> Reduce ztunnel binary minimum size. Fix message

- pkg/slices/slices.go
Hi, this very small cleanup is removing the explicit zeroing `s[i] = empty` in `slices.Delete`.
2 good reasons to do this:
- The stdlib `slices.Delete` does now zero/nil out the obsolete elements, since Go 1.22 ([1](https://github.com/golang/go/issues/63393), [2](https://go.dev/cl/541477), [3](https://go.dev/blog/generic-slice-functions)).  No need to have `istio.io/istio/pkg/slices` do the zeroing anymore.
- istio's `go.mod` specifies `go 1.22.0` so we can move forward
- Zeroing the correct elements is a subtle exercise. The former code was zeroing at the index being deleted (overwritten), which is not what we wanted. We wanted to zero the now-obsolete element **at the end** of the slice. The test `TestDelete` did check if the deleted element …
> slices: remove redundant zeroing in Delete

- pilot/pkg/model/endpointshards.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pilot/pkg/serviceregistry/serviceentry/conversion_test.go
- pilot/pkg/xds/cds_test.go
- releasenotes/notes/se-conflict.yaml
Throwing in my attempt at fixing https://github.com/istio/istio/issues/50478.
Note this pairs well with https://github.com/istio/istio/pull/50690 to fix the EDS issue (https://github.com/istio/istio/issues/50688). With both PRs, all known issues are fixed.
There are a few approaches here:
Up to 1.19.8 the created clusters are one per port without LB between ports:
```
outbound|80||news.google.com::172.217.22.110:80
outbound|8080||news.google.com::172.217.22.110:8080
```
This behavior is, IMO, what a user expects. While the port names are colliding, user probably doesn't really care -- they care about the number. This also is the behavior if the port names did not collide.
This was the behavior in 1.19 **and what I implemented here**.
Cross product the ports:
``` …
```
> Fix service entry merge

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pkg/slices/slices.go
- pkg/slices/slices_test.go
Changed `sort.SliceStable` to `slices.SortStableFunc`.
```
goos: darwin
goarch: arm64
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
SortServicesByCreationTime-8   8.795µ ± 2%   5.005µ ± 1%  -43.10% (p=0.002 n=6)
│  old.txt   │              new.txt              │
│    B/op    │   B/op     vs base                │
SortServicesByCreationTime-8   56.00 ± 0%   0.00 ± 0%  -100.00% (p=0.002 n=6)
│  old.txt   │              new.txt               │
│ allocs/op  │ allocs/op   vs base                │
SortServicesByCreationTime-8   2.000 ± 0%   0.000 ± 0%  -100.00% (p=0.002 n=6)
```
> Optimize service sorting

- istioctl/pkg/waypoint/waypoint.go
- releasenotes/notes/50791.yaml
Fixes: #50790 
Adds the `--for` flag to the waypoint generate command so that users can preview what the flag does before they run it. It should show what the update looks like with the `istio.io/waypoint-for` annotation updated. Ran it locally to confirm (reviewer can reproduce this the same way):
Create local istioctl build with this change:
```
azureuser@dev-2024:~/istio$ make istioctl 
azureuser@dev-2024:~/istio$ alias ik=./out/linux_amd64/istioctl                                                                    
azureuser@dev-2024:~/istio$ ik
```
Ran the command for the different options and got the following expected results:
**Not an existing option:**
```bash
azureuser@dev-2024:~/istio$ ik x waypoint generate --for foobar …
```
> Add --for to waypoint generate to allow preview of yaml

- pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
Some remaining code comments now contradict the current state of things since issue #50572 changed `istio.io/use-waypoint` to be label instead of an annotation.
This PR cleans that up to maintain consistency.
> clean up remaining references to use-waypoint being an annotation

- tests/integration/helm/install_test.go
- tests/integration/helm/upgrade/helm_upgrade_test.go
- tests/integration/helm/upgrade/util.go
- tests/integration/helm/util.go
Instead of upgrading from `.0`. For instance, if latest `N-1` release is 1.21.2, the test deploys Istio 1.21.2 (not 1.21.0 as it does today) and then performs an upgrade to the current dev version.
For this we make use of the `~` in the version parameter of `helm install`. Instead of invoking e.g., `helm install  --version 1.21.0`, we use `helm install --version ~1.21.0`. This instructs helm to install the latest patch release in 1.21.x: https://helm.sh/docs/chart_best_practices/dependencies/#versions
While on it, removed the workaround for 1.17. It's EOL.
> helm upgrade tests: Upgrade from latest patch release

- pilot/pkg/features/ambient.go
- tests/integration/ambient/baseline_test.go
This means out of mesh traffic like Prometheus can never reach Waypointed workloads. A service captured one must also be workload captured to make prom traffic go through the Waypoint.
> turn off default allow waypoint by default

- pilot/pkg/model/sidecar.go
- pilot/pkg/model/sidecar_test.go
- releasenotes/notes/sidecar-port-merge.yaml
K8s servie merge in sidecar is broken since https://github.com/istio/istio/pull/48896. When a sidecar is defined with two egress listeners  pointing to two ports, the port merge does not happen
```
egress:
- hosts:
- '*/foo.svc.cluster.local'
port:
name: tcp-port1
number: 7443
protocol: TCP
- hosts:
- '*/foo.svc.cluster.local'
port:
name: tcp-port2
number: 7442
protocol: TCP
```
With the above sidecar, the merged service will only have one port and hence only cluster is created.
> fix port merge of kubernetes services in sidecar

- tests/integration/README.md
Update integration README by adding a missing command-line flag `-istio.test.skip` and fixing typos.
> Update integration README by adding a missing command-line flag and fixing typos

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
- releasenotes/notes/49700.yaml
fixes #50841 
changes `#none` to `none` for use-waypoint
removes the totally undocumented `~` optional alias for opting out of a waypoint
updates original release note to include correct information about how this feature will function
> change #none to none for use-waypoint

- cni/pkg/plugin/plugin.go
- cni/pkg/plugin/plugin_test.go
This change handles the case where `PrevResult` is `nil`, as in the case when using `Multus`, e.g. on OpenShift.
Before this fix, we get this error:
```
error adding container to network "istio-cni": istio-cni panicked during cmdAdd: interface conversion: types.Result is nil, not *types100.Result
```
> Fix ambient cni on OpenShift

- istioctl/pkg/waypoint/waypoint.go
adds a check for the waypoint name to ensure user doesn't create a waypoint named `none`
fixes #50873
example output:
```
$ out/linux_amd64/istioctl x waypoint apply --name none
Error: failed to create gateway: invalid name provided for waypoint, 'none' is a reserved value
```
> validation of waypoint name for istioctl

- bin/update_deps.sh
- cni/deployments/kubernetes/Dockerfile.install-cni
- docker/Dockerfile.distroless
- pilot/docker/Dockerfile.proxyv2
- pilot/docker/Dockerfile.ztunnel
- releasenotes/notes/apko-distroless.yaml
Fixes https://github.com/istio/istio/issues/44510
This moves our images over to the new images added in https://github.com/istio/istio/pull/50545.
This has 2 commits: 1 replaces just our iptables one, the second replaces the other `static` ones. 
The main value is on the `iptables` one, since that is our fork and has maintenance benefits. I changed `static` as well to align there (why depend on 2 things when we can depend on 1).
> distroless: move to apko/wolfi images

- pkg/envoy/proxy.go
- pkg/envoy/proxy_test.go
We already have this logic on other code paths.
This allows a config like:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: dog-statsd
data:
custom_bootstrap.json: |
{
"statsSinks": [
{
"name": "envoy.stat_sinks.dog_statsd",
"typedConfig": {
"@type": "type.googleapis.com/envoy.config.metrics.v3.DogStatsdSink",
"address": {
"socketAddress": {
"address": "$(HOST_IP)",
"portValue": 1231
}
}
}
}
]
}
```
> bootstrap: interpolate HOST_IP like we do for native traces

- pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
- releasenotes/notes/50933.yaml
add support for istio.io/waypoint-for on gatewayClasses
> add support for istio.io/waypoint-for on gatewayClasses

- pkg/test/framework/components/istio/kube.go
- tests/integration/pilot/cni_race_test.go
- tests/integration/pilot/multiplecontrolplanes/main_test.go
This was originally set in 2021 to make the tests run on GKE/others.
Long ago, the installation automatically detects the kube-system
requirements and installs appropriately.
As-is, this means if you install the integ test on a running cluster off
GKE, it will end up with 2 CNIs and cause havoc
> tests: drop hardcoded kube-system CNI

- pilot/pkg/model/context.go
- pilot/pkg/model/gateway.go
- pilot/pkg/model/gateway_test.go
- pilot/pkg/xds/cds.go
- releasenotes/notes/push-cds-on-auto-passthrough-gateway-change.yaml
I noticed that auto-passthrough gateways created after enabling mTLS return 503 errors due to missing clusters. After investigating the implementation, I noticed that SNI DNAT clusters (in format `outbound_.<port>_.<subset>_.<hostname>`) are returned only when they are referenced by listeners, and at the same time a Gateway change triggered only LDS update. This means that mTLS must be created after creating a Gateway or the Gateway deployment must be restarted after enabling mTLS to pull all XDS resources.
**How to reproduce this issue:**
```
cat <<EOF >> istio.yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
name: control-plane
spec:
profile: minimal
meshConfig:
accessLogFile: /dev/stdout
values:
global:
network: …
```
> xds: push CDS on AUTO_PASSTHROUGH Gateway change

- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pkg/kube/krt/collection.go
- pkg/kube/krt/core.go
- pkg/kube/krt/fetch.go
- pkg/kube/krt/filter.go
- pkg/kube/krt/helpers.go
- pkg/kube/krt/informer.go
- pkg/kube/krt/internal.go
- pkg/kube/krt/join.go
- pkg/kube/krt/singleton.go
- pkg/kube/krt/static.go
- pkg/kube/krt/testing.go
- pkg/slices/slices.go
- pkg/slices/slices_test.go
- pkg/util/smallset/smallset.go
- pkg/util/smallset/smallset_test.go
For the same test workload:
Old: 9.5s, 290mb used, 22M objects allocated
Now: 7s, 250mb used, 12M objects allocated
Optimizations include:
* Introduce a new `smallset`, optimized for sets with very few items. This has huge improvements in memory and CPU for small sets. 1-2 elements are WAY faster in CPU, and memory usage is much smaller even for larger ones. In krt, the set I replaced is often 1 item so this gives big wins
* Remove erasedCollection and pass params directly. Avoid storing +comparing the full collection (expensive!) and instead give each collection a UID to compare cheaply.
> krt: various micro-optimizations

- pilot/pkg/model/context.go
- pilot/pkg/networking/core/listener_waypoint.go
- pilot/pkg/networking/core/route/route.go
- pilot/pkg/networking/core/route/route_internal_test.go
- releasenotes/notes/50452.yaml
API: https://github.com/istio/api/pull/3171
Related to https://github.com/envoyproxy/envoy/pull/33051
> cors: do not forwarded preflight request if the origin is not allowed

- pkg/config/analysis/msg/messages.gen.go
- pkg/config/analysis/msg/messages.yaml
- pkg/config/validation/validation.go
fix https://github.com/istio/istio/issues/50805
> Fix warning

- cni/pkg/plugin/testdata/dns.txt.golden
- tools/istio-clean-iptables/pkg/cmd/cleanup.go
- tools/istio-clean-iptables/pkg/cmd/testdata/dns-uid-gid.golden
- tools/istio-clean-iptables/pkg/cmd/testdata/dns.golden
- tools/istio-clean-iptables/pkg/cmd/testdata/empty.golden
- tools/istio-clean-iptables/pkg/cmd/testdata/inbound-interception-mode.golden
- tools/istio-clean-iptables/pkg/cmd/testdata/outbound-owner-groups-exclude.golden
- tools/istio-clean-iptables/pkg/cmd/testdata/outbound-owner-groups.golden
- tools/istio-iptables/pkg/capture/run.go
- tools/istio-iptables/pkg/capture/testdata/dns-uid-gid.golden
- tools/istio-iptables/pkg/capture/testdata/ip-range.golden
- tools/istio-iptables/pkg/capture/testdata/ipv6-dns-outbound-owner-groups-exclude.golden
- tools/istio-iptables/pkg/capture/testdata/ipv6-dns-outbound-owner-groups.golden
- tools/istio-iptables/pkg/capture/testdata/ipv6-dns-uid-gid.golden
- tools/istio-iptables/pkg/capture/testdata/loopback-outbound-iprange.golden
- tools/istio-iptables/pkg/capture/testdata/tproxy.golden
> iptables: use `ISTIO_OUTPUT` chain for DNS UDP rules

- tests/integration/pilot/cni/cniversionskew_test.go
https://prow.istio.io/view/gs/istio-prow/logs/integ-cni_istio_postsubmit/1788646342856282112
(should we be testing CNI from 1.11 "N-1"? Probably not)
> test: fix CNI Version Skew test

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
- pilot/pkg/config/kube/gateway/testdata/deployment/infrastructure-labels-annotations.yaml
Fixes https://github.com/istio/istio/issues/50983, I think
Basically, we have logic to use `infra.Labels || meta.Labels`. We modify
meta.Labels.
This is wrong, we should modify AFTER we pick which set of labels to
use.
Also, we need to deepcopy anything we mutate since its accessing a
shared object cache
> Fix usage of infrastructure labels/annotations on gateway

- pilot/pkg/model/endpointshards.go
- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
TBH I am not sure how this isn't a bigger issue. Currently if an
endpoint changes we are not triggering a push at all. In this case, it
was port number, but could be others.
Implementation is *bad* right now, but if this is desired we can swap
for an optimized Equals implementation
> pilot: fix bug in endpoint updates

- pilot/pkg/networking/core/listener_waypoint.go
- pilot/pkg/networking/core/route/retry/retry.go
- pilot/pkg/networking/core/route/retry/retry_test.go
- pilot/pkg/networking/core/route/route.go
- pilot/pkg/networking/core/route/route_test.go
Fixes https://github.com/istio/istio/issues/50756
> do not add previous hosts predicate when consistent hashing is enabled

- pilot/pkg/model/push_context.go
- pilot/pkg/networking/core/extension/wasmplugin.go
- pilot/pkg/networking/core/extension/wasmplugin_test.go
- pilot/pkg/networking/core/extension_config_builder.go
Fixes https://github.com/istio/istio/issues/51014
Need tests
The issue is in the LDS gen we lookup with Service, but in the ECDS request we don't so we don't find it.
Actually, the lookup in ECDS is not needed in general, not just in ambient: the proxy already requested a lsit of names, so we can just return those.
> ambient: fix WasmPlugin bind to Service

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_test.go
- releasenotes/notes/51044.yaml
Istio Stackdriver metrics are implemented using the OpenCensus SDK. As OpenCensus is deprecated, this PR removes the XDS programming of the Istio Stackdriver metrics from Istio. 
Istio Stackdriver logs are not implemented using the OpenCensus SDK and are not removed in this PR.
Related issue: https://github.com/istio/istio/issues/50808.
- [ X] Policies and Telemetry
> Remove Istio stackdriver metrics from XDS

- istio.deps
- releasenotes/notes/51072.yaml
- tests/integration/telemetry/tracing/tracing.go
fix: https://github.com/istio/istio/pull/51039
related to https://github.com/envoyproxy/envoy/pull/34062 and https://github.com/envoyproxy/envoy/issues/34063
> fix span name when using the OpenTelemetry tracing provider

- pkg/kube/kclient/client.go
- pkg/kube/kclient/client_test.go
- pkg/kube/namespace/filter.go
Example crash https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-126_istio_postsubmit/1790453700397895680
> Fix data race in discovery filter

- pilot/pkg/networking/core/envoyfilter/listener_patch.go
It's easy to misread with `patchHTTPFilters` and `patchHTTPFilter`.
`patchHTTPFilter` only handle `MERGE` opteration, rename it would be better to understand.
> rename confused function

- cni/pkg/nodeagent/net.go
- cni/pkg/nodeagent/net_test.go
- releasenotes/notes/51081.yaml
A user is (somehow) able to produce a scenario where, without `istio-cni` restarting, a pod IP goes `missing` from the host node ipset, causing an active pod to begin failing host node healthchecks.
Since we destructively mutate the ipset contents in _exactly_ 3 spots:
1. Flush on `istio-cni` startup
2. Flush/destroy on `istio-cni` shutdown
3. Removing pod IPs on K8S pod unlabel/delete events
and no `istio-cni` restart happens as per logs, that leaves (3) as the only way this could manifest, barring outside interference with the contents of the ipset.
The only scenario where I can imagine this happening is if 
- two pods reuse the same IP relatively close to each other on the same node.
- K8S `pod add` and `pod remove` events for those two pods both overlap, and come in to us out-of-order …
> Explicitly fail when we are asked to add a duplicate ip to the ipset

- pilot/pkg/networking/core/cluster.go
- pilot/pkg/networking/core/cluster_builder.go
- pilot/pkg/networking/core/cluster_builder_test.go
- pilot/pkg/networking/core/cluster_waypoint.go
- releasenotes/notes/alt-stat-name.yaml
Regression caused in https://github.com/istio/istio/pull/46352 . The code has been removed
> fix altstatname for subset clusters

- pkg/config/validation/validation.go
It's not obvious to the user that it is intended for the policy object's namespace to be used and that they shouldn't set the namespace for targetRef. This PR updates the validation message to make this clearer and adds a comment adding context to why we do this.
Notes for reviewer(s):
- message in this PR uses language from the API comment/description of the Namespace field on PolicyTargetReference shown [here](https://github.com/istio/api/blob/aa8be1710a492e2a31cf0949fbe9eae0c14d1a5a/type/v1beta1/selector.pb.go#L263-L265)
- context for why we do [this](https://github.com/istio/istio/pull/46621/files#r1318048974)
- context around [user experience](https://istio.slack.com/archives/C049TCZMPCP/p1716303337650699?thread_ts=1716258271.529259&cid=C04 …
> Make validation message clearer when user attempts to set namespace for targetRef

- cni/pkg/iptables/iptables.go
- cni/pkg/iptables/iptables_test.go
- cni/pkg/iptables/testdata/default_ipv6.golden
- cni/pkg/nodeagent/net.go
- releasenotes/notes/51221.yaml
This should have been in https://github.com/istio/istio/pull/50747 but somehow I looked at that (and the goldens!) and _didn't_ recognize that using a v4 ip in a v6 rule was wrong.
> Bugfix: actually use v6 SNAT IP inpod

- samples/bookinfo/src/details/Gemfile.lock
It is best practice to include Gemfile.lock. Adding that to bookinfo.
More platforms are supported, but they can be added as-tested; the "ruby" entry should make it work platform-independently most of the time any way.
> Adding Gemfile.lock to bookinfo

- security/pkg/nodeagent/sds/sdsservice.go
Without this, when we call Initialize we are not always referring to the
same BaseConnection
> agent sds: fix log of connection line

- security/pkg/server/ca/server.go
Update error message to point to something useful to fix the error when CA_TRUSTED_NODE_ACCOUNTS is not set. 
https://istio.slack.com/archives/C041EQL1XMY/p1716558663964619
> Update error message for node authorizer

- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pilot/pkg/serviceregistry/serviceentry/store.go
- pilot/pkg/serviceregistry/serviceentry/store_test.go
- pilot/pkg/serviceregistry/serviceentry/util.go
- pkg/config/kube/conversion.go
Some miscellaneous refactorings and optimizations:
1. ~fix typo: `initialSyncTimedout` -> `initialSyncTimeout`~
2. remove redundant set options, remove `ConvertServiceEntry` function
3. extract a `isDNSTypeServiceEntry` function
4. set capacity when initializing slices in some places
5. for other information, see code comments
> minor refactor and optimize serviceregistry

- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- pilot/pkg/serviceregistry/serviceentry/store.go
- pilot/pkg/serviceregistry/serviceentry/store_test.go
- pkg/config/model.go
Fixes #51212
In draft since I will probably go and add more comments, etc
Root cause is we key on `hostname+namespace` and delete instances. But we actually need to take into account which SE its from, otherwise if 2 SE share the same hostname, removal of one removes all instances
> pilot: fix double SE deletion

- cni/pkg/plugin/plugin.go
- cni/pkg/plugin/plugin_cni_conformance.go
The K8sArgs struct should be in sync with the k/v map returned by the containerd `toCNILabels` function. This PR adds the missing `K8S_POD_UID` CNI label.
Fixes #51292
> CNI Plugin: Adds K8S_POD_UID Field to K8sArgs Struct

- cni/pkg/ipset/nldeps_linux.go
Fix log wording, remove extra info so it's less confusing (we only have TCP ipsets, the proto is always `unix.IPPROTO_TCP` which _happens_ to be `6` - but this has nothing to do with ipv6)
> fix log wording, drop `PROTO` (it's hardcoded anyway)

- cni/pkg/repair/netns.go
Currently, repair logic is broken on any platform that does not have a /32 route entry in the host netns for each pod.  Specifically seeing failures in AKS using Kubenet and EKS using Amazon VPC CNI, but this also applies to Cilium users.  With this we check for the matching interface ip existence across all proc netns's directly, which should avoid the issue.
> Change pod repair getPodNetNs logic to not rely on /32 route in host ns.

- cni/pkg/nodeagent/informers.go
- cni/pkg/nodeagent/informers_test.go
- cni/pkg/nodeagent/net.go
- cni/pkg/nodeagent/pod_cache.go
- cni/pkg/nodeagent/server.go
- cni/pkg/util/podutil.go
When `istio-cni` (re)starts up, we build a snapshot of currently-enrolled ambient pods, which we send to ztunnel. This is to make sure a new ztunnel client connection always gets the current set of enrolled pods.
We cannot rely on the informer for this, because it is (correctly) designed to not-enroll pods that have already been marked as enrolled.
The informer decides whether it should do something with a new pod event by looking at
-  user _intent_ (the `istio.io/dataplane-mode=ambient` label)
- actual state (the `ambient.istio.io/redirection=enabled` annotation)
and reconciling any mismatch between the two. There is of course a time window/delta between someone labelling a pod with _intent_, and then k8s telling us about it, and us actually …
> Ambient: Fix bug with initial node agent snapshot create

- istioctl/pkg/writer/ztunnel/configdump/api.go
- istioctl/pkg/writer/ztunnel/configdump/configdump.go
- istioctl/pkg/writer/ztunnel/configdump/connections.go
- istioctl/pkg/writer/ztunnel/configdump/policies.go
- istioctl/pkg/writer/ztunnel/configdump/services.go
- istioctl/pkg/writer/ztunnel/configdump/workload.go
- istioctl/pkg/ztunnelconfig/ztunnelconfig.go
Related to #51217 
This PR gets the zc command not breaking and functional again for things like `istioctl zc all`, `istioctl zc workload` etc. by updating ZtunnelDump struct types to slice instead of map.
**Notes for Reviewer(s):** can manually confirm this by checking out this branch and running zc commands (e.g. `go run ./istioctl/cmd/istioctl zc all`)
> istioctl: update ZtunnelDump struct to unmarshall data correctly

- tests/fuzz/oss_fuzz_build.sh
I think this was some legacy stuff no longer needed. I guess we will
see...
Either way, its broken as-is.
> Attempt to fix fuzzing build

- samples/bookinfo/platform/kube/bookinfo-db.yaml
- samples/bookinfo/platform/kube/bookinfo-details-dualstack.yaml
- samples/bookinfo/platform/kube/bookinfo-details-v2.yaml
- samples/bookinfo/platform/kube/bookinfo-details.yaml
- samples/bookinfo/platform/kube/bookinfo-dualstack.yaml
- samples/bookinfo/platform/kube/bookinfo-mysql.yaml
- samples/bookinfo/platform/kube/bookinfo-psa.yaml
- samples/bookinfo/platform/kube/bookinfo-ratings-dualstack.yaml
- samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql-vm.yaml
- samples/bookinfo/platform/kube/bookinfo-ratings-v2-mysql.yaml
- samples/bookinfo/platform/kube/bookinfo-ratings-v2.yaml
- samples/bookinfo/platform/kube/bookinfo-ratings.yaml
- samples/bookinfo/platform/kube/bookinfo-reviews-v2.yaml
- samples/bookinfo/platform/kube/bookinfo.yaml
- samples/bookinfo/src/productpage/templates/productpage.html
Some tests rely on checking for the specific output from the productpage (e.g. `glyphicon glyphicon-star` to check whether stars are rendered). 
With the re-design, we're not using glyphicons anymore, so this change adds an`id: glyphicon glyphicon-star` to the SVG element, so we don't have to change all tests.
> add the id to the svg element in productpage

- istioctl/pkg/waypoint/waypoint.go
- releasenotes/notes/add-overwrite-flag.yaml
Fixes: #51312 
This PR adds an --overwrite flag to force users to explicitly declare that they want to override the namespace's labeled use-waypoint value. If a user doesn't provide the flag, then --enroll-namespace won't add the new waypoint and will instead give them a warning:
```bash
azureuser@dev-2024:~/istio$ go run ./istioctl/cmd/istioctl x waypoint apply --for all --name test2 --enroll-namespace --overwrite
waypoint default/test2 applied
namespace default labeled with "istio.io/use-waypoint: test2"
azureuser@dev-2024:~/istio$ go run ./istioctl/cmd/istioctl x waypoint apply --for all --name test3 --enroll-namespace
Warning: namespace (default) already has an enrolled Waypoint. Consider adding the `--overwrite` flag to your apply command. …
```
> istioctl: add overwrite flag for enroll-namespace

- pilot/pkg/model/sidecar.go
If a Service is selected multiple times (might happen if it's a destination of multiple routes or multiple VirtualServices), we currently **always DeepCopy the service** even though it's not actually needed and nothing is actually changing.
Changes proposed:
- fast equals check to see if the service being added is already present (this only actually succeeds if the service has not been copied by some other process, but should be true for most cases unless sidecar egress is matching a subset of ports of a service, even so, it's mostly free to make this check)
- ignore services with the same hostname and the same ports, since we're not gonna merge them anyways
Data:
We're currently seeing `Service.DeepCopy()` spending ~5% of cpu and …
> optimize: sidecar service selection and merge

- pilot/pkg/model/gateway.go
- pilot/pkg/model/gateway_test.go
In real world we have seen this use 10% total Istiod CPU. It is trivial to optimize.
Technically we could get rid of the last allocation too but its more complex.
```
name                         old time/op    new time/op    delta
ParseGatewayRDSRouteName-16     227ns ± 8%      66ns ± 7%  -70.77%  (p=0.000 n=10+10)
name                         old alloc/op   new alloc/op   delta
ParseGatewayRDSRouteName-16      184B ± 0%        8B ± 0%  -95.65%  (p=0.000 n=10+10)
name                         old allocs/op  new allocs/op  delta
ParseGatewayRDSRouteName-16      4.00 ± 0%      1.00 ± 0%  -75.00%  (p=0.000 n=10+10)
```
> Optimize ParseGatewayRDSRouteName

- cni/pkg/nodeagent/informers.go
- cni/pkg/nodeagent/informers_test.go
- cni/pkg/nodeagent/net.go
- cni/pkg/nodeagent/net_test.go
- pkg/kube/util.go
- releasenotes/notes/51429.yaml
Original:
Similar to https://github.com/istio/istio/pull/51081 - in the *real* world we may have misconfigured IPAM or other problems, and during initial snapshot of the node, we could get 2 pods with the same IP.
This is an error state for the cluster generally, and there's not much we can do about it, but one thing we _can_ do is skip the problem pod and carry on processing the rest, rather than immediately stopping and returning an error.
Updated:
Retain above, but actual root cause is K8S terminated jobs never triggering Delete events (k8s keeps them around), effectively letting terminated job pods eat up IPs in the ambient ipset. Fix this by special casing terminated pods - we now explicitly unenroll all pods that enter a terminated state, regardless of other labels or annotations.
> Ambient CNI informer: K8S job pods must be handled uniquely

- istioctl/pkg/writer/ztunnel/configdump/configdump.go
- istioctl/pkg/writer/ztunnel/configdump/configdump_test.go
- istioctl/pkg/writer/ztunnel/configdump/workload.go
- istioctl/pkg/ztunnelconfig/ztunnelconfig.go
Related to: #50655
I went to add more verbosity to the ztunnel-config command and realized we have a command that already does this. It just always defaulted to true and didn't actually do anything. This PR updates it to actually make the `--verbose` flag toggle verbosity when it's used:
**without** update:
```bash
azureuser@dev-2024:~/istio$ go run ./istioctl/cmd/istioctl zc w
NAMESPACE          POD NAME                              IP          NODE                        WAYPOINT PROTOCOL
default            test1-6484bd9cd9-l7rmh                10.244.0.9  istio-testing-control-plane None     TCP
default            test2-b8dc7b5c9-55pt8                 10.244.0.10 istio-testing-control-plane None     TCP
istio-system …
```
> istioctl: remove --verbose flag since it should be the default column output anyway

- cni/pkg/nodeagent/cni-watcher.go
- cni/pkg/nodeagent/cni-watcher_test.go
- cni/pkg/nodeagent/informers.go
I ran into this in an *extremely* bespoke and unsupported environment,
but I think it could occur in real world. We are looping outside of
GetPodIfAmbient for the pod to show up, but if it fails we panic. We
want to instead get an error.
> ambient: fix nil pointer when pod cache is stale

- pkg/config/security/security.go
The underlying boringssl version used in envoy no longer supports CECPQ2 for TLS groups, and is upgraded to use X25519Kyber768Draft00. Reflect this usage accurately in Istio by removing CECPQ2, and enabling X25519Kyber768Draft00
The dependency of istio -> proxy -> envoy -> boringssl is the following: 
Istio -> proxy : [proxy SHA]( https://github.com/istio/istio/blob/master/istio.deps#L7)
Proxy -> envoy: [envoy SHA](https://github.com/istio/proxy/blob/1678bacbcdbc833935ac33a4efbfd59fb6600ef3/WORKSPACE#L26) 
Envoy -> boringssl: [boringssl version](https://github.com/envoyproxy/envoy/blob/a1c5de9500a96553186935a288efaeef47ddbaf0/bazel/repository_locations.bzl#L114-L132)
BoringSSL - [supported …
> update supported groups for TLS

- security/pkg/nodeagent/sds/server.go
Fixes #51433
Commit is moving and changing the "SDS has started" message since it will never be printed at the right time due to Server() being blocking.
> Minor improvement to sds init logging

- tests/integration/ambient/cnirepair/main_test.go
- tests/integration/ambient/main_test.go
We have 3 sidecar configs, but 2 are unused and never applied. This
doesn't change tests at all, just removes dead code
> ambient: cleanup sidecar tests

- samples/bookinfo/src/details/details.rb
- samples/bookinfo/src/productpage/Dockerfile
- samples/bookinfo/src/productpage/productpage.py
- samples/bookinfo/src/productpage/requirements.in
- samples/bookinfo/src/productpage/requirements.txt
bookinfo has 3 major performance bottlenecks:
* Productpage doesn't allow keepalives on incoming requests
* Productpage does not pool outgoing requests
* Details does not set tcp_nodelay
These all add up to some terrible performance attributes. This doesn't really matter but people like to use this for benchmarks which skews results in silly ways. Also, sometimes productpage is so slow its noticeable to humans.
I did not add pooling for outgoing since it impacts some of our tests which want to hit a random backend each time
Before: ~150qps. After: 1.5k qps
> Make bookinfo not really slow

- pilot/test/xds/fake.go
This allows testing gatewayclass changes as well. Splitting this out to
make things a bit more clean
> ambient tests: add all CRDs for unit tests

- pilot/pkg/bootstrap/server.go
- pilot/pkg/bootstrap/server_test.go
- pilot/pkg/bootstrap/webhook.go
- releasenotes/notes/51506.yaml
Previously, remote clusters utilizing a control plane running on a different cluster weren't able to check whether the control plane is ready, because the readiness handler was only exposed over http, which is only accessible within the pod. Now, the control plane's readiness status is also exposed via https, allowing tooling in a remote cluster to check the control plane's readiness.
> Enable remote readiness checks over https

- pkg/ctrlz/ctrlz.go
Due to differences in gorilla mux and default mux, the copy+paste from
the other pprof code results in 404 for the things outside of index.
Re-order to fix.
This brings up a new issue - default pprof time is too long for our
write timeout. Increase it.
> cni: fix running profile

- pkg/config/validation/validation.go
We validate them again a few lines later. This should have ~no impact
though
> validation: avoid double validation of labels

- pilot/pkg/model/envoyfilter.go
When I see the error log below, I don't know which configuration is wrong.
```
2024-06-12T20:19:21.417789Z	error	model	failed to build envoy filter value: Envoy filter: json: cannot unmarshal number -1 into Go value of type uint32
```
> envoyfilter build error log add flag

- cni/pkg/log/uds.go
- cni/pkg/log/uds_test.go
Fixes https://github.com/istio/istio/issues/51494
We dropped these on the floor when we unmarshal into a struct with only
static fields
> cni: fix k/v pairs in UDS logging from plugin

- pilot/pkg/networking/core/cluster.go
- pilot/pkg/networking/core/cluster_builder.go
- pilot/pkg/networking/core/cluster_builder_test.go
- pilot/pkg/networking/core/cluster_test.go
- pilot/pkg/networking/core/listener_builder_test.go
- pilot/pkg/networking/core/listener_inbound.go
- pilot/pkg/networking/core/listener_test.go
- pilot/pkg/networking/core/listenertest/match.go
- pilot/pkg/networking/core/peer_authentication_simulation_test.go
- pilot/pkg/networking/core/sidecar_simulation_test.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/simulation/traffic.go
- pilot/pkg/xds/delta_test.go
- pilot/pkg/xds/deltatest.go
There is no need for 2 clusters/filter chains now, envoy can handle this
directly
However, this is slgiht breaking change -- the cluster name changes,
which can be used for XDS matching in Envoyfilter and stats. Worse,
istio/proxy itself has hardcoded semantics around the cluster name. I
think we can just fix istio/proxy and release note the rest.
Currently a draft to fix tests and istio/proxy, pending feedback on if ^ is acceptable
> pilot: collapse to single inbound passthrough

- pilot/pkg/model/telemetry_logging.go
- pilot/pkg/model/telemetry_logging_test.go
- pilot/pkg/model/telemetry_test.go
- pilot/pkg/networking/core/accesslog_test.go
- releasenotes/notes/48882.yaml
This PR reverts the changes made in https://github.com/istio/istio/pull/48882 due to an bug in envoy where all numbers are logged as floating numbers. When removing sorting, a different serializer is used in envoy ensuring consistent behaviour.
Envoy issue: https://github.com/envoyproxy/envoy/issues/34420.
Another approach would be to add sorting of json output as a mesh option, but I am unfamiliar with the definition of the meshconfig, and if that woul be a viable approach?
> disable sorting of JSON logging by default due to float serialization in envoy

- pilot/pkg/serviceregistry/kube/controller/controller.go
This is a perfectly valid Kubernetes config; its fine to have a named
targetPort not found, it just excludes the endpoint
> logging: drop excessive warning

- istioctl/pkg/waypoint/waypoint.go
- releasenotes/notes/51559.yaml
- Adds a flag for retrieving waypoint status (resolves: #51294)
- Updates unnecessary uses of `PersistentFlags` to `Flags` instead. [PersistentFlags](https://github.com/spf13/cobra/blob/main/site/content/user_guide.md#persistent-flags) should only be used if a flag is intended to be a global flag. The following flags are not global, but instead are [local flags](https://github.com/spf13/cobra/blob/main/site/content/user_guide.md#local-flags) and were updated to reflect this:
- `waypointApplyCmd.Flags().StringVarP(&revision, ...)`
- `waypointApplyCmd.Flags().BoolVarP(&waitReady, ...)`
- `waypointGenerateCmd.Flags().StringVarP(&revision, ...)`
- `waypointListCmd.Flags().BoolVarP(&allNamespaces, ...)`
- …
> istioctl: add subcommand for retrieving waypoint status

- tests/integration/ambient/cni/main_test.go
This does nothing but add a test to ensure that disrupting `istio-cni` itself does not negatively impact established pod dataplanes.
This is not a recommendation that people SHOULD do this, as in the real world it is unsafe and would miss new pods, but this is a decent way to verify that 
- properly established pod ambient dataplanes do not have a hard, continuous dependency on `istio-cni` being healthy.
- `ztunnel` can continue to manage established pods happily even if `istio-cni` drops out
> Add test to ensure `istio-cni` disruption does not impact established ambient pod dataplane

- pilot/pkg/serviceregistry/kube/controller/ambient/services.go
Currently, we treat LB IP as just another ClusterIP. This is not
correct. Load Balancer IP's are opaque, we cannot just elide them and
proxy directly to pods. The LB may implement arbitrary behavior outside
of our scope.
The correct behavior (also matching sidecars, etc) is to treat these as
opaque traffic that we proxy as-is
> ambient: do not include LoadBalancer IP in Service VIPs

- pilot/pkg/model/context.go
- pilot/pkg/model/gateway.go
- pilot/pkg/model/gateway_test.go
- pilot/pkg/xds/cds.go
- Fix typo
- Add AutoPassThroughSNIHosts to MergedGateways similar to PrevMergedGateways and compute once instead of in Get
> compute autpassthroughsni hosts once for merged gateways

- istioctl/pkg/writer/pilot/status.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/delta.go
- pilot/pkg/xds/statusgen.go
- pkg/xds/server.go
- releasenotes/notes/istioctl-ps-improvements.yaml
This PR makes a few improvements to proxy-status:
* Report the timestamp of the last message. This is critical, and we used to have it in `ps` but it was removed. Without this, we do not know if something is stale for 10ms or 10minutes -- a HUGE difference.
* We incorrectly report unsubscribed types as "Not sent". These are **not going to be sent** so they should be marked as IGNORED. 
* Report all types. We do not yet show them in `istioctl ps` but as a followup I would like to add an `-ojson` to `istioctl ps`. `x internal-debug syncz` does have them though.
```
NAME                                                   CLUSTER        CDS         LDS         EDS         RDS          ECDS         ISTIOD                      VERSION
istio-ingressgateway-64b44c89cd-hnzgz.istio-system …
```
> Enhancements to proxy-status

- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
I am aware there are no automated tests on this; I am working to add
these but it is very challenging to automate these types of tests that
there is zero-downtime on rollout. I think its best to get this in
in-parallel to test development.
> ambient: properly mark pod as not ready when it is shutting down

- pilot/pkg/model/jwks_resolver.go
- pilot/pkg/model/jwks_resolver_test.go
- releasenotes/notes/51636.yaml
When there is an error fetching a JWKS URI in the main flow (i.e. when generating configuration), an immediate background refresh is triggered. However this is only a partial refresh and will only fetch URIs that don't have an entry in the cache, i.e. the URIs that had errors, in the hope that the requests will succeed and the keys can be sent to the affected proxies.
When this partial refresh was triggered, the background refresh ticker was being reset. So there would be a longer delay before any URIs already in the cache would be fetched again to see if there are any changes.
The default interval between refreshes is 20 minutes, and there is exponential backoff on failure up to 60 minutes, so in the case of a busy istiod, and a single invalid URI, there may never be an interval that …
> Don't reset the jwks refresh ticker on URI fetch errors

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
This adds support for reading EndpointSlice addresses in ambient. This works by getting all non-pod addresses and sending them over.
The #1 use case is the `kubernetes.default.svc` service. This has a test case, and it was intentionally broken in https://github.com/istio/ztunnel/commit/636c69c6176456f50bfa9ce3ec7698f3d344c133. That is why this PR does not have any new e2e tests; they already exist and are broken with ztunnel from HEAD (ztunnel has not update as a result).
Fixes https://github.com/istio/istio/issues/51539
> ambient: support explicit EndpointSlice endpoints

- pkg/kube/kclient/client.go
- pkg/kube/kclient/client_test.go
- pkg/kube/kclient/delayed.go
- pkg/kube/kclient/index.go
- pkg/kube/kclient/index_test.go
- pkg/kube/kclient/interfaces.go
- pkg/kube/krt/index.go
- pkg/revisions/tag_watcher.go
- security/pkg/server/ca/node_auth.go
Before: we register an informer handler which builds our own index on
top of the underlying store.
After: we register an index directly into the informer, which handles
things entirely.
This was not done originally because Kubernetes only added the ability
to add indexes dynamically recently (I added this).
The benefits here are:
* Deterministic ordering. The index is ALWAYS updated before any other
handlers are called. This allows us to guarantee the index is up to
date in our handlers. Without this, we had the crazy Delegate hack.
* Minor performance benefit from not needing to cut through as many
abstractions or locking.
K8s indexes are actually a pain to use, so kclient provides a higher
level API over it; the same as what we had before. One quirk is they
only allow string keys. To …
> kclient: use internal indexes instead of external

- pilot/pkg/model/jwks_resolver.go
- pilot/pkg/model/jwks_resolver_test.go
- releasenotes/notes/51636.yaml
Cherry picks #51637 
There was a function signature change so the automated CP (https://github.com/istio/istio/pull/51680) failed, this includes the fix
> [release-1.20] Don't reset the jwks refresh ticker on URI fetch errors

- pilot/pkg/model/jwks_resolver.go
- pilot/pkg/model/jwks_resolver_test.go
- releasenotes/notes/51636.yaml
Cherry picks #51637 
There was a function signature change so the automated CP (https://github.com/istio/istio/pull/51681) failed, this includes the fix
> [release-1.21] Don't reset the jwks refresh ticker on URI fetch errors

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/ingress/controller.go
- pilot/pkg/model/config.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
Trades slight complexity for better performance.
Please note that since `BenchmarkInitPushContext` does not set `CreationTimestamp` for the resources, the time of the resources are the same, which causes the `name/namespace` comparison to be performed when sorting, which is the main reason why the benchmark shows a significant improvement in performance. In a production environment, there are generally not too many resources with the same `CreationTimestamp`, so the overall performance improvement of this optimization is limited.
```
goos: darwin
goarch: amd64
pkg: istio.io/istio/pilot/pkg/xds
│   old.txt    │               new.txt               │
│    sec/op    │    sec/op     vs base               │
InitPushContext/gateways-12 …
```
> Optimize resource sorting performance

- pkg/log/logr_test.go
- pkg/log/scope.go
- pkg/log/scope_test.go
in withLabels we do a copy. Copy of atomic.Value is bad, and makes it so the updates no longer work -- instead we want to just copy the pointer
> log: fix race when updating output level and cloning

- cni/pkg/iptables/iptables_linux.go
- cni/pkg/nodeagent/informers.go
- cni/pkg/nodeagent/informers_test.go
- cni/pkg/nodeagent/net.go
- cni/pkg/nodeagent/net_test.go
- cni/pkg/nodeagent/server.go
- cni/pkg/nodeagent/server_test.go
- cni/pkg/nodeagent/ztunnelserver.go
Followup to https://github.com/istio/istio/pull/51429.
When a pod is moved to terminal stage, we call RemovePodFromMesh. This
has a variety of cleanup steps, and aborts early if any fail.
Because the pod is terminated, we will fail to cleanup the in-pod rules.
This is OK! The pod is terminated anyways. But with the current logic,
this also means we do not send ztunnel the removed message, and it will
leak proxy instances.
Additionally, this does a variety of logging cleanups so that we
consistently format messages and always show which pod we are acting on.
> cni: properly cleanup completed pods

- pilot/pkg/serviceregistry/aggregate/controller.go
- pilot/pkg/serviceregistry/aggregate/controller_test.go
- pkg/slices/slices.go
- releasenotes/notes/serviceregistry-order.yaml
* add kubernetes registry infront of serviceentry
* add test
* address comments
* fix lint
* fix lint
> [cherry-pick 1.20] Add kubernetes registry in front of ServiceEntry (#51003)

- cni/pkg/nodeagent/ztunnelserver.go
- cni/pkg/plugin/cnieventclient.go
This was being consistently hit when concurrently spawning pods due to a
bug in iptables causing it to wait too long for the lock (if it cannot
obtain the lock, it would always wait on 1s intervals). This is fixed in
https://github.com/istio/istio/pull/51738.
This extends the timeout to not be so aggressive; a hard 1s deadline to
manipulate iptables rules and make write calls to the API server is
pretty tight deadline. Additionally, if we do hit the deadline, improve
the error logs.
> cni: extend timeout for command and improve logs

- cni/pkg/iptables/iptables_linux.go
- cni/pkg/nodeagent/informers.go
- cni/pkg/nodeagent/informers_test.go
- cni/pkg/nodeagent/net.go
- cni/pkg/nodeagent/net_test.go
- cni/pkg/nodeagent/server.go
- cni/pkg/nodeagent/server_test.go
- cni/pkg/nodeagent/ztunnelserver.go
> [1.22] cni: properly cleanup completed pods (#51713)

- pilot/pkg/networking/core/listener_inbound.go
- tests/integration/ambient/baseline_test.go
Fixes https://github.com/istio/istio/issues/51336.
Currently, we do not support HBONE on arbitrary ports like we do for non-hbone. This breaks things like prometheus scraping, etc.
This PR simply adds the chains to do so. That is fairly trivial. It also adds a variety of test cases
> Enable inbound passthrough for hbone sidecars

- pkg/test/framework/components/prometheus/kube.go
The `telemetryNamespace` works as expected except for substituting the namespace of the subjects for the ClusterRoleBinding. 
```
subjects:
- kind: ServiceAccount
name: prometheus
```
Replacing all instances of `namespace: istio-system` in the YAML before applying the configuration solves this. I hard coded `istio-system` as the user can change the `systemNamespace` variable and `istio-system` is set in [samples/addons/prometheus.yaml](https://github.com/istio/istio/blob/77fda683f0d37a23879e1e258d9d82e1d0844eec/samples/addons/prometheus.yaml)
> substitute default ns for  telemetryNs in yaml for prom install

- cni/pkg/nodeagent/fakes_test.go
- cni/pkg/nodeagent/net.go
- cni/pkg/nodeagent/net_test.go
Few minor tweaks.
1. Make sure we unconditionally drop our netns reference on pod removal if we have one, regardless of whether it's a delete or not (it's _probably_ fine if we do not, but there's no reason not to be eager + consistent with it to avoid the opportunity for leaking netns refs)
2. Make sure we unconditionally remove the ip from the set on pod removal, even if there are later errors.
3. Add some tests to fence the above behaviors.
> Make sure we always Take() the netns, always remove the IP, and fence with more tests

- cni/pkg/iptables/iptables.go
- cni/pkg/iptables/iptables_test.go
- cni/pkg/nodeagent/net.go
- cni/pkg/nodeagent/net_test.go
- cni/pkg/nodeagent/server.go
- cni/pkg/plugin/sidecar_iptables_linux.go
- tools/istio-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/config/config.go
- tools/istio-iptables/pkg/dependencies/implementation.go
- tools/istio-iptables/pkg/dependencies/implementation_linux.go
"CNIMode" was a mode added to control how IPTables rules are executed
when running like CNI. In particular, that means we are in the host
filesystem, but the pod network namespace. In this case, we would be
fetching the node level lock which doesn't make sense. There is also
some crazy NSS interactions on some platforms; notably, in GKE, this can
lead to ~1min pod startup times.
Another issue with the locking is a bug in some versions of iptables,
including the one in 1.22. In these versions, `--wait` only acts on 1s
intervals. So if I start many pods at the same time, they will take
`NPods seconds` to start. This is observed in real world clusters almost
100% consistently when many cronjobs trigger pods at the same time. By
avoiding the lock, we sidestep this problem.
Because ambient …
> ambient: use "CNIMode" (now renamed) for inpod rules

- pkg/test/framework/components/echo/common/deployment/echos.go
- pkg/test/framework/components/echo/common/deployment/external.go
- pkg/test/framework/components/echo/config.go
- pkg/test/framework/components/echo/echotest/filters.go
- pkg/test/framework/components/istio/kube.go
- tests/integration/security/reachability_test.go
At couple of places in the integration tests, we use `RequireDualStack` or `SingleStack`. 
This PR modifies the code to use constants and also updates the API comments to match the latest tests.
> Use constants for the ipFamilyPolicy

- pkg/test/fakes/imageregistry/Makefile
- pkg/test/fakes/imageregistry/main.go
- pkg/test/framework/components/registryredirector/kube.go
- pkg/test/framework/components/registryredirector/registry_redirector_server.yaml
- pkg/test/framework/components/registryredirector/registryredirector.go
This change is needed to allow HTTP requests to kind-registry. Read #51778 and #35915 for more context.
> tests: add `--scheme` argument to registry-redirector to allow HTTP requests

- cni/pkg/nodeagent/cni-watcher.go
- cni/pkg/plugin/cnieventclient.go
- cni/pkg/plugin/cnieventclient_test.go
```
Warning  FailedCreatePodSandBox  2m28s              kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "5971b5502d010075b13fa87ad7fce07e164dbba7fada3c9e498ebf1a55693c8e": plugin type="istio-cni" name="istio-cni" failed (add): unable to push CNI event, error was 500
Warning  FailedCreatePodSandBox  2m17s              kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "6738e4113866d42813aeb65a90e87a3ae40a18cc2cc5e93ee86d4332db5d783e": plugin type="istio-cni" name="istio-cni" failed (add): unable to push CNI event, error was 500
Warning  FailedCreatePodSandBox  2m3s               kubelet            Failed to create pod sandbox: rpc error: code = Unknown …
```
> cni: expose error messages to client

- istioctl/pkg/proxyconfig/proxyconfig.go
The flag is relevant to routes, not listeners.
> Typo in "proxy-config route" name flag description

- pkg/test/framework/components/echo/calloptions.go
- tests/integration/ambient/baseline_test.go
Skip JWT test, it is legit broken for a known issue (impacting tests
only, not real code, hopefully)
Fix SE test:
* Stop setting Host header invalid in the test (we are not wrapping Ipv6
in `[]`). Leaving unset allows Go to default it more correctly, so no
need for more complex logic.
* Create SE for v4 and v6. This cannot be one single SE due to a bug
* Call v4 and/or v6 depending on the environment
> Fix ambient IPv6 tests

- istioctl/pkg/writer/ztunnel/configdump/api.go
- istioctl/pkg/writer/ztunnel/configdump/services.go
* Add them to the struct so they show up in -ojson
* Expose just the count in short form
```
NAMESPACE    SERVICE NAME         SERVICE VIP  WAYPOINT ENDPOINTS
default      echo                 10.96.77.254 None     1/1
default      kubernetes           10.96.0.1    None     1/1
default      shell                10.96.61.1   None     1/1
istio-system istio-ingressgateway 10.96.8.67   None     1/1
istio-system istiod               10.96.98.157 None     1/1
kube-system  kube-dns             10.96.0.10   None     2/2
```
> Expose endpoints in `istioctl ztunnel-config`

- pkg/test/framework/components/registryredirector/registry_redirector_server.yaml
- prow/integ-suite-kind.sh
- tests/integration/telemetry/api/customize_metrics_test.go
- tests/integration/telemetry/api/registry_setup_test.go
- tests/integration/telemetry/api/setup_test.go
- tests/integration/telemetry/api/stats_test.go
Fixes #35915.
This [comment](https://github.com/istio/istio/pull/47978#issuecomment-1823155014) explains why do we have to upload WASM plugins to kind-registry before running tests. Additionally, I had to patch CoreDNS config map, because `kind-registry` is not resolvable in IPv6-only cluster.
First https://github.com/istio/istio/pull/51779 must be merged.
> tests: upload WASM plugins to kind-registry to avoid DNS issues in IPv6 clusters

- pilot/pkg/config/kube/crdclient/client.go
- pkg/config/analysis/local/istiod_analyze.go
- pkg/kube/informerfactory/factory.go
Else we get `for type /v1, Resource=pods, registered conflicting ObjectTransform. Stack: goroutine 833 [running]:`
> Avoid opening two watches when analysis is enabled

- pilot/pkg/features/experimental.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- releasenotes/notes/51897.yaml
This has been enabled for many releases and no one complained.
> remove optimized service push flag

- tests/integration/telemetry/api/stats_test.go
- tests/integration/telemetry/testdata/external-service-entry.yaml
- tests/integration/telemetry/testdata/istio-mtls-dest-rule.yaml
- tests/integration/telemetry/testdata/istio-mtls-gateway.yaml
- tests/integration/telemetry/testdata/istio-mtls-vs.yaml
This test fails, because it can't resolve `fake.external.com` in IPv6 cluster.
> tests: fix TestStatsGatewayServerTCPFilter in IPv6 cluster

- tests/integration/security/egress_sidecar_tls_origination_test.go
Otherwise we are leaking the DR config, which impacts future tests
> tests: properly cleanup config from previous test

- tests/integration/security/ingress_test.go
- tests/integration/security/main_test.go
- tests/integration/security/sds_ingress/quic/ingress_test.go
- tests/integration/security/sds_ingress/util/util.go
The test takes 90s to run before, 10s after. We should only create new
suite when it has a new setup requirement.
> Drop redundant test suite in security sds_ingress

- pkg/test/framework/components/echo/match/matchers.go
- tests/integration/security/reachability_test.go
TestReachability accounts for a whopping 10minutes total. This cuts the
runtime (TBD how much...) while retaining ~identical coverage.
> TestReachability: prune redundant test cases

- pilot/pkg/model/service.go
- pilot/pkg/networking/core/listener_waypoint.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pilot/pkg/serviceregistry/serviceentry/conversion_test.go
- pilot/pkg/serviceregistry/serviceentry/store_test.go
- pkg/test/framework/components/echo/common/deployment/namespace.go
- releasenotes/notes/51939.yaml
- tests/integration/ambient/waypoint_test.go
Fixes #51886
Istio will store all cluster VIPs for service entries, but these VIPs will be applied only to waypoint listeners for now -  I will fix sidecars in a follow-up PR.
> ambient: match multiple svc VIPs in waypoint

- tests/integration/pilot/cni/cniversionskew_test.go
Move the check from test level to suite level to avoid the ~1 min test
suite setup for no reason
> Skip test setup for CNI skew test when we skip all tests

- pkg/test/framework/components/istio/kube.go
Currently, in our integration tests, when "enableDualStack=true" we configure the ingress/egress gateways as dualStack but do not configure the istiod service as a dualStack service. This PR updates the istiod configuration to use a dualStack istiod control plane.
> Enable dualStack cfg for istiod control plane in dualStack tests

- pilot/pkg/networking/grpcgen/grpcecho_test.go
- pkg/test/echo/cmd/server/main.go
- pkg/test/echo/server/endpoint/grpc.go
- pkg/test/echo/server/endpoint/http.go
- pkg/test/echo/server/endpoint/instance.go
- pkg/test/echo/server/endpoint/tcp.go
- pkg/test/echo/server/instance.go
- pkg/test/framework/components/echo/kube/deployment.go
- pkg/test/framework/components/echo/util/traffic/result.go
- tests/integration/ambient/baseline_test.go
This adds tests for restarting ztunnel and workloads. Depends on https://github.com/istio/ztunnel/pull/1176 to pass with 100% success rate.
I have been stress testing this on my local machine. We have currently zero tolerance for any errors. This _might_ be too sensitive, in which case we can re-evaluate. But it works fine on my end.
This change includes some logic into the echo server to gracefully shutdown. This is required _outside of Istio_ to properly gracefully shutdown an application running in Kubernetes.
> ambient: add tests for components restarting

- prow/integ-suite-kind.sh
Without this, you will see ingress pod hang for 30s to resolve Istiod
DNS on each additional suite
> Speedup isntall of multiple suites by up to 30s

- tests/integration/security/cacert_rotation/main_test.go
This has been flaky for a long time. Ref https://github.com/istio/istio/issues/47829.
Additionally, the test takes 10min which is orders of magnitude longer than is appropriate for a single test
> Skip flaky cacert_rotation test

- istioctl/pkg/precheck/precheck.go
- istioctl/pkg/precheck/precheck_test.go
This PR adds basic unit tests for the `precheck` package in `istioctl`, as per the issue https://github.com/istio/istio/issues/50255.
I added a basic structure for the `precheck_test.go` file and added basic test cases for the `checkFromVersion` and `checkTracing` functions. This is a partial implementation of the tests for the `precheck` package, and I will continue to add more tests in future PRs. I did not include all the tests in this PR to get feedback on the structure and approach before adding more.
> Note: I hope I ticked the right boxes in the list below. Please let me know if it needs any changes.
**Please check any …
> Add (partial) unit tests for istioctl precheck package

- Makefile.core.mk
updates `check-agent-deps` to support ServiceEntryStatus
https://github.com/istio/api/pull/3244 and https://github.com/istio/istio/pull/51834 add a new status field which has a few different deps. These deps are part and parcel with having ServiceEntryStatus live under networking and should be acceptable.
> update check-agent-deps to support ServiceEntryStatus

- pilot/pkg/networking/core/cluster.go
- pilot/pkg/networking/core/cluster_builder.go
- pilot/pkg/networking/core/cluster_builder_test.go
- pilot/pkg/networking/core/cluster_tls.go
- pilot/pkg/networking/core/cluster_traffic_policy.go
- pilot/pkg/networking/core/cluster_waypoint.go
- pilot/pkg/networking/util/internal_upstream.go
- pkg/wellknown/wellknown.go
- tests/integration/ambient/baseline_test.go
This PR implements full DestinationRule support in waypoints. Prior to this, only subsets were supported.
As part of this change, some of the sidecar TLS logic is refactored to avoid duplication. Aside from that, the changes should be scoped only to waypoints. Testing coverage includes e2e tests of applying various policies to waypoints
Fixes https://github.com/istio/istio/issues/50215
> Support DestinationRule (beyond subsets) in waypoint

- istioctl/pkg/writer/envoy/configdump/endpoint.go
Example:
```
NAME                                             STATUS      LOCALITY     CLUSTER
127.0.0.1:15020                                  HEALTHY                  agent
10.244.0.8:80                                    HEALTHY                  outbound|80||echo-v4v6.default.svc.cluster.local
10.244.0.8:9090                                  HEALTHY                  outbound|9090||echo-v4v6.default.svc.cluster.local
10.244.0.8:80                                    HEALTHY                  outbound|80||echo-v6v4.default.svc.cluster.local
10.244.0.8:9090                                  HEALTHY                  outbound|9090||echo-v6v4.default.svc.cluster.local
10.244.0.8:80                                    HEALTHY                  outbound|80||echo.default.svc.cluster.local …
```
> istioctl: Show all addresses in eds proxy-config

- pilot/pkg/networking/core/httproute.go
This has no impact to the generated config, just simplify by using the
better helper method for this job
> dual stack: minor route refactoring

- pkg/config/analysis/analyzers/serviceentry/protocoladdresses.go
> Fix analyzeProtocolAddresses only work when tcp capitalized

- pilot/pkg/serviceregistry/kube/controller/ambient/services_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
- pkg/config/constants/constants.go
Our old strategy was to allow a user to set the label to
"namespace/name". This is great... but its illegal Kubernetes syntax,
making it impossible for a user to actually do this.
Instead, split this into two annotations
> ambient: allow cross-namespace waypoint references

- pkg/monitoring/monitortest/test.go
- releasenotes/notes/52005.yaml
- security/pkg/nodeagent/cache/secretcache.go
- security/pkg/nodeagent/cache/secretcache_test.go
Fixes: https://github.com/istio/istio/issues/50356
```
// Cert expire time by default is createTime + sc.configOptions.SecretTTL.
// Istiod respects SecretTTL that passed to it and use it decide TTL of cert it issued.
// Some customer CA may override TTL param that's passed to it.
```
For ROOTCA, the expire time is meanlingless, we should just record this for `WorkloadKeyCertResourceName` cert
> fix inconsistent behavior with the 'istio_agent_cert_expiry_seconds' metric

- pkg/monitoring/monitortest/test.go
- releasenotes/notes/52005.yaml
- security/pkg/nodeagent/cache/secretcache.go
- security/pkg/nodeagent/cache/secretcache_test.go
> [release-1.22] fix inconsistent behavior with the 'istio_agent_cert_expiry_seconds' metric

- pkg/monitoring/monitortest/test.go
- releasenotes/notes/52005.yaml
- security/pkg/nodeagent/cache/secretcache.go
- security/pkg/nodeagent/cache/secretcache_test.go
> [release-1.21] fix inconsistent behavior with the 'istio_agent_cert_expiry_seconds' metric

- pilot/pkg/xds/debug.go
- pilot/pkg/xds/workload.go
- pilot/pkg/xds/workload_test.go
When a PA was changed, it could trigger a removal of the policy due to
conflicting events from the ambient controller and the normal CRD
controller
> ambient: fix accidental deletion on NOP PA change

- pkg/test/framework/suite.go
- pkg/test/framework/suite_test.go
- pkg/test/framework/suitecontext.go
- pkg/test/framework/test.go
See
https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-123_istio_postsubmit/1812908054123909120;
this fails since setup is never run but the test is executed
> tests: make suite skip immediately exit

- pilot/pkg/networking/core/gateway.go
- pilot/pkg/networking/core/gateway_test.go
- pilot/pkg/networking/core/listener_builder.go
- pilot/pkg/networking/core/listener_builder_test.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/networking/util/util_test.go
Identical code was in both listener and gateway handling, and if multiple mesh networks were present it would pick a random one. This properly merges all meshes, and sorts the addresses (because meshes are unordered).
Fixes #52037
> Dedupe IAC handling and fix multiple nets case.

- pilot/pkg/model/service.go
- pilot/pkg/model/service_test.go
- pilot/pkg/networking/core/listener.go
- pilot/pkg/networking/core/tls.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pilot/pkg/serviceregistry/serviceentry/conversion_test.go
- pilot/pkg/xds/eds_test.go
- releasenotes/notes/51967.yaml
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/common/traffic.go
Fixes #51747
What did I change:
1. `GetAllAddressesForProxy` and `GetExtraAddressesForProxy` always return all addresses for the proxy's IP family. Previously these functions were returning all addresses only when `ISTIO_DUAL_STACK` was enabled.
2. `buildSidecarOutboundListener` used these functions to configure CIDR matching. These functions always returned the default address, so outbound listeners couldn't match all the addresses. Now, all CIDRs are configured for the supported IP family.
3. `convertServices` created internal service instance for each [host, address] pair. Now, it creates an instance for each [host,  address list] pair.
**Example:**
When the following SE is applied:
```
kind: …
```
> networking: match multiple VIPs in sidecar outbound listener

- pilot/pkg/model/service_test.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pilot/pkg/serviceregistry/serviceentry/conversion_test.go
- tests/integration/pilot/dns_auto_allocation_test.go
I introduced a regression in https://github.com/istio/istio/pull/51939, because in that PR I set addresses in `ClusterVIPs`. Previously when `ClusterVIPs` was empty, function `GetAddressForProxy` was trying to return auto-allocated address, so I fixed it by setting `ClusterVIPs` only if addresses are explicitly specified in a ServiceEntry. I also added an integration test.
> networking: fix DNS auto-allocation

- pilot/pkg/controllers/ipallocate/ipallocate.go
adds logic to handle json patching if status doesn't already exist.
this removes use of the jsonpatch library nodeuntaint controller was using from the ip autoallocate controller because it was not able to express the nil test for status.
> fix: ipautoallocate fails if status doesn't exists

- tests/integration/helm/install_test.go
- tests/integration/helm/util.go
- tests/integration/operator/switch_cr_test.go
- tests/util/sanitycheck/sanity_check.go
This is currently the slowest test in istio, taking 225s to complete.
This speeds it up and improves coverage
* Do not do 3 tests, one for each component -- deploy all of them in
their own namespace in one test.
* Also deploy istiod in its own namespace
* Actually deploy pods into ambient, which reveals a bug/misconfig (not
setting ztunnel sa)
* Cleanup namespace in parallel
> Improvements to Helm ambient test

- security/pkg/k8s/configutil.go
- security/pkg/k8s/configutil_test.go
Example of us trying to do it: https://storage.googleapis.com/istio-prow/logs/integ-ambient_istio_postsubmit/1813767255159214080/artifacts/ambient-946fbc91d18c49609caffad/TestTraffic/_test_context/istio-state3324201519/primary-0/istiod-5497c4576-pwjt2_discovery.log
> Do not retry creating configmap in deleted namespace

- pkg/collateral/control.go
The completion command descriptions come from the `cobra` package and contain Markdown. When rendering this as HTML, it obviously doesn't render. This brings the descriptions into our codebase and formats it as HTML (not sure if there's a better fix for this - we could update the command descriptions in `cobra`, but it still wouldn't render nicely in our docs). 
Ref: https://github.com/istio/istio.io/issues/15417
> istioctl: provide custom html for completion commands to fix formatting

- tests/integration/ambient/baseline_test.go
- tests/integration/ambient/waypoint_test.go
It's a follow-up to https://github.com/istio/istio/pull/51939 and addresses this comment: https://github.com/istio/istio/pull/51939#discussion_r1668976103.
> tests: use single ServiceEntry with multiple addresses in ambient tests

- pkg/collateral/control.go
Fixes the rendering of completion command description for any command ending with `completion-[shell_name]`.
Ref: https://github.com/istio/istio.io/issues/15417
> istioctl: fix cmd completion text rendering for other binaries 

- pilot/pkg/model/endpointshards.go
- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- releasenotes/notes/pilot-dupe-ip.yaml
See test case for details. The problem is we key on IP address; this is
not a unique key. This means a random WE will 'win' the slot, giving us
a 50/50 chance we only compare to ourselves, realize there was no
change, and skip the push.
Interestingly, the comment notes the key is not unique! I believe that
over time the code was refactored to make the uniqueness critcal to
correctness, whereas before it was not.
> Fix missed EDS push when overlapping IPs are found between WEs

- istioctl/pkg/writer/envoy/configdump/endpoint.go
Remove workaround in configdump handling for istioctl as I merged the fix for https://github.com/envoyproxy/envoy/issues/35100 (fix: https://github.com/envoyproxy/envoy/pull/35120) in Envoy
> Remove workaround for duplicated addresses in configdump

- tests/integration/telemetry/api/istioctl_metrics_test.go
The default system namespace for the `istioctl experimental metrics` command is set to `istio-system` where the command looks for prometheus pods. If any other system ns is used during testing, this test fails.
> specify ns to find prometheus pods

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/supported_features.go
- releasenotes/notes/support-features.yaml
This field provides no value but causes a lot of harm:
* https://github.com/kubernetes-sigs/gateway-api/pull/3200#discussion_r1681853821
* https://github.com/istio/istio/issues/50851
And it looks like there is no conformance requirement to support it.
If we do, we need to make it off-by-default with a flag; I see no reason to provide this.
> Drop SupportedFeatures from gateway-api

- cni/pkg/ipset/nldeps_linux.go
Manual cherry for https://github.com/istio/istio/issues/52172
As this is a backport, this omits the
- user-facing changes to remove an unused var
- tests added to a suite that doesn't exist in this release
present in the original.
---------
> [release-1.22] Work around netlink bug on ipset create error

- pilot/pkg/model/authorization_test.go
- pilot/pkg/model/policyattachment.go
- pilot/pkg/model/policyattachment_test.go
- pkg/config/validation/validation.go
API change: https://github.com/istio/api/pull/3271
This adds the ability to use SE as a targetRef in policies. We already have Service, so its natural to work with SE.
> Allow ServiceEntry as targetRef

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/network_test.go
- pkg/kube/krt/join_test.go
- pkg/kube/krt/krttest/helpers.go
- pkg/kube/krt/recomputetrigger.go
- pkg/kube/krt/recomputetrigger_test.go
- pkg/kube/krt/singleton.go
- pkg/kube/krt/singleton_test.go
otherwise, we can startup without network gateway sync and give
incorrect response
> ambient: ensure we sync network before we mark ourselves synced

- pkg/collateral/control.go
Escape the characters in the HTML text for the completion commands. 
Fixes: https://github.com/istio/istio.io/issues/15462 and https://github.com/istio/istio.io/pull/15453
> docs: escape the characters in completion text

- pkg/collateral/control.go
Change the sub-commands `<h3>` when exporting the HTML so the environment variables and metrics elements appear top-level/parents in the TOC.
Ref: https://github.com/istio/istio.io/pull/15451
> docs/collateral: make the sub-commands h3

- cni/pkg/install/install.go
- releasenotes/notes/52252.yaml
Description
This PR adds error wrapping to the Cleanup function to provide more detailed context for each possible error. By specifying the file and operation that caused the error, this change enhances the ability to debug and trace issues effectively.
Changes
•	Wrapped errors with fmt.Errorf in the Cleanup function.
•	Provided detailed context for each error, including file paths and operation descriptions.
> chore: Wrap errors with context in Cleanup function

- pilot/pkg/xds/delta.go
- pilot/pkg/xds/delta_test.go
- releasenotes/notes/delta-xds-stale.yaml
Fixes https://github.com/istio/istio/issues/51612
What is happening here is we get a request from Envoy without Nonce set. We end up setting `Acked=""`. Then, `istioctl ps` sees `sent=some-nonce, acked=""` and thinks it is STALE; its not.
Instead, we should not reset the `Acked` var when its not a real ACK.
This PR fixes this issue and adds a test case.
I am fairly sure this fixes https://github.com/istio/istio/issues/51165 as well, not but 100%
Easy manual reproducer is to apply a Gateway to an otherwise empty cluster, then remove it. 45s later the listener will drain and RDS will start reporting as stale
> pilot: fix treating spontaneous request as ACK

- pkg/test/util/yml/parts.go
- pkg/test/util/yml/parts_test.go
- tests/integration/ambient/main_test.go
* Run steps in parallel
* Avoid using regex to split lines (yes, this really is a bottleneck!
over 2 CPU seconds spent on this)
This cuts the test setup time on an already deployed cluster from
roughly 4s to .8s. Not crazy but nice for iteration.
> Optimize test suite setup

- pilot/pkg/networking/core/serviceentry_simulation_test.go
- pilot/pkg/simulation/traffic.go
- pkg/slices/slices.go
This test is... weird. I don't think its valid.
It is meant to test overlapping CIDRs, but it is actually testing two
services with the same hostname, so one is entirely ignored.
I have updated the test to test real overlapping IPs. In doing this, I
found another bug when SNI+CIDR is set together (very niche), tracking
in https://github.com/istio/istio/issues/52235. I did NOT fix this bug
in this PR, merely test it.
In order to facilitate this, I made changes to our FCM to match Envoy to
chose the closest matches, not only a boolean of exact matching
Related to https://github.com/istio/istio/pull/51776
> Improve testing of overlapping CIDRs

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
- pkg/workloadapi/workload.pb.go
- pkg/workloadapi/workload.proto
- releasenotes/notes/ambient-hostnetwork.yaml
This contains a series of fixes to make pods in the hostNetwork work.
Ztunnel side: https://github.com/istio/ztunnel/pull/1216. Either PR can merge first (though the Ztunnel one will not do anything without this change), and the ztunnel change only really addresses a minor edge case.
On the surface, the fix is trivial: just allow hostNetwork pods. The
issue arises in the fact this now allows duplication of IPs, since
multiple host network pods on the same node will share the same IP.
We address this in a number of ways.
1. Remove the restriction on overlapping IPs that we currently have. If
the pod is a host network pod, we allow multiple with the same IP.
1. In order to facilitate this, we indicate this in WDS. This allows
Ztunnel to know it should not treat the address as unique. In …
> ambient: make HostNetwork pods work

- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice_test.go
In the case a endpointslice (ipv6 address family) is created manually, and contains two endpoints:
one with targetRef, and the other not.  We can miss the second ipv6 address.  This is very uncommon. 
See the test case added.
> Fix cases: manually created endpointslice contain endpoints with mixed targetRef

- pilot/pkg/model/service.go
- pilot/pkg/networking/core/cluster.go
- pilot/pkg/networking/grpcgen/cds.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
Fixes https://github.com/istio/istio/issues/52256. The same draining logic used for stateful session cookies is extended for header based as well.
> handle draining endpoints for stateful header sessions

- releasenotes/notes/51967.yaml
- tests/integration/pilot/common/routing.go
It turned out that #30282 was fixed in #51967. However, I found another bug (?) related to `ServiceEntry` with multiple VIPs and described it in a comment. If we agree that the described bug should be fixed, I can create an issue with reproducing steps.
> tests: create `ServiceEntry` with multiple VIPs in `DNSTestCases`

- cni/pkg/nodeagent/cni-watcher_test.go
- cni/pkg/nodeagent/informers_test.go
- cni/pkg/nodeagent/net.go
- cni/pkg/nodeagent/net_test.go
- cni/pkg/nodeagent/server.go
- cni/pkg/nodeagent/server_test.go
- releasenotes/notes/52320.yaml
Should fix: https://github.com/istio/istio/issues/52218 (@howardjohn repro'd locally)
Basically, when we "add" a pod to the mesh, there are several things that (in order) can fail.
1. We can fail to get the pod netns.
2. We can fail to inject iptables
3. We can fail to talk to ztunnel
4. We can fail to annotate the pod (which officially indicates to the Istio CP that the pod is "in  ambient")
5. We can fail to add the pod to the hostipset, so health checks begin working for that pod
For _anything_ after No. 2, we return a PartialError - Before that point failures don't have side effects really - but once we step into the netns and mutate the pod netrules, we have changed the app pod state and (potentially) must unhook at least something before …
> Do not add pod to ipset if we have a "partial failure" adding to the dataplane.

- tests/integration/ambient/waypoint_test.go
Its not *always* v4, its depends on a lot of factors. So for now we just
won't assert this
fixes https://github.com/istio/istio/issues/52325
> Remove over ambitious check on new test

- pilot/pkg/serviceregistry/kube/controller/controller_test.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice_test.go
- pilot/pkg/serviceregistry/kube/controller/network_test.go
- pilot/pkg/serviceregistry/kube/controller/pod_test.go
- pilot/pkg/serviceregistry/kube/controller/serviceexportcache_test.go
- pilot/pkg/serviceregistry/kube/controller/serviceimportcache_test.go
No major changes
- generatePod will now take ips instead of only one ip
- remove code in TestUpdateEndpointCacheForSliceWithMultiAddrs that inserted the additional pod IPs after creation of the pod object
- createServiceWait, createService, generateService will take an IPs list as arg instead of always creating a service with IPs 10.0.0.1, 10.0.0.2
> Improve multi-addrs handling in test functions

- istioctl/pkg/describe/describe.go
- istioctl/pkg/describe/describe_test.go
```
➜  ~ istioctl x describe service waypoint
Service: waypoint
Port: status-port 15021/TCP targets pod port 15021
Port: mesh 15008/UnsupportedProtocol targets pod port 15008
15021:
15008:
Skipping Gateway information (no ingress gateway pods)
```
> Fix istioctl describe service being unable to display the HBONE protocol

- samples/httpbin/httpbin.yaml
Currently we are only binding on ipv4.
update gunicorn cmd to bind on both ipv4 and ipv6
> make httpbin sample bind on both ipv4 and ipv6

- pilot/pkg/bootstrap/server.go
- pkg/kube/multicluster/secretcontroller.go
- security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go
- security/pkg/server/ca/authenticate/kubeauth/kube_jwt_test.go
Common error is configure client and istiod with different cluster name.
This shows it clearly.
```
Failed to authenticate client from 10.244.0.20:55098: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: could not get cluster Kubernetesx's kube client
Failed to authenticate client from 10.244.0.20:36552: Authenticator ClientCertAuthenticator: no verified chain is found; Authenticator KubeJWTAuthenticator: client claims to be in cluster "Kubernetesx", but we only know about local cluster "Kubernetes" and remote clusters []
```
> Better auth logs for cluster mismatch

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_logging.go
- pilot/pkg/model/telemetry_logging_test.go
- pilot/pkg/networking/core/accesslog.go
- pilot/pkg/networking/core/accesslog_test.go
This should be the last in the series of PRs around stats and delimiters. This PR utilizes the new UPSTREAM_CLUSTER_RAW formatter that I added in Envoy to ignore the alt stat name for access logs (but not metrics). This keeps access logs consistent for users, and they don't have to see a random semicolon show up.
> Use UPSTREAM_CLUSTER_RAW for access log format

- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/network_test.go
Apparently there are two ways to subscribe to gateways, and we need to
do both. Adds a unit test to capture this case
> Fix gateway trigger for ambient

- pkg/kube/kclient/client_test.go
- pkg/kube/namespace/filter.go
- releasenotes/notes/namespace-filter-deadlock.yaml
This fixes a bug triggered under a very precise set of circumstances, which has been captured in a unit test:
* Using discoverySelectors
* Namespace changes from selected to not selected. This triggers the namespace filter to call handlers *with the lock held*.
* There are handlers that use the filter, and call .List() in their handler. This ultimately calls .Filter(), which requires a lock, which deadlocks since we hold the lock already.
The fix here is to drop the lock before we call the filter.
In Istio, we have 2 cases that have handlers call .List(): Ingress and Gateway. So this can only occor for namespaces that contain those objects.
Running all the filter tests locally (not just the new one): `2830 runs so far, 0 failures (100.00% pass rate). 552.201538ms avg, 757.274586ms max, …
> Fix a deadlock when using `discoverySelectors`

- pkg/collateral/control.go
Manual cherry-pick of #52274.
This changes a generator for command line documentation, needed for a docs change, and shouldn't have any impact elsewhere.
/release-notes-none
> docs/collateral: fix docs generator to indent at correct levels

- releasenotes/notes/52193.yaml
- security/pkg/pki/ca/ca.go
- security/pkg/pki/util/keycertbundle.go
- security/pkg/pki/util/keycertbundle_test.go
- security/pkg/server/ca/monitoring.go
- security/pkg/server/ca/server.go
Fixed some incorrect documentation and refactored keycertbundle logging code to be a bit more efficient.
Main thing is that the documentation for `rootCertExpiryTimestamp`/`certChainExpiryTimestamp` was incorrect and the question is whether we want to keep the docs and update the behavior or update the docs and keep the behavior.
> Refactor keycertbundle

- pilot/pkg/features/telemetry.go
- pilot/pkg/networking/core/cluster_builder.go
- pilot/pkg/networking/core/cluster_builder_test.go
- pilot/pkg/networking/core/cluster_test.go
- pilot/pkg/networking/core/cluster_waypoint.go
- pilot/pkg/networking/core/gateway.go
- pilot/pkg/networking/core/listener.go
- pilot/pkg/networking/core/listener_inbound.go
- pilot/pkg/networking/grpcgen/cds.go
- pilot/pkg/networking/util/util.go
We changed all statnames to end with a delimiter(;) but if user provides a statname format - it should be respected. If he needs regex support, he should add that in that format.
> respect cluster statname pattern if provided

- pilot/pkg/controllers/ipallocate/ipallocate.go
- pilot/pkg/controllers/ipallocate/ipallocate_test.go
- pilot/pkg/networking/serviceentry/ip_autoallocation.go
- pilot/pkg/serviceregistry/kube/controller/ambient/services.go
- pilot/pkg/serviceregistry/kube/controller/ambient/services_test.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pilot/pkg/serviceregistry/serviceentry/conversion_test.go
- releasenotes/notes/52319.yaml
Implementation consuming https://github.com/istio/api/pull/3279 to make the new auto-allocation behavior align more closely to the existing behavior of addressing per-host rather than addressing per-serviceentry
> implement addressing per-hosts for autoallocate

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
This should have effectively no impact (ztunnel will ignore it), but is consistent with workload
waypoints and overall nicer
> ambient: do not allow service waypoint to have a waypoint

- pilot/pkg/config/memory/store_test.go
Causing postsubmit failure post merge of the v1 change
> Fix stale GVK in benchmark test

- pilot/pkg/model/service.go
- pilot/pkg/model/service_test.go
fix #52446 
benchmark result:
```
goos: darwin
goarch: amd64
│    old.txt     │               new.txt               │
│     sec/op     │    sec/op     vs base               │
EndpointDeepCopy-12   14235.5n ± 16%   271.2n ± 10%  -98.10% (p=0.002 n=6)
│   old.txt   │              new.txt              │
│    B/op     │    B/op     vs base               │
EndpointDeepCopy-12   6688.0 ± 0%   624.0 ± 0%  -90.67% (p=0.002 n=6)
│   old.txt    │              new.txt              │
│  allocs/op   │ allocs/op   vs base               │
EndpointDeepCopy-12   189.000 ± 0%   4.000 ± 0%  -97.88% (p=0.002 n=6)
```
> hand written IstioEndpoint deepcopy

- pilot/pkg/controllers/ipallocate/ipallocate.go
- pilot/pkg/controllers/ipallocate/ipallocate_test.go
- pilot/pkg/networking/serviceentry/ip_autoallocation.go
- pilot/pkg/serviceregistry/kube/controller/ambient/services.go
- pilot/pkg/serviceregistry/kube/controller/ambient/services_test.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pilot/pkg/serviceregistry/serviceentry/conversion_test.go
- releasenotes/notes/52319.yaml
Fixes #52481
Manual cherry-pick of #52319, the change in master from working with v1alpha3 types to v1 types prevented the automatic cherry-pick from working
> [release-1.23] cherry-pick: implement addressing per-hosts for autoallocate (#52319)

- releasenotes/notes/51966.yaml
- security/pkg/pki/ra/common.go
- security/pkg/pki/ra/common_test.go
- security/pkg/pki/ra/k8s_ra_test.go
- security/pkg/pki/util/generate_cert.go
- security/pkg/pki/util/generate_csr.go
- security/pkg/pki/util/san.go
- security/pkg/pki/util/san_test.go
Alternative to https://github.com/istio/istio/pull/51920
Notes on https://github.com/istio/istio/pull/51959:
- This change is very similar but generated the CSR template using the same code as the client (istio-proxy) making the istio CSR request
- Added some additional testing using CSRs from `genCSR` and individually built CSRs for testing fields that could not be set with `GenCSR`
- Slightly different logical comparisons to add some leniency in negligible config difference of the CSRs (which in turn makes the code more testable. I was unable to use `openss`l to generate a CSR with an `Org` value of "". It is always interpreted as unset.
**To help us figure out who should review this PR, please put an X in all the areas that this PR …
> Strict CSR validation in k8s CSR workflow

- pilot/pkg/model/sidecar_test.go
Fixes https://github.com/istio/istio/issues/52559
The issue is the sorting logic for the services only took name into
account and we had overlapping names. Could sort it more, but its more
clear to just have a distinct name (which does not impact the test
coverage in any way here).
> Fix flake in TestCreateSidecarScope

- go.mod
- go.sum
We only depend on the 'homedir' package which is trivial, but scanners
are not smart enough and flag a CVE
> Bump docker go dep

- go.mod
- go.sum
We only depend on the 'homedir' package which is trivial, but scanners
are not smart enough and flag a CVE
> 1.21: bump docker go dep

- go.mod
- go.sum
We only depend on the 'homedir' package which is trivial, but scanners
are not smart enough and flag a CVE
> 1.22: bump docker go dep

- pkg/test/failer.go
- pkg/test/failer_test.go
This is just a trivial dependency trimming
> Do not expose `testing` package beyond where its needed

- pilot/pkg/model/sidecar.go
- pilot/pkg/networking/core/route/route.go
PERSIST_OLDEST_FIRST_HEURISTIC_FOR_VIRTUAL_SERVICE_HOST_MATCHING is removed on master.
I'm cleaning up some leftover comments
> Remove comments about virtual service host matching flag

- pkg/istio-agent/xds_proxy.go
Currently, in istio-agent, if there is an EOF from Recv for the upstream, xds_proxy sends EOF error to the downstream.
But, since EOF is meaning the graceful termination of the connection, we need to return `nil` instead of EOF.
Note that this returning EOF is regarded as 'Unknown' error in gRPC and so Envoy is now displaying confusing error message like:
```
... warning envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_stream.h:152 
StreamAggregatedResources gRPC config stream to xds-grpc closed: 2, EOF thread=15
```
(2 is Unknown error code.)
Change-Id: I0a3065df3a842ab4fa6336f4155f5aec84fc5226
> Return nil if the upstream error is io.EOF in istio-agent

- pkg/config/validation/validation.go
These are not literally headers, they are values that end up *inside*
cors headers. These can be `<header name> || *`; we were missing the
star case.
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers
See https://github.com/istio/istio/pull/51343#issuecomment-2266705080
> Fix regression in CORS header validation

- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
Added logic to ensure that any keys without corresponding endpoints are explicitly treated as deletions by sending a `nil` endpoints update. Previously, such keys were not properly handled, leading to potential inconsistencies in the EDS Updates.
> Fix Handling of Deletions in EDS Cache and Update Functions

- pilot/pkg/security/authz/matcher/header.go
- pilot/pkg/security/authz/matcher/header_test.go
- tests/fuzz/oss_fuzz_build.sh
- tests/fuzz/pilot_security_fuzzer.go
- tests/fuzz/regression_test.go
`HostMatcherWithRegex` only has test cases, which I think could be cleaned up.
> cleanup HostMatcherWithRegex deadcode

- releasenotes/notes/grace-ratio-jitter.yaml
- security/pkg/nodeagent/cache/secretcache.go
Just a slight modification to https://github.com/istio/istio/pull/52102/files to ensure there is always "jitter" in cert renewal timeframes. The original implementation leaves ~1/3rd certs un-modified (multiplier was -1, 0, 1 and is now just -1 or 1).
> ensure there is always jitter in cert renwals

- pkg/kube/inject/inject_test.go
- pkg/kube/inject/testdata/inject/hello-openshift-custom-injection.yaml
- pkg/kube/inject/testdata/inject/hello-openshift-custom-injection.yaml.injected
- pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.48.mesh.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.48.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.48.values.gen.yaml
- pkg/kube/inject/webhook.go
OpenShift automatically assigns a SecurityContext.RunAsUser to all containers in the Pod, even if the Pod's YAML does not explicitly set this value. Istio treats the values specified in the istio-proxy container as overrides and preserves them in the final Pod yaml as expected. However, the RunAsUser value which is automatically set by OpenShift would be the same for all containers within the Pod, which is a problem. Because the RunAsUser is identical for both the application container and the proxy container, traffic interception fails for the pod. In this PR, we ignore the RunAsUser value on the sidecar proxy if it matches the application container's value for OpenShift deployments. At the same time, if user explicitly configures a RunAsUser in the istio-proxy container which is …
> Fix custom sidecar injection in an OpenShift deployment

- Makefile.core.mk
- tests/binary/dependencies_test.go
This was previously done partially for agent, but in a hard to
understand makefile target. Now it is a bit more explicit, and added
pilot
> testing: create dependency deny/allow list

- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/cluster_builder_test.go
- pilot/pkg/networking/core/cluster_test.go
- pilot/pkg/networking/core/cluster_tls.go
- pilot/pkg/networking/core/cluster_tls_test.go
- pilot/pkg/networking/core/cluster_traffic_policy.go
VERIFY_CERTIFICATE_AT_CLIENT is officially removed from 1.20 compatibility charts on master.
This commit remove the relevant code paths.
> Remove code paths for VERIFY_CERTIFICATE_AT_CLIENT

- pilot/pkg/controllers/ipallocate/ipallocate.go
- pilot/pkg/controllers/ipallocate/ipallocate_test.go
This allows running without the Istio CRDs installed, which is currently
supported by the rest of the codebase
> ipautoallocator: do not watch SE if they do not exist

- manifests/charts/istio-control/istio-discovery/templates/deployment.yaml
* Fix istiod helm chart for remote
* Add another check
* Fix args
* Add comment
---------
Cherry pick  aa4df2c817e7da9767f4b40923783d3116c30c20 from master. https://github.com/istio/istio/pull/52400/files. This fixes the env value in the Istiod helm chart for istiod-remote for primary-remote setups.
> [cherry-pick][release-1.23] Fix istiod helm chart for remote

- tests/integration/ambient/main_test.go
revert change to stop manual allocation of se address in favor of using ip-autoallocate
Ambient DS postsubmit tests are failing. Revert the change which leads to this failure until https://github.com/istio/istio/issues/52678 can be resolved.
> revert change to stop manual allocation of se address

- istioctl/pkg/proxyconfig/proxyconfig.go
- releasenotes/notes/52630.yaml
Support filter pod by labels for envoy-stats
Printing here can filter Pods through label selector, but it was not implemented before：https://github.com/istio/istio/blob/master/istioctl/pkg/proxyconfig/proxyconfig.go#L598
> istioctl: support filter pod by labels for envoy-stats

- pilot/pkg/model/service.go
- releasenotes/notes/52753.yaml
don't require DNS capture for waypoints to use auto-ups.
fixes #52746
> revised logic for when a proxy consumes autoallocated IPs

- pilot/pkg/model/service.go
- pilot/pkg/networking/core/cluster_waypoint.go
- releasenotes/notes/ambient-waypoint-portlevel.yaml
- tests/integration/ambient/baseline_test.go
Respect port level DR settings. Pretty straightforward change; 1 liner fix + adding test. Feature was new in 1.23
> waypoint: Respect port level DR settings

- pilot/pkg/networking/core/listener_waypoint.go
Currently, with a SE bound to a waypoint, we end up hitting the
inbound-vip path if there is no route, but if we make a route -- even
pointing to the same SE -- we start treating it as 'outbound'.
A route pointing from X to X should never change the behavior. Remove
this special case, which I added in the very first Waypoint Routing PR
long before we had SE support.
> Make waypoint treat SE like services

- pkg/monitoring/counter.go
- pkg/monitoring/distribution.go
- pkg/monitoring/gauge.go
- pkg/monitoring/monitoring_test.go
Added in https://github.com/open-telemetry/opentelemetry-go/pull/5304.
Prior to this, we hack around the lack of a sync gauge by approximating one with an async gauge. This is complex and has a race condition, captured by the test I added.
If we compare the performance:
```
name                     old time/op    new time/op    delta
Gauge/no_labels-16         13.0ns ± 1%    50.7ns ± 2%  +290.07%  (p=0.004 n=8+4)
Gauge/dynamic_labels-16     322ns ± 7%     385ns ± 7%   +19.54%  (p=0.002 n=10+4)
Gauge/static_labels-16     13.2ns ± 9%   117.2ns ± 3%  +788.01%  (p=0.004 n=8+4)
name                     old alloc/op   new alloc/op   delta
Gauge/no_labels-16          0.00B          0.00B           ~     (all equal)
Gauge/dynamic_labels-16      288B ± 0%      320B ± 0%   +11.11%  (p=0.002 n=10+4) …
```
> monitoring: move to OTEL sync gauge

- pilot/pkg/grpc/grpc.go
- pilot/pkg/grpc/grpc_test.go
- pilot/pkg/xds/delta.go
- pkg/istio-agent/xds_proxy.go
- pkg/xds/server.go
Currently, in istio-agent, if there is an EOF from Recv for the upstream, xds_proxy sends EOF error to the downstream.
But, since EOF is meaning the graceful termination of the connection, we need to return `nil` instead of EOF.
Note that this returning EOF is regarded as 'Unknown' error in gRPC and so Envoy is now displaying confusing error message like:
```
... warning envoy config external/envoy/source/extensions/config_subscription/grpc/grpc_stream.h:152 
StreamAggregatedResources gRPC config stream to xds-grpc closed: 2, EOF thread=15
```
(2 is Unknown error code.)
This is the second trial after https://github.com/istio/istio/pull/52608, but followed the last comments.
Change-Id: I88e225acad5a359f663eaf6b215c601b13410ea0
> Return nil if gRPC stream returns io.EOF instead of returning io.EOF itself.

- pilot/pkg/networking/core/listener_waypoint.go
Now operation shows as 'productpage.amb.svc.cluster.local:9080/*' vs
':9080/*'
> ambient: set decoration name properly

- pilot/pkg/networking/core/envoyfilter/rc_patch.go
Only compute listenerPort related logic when routeConfiguration has match on port
> minor optimization in route patch matching

- tools/istio-iptables/pkg/builder/iptables_builder_impl.go
No need to make these pointers since they are never modified and never
null. Just makes things more confusing
> iptables: minor refactor to avoid excessive pointers

- cni/pkg/iptables/iptables.go
- cni/pkg/iptables/testdata/default.golden
- cni/pkg/iptables/testdata/default_ipv6.golden
- cni/pkg/iptables/testdata/tproxy.golden
- cni/pkg/iptables/testdata/tproxy_ipv6.golden
Fixes https://github.com/istio/ztunnel/issues/1177
Pre-req for https://github.com/istio/ztunnel/issues/1281
This adds TCP redirection, and excludes marked traffic.
The supported upgrade path is CNI first, then Ztunnel.
CNI w/ this patch, Ztunnel 1.23: TCP will start redirecting, which is
already supported by Ztunnel. UDP change does nothing
CNI + Ztunnel patched (with https://github.com/istio/ztunnel/pull/1282):
DNS requests come from the application pod. UDP packets are marked, so
they do not loop due to the CNI change here.
> ambient: enhance DNS capture

- pilot/pkg/networking/core/accesslog.go
- pilot/pkg/networking/core/listener.go
- pilot/pkg/networking/core/listener_waypoint.go
- releasenotes/notes/ambient-logs.yaml
This takes a similar approach to our current 'listener' logs -- we apply
a access logger somewhere but only log on certain error conditions. In
this case, upstream HBONE connection failure.
Some example failures; in both cases, the top line is new:
```
[2024-08-27T20:00:10.142Z] "- - -" 0 UF,URX - - "delayed_connect_error:_Connection_refused" 0 0 0 - "-" "-" "-" "-" "10.244.0.17:15008" connect_originate - 10.244.0.17:80 envoy://internal_client_address/ - -
[2024-08-27T20:00:10.142Z] "GET / HTTP/1.1" 503 UF upstream_reset_before_response_started{remote_connection_failure|delayed_connect_error:_Invalid_argument} - "delayed_connect_error:_Invalid_argument" 0 165 0 - "10.244.0.1" "curl/8.9.1" "58c0e2c6-fa7e-4a68-a4f1-3bae11113f7c" "172.18.0.101" "envoy://connect_originate/10.244.0.17:80" …
```
> hbone: log transport errors

- pkg/config/validation/validation.go
It should be capitalized. Replace with constant to make it more robust.
> validation: fix error casing on workload group

- pilot/pkg/model/telemetry.go
- pilot/pkg/model/telemetry_logging.go
- pilot/pkg/model/telemetry_logging_test.go
- pilot/pkg/networking/core/accesslog.go
- pilot/pkg/networking/core/cluster.go
- pilot/pkg/networking/core/cluster_builder.go
- pilot/pkg/networking/core/cluster_waypoint.go
- pilot/pkg/networking/core/gateway.go
- pilot/pkg/networking/core/listener.go
- pilot/pkg/networking/core/listener_inbound.go
- pilot/pkg/networking/core/listener_test.go
- pilot/pkg/networking/core/listener_waypoint.go
- pilot/pkg/networking/grpcgen/cds.go
- pilot/pkg/networking/util/util.go
Proxy 1.22 cannot connect to Istiod 1.24 safely per our compatibility
guarantees, so clean up the tech tdebt
> pilot: drop obsolete 1.22 proxy compat

- pilot/pkg/networking/core/cluster_waypoint.go
We do this for every cluster *but* this one. Based on some
troubleshooting with a user
(https://istio.slack.com/archives/C37A4KAAD/p1724878840164799?thread_ts=1724224161.756969&cid=C37A4KAAD)
there is some signs pointing to this being the root cause of some
connectivity issues.
Additionally, do not hardcode the connect_timeout.
~I put a hold since we are going to get some production testing of this in ~12 hours so will wait to hear back~ actually we should do this anyways..
> Do not use circuit breakers on connect_originate clusters

- pilot/pkg/networking/core/listener_inbound.go
Add sidecar metadata in inbound filter chains created by sidecar to distinguish clearly whether they are created by sidecar or by service
> add sidecar metadata to inbound listeners

- tests/binary/dependencies_test.go
Notably, proves https://github.com/istio/istio/pull/52921 is not needed
to impact istioctl
> Add dep test for istioctl

- pilot/docker/Dockerfile.proxyv2
- pilot/docker/Dockerfile.ztunnel
- samples/bookinfo/src/details/Dockerfile
- samples/bookinfo/src/productpage/Dockerfile
- samples/bookinfo/src/ratings/Dockerfile
- samples/bookinfo/src/reviews/Dockerfile
- samples/helloworld/src/Dockerfile
Fix docker warnings when building images
`warning: LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value"`
> fix LegacyKeyValueFormat docker warnings

- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pkg/kube/krt/filter.go
See the test; without this change, objects with no labels (WE, pod, etc)
will get selected as part of a service.
> krt: fix FilterSelectsNonEmpty when the object has no labels

- tools/packaging/common/istio-start.sh
This update will change the current handling of start/stop/clean operations in VMs to rely on `istio-iptables --cleanup-only` instead of the old `istio-clean-iptables` command.
`istio-iptables --cleanup-only `computes the rules that need to be deleted in a "dynamic" way based on what the command would have applied if the cleanup option was not used.
On the other hand, `istio-clean-iptables` relied on hardcoded logic which was separate from the one used to create rules in istio-iptables. This approach required constant maintenance to ensure that the two different tools did not diverge over time.
This change removes the need to maintain `istio-clean-iptables `and prevents issues similar to #52835 and #41431 from occurring.
I'm not sure whether the istio-clean-iptables source code in the …
> Use new istio-iptables cleanup methodology in VMs

- pilot/pkg/networking/core/httproute.go
- pilot/pkg/networking/core/route/route.go
- tests/integration/pilot/common/routing.go
Currently, you can send traffic to an ExternalName service to a VS only from Gateways. This was due to an over-ambitiuous filtering. To align with Gateway behavior, move this check later. See the added e2e test case for more info on this.
Reported https://istio.slack.com/archives/C38CF1PEC/p1723100116648679
> Fix sending to external service entry from a VS

- tests/integration/pilot/gateway_test.go
Add/Increase retry timeout due to delay in config propagation for GKE on AWS platform
> Add/Increase retry timeout due to delay for GKE on AWS platform in config propagation

- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
This is similar to [PR #52189](https://github.com/istio/istio/pull/52189).
We should include service port name as well in the key to make sure multiport service entry selecting workload entry comparison works well.
> fix endpoint comparision logic in UpdateServiceEndpoints

- pilot/pkg/networking/core/listener_waypoint.go
This mirrors what we do for sidecars, gateways, etc
> waypoint: log when we cannot find a route in the internal listener

- pilot/pkg/networking/core/listener.go
- pilot/pkg/networking/core/sidecar_simulation_test.go
- pilot/pkg/networking/core/tls.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pilot/pkg/serviceregistry/serviceentry/conversion_test.go
- pilot/pkg/xds/eds_test.go
- releasenotes/notes/51967.yaml
- releasenotes/notes/revert-multi-vip.yaml
This mirrors https://github.com/istio/istio/pull/52952/files on 1.22 branch.
This PR caused 2 regressions: https://github.com/istio/istio/issues/52847 and https://github.com/istio/istio/issues/52944.
By reverting this, we bring back the original issue (which has been in Istio for many releases): that multiple addresses may be dropped in a SE. However, users can workaround this by creating a Sidecar resource. See TestOverlappingServices for a reproduction of this (with and without Sidecar).
The long term path forward will be to merge https://github.com/istio/istio/pull/51776. This is a risky change, though, so will be kept on the master branch
> 1.23: Revert networking: match multiple VIPs in sidecar outbound listener

- pilot/pkg/serviceregistry/kube/controller/ambient/helpers.go
Not sure why the golangci-lint `unused` linter does not detect it
> rm unused functions

- pilot/pkg/networking/core/tracing.go
- pilot/pkg/networking/core/tracing_test.go
- pkg/config/validation/agent/extensionprovider.go
- pkg/config/validation/agent/extensionprovider_test.go
- releasenotes/notes/52873.yaml
- tests/integration/telemetry/tracing/otelcollector/testdata/test-otel-grpc-with-initial-metadata.yaml
- tests/integration/telemetry/tracing/otelcollector/tracing_test.go
This PR aims to support this feature request https://github.com/istio/istio/issues/52873.
I have already tested this implementation on Alibaba Cloud OpenTelemetry, which requires adding header like `Authentication: token-xxxxx` on gRPC requests for authentication and it works fine on my cluster.
> Support grpc headers configuration of opentelemetry provider

- pilot/pkg/grpc/grpc.go
- pilot/pkg/grpc/grpc_test.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/delta.go
- pkg/istio-agent/xds_proxy.go
Fix https://github.com/istio/istio/issues/52840
Change-Id: I88e225acad5a359f663eaf6b215c601b13410ea0
> [release-1.21] Return nil if gRPC stream returns io.EOF instead of returning io.EOF itself.

- pilot/pkg/grpc/grpc.go
- pilot/pkg/grpc/grpc_test.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/delta.go
- pkg/istio-agent/xds_proxy.go
Fix https://github.com/istio/istio/issues/52838
Change-Id: I88e225acad5a359f663eaf6b215c601b13410ea0
> [release-1.22] Return nil if gRPC stream returns io.EOF instead of returning io.EOF itself.

- pkg/config/host/names.go
- pkg/config/host/names_test.go
This is a small patch to fix panic while comparing two empty hostname string. Although there is a validation done by webhook so a hostname should never be empty. But this can occur if webhook is not validating first for any reason.
> fix panic comparing empty hostnames

- common/config/.golangci.yml
- pkg/adsc/adsc.go
- pkg/adsc/delta.go
- pkg/adsc/delta_test.go
- tools/golangci-override.yaml
* Fix and test panic on double remove
* Avoid storing the full last xds response; this is expensive
* Avoid global var usage in test
> Various delta adsc improvements

- istioctl/pkg/tag/generate.go
We were accidentally dropping the IstioNamespace config part
> install: fix regression in default tag generation

- tests/integration/helm/install_test.go
- tests/integration/helm/util.go
Currently, the helm integration test sets the `values.yaml` by using sprintf over a string variable to set those values. There is a comment mentioning this:
`// TODO why not just use yaml parsing here, this sprintf stuff is fragile`
I replaced the way that is done now by using a map to set the values for the helm install.
This is part of #53077. In a consecutive PR, I'll do the flattening of the gateway to avoid the need to set `values["platform"] = "openshift"`
> Improve Helm Integration test

- pilot/pkg/xds/workload_test.go
We add the pod, but race it to be handled by the controller
> Fix flake in TestWorkloadReconnect

- pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
Before we always sent it, but with empty config. Just a bit more
clear/clean to not set it at all.
Also add two new tests:
* Pod with a waypoint
* A pod that *is* a waypoint
> ambient: only set app tunnel if configured

- pkg/kube/inject/webhook.go
We have received some error logs about injecting sidecar, but can not figure out which pod should I check, we have thousands pod, and it's hard, so I want add pod name and namespace info when injecting sidecar error:
Now
```
2024-09-11T09:30:24.387340Z    error    Pod injection failed: failed to run injection template: failed applying injection overlay: unmarshal patched pod: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```
then
```bash
2024-09-11T09:30:24.387340Z    error    Pod injection failed: failed to run injection template: failed applying injection overlay: unmarshal patched pod(${pod_name} ${pod_namespace}): quantities must match the regular expression …
```
> Add pod name and namespace info when inject sidecar error

- tests/integration/pilot/ingress_test.go
* Fix TestCustomGateway integration tests on OCP
The test case was not configuring the platform details in the Helm values, because of which the test was failing. This PR fixes it.
* Remove TestCustomGateway/helm as it uses unsupported chart
TestCustomGateway/helm uses manifests/charts/gateways/istio-ingress which is no longer supported. This PR removes it.
* Use string append instead of appendToFile
Fixes: https://github.com/istio/istio/issues/53088
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>
(cherry picked from commit 04f15fe786f97f9a95861860bee0c8f89d5e3c66)
> [release-1.23] Fix TestCustomGateway integration tests on OCP (#52974)

- pkg/version/cobra.go
For our internal implementation, remoteVersion is empty, which leads to out of index error. Added a zero length array check to mitigate it.
> Add zero length check for remoteVersion

- manifests/charts/istio-cni/templates/daemonset.yaml
- releasenotes/notes/53184.yaml
Added the metric port definition to the DaemonSet manifest of cni-node to allow prometheus metrics scrapping with a PodMonitor.
This pr backports these two pr's at once as a bug was introduced in the first one and fixed in the second one:
- #52461
- #52513
>  [release-1.23] Backport to 1.23 the metrics port definition for istio-cni

- istioctl/pkg/proxyconfig/proxyconfig.go
Support for filtering Pods by label selector to `istioctl pc`.
Related discussions:  https://github.com/istio/istio/pull/53089#issuecomment-2345082433
> istioctl: add  example about filter pod by deployment name for proxy-config

- istioctl/pkg/ztunnelconfig/ztunnelconfig.go
This PR fixes examples that didn't match up correctly with the associated ztunnel-config sub-command.
> istioctl: fix incorrect examples/descriptions for zc cmd

- pilot/pkg/model/push_context.go
- pilot/pkg/networking/core/cluster.go
- pilot/pkg/networking/core/cluster_test.go
When a Service and Destination Rule is created, they select the same "service" - so there is a possibility to create duplicate clusters which would be later normalized. This PR fixes it to not create them.
> fix duplicate clusters in delta xds

- pkg/kube/client.go
`pkg/kube/client.go > ssapplyYAML` [code](https://github.com/istio/istio/blob/876810aa99143e63e22e0fb6358807b78ba6a430/pkg/kube/client.go#L1070) skipped the missing kind error.
But after https://github.com/istio/istio/pull/52541, `buildObject` [code](https://github.com/istio/istio/blob/876810aa99143e63e22e0fb6358807b78ba6a430/pkg/kube/client.go#L1210)  wrap the error with `fmt.Errorf`. 
Therefore, `runtime.IsMissingKind` is no more working.
To fix it, let's just use the error from decode function without wrapping.
Change-Id: Ida3a7c818014902c15d1ab82c0664682f3f18112
> Fix the missing kind error

- samples/httpbin/httpbin-vault.yaml
- samples/httpbin/httpbin.yaml
The httpbin sample received a new tag yesterday that breaks the command we inject in the samples. This fixes it to still continue to mirror the RUN command of the image but on an unprivileged port: https://hub.docker.com/layers/kong/httpbin/0.2.0/images/sha256-f142bf7c8d532447a3b81b33bb8060ac6ecaa94be9256d81a175945fd47ed8b8?context=explore
> Fix httpbin sample's command

- tests/integration/ambient/baseline_test.go
The sidecar test is just way too unreliable at this point, disable for
now.
> Reduce ambient flakes in TestServiceDynamicEnroll

- tests/integration/ambient/baseline_test.go
https://github.com/istio/istio/pull/53310 made the test stricter in some ways, and less strict in others.
The 'more strict' part is causing issues as well unfortunately, so revert that part
> Reduce ambient flakes in TestServiceDynamicEnroll 2

- pilot/pkg/serviceregistry/kube/controller/pod.go
- pilot/pkg/xds/endpoints/endpoint_builder.go
- pilot/pkg/xds/waypoint_test.go
- pilot/test/xdstest/extract.go
Today, we set an address pointing to the internal listener, and an additionalAddress pointing to the raw IP. The raw IP is never used.
Per https://github.com/envoyproxy/envoy/issues/36318 - we cannot actually set the additional address with the internal listener.
In order to properly test this I also had to fix https://github.com/istio/istio/issues/53333
> Ambient: fix incorrect dualstack EDS with tunnelling

- pkg/test/framework/components/istio/installer.go
This is a typo fix to ensure per cluster direcotories created before writing dump files.
Triggered when `-istio.test.istio.dumpManifests` flag is specified during the test. E.g.
```
2024-09-27T23:32:45.782114Z     info    tf      === BEGIN: Cleanup Istio [Suite=security] ===
2024-09-27T23:32:45.782489Z     error   tf      Unable to create directory for dumping cluster-0 install manifests: mkdir /tmp/security-e2dec165f98347419cbcd5/_suite_context/istio-deployment-3933594192/manifests: file exists
2024-09-27T23:32:45.782928Z     error   tf      Failed writing manifest 0/1 in cluster-0: open /tmp/security-e2dec165f98347419cbcd5/_suite_context/istio-deployment-3933594192/manifests/cluster-0/manifest-0.yaml: no such file or directory …
```
> Fix missing directory for manifests dump in integration test

- go.mod
- go.sum
Not sure why https://github.com/istio/istio/pull/52577 was to 26.1.4
not 26.1.5. Probably a mistake...
> 1.23: bump to docker 26.1.5

- tests/integration/ambient/baseline_test.go
This works since the later keys override the former ones... weird
> cleanup invalid yaml in test

- pilot/pkg/serviceregistry/kube/conversion.go
- pilot/pkg/serviceregistry/kube/conversion_test.go
- pkg/config/analysis/analyzers/util/service_lookup.go
- pkg/config/analysis/analyzers/util/service_lookup_test.go
- releasenotes/notes/53429.yaml
This PR allows users to put extra spaces between namespaces in `networking.istio.io/exportTo` annotation.
Currently, adding extra spaces between namespaces in `networking.istio.io/exportTo` annotation causes unexpected behavior. For example, `networking.istio.io/exportTo: ns1, ns2` is recognized as `ns1` and ` ns2` namespaces (Note the extra space in `ns2` namespace), and as a result it's not exported to `ns2` namespace properly.
This PR trims the extra spaces after splitting the value into multiple items. In Kubernetes, Namespace must be [RFC 1123 label name](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#namespaces-and-dns), so this doesn't break backward compatibility.
Fix: #53429
> Allow extra spaces between namespaces in networking.istio.io/exportTo annotation

- pilot/pkg/model/cluster_local.go
- pilot/pkg/model/cluster_local_test.go
- releasenotes/notes/52367.yaml
Please provide a description of this PR:
Backport https://github.com/istio/istio/pull/52367 to Istio 1.22, support clusterLocal host exclusions for multi-cluster.
1.23 release here: https://github.com/istio/istio/pull/53443
> [release-1.22] Support clusterLocal host exclusions for multi-cluster

- pilot/pkg/config/kube/gateway/conversion.go
- pilot/pkg/config/kube/gateway/testdata/eastwest-remote.status.yaml.golden
- pilot/pkg/config/kube/gateway/testdata/eastwest-remote.yaml
This is the gateway mode that just represents a remote thing. it does
not get infrastructure deployed in the local cluster.
Writing status is useful merely because it shows up in `kubectl` and
makes things not show up as 'Unknown, waiting for controller'
everywhere.
> gateway: report status for istio-remote gateway

- istioctl/pkg/injector/injector-list.go
- releasenotes/notes/53450.yaml
Support filter resource by namespace for `istioctl x injector list`:
1. The global flags include flags for specifying namespaces, but they are not implemented in this command.
2. When there are too many resources such as namespaces, it is useful to support filtering and printing resources by namespace.
> istioctl: support filter resource by namespace for injector list

- pkg/adsc/adsc.go
- pkg/adsc/delta.go
- pkg/adsc/delta_test.go
This current has odd behavior.
1. It has a Run() method and allows retries. Run returns after the first
connection is done, and retries in the background.
2. It accepts a context, but doesn't use it for cancellation; instead,
the caller should call .Close() explicitly
This PR changes both of these. Run() handles all execution of the
initial connection + retries, and respects the context for cancellation
> adsc: improve backoff for delta mode

- istioctl/pkg/ztunnelconfig/ztunnelconfig.go
- tests/integration/ambient/istioctl_test.go
Right now its just entirely ignored, as seen from our tests passing a
bogus flag entirely. This means if ztunnel is outside of istio-system we
cannot do anything about it really.
> Respect --namespace flag in `istioctl ztunnelconfig`

- releasenotes/notes/48368.yaml
- tools/istio-clean-iptables/pkg/cmd/cleanup.go
- tools/istio-clean-iptables/pkg/cmd/cleanup_test.go
- tools/istio-clean-iptables/pkg/cmd/testdata/ipnets-with-kube-virt-interfaces.golden
- tools/istio-clean-iptables/pkg/cmd/testdata/kube-virt-interfaces.golden
- tools/istio-clean-iptables/pkg/config/config.go
Fixes #48368
This issue does not affect Istio 1.24 out-of-the-box, as 1.24 is the first version to use the new cleanup methodology by default (via `istio-iptables --cleanup-only`).
This commit fixes the legacy istio-clean-iptables methodology, which is the only one available for Istio 1.22 and 1.23 (a cherry-pick will be needed for those versions).
I plan to remove the legacy istio-clean-iptables methodology in Istio 1.25, as it is prone to issues like this, which have occurred 3 or 4 times already.
> Fix kube-virt-related rules cleanup in legacy istio-clean-iptables

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
wait for index to sync before starting the status queue
> don't process status queue while ambient index is not synched

- releasenotes/notes/48368.yaml
- tools/istio-clean-iptables/pkg/cmd/cleanup.go
- tools/istio-clean-iptables/pkg/cmd/cleanup_test.go
- tools/istio-clean-iptables/pkg/cmd/testdata/ipnets-with-kube-virt-interfaces.golden
- tools/istio-clean-iptables/pkg/cmd/testdata/kube-virt-interfaces.golden
- tools/istio-clean-iptables/pkg/config/config.go
Proper backporting of https://github.com/istio/istio/pull/53484 as the automatic one failed (#53491).
The tests failed as the testdata diverged due to https://github.com/istio/istio/pull/52881 missing in 1.22 branch (as it is not required there).
> [release-1.22] Fix kube-virt-related rules cleanup in legacy istio-clean-iptables

- pilot/pkg/model/cluster_local.go
- pilot/pkg/model/cluster_local_test.go
- releasenotes/notes/52367.yaml
Please provide a description of this PR:
Backport https://github.com/istio/istio/pull/52367 to Istio 1.23, support clusterLocal host exclusions for multi-cluster.
1.22 release here: https://github.com/istio/istio/pull/53442
> [release-1.23] Support clusterLocal host exclusions for multi-cluster (#52367)

- tools/packaging/common/envoy_bootstrap.json
Earlier the deferred_stat_options were under the condition for cluster_manager. Now bringing it out of the condition.
> Bring deferred_stat_options out of the cluster_manager's condition

- istioctl/pkg/injector/injector-list.go
- releasenotes/notes/53571.yaml
`istioctl x injector list` will print out all webhook information. In an online environment, most of them are not related to istio. Printing them out is meaningless and the display effect is not friendly.
> istioctl: fix injector list prints webhooks not related to istio

- pkg/slices/slices.go
- pkg/slices/slices_test.go
Similar with native `slices.DeleteFunc`, but `FilterInPlace` uses `keep` not `del`.
This will save 14%~30% cpu cost.
```
func BenchmarkFilterInPlace(b *testing.B) {
ss := make([]int, 0, 100)
for i := 0; i < 100; i++ {
ss = append(ss, i)
}
b.ResetTimer()
b.Run("keep all", func(b *testing.B) {
for i := 0; i < b.N; i++ {
FilterInPlace(ss, func(s int) bool {
return true
})
}
})
b.Run("filter all", func(b *testing.B) {
for i := 0; i < b.N; i++ {
FilterInPlace(ss, func(s int) bool {
return false
})
}
})
}
---
goos: darwin
goarch: amd64
pkg: istio.io/istio/pkg/slices
│   old.txt   │              new.txt               │
│   sec/op    │   sec/op     vs base               │
FilterInPlace/keep_all-12     184.4n ± 5%   158.5n ± 3%  -14.07% (p=0.002 n=6) …
```
> minor optimize FilterInPlace

- samples/ambient-argo/application/details-waypoint.yaml
- samples/ambient-argo/application/ingress-gateway.yaml
- samples/ambient-argo/application/reviews-waypoint.yaml
- samples/ambient-argo/application/route-reviews-90-10.yaml
- samples/bookinfo/gateway-api/bookinfo-gateway.yaml
- samples/bookinfo/gateway-api/route-all-v1.yaml
- samples/bookinfo/gateway-api/route-reviews-50-v3.yaml
- samples/bookinfo/gateway-api/route-reviews-90-10.yaml
- samples/bookinfo/gateway-api/route-reviews-v1.yaml
- samples/bookinfo/gateway-api/route-reviews-v3.yaml
- samples/helloworld/gateway-api/helloworld-gateway.yaml
- samples/helloworld/gateway-api/helloworld-route.yaml
- samples/httpbin/gateway-api/httpbin-gateway.yaml
- samples/tcp-echo/gateway-api/tcp-echo-all-v1.yaml
s/v1beta1/v1/ for Gateway and HTTPRoute objects.  TCPRoute remains only in the v1alpha2 group.
> Update Gateway API version in samples to v1

- pilot/pkg/features/ambient.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/service.go
- pilot/pkg/networking/core/cluster_cache.go
- pilot/pkg/networking/util/util.go
- pilot/pkg/serviceregistry/aggregate/controller.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/services.go
- pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop.go
- pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop_test.go
- pilot/pkg/serviceregistry/memory/discovery.go
- pilot/pkg/xds/endpoints/endpoint_builder.go
- pilot/test/xdstest/extract.go
- pkg/kube/krt/core.go
- pkg/kube/krt/util.go
- tests/integration/ambient/waypoint_test.go
This PR adds new functionality to support ingress envoys sending to waypoints.
This is a tricky case. Both the ingress and waypoints are applying routing and other policies. For instance, I may do an "add header foo=bar" operation.
In the traditional sidecar model, you would apply the same policy to 'mesh' and to the gateway; traffic never goes through _both_.
Today, we force users to do the same thing with the waypoint model, which seems sub-optimal. For instance, why should I (as a service producer) define a canary rule in two places? This is especially troublesome with the ownership and delegation requirements to give a lower privilege service owner write access to the high-priv gateway.
However, unconditionally forwarding the waypoint has the problem of double policies. In the 'add …
> Support sending from ingress -> service waypoint

- pilot/pkg/networking/core/listener_waypoint.go
- pilot/pkg/xds/waypoint_test.go
- releasenotes/notes/53588.yaml
This change adds support for `connection.sni` authz policy applied to a waypoint.
Fixes #52752.
> waypoint: enable TLS inspector if TLS service is enrolled

- pkg/kube/krt/static.go
- pkg/kube/krt/static_test.go
Maybe we should rename this to 'direct'.
The intent of this collection is to be the bridge into other systems.
You either have:
* Static collection, bridging some other state into a Collection
* Informer, logically the same as ^ but optimized since we use it so
much
* Transformation of collections to other collections
The static collection was originally immutable which made it not fit for
bridging other state that can change. This makes that possible. This
will be useful to read config from files, xDS, etc.
> krt: allow changing the state of the static collection

- pilot/cmd/pilot-agent/status/server.go
- pilot/cmd/pilot-agent/status/server_test.go
- pkg/kube/inject/app_probe.go
- pkg/kube/inject/app_probe_test.go
- pkg/kube/inject/testdata/inject/hello-probes.proxyHoldsApplication.yaml.injected
- pkg/kube/inject/testdata/inject/hello-probes.yaml
- pkg/kube/inject/testdata/inject/hello-probes.yaml.injected
Rewrite the `postStart` and `preStop` lifecycle hooks in app containers if present when `sidecar.istio.io/rewriteAppHTTPProbers` is enabled.
Refer #30857
> Rewrite container lifeycle hooks for pilot to takeover

- tests/integration/security/jwt_test.go
**Changes:**
- Moved the `/healthz` test case to the beginning of the subtests.
**Description:**
The /healthz endpoint is typically used to check the health status of services before performing more complex tests. If the health check fails, it would indicate that something is wrong with the setup or the system is not ready for the rest of the tests, potentially saving time in finding the root cause of test failure.
By running the allow healthz check first:
- We can detect if the service is up and operational early in the test.
- This provides faster feedback during continuous integration (CI) runs, especially in environments where test time is critical.
**Justification:**
- Efficiency: Ensures that system readiness is confirmed before running complex authentication tests.
- Error …
> Reordered healthz test case to ensure that the health status is checked first

- prow/release-commit.sh
This aligns with how we build in release-builder for the official builds
> release: use client-go from go.mod

- go.mod
- go.sum
- pkg/config/xds/filter_types.gen.go
From the branch, we had g-c-p from `main`. We should match it to Envoy
1.32 per the release branching steps
> [release-1.24] Downgrade go-control-plane to match Envoy 1.32

- istioctl/pkg/install/k8sversion/version.go
- istioctl/pkg/install/k8sversion/version_test.go
Align tooling with our documentation that is at
https://preliminary.istio.io/latest/docs/releases/supported-releases/.
> Bump minimum Kubernetes version

- pilot/pkg/grpc/grpc.go
https://github.com/istio/istio/blob/7a52323d5e9228898b2b332251898c4420c3cab5/pilot/pkg/grpc/grpc.go#L119-L141
The GRPCErrorType function does not return `UnexpectedError` causing it to always be true when used.
So I modify GRPCErrorType function return UnexpectedError in the end.
#53730
> modify GRPCErrorType function return UnexpectedError in the end

- samples/httpbin/httpbin-nodeport.yaml
Found this typo while manually cherry picking the original commit for 1.23 in PR https://github.com/istio/istio/pull/53732 
Original PR https://github.com/istio/istio/pull/53315
> Fix httpbin version typo

- pkg/istio-agent/xds_proxy_delta_test.go
- pkg/istio-agent/xds_proxy_test.go
- pkg/wasm/convert.go
- pkg/wasm/convert_test.go
- releasenotes/notes/53279.yaml
- tests/binary/dependencies_test.go
- tests/integration/telemetry/api/stats_test.go
- tests/integration/telemetry/api/wasmplugin_test.go
This PR aims to fix this issue #53279
* Add default deny rule for network/http wasmplugin when pull wasm image fails.
* fix default allow-all network rbac rule, cause `StatPrefix` in network rbac filter is required.
> add default deny rule for wasmplugin & fix default network allow-all

- tests/integration/telemetry/api/stats_test.go
- tests/integration/telemetry/api/wasmplugin_test.go
fix integration-test TestBadWasmRemoteLoad for default deny-all policy when wasmplugin  FAIL_CLOSE
#53363 broke TestBadWasmRemoteLoad and this PR is a fix for it.
> fix integration-test TestBadWasmRemoteLoad for default deny-all policy

- pkg/config/security/security.go
- pkg/config/security/security_test.go
- tests/integration/security/authz_test.go
- Verifies each segment is a valid string literal
- Ensures `{**}` is the last operator in the template
- Aligns pre validation with Envoy's validation for path template
> Update path template validation for AuthzPolicy

- pilot/pkg/leaderelection/k8sleaderelection/leaderelection.go
The `wait.PollImmediateUntil` has been deprecated:
```
// Deprecated: This method does not return errors from context, use PollUntilContextCancel.
// Note that the new method will no longer return ErrWaitTimeout and instead return errors
// defined by the context package. Will be removed in a future release.
func PollImmediateUntil(interval time.Duration, condition ConditionFunc, stopCh <-chan struct{}) error {
return PollImmediateUntilWithContext(ContextForChannel(stopCh), interval, condition.WithContext())
}
```
> cleanup deprecated function wait.PollImmediateUntil

- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/network.go
- pilot/pkg/serviceregistry/kube/controller/network_test.go
The syncall has been registered as a gateway handler here
https://github.com/istio/istio/blob/f37a8d2481bdfa5fb4ffde695246cf122d5bba42/pilot/pkg/serviceregistry/kube/controller/controller.go#L306-L311
And it will be called in `reloadNetworkGateways`
>  Remove duplicate ambient index sync all

- istioctl/pkg/writer/table/writer.go
- pilot/pkg/networking/core/httproute.go
We can use the built-in `min` and `max` functions since Go 1.21.
Reference: https://go.dev/ref/spec#Min_and_max
> Replace min/max helpers with built-in min/max

- pilot/pkg/networking/core/route/route.go
- pilot/pkg/networking/core/route/route_test.go
If you set an invalid redirect code in a `VirtualService`, istiod will crash due to the weird Go quirk that [nil is not always nil
](https://yourbasic.org/golang/gotcha-why-nil-error-not-equal-nil/). Added a comment and a test to prevent regressions
> Fix bug where invalid redirect codes in VirtualService caused proto marshal errors

- pkg/bootstrap/platform/gcp.go
- pkg/bootstrap/platform/gcp_test.go
Current implementation is assuming that the cluster location is "zone" when creating Locality for GCP platform. 
However, for the GKE regional cluster, it is not true.
Therefore, this PR proposes to use "metadata" server to get the zone, if the cluster location is not zonal.
Change-Id: I27f1b699f7ea464eb43993eb7870ee15f7ffc8ad
> Use the zone from the metadata for creating locality

- pilot/pkg/networking/core/cluster_builder_test.go
- pilot/pkg/networking/core/cluster_traffic_policy.go
If the meshConfig has h2Upgrade set and DR has useClientProtocol, the h2Upgrade is done. This is not according to the [Istio Docs](https://istio.io/latest/docs/reference/config/networking/destination-rule/#ConnectionPoolSettings-HTTPSettings), which says `when useClientProtocol is set set to true,
h2_upgrade_policy will be ineffective i.e. the client connections will not be upgraded to http2.`
This PR corrects this behavior.
> [fix]: do not h2upgrade when useClientProtocol is set in DR

- istioctl/pkg/analyze/analyze.go
- releasenotes/notes/53339.yaml
It's good to add a shortcode for the revision of `istioctl analyze` like other place, and there are no other parameters to confuse it here.
> istioctl: add revision shortcode for analyze

- pilot/pkg/model/sidecar.go
benchmark result:
```
goos: darwin
goarch: arm64
cpu: Apple M2
│   old.txt    │              new.txt              │
│    sec/op    │   sec/op     vs base              │
ConvertIstioListenerToWrapper/small-exact-8        2.320µ ±  1%   2.232µ ± 0%  -3.77% (p=0.002 n=6)
ConvertIstioListenerToWrapper/small-wildcard-8     1.121µ ±  1%   1.042µ ± 1%  -7.05% (p=0.002 n=6)
ConvertIstioListenerToWrapper/small-match-all-8    5.409µ ±  0%   5.365µ ± 3%       ~ (p=0.061 n=6)
ConvertIstioListenerToWrapper/middle-exact-8       14.81µ ±  0%   14.50µ ± 0%  -2.09% (p=0.002 n=6)
ConvertIstioListenerToWrapper/middle-wildcard-8    15.23µ ±  1%   14.97µ ± 0%  -1.75% (p=0.002 n=6)
ConvertIstioListenerToWrapper/middle-match-all-8   54.92µ ± 49%   55.05µ ± 1%       ~ (p=0.937 …
```
> optimize performance and minor refactor

- pkg/kube/inject/webhook.go
- pkg/kube/inject/webhook_test.go
This PR returns the error and fails immediately instead of just logging it and continuing processing. This PR also adds detailed error messages to other failure paths to help the user understand what went wrong. See this [thread ](https://istio.slack.com/archives/C01TBTKLA9Z/p1727363704546059?thread_ts=1727182662.785479&cid=C01TBTKLA9Z) for more details.
Related to #53357
> return error instead of just logging it and add detailed error messages

- cni/pkg/ipset/nldeps_linux.go
- releasenotes/notes/53862.yaml
[`vishvananda/netlink` _seems to_ have a bug where it defaults to revision=1 for `hash:ip,port` ](https://github.com/vishvananda/netlink/blob/main/ipset_linux.go#L398) but defaults to revision=0 for `hash:ip` (what we use).
This causes breakages in some cases with Docker-based nodes: https://github.com/istio/istio/issues/53512
Explicitly setting `Revision=1` during ipset creation seems to work correctly in all cases found thus far.
I really am not clear on what `revision` _does_ so this is a bit sketch, but it seems to work more reliably, including in spots where before we got errors about `comment` validation (older images).
> Explicitly specifiying ipset revision seems to fix some ipset creation/insertion corner cases

- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- releasenotes/notes/waypoint-revision.yaml
In 1.24, we started preferring to use Hostname as the gateway object. However, this has a (few) problem:
* During upgrade, there is a small amount of time before status is updated.
* With revisions, this time can be indefinite if the older revision is the leader
* 3p implementations can use IP address
This PR adds support for either type. A test is added to cover this case.
Fixes https://github.com/istio/istio/issues/53883
> ambient: fully support Gateway's with IP address in status

- pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/queue_test.go
We were incorrectly writing the condition with `""` type which confused
things. Instead, the test is supposed to not set them in this case
> Fix flake in TestQueue

- cni/pkg/iptables/iptables.go
- releasenotes/notes/53951.yaml
- tools/istio-iptables/pkg/dependencies/implementation_linux.go
Change-Id: Ib636985911338401aeefb9d03e8789af2b65e9c9
This was spun out of the idempotency/reconciliation PR (#53153) as it is no longer planned for 1.24.1.
Automated test coverage for this is already present in that PR.
Fixed in-pod deletion errors caused by the deletion logic incorrectly assuming that certain commands would work, even when the relevant rules were not present. The creation of these rules depends on the values of tproxy and ingressMode. Therefore, certain failed deletion commands cannot reliably indicate successful deletion.
> Ignore delete cmds errors from optional iptables rules

- istioctl/pkg/authz/authz_test.go
- istioctl/pkg/authz/listener.go
- istioctl/pkg/authz/testdata/configdump.yaml
- releasenotes/notes/53894.yaml
This PR extends the `istioctl x authz check` command to support outputting AuthorizationPolicies with the `CUSTOM` action. Currently policies with the `CUSTOM` action aren't included in the output which makes debugging more difficult and might cause confusion as to which policies are actually loaded.
> feat(istioctl): add support for custom authz

- manifests/charts/istio-cni/templates/daemonset.yaml
- releasenotes/notes/53829.yaml
* Set AppArmor annotation instead of appArmorProfile
appArmorProfile is not support in Kubernetes 1.29
* Update release note
* clarify reasoning for setting annotation rather than appArmorProfile in the securityContext.
> [release 1.24] Set AppArmor annotation to unconfined on istio-cni-node (#53953)

- releasenotes/notes/propagate-injection-config-errors.yaml
Add the release note that was missed for PR #53708. (Adding this now after realizing a backport might make sense for the change). As a consequence, we should backport this wherever #53708 ends up.
> Add release note that was missed for PR 53708

- pkg/test/framework/components/zipkin/kube.go
- pkg/test/framework/components/zipkin/zipkin.go
- tests/integration/telemetry/tracing/otelcollector/tracing_test.go
- tests/integration/telemetry/tracing/zipkin/client_tracing_test.go
- tests/integration/telemetry/tracing/zipkin/server_tracing_test.go
Fixes: #53977 
All telemetry tracing tests are failing during execution on Openshift.
During the tests execution, the traffic is being sent and should be captured through the service routed through ingress gateway.
In Kind environment, the "sslip.io" service is used, which servers as a DNS service that works with embedded ip addresses and returns that ip address as a name during query.
But in Openshift it's not working.
The Openshift cluster has a routable and dns resolvable ingress gateway. But when the test adds the service "tracing' to the ingress gateway - "tracing.<ingress-gateway>/api/v2...",
dns resolve is not working anymore and query to that url fails. Since we're not able to create a custom dns record to that url during each test …
> Fix telemetry tracing tests on Openshift

- istioctl/pkg/waypoint/waypoint.go
- releasenotes/notes/54064.yaml
**Fixed** `istioctl waypoint delete --all` deletes gateway resources that are not waypoints.
fix https://github.com/istio/istio/issues/54056
> fix istioctl waypoint delete deletes things which are not waypoints 

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop.go
- pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/queue.go
- pkg/kube/krt/collection.go
- pkg/kube/krt/core.go
- pkg/kube/krt/fetch.go
- pkg/kube/krt/filter.go
- pkg/kube/krt/helpers.go
- pkg/kube/krt/informer.go
- pkg/kube/krt/internal.go
- pkg/kube/krt/join.go
- pkg/kube/krt/singleton.go
- pkg/kube/krt/static.go
The idea was this was supposed to avoid the ambiguity of which type the
`string` key was for. But in practice, there is no meaningful way to use
this, since a caller of `GetKey` has no way to get a key magically.
It is, however, slightly useful internally where we deal with multiple
types (like `map[Key[I]]Key[O]`).
This PR removes it from the user facing stuff but keeps the internal
usage where its helpful.
> krt: drop the custom Key type

- pilot/pkg/model/telemetry.go
- pilot/pkg/xds/waypoint_test.go
See https://github.com/istio/api/pull/3366. We simply didn't pass the
value thru far enough
> ambient: fix Telemetry-service binding for logs

- pilot/pkg/networking/core/listener.go
- pilot/pkg/networking/core/listener_test.go
The relevant envoy issue has been fixed https://github.com/envoyproxy/envoy/issues/13601 - We do not have to add this automatically
> remove unnecessary tls inspector

- pilot/pkg/leaderelection/leaderelection.go
On kubernetes, we always set `REVISION`. It will be 'default' if there
is no revision.
When running in other environments, it may be `''`. This ends up with a
problem for leader election: two processes are leaders for the same
thing:
```
NAME                               HOLDER                    AGE
istio-gateway-deployment           not-on-kubernetes         26m
istio-gateway-deployment-default   istiod-7dd98766d4-mbqmw   57m
```
This normalizes the revision to avoid this issue
> leader election: default revision properly

- pkg/config/schema/kubeclient/common.go
- pkg/config/schema/kubeclient/common_test.go
- pkg/config/schema/metadata.yaml
- pkg/kube/kclient/client.go
```
Register[*v1.NetworkPolicy](
gvr, gvk,
func(c ClientGetter, namespace string, o metav1.ListOptions) (runtime.Object, error) {
return c.Kube().NetworkingV1().NetworkPolicies(namespace).List(context.Background(), o)
},
func(c ClientGetter, namespace string, o metav1.ListOptions) (watch.Interface, error) {
return c.Kube().NetworkingV1().NetworkPolicies(namespace).Watch(context.Background(), o)
},
)
```
When we set up a dynamic client like this, we can easily get the informer with `GetInformerFiltered`. 
The most common utility used to setup the clients for KRT collections is to use `NewDelayedInformer` which bypasses `GetInformerFiltered`.
This change makes use go through `GetInformerFiltered[T]`  to ensure registered clients can be used.
> NewDelayedInformer allows using clients from Register

- tests/integration/ambient/cniupgrade/main_test.go
Can't repro the postsubmit flakes locally - looks like pods under test are terminating/going unhealthy mid-suite (and then coming back so subsequent tests pass), which could be a timing thing related to this rollout restart of the app pods.
This at least stalls the test until we are sure the app pods in the test namespace are all back before proceeding, to rule this out.
> [integ tests] ensure *all* pods are healthy before continuing CNI test

- pkg/kube/krt/collection.go
- pkg/kube/krt/fetch.go
- pkg/kube/krt/filter.go
- pkg/kube/krt/index.go
- pkg/kube/krt/internal.go
This PR is in draft pending https://github.com/istio/istio/pull/53994, as it builds on it. I will rebase once that lands, and this will get much smaller
Consider a collection like this:
```go
NewCollection(Pods, func(p Pod) {
services := Fetch(Services, FilterIndex(ServiceNamespaceIndex, p.Namespace))
})
```
We call `Pods` the primary dependency, and `Services` a secondary dependency.
Currently, when a secondary dependency changes, we need to determine which primary objects depend on it so we can recompute them. That is, when Service `foo/bar` changes, we look for any pods that depended on services in namespace `foo`.
Today, we do this by an O(n) scan on all primary inputs. This can be problematic when the secondary input changes often, and the size of the primary input is large. For …
> krt: introduce a reverse index for dependencies, dramatically reducing CPU usage

- cni/pkg/iptables/iptables.go
- cni/pkg/iptables/iptables_e2e_test.go
- cni/pkg/nodeagent/informers.go
- cni/pkg/nodeagent/net.go
- cni/pkg/nodeagent/server.go
- tools/istio-iptables/pkg/capture/run.go
- tools/istio-iptables/pkg/dependencies/implementation.go
- tools/istio-iptables/pkg/dependencies/implementation_linux.go
- tools/istio-iptables/pkg/dependencies/implementation_unspecified.go
- tools/istio-iptables/pkg/dependencies/interface.go
- tools/istio-iptables/pkg/dependencies/stub.go
Ensure all logs in the CNI codepath have the pod context associated for
debugging.
> cni: propogate log context further

- pilot/pkg/networking/core/serviceentry_simulation_test.go
- pilot/pkg/serviceregistry/serviceentry/controller.go
- pilot/pkg/serviceregistry/serviceentry/controller_test.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pilot/pkg/serviceregistry/serviceentry/conversion_test.go
- pilot/test/xdstest/extract.go
- pilot/test/xdstest/validate.go
- pkg/dns/server/name_table.go
- pkg/dns/server/name_table_test.go
- releasenotes/notes/fix-overlapping-se.yaml
- tests/integration/pilot/common/routing.go
This has a very long history of back-and-forth on bugs/fixes/regressions. Ill try to capture the history accurately...
Istio 1.22 introduced a regression: https://github.com/istio/istio/issues/51747 causing SE with multiple addresses to get some of their addresses ignored. I cannot actually find the PR that broke things but the issue has plenty of detail.
From that investigation, we found this occurs only when there is no Sidecar object -- otherwise its fine. 
Meanwhile, https://github.com/istio/istio/pull/51967 was merged and cherrypicked to 1.22 and 1.23. This fixed the issue, but caused 2 new ones:
* https://github.com/istio/istio/issues/52847
* https://github.com/istio/istio/issues/52944
This was reverted in 1.22 https://github.com/istio/istio/pull/52952 and 1.23 …
> Fix NACKS when service addresses partially overlap

- cni/pkg/ipset/ipset.go
- cni/pkg/ipset/nldeps_linux.go
- cni/pkg/ipset/nldeps_mock.go
- cni/pkg/nodeagent/server.go
- cni/pkg/nodeagent/server_test.go
Fundamentally we have 2 sources of pod ADDs in ambient's node agent that we have to ensure don't step on each other (we only have 1 possible source of pod REMOVEs, so that's easier to reason about) - the CNI plugin, and the informer.
Once we get [iptables reconciliation](https://github.com/istio/istio/pull/53153) in ambient, this gets much easier, but there's one other annoying bit of state that traditionally doesn't play nice with upserts or idempotency - the `ipsets` we use for pod health checks.
This PR attempts to fix that, anticipating https://github.com/istio/istio/pull/53153 so that we can eventually just not care about synchronization in the informer as much, since it will be safe to ADD the same pod 2x regardless of source.
I had …
> Prep for iptables idempotency by making ipset ops (safely) idempotent by doubling-down on comments

- pilot/pkg/model/service.go
We are using `==` to compare pointers. We actually want to compare the
underlying contents.
Without this we may get into a bad loop of status writing
> ambient: fix case of incorrect equals leading to excessive load

- tests/integration/ambient/baseline_test.go
The [failing](https://prow.istio.io/view/gs/istio-prow/logs/integ-ipv6_istio_postsubmit/1866264993557647360) test [flakes](https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/54136/integ-ambient_istio/1863745610658615296) for the test flakes described in #54146 (potentially caused by #54073) are sending traffic to port 9090 while the test in question only has port rules for the http workload port (with a corresponding service port of 8080). If we add the workload tcp port to the policy, it should fix the flakes
> Add tcp port to peer authn test

- cni/pkg/nodeagent/net.go
- cni/pkg/nodeagent/options.go
- cni/pkg/nodeagent/server.go
- tools/istio-iptables/pkg/capture/run_test.go
- tools/istio-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/dependencies/implementation.go
- tools/istio-iptables/pkg/dependencies/implementation_linux.go
Related to https://github.com/istio/istio/issues/54050 but I want to do some more testing to see if I can reproduce that reliably first.
Basically:
- Always run `iptables-legacy` with a waitlock, even if we are using the sandboxed lockfile
- In the sandboxed lock mode we have, we use the netns file as the lockfile, and assume we don't have to wait for it to be unlocked. This mostly works pretty well, but a netns is just a file like any other and we can't assume no other process on the node has locked the netns for some reason - so reintroduce the wait arg for that case too. This shouldn't trigger any blanket delays since we will only wait if we can't grab the sandboxed lockfile for that pod as a first thing.
- Rename the `iptables-legacy` …
> Always wait for `iptables-legacy` lock, even if using sandboxing. Also, rename var.

- cni/pkg/nodeagent/informers_test.go
- cni/pkg/util/podutil.go
After a recent PR flakes like https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1866952380273135616 showed up, which are reproducible (eventually) with `stress`.
This is because some of these tests aren't waiting for the correct number of events before proceeding. Looking at them, it's obvious they aren't correct, but it wasn't obvious to the idiot that wrote them (me) at the time.
This PR 
- tightens up the event counting the unit tests use to keep things deterministic (actual cause of the flakes)
- puts explicit invocation counts on all mocks (these are good, the only reason the flake manifested in the first place in the one test they're used)
A 20 min `stress` run of the affected tests here seemed good enough to …
> [ambient] Fix some unit test flakes for ambient informer

- cni/pkg/nodeagent/informers_test.go
https://github.com/istio/istio/pull/54298 fixed up some, but this test still had event counts that were not quite right, leading to it flaking on a different mock call, e.g: https://prow.istio.io/view/gs/istio-prow/logs/unit-tests-arm64_istio_postsubmit/1867632906684338176
Also, at this point, I'm just moving everything to `Exact` counts for all event assertions, `AtLeast` isn't much use/prone to hide issues/isn't deterministic enough for what we're doing here.
stress:
> stress ./nodeagent.test -test.v -test.run TestJobPodRemovedWhenPodTerminate
> 5m5s: 1784 runs so far, 0 failures, 10 active
> Event counts stil not exact for this test

- cni/pkg/install/binaries.go
- cni/pkg/install/binaries_test.go
- releasenotes/notes/54311.yaml
Fix for https://github.com/istio/istio/issues/54311
> fix: clear tmp files from previous run if exist before copy cni binaries again

- cni/pkg/nodeagent/informers_test.go
https://github.com/istio/istio/pull/54320 still did not eliminate every race - for all tests we need to wait for both `add` AND `update` events to settle, or initial events can get delayed and skew later count expectations (I had thought it was just `ADD` events during the initial fake informer boot, but I was wrong).
See 
- https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1868599546913755136
- https://prow.istio.io/view/gs/istio-prow/logs/unit-tests-arm64_istio_postsubmit/1868687172098330624
> Still some racy tests - there are more initial update events to wait on

- tests/integration/telemetry/api/customize_metrics_test.go
- tests/integration/telemetry/api/registry_setup_test.go
- tests/integration/telemetry/api/setup_test.go
Fixes: https://github.com/istio/istio/issues/54271
Make the telemetry api "registry-redirector" tests agnostic to any platform, including Openshift.
Kind environment require to keep the images in "kind-registry" to avoid DNS issues in IPv6.
For that add "IsKindCluster" function to identify if the cluster is "Kind" based. If so, apply the "kind-registry" config.
> Adapt telemetry api "registry-redirector" tests to Openshift

- prow/integ-suite-kind.sh
Update the base k8s to test against as 1.32.0
> use k8s 1.32.0 as base to run tests against

- pilot/pkg/xds/debug.go
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
Envoy Admin API only checks if include_eds exists: https://github.com/envoyproxy/envoy/blob/b87da3fa9f008d87ab02df53840c5246f1ba6209/source/server/admin/config_dump_handler.cc#L126.
It doesn't require the value to be "true".
> debug: align ConfigDump behavior with Envoy Admin API

- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
- pilot/pkg/config/kube/gateway/testdata/deployment/istio-upgrade-to-1.24.yaml
- releasenotes/notes/54145.yaml
* Fix upgrade to 1.24, the managed gateway/waypoint cannot be patched
* revert debug log level
* Fix comments
* address comment
* lint
* add legacy label
---------
> Fix patching deployment when upgrade to istio 1.24 (#54170)

- cni/pkg/cmd/root.go
- pkg/test/framework/components/istio/cleanup.go
- pkg/test/framework/components/istio/installer.go
- tests/integration/ambient/cni/main_test.go
- tests/integration/ambient/util.go
Trying a few things  to understand how/why https://github.com/istio/istio/issues/54303 can happen,  since it's still non-obvious to me how it could and I cannot coerce local repros.
There are, as far as I can see, only 2 possibilities here.
1. The `kubeclient` we use on shutdown is reporting stale data - the DS has been deleted, our pods get a SIGTERM, we `GET` the DS from inside the pod, and it's still there, even though our pod has been told to terminate _because_ it was deleted - e.g. racy/stale reads from the K8S API server. I haven't been able to repro this with `helm` or `istioctl` or plain old manifest deletion.  It is _very_ unlikely that this is the case.
2. `TestCNIMisconfigHealsOnRestart` is putting the installer into a bad state …
> Skip test/try to diagnose test flakes

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_serviceentry_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/meshconfig.go
- pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
- pilot/pkg/serviceregistry/kube/controller/ambient/services.go
- pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop.go
- pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pkg/kube/kclient/client.go
- pkg/kube/kclient/delayed.go
- pkg/kube/kclient/interfaces.go
- pkg/kube/krt/collection_test.go
- pkg/kube/krt/index_test.go
- pkg/kube/krt/informer_test.go
- pkg/kube/krt/join_test.go
- pkg/kube/krt/recomputetrigger_test.go
- pkg/kube/krt/singleton_test.go
- pkg/kube/krt/sync.go
This **partially** backports https://github.com/istio/istio/pull/53994 to 1.24.
The overall PR has two portions:
* Misc refactoring to pass `stop` around everywhere and improve tests to be more resiliant. This is universally better and has no risk. **This is what the backport includes**
* Change the core of `krt` to use queues - this is **not included** in this PR.
The intent here is it prep for a possible full backport of the queue change. Getting the non-controversial parts in now will make that easier (for example, we may put the new changes behind a feature flag -- it will be easy to tell what is flag protected and what isn't).
I will discuss in the upcoming WG meeting a full backport
> Partial backport: krt: move event processing to queue (#53994)

- cni/pkg/nodeagent/informers_test.go
The last PR got it down to this one (`TestExistingPodNotAddedIfNoIPInAnyStatusField`) consistently failing.
Running it by itself with `stress` for an hour didn't produce any flakes at all, which I suspect means other tests are influencing it.
I note the tests preceding this one aren't using `monitortest` waits, so I just made everything use those that needs to do anything with events, and cleaned up some of the old mock-based sync locks so everything uses `monitortest` consistently.
This should fix
- https://prow.istio.io/view/gs/istio-prow/logs/unit-tests_istio_postsubmit/1868777180813594624
and such, and should be the last one of these.
Running all the informer tests under `stress` overnight to make sure I see no flakes tho.
> Commit to monitor event implicit sync and use it for all tests

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
Today, the ambient hot-path is the workload constructors. These are the
highest scale + highest churn generally. Right now, we call
LookupNetworkGateway each time on this path. This call is not something
that was originally meant to be on a hot path, and is instead cached in
PushContext. Its very slow! We then use this and do an O(n) search which
is, again, pretty slow.
In some testing I was doing, while I was on a single cluster I had a
bunch of networks setup from previously, I found 30% of Istiod CPU on
this function. This is very simple to change into a cache O(1) lookup,
which is what I have done in this PR.
> ambient: avoid slow lookup for network

- pilot/pkg/controllers/untaint/nodeuntainter.go
- pkg/kube/krt/helpers.go
- pkg/kube/krt/internal.go
Subtly, taking the pointer of any `any` value is not the same as a
pointer to the underlying value. See https://go.dev/play/p/F5BKfrd7Y89.
This is never exercised in Istio, but gives the false impression this
could be done.
> krt: remove dead code that doesn't work right

- pilot/pkg/xds/cds.go
- pilot/pkg/xds/ecds.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/lds.go
- pilot/pkg/xds/nds.go
- pilot/pkg/xds/rds.go
This is impossible in standard operations. However, a client can connect
to Istiod with arbitrary XDS info. If they declare themselves `ztunnel`,
we don't compute SidecarScope. Most of the generators make an assumption
SidecarScope is non-nil and don't check it. To handle this, we skip
these at the top level.
> xds: do not attempt to push resources to Ztunnel

- pilot/pkg/serviceregistry/kube/controller/controller.go
Our tests set these, but not the real code (which makes this PR hard to
add tests for!). Regression from a recent change only on master.
> ambient: fix forgetting to pass feature flags

- istioctl/pkg/version/version.go
Currently, if xdsRemoteVersionWrapper fails to get an xdsResponse, xdsProxyVersionWrapper does not properly handle a nil *xdsResponse. **xdsResponse is shared between xdsRemoteVersionWrapper and xdsProxyVersionWrapper. **xdsResponse shouldn't be nil since it is set to the address of a nil pointer.
> Handle nil *xdsResponse for istioctl x version

- cni/pkg/cmd/root.go
- cni/pkg/nodeagent/informers.go
- cni/pkg/nodeagent/informers_test.go
- pkg/kube/client.go
- pkg/test/framework/components/istio/cleanup.go
- pkg/test/kube/dump.go
- tests/integration/ambient/cni/main_test.go
Still seeing flakes for integ: https://prow.istio.io/view/gs/istio-prow/logs/integ-k8s-128_istio_postsubmit/1869099513055023104
More hypothesis-es:
1.  Create a failsafe-cleanup `defer` that only runs under node agent panic, on the hypothesis that the agent could be panicking on shutdown somehow ~(haven't figured out a reasonable way to capture shutdown logs on uninstall in the integ tests yet)~.
2. Change integ test cleanup to wait for pods to go away in `istio-system` before considering cleanup "done" (I don't see how this could have caused the problem but in general it's a bit more robust).
3. Add a way to follow pod logs until stream interrupted in integ test cleanup - doing this for any CNI pods that are present during cluster cleanup ATM …
> Collect more integ flake info + fix potential nil panic

- tests/integration/telemetry/api/setup_test.go
This is a followup PR for https://github.com/istio/istio/pull/54348
When "Image-regirector" deployment is created on Openshift cluster and kubeconfig file provided via KUBECONFIG environment variable and the "~/.kube/config" file does not exist, the "IsKindCluster" function fails to allocate the kubeconfig file from the env var.
Modify the function to check the "KUBECONFIG" env var and check the kubeconfig file path from it.
> Modify telemetry test "cluster type detection" function

- go.mod
Kubernetes no longer depends on this, yay.
The original failure was from 2020:
https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/23130/unit-tests_istio/12074.
This tests now passes since k8s moved off of it
> mod: drop last `replace` directive

- manifests/charts/istio-control/istio-discovery/files/waypoint.yaml
- pkg/kube/inject/testdata/inputs/custom-template.yaml.43.template.gen.yaml
- pkg/kube/inject/testdata/inputs/default.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks-json.yaml.15.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-existing-cncf-networks.yaml.14.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-image-pull-secret.yaml.10.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-openshift-custom-injection.yaml.51.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-openshift.yaml.50.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-probes-noProxyHoldApplication-ProxyConfig.yaml.19.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello-probes.yaml.17.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.0.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.1.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.11.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.12.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.13.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.16.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.3.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.4.template.gen.yaml
- pkg/kube/inject/testdata/inputs/hello.yaml.9.template.gen.yaml
- pkg/kube/inject/testdata/inputs/kubevirtInterfaces.yaml.8.template.gen.yaml
- pkg/kube/inject/testdata/inputs/merge-probers.yaml.46.template.gen.yaml
- pkg/kube/inject/testdata/inputs/proxy-override-runas.yaml.33.template.gen.yaml
- pkg/kube/inject/testdata/inputs/status_params.yaml.7.template.gen.yaml
- pkg/kube/inject/testdata/inputs/traffic-params.yaml.6.template.gen.yaml
fixes https://github.com/istio/istio/issues/54408
propagates helm configuration value outlierLogPath to waypoint template.
this PR is a cherry pick of this one that was merged into master last week (dec 12 2024): https://github.com/istio/istio/pull/54283
> [release-1.24] enable configuration of global.proxy.outlierLogPath for waypoints

- pilot/pkg/leaderelection/leaderelection.go
This var did nothing, making usage fall back to the legacy usage
> leaderelection: actually respect useLeaseLock

- pkg/kube/krt/collection.go
- pkg/kube/krt/conformance_test.go
- pkg/kube/krt/core.go
- pkg/kube/krt/fetch.go
- pkg/kube/krt/informer.go
- pkg/kube/krt/internal.go
- pkg/kube/krt/processor.go
- pkg/kube/krt/static.go
- pkg/kube/krt/static_test.go
- pkg/kube/krt/testing.go
- pkg/queue/instance.go
cherrypick of https://github.com/istio/istio/pull/53994/files
Part of this was already cherrypicked in
https://github.com/istio/istio/pull/54369. This finishes it.
This is based on discussion in the WG meeting on 12/18 - the concern was that this deadlock was easy to trigger in real world environments. We were a bit worried about the risk of the backport, but ultimately decided that the pros outweighed the cons. A feature flag was seriously considered but ultimately decided against, due to the complexity to implement such a flag -- we felt the risk of imlementing the flag incorrectly was higher than the risk of not having the flag at all.
> 1.24 cherrypick: krt: move event processing to queue

- istioctl/pkg/injector/injector-list.go
- releasenotes/notes/54095.yaml
Fix `istioctln experimental injector list` print redundant namespaces, the discussion: https://github.com/istio/istio/pull/53583#discussion_r1851509977
> Fix istioctl experimental injector list print redundant namespaces

- pkg/kube/client.go
- pkg/test/framework/components/istio/cleanup.go
- pkg/test/kube/util.go
Fixes: https://github.com/istio/istio/issues/54446
When test resources cleaned up in Openshift, it takes time for the "istio-ingressgateway" and "istio-egressgateway" services to be deleted.
As a result, when the resources are cleaned after one test and the next test starts, ittend to fail because the services are in deletion state and failed to be used by the next test.
Check for the services to be deleted completely before ending the test.
> Fix tests resources cleanup for Openshift

- pilot/pkg/xds/ads.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/delta_test.go
- pilot/pkg/xds/waypoint_test.go
- pilot/pkg/xds/workload.go
- pilot/pkg/xds/workload_test.go
- pilot/test/xds/fake.go
- pkg/kube/krt/collection.go
This makes it so during a few tests we call all the debug endpoints.
This found a few races which have been fixed in this PR
> debug: test and fix race conditions in debug endpoints

- pilot/pkg/xds/debug.go
- pilot/pkg/xds/eds_test.go
This has been a part of config_dump for many releases, we should
consolidate one this
> debug: remove type-specific endpoints

- pilot/pkg/serviceregistry/aggregate/controller.go
if there is only one registry (~all the time today), there is no need to do this dedupe + copy
> ambient: optimize for single registry case

- go.mod
- go.sum
- tests/integration/pilot/testdata/gateway-api-crd.yaml
Thi has no code changes. The intent of this is essentially to give us a conformance report for 1.2.1 -- the website requires you to be on the latest patch releae so we are missing from
https://gateway-api.sigs.k8s.io/implementations/v1.2/.
This is probably not good -- I am also working to change that upstream.
> 1.24: Use official gateway 1.2.1 release

- prow/benchtest.sh
We keep hitting this. We should probably find a way to make the tst
shorter, but for now bump the time
> Increase timeout on benchmark test

- CODEOWNERS
As Eric has stepped down, I nominate Keith to take this place. Keith is one of the most active maintainers and now a member of the TOC so a good fit for these top level decisions.
> Replace Eric with keithmattix for top level ownership

- pilot/pkg/xds/delta.go
- pkg/util/protomarshal/grpc.go
Currently, we use vtproto only to encode anypb messages. This extends this to the last-mile of gRPC messages as well (basically, DiscoveryResponse).
This has pretty substantial improvements:
```
benchmark            ns/op 
golang-protobuf      11116     
vtprotobuf           2858     
```
Note: all this code is copied; it may be merged into the library (https://github.com/planetscale/vtprotobuf/pull/138) but for now the expectation is to manually copy this.
> Use vtproto to encode gRPC messages

- pilot/pkg/model/context.go
- pilot/pkg/networking/core/cluster.go
- pilot/pkg/networking/core/cluster_test.go
- pilot/pkg/networking/grpcgen/grpcgen.go
- pilot/pkg/xds/ads.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/debug.go
- pilot/pkg/xds/debuggen.go
- pilot/pkg/xds/delta.go
- pilot/pkg/xds/delta_test.go
- pilot/pkg/xds/deltatest.go
- pilot/pkg/xds/ecds.go
- pilot/pkg/xds/ecds_test.go
- pilot/pkg/xds/eds.go
- pilot/pkg/xds/nds_test.go
- pilot/pkg/xds/rds.go
- pilot/pkg/xds/sds.go
- pilot/pkg/xds/sds_test.go
- pilot/pkg/xds/statusgen.go
- pilot/pkg/xds/workload.go
- pilot/pkg/xds/workload_test.go
- pilot/pkg/xds/xdsgen.go
- pkg/util/sets/set.go
- pkg/xds/server.go
- pkg/xds/server_test.go
- security/pkg/nodeagent/sds/sdsservice.go
The `watchedResource.ResourceNames` field contains the set of all resources watched by a proxy. Today, this is stored as a `[]string`.
This field is used exclusively as a set through Istio. It has no ordering semantics, and is regularly converting into a set (and from a set), in a variety of places, such as `slices.EqualUnordered` and various places where we try to insert/delete resources by name, do merge/union/difference operations, and more.
This PR officially moves the usage over to actually be a set.
Primary changes beyond the superficial compilation fixes:
* `deltaWatchedResources` - before, we build a new resource set and then diff it. Now, we modify-in-place the resource set, and mark if we ever changed it.
* Workload generator -- massive performance wins by modifying set in place …
> xds: move ResourceNames to a set

- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/testdata/benchmarks/serviceentry-workloadentry.yaml
Running this on a few PRs...
```
│   baseline    │               master                │
│    sec/op     │    sec/op     vs base               │
AddressFullGeneration/serviceentry-workloadentry-16            2.642m ± 9%   1.323m ± 17%  -49.92% (p=0.002 n=6)
AddressIncrementalGeneration/serviceentry-workloadentry-16   136.429µ ± 3%   1.452µ ±  7%  -98.94% (p=0.002 n=6)
geomean                                                        600.4µ        43.83µ        -92.70%
│    baseline    │               master                │
│      B/op      │     B/op      vs base               │
AddressFullGeneration/serviceentry-workloadentry-16            1.631Mi ± 0%   1.225Mi ± 0%  -24.91% (p=0.002 n=6)
AddressIncrementalGeneration/serviceentry-workloadentry-16   143.185Ki ± 0%   1.250Ki ± 0%  -99.13% …
```
> Benchmark WDS

- pilot/pkg/xds/discovery.go
ConfigsUpdated is very frequently. So removing fmt.Sprintf
> remove expensive sprintf in configs updated

- pilot/pkg/serviceregistry/kube/controller/controller_test.go
fixes https://github.com/istio/istio/issues/54543 - We do not have to check for eds or "eds cache". "service" and full push is sufficient
> fix test flake

- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/helpers.go
- pilot/pkg/serviceregistry/kube/controller/ambient/services.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pilot/pkg/xds/workload.go
This implements a long-standing TODO in the ambient code path, greatly improving performance.
In WDS, we (intentionally) do not have client-specific configuration. As such, we can pre-marshal all our resources, rather than marshalling them for each client. This dramatically reduces the number of times we need to marshal config.
For example, consider a large cluster with 25k pods and 500 ztunnel connections. Today, each workload change would be marshalled 500x. A full push (which can be improved - https://github.com/istio/istio/issues/54499) would require 12.5M marshals.
With this change, a workload change is marshalled 1x. Additional full pushes required 0 marshals!
There is a small cost to this -- the memory overhead of storing the pre-marshaled bytes. However, this is negligible. With …
> Ambient: Add pre-marshalling of xds

- pkg/test/framework/components/cluster/clusters.go
- tests/integration/telemetry/api/customize_metrics_test.go
- tests/integration/telemetry/api/registry_setup_test.go
- tests/integration/telemetry/api/setup_test.go
Follow up for https://github.com/istio/istio/pull/54392 and https://github.com/istio/istio/pull/54488
Focusing on the following suggestion: https://github.com/istio/istio/pull/54392#discussion_r1890491152
The "isKindCluster" function used to detect if the cluster during the test is of "Kind" type or any other cluster type - vanilla Kubernetes or Openshift.
Move the "isKindCluster" function under the
"(resource.Context).Clusters()" to be available as "(resource.Context).Clusters().IsKindCluster()"
> Refactor Telemetry tests "IsKindCluster" function

- cni/pkg/nodeagent/server.go
- cni/pkg/nodeagent/ztunnelserver.go
- cni/pkg/nodeagent/ztunnelserver_test.go
- releasenotes/notes/54565.yaml
I had actually fixed this in passing ages ago in internal builds as part of unrelated work, but forgot to backport when that work was dropped.
Should fix https://github.com/istio/istio/issues/54544 and (I bet) https://github.com/istio/istio/issues/53843
Moves ztunnel conns to an ordered slice so we can keep track of what the "previous" connection was and revert back to that, if we happen to get out-of-order `deleteConn` calls due to restart timing variances.
> Handle out-of-order ztunnel connection removals correctly.

- pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
- pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-port-mtls-strict-and-permissive-in.yaml
- pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-port-mtls-strict-and-permissive.yaml
- pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-permissive-namespace-strict-workload-ports-in.yaml
- pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-permissive-namespace-strict-workload-ports.yaml
- pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-unset-namespace-mixed-workload-ports-in.yaml
- pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-permissive-root-unset-namespace-mixed-workload-ports.yaml
- pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-port-mtls-strict-and-permissive-in.yaml
- pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-port-mtls-strict-and-permissive.yaml
- pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-unset-workload-port-mtls-strict-and-permissive-in.yaml
- pilot/pkg/serviceregistry/kube/controller/ambient/testdata/peer-authn-strict-root-unset-workload-port-mtls-strict-and-permissive.yaml
- releasenotes/notes/54146.yaml
- tests/integration/ambient/baseline_test.go
Fixes #54146. I suspect that our test runners were too fast which is why this flaked instead of failing 100% of the time.
The ambient Peerauthn implementation is based on the on the WDS protobuf documentation for authorization; this exists here in istio as well as the ztunnel repo. #53938 and the subsequent PR revealed that the istio version of the documentation was incorrect; Group.Rules (in the istio version) are AND'd during evaluation, not OR'd (like the documentation says). This PR fixes that and adds tests for even more combinations of port-level overrides
> Fix Ambient Peer Authn flake

- pilot/pkg/model/jwks_resolver.go
- pilot/pkg/model/jwks_resolver_test.go
- releasenotes/notes/54118.yaml
Resolves https://github.com/istio/istio/issues/52121
This updates the JWKS resolver cache accessing/refreshing logic respectively to resolve two TOC-TOU race conditions as mentioned in the issue.
**Updating lastUsedTime**
The prior implementation would potentially conflict with a public key refresh since `lastUsedTime` is incremented on each cache access and is stored in the same map. The value was read and stored without any mutex lock in between. The solution is to use `CompareAndSwap` to make a best-effort attempt to update the currently stored entry assuming no writes have occurred between load and store ops. If `CompareAndSwap` fails after a certain number of attempts, the code will assume that `lastUsedTime` will have been set to a close …
> Resolve JWKS Resolver TOCTOU Race Conditions

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_serviceentry_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/helpers.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
Fixes https://github.com/istio/istio/issues/54528
This removes the dedupe of workloads for WDS. This check is not correct (see https://github.com/istio/istio/issues/54528) and typically has no impact. Ztunnel has been updated to do the dedupe itself, where it can be done appropriately (https://github.com/istio/ztunnel/pull/1409)
```
│ /tmp/baseline │              /tmp/remove              │
│    sec/op     │   sec/op     vs base                  │
AddressFullGeneration/serviceentry-workloadentry-16          1223.3µ ± 60%   705.3µ ± 5%  -42.35% (p=0.000 n=10+6)
AddressIncrementalGeneration/serviceentry-workloadentry-16    1.583µ ± 34%   1.079µ ± 7%  -31.82% (p=0.000 n=10+6)
geomean                                                       44.00µ         27.59µ       -37.30%
│ /tmp/baseline │ …
```
> ambient: drop dedupe of workloads

- pilot/pkg/config/kube/gateway/conversion.go
Minor update regarding keys used while populating Gateway (gateway.networking.k8s.io/v1) conditions
* gatewayConditions map uses `condition` type as a key. This PR updates assignments to `gatewayConditions` map using `reason` as the key.
* Although both GatewayReasonProgrammed and GatewayConditionProgrammed yield the same string, type diff might cause confusion. It helps prevent potential errors that could arise from mixing reason and condition types.
> (fix): align gateway condition key usage

- tests/integration/ambient/baseline_test.go
This has been a pain for awhile, and the true source of some of the ambient test flakes (finding #54566 was just a coincidence apparently). Our test code makes deep copies of opt, but assigns it to a shared variable, meaning that the evaluation criteria for echo tests was changing in between requests. This is why in failures like https://prow.istio.io/view/gs/istio-prow/logs/integ-assertion_istio_postsubmit/1877054177264275456, we see different reasons why the test failed even though the response status code is consistent (always a 200). What made me notice this is that the above test was failing because it expected an error even though the code as written always expects a 200. This can only happen if state is being changed from multiple …
> Fix shared state access causing test flakes

- releasenotes/notes/fix-iptables-state-custom-table.yaml
- tools/istio-iptables/pkg/builder/iptables_builder_impl.go
- tools/istio-iptables/pkg/builder/iptables_builder_test.go
This addresses an issue where the user has a non-empty custom table beyond the built-in tables (RAW, NAT, FILTER, MANGLE).
Currently, the code panics when attempting to populate the state if a non-empty non-built-in table exists (e.g: SECURITY table from SELINUX). It was reported by an user on Slack and the PR was confirmed to fix the issue.
The new behavior will disregard chains, and rules from non-built-in tables.
> Prevent iptables GetStateFromSave from processing lines related to non-built-in tables

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/gateway/conflictinggateway.go
- pkg/config/analysis/analyzers/testdata/conflicting-gateways-multiple-ports.yaml
- pkg/config/analysis/analyzers/testdata/gateway-different-port.yaml
- releasenotes/notes/54643.yaml
Fixes #54643.
This PR fixes the conflict check for Gateways, when different ports are used for the same hosts.
> Check equality of ports in Gateway conflict check

- tools/istio-iptables/pkg/dependencies/implementation.go
Istio automatically detects whether the host is using the legacy version or the nft version of iptables, and does not use these constants. This PR removes them.
> Remove unused iptable restore constants

- pilot/pkg/features/ambient.go
- pilot/pkg/networking/core/listener_waypoint.go
- pilot/pkg/networking/core/match/match.go
- pilot/pkg/xds/filters/filters.go
- tests/integration/ambient/baseline_test.go
- tests/integration/ambient/main_test.go
High level implementation as a fallback for if `:authority` matches a hostname. Since we always store the :authority in filter state, we can build a matcher tree off of it to use if the IP based matching doesn't work. Added a test using echo server as the client for now since we don't have the ztunnel implementation yet.
> Allow waypoints servers to support hostnames in routing

- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pkg/kube/krt/collection.go
- pkg/kube/krt/internal.go
- pkg/kube/krt/join.go
```
cpu: AMD Ryzen 7 PRO 7840U w/ Radeon 780M Graphics
│  baseline2  │                join2                │
│   sec/op    │   sec/op     vs base                │
AddressFullGeneration/serviceentry-workloadentry-16          1.377m ± 4%   1.115m ± 3%  -19.05% (p=0.000 n=10)
AddressIncrementalGeneration/serviceentry-workloadentry-16   1.410µ ± 7%   1.411µ ± 3%        ~ (p=0.869 n=10)
geomean                                                      44.06µ        39.66µ        -9.99%
│   baseline2   │                 join2                  │
│     B/op      │     B/op      vs base                  │
AddressFullGeneration/serviceentry-workloadentry-16          1254.2Ki ± 0%   995.8Ki ± 0%  -20.61% (p=0.000 n=10)
AddressIncrementalGeneration/serviceentry-workloadentry-16    1.250Ki ± 0%   1.250Ki ± …
```
> krt: optimize lookups in Join

- pilot/pkg/model/push_context.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/xds/bench_test.go
- pilot/pkg/xds/delta_test.go
- pilot/pkg/xds/workload.go
Solves part 1 of https://github.com/istio/istio/issues/54499.
The idea here is that we use ConfigsUpdate which is lossy - at some points we wipe the configs, and the only choice is to push everything. At large scale, these full pushes cause dramatic spikes in Istio CPU utilization. For instance, imagine I have a massive scale of 100k pods and 1k ztunnels connected. At steady state, even with a crazy 10 pods/s changing, I need to push 10 workloads * 1k ztunnels = 10k workloads/s. If a full push is triggered, it will instantly need to push 100M workloads - a 10000x increase.
This fixes things by putting Addresses in a separate object. This _probably_ should not actually be specialized to Addresses and instead should also allow WADS resources maybe, to apply the same optimization there. …
> ambient: do not full push for WDS when we don't need to

- common/scripts/kind_provisioner.sh
- pkg/test/framework/components/echo/common/deployment/echos.go
- pkg/test/framework/components/echo/common/deployment/external.go
- pkg/test/framework/components/echo/common/deployment/namespace.go
- pkg/test/framework/components/echo/deployment/builder.go
- pkg/test/framework/components/istio/kube.go
- pkg/test/framework/resource/flags.go
- pkg/test/framework/resource/settings.go
- pkg/test/framework/suite.go
- pkg/test/framework/test.go
- prow/integ-suite-kind.sh
- prow/lib.sh
- tests/integration/pilot/common/routing.go
- tests/integration/pilot/gateway_test.go
- tests/integration/security/policy_attachment_only/main_test.go
- tests/integration/security/reachability_test.go
- tests/integration/tests.mk
This PR tries to address the comment as mentioned in https://github.com/istio/istio/pull/51914#discussion_r1668094067
Fixes https://github.com/istio/istio/issues/53704
Currently this includes kind_provisioner.sh too just for testing purpose and review. Once finalized the respective changes will move to istio/common-files repo
Right now we have IP_FAMILIES which can be
"V4"
"V6"
"dual"
This PR suggests we simply pass a list of families to the test as a test arg and drop "dual". Whatever ipfamily order the tests are passed is the order that will be used in the test, and if more than one family (regardless of order) is provided we always use IPFamilyPolicyRequireDualStack for the policy.
This simplifies things, as the only test knob is IP_FAMILIES …
> [Dual-stack] Introduce IP_FAMILIES for integration tests

- releasenotes/notes/retroactive-note-for-53949.yaml
As mentioned in https://github.com/istio/istio/issues/53949 this behavior changed in 1.23 but we didn't catch or relnote it, so might as well do it retroactively in the affected older branches for posterity's sake.
>  [release-1.23] Backport release note for missed behavior change #54699 

- samples/security/spire/istio-spire-config.yaml
This is setting `global` to null which is not valid
> spire: fixup sample

- istioctl/pkg/cli/option.go
- istioctl/pkg/cli/option_test.go
- releasenotes/notes/54667.yaml
Do not impersonate empty group when group not set in flags
When `--as` flag is passed to `istioctl`, it overwrites `UserName`, `UID`, and `Groups` in `rest.ImpersonationConfig` from default (empty) values using the corresponding values from `RootFlags`. If a parameter is not set in flags, then custom default values are used. The default value for `impersonateGroup` is not `nil`, but a slice with a single empty string. This breaks impersonalisation when only username (i.e. `--as` is used).
**Example**
When permissions are missing, `istioctl` fails _as expected_:
```
❯ k auth can-i create pods/portforward
no - User does not have access to the resource in Azure. Update role assignment to allow access.
❯ istioctl pc log --level 'http:warn' mypod
2025-01-13T17:11:18.447037Z	error	port forward …
```
> Do not impersonate empty group

- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/xds/eds_test.go
- pilot/pkg/xds/endpoints/endpoint_builder.go
- pkg/dns/server/name_table.go
- pkg/dns/server/name_table_test.go
- releasenotes/notes/endpoint-termination.yaml
The purpose of PILOT_SEND_UNHEALTHY_ENDPOINTS is to let envoy know about
the count of health and unhealth endpoints as a factor into its failover
decisions. For instance, if we have 5/10 pods health, it would failover.
This has problematic behavior during scaling up/down. For instance, if I
just have a single pod and then make a change, I will temporarily have 2
pods (the new one, and the old one terminating). Envoy will now see this
as 50% health and failover. This is bad -- its not actually unhealthy at
all!
Additionally, when pods are scaling down we end up keeping them as
unhealthy. Consider I have 1/2 pods healthy, and shut down the unhealthy
one but it takes a few minutes to fully terminate. During that time,
envoy will consider us 50% healthy. However, because we requested 1 pod …
> PILOT_SEND_UNHEALTHY_ENDPOINTS: exclude terminating endpoints

- prow/integ-suite-kind.sh
Just a small script change to make spinning up local clusters a bit easier
> Enable modifying the prow cluster name

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/helpers.go
- pilot/pkg/serviceregistry/kube/controller/ambient/networks.go
- pilot/pkg/serviceregistry/kube/controller/ambient/services.go
- pilot/pkg/serviceregistry/kube/controller/ambient/services_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/network_test.go
- tests/binary/binaries_test.go
Alternative to https://github.com/istio/istio/pull/54376/. In that PR,
I moved all the network logic to krt. This just makes ambient network
logic on krt, as its own copy.
This makes ambient's full state managed by krt! We can remove the hacks
around syncing, etc.
Note this only implements the system-namespace and Gateway driven
network logic, not the older MeshNetworks logic.
> ambient: move networks logic to native krt

- pilot/pkg/xds/sds.go
- pilot/pkg/xds/sds_test.go
This allows a config like this:
```yaml
apiVersion: networking.istio.io/v1
metadata:
name: originate-tls
spec:
host: example.com
trafficPolicy:
tls:
mode: SIMPLE
credentialName: root-cert
workloadSelector:
matchLabels:
app: shell
---
apiVersion: v1
data:
ca.crt: xxx
kind: Secret
metadata:
name: root-cert
```
to work without `shell` having secret LIST RBAC privilege
Fixes https://github.com/istio/istio/issues/54710
Related to https://github.com/istio/istio/issues/52728 (but doesn't
solve it, that one was doing mTLS which is legitimately secret).
> Allow SIMPLE TLS origination without secret read acces

- pilot/pkg/model/telemetry_logging.go
- pilot/pkg/networking/core/accesslog.go
- releasenotes/notes/54795.yaml
This change is specific to Istio 1.23 (other releases are not affected since support for this upgrade scenario is absent in 1.24).
Currently, a 1.23 controller encounters issues when sending configuration for access logs to proxies running versions earlier than 1.23 for two reasons:
- It uses the UPSTREAM_CLUSTER_RAW field in the JSON access log format, which older proxies do not recognize.
- The access log format for listeners is cached, which may result in a 1.23 configuration being sent to <1.23 sidecars (and potentially vice versa).
This issue could prevent new proxies with 1.22 from going in a ready state or prevent existing ones to receive LDS updates.
```
envoy config\tgRPC config for type.googleapis.com/envoy.config.listener.v3.Listener …
```
> Fix accesslog format incompatibility between 1.23 istiod and <1.23 proxies

- pilot/pkg/networking/grpcgen/lds.go
- pilot/pkg/security/authz/builder/builder.go
- pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-in.yaml
- pilot/pkg/security/authz/builder/testdata/http/allow-full-rule-out.yaml
- pilot/pkg/security/authz/builder/testdata/http/extended-allow-full-rule-out.yaml
- pilot/pkg/security/authz/model/generator.go
- pilot/pkg/security/authz/model/generator_test.go
- pilot/pkg/security/authz/model/model.go
- pilot/pkg/security/authz/model/model_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/authorization.go
- pilot/pkg/serviceregistry/kube/controller/ambient/testdata/allow-full-in.yaml
- pilot/pkg/serviceregistry/kube/controller/ambient/testdata/allow-full.yaml
- pkg/config/security/security.go
- pkg/config/security/security_test.go
This allows applying a policy like
```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
name: allow-waypoint
spec:
selector:
matchLabels:
app: echo
action: ALLOW
rules:
- from:
- source:
serviceAccounts: ["waypoint"]
```
To get the semantics of "allow the waypoint in the same namespace". 
It is common in k8s to allow configurations to be written without a namespace specified and have the namespace of references implied by the namespace it is eventually written to. This allows taking the same policy and applying it to many places without the need for modification/templating. As far as I know, this is allowed with virtually every k8s core type and Istio type today.
No changes are needed to the dataplane to support this, as it is entirely control plane logic changing …
> AuthorizationPolicy serviceAccount: allow same namespace

- pkg/bootstrap/platform/gcp.go
- pkg/bootstrap/platform/gcp_test.go
To avoid MDS query, this PR uses the /etc/resolv.conf configuration in GKE pod.
Currently GKE pod has resolv.conf has the entry like:
```
search ... [zone].c.[GCP-project].internal ...
```
Therefore we can extract the zone from the search clause in `resolv.conf` without using the GKE metadata server.
We had some issues on GKE metadata server, so I believe that it can help to get better stability.
This is basically a short-term approach. If https://github.com/istio/istio/issues/53859 is cleared, then we should use the zone from topology annotation.
Change-Id: I24f8da81a940703bab43c16eea6d079986fa2d52
> Use resolv.conf for getting the zone

- pilot/pkg/features/experimental.go
- pilot/pkg/model/endpointshards.go
- pilot/pkg/model/service.go
- pilot/pkg/networking/core/cluster_builder.go
- pilot/pkg/networking/core/cluster_test.go
- pilot/pkg/networking/core/cluster_traffic_policy.go
- pilot/pkg/networking/core/cluster_waypoint.go
- pilot/pkg/networking/core/loadbalancer/loadbalancer.go
- pilot/pkg/networking/core/loadbalancer/loadbalancer_test.go
- pilot/pkg/serviceregistry/kube/controller/endpoint_builder.go
- pilot/pkg/serviceregistry/kube/controller/endpointslice.go
- pilot/pkg/serviceregistry/kube/controller/pod.go
- pilot/pkg/serviceregistry/kube/conversion.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
- pilot/pkg/xds/eds_test.go
- pilot/pkg/xds/endpoints/endpoint_builder.go
- releasenotes/notes/traffic-distribution.yaml
- tests/integration/pilot/locality_test.go
Fixes https://github.com/istio/istio/issues/53055
This enables TrafficDistribution to work with Envoy. Today, this is implemented only for ztunnel. That leads to some awkward behavior where I can control the distribution with native k8s APIs (that are much simpler than ours) with ztunnel, but if I add a waypoint it is ignored. With this change, you can just set preferClose on the service and everything will respect it.
The implementation is _mostly_ straightforward. We follow this ordering of precedence: DR locality LB > prefer close > mesh config locality LB. if they have preferclose, we setup a default `failover` locality LB policy.
The more complicated aspect is around failover/outlier detection. In locality LB, we only allow failover if locality LB is configured. The intent for this …
> Support TrafficDistribution for Envoy

- pilot/pkg/model/service.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/services.go
- pilot/pkg/xds/endpoints/endpoint_builder.go
- pilot/pkg/xds/waypoint_test.go
Two different bugs leading to the same breakage
1. We just incorrectly assigned the IngressUseWaypoint option in the SE
codepath
2. We ignore auto-allocated IPs and prematurely filter out services from
waypoint support
> ambient: fix ingress-use-waypoint with ServiceEntry

- pilot/pkg/networking/core/cluster_tls.go
- pilot/pkg/networking/core/cluster_waypoint.go
- pilot/pkg/networking/util/internal_upstream.go
This is pure refactor, no behavior changes.
Currently we have 3 usage of internal upstream, and they are all named
similarly but used for different purposes.
Trying to move these to a centralized place + explain when they are
used.
We still probably should comment WHY but I honestly don't really know
myself...
> ambient: refactor internal transports

- pilot/pkg/networking/core/accesslog.go
Really niche bug. We log for only UF, but we don't clear the cache so we
don't get formatting changes if someone changes mesh config
> ambient: fix caching of HBONE access log filter

- cni/pkg/iptables/iptables.go
- releasenotes/notes/54644.yaml
- tools/istio-iptables/pkg/capture/helper.go
- tools/istio-iptables/pkg/capture/run.go
- tools/istio-iptables/pkg/capture/run_test.go
- tools/istio-iptables/pkg/dependencies/implementation.go
- tools/istio-iptables/pkg/dependencies/implementation_linux.go
- tools/istio-iptables/pkg/dependencies/implementation_unspecified.go
- tools/istio-iptables/pkg/dependencies/interface.go
- tools/istio-iptables/pkg/dependencies/stub.go
This PR refactor the iptables code to have a single Run() interface to execute iptables commands.
Previously, there were three Run functions:
- Run(): Did not return stdout, only an error. It logged the executed command, output, and error at the info level.
- RunWithOutput(): Returned both stdout and an error. It logged the executed command and error at the info level, with output logged at the debug level.
- RunQuietlyAndIgnore(): Returned nothing. It logged the executed command and output at the info level, with errors logged at the debug level.
The new Run() always returns both the command output and any error that occurs, it is up to the caller to decide which one to ignore. It now includes a flag to silence all errors (info->debug level). …
> Refactor RunX cmds for istio-iptables into a single API

- common/config/.golangci.yml
- pilot/pkg/networking/core/cluster_builder.go
- pilot/pkg/networking/core/cluster_builder_test.go
- tools/golangci-override.yaml
Remove lint rules from copied file which will be overwritten during common-files sync, add to overrides.
Refs https://github.com/istio/istio/pull/54803, https://github.com/istio/common-files/pull/1141
Couldn't get exclude rules as documented at https://golangci-lint.run/usage/false-positives/#exclude-or-skip working properly, so opting for granular nolint comments for now.
> move Envoy go-control-plane DNS lint rules to local overrides

- istioctl/pkg/waypoint/waypoint.go
- releasenotes/notes/54843.yaml
Support delete specific revision waypoints.
`istioctl waypoint apply` and `istioctl waypoint generate` have a flag to apply or generate waypoints of a specified revision. `istioctl waypoint delete` should also have a flag to delete specified revision waypoints.
> istioctl: support delete specific revision waypoints

- cni/pkg/nodeagent/informers_test.go
This is probably something that got missed in a past refactoring, but we don't need to double-`goroutine` in test code, and in fact it defeats the "wait for informer sync" stuff.
This is likely the cause of https://prow.istio.io/view/gs/istio-prow/logs/unit-tests-arm64_istio_postsubmit/1882560216436838400 and similar.
> Drop clearly wrong goroutine spawn in test code

- pilot/pkg/networking/core/accesslog.go
- pilot/pkg/networking/core/listener_waypoint.go
Right now, if we have a failure in the HBONE termination side, we don't
get any logs. This could be things like a protocol error getting a 400,
or with https://github.com/istio/istio/pull/54833/ a 403.
Since we now have 4 types of logs, our copy+pasting of each type got
pretty gross, so abstracted things a bit with a new
cachedMeshConfigAccessLog type
> Add HBONE termination access logs

- istioctl/pkg/analyze/analyze.go
- istioctl/pkg/util/formatting/formatter.go
- istioctl/pkg/util/formatting/formatter_test.go
- pkg/config/analysis/diag/helper.go
- pkg/config/analysis/diag/message.go
- pkg/config/analysis/diag/message_test.go
- pkg/config/analysis/diag/messages.go
In multi-cluster scenario, when running `istioctl analyze`, if resources in different clusters have the same name, the analyze result messages will be filtered.
For example, if two services both named as `reviews-service` and have same issue, only one message will be printed since their messages are completely the same.
```go
func (ms *Messages) SortedDedupedCopy() Messages {
newMs := append((*ms)[:0:0], *ms...)
newMs.Sort()
// Take advantage of the fact that the list is already sorted to dedupe
// messages (any duplicates should be adjacent).
var deduped Messages
for _, m := range newMs {
// Two messages are duplicates if they have the same string representation.
if len(deduped) != 0 && deduped[len(deduped)-1].String() == m.String() {
continue …
```
> fix missing analysis messages in multi-cluster scenario

- prow/integ-suite-kind.sh
- prow/lib.sh
Currently, it is very painful to run integ tests against kind from within a dev container, because our kind setup scripts rely on port-forwarding to the host machine, but the dev container does not have access to host ports.  This change adds an env var `DEVCONTAINER` which, if set, causes the script to run using docker network connections and hostnames, rather than ports on localhost.  This change depends on https://github.com/istio/common-files/pull/1138.
> Allow kind integ tests inside devcontainer

- pkg/kube/inject/webhook.go
While reviewing code to debug this https://github.com/istio/istio/issues/54868 - realized we missed to increment error metrics in some cases. I still do not think that is causing the issue described in the issue but good to correct this.
> increment sidecar injector metrics for more error cases

- istioctl/pkg/waypoint/waypoint.go
The current code logic requires that waypoints must be specified, so this part of the example cannot be executed:
```
if !(deleteAll || revision != "") && len(args) == 0 {
return fmt.Errorf("must specify a waypoint name or delete all using --all or delete specific revision using --revision")
```
> remove wrong example for waypoint delete

- pilot/pkg/features/ambient.go
- pilot/pkg/networking/core/listener_waypoint.go
- pilot/pkg/networking/plugin/authz/authorization.go
- pilot/pkg/security/authz/builder/builder.go
Waypoints are logically two parts merged into one component for operational reasons:
* An HBONE termination and encapsulation phase, for inbound/outbound traffic, equivalent to having Ztunnel in front of the waypoint
* The inner waypoint logic
However, we behave different from Ztunnel in one key way -- we don't apply any policies on the HBONE termination layer. This adds a feature flag (off by default while we evaluate it) to apply these policies like Ztunnel would.
See https://github.com/istio/istio/issues/54696 for some previous discussion
Fixes https://github.com/istio/istio/issues/54718
> Initial implementation of L4 policies for waypoints

- cni/pkg/iptables/common_test.go
- cni/pkg/iptables/iptables.go
- cni/pkg/iptables/testdata/dns_pod_disabled_and_on_globally.golden
- cni/pkg/iptables/testdata/dns_pod_disabled_and_on_globally_ipv6.golden
- cni/pkg/iptables/testdata/dns_pod_enabled_and_off_globally.golden
- cni/pkg/iptables/testdata/dns_pod_enabled_and_off_globally_ipv6.golden
- cni/pkg/nodeagent/net.go
- cni/pkg/nodeagent/net_test.go
- cni/pkg/util/podutil.go
- releasenotes/notes/54935.yaml
Impl side of https://github.com/istio/api/pull/3361 (which I had forgotten about - my bad).
Since Ambient DNS capture is newly opt-in by default in 1.25, there's a case to be made for backporting this (and https://github.com/istio/api/pull/3361).
I've raised an API backport PR here: https://github.com/istio/api/pull/3427, if that merges I will tag this for 1.25 backport as well.
> Implement ambient pod-level DNS inclusion/exclusion

- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/networking/core/cluster.go
- pilot/pkg/networking/core/waypoint.go
- pilot/pkg/xds/proxy_dependencies.go
Two improvements:
* Add an explicit annotation to services to include them. This allows
reference from unknown usage like EnvoyFilter
* Bug fix: PILOT_FILTER_GATEWAY_CLUSTER_CONFIG needs to respect the
`namespace/hostname` format of extension providers
> Improvements to PILOT_FILTER_GATEWAY_CLUSTER_CONFIG

- pilot/pkg/networking/core/envoyfilter/rc_patch.go
- pilot/pkg/networking/core/envoyfilter/rc_patch_test.go
- releasenotes/notes/54892.yaml
allow envoyfilter to match a virtualhost on domain name as well
https://github.com/istio/api/pull/3376
it is backward compatible and handles all cases:
1. name match
2. name and domain match
3. domain match
> match vhost on domain in envoyfilter

- pkg/wasm/convert.go
wasm convert error message is now not logged correct incase of conversion errors. Broken  in https://github.com/istio/istio/pull/53363. The createDefaultxxx now overwrites the original error that gets copied to convertErrs
> fix missing wasm convert error logs

- security/pkg/k8s/chiron/utils.go
We noticed memory leak over time after integrating with K8s CSR, heap profiling points this to chiron not `Stop`-ing on the watcher after the cert is signed or the wait times out.
Before:
After:
> chiron: fix goroutine/memory leak of CSR watcher

- samples/extauthz/ext-authz.yaml
If we are not supposed to inject the ext authz server, this can lead to unexpected behavior when you apply authz rules in root namespace.
> samples: do not inject ext-authz demo

- architecture/security/istio-agent.md
`OUTPUT_CERT` should be `OUTPUT_CERTS`
Fix for a small typo in the Istio Agent configuration documentation where the configuration variable should be `OUTPUT_CERTS`. 
> Documentation fix - `OUTPUT_CERT` should be `OUTPUT_CERTS`

- pilot/pkg/model/envoyfilter.go
- pilot/pkg/model/envoyfilter_test.go
- pilot/pkg/model/push_context.go
- pilot/pkg/networking/core/cluster.go
- pilot/pkg/networking/core/envoyfilter/cluster_patch.go
- pilot/pkg/networking/core/envoyfilter/extension_configuration_patch.go
- pilot/pkg/networking/core/envoyfilter/listener_patch.go
- pilot/pkg/networking/core/envoyfilter/rc_patch.go
- pilot/pkg/networking/core/httproute.go
- pilot/pkg/networking/core/listener_builder.go
We use EnvoyFilterWrapper for the per-config info, and for the merged
info. This is problematic since we just need to be careful not to
depend on fields we shouldn't use (which we have failed to do!).
This makes it clear which info is actually available.
> EnvoyFilter: do not re-use struct where not appropriate

- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
See https://istio.slack.com/archives/C06M609UE11/p1738680394797249
This PR makes us support any controller kind (well, any that is already supported in the shared-with-sidecars heuristics).
As part of this, it removes any setting of "workload type". This field is inaccurate and not useful; we do not use it anywhere in ztunnel except to plug into baggage. I propose we hardcode this for all resource types. Otherwise, we will need to continually update it with all sorts of types we may want to include which seems of limited value
> ambient: support direct usage of ReplicaSet

- pilot/pkg/networking/core/loadbalancer/loadbalancer.go
- pilot/pkg/networking/core/loadbalancer/loadbalancer_test.go
- pilot/pkg/serviceregistry/kube/conversion.go
- pilot/pkg/serviceregistry/serviceentry/conversion.go
- tests/integration/pilot/locality_test.go
Before, we only consider region/zone. Now we also consider network,
mirroring the ztunnel path/desired state
> trafficDistribution: align Envoy behavior with ambient

- pilot/pkg/networking/core/cluster_waypoint.go
Now:
```
$ istioctl pc c gtw/waypoint -ojson | jq '.[] | select(.circuitBreakers == null).name' -r
agent
prometheus_stats
sds-grpc
```
Fixes https://github.com/istio/istio/issues/55076
> ambient: do not put circuit breakers on internal clusters

- releasenotes/notes/serverca-expand-certs.yaml
- security/pkg/server/ca/server.go
- security/pkg/server/ca/server_test.go
( Reopen https://github.com/istio/istio/pull/54422 after working out the CLA )
Fixes https://github.com/istio/ztunnel/issues/1061
In multiple places such as the cert chain from CA bundle, or returned singed certs, there could be a single `string` representing a PEM with multiple blocks/certs.
Since `IstioCertificateResponse`'s signature is `[]string`, we should semantically expand those multi-cert PEMs.
See detailed analysis on how this is causing issues with `ztunnel` in particular https://github.com/istio/ztunnel/issues/1061#issuecomment-2542545936
> serverca: expand signed cert and cert chain PEMs with multiple cert blocks inside

- pilot/pkg/bootstrap/configcontroller.go
- pilot/pkg/bootstrap/configcontroller_test.go
- pilot/pkg/credentials/kube/secrets.go
> Support simple TLS for MCP

- cni/pkg/nodeagent/ztunnelserver.go
- cni/pkg/nodeagent/ztunnelserver_test.go
ref: #54645
In #54645, we are pretty clearly getting "the wrong" connection - we try to send a delete on a connection when we should only have one ztunnel connected, and the connection is trashed - the ztunnel never gets it (but continues on with no error) - and this happens right after the previous ztunnel disconnects.
In https://github.com/istio/istio/pull/54565/files#diff-9873062ab6cdec1c9e1829c5cad625c4ef9d878a05b8b96ee3449623ea50f442L64 because we needed to order connections temporally, I dropped the `map[pointer]` approach for a slice, but this creates a possible (unlikely but possible, I think) pointer mixup in some cases which may be what is triggering https://github.com/istio/istio/issues/54645
This drops pointers for the collection …
> Fix *possible* pointer mismatch (re-introduced) by #54565

- pilot/pkg/model/push_context.go
- pilot/pkg/networking/core/cluster.go
- pilot/pkg/networking/core/cluster_builder.go
- pilot/pkg/networking/core/httproute.go
- tests/integration/ambient/baseline_test.go
Fixes https://github.com/istio/istio/issues/54913
This is a control plane hack for a limitation in the filter. The MX filter is currently a HCM-level filter, which can access cluster metadata but not **host metadata**. This means we cannot just check `if the endpoint is hbone, do not send MX`.
There are two routes here:
(1) Move MX filter to an upstream filter. Probably more correct overall, but a big effort
(2) Infer that all instances are hbone, and stop sending MX in this case. This leaves some edge cases of a mixed service, but these are niche
Note that (2) is already used for enabling mTLS for headless services, so the same concept has proven to be ok-enough.
This PR is a WIP since it requires some envoy changes as well. We currently let us skip MX if the filter has …
> hbone: disable metadata exchange to the upstream HBONEs

- cni/pkg/nodeagent/ztunnelserver.go
- cni/pkg/nodeagent/ztunnelserver_mocks.go
- cni/pkg/nodeagent/ztunnelserver_test.go
Followup to https://github.com/istio/istio/pull/55085
Should fix: https://github.com/istio/istio/issues/54645 and the flakes.
Context - failures like: https://prow.istio.io/view/gs/istio-prow/logs/integ-ambient-dual_istio_postsubmit/1890443585262718976
(on one node, the conn failure happened during an update, and the others it happened after/before)
tl;dr because in the case of the connection failing with a broken pipe *during* an update handling, we were returning _without_ pushing a response back thru the response channel, this was causing `PodDeleted` to deadlock and never send the second delete, causing the ztunnel that should have gotten the delete message to never get it (thus failing the test).
Should _not_ have taken me this long to see …
> Ambient - Send on response channel to prevent deadlock if ztunnel disconnects during event process

- pilot/pkg/model/telemetry_logging.go
- releasenotes/notes/55116.yaml
- releasenotes/notes/fix-acccesslogencoding-json-1-23.yaml
Followup of #54795 ,
Fixes #55116
This cover a missed edge case where, in case meshConfig.accessLogEncoding is JSON but meshConfig.accessLogFormat is empty, the new format could be pushed to older proxies that do not support it.
As for the previous PR, this one is targeting release-1.23 exclusively. 1.24 and 1.25 are left unchanged since the conditional checks for retro-compatibility have been removed there.
> [release-1.23] Fix compatibility with <1.23 proxies when meshConfig.accessLogEncoding is JSON

- pilot/pkg/model/envoyfilter.go
- pilot/pkg/model/push_context.go
- pilot/pkg/model/push_context_test.go
- pilot/pkg/networking/core/cluster.go
This solves the issues I was aiming for in https://github.com/istio/istio/pull/54895 but in a better way.
Instead of saying "This service is needed", the envoyfilter itself declares what it needs.
> EnvoyFilter: allow referencing services as annotation

- pilot/pkg/networking/core/httproute.go
- pilot/pkg/networking/core/route/route.go
- pilot/pkg/networking/core/route/route_test.go
- releasenotes/notes/grpc-inbound-retry.yaml
See https://github.com/envoyproxy/envoy/pull/35074#issuecomment-2656794485. Ideally we would do this for streaming services only. But for us it is difficult to identify. So it is safe to remove from gRPC. We can provide an option in proxyMetadata to add if needed for regular gRPC services @keithmattix WDYT?
> disable inbound retry policy for gRPC streaming

- pilot/pkg/serviceregistry/kube/controller/pod.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- releasenotes/notes/eviction-bug.yaml
When selecting pods via a ServiceEntry, there are times when the pod may not have an IP address:
1. When it is first created
2. When it is Evicted/Failed.
The code today handles (1), however there exists a case when the IP is removed from the Pod in the same event that marks it with a terminal (Failed) status. Due to the cross-controller interaction (between the kube registry and serviceentry registry), the WorkloadInstance needs to have a valid IP, as the podCache and endpointShards are both keyed by address. This PR adds logic to fetch the oldIP from the ipByPods cache, and uses that when building the WorkloadInstance.
Fixes https://github.com/istio/istio/issues/54997
> kube/controller: Prevent leaking stale endpoints

- pkg/test/echo/docker/Dockerfile.app_sidecar_centos_8
- tools/docker-copy.sh
Setting DOCKER_ARCHITECUTRES=linux/amd64,linux/arm64 would
break the build.
> Fix multi-arch builds

- go.mod
- go.sum
- pkg/config/xds/filter_types.gen.go
Pin `envoyproxy/go-control-plane`, `envoyproxy/go-control-plane/contrib` and `envoyproxy/go-control-plane/envoy` to the last mirrored change from Envoy repo before Envoy v1.33 release branch cut.
> [release-1.25] pin envoyproxy/go-control-plane to last change before Envoy v1.33 cut

- bin/update_deps.sh
- bin/update_ztunnel.sh
- docker/Dockerfile.distroless
- istio.deps
- prow/release-commit.sh
...and run `./bin/update_deps.sh` and `./bin/update_ztunnel.sh`. Equivalent to #53718 for 1.25
**FIXME:** these scripts currently do not run completely on macOS due to differences in syntax between GNU `sed` and BSD `sed`. Should these scripts be updated, or should they instead be run through a containerized workflow?
```
+ sed -i.bak -e '/PROXY_REPO_SHA/,/lastStableSHA/ { s/"lastStableSHA":.*/"lastStableSHA": "1a1039c27701ecefdc2ce1e8e4e2fe9c1feedc4a"/  }; /ZTUNNEL_REPO_SHA/,/lastStableSHA/ { s/"lastStableSHA":.*/"lastStableSHA": "fb2a7be8e49c82a8a0c722c19206a1199531984e"/  }' istio.deps
sed: 1: "/PROXY_REPO_SHA/,/lastS ...": bad flag in substitute command: '}'
```
```
sed: 1: "/ZTUNNEL_REPO_SHA/,/las ...": bad flag in substitute command: '}'
```
Refs …
> update bin/update_deps.sh and bin/update_ztunnel.sh to release-1.25

- pilot/pkg/features/telemetry.go
- pilot/pkg/networking/core/cluster_builder_test.go
- pilot/pkg/networking/core/cluster_test.go
- pilot/pkg/networking/util/util.go
- pkg/bootstrap/config.go
- pkg/bootstrap/instance_test.go
- pkg/bootstrap/option/instances.go
- tools/packaging/common/envoy_bootstrap.json
The flag has reached the end of its deprecation period now that the last compatibility profile with it set to false (1.22) is being removed in 1.26.
If there are no objections the flag and code paths can be removed
> Remove ENABLE_DELIMITED_STATS_TAG_REGEX flag and code paths

- security/pkg/pki/ra/common.go
When operating in RA mode, Istiod fails validation of CSRs from `ztunnel`. This is due to a strict check on the CSR [having to have an empty `O=` in Subject](https://github.com/istio/istio/blob/aeb416ac10571de0570294792a84c2d023895064/security/pkg/pki/util/generate_csr.go#L89-L91).
This check is introduced in https://github.com/istio/istio/pull/51966 and seems to be very specific on asserting CSRs conform to the way Sidecar issues them.
This fix solves the issue with `ztunnel` but would like to tag @jaellio on the intention of the original check and if this fix is the most appropriate way to fix.
> ra: fix ztunnel CSR validation

- cni/pkg/iptables/iptables_e2e_test.go
- common/scripts/run.sh
- tools/istio-iptables/pkg/capture/run_test.go
The issue was caused by a combination of problems: a lack of permissions for userns and netns, along with the inability to change permissions on /run/.
I added SYS_ADMIN capability and an override to the path of the xtables lockfile, eliminating the need to unshare the mount namespace or worry about permissions in /run/.
> Fix execution of e2e iptables TCs in build-tools container

- pilot/pkg/xds/delta.go
- pilot/pkg/xds/workload.go
This is a further optimization on https://github.com/istio/istio/pull/54464, to avoid storing the resource name entirely in some scenarios where its not needed.
I've somehow lost my test results around this but at large scale this accounts for about 35% of Istiod memory usage, ~1GB in the test I had setup
> Do not record resource names for WDS

- pilot/pkg/xds/monitoring.go
Since debounce time is bound by [debounceMax](https://github.com/istio/istio/blob/fbe084f46ed796559f0d0afdbb5a916988b07454/pilot/pkg/xds/discovery.go#L55-L58), it is natural to assume **pilot_debounce_time** will be too.
But that's not the case, pilot_debounce_time [includes](https://github.com/istio/istio/blob/fbe084f46ed796559f0d0afdbb5a916988b07454/pilot/pkg/xds/discovery.go#L348) time taken by **initPushContext** as well.
Clarifying in the docs that -> 
pilot_debounce_time = debounce time + [pilot_pushcontext_init_seconds](https://github.com/istio/istio/blob/fbe084f46ed796559f0d0afdbb5a916988b07454/pilot/pkg/xds/monitoring.go#L63-L67)
> doc: pilot_debounce_time is not bound by debounceMax. Clarify in docs

- pkg/test/framework/components/istio/ingress.go
- pkg/test/kube/util.go
Fixes: https://github.com/istio/istio/issues/55027
While executing the TestGatewayAPIRequestAuthentication and TestGatewayAPIAuthorizationPolicy tests on a cluster that runs on a public cloud, the tests fail.
When the Ingress is a domain name, like in public cloud, it might take a bit for the DNS name to become populated.
Set a check to wait for the domain name to become resolvable.
> Check for reachable ingress in TestGatewayAPI security test

- pilot/pkg/bootstrap/mesh.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
- pkg/kube/krt/collection_test.go
- pkg/kube/krt/krttest/helpers.go
- pkg/kube/krt/options.go
Today we only use krt in 2 places, so the names are fine. As we expand
it, the naming is quite confusing. What is the difference between a
Gateway in ambient vs in the Gateway controller vs in some other
controller, for instance.
Adding a namespace to this makes things much more clear. I accomplish
this by adding this to the common opts builder, so we just set it once.
I also establish a pattern of prefixing informers with `informer/`. This
is helpful since often the collections are `k8s.Type` --> `internal.Type`,
so now we can name these `informer/Type` and `Type` and clearly
distinguish them.
> krt: add name prefix to naming scheme

- cni/pkg/iptables/iptables_e2e_test.go
- releasenotes/notes/55281.yaml
- tools/istio-iptables/pkg/capture/run.go
- tools/istio-iptables/pkg/capture/run_test.go
- tools/istio-iptables/pkg/cmd/root.go
- tools/istio-iptables/pkg/dependencies/implementation.go
- tools/istio-iptables/pkg/dependencies/implementation_linux.go
- tools/istio-iptables/pkg/dependencies/interface.go
Followon from https://github.com/istio/istio/pull/55276, xref: https://github.com/istio/istio/issues/55215
After https://github.com/istio/istio/pull/55228/ and https://github.com/istio/istio/pull/54845 I started getting `cni/pkg/iptables` test failures within the build container that I hadn't gotten before, which led me to a few of these fixes.
1. `iptables_e2e_test.go` was detecting iptables 2x, which in some contexts would result in them failing because the detected binary changed mid-test. Also some tests were ignoring the detected binary and using `iptables` when that wasn't contextually correct - I've removed the double-detect and made sure that tests use the detected binary in all cases, rather than hardcoding `iptables`.
2. The iptables …
> `istio-cni`: Fixup iptables tests + make iptables binary detect more robust

- tests/integration/ambient/cniupgrade/main_test.go
Right now we log `main_test.go:225: failed to rollout status deployments exit status 1` which tells us nothing really.
> Show command output on CNI test failure.

- pkg/test/echo/parse.go
This ensures we are not accidentally swallowing multiple header
responses. Hopefully no tests fail...
> test framework: respect multiple headers

- pkg/test/framework/components/echo/check/checkers.go
Otherwise the errors are confusing since they don't explain we need only
1 to succeed, not all of them
> test framework: clearly log Or() errors

- istioctl/pkg/internaldebug/internal-debug.go
- istioctl/pkg/multixds/gather.go
fix some bugs:
- https://github.com/istio/istio/pull/54752 return error `https://github.com/istio/istio/pull/54752` when `Proxy not connected to this Pilot instance. It may be connected to another instance.`
- Retry from next istio if return with `Proxy not connected to this Pilot instance. It may be connected to another instance.`
> istioctl: fix bug for internl-debug

- pkg/config/mesh/meshwatcher/mesh.go
- pkg/config/mesh/meshwatcher/mesh_test.go
- pkg/config/mesh/meshwatcher/networks.go
- pkg/kube/kclient/client.go
- pkg/kube/kclient/client_test.go
- pkg/kube/kclient/delayed.go
- pkg/kube/kclient/interfaces.go
- pkg/kube/krt/collection.go
- pkg/kube/krt/conformance_test.go
- pkg/kube/krt/core.go
- pkg/kube/krt/informer.go
- pkg/kube/krt/internal.go
- pkg/kube/krt/join.go
- pkg/kube/krt/processor.go
- pkg/kube/krt/singleton.go
- pkg/kube/krt/static.go
kclient:
* allow removing a single handler instead of just all
* Ensure dynamic object filter events do not sent on removed handlers
krt:
* Allow removing a handler
* Utilize this to properly remove mesh config handlers instead of just marking them "inactive"
Tests:
* Add tests for removing single/all handlers in kclient
* Add test covering dynamic object case
* Add removing handlers to 'conformance' for krt, ensuning all collections get coverage
* Add a new test case specific to mesh config's usage to ensure the new change is functionally the same
> krt/kclient: Allow removing handlers

- pkg/test/framework/components/zipkin/kube.go
- tests/integration/telemetry/tracing/otelcollector/tracing_test.go
- tests/integration/telemetry/tracing/zipkin/client_tracing_test.go
- tests/integration/telemetry/tracing/zipkin/server_tracing_test.go
When running the telemetry tests on public cloud platforms, DNS endpoint resolve could take some time.
- Increase telemetry tracing tests timeout.
- Use the function with the wait and retry approach to get the endpoint resolvable.
> Fix Telemetry Tracint flaky tests failures

- pkg/kube/inject/template.go
- pkg/kube/inject/testdata/inject/hello-existing-cncf-networks-json.yaml
- pkg/kube/inject/testdata/inject/hello-existing-cncf-networks-json.yaml.injected
Fixes #54820
Fix behavior when the value of `k8s.v1.cni.cncf.io/networks` annotation is a JSON array.
> multus: fix behavior when the value of `k8s.v1.cni.cncf.io/networks` annotation is a JSON array

- pilot/pkg/bootstrap/server.go
- pilot/pkg/controllers/untaint/nodeuntainter.go
- pilot/pkg/controllers/untaint/nodeuntainter_test.go
- pkg/kube/krt/options.go
Plumb the krt debugger to the node-untaint controllers, so we can diagnose its state while running.
> node untaint: plumb krt debugger to krt collections

- pilot/pkg/controllers/untaint/nodeuntainter_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/queue_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
- pilot/pkg/serviceregistry/kube/controller/fake.go
- pkg/kube/krt/conformance_test.go
- pkg/kube/krt/join_test.go
- pkg/kube/krt/krttest/helpers.go
- pkg/kube/krt/recomputetrigger_test.go
- pkg/kube/krt/singleton_test.go
- pkg/kube/krt/static_test.go
To make sure we avoid https://github.com/istio/istio/pull/55377 for
other places. Fortunately, all places missing it were tests, but
consistently using it everywhere ensures we can add checks that enforce
its always set.
> krt: use stop and debugger everywhere

- cni/pkg/nodeagent/server.go
When mesh dataplane initialization fails, the cause was unclear in the logs because the error was dropped by `NewServer`. The patch ensures that the underlay error is included, making it easier to diagnose:
Before:
```
Error: failed to create ambient nodeagent service: error initializing mesh dataplane
```
After:
```
Error: failed to create ambient nodeagent service: error initializing mesh dataplane: stat 1/ns/net: permission denied
```
> Include the underlay error in the mesh dataplane initialization error

- samples/bookinfo/src/ratings/Dockerfile
We add curl, but the base has no CA certs so you cannot use it to hit
HTTPs endpoints. Not a big deal but useful for debugging sometimes.
> Fix TLS from ratings sample

- pilot/pkg/model/push_context.go
- pilot/pkg/model/virtualservice.go
We do not need to clone VS for GW objects since we just return anyways. Thios is about 10% of CPU on a GW-API heavy cluster
> optimization: do not copy when we do not need to

- pilot/pkg/networking/core/gateway.go
- pilot/pkg/networking/core/listener_waypoint.go
- pilot/pkg/networking/core/route/route.go
- pilot/pkg/networking/core/route/route_test.go
Before, we had custom code for waypoint routes and sidecar/gateway routes. This led to bugs like https://github.com/istio/istio/issues/55259.
This PR merges them. The reason we had the split was due to differences in how we lookup services, destination clusters, and hash policies. These have been abstracted into RouteOptions to allow each path to specify their own way to do the lookups.
> waypoint: unify XDS for waypoint routes

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/55409.yaml
Fixes #55409
Regression from #51946
I added a small unit test to prevent regressions in the future
> Fix validation for 0s connectionPool.tcp.IdleTimeout

- pilot/pkg/model/envoyfilter.go
- pilot/pkg/model/push_context.go
- pilot/pkg/networking/core/cluster.go
- pilot/pkg/networking/core/httproute.go
- pilot/pkg/networking/core/listener_builder.go
- tests/integration/ambient/baseline_test.go
EnvoyFilter is not implemented in waypoint, but due to code-reuse around
Istio we essentially accidentally implement some form of it.
Proper support is tracked in
https://github.com/istio/istio/issues/43720. This will require new logic
into Istio, likely around a new `WAYPOINT` context, `targetRef`
implementation, etc.
Until then, explicitly disable support to avoid accidental partial
attachment of filters to waypoints.
> ambient: disable accidental EnvoyFilter implementation

- pkg/kube/krt/index.go
- pkg/kube/krt/index_test.go
This adds support for using indexes as collections in krt. The primary motivation for this is aggregations.
For instance, maybe I want to take a `Collection[ServiceEntry]` and merge it by hostname.
This is a draft since its pretty hacky. Only the MVP amount of functionality is implemented. The primary challenge is we cannot get the old and new state for the index. We don't _need_ it to use it as an input to a transformation collection, but if you just register a raw handler you would get raw results. Probably we will just need to document the limitations.
> krt: support using indexes as collections

- Makefile.overrides.mk
This spams `which: no overcover in` about 100 times when you run any
command. Also, it serves no purpose.
> Drop spammy env var

- pilot/pkg/model/context.go
- pilot/pkg/xds/ads.go
Currently we check if any `ServiceEntry` has been updated, but in reality we're only interested in `ServiceEntry` which can actually select this proxy, this means in the same namespace.
> optimize: avoid updating service targets when it's not really necessary

- pkg/test/framework/components/istio/ingress.go
- pkg/test/kube/util.go
This PR cherry-picks the following change - https://github.com/istio/istio/pull/55028
While executing the TestGatewayAPIRequestAuthentication and TestGatewayAPIAuthorizationPolicy tests on a cluster that runs on a public cloud, the tests fail.
When the Ingress is a domain name, like in public cloud, it might take a bit for the DNS name to become populated.
Set a check to wait for the domain name to become resolvable.
> Check for reachable ingress in TestGatewayAPI security test (#55028)

- istioctl/pkg/waypoint/waypoint.go
- releasenotes/notes/55465.yaml
Fix `istio.io/waypoint-for` and `istio.io/rev` labels cannot be generated simultaneously when creating Waypoint Proxy with istioctl.
Fix https://github.com/istio/istio/issues/55437
> fix waypoint-for and rev labels cannot be generated simultaneously by istioctl waypoint

- pkg/test/framework/components/zipkin/kube.go
- pkg/test/framework/components/zipkin/zipkin.go
- tests/integration/telemetry/tracing/otelcollector/tracing_test.go
- tests/integration/telemetry/tracing/zipkin/client_tracing_test.go
- tests/integration/telemetry/tracing/zipkin/server_tracing_test.go
This is a cherry-pick of the following PR - https://github.com/istio/istio/pull/53980
All telemetry tracing tests are failing during execution on Openshift.
During the tests execution, the traffic is being sent and should be captured through the service routed through ingress gateway.
In Kind environment, the "sslip.io" service is used, which servers as a DNS service that works with embedded ip addresses and returns that ip address as a name during query.
But in Openshift it's not working.
The Openshift cluster has a routable and dns resolvable ingress gateway. But when the test adds the service "tracing' to the ingress gateway - "tracing./api/v2...",
dns resolve is not working anymore and query to that url fails. Since we're not able to create …
> [release 1.24] fix telemetry tracing tests on openshift

- pkg/test/framework/components/zipkin/kube.go
- tests/integration/telemetry/tracing/otelcollector/tracing_test.go
- tests/integration/telemetry/tracing/zipkin/client_tracing_test.go
- tests/integration/telemetry/tracing/zipkin/server_tracing_test.go
This PR cheery-picks the following change - https://github.com/istio/istio/pull/55325
When running the telemetry tests on public cloud platforms, DNS endpoint resolve could take some time.
- Increase telemetry tracing tests timeout.
- Use the function with the wait and retry approach to get the endpoint resolvable.
> Fix Telemetry Tracint flaky tests failures (#55325)

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/statusqueue/queue.go
- pkg/config/mesh/meshwatcher/mesh.go
- pkg/config/mesh/meshwatcher/networks.go
- pkg/kube/krt/collection.go
- pkg/kube/krt/collection_test.go
- pkg/kube/krt/conformance_test.go
- pkg/kube/krt/core.go
- pkg/kube/krt/fetch.go
- pkg/kube/krt/helpers.go
- pkg/kube/krt/index.go
- pkg/kube/krt/informer.go
- pkg/kube/krt/internal.go
- pkg/kube/krt/join.go
- pkg/kube/krt/krttest/helpers.go
- pkg/kube/krt/processor.go
- pkg/kube/krt/processor_test.go
- pkg/kube/krt/recomputetrigger.go
- pkg/kube/krt/singleton.go
- pkg/kube/krt/singleton_test.go
- pkg/kube/krt/static.go
- pkg/kube/krt/static_test.go
- pkg/kube/krt/status.go
- pkg/kube/krt/util.go
1. Drop the 'initial sync' arg to handlers. This was added in
https://github.com/istio/istio/pull/49843 to fix a bug that doesn't
exist anymore (due to the queue we added a while back), makes things
more complex, isn't tested, isn't used, and doesn't work properly.
2. Fix a bug where event handlers could be marked as synced before
the processed all events. Many tests addeed to cover these cases.
3. Fixed a bug in the status controller (which is not used today, yet)
that doesn't properly handle syncing at all.
3a. Allow static collection to be marked as synced after startup,
instead of assuming it starts synced. This is to help implement the fix.
This is useful in general IMO.
4. Add a new `RecomputeProtected`. This is a wrapper around data that
ensures any access is properly marked as …
> krt: various improvements split out

- pilot/pkg/model/sidecar.go
These seem to have been missed.
> optimize: add missing cluster scoped known config types for sidecar

- pilot/pkg/networking/core/cluster_tls.go
- pilot/pkg/xds/endpoints/endpoint_builder.go
- tests/integration/ambient/baseline_test.go
Fixes https://github.com/istio/istio/issues/53526.
Two flaws in the code:
* In CDS, we accidentally wrapped HBONE on top of mTLS. It should be on raw_buffer. Note this never triggered, due to the next issue, so went unnoticed.
* In EDS, we disable HBONE if mTLS is explicitly enabled. The intent was to make it so we prefer to use mTLS. But this means we would use it even when we should use HBONE. Loosen the check to make it only apply if the backend supports mTLS.
> HBONE: properly use HBONE when ISTIO_MUTUAL is explicitly set

- cni/pkg/install/install.go
```
2025-03-14T18:37:17.759977Z     error   cni-agent       failed file copy of /opt/cni/bin/istio-cni to /host/opt/cni/bin: open /host/opt/cni/bin/istio-cni.tmp.2628672928: read-only file system
2025-03-14T18:37:17.760096Z     warn    hint: some Kubernetes environments require customization of the CNI directory. Ensure you properly set global.platform=<name> during installation
2025-03-14T18:37:17.760202Z     error   cni-agent       installer failed: copy binaries: open /host/opt/cni/bin/istio-cni.tmp.2628672928: read-only file system
```
> cni: give hint when platform is not set appropriately

- istioctl/pkg/ztunnelconfig/ztunnelconfig.go
`ztunnel-config` has two types of commands:
* Introspecting config that should be identical across all pods
* Introspecting a single instance
For the former, allowing eliding a specific pod name is quite nice
since, unless debugging out-of-sync issues, the result will be the same.
For some commands, though, this just leads to confusion.
This PR makes it so certain commands MUST specify a specific pod/node
> istioctl zc: avoid accidentally selecting random pod

- pilot/pkg/networking/core/cluster_builder_test.go
- pilot/pkg/networking/core/cluster_test.go
- pilot/pkg/networking/core/cluster_tls.go
- pilot/pkg/networking/core/cluster_tls_test.go
- pilot/pkg/networking/core/cluster_traffic_policy.go
We are modifying the TLS type, which is shared object. This is not
supposed to be done. Change this to just modify the place we use it.
We had 2 tests for the same thing. I deleted one after verifying it has
identical coverage, and modified the other to check the resulting XDS
instead of asserting that we mutate the DestinationRule
> tls: do not modify shared objects

- pilot/pkg/serviceregistry/serviceentry/controller.go
Simple change to avoid unnecesary slice copying, `getAllServices()` already returns a new slice everytime, so we can reuse the returned slice,
> optimize: avoid unnecessary slice copying

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
- releasenotes/notes/55567.yaml
xref: https://github.com/istio/istio/issues/50164#issuecomment-2731904656
This warn message confuse me a lot, maybe it's better to remove it.
cc @ramaraochavali @hzxuzhonghu 
fixes: #50164
> don't warning when se is set workloadSelector with resolution DNS

- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads_test.go
- pkg/test/framework/components/istio/ingress.go
- pkg/test/framework/components/istio/ingress/interface.go
- releasenotes/notes/55569.yaml
- tests/integration/ambient/baseline_test.go
following configuration is valid in sidecar mode, as a follow up of #51152, this patch make it also work in ambient
```
apiVersion: networking.istio.io/v1
kind: WorkloadEntry
metadata:
name: httpbin-we
spec:
address: httpbin.local
labels:
app: httpbin-local
---
apiVersion: networking.istio.io/v1
metadata:
name: httpbin-local
spec:
exportTo:
- "*"
hosts:
- httpbin.local
location: MESH_EXTERNAL
ports:
- name: tcp
number: 8000
protocol: TCP
resolution: DNS
workloadSelector:
labels:
app: httpbin-local
```
@howardjohn PTAL
> ambient: support fqdn in workloadentry

- istioctl/pkg/waypoint/waypoint.go
* Log "applied" when we apply it, not after its ready
* Explicitly log once ready, if we waited
* Make the messages a bit more consistent with others (emoji)
> Minor cleanup on istioctl waypoint command

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
- releasenotes/notes/ap-gateway-class-status.yml
When applying an AuthorizationPolicy that specifies a targetRef of GatewayClass type, the status never shows a `WaypointAccepted` condition of status `true`. This PR adds resolution of `GatewayClass` type for this condition so it shows the proper status.
> Bug Fix - Add Handling of `GatewayClass` to `WaypointPolicyStatusCollection`

- pkg/kube/krt/collection.go
- pkg/kube/krt/filter.go
- pkg/kube/krt/index_test.go
- pkg/kube/krt/internal.go
See test case added. Our optimization around reverse indexing only
allowed a single Index/Key fetch per collection. This allows doing both.
In theory you may want multiple distinct Index/Key lookups to a single
collection, but this is pretty hard to address.
How this works is instead of keying just by `collection`, we key by
`{collection, lookupType}`.
We explicitly detect the case of an Index+Key lookup on the same Fetch.
We cannot detect the case of 2 separate Fetch calls both doing an Index
or both doing a Get, though.
Fixes https://github.com/istio/istio/issues/55503
> krt: allow fetching a collection by Index and Key

- pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
These are not supported by ztunnel, but we should treat them as not
existing
> ambient: do not process dry-run rules

- istioctl/pkg/writer/ztunnel/configdump/connections.go
This was supposed to be based on namespace+name but was only namespace
> istioctl: properly sort ztunnel-connections

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/authorization_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/policies.go
- releasenotes/notes/ap-not-in-root-ns-gwclass-targetref.yml
When an `AuthorizationPolicy` uses a target reference of `GatewayClass` type, it must reside in the root namespace. This PR adds a check to the waypoint status collection to update the status condition `WaypointAccepted` when this use case is violated.
> add status for when ap is not in root ns and gw class target ref is used

- pkg/test/echo/cmd/server/main.go
- pkg/test/echo/server/instance.go
Reproducer:
```
unshare --map-root-user --net sh -c 'ip link set dev lo up; server'
```
Also, add a small helper to make ctrl-C twice drain instantly
> echo: fallback to IPv4 if there are no address

- pilot/pkg/serviceregistry/kube/controller/namespacecontroller.go
- pkg/kube/controllers/queue.go
- pkg/kube/multicluster/secretcontroller.go
- pkg/kube/watcher/configmapwatcher/configmapwatcher.go
- pkg/revisions/tag_watcher.go
The k8s queue MUST be shutdown after its created. This is done
automatically with Run(stop), but if we never run it, we never shutdown.
This change ensures we always shutdown, even if we exit before we run.
Example test failure: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/55761/unit-tests-arm64_istio/1906970954236432384
> Fix goroutine leak when sync fails

- manifests/charts/istio-cni/templates/configmap-cni.yaml
Currently, the CNI `REPAIR_ENABLED` flag is mistakenly enabled based on `.cni.chained` value instead of `.repair.enabled`. This PR fixes it.
Fixes: https://github.com/istio/istio/issues/55704
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>
cherry picked from commit af784e7e2e4840ea8902ebdc7958cfbdf058244a
> [release-1.23] Fix broken IstioCNI config for enabling repair mode (#55665)

- pilot/pkg/networking/core/route/route_cache.go
- releasenotes/notes/rds-cache-alias.yaml
We accounted for this in DependantConfigs() but not Key(). Can reproduce
by adding/removing a Alias service from a Sidecar scope and you will see
its not updated before this PR. With RDS cache off, or
`cachez?clear=true`, or this PR, it is updated.
> pilot: fix bug in Alias type RDS cache

- pilot/pkg/serviceregistry/serviceentry/conversion.go
resolve #55798, ensure ServiceEntry with DNS resolution to work when clusterLocal enabled for all services.
> add locality info for ServiceEntry endpoints

- prow/config/default.yaml
- prow/integ-suite-kind.sh
- prow/lib.sh
This is setting the local registry up following the [kind v0.27.0 breaking changes](https://github.com/kubernetes-sigs/kind/releases/tag/v0.27.0).
Related issue #55132
> Update local registry setup

- pkg/kube/client.go
- pkg/test/framework/components/istio/cleanup.go
- pkg/test/kube/dump.go
- pkg/test/kube/util.go
This PR contains cherry-pick for the following PRs:
- https://github.com/istio/istio/pull/54447
- https://github.com/istio/istio/pull/54377 (partially. only cleanup part)
When test resources cleaned up in Openshift, it takes time for the "istio-ingressgateway" and "istio-egressgateway" services to be deleted.
As a result, when the resources are cleaned after one test and the next test starts, ittend to fail because the services are in deletion state and failed to be used by the next test.
Check for the services to be deleted completely before ending the test.
> [release-1.24] Fix tests resources cleanup for Openshift

- pilot/pkg/config/kube/gateway/gateway_collection.go
The key name was not distinct, leading to forgetting the other
namespaces if we have the same name
> gateway: fix regression around shared name cross-namespace

- istioctl/pkg/writer/ztunnel/configdump/api.go
- istioctl/pkg/writer/ztunnel/configdump/certificates.go
- security/pkg/server/ca/server.go
Fixes https://github.com/istio/istio/issues/55793
Also adds istioctl support for the ztunnel side fixes in https://github.com/istio/ztunnel/pull/1510
> Do not split root CA, fixing 1.25.1 regression

- pkg/bootstrap/config.go
WDS only supports Delta. This maybe could have a restriction on the
server side, too, but there are some tooling (debug interface, etc) that
always expect to use the SOTW flow which makes it hard.
> Disable metadata lookup on SotW

- pilot/pkg/config/kube/crd/conversion.go
We skipped these for some reason, useful to have the full object
> debug configz: show all metadata fields

- tests/integration/telemetry/api/stats_test.go
Fix the TestStatsFilter/mockprom-to-metrics telemetry test.
Add the missing mock for secured prometheus scraping test.
> Fix Telemetry api TestStatsFilter/mockprom-to-metrics test

- tools/istio-iptables/pkg/builder/iptables_builder_impl.go
- tools/istio-iptables/pkg/capture/run.go
- tools/istio-iptables/pkg/capture/run_linux.go
- tools/istio-iptables/pkg/constants/constants.go
Currently, the `BuiltInChainsMap` is used in various places to ignore the creation/deletion of built-in chains. However, the map also includes `ACCEPT`, `RETURN`, and `DROP`, which are targets, not chain names. This PR removes these target names from the list.
> Rename BuiltInChainsMap to BuiltInChainsAndTargetsMap

- pkg/kube/util.go
We really do not want to ignore a configuration to explicitly use a
certain kubeconfig.
See https://github.com/istio/istio/issues/55894#issuecomment-2802143117
for example
> Disable fallback for missing kubeconfig

- pkg/kube/krt/collection.go
- pkg/kube/krt/filter.go
- pkg/kube/krt/index_test.go
Ensure that the mechanisms introduced in #54074 #55515 don't prevent multiple FilterIndex in a single transformation, so long as we are filtering using the _same_ index.
> add test for multiple FilterIndex

- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/listener.go
- pilot/pkg/networking/core/listener_builder.go
- pilot/pkg/networking/core/listener_inbound.go
- releasenotes/notes/max-socket-events.yaml
See https://github.com/envoyproxy/envoy/pull/38999 and https://github.com/envoyproxy/envoy/issues/19103#issuecomment-2719261380
I think compatibility version is not needed as it is most sensible default but if there are concerns I can add
> default maxconnectionstoacceptpersocketevent to a sensible value

- pkg/config/mesh/meshwatcher/collection.go
- pkg/kube/krt/conformance_test.go
- pkg/kube/krt/files.go
- pkg/kube/krt/files/files.go
- pkg/kube/krt/files/files_test.go
- pkg/kube/krt/internal.go
- pkg/kube/krt/static.go
This gives us the ability to register a collection based on a folder. The intent is to allow us to be able to have the same config as https://github.com/istio/istio/blob/b59d3f59928046f3a0cc64563004f70152530888/pilot/pkg/bootstrap/configcontroller.go#L258
> krt: implement folder based collections

- istioctl/pkg/admin/istiodconfig.go
- istioctl/pkg/admin/istiodconfig_test.go
- releasenotes/notes/55976.yaml
Related: https://github.com/istio/istio/issues/55741#issuecomment-2812343990
Fix`istioctl admin log` cannot modify the log level of `ip-autoallocate`.
> fix istioctl admin log cannot modify the log level of ip-autoallocate

- pilot/pkg/features/pilot.go
- pilot/pkg/networking/core/httproute.go
- pilot/pkg/networking/core/httproute_test.go
- releasenotes/notes/fix-enable-absolute-fqdn-domain-vhost.yaml
**Description:**
This PR fixes an issue where Istio's outbound route configuration (`RouteConfiguration`) did not include the absolute/fully qualified domain name (FQDN) variant (e.g., `my-service.my-ns.svc.cluster.local.`) in the `domains` list for `VirtualHost` entries.
Updated the TestGenerateVirtualHostDomains test to verify new functionality
**Problem:**
When clients make requests using the absolute FQDN (with the trailing dot) in the `Host` header, Envoy would fail to match this against the specific `VirtualHost` domains generated by Istio. This caused such requests to fall back to the wildcard (`*`) virtual host, typically resulting in routing to the `PassthroughCluster` or `BlackHoleCluster` instead of the intended service cluster and associated Istio policies (like …
> fix(networking): Add absolute FQDNs (trailing dot) to VirtualHost domains

- pilot/pkg/networking/core/accesslog_test.go
In `pilot/pkg/networking/core/accesslog_test.go` file, `newTestEnviroment` should be named as `newTestEnvironment`.
> doc: fix typo in accesslog test

- istioctl/pkg/tag/util.go
- releasenotes/notes/56004.yaml
fix istio-revision-tag-default MutatingWebhookConfiguration is not created during installation when the revision is not default
Fix https://github.com/istio/istio/issues/55980
> fix istio-revision-tag-default MutatingWebhookConfigurations is not created during installation

- pilot/pkg/serviceregistry/kube/controller/ambient/waypoints.go
- pilot/pkg/serviceregistry/kube/controller/ambient/waypoints_test.go
- pkg/config/constants/constants.go
- releasenotes/notes/56011-sandwich-allowedRoutes.yaml
Adds determining allowedRoutes for waypoint based on the `ambient.istio.io/waypoint-inbound-binding` annotation used to determine the correct inbound binding.
This is required to support cross-namespace waypoints for 3rd-party waypoint proxies which are wrapped by ztunnel (a.k.a. "sandwiched" waypoints) rather than implementing their own HBONE listener.
fixes #56010
> handle allowedRoutes for PROXY waypoints

- pilot/pkg/model/telemetry.go
follow up: https://github.com/istio/istio/pull/56041
without this, we may send accesslog config of v1.26 to a v1.25 sidecar with same telemetry configs
> telemetry: computedLoggingConfig cached should be versioned

- pilot/pkg/model/envoyfilter.go
- pilot/pkg/model/push_context.go
- pilot/pkg/networking/core/cluster.go
- pilot/pkg/networking/core/httproute.go
- pilot/pkg/networking/core/listener_builder.go
- tests/integration/ambient/baseline_test.go
this revert #55149 to prvent break end users, because https://github.com/istio/api/pull/3442 didn't land in `v1.26`.
**https://github.com/istio/api/pull/3442 still the future plan**
cc @therealmitchconnors @howardjohn  @hzxuzhonghu @keithmattix @linsun @vikaschoudhary16
> revert ambient: disable accidental EnvoyFilter implementation

- pkg/kube/krt/collection.go
- pkg/kube/krt/collection_test.go
- pkg/kube/krt/filter.go
- pkg/kube/krt/index.go
- pkg/kube/krt/index_test.go
- tests/binary/binaries_test.go
https://github.com/istio/istio/issues/56036
This PR makes the following example _safe_ without subscriptions being missed/overwritten:
```
// same collection, same transform, different index
krt.NewCollection(..., func (ctx krt.HandlerContext, o I) *O {
Fetch(colA, krt.FilterIndex(indexA, "key 1"))
Fetch(colA, krt.FilterIndex(indexB, "key 2"))
}
```
> krt: remove restrictions on multiple Fetch calls

- pilot/pkg/model/service.go
- pilot/pkg/model/service_test.go
When a dual-stack service is configured with ipFamilies: [IPv6, IPv4], the listener ends up using the same IPv4 address for both address and additionalAddress (ignoring the IPv6 address). This happens because [GetAddressForProxy](https://github.com/istio/istio/blob/82bee2b455527f406cd7dbd884316070f1232a21/pilot/pkg/model/service.go#L1599)() (via [filterAddresses](https://github.com/istio/istio/blob/82bee2b455527f406cd7dbd884316070f1232a21/pilot/pkg/model/service.go#L1733) method) prioritizes IPv4 over IPv6, and [GetExtraAddressesForProxy](https://github.com/istio/istio/blob/82bee2b455527f406cd7dbd884316070f1232a21/pilot/pkg/model/service.go#L1629)() also returns the same IPv4 address from the service. This PR modifies the filterAddresses to return the addresses based on the …
> Fix listener addr duplication for dualStack svc with IPv6 as primary

- pilot/pkg/model/service.go
- pilot/pkg/model/service_test.go
When a dual-stack service is configured with ipFamilies: [IPv6, IPv4], the listener ends up using the same IPv4 address for both address and additionalAddress (ignoring the IPv6 address). This happens because GetAddressForProxy() (via filterAddresses method) prioritizes IPv4 over IPv6, and GetExtraAddressesForProxy() also returns the same IPv4 address from the service. This PR modifies the filterAddresses to return the addresses based on the firstAddrFamily.
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>
(cherry picked from commit 1bc024b509c7647777e11e7c9c2b3403cc1e5f60)
Fixes: https://github.com/istio/istio/issues/56175
> [release-1.26] Fix listener addr duplication for dualStack svc with IPv6 as primary

- istioctl/pkg/dashboard/dashboard.go
- istioctl/pkg/dashboard/dashboard_test.go
- releasenotes/notes/55843.yaml
Add `--revision` flags for `istioctl dashborad controlz` and `istioctl dashborad istiod-debug`.
For the istioctl command, it is now possible to filter by revision when selecting the istiod control plane. Likewise, it would be nice to have a `--revision` flag for `istioctl dashborad controlz` and `istioctl dashborad istiod-debug`.
> istioctl: support specify revision for istiod dashboard

- pilot/pkg/model/service.go
- pilot/pkg/model/service_test.go
When a dual-stack service is configured with ipFamilies: [IPv6, IPv4], the listener ends up using the same IPv4 address for both address and additionalAddress (ignoring the IPv6 address). This happens because GetAddressForProxy() (via filterAddresses method) prioritizes IPv4 over IPv6, and GetExtraAddressesForProxy() also returns the same IPv4 address from the service. This PR modifies the filterAddresses to return the addresses based on the firstAddrFamily.
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>
(cherry picked from commit 1bc024b509c7647777e11e7c9c2b3403cc1e5f60)
Fixes: https://github.com/istio/istio/issues/56183
> [release-1.24] Fix listener addr duplication for dualStack svc with IPv6 as primary

- pkg/kube/krt/collection.go
- pkg/kube/krt/core.go
- pkg/kube/krt/dynamic.go
- pkg/kube/krt/index.go
- pkg/kube/krt/informer.go
- pkg/kube/krt/join.go
- pkg/kube/krt/nestedjoin.go
- pkg/kube/krt/singleton.go
- pkg/kube/krt/static.go
Replace usage of `kclient.RawIndexer` internally in krt to a typed `indexer[T]` which allows us to skip unnecessary conversions on every call to `index.Lookup()`.
> krt: typed indexers to avoid unnecessary conversions

- tests/integration/pilot/analysis/analysis_test.go
Increasing timeout since TestAnalysisWritesStatus is flaky on Openshift Cloud Platform
> Fix TestAnalysisWritesStatus flaky on Openshift Cloud Platform

- pkg/kube/krt/processor.go
- pkg/kube/krt/processor_test.go
```
panic: send on closed channel
goroutine 1545 [running]:
istio.io/istio/pkg/kube/krt.(*handlerSet[...]).Insert.func3()
istio.io/istio/pkg/kube/krt/processor.go:76 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
k8s.io/apimachinery@v0.32.3/pkg/util/wait/wait.go:72 +0x4c
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start in goroutine 1517
k8s.io/apimachinery@v0.32.3/pkg/util/wait/wait.go:70 +0x73
```
In rare cases, we already have a handler unregistered before we even sync the parent collection, causing this panic. 
This PR has a test that easily reproduces the panic, and simply guards that  the handler is still in the set before we send to that channel. 
Set membership is a good proxy for the channel not being closed, because we close the channel at the same …
> krt: fix panic when we remove handlers before sync

- tests/integration/security/ingress_test.go
- tests/integration/security/sds_ingress/util/util.go
Support multiple error messages in TestMultiTlsGateway_InvalidSecret and TestMultiMtlsGateway_InvalidSecret tests, where the error may differ across different environments.
In Openshift, the expected error for the test appear as "EOF" instead of "connection reset by peer".
Enhanced ExpectedResponse to allow a list of allowed error message substrings via the new AllowedErrorMessages field. This improves test reliability across environments (e.g., Kind vs OpenShift), where error messages like "connection reset by peer" and "EOF" may differ.
Maintains backward compatibility with the original ErrorMessage field.
Includes updated validation logic to check against both single and multiple expected error messages.
> Support multiple err msg in TestMultiTlsGateway_InvalidSecret test

- pkg/test/framework/components/istio/ingress.go
Integration tests running on public clusters and using ingress address resolution may become flaky, because DNS resolution, after ingress address creation may take time to become resolvable.
As a result, the tests fail with the following error: unable to get reachable ingress. Error: timeout while waiting after 9 attempts (last error: lookup <ingress addr> on 172.31.0.10:53: no such host
Improve the "getAddressesInner" function and add:
- Added DNS resolution check after retrieving remote service addresses to avoid flakiness
- Skips DNS check if the address already an IP (e.g., NodePort fallback)
- Ensures retry logic waits for a resolvable host before proceeding
- Improves error wrapping and handling of unexpected address formats
> Improve ingress address resolution in integration tests flow

- istioctl/pkg/workload/workload.go
- istioctl/pkg/workload/workload_test.go
- releasenotes/notes/56666.yaml
It is better for user can use `istioctl experimental workload group create` to specify any parameter for workload group.
> support --weight parameter for istioctl x workload group create

- istio.deps
- tests/binary/binaries_test.go
We've been at the upper limit of ztunnel binary size. The latest ztunnel is failing that test, bump the allowed size range a little.
Adopt the zt SHA which failed to merge due to binary size.
> Increase zt bin limit

- istioctl/pkg/admin/istiodconfig.go
- istioctl/pkg/dashboard/dashboard.go
- istioctl/pkg/util/constants.go
- pkg/ctrlz/options.go
The controlz port is set to 9847 in many places. It would be better to set it to a constant.
> Set the controlz port to a constant

- tools/build-base-images.sh
We pushd but did not popd so the config file was not found
> base image builder: fix script

- pilot/pkg/features/tuning.go
These are not used, cleanup to avoid confusion
> pilot: cleanup deadcode in features

- pkg/kube/krt/collection.go
- pkg/kube/krt/collection_test.go
- pkg/kube/krt/map.go
Krt places a number of un-checked requirements on collections.
This PR introduces a new knob to turn on assertions to be used during
development. IT IS OFF for production.
For the record, I had two tests that fail these assertions:
```go
func TestCollectionInvalid(t *testing.T) {
//return
stop := test.NewStop(t)
opts := testOptions(t)
c := kube.NewFakeClient()
kpc := kclient.New[*corev1.Pod](c)
pc := clienttest.Wrap(t, kpc)
pods := krt.WrapClient[*corev1.Pod](kpc, opts.WithName("Pods")...)
c.RunAndWait(stop)
BadPods := krt.NewCollection(pods, func(ctx krt.HandlerContext, i *corev1.Pod) *SimplePod {
return &SimplePod{
// Ignore namespace, so we will have 2 inputs map to one output.
Named: Named{Name: i.Name},
IP:    i.Status.PodIP,
}
}, opts.WithName("Broken")...)
BadPods.Register(func(o …
```
> krt: add assertions

- pilot/pkg/features/pilot.go
- pilot/pkg/serviceregistry/kube/controller/pod.go
- pilot/pkg/serviceregistry/kube/controller/util.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- releasenotes/notes/pod-controller-avoid-ip-search.yaml
Creating this as a draft to check if tests pass, I'm not sure why we still maintain this logic, I cannot understand in which cases we would fail to find a Pod by it's name+namespace but find them by IP.
> remove finding of pods by IP

- pilot/pkg/features/experimental.go
- pkg/bootstrap/config.go
- pkg/bootstrap/option/instances.go
- releasenotes/notes/envoy-status-port-proxy-protocol.yaml
- tools/packaging/common/envoy_bootstrap.json
On AWS network load balancers, when enabling proxy protocol and configuring health check to query Istio status port on the path /healthz/ready, the health check fails, because Istio status port does not support proxy protocol. However, on the load balancer, proxy protocol cannot be disabled for the health check only.
Envoy supports the proxy protocol with an option to allow requests without proxy protocol. This option breaks conformance to the proxy protocol specification, and should only be enabled when the traffic to the listener comes from a trusted source, which should be the case for the status port. This seems to be a good compromise to allow both requests with and without proxy protocol on the status port.
Fixes #39868
This PR is meant …
> feat: enable support for proxy protocol on status port

- pkg/test/framework/components/crd/gateway.go
- pkg/test/framework/components/istio/config.go
- pkg/test/framework/components/istio/flags.go
- tests/integration/README.md
Integration tests should be able to control deployment of Gateway API during execution.
In some cases, environment does not need to deploy Gateway API CRDs during integration tests execution.
For example, in Openshift 4.19, the cluster comes with pre installed Gateway API CRDs, which could not be modified by the users. In that case, no Gateway API deployment is needed.
Add a flag - "--istio.test.kube.deployGatewayAPI" to control the flow. By default - true.
> Control Gateway API deploy in integration tests

- pkg/collateral/control.go
Resolves https://github.com/istio/istio.io/issues/16552. 
This PR adds anchor link tags to the tool that generates the environment variable tables for the documentation of each CLI. 
I tested this change by running `make build` followed by `./out/darwin_arm64/pilot-discovery collateral --html_fragment_with_front_matter`.
This change outputs HTML in the following format: 
```html
<tr id='ambient-enable-multi-network'>
<td><a href='#ambient-enable-multi-network'><code>AMBIENT_ENABLE_MULTI_NETWORK</code></a></td>
<td>Boolean</td>
<td><code>false</code></td>
<td>If true, the multi-network functionality will be enabled.</td>
</tr>
```
I then took the HTML that was generated and ran in locally through the website via `make serve` from the `istio.io` …
> Enhance `genHTMLFragment` to Include Anchor Tags in Environment Variable Table Output

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_serviceentry_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_workloadentry_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/sidecar_interop_test.go
- pkg/kube/kubetypes/types.go
- releasenotes/notes/56477.yaml
…
* Ambient: In ambient index, filter configs by revision (#56477)
* In ambient index, filter configs by revision
* release notes
* Address feedback
* Update releasenotes/notes/56477.yaml
---------
> [release-1.25] Ambient: In ambient index, filter configs by revision (#56477) (#56689)

- pilot/pkg/model/extensions.go
- pilot/pkg/model/extensions_test.go
- releasenotes/notes/wasm-fail-reload.yaml
Pairs with https://github.com/istio/api/pull/3471 to allow configuration of [Envoy's WASM FailurePolicy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/wasm/v3/wasm.proto#enum-extensions-wasm-v3-failurepolicy) `FAIL_RELOAD`
> wasmplugin: Allow configuration of fail reload strategy

- pkg/kube/inject/inject.go
- pkg/kube/inject/webhook_test.go
Allow `true`/`false` inject label values to maintain consistency. Fixes: #51841
> ensure consistency in inject label validation

- cni/pkg/nodeagent/informers.go
- cni/pkg/nodeagent/net_linux.go
- releasenotes/notes/56738.yaml
An edge case race condition in the cni: If a pod is deleted before we mark it as captured but that pod would have been captured it can wind up being included in our zds snapshot even though the pod no longer exists. If this occurs timed such that we send the snapshot but throw away the Kubernetes delete event (because the pod was not captured), it can cause ztunnel to endlessly retry setting up a proxy for a pod which is not going to exist and prevent ztunnel from becoming ready.
I'm honestly not that sure how to automate testing. I have a script which stresses this scenario on my machine. Using my script it takes an average of 4 loops to reach this broken state (as noted by a restarting ztunnel never becoming ready). In attempting to find this …
> CNI Pod delete edge case

- pilot/pkg/config/kube/gateway/conversion.go
- Istio Gateways support OPTIONAL_MUTUAL TLS termination.
- This isn't supported by the Gateway API option, since `conversion.go` lacks translation for this enum.
- Implement this.
> Add support for OPTIONAL_MUTUAL to Gateway API

- tests/integration/ambient/baseline_test.go
When executing TestServiceEntryInlinedWorkloadEntry Ambient test in a public cloud based cluster, the created ingress is a domain based name and the test fails with the following error:
configuration is invalid: endpoint address
"a6eec2a91721a42b0aa8e140fc6611fc-1873540778.us-east-1.elb.amazonaws.com" is not a valid IP address
Add a domain name resolution to ip based address.
> Add domain resolve to Ambient TestServiceEntryInlinedWorkloadEntry test

- pilot/pkg/serviceregistry/kube/controller/controller.go
- pilot/pkg/serviceregistry/kube/controller/network_test.go
- releasenotes/notes/56687.yaml
When discoveryFilters are set, this will make us potentially NOT watch the system namespace.. this has multiple bad effects:
1. We will never see events for the system namespace, so we never set the network for local pods. This does _not_ affect sidecars base-case, because we rely on the injector setting the label directly on the pods. 
https://github.com/istio/istio/blob/4bcf5060e46052d869c9207e44f10fb5e0b78e06/pilot/pkg/serviceregistry/kube/controller/controller.go#L248
2. If we're using waypoints, the waypoints will send plaintext to their backends. We do a lookup using `<network>/<ip>` to check the ambient indexes. The ambient index watches the system namespace separately, without this discovery selector. There will be a mismatch of `"" != …
> do not use discovery filter for system namespace network

- pilot/pkg/status/resourcelock.go
- pilot/pkg/status/resourcelock_test.go
This has been observed to cause extremely high CPU usage as we busyloop.
Basically if we have at least 1 pending item, and we re-enqueue and
actively worked on item, it will busy loop until the actively worked on
item is handled.
We should instead kill this worker. The other worker will handle the
task when it completes
> status: fix busyloop

- pkg/dns/client/dns.go
- pkg/dns/client/dns_test.go
Because we unconditionally add searchNamespace[0] and then check for existence, we unnecessarily create a 
CNAME for productpage.ns1.svc.cluster.local.ns1.svc.cluster.local (notice search namespace repeat)
This PR fixes it
> fix dns althost name generation

- pilot/pkg/config/kube/gateway/controller.go
- pilot/pkg/config/kube/gateway/inferencepool_collection.go
- pilot/pkg/config/kube/gateway/inferencepool_status_test.go
Includes tests for InferencePool.Status handling and cross namespace
lookups.
Test for the following basic scenarios:
* Cross namespace references
* Removing old state
* Keeping old state from other controllers
* ResolvedRef conditions
* Accepted conditions
A HTTPRoute can target BackendRefs in namespaces besides it self,
so when we try to do a reverse lookup from InferencePool to find parent
Gateways via HTTPRoute we need to list all HTTPRoutes in all Namespaces.
Added InferencePool to HTTPRoute.BackendRef index for easy access lookups.
@LiorLieberman @keithmattix 
Test case seems delayed until 0.5, but branch test ok kubernetes-sigs/gateway-api-inference-extension#1061
> Inference pool Status handling and cross namespace references

- pilot/pkg/config/kube/gateway/inferencepool_collection.go
- pilot/pkg/config/kube/gateway/inferencepool_test.go
The InferencePool should only create a shadow service if a HTTPRoute that has a Gateway that we control is connected. Else do nothing.
Clean up Service and Status if the HTTPRoute disconnects.
@LiorLieberman @keithmattix
> fix(gw-inference): Shadow service should only exist if it has to

- istioctl/pkg/dashboard/dashboard.go
There are no Pods with the name poilt-* in the istio system now. It would be better to change it to istiod-* in the example.
> improve istioctl dashboard example

- common/config/.golangci.yml
- pilot/pkg/config/kube/gateway/deploymentcontroller.go
- pilot/pkg/config/kube/gateway/deploymentcontroller_test.go
- pilot/pkg/xds/endpoints/endpoint_builder.go
- pkg/config/constants/constants.go
- releasenotes/notes/56845-inference-extension.yaml
> feedback and cleanup

- pkg/config/analysis/analyzers/analyzers_test.go
- pkg/config/analysis/analyzers/serviceentry/protocoladdresses.go
- pkg/config/analysis/analyzers/testdata/serviceentry-address-allocated-mesh-cfg.yaml
- pkg/config/analysis/analyzers/testdata/serviceentry-address-allocated.yaml
Fix serviceentry analyze false positive when address already allocated. Since from 1.25 `PILOT_ENABLE_IP_AUTOALLOCATE` is set to true by default, this may not be specified in meshconfig. Currently this analyzer will report a false positive message even though the address is written in the status field.
> Fix  false positive of serviceentry analyzer

- pkg/test/framework/resource/flags.go
- pkg/test/framework/resource/settings.go
- tests/integration/pilot/gateway_conformance_test.go
This PR adds a test flag which lets users to use AllowCRDsMismatch parameter defined in Gateway API Conformance suite.
> Add AllowCRDsMismatch parameter to gateway conformance options.

- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_multicluster_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/ambientindex_test.go
- pilot/pkg/serviceregistry/kube/controller/ambient/workloads.go
- pilot/pkg/serviceregistry/util/xdsfake/updater.go
- pkg/kube/krt/collection.go
Its hard to consistently test "action A will only cause this event" because event could have occurred before A and there is no way of saying "wait until all events propagate/KRT state is stable, then run A".
> Remove flaky test

- istioctl/pkg/admin/istiodconfig.go
- istioctl/pkg/admin/istiodconfig_test.go
- releasenotes/notes/56600.yaml
Currently there is only one `--reset` flag to reset the log level for both log and stack trace. It would be better to be able to reset two convenient log levels separately (like `--level` and `--stack-trace-level` for each).
> support reset log level or stack trace level separately for admin log

- cni/pkg/iptables/iptables.go
- cni/pkg/iptables/testdata/hostprobe.golden
- cni/pkg/iptables/testdata/hostprobe_ipv6.golden
- releasenotes/notes/56414.yaml
This PR modifies the existing host iptables rule addition logic from using the Append method to the Insert method. By inserting Istio's rules at the front of the iptables chain, we ensure these rules have higher matching priority compared to existing iptables rules.
Previously, appending rules caused issues in scenarios where existing iptables rules matched and handled targeted traffic before it reached Istio's rules. Consequently, the rules configured by Istio became ineffective.
We use a whitelist with iptables on the host, which only affects pods within the istio ipset. Therefore, matching it first will not cause any issues.
> Change host iptables rule addition from Append to Insert to ensure Istio's rules take precedence

- pkg/test/framework/resource/flags.go
- pkg/test/framework/resource/settings.go
- tests/integration/pilot/gateway_conformance_test.go
This manual cherrypick is necessary to be able to run istio v1.26 Gateway Conformance Tests with gateway api v1.2. 
[auto cherry-pick](https://github.com/istio/istio/issues/56973)
> Add AllowCRDsMismatch parameter to gateway conformance options. (#56945)

- tools/build-base-images.sh
The PR is fixing  build-base-images_release-builder_periodic job error since July 14.
Reference: https://prow.istio.io/job-history/gs/istio-prow/logs/build-base-images_release-builder_periodic
The failed job logs shows the error: 
```
+ exefiles+='\n'
++ grep -v '^usr/lib/xtables'
++ grep -v '^usr/bin/xtables'
++ grep -v '^usr/bin/ldconfig$'
++ grep -v '^etc/apk/commit_hooks.d/ldconfig-commit.sh$'
++ grep -v '.*\.so[0-9\.]*'
+ unexpectedFiles='usr/bin/clear
+ echo 'Found unexpected binaries: usr/bin/clear
```
The failure happened between 	Jul 14 15:00:39 and Jul 15 15:00:41 
Checking the commit history and it was caused by https://github.com/istio/istio/pull/56363
I added a new package `nftables` in the docker/iptables.yaml 
**To help us figure out who should review this PR, please put an …
> Fix build-base-images_release-builder_periodic job error: Found unexpected binaries

- docker/Dockerfile.base
- docker/iptables.yaml
- tools/build-base-images.sh
This PR is following today's WG Meeting discussion about the nft binary package for the Istio 1.27 release.
We will include the nft binary only in the distro debug image (docker/Dockerfile.base) . And this PR is reverting changes in the distroless iptables.yaml base image and the build-base-images.sh
I have run the part of expectedFiles and unexpectedFiles checking in the build-base-image.sh locally. There is no error in this PR.
There are other action items such as alerting the user that the distroless image does not include nft binary when a user enables  nativeNftables=true and selects distroless image. We will address that suggestion and golang library for nftables support in other PRs later. Thanks.
> nftables: Revert the package change in distroless base image and build-base-images.sh

- tests/binary/binaries_test.go
we need 146mb for arm64.
xref: https://prow.istio.io/view/gs/istio-prow/pr-logs/pull/istio_istio/57111/unit-tests-arm64_istio/1948584644928606208
```
=== RUN   TestBinarySizes/envoy
binaries_test.go:130: Actual size: 146mb. Range: [60mb, 140mb]
binaries_test.go:132: Binary size of 146mb was greater than max allowed size 140mb
```
> fix TestBinarySizes for envoy arm64

- tests/integration/helm/install_test.go
- tests/integration/pilot/nftables/main_test.go
- tests/integration/pilot/nftables/routing_test.go
- tools/istio-nftables/pkg/capture/run.go
- tools/istio-nftables/pkg/capture/testdata/dns-uid-gid.golden
- tools/istio-nftables/pkg/capture/testdata/inbound-ports-tproxy.golden
- tools/istio-nftables/pkg/capture/testdata/inbound-ports-wildcard-tproxy.golden
- tools/istio-nftables/pkg/capture/testdata/ip-range.golden
- tools/istio-nftables/pkg/capture/testdata/loopback-outbound-iprange.golden
- tools/istio-nftables/pkg/capture/testdata/tproxy.golden
This PR re-runs the pilot integration tests with native nftables mode enabled.
Related to: https://github.com/istio/istio/issues/47821
Co-authored-by: Yuanlin Xu <yuanlin.xu@redhat.com>
> Add integ tests for sidecar mode with nftables enabled

- tools/istio-nftables/pkg/capture/run.go
- tools/istio-nftables/pkg/capture/testdata/basic-exclude-nic.golden
- tools/istio-nftables/pkg/capture/testdata/dns-uid-gid.golden
- tools/istio-nftables/pkg/capture/testdata/drop-invalid.golden
- tools/istio-nftables/pkg/capture/testdata/empty.golden
- tools/istio-nftables/pkg/capture/testdata/host-ipv4-loopback-cidr.golden
- tools/istio-nftables/pkg/capture/testdata/inbound-ports-include.golden
- tools/istio-nftables/pkg/capture/testdata/inbound-ports-tproxy.golden
- tools/istio-nftables/pkg/capture/testdata/inbound-ports-wildcard-tproxy.golden
- tools/istio-nftables/pkg/capture/testdata/inbound-ports-wildcard.golden
- tools/istio-nftables/pkg/capture/testdata/ip-range.golden
- tools/istio-nftables/pkg/capture/testdata/ipnets-with-kube-virt-interfaces.golden
- tools/istio-nftables/pkg/capture/testdata/ipnets.golden
- tools/istio-nftables/pkg/capture/testdata/ipv6-dns-outbound-owner-groups-exclude.golden
- tools/istio-nftables/pkg/capture/testdata/ipv6-dns-outbound-owner-groups.golden
- tools/istio-nftables/pkg/capture/testdata/ipv6-dns-uid-gid.golden
- tools/istio-nftables/pkg/capture/testdata/ipv6-empty-inbound-ports.golden
- tools/istio-nftables/pkg/capture/testdata/ipv6-inbound-ports.golden
- tools/istio-nftables/pkg/capture/testdata/ipv6-ipnets.golden
- tools/istio-nftables/pkg/capture/testdata/ipv6-outbound-ports.golden
- tools/istio-nftables/pkg/capture/testdata/ipv6-uid-gid.golden
- tools/istio-nftables/pkg/capture/testdata/ipv6-virt-interfaces.golden
- tools/istio-nftables/pkg/capture/testdata/kube-virt-interfaces.golden
- tools/istio-nftables/pkg/capture/testdata/loopback-outbound-iprange.golden
- tools/istio-nftables/pkg/capture/testdata/outbound-owner-groups-exclude.golden
- tools/istio-nftables/pkg/capture/testdata/outbound-owner-groups.golden
- tools/istio-nftables/pkg/capture/testdata/outbound-ports-include.golden
- tools/istio-nftables/pkg/capture/testdata/tproxy.golden
- tools/istio-nftables/pkg/constants/constants.go
Unlike iptables, where packet counters are available by default in verbose mode, nftables requires explicit use of the counter flag in rules. This PR adds counter in the nftables rules to aid in troubleshooting, understanding traffic flow, and verifying that specific match conditions are being triggered.
Related to: https://github.com/istio/istio/issues/47821
> Add counters in the nftable rules

- tests/integration/helm/install_test.go
This PR removes the helm TestNativeNftablesInstall test because the `nft` binary isn't available in the distroless base image.
Ref: https://prow.istio.io/view/gs/istio-prow/logs/integ-distroless_istio_postsubmit/1951292367382253568
The pilot's nftables test suite (i.e., TestMain), already provides good coverage for NativeNftables. Until the nft binary is available in the distroless image, this Helm test is being removed.
> nftables: remove the helm TestNativeNftablesInstall test

- istio.deps
- tests/binary/binaries_test.go
Manual cherry-pick of #57160 with fix to binary size test to resolve unit test failures.
> [release-1.25] fix binary_test size for envoy, manual cp #57160

- samples/multicluster/gen-eastwest-gateway.sh
It currently ignores the --network parameter passed to the script and just hardcodes "network-1" which does not seem to result in the correct gatway config.
Fixing the script since it's referenced from the docs we are creating for ambient multicluster.
+cc @keithmattix @Stevenjin8 @jaellio @therealmitchconnors
> Fix gen-eastwest-gateway.sh for ambient multi-cluster

- istioctl/pkg/proxystatus/proxystatus_test.go
- istioctl/pkg/writer/pilot/status.go
- releasenotes/notes/57340.yaml
Fixed the behavior change of `istioctl proxy-status` when no proxy is present will breaks foreign tooling calling.
Fix https://github.com/istio/istio/issues/57339
Related discussions：https://github.com/istio/istio/pull/56441#discussion_r2274074541
> fix the behavior change of istio ps will breaks foreign tooling calling

- cni/pkg/iptables/iptables.go
- cni/pkg/iptables/iptables_test.go
- tools/istio-iptables/pkg/capture/run.go
- tools/istio-iptables/pkg/capture/run_linux_test.go
- tools/istio-iptables/pkg/dependencies/stub.go
When IPv6 support is disabled (`EnableIPv6=false`), iptables initialization now skips detection of the `ip6tables` binary instead of returning an error. This allows running in IPv4-only mode even when IPv6 is disabled in the kernel (e.g. `ipv6.disable=1` kernel parameter).
**Please provide a description of this PR:** Fixes https://github.com/istio/istio/issues/57199
> iptables: gracefully handle missing IPv6 support

- tests/integration/helm/install_test.go
- tests/integration/pilot/nftables/main_test.go
The nftables-slim package was recently merged into the Wolfi repo, and it has also been updated in Istio as part of PR #56917. So, we can now remove the logic that skips the test when the image is distroless.
Related to: https://github.com/istio/istio/issues/57429
> Run nftable tests even with distroless images

- istioctl/pkg/writer/ztunnel/configdump/configdump.go
- releasenotes/notes/57434.yaml
`istioctl ztunnel-config all` should print connections info (`istioctl ztunnel-config all -oyaml` was print it)
> support display connections info for ztunnel-config all

- security/pkg/server/ca/authenticate/kubeauth/kube_jwt.go
istio-csr panics when testing with a basic gRPC call(emulating istio certificate request) with incorrect ClusterID and when multi-cluster controllers are not initialized.
The fix checks whether the pointer var is initialized or not before using it.
- [X ] Multi Cluster
- [ X] Does not have any [user-facing](https://github.com/istio/istio/tree/master/releasenotes#when-to-add-release-notes) changes. This may include CLI changes, API changes, behavior changes, performance improvements, etc.
> Fixes panic due to uninitialized pointer when ClusterID is misconfigured

- docker/iptables.yaml
This PR is removing the unnecessary package `wolfi-baselayout` in the docker/iptables.yaml. 
This package is causing conflicts in Jobs:  build-base-images_release-builder_release-1.25_periodic  and build-base-images_release-builder_release-1.26_periodic
The release-1.25 branch and release-1.26 branch have no change in the docker/iptables.yaml file since last year.
The error is about a conflict when apko publish the iptables image tag with the package wolfi-baselayout.
I haven't seen any usage of this package so far. Need to wait more CI job results and verify that it's safe to remove this package in the distroless base image build.
Error log in those two jobs:
https://storage.googleapis.com/istio-prow/logs/build-base-images_release-builder_release-1.25_periodic/1960779518805282816/build-lo …
> Remove unnessary package wolfi-baselayout

- tools/build-base-images.sh
This PR is cherry-picking two commits for the `istio/tools/build-base-images.sh` file.
The two commits added a step of "apko build .." command.
After comparing the failed periodic job log in release-1.25 with the passed one in release-1.26, this difference may fix the failed job error. 
The fix of https://github.com/istio/istio/pull/57484 removed a conflict package. It looks like the `apko build` will install a non conflict package from a cache. However, it shows different behavior from release-1.25 branch with the `apko publish` only script.  
...
https://storage.googleapis.com/istio-prow/logs/build-base-images_release-builder_release-1.25_periodic/1961141910764523520/build-log.txt
https://storage.googleapis.com/istio-prow/logs/build-base-images_release-builder_release-1.26_periodic/19611 …
> [release-1.25] Fix build-base-images_release-builder_release-1.25_periodic job error

- tools/build-base-images.sh
This PR is fixing the build-base-images.sh unexpectedFiles check by ignoring the `usr/share/doc/nftables/examples/.*.nft` files. Those files were added back in the package when wolfi-dev moved the `nftables-slim` package as a subpackage in:
https://github.com/wolfi-dev/os/pull/63313
Those are small example doc files. So I updated the unexpectedFiles check list and ignore those doc files.
The `etc/apk/commit_hooks.d/ldconfig-commit.sh` has already been ignored in the check list. When the previous item ends with `\n` , it was captured in the list.
Related PR: https://github.com/istio/istio/pull/56917
> nftables-slim: ignore checking examples doc files

- go.mod
- go.sum
- pilot/pkg/config/kube/gateway/inferencepool_collection.go
- pilot/pkg/config/kube/gateway/inferencepool_test.go
- pilot/pkg/config/kube/gateway/testdata/http.yaml
- pilot/pkg/config/kube/gateway/testdata/reference-policy-inferencepool.yaml
- releasenotes/notes/57219-rc2.yaml
- tests/integration/pilot/testdata/gateway-api-inference-extension-crd.yaml
Bumps InferencePool to v1.0.0-rc.2. In this version, `inferencePool.spec.endpointPickerRef.portNumber` field has been replaced with `inferencePool.spec.endpointPickerRef.port.number`. The `inferencePool.spec.endpointPickerRef.port` field is a non-pointer and required when `inferencePool.spec.endpointPickerRef.kind` is unset or "Service". The port number `9002` is no longer inferred.
> feat(gw-inference): Bumps InferencePool to v1.0.0-rc.2

- pilot/pkg/features/pilot.go
- pilot/pkg/serviceregistry/kube/controller/pod.go
- pilot/pkg/serviceregistry/kube/controller/util.go
- pilot/pkg/serviceregistry/serviceregistry_test.go
- releasenotes/notes/pod-controller-avoid-ip-search.yaml
Backports https://github.com/istio/istio/pull/56502. Unlike that PR, this is made to be _no changes by default_; users can opt into the new behavior.
> remove finding of pods by IP (#56502)

- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
Fixes https://github.com/istio/istio/issues/56686
This accidentally removed `_` which was allowed in the old regex
> Fix regression in strict header validation

- README.md
This updates the README.md with image alternatives so the logos no longer look broken in GitHub's dark mode.
> fix: update README.md to support dark theme

- cni/pkg/nodeagent/informers_test.go
The reconcile loop will constantly retry given an error. This can affect further tests since the reconcile event counter is a global. Allow the pod to be added to the mesh and no more update events occur.
What tends to happen is that the next test
`TestInformerExistingPodAddErrorDoesNotRetryIfNotRetryable` fails with 
```
informers_test.go:1295: Metric nodeagent_reconcile_events_total/map[type:update] not matched (timeout while waiting after 35 attempts (last             │ │ error: got unexpected val 4: want 1, got 4)); 
```
All tests after will fail, and all tests pass if the PartialStatusOnRetry is skipped.
> fix TestInformerExistingPodAddErrorAnnotatesWithPartialStatusOnRetry

- tools/istio-iptables/pkg/dependencies/implementation_linux.go
Fixes https://github.com/istio/istio/issues/57678
Use of comment module when verifying there is kernal support for the current iptables version is unnecessary, and its use prevents use of istio in gVisor.
This change removes its use, given it is unnecessary for the test.
> Remove use of comment module when testing kernel support for iptables version
